/*UNIT*/
{id:149,c:"NEGO",n:"Module 1",t:"Positions et intérêts : ce que le client dit, ce qu'il veut",col:"--blue",ic:"🤝",guide:`
<h3>Ton premier rendez-vous à l'agence</h3>
<div class="gstory">Nantes, place Graslin, agence de la Banque Rivage. Tu viens d'être nommé conseiller patrimonial. À 9 h 30, Marc Delorme, 52 ans, pharmacien à Rezé, s'assoit sans enlever son manteau : « Je vais être direct. Je veux que vous baissiez vos frais sur mon assurance-vie, sinon je pars chez une banque en ligne. » Ta directrice, Sylvie Morel, t'a glissé un conseil avant d'entrer : « Ne réponds jamais à la phrase. Réponds à la raison qui est derrière. » Tout ce module tient dans cette phrase.</div>
<p>Tu retrouveras les mêmes personnes tout au long du cours : <b>Marc Delorme</b> (pharmacien, trouve tout trop cher), <b>Claire Vasseur</b> (45 ans, dirige une menuiserie de 38 salariés, 650 000 € à placer, deux enfants Léo et Inès), <b>Gérard et Martine Robin</b> (61 et 59 ans, préparent leur retraite), <b>Kevin et Laura</b> (29 ans, premier achat immobilier), <b>Sylvie Morel</b> ta directrice, et <b>Hugo</b>, le stagiaire qui confond encore tout. Retiens leurs visages : chaque notion sera accrochée à l'un d'eux.</p>
<h3>Négocier, c'est quoi exactement ?</h3>
<p>Une négociation est une discussion entre deux parties qui ont besoin l'une de l'autre et qui ne sont pas d'accord au départ. Elle n'existe que si chacun peut dire non. Si Marc n'avait aucune autre banque possible, tu n'aurais rien à négocier ; s'il n'avait aucune raison de rester, il serait déjà parti.</p>
<h3>La méthode en quatre gestes</h3>
<div class="formula">1. Poser des questions (avant de proposer quoi que ce soit)
2. Trouver les intérêts réels, pas seulement les positions
3. Aller vers l'intérêt du client (c'est lui qu'on sert)
4. S'appuyer sur des critères objectifs : marché, fiscalité, profil de risque</div>
<h3>Position ou intérêt : la différence qui change tout</h3>
<table><tr><th></th><th>Position</th><th>Intérêt</th></tr>
<tr><td>Définition</td><td>Ce que le client affirme, sa demande</td><td>Ce dont il a besoin, la raison de sa demande</td></tr>
<tr><td>Exemple Marc</td><td>« Je veux réduire les frais »</td><td>Ne pas se sentir perdant, voir son épargne progresser, être respecté</td></tr>
<tr><td>Exemple Claire</td><td>« Je veux placer sans risque »</td><td>Payer les études de Léo et Inès, dormir tranquille, ne pas fragiliser son entreprise</td></tr>
<tr><td>Comment on la trouve</td><td>Elle est dite tout de suite</td><td>Elle se découvre avec la question « pourquoi est-ce important pour vous ? »</td></tr></table>
<p>La position est une solution que le client a déjà choisie. L'intérêt est le problème qu'il cherche à résoudre. Il existe souvent plusieurs solutions à un même intérêt, alors que deux positions opposées ne se rencontrent jamais. C'est pour ça qu'on négocie sur les intérêts.</p>
<div class="gmnemo"><b>L'iceberg.</b> La position, c'est la pointe qui dépasse de l'eau : on la voit, on s'y cogne. L'intérêt, c'est les neuf dixièmes cachés dessous. Ton outil pour plonger : « <b>Pourquoi ?</b> » posé avec douceur, puis « <b>Qu'est-ce qui est important pour vous ?</b> ». Deux positions se cognent, deux intérêts se combinent.</div>
<h3>L'école de Harvard</h3>
<p>Cette approche vient de Roger Fisher et William Ury, du Harvard Negotiation Project (livre <i>Getting to Yes</i>, 1981, en français <i>Comment réussir une négociation</i>). Leur négociation « raisonnée » repose sur quatre principes : séparer les personnes du problème, se concentrer sur les intérêts et non sur les positions, imaginer des options à bénéfice mutuel, exiger des critères objectifs.</p>
<div class="gstory">L'histoire de l'orange, racontée par Fisher et Ury : deux sœurs se disputent une orange. Elles la coupent en deux, chacune repart avec sa moitié. La première presse sa moitié pour le jus et jette l'écorce ; la seconde râpe l'écorce pour un gâteau et jette la pulpe. Si elles s'étaient demandé « pourquoi la veux-tu ? », chacune aurait eu 100 % de ce qu'elle voulait. Couper en deux, c'est négocier sur les positions.</div>
<h3>Les critères objectifs : sortir du rapport de force</h3>
<p>Un critère objectif est une référence extérieure aux deux parties, que ni toi ni le client ne pouvez manipuler. En banque et en patrimoine, les trois grands critères sont :</p>
<ul><li><b>Le marché</b> : prix pratiqués ailleurs, taux du moment, rendement moyen des fonds euros (2,63 % en 2025 selon l'ACPR, net de frais de gestion, avant prélèvements sociaux).</li>
<li><b>La fiscalité</b> : ce que le client paiera réellement selon l'enveloppe (assurance-vie, PER, compte-titres).</li>
<li><b>Le profil de risque</b> : ce que le client peut et veut supporter, mesuré par un questionnaire.</li></ul>
<p>Face à « vos frais sont trop élevés », dire « non, ils sont normaux » est une opinion contre une opinion. Montrer le frais moyen du marché, le rendement net après frais et l'impact fiscal, c'est un critère objectif : on regarde ensemble la même règle.</p>
<h3>Le mot-clé de l'évaluation : la valeur</h3>
<p>Ton rôle n'est pas de défendre un prix mais d'<b>apporter de la valeur ajoutée</b> au client : une solution adaptée à ses intérêts, qu'il n'aurait pas trouvée seul. Les deux positions les plus fréquentes en patrimoine sont <b>Sécurité</b> (« je ne veux pas perdre ») et <b>Rendement</b> (« je veux que ça rapporte »). Derrière chacune, il y a un intérêt à découvrir.</p>
<div class="gtrap">Les notes disent « trouver l'intérêt réel du client et pas seulement les positions ». Le mot important est <b>seulement</b> : la position n'est pas à jeter. Elle te dit où le client en est et ce qu'il a déjà en tête. On la respecte, on la reformule, puis on creuse ce qu'elle cache.</div>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Distinguer une position d'un intérêt dans une phrase de client</li><li>Poser la question qui fait passer de l'un à l'autre</li><li>Citer les trois critères objectifs et en donner un exemple chiffré</li><li>Citer les quatre principes de Harvard</li><li>Expliquer pourquoi on ne commence jamais par répondre à la position</li></ul>`},
/*EXOS*/
{i:"n149_01",u:149,t:"sort",d:.25,nw:"Position ou intérêt",q:"Classe chaque phrase de client : position ou intérêt ?",bins:["Position","Intérêt"],it:[["« Je veux réduire vos frais de 1 %. »",0],["« J'ai peur de voir mon épargne fondre avant ma retraite. »",1],["« Je veux un placement sans aucun risque. »",0],["« Je veux payer les études de mes enfants sans m'endetter. »",1],["« Je veux le même taux que mon beau-frère. »",0],["« J'ai besoin de me sentir respecté par ma banque. »",1]],w:"La position est la solution que le client a déjà choisie ; l'intérêt est le besoin qui la justifie. Pense à l'iceberg : la position dépasse, l'intérêt est dessous."},
{i:"n149_02",u:149,t:"story",d:.3,q:"Quelle est ta meilleure première réponse à Marc ?",sc:[{who:"Marc Delorme",txt:"Je vais être direct. Vous baissez vos frais sur mon assurance-vie ou je pars dans une banque en ligne."},{who:"Toi",me:true,txt:"..."}],o:["« Je vous entends. Avant de parler chiffres, qu'est-ce qui vous fait dire que ces frais sont trop lourds ? »","« Nos frais sont dans la moyenne du marché, vous ne trouverez pas vraiment moins cher ailleurs. »","« Je peux vous faire un geste de 0,2 % dès aujourd'hui si vous restez chez nous au moins cette année. »","« Les banques en ligne ne proposent pas du tout le même accompagnement personnalisé que le nôtre. »"],a:0,w:"On ne répond pas à la position (baisser les frais), on cherche l'intérêt qui la motive. Céder tout de suite ou se défendre ferme la porte à la vraie discussion."},
{i:"n149_03",u:149,t:"mcq",d:.25,q:"Dans la négociation raisonnée de Harvard, sur quoi faut-il se concentrer ?",o:["Sur les intérêts","Sur les positions","Sur le rapport de force","Sur la première offre"],a:0,w:"Fisher et Ury : séparer les personnes du problème, se concentrer sur les intérêts, inventer des options à bénéfice mutuel, utiliser des critères objectifs."},
{i:"n149_04",u:149,t:"order",d:.3,nw:"La méthode en quatre gestes",q:"Remets dans l'ordre la méthode de négociation du conseiller.",it:["Poser des questions","Trouver les intérêts réels derrière les positions","Aller vers l'intérêt du client","S'appuyer sur des critères objectifs pour conclure"],w:"Questions d'abord, puis intérêts, puis solution tournée vers le client, validée par des critères que personne ne peut contester."},
{i:"n149_05",u:149,t:"multi",d:.35,nw:"Les critères objectifs",q:"Lesquels sont des critères objectifs pour discuter d'un placement ?",o:["Le rendement moyen des fonds euros publié par l'ACPR","Le taux d'imposition applicable aux gains du client","Le résultat du questionnaire de profil de risque","L'objectif commercial de l'agence ce trimestre","Ce que le conseiller trouve raisonnable"],a:[0,1,2],w:"Marché, fiscalité, profil de risque : trois références extérieures aux deux parties. L'objectif de l'agence et l'avis du conseiller sont des positions, pas des critères."},
{i:"n149_06",u:149,t:"tf",d:.2,q:"Deux positions opposées peuvent cacher des intérêts compatibles.",a:true,w:"C'est l'histoire de l'orange : l'une veut le jus, l'autre l'écorce. Les positions (« je veux l'orange ») s'opposent, les intérêts se complètent."},
{i:"n149_07",u:149,t:"fill",d:.25,q:"Ce que le client affirme s'appelle sa ___ ; ce dont il a besoin s'appelle son intérêt.",o:["position","objection","exigence","motivation"],a:0,w:"Position = ce qu'il dit vouloir. Intérêt = pourquoi il le veut. La question « pourquoi est-ce important pour vous ? » fait passer de l'un à l'autre."},
{i:"n149_08",u:149,t:"story",d:.35,q:"Que cache probablement la position de Claire ?",ctx:"Claire Vasseur, 45 ans, dirige une menuiserie de 38 salariés à Carquefou. Elle vient de recevoir 650 000 € de la vente d'un entrepôt.",sc:[{who:"Claire Vasseur",txt:"Je veux placer cet argent sans aucun risque. Point."},{who:"Toi",me:true,txt:"Qu'est-ce qui rend la sécurité si importante pour vous en ce moment ?"},{who:"Claire Vasseur",txt:"Mon entreprise a failli couler en 2020. Et Léo entre en prépa l'an prochain."}],o:["La peur de revivre 2020 et le besoin de financer les études de Léo","Une envie de rendement élevé qu'elle n'ose pas avouer à son banquier","Une méfiance de principe envers tout ce que propose la Banque Rivage","Un manque total de connaissances financières, qu'il faut combler"],a:0,w:"« Sans risque » est une position. Les intérêts apparaissent quand elle explique pourquoi : sécurité après un traumatisme, et un besoin de liquidités pour les études."},
{i:"n149_09",u:149,t:"match",d:.3,q:"Associe chaque position de client à l'intérêt le plus probable.",p:[["« Je veux baisser les frais »","Ne pas se sentir perdant"],["« Je veux du sans risque »","Protéger un projet proche"],["« Je veux 8 % par an »","Compléter sa retraite"],["« Je veux tout retirer »","Retrouver de la liquidité"]],w:"Chaque position est une solution. Ton travail : remonter au besoin. Une même position peut cacher d'autres intérêts, d'où les questions."},
{i:"n149_10",u:149,t:"tiles",d:.3,q:"Reconstitue le conseil de Sylvie Morel.",a:["Ne","réponds","pas","à","la","phrase","réponds","à","la","raison"],dd:["prix","toujours","position"],w:"La phrase est la position, la raison est l'intérêt. Répondre à la phrase, c'est se battre sur la pointe de l'iceberg."},
{i:"n149_11",u:149,t:"story",d:.4,q:"Quelle question fait le mieux passer de la position à l'intérêt ?",sc:[{who:"Gérard Robin",txt:"On veut un placement qui rapporte au moins 5 %, sinon ça ne sert à rien."},{who:"Martine Robin",txt:"Gérard, ne recommence pas..."}],o:["« Qu'est-ce que ces 5 % vous permettraient de faire concrètement ? »","« Vous savez qu'aucun placement sûr ne rapporte 5 % aujourd'hui ? »","« Vous accepteriez de prendre plus de risque pour obtenir ces 5 % ? »","« Préférez-vous un fonds euros ou une unité de compte dynamique ? »"],a:0,w:"La question ouverte sur l'usage fait apparaître l'intérêt (un revenu de retraite, un projet). Les autres questions restent au niveau de la position ou la contredisent."},
{i:"n149_12",u:149,t:"mcq",d:.3,q:"Pourquoi les critères objectifs apaisent-ils une négociation ?",o:["Ils remplacent un duel d'opinions par une règle extérieure","Ils prouvent que le conseiller a toujours raison sur le prix","Ils évitent de poser des questions au client","Ils permettent d'imposer le tarif de la banque"],a:0,w:"Un critère objectif (marché, fiscalité, profil de risque) ne dépend ni de toi ni du client. On regarde ensemble la même référence au lieu de s'affronter."},
{i:"n149_13",u:149,t:"slider",d:.3,q:"Selon l'ACPR, quel a été le rendement moyen des fonds euros des contrats individuels au titre de 2025 (en %) ?",min:0,max:6,step:.01,a:2.63,tol:.15,pre:"",un:" %",w:"2,63 % en 2025, comme en 2024 : net des frais de gestion, avant prélèvements sociaux. C'est un critère de marché pour juger un fonds euros."},
{i:"n149_14",u:149,t:"tf",d:.3,q:"Si un client annonce clairement sa position, il est inutile de lui poser des questions.",a:false,w:"Une position claire n'est qu'une solution parmi d'autres. Sans questions, tu ne sais pas quel besoin tu dois servir et tu risques de proposer à côté."},
{i:"n149_15",u:149,t:"story",d:.45,q:"Quelle réponse s'appuie sur un critère objectif ?",sc:[{who:"Marc Delorme",txt:"Vos 0,85 % de frais de gestion, c'est du vol."},{who:"Toi",me:true,txt:"..."}],o:["« Regardons ensemble le rendement net de frais de votre contrat face à la moyenne publiée par l'ACPR. »","« Je vous assure que nos frais sont justes, nous avons une vraie expertise et un service premium. »","« Si nos frais vous choquent, c'est que vous n'avez pas lu les conditions générales attentivement. »","« Tous nos clients paient ces mêmes frais et personne ne s'en est jamais plaint auprès de nous. »"],a:0,w:"Le rendement net de frais comparé à une moyenne publiée est une référence que Marc peut vérifier. Les autres réponses sont des opinions ou des reproches."},
{i:"n149_16",u:149,t:"multi",d:.4,nw:"Les quatre principes de Harvard",q:"Coche les principes de la négociation raisonnée de Fisher et Ury.",o:["Séparer les personnes du problème","Se concentrer sur les intérêts","Inventer des options à bénéfice mutuel","Exiger des critères objectifs","Ancrer très haut pour impressionner"],a:[0,1,2,3],w:"Quatre principes, dans Getting to Yes (1981). L'ancrage agressif relève du marchandage de positions, justement ce qu'ils déconseillent."},
{i:"n149_17",u:149,t:"fill",d:.35,q:"Pour trouver l'intérêt, la question reine est : « Qu'est-ce qui est ___ pour vous ? »",o:["important","possible","négociable","urgent"],a:0,w:"« Qu'est-ce qui est important pour vous ? » est ouverte, bienveillante, et fait parler le client de ses priorités, pas de sa solution."},
{i:"n149_18",u:149,t:"story",d:.4,q:"Qu'est-ce que tu corriges dans la fiche d'Hugo ?",sc:[{who:"Hugo",txt:"J'ai noté pour M. Delorme : intérêt = baisser les frais de 0,3 %. Position = pas identifiée."},{who:"Toi",me:true,txt:"Tu as inversé deux choses."}],o:["Baisser les frais est sa position ; son intérêt reste à découvrir en le questionnant","Il fallait écrire le chiffre de 0,3 % en objectif de la banque et non du client","Baisser les frais est bien l'intérêt, mais il faut préciser le type de frais concernés","La position de Marc, c'est son envie de rester ; l'intérêt, c'est de partir ailleurs"],a:0,w:"« Baisser les frais de 0,3 % » est la solution qu'il réclame : sa position. L'intérêt (ne pas se sentir perdant, rendement net, respect) se découvre par les questions."},
{i:"n149_19",u:149,t:"mcq",d:.35,q:"Dans l'histoire de l'orange, pourquoi le partage en deux est-il un échec ?",o:["Chacune avait besoin d'une partie différente du fruit","Le partage en deux n'était pas parfaitement équitable","Les deux sœurs voulaient exactement la même chose","Il aurait fallu tirer au sort celle qui la garde"],a:0,w:"L'une voulait le jus, l'autre l'écorce. En se demandant « pourquoi ? », chacune aurait eu 100 %. Couper en deux, c'est négocier sur les positions."},
{i:"n149_20",u:149,t:"num",d:.4,q:"Marc a 120 000 € sur son assurance-vie. Il réclame une baisse des frais de gestion de 0,85 % à 0,60 % par an. Combien économiserait-il la première année, en euros ?",a:300,tol:1,un:" €",h:"Écart de taux multiplié par l'encours",w:"0,25 % de 120 000 € = 300 €. Chiffrer la position permet de voir ce qui est vraiment en jeu et de chercher d'autres façons de créer 300 € de valeur."},
{i:"n149_21",u:149,t:"story",d:.45,q:"Que réponds-tu à Kevin ?",ctx:"Kevin, 29 ans, infirmier, veut acheter un deux-pièces à Rezé avec sa compagne Laura.",sc:[{who:"Kevin",txt:"Je veux absolument un prêt sur 25 ans, pas un an de moins."},{who:"Toi",me:true,txt:"Qu'est-ce qui vous tient à cœur dans cette durée ?"},{who:"Kevin",txt:"Laura veut arrêter de travailler deux ans quand on aura un bébé. Il nous faut une mensualité basse."}],o:["« Alors le vrai sujet est une mensualité supportable sur un seul salaire : regardons plusieurs montages. »","« Très bien, je vous monte le dossier sur 25 ans comme vous le demandez, c'est la solution la plus simple. »","« Sur 25 ans vous paierez beaucoup plus d'intérêts, je vous conseille fortement plutôt 20 ans. »","« Si Laura arrête de travailler, votre dossier sera refusé par la banque, il faut revoir le projet. »"],a:0,w:"La position (25 ans) cache un intérêt (mensualité compatible avec un salaire unique temporaire). D'autres options peuvent le servir : modulation, différé, prêt à paliers."},
{i:"n149_22",u:149,t:"sort",d:.4,q:"Classe chaque argument : critère objectif ou opinion ?",bins:["Critère objectif","Opinion"],it:[["Le barème fiscal applicable aux rachats",0],["« Notre banque est la meilleure de Nantes »",1],["Le score du questionnaire de risque",0],["Le taux moyen pratiqué sur le marché ce mois-ci",0],["« Ce fonds est vraiment excellent »",1],["« Vous me faites confiance, non ? »",1]],w:"Un critère objectif se vérifie et s'impose aux deux parties : marché, fiscalité, profil de risque. Tout le reste est une opinion, contestable par une autre opinion."},
{i:"n149_23",u:149,t:"tf",d:.35,q:"Séparer les personnes du problème signifie qu'on peut être dur sur le problème et doux avec la personne.",a:true,w:"C'est la formule de Fisher et Ury : « doux avec les personnes, dur sur le problème ». On respecte Marc tout en tenant une analyse chiffrée des frais."},
{i:"n149_24",u:149,t:"mcq",d:.4,q:"Quel est le mot-clé attendu dans toute réponse d'évaluation sur la négociation ?",o:["La valeur apportée au client","Le prix le plus bas possible","La marge de la banque","La rapidité de signature"],a:0,w:"L'évaluation attend la notion de valeur : apporter de la plus-value, de la valeur ajoutée au client, en comprenant ses intérêts et en proposant une solution adaptée."},
{i:"n149_25",u:149,t:"story",d:.5,q:"Quelle phrase de conclusion est la plus solide ?",ctx:"Après vingt minutes, Marc explique qu'il veut surtout voir son épargne progresser pour aider sa fille à acheter un logement dans cinq ans.",sc:[{who:"Marc Delorme",txt:"Bon. Alors, vous me proposez quoi ?"}],o:["« Voici deux options chiffrées pour votre objectif à cinq ans, avec le rendement net après frais et impôts. »","« Je vous baisse les frais de 0,25 %, c'est vraiment le maximum que je peux faire pour vous aujourd'hui. »","« On garde le contrat actuel, il est très bien, et on en reparle dans cinq ans pour votre fille. »","« Je vous propose notre fonds star, il a fait 12 % l'an dernier, vous ne serez vraiment pas déçu. »"],a:0,w:"La bonne réponse sert l'intérêt (aider sa fille dans cinq ans) et s'appuie sur des critères objectifs (rendement net, fiscalité). La remise sèche répond à la position ; le fonds star ignore le profil de risque."},
{i:"n149_26",u:149,t:"order",d:.4,q:"Remets dans l'ordre le chemin qui mène de la position à l'intérêt.",it:["Écouter la position sans la contredire","La reformuler avec les mots du client","Demander pourquoi elle est importante","Noter l'intérêt qui apparaît et le faire confirmer"],w:"On respecte d'abord la position (écoute, reformulation), puis on creuse (pourquoi ?), puis on vérifie qu'on a bien compris. Jamais de solution avant cette étape."},
{i:"n149_27",u:149,t:"tiles",d:.35,q:"Reconstitue la règle d'or de ce module.",a:["Deux","positions","se","cognent","deux","intérêts","se","combinent"],dd:["prix","toujours","refusent"],w:"Les positions sont figées et s'opposent. Les intérêts sont souvent différents et compatibles : c'est là qu'on crée de la valeur."},
{i:"n149_28",u:149,t:"match",d:.4,q:"Associe chaque critère objectif à son exemple concret.",p:[["Marché","Taux moyen des crédits ce mois-ci"],["Fiscalité","Imposition des gains après 8 ans"],["Profil de risque","Perte maximale acceptée : 10 %"],["Frais","Coût total annuel du contrat"]],w:"Marché, fiscalité, profil de risque (et le coût réel qui en découle) : ce sont les juges de paix d'une négociation patrimoniale."},
{i:"n149_29",u:149,t:"story",d:.5,q:"Quel intérêt commun peux-tu mettre en avant ?",sc:[{who:"Sylvie Morel",txt:"Delorme menace de partir. Tu as une idée pour qu'on garde le client sans brader nos frais ?"},{who:"Toi",me:true,txt:"Oui, j'ai trouvé ce qu'on veut tous les deux."}],o:["Une relation durable où son épargne progresse et où la banque garde un client rentable","Une baisse des frais pour lui, compensée par une hausse des frais sur ses autres contrats","Un geste commercial cette année puis un retour aux frais normaux l'an prochain","Un contrat sans frais pour lui, compensé par les frais des autres clients"],a:0,w:"L'intérêt commun est la relation durable : Marc veut voir son épargne grandir, la banque veut le garder. On cherche des solutions qui servent les deux, pas un transfert de perte."},
{i:"n149_30",u:149,t:"fill",d:.4,q:"Fisher et Ury conseillent d'être doux avec les personnes et dur sur le ___.",o:["problème","prix","rendement","contrat"],a:0,w:"Séparer les personnes du problème : on garde la relation chaleureuse, on reste exigeant sur l'analyse et les critères."},
{i:"n149_31",u:149,t:"multi",d:.45,q:"Martine Robin dit : « Je veux de la sécurité. » Quelles questions l'aident à exprimer son intérêt ?",o:["« Que voulez-vous protéger en priorité ? »","« Qu'est-ce qui vous inquiète le plus ? »","« Que ferait cet argent dans dix ans, idéalement ? »","« Vous voulez un fonds euros, c'est ça ? »","« Vous êtes sûre de ne pas vouloir de rendement ? »"],a:[0,1,2],w:"Les trois premières sont ouvertes et font parler de besoins. Les deux dernières enferment Martine dans une solution ou contestent sa position."},
{i:"n149_32",u:149,t:"tf",d:.4,q:"Répondre « nos frais sont dans la moyenne » à un client mécontent est une réponse fondée sur un critère objectif.",a:false,w:"Dit comme ça, c'est une affirmation invérifiable. Elle devient un critère objectif quand tu montres la source (moyenne publiée, comparaison chiffrée) et que le client peut la vérifier."}
