/*UNIT*/
{id:150,c:"NEGO",n:"Module 2",t:"MESORE, BATNA, ZOPA : savoir jusqu'où aller",col:"--blue",ic:"🧭",guide:`
<h3>Le jour où Marc a sorti son téléphone</h3>
<div class="gstory">Deuxième rendez-vous avec Marc Delorme. Il pose son téléphone sur ton bureau, écran allumé : une simulation de NeoBanque, frais de gestion 0,50 %. « Voilà ma porte de sortie. » Tu souris, parce que tu as préparé ce moment : tu sais que NeoBanque n'a ni conseiller dédié, ni gestion de sa succession, ni prêt professionnel pour sa pharmacie. Sa porte de sortie existe, mais elle a un prix. Celui qui connaît le mieux les portes de sortie des deux côtés gagne la négociation.</div>
<h3>MESORE et BATNA : une seule et même idée</h3>
<p>La <b>MESORE</b> (MEilleure SOlution de REchange) est ce que tu feras si la négociation échoue. En anglais, on dit <b>BATNA</b> : <i>Best Alternative To a Negotiated Agreement</i>. Le terme vient de Fisher et Ury (Harvard, 1981). C'est ta vraie force : plus ta MESORE est bonne, moins tu as besoin de l'accord, et plus tu peux dire non.</p>
<div class="gtrap">Les notes écrivent « 2 techniques : MESORE, BATMA ». Deux erreurs. <b>BATMA</b> n'existe pas : c'est <b>BATNA</b>. Et ce ne sont pas deux techniques mais <b>le même concept</b> dans deux langues. La phrase juste des notes est la suivante : la MESORE (ou BATNA) est la meilleure solution si aucun accord n'est trouvé.</div>
<h3>Les trois repères de toute négociation</h3>
<table><tr><th>Repère</th><th>Définition</th><th>Exemple de Marc (frais annuels)</th></tr>
<tr><td><b>Point cible</b></td><td>Résultat ambitieux mais crédible que tu vises</td><td>Pour la banque : garder 0,75 %</td></tr>
<tr><td><b>Point de réserve</b></td><td>Limite au-delà de laquelle tu ne signes pas</td><td>Pour la banque : pas sous 0,60 %</td></tr>
<tr><td><b>MESORE / BATNA</b></td><td>Ce que tu fais si c'est non</td><td>Pour Marc : NeoBanque à 0,50 % sans conseil</td></tr></table>
<p>Le point de réserve se <b>calcule à partir de la MESORE</b>. Marc sait qu'à 0,50 % chez NeoBanque, il perd son conseiller et le suivi de sa pharmacie. Il estime que ce service vaut 0,20 %. Son point de réserve est donc 0,70 % : au-dessus, il part, et en dessous, il reste.</p>
<h3>La ZOPA : la zone où l'accord est possible</h3>
<p>La <b>ZOPA</b> (<i>Zone Of Possible Agreement</i>, zone d'accord possible) est l'espace entre les deux points de réserve. Elle n'existe que s'ils se chevauchent.</p>
<div class="formula">Banque : ne descend pas sous 0,60 %  (réserve banque)
Marc   : ne paie pas plus de 0,70 %  (réserve Marc)
ZOPA   = de 0,60 % à 0,70 %   (largeur 0,10 point)
Si la banque exigeait 0,75 % minimum : pas de ZOPA, pas d'accord.</div>
<div class="gmnemo"><b>C.R.M.</b> comme « Cap, Rempart, Muraille de secours ». Le <b>Cap</b> est ton point cible (là où tu navigues), le <b>Rempart</b> ton point de réserve (tu ne le franchis jamais), la <b>Muraille de secours</b> ta MESORE (là où tu te réfugies si tout échoue). Et la ZOPA, c'est la <b>plage</b> où les deux bateaux peuvent accoster ensemble.</div>
<h3>Les règles d'or</h3>
<ul><li><b>Fixe ton point de réserve avant d'entrer</b>, à froid. En pleine discussion, on le déplace sous la pression.</li>
<li><b>Ne révèle jamais ton point de réserve</b> : l'autre s'y installerait immédiatement.</li>
<li><b>Améliore ta MESORE avant de négocier</b> : une deuxième offre de prêt, un autre acheteur, un autre employeur. C'est le levier le plus puissant et le plus négligé.</li>
<li><b>Estime la MESORE de l'autre</b> : que fera Marc s'il part ? Moins elle est bonne, plus tu as de marge.</li>
<li><b>Ouvre près de ton point cible</b> : la première offre crée un <b>ancrage</b>, un chiffre de référence autour duquel la discussion va tourner (effet étudié par Tversky et Kahneman, 1974).</li></ul>
<div class="gstory">Claire Vasseur a vendu son entrepôt de Carquefou. Son point cible : 700 000 €. Son point de réserve : 620 000 €, parce qu'un promoteur lui avait promis 610 000 € par écrit (sa MESORE) et qu'elle voulait un peu mieux. L'acheteur, lui, ne pouvait pas dépasser 660 000 €. ZOPA : de 620 000 à 660 000 €. Elle a signé à 650 000 €, la somme qu'elle vient placer chez toi.</div>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Définir MESORE, BATNA, point cible, point de réserve, ZOPA</li><li>Dire que MESORE et BATNA sont le même concept (et que « BATMA » est une coquille)</li><li>Calculer une ZOPA et dire si elle existe</li><li>Déduire un point de réserve d'une MESORE</li><li>Expliquer pourquoi on améliore sa MESORE avant de négocier</li></ul>`},
/*EXOS*/
{i:"n150_01",u:150,t:"match",d:.25,nw:"Les repères de la négociation",q:"Associe chaque terme à sa définition.",p:[["MESORE","Ce que je fais si aucun accord n'est trouvé"],["Point cible","Résultat ambitieux mais crédible"],["Point de réserve","Limite au-delà de laquelle je ne signe pas"],["ZOPA","Zone où les deux réserves se chevauchent"]],w:"Cap (cible), Rempart (réserve), Muraille de secours (MESORE), et la plage où les bateaux accostent (ZOPA)."},
{i:"n150_02",u:150,t:"story",d:.3,q:"Que réponds-tu à Hugo ?",sc:[{who:"Hugo",txt:"Dans mes notes il y a deux techniques : la MESORE et la BATMA. On les utilise dans quel ordre ?"},{who:"Toi",me:true,txt:"..."}],o:["« C'est une seule notion : MESORE en français, BATNA en anglais. »","« D'abord la MESORE pour préparer, ensuite la BATMA pour conclure. »","« La BATMA sert au client et la MESORE sert au conseiller bancaire. »","« La MESORE fixe le prix plancher, la BATMA fixe le prix plafond. »"],a:0,w:"BATMA est une coquille pour BATNA (Best Alternative To a Negotiated Agreement). MESORE (Meilleure Solution de Rechange) en est la traduction : un seul concept."},
{i:"n150_03",u:150,t:"num",d:.35,q:"La banque ne descend pas sous 0,60 % de frais. Marc part au-delà de 0,70 %. Quelle est la largeur de la ZOPA, en points de pourcentage ?",a:.1,tol:.001,un:" point",h:"Écart entre les deux points de réserve",w:"ZOPA de 0,60 % à 0,70 % : 0,10 point. Tout accord dans cette zone vaut mieux, pour chacun, que sa MESORE."},
{i:"n150_04",u:150,t:"tf",d:.25,q:"Plus ta MESORE est bonne, plus tu es fort dans la négociation.",a:true,w:"Une bonne alternative te rend capable de dire non. C'est ta vraie source de pouvoir, bien plus que l'éloquence."},
{i:"n150_05",u:150,t:"mcq",d:.3,q:"Que signifie l'acronyme BATNA ?",o:["Best Alternative To a Negotiated Agreement","Bank Agreement To Negotiate Assets","Best Agreement That No one Accepts","Basic Approach To Negotiation Analysis"],a:0,w:"La meilleure alternative à un accord négocié. En français : MESORE, meilleure solution de rechange. Concept de Fisher et Ury."},
{i:"n150_06",u:150,t:"slider",d:.35,q:"Claire a une promesse écrite à 610 000 € (sa MESORE). L'acheteur ne peut pas dépasser 660 000 €. Claire fixe sa réserve à 620 000 €. Quel est le plus haut prix possible dans la ZOPA, en milliers d'euros ?",min:600,max:720,step:5,a:660,tol:0,pre:"",un:" k€",w:"La ZOPA va de la réserve du vendeur (620 k€) à la réserve de l'acheteur (660 k€). Au-delà de 660 k€, l'acheteur préfère renoncer."},
{i:"n150_07",u:150,t:"story",d:.35,q:"Quelle est la faute de Hugo ?",sc:[{who:"Hugo",txt:"J'ai dit à Kevin que je ne pouvais pas descendre sous 3,20 % de taux, pour être transparent."},{who:"Kevin",txt:"Parfait, alors signons à 3,20 % tout de suite."}],o:["Il a révélé son point de réserve, et le client s'y est installé","Il aurait dû annoncer un taux plus élevé pour garder de la marge","Il a oublié de préciser le TAEG et le coût de l'assurance","Il aurait dû demander l'accord de sa directrice avant"],a:0,w:"Un point de réserve se garde pour soi. Annoncé, il devient le prix : l'autre n'a plus aucune raison d'accepter mieux pour toi."},
{i:"n150_08",u:150,t:"fill",d:.3,q:"Le point de réserve se déduit de la ___ : on ne signe pas un accord moins bon que ce qu'on obtiendrait ailleurs.",o:["MESORE","ZOPA","cible","première offre"],a:0,w:"La MESORE est l'étalon. Si NeoBanque plus la perte de service équivaut pour Marc à 0,70 %, il ne paiera jamais plus de 0,70 % ici."},
{i:"n150_09",u:150,t:"multi",d:.4,q:"Kevin veut négocier le taux de son prêt. Quelles actions améliorent sa MESORE ?",o:["Obtenir une offre écrite d'une autre banque","Passer par un courtier qui consulte plusieurs banques","Faire une simulation chez une banque en ligne","Dire qu'il adore votre agence","Annoncer qu'il est pressé de signer"],a:[0,1,2],w:"Une MESORE s'améliore avec de vraies alternatives. Montrer son attachement ou son urgence l'affaiblit au contraire."},
{i:"n150_10",u:150,t:"tf",d:.3,q:"Il existe toujours une ZOPA entre deux parties qui se parlent.",a:false,w:"La ZOPA n'existe que si les points de réserve se chevauchent. Si la banque exige 0,75 % et que Marc part au-delà de 0,70 %, il n'y a pas de zone d'accord : partir est rationnel."},
{i:"n150_11",u:150,t:"story",d:.4,q:"Que réponds-tu à Marc ?",sc:[{who:"Marc Delorme",txt:"NeoBanque me prend 0,50 %. Vous êtes à 0,85 %. Alignez-vous ou je signe chez eux ce soir."},{who:"Toi",me:true,txt:"..."}],o:["« Comparons ce que chaque offre vous apporte vraiment, services compris, avant de décider. »","« Nous ne pouvons pas nous aligner sur une banque en ligne, notre modèle est complètement différent. »","« D'accord, on s'aligne à 0,50 % pour vous garder, mais n'en parlez à personne à la pharmacie. »","« Signez chez eux, vous reviendrez vers nous dès que vous aurez besoin d'un vrai conseiller. »"],a:0,w:"Tu testes la MESORE de Marc : NeoBanque à 0,50 % sans conseil ni suivi professionnel vaut moins qu'il ne le croit. S'aligner tout de suite, c'est céder sans savoir où est sa réserve."},
{i:"n150_12",u:150,t:"order",d:.35,q:"Remets dans l'ordre la préparation des chiffres avant un rendez-vous.",it:["Identifier ma MESORE","En déduire mon point de réserve","Fixer un point cible ambitieux mais crédible","Estimer la MESORE et la réserve de l'autre","Évaluer la ZOPA probable"],w:"On part de ce qu'on fera en cas d'échec, on en tire sa limite, on vise haut mais crédible, puis on se met à la place de l'autre pour estimer la zone d'accord."},
{i:"n150_13",u:150,t:"mcq",d:.35,q:"Quel est l'effet d'ancrage ?",o:["La première offre sert de référence et attire la suite vers elle","Le client reste fidèle à sa toute première banque par simple habitude","Le conseiller s'attache aux clients les plus anciens","Le prix final est toujours la moyenne des deux offres"],a:0,w:"Le premier chiffre annoncé sert de repère mental. D'où la règle : ouvrir près de son point cible, avec une justification."},
{i:"n150_14",u:150,t:"sort",d:.4,q:"Classe chaque élément dans le bon repère, pour Marc.",bins:["MESORE","Point de réserve","Point cible"],it:[["Partir chez NeoBanque à 0,50 %",0],["Ne pas payer plus de 0,70 %",1],["Obtenir 0,60 % et un bilan retraite offert",2],["Confier son épargne à un courtier en ligne",0],["Au-delà de 0,70 %, il signe ailleurs",1]],w:"La MESORE est une action (partir), la réserve est une limite (0,70 %), la cible est l'objectif ambitieux (0,60 % plus un service)."},
{i:"n150_15",u:150,t:"story",d:.45,q:"Quelle est la bonne décision pour la banque ?",ctx:"Sylvie Morel refuse de descendre sous 0,75 % de frais sur les contrats de plus de 100 000 €. Marc a fait savoir qu'il partait au-delà de 0,70 %.",sc:[{who:"Sylvie Morel",txt:"On fait quoi avec Delorme ?"}],o:["Il n'y a pas de ZOPA sur les frais : il faut créer de la valeur ailleurs ou accepter son départ","On descend à 0,72 %, il acceptera forcément un petit effort sur les frais s'il voit notre bonne volonté","On lui dit qu'il n'aura pas mieux ailleurs, c'est la meilleure façon de tester sa détermination","On attend qu'il revienne de lui-même, les clients mécontents reviennent souvent au bout d'un an"],a:0,w:"0,75 % contre 0,70 % : les réserves ne se chevauchent pas. Soit on élargit le gâteau (un service qui vaut plus que 0,05 % pour lui), soit on accepte que sa MESORE l'emporte."},
{i:"n150_16",u:150,t:"tiles",d:.35,q:"Reconstitue la définition du point de réserve.",a:["La","limite","au-delà","de","laquelle","on","ne","signe","pas"],dd:["cible","toujours","rêve"],w:"Au-delà de ton point de réserve, ta MESORE vaut mieux que l'accord : tu dois partir."},
{i:"n150_17",u:150,t:"num",d:.45,q:"Kevin a une offre écrite d'une autre banque à 3,40 %. Changer de banque lui coûterait des frais de dossier qu'il estime équivalents à 0,10 point de taux. Quel taux maximum peut-il accepter chez vous, en % ?",a:3.5,tol:.001,un:" %",h:"MESORE plus coût de changement",w:"Rester chez vous lui évite 0,10 point de frais : son point de réserve est 3,40 + 0,10 = 3,50 %. Au-dessus, l'autre banque est plus intéressante."},
{i:"n150_18",u:150,t:"tf",d:.35,q:"Le bon moment pour fixer son point de réserve est pendant la discussion, quand on voit comment l'autre réagit.",a:false,w:"On le fixe à froid, avant. En pleine discussion, la pression, la fatigue et l'envie de conclure le font glisser."},
{i:"n150_19",u:150,t:"story",d:.45,q:"Quelle première offre fais-tu ?",ctx:"Pour garder Marc, la banque peut descendre jusqu'à 0,60 %. Ton point cible est 0,75 %. Marc a évoqué 0,50 %.",sc:[{who:"Marc Delorme",txt:"Alors, c'est quoi votre meilleur prix ?"}],o:["« 0,75 %, avec un bilan patrimonial et un suivi de votre pharmacie inclus. »","« Je peux descendre à 0,60 %, c'est vraiment le plancher que ma directrice m'autorise. »","« On peut couper la poire en deux entre vos 0,50 % et nos 0,85 %, soit 0,675 %. »","« Dites-moi votre prix à vous, et je verrai ce que je peux faire pour m'en rapprocher. »"],a:0,w:"On ouvre près du point cible, avec une justification de valeur : c'est un ancrage crédible. Annoncer le plancher ou couper la poire en deux abandonne toute la marge d'un coup."},
{i:"n150_20",u:150,t:"mcq",d:.4,q:"Qui a popularisé la notion de BATNA ?",o:["Roger Fisher et William Ury","Neil Rackham et Huthwaite","Daniel Kahneman et Amos Tversky","Dale Carnegie et Napoleon Hill"],a:0,w:"Fisher et Ury, Harvard Negotiation Project, Getting to Yes (1981). Rackham est l'auteur de SPIN, Kahneman a étudié les biais comme l'ancrage."},
{i:"n150_21",u:150,t:"multi",d:.45,q:"Marc menace de partir. Quelles informations t'aident à évaluer sa MESORE réelle ?",o:["Les services que NeoBanque ne propose pas","Le coût et la durée d'un transfert de contrat","Son besoin d'un prêt professionnel pour la pharmacie","Sa couleur préférée","Le nombre de clients de ton agence"],a:[0,1,2],w:"La MESORE de l'autre se mesure à ce qu'il perdrait vraiment en partant : services, coûts de transfert, besoins futurs. Plus elle est faible, plus tu as de marge."},
{i:"n150_22",u:150,t:"fill",d:.4,q:"La ZOPA est la zone située entre les deux points de ___.",o:["réserve","cible","rupture","vente"],a:0,w:"Entre la réserve de l'un et celle de l'autre. Hors de cette zone, au moins une partie préfère sa MESORE."},
{i:"n150_23",u:150,t:"story",d:.5,q:"Comment Claire aurait-elle dû préparer la vente de son entrepôt ?",sc:[{who:"Claire Vasseur",txt:"Honnêtement, j'y suis allée au feeling. J'avais juste en tête que 700 000, ce serait bien."},{who:"Toi",me:true,txt:"Vous avez eu de la chance que l'acheteur monte à 650 000."}],o:["Obtenir d'abord une offre écrite ailleurs, en déduire sa réserve, puis viser 700 000","Annoncer tout de suite 620 000 pour montrer sa bonne foi à l'acheteur","Demander d'abord à l'acheteur son budget maximum et se caler juste en dessous","Attendre sagement que l'acheteur fasse la première offre, forcément plus basse"],a:0,w:"MESORE d'abord (l'offre du promoteur), réserve ensuite (620 000), cible ambitieuse enfin (700 000). Sans MESORE, on n'a pas de réserve fiable."},
{i:"n150_24",u:150,t:"sort",d:.45,q:"Classe chaque situation : ZOPA ou pas de ZOPA ?",bins:["Une ZOPA existe","Pas de ZOPA"],it:[["Vendeur : pas sous 300 k€. Acheteur : pas au-dessus de 320 k€.",0],["Banque : pas sous 3,1 %. Client : pas au-dessus de 3,0 %.",1],["Salarié : pas sous 42 k€. Employeur : jusqu'à 45 k€.",0],["Banque : frais minimum 0,75 %. Client : 0,70 % maximum.",1]],w:"Une ZOPA existe quand la réserve du vendeur est inférieure ou égale à celle de l'acheteur. Sinon, aucun accord n'est rationnel sur ce seul critère."},
{i:"n150_25",u:150,t:"tf",d:.45,q:"Quand il n'y a pas de ZOPA sur le prix, on peut parfois en créer une en ajoutant d'autres éléments à la discussion.",a:true,w:"C'est le passage à la négociation intégrative (module 3) : un service, un délai, une garantie qui vaut plus pour l'autre qu'il ne te coûte peut faire apparaître une zone d'accord."},
{i:"n150_26",u:150,t:"story",d:.5,q:"Quelle phrase protège le mieux ta marge ?",sc:[{who:"Laura",txt:"Franchement, on est pressés, le compromis de vente est signé et la date butoir est dans six semaines."},{who:"Kevin",txt:"Laura !"}],o:["Aucune : c'est Laura qui vient d'affaiblir leur MESORE en révélant leur urgence","« Parfait, alors je vous propose de signer dès aujourd'hui au taux affiché, sans négociation. »","« Dans ce cas, je vous conseille de ne consulter aucune autre banque pour gagner du temps. »","« L'urgence n'a aucun impact sur une négociation de taux, ne vous en faites pas pour ça. »"],a:0,w:"Révéler l'urgence réduit la MESORE perçue (pas le temps d'aller ailleurs). Un bon conseiller le remarque, mais ne l'exploite pas au détriment de l'intérêt du client."},
{i:"n150_27",u:150,t:"slider",d:.4,q:"Sylvie autorise jusqu'à 0,60 %. Marc part au-delà de 0,70 %. Tu signes à 0,68 %. Quel pourcentage de la ZOPA la banque a-t-elle capté (de 0 % au plancher à 100 % au plafond) ?",min:0,max:100,step:5,a:80,tol:0,pre:"",un:" %",w:"La ZOPA fait 0,10 point. De 0,60 à 0,68, la banque a obtenu 0,08 point, soit 80 % de la zone. Chiffrer la ZOPA, c'est savoir comment on a partagé le surplus."},
{i:"n150_28",u:150,t:"mcq",d:.45,q:"Quelle est la meilleure façon de renforcer ta position avant de demander une augmentation à Sylvie ?",o:["Avoir une offre d'un autre employeur","Travailler plus tard le soir","Lui dire que tu es très motivé","Attendre qu'elle soit de bonne humeur"],a:0,w:"Une offre extérieure est une MESORE concrète. La motivation ou le moment choisi comptent, mais ne remplacent pas une alternative réelle."},
{i:"n150_29",u:150,t:"tiles",d:.45,q:"Reconstitue la règle du point de réserve.",a:["On","fixe","sa","réserve","avant","et","on","ne","la","révèle","jamais"],dd:["pendant","toujours","prix"],w:"À froid et en secret : c'est ce qui la rend solide. Révélée, elle devient le prix de l'accord."},
{i:"n150_30",u:150,t:"story",d:.55,q:"Rappel du module 1 : quel est le vrai sujet de Marc ?",sc:[{who:"Marc Delorme",txt:"Au fond, les 0,25 % je m'en fiche un peu. Ce qui m'énerve, c'est que personne ne m'a appelé en six ans."},{who:"Toi",me:true,txt:"..."}],o:["Son intérêt est d'être suivi et considéré : un rendez-vous annuel peut valoir plus qu'une remise","Sa position a changé : il veut désormais une remise de 0,50 % au lieu des 0,25 % demandés","Il cherche un prétexte pour partir, il faut donc lui accorder la remise tout de suite","Il veut changer de conseiller, il faut donc transmettre au plus vite son dossier à un collègue"],a:0,w:"La position était « baisser les frais », l'intérêt est la considération. Un suivi régulier élargit la ZOPA : il vaut beaucoup pour lui et coûte peu à la banque."},
{i:"n150_31",u:150,t:"fill",d:.5,q:"Un point cible doit être ambitieux mais ___.",o:["crédible","secret","négociable","extrême"],a:0,w:"Trop bas, tu laisses de la valeur sur la table ; trop haut, tu perds ta crédibilité et l'autre claque la porte. Ambitieux mais crédible, et justifiable."},
{i:"n150_32",u:150,t:"match",d:.5,q:"Associe chaque personnage à sa MESORE la plus probable.",p:[["Marc Delorme","Transférer son contrat chez NeoBanque"],["Kevin","L'offre écrite d'une autre banque"],["Claire (entrepôt)","La promesse écrite du promoteur"],["Toi, face à Sylvie","L'offre d'un autre employeur"]],w:"Chaque MESORE est une action concrète et réalisable, pas un espoir. C'est elle qui fixe la limite de chacun."}
