/*UNIT*/
{id:151,c:"NEGO",n:"Module 3",t:"Distributive ou intégrative : partager le gâteau ou l'agrandir",col:"--blue",ic:"🍰",guide:`
<h3>Claire et la grosse commande</h3>
<div class="gstory">Claire Vasseur t'appelle un vendredi soir, entre deux palettes. Maison Loire, une chaîne de magasins de cuisine, veut 10 000 façades de placard pour une opération nationale qui démarre dans trois mois. Son atelier peut en sortir 2 000 en trois mois, à condition de payer des heures supplémentaires et un contrôle qualité renforcé : 80 000 € de coût en plus. Les 10 000 ? Pas avant cinq mois. « Je vais devoir leur dire non, ou alors me battre sur le prix pour absorber les 80 000. » Tu lui réponds : « Et si on leur demandait d'abord pourquoi il leur faut 10 000 pièces dans trois mois ? »</div>
<h3>Deux façons de négocier</h3>
<table><tr><th></th><th>Distributive</th><th>Intégrative</th></tr>
<tr><td>Image</td><td>Partager un gâteau de taille fixe</td><td>Agrandir le gâteau avant de le partager</td></tr>
<tr><td>Logique</td><td>Valeur fixe : je gagne, tu perds</td><td>Valeur créée : je gagne, tu gagnes</td></tr>
<tr><td>Sur quoi ?</td><td>Un seul critère : un prix, des frais, une durée, une clause</td><td>Plusieurs critères, avec des priorités différentes</td></tr>
<tr><td>Outil clé</td><td>Point cible, réserve, ancrage, concessions</td><td>Questions sur les intérêts, échanges de priorités</td></tr>
<tr><td>Risque</td><td>Abîmer la relation</td><td>Se faire exploiter si l'on est seul à jouer le jeu</td></tr></table>
<h3>Comment on crée de la valeur</h3>
<p>La valeur apparaît parce que les deux parties n'accordent pas la même importance aux mêmes choses. On échange ce qui compte peu pour soi contre ce qui compte beaucoup pour soi. Les Anglo-Saxons appellent ça le <i>logrolling</i> (faire rouler les troncs ensemble).</p>
<div class="formula">LA BONNE QUESTION
« Que puis-je échanger qui me coûte peu et vaut beaucoup pour l'autre ? »</div>
<div class="gstory">Retour chez Maison Loire. Claire pose la question. Réponse de l'acheteuse : « Il nous faut du stock en magasin le jour du lancement, pour la photo du catalogue et les vitrines. Les 10 000, c'est pour tenir toute la saison. » Le véritable intérêt, ce n'est pas 10 000 pièces en trois mois, c'est de ne pas rater le lancement. Accord trouvé : 2 000 pièces livrées à trois mois pour les vitrines, les 8 000 autres à cinq mois, et Maison Loire prend en charge la moitié des 80 000 € de surcoût. Claire gagne une commande qu'elle allait refuser, et Maison Loire tient son lancement.</div>
<div class="gmnemo"><b>Le gâteau et le couteau.</b> En distributive, tu ne tiens que le couteau : chaque part que tu prends est retirée à l'autre. En intégrative, tu passes d'abord par le four : on fait grossir le gâteau (en cherchant les priorités différentes), puis seulement on sort le couteau pour partager. <b>Four d'abord, couteau ensuite.</b></div>
<h3>Ne pas commencer par le prix</h3>
<p>Si la discussion démarre sur le prix, elle devient distributive : un seul critère, un gagnant, un perdant. On commence donc par expliquer et explorer les <b>intérêts</b> (les siens et ceux de l'autre), puis on construit des options, et le prix vient à la fin, quand il y a plusieurs éléments à combiner.</p>
<h3>En banque, quelles monnaies d'échange ?</h3>
<table><tr><th>Élément</th><th>Coûte peu à la banque</th><th>Peut valoir beaucoup pour le client</th></tr>
<tr><td>Frais de dossier offerts</td><td>Oui</td><td>Oui, visible et immédiat</td></tr>
<tr><td>Bilan patrimonial annuel</td><td>Une heure de conseiller</td><td>Tranquillité, sentiment d'être suivi</td></tr>
<tr><td>Modularité des échéances</td><td>Presque rien</td><td>Souplesse en cas de coup dur</td></tr>
<tr><td>Carte haut de gamme offerte un an</td><td>Faible</td><td>Statut, assurances voyage</td></tr>
<tr><td>Domiciliation des salaires</td><td>Intéressant pour la banque</td><td>Peu coûteux pour le client</td></tr></table>
<div class="gtrap">Les notes opposent distributive et intégrative comme deux mondes séparés. En pratique, presque toute négociation est <b>mixte</b> : on crée d'abord de la valeur (intégratif), puis il faut bien la partager (distributif). Même chez Maison Loire, il a fallu trancher qui payait les 80 000 €. Les deux savoir-faire sont nécessaires.</div>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Dire si une négociation est distributive ou intégrative et justifier</li><li>Réciter la bonne question mot pour mot</li><li>Trouver trois éléments qui coûtent peu et valent beaucoup</li><li>Expliquer pourquoi on ne commence pas par le prix</li><li>Construire une solution intégrative à partir d'intérêts différents (cas Maison Loire)</li></ul>`},
/*EXOS*/
{i:"n151_01",u:151,t:"sort",d:.25,nw:"Distributive ou intégrative",q:"Classe chaque situation : distributive ou intégrative ?",bins:["Distributive","Intégrative"],it:[["Marchander 10 € sur un vélo d'occasion",0],["Échanger un délai contre un meilleur prix",1],["Négocier uniquement les frais de dossier",0],["Combiner taux, durée, assurance et services",1],["Discuter d'une clause de pénalité seule",0],["Livrer en deux fois pour tenir un lancement",1]],w:"Un seul critère à partager : distributive. Plusieurs critères aux priorités différentes, qu'on combine : intégrative. Four d'abord, couteau ensuite."},
{i:"n151_02",u:151,t:"fill",d:.25,q:"La bonne question : « Que puis-je échanger qui me coûte ___ et vaut beaucoup pour l'autre ? »",o:["peu","cher","rien du tout","la même chose"],a:0,w:"Ce qui te coûte peu et vaut beaucoup pour l'autre crée de la valeur. C'est le cœur de la négociation intégrative."},
{i:"n151_03",u:151,t:"mcq",d:.3,q:"Dans une négociation distributive, la valeur est :",o:["Fixe : ce que l'un gagne, l'autre le perd","Créée : chacun repart avec plus qu'au départ","Nulle : personne ne gagne rien","Garantie : chacun obtient sa cible"],a:0,w:"Distributive = gâteau de taille fixe. Je gagne, tu perds. Typique d'un prix, de frais, d'une durée ou d'une clause négociés seuls."},
{i:"n151_04",u:151,t:"story",d:.35,q:"Quelle question Claire doit-elle poser à Maison Loire ?",sc:[{who:"Claire Vasseur",txt:"Ils veulent 10 000 façades en trois mois. Je ne peux en faire que 2 000, et encore, avec 80 000 € de surcoût."},{who:"Toi",me:true,txt:"Avant de parler prix, il faut comprendre leur besoin."}],o:["« Qu'est-ce que ces 10 000 pièces à trois mois vous permettent de faire ? »","« Quel est le prix maximum que vous êtes prêts à payer pour ces 10 000 pièces ? »","« Accepteriez-vous de payer entièrement les 80 000 € de surcoût de production ? »","« Pouvez-vous confier une partie de la commande à un autre de vos fournisseurs ? »"],a:0,w:"La question ouverte sur l'usage révèle l'intérêt (réussir le lancement) et ouvre des options. Les autres ramènent tout de suite à une discussion distributive."},
{i:"n151_05",u:151,t:"tf",d:.25,q:"Il vaut mieux commencer une négociation par le prix, pour poser les bases.",a:false,w:"Commencer par le prix réduit la discussion à un seul critère : elle devient distributive. On explique et explore d'abord les intérêts."},
{i:"n151_06",u:151,t:"multi",d:.35,q:"Pour garder Marc sans baisser les frais, lesquels coûtent peu à la banque et peuvent valoir beaucoup pour lui ?",o:["Un bilan patrimonial annuel","Un point sur la transmission de sa pharmacie","Un accès direct à son conseiller par téléphone","Une remise de 0,40 % sur tous ses contrats","Le remboursement de ses frais des dix dernières années"],a:[0,1,2],w:"Des services à forte valeur perçue et faible coût. La remise massive et le remboursement coûtent cher : ils relèvent du partage, pas de la création de valeur."},
{i:"n151_07",u:151,t:"order",d:.3,q:"Remets dans l'ordre une négociation intégrative.",it:["Explorer les intérêts des deux parties","Repérer les priorités différentes","Construire plusieurs options combinées","Choisir l'option et partager la valeur créée"],w:"Four d'abord (intérêts, priorités, options), couteau ensuite (on partage). Le prix vient à la fin, jamais au début."},
{i:"n151_08",u:151,t:"story",d:.4,q:"Quel accord crée le plus de valeur ?",ctx:"Maison Loire explique : « Il nous faut du stock pour la photo du catalogue et les vitrines le jour du lancement. Les 10 000, c'est pour la saison. »",sc:[{who:"Acheteuse Maison Loire",txt:"Alors, qu'est-ce que vous nous proposez ?"}],o:["2 000 pièces à trois mois pour le lancement, 8 000 à cinq mois, surcoût partagé","10 000 pièces à cinq mois au prix initial, en renonçant complètement au lancement","2 000 pièces à trois mois au prix initial, et Claire garde tout le surcoût à sa charge","10 000 pièces à trois mois en sous-traitant sans contrôle qualité, au même prix"],a:0,w:"L'accord sert l'intérêt de Maison Loire (réussir le lancement) et celui de Claire (une production réaliste, un surcoût partagé). C'est la valeur créée."},
{i:"n151_09",u:151,t:"match",d:.3,q:"Associe chaque notion à son image.",p:[["Distributive","Partager un gâteau de taille fixe"],["Intégrative","Agrandir le gâteau avant de partager"],["Logrolling","Échanger des priorités différentes"],["Négociation mixte","Créer puis partager la valeur"]],w:"Presque toutes les vraies négociations sont mixtes : on agrandit le gâteau, puis on le partage."},
{i:"n151_10",u:151,t:"num",d:.4,q:"Dans l'accord Maison Loire, le client prend en charge la moitié des 80 000 € de surcoût. Combien reste-t-il à la charge de Claire, en euros ?",a:40000,tol:1,un:" €",h:"Moitié de 80 000",w:"40 000 € pour Claire, 40 000 € pour Maison Loire. La valeur a d'abord été créée (une commande sauvée), puis partagée (le surcoût)."},
{i:"n151_11",u:151,t:"tiles",d:.3,q:"Reconstitue la bonne question.",a:["Que","puis-je","échanger","qui","me","coûte","peu","et","vaut","beaucoup","pour","l'autre"],dd:["cher","gagner","prix"],w:"Mot pour mot : elle est attendue en évaluation. Elle oblige à chercher des asymétries de valeur."},
{i:"n151_12",u:151,t:"story",d:.4,q:"Que proposes-tu aux Robin ?",ctx:"Les Robin veulent un prêt relais pour acheter une maison plus petite. Ils trouvent le taux trop haut. La banque aimerait qu'ils domicilient leurs pensions de retraite chez elle.",sc:[{who:"Gérard Robin",txt:"Votre taux, c'est non. Trouvez mieux ou on va ailleurs."}],o:["« Si vous domiciliez vos pensions chez nous, je peux améliorer le taux. »","« Le taux est fixé par le siège, je n'ai aucune marge de manœuvre là-dessus. »","« Je vous baisse le taux de 0,3 point, mais vous renoncez à l'assurance déléguée. »","« Je comprends, allez comparer ailleurs et revenez me voir avec une offre écrite. »"],a:0,w:"La domiciliation vaut beaucoup pour la banque et coûte peu aux Robin. En l'échangeant contre un meilleur taux, on crée de la valeur au lieu de se battre sur un seul chiffre."},
{i:"n151_13",u:151,t:"tf",d:.35,q:"Une négociation intégrative n'a jamais de partie distributive.",a:false,w:"Une fois le gâteau agrandi, il faut le partager. Chez Maison Loire, il a fallu décider qui payait les 80 000 €. Les négociations réelles sont presque toujours mixtes."},
{i:"n151_14",u:151,t:"mcq",d:.35,q:"D'où vient la valeur créée dans une négociation intégrative ?",o:["Des priorités différentes des deux parties","D'une remise accordée par la partie la plus faible","Du rapport de force entre les deux parties","De la première offre, qui fixe l'ancrage"],a:0,w:"Si Maison Loire tient au lancement et Claire au réalisme de production, chacun cède sur ce qui compte moins pour lui : les deux y gagnent."},
{i:"n151_15",u:151,t:"sort",d:.4,q:"Pour la banque, classe chaque monnaie d'échange.",bins:["Coûte peu à la banque","Coûte cher à la banque"],it:[["Offrir les frais de dossier",0],["Un bilan patrimonial annuel",0],["Baisser le taux de 1 point",1],["Modularité des échéances",0],["Prendre en charge tous les frais de notaire",1],["Carte premium offerte un an",0]],w:"Les services et la souplesse coûtent peu à la banque mais ont une vraie valeur perçue. Les gros gestes financiers entament directement sa marge."},
{i:"n151_16",u:151,t:"story",d:.45,q:"Quelle est l'erreur de Hugo ?",sc:[{who:"Hugo",txt:"Kevin voulait un meilleur taux. Je lui ai directement proposé 0,2 point de moins, puis 0,3, puis 0,4. Il a fini par signer."},{who:"Sylvie Morel",txt:"Et tu as parlé d'autre chose que du taux ?"},{who:"Hugo",txt:"Non, c'est ce qu'il demandait."}],o:["Il a gardé une négociation à un seul critère et n'a fait que céder","Il aurait dû proposer directement 0,4 point pour conclure plus vite","Il aurait dû refuser toute baisse de taux dès la première demande","Il aurait dû demander à Kevin de revenir avec son conjoint"],a:0,w:"En restant sur le taux, Hugo a transformé la négociation en pure distributive, et il a été le seul à céder. Il aurait fallu explorer les intérêts (mensualité, souplesse, assurance) et échanger."},
{i:"n151_17",u:151,t:"slider",d:.4,q:"Maison Loire commande 10 000 façades. Claire en livre 2 000 à trois mois pour le lancement. Quel pourcentage de la commande arrive pour le lancement ?",min:0,max:100,step:5,a:20,tol:0,pre:"",un:" %",w:"2 000 sur 10 000 = 20 %. Et pourtant ces 20 % suffisent à Maison Loire, parce que son intérêt réel est d'avoir du stock pour les vitrines et le catalogue le jour J, pas toute la saison d'un coup."},
{i:"n151_18",u:151,t:"fill",d:.4,q:"En négociation intégrative, la valeur est ___ : je gagne, tu gagnes.",o:["créée","partagée","perdue","imposée"],a:0,w:"Valeur créée grâce aux priorités différentes. En distributive, elle est seulement partagée."},
{i:"n151_19",u:151,t:"story",d:.45,q:"Comment Claire doit-elle ouvrir la réunion avec Maison Loire ?",sc:[{who:"Claire Vasseur",txt:"J'ai préparé mon prix unitaire avec les 80 000 € dedans. Je l'annonce en premier ?"},{who:"Toi",me:true,txt:"..."}],o:["« Commencez par leurs enjeux sur ce lancement, le prix viendra après. »","« Oui, annoncez-le tout de suite, ça crée un ancrage favorable pour vous. »","« Non, attendez qu'ils annoncent leur budget et ajustez votre prix unitaire dessus. »","« Annoncez un prix sans les 80 000 €, vous les rajouterez plus tard en cours de route. »"],a:0,w:"Ne pas commencer par le prix : expliquer et explorer les intérêts d'abord. Sinon la discussion se fige sur un seul critère."},
{i:"n151_20",u:151,t:"multi",d:.45,q:"Quels éléments peuvent être mis sur la table dans la négociation Maison Loire, en plus du prix ?",o:["Le calendrier de livraison","Le partage du surcoût","Le volume de la première livraison","Un contrat sur plusieurs saisons","La couleur du logo de Claire"],a:[0,1,2,3],w:"Plus il y a de critères, plus il y a d'échanges possibles. Délai, volume, surcoût, durée de la relation : autant de monnaies d'échange."},
{i:"n151_21",u:151,t:"mcq",d:.45,q:"Rappel du module 2 : Maison Loire menace d'aller chez un autre fabricant. Que dois-tu vérifier en premier ?",o:["Si ce fabricant peut vraiment livrer dans les délais","Le prix exact que ce fabricant propose","La taille de l'entreprise de ce fabricant","Si Claire connaît personnellement ce fabricant"],a:0,w:"La MESORE de Maison Loire n'est bonne que si l'alternative est réaliste. Si personne ne peut livrer 10 000 pièces en trois mois, leur menace est faible."},
{i:"n151_22",u:151,t:"tf",d:.4,q:"La domiciliation des revenus est un exemple d'élément qui peut coûter peu au client et valoir beaucoup pour la banque.",a:true,w:"Pour la banque, les flux de revenus sont précieux (relation, dépôts, ventes croisées). Pour le client, changer de banque principale coûte peu : c'est une monnaie d'échange classique."},
{i:"n151_23",u:151,t:"story",d:.5,q:"Quelle réponse transforme la négociation en intégrative ?",sc:[{who:"Marc Delorme",txt:"0,85 % c'est trop. 0,60 % ou rien."},{who:"Toi",me:true,txt:"..."}],o:["« Parlons de ce que vous attendez de nous pour votre épargne et votre pharmacie. »","« Je peux faire 0,75 %, c'est un vrai effort de notre part, croyez-moi. »","« Coupons la poire en deux : 0,725 % et on n'en parle plus jamais. »","« 0,60 % c'est impossible, nous ne pourrions plus couvrir nos coûts. »"],a:0,w:"Élargir la discussion aux attentes de Marc (épargne, pharmacie) ouvre d'autres critères. Les autres réponses restent sur un seul chiffre."},
{i:"n151_24",u:151,t:"order",d:.45,q:"Remets dans l'ordre l'histoire de l'accord Maison Loire.",it:["Maison Loire demande 10 000 pièces en trois mois","Claire demande à quoi servent ces pièces","L'acheteuse révèle l'enjeu du lancement","Livraison en deux fois proposée","Partage du surcoût de 80 000 €"],w:"Demande (position), question (pourquoi ?), intérêt révélé, option créée, puis partage : c'est une négociation mixte complète."},
{i:"n151_25",u:151,t:"tiles",d:.45,q:"Reconstitue la formule mémo.",a:["Four","d'abord","couteau","ensuite"],dd:["prix","toujours","gâteau"],w:"On agrandit le gâteau (four) avant de le partager (couteau). Commencer par le couteau, c'est commencer par le prix."},
{i:"n151_26",u:151,t:"match",d:.45,q:"Associe chaque élément négociable à la partie pour qui il vaut le plus.",p:[["Livraison rapide de 2 000 pièces","Maison Loire"],["Délai de cinq mois pour le reste","Claire"],["Domiciliation des pensions","La banque"],["Modularité des échéances","Kevin et Laura"]],w:"Chaque élément a plus de valeur pour une partie que pour l'autre : c'est ce déséquilibre qui permet d'échanger."},
{i:"n151_27",u:151,t:"story",d:.5,q:"Quel risque Sylvie souligne-t-elle ?",sc:[{who:"Sylvie Morel",txt:"L'intégratif c'est bien. Mais attention quand tu es le seul à jouer le jeu."},{who:"Toi",me:true,txt:"Tu veux dire quoi ?"}],o:["Si tu partages tes priorités et que l'autre ne le fait pas, il peut en profiter","L'intégratif prend trop de temps, il vaut mieux négocier toujours le prix d'abord","Le client risque de trouver bizarre qu'on lui pose des questions sur ses projets","La banque interdit de proposer plusieurs options à un même client lors d'un rendez-vous"],a:0,w:"Le risque de l'intégratif est l'exploitation : révéler ce qui compte pour toi sans réciprocité. On partage l'information progressivement, en échange d'informations."},
{i:"n151_28",u:151,t:"num",d:.5,q:"Pour garder Marc, la banque offre un bilan patrimonial qui lui coûte 150 € de temps de conseiller. Marc estime ce bilan à 600 €. Quelle valeur a été créée, en euros ?",a:450,tol:1,un:" €",h:"Valeur pour le client moins coût pour la banque",w:"600 − 150 = 450 € de valeur créée. C'est exactement « ce qui me coûte peu et vaut beaucoup pour l'autre »."},
{i:"n151_29",u:151,t:"fill",d:.5,q:"Négocier un prix, des frais, une durée ou une ___ isolément relève de la négociation distributive.",o:["clause","relation","stratégie","priorité"],a:0,w:"Les notes citent ces quatre objets : prix, frais, durée, clause. Discutés un par un, ils créent un duel à somme fixe."},
{i:"n151_30",u:151,t:"story",d:.55,q:"Rappel du module 1 : quelle est la position de l'acheteuse de Maison Loire, et quel est son intérêt ?",sc:[{who:"Acheteuse Maison Loire",txt:"Nous voulons 10 000 façades dans trois mois. C'est notre condition."}],o:["Position : 10 000 à trois mois. Intérêt : réussir le lancement en magasin","Position : réussir le lancement. Intérêt : obtenir 10 000 pièces à trois mois","Position : payer le moins cher. Intérêt : changer de fournisseur","Position : tester Claire. Intérêt : imposer des pénalités de retard"],a:0,w:"La position est la demande chiffrée ; l'intérêt est la raison (le lancement). C'est en travaillant l'intérêt qu'on a trouvé l'accord."},
{i:"n151_31",u:151,t:"mcq",d:.5,q:"Quel est le principal risque d'une négociation purement distributive dans une relation client durable ?",o:["Abîmer la relation","Créer trop de valeur","Proposer trop d'options","Perdre du temps en questions"],a:0,w:"Quand l'un gagne ce que l'autre perd, le perdant s'en souvient. En banque, où la relation dure des années, c'est un coût caché important."},
{i:"n151_32",u:151,t:"tf",d:.5,q:"Offrir des frais de dossier peut être une meilleure concession qu'une baisse de taux, car elle coûte moins cher à la banque sur la durée.",a:true,w:"Une baisse de taux coûte chaque mois pendant des années ; des frais de dossier offerts coûtent une fois. Pour le client, le geste est visible tout de suite. Ce qui coûte peu et vaut beaucoup."}
