/*UNIT*/
{id:152,c:"NEGO",n:"Module 4",t:"Préparer avant d'entrer : la carte du client et les objections",col:"--blue",ic:"🗺️",guide:`
<h3>La veille du grand rendez-vous</h3>
<div class="gstory">Mardi, 18 h 40. Demain à 10 h, Claire Vasseur vient parler de ses 650 000 €. Hugo range déjà ses affaires : « Je verrai sur place, je suis bon en impro. » Sylvie Morel lui répond sans lever les yeux : « Les négociations se gagnent la veille, Hugo. Le jour J, on ne fait que récolter. » Tu ouvres une feuille blanche et tu la divises en quatre.</div>
<p>Préparer, c'est trois chantiers : <b>cartographier le client</b>, <b>définir ta position</b>, <b>préparer tes questions et anticiper les objections</b>.</p>
<h3>1. Cartographier le client</h3>
<table><tr><th>Case</th><th>Question à se poser</th><th>Pour Claire</th></tr>
<tr><td><b>Situation</b></td><td>Où en est-il ? Famille, métier, patrimoine, revenus</td><td>45 ans, mariée à Olivier (professeur), séparation de biens, Léo 17 ans, Inès 14 ans, dirige une menuiserie de 38 salariés</td></tr>
<tr><td><b>Objectifs</b></td><td>Que veut-il obtenir, à quelle échéance ?</td><td>Études des enfants, retraite, transmission</td></tr>
<tr><td><b>Contraintes</b></td><td>Qu'est-ce qui limite ses choix ?</td><td>Garder de la trésorerie pour l'entreprise, horizon court pour Léo</td></tr>
<tr><td><b>Émotions</b></td><td>Que ressent-il ? Peurs, fiertés, colères</td><td>Peur de revivre 2020, fierté d'avoir sauvé l'atelier, méfiance envers les banques</td></tr></table>
<div class="gmnemo"><b>La carte routière.</b> Où est la voiture ? (<b>Situation</b>). Où veut-elle aller ? (<b>Objectifs</b>). Quels travaux sur la route ? (<b>Contraintes</b>). Dans quel état est le conducteur, calme ou paniqué ? (<b>Émotions</b>). Oublie le conducteur, et même le meilleur itinéraire finit dans le fossé.</div>
<p>Les émotions ne sont pas un détail. Un client qui a peur n'entend pas un argument de rendement ; un client blessé dans son orgueil n'entend pas une remise. Si tu ne les as pas repérées, tes arguments tombent à côté.</p>
<h3>2. Définir ta position</h3>
<div class="formula">Cible      : ce que tu vises (ambitieux mais crédible)
Plancher   : ta limite, le point de réserve du module 2
Arguments  : pourquoi ta proposition sert ses intérêts
Preuves    : ce qui rend chaque argument vérifiable</div>
<div class="gmnemo"><b>C.P.A.P. : « Chaque Promesse A sa Preuve ».</b> Cible, Plancher, Arguments, Preuves. Un argument sans preuve est une promesse en l'air ; le client le sent immédiatement.</div>
<p>Une <b>preuve</b> peut être un chiffre publié (rendement moyen des fonds euros : 2,63 % en 2025 selon l'ACPR), une simulation chiffrée, un document contractuel, un historique de performance avec sa volatilité, un cas client anonymisé, un texte de loi.</p>
<h3>3. Préparer les questions qui ouvrent la discussion</h3>
<p>Tu écris à l'avance trois ou quatre questions ouvertes qui feront parler le client de ses priorités : « Qu'est-ce qui est important pour vous dans ce placement ? », « Comment voyez-vous les dix prochaines années ? », « Qu'est-ce qui vous a déçu jusqu'ici avec les banques ? ».</p>
<h3>4. Anticiper les objections</h3>
<p>Les cinq objections qui reviennent dans presque tout rendez-vous patrimonial :</p>
<table><tr><th>Objection</th><th>Ce que dit le client</th><th>Ce que tu prépares</th></tr>
<tr><td><b>Frais</b></td><td>« C'est trop cher »</td><td>Coût total chiffré, comparaison marché, valeur apportée</td></tr>
<tr><td><b>Risques</b></td><td>« Je ne veux pas perdre »</td><td>Scénarios défavorables chiffrés, part garantie, horizon</td></tr>
<tr><td><b>Liquidité</b></td><td>« Et si j'ai besoin de l'argent ? »</td><td>Délais de rachat, poche disponible, avance</td></tr>
<tr><td><b>Confiance</b></td><td>« Vous voulez juste me vendre un produit »</td><td>Transparence sur ta rémunération, documents, suivi</td></tr>
<tr><td><b>Fiscalité</b></td><td>« Je vais payer plus d'impôts »</td><td>Comparaison fiscale des enveloppes, simulation nette</td></tr></table>
<div class="gmnemo"><b>La main du client.</b> Le pouce compte les billets : <b>Frais</b>. L'index pointe le danger : <b>Risques</b>. Le majeur, le plus long, doit pouvoir atteindre l'argent : <b>Liquidité</b>. L'annulaire porte l'alliance : <b>Confiance</b>. Le petit doigt se glisse partout, comme le fisc : <b>Fiscalité</b>. Avant chaque rendez-vous, compte sur tes doigts.</div>
<div class="gtrap">Dans les notes, « Écoute active et questionnement » est rangé sous « Préparation stratégique ». L'écoute ne se prépare pas seulement : elle se pratique pendant l'entretien (module 5). Ce qu'on prépare, ce sont les <b>questions</b> ; ce qu'on pratique, c'est l'<b>écoute</b>. Et le « plancher » des notes est exactement le <b>point de réserve</b> du module 2 : deux mots, une même limite.</div>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Remplir une carte client en quatre cases à partir d'un brief</li><li>Distinguer cible et plancher, argument et preuve</li><li>Écrire trois questions d'ouverture</li><li>Citer les cinq objections et une réponse préparée pour chacune</li></ul>`},
/*EXOS*/
{i:"n152_01",u:152,t:"sort",d:.25,nw:"Cartographier le client",q:"Range chaque information sur Claire dans la bonne case de la carte.",bins:["Situation","Objectifs","Contraintes","Émotions"],it:[["Mariée, deux enfants de 17 et 14 ans",0],["Financer les études de Léo et Inès",1],["Garder de la trésorerie pour l'entreprise",2],["Peur de revivre la crise de 2020",3],["Préparer sa retraite",1],["Méfiance envers les banques",3],["Dirige une menuiserie de 38 salariés",0]],w:"Situation (où est la voiture), Objectifs (où elle va), Contraintes (les travaux sur la route), Émotions (l'état du conducteur)."},
{i:"n152_02",u:152,t:"story",d:.3,q:"Que réponds-tu à Hugo ?",sc:[{who:"Hugo",txt:"Préparer ? Je verrai sur place, je suis bon en impro."},{who:"Sylvie Morel",txt:"Réponds-lui, toi."}],o:["« Une négociation se gagne la veille : sans carte ni plancher, tu improvises ta limite. »","« Tu as raison, l'improvisation permet de mieux s'adapter au client au moment présent. »","« Prépare seulement ton prix, le reste viendra naturellement pendant le rendez-vous. »","« Prépare surtout ton argumentaire produit, c'est ce qui convainc vraiment le client. »"],a:0,w:"Sans préparation, pas de plancher fixé à froid, pas de questions d'ouverture, pas d'objections anticipées. On récolte le jour J ce qu'on a semé la veille."},
{i:"n152_03",u:152,t:"match",d:.3,nw:"Définir sa position",q:"Associe chaque élément de ta position à son exemple pour Claire.",p:[["Cible","Placer 400 000 € en assurance-vie multisupport"],["Plancher","Pas moins de 200 000 € confiés à la banque"],["Argument","Une poche disponible pour les études de Léo"],["Preuve","Simulation des rachats possibles chaque année"]],w:"Chaque Promesse A sa Preuve : Cible, Plancher, Arguments, Preuves."},
{i:"n152_04",u:152,t:"tf",d:.25,q:"Le plancher de la préparation stratégique correspond au point de réserve.",a:true,w:"Deux mots pour la même limite : en dessous, on ne signe pas. On le fixe à froid, la veille, à partir de sa MESORE."},
{i:"n152_05",u:152,t:"multi",d:.3,nw:"Les cinq objections",q:"Coche les cinq objections à anticiper dans un rendez-vous patrimonial.",o:["Les frais","Les risques","La liquidité","La confiance","La fiscalité","La météo"],a:[0,1,2,3,4],w:"La main du client : pouce Frais, index Risques, majeur Liquidité, annulaire Confiance, petit doigt Fiscalité."},
{i:"n152_06",u:152,t:"story",d:.35,q:"Quelle objection Claire exprime-t-elle ?",sc:[{who:"Claire Vasseur",txt:"Et si mon entreprise a un coup dur l'an prochain, je peux récupérer l'argent en combien de temps ?"}],o:["La liquidité","La fiscalité","Les frais","La confiance"],a:0,w:"Pouvoir récupérer son argent vite : c'est la liquidité (le majeur qui doit pouvoir atteindre l'argent). Prépare les délais de rachat et une poche disponible."},
{i:"n152_07",u:152,t:"fill",d:.3,q:"Un argument sans ___ est une promesse en l'air.",o:["preuve","cible","émotion","remise"],a:0,w:"Chaque Promesse A sa Preuve : chiffre publié, simulation, document, historique. Le client doit pouvoir vérifier."},
{i:"n152_08",u:152,t:"order",d:.3,q:"Remets dans l'ordre les trois chantiers de la préparation.",it:["Cartographier le client","Définir cible, plancher, arguments et preuves","Préparer les questions d'ouverture et anticiper les objections"],w:"D'abord comprendre l'autre, ensuite fixer sa position, enfin préparer le dialogue."},
{i:"n152_09",u:152,t:"mcq",d:.35,q:"Pourquoi les émotions figurent-elles sur la carte du client ?",o:["Un client inquiet n'entend pas un argument de rendement","Elles permettent de facturer plus cher les clients anxieux","Elles remplacent le questionnaire réglementaire de profil","Elles servent uniquement aux clients particuliers fortunés"],a:0,w:"Les émotions filtrent tout ce que le client entend. Claire a peur de revivre 2020 : un discours sur la performance tomberait à plat."},
{i:"n152_10",u:152,t:"story",d:.4,q:"Quelle réponse as-tu préparée pour l'objection de Marc ?",sc:[{who:"Marc Delorme",txt:"De toute façon, vous touchez une commission sur tout ce que vous me vendez."}],o:["« Oui, et je vous montre exactement combien et comment, noir sur blanc. »","« Pas du tout, je suis payé au fixe, les commissions ne me concernent pas. »","« Toutes les banques font pareil, ça ne change rien à la qualité du conseil. »","« C'est un sujet interne, je ne peux pas vous communiquer ces informations. »"],a:0,w:"C'est l'objection de confiance (l'annulaire). La transparence sur la rémunération est la réponse préparée : elle désarme le soupçon au lieu de l'alimenter."},
{i:"n152_11",u:152,t:"sort",d:.4,q:"Classe chaque phrase de client dans l'objection correspondante.",bins:["Frais","Risques","Liquidité","Confiance","Fiscalité"],it:[["« 1 % par an, c'est énorme »",0],["« Et si la Bourse chute de 30 % ? »",1],["« Je ne veux pas bloquer mon argent »",2],["« Vous me dites ça pour vos objectifs »",3],["« Combien je paierai d'impôts en retirant ? »",4]],w:"Pouce, index, majeur, annulaire, petit doigt : anticiper les objections, c'est compter sur tes doigts avant chaque rendez-vous."},
{i:"n152_12",u:152,t:"tf",d:.3,q:"Une question d'ouverture efficace se prépare à l'avance.",a:true,w:"On écrit trois ou quatre questions ouvertes avant le rendez-vous. Sur le moment, sous pression, on retombe vite sur des questions fermées ou sur son argumentaire."},
{i:"n152_13",u:152,t:"multi",d:.4,q:"Lesquelles sont de bonnes preuves à apporter à Claire ?",o:["Le rendement moyen des fonds euros publié par l'ACPR","Une simulation chiffrée de ses rachats pour les études","La notice du contrat avec les frais détaillés","« Faites-moi confiance, je connais bien ces produits »","« Tous mes clients sont ravis »"],a:[0,1,2],w:"Une preuve est vérifiable : chiffre publié, simulation, document contractuel. L'appel à la confiance et les généralités ne prouvent rien."},
{i:"n152_14",u:152,t:"story",d:.4,q:"Quelle question d'ouverture prépares-tu pour les Robin ?",ctx:"Gérard et Martine Robin, 61 et 59 ans, viennent pour « préparer leur retraite ». Gérard est commercial, Martine assistante de direction.",sc:[{who:"Toi",me:true,txt:"(dans ta préparation, tu écris ta première question)"}],o:["« Comment imaginez-vous une journée type de votre retraite ? »","« Voulez-vous ouvrir un PER ou plutôt une assurance-vie avec nous ? »","« Quel montant exact souhaitez-vous placer chez nous cette année ? »","« Avez-vous déjà entendu parler de nos SCPI les plus rentables ? »"],a:0,w:"Une question ouverte fait parler des projets et des priorités. Les autres ferment tout de suite la discussion sur un produit ou un montant."},
{i:"n152_15",u:152,t:"fill",d:.35,q:"Quand Claire dit « je ne veux pas perdre », elle exprime une objection de ___.",o:["risque","liquidité","fiscalité","confiance"],a:0,w:"L'index qui pointe le danger. Réponse préparée : scénarios défavorables chiffrés, part garantie, horizon de placement."},
{i:"n152_16",u:152,t:"mcq",d:.35,q:"Dans la carte du client, « garder de la trésorerie pour l'entreprise » est :",o:["Une contrainte","Un objectif","Une émotion","Un argument clé"],a:0,w:"C'est ce qui limite ses choix : une contrainte (les travaux sur la route). L'objectif serait « financer les études » ou « préparer la retraite »."},
{i:"n152_17",u:152,t:"tiles",d:.35,q:"Reconstitue la phrase de Sylvie.",a:["Les","négociations","se","gagnent","la","veille"],dd:["toujours","prix","demain"],w:"Le jour J, on récolte ce qu'on a préparé : carte du client, plancher, preuves, questions, objections."},
{i:"n152_18",u:152,t:"story",d:.45,q:"Quelle réponse as-tu préparée pour l'objection fiscale de Claire ?",sc:[{who:"Claire Vasseur",txt:"Si je retire de l'argent pour les études de Léo, je vais me faire matraquer par les impôts, non ?"}],o:["« Seule la part de gains est imposée, je vous montre une simulation nette. »","« Non, les retraits d'assurance-vie ne sont jamais imposés, aucun souci. »","« Si, c'est pour cela qu'il vaut mieux ne jamais retirer avant la retraite. »","« La fiscalité change tout le temps, on ne peut rien prévoir à l'avance. »"],a:0,w:"En assurance-vie, un rachat n'impose que la quote-part de gains qu'il contient. Une simulation nette est la preuve préparée. Dire « jamais imposé » est faux."},
{i:"n152_19",u:152,t:"num",d:.45,q:"Tu prépares une preuve de frais : Claire place 400 000 € sur un contrat à 0,70 % de frais de gestion annuels. Combien lui coûtent ces frais la première année, en euros ?",a:2800,tol:1,un:" €",h:"0,70 % de 400 000",w:"400 000 × 0,70 % = 2 800 €. Afficher le coût en euros, pas seulement en %, désamorce l'objection des frais (le pouce) : le client voit ce qu'il paie et ce qu'il obtient."},
{i:"n152_20",u:152,t:"story",d:.45,q:"Rappel du module 2 : Hugo a noté son plancher sur sa fiche. Qu'en fais-tu ?",sc:[{who:"Hugo",txt:"Je pose ma fiche sur le bureau pendant le rendez-vous, comme ça je n'oublie pas mon plancher."}],o:["« Garde-la hors de vue : un plancher lu par le client devient le prix. »","« Bonne idée, la transparence est toujours appréciée par les clients. »","« Écris-le plutôt en gros sur le tableau, c'est plus professionnel. »","« Montre-la au client à la fin, pour prouver que tu as fait un effort. »"],a:0,w:"Le plancher (point de réserve) ne se révèle jamais. Lu par le client, il devient immédiatement le prix de l'accord."},
{i:"n152_21",u:152,t:"order",d:.4,q:"Remets dans l'ordre les quatre cases de la carte routière.",it:["Situation","Objectifs","Contraintes","Émotions"],w:"Où est la voiture, où elle va, quels obstacles, dans quel état est le conducteur. S.O.C.E."},
{i:"n152_22",u:152,t:"slider",d:.4,q:"Combien d'objections types faut-il préparer avant un rendez-vous patrimonial ?",min:1,max:10,step:1,a:5,tol:0,pre:"",un:" objections",w:"Cinq, une par doigt : frais, risques, liquidité, confiance, fiscalité."},
{i:"n152_23",u:152,t:"match",d:.45,q:"Associe chaque objection à la preuve la plus adaptée.",p:[["Frais","Coût total chiffré en euros"],["Risques","Scénario défavorable simulé"],["Liquidité","Délai de rachat inscrit au contrat"],["Fiscalité","Simulation nette d'impôt"]],w:"Chaque objection a sa preuve. Anticiper, c'est la préparer la veille : chiffrer, simuler, montrer le contrat. Le client doit pouvoir vérifier seul."},
{i:"n152_24",u:152,t:"tf",d:.45,q:"Si l'on a bien cartographié le client, il est inutile de lui poser des questions pendant l'entretien.",a:false,w:"La carte est une série d'hypothèses. L'entretien sert à les vérifier : une hypothèse non validée peut te faire proposer à côté."},
{i:"n152_25",u:152,t:"story",d:.5,q:"Quelle émotion devais-tu repérer chez Marc ?",ctx:"Marc explique qu'il a appris par hasard, en parlant avec un confrère, que celui-ci payait moins de frais dans la même banque.",sc:[{who:"Marc Delorme",txt:"Je me suis senti pris pour un pigeon."}],o:["Le sentiment d'être traité injustement, bien plus que le montant","Une envie de rendement plus élevé sur ses placements financiers","Une peur de perdre son capital en cas de crise sur les marchés","Une inquiétude sur la fiscalité de ses rachats à la retraite"],a:0,w:"C'est une blessure d'orgueil et d'équité. Tant qu'elle n'est pas reconnue, aucun chiffre ne passera. D'où l'importance de la case Émotions."},
{i:"n152_26",u:152,t:"fill",d:.5,q:"Chaque Promesse A sa ___ : c'est le moyen de retenir cible, plancher, arguments, preuves.",o:["Preuve","Prime","Pause","Priorité"],a:0,w:"C.P.A.P. : Cible, Plancher, Arguments, Preuves."},
{i:"n152_27",u:152,t:"multi",d:.5,q:"Pour l'objection de liquidité de Claire, que peux-tu préparer ?",o:["Les délais de rachat de l'assurance-vie","Une poche d'épargne disponible à côté","La possibilité d'une avance sur contrat","Un placement bloqué dix ans mieux rémunéré","Une réponse vague pour ne pas l'inquiéter"],a:[0,1,2],w:"Rachat possible, poche disponible, avance : trois réponses concrètes. Proposer un placement bloqué ignore sa contrainte ; être vague détruit la confiance."},
{i:"n152_28",u:152,t:"story",d:.5,q:"Rappel du module 3 : que prépares-tu en plus de ton prix ?",sc:[{who:"Sylvie Morel",txt:"Pour Claire, tu as préparé autre chose que tes frais ?"}],o:["« Des éléments qui me coûtent peu et valent beaucoup pour elle. »","« Non, je vais d'abord annoncer mes frais pour ancrer la discussion. »","« Une remise maximale, à donner dès qu'elle hésite un peu trop. »","« Un argumentaire sur nos meilleurs fonds de l'année dernière. »"],a:0,w:"Préparer des monnaies d'échange (bilan annuel, suivi, souplesse) permet une négociation intégrative. Ancrer sur les frais d'emblée la rendrait distributive."},
{i:"n152_29",u:152,t:"tiles",d:.5,q:"Reconstitue les cinq objections dans l'ordre des doigts, du pouce au petit doigt.",a:["frais","risques","liquidité","confiance","fiscalité"],dd:["prix","rendement","durée"],w:"Pouce Frais, index Risques, majeur Liquidité, annulaire Confiance, petit doigt Fiscalité."},
{i:"n152_30",u:152,t:"mcq",d:.5,q:"Où les notes rangent-elles l'écoute active, et qu'en retenir ?",o:["Sous la préparation, mais elle se pratique pendant l'entretien","Sous le closing, car elle sert surtout à conclure la vente","Sous le suivi, car elle intervient seulement après la signature","Nulle part, car elle n'est pas utile en banque"],a:0,w:"On prépare les questions ; on pratique l'écoute en direct. C'est l'objet du module 5 (questions ouvertes, reformulation, silence, résumé)."},
{i:"n152_31",u:152,t:"story",d:.55,q:"Qu'aurait dû noter Hugo dans la case Émotions de Kevin ?",ctx:"Kevin a raconté que ses parents ont perdu leur maison quand il avait douze ans, après un crédit mal remboursé.",sc:[{who:"Hugo",txt:"J'ai rien mis dans Émotions, c'était une anecdote."}],o:["Une peur forte du surendettement, qui guidera toutes ses décisions","Une envie de rembourser son prêt le plus vite possible, en 10 ans","Une méfiance à l'égard des taux variables et des courtiers en ligne","Une préférence très nette pour les prêts in fine sans amortissement"],a:0,w:"Ce souvenir est une émotion puissante : la peur du surendettement. Elle expliquera ses objections (mensualité, sécurité) : il faut la noter et en tenir compte."},
{i:"n152_32",u:152,t:"tf",d:.55,q:"Préparer des preuves sert aussi à se protéger soi-même, en laissant une trace de ce qui a été présenté au client.",a:true,w:"Simulations, documents remis, notices : ils prouvent au client, et plus tard à un contrôleur, que le conseil reposait sur des éléments objectifs."}
