/*UNIT*/
{id:153,c:"NEGO",n:"Module 5",t:"Écouter pour de vrai : questions ouvertes, silence et 4R",col:"--blue",ic:"👂",guide:`
<h3>Les trois secondes qui ont tout changé</h3>
<div class="gstory">Dix heures, Claire Vasseur est assise en face de toi. Tu demandes : « Qu'est-ce qui est important pour vous dans ce placement ? » Elle répond : « Que ce soit sûr. » Hugo, à côté de toi, ouvre déjà la bouche pour parler du fonds euros. Tu poses la main sur son bras et tu ne dis rien. Une seconde. Deux. Trois. Claire regarde la fenêtre, puis ajoute : « En fait... mon mari ne sait pas que l'entreprise a failli fermer en 2020. S'il m'arrive quelque chose, je veux que Léo et Inès ne manquent de rien. » Le vrai critère de décision venait d'arriver. Il était caché derrière trois secondes de silence.</div>
<h3>Les quatre outils de l'écoute active</h3>
<table><tr><th>Outil</th><th>À quoi il sert</th><th>Exemple</th></tr>
<tr><td><b>Questions ouvertes</b></td><td>Faire parler le client de ce qui compte pour lui</td><td>« Qu'est-ce qui est important pour vous ? »</td></tr>
<tr><td><b>Reformulation</b></td><td>Valider la compréhension et créer la confiance</td><td>« Si je vous suis bien, la sécurité passe avant le rendement ? »</td></tr>
<tr><td><b>Silence utile</b></td><td>Laisser émerger les vrais critères de décision</td><td>Compter trois secondes après une réponse importante</td></tr>
<tr><td><b>Résumé intermédiaire</b></td><td>Transformer le flou du client en critères d'accord</td><td>« Nous avons trois critères : sécurité, disponibilité pour Léo, transmission. »</td></tr></table>
<h3>Question ouverte ou fermée ?</h3>
<p>Une <b>question fermée</b> appelle oui, non ou un chiffre : « Voulez-vous un fonds euros ? ». Elle sert à <b>vérifier</b> ou <b>conclure</b>. Une <b>question ouverte</b> commence souvent par comment, qu'est-ce que, pourquoi, dans quelle mesure : elle sert à <b>découvrir</b>. En début d'entretien, on ouvre ; en fin d'entretien, on ferme.</p>
<div class="gtrap">« Pourquoi » est une question ouverte, mais elle peut sonner comme un reproche (« Pourquoi avez-vous fait ça ? »). Préfère « Qu'est-ce qui vous a amené à... ? » ou « Qu'est-ce qui compte pour vous dans... ? ». Et attention à la fausse question ouverte : « Vous ne pensez pas qu'un fonds euros serait mieux ? » est une suggestion déguisée, fermée.</div>
<h3>La méthode des 4R</h3>
<div class="formula">Reprendre   : reprendre les mots exacts du client
Relier      : relier besoin, contraintes et objectifs
Reformuler  : dire ce que l'on a compris, sans interpréter
Revalider   : obtenir un « oui, c'est bien cela » avant tout conseil</div>
<div class="gstory">Tu l'appliques avec Claire. <b>Reprendre</b> : « Vous avez dit : que Léo et Inès ne manquent de rien. » <b>Relier</b> : « Donc votre besoin de sécurité est lié à leur avenir, avec une contrainte : garder de la trésorerie pour l'entreprise. » <b>Reformuler</b> : « Si je comprends bien, vous cherchez à protéger vos enfants en cas de coup dur, tout en gardant de la souplesse. » <b>Revalider</b> : « C'est bien cela ? » Claire : « Oui, c'est exactement ça. » Là seulement, tu peux conseiller.</div>
<div class="gmnemo"><b>Le miroir en 4 temps.</b> Tu tends d'abord le miroir tel quel (Reprendre ses mots), tu relies les morceaux du reflet (Relier), tu décris l'image entière (Reformuler), puis tu demandes « c'est bien vous ? » (Revalider). Un conseil donné avant le « oui » est un conseil donné à quelqu'un d'autre.</div>
<h3>Pourquoi valider la compréhension avant de conseiller ?</h3>
<p>Pour être sûr que le conseil est en <b>réelle adéquation</b> avec la situation du client. Un conseil bâti sur un malentendu est inadapté, même s'il est techniquement parfait. C'est aussi une exigence réglementaire : le conseil doit être adapté (on parle d'<b>adéquation</b> en investissement), et la reformulation validée en est la meilleure preuve.</p>
<h3>Reformuler sans interpréter</h3>
<p>Reformuler, ce n'est pas ajouter ton analyse. Claire dit « je veux de la sécurité » ; « donc vous êtes prudente et vous voulez du fonds euros » est une interprétation. « La sécurité est votre priorité » est une reformulation. L'interprétation vient plus tard, dans le conseil.</p>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Citer les quatre outils de l'écoute active et leur utilité exacte</li><li>Transformer une question fermée en question ouverte</li><li>Dérouler les 4R sur un cas</li><li>Distinguer reformulation et interprétation</li><li>Expliquer pourquoi on valide avant de conseiller</li></ul>`},
/*EXOS*/
{i:"n153_01",u:153,t:"sort",d:.25,nw:"Question ouverte ou fermée",q:"Classe chaque question : ouverte ou fermée ?",bins:["Ouverte","Fermée"],it:[["« Qu'est-ce qui est important pour vous ? »",0],["« Voulez-vous un fonds euros ? »",1],["« Comment voyez-vous votre retraite ? »",0],["« Avez-vous des enfants ? »",1],["« Qu'est-ce qui vous inquiète le plus ? »",0],["« Vous ne pensez pas que ce serait mieux ? »",1]],w:"Ouverte : comment, qu'est-ce que, dans quelle mesure. Fermée : oui, non, un chiffre. La dernière est une suggestion déguisée, donc fermée."},
{i:"n153_02",u:153,t:"match",d:.3,nw:"Les quatre outils de l'écoute active",q:"Associe chaque outil à son utilité.",p:[["Questions ouvertes","Faire parler de ce qui compte"],["Reformulation","Valider la compréhension et créer la confiance"],["Silence utile","Laisser émerger les vrais critères"],["Résumé intermédiaire","Transformer le flou en critères d'accord"]],w:"Ce sont les formulations exactes des notes. Chaque outil a une fonction précise."},
{i:"n153_03",u:153,t:"story",d:.3,q:"Claire vient de répondre « que ce soit sûr ». Que fais-tu ?",sc:[{who:"Claire Vasseur",txt:"Que ce soit sûr."},{who:"Hugo",txt:"(il ouvre la bouche pour parler du fonds euros)"}],o:["Je me tais trois secondes et je la laisse continuer","Je présente immédiatement le fonds euros qui répond à sa demande","Je lui demande si elle préfère un fonds euros ou des obligations","Je lui explique que rien n'est totalement sûr en finance"],a:0,w:"Le silence utile laisse émerger les vrais critères. C'est après ces trois secondes que Claire a parlé de protéger ses enfants."},
{i:"n153_04",u:153,t:"order",d:.3,nw:"La méthode des 4R",q:"Remets les 4R dans l'ordre.",it:["Reprendre les mots exacts du client","Relier besoin, contraintes et objectifs","Reformuler ce que l'on a compris","Revalider avant de conseiller"],w:"Le miroir en 4 temps : les mots tels quels, les liens, l'image entière, puis « c'est bien vous ? »."},
{i:"n153_05",u:153,t:"tf",d:.25,q:"Une question fermée est utile en fin d'entretien pour vérifier ou conclure.",a:true,w:"On ouvre au début pour découvrir, on ferme à la fin pour valider. Les deux ont leur place."},
{i:"n153_06",u:153,t:"fill",d:.3,q:"Revalider, c'est obtenir un « oui, c'est bien ___ » avant de donner un conseil.",o:["cela","possible","signé","compris"],a:0,w:"Tant que le client n'a pas confirmé ta reformulation, tout conseil risque d'être donné à quelqu'un d'autre."},
{i:"n153_07",u:153,t:"story",d:.35,q:"Quelle phrase est une reformulation sans interprétation ?",sc:[{who:"Martine Robin",txt:"Je voudrais qu'on arrête de s'inquiéter pour l'argent une fois à la retraite."}],o:["« Vous souhaitez être sereins financièrement à la retraite. »","« Vous êtes donc très prudents, il vous faut un fonds euros. »","« Vous avez peur de manquer, c'est un signe d'anxiété. »","« Vous voulez un complément de revenus avec des SCPI. »"],a:0,w:"La reformulation redit l'idée du client sans y ajouter de diagnostic ni de produit. Le conseil viendra après la revalidation."},
{i:"n153_08",u:153,t:"mcq",d:.3,q:"Pourquoi valide-t-on la compréhension avant de conseiller ?",o:["Pour que le conseil soit en réelle adéquation avec sa situation","Pour gagner du temps en évitant les questions inutiles","Pour montrer au client qu'on connaît bien les produits","Pour pouvoir facturer le rendez-vous comme du conseil"],a:0,w:"Un conseil bâti sur un malentendu est inadapté, même techniquement parfait. C'est aussi l'exigence d'adéquation."},
{i:"n153_09",u:153,t:"multi",d:.35,q:"Lesquelles sont de vraies questions ouvertes ?",o:["« Comment imaginez-vous les dix prochaines années ? »","« Qu'est-ce qui vous a déçu avec votre ancienne banque ? »","« Dans quelle mesure êtes-vous prêt à voir votre épargne varier ? »","« Vous êtes d'accord pour un PER ? »","« Vous ne voulez quand même pas tout garder sur le livret ? »"],a:[0,1,2],w:"Les trois premières laissent le client libre de sa réponse. Les deux dernières attendent oui ou non, la dernière est même une suggestion déguisée."},
{i:"n153_10",u:153,t:"story",d:.4,q:"Quel résumé intermédiaire fais-tu ?",ctx:"Après vingt minutes, Claire a parlé des études de Léo (prépa l'an prochain), de sa retraite dans une vingtaine d'années, de la transmission, de sa peur de 2020 et de la trésorerie de l'entreprise.",sc:[{who:"Claire Vasseur",txt:"Je me rends compte que je vous ai dit beaucoup de choses en vrac."}],o:["« Je retiens trois critères : disponible pour Léo, sûr, et pensé pour transmettre. »","« Pas de souci, je vous envoie une proposition dès demain matin par e-mail. »","« Vous avez beaucoup de projets, il faudrait sans doute commencer par la retraite. »","« C'est normal, les chefs d'entreprise ont toujours beaucoup de sujets en tête. »"],a:0,w:"Le résumé intermédiaire transforme le flou en critères d'accord. Ces critères serviront ensuite à juger chaque proposition."},
{i:"n153_11",u:153,t:"tiles",d:.35,q:"Reconstitue la définition du silence utile.",a:["Laisser","émerger","les","vrais","critères","de","décision"],dd:["prix","vite","conseiller"],w:"Après une réponse importante, trois secondes de silence poussent le client à compléter : c'est souvent là que vient le vrai critère."},
{i:"n153_12",u:153,t:"sort",d:.4,q:"Classe chaque phrase dans l'étape des 4R qu'elle illustre.",bins:["Reprendre","Relier","Reformuler","Revalider"],it:[["« Vous avez dit : que mes enfants ne manquent de rien. »",0],["« Votre besoin de sécurité est lié à l'avenir de Léo et Inès. »",1],["« Vous voulez protéger vos enfants tout en gardant de la souplesse. »",2],["« C'est bien cela ? »",3]],w:"Reprendre les mots, Relier les éléments, Reformuler l'ensemble, Revalider avant de conseiller."},
{i:"n153_13",u:153,t:"tf",d:.35,q:"« Pourquoi avez-vous tout mis sur un livret ? » est la meilleure formulation pour comprendre un choix passé.",a:false,w:"Ce « pourquoi » peut sonner comme un reproche. « Qu'est-ce qui vous a amené à choisir le livret ? » obtient la même information sans mettre le client sur la défensive."},
{i:"n153_14",u:153,t:"story",d:.4,q:"Transforme la question fermée de Hugo en question ouverte.",sc:[{who:"Hugo",txt:"Kevin, vous voulez une mensualité de 1 200 € ?"}],o:["« Quelle mensualité vous laisserait vivre sereinement chaque mois ? »","« Kevin, vous voulez bien une mensualité de 1 200 € sur 25 ans ? »","« Une mensualité de 1 200 €, ça vous convient, n'est-ce pas ? »","« Vous préférez 1 100 € ou plutôt 1 200 € par mois, alors ? »"],a:0,w:"La version ouverte laisse Kevin dire ce qui compte (vivre sereinement) au lieu de valider un chiffre proposé par le conseiller."},
{i:"n153_15",u:153,t:"slider",d:.35,q:"Combien de secondes de silence conseille-t-on de tenir après une réponse importante du client ?",min:0,max:10,step:1,a:3,tol:1,pre:"",un:" s",w:"Environ trois secondes : assez pour que le client complète, pas assez pour créer un malaise. C'est souvent là que sort le vrai critère."},
{i:"n153_16",u:153,t:"mcq",d:.35,q:"Quel est l'effet principal de la reformulation sur le client ?",o:["Il se sent compris, la confiance s'installe","Il se sent jugé et doit se justifier","Il comprend qu'on veut lui vendre un produit","Il perd patience et veut conclure vite"],a:0,w:"La reformulation valide la compréhension et crée la confiance : le client entend que tu as vraiment écouté."},
{i:"n153_17",u:153,t:"fill",d:.4,q:"Le résumé intermédiaire sert à transformer le ___ du client en critères d'accord.",o:["flou","refus","budget","dossier"],a:0,w:"Le client parle en vrac. Le résumé met de l'ordre : trois critères clairs, qui serviront à juger les propositions."},
{i:"n153_18",u:153,t:"story",d:.45,q:"Rappel du module 1 : Gérard dit « je veux 5 % par an ». Quelle question ouverte poses-tu ?",sc:[{who:"Gérard Robin",txt:"5 % minimum, je ne discute pas."}],o:["« Qu'est-ce que ces 5 % vous permettraient de réaliser ? »","« Vous accepteriez un risque de perte pour obtenir 5 % par an ? »","« 5 % sur quel horizon exactement, cinq ans ou plutôt dix ans ? »","« Vous savez que le fonds euros rapporte environ 2,6 % en ce moment ? »"],a:0,w:"La question ouverte sur l'usage fait passer de la position (5 %) à l'intérêt (un revenu, un projet). Les autres restent au niveau du chiffre."},
{i:"n153_19",u:153,t:"multi",d:.45,q:"Quelles erreurs Hugo commet-il dans sa reformulation ?",ctx:"Kevin a dit : « On veut acheter sans se mettre la corde au cou. »",o:["Il dit : « Vous êtes donc anxieux de nature »","Il ajoute : « Il vous faut une durée de 25 ans »","Il ne demande pas si c'est bien cela","Il reprend l'expression « sans vous mettre la corde au cou »"],a:[0,1,2],w:"Interpréter (anxieux), glisser une solution (25 ans) et oublier de revalider sont trois erreurs. Reprendre les mots exacts du client est au contraire le premier des 4R."},
{i:"n153_20",u:153,t:"num",d:.45,q:"Dans un entretien de 50 minutes, Sylvie recommande que le client parle au moins 70 % du temps. Combien de minutes, au minimum ?",a:35,tol:0,un:" min",h:"70 % de 50",w:"35 minutes de parole pour le client, 15 pour toi. Plus le client parle, plus tu découvres ses intérêts et ses critères de décision."},
{i:"n153_21",u:153,t:"story",d:.45,q:"Claire répond « oui, mais... » à ta reformulation. Que fais-tu ?",sc:[{who:"Toi",me:true,txt:"Vous voulez protéger vos enfants tout en gardant de la souplesse. C'est bien cela ?"},{who:"Claire Vasseur",txt:"Oui, mais... pas seulement les enfants."}],o:["« Dites-m'en plus : qui d'autre voulez-vous protéger ? »","« Très bien, je vous propose donc une assurance-vie pour eux. »","« D'accord, on ajoutera les autres plus tard dans le dossier. »","« C'est noté, passons maintenant aux produits disponibles. »"],a:0,w:"Un « oui, mais » n'est pas une validation. On reprend la découverte jusqu'au « oui, c'est bien cela » franc."},
{i:"n153_22",u:153,t:"tf",d:.45,q:"Reformuler consiste à ajouter son analyse professionnelle à ce qu'a dit le client.",a:false,w:"Reformuler, c'est redire sans interpréter. L'analyse et le conseil viennent après la revalidation."},
{i:"n153_23",u:153,t:"match",d:.45,q:"Associe chaque moment de l'entretien au type de question le plus adapté.",p:[["Début de l'entretien","Questions ouvertes pour découvrir"],["Après une réponse forte","Silence utile"],["Milieu de l'entretien","Résumé intermédiaire"],["Avant le conseil","Question fermée de revalidation"]],w:"On ouvre, on laisse parler, on résume, on fait valider. Puis seulement on conseille."},
{i:"n153_24",u:153,t:"story",d:.5,q:"Rappel du module 4 : pendant l'écoute, Claire exprime une objection. Laquelle ?",sc:[{who:"Claire Vasseur",txt:"J'ai l'impression que les banques pensent d'abord à leurs objectifs avant les miens."}],o:["La confiance","La liquidité","La fiscalité","Les frais"],a:0,w:"L'annulaire qui porte l'alliance : la confiance. Elle se traite par la transparence et une vraie écoute, pas par un argument produit."},
{i:"n153_25",u:153,t:"tiles",d:.5,q:"Reconstitue la règle du miroir.",a:["Un","conseil","donné","avant","le","oui","est","donné","à","quelqu'un","d'autre"],dd:["toujours","client","prix"],w:"Sans revalidation, tu conseilles l'image que tu te fais du client, pas le client lui-même."},
{i:"n153_26",u:153,t:"mcq",d:.5,q:"Quelle phrase est une fausse question ouverte ?",o:["« Vous ne pensez pas qu'un PER serait idéal ? »","« Qu'est-ce qui compte pour vous à la retraite ? »","« Comment voyez-vous la transmission à vos enfants ? »","« Qu'est-ce qui vous a amené à nous consulter ? »"],a:0,w:"« Vous ne pensez pas que... » oriente la réponse vers oui : c'est une suggestion déguisée en question."},
{i:"n153_27",u:153,t:"story",d:.5,q:"Quelle attitude montre une écoute active ?",sc:[{who:"Laura",txt:"Et j'aimerais pouvoir arrêter deux ans quand on aura un enfant."},{who:"Hugo",txt:"(il regarde son écran et tape la simulation)"}],o:["Regarder Laura, noter ses mots et lui demander ce que cela implique pour eux","Continuer la simulation pour gagner du temps et lui répondre à la fin","Lui dire qu'on verra ça plus tard, une fois le prêt accordé par la banque","Lui répondre que c'est risqué d'arrêter de travailler avec un crédit en cours"],a:0,w:"L'écoute active est aussi physique : regard, prise de notes, question de relance. Taper sur son écran dit au client que sa parole compte moins que le produit."},
{i:"n153_28",u:153,t:"fill",d:.5,q:"Relier, c'est relier le besoin, les contraintes et les ___ du client.",o:["objectifs","produits","revenus","documents"],a:0,w:"Deuxième R : on montre au client que ses éléments forment un tout (besoin de sécurité, contrainte de trésorerie, objectif de transmission)."},
{i:"n153_29",u:153,t:"order",d:.5,q:"Remets dans l'ordre le déroulé de l'entretien avec Claire.",it:["Question ouverte sur ce qui est important","Silence utile après sa réponse","Résumé intermédiaire en trois critères","Reformulation puis revalidation","Premier conseil"],w:"Découvrir, laisser émerger, structurer, faire valider, puis conseiller. Jamais le conseil avant le « oui, c'est bien cela »."},
{i:"n153_30",u:153,t:"story",d:.55,q:"Rappel du module 2 : pendant ton écoute, Kevin laisse échapper une information. Que représente-t-elle ?",sc:[{who:"Kevin",txt:"De toute façon, la banque de mes parents nous a déjà fait une offre à 3,30 %."}],o:["Sa MESORE : une alternative réelle qui fixe sa limite chez vous","Son point cible : le taux qu'il espère obtenir dans votre agence","Sa ZOPA : la zone dans laquelle il acceptera forcément de signer","Une objection de confiance envers votre agence et vos conseillers"],a:0,w:"Une offre écrite ailleurs est une MESORE. L'écoute active sert aussi à repérer ces informations stratégiques."},
{i:"n153_31",u:153,t:"tf",d:.55,q:"Un client qui répond « oui, mais » à une reformulation a validé ta compréhension.",a:false,w:"« Oui, mais » signale un élément manquant. On relance jusqu'au « oui, c'est bien cela » sans réserve."},
{i:"n153_32",u:153,t:"multi",d:.55,q:"Quels signes montrent que ton résumé intermédiaire a réussi ?",o:["Le client ajoute « et aussi... » puis complète","Le client dit « c'est exactement ça »","Le client commence à comparer tes propositions à ses critères","Le client regarde sa montre","Le client répète sa position initiale mot pour mot"],a:[0,1,2],w:"Un bon résumé fait réagir, valider, puis sert d'étalon. Regarder sa montre ou répéter sa position signale que tu n'as pas saisi le vrai critère."}
