/*UNIT*/
{id:154,c:"NEGO",n:"Module 6",t:"SPIN : amener le client à formuler lui-même l'enjeu",col:"--blue",ic:"🌀",guide:`
<h3>Gérard n'avait pas de problème. Jusqu'à la troisième question.</h3>
<div class="gstory">Gérard Robin s'est calé au fond du fauteuil, bras croisés : « On vient par politesse, hein. La retraite, c'est dans trois ans, on a nos livrets, tout va bien. » Tu ne proposes rien. Tu demandes combien il gagne aujourd'hui (3 500 € net par mois) et ce que lui promet son relevé de carrière (2 100 €). Puis : « Qu'est-ce qui changerait pour vous avec 1 400 € de moins chaque mois ? » Silence. Martine répond à sa place : « Le camping-car. Et l'aide pour les études des petits. » Gérard décroise les bras. « Et vous auriez quoi, pour combler ça ? » Ce n'est plus toi qui vends. C'est lui qui demande.</div>
<h3>La méthode SPIN</h3>
<p>Créée par <b>Neil Rackham</b> (Huthwaite, livre <i>SPIN Selling</i>, 1988) après l'analyse de <b>35 000 entretiens de vente</b> dans 23 pays pendant douze ans. Sa découverte : dans les ventes complexes, les meilleurs vendeurs ne parlent pas plus, ils posent de meilleures questions, dans un ordre précis.</p>
<table><tr><th>Lettre</th><th>Type de question</th><th>But (selon les notes)</th><th>Exemple avec les Robin</th></tr>
<tr><td><b>S</b></td><td>Situation</td><td>Comprendre le contexte patrimonial</td><td>« Quels sont vos revenus et votre date de départ ? »</td></tr>
<tr><td><b>P</b></td><td>Problème</td><td>Faire émerger les insatisfactions ou les risques</td><td>« Qu'est-ce qui vous préoccupe dans ce passage à la retraite ? »</td></tr>
<tr><td><b>I</b></td><td>Implication</td><td>Mesurer les conséquences si rien ne change</td><td>« Que deviendraient vos projets avec 1 400 € de moins par mois ? »</td></tr>
<tr><td><b>N</b></td><td>Need-payoff</td><td>Faire formuler la valeur attendue par le client</td><td>« Qu'est-ce que ça vous apporterait de garder votre niveau de vie ? »</td></tr></table>
<div class="formula">Le client achète mieux quand il a formulé lui-même l'enjeu.</div>
<div class="gmnemo"><b>La consultation du médecin.</b> <b>S</b> : « Racontez-moi votre quotidien » (l'anamnèse). <b>P</b> : « Où avez-vous mal ? ». <b>I</b> : « Si on ne soigne pas, qu'est-ce qui risque d'arriver ? ». <b>N</b> : « Qu'est-ce que la guérison changerait pour vous ? ». Aucun bon médecin ne prescrit avant d'avoir posé ces quatre questions. Aucun bon conseiller non plus.</div>
<h3>Ce que Rackham a mesuré</h3>
<ul><li>Les vendeurs moyens posent surtout des questions de <b>Situation</b> : elles ennuient le client et ne lui apportent rien. Prépare la situation à l'avance (fiche client, documents) pour en poser peu.</li>
<li>Les meilleurs posent beaucoup de questions d'<b>Implication</b> et de <b>Need-payoff</b> : ce sont elles qui transforment un petit souci en besoin clair.</li>
<li>Une question <b>Need-payoff</b> fait dire au client lui-même le bénéfice de la solution. Un bénéfice qu'il a formulé vaut mieux que dix arguments que tu lui assènes.</li></ul>
<div class="gtrap">Erreur fréquente : sauter de P à la solution. Claire dit « j'ai peur pour la trésorerie » et Hugo propose aussitôt une assurance-vie. Il a oublié l'Implication (que se passerait-il concrètement ?) et le Need-payoff (qu'est-ce qu'une réserve disponible vous apporterait ?). Le client entend alors une vente, pas une solution. Autre piège : une question d'Implication doit rester honnête. Exagérer les risques pour faire peur, c'est de la manipulation, et c'est contraire au devoir de conseil.</div>
<h3>SPIN et patrimoine : quatre exemples prêts à l'emploi</h3>
<table><tr><th>Thème</th><th>Question d'implication</th><th>Question need-payoff</th></tr>
<tr><td>Retraite</td><td>« Sur vingt-cinq ans de retraite, que représente cet écart ? »</td><td>« Que feriez-vous d'un complément régulier ? »</td></tr>
<tr><td>Transmission</td><td>« Si rien n'est organisé, qu'arriverait-il à vos enfants ? »</td><td>« Qu'est-ce que ça vous apporterait de savoir que c'est réglé ? »</td></tr>
<tr><td>Fiscalité</td><td>« Combien d'impôt payez-vous chaque année sur ces revenus ? »</td><td>« Que feriez-vous de l'impôt économisé ? »</td></tr>
<tr><td>Protection</td><td>« Si vous ne pouviez plus travailler, comment ferait la famille ? »</td><td>« En quoi une protection vous rassurerait-elle ? »</td></tr></table>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Dire ce que signifie chaque lettre et donner son but exact</li><li>Classer une question dans la bonne lettre</li><li>Écrire une question d'implication et une question need-payoff sur un cas</li><li>Expliquer pourquoi le client doit formuler lui-même l'enjeu</li><li>Citer l'auteur et l'origine de la méthode</li></ul>`},
/*EXOS*/
{i:"n154_01",u:154,t:"order",d:.25,nw:"La méthode SPIN",q:"Remets les questions SPIN dans l'ordre.",it:["Situation","Problème","Implication","Need-payoff"],w:"La consultation du médecin : votre quotidien, où avez-vous mal, que risque-t-il d'arriver, que changerait la guérison."},
{i:"n154_02",u:154,t:"match",d:.3,q:"Associe chaque lettre à son but.",p:[["Situation","Comprendre le contexte patrimonial"],["Problème","Faire émerger les insatisfactions ou risques"],["Implication","Mesurer les conséquences si rien ne change"],["Need-payoff","Faire formuler la valeur attendue par le client"]],w:"Ce sont les formulations exactes des notes, à connaître mot pour mot."},
{i:"n154_03",u:154,t:"sort",d:.35,q:"Classe chaque question dans la bonne lettre SPIN.",bins:["S","P","I","N"],it:[["« Quel âge ont vos enfants ? »",0],["« Qu'est-ce qui vous inquiète dans votre épargne actuelle ? »",1],["« Si rien ne change, où en serez-vous dans dix ans ? »",2],["« Qu'est-ce que ça vous apporterait d'être serein ? »",3],["« Quel est votre régime matrimonial ? »",0],["« Qu'est-ce qui vous déplaît dans votre contrat ? »",1]],w:"S : les faits. P : ce qui ne va pas. I : les conséquences. N : le bénéfice formulé par le client."},
{i:"n154_04",u:154,t:"fill",d:.3,q:"Le client achète mieux quand il a ___ lui-même l'enjeu.",o:["formulé","compris","signé","accepté"],a:0,w:"C'est le principe de SPIN : un bénéfice dit par le client vaut plus que tous tes arguments."},
{i:"n154_05",u:154,t:"mcq",d:.3,q:"Qui a créé la méthode SPIN ?",o:["Neil Rackham","Roger Fisher","William Ury","Daniel Kahneman"],a:0,w:"Neil Rackham, Huthwaite, SPIN Selling (1988), à partir de 35 000 entretiens de vente analysés. Fisher et Ury sont les auteurs de la négociation raisonnée."},
{i:"n154_06",u:154,t:"story",d:.35,q:"Quelle est la meilleure question d'implication pour Gérard ?",sc:[{who:"Gérard Robin",txt:"Je gagne 3 500 € net, ma retraite sera de 2 100 €. Bon, on s'adaptera."}],o:["« Qu'est-ce qui changerait pour vous avec 1 400 € de moins chaque mois ? »","« Voulez-vous ouvrir un PER pour compenser la baisse de vos revenus ? »","« À quelle date exacte avez-vous prévu de partir à la retraite, Gérard ? »","« Avez-vous déjà pensé à investir dans des SCPI de rendement ? »"],a:0,w:"L'implication fait mesurer les conséquences si rien ne change. Les autres questions sont une proposition, une question de situation, ou une vente déguisée."},
{i:"n154_07",u:154,t:"num",d:.35,q:"Gérard gagne 3 500 € net par mois et touchera 2 100 € de retraite. De quel pourcentage ses revenus baisseront-ils ?",a:40,tol:.5,un:" %",h:"Écart divisé par le revenu actuel",w:"1 400 / 3 500 = 40 %. Chiffrer l'écart rend la question d'implication concrète."},
{i:"n154_08",u:154,t:"tf",d:.3,q:"Selon Rackham, les meilleurs vendeurs posent surtout des questions de situation.",a:false,w:"C'est l'inverse : les vendeurs moyens abusent des questions de situation, qui ennuient le client. Les meilleurs posent davantage de questions d'implication et de need-payoff."},
{i:"n154_09",u:154,t:"story",d:.4,q:"Quelle question need-payoff poses-tu à Martine ?",sc:[{who:"Martine Robin",txt:"Ce qui m'embête, c'est de ne plus pouvoir aider nos petits-enfants pour leurs études."}],o:["« Qu'est-ce que ça représenterait pour vous de pouvoir les aider ? »","« Combien de petits-enfants avez-vous exactement, et de quel âge ? »","« Si vous ne les aidez pas, pensez-vous qu'ils pourront étudier ? »","« Je peux vous proposer un contrat d'épargne dédié pour eux. »"],a:0,w:"La question need-payoff fait formuler la valeur attendue : c'est Martine qui dit ce que la solution lui apporterait."},
{i:"n154_10",u:154,t:"multi",d:.4,q:"Lesquelles sont des questions d'implication ?",o:["« Sur vingt-cinq ans de retraite, que représente cet écart ? »","« Si rien n'est organisé, qu'arriverait-il à vos enfants ? »","« Que se passerait-il si l'entreprise avait un coup dur l'an prochain ? »","« Où êtes-vous domicilié fiscalement ? »","« Qu'est-ce qu'un complément régulier vous apporterait ? »"],a:[0,1,2],w:"L'implication mesure les conséquences si rien ne change. La domiciliation est une question de situation, la dernière est une need-payoff."},
{i:"n154_11",u:154,t:"tiles",d:.35,q:"Reconstitue le principe de la méthode SPIN.",a:["Le","client","achète","mieux","quand","il","a","formulé","lui-même","l'enjeu"],dd:["vendeur","toujours","prix"],w:"C'est la phrase des notes. Ton rôle : poser les questions qui l'amènent à dire l'enjeu."},
{i:"n154_12",u:154,t:"story",d:.4,q:"Quelle est l'erreur de Hugo ?",sc:[{who:"Claire Vasseur",txt:"J'ai peur de manquer de trésorerie pour l'entreprise."},{who:"Hugo",txt:"Alors je vous propose une assurance-vie avec une poche disponible !"}],o:["Il est passé du problème à la solution sans implication ni need-payoff","Il aurait dû poser d'abord une question sur la situation fiscale de Claire","Il aurait dû proposer un produit plus rentable qu'une assurance-vie","Il aurait dû laisser Claire proposer elle-même un produit précis"],a:0,w:"Sauter I et N, c'est vendre trop tôt. Il fallait demander ce qui se passerait sans réserve, puis ce qu'une réserve disponible lui apporterait."},
{i:"n154_13",u:154,t:"mcq",d:.35,q:"Pourquoi faut-il préparer les informations de situation avant le rendez-vous ?",o:["Pour poser peu de questions de situation, qui lassent le client","Pour pouvoir sauter complètement toutes les questions de problème","Pour éviter d'avoir à reformuler ce que dit le client","Pour présenter les produits dès la première minute"],a:0,w:"Rackham l'a mesuré : trop de questions de situation ennuient. La fiche client et les documents permettent d'en poser peu et d'aller vers P, I et N."},
{i:"n154_14",u:154,t:"slider",d:.4,q:"Sur combien d'entretiens de vente la recherche de Rackham s'est-elle appuyée (en milliers) ?",min:5,max:100,step:5,a:35,tol:0,pre:"",un:" 000",w:"35 000 entretiens, dans 23 pays, sur douze ans : la plus grande étude empirique de l'efficacité commerciale. D'où la solidité de la méthode."},
{i:"n154_15",u:154,t:"story",d:.45,q:"Quelle question de problème ouvre le mieux la discussion avec Marc ?",sc:[{who:"Marc Delorme",txt:"Mon contrat ? Il tourne, je ne le regarde jamais."}],o:["« Qu'est-ce qui vous satisfait le moins dans la façon dont il est géré ? »","« Depuis combien d'années exactement l'avez-vous ouvert ici, chez nous ? »","« Si vous ne le regardez jamais, que risquez-vous à la retraite ? »","« Je vous propose d'arbitrer vers notre fonds le plus performant. »"],a:0,w:"La question de problème fait émerger une insatisfaction. La deuxième est une situation, la troisième une implication (trop tôt), la dernière une vente."},
{i:"n154_16",u:154,t:"tf",d:.4,q:"Exagérer les risques dans une question d'implication pour faire peur au client est une bonne technique SPIN.",a:false,w:"L'implication doit rester honnête. Dramatiser pour vendre est de la manipulation et viole le devoir de conseil."},
{i:"n154_17",u:154,t:"fill",d:.45,q:"La lettre I de SPIN mesure les conséquences si ___ ne change.",o:["rien","tout","le client","la loi"],a:0,w:"Implication : si rien ne change, que se passe-t-il ? C'est ce qui transforme un petit souci en besoin clair."},
{i:"n154_18",u:154,t:"sort",d:.45,q:"Classe chaque question sur la transmission de Claire.",bins:["Situation","Problème","Implication","Need-payoff"],it:[["« Êtes-vous mariée, et sous quel régime ? »",0],["« Qu'est-ce qui vous préoccupe dans la transmission ? »",1],["« Si rien n'est prévu, que deviendrait l'entreprise ? »",2],["« Que vous apporterait une transmission déjà organisée ? »",3]],w:"Même thème, quatre niveaux. Le médecin : votre quotidien, où avez-vous mal, que risque-t-il d'arriver, que changerait la guérison."},
{i:"n154_19",u:154,t:"story",d:.45,q:"Rappel du module 5 : Martine vient de répondre à ta question need-payoff. Que fais-tu ?",sc:[{who:"Martine Robin",txt:"Ce serait... un vrai soulagement. On pourrait enfin profiter sans compter."}],o:["Je reformule son bénéfice et je lui fais valider","Je présente tout de suite un PER et une SCPI","Je lui demande son âge et celui de Gérard, pour la fiche","Je passe à un autre sujet pour ne pas insister"],a:0,w:"Un bénéfice formulé se reformule et se revalide (4R). Il deviendra un critère d'accord pour juger ta proposition."},
{i:"n154_20",u:154,t:"multi",d:.5,q:"Quelles questions sont de vraies need-payoff ?",o:["« En quoi une protection vous rassurerait-elle ? »","« Que feriez-vous de l'impôt économisé ? »","« Qu'est-ce que ça changerait de savoir que c'est réglé ? »","« Si vous ne pouviez plus travailler, comment ferait la famille ? »","« Vous voulez que je vous montre notre offre prévoyance ? »"],a:[0,1,2],w:"Need-payoff : le client formule lui-même la valeur. La quatrième est une implication, la cinquième une proposition fermée."},
{i:"n154_21",u:154,t:"match",d:.5,q:"Associe chaque étape SPIN à la question du médecin.",p:[["Situation","« Racontez-moi votre quotidien »"],["Problème","« Où avez-vous mal ? »"],["Implication","« Si on ne soigne pas, que risque-t-il d'arriver ? »"],["Need-payoff","« Que changerait la guérison pour vous ? »"]],w:"Aucun bon médecin ne prescrit avant ces quatre questions. Aucun bon conseiller non plus."},
{i:"n154_22",u:154,t:"story",d:.5,q:"Quelle question d'implication poses-tu à Kevin ?",ctx:"Kevin et Laura veulent emprunter sans assurance décès-invalidité sur la tête de Laura, pour réduire la mensualité.",sc:[{who:"Kevin",txt:"Laura gagne moins, on l'assure à 0 %, ça fait 30 € d'économie par mois."}],o:["« Si Laura ne pouvait plus travailler, comment rembourseriez-vous seul ? »","« Combien Laura gagne-t-elle exactement chaque mois, en net ? »","« Vous voulez que je vous montre plutôt notre offre d'assurance emprunteur ? »","« 30 € d'économie par mois, ça fait 9 000 € sur vingt-cinq ans. »"],a:0,w:"L'implication fait mesurer les conséquences. Ici, l'enjeu est la capacité à rembourser si Laura a un accident. La question de salaire est une situation, les autres sont des arguments."},
{i:"n154_23",u:154,t:"tf",d:.5,q:"La méthode SPIN a été conçue surtout pour les ventes complexes, où la décision engage beaucoup.",a:true,w:"Rackham a étudié les grandes ventes, longues et à enjeu. C'est exactement le cas d'un conseil patrimonial : placement, retraite, transmission."},
{i:"n154_24",u:154,t:"mcq",d:.5,q:"Rappel du module 1 : que révèlent souvent les questions de problème et d'implication ?",o:["Les intérêts cachés derrière la position","Le point de réserve réel de la banque","La commission exacte du conseiller","Le produit le plus rentable du moment"],a:0,w:"Ce que le client ne voit pas encore de lui-même : ses intérêts réels. La position de Gérard (« tout va bien ») cachait un intérêt fort (garder son niveau de vie)."},
{i:"n154_25",u:154,t:"num",d:.55,q:"Gérard perd 1 400 € par mois à la retraite. Sur 25 ans de retraite, quel est l'écart total, en euros ?",a:420000,tol:1,un:" €",h:"Mensuel × 12 × 25",w:"1 400 × 12 × 25 = 420 000 €. C'est une question d'implication chiffrée : l'écart paraît soudain beaucoup plus concret que « on s'adaptera »."},
{i:"n154_26",u:154,t:"tiles",d:.5,q:"Reconstitue le rôle de la question need-payoff.",a:["Faire","formuler","la","valeur","attendue","par","le","client"],dd:["vendeur","prix","imposer"],w:"C'est le client qui dit la valeur. Toi, tu poses la question."},
{i:"n154_27",u:154,t:"story",d:.55,q:"Rappel du module 4 : pendant le SPIN, Claire soulève une objection. Laquelle ?",sc:[{who:"Claire Vasseur",txt:"Et si je bloque cet argent, et que l'atelier a besoin de 80 000 € du jour au lendemain ?"}],o:["La liquidité","La confiance","La fiscalité","Les frais"],a:0,w:"Récupérer l'argent vite : liquidité (le majeur). Ta réponse préparée : délais de rachat, poche disponible, avance sur contrat."},
{i:"n154_28",u:154,t:"order",d:.55,q:"Remets dans l'ordre l'entretien avec Gérard.",it:["Revenus actuels et montant de la retraite","Ce qui le préoccupe dans ce passage","Ce que 1 400 € de moins changeraient","Ce que garder son niveau de vie lui apporterait","Reformulation et proposition"],w:"S, P, I, N, puis 4R et proposition. C'est Gérard qui a fini par demander une solution."},
{i:"n154_29",u:154,t:"fill",d:.55,q:"Les questions de ___ sont celles qui ennuient le plus le client quand elles sont trop nombreuses.",o:["situation","problème","implication","need-payoff"],a:0,w:"Elles ne lui apportent rien : il connaît déjà sa situation. Prépare-les avec la fiche client pour en poser peu."},
{i:"n154_30",u:154,t:"story",d:.6,q:"Quelle phrase de Gérard montre que SPIN a fonctionné ?",sc:[{who:"Gérard Robin",txt:"..."}],o:["« Et vous auriez quoi, vous, pour combler cet écart ? »","« Bon, on reviendra vous voir quand on sera à la retraite. »","« On a nos livrets, ça ira bien pour nous deux. »","« Vous allez encore essayer de nous vendre quelque chose. »"],a:0,w:"Quand le client demande lui-même une solution, c'est qu'il a formulé l'enjeu. Tu n'as plus à vendre : tu réponds à une demande."},
{i:"n154_31",u:154,t:"multi",d:.6,q:"Quels bénéfices la méthode SPIN apporte-t-elle au conseiller ?",o:["Le client s'approprie le besoin","Les objections diminuent","La solution répond à un enjeu formulé","Le conseiller parle plus longtemps","On évite la découverte client"],a:[0,1,2],w:"Un besoin formulé par le client réduit les objections et justifie la solution. SPIN ne fait pas parler plus le conseiller et ne remplace pas la découverte."},
{i:"n154_32",u:154,t:"tf",d:.6,q:"Dans SPIN, « Need-payoff » signifie que le conseiller explique au client les bénéfices du produit.",a:false,w:"Justement non : c'est le client qui formule la valeur attendue, en réponse à ta question. Si c'est toi qui l'expliques, c'est un argument, pas une need-payoff."}
