/*UNIT*/
{id:156,c:"NEGO",n:"Module 8",t:"Objections : accueillir, clarifier, traiter, valider",col:"--blue",ic:"🛡️",guide:`
<h3>« Vos frais sont trop élevés »</h3>
<div class="gstory">Troisième rendez-vous avec Marc Delorme. Tu as préparé ta proposition. À peine as-tu posé le document qu'il tapote la ligne des frais : « 0,75 %. Toujours trop cher. » Hugo, qui assiste, se penche et commence : « Mais monsieur, c'est parce que... » Tu l'arrêtes d'un regard. Tu te tournes vers Marc : « Je comprends que ce chiffre vous saute aux yeux. Quand vous dites trop cher, vous comparez à quoi exactement ? » Marc hésite. « En fait... à ce que mon confrère paie. Et je ne sais même pas ce qu'il a comme services. » L'objection vient de changer de nature : ce n'était pas le prix, c'était l'inquiétude de s'être fait avoir.</div>
<h3>Les quatre temps du traitement d'une objection</h3>
<table><tr><th>Temps</th><th>Ce que tu fais</th><th>Ce que tu dis</th></tr>
<tr><td><b>1. Accueillir</b></td><td>Recevoir l'objection sans te défendre</td><td>« Je comprends votre point de vue. »</td></tr>
<tr><td><b>2. Clarifier</b></td><td>Distinguer objection réelle, prétexte ou inquiétude</td><td>« Qu'est-ce qui vous fait dire cela ? », « Par rapport à quoi ? »</td></tr>
<tr><td><b>3. Traiter</b></td><td>Répondre avec une preuve, un exemple ou un compromis</td><td>« Voici le rendement net comparé, chiffres à l'appui. »</td></tr>
<tr><td><b>4. Valider</b></td><td>Vérifier que la réponse a porté</td><td>« Est-ce que cela répond à votre préoccupation ? »</td></tr></table>
<div class="gmnemo"><b>A.C.T.V. : « Avant Chaque Traitement, Vérifie ».</b> Accueillir, Clarifier, Traiter, Valider. Et l'image du <b>colis</b> : tu <b>Acceptes</b> le colis sans le jeter, tu <b>Contrôles</b> ce qu'il y a dedans, tu <b>Traites</b> son contenu, tu fais <b>Valider</b> la livraison par une signature.</div>
<div class="gtrap">Les notes écrivent « Clairifier » : c'est <b>clarifier</b>. Autre piège : « je comprends votre point de vue » ne veut pas dire « je suis d'accord ». On accueille l'émotion, pas forcément le fond. Et on évite le <b>« mais »</b> juste après (« je comprends, mais... ») : il efface tout ce qui précède. On dit « je comprends, <b>et</b>... » ou on enchaîne sur une question.</div>
<h3>Clarifier : trois natures d'objection</h3>
<table><tr><th>Nature</th><th>Comment la reconnaître</th><th>Comment la traiter</th></tr>
<tr><td><b>Réelle</b></td><td>Précise, argumentée, répétée</td><td>Preuve, exemple, compromis</td></tr>
<tr><td><b>Prétexte</b></td><td>Vague, change à chaque réponse (« je dois réfléchir », « pas le temps »)</td><td>Chercher le vrai motif : « Qu'est-ce qui vous retient vraiment ? »</td></tr>
<tr><td><b>Inquiétude</b></td><td>Posée sous forme de question, avec de l'émotion (« et si... ? »)</td><td>Rassurer avec des faits, des scénarios, des garanties</td></tr></table>
<p>Une astuce pour démasquer un prétexte : <b>isoler l'objection</b>. « Si on règle la question des frais, y a-t-il autre chose qui vous empêcherait d'avancer ? » Si le client sort une nouvelle objection, la première n'était pas la vraie.</p>
<h3>Traiter : preuve, exemple, compromis</h3>
<ul><li><b>Preuve</b> : un chiffre vérifiable, un document, une simulation (le C.P.A.P. du module 4).</li>
<li><b>Exemple</b> : un cas client anonymisé, une situation concrète. « Un client dans votre cas a... »</li>
<li><b>Compromis</b> : un ajustement qui ne sacrifie pas l'essentiel, toujours contre une contrepartie (module 9).</li></ul>
<h3>La meilleure réponse à « vos frais sont trop élevés »</h3>
<p>Démontrer qu'on va lui <b>apporter de la valeur</b>. Pas justifier le prix, pas céder tout de suite : montrer ce que les frais achètent (rendement net, conseil, suivi, fiscalité, transmission) et le comparer à un critère objectif. Si la valeur perçue dépasse le prix, l'objection tombe d'elle-même.</p>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Dérouler les quatre temps sur un cas</li><li>Reconnaître une objection réelle, un prétexte, une inquiétude</li><li>Donner la phrase d'accueil et la question de validation</li><li>Répondre à « vos frais sont trop élevés » par la valeur</li></ul>`},
/*EXOS*/
{i:"n156_01",u:156,t:"order",d:.25,nw:"Traiter une objection",q:"Remets dans l'ordre les quatre temps du traitement d'une objection.",it:["Accueillir sans se défendre","Clarifier sa nature","Traiter avec preuve, exemple ou compromis","Valider que la réponse convient"],w:"A.C.T.V. : Avant Chaque Traitement, Vérifie. Ou le colis : accepter, contrôler, traiter, faire signer."},
{i:"n156_02",u:156,t:"story",d:.3,q:"Quelle est ta première réponse à Marc ?",sc:[{who:"Marc Delorme",txt:"0,75 %. Toujours trop cher."},{who:"Hugo",txt:"Mais monsieur, c'est parce que..."}],o:["« Je comprends que ce chiffre vous saute aux yeux. Vous comparez à quoi ? »","« Mais enfin, c'est déjà une grosse remise par rapport à nos 0,85 % habituels ! »","« Tous les clients paient ce tarif, nous ne pouvons pas faire d'exception pour vous. »","« D'accord, je peux descendre à 0,70 % si vous signez la proposition aujourd'hui. »"],a:0,w:"Accueillir puis clarifier. Se défendre (« mais ») ou céder tout de suite saute les deux premiers temps."},
{i:"n156_03",u:156,t:"sort",d:.3,nw:"Réelle, prétexte ou inquiétude",q:"Classe chaque objection selon sa nature probable.",bins:["Réelle","Prétexte","Inquiétude"],it:[["« Vos frais sont 0,25 point au-dessus de l'offre écrite que j'ai reçue »",0],["« Je dois réfléchir » (sans autre précision)",1],["« Et si la Bourse s'effondre juste après ? »",2],["« Je n'ai pas le temps en ce moment »",1],["« Et si j'ai besoin de l'argent pour mon entreprise ? »",2],["« Votre contrat n'a pas de gestion pilotée, j'en veux une »",0]],w:"Réelle : précise et argumentée. Prétexte : vague et changeant. Inquiétude : une question chargée d'émotion (« et si... ? »)."},
{i:"n156_04",u:156,t:"fill",d:.3,q:"Pour valider, on demande : « Est-ce que cela répond à votre ___ ? »",o:["préoccupation","demande de remise","signature","budget"],a:0,w:"C'est la question des notes. Sans validation, tu ne sais pas si l'objection est réglée ou si elle reviendra au moment de signer."},
{i:"n156_05",u:156,t:"tf",d:.25,q:"Dire « je comprends votre point de vue » signifie qu'on est d'accord avec le client.",a:false,w:"On accueille le ressenti, pas forcément le fond. On peut comprendre que les frais paraissent élevés sans admettre qu'ils le sont."},
{i:"n156_06",u:156,t:"mcq",d:.3,q:"Quelle est la meilleure réponse de fond à « vos frais sont trop élevés » ?",o:["Démontrer la valeur apportée","Accorder une remise immédiate","Rappeler les tarifs officiels","Comparer avec une banque plus chère"],a:0,w:"Le mot-clé de l'évaluation : la valeur. Si la valeur perçue dépasse le prix, l'objection tombe."},
{i:"n156_07",u:156,t:"story",d:.35,q:"Comment démasques-tu un prétexte ?",sc:[{who:"Claire Vasseur",txt:"C'est intéressant, mais je dois réfléchir."}],o:["« Bien sûr. Qu'est-ce qui vous fait encore hésiter, concrètement ? »","« Très bien, je vous rappelle dans quinze jours pour faire le point. »","« Il faut vite vous décider, les conditions peuvent changer bientôt. »","« Réfléchir à quoi ? Tout est clair dans ma proposition, je crois. »"],a:0,w:"« Je dois réfléchir » est souvent un prétexte. Une question ouverte bienveillante fait apparaître le vrai motif. Presser le client ou le contredire le braque."},
{i:"n156_08",u:156,t:"multi",d:.35,q:"Avec quoi peut-on traiter une objection réelle ?",o:["Une preuve chiffrée","Un exemple concret","Un compromis avec contrepartie","Une promesse orale de rendement","Un changement de sujet"],a:[0,1,2],w:"Preuve, exemple, compromis : les trois outils des notes. Promettre un rendement est interdit ; changer de sujet laisse l'objection intacte."},
{i:"n156_09",u:156,t:"tiles",d:.3,q:"Reconstitue la phrase d'accueil des notes.",a:["Je","comprends","votre","point","de","vue"],dd:["mais","accord","prix"],w:"Accueillir sans se défendre. Et surtout pas de « mais » juste après."},
{i:"n156_10",u:156,t:"story",d:.4,q:"Martine s'inquiète. Comment traites-tu son objection ?",sc:[{who:"Martine Robin",txt:"Et si l'assureur fait faillite ? On perd tout ?"}],o:["« Le FGAP garantit jusqu'à 70 000 € par assuré et par assureur ; on peut répartir. »","« Aucun assureur français n'a jamais fait faillite, vous n'avez rien à craindre. »","« Ça n'arrivera pas, je vous le garantis personnellement, faites-moi confiance. »","« C'est un risque qui existe, on ne peut rien y faire, c'est comme ça. »"],a:0,w:"Une inquiétude se traite avec des faits : la garantie du FGAP et la répartition entre assureurs. Les promesses et les affirmations fausses détruisent la confiance."},
{i:"n156_11",u:156,t:"tf",d:.3,q:"Il vaut mieux éviter de dire « je comprends, mais... » car le « mais » efface ce qui précède.",a:true,w:"« Je comprends, et... » ou une question de clarification gardent l'accueil intact."},
{i:"n156_12",u:156,t:"match",d:.35,q:"Associe chaque nature d'objection à son traitement.",p:[["Objection réelle","Preuve, exemple ou compromis"],["Prétexte","Chercher le vrai motif"],["Inquiétude","Rassurer avec des faits"],["Objection multiple","Isoler la principale"]],w:"On ne traite pas un prétexte comme une objection réelle : on perdrait son temps à répondre à un faux problème."},
{i:"n156_13",u:156,t:"story",d:.4,q:"Quelle question isole l'objection de Kevin ?",sc:[{who:"Kevin",txt:"Votre assurance emprunteur est trop chère."}],o:["« Si on règle l'assurance, y a-t-il autre chose qui vous retient ? »","« Notre assurance est la plus complète du marché, croyez-moi bien. »","« Vous pouvez prendre une assurance ailleurs, c'est votre droit. »","« Combien vous propose-t-on exactement dans l'autre banque ? »"],a:0,w:"Isoler, c'est vérifier que c'est la seule objection. Si Kevin en sort une autre, l'assurance n'était pas le vrai frein."},
{i:"n156_14",u:156,t:"fill",d:.35,q:"Les notes écrivent « Clairifier » ; le bon mot est ___.",o:["clarifier","qualifier","clôturer","certifier"],a:0,w:"Clarifier : comprendre si l'objection est réelle, un prétexte ou une inquiétude."},
{i:"n156_15",u:156,t:"num",d:.4,q:"Pour traiter l'objection de Marc, tu montres que le conseil lui fait gagner 0,40 % de rendement net par an grâce à une meilleure allocation, pour 0,15 % de frais en plus que NeoBanque. Sur 120 000 €, quel est son gain net annuel, en euros ?",a:300,tol:1,un:" €",h:"(0,40 % − 0,15 %) × 120 000",w:"0,25 % × 120 000 = 300 € par an. C'est une preuve de valeur : les frais sont plus que compensés. Ce calcul doit reposer sur des hypothèses honnêtes et présentées comme telles."},
{i:"n156_16",u:156,t:"mcq",d:.4,q:"Qu'est-ce qui distingue le plus souvent une inquiétude d'une objection réelle ?",o:["Elle prend la forme d'une question chargée d'émotion","Elle est toujours liée aux frais du contrat proposé","Elle arrive toujours tout à la fin de l'entretien","Elle cache toujours un refus déjà décidé"],a:0,w:"« Et si... ? » : l'inquiétude demande à être rassurée par des faits. L'objection réelle, elle, est précise et argumentée."},
{i:"n156_17",u:156,t:"story",d:.45,q:"Tu as traité l'objection. Que fais-tu maintenant ?",sc:[{who:"Toi",me:true,txt:"Voici le rendement net comparé, avec et sans conseil, sur dix ans."},{who:"Marc Delorme",txt:"Hmm."}],o:["« Est-ce que cela répond à votre préoccupation sur les frais ? »","« Parfait, alors signons tout de suite la proposition écrite. »","« Je vois que vous êtes convaincu, passons à la suite. »","« Vous voulez que je vous montre encore d'autres chiffres ? »"],a:0,w:"Un « hmm » n'est pas un oui. On valide explicitement. Sinon, l'objection reviendra au moment de signer."},
{i:"n156_18",u:156,t:"sort",d:.45,q:"Classe chaque réponse de conseiller dans le bon temps du traitement.",bins:["Accueillir","Clarifier","Traiter","Valider"],it:[["« Je comprends votre point de vue. »",0],["« Par rapport à quoi trouvez-vous cela cher ? »",1],["« Voici la simulation nette sur dix ans. »",2],["« Est-ce que cela répond à votre préoccupation ? »",3],["« Qu'est-ce qui vous fait dire cela ? »",1]],w:"Accueillir, Clarifier (question), Traiter (preuve), Valider (question fermée de contrôle)."},
{i:"n156_19",u:156,t:"tf",d:.45,q:"Quand un client enchaîne une nouvelle objection dès que tu réponds à la précédente, c'est souvent le signe d'un prétexte.",a:true,w:"Si chaque réponse fait surgir une autre objection, aucune n'est la vraie. Il faut chercher le motif réel : « Qu'est-ce qui vous retient vraiment ? »"},
{i:"n156_20",u:156,t:"story",d:.45,q:"Rappel du module 7 : Marc révèle son vrai frein. Quel levier SONCAS dois-tu servir ?",sc:[{who:"Marc Delorme",txt:"En fait, ce qui m'embête, c'est de passer pour un pigeon auprès de mes confrères."}],o:["L'orgueil : reconnaître son statut et lui montrer qu'il est bien traité","La sécurité : lui parler de la garantie en capital de son fonds euros","La nouveauté : lui présenter la nouvelle appli de gestion en ligne","Le confort : lui proposer une gestion pilotée sans rien à faire de son côté"],a:0,w:"Passer pour un pigeon : c'est l'image de soi, le O de SONCAS. Un rendez-vous annuel avec Sylvie peut valoir plus qu'une remise."},
{i:"n156_21",u:156,t:"multi",d:.5,q:"Quelles réponses sont des erreurs face à une objection ?",o:["Se justifier longuement dès la première phrase","Céder une remise avant d'avoir clarifié","Contredire le client : « c'est faux »","Demander : « Qu'est-ce qui vous fait dire cela ? »","Montrer une simulation chiffrée"],a:[0,1,2],w:"Se défendre, céder et contredire sautent l'accueil ou la clarification. Questionner et prouver sont justement les bonnes réponses."},
{i:"n156_22",u:156,t:"slider",d:.5,q:"Kevin compare votre assurance emprunteur à 0,34 % du capital par an avec une délégation à 0,12 %. Sur 250 000 €, quelle est la différence annuelle, en euros ?",min:0,max:1200,step:10,a:550,tol:0,pre:"",un:" €",w:"(0,34 − 0,12) % × 250 000 = 550 € par an. L'objection est réelle et chiffrée : il faut la traiter avec des faits (garanties comparées) ou un compromis, pas la balayer. Et depuis la loi Lemoine, il peut changer d'assurance à tout moment."},
{i:"n156_23",u:156,t:"story",d:.5,q:"Quel exemple utilises-tu pour traiter l'inquiétude de Claire ?",sc:[{who:"Claire Vasseur",txt:"Si je place 400 000 € et que l'atelier a un coup dur, je serai coincée."}],o:["« Un de nos clients artisans a fait un rachat partiel en 48 heures l'an dernier. »","« Nos clients ne font presque jamais de rachat, ne vous inquiétez pas pour ça. »","« Placez plutôt tout sur un compte courant, vous serez libre d'y toucher. »","« Si l'atelier a un coup dur, il faudra simplement demander un prêt à la banque. »"],a:0,w:"Un exemple concret et vrai rassure mieux qu'une promesse. Il répond à l'objection de liquidité (le majeur) avec un cas vécu."},
{i:"n156_24",u:156,t:"fill",d:.5,q:"Un compromis se donne toujours contre une ___.",o:["contrepartie","signature orale","remise","promesse"],a:0,w:"Un compromis sans contrepartie est un cadeau, et un cadeau en appelle d'autres. C'est la réciprocité du module 9."},
{i:"n156_25",u:156,t:"match",d:.5,q:"Associe chaque objection des cinq doigts à sa meilleure preuve.",p:[["« Trop de frais »","Rendement net comparé"],["« Trop risqué »","Scénario défavorable simulé"],["« Argent bloqué »","Délai de rachat au contrat"],["« Trop d'impôts »","Simulation nette de fiscalité"]],w:"Chaque objection a sa preuve. On revient à la main du module 4 : frais, risques, liquidité, confiance, fiscalité."},
{i:"n156_26",u:156,t:"tiles",d:.5,q:"Reconstitue le moyen mnémotechnique.",a:["Avant","Chaque","Traitement","Vérifie"],dd:["Accorde","Cède","Toujours"],w:"A.C.T.V. : Accueillir, Clarifier, Traiter, Valider."},
{i:"n156_27",u:156,t:"story",d:.55,q:"Rappel du module 2 : Marc objecte avec une offre concurrente. Que vérifies-tu ?",sc:[{who:"Marc Delorme",txt:"NeoBanque, c'est 0,50 %. Point final."}],o:["Ce que cette offre inclut vraiment, pour mesurer sa MESORE réelle","Le nombre de clients de NeoBanque, pour le rassurer sur sa taille","Si NeoBanque est bien immatriculée, car c'est sûrement une arnaque","La date de création de NeoBanque, pour montrer qu'elle est récente"],a:0,w:"Une objection fondée sur une alternative se clarifie en évaluant cette alternative. Sans conseil ni suivi, la MESORE de Marc vaut moins que 0,50 %."},
{i:"n156_28",u:156,t:"mcq",d:.55,q:"Pourquoi clarifie-t-on avant de traiter ?",o:["Pour ne pas répondre à côté du vrai problème","Pour gagner du temps avant de céder une remise","Pour montrer au client qu'on connaît la réglementation","Pour laisser le client se calmer tout seul"],a:0,w:"Traiter une inquiétude comme une objection de prix (ou l'inverse) ne règle rien. Clarifier, c'est viser juste."},
{i:"n156_29",u:156,t:"story",d:.55,q:"Comment traites-tu l'objection de Gérard ?",sc:[{who:"Gérard Robin",txt:"Un PER, ça bloque l'argent jusqu'à la retraite. Hors de question."},{who:"Toi",me:true,txt:"Je comprends. Qu'est-ce qui vous gêne le plus dans ce blocage ?"},{who:"Gérard Robin",txt:"Si on a un gros pépin de santé, je veux pouvoir y toucher."}],o:["« Le PER prévoit des cas de déblocage anticipé, dont certains accidents de la vie. »","« Le PER est bloqué quoi qu'il arrive, c'est le prix de l'avantage fiscal à l'entrée. »","« Ne vous inquiétez pas, un pépin de santé grave arrive très rarement à votre âge. »","« Dans ce cas, oublions le PER et plaçons tout sur un livret A, c'est plus simple. »"],a:0,w:"Le PER se débloque par anticipation dans certains cas (invalidité, décès du conjoint ou du partenaire de PACS, surendettement, fin de droits au chômage, achat de la résidence principale...). La preuve factuelle traite l'objection réelle."},
{i:"n156_30",u:156,t:"tf",d:.55,q:"Une objection est un signal d'intérêt : le client qui n'objecte rien est souvent celui qui ne signera pas.",a:true,w:"Objecter, c'est se projeter. Le client qui ne dit rien n'est souvent pas engagé. Accueille les objections comme des questions sur le chemin de l'accord."},
{i:"n156_31",u:156,t:"order",d:.6,q:"Remets dans l'ordre le traitement de l'objection de Marc sur les frais.",it:["« Je comprends que ce chiffre vous saute aux yeux. »","« Vous comparez à quoi exactement ? »","Il révèle qu'il compare avec un confrère, sans connaître ses services","Tu montres le rendement net et les services inclus","« Est-ce que cela répond à votre préoccupation ? »"],w:"Accueillir, clarifier (question puis réponse du client), traiter (preuve de valeur), valider."},
{i:"n156_32",u:156,t:"multi",d:.6,q:"Parmi ces réponses à « c'est trop cher », lesquelles démontrent la valeur ?",o:["Chiffrer le gain net apporté par le conseil","Montrer le bilan patrimonial inclus","Comparer le coût total à une référence de marché","Dire « c'est le prix de la qualité »","Dire « vous pouvez vous le permettre »"],a:[0,1,2],w:"Démontrer la valeur, c'est chiffrer, montrer, comparer. « Le prix de la qualité » est une formule creuse, « vous pouvez vous le permettre » est déplacé."}
