/*UNIT*/
{id:157,c:"NEGO",n:"Module 9",t:"Concéder sans se faire plumer : si... alors, closing et suivi",col:"--blue",ic:"🔁",guide:`
<h3>Hugo a tout donné. Et n'a rien reçu.</h3>
<div class="gstory">Vendredi, débrief avec Sylvie Morel. Hugo raconte fièrement son rendez-vous avec un client : frais de dossier offerts, puis 0,10 point de taux en moins, puis l'assurance à prix réduit, puis la carte premium gratuite. « Il a signé ? » demande Sylvie. « Pas encore, il réfléchit. Il m'a demandé si je pouvais encore faire un geste sur la garantie. » Sylvie soupire : « Tu lui as appris une chose, Hugo : qu'il suffit d'attendre pour que tu donnes. » Chaque concession gratuite en appelle une autre.</div>
<h3>La concession conditionnelle</h3>
<div class="formula">« SI nous ajustons X, ALORS vous validez Y. »</div>
<p>La condition passe <b>avant</b> la concession. Tu ne dis pas « je vous baisse les frais, et vous signeriez ? », tu dis « si vous regroupez vos deux contrats chez nous, alors je peux ramener les frais à 0,70 % ». Le client entend d'abord ce qu'il doit donner : la concession n'existe que s'il accepte la contrepartie.</p>
<h3>La réciprocité</h3>
<p>Règle des notes : <b>ne jamais céder gratuitement sur un élément important</b>. Chaque concession a un prix. Ce n'est pas de la dureté, c'est de la clarté : une concession gratuite n'a pas de valeur aux yeux de l'autre, et elle lui apprend à redemander.</p>
<div class="gmnemo"><b>« Pas de SI, pas de OUI. »</b> Avant chaque concession, ta phrase doit commencer par « Si ». Image : chaque concession porte une <b>étiquette de prix</b>. Si tu retires l'étiquette, le client croit que c'est gratuit, et il en reprendra.</div>
<h3>Bien concéder : les règles pratiques</h3>
<ul><li><b>Des concessions décroissantes</b> : 0,10 point, puis 0,05, puis 0,02. Le client comprend qu'on approche de la limite. Des concessions égales (0,05, 0,05, 0,05) lui disent qu'il peut continuer.</li>
<li><b>Ne jamais couper la poire en deux par réflexe</b> : c'est récompenser celui qui a ancré le plus loin.</li>
<li><b>Concéder sur ce qui coûte peu</b> (module 3) et demander ce qui vaut beaucoup.</li>
<li><b>Garder de la marge</b> : ne pas arriver au plancher dès la deuxième concession.</li></ul>
<h3>Le closing éthique</h3>
<p>Conclure, c'est demander la décision. Le faire de façon éthique, c'est faire une <b>synthèse</b> qui permet au client de décider en connaissance de cause :</p>
<div class="formula">Synthèse des BESOINS       : ce que vous m'avez dit vouloir
Synthèse des RISQUES       : ce qui peut mal tourner
Synthèse des COÛTS         : ce que vous paierez, en euros
Les PROCHAINES ÉTAPES      : qui fait quoi, quand</div>
<div class="gmnemo"><b>B.R.C.P. : « Bien Relire Chaque Point ».</b> Besoins, Risques, Coûts, Prochaines étapes. Un closing qui oublie les risques ou les coûts n'est pas un closing, c'est un piège.</div>
<div class="gtrap">Le closing éthique exclut les techniques de pression : fausse urgence (« offre valable jusqu'à ce soir » quand c'est faux), culpabilisation, signature le jour même d'un placement complexe. Elles sont contraires au devoir de conseil, et la loi prévoit d'ailleurs des délais de protection : <b>30 jours</b> pour renoncer à une assurance-vie, <b>14 jours</b> de rétractation en cas de démarchage, <b>10 jours</b> de réflexion avant d'accepter une offre de crédit immobilier.</div>
<h3>Le suivi</h3>
<p>Selon les notes, le suivi sert à <b>formaliser l'accord</b> et à <b>sécuriser la compréhension du client</b>. Concrètement : un compte rendu écrit de ce qui a été décidé, les documents remis, la date du prochain point, et une vérification que le client sait expliquer avec ses mots ce qu'il a signé. Un client qui a compris reste ; un client qui découvre plus tard une mauvaise surprise part, et parle.</p>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Écrire une concession conditionnelle correcte</li><li>Expliquer la réciprocité et le risque d'une concession gratuite</li><li>Construire une série de concessions décroissantes</li><li>Faire un closing en quatre points</li><li>Dire ce que contient un bon suivi</li></ul>`},
/*EXOS*/
{i:"n157_01",u:157,t:"tiles",d:.25,nw:"La concession conditionnelle",q:"Reconstitue la formule de la concession conditionnelle.",a:["Si","nous","ajustons","X","alors","vous","validez","Y"],dd:["peut-être","gratuitement","toujours"],w:"La condition d'abord, la concession ensuite. Pas de SI, pas de OUI."},
{i:"n157_02",u:157,t:"story",d:.3,q:"Quelle phrase respecte la concession conditionnelle ?",sc:[{who:"Marc Delorme",txt:"Si vous faites un effort sur les frais, je réfléchirai."}],o:["« Si vous regroupez vos deux contrats chez nous, je ramène les frais à 0,70 %. »","« Je vous ramène les frais à 0,70 %, et j'espère que vous regrouperez vos contrats. »","« D'accord pour 0,70 %, c'est bien parce que c'est vous et que je vous apprécie. »","« Je baisse à 0,70 % maintenant, on verra ensuite pour le regroupement des contrats. »"],a:0,w:"La contrepartie (regrouper les contrats) vient en premier et conditionne la concession. Les autres donnent d'abord et espèrent ensuite."},
{i:"n157_03",u:157,t:"mcq",d:.3,q:"Que dit la règle de réciprocité ?",o:["Ne jamais céder gratuitement sur un élément important","Toujours rendre une remise égale à celle du client","Céder exactement la même chose que ce que l'autre demande","Accorder un petit geste à chaque rendez-vous client"],a:0,w:"Chaque concession importante a une contrepartie. Une concession gratuite n'a pas de valeur perçue et appelle la suivante."},
{i:"n157_04",u:157,t:"sort",d:.3,q:"Classe chaque phrase : concession conditionnelle ou concession gratuite ?",bins:["Conditionnelle","Gratuite"],it:[["« Si vous domiciliez vos salaires, j'offre les frais de dossier. »",0],["« Je vous offre les frais de dossier, pour vous faire plaisir. »",1],["« Si vous signez avant le 30, je bloque ce taux. »",0],["« Allez, je vous baisse encore un peu. »",1],["« Si vous prenez l'assurance habitation, je réduis la garantie. »",0]],w:"La conditionnelle commence par « si » et exige une contrepartie. La gratuite donne sans rien demander."},
{i:"n157_05",u:157,t:"order",d:.3,nw:"Le closing éthique",q:"Remets dans l'ordre les quatre points du closing éthique.",it:["Synthèse des besoins","Synthèse des risques","Synthèse des coûts","Prochaines étapes"],w:"B.R.C.P. : Bien Relire Chaque Point. Besoins, Risques, Coûts, Prochaines étapes."},
{i:"n157_06",u:157,t:"tf",d:.25,q:"Couper la poire en deux est toujours une solution équitable.",a:false,w:"C'est récompenser celui qui a ancré le plus loin. Si le client ouvre à 0,40 % face à tes 0,80 %, le milieu (0,60 %) est peut-être ton plancher."},
{i:"n157_07",u:157,t:"slider",d:.35,q:"Hugo a concédé 0,05 point, puis 0,05, puis 0,05 sur le taux. Combien de points a-t-il cédé au total ?",min:0,max:.5,step:.05,a:.15,tol:0,pre:"",un:" point",w:"0,15 point, en trois concessions égales : le client comprend qu'il peut continuer. Des concessions décroissantes (0,10, puis 0,04, puis 0,01) montrent qu'on approche de la limite."},
{i:"n157_08",u:157,t:"story",d:.35,q:"Quelle série de concessions envoie le bon signal ?",ctx:"Ta marge totale sur le taux de Kevin est de 0,15 point.",sc:[{who:"Kevin",txt:"Vous pouvez faire mieux ?"}],o:["0,08 point, puis 0,04, puis 0,02","0,05 point, puis 0,05, puis 0,05","0,02 point, puis 0,05, puis 0,08","0,15 point d'un coup pour conclure vite"],a:0,w:"Des concessions décroissantes signalent qu'on approche de la limite. Croissantes, elles encouragent à redemander ; tout d'un coup, on n'a plus rien à échanger."},
{i:"n157_09",u:157,t:"fill",d:.3,q:"Le suivi sert à formaliser l'accord et à sécuriser la ___ du client.",o:["compréhension","signature","fidélité","satisfaction durable"],a:0,w:"Formulation des notes. Un client qui a compris ce qu'il a signé reste ; celui qui découvre une surprise part."},
{i:"n157_10",u:157,t:"multi",d:.35,q:"Que contient un bon suivi après l'accord ?",o:["Un compte rendu écrit des décisions","La liste des documents remis","La date du prochain point","Une vérification que le client sait expliquer ce qu'il a signé","Une nouvelle proposition commerciale dès le lendemain"],a:[0,1,2,3],w:"Formaliser et sécuriser la compréhension. Relancer tout de suite avec une autre vente abîme la confiance."},
{i:"n157_11",u:157,t:"story",d:.4,q:"Que réponds-tu à Hugo ?",sc:[{who:"Hugo",txt:"Je lui ai offert les frais, baissé le taux, réduit l'assurance. Et maintenant il veut un geste sur la garantie !"},{who:"Sylvie Morel",txt:"Explique-lui."}],o:["« Chaque concession gratuite lui a appris qu'il suffit d'attendre pour obtenir plus. »","« Il faut lui accorder aussi la garantie, sinon tous tes efforts précédents seront perdus. »","« Refuse tout net et retire toutes les concessions précédentes pour lui faire peur. »","« C'est normal, les clients demandent toujours plus, il ne faut surtout pas t'en faire. »"],a:0,w:"C'est la réciprocité : sans contrepartie, les concessions n'ont pas de valeur et en appellent d'autres. Retirer tout d'un coup détruirait la relation."},
{i:"n157_12",u:157,t:"tf",d:.3,q:"Dire à un client « cette offre n'est valable que jusqu'à ce soir » alors que c'est faux est une technique de closing acceptable.",a:false,w:"C'est une fausse urgence : une pression déloyale, contraire au devoir de conseil. Le closing éthique repose sur une synthèse honnête."},
{i:"n157_13",u:157,t:"match",d:.35,q:"Associe chaque délai de protection du client à son opération.",p:[["30 jours","Renonciation à une assurance-vie"],["14 jours","Rétractation après démarchage"],["10 jours","Réflexion avant d'accepter un crédit immobilier"],["Aucun délai légal","Ouverture d'un livret A"]],w:"La loi protège les décisions importantes. Le closing éthique les respecte et les rappelle au client."},
{i:"n157_14",u:157,t:"story",d:.4,q:"Quel closing est éthique pour Claire ?",sc:[{who:"Claire Vasseur",txt:"Bon, je crois qu'on y est. On fait quoi maintenant ?"}],o:["Je résume ses besoins, les risques, les coûts en euros et les prochaines étapes","Je lui tends le bulletin de souscription pour qu'elle signe tant qu'elle est décidée","Je lui rappelle que les taux peuvent baisser et qu'elle doit signer aujourd'hui","Je lui dis que tout est sans risque et qu'elle peut signer les yeux fermés"],a:0,w:"B.R.C.P. Le closing éthique permet de décider en connaissance de cause. Précipiter la signature ou taire les risques est une faute."},
{i:"n157_15",u:157,t:"num",d:.4,q:"Tu proposes : « Si vous regroupez vos 80 000 € d'épargne chez nous, alors je passe vos frais de 0,85 % à 0,75 % sur votre contrat de 120 000 € ». Combien Marc économise-t-il par an, en euros ?",a:120,tol:1,un:" €",h:"0,10 % de 120 000",w:"0,10 % × 120 000 = 120 €. En échange, la banque gagne 80 000 € d'encours : c'est une concession conditionnelle qui crée de la valeur pour les deux."},
{i:"n157_16",u:157,t:"mcq",d:.4,q:"Pourquoi fait-on des concessions décroissantes ?",o:["Pour signaler qu'on approche de sa limite","Pour montrer qu'on a encore beaucoup de marge","Pour finir avec la plus grosse concession","Pour que le client ne remarque rien"],a:0,w:"0,08 puis 0,04 puis 0,02 : le client comprend que la prochaine sera minuscule, ou nulle. C'est un message sans mots."},
{i:"n157_17",u:157,t:"story",d:.45,q:"Rappel du module 3 : que demandes-tu en échange d'une baisse de frais à Marc ?",sc:[{who:"Toi",me:true,txt:"(tu cherches une contrepartie qui lui coûte peu)"}],o:["Qu'il regroupe son épargne dispersée chez nous","Qu'il paie une année de frais d'avance à la banque","Qu'il renonce à son droit de renonciation de 30 jours","Qu'il accepte des frais plus élevés sur un autre contrat"],a:0,w:"Regrouper coûte peu à Marc (simplicité) et vaut beaucoup pour la banque (encours). Renoncer à un droit légal est impossible ; les autres contreparties lui coûtent cher."},
{i:"n157_18",u:157,t:"tf",d:.4,q:"Dans une concession conditionnelle, on annonce la condition avant la concession.",a:true,w:"« Si vous..., alors je... » : le client entend d'abord ce qu'il doit donner. Dans l'autre sens, il retient la concession et oublie la condition."},
{i:"n157_19",u:157,t:"sort",d:.45,q:"Classe chaque phrase dans le bon point du closing éthique.",bins:["Besoins","Risques","Coûts","Prochaines étapes"],it:[["« Vous voulez sécuriser les études de Léo et Inès. »",0],["« La partie en unités de compte peut baisser de 20 % une mauvaise année. »",1],["« Les frais de gestion vous coûteront 2 800 € par an. »",2],["« Je vous envoie le rapport jeudi, on se revoit dans six mois. »",3],["« Vous gardez 80 000 € disponibles pour l'atelier. »",0]],w:"Besoins (ce qu'elle veut), Risques (ce qui peut mal tourner), Coûts (en euros), Prochaines étapes (qui, quoi, quand)."},
{i:"n157_20",u:157,t:"fill",d:.45,q:"Pas de SI, pas de ___.",o:["OUI","prix","remise","closing"],a:0,w:"Chaque concession commence par « si ». Sinon, c'est un cadeau, et le client en redemandera."},
{i:"n157_21",u:157,t:"story",d:.45,q:"Comment sécurises-tu la compréhension de Kevin et Laura ?",sc:[{who:"Laura",txt:"Super, on signe l'offre dans onze jours alors !"}],o:["« Pouvez-vous me redire avec vos mots ce qui se passe si l'un de vous arrête de travailler ? »","« Parfait, je vous envoie simplement les documents par e-mail et on n'en parle plus. »","« Vous avez tout compris, j'en suis absolument certain, vous êtes des gens intelligents. »","« Ne lisez pas tout, c'est très long, l'essentiel est résumé sur la première page. »"],a:0,w:"Faire reformuler par le client est la meilleure preuve de compréhension. C'est le cœur du suivi."},
{i:"n157_22",u:157,t:"multi",d:.5,q:"Quelles techniques sont contraires au closing éthique ?",o:["Inventer une date limite","Taire les frais jusqu'à la signature","Faire signer un placement complexe dans l'urgence","Résumer besoins, risques et coûts","Fixer ensemble les prochaines étapes"],a:[0,1,2],w:"Fausse urgence, dissimulation, précipitation : trois pressions déloyales. Résumer et planifier sont justement le closing éthique."},
{i:"n157_23",u:157,t:"story",d:.5,q:"Rappel du module 2 : Kevin propose de couper la poire en deux. Que fais-tu ?",sc:[{who:"Kevin",txt:"Vous êtes à 3,50 %, j'ai une offre à 3,20 %. Coupons la poire en deux : 3,35 % ?"}],o:["Je vérifie où tombe 3,35 % par rapport à mon plancher avant de répondre","J'accepte, couper la poire en deux est toujours juste et bien plus rapide","Je refuse net, on ne coupe jamais la poire en deux avec un client","Je propose directement 3,30 % pour montrer ma bonne volonté au client"],a:0,w:"Le milieu n'est pas un principe, c'est un chiffre à comparer à ton point de réserve. S'il est au-dessus, tu peux accepter ; sinon, contre-propose avec une condition."},
{i:"n157_24",u:157,t:"tiles",d:.5,q:"Reconstitue les quatre éléments du closing éthique.",a:["besoins","risques","coûts","prochaines","étapes"],dd:["remise","urgence","signature"],w:"B.R.C.P. : Bien Relire Chaque Point. Besoins, risques, coûts, prochaines étapes : le client décide en connaissance de cause."},
{i:"n157_25",u:157,t:"story",d:.55,q:"Écris la bonne concession conditionnelle pour Claire.",ctx:"Claire hésite à placer 400 000 €. Tu peux lui offrir un bilan transmission avec le notaire partenaire (coût faible pour la banque, forte valeur pour elle).",sc:[{who:"Claire Vasseur",txt:"La transmission, c'est ce qui me préoccupe le plus pour plus tard."}],o:["« Si vous confiez 400 000 € à notre gestion, alors je vous organise un bilan transmission. »","« Je vous organise un bilan transmission gratuit, et vous verrez ensuite pour le placement. »","« Un bilan transmission coûte cher, je ne peux pas vous le proposer dans ce dossier. »","« Si vous voulez un bilan transmission, allez voir directement un notaire de votre côté. »"],a:0,w:"La condition (confier 400 000 €) précède la concession (le bilan). Et le bilan vaut beaucoup pour elle en coûtant peu à la banque : concession intelligente."},
{i:"n157_26",u:157,t:"mcq",d:.55,q:"Rappel du module 8 : après avoir fait une concession, que vérifies-tu ?",o:["Que la concession répond à sa préoccupation","Que le client a bien remercié la banque","Que la concession est bien inscrite au tarif officiel","Que le client n'en parlera à personne"],a:0,w:"Valider : « Est-ce que cela répond à votre préoccupation ? ». Une concession qui ne règle pas le vrai problème est perdue."},
{i:"n157_27",u:157,t:"tf",d:.55,q:"Le délai de réflexion d'un crédit immobilier empêche d'accepter l'offre avant le 11e jour après sa réception.",a:true,w:"Délai de réflexion de 10 jours : l'emprunteur ne peut accepter l'offre qu'à partir du 11e jour. D'où la phrase de Laura : « on signe dans onze jours »."},
{i:"n157_28",u:157,t:"order",d:.55,q:"Remets dans l'ordre la fin de négociation avec Marc.",it:["Concession conditionnelle : regroupement contre 0,75 %","Validation de sa préoccupation sur les frais","Closing : besoins, risques, coûts, prochaines étapes","Compte rendu écrit et date du prochain point","Appel à trois mois pour vérifier sa satisfaction"],w:"Concéder avec condition, valider, conclure proprement, formaliser, suivre. C'est la fin d'une négociation réussie."},
{i:"n157_29",u:157,t:"fill",d:.55,q:"Des concessions ___ (0,08 puis 0,04 puis 0,02) signalent qu'on approche de la limite.",o:["décroissantes","égales","croissantes","conditionnelles"],a:0,w:"Chaque concession plus petite que la précédente dit au client que la marge s'épuise."},
{i:"n157_30",u:157,t:"story",d:.6,q:"Quelle est la meilleure réponse à ton manager ?",ctx:"Tu demandes une augmentation. Sylvie répond que le budget est très serré. Tu as préparé une concession conditionnelle.",sc:[{who:"Sylvie Morel",txt:"Je ne peux rien te promettre cette année."}],o:["« Si j'atteins un objectif relevé de 10 % d'ici décembre, alors vous vous engagez à 5 % d'augmentation. »","« Je comprends, dans ce cas je n'insiste pas et je vous en reparlerai sans doute l'année prochaine. »","« Si vous ne m'augmentez pas, je serai obligé de regarder les offres des autres banques de Nantes. »","« Vous pourriez au moins faire un petit geste, même symbolique, pour me montrer votre soutien. »"],a:0,w:"C'est la réponse modèle des notes : une condition mesurable (objectif +10 %) contre un engagement précis (5 %). La menace abîme la relation, le geste symbolique est une demande sans contrepartie."},
{i:"n157_31",u:157,t:"multi",d:.6,q:"Pourquoi une concession gratuite est-elle dangereuse ?",o:["Elle n'a pas de valeur perçue","Elle apprend au client à redemander","Elle rapproche du plancher sans rien gagner","Elle est interdite par la loi","Elle oblige à rembourser le client"],a:[0,1,2],w:"Pas de valeur perçue, pas de contrepartie, et une habitude prise. Ce n'est pas illégal, c'est simplement une mauvaise négociation."},
{i:"n157_32",u:157,t:"tf",d:.6,q:"Le suivi commence après la signature et sert aussi à préparer la relation future.",a:true,w:"Formaliser, sécuriser la compréhension, planifier le prochain point : la prochaine négociation avec ce client se prépare dès aujourd'hui."}
