/*UNIT*/
{id:160,c:"NEGO",n:"Module 12",t:"La découverte client : contexte, objectifs, contraintes, risque, décision",col:"--blue",ic:"🔎",guide:`
<h3>Les Robin, deuxième rendez-vous</h3>
<div class="gstory">Mardi, 14 h. Gérard et Martine Robin reviennent avec une chemise cartonnée pleine de relevés. Gérard : « On a réfléchi depuis la dernière fois. On veut des revenus en plus à la retraite, commencer à donner aux enfants, les protéger, et payer moins d'impôts. » Quatre objectifs dans une phrase. Avant de proposer quoi que ce soit, tu déroules ta grille de découverte, case par case. Quarante minutes plus tard, tu sais ce qu'ils veulent, ce qu'ils peuvent, ce qu'ils supportent, et comment ils décideront.</div>
<h3>La grille de découverte en cinq blocs</h3>
<table><tr><th>Bloc</th><th>Ce qu'on explore</th><th>Chez les Robin</th></tr>
<tr><td><b>Contexte</b></td><td>Famille, activité, fiscalité, patrimoine</td><td>Mariés sans contrat, deux enfants et trois petits-enfants, salariés, 30 % de tranche marginale, maison payée et 180 000 € de livrets</td></tr>
<tr><td><b>Objectifs</b></td><td>Court, moyen et long terme</td><td>Camping-car à 2 ans, aider les petits-enfants à 5-10 ans, transmettre à long terme</td></tr>
<tr><td><b>Contraintes</b></td><td>Liquidités, dette, horizon, éthique</td><td>Garder 30 000 € disponibles, pas de dette, départ dans 3 ans, refus d'investir dans l'armement</td></tr>
<tr><td><b>Risque</b></td><td>Capacité, tolérance, expérience</td><td>Capacité moyenne, tolérance faible chez Martine, aucune expérience des actions</td></tr>
<tr><td><b>Décision</b></td><td>Critères de choix, prochaines étapes</td><td>Simplicité et sécurité d'abord, décision à deux après en avoir parlé à leur fille</td></tr></table>
<div class="gmnemo"><b>« C.O.C.R.D. : Chaque Objectif Cache un Risque à Découvrir ».</b> Contexte, Objectifs, Contraintes, Risque, Décision. Et c'est littéral : l'objectif « revenus en plus » cachait chez les Robin un risque qu'ils n'avaient pas vu (bloquer trop d'argent juste avant d'acheter le camping-car).</div>
<h3>Court, moyen, long terme</h3>
<p>Il n'existe pas de définition légale. Convention courante : <b>court terme</b> moins de 2 ans, <b>moyen terme</b> de 2 à 8 ans, <b>long terme</b> au-delà de 8 ans (8 ans, c'est aussi le seuil fiscal de l'assurance-vie). L'horizon décide de la part de risque possible : on ne place pas en actions l'argent du camping-car.</p>
<h3>Le risque en trois dimensions</h3>
<table><tr><th>Dimension</th><th>Question</th><th>Nature</th></tr>
<tr><td><b>Capacité</b> (capacité de perte)</td><td>Combien peut-il perdre sans que sa vie change ?</td><td>Objective : patrimoine, revenus, charges</td></tr>
<tr><td><b>Tolérance</b></td><td>Combien supporte-t-il de voir baisser sans paniquer ?</td><td>Subjective : psychologie</td></tr>
<tr><td><b>Expérience</b></td><td>Que connaît-il des produits, qu'a-t-il déjà fait ?</td><td>Connaissances et opérations passées</td></tr></table>
<p>On retient la plus prudente des trois. Gérard a une bonne capacité mais Martine une faible tolérance : le couple est prudent.</p>
<h3>Les trois questions ouvertes des notes pour explorer la tolérance</h3>
<ul><li>« Comment réagiriez-vous en cas de mouvements importants du marché ? »</li>
<li>« Quelle part de votre patrimoine, en pourcentage, vous placerait dans une situation critique si elle venait à être perdue ? »</li>
<li>« Quelle proportion mettriez-vous entre sécurité et performance ? »</li></ul>
<h3>L'exercice « Préparer sa retraite »</h3>
<table><tr><th>Objectif</th><th>Piste de solution</th></tr>
<tr><td>Compléments de revenus réguliers et passifs</td><td>SCPI (société civile de placement immobilier) : des loyers distribués sans gérer de locataire, mais capital et revenus non garantis, frais d'entrée élevés, revente parfois lente</td></tr>
<tr><td>Anticiper une transmission petit à petit</td><td>Donations régulières (100 000 € par parent et par enfant tous les 15 ans), assurance-vie</td></tr>
<tr><td>Protéger ses enfants</td><td>Clause bénéficiaire d'assurance-vie, prévoyance, testament</td></tr>
<tr><td>Optimiser sa fiscalité</td><td>PER (plan d'épargne retraite) : versements déductibles du revenu imposable</td></tr></table>
<div class="gtrap">Les notes disent « optimiser sa fiscalité à la retraite : ouvrir un PER ». Nuance indispensable : le PER fait gagner de l'impôt <b>pendant la vie active</b> (déduction des versements), et la sortie à la retraite est <b>imposée</b>. Il est très intéressant si la tranche d'imposition baisse à la retraite (30 % aujourd'hui, 11 % demain), beaucoup moins si elle reste la même. Pour les Robin, à trois ans du départ, l'effet est limité : il faut le chiffrer, pas le promettre.</div>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Dérouler les cinq blocs de la découverte sur un cas</li><li>Classer un objectif en court, moyen ou long terme</li><li>Distinguer capacité, tolérance et expérience</li><li>Réciter les trois questions sur la tolérance au risque</li><li>Associer chaque objectif retraite à une solution, avec ses limites</li></ul>`},
/*EXOS*/
{i:"n160_01",u:160,t:"order",d:.25,nw:"La grille de découverte",q:"Remets dans l'ordre les cinq blocs de la découverte client.",it:["Contexte","Objectifs","Contraintes","Risque","Décision"],w:"C.O.C.R.D. : Chaque Objectif Cache un Risque à Découvrir."},
{i:"n160_02",u:160,t:"sort",d:.3,q:"Range chaque information sur les Robin dans le bon bloc.",bins:["Contexte","Objectifs","Contraintes","Risque","Décision"],it:[["Mariés sans contrat, trois petits-enfants",0],["Acheter un camping-car dans deux ans",1],["Garder 30 000 € disponibles",2],["Martine ne supporte pas les baisses",3],["Ils décideront après en avoir parlé à leur fille",4],["Tranche marginale d'imposition de 30 %",0]],w:"Contexte (qui ils sont), Objectifs (ce qu'ils veulent), Contraintes (ce qui limite), Risque (ce qu'ils supportent), Décision (comment ils choisiront)."},
{i:"n160_03",u:160,t:"match",d:.3,nw:"Capacité, tolérance, expérience",q:"Associe chaque dimension du risque à sa question.",p:[["Capacité de perte","Combien peut-il perdre sans que sa vie change ?"],["Tolérance","Combien supporte-t-il de voir baisser sans paniquer ?"],["Expérience","Que connaît-il des produits financiers ?"],["Horizon","Dans combien de temps aura-t-il besoin de l'argent ?"]],w:"Capacité : objective. Tolérance : psychologique. Expérience : connaissances et opérations passées. On retient la plus prudente."},
{i:"n160_04",u:160,t:"story",d:.3,q:"Quelle question explore le mieux la tolérance au risque de Martine ?",sc:[{who:"Martine Robin",txt:"Je ne sais pas trop ce que je supporte, en fait."}],o:["« Comment réagiriez-vous si votre placement baissait fortement pendant quelques mois ? »","« Vous voulez plutôt un profil prudent, équilibré ou dynamique pour votre contrat ? »","« Vous savez que les marchés remontent toujours sur le long terme, n'est-ce pas ? »","« Combien d'argent avez-vous exactement sur vos différents livrets bancaires aujourd'hui ? »"],a:0,w:"C'est la première question des notes : la réaction face aux mouvements de marché. Les autres ferment, orientent ou relèvent de la situation."},
{i:"n160_05",u:160,t:"slider",d:.3,q:"Selon la convention courante, au-delà de combien d'années parle-t-on de long terme ?",min:1,max:15,step:1,a:8,tol:0,pre:"",un:" ans",w:"Au-delà de 8 ans (convention, pas de définition légale) : court terme moins de 2 ans, moyen terme de 2 à 8 ans. 8 ans, c'est aussi le seuil fiscal de l'assurance-vie."},
{i:"n160_06",u:160,t:"tf",d:.25,q:"La capacité de perte et la tolérance au risque sont deux choses différentes.",a:true,w:"Gérard peut financièrement supporter une perte (capacité) ; Martine ne la supporterait pas psychologiquement (tolérance). Le conseil retient la plus prudente."},
{i:"n160_07",u:160,t:"multi",d:.35,nw:"Les questions sur la tolérance",q:"Coche les trois questions ouvertes des notes pour explorer la tolérance au risque.",o:["« Comment réagiriez-vous en cas de mouvements importants du marché ? »","« Quelle part de votre patrimoine vous placerait dans une situation critique si elle était perdue ? »","« Quelle proportion mettriez-vous entre sécurité et performance ? »","« Vous êtes plutôt prudent, n'est-ce pas ? »","« Vous voulez un rendement de combien ? »"],a:[0,1,2],w:"Trois questions ouvertes, à connaître par cœur. Les deux dernières ferment la discussion ou restent sur la position."},
{i:"n160_08",u:160,t:"story",d:.35,q:"Quel produit répond à l'objectif « compléments de revenus réguliers et passifs » ?",sc:[{who:"Gérard Robin",txt:"Je veux toucher un petit loyer chaque trimestre, mais sans gérer de locataire."}],o:["Les SCPI, avec leurs limites à expliquer","Un PER, qui verse des loyers chaque mois","Un livret A, qui distribue des revenus fonciers","Un fonds euros, qui paie des loyers garantis"],a:0,w:"Les SCPI distribuent des revenus issus de loyers, sans gestion locative. Mais capital et revenus ne sont pas garantis, les frais d'entrée sont élevés et la revente peut être lente."},
{i:"n160_09",u:160,t:"fill",d:.3,q:"Refuser d'investir dans l'armement est une contrainte ___.",o:["éthique","fiscale","de liquidité","d'horizon"],a:0,w:"Les notes citent quatre contraintes : liquidités, dette, horizon, éthique. L'éthique rejoint les préférences de durabilité (le E de SONCASE)."},
{i:"n160_10",u:160,t:"sort",d:.4,q:"Classe chaque projet selon son horizon.",bins:["Court terme","Moyen terme","Long terme"],it:[["Camping-car dans deux ans",0],["Aider un petit-fils pour ses études dans six ans",1],["Transmettre le patrimoine dans vingt ans",2],["Refaire la toiture l'an prochain",0],["Compléter la retraite pendant vingt-cinq ans",2]],w:"Convention : moins de 2 ans, 2 à 8 ans, plus de 8 ans. Plus l'horizon est court, moins on peut prendre de risque."},
{i:"n160_11",u:160,t:"tf",d:.35,q:"Le PER fait gagner de l'impôt surtout à la retraite, au moment de la sortie.",a:false,w:"C'est l'inverse : les versements sont déductibles pendant la vie active, et la sortie est imposée. Le PER est intéressant quand la tranche d'imposition baisse à la retraite."},
{i:"n160_12",u:160,t:"story",d:.4,q:"Que réponds-tu à Gérard sur le PER ?",sc:[{who:"Gérard Robin",txt:"Mon beau-frère dit que le PER, c'est zéro impôt à la retraite."}],o:["« On déduit à l'entrée, on est imposé à la sortie : je vous chiffre votre cas. »","« Il a raison, la sortie en capital du PER est totalement exonérée d'impôt. »","« Le PER est surtout intéressant pour les jeunes actifs, oubliez-le à votre âge. »","« Le PER n'a aucun intérêt fiscal réel, c'est un produit purement commercial. »"],a:0,w:"Correction factuelle et proposition de chiffrer. À trois ans du départ avec une tranche qui passera peut-être de 30 % à 11 %, il peut rester intéressant : il faut calculer, pas promettre."},
{i:"n160_13",u:160,t:"mcq",d:.35,q:"Quand capacité et tolérance au risque divergent, laquelle retient-on ?",o:["La plus prudente des deux","La plus élevée des deux","La moyenne des deux","Celle que préfère le conseiller"],a:0,w:"On retient la plus prudente : un client capable de perdre mais qui paniquerait vendrait au pire moment."},
{i:"n160_14",u:160,t:"num",d:.4,q:"Les Robin ont 180 000 € sur leurs livrets. Ils veulent garder 30 000 € disponibles et 60 000 € pour le camping-car dans deux ans. Combien reste-t-il pour le long terme, en euros ?",a:90000,tol:1,un:" €",h:"Total moins ce qui doit rester disponible à court terme",w:"180 000 − 30 000 − 60 000 = 90 000 €. Seule cette somme peut accepter un peu de risque. Les contraintes (liquidités, horizon) dessinent l'allocation avant les produits."},
{i:"n160_15",u:160,t:"tiles",d:.35,q:"Reconstitue le moyen mnémotechnique de la découverte.",a:["Chaque","Objectif","Cache","un","Risque","à","Découvrir"],dd:["Client","Rendement","Toujours"],w:"Contexte, Objectifs, Contraintes, Risque, Décision."},
{i:"n160_16",u:160,t:"match",d:.4,q:"Associe chaque objectif retraite à sa piste de solution.",p:[["Revenus réguliers sans gestion","SCPI"],["Transmettre petit à petit","Donations régulières"],["Protéger ses enfants","Clause bénéficiaire et prévoyance"],["Réduire l'impôt pendant la vie active","PER"]],w:"Ce sont les quatre objectifs de l'exercice des notes. Chaque solution a des limites à expliquer."},
{i:"n160_17",u:160,t:"story",d:.45,q:"Rappel du module 5 : les Robin ont listé quatre objectifs d'un coup. Que fais-tu ?",sc:[{who:"Gérard Robin",txt:"Revenus en plus, donner aux enfants, les protéger, payer moins d'impôts. Voilà."}],o:["Un résumé intermédiaire, puis je leur demande lequel passe en premier","Je leur propose un produit pour chaque objectif, dans l'ordre énoncé","Je choisis l'objectif fiscal, qui est le plus simple à traiter d'abord","Je leur dis qu'on ne peut pas tout faire en même temps, qu'il faut choisir"],a:0,w:"Le résumé transforme le flou en critères, et la question de priorité fait décider les clients eux-mêmes. Choisir à leur place ou leur faire la leçon brise la découverte."},
{i:"n160_18",u:160,t:"fill",d:.4,q:"La capacité de perte est une notion ___ : elle se mesure avec le patrimoine, les revenus et les charges.",o:["objective","subjective","fiscale","juridique"],a:0,w:"Objective, parce qu'elle se calcule. La tolérance, elle, est subjective : elle se découvre par des questions."},
{i:"n160_19",u:160,t:"multi",d:.45,q:"Que faut-il expliquer aux Robin avant de leur proposer des SCPI ?",o:["Le capital n'est pas garanti","Les revenus peuvent baisser","Les frais d'entrée sont élevés","La revente peut prendre du temps","Le rendement est garanti par l'État"],a:[0,1,2,3],w:"Quatre limites essentielles. Aucun rendement de SCPI n'est garanti, encore moins par l'État. Un conseil honnête montre les risques avant les avantages."},
{i:"n160_20",u:160,t:"story",d:.45,q:"Quel critère de décision Martine exprime-t-elle ?",sc:[{who:"Martine Robin",txt:"Ce qui compte, c'est que ce soit simple. Si je ne comprends pas, je ne signe pas."}],o:["La simplicité et la compréhension","Le rendement et la performance","La nouveauté et l'innovation","Le prix et le niveau des frais"],a:0,w:"Bloc Décision : les critères de choix. Pour Martine, comprendre est une condition. C'est aussi le levier Confort de SONCAS."},
{i:"n160_21",u:160,t:"mcq",d:.45,q:"Dans la grille, que contient le bloc Décision ?",o:["Les critères de choix et les prochaines étapes","Le produit retenu et le montant placé au final","Le contrat signé et la date du premier versement","Le profil de risque et les frais négociés"],a:0,w:"Comment le client choisira (critères) et comment on avance (qui fait quoi, quand). C'est ce qui prépare le closing."},
{i:"n160_22",u:160,t:"tf",d:.45,q:"Une dette en cours est une contrainte à intégrer dans la découverte, même pour un placement.",a:true,w:"Les notes citent la dette parmi les contraintes. Rembourser un crédit cher peut rapporter plus, sans risque, que n'importe quel placement."},
{i:"n160_23",u:160,t:"story",d:.5,q:"Quelle question te donne la part critique du patrimoine de Gérard ?",sc:[{who:"Gérard Robin",txt:"Perdre un peu, ça va. Perdre beaucoup, non."}],o:["« Quelle part de votre patrimoine vous mettrait en difficulté si elle était perdue ? »","« Qu'entendez-vous exactement par beaucoup : dix mille euros, ou bien cent mille ? »","« Vous accepteriez donc un profil dynamique avec une petite part d'actions ? »","« La plupart de nos clients acceptent de perdre jusqu'à 20 % sans aucune difficulté. »"],a:0,w:"C'est la deuxième question des notes, ouverte et exprimée en proportion. La deuxième réponse est utile mais fermée ; la dernière oriente la réponse (ancrage)."},
{i:"n160_24",u:160,t:"num",d:.5,q:"Pour 10 000 € versés sur un PER, Gérard (tranche à 30 %) économise combien d'impôt, en euros ?",a:3000,tol:1,un:" €",h:"Montant déduit × tranche marginale",w:"10 000 × 30 % = 3 000 € d'impôt en moins, dans la limite du plafond de déduction. Mais la sortie sera imposée : si sa tranche passe à 11 % à la retraite, le gain net reste réel."},
{i:"n160_25",u:160,t:"sort",d:.5,q:"Classe chaque information du bloc Risque.",bins:["Capacité","Tolérance","Expérience"],it:[["Maison payée et 180 000 € d'épargne",0],["Martine perd le sommeil quand un placement baisse",1],["N'ont jamais détenu d'actions",2],["Revenus stables jusqu'à la retraite",0],["Gérard a suivi un cours de Bourse en ligne",2]],w:"Capacité : les chiffres. Tolérance : les réactions. Expérience : ce qu'on sait et ce qu'on a déjà fait."},
{i:"n160_26",u:160,t:"story",d:.5,q:"Rappel du module 11 : qui est l'influenceur dans la décision des Robin ?",sc:[{who:"Martine Robin",txt:"On en parlera à Émilie avant de signer. Elle est comptable, elle s'y connaît."}],o:["Émilie, leur fille, qui pèsera sans signer","Gérard, qui décide seul pour le couple","Toi, parce que tu fais la proposition finale","Le notaire de la famille, qui a les actes"],a:0,w:"Émilie influence, les Robin décident. Il faut l'intégrer : proposer de lui envoyer la synthèse, ou de l'inviter au rendez-vous suivant."},
{i:"n160_27",u:160,t:"fill",d:.55,q:"Donner 100 000 € par parent et par enfant sans droits est possible tous les ___ ans.",o:["15","6","10","20"],a:0,w:"Abattement de 100 000 € en ligne directe, renouvelable tous les 15 ans. C'est l'outil de la « transmission petit à petit » (vu en détail dans le cours de transmission)."},
{i:"n160_28",u:160,t:"multi",d:.55,q:"Quelles contraintes des notes as-tu identifiées chez les Robin ?",o:["Liquidités : 30 000 € disponibles","Horizon : départ en retraite dans trois ans","Éthique : pas d'armement","Dette : aucune","Tolérance faible de Martine"],a:[0,1,2,3],w:"Liquidités, dette, horizon, éthique : les quatre contraintes. La tolérance de Martine relève du bloc Risque, pas des contraintes."},
{i:"n160_29",u:160,t:"story",d:.55,q:"Rappel du module 9 : quelles prochaines étapes fixes-tu avec les Robin ?",sc:[{who:"Gérard Robin",txt:"Bon, et maintenant ?"}],o:["Envoi de la synthèse chiffrée, rendez-vous dans quinze jours avec Émilie","Signature de tous les contrats aujourd'hui, pour ne pas perdre de temps","Attendre tranquillement qu'ils rappellent quand ils auront pris leur décision finale","Leur envoyer notre plaquette commerciale et des offres chaque semaine"],a:0,w:"Prochaines étapes claires, datées, qui intègrent l'influenceur. C'est le bloc Décision de la découverte et le P du closing B.R.C.P."},
{i:"n160_30",u:160,t:"tf",d:.55,q:"On peut placer en actions l'argent prévu pour un achat dans dix-huit mois si le client accepte le risque.",a:false,w:"L'horizon est une contrainte : à dix-huit mois, une baisse des marchés n'aurait pas le temps d'être rattrapée. Accepter le risque ne change pas le calendrier."},
{i:"n160_31",u:160,t:"mcq",d:.6,q:"Rappel du module 6 : « Qu'est-ce que ça vous apporterait de pouvoir aider vos petits-enfants ? » est une question :",o:["Need-payoff","Situation","Problème","Implication"],a:0,w:"Elle fait formuler la valeur attendue par le client : c'est la N de SPIN. La découverte et SPIN se nourrissent mutuellement."},
{i:"n160_32",u:160,t:"slider",d:.6,q:"Martine accepte au maximum 10 % de baisse temporaire ; Gérard 25 %. Quelle baisse maximale retiens-tu pour le couple, en % ?",min:0,max:40,step:5,a:10,tol:0,pre:"",un:" %",w:"On retient la plus prudente : 10 %. Un placement commun doit convenir aux deux, et c'est celui qui paniquerait qui ferait vendre au pire moment."}
