/*UNIT*/
{id:161,c:"NEGO",n:"Module 13",t:"Le cas Claire : 650 000 € « sans risque »",col:"--blue",ic:"💎",guide:`
<h3>Le brief client</h3>
<div class="formula">Claire Vasseur, 45 ans, dirigeante (menuiserie, 38 salariés)
650 000 € disponibles (vente d'un entrepôt)
Évoque : études des enfants, retraite, transmission
Veut : « placer sans risque »</div>
<div class="gstory">C'est le cas d'examen type, et c'est la vraie Claire, assise en face de toi. Elle a tout dit en trois phrases, et presque rien n'est encore clair. « Les études », mais lesquelles, quand, combien ? « La retraite », dans combien de temps, avec quel revenu voulu ? « La transmission », pourquoi, à qui, quand ? Et surtout : « sans risque ». Ton métier commence ici : transformer trois mots en un plan, par des questions.</div>
<h3>1. Les études des enfants</h3>
<ul><li><b>À quel horizon ?</b> Léo entre en prépa dans un an (court terme), Inès dans quatre ans (moyen terme).</li>
<li><b>Combien ?</b> Logement, frais de scolarité, école de commerce éventuelle : on chiffre avec elle.</li>
<li><b>Le prêt étudiant</b> : une option à connaître. Le prêt garanti par l'État (via Bpifrance) permet d'emprunter jusqu'à <b>20 000 €</b>, sans caution des parents, l'État garantissant 70 % du prêt, avec un remboursement qui peut être différé après les études. Pour une famille aisée, il peut servir d'outil pédagogique (responsabiliser l'étudiant) ou de choix financier si le placement rapporte plus que le coût du crédit. Mais ce n'est pas un objectif : c'est une piste à mettre sur la table.</li></ul>
<h3>2. La retraite</h3>
<ul><li><b>À quel horizon ?</b> Vers 62-64 ans : environ vingt ans (long terme).</li>
<li><b>Quel objectif ?</b> Quel revenu mensuel veut-elle ? Que deviendra l'entreprise (cession, transmission à un enfant) ? Sa retraite de dirigeante sera-t-elle suffisante ?</li></ul>
<h3>3. La transmission : quatre questions</h3>
<table><tr><th>Question</th><th>Pourquoi on la pose</th></tr>
<tr><td><b>À quel horizon ?</b></td><td>Pour choisir les outils (donations maintenant, ou assurance-vie et testament pour plus tard)</td></tr>
<tr><td><b>Pourquoi transmettre ?</b></td><td>Aider les enfants à démarrer, réduire les droits, protéger le conjoint, transmettre l'entreprise</td></tr>
<tr><td><b>À qui transmettre ?</b></td><td>Enfants, conjoint (séparation de biens : il n'est protégé que par ce qu'on prévoit), neveu repreneur</td></tr>
<tr><td><b>Quand transmettre ?</b></td><td>Donation de son vivant, ou au décès</td></tr></table>
<div class="gmnemo"><b>H.P.Q.Q. : « Hériter Proprement, Question de Quand ».</b> Horizon, Pourquoi, Qui, Quand. Pour chaque projet de Claire, tu te poses aussi la question de l'horizon : c'est lui qui décide du risque possible.</div>
<h3>4. « Sans risque » : pourquoi, et qu'est-ce que ça veut dire ?</h3>
<p>Première question, toujours : <b>« Pourquoi voulez-vous placer sans risque ? »</b> (réponse de Claire : la peur de 2020, la protection des enfants). Puis on explique honnêtement que chaque solution « sûre » a un risque ou un coût :</p>
<table><tr><th>Solution</th><th>Ce qui est sûr</th><th>Le risque ou le coût réel</th></tr>
<tr><td><b>Fonds euros</b></td><td>Capital garanti par l'assureur, gains acquis chaque année (effet cliquet)</td><td>Rendement modeste (2,63 % en moyenne en 2025), risque de défaillance de l'assureur couvert par le FGAP jusqu'à 70 000 €</td></tr>
<tr><td><b>Obligations</b></td><td>Coupons connus, remboursement à l'échéance si l'émetteur ne fait pas défaut</td><td>Risque de taux (le prix baisse si les taux montent avant l'échéance), risque de crédit de l'émetteur</td></tr>
<tr><td><b>Produit structuré</b></td><td>Capital protégé à l'échéance sous conditions</td><td>Protection conditionnelle (barrière, par exemple une baisse de l'indice de plus de 40 %), risque de défaut de la banque émettrice, complexité, durée longue</td></tr></table>
<div class="gtrap">Les notes rangent « obligations, fonds euros, produit structuré » sous « placer sans risque ». Aucun des trois n'est totalement sans risque. Le fonds euros est le plus proche (garanti par l'assureur), mais l'<b>inflation</b> peut rogner son rendement réel. Un produit structuré n'est jamais « garanti » au sens strict : on parle de capital <b>protégé</b>, sous conditions. Présenter ces produits comme sans risque serait un défaut de conseil.</div>
<h3>5. Les critères objectifs d'un arbitrage patrimonial</h3>
<p>Plus tard, quand tu proposeras à Claire de modifier son allocation (un arbitrage), il te faudra des raisons vérifiables, pas une intuition :</p>
<ul><li><b>L'évolution du contexte de marché</b> (taux, valorisations)</li><li><b>La prise de profit</b> (une ligne a beaucoup monté, on sécurise une partie)</li><li><b>L'évolution des liquidités</b> (Léo entre en prépa : il faut du disponible)</li><li><b>L'évolution de la fiscalité</b> (une loi de finances change la donne)</li></ul>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Poser les bonnes questions sur chaque projet du brief</li><li>Présenter le prêt étudiant garanti par l'État</li><li>Expliquer le risque réel du fonds euros, des obligations et d'un produit structuré</li><li>Citer quatre critères objectifs d'arbitrage</li><li>Proposer une allocation par poches selon les horizons</li></ul>`},
/*EXOS*/
{i:"n161_01",u:161,t:"story",d:.25,nw:"Le brief de Claire",q:"Quelle est ta première question sur « sans risque » ?",sc:[{who:"Claire Vasseur",txt:"Je veux placer ces 650 000 € sans aucun risque."}],o:["« Qu'est-ce qui rend la sécurité si importante pour vous aujourd'hui ? »","« Dans ce cas, je vous propose tout de suite notre fonds euros garanti. »","« Vous savez qu'aucun placement n'est vraiment sans risque, madame ? »","« Préférez-vous des obligations ou un produit structuré à capital protégé ? »"],a:0,w:"C'est la question des notes : pourquoi vouloir placer sans risque ? Derrière la position, l'intérêt : la peur de 2020 et la protection des enfants."},
{i:"n161_02",u:161,t:"multi",d:.3,nw:"Les quatre questions de la transmission",q:"Coche les quatre questions des notes sur la transmission.",o:["À quel horizon ?","Pourquoi transmettre ?","À qui transmettre ?","Quand transmettre ?","Combien voulez-vous garder ?"],a:[0,1,2,3],w:"H.P.Q.Q. : Horizon, Pourquoi, Qui, Quand."},
{i:"n161_03",u:161,t:"sort",d:.3,q:"Classe chaque projet de Claire selon son horizon.",bins:["Court terme","Moyen terme","Long terme"],it:[["Prépa de Léo l'an prochain",0],["Études d'Inès dans quatre ans",1],["Retraite dans une vingtaine d'années",2],["Transmission de l'entreprise",2],["Trésorerie de sécurité pour l'atelier",0]],w:"L'horizon décide de la part de risque possible. Le court terme reste disponible et sûr (et pour la prépa de Léo, le prêt étudiant garanti par l'État est une piste), le long terme peut accepter des fluctuations."},
{i:"n161_04",u:161,t:"slider",d:.3,nw:"Le prêt étudiant garanti par l'État",q:"Jusqu'à quel montant un étudiant peut-il emprunter avec le prêt garanti par l'État (en euros) ?",min:5000,max:50000,step:1000,a:20000,tol:0,pre:"",un:" €",w:"20 000 €, sans caution parentale ; l'État garantit 70 % via Bpifrance, et le remboursement peut être différé après les études."},
{i:"n161_05",u:161,t:"tf",d:.25,q:"Un produit structuré à capital protégé est un placement sans risque.",a:false,w:"La protection est conditionnelle (barrière) et il existe un risque de défaut de l'émetteur. On parle de capital protégé, pas garanti."},
{i:"n161_06",u:161,t:"match",d:.3,q:"Associe chaque solution « sûre » à son principal risque.",p:[["Fonds euros","Rendement modeste face à l'inflation"],["Obligations","Baisse de prix si les taux montent"],["Produit structuré","Protection conditionnelle et risque émetteur"],["Livret bancaire","Plafond et rendement faibles"]],w:"Chaque solution sûre a un risque ou un coût. L'expliquer, c'est le devoir de conseil."},
{i:"n161_07",u:161,t:"fill",d:.3,q:"Sur un fonds euros, les gains sont définitivement acquis chaque année : c'est l'effet ___.",o:["cliquet","levier","barrière","ciseau"],a:0,w:"Effet cliquet : une fois crédités, les intérêts ne peuvent plus être repris (sauf frais de gestion prélevés selon les contrats)."},
{i:"n161_08",u:161,t:"story",d:.35,q:"Comment présentes-tu le prêt étudiant à Claire ?",sc:[{who:"Claire Vasseur",txt:"Un prêt étudiant ? J'ai les moyens de payer les études de mes enfants !"}],o:["« Bien sûr. C'est une option : elle peut responsabiliser Léo ou laisser votre capital travailler. »","« Tous nos clients aisés le font, c'est devenu la norme pour les familles de dirigeants, vous savez. »","« Si vous ne prenez pas de prêt étudiant, vous perdrez forcément de l'argent sur vos placements actuels. »","« Oubliez le prêt étudiant, c'est réservé aux familles modestes qui n'ont pas d'autre solution. »"],a:0,w:"On accueille l'objection (orgueil touché) et on présente la piste honnêtement : un outil pédagogique ou un arbitrage financier, jamais une obligation."},
{i:"n161_09",u:161,t:"mcq",d:.35,q:"Pourquoi le prix d'une obligation baisse-t-il quand les taux montent ?",o:["Les nouvelles obligations rapportent plus, l'ancienne vaut moins","L'émetteur réduit alors les coupons déjà promis aux porteurs","L'État taxe davantage les anciennes obligations en circulation","La banque dépositaire prélève des frais de garde supplémentaires"],a:0,w:"C'est le risque de taux : si les nouvelles obligations offrent 4 %, personne ne paie le même prix pour une ancienne à 2 %. Tenue jusqu'à l'échéance, elle est remboursée au pair (hors défaut)."},
{i:"n161_10",u:161,t:"order",d:.35,q:"Remets dans l'ordre ta démarche face au brief de Claire.",it:["Demander pourquoi elle veut placer sans risque","Clarifier chaque projet : études, retraite, transmission","Fixer un horizon pour chaque projet","Proposer une poche par horizon","Expliquer le risque réel de chaque solution"],w:"Intérêt d'abord, puis projets, horizons, allocation, et transparence sur les risques."},
{i:"n161_11",u:161,t:"tiles",d:.35,q:"Reconstitue la question des notes sur la sécurité.",a:["Pourquoi","vouloir","placer","sans","risque"],dd:["combien","jamais","rendement"],w:"Toujours la première question : derrière « sans risque », il y a un intérêt à découvrir."},
{i:"n161_12",u:161,t:"multi",d:.4,nw:"Les critères objectifs d'arbitrage",q:"Quels sont les critères objectifs d'un arbitrage patrimonial cités par les notes ?",o:["L'évolution du contexte de marché","La prise de profit","L'évolution des liquidités","L'évolution de la fiscalité","L'intuition du conseiller"],a:[0,1,2,3],w:"Quatre critères vérifiables. L'intuition n'est pas un critère objectif : elle ne se justifie pas face au client ni face à un contrôle."},
{i:"n161_13",u:161,t:"story",d:.4,q:"Quel critère justifie un arbitrage dans deux ans ?",ctx:"Deux ans ont passé. La poche actions de Claire a pris 35 %. Inès entre en école dans un an.",sc:[{who:"Claire Vasseur",txt:"Pourquoi toucher à quelque chose qui marche ?"}],o:["La prise de profit et le besoin de liquidités pour Inès","L'intuition que les marchés vont forcément baisser bientôt","Le lancement d'un nouveau fonds maison par la banque","L'envie de générer des frais d'arbitrage"],a:0,w:"Deux critères objectifs : sécuriser une partie des gains, et rendre disponible l'argent des études d'Inès (horizon devenu court)."},
{i:"n161_14",u:161,t:"tf",d:.35,q:"Marié sous séparation de biens, Olivier est automatiquement protégé par la vente de l'entrepôt de Claire.",a:false,w:"En séparation de biens, les 650 000 € appartiennent à Claire seule. Olivier ne sera protégé que par ce qu'elle prévoit : donation entre époux, clause bénéficiaire, testament."},
{i:"n161_15",u:161,t:"num",d:.4,q:"Tu proposes une poche de court terme égale à la prépa de Léo (40 000 €) plus six mois de trésorerie de sécurité pour l'atelier (80 000 €). Quel montant reste-t-il pour le moyen et le long terme, en euros ?",a:530000,tol:1,un:" €",h:"650 000 moins la poche court terme",w:"650 000 − 120 000 = 530 000 €. Les contraintes et les horizons dessinent l'allocation avant de choisir les produits."},
{i:"n161_16",u:161,t:"story",d:.45,q:"Que réponds-tu sur le produit structuré ?",sc:[{who:"Claire Vasseur",txt:"Mon expert-comptable m'a parlé d'un produit structuré « garanti ». C'est bien sans risque ?"}],o:["« Il est protégé sous conditions : au-delà de 40 % de baisse de l'indice, ou si l'émetteur fait défaut, vous perdez. »","« Oui, c'est garanti à 100 %, sinon votre expert-comptable ne vous l'aurait jamais recommandé en premier. »","« Non, c'est un produit très risqué, il faut absolument l'éviter dans votre cas, madame. »","« Oui, il est garanti par le fonds de garantie des dépôts bancaires jusqu'à 100 000 € par personne. »"],a:0,w:"On explique la protection conditionnelle et le risque émetteur, sans diaboliser. Le FGDR couvre les dépôts bancaires, pas les produits structurés."},
{i:"n161_17",u:161,t:"fill",d:.4,q:"Dans un produit structuré, on parle de capital ___ et non garanti, car la protection dépend de conditions.",o:["protégé","assuré","bloqué","certifié"],a:0,w:"Protégé sous conditions (barrière), et exposé au risque de défaut de l'émetteur. Le mot garanti serait trompeur."},
{i:"n161_18",u:161,t:"mcq",d:.45,q:"Rappel du module 5 : pourquoi valider ta compréhension avant de proposer une allocation à Claire ?",o:["Pour que le conseil soit en réelle adéquation avec sa situation","Pour lui faire signer plus vite l'ensemble des documents","Pour vérifier qu'elle a bien lu toutes nos brochures commerciales","Pour respecter le temps de rendez-vous fixé par la direction de l'agence"],a:0,w:"C'est la réponse des notes. Un conseil fondé sur un malentendu (par exemple sur l'horizon des études d'Inès) est inadapté."},
{i:"n161_19",u:161,t:"sort",d:.45,q:"Pour chaque poche de Claire, choisis la solution la plus adaptée.",bins:["Livrets et fonds euros","Assurance-vie diversifiée","PER"],it:[["Prépa de Léo l'an prochain",0],["Trésorerie de sécurité de l'atelier",0],["Transmission aux enfants à long terme",1],["Revenus de retraite dans vingt ans, avec déduction fiscale",2],["Études d'Inès dans quatre ans, en restant prudente",0]],w:"Court terme : disponibilité et sécurité. Long terme : diversification. Retraite avec forte tranche d'imposition : le PER a du sens, à chiffrer."},
{i:"n161_20",u:161,t:"story",d:.45,q:"Rappel du module 7 : quels leviers SONCAS utilises-tu dans ta proposition à Claire ?",sc:[{who:"Claire Vasseur",txt:"Je me suis battue pour cette boîte. Je ne veux pas tout risquer maintenant."}],o:["Sécurité (protéger) et Orgueil (reconnaître son parcours)","Nouveauté (fonds innovants) et Argent (rendement élevé)","Confort (gestion pilotée) et Sympathie (la relation humaine)","Argent (frais bas) et Nouveauté (appli bancaire moderne)"],a:0,w:"Sa peur appelle la Sécurité ; sa fierté appelle l'Orgueil. Ta proposition doit protéger ET valoriser ce qu'elle a construit."},
{i:"n161_21",u:161,t:"tf",d:.45,q:"L'inflation est un risque même pour un placement dont le capital est garanti.",a:true,w:"Si le fonds euros rapporte 2,63 % et que l'inflation est plus forte, le pouvoir d'achat baisse. « Sans risque » en euros n'est pas « sans risque » en pouvoir d'achat."},
{i:"n161_22",u:161,t:"match",d:.5,q:"Associe chaque question de la transmission à la réponse de Claire.",p:[["À quel horizon ?","Dans une quinzaine d'années pour l'entreprise"],["Pourquoi ?","Que les enfants ne manquent de rien"],["À qui ?","Léo, Inès, et protéger Olivier"],["Quand ?","Commencer de son vivant, petit à petit"]],w:"Horizon, Pourquoi, Qui, Quand. Les réponses orientent vers les outils : donations, assurance-vie, donation entre époux."},
{i:"n161_23",u:161,t:"story",d:.5,q:"Hugo veut tout mettre sur le fonds euros « puisqu'elle veut du sans risque ». Que lui dis-tu ?",sc:[{who:"Hugo",txt:"Elle veut zéro risque, je mets 650 000 € sur le fonds euros, dossier réglé."}],o:["« Tu réponds à sa position, pas à ses intérêts : ses horizons longs justifient une part diversifiée. »","« Bonne idée, c'est exactement ce qu'elle demande, et le client a toujours raison, Hugo. »","« Mets plutôt tout en produit structuré, c'est plus rentable et presque aussi sûr qu'un fonds euros. »","« Mets tout sur un livret A, c'est encore plus sûr que le fonds euros et plus disponible. »"],a:0,w:"Hugo reste sur la position. Les intérêts de Claire (retraite à vingt ans, transmission) acceptent une part de risque maîtrisée. Et le livret A est plafonné à 22 950 €."},
{i:"n161_24",u:161,t:"num",d:.5,q:"Claire place 200 000 € sur un fonds euros à 2,63 %. Si l'inflation est de 2 %, quel est son gain réel approximatif la première année, en euros ?",a:1260,tol:5,un:" €",h:"(2,63 % − 2 %) × 200 000",w:"0,63 % × 200 000 ≈ 1 260 €. Le gain en euros (5 260 €) est bien plus grand que le gain de pouvoir d'achat : c'est le risque d'inflation, invisible sur le relevé."},
{i:"n161_25",u:161,t:"fill",d:.5,q:"Revendre une ligne qui a beaucoup monté pour sécuriser une partie des gains s'appelle une ___.",o:["prise de profit","prise de risque","liquidation","dévaluation"],a:0,w:"C'est l'un des quatre critères objectifs d'arbitrage des notes, avec le marché, les liquidités et la fiscalité."},
{i:"n161_26",u:161,t:"mcq",d:.5,q:"Rappel du module 11 : qui est un influenceur dans le dossier de Claire ?",o:["Jean-Pierre, son expert-comptable","Léo, qui entre en prépa l'an prochain","Sylvie Morel, ta directrice d'agence","L'assureur qui gère le fonds euros"],a:0,w:"Il pèse sur la décision sans signer. L'intégrer (envoi de l'analyse, réunion à trois) évite un « non » après le rendez-vous."},
{i:"n161_27",u:161,t:"story",d:.55,q:"Rappel du module 9 : quel closing fais-tu avec Claire ?",sc:[{who:"Claire Vasseur",txt:"Bon. On fait quoi, concrètement ?"}],o:["Besoins, risques de chaque poche, coûts en euros, et un second rendez-vous transmission","La signature immédiate de tous les contrats, pour sécuriser son épargne au plus vite","Un e-mail récapitulatif, puis on attend qu'elle nous rappelle quand elle sera enfin prête","Une remise sur les frais si elle signe aujourd'hui, pour la décider définitivement"],a:0,w:"B.R.C.P. : Besoins, Risques, Coûts, Prochaines étapes. Un placement de 650 000 € ne se signe pas dans l'urgence ni contre une remise de dernière minute."},
{i:"n161_28",u:161,t:"multi",d:.55,q:"Quelles informations te manquent encore pour conseiller la retraite de Claire ?",o:["Le revenu mensuel qu'elle souhaite","L'âge de départ envisagé","Le sort prévu pour l'entreprise","Ses droits à la retraite déjà acquis","La couleur de son bureau"],a:[0,1,2,3],w:"Retraite : horizon et objectif (notes). Pour une dirigeante, le devenir de l'entreprise est souvent son premier actif de retraite."},
{i:"n161_29",u:161,t:"tf",d:.55,q:"Le FGAP couvre l'épargne en assurance-vie jusqu'à 70 000 € par assuré et par assureur ; au-delà, on peut répartir entre plusieurs assureurs.",a:true,w:"Pour 650 000 €, la répartition entre assureurs est un argument de sécurité factuel, bien plus convaincant qu'une promesse."},
{i:"n161_30",u:161,t:"story",d:.6,q:"Rappel du module 2 : Claire menace de tout laisser sur son compte courant. Qu'est-ce que ça représente ?",sc:[{who:"Claire Vasseur",txt:"Si c'est trop compliqué, je laisse tout sur mon compte et on n'en parle plus."}],o:["Sa MESORE : une alternative réelle, mais coûteuse face à l'inflation","Son point cible : le résultat qu'elle espère au fond obtenir de nous","Sa ZOPA : la zone dans laquelle elle acceptera un accord à coup sûr","Une objection de fiscalité sur ses futurs rachats d'assurance-vie"],a:0,w:"Laisser tout sur un compte non rémunéré est sa solution de repli. La montrer chiffrée (perte de pouvoir d'achat) aide à évaluer honnêtement l'accord."},
{i:"n161_31",u:161,t:"order",d:.6,q:"Remets dans l'ordre les quatre questions de la transmission, comme dans le moyen mnémotechnique.",it:["Horizon","Pourquoi","Qui","Quand"],w:"H.P.Q.Q. : Hériter Proprement, Question de Quand."},
{i:"n161_32",u:161,t:"slider",d:.6,q:"Pour une retraite vers 64 ans, combien d'années d'horizon a Claire, qui a 45 ans ?",min:5,max:30,step:1,a:19,tol:1,pre:"",un:" ans",w:"64 − 45 = 19 ans : un horizon long, qui permet d'accepter une part de risque maîtrisée pour cette poche, contrairement à celle des études de Léo."}
