/*UNIT*/
{id:162,c:"NEGO",n:"Module 14",t:"Qui a le droit de conseiller quoi : CIF, IAS, IOBSP et les autres",col:"--blue",ic:"🎓",guide:`
<h3>Le cabinet de Thomas, trois casquettes</h3>
<div class="gstory">Marc Delorme te montre la carte de visite d'un conseiller en gestion de patrimoine indépendant : « Thomas Leroy, CGP. CIF, COA, COBSP, carte T. » Marc rigole : « C'est quoi, cette soupe de lettres ? Il m'a dit qu'il pouvait tout faire : mes placements, mon assurance, mon crédit pour le local de la pharmacie, et même m'aider à vendre mon appartement. » Il a raison : ces lettres sont les autorisations qui disent ce que Thomas a le droit de faire. Sans la bonne lettre, il n'aurait pas le droit de te faire concurrence sur ce terrain.</div>
<h3>Le principe : un statut par activité</h3>
<p>Le titre de « conseiller en gestion de patrimoine » (CGP) n'est pas protégé en lui-même. Ce qui compte, ce sont les <b>statuts réglementés</b> qu'il détient, chacun pour une activité précise. Tous s'enregistrent à l'<b>ORIAS</b> (le registre unique des intermédiaires en assurance, banque et finance), avec une inscription renouvelée chaque année. Un CGP en cumule souvent plusieurs.</p>
<table><tr><th>Statut</th><th>Activité</th><th>Obligation phare (notes)</th><th>Superviseur</th></tr>
<tr><td><b>CIF</b> : Conseiller en Investissements Financiers</td><td>Conseil sur les placements financiers (actions, fonds, produits structurés)</td><td>Lettre de mission et rapport écrit (déclaration d'adéquation)</td><td>AMF, via une association professionnelle agréée</td></tr>
<tr><td><b>IAS</b> : Intermédiaire en Assurance</td><td>Distribution d'assurance, dont l'assurance-vie</td><td>Recueil des exigences et besoins, devoir de conseil</td><td>ACPR</td></tr>
<tr><td><b>IOBSP</b> : Intermédiaire en Opérations de Banque et en Services de Paiement</td><td>Crédit, regroupement de crédits, opérations bancaires</td><td>Devoir d'explication sur le crédit et les opérations bancaires</td><td>ACPR</td></tr>
<tr><td><b>Autres</b></td><td>Agent immobilier, démarchage, courtage</td><td>Carte professionnelle, règles propres à chaque activité</td><td>Selon l'activité</td></tr></table>
<div class="gmnemo"><b>« Le CIF écrit, l'IAS écoute, l'IOBSP explique. »</b> Le CIF <b>écrit</b> (lettre de mission, rapport). L'IAS <b>écoute</b> les exigences et besoins avant de conseiller. L'IOBSP <b>explique</b> le crédit. Et pour les gendarmes : l'<b>AMF</b> surveille les <b>M</b>archés financiers (CIF), l'<b>ACPR</b> surveille les <b>A</b>ssurances et les <b>P</b>rêts (IAS, IOBSP).</div>
<h3>Le CIF en détail</h3>
<ul><li>Adhésion obligatoire à une <b>association professionnelle agréée par l'AMF</b>, qui le contrôle.</li>
<li><b>Document d'entrée en relation</b> (qui il est, ses statuts, sa rémunération), puis <b>lettre de mission</b> (ce qu'il va faire, pour quel prix), puis <b>rapport écrit</b> qui justifie le conseil en l'adaptant au profil (la <b>déclaration d'adéquation</b>).</li>
<li>Il peut être <b>indépendant</b> (il ne garde aucune commission des fournisseurs de produits et se fait payer en honoraires) ou <b>non indépendant</b> (il peut conserver des rétrocessions, en les déclarant).</li></ul>
<h3>L'IAS en détail</h3>
<p>L'IAS peut être courtier en assurance, agent général ou mandataire. Depuis la directive sur la distribution d'assurances (DDA, en vigueur depuis 2018), il doit d'abord recueillir les <b>exigences et besoins</b> du client et proposer un contrat cohérent avec eux. Pour l'assurance-vie, il doit fournir un <b>conseil</b> personnalisé et motivé. Il suit 15 heures de formation continue par an.</p>
<h3>L'IOBSP en détail</h3>
<p>Courtier en crédit ou mandataire d'une banque. Son obligation clé : le <b>devoir d'explication</b>, c'est-à-dire expliquer les caractéristiques du crédit, son coût total, les conséquences sur la situation de l'emprunteur et les risques en cas de défaut de paiement, pour que le client puisse choisir en connaissance de cause.</p>
<div class="gtrap">Deux précisions que les notes ne donnent pas. D'abord, depuis le <b>1er avril 2022</b>, les courtiers en assurance et en opérations de banque doivent adhérer à une <b>association professionnelle agréée par l'ACPR</b> (loi du 8 avril 2021). Ensuite, « autres » recouvre des activités bien réglementées : l'<b>agent immobilier</b> a besoin d'une carte professionnelle « transaction » (loi Hoguet), le <b>démarchage</b> bancaire et financier est encadré (délai de rétractation de 14 jours), et le <b>courtage</b> relève des statuts IAS ou IOBSP.</div>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Développer chaque sigle</li><li>Dire quel statut est nécessaire pour une activité</li><li>Associer chaque statut à son obligation phare et à son superviseur</li><li>Citer les documents du CIF dans l'ordre</li><li>Expliquer le rôle de l'ORIAS</li></ul>`},
/*EXOS*/
{i:"n162_01",u:162,t:"match",d:.25,nw:"Les statuts du CGP",q:"Associe chaque sigle à sa signification.",p:[["CIF","Conseiller en Investissements Financiers"],["IAS","Intermédiaire en Assurance"],["IOBSP","Intermédiaire en Opérations de Banque et en Services de Paiement"],["ORIAS","Registre unique des intermédiaires"]],w:"Un statut par activité, tous enregistrés à l'ORIAS."},
{i:"n162_02",u:162,t:"sort",d:.3,q:"Quel statut faut-il pour chaque activité ?",bins:["CIF","IAS","IOBSP"],it:[["Conseiller un portefeuille d'actions et de fonds",0],["Distribuer un contrat d'assurance-vie",1],["Négocier un prêt immobilier pour un client",2],["Recommander un produit structuré",0],["Proposer une assurance emprunteur",1],["Monter un regroupement de crédits",2]],w:"Placements financiers : CIF. Assurance : IAS. Crédit et opérations bancaires : IOBSP."},
{i:"n162_03",u:162,t:"fill",d:.3,q:"Le CIF doit remettre une lettre de ___ et un rapport écrit.",o:["mission","motivation","recommandation","candidature"],a:0,w:"Le CIF écrit : document d'entrée en relation, lettre de mission, rapport écrit (déclaration d'adéquation)."},
{i:"n162_04",u:162,t:"story",d:.3,q:"Que réponds-tu à Marc ?",sc:[{who:"Marc Delorme",txt:"CIF, COA, COBSP, carte T... C'est de la déco sur une carte de visite, non ?"}],o:["« Ce sont ses autorisations : chacune lui permet d'exercer une activité réglementée précise. »","« Oui, ce sont surtout des labels commerciaux pour impressionner les clients les plus fortunés. »","« Ce sont ses diplômes universitaires, obtenus pendant ses études de gestion de patrimoine. »","« Ce sont les noms des assureurs et des banques partenaires avec lesquels il travaille. »"],a:0,w:"Chaque sigle est un statut réglementé : CIF (placements), COA (courtier en assurance), COBSP (courtier en crédit), carte T (transaction immobilière)."},
{i:"n162_05",u:162,t:"tf",d:.25,q:"Le titre de conseiller en gestion de patrimoine est protégé en lui-même.",a:false,w:"Ce sont les statuts (CIF, IAS, IOBSP, carte T) qui sont réglementés. Le titre de CGP seul ne donne aucun droit."},
{i:"n162_06",u:162,t:"mcq",d:.3,q:"Quelle est l'obligation phare de l'IOBSP selon les notes ?",o:["Le devoir d'explication sur le crédit","La lettre de mission et le rapport écrit","Le recueil des exigences et besoins","La carte professionnelle de transaction"],a:0,w:"L'IOBSP explique : caractéristiques du crédit, coût total, conséquences et risques en cas de défaut."},
{i:"n162_07",u:162,t:"multi",d:.35,q:"Quelles obligations s'imposent à un IAS qui distribue une assurance-vie ?",o:["Recueillir les exigences et besoins du client","Fournir un conseil personnalisé et motivé","S'inscrire à l'ORIAS","Suivre une formation continue","Garantir un rendement minimum"],a:[0,1,2,3],w:"DDA : exigences et besoins, conseil, enregistrement, 15 heures de formation par an. Garantir un rendement est interdit."},
{i:"n162_08",u:162,t:"tiles",d:.3,q:"Reconstitue la phrase mémo des statuts.",a:["Le","CIF","écrit","l'IAS","écoute","l'IOBSP","explique"],dd:["vend","signe","garantit"],w:"Écrit : lettre de mission et rapport. Écoute : exigences et besoins. Explique : devoir d'explication sur le crédit."},
{i:"n162_09",u:162,t:"story",d:.35,q:"Quel superviseur contrôle quoi ?",sc:[{who:"Hugo",txt:"L'AMF, l'ACPR, c'est la même chose, non ?"}],o:["« L'AMF supervise les marchés et les CIF ; l'ACPR, les assureurs, les banques, les IAS et les IOBSP. »","« Oui, c'est le même organisme sous deux noms différents, un pour la France et un pour l'Europe. »","« L'AMF contrôle les banques et l'ACPR contrôle uniquement les compagnies d'assurance sur la vie. »","« L'ACPR s'occupe des marchés financiers, et l'AMF des prêts immobiliers accordés aux particuliers. »"],a:0,w:"L'AMF surveille les Marchés ; l'ACPR surveille les Assurances et les Prêts (et les banques)."},
{i:"n162_10",u:162,t:"order",d:.35,q:"Remets dans l'ordre les documents remis par un CIF.",it:["Document d'entrée en relation","Lettre de mission","Rapport écrit (déclaration d'adéquation)"],w:"Qui je suis, ce que je vais faire pour vous, puis pourquoi ce conseil vous correspond."},
{i:"n162_11",u:162,t:"tf",d:.35,q:"Depuis le 1er avril 2022, les courtiers en assurance et en crédit doivent adhérer à une association professionnelle agréée par l'ACPR.",a:true,w:"C'est la réforme du courtage (loi du 8 avril 2021). Les CIF, eux, adhéraient déjà à une association agréée par l'AMF."},
{i:"n162_12",u:162,t:"fill",d:.35,q:"L'IAS doit d'abord recueillir les ___ et besoins du client.",o:["exigences","revenus","objections","signatures"],a:0,w:"Exigences et besoins : c'est la première étape imposée par la DDA, avant toute proposition de contrat."},
{i:"n162_13",u:162,t:"sort",d:.4,q:"Classe chaque obligation selon le statut qu'elle concerne en premier.",bins:["CIF","IAS","IOBSP"],it:[["Rapport écrit justifiant l'adéquation",0],["Exigences et besoins avant le contrat",1],["Explication du coût total du crédit",2],["Adhésion à une association agréée par l'AMF",0],["15 heures de formation continue par an (DDA)",1]],w:"Le CIF écrit, l'IAS écoute, l'IOBSP explique."},
{i:"n162_14",u:162,t:"story",d:.4,q:"Thomas veut aider Marc à vendre son appartement contre une commission. De quoi a-t-il besoin ?",sc:[{who:"Marc Delorme",txt:"Il m'a dit qu'il pouvait aussi me trouver un acheteur."}],o:["D'une carte professionnelle « transaction », la carte T","De son statut de CIF, qui couvre aussi l'immobilier","De son statut d'IOBSP, puisqu'un crédit sera nécessaire","D'aucun statut, l'immobilier est une activité libre"],a:0,w:"La transaction immobilière exige la carte T (loi Hoguet). Ses statuts financiers ne l'autorisent pas à vendre un bien."},
{i:"n162_15",u:162,t:"mcq",d:.4,q:"Qu'est-ce qui distingue un CIF indépendant d'un CIF non indépendant ?",o:["L'indépendant ne garde aucune commission des fournisseurs","L'indépendant n'a pas besoin de lettre de mission écrite","L'indépendant n'a pas à être inscrit à l'ORIAS","L'indépendant ne peut conseiller que des actions cotées"],a:0,w:"L'indépendant se rémunère en honoraires et ne conserve pas de rétrocessions. Le non indépendant peut en garder, en les déclarant."},
{i:"n162_16",u:162,t:"story",d:.45,q:"Quelle explication doit donner l'IOBSP à Kevin ?",sc:[{who:"Kevin",txt:"Le courtier m'a juste donné la mensualité. C'est suffisant, non ?"}],o:["Non : il doit expliquer le coût total, les conséquences et les risques en cas d'impayés","Oui : la mensualité est la seule information obligatoire pour un prêt immobilier","Oui : c'est à la banque, pas au courtier, de donner toutes les autres explications utiles","Non : il doit surtout lui garantir le meilleur taux du marché, par écrit et signé"],a:0,w:"Devoir d'explication : caractéristiques, coût total, conséquences sur la situation, risques en cas de défaut. La mensualité seule ne suffit pas."},
{i:"n162_17",u:162,t:"num",d:.4,q:"Un IAS doit suivre 15 heures de formation continue par an. Combien d'heures sur un cycle de 3 ans ?",a:45,tol:0,un:" h",h:"15 × 3",w:"45 heures en trois ans. La formation continue garantit que le conseiller reste à jour sur la réglementation et les produits."},
{i:"n162_18",u:162,t:"tf",d:.45,q:"Un CIF peut distribuer une assurance-vie sans être aussi IAS.",a:false,w:"L'assurance-vie est un contrat d'assurance : il faut le statut d'IAS pour la distribuer, même si les supports sont des fonds financiers."},
{i:"n162_19",u:162,t:"multi",d:.45,q:"Que doit contenir le document d'entrée en relation d'un CIF ?",o:["Son identité et ses statuts","Son association professionnelle","Son mode de rémunération","Son numéro d'inscription ORIAS","La performance garantie de ses conseils"],a:[0,1,2,3],w:"Le client doit savoir qui il a en face de lui et comment il est payé. Aucune performance ne peut être garantie."},
{i:"n162_20",u:162,t:"story",d:.45,q:"Rappel du module 4 : Marc soupçonne un conflit d'intérêts. Quelle objection est-ce ?",sc:[{who:"Marc Delorme",txt:"Thomas, il touche combien sur ce qu'il me conseille ?"}],o:["La confiance, qui se traite par la transparence sur la rémunération","La fiscalité, qui se traite par une simulation nette sur dix ans","Les frais, qui se traitent par une remise immédiate sur la gestion","La liquidité, qui se traite par une poche disponible gardée à part"],a:0,w:"L'annulaire : la confiance. Le document d'entrée en relation doit justement dire comment le conseiller est rémunéré."},
{i:"n162_21",u:162,t:"mcq",d:.5,q:"Quel est le rôle de l'ORIAS ?",o:["Tenir le registre unique des intermédiaires","Fixer les taux des crédits immobiliers","Garantir l'épargne des clients en cas de faillite","Sanctionner les banques qui fraudent"],a:0,w:"ORIAS : Organisme pour le registre unique des intermédiaires en assurance, banque et finance. On vérifie un conseiller sur son site."},
{i:"n162_22",u:162,t:"match",d:.5,q:"Associe chaque activité réglementée « autre » à sa règle.",p:[["Agent immobilier","Carte professionnelle transaction (loi Hoguet)"],["Démarchage bancaire et financier","Délai de rétractation de 14 jours"],["Courtage en crédit","Statut d'IOBSP"],["Courtage en assurance","Statut d'IAS"]],w:"« Autres » ne veut pas dire libre : chaque activité a ses règles."},
{i:"n162_23",u:162,t:"story",d:.5,q:"Hugo veut conseiller un portefeuille d'actions à Yanis, en dehors de la banque, le week-end. Que lui dis-tu ?",sc:[{who:"Hugo",txt:"Je lui fais ça en extra, il me donnera un petit quelque chose."}],o:["« Sans statut de CIF et hors de la banque, c'est une activité réglementée exercée illégalement. »","« Pas de problème tant que Yanis est d'accord et que tu restes raisonnable sur ta rémunération. »","« C'est autorisé si tu ne lui conseilles que des fonds de notre banque et rien d'autre. »","« Tu peux le faire, mais seulement si Yanis signe une décharge de responsabilité écrite. »"],a:0,w:"Le conseil en investissement est réglementé. À titre personnel, sans statut et hors de l'employeur, Hugo exercerait illégalement."},
{i:"n162_24",u:162,t:"fill",d:.5,q:"Le rapport écrit du CIF justifie que le conseil est adapté au profil du client : on parle de déclaration d'___.",o:["adéquation","adhésion","intention","engagement"],a:0,w:"Adéquation : le conseil correspond aux objectifs, à la situation financière, aux connaissances et à la tolérance au risque du client."},
{i:"n162_25",u:162,t:"sort",d:.55,q:"Qui supervise chaque professionnel ?",bins:["AMF","ACPR"],it:[["Un CIF (via son association)",0],["Un courtier en assurance",1],["Un courtier en crédit",1],["Une compagnie d'assurance-vie",1],["Une société de gestion de fonds",0]],w:"L'AMF surveille les Marchés ; l'ACPR, les Assurances, les Prêts et les banques."},
{i:"n162_26",u:162,t:"tf",d:.55,q:"L'inscription à l'ORIAS doit être renouvelée chaque année.",a:true,w:"Renouvellement annuel : un conseiller peut perdre son inscription s'il ne remplit plus les conditions (assurance, association, formation)."},
{i:"n162_27",u:162,t:"story",d:.55,q:"Rappel du module 11 : lequel est un non négociable réglementaire pour Thomas, CIF ?",sc:[{who:"Marc Delorme",txt:"Pas besoin de me faire un rapport écrit, je vous fais confiance."}],o:["Le rapport écrit : il le lui doit, même si Marc y renonce","Le niveau de ses honoraires, qui est fixé par la loi","Le choix des fonds, qui est imposé par son association agréée","La durée du rendez-vous, fixée à une heure minimum par la loi"],a:0,w:"Le rapport écrit d'adéquation est obligatoire. Le client ne peut pas en dispenser le CIF, c'est une protection pour lui."},
{i:"n162_28",u:162,t:"multi",d:.6,q:"Pour conseiller Marc sur ses placements, son assurance-vie et le crédit du local de sa pharmacie, de quels statuts Thomas a-t-il besoin ?",o:["CIF","IAS","IOBSP","Carte T","Aucun, un CGP peut tout faire"],a:[0,1,2],w:"Placements (CIF), assurance-vie (IAS), crédit (IOBSP). La carte T ne serait utile que pour vendre un bien immobilier."},
{i:"n162_29",u:162,t:"mcq",d:.6,q:"Depuis quelle directive l'IAS doit-il recueillir les exigences et besoins du client ?",o:["La DDA, en vigueur depuis 2018","MIF 1, en vigueur depuis 2007","La loi Hoguet, votée en 1970","La loi Lemoine, votée en 2022"],a:0,w:"Directive sur la distribution d'assurances (DDA), appliquée en France depuis 2018. MIF concerne les services d'investissement, Hoguet l'immobilier, Lemoine l'assurance emprunteur."},
{i:"n162_30",u:162,t:"story",d:.6,q:"Rappel du module 5 : comment l'IAS recueille-t-il le mieux les exigences et besoins de Martine ?",sc:[{who:"Martine Robin",txt:"Je veux juste une assurance-vie, comme ma sœur."}],o:["Par des questions ouvertes, puis une reformulation qu'elle valide","En reprenant simplement le contrat de sa sœur, qui lui convient déjà","En lui faisant cocher une liste de produits sur une tablette","En lui demandant uniquement le montant qu'elle souhaite verser"],a:0,w:"Exigences et besoins se découvrent par l'écoute active : questions ouvertes, reformulation, revalidation. Copier le contrat de la sœur ignorerait sa situation."},
{i:"n162_31",u:162,t:"tiles",d:.6,q:"Reconstitue la phrase sur les superviseurs.",a:["L'AMF","surveille","les","marchés","l'ACPR","les","assurances","et","les","prêts"],dd:["taux","notaires","impôts"],w:"AMF : Marchés (et CIF). ACPR : Assurances, Prêts, banques (et IAS, IOBSP)."},
{i:"n162_32",u:162,t:"slider",d:.6,q:"Combien de jours de rétractation le client a-t-il après un démarchage bancaire ou financier ?",min:0,max:30,step:1,a:14,tol:0,pre:"",un:" jours",w:"14 jours calendaires. Ne pas confondre avec les 30 jours de renonciation de l'assurance-vie et les 10 jours de réflexion du crédit immobilier."}
