/*UNIT*/
{id:163,c:"NEGO",n:"Module 15",t:"KYC : la fiche client complète et le parcours de la relation",col:"--blue",ic:"🪪",guide:`
<h3>Le dossier qui a sauvé Sylvie</h3>
<div class="gstory">Il y a dix ans, un contrôleur de l'ACPR a passé trois jours à l'agence Graslin. Il a ouvert cinquante dossiers clients au hasard. Pour chacun, une question : « Montrez-moi que vous connaissiez ce client avant de lui conseiller quelque chose. » Les dossiers de Sylvie Morel étaient complets : pièce d'identité, justificatif de domicile, patrimoine, revenus, profil de risque signé, mises à jour datées. Ceux de son collègue de l'époque, non. Il a quitté la banque six mois plus tard. Sylvie te tend une fiche vierge : « La connaissance client, c'est ta ceinture de sécurité. On la boucle avant de démarrer. »</div>
<h3>KYC : Know Your Customer</h3>
<p><b>KYC</b> signifie « connais ton client ». C'est à la fois une obligation de conseil (on ne peut pas conseiller quelqu'un qu'on ne connaît pas) et une obligation de lutte contre le blanchiment (on doit savoir avec qui l'on travaille et d'où vient l'argent). Elle se matérialise dans une fiche en six blocs.</p>
<table><tr><th>Bloc</th><th>Contenu</th></tr>
<tr><td><b>Identité</b></td><td>Pièce d'identité officielle avec photo (CNI, passeport), justificatif de domicile (JDD) récent</td></tr>
<tr><td><b>Patrimoine</b></td><td>Immobilier, placements, liquidités</td></tr>
<tr><td><b>Vie personnelle</b></td><td>Famille, régime matrimonial, personnes à charge</td></tr>
<tr><td><b>Passif</b></td><td>Emprunts, garanties données (cautions, hypothèques), engagements</td></tr>
<tr><td><b>Profession et revenus</b></td><td>Activité, revenus, stabilité, charges</td></tr>
<tr><td><b>Profil investisseur</b></td><td>Horizon, risque, expérience, capacité de perte</td></tr></table>
<div class="gmnemo"><b>« I.P.V.P.P.P. : Il Protège Vraiment Pour Plus tard, Prudemment ».</b> Identité, Patrimoine, Vie personnelle, Passif, Profession, Profil. Ou plus simplement : <b>un I suivi de cinq P</b>. Si un P manque, le conseil boite.</div>
<div class="gtrap">Trois précisions sur les notes. « Immobilies » est une coquille pour <b>immobilier</b>. Le <b>justificatif de domicile</b> est une pratique de connaissance client très répandue, mais ce que la réglementation anti-blanchiment exige d'abord, c'est de <b>vérifier l'identité</b> sur un document officiel avec photo. Enfin, pour une société (comme la menuiserie de Claire), il faut aussi l'extrait Kbis et identifier le <b>bénéficiaire effectif</b> : la personne qui détient, directement ou non, plus de 25 % du capital ou des droits de vote, ou qui contrôle la société.</div>
<h3>Le passif, le bloc qu'on oublie</h3>
<p>Un client peut avoir 650 000 € à placer et s'être porté <b>caution</b> du prêt de son entreprise pour 300 000 €. Ce n'est pas une dette aujourd'hui, c'est un <b>engagement</b> : si l'entreprise ne paie plus, la banque se tournera vers lui. Sa vraie capacité de perte est donc bien plus faible qu'elle n'en a l'air.</p>
<h3>Origine des fonds et origine du patrimoine</h3>
<table><tr><th></th><th>Origine des fonds</th><th>Origine du patrimoine</th></tr>
<tr><td>Question</td><td>D'où viennent les sommes versées aujourd'hui ?</td><td>Comment le client a-t-il constitué sa richesse globale ?</td></tr>
<tr><td>Pour Claire</td><td>Les 650 000 € viennent de la vente de l'entrepôt (acte de vente)</td><td>Vingt ans de dirigeante, rémunérations, dividendes, un héritage</td></tr>
<tr><td>Justificatif</td><td>Acte de vente, relevé, avis de succession, contrat</td><td>Cohérence d'ensemble entre revenus, âge, métier et patrimoine</td></tr></table>
<div class="gmnemo"><b>Le robinet et la baignoire.</b> L'origine des <b>fonds</b>, c'est le robinet : d'où vient l'eau qui coule maintenant ? L'origine du <b>patrimoine</b>, c'est la baignoire : comment s'est-elle remplie au fil des années ? Une baignoire pleine chez un client de 25 ans sans revenus, ça doit poser question.</div>
<h3>Le parcours client : la connaissance vit dans le temps</h3>
<div class="formula">1. Entrée en relation   : identification, fiche KYC, profil
2. Mise à jour         : actualiser la fiche (fréquence selon le risque)
3. Suivi des opérations: vérifier que les opérations collent au profil
4. Réexamen du risque  : revoir le niveau de risque après un changement</div>
<p>La connaissance client n'est pas une photo prise une fois, c'est un film. Un client dont la situation change (vente d'entreprise, divorce, héritage, expatriation) doit voir sa fiche et son profil mis à jour. Plus le risque est élevé, plus la mise à jour est fréquente.</p>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Citer les six blocs de la fiche et leur contenu</li><li>Distinguer origine des fonds et origine du patrimoine, avec un exemple</li><li>Dire ce qu'est un bénéficiaire effectif</li><li>Remettre les quatre étapes du parcours client dans l'ordre</li><li>Repérer un engagement caché dans le passif</li></ul>`},
/*EXOS*/
{i:"n163_01",u:163,t:"sort",d:.25,nw:"La fiche KYC",q:"Range chaque information dans le bon bloc de la fiche KYC.",bins:["Identité","Patrimoine","Vie personnelle","Passif","Profession","Profil"],it:[["Carte nationale d'identité",0],["Appartement locatif à Rezé",1],["Mariée sous séparation de biens",2],["Caution du prêt de l'entreprise",3],["Dirigeante, 9 000 € net par mois",4],["Horizon de placement de quinze ans",5]],w:"Un I suivi de cinq P : Identité (CNI et justificatif de domicile), Patrimoine, Vie personnelle (famille, régime matrimonial), Passif, Profession et revenus, Profil investisseur."},
{i:"n163_02",u:163,t:"fill",d:.25,q:"KYC signifie Know Your ___ : connais ton client.",o:["Customer","Company","Contract","Capital"],a:0,w:"Connaissance client : obligation de conseil (adéquation) et de lutte contre le blanchiment."},
{i:"n163_03",u:163,t:"match",d:.3,nw:"Origine des fonds et du patrimoine",q:"Associe chaque notion à sa question.",p:[["Origine des fonds","D'où viennent les sommes versées aujourd'hui ?"],["Origine du patrimoine","Comment la richesse globale s'est-elle constituée ?"],["Bénéficiaire effectif","Qui contrôle réellement la société ?"],["Capacité de perte","Combien peut-il perdre sans que sa vie change ?"]],w:"Le robinet (les fonds qui arrivent) et la baignoire (le patrimoine accumulé)."},
{i:"n163_04",u:163,t:"story",d:.3,q:"Quel justificatif demandes-tu pour les 650 000 € de Claire ?",sc:[{who:"Claire Vasseur",txt:"C'est l'argent de la vente de mon entrepôt de Carquefou, en mars."}],o:["L'acte de vente de l'entrepôt ou le relevé montrant le versement du notaire","Aucun : une cliente connue depuis dix ans n'a pas à justifier ses fonds","Une attestation sur l'honneur rédigée et signée par Claire elle-même","Ses trois derniers bulletins de salaire en tant que dirigeante de la société"],a:0,w:"L'origine des fonds se justifie par un document probant : acte de vente, relevé du virement du notaire. Les bulletins de salaire ne prouvent pas l'origine de 650 000 €."},
{i:"n163_05",u:163,t:"tf",d:.25,q:"Se porter caution du prêt de son entreprise est un engagement à inscrire au passif de la fiche client.",a:true,w:"Ce n'est pas une dette aujourd'hui, mais un engagement qui peut le devenir. Il réduit la vraie capacité de perte du client."},
{i:"n163_06",u:163,t:"order",d:.3,nw:"Le parcours client",q:"Remets dans l'ordre les étapes du parcours client.",it:["Entrée en relation","Mise à jour","Suivi des opérations","Réexamen du risque"],w:"La connaissance client est un film, pas une photo : on identifie, on actualise, on surveille, on réévalue."},
{i:"n163_07",u:163,t:"multi",d:.35,q:"Quels éléments composent le profil investisseur selon les notes ?",o:["L'horizon","Le risque","L'expérience","La capacité de perte","Le régime matrimonial"],a:[0,1,2,3],w:"Horizon, risque, expérience, capacité de perte. Le régime matrimonial relève de la vie personnelle."},
{i:"n163_08",u:163,t:"mcq",d:.3,q:"Qui est le bénéficiaire effectif d'une société ?",o:["La personne qui détient plus de 25 % ou qui la contrôle","Le salarié le mieux payé de toute la société","L'expert-comptable qui tient les comptes annuels","Le client principal, qui fait le plus gros chiffre"],a:0,w:"Plus de 25 % du capital ou des droits de vote, directement ou indirectement, ou le contrôle. Pour la menuiserie, c'est Claire."},
{i:"n163_09",u:163,t:"story",d:.35,q:"Que fais-tu de cette nouvelle information ?",ctx:"Six mois après l'entrée en relation, Claire t'annonce qu'elle divorce d'Olivier.",sc:[{who:"Claire Vasseur",txt:"Ça ne change rien à mes placements, si ?"}],o:["Je mets à jour sa fiche et je réexamine son profil et ses objectifs","Rien : sa fiche a été remplie il y a six mois, elle reste donc valable","Je note l'information dans un coin, on verra à la prochaine revue","Je lui conseille d'attendre la fin du divorce pour me recontacter"],a:0,w:"Un divorce change la vie personnelle, le patrimoine, parfois les objectifs (transmission, protection). C'est une mise à jour et un réexamen, sans attendre."},
{i:"n163_10",u:163,t:"tiles",d:.35,q:"Reconstitue l'image de l'origine des fonds.",a:["L'origine","des","fonds","c'est","le","robinet"],dd:["baignoire","compte","toujours"],w:"Le robinet : d'où vient l'eau qui coule maintenant. La baignoire, c'est le patrimoine accumulé."},
{i:"n163_11",u:163,t:"sort",d:.4,q:"Classe chaque élément : origine des fonds ou origine du patrimoine ?",bins:["Origine des fonds","Origine du patrimoine"],it:[["Le virement du notaire après la vente",0],["Vingt ans de rémunération de dirigeante",1],["Un héritage reçu en 2012",1],["Le chèque de 30 000 € déposé ce matin",0],["Des dividendes réguliers de l'entreprise",1]],w:"Fonds : la somme précise versée maintenant. Patrimoine : l'histoire de la richesse accumulée."},
{i:"n163_12",u:163,t:"tf",d:.35,q:"Une fois la fiche KYC remplie à l'entrée en relation, elle n'a plus besoin d'être mise à jour.",a:false,w:"Mise à jour, suivi, réexamen : la connaissance client vit dans le temps. Sa fréquence dépend du niveau de risque."},
{i:"n163_13",u:163,t:"story",d:.4,q:"Qu'est-ce qui doit t'interroger dans ce dossier ?",ctx:"Un nouveau client de 24 ans, sans emploi déclaré, veut verser 400 000 € sur une assurance-vie. Il n'a pas d'héritage connu.",sc:[{who:"Le client",txt:"C'est mon argent, je n'ai pas à me justifier."}],o:["L'incohérence entre son âge, ses revenus et l'origine du patrimoine","Le choix de l'assurance-vie plutôt que d'un compte-titres classique","Le fait qu'il n'ait pas encore choisi ses unités de compte","Son refus de prendre un rendez-vous de suivi dans six mois"],a:0,w:"Une baignoire pleine sans robinet visible : l'origine du patrimoine n'est pas cohérente. Il faut des justificatifs ; à défaut, on applique la procédure LCB-FT (module 16)."},
{i:"n163_14",u:163,t:"fill",d:.35,q:"Pour un client personne morale, on demande notamment l'extrait ___.",o:["Kbis","de naissance","de casier judiciaire","d'acte notarié"],a:0,w:"L'extrait Kbis identifie la société (dénomination, siège, dirigeants). On identifie aussi le bénéficiaire effectif."},
{i:"n163_15",u:163,t:"num",d:.4,q:"Claire a 650 000 € de placements et 250 000 € sur ses comptes. Elle s'est portée caution à hauteur de 300 000 € pour l'entreprise. Si la caution était appelée en totalité, combien lui resterait-il, en euros ?",a:600000,tol:1,un:" €",h:"Actif financier total moins l'engagement",w:"900 000 − 300 000 = 600 000 €. Le passif (engagements) change la vraie capacité de perte : c'est pour cela qu'il figure dans la fiche."},
{i:"n163_16",u:163,t:"mcq",d:.4,q:"Rappel du module 12 : la capacité de perte est-elle objective ou subjective ?",o:["Objective : elle se calcule avec patrimoine, revenus et charges","Subjective : elle dépend avant tout de ce que le client ressent","Réglementaire : elle est fixée par un barème officiel de l'AMF","Commerciale : elle est fixée par la banque selon le produit"],a:0,w:"Objective. La tolérance, elle, est subjective. Le passif (engagements, dettes) pèse directement sur la capacité."},
{i:"n163_17",u:163,t:"story",d:.45,q:"Que réponds-tu à Hugo ?",sc:[{who:"Hugo",txt:"Marc, on le connaît depuis quinze ans. Je ne vais pas lui redemander sa carte d'identité, ce serait vexant."}],o:["« Si elle est périmée ou si sa situation a changé, la mise à jour est obligatoire, avec tact. »","« Tu as raison, un client ancien est dispensé de toute mise à jour de ses justificatifs. »","« Demande-la par e-mail sans aucune explication, comme ça tu n'as pas à lui en parler en face. »","« Remplis toi-même les informations manquantes de mémoire, tu le connais déjà assez bien. »"],a:0,w:"L'ancienneté ne dispense pas de la mise à jour (pièce d'identité valide, justificatif de domicile récent, situation actuelle). On l'explique comme une protection commune, avec tact : c'est aussi une affaire de relation (levier Sympathie)."},
{i:"n163_18",u:163,t:"multi",d:.45,q:"Que contient le bloc Profession et revenus selon les notes ?",o:["L'activité","Les revenus","La stabilité des revenus","Les charges","Les biens immobiliers"],a:[0,1,2,3],w:"Activité, revenus, stabilité, charges. Les biens immobiliers relèvent du bloc Patrimoine."},
{i:"n163_19",u:163,t:"tf",d:.45,q:"Vérifier l'identité du client sur un document officiel avec photo est l'exigence première de la réglementation anti-blanchiment.",a:true,w:"L'identification et la vérification d'identité passent avant tout. Le justificatif de domicile complète la connaissance client."},
{i:"n163_20",u:163,t:"story",d:.45,q:"Rappel du module 11 : le KYC est-il négociable avec un client pressé ?",sc:[{who:"Marc Delorme",txt:"Vos papiers, on verra plus tard. Faites le virement maintenant."}],o:["Non : c'est un non négociable réglementaire, on le fait avant l'opération","Oui : pour un bon client, on peut toujours régulariser dans les trois mois","Oui : si la directrice donne son accord écrit, c'est tout à fait autorisé","Non, sauf si le montant versé reste inférieur à 100 000 €"],a:0,w:"L'identification (pièce d'identité, justificatif de domicile) et la connaissance client précèdent l'opération. Aucune exception commerciale n'est possible."},
{i:"n163_21",u:163,t:"match",d:.5,q:"Associe chaque bloc de la fiche à un exemple chez les Robin.",p:[["Vie personnelle","Mariés sans contrat, trois petits-enfants"],["Patrimoine","Maison payée et 180 000 € de livrets"],["Passif","Aucun crédit en cours"],["Profil investisseur","Horizon court, tolérance faible"]],w:"Un I suivi de cinq P. Le régime matrimonial des Robin (communauté légale) compte pour la transmission. Même un passif vide doit être renseigné : « aucun » est une information."},
{i:"n163_22",u:163,t:"fill",d:.5,q:"Selon la réglementation, la fréquence de mise à jour de la fiche dépend du niveau de ___ du client.",o:["risque","fortune","fidélité","ancienneté"],a:0,w:"Approche par les risques : plus le risque est élevé, plus la mise à jour est fréquente."},
{i:"n163_23",u:163,t:"story",d:.5,q:"Quelle opération détonne avec le profil de Martine ?",ctx:"Martine Robin, profil prudent, verse habituellement 200 € par mois sur son livret.",sc:[{who:"Toi",me:true,txt:"(tu regardes le suivi de ses opérations)"}],o:["Un dépôt de 45 000 € en espèces, sans explication","Un virement de 200 € ce mois-ci vers son livret A","Un retrait de 60 € au distributeur de son quartier","Le prélèvement mensuel de sa facture d'électricité"],a:0,w:"Le suivi des opérations sert à repérer ce qui ne colle pas au profil. Un gros dépôt en espèces inexpliqué appelle des questions, puis la procédure LCB-FT si besoin."},
{i:"n163_24",u:163,t:"sort",d:.5,q:"Classe chaque action dans la bonne étape du parcours client.",bins:["Entrée en relation","Mise à jour","Suivi des opérations","Réexamen du risque"],it:[["Vérifier la pièce d'identité et remplir la fiche",0],["Actualiser la fiche après un déménagement",1],["Repérer un virement inhabituel vers l'étranger",2],["Revoir le niveau de risque après la vente de l'entreprise",3]],w:"Identifier, actualiser, surveiller, réévaluer."},
{i:"n163_25",u:163,t:"mcq",d:.55,q:"Pourquoi le KYC sert-il aussi le devoir de conseil ?",o:["On ne peut conseiller de façon adaptée qu'un client qu'on connaît","Il permet surtout de vendre plus de produits au même client","Il remplace entièrement le questionnaire de profil de risque","Il dispense de remettre les documents précontractuels"],a:0,w:"KYC et adéquation sont liés : sans connaissance de la situation, des objectifs et du profil, aucun conseil ne peut être adapté."},
{i:"n163_26",u:163,t:"story",d:.55,q:"Rappel du module 5 : comment demandes-tu à Claire des informations sur son passif sans la braquer ?",sc:[{who:"Claire Vasseur",txt:"Pourquoi vous voulez savoir si j'ai des cautions ? C'est privé."}],o:["« Pour bien protéger ce que vous avez construit, j'ai besoin de voir les risques qui pèsent sur vous. »","« C'est obligatoire, sinon je ne pourrai rien faire pour vous, c'est la réglementation, désolé. »","« Tous mes clients me donnent ces informations sans discuter, vous savez, c'est tout à fait habituel. »","« Ce n'est pas grave du tout, on peut très bien faire le dossier sans cette information-là. »"],a:0,w:"On relie la question à son intérêt (protéger, levier Sécurité) : c'est l'étape Relier des 4R. Invoquer la seule contrainte ou comparer aux autres clients crispe."},
{i:"n163_27",u:163,t:"tf",d:.55,q:"L'origine du patrimoine s'apprécie par la cohérence entre l'âge, le métier, les revenus et la richesse du client.",a:true,w:"La baignoire doit correspondre aux robinets connus : revenus, héritages, ventes. Une incohérence appelle des justificatifs."},
{i:"n163_28",u:163,t:"slider",d:.6,q:"Au-delà de quel pourcentage de détention du capital ou des droits de vote est-on bénéficiaire effectif d'une société ?",min:5,max:75,step:5,a:25,tol:0,pre:"",un:" %",w:"Plus de 25 %, directement ou indirectement, ou à défaut le contrôle de la société. On l'identifie pour savoir qui est vraiment derrière la personne morale."},
{i:"n163_29",u:163,t:"multi",d:.6,q:"Quels événements doivent déclencher une mise à jour de la fiche KYC ?",o:["La vente de l'entreprise","Un divorce","Un héritage important","Une expatriation","Un changement de numéro de téléphone seul"],a:[0,1,2,3],w:"Les moments de vie changent le patrimoine, la famille, les revenus et parfois le niveau de risque. Un simple changement de téléphone se met à jour, mais ne réévalue pas le profil."},
{i:"n163_30",u:163,t:"story",d:.6,q:"Rappel du module 14 : un CIF externe veut te transmettre un client. Que vérifies-tu d'abord sur ce CIF ?",sc:[{who:"Thomas Leroy",txt:"J'ai un client pour vous, je vous l'envoie demain."}],o:["Son inscription à l'ORIAS et son association professionnelle","Son chiffre d'affaires et le nombre total de ses clients","Son diplôme universitaire et son école de commerce d'origine","Son adresse personnelle et sa situation familiale"],a:0,w:"L'ORIAS et l'association agréée garantissent qu'il exerce légalement. Et le client transmis, lui, passera par ta propre entrée en relation KYC."},
{i:"n163_31",u:163,t:"order",d:.6,q:"Remets dans l'ordre les blocs de la fiche client, comme dans les notes.",it:["Identité","Patrimoine","Vie personnelle","Passif","Profession et revenus","Profil investisseur"],w:"Un I suivi de cinq P : Identité, Patrimoine, Vie personnelle, Passif, Profession et revenus, Profil investisseur."},
{i:"n163_32",u:163,t:"fill",d:.6,q:"« Comment le client a-t-il constitué sa richesse globale ? » est la question de l'origine du ___.",o:["patrimoine","virement","contrat","versement"],a:0,w:"Origine du patrimoine : la baignoire. Origine des fonds : le robinet d'aujourd'hui."}
