/*UNIT*/
{id:164,c:"NEGO",n:"Module 16",t:"LCB-FT : l'approche par les risques et le réflexe TRACFIN",col:"--blue",ic:"🚨",guide:`
<h3>Le client trop pressé</h3>
<div class="gstory">Un lundi matin, un homme élégant entre à l'agence sans rendez-vous. Stéphane Lacour, 41 ans, se présente comme marchand de voitures de collection. Il veut ouvrir une assurance-vie et y verser 180 000 €, « en plusieurs fois, en espèces surtout, les clients paient comme ça dans mon milieu ». Bénéficiaire : une société à Chypre. Il veut pouvoir tout racheter « dans trois mois, au cas où ». Et il est pressé. Hugo voit déjà la commission. Toi, tu vois quatre voyants rouges allumés en même temps. Ce module t'apprend à les voir, et surtout à savoir quoi faire ensuite.</div>
<h3>LCB-FT : de quoi parle-t-on ?</h3>
<p><b>LCB-FT</b> signifie Lutte Contre le Blanchiment de capitaux et le Financement du Terrorisme. Le <b>blanchiment</b>, c'est donner une apparence légale à de l'argent issu d'un crime ou d'un délit (trafic, fraude fiscale, corruption). Il se fait en trois étapes : le <b>placement</b> (faire entrer l'argent sale dans le circuit, souvent en espèces), l'<b>empilement</b> (multiplier les opérations pour brouiller les pistes), l'<b>intégration</b> (réinvestir l'argent devenu propre). Le <b>financement du terrorisme</b> peut, lui, utiliser de l'argent d'origine légale et de petits montants : c'est la destination qui pose problème.</p>
<h3>L'approche par les risques : quatre familles</h3>
<table><tr><th>Famille</th><th>Facteurs de risque (notes)</th><th>Chez Stéphane Lacour</th></tr>
<tr><td><b>Client</b></td><td>Profil, activité, comportement, PPE</td><td>Activité à forte circulation d'espèces, comportement pressé</td></tr>
<tr><td><b>Produit</b></td><td>Complexité, liquidité, anonymat, assurance-vie</td><td>Assurance-vie avec rachat total rapide envisagé</td></tr>
<tr><td><b>Géographie</b></td><td>Pays à risque, sanctions, flux internationaux</td><td>Bénéficiaire société à l'étranger, flux sortants</td></tr>
<tr><td><b>Opération</b></td><td>Montant, fréquence, bénéficiaire</td><td>180 000 € en espèces fractionnées, bénéficiaire sans lien apparent</td></tr></table>
<div class="gmnemo"><b>C.P.G.O. : « Chaque Placement Garde son Origine ».</b> Client, Produit, Géographie, Opération : les quatre voyants du tableau de bord. Un voyant allumé, on regarde de plus près. Plusieurs voyants allumés en même temps, on s'arrête.</div>
<p>Selon le niveau de risque, la vigilance est <b>simplifiée</b>, <b>standard</b> ou <b>renforcée</b>. L'assurance-vie figure dans les notes parce qu'elle permet de transmettre hors succession, de désigner des bénéficiaires tiers et de racheter : un circuit tentant pour recycler de l'argent.</p>
<h3>Les PPE : personnes politiquement exposées</h3>
<p>Une <b>PPE</b> exerce, ou a cessé d'exercer depuis <b>moins d'un an</b>, une fonction publique importante (chef d'État, ministre, parlementaire, haut magistrat, dirigeant de parti, ambassadeur, dirigeant d'entreprise publique...). Les membres de sa famille directe et ses proches associés sont aussi concernés. Elle impose une <b>vigilance complémentaire</b> : accord d'un membre de la direction pour entrer en relation, recherche de l'origine du patrimoine et des fonds, surveillance renforcée. Le délai d'un an n'est pas automatique : si le risque demeure, la vigilance est maintenue.</p>
<h3>En cas de soupçon : les quatre étapes</h3>
<div class="formula">1. Constat d'une anomalie   (opération incohérente avec le profil)
2. Analyse du dossier        (questions, justificatifs, historique)
3. Décision interne          (le déclarant TRACFIN de la banque tranche)
4. Déclaration à TRACFIN     (déclaration de soupçon)</div>
<p><b>TRACFIN</b> (Traitement du Renseignement et Action contre les Circuits FINanciers clandestins) est la cellule de renseignement financier du ministère de l'Économie. La <b>déclaration de soupçon</b> se fait sans attendre, en principe avant l'exécution de l'opération. Elle est <b>confidentielle</b> : il est interdit d'en informer le client (sous peine d'amende). Les documents de connaissance client et d'opérations se conservent <b>5 ans</b> après la fin de la relation.</p>
<div class="gtrap">Deux erreurs à ne jamais commettre. La première : croire qu'il faut une <b>preuve</b> pour déclarer. Il suffit d'un <b>soupçon</b> (on sait, on soupçonne ou on a de bonnes raisons de soupçonner), et c'est TRACFIN qui enquête. La seconde : prévenir le client (« attention, je vais devoir signaler votre opération »). C'est le <b>tipping off</b>, interdit et sanctionné. Et un conseiller ne décide pas seul de déclarer : il remonte l'anomalie au déclarant de sa banque, qui prend la décision interne.</div>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Développer LCB-FT et TRACFIN, citer les trois étapes du blanchiment</li><li>Classer un facteur de risque dans les quatre familles</li><li>Définir une PPE et la règle du délai d'un an</li><li>Dérouler les quatre étapes en cas de soupçon</li><li>Citer confidentialité, absence de preuve nécessaire et conservation 5 ans</li></ul>`},
/*EXOS*/
{i:"n164_01",u:164,t:"sort",d:.25,nw:"L'approche par les risques",q:"Classe chaque facteur dans sa famille de risque.",bins:["Client","Produit","Géographie","Opération"],it:[["Personne politiquement exposée",0],["Assurance-vie avec rachat rapide",1],["Virement vers un pays sous sanctions",2],["Dépôt en espèces fractionné",3],["Comportement pressé et fuyant",0],["Produit permettant l'anonymat",1]],w:"C.P.G.O. : Client, Produit, Géographie, Opération. Les quatre voyants du tableau de bord."},
{i:"n164_02",u:164,t:"fill",d:.25,q:"LCB-FT signifie Lutte Contre le Blanchiment de capitaux et le ___ du Terrorisme.",o:["Financement","Fichage","Filtrage","Fonctionnement"],a:0,w:"Deux fléaux : le blanchiment (argent sale rendu propre) et le financement du terrorisme (argent, parfois propre, envoyé à de mauvaises fins)."},
{i:"n164_03",u:164,t:"order",d:.3,nw:"En cas de soupçon",q:"Remets dans l'ordre les étapes en cas de soupçon.",it:["Constat d'une anomalie","Analyse du dossier","Décision interne","Déclaration à TRACFIN"],w:"On constate, on analyse, le déclarant de la banque décide, puis on déclare. Le conseiller ne décide pas seul."},
{i:"n164_04",u:164,t:"story",d:.3,q:"Que fais-tu face à Stéphane Lacour ?",sc:[{who:"Stéphane Lacour",txt:"180 000 € en espèces en plusieurs fois, bénéficiaire ma société à Chypre, et je veux pouvoir tout racheter dans trois mois. On peut faire vite ?"}],o:["Je pose des questions, demande des justificatifs et remonte l'anomalie au déclarant","J'ouvre le contrat tout de suite, il a l'air sérieux, poli et très bien habillé","Je lui dis que je vais devoir le signaler à TRACFIN s'il continue à insister ainsi","Je refuse sèchement et je lui demande de quitter l'agence sur-le-champ"],a:0,w:"Plusieurs voyants allumés : on analyse (questions, justificatifs) et on remonte au déclarant. Prévenir le client est interdit (tipping off)."},
{i:"n164_05",u:164,t:"tf",d:.25,q:"Pour faire une déclaration de soupçon, il faut une preuve du blanchiment.",a:false,w:"Un soupçon suffit : on sait, on soupçonne ou on a de bonnes raisons de soupçonner. C'est TRACFIN qui enquête."},
{i:"n164_06",u:164,t:"match",d:.3,q:"Associe chaque étape du blanchiment à sa description.",p:[["Placement","Faire entrer l'argent sale dans le circuit"],["Empilement","Multiplier les opérations pour brouiller les pistes"],["Intégration","Réinvestir l'argent devenu propre"],["Financement du terrorisme","Argent parfois légal, destination illégale"]],w:"Placement, empilement, intégration. Le financement du terrorisme se distingue par sa destination."},
{i:"n164_07",u:164,t:"mcq",d:.3,q:"Combien de temps une personne reste-t-elle PPE après avoir cessé sa fonction, au minimum ?",o:["Un an","Six mois","Cinq ans","Toute sa vie"],a:0,w:"Moins d'un an après la fin de la fonction (article R561-18 du CMF). Et si le risque demeure, la vigilance est maintenue au-delà."},
{i:"n164_08",u:164,t:"multi",d:.35,q:"Quels sont les facteurs de risque « produit » cités par les notes ?",o:["La complexité","La liquidité","L'anonymat","L'assurance-vie","La couleur du logo"],a:[0,1,2,3],w:"Un produit complexe, liquide, qui permet l'anonymat ou la transmission à des tiers (assurance-vie) attire les blanchisseurs."},
{i:"n164_09",u:164,t:"story",d:.35,q:"Hugo veut prévenir le client. Que lui dis-tu ?",sc:[{who:"Hugo",txt:"Je vais quand même dire à M. Lacour qu'on va sûrement le déclarer, c'est plus honnête."}],o:["« Surtout pas : informer le client d'une déclaration est interdit et sanctionné. »","« Bonne idée, la transparence avec le client est toujours la meilleure des politiques. »","« Préviens-le seulement par écrit, comme ça tu gardes une trace de ta démarche. »","« Tu peux le prévenir si le déclarant de la banque te donne son accord verbal. »"],a:0,w:"C'est le tipping off : la déclaration est confidentielle. L'honnêteté envers le client ne l'emporte jamais sur cette obligation légale."},
{i:"n164_10",u:164,t:"tiles",d:.3,q:"Reconstitue le moyen mnémotechnique des familles de risque.",a:["Chaque","Placement","Garde","son","Origine"],dd:["Prix","Toujours","Gain"],w:"Client, Produit, Géographie, Opération. Un voyant allumé, on regarde ; plusieurs voyants, on s'arrête et on analyse."},
{i:"n164_11",u:164,t:"fill",d:.35,q:"TRACFIN est la cellule de renseignement financier rattachée au ministère de l'___.",o:["Économie","Intérieur","Justice","Éducation"],a:0,w:"TRACFIN : Traitement du Renseignement et Action contre les Circuits FINanciers clandestins, service de Bercy."},
{i:"n164_12",u:164,t:"story",d:.4,q:"Paul Mercier a quitté son mandat de député il y a huit mois. Quel régime appliques-tu ?",sc:[{who:"Paul Mercier",txt:"Je ne suis plus député, je suis un client comme les autres maintenant."}],o:["Vigilance complémentaire : il est PPE jusqu'à un an après la fin de son mandat","Vigilance standard : il n'est plus député, il n'est donc plus du tout PPE","Vigilance simplifiée : un ancien élu présente toujours un risque très faible","Refus d'entrée en relation : on n'accepte jamais d'anciens parlementaires"],a:0,w:"Huit mois : moins d'un an, il reste PPE. Vigilance complémentaire, avec accord de la direction. Refuser par principe n'est pas la règle."},
{i:"n164_13",u:164,t:"tf",d:.35,q:"Les membres de la famille directe d'une PPE et ses proches associés sont aussi concernés par la vigilance complémentaire.",a:true,w:"L'argent de la corruption transite souvent par l'entourage. La vigilance s'étend donc à la famille et aux proches associés."},
{i:"n164_14",u:164,t:"slider",d:.4,q:"Combien d'années faut-il conserver les documents de connaissance client après la fin de la relation ?",min:1,max:15,step:1,a:5,tol:0,pre:"",un:" ans",w:"5 ans après la fin de la relation d'affaires (ou après l'opération pour un client occasionnel). C'est ce qui permet à TRACFIN de remonter une piste."},
{i:"n164_15",u:164,t:"sort",d:.4,q:"Classe chaque situation : vigilance standard ou vigilance renforcée ?",bins:["Standard","Renforcée"],it:[["Salariée qui verse 200 € par mois sur son livret",0],["Ancien ministre sorti du gouvernement il y a trois mois",1],["Virement important vers un pays sur liste grise",1],["Retraité qui domicilie sa pension",0],["Dépôts d'espèces répétés juste sous les seuils de contrôle",1]],w:"Le niveau de vigilance suit le niveau de risque : PPE, pays à risque (liste grise, sanctions), fractionnement suspect appellent la vigilance renforcée."},
{i:"n164_16",u:164,t:"mcq",d:.4,q:"Qui prend la décision de déclarer à TRACFIN dans une banque ?",o:["Le déclarant TRACFIN désigné par la banque","Le conseiller qui a vu passer l'opération","Le client, après une explication","La directrice d'agence, seule et sans avis"],a:0,w:"Le conseiller remonte l'anomalie ; le déclarant désigné (souvent au service conformité) analyse et décide. C'est l'étape « décision interne »."},
{i:"n164_17",u:164,t:"story",d:.45,q:"Rappel du module 15 : quelle question poses-tu d'abord à Stéphane Lacour ?",sc:[{who:"Stéphane Lacour",txt:"C'est de l'argent propre, je vous assure."}],o:["« Pouvez-vous me montrer d'où viennent ces sommes, factures ou relevés à l'appui ? »","« Je vous crois, mais pourquoi ne pas faire un simple virement plutôt, ce serait mieux ? »","« Combien de voitures de collection vendez-vous environ chaque année, en moyenne ? »","« Pourquoi avoir choisi Chypre pour votre société, c'est pour des raisons fiscales ? »"],a:0,w:"L'origine des fonds se justifie par des documents. Les autres questions ont leur place ensuite, mais la première est la preuve du robinet."},
{i:"n164_18",u:164,t:"multi",d:.45,q:"Quels signaux d'alerte présente l'opération de Stéphane Lacour ?",o:["Des espèces fractionnées","Un bénéficiaire étranger sans lien familial","Un rachat total envisagé à trois mois","Une urgence injustifiée","Un rendez-vous pris à l'avance"],a:[0,1,2,3],w:"Placement en espèces, transmission à un tiers opaque, sortie rapide, précipitation : plusieurs voyants à la fois. Prendre rendez-vous n'a rien de suspect."},
{i:"n164_19",u:164,t:"tf",d:.45,q:"Le financement du terrorisme peut utiliser de l'argent d'origine parfaitement légale.",a:true,w:"C'est ce qui le distingue du blanchiment : le problème est la destination des fonds. D'où la vigilance sur les flux et les bénéficiaires."},
{i:"n164_20",u:164,t:"story",d:.5,q:"Rappel du module 11 : Stéphane propose de doubler ses versements si tu passes sur les justificatifs. Que réponds-tu ?",sc:[{who:"Stéphane Lacour",txt:"Si on oublie la paperasse, je vous verse 400 000 € au lieu de 180 000."}],o:["« Les justificatifs sont un non négociable réglementaire, quel que soit le montant. »","« D'accord pour cette fois, à condition que vous fassiez les versements par virement. »","« Je dois demander à ma directrice, elle peut accepter pour un gros montant. »","« Pour 400 000 €, on peut en effet alléger un peu la procédure habituelle. »"],a:0,w:"Les non négociables ne se négocient pas, surtout contre plus d'argent. Cette proposition est d'ailleurs un signal d'alerte supplémentaire à remonter."},
{i:"n164_21",u:164,t:"fill",d:.5,q:"Informer le client qu'une déclaration de soupçon le concerne s'appelle le tipping ___.",o:["off","out","over","in"],a:0,w:"Tipping off : divulgation interdite et sanctionnée. La déclaration est strictement confidentielle."},
{i:"n164_22",u:164,t:"match",d:.5,q:"Associe chaque famille de risque à un exemple.",p:[["Client","Activité à forte circulation d'espèces"],["Produit","Assurance-vie rachetée juste après le versement"],["Géographie","Flux vers un pays sous sanctions"],["Opération","Montants fractionnés à haute fréquence"]],w:"Un facteur isolé n'est pas un soupçon ; plusieurs facteurs qui se cumulent le deviennent."},
{i:"n164_23",u:164,t:"story",d:.5,q:"Martine Robin dépose un chèque de 60 000 €. Que fais-tu ?",ctx:"Martine verse d'habitude 200 € par mois. Elle explique qu'il s'agit de la vente de la maison de sa mère décédée.",sc:[{who:"Martine Robin",txt:"C'est la part de la maison de maman."}],o:["Je demande l'acte de vente ou l'attestation du notaire, puis j'enregistre l'opération","Je déclare immédiatement à TRACFIN, puisque le montant est inhabituel pour elle","Je refuse le chèque, il est beaucoup trop important par rapport à son profil","Je l'encaisse sans rien demander, Martine est une cliente de confiance depuis longtemps"],a:0,w:"Une anomalie n'est pas un soupçon. On analyse : l'explication est cohérente et se justifie par un document. Si le justificatif existe, pas de déclaration."},
{i:"n164_24",u:164,t:"num",d:.5,q:"Un client dépose 9 500 € en espèces chaque semaine pendant 6 semaines. Quel montant total a-t-il déposé, en euros ?",a:57000,tol:1,un:" €",h:"9 500 × 6",w:"57 000 €, fractionnés pour rester sous 10 000 € à chaque dépôt : c'est le schéma type du placement par fractionnement (le « smurfing »). La fréquence est un facteur de risque « opération »."},
{i:"n164_25",u:164,t:"mcq",d:.55,q:"Rappel du module 14 : quelle autorité contrôle le respect des obligations LCB-FT des banques et assureurs ?",o:["L'ACPR","L'ORIAS","L'INSEE","La CNIL"],a:0,w:"L'ACPR contrôle les banques et les assureurs, y compris sur la LCB-FT. L'AMF fait de même pour les acteurs des marchés financiers."},
{i:"n164_26",u:164,t:"story",d:.55,q:"Le déclarant a transmis une déclaration. Stéphane Lacour revient demander où en est son dossier. Que réponds-tu ?",sc:[{who:"Stéphane Lacour",txt:"Alors, pourquoi mon contrat n'est pas encore ouvert ?"}],o:["« Votre dossier est en cours d'analyse, nous revenons vers vous. » Rien de plus.","« TRACFIN examine votre dossier en ce moment, c'est pour cela que tout est bloqué. »","« Ma direction vous soupçonne de quelque chose, je ne peux rien faire de plus pour vous. »","« Retirez votre demande, ce sera mieux pour vous, croyez-moi bien. »"],a:0,w:"Réponse neutre, sans rien laisser deviner : la déclaration est confidentielle. Évoquer TRACFIN ou un soupçon serait du tipping off."},
{i:"n164_27",u:164,t:"tf",d:.55,q:"L'assurance-vie figure parmi les produits à risque en LCB-FT, notamment parce qu'elle permet de transmettre des capitaux à des tiers.",a:true,w:"Bénéficiaires tiers, transmission hors succession, rachats, parfois un certain anonymat du bénéficiaire final : autant de possibilités de recyclage. D'où la vigilance sur les versements, rachats et bénéficiaires."},
{i:"n164_28",u:164,t:"sort",d:.55,q:"Classe chaque action : obligatoire ou interdite en LCB-FT ?",bins:["Obligatoire","Interdite"],it:[["Conserver les documents 5 ans",0],["Prévenir le client d'une déclaration",1],["Remonter une anomalie au déclarant",0],["Exécuter l'opération sans analyser des signaux graves",1],["Identifier le bénéficiaire effectif d'une société",0]],w:"Conserver, remonter, identifier : obligatoire. Divulguer une déclaration ou fermer les yeux : interdit."},
{i:"n164_29",u:164,t:"fill",d:.6,q:"Le niveau de vigilance peut être simplifié, standard ou ___.",o:["renforcé","suspendu","annulé","doublé"],a:0,w:"Il dépend du niveau de risque. PPE, pays à risque et opérations atypiques appellent la vigilance renforcée."},
{i:"n164_30",u:164,t:"story",d:.6,q:"Rappel du module 8 : Stéphane Lacour s'énerve contre tes questions. Comment accueilles-tu son objection ?",sc:[{who:"Stéphane Lacour",txt:"Vous me traitez de voleur, là ? Toutes ces questions, c'est insultant !"}],o:["« Je comprends que ça puisse agacer. Ces questions sont posées à tous les clients dans votre cas. »","« Si vous n'avez vraiment rien à cacher, vous ne devriez pas du tout vous énerver comme ça, monsieur. »","« Vous avez raison, je suis désolé, oublions ces questions et ouvrons tout de suite le contrat. »","« Calmez-vous immédiatement ou j'appelle la sécurité de l'agence pour vous raccompagner dehors. »"],a:0,w:"Accueillir sans céder : on reconnaît l'agacement et on présente la démarche comme une règle générale. Céder ou accuser sont deux fautes."},
{i:"n164_31",u:164,t:"multi",d:.6,q:"Quelles mesures composent la vigilance complémentaire pour une PPE ?",o:["Accord d'un membre de la direction pour entrer en relation","Recherche de l'origine du patrimoine et des fonds","Surveillance renforcée des opérations","Refus automatique de toute ouverture de compte","Information du client qu'il est « à risque »"],a:[0,1,2],w:"Accord de la direction, origine du patrimoine et des fonds, surveillance renforcée. On ne refuse pas par principe, et on ne stigmatise pas le client."},
{i:"n164_32",u:164,t:"tiles",d:.6,q:"Reconstitue la règle sur la déclaration.",a:["Un","soupçon","suffit","la","preuve","n'est","pas","nécessaire"],dd:["client","toujours","prévenir"],w:"On sait, on soupçonne ou on a de bonnes raisons de soupçonner : on déclare. L'enquête, c'est le travail de TRACFIN."}
