/*UNIT*/
{id:165,c:"NEGO",n:"Module 17",t:"Négocier un crédit immobilier : taux, assurance, frais, clauses",col:"--blue",ic:"🏠",guide:`
<h3>Kevin et Laura signent leur premier prêt</h3>
<div class="gstory">Kevin, infirmier au CHU (2 400 € net par mois), et Laura, graphiste (2 100 €), ont signé un compromis pour un deux-pièces à Rezé : 250 000 €, dont 30 000 € d'apport. Ils ont deux offres : la tienne et celle de la banque des parents de Kevin. Laura a préparé une liste : « taux, assurance, frais, et je ne sais plus quoi ». Ton travail : leur montrer tout ce qui se négocie vraiment, ce qui ne se négocie pas, et construire avec eux une offre qui tient sur vingt-cinq ans.</div>
<h3>Ce qui ne se négocie pas : le cadre</h3>
<table><tr><th>Règle</th><th>Contenu</th></tr>
<tr><td><b>Normes du HCSF</b> (Haut Conseil de stabilité financière)</td><td>Le taux d'effort ne doit pas dépasser <b>35 %</b> des revenus nets avant impôt, assurance comprise. La durée du prêt est limitée à <b>25 ans</b>, ou 27 ans si le différé est lié à des travaux ou à un achat sur plan. Les banques peuvent déroger à ces règles pour 20 % de leur production, surtout pour la résidence principale.</td></tr>
<tr><td><b>Taux d'usure</b></td><td>Le TAEG ne peut pas dépasser ce plafond légal, fixé par la Banque de France</td></tr>
<tr><td><b>Délai de réflexion</b></td><td>10 jours : l'offre ne peut être acceptée qu'à partir du 11e jour</td></tr></table>
<div class="formula">Taux d'effort = (mensualités de tous les crédits + assurance) / revenus nets mensuels
Kevin et Laura : 4 500 € × 35 % = 1 575 € de mensualité maximum</div>
<h3>Ce qui se négocie</h3>
<table><tr><th>Élément</th><th>Levier et règle</th></tr>
<tr><td><b>Le taux nominal</b></td><td>Profil, apport, épargne, et surtout une offre concurrente (la MESORE)</td></tr>
<tr><td><b>L'assurance emprunteur</b></td><td>La délégation d'assurance est possible dès la souscription. Depuis la <b>loi Lemoine</b> (2022), on peut résilier et changer d'assurance <b>à tout moment</b>, à garanties équivalentes. Il n'y a plus de questionnaire de santé si la part assurée par personne est de 200 000 € maximum et que le prêt se termine avant 60 ans. Le droit à l'oubli s'applique après 5 ans pour les cancers et l'hépatite C.</td></tr>
<tr><td><b>Les frais de dossier</b></td><td>Souvent réductibles, voire offerts</td></tr>
<tr><td><b>Les IRA</b> (indemnités de remboursement anticipé)</td><td>Plafond légal : 6 mois d'intérêts sur le capital remboursé, sans dépasser 3 % du capital restant dû. On peut négocier leur suppression dans l'offre. Elles ne sont pas dues en cas de vente liée à une mobilité professionnelle, au décès ou à la cessation forcée d'activité</td></tr>
<tr><td><b>La domiciliation des revenus</b></td><td>La banque peut l'exiger seulement en échange d'un avantage individualisé écrit dans l'offre. Depuis que le Conseil d'État a annulé en 2021 le décret qui la limitait à 10 ans, sa durée se négocie</td></tr>
<tr><td><b>Les options de souplesse</b></td><td>Modulation des échéances, report, transférabilité du prêt en cas de revente</td></tr></table>
<div class="gmnemo"><b>« T.A.F.I.D.O. : Tout A un Facteur Invisible Dans l'Offre ».</b> Taux, Assurance, Frais, IRA, Domiciliation, Options. Six lignes à regarder, pas une seule. Et le juge de paix : le <b>TAEG</b> (taux annuel effectif global), qui additionne les intérêts, l'assurance exigée, les frais de dossier, la garantie et les frais de courtage. On compare deux offres au TAEG et au coût total, jamais au seul taux nominal.</div>
<div class="gtrap">Erreur classique : comparer deux offres sur le seul taux nominal. Une offre à 3,30 % avec une assurance groupe chère et 1 000 € de frais peut coûter plus cher qu'une offre à 3,45 % avec une délégation d'assurance et des frais offerts. Autre piège : croire que la domiciliation est interdite. Elle est permise, à condition d'un avantage individualisé (L313-25-1 du Code de la consommation) : c'est une monnaie d'échange, donc une concession conditionnelle à négocier.</div>
<h3>La négociation en pratique</h3>
<ul><li>Préparer la MESORE : une deuxième offre écrite, ou un courtier.</li>
<li>Négocier le <b>package</b>, pas une ligne : c'est une négociation intégrative.</li>
<li>Utiliser la concession conditionnelle : « Si nous domicilions nos salaires, alors vous supprimez les IRA. »</li>
<li>Comparer au TAEG et au coût total, puis faire valider.</li></ul>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Calculer un taux d'effort et une mensualité maximum</li><li>Citer les règles HCSF, Lemoine, IRA, domiciliation, délai de réflexion</li><li>Calculer des IRA</li><li>Expliquer ce que contient le TAEG</li><li>Construire une contre-proposition conditionnelle sur un crédit</li></ul>`},
/*EXOS*/
{i:"n165_01",u:165,t:"num",d:.25,nw:"Le taux d'effort",q:"Kevin gagne 2 400 € et Laura 2 100 € net par mois. Quelle mensualité maximum, assurance comprise, respecte le taux d'effort de 35 %, en euros ?",a:1575,tol:1,un:" €",h:"Revenus × 35 %",w:"4 500 × 35 % = 1 575 €. C'est une norme du HCSF : elle se discute peu, et encadre toute la négociation."},
{i:"n165_02",u:165,t:"multi",d:.3,nw:"Ce qui se négocie",q:"Lesquels se négocient dans une offre de prêt immobilier ?",o:["Le taux nominal","L'assurance emprunteur","Les frais de dossier","Les indemnités de remboursement anticipé","Le délai de réflexion de 10 jours"],a:[0,1,2,3],w:"T.A.F.I.D.O. : taux, assurance, frais, IRA, domiciliation, options. Le délai de réflexion est légal, il ne se négocie pas."},
{i:"n165_03",u:165,t:"slider",d:.3,q:"Quelle est la durée maximum d'un prêt immobilier selon le HCSF, hors différé (en années) ?",min:15,max:35,step:1,a:25,tol:0,pre:"",un:" ans",w:"25 ans, portés à 27 ans si un différé est lié à des travaux ou à un achat sur plan. Les banques peuvent déroger pour 20 % de leur production."},
{i:"n165_04",u:165,t:"story",d:.3,q:"Laura compare deux offres. Que lui conseilles-tu ?",sc:[{who:"Laura",txt:"L'autre banque est à 3,30 %, vous à 3,45 %. C'est vu, non ?"}],o:["« Comparons le TAEG et le coût total, assurance et frais compris. »","« Oui, prenez l'autre banque, le taux nominal fait toute la différence. »","« Notre taux est plus élevé, mais notre service est bien meilleur. »","« Je m'aligne à 3,30 % tout de suite pour ne pas vous perdre. »"],a:0,w:"Le taux nominal ne dit pas tout : l'assurance et les frais peuvent inverser le classement. Le TAEG et le coût total sont les critères objectifs."},
{i:"n165_05",u:165,t:"tf",d:.25,q:"Depuis la loi Lemoine, un emprunteur peut changer d'assurance emprunteur à tout moment, à garanties équivalentes.",a:true,w:"Résiliation à tout moment depuis 2022. Avant, il fallait attendre la date anniversaire (loi Bourquin) ou la première année (loi Hamon)."},
{i:"n165_06",u:165,t:"fill",d:.3,q:"Le ___ additionne les intérêts, l'assurance exigée, les frais de dossier, la garantie et le courtage.",o:["TAEG","taux nominal","taux d'usure","taux d'effort"],a:0,w:"Taux annuel effectif global : c'est lui qu'on compare, et c'est lui qui ne doit pas dépasser le taux d'usure."},
{i:"n165_07",u:165,t:"num",d:.35,nw:"Les IRA",q:"Kevin rembourse par anticipation 180 000 € d'un prêt à 3,5 %. Les IRA valent au maximum 6 mois d'intérêts, sans dépasser 3 % du capital. Combien paie-t-il, en euros ?",a:3150,tol:1,un:" €",h:"Comparer 6 mois d'intérêts et 3 % du capital",w:"6 mois d'intérêts : 180 000 × 3,5 % / 2 = 3 150 €. 3 % du capital : 5 400 €. On retient le plus petit : 3 150 €."},
{i:"n165_08",u:165,t:"match",d:.3,q:"Associe chaque règle à son contenu.",p:[["HCSF","35 % de taux d'effort et 25 ans maximum"],["Loi Lemoine","Changer d'assurance emprunteur à tout moment"],["Taux d'usure","Plafond légal du TAEG"],["Délai de réflexion","Accepter l'offre au 11e jour au plus tôt"]],w:"Le cadre non négociable. À l'intérieur, tout le reste se négocie."},
{i:"n165_09",u:165,t:"story",d:.35,q:"Quelle concession conditionnelle proposes-tu à Kevin et Laura ?",sc:[{who:"Kevin",txt:"On aimerait bien ne pas avoir de pénalités si on revend dans cinq ans."}],o:["« Si vous domiciliez vos salaires chez nous, je supprime les IRA. »","« Je supprime les IRA, et j'espère que vous domicilierez vos salaires. »","« Les IRA sont fixées par la loi, on ne peut pas y toucher du tout. »","« Si vous revendez dans cinq ans, les IRA ne s'appliquent jamais. »"],a:0,w:"La condition d'abord (domiciliation, qui vaut beaucoup pour la banque), la concession ensuite (IRA supprimées, qui valent beaucoup pour eux). Les IRA se négocient bel et bien."},
{i:"n165_10",u:165,t:"tf",d:.3,q:"Une banque peut exiger la domiciliation des revenus sans rien accorder en échange.",a:false,w:"Seulement en échange d'un avantage individualisé écrit dans l'offre (article L313-25-1 du Code de la consommation). C'est une concession conditionnelle encadrée par la loi."},
{i:"n165_11",u:165,t:"sort",d:.4,q:"Classe chaque élément : négociable ou cadre non négociable ?",bins:["Négociable","Non négociable"],it:[["Frais de dossier",0],["Taux d'usure",1],["Suppression des IRA",0],["Délai de réflexion de 10 jours",1],["Choix de l'assurance emprunteur",0],["Durée de la domiciliation",0]],w:"Le cadre légal ne se discute pas ; tout le reste est une monnaie d'échange."},
{i:"n165_12",u:165,t:"mcq",d:.35,q:"Dans quel cas les IRA ne sont-elles pas dues, même sans clause particulière ?",o:["Vente liée à une mutation professionnelle","Vente pour acheter un logement plus grand","Remboursement grâce à un héritage reçu","Rachat du prêt par une autre banque moins chère"],a:0,w:"Mobilité professionnelle, décès, cessation forcée d'activité : trois cas légaux d'exonération. Dans les autres cas, il faut l'avoir négocié."},
{i:"n165_13",u:165,t:"story",d:.4,q:"Rappel du module 2 : comment Kevin renforce-t-il sa MESORE ?",sc:[{who:"Kevin",txt:"On a juste votre offre et celle de la banque de mes parents. C'est suffisant ?"}],o:["Faire consulter plusieurs banques par un courtier et obtenir des offres écrites","Dire à chaque banque qu'il a déjà une offre bien meilleure, même sans en avoir","Attendre que les taux baissent avant de relancer les deux banques en même temps","Annoncer qu'il signera dans la semaine avec celle qui lui répondra en premier"],a:0,w:"Une vraie alternative écrite est une MESORE solide. Bluffer sans offre expose à être démasqué ; l'urgence affaiblit sa position."},
{i:"n165_14",u:165,t:"tiles",d:.35,q:"Reconstitue le moyen mnémotechnique des six lignes d'une offre.",a:["Tout","A","un","Facteur","Invisible","Dans","l'Offre"],dd:["Taux","Toujours","Prix"],w:"Taux, Assurance, Frais, IRA, Domiciliation, Options."},
{i:"n165_15",u:165,t:"num",d:.45,q:"L'assurance groupe coûte 0,34 % par an du capital emprunté (220 000 €) ; une délégation coûte 0,12 %. Quelle économie sur 25 ans, en euros (assurance calculée sur le capital initial) ?",a:12100,tol:1,un:" €",h:"Écart de taux × capital × 25",w:"0,22 % × 220 000 = 484 € par an, soit 12 100 € sur 25 ans. L'assurance est souvent le poste le plus négociable."},
{i:"n165_16",u:165,t:"fill",d:.4,q:"Sans questionnaire de santé, la part assurée par personne doit être au maximum de ___ € et le prêt se terminer avant 60 ans.",o:["200 000","100 000","150 000","300 000"],a:0,w:"Loi Lemoine : suppression du questionnaire de santé sous ces deux conditions. Et droit à l'oubli à 5 ans pour les cancers et l'hépatite C."},
{i:"n165_17",u:165,t:"story",d:.45,q:"Rappel du module 3 : quelle option de souplesse vaut beaucoup pour Kevin et Laura ?",sc:[{who:"Laura",txt:"Si on a un bébé, j'aimerais m'arrêter un peu."}],o:["La modulation ou le report d'échéances inscrit dans l'offre","Un taux plus bas de 0,02 point sur toute la durée du prêt","Une carte bancaire premium offerte pendant la première année","La suppression de la garantie Crédit Logement de l'offre"],a:0,w:"La modulation coûte peu à la banque et vaut beaucoup pour eux : c'est exactement « ce qui me coûte peu et vaut beaucoup pour l'autre »."},
{i:"n165_18",u:165,t:"tf",d:.4,q:"Le taux d'effort de 35 % se calcule assurance emprunteur comprise.",a:true,w:"Depuis 2022, la norme HCSF est juridiquement contraignante et s'entend assurance comprise, sur les revenus nets avant impôt."},
{i:"n165_19",u:165,t:"order",d:.45,q:"Remets dans l'ordre la négociation du prêt de Kevin et Laura.",it:["Obtenir une deuxième offre écrite","Lister les six lignes de chaque offre","Proposer des échanges conditionnels","Comparer au TAEG et au coût total","Faire valider puis respecter le délai de réflexion"],w:"MESORE, analyse complète, concessions conditionnelles, critère objectif, validation. Tout le cours appliqué à un prêt."},
{i:"n165_20",u:165,t:"story",d:.5,q:"Rappel du module 8 : Kevin objecte sur l'assurance. Comment traites-tu ?",sc:[{who:"Kevin",txt:"Votre assurance, c'est 550 € de plus par an qu'une délégation. C'est du vol."}],o:["« Je comprends. Comparons les garanties : si elles sont équivalentes, la délégation est votre droit. »","« Notre assurance groupe est obligatoire pour obtenir notre taux, c'est à prendre ou à laisser. »","« Une délégation, c'est beaucoup de paperasse, vous regretterez de ne pas avoir pris la nôtre. »","« Je vous fais un geste de 100 € par an sur l'assurance, mais seulement si vous signez cette semaine. »"],a:0,w:"Accueillir, clarifier (garanties), traiter par un critère objectif. Refuser la délégation à garanties équivalentes serait illégal, et le geste pressé saute la clarification."},
{i:"n165_21",u:165,t:"mcq",d:.5,q:"Qui fixe le taux d'usure ?",o:["La Banque de France","Chaque banque prêteuse","Le Haut Conseil (HCSF)","L'ACPR, le superviseur"],a:0,w:"La Banque de France publie les taux d'usure par catégorie de prêt. Le TAEG ne peut pas les dépasser."},
{i:"n165_22",u:165,t:"sort",d:.5,q:"Classe chaque coût : inclus dans le TAEG ou non ?",bins:["Inclus dans le TAEG","Non inclus"],it:[["Intérêts",0],["Assurance exigée par le prêteur",0],["Frais de dossier",0],["Frais de garantie",0],["Frais de notaire de l'achat",1],["Frais d'agence immobilière",1]],w:"Le TAEG intègre tout ce qu'impose le crédit. Les frais de l'achat lui-même (notaire sur la vente, agence) n'en font pas partie."},
{i:"n165_23",u:165,t:"slider",d:.5,q:"Quel pourcentage de leur production de crédits immobiliers les banques peuvent-elles accorder en dérogation aux normes HCSF ?",min:0,max:50,step:5,a:20,tol:0,pre:"",un:" %",w:"20 % par trimestre, en priorité pour la résidence principale et les primo-accédants. C'est la seule souplesse du cadre."},
{i:"n165_24",u:165,t:"story",d:.55,q:"Quelle phrase de Hugo est fausse ?",sc:[{who:"Hugo",txt:"J'ai dit à un client trois choses sur la domiciliation."}],o:["« La loi limite toujours la domiciliation à 10 ans maximum. »","« Elle n'est possible qu'avec un avantage individualisé. »","« L'avantage doit être écrit noir sur blanc dans l'offre de prêt. »","« Sa durée peut tout à fait se négocier avec la banque. »"],a:0,w:"Le décret qui fixait un maximum de 10 ans a été annulé par le Conseil d'État en 2021 : la durée se négocie. Les trois autres phrases sont justes."},
{i:"n165_25",u:165,t:"fill",d:.55,q:"L'offre de prêt ne peut être acceptée qu'à partir du ___ jour après sa réception.",o:["11e","8e","15e","31e"],a:0,w:"10 jours de délai de réflexion pleins : acceptation au plus tôt le 11e jour. On ne signe pas « tout de suite », même si le client est pressé."},
{i:"n165_26",u:165,t:"multi",d:.55,q:"Quels arguments renforcent Kevin et Laura face à la banque ?",o:["Un apport de 30 000 €","Des revenus stables (CDI, fonction publique hospitalière)","Une offre écrite concurrente","Une épargne résiduelle après l'achat","L'urgence de leur date de signature"],a:[0,1,2,3],w:"Apport, stabilité, alternative, épargne : ce sont les forces d'un dossier. L'urgence, révélée, affaiblit au contraire leur position."},
{i:"n165_27",u:165,t:"tf",d:.55,q:"Une offre à taux nominal plus bas peut avoir un coût total plus élevé qu'une offre à taux plus haut.",a:true,w:"Assurance, frais et garantie peuvent inverser l'ordre. C'est pourquoi on compare le TAEG et le coût total."},
{i:"n165_28",u:165,t:"match",d:.6,q:"Associe chaque demande de Kevin et Laura à la contrepartie qui l'équilibre.",p:[["Suppression des IRA","Domiciliation des salaires"],["Frais de dossier offerts","Ouverture d'une épargne régulière"],["Taux réduit de 0,10 point","Assurance habitation chez la banque"],["Modulation des échéances","Durée de domiciliation plus longue"]],w:"Chaque demande a son prix : la réciprocité appliquée au crédit. On bâtit un package équilibré, pas une liste de cadeaux."},
{i:"n165_29",u:165,t:"story",d:.6,q:"Rappel du module 9 : quel closing fais-tu avec Kevin et Laura ?",sc:[{who:"Laura",txt:"On est d'accord sur tout, je crois !"}],o:["Mensualité, coût total, risques en cas d'arrêt de travail, puis offre à accepter au 11e jour","La signature de l'offre dès aujourd'hui, puisqu'ils sont d'accord sur toutes les conditions","L'envoi de l'offre par la poste, en les laissant lire seuls toutes les conditions générales du prêt","Un dernier geste commercial sur le taux, pour les remercier de nous avoir choisis"],a:0,w:"B.R.C.P. adapté au crédit, et respect du délai de réflexion légal. Signer le jour même est impossible, et le geste final gratuit n'a pas lieu d'être."},
{i:"n165_30",u:165,t:"num",d:.6,q:"Laura réduit son temps de travail : ses revenus passent à 1 400 €. Avec les 2 400 € de Kevin, quelle mensualité maximum reste compatible avec 35 %, en euros ?",a:1330,tol:1,un:" €",h:"(2 400 + 1 400) × 35 %",w:"3 800 × 35 % = 1 330 €. D'où l'intérêt d'une option de modulation ou d'une durée adaptée, discutées dès la négociation."},
{i:"n165_31",u:165,t:"mcq",d:.6,q:"Rappel du module 16 : Kevin veut payer une partie de l'apport en espèces. Que fais-tu ?",o:["Je demande l'origine des fonds, justificatifs à l'appui","J'accepte sans question, ce n'est qu'un petit montant","Je refuse par principe tout apport versé en espèces","Je le préviens qu'il sera déclaré à TRACFIN aussitôt"],a:0,w:"Origine des fonds d'abord : épargne justifiée, don familial déclaré... On analyse avant de conclure, et on ne prévient jamais d'une déclaration."},
{i:"n165_32",u:165,t:"tf",d:.6,q:"Refuser une délégation d'assurance qui présente des garanties équivalentes est un choix commercial libre pour la banque.",a:false,w:"À garanties équivalentes, la banque ne peut pas refuser la délégation, ni modifier le taux en contrepartie. C'est un droit de l'emprunteur."}
