/*UNIT*/
{id:166,c:"NEGO",n:"Module 18",t:"Synthèse : la journée complète d'un négociateur bancaire",col:"--blue",ic:"🏆",guide:`
<h3>Un an plus tard</h3>
<div class="gstory">Un an a passé à l'agence Graslin. Marc Delorme est resté : il a regroupé son épargne et déjeune avec Sylvie une fois par an. Claire Vasseur a placé ses 650 000 € en trois poches et prépare la transmission de l'atelier avec son notaire. Les Robin ont acheté leur camping-car sans toucher à leur épargne de long terme. Kevin et Laura ont eu une petite Lina et ont activé la modulation d'échéances. Hugo, lui, a arrêté d'offrir des frais de dossier sans contrepartie. Ce dernier module rassemble tout : une journée, toutes les méthodes.</div>
<h3>La carte de tout le cours</h3>
<table><tr><th>Moment</th><th>Outil</th><th>La phrase à retenir</th></tr>
<tr><td>Avant</td><td>Carte client S.O.C.E., C.P.A.P., fiche 3 colonnes, M.P.D.R., KYC</td><td>Les négociations se gagnent la veille</td></tr>
<tr><td>Avant</td><td>MESORE (BATNA), point cible, point de réserve, ZOPA</td><td>Réserve fixée à froid, jamais révélée</td></tr>
<tr><td>Pendant : découvrir</td><td>Questions ouvertes, silence utile, résumé intermédiaire, SPIN, découverte C.O.C.R.D.</td><td>Le client achète mieux quand il a formulé lui-même l'enjeu</td></tr>
<tr><td>Pendant : comprendre</td><td>Positions et intérêts, 4R, SONCAS</td><td>Deux positions se cognent, deux intérêts se combinent</td></tr>
<tr><td>Pendant : proposer</td><td>Négociation intégrative, critères objectifs</td><td>Que puis-je échanger qui me coûte peu et vaut beaucoup pour l'autre ?</td></tr>
<tr><td>Pendant : défendre</td><td>A.C.T.V. (accueillir, clarifier, traiter, valider)</td><td>Je comprends votre point de vue</td></tr>
<tr><td>Conclure</td><td>Concession conditionnelle, réciprocité, B.R.C.P.</td><td>Pas de SI, pas de OUI</td></tr>
<tr><td>Après</td><td>Suivi, mise à jour, suivi des opérations, réexamen</td><td>Ce qui n'est pas écrit n'a pas eu lieu</td></tr>
<tr><td>Toujours</td><td>Statuts, non négociables, LCB-FT, TRACFIN</td><td>On adapte l'argument, jamais la vérité</td></tr></table>
<div class="gmnemo"><b>La journée en cinq verbes : Préparer, Découvrir, Proposer, Conclure, Suivre.</b> Retiens la phrase « <b>Pour Décrocher Plus, Commence par Suivre</b> » : on ne décroche un accord solide qu'en préparant et en découvrant, et on ne garde un client qu'en le suivant.</div>
<h3>Les mots-clés de l'évaluation (d'après tes notes)</h3>
<ul><li><b>La valeur</b> : apporter de la plus-value, de la valeur ajoutée au client. C'est la réponse à « vos frais sont trop élevés ».</li>
<li><b>Aller derrière les intérêts et la position</b> : comprendre les intérêts et les besoins, et proposer des solutions adaptées. Les deux positions types : <b>Sécurité</b> et <b>Rendement</b>.</li>
<li>Les exercices types des notes : la différence entre position et intérêt ; deux questions ouvertes sur la tolérance au risque ; la meilleure réponse à « vos frais sont trop élevés » ; pourquoi valider la compréhension avant de conseiller ; un critère objectif dans un arbitrage patrimonial ; le brief de la dirigeante de 45 ans ; la demande d'augmentation face au budget serré.</li></ul>
<div class="gtrap">Récapitulatif des corrections apportées à tes notes : <b>BATMA</b> est une coquille pour BATNA, et MESORE et BATNA sont un seul concept ; « Clairifier » s'écrit <b>clarifier</b> ; <b>Confort, Argent et Sympathie</b> sont trois lettres distinctes de SONCAS ; aucun des placements dits « sans risque » (obligations, fonds euros, produit structuré) ne l'est totalement ; le PER fait gagner de l'impôt <b>à l'entrée</b>, la sortie est imposée ; « Immobilies » signifie immobilier ; la domiciliation n'est plus limitée légalement à 10 ans depuis 2021.</div>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Traiter le brief complet d'un client de A à Z</li><li>Nommer chaque méthode et son moment dans l'entretien</li><li>Rédiger une concession conditionnelle et un closing éthique</li><li>Reconnaître un non négociable réglementaire et un signal LCB-FT</li><li>Répondre par la valeur, jamais par la remise seule</li></ul>`},
/*EXOS*/
{i:"n166_01",u:166,t:"order",d:.3,nw:"La journée du négociateur",q:"Remets dans l'ordre les cinq verbes de la journée.",it:["Préparer","Découvrir","Proposer","Conclure","Suivre"],w:"Pour Décrocher Plus, Commence par Suivre : préparer, découvrir, proposer, conclure, suivre."},
{i:"n166_02",u:166,t:"sort",d:.35,q:"Classe chaque outil selon le moment où on l'utilise.",bins:["Avant","Pendant","Après"],it:[["Fixer son point de réserve",0],["Méthode SPIN",1],["Compte rendu écrit",2],["Carte du client",0],["Traitement des objections",1],["Mise à jour de la fiche KYC",2]],w:"Préparer avant, découvrir et proposer pendant, formaliser et suivre après."},
{i:"n166_03",u:166,t:"story",d:.35,q:"Un nouveau client, Antoine, 38 ans, t'accueille ainsi. Quelle est ta première réponse ?",sc:[{who:"Antoine Mercier",txt:"Je veux un placement qui rapporte 6 %. Vous avez ça ?"}],o:["« Qu'est-ce que ces 6 % vous permettraient de réaliser ? »","« Oui, notre fonds actions monde a fait 8 % l'an dernier. »","« Non, aucun placement sûr ne rapporte 6 % aujourd'hui. »","« Quel montant voulez-vous placer, et pour quelle durée ? »"],a:0,w:"Position (6 %), puis question ouverte vers l'intérêt. Le rendement est une des deux positions types des notes, avec la sécurité."},
{i:"n166_04",u:166,t:"match",d:.35,q:"Associe chaque méthode à sa phrase clé.",p:[["SPIN","Le client achète mieux quand il a formulé l'enjeu"],["Négociation intégrative","Ce qui me coûte peu et vaut beaucoup pour l'autre"],["Concession conditionnelle","Si nous ajustons X, alors vous validez Y"],["Objections","Je comprends votre point de vue"]],w:"Quatre phrases, quatre méthodes, à connaître mot pour mot."},
{i:"n166_05",u:166,t:"tf",d:.3,q:"MESORE et BATNA désignent la même notion.",a:true,w:"Meilleure solution de rechange, Best Alternative To a Negotiated Agreement. « BATMA » dans les notes est une coquille."},
{i:"n166_06",u:166,t:"multi",d:.4,q:"Quels sont les deux mots-clés de l'évaluation selon les notes ?",o:["Apporter de la valeur au client","Aller derrière les intérêts et la position","Obtenir la plus grosse marge","Signer le plus vite possible","Imposer le produit maison"],a:[0,1],w:"La valeur, et la capacité à dépasser la position pour trouver l'intérêt. Tout le reste en découle."},
{i:"n166_07",u:166,t:"story",d:.4,q:"Antoine révèle son intérêt. Quelle question need-payoff poses-tu ?",sc:[{who:"Antoine Mercier",txt:"En fait, je veux pouvoir passer à 4 jours par semaine dans dix ans."}],o:["« Qu'est-ce que ce cinquième jour libre changerait pour vous ? »","« Combien gagnez-vous exactement aujourd'hui, net par mois ? »","« Si rien ne change, dans dix ans vous serez toujours à 5 jours. »","« Je vous propose un PER pour préparer ce projet de temps partiel. »"],a:0,w:"Need-payoff : le client formule la valeur attendue. La deuxième est une question de situation, la troisième une implication, la dernière une proposition prématurée."},
{i:"n166_08",u:166,t:"fill",d:.35,q:"Dans la méthode des 4R, on obtient un « oui, c'est bien cela » à l'étape ___.",o:["Revalider","Reprendre","Relier","Reformuler"],a:0,w:"Reprendre, Relier, Reformuler, Revalider. Pas de conseil avant le « oui »."},
{i:"n166_09",u:166,t:"num",d:.45,q:"Antoine veut au plus 0,70 % de frais ; ta banque ne descend pas sous 0,55 %. Quelle est la largeur de la ZOPA, en points ?",a:.15,tol:.001,un:" point",h:"Écart entre les deux réserves",w:"De 0,55 % à 0,70 % : 0,15 point de zone d'accord. Ouvre près de ton point cible, pas au plancher."},
{i:"n166_10",u:166,t:"story",d:.45,q:"Antoine objecte. Quelle réponse suit A.C.T.V. ?",sc:[{who:"Antoine Mercier",txt:"Votre gestion pilotée, 0,70 %, c'est le prix d'un ETF plus 0,50 % de rien du tout."}],o:["« Je comprends. Qu'est-ce que vous attendez de la gestion, en plus du prix ? »","« Un ETF, ce n'est pas du tout pareil, vous comparez des choses incomparables. »","« D'accord, je peux descendre à 0,60 % si ça vous fait vraiment plaisir. »","« Achetez donc un ETF tout seul, vous verrez bien si vous vous en sortez. »"],a:0,w:"Accueillir puis clarifier. Les autres réponses contredisent, cèdent ou provoquent."},
{i:"n166_11",u:166,t:"tiles",d:.4,q:"Reconstitue la phrase qui résume la réciprocité.",a:["Pas","de","SI","pas","de","OUI"],dd:["prix","NON","remise"],w:"Chaque concession importante est conditionnée."},
{i:"n166_12",u:166,t:"sort",d:.45,q:"Classe chaque phrase de client selon le levier SONCAS.",bins:["Sécurité","Orgueil","Nouveauté","Confort","Argent","Sympathie"],it:[["« Le capital est garanti ? »",0],["« Pour un chef d'entreprise comme moi... »",1],["« Je peux tout piloter sur l'appli ? »",2],["« Je ne veux pas m'en occuper »",3],["« Ça rapporte combien, net ? »",4],["« Je reste parce que c'est vous »",5]],w:"Six lettres, six motivations. Six Occasions Nettes de Convaincre Avec Sincérité."},
{i:"n166_13",u:166,t:"mcq",d:.45,q:"Quel statut faut-il pour conseiller un portefeuille de fonds hors assurance-vie ?",o:["CIF","IAS","IOBSP","Carte T"],a:0,w:"Le CIF écrit (lettre de mission, rapport). L'IAS écoute (assurance), l'IOBSP explique (crédit), la carte T sert à la transaction immobilière."},
{i:"n166_14",u:166,t:"story",d:.45,q:"Antoine veut verser 90 000 € par virement depuis un compte à l'étranger. Que fais-tu ?",sc:[{who:"Antoine Mercier",txt:"C'est ma prime de départ d'une filiale au Luxembourg."}],o:["Je demande le justificatif de la prime et le relevé du compte d'origine","Je refuse, les virements venant de l'étranger sont toujours interdits","Je déclare à TRACFIN sans lui poser de question, par sécurité","J'accepte sans rien demander, le Luxembourg est dans l'Union européenne"],a:0,w:"Origine des fonds : on justifie avec des documents. Un flux international n'est pas un soupçon en soi ; l'analyse précède toute décision."},
{i:"n166_15",u:166,t:"tf",d:.4,q:"Un produit structuré à capital protégé fait partie des placements totalement sans risque.",a:false,w:"Protection conditionnelle et risque émetteur. Aucun des trois placements « sûrs » des notes n'est totalement sans risque."},
{i:"n166_16",u:166,t:"slider",d:.5,q:"Antoine gagne 5 200 € net par mois. Quelle mensualité maximum, assurance comprise, pour un crédit immobilier (norme HCSF), en euros ?",min:1000,max:2500,step:10,a:1820,tol:0,pre:"",un:" €",w:"5 200 × 35 % = 1 820 €. Norme HCSF, assurance comprise : un cadre non négociable."},
{i:"n166_17",u:166,t:"multi",d:.5,q:"Quelles sont les trois questions ouvertes des notes sur la tolérance au risque ?",o:["Comment réagiriez-vous en cas de mouvements importants du marché ?","Quelle part de votre patrimoine, si elle était perdue, vous mettrait en situation critique ?","Quelle proportion mettriez-vous entre sécurité et performance ?","Voulez-vous un profil dynamique ?","Avez-vous déjà perdu de l'argent en Bourse ?"],a:[0,1,2],w:"Les trois questions des notes, à connaître par cœur. Les deux dernières sont fermées."},
{i:"n166_18",u:166,t:"story",d:.5,q:"Quelle concession conditionnelle proposes-tu à Antoine ?",sc:[{who:"Antoine Mercier",txt:"0,60 % et je signe."}],o:["« Si vous transférez aussi votre PEA chez nous, je passe à 0,60 %. »","« D'accord pour 0,60 %, c'est bien parce que je vous trouve sympathique. »","« On coupe la poire en deux entre 0,70 % et 0,60 % : 0,65 %, et on signe. »","« Impossible de descendre sous 0,70 %, c'est le tarif de la maison pour tous. »"],a:0,w:"Condition d'abord (transfert du PEA, qui vaut beaucoup pour la banque), concession ensuite. 0,60 % reste au-dessus de ton plancher de 0,55 %."},
{i:"n166_19",u:166,t:"order",d:.5,q:"Un client dépose 45 000 € en espèces, sans explication, alors qu'il verse d'habitude 100 € par mois. Remets tes actions dans l'ordre.",it:["Tu constates que l'opération ne colle pas à son profil","Tu lui demandes l'origine des fonds et des justificatifs","Faute de justificatif, tu remontes l'anomalie au déclarant","Le déclarant prend la décision interne de déclarer","Tu réponds au client de façon neutre, sans rien révéler"],w:"Anomalie, analyse, décision interne, déclaration à TRACFIN, et confidentialité absolue : jamais de tipping off."},
{i:"n166_20",u:166,t:"fill",d:.5,q:"La meilleure réponse à « vos frais sont trop élevés » est de démontrer la ___ apportée.",o:["valeur","remise","sécurité","rapidité"],a:0,w:"Le mot-clé de l'évaluation. Chiffrer ce que les frais achètent, comparer à un critère objectif."},
{i:"n166_21",u:166,t:"match",d:.5,q:"Associe chaque correction des notes à la bonne version.",p:[["BATMA","BATNA, même concept que MESORE"],["Clairifier","Clarifier"],["Confort / Argent / Sympathie","Trois lettres distinctes de SONCAS"],["Immobilies","Immobilier"]],w:"Les notes contiennent des coquilles : on les corrige, on ne les recopie pas."},
{i:"n166_22",u:166,t:"story",d:.55,q:"Rappel du module 12 : Antoine et sa compagne n'ont pas la même tolérance. Que retiens-tu ?",sc:[{who:"Antoine Mercier",txt:"Moi, 30 % de baisse, ça ne me fait pas peur. Chloé, elle, panique à 5 %."}],o:["La plus prudente des deux pour un placement commun","La plus élevée, c'est Antoine qui a les revenus","La moyenne des deux, soit environ 17,5 % de baisse","Celle d'Antoine, puisque c'est lui qui est venu"],a:0,w:"Pour un placement commun, on retient la tolérance la plus faible : celle qui paniquerait ferait vendre au pire moment."},
{i:"n166_23",u:166,t:"tf",d:.55,q:"Le PER fait gagner de l'impôt à l'entrée, et la sortie à la retraite est imposée.",a:true,w:"Correction des notes : c'est un outil de défiscalisation pendant la vie active. Son intérêt dépend de l'écart de tranche entre aujourd'hui et la retraite."},
{i:"n166_24",u:166,t:"mcq",d:.55,q:"Pourquoi valider la compréhension avant de conseiller ?",o:["Pour un conseil en réelle adéquation avec la situation","Pour que le client signe beaucoup plus vite","Pour éviter de remplir le questionnaire de profil","Pour montrer au client ses connaissances techniques"],a:0,w:"Réponse type des notes. Un conseil bâti sur un malentendu est inadapté, même techniquement parfait."},
{i:"n166_25",u:166,t:"story",d:.6,q:"Rappel du module 10 : Sylvie te dit encore « budget serré ». Quelle est ta meilleure question ?",sc:[{who:"Sylvie Morel",txt:"Cette année encore, le budget est serré."}],o:["« Quelles marges de manœuvre avons-nous, et à quelle date pourrez-vous me répondre ? »","« Encore ? Vous m'aviez dit la même chose l'an dernier, ce n'est pas très juste. »","« Dans ce cas, je vais regarder sérieusement ce que proposent les autres banques de Nantes. »","« Je comprends parfaitement, ce n'est vraiment pas grave, on verra l'an prochain. »"],a:0,w:"Question ouverte sur les marges, et demande d'une date précise : les deux réponses modèles des notes. Le reproche et la menace braquent ; renoncer n'apprend rien."},
{i:"n166_26",u:166,t:"sort",d:.6,q:"Classe chaque élément : négociable ou non négociable réglementaire ?",bins:["Négociable","Non négociable"],it:[["Les frais de gestion",0],["Le questionnaire de profil",1],["La vérification d'identité",1],["Les frais de dossier d'un prêt",0],["Le rapport écrit d'un CIF",1],["La durée de domiciliation",0]],w:"Les prix, frais et options se négocient ; la réglementation, jamais."},
{i:"n166_27",u:166,t:"num",d:.6,q:"Antoine place 150 000 € avec 0,60 % de frais. Combien paie-t-il de frais la première année, en euros ?",a:900,tol:1,un:" €",h:"0,60 % de 150 000",w:"900 €. Afficher le coût en euros est une preuve (C.P.A.P.) qui désamorce l'objection des frais."},
{i:"n166_28",u:166,t:"story",d:.6,q:"Rappel du module 9 : quel closing fais-tu avec Antoine ?",sc:[{who:"Antoine Mercier",txt:"Bon, on y va ?"}],o:["Besoins, risques de la gestion pilotée, coûts en euros, prochaines étapes datées","La signature immédiate du contrat, pour ne surtout pas lui laisser le temps d'hésiter","Un dernier geste gratuit sur les frais, pour le remercier de sa confiance","L'envoi du contrat par e-mail, et on attend patiemment sa réponse écrite"],a:0,w:"B.R.C.P. : Bien Relire Chaque Point. Précipiter, offrir sans condition ou laisser le client seul ne sont pas des closings éthiques."},
{i:"n166_29",u:166,t:"multi",d:.65,q:"Quels éléments font partie d'un bon suivi après la signature d'Antoine ?",o:["Un compte rendu écrit","Le rapport d'adéquation","Une date de revue","Une vérification de sa compréhension","Une relance commerciale chaque semaine"],a:[0,1,2,3],w:"Formaliser et sécuriser la compréhension. Le harcèlement commercial détruit ce que la négociation a construit."},
{i:"n166_30",u:166,t:"fill",d:.65,q:"La phrase « Pour Décrocher Plus, Commence par ___ » rappelle les cinq verbes de la journée.",o:["Suivre","Signer","Sourire","Solder"],a:0,w:"Préparer, Découvrir, Proposer, Conclure, Suivre."},
{i:"n166_31",u:166,t:"story",d:.65,q:"Dernier cas : Claire Vasseur revient pour un arbitrage. Quel critère objectif invoques-tu ?",ctx:"Deux ans après, la poche actions de Claire a pris 28 %. Inès entre en école dans huit mois.",sc:[{who:"Claire Vasseur",txt:"Vous voulez que je vende ? Mais ça marche bien !"}],o:["La prise de profit et l'évolution de mes besoins de liquidités","Mon intuition que la Bourse va bientôt se retourner fortement","La nouvelle campagne commerciale de la banque sur les fonds","L'envie de faire tourner votre portefeuille pour le dynamiser"],a:0,w:"Deux des quatre critères objectifs des notes : prise de profit et liquidités. L'intuition et les campagnes commerciales ne sont pas des critères."},
{i:"n166_32",u:166,t:"tiles",d:.7,q:"Reconstitue la règle d'éthique qui clôt le cours.",a:["On","adapte","l'argument","jamais","la","vérité"],dd:["prix","client","toujours"],w:"SONCAS, analogies, reformulations : tout sert à traduire une solution adaptée. Rien ne sert à rendre attirante une solution inadaptée."}
