/* =====================================================================
   GLOSSAIRE « EN CLAIR » (01/10/2026)
   Demande de Corentin : tout mot du metier que le commun des mortels ne
   connait pas recoit une phrase simple et un exemple. Le mot est souligne
   en pointilles dans la lecon, l enonce et la correction ; un toucher
   ouvre l explication. Les cours ne sont pas modifies.
   t : le terme, f : ses autres formes, c : les cours concernes (vide = tous),
   d : l explication simple, x : un exemple concret.
   Les sigles (tout en majuscules) ne sont reconnus qu ecrits en majuscules.
   ===================================================================== */
window.ARC_GLOSS=[
 /* ---------- patrimoine, succession, fiscalite ---------- */
 {t:"usufruit",c:"PATRI FISCA NEGO",d:"Le droit d'utiliser un bien et d'en toucher les revenus, sans en être le propriétaire complet.",x:"Mamie garde l'usufruit de sa maison : elle y vit, ou la loue et encaisse les loyers."},
 {t:"usufruitier",f:["usufruitière","usufruitiers"],c:"PATRI FISCA NEGO",d:"La personne qui a l'usufruit d'un bien : elle s'en sert et touche ses revenus.",x:"Le conjoint usufruitier habite la maison, les enfants en ont la nue-propriété."},
 {t:"nue-propriété",c:"PATRI FISCA NEGO",d:"La propriété d'un bien sans pouvoir l'utiliser ni en toucher les revenus, tant que l'usufruit existe.",x:"Les enfants ont la nue-propriété de la maison : elle deviendra entièrement à eux au décès de leur mère."},
 {t:"nu-propriétaire",f:["nus-propriétaires","nue-propriétaire"],c:"PATRI FISCA NEGO",d:"La personne qui détient la nue-propriété : le bien lui reviendra en entier quand l'usufruit s'éteindra.",x:"Léa est nu-propriétaire de l'appartement que sa mère occupe."},
 {t:"pleine propriété",c:"PATRI FISCA NEGO",d:"L'usufruit et la nue-propriété réunis : on peut utiliser le bien, en tirer des revenus et le vendre.",x:"Quand l'usufruitier décède, le nu-propriétaire récupère la pleine propriété."},
 {t:"démembrement",c:"PATRI FISCA NEGO",d:"Le fait de couper la propriété d'un bien en deux : l'usufruit d'un côté, la nue-propriété de l'autre.",x:"Des parents donnent la nue-propriété de leur maison et gardent l'usufruit."},
 {t:"réserve héréditaire",c:"PATRI",d:"La part de l'héritage que la loi garantit aux enfants : un testament ne peut pas les en priver.",x:"Avec deux enfants, ils ont droit ensemble à au moins les deux tiers des biens."},
 {t:"réservataire",f:["réservataires","héritier réservataire","héritiers réservataires"],c:"PATRI",d:"Un héritier qui a droit à la réserve : les enfants, ou le conjoint quand il n'y a pas d'enfant.",x:"Un fils est réservataire : on ne peut pas le déshériter totalement."},
 {t:"quotité disponible",c:"PATRI",d:"La part de ses biens que l'on peut donner librement à qui l'on veut, en plus de la réserve.",x:"Avec un seul enfant, on peut léguer librement la moitié de ses biens."},
 {t:"donation-partage",f:["donations-partages"],c:"PATRI FISCA NEGO",d:"Une donation qui répartit dès maintenant ses biens entre ses enfants, avec des valeurs figées au jour du don.",x:"Les parents donnent la maison à Léa et des titres à Hugo : au décès, on ne recalcule pas les valeurs."},
 {t:"don manuel",f:["dons manuels"],c:"PATRI FISCA NEGO",d:"Un cadeau remis de la main à la main (argent, virement, objet), sans passer chez le notaire. Il faut le déclarer au fisc.",x:"Un virement de 10 000 € à son fils pour ses 25 ans."},
 {t:"legs",c:"PATRI",d:"Un bien que l'on transmet par testament, au moment de son décès.",x:"Par testament, Jean lègue sa voiture à son neveu."},
 {t:"légataire",f:["légataires","légataire universel"],c:"PATRI",d:"La personne qui reçoit un bien grâce à un testament.",x:"Le neveu est légataire de la voiture de son oncle."},
 {t:"testament olographe",f:["testaments olographes"],c:"PATRI",d:"Un testament écrit entièrement à la main, daté et signé par son auteur, sans notaire.",x:"Une feuille manuscrite « Je lègue mon piano à Inès », datée et signée."},
 {t:"testament authentique",c:"PATRI",d:"Un testament dicté à un notaire, devant deux témoins ou un second notaire. Il est très difficile à contester.",x:"Paul, malade, fait venir le notaire chez lui pour dicter ses volontés."},
 {t:"indivision",c:"PATRI FISCA NEGO",d:"Plusieurs personnes possèdent ensemble un même bien, chacune pour une part, sans lot à elle.",x:"Trois enfants héritent ensemble de la maison : chacun en possède un tiers."},
 {t:"soulte",f:["soultes"],c:"PATRI FISCA",d:"Une somme d'argent versée pour équilibrer un partage quand les lots n'ont pas la même valeur.",x:"Léa garde la maison de 300 000 € à partager avec son frère : elle lui verse une soulte de 150 000 €."},
 {t:"abattement",f:["abattements"],c:"PATRI FISCA NEGO",d:"Une somme retirée avant de calculer l'impôt : en dessous, on ne paie rien.",x:"Un parent peut donner 100 000 € à chaque enfant sans droits, une fois tous les 15 ans."},
 {t:"barème",f:["barèmes"],c:"PATRI FISCA NEGO",d:"Le tableau qui fixe le taux d'impôt selon le montant taxé, tranche par tranche.",x:"Entre parents et enfants, le taux monte de 5 % à 45 % selon la somme reçue."},
 {t:"tranche marginale",f:["tranches marginales"],c:"PATRI FISCA NEGO",d:"Le taux d'impôt sur le revenu appliqué au dernier euro gagné.",x:"Avec une tranche marginale à 30 %, 1 000 € de revenus en plus coûtent 300 € d'impôt."},
 {t:"droits de succession",c:"PATRI FISCA NEGO",d:"L'impôt payé par les héritiers sur ce qu'ils reçoivent au décès.",x:"Un neveu qui hérite paie beaucoup plus de droits de succession qu'un enfant."},
 {t:"droits d'enregistrement",c:"PATRI FISCA",d:"Un impôt payé quand un acte important est enregistré par l'administration (vente, donation, cession de parts).",x:"En achetant des parts de société, l'acheteur paie des droits d'enregistrement."},
 {t:"dévolution",c:"PATRI",d:"Les règles de la loi qui disent qui hérite, et dans quel ordre, quand il n'y a pas de testament.",x:"Sans testament, la dévolution légale fait passer les enfants avant les parents du défunt."},
 {t:"conjoint survivant",c:"PATRI FISCA NEGO",d:"L'époux ou l'épouse qui reste en vie après le décès de l'autre.",x:"Le conjoint survivant hérite sans payer de droits de succession."},
 {t:"régime matrimonial",f:["régimes matrimoniaux"],c:"PATRI FISCA NEGO",d:"Les règles qui disent à qui appartiennent les biens d'un couple marié.",x:"Sans contrat de mariage, c'est la communauté réduite aux acquêts."},
 {t:"communauté réduite aux acquêts",c:"PATRI NEGO",d:"Le régime par défaut des couples mariés : ce qui est acheté pendant le mariage est commun, le reste reste personnel.",x:"L'appartement acheté à deux après le mariage est commun, l'héritage de Paul reste à lui."},
 {t:"acquêts",c:"PATRI",d:"Les biens achetés pendant le mariage avec les revenus du couple : ils sont communs.",x:"La voiture achetée ensemble l'an dernier fait partie des acquêts."},
 {t:"biens propres",c:"PATRI NEGO",d:"Les biens qui appartiennent à un seul époux : ceux d'avant le mariage, ou reçus par donation ou héritage.",x:"La maison héritée par Claire reste un bien propre, même mariée."},
 {t:"communauté universelle",c:"PATRI NEGO",d:"Un régime où tous les biens des époux sont communs, même ceux d'avant le mariage.",x:"Des retraités passent en communauté universelle pour protéger le survivant."},
 {t:"séparation de biens",c:"PATRI NEGO FISCA",d:"Un régime où chaque époux reste seul propriétaire de ce qu'il achète ou reçoit.",x:"Une commerçante choisit la séparation de biens pour protéger son mari de ses dettes."},
 {t:"avantage matrimonial",f:["avantages matrimoniaux"],c:"PATRI",d:"Un avantage donné à un époux par le contrat de mariage. Il joue avant la succession.",x:"La clause d'attribution intégrale donne toute la communauté au survivant."},
 {t:"préciput",c:"PATRI",d:"Une clause du contrat de mariage qui permet au survivant de prendre un bien commun avant tout partage.",x:"Paul garde la résidence principale avant que l'on partage le reste."},
 {t:"libéralité",f:["libéralités"],c:"PATRI",d:"Un cadeau sans contrepartie, fait de son vivant (donation) ou au décès (legs).",x:"Donner un appartement à sa nièce est une libéralité."},
 {t:"exhérédation",c:"PATRI",d:"Le fait de priver un héritier de sa part, par testament. C'est impossible pour la part réservée aux enfants.",x:"Un père peut déshériter son frère, pas son fils."},
 {t:"action en réduction",c:"PATRI",d:"Le recours d'un enfant qui a reçu moins que sa réserve : il fait réduire les cadeaux trop gros faits aux autres.",x:"Hugo, oublié par le testament, récupère sa part grâce à l'action en réduction."},
 {t:"représentation",c:"PATRI",d:"Quand un héritier est décédé avant, ses enfants prennent sa place dans la succession.",x:"Le fils de Paul étant décédé, les petits-enfants héritent de sa part."},
 {t:"renonciation",c:"PATRI",d:"Le fait de refuser un héritage : on ne reçoit ni les biens, ni les dettes.",x:"Une succession pleine de dettes ? Les enfants peuvent y renoncer."},
 {t:"PACS",c:"PATRI FISCA NEGO",d:"Pacte civil de solidarité : un contrat de vie commune, plus léger que le mariage.",x:"Partenaires de PACS, Inès et Tom ne paient pas de droits entre eux, mais n'héritent pas sans testament."},
 {t:"concubin",f:["concubine","concubins"],c:"PATRI FISCA NEGO",d:"La personne avec qui l'on vit en couple sans être marié ni pacsé.",x:"Une concubine qui hérite par testament paie 60 % de droits."},
 {t:"ascendant",f:["ascendants"],c:"PATRI FISCA",d:"Un membre de la famille dont on descend : parent, grand-parent.",x:"Les parents du défunt sont ses ascendants."},
 {t:"descendant",f:["descendants"],c:"PATRI FISCA",d:"Un membre de la famille qui descend de soi : enfant, petit-enfant.",x:"Les enfants et petits-enfants sont des descendants."},
 {t:"collatéral",f:["collatéraux"],c:"PATRI",d:"Un membre de la famille qui n'est ni un ascendant ni un descendant : frère, sœur, neveu, oncle, cousin.",x:"Un neveu est un collatéral : il hérite après les enfants et les parents."},
 {t:"assurance-vie",f:["assurances-vie"],c:"PATRI FISCA NEGO",d:"Un placement : l'argent versé fructifie, puis il est transmis à la personne choisie au décès, avec une fiscalité douce.",x:"Marie verse 50 000 € sur une assurance-vie au profit de ses deux enfants."},
 {t:"clause bénéficiaire",f:["clauses bénéficiaires"],c:"PATRI NEGO FISCA",d:"La phrase du contrat d'assurance-vie qui dit qui recevra l'argent au décès.",x:"« Mon conjoint, à défaut mes enfants par parts égales »."},
 {t:"rachat",f:["rachats"],c:"PATRI NEGO FISCA",d:"Un retrait d'argent sur un contrat d'assurance-vie, en partie ou en totalité.",x:"Paul retire 20 000 € de son contrat pour payer des travaux : c'est un rachat partiel."},
 {t:"rente viagère",f:["rentes viagères"],c:"PATRI FISCA NEGO",d:"Une somme versée régulièrement à quelqu'un, jusqu'à la fin de sa vie.",x:"Au lieu de 100 000 € d'un coup, Paul touche 400 € par mois jusqu'à son décès."},
 {t:"viager",c:"PATRI FISCA",d:"La vente d'un logement contre une somme au départ (le bouquet) et une rente versée au vendeur jusqu'à son décès.",x:"Jeanne, 78 ans, vend sa maison en viager : 50 000 € tout de suite, puis 900 € par mois."},
 {t:"bouquet",c:"FISCA PATRI",d:"La somme versée comptant au vendeur le jour d'une vente en viager.",x:"Bouquet de 50 000 €, puis une rente chaque mois."},
 {t:"pacte Dutreil",f:["Dutreil"],c:"PATRI",d:"Un dispositif qui réduit fortement les droits quand on transmet une entreprise familiale, si les héritiers s'engagent à la garder plusieurs années.",x:"Le fondateur transmet sa PME à ses enfants : seul un quart de sa valeur est taxé."},
 {t:"holding",f:["holdings"],c:"PATRI FISCA",d:"Une société dont le métier est de détenir des parts d'autres sociétés.",x:"Marc détient sa société de plomberie via une holding qui reçoit les dividendes."},
 {t:"SCI",c:"PATRI FISCA NEGO",d:"Société civile immobilière : une société créée pour détenir et gérer un ou plusieurs biens immobiliers à plusieurs.",x:"Deux frères mettent l'appartement familial dans une SCI et se partagent les parts."},
 {t:"SARL",c:"PATRI",d:"Société à responsabilité limitée : une forme de société courante pour les PME, dirigée par un gérant.",x:"Le garage de Luc est une SARL dont il est le gérant."},
 {t:"SAS",c:"PATRI",d:"Société par actions simplifiée : une forme de société souple, dirigée par un président.",x:"Une start-up créée à trois associés en SAS."},
 {t:"cédant",f:["cédants"],c:"PATRI FISCA",d:"Celui qui vend (cède) son entreprise ou ses parts.",x:"Le cédant part à la retraite et vend sa boulangerie."},
 {t:"cessionnaire",f:["cessionnaires"],c:"PATRI FISCA",d:"Celui qui achète (reçoit) l'entreprise ou les parts.",x:"Le cessionnaire reprend la boulangerie et ses salariés."},
 {t:"garantie d'actif et de passif",c:"PATRI",d:"Le vendeur d'une entreprise s'engage à rembourser l'acheteur si une dette cachée, née avant la vente, apparaît.",x:"Un redressement fiscal sur l'année d'avant la vente ? C'est le vendeur qui paie."},
 {t:"caution",c:"PATRI NEGO",d:"Une personne qui s'engage à payer la dette d'un autre s'il ne la paie pas.",x:"Les parents se portent caution du prêt étudiant de leur fille."},
 {t:"plus-value",f:["plus-values"],c:"PATRI FISCA NEGO",d:"Le gain réalisé quand on revend un bien plus cher qu'on ne l'a acheté.",x:"Acheté 200 000 €, revendu 260 000 € : 60 000 € de plus-value."},
 {t:"PFU",c:"PATRI FISCA NEGO",d:"Prélèvement forfaitaire unique : un taux unique, impôt et prélèvements sociaux compris, sur les revenus des placements.",x:"Intérêts, dividendes et plus-values sur actions sont taxés au PFU par défaut."},
 {t:"flat tax",c:"PATRI FISCA NEGO",d:"Le surnom du PFU : un taux unique sur les revenus des placements, au lieu du barème progressif.",x:"Avec la flat tax, 1 000 € de dividendes subissent le même taux pour tout le monde."},
 {t:"prélèvements sociaux",c:"PATRI FISCA NEGO",d:"Des contributions (CSG, CRDS...) prélevées sur les revenus du patrimoine, en plus de l'impôt. Elles financent la Sécurité sociale.",x:"Les loyers d'un studio supportent l'impôt et les prélèvements sociaux."},
 {t:"CSG",c:"PATRI FISCA NEGO",d:"Contribution sociale généralisée : la plus grosse part des prélèvements sociaux.",x:"La CSG est prélevée sur les salaires, les retraites et les revenus des placements."},
 {t:"IFI",c:"PATRI FISCA NEGO",d:"Impôt sur la fortune immobilière : un impôt annuel sur le patrimoine immobilier des foyers les plus aisés, au-delà d'un seuil.",x:"Un couple qui possède plusieurs appartements de valeur déclare l'IFI chaque année."},
 {t:"SCPI",c:"FISCA NEGO PATRI",d:"Société civile de placement immobilier : on achète des parts d'un grand parc immobilier géré par des pros, et on touche une part des loyers.",x:"Avec 1 000 €, on détient un petit bout de bureaux et de commerces."},
 {t:"OPCVM",c:"FISCA NEGO",d:"Un fonds de placement qui regroupe l'argent de nombreux épargnants pour l'investir en actions, obligations...",x:"Un fonds actions européennes acheté via sa banque est un OPCVM."},
 {t:"SICAV",c:"FISCA NEGO",d:"Un fonds de placement constitué en société : en achetant une part, on devient actionnaire du fonds.",x:"Une SICAV monétaire placée par la banque."},
 {t:"FCP",c:"FISCA NEGO",d:"Fonds commun de placement : une copropriété de titres, sans être une société.",x:"Un FCP où chaque porteur détient une part du panier d'actions."},
 {t:"ETF",c:"FISCA NEGO",d:"Un fonds coté en Bourse qui copie un indice, comme le CAC 40, avec des frais faibles.",x:"Un ETF MSCI World achète d'un coup les grandes entreprises du monde entier."},
 {t:"PER",c:"FISCA NEGO PATRI",d:"Plan d'épargne retraite : une épargne bloquée jusqu'à la retraite, dont les versements peuvent réduire l'impôt.",x:"Élise verse 5 000 € sur son PER et les déduit de son revenu imposable."},
 {t:"PEA",c:"FISCA NEGO",d:"Plan d'épargne en actions : une enveloppe pour placer en actions européennes, avec un avantage fiscal après 5 ans.",x:"Après 5 ans, les gains d'un PEA ne supportent plus que les prélèvements sociaux."},
 {t:"fonds euros",f:["fonds en euros"],c:"FISCA NEGO PATRI",d:"Le support sans risque de l'assurance-vie : le capital est garanti par l'assureur, le rendement est modeste.",x:"Un fonds euros a rapporté autour de 2,5 % par an ces dernières années."},
 {t:"unités de compte",c:"FISCA NEGO PATRI",d:"Les supports à risque de l'assurance-vie (actions, immobilier...) : leur valeur peut monter ou baisser.",x:"Mettre 30 % en unités de compte pour viser plus de rendement."},
 {t:"frais d'entrée",c:"FISCA NEGO",d:"Un pourcentage prélevé sur chaque somme versée sur un placement.",x:"3 % de frais d'entrée sur 10 000 € : seuls 9 700 € sont placés."},
 {t:"frais de gestion",c:"FISCA NEGO",d:"Un pourcentage prélevé chaque année sur l'épargne, pour payer celui qui la gère.",x:"0,8 % de frais de gestion sur 50 000 € : 400 € par an."},
 {t:"TVA",c:"FISCA",d:"Taxe sur la valeur ajoutée : l'impôt inclus dans le prix de ce qu'on achète.",x:"Un logement neuf vendu 240 000 € TTC contient 40 000 € de TVA à 20 %."},
 {t:"VEFA",c:"FISCA",d:"Vente en l'état futur d'achèvement : on achète un logement sur plan, payé au fil de la construction.",x:"On signe en 2026 pour un appartement livré en 2028."},
 {t:"PTZ",c:"FISCA",d:"Prêt à taux zéro : un prêt aidé par l'État, sans intérêts, pour acheter sa première résidence principale.",x:"Un couple finance une partie de son achat avec un PTZ de 80 000 €."},
 {t:"primo-accédant",f:["primo-accédants"],c:"FISCA",d:"Quelqu'un qui n'a pas été propriétaire de sa résidence principale ces deux dernières années.",x:"Un jeune locataire qui achète son premier logement est primo-accédant."},
 {t:"zone tendue",f:["zones tendues"],c:"FISCA",d:"Une ville où il manque des logements par rapport à la demande : les loyers y sont élevés et encadrés.",x:"Paris, Lyon et Lille sont en zone tendue."},
 {t:"surface pondérée",c:"FISCA",d:"La surface habitable plus la moitié des annexes (balcon, cave...), dans la limite de 8 m².",x:"50 m² habitables et 6 m² de balcon : 53 m² de surface pondérée."},
 {t:"Pinel",c:"FISCA",d:"Un ancien dispositif de réduction d'impôt pour l'achat d'un logement neuf mis en location. Il a pris fin le 31 décembre 2024.",x:"Un appartement acheté en Pinel en 2022 garde son avantage jusqu'au bout de l'engagement."},
 {t:"Jeanbrun",c:"FISCA",d:"Le nouveau dispositif d'investissement locatif : on amortit une partie du prix du logement loué, ce qui réduit le revenu imposable.",x:"Pinel réduisait l'impôt, Jeanbrun réduit le revenu sur lequel on le calcule."},
 {t:"Denormandie",c:"FISCA",d:"Une réduction d'impôt pour l'achat d'un logement ancien à rénover dans certaines villes, puis mis en location.",x:"Acheter un vieil appartement dans un centre-ville à revitaliser et le refaire."},
 {t:"Malraux",c:"FISCA",d:"Une réduction d'impôt pour restaurer un immeuble dans un quartier historique protégé.",x:"Restaurer une façade dans le vieux centre de Bordeaux."},
 {t:"revenus fonciers",c:"FISCA NEGO",d:"Les loyers tirés de la location d'un logement vide (non meublé).",x:"Les 9 000 € de loyers annuels d'un T2 vide sont des revenus fonciers."},
 {t:"micro-foncier",c:"FISCA",d:"Le régime simple pour les loyers de logements vides : le fisc retire un forfait de 30 % pour les charges.",x:"12 000 € de loyers : seuls 8 400 € sont imposés."},
 {t:"régime réel",c:"FISCA",d:"On déduit ses vraies charges (travaux, intérêts d'emprunt, taxe foncière) au lieu d'un forfait.",x:"Avec 6 000 € de travaux, le régime réel bat le forfait."},
 {t:"déficit foncier",c:"FISCA",d:"Quand les charges d'un logement loué vide dépassent les loyers, la perte peut réduire les autres revenus imposables, dans une limite.",x:"20 000 € de travaux pour 8 000 € de loyers : la perte réduit l'impôt sur le salaire."},
 {t:"meublé",f:["location meublée"],c:"FISCA",d:"Un logement loué avec les meubles nécessaires pour y vivre : il a sa propre fiscalité.",x:"Un studio étudiant loué équipé (lit, table, frigo, plaques) est un meublé."},
 {t:"amortissement",f:["amortissements"],c:"FISCA",d:"Déduire chaque année une part du prix d'un bien pour tenir compte de son usure.",x:"Un logement de 200 000 € hors terrain, amorti sur 30 ans, permet de déduire environ 6 700 € par an."},
 {t:"réduction d'impôt",f:["réductions d'impôt"],c:"FISCA NEGO",d:"Une somme retirée directement de l'impôt à payer. Si elle dépasse l'impôt, le surplus est perdu.",x:"2 000 € d'impôt et 2 500 € de réduction : on paie 0, les 500 € restants sont perdus."},
 {t:"crédit d'impôt",f:["crédits d'impôt"],c:"FISCA NEGO",d:"Comme une réduction, sauf que si elle dépasse l'impôt, le fisc rembourse la différence.",x:"500 € d'impôt et 800 € de crédit : le fisc verse 300 €."},
 {t:"délai de jouissance",c:"FISCA",d:"Le temps d'attente entre l'achat de parts de SCPI et le premier loyer versé.",x:"Parts achetées en janvier, premiers revenus en mai : quatre mois de délai de jouissance."},
 {t:"effet de levier",c:"FISCA BANQUE NEGO",d:"Emprunter pour investir plus que son apport : les gains, comme les pertes, sont amplifiés.",x:"Avec 20 000 € d'apport et un prêt, on achète un bien de 200 000 €."},
 {t:"impôt sur les sociétés",f:["IS"],c:"FISCA PATRI",d:"L'impôt payé par une entreprise sur ses bénéfices, et non par ses associés.",x:"Une SCI qui opte pour l'IS paie l'impôt elle-même sur son bénéfice."},
 {t:"délai de réflexion",c:"NEGO FISCA",d:"Un temps imposé avant de pouvoir accepter une offre, pour éviter de signer sous la pression.",x:"Après une offre de prêt immobilier, on attend 10 jours avant de l'accepter."},
 /* ---------- negociation, conseil bancaire ---------- */
 {t:"MESORE",c:"NEGO NON",d:"Meilleure solution de rechange : ce que tu feras si la négociation échoue. Plus elle est bonne, plus tu es libre de refuser.",x:"Avoir une autre offre de prêt en poche avant d'aller voir sa banque."},
 {t:"BATNA",c:"NEGO",d:"Le nom anglais de la MESORE : la meilleure solution si l'on ne signe pas.",x:"Ta BATNA, c'est l'offre concurrente à 3,4 %."},
 {t:"SONCAS",c:"NEGO",d:"Les six motivations d'achat d'un client : sécurité, orgueil, nouveauté, confort, argent, sympathie.",x:"Un client qui demande « et si ça baisse ? » parle sécurité."},
 {t:"ancrage",c:"NEGO",d:"Le premier chiffre posé dans une négociation : il sert de point de repère à toute la suite.",x:"Annoncer d'abord 5 000 € fait paraître 4 200 € raisonnable."},
 {t:"reformulation",c:"NEGO",d:"Redire avec ses mots ce que l'autre vient de dire, pour vérifier qu'on a compris et lui montrer qu'on écoute.",x:"« Si je comprends bien, ce qui vous inquiète, c'est de bloquer l'argent ? »"},
 {t:"IOBSP",c:"NEGO",d:"Intermédiaire en opérations de banque : celui qui place des crédits pour des banques, comme un courtier en prêt immobilier.",x:"Le courtier qui négocie ton prêt auprès de plusieurs banques est un IOBSP."},
 {t:"CIF",c:"NEGO",d:"Conseiller en investissements financiers : un professionnel agréé qui conseille sur les placements.",x:"Un conseiller en gestion de patrimoine indépendant est souvent CIF."},
 {t:"IAS",c:"NEGO",d:"Intermédiaire en assurance : celui qui conseille et vend des contrats d'assurance.",x:"Le conseiller qui propose une assurance-vie agit comme IAS."},
 {t:"ACPR",c:"NEGO RISK FISCA BANQUE",d:"Autorité de contrôle prudentiel et de résolution : elle surveille les banques et les assurances en France.",x:"Une banque qui vend mal ses crédits peut être sanctionnée par l'ACPR."},
 {t:"AMF",c:"NEGO RISK FISCA",d:"Autorité des marchés financiers : elle surveille la Bourse, les produits financiers et ceux qui les vendent.",x:"L'AMF publie des listes noires de faux sites de placement."},
 {t:"LCB-FT",c:"NEGO RISK",d:"Lutte contre le blanchiment et le financement du terrorisme : les règles qui obligent la banque à vérifier d'où vient l'argent.",x:"Un dépôt de 80 000 € en espèces ? La banque demande l'origine des fonds."},
 {t:"KYC",c:"NEGO RISK",d:"Know your customer : bien connaître son client (identité, situation, objectifs) avant de lui vendre quoi que ce soit.",x:"Le questionnaire rempli à l'ouverture du compte, c'est le KYC."},
 {t:"TRACFIN",c:"NEGO RISK",d:"Le service de l'État à qui la banque signale les opérations qui pourraient cacher du blanchiment.",x:"Des virements répétés juste sous les seuils déclenchent une déclaration à TRACFIN."},
 {t:"PPE",c:"NEGO RISK",d:"Personne politiquement exposée : quelqu'un qui a, ou a eu, une fonction publique importante, donc surveillé de plus près.",x:"Un maire de grande ville ou un ministre est une PPE."},
 {t:"MIF",c:"NEGO",d:"La directive européenne qui oblige à proposer des placements adaptés au profil de chaque client.",x:"Avant de vendre des actions, la banque vérifie que le client comprend le risque."},
 {t:"devoir de conseil",c:"NEGO",d:"L'obligation de recommander une solution adaptée à la situation et aux objectifs du client, pas la plus rentable pour le vendeur.",x:"Déconseiller un placement bloqué 8 ans à quelqu'un qui achète une maison l'an prochain."},
 {t:"profil de risque",f:["profils de risque"],c:"NEGO",d:"Le niveau de risque qu'un client accepte, selon sa situation, son horizon et sa réaction face aux pertes.",x:"Un retraité prudent a un profil de risque bas."},
 /* ---------- finance, credit, banque ---------- */
 {t:"spread",f:["spreads"],c:"MRC RISK BANQUE",d:"L'écart de rendement entre une obligation risquée et un placement sans risque : c'est le prix du risque de défaut.",x:"L'État emprunte à 3 %, l'entreprise à 5 % : le spread est de 2 %."},
 {t:"obligation",f:["obligations"],c:"MRC BANQUE FISCA NEGO RISK",d:"Un titre de dette : on prête à une entreprise ou un État, qui verse des intérêts puis rembourse.",x:"Une obligation de 1 000 € à 4 % rapporte 40 € par an, puis 1 000 € à la fin."},
 {t:"taux sans risque",c:"MRC RISK BANQUE",d:"Le rendement d'un placement jugé sans risque de défaut, comme un emprunt d'un État solide.",x:"On prend souvent le taux des emprunts d'État allemands comme taux sans risque."},
 {t:"zéro-coupon",c:"MRC",d:"Une obligation qui ne verse aucun intérêt en cours de route : on l'achète moins cher et on reçoit la valeur pleine à la fin.",x:"Payée 950 € aujourd'hui, elle rembourse 1 000 € dans un an."},
 {t:"put",f:["puts"],c:"MRC",d:"Une option qui donne le droit de vendre un actif à un prix fixé à l'avance.",x:"Un put à 100 € sur une action qui tombe à 70 € rapporte 30 €."},
 {t:"call",f:["calls"],c:"MRC",d:"Une option qui donne le droit d'acheter un actif à un prix fixé à l'avance.",x:"Un call à 100 € sur une action qui monte à 130 € rapporte 30 €."},
 {t:"prix d'exercice",c:"MRC",d:"Le prix fixé à l'avance auquel une option permet d'acheter ou de vendre.",x:"Un call de prix d'exercice 100 € : on pourra acheter à 100 €, quel que soit le cours."},
 {t:"sous-jacent",f:["sous-jacents"],c:"MRC RISK",d:"L'actif sur lequel porte un produit dérivé (une action, un indice, les actifs d'une entreprise).",x:"Pour une option sur l'action Airbus, le sous-jacent est l'action Airbus."},
 {t:"maturité",c:"MRC BANQUE RISK",d:"La date, ou la durée, au bout de laquelle un prêt ou une obligation doit être remboursé.",x:"Une obligation de maturité 5 ans rembourse son capital dans 5 ans."},
 {t:"nominal",c:"MRC NEGO BANQUE",d:"Le montant prêté qui sera remboursé à la fin, sur lequel on calcule les intérêts.",x:"Une obligation de nominal 1 000 € à 3 % verse 30 € par an."},
 {t:"volatilité",c:"MRC RISK NEGO",d:"L'ampleur des variations d'un prix : plus elle est forte, plus la valeur bouge, et plus c'est risqué.",x:"Une action qui fait souvent plus ou moins 5 % en un jour est très volatile."},
 {t:"recouvrement",c:"MRC",d:"La part de la dette que le prêteur récupère quand l'emprunteur fait défaut.",x:"Recouvrement de 40 % : sur 100 € prêtés, on récupère 40 €."},
 {t:"corrélation",c:"MRC RISK",d:"La tendance de deux choses à bouger ensemble, de -1 (en sens opposés) à +1 (exactement ensemble).",x:"Deux entreprises du même secteur ont des défauts très corrélés en crise."},
 {t:"loi normale",c:"MRC RISK",d:"La courbe en cloche : la plupart des valeurs sont proches de la moyenne, les extrêmes sont rares.",x:"N(d2) lit dans la loi normale la probabilité d'être au-dessus du seuil."},
 {t:"probabilité de défaut",f:["probabilités de défaut"],c:"MRC RISK BANQUE",d:"La chance, en pourcentage, qu'un emprunteur ne rembourse pas, en général sur un an.",x:"Une PD de 2 % : sur 100 emprunteurs semblables, environ 2 feront défaut dans l'année."},
 {t:"CDS",c:"MRC RISK",d:"Credit default swap : une assurance contre le défaut d'une entreprise. On paie une prime régulière et on est indemnisé en cas de défaut.",x:"Une banque achète un CDS pour se protéger si son gros client fait faillite."},
 {t:"risque neutre",c:"MRC",d:"Une méthode de calcul où l'on fait comme si les investisseurs ne demandaient aucune prime de risque : on actualise alors au taux sans risque.",x:"En univers risque neutre, toutes les valeurs grandissent en moyenne au taux sans risque."},
 {t:"lemme d'Itô",c:"MRC",d:"La règle de calcul qui dit comment évolue une fonction d'un prix aléatoire, par exemple le logarithme d'un cours.",x:"Grâce au lemme d'Itô, on passe de dS à d ln(S)."},
 {t:"mouvement brownien",f:["brownien"],c:"MRC",d:"Un mouvement aléatoire continu, fait de petits chocs imprévisibles : le modèle de base des cours de Bourse.",x:"Le terme sigma dz représente les chocs browniens."},
 {t:"Merton",c:"MRC",d:"Le modèle de 1974 qui voit les actions d'une entreprise comme une option d'achat sur ses actifs : il y a défaut si les actifs tombent sous la dette.",x:"Actifs de 120, dette de 100 à rembourser : les actionnaires gardent 20."},
 {t:"FTD",c:"MRC",d:"First to default : un contrat qui indemnise dès le premier défaut dans un panier d'entreprises.",x:"Panier de 10 entreprises : le FTD paie à la première faillite."},
 {t:"prime de risque",f:["primes de risque"],c:"MRC BANQUE RISK",d:"Le supplément de rendement exigé pour accepter un risque.",x:"Une entreprise fragile doit offrir 3 % de plus que l'État pour trouver des prêteurs."},
 {t:"arbitrage",c:"MRC",d:"Gagner de l'argent sans risque en profitant d'un écart de prix anormal. En théorie, cela ne dure pas.",x:"Acheter un actif 99 € à Paris pour le revendre 100 € à Londres au même instant."},
 {t:"actualisation",f:["actualiser"],c:"MRC RISK PATRI",d:"Ramener une somme future à sa valeur d'aujourd'hui, parce qu'un euro demain vaut moins qu'un euro aujourd'hui.",x:"1 050 € dans un an, actualisés à 5 %, valent 1 000 € aujourd'hui."},
 {t:"fonds propres",c:"MRC BANQUE RISK",d:"L'argent apporté par les actionnaires et les bénéfices gardés : le coussin qui absorbe les pertes.",x:"Une banque qui perd 10 M€ les impute sur ses fonds propres."},
 {t:"dividende",f:["dividendes"],c:"MRC PATRI FISCA NEGO",d:"La part du bénéfice qu'une société verse à ses actionnaires.",x:"Une action qui verse 2 € de dividende par an."},
 {t:"coupon",f:["coupons"],c:"MRC FISCA",d:"L'intérêt versé régulièrement par une obligation.",x:"Un coupon annuel de 40 € sur une obligation de 1 000 €."},
 {t:"intermédiation",c:"BANQUE",d:"Le métier de base d'une banque : collecter l'épargne des uns pour prêter aux autres.",x:"Les dépôts des clients financent les prêts immobiliers d'autres clients."},
 {t:"asymétrie d'information",f:["asymétries d'information"],c:"BANQUE",d:"Quand une partie en sait plus que l'autre : l'emprunteur connaît mieux son propre risque que la banque.",x:"Le patron sait que ses ventes chutent, son banquier pas encore."},
 {t:"aléa moral",c:"BANQUE RISK",d:"Quand quelqu'un prend plus de risques parce qu'il est protégé des conséquences.",x:"Une banque sûre d'être sauvée par l'État prête plus imprudemment."},
 {t:"sélection adverse",c:"BANQUE",d:"Quand un prix mal ajusté attire surtout les mauvais risques.",x:"Un taux trop élevé fait fuir les bons emprunteurs et ne garde que les plus risqués."},
 {t:"création monétaire",c:"BANQUE",d:"En accordant un crédit, la banque crée de la monnaie : elle inscrit la somme sur le compte de l'emprunteur.",x:"Un prêt de 200 000 € fait apparaître 200 000 € sur le compte du client."},
 {t:"taux directeur",f:["taux directeurs"],c:"MRC BANQUE RISK",d:"Le taux auquel la banque centrale prête aux banques : il influence tous les autres taux.",x:"Quand la BCE monte son taux directeur, les crédits immobiliers deviennent plus chers."},
 {t:"BCE",c:"RISK BANQUE MRC",d:"Banque centrale européenne : elle fixe les taux directeurs de la zone euro et supervise les grandes banques.",x:"La BCE contrôle directement BNP Paribas ou la Société Générale."},
 {t:"perte attendue",f:["pertes attendues"],c:"RISK MRC",d:"La perte moyenne que l'on prévoit sur un prêt : PD x LGD x EAD. Elle est couverte par les provisions.",x:"PD 2 %, LGD 40 %, EAD 100 000 € : 800 € de perte attendue."},
 {t:"LGD",c:"RISK MRC",d:"Loss given default : la part de la somme due que l'on perd vraiment si l'emprunteur fait défaut, après les garanties.",x:"Prêt de 100 000 €, on récupère 60 000 € : LGD de 40 %."},
 {t:"EAD",c:"RISK MRC",d:"Exposure at default : le montant encore dû au moment du défaut.",x:"Il restait 80 000 € à rembourser le jour du défaut : EAD de 80 000 €."},
 {t:"VaR",c:"RISK",d:"Value at Risk : la perte maximale que l'on ne devrait pas dépasser, avec une probabilité donnée, sur une période.",x:"VaR à 99 % sur un jour de 2 M€ : 99 jours sur 100, on perd moins de 2 M€."},
 {t:"RWA",c:"RISK BANQUE",d:"Actifs pondérés par les risques : les prêts et titres de la banque, chacun compté selon son risque, pour calculer le capital exigé.",x:"100 M€ de prêts très sûrs peuvent ne compter que pour 20 M€ de RWA."},
 {t:"Bâle",f:["Bâle III","Bâle II","Bâle IV"],c:"RISK BANQUE",d:"Les accords internationaux (Bâle I, II, III) qui fixent combien de capital une banque doit garder face à ses risques.",x:"Bâle III a durci les exigences après la crise de 2008."},
 {t:"LCR",c:"RISK",d:"Ratio de liquidité à 30 jours : la banque doit avoir assez d'actifs faciles à vendre pour tenir un mois de crise.",x:"LCR de 130 % : la banque couvre 1,3 fois ses sorties de cash d'un mois de crise."},
 {t:"NSFR",c:"RISK",d:"Ratio de financement stable : les prêts longs doivent être financés par des ressources stables, sur un an.",x:"Un crédit sur 20 ans financé par de l'épargne bloquée plutôt que par des dépôts du jour."},
 {t:"HQLA",c:"RISK",d:"Actifs liquides de haute qualité : ce que la banque peut vendre vite sans perte (cash, dettes d'États solides).",x:"Des obligations d'État françaises comptent comme HQLA."},
 {t:"backtesting",c:"RISK",d:"Vérifier après coup si un modèle a bien prévu, en comparant ses prévisions aux pertes vraiment constatées.",x:"Une VaR à 99 % ne doit être dépassée qu'environ 2 à 3 jours sur 250."},
 {t:"stress test",f:["stress tests"],c:"RISK BANQUE",d:"Simuler une crise grave (récession, krach) pour voir si la banque tiendrait le choc.",x:"Et si l'immobilier chutait de 30 % et le chômage doublait ?"},
 {t:"ICAAP",c:"RISK",d:"Le processus interne par lequel la banque évalue elle-même le capital dont elle a besoin face à tous ses risques.",x:"La banque ajoute un coussin pour le risque de taux, que le Pilier 1 ne couvre pas."},
 {t:"Pilier 2",c:"RISK",d:"La partie de Bâle où le superviseur examine les risques propres à chaque banque et peut exiger plus de capital.",x:"La BCE impose 2 % de capital en plus à une banque jugée fragile."},
 {t:"risque opérationnel",c:"RISK BANQUE",d:"Le risque de perte due à une erreur, une fraude, une panne informatique ou un événement extérieur.",x:"Un trader qui cache ses pertes, une cyberattaque."},
 {t:"risque de marché",c:"RISK BANQUE",d:"Le risque de perdre à cause des variations des prix de marché (actions, taux, devises).",x:"Le portefeuille d'actions de la banque perd 8 % en une semaine."},
 {t:"risque de contrepartie",c:"RISK MRC",d:"Le risque que l'autre partie d'un contrat ne paie pas ce qu'elle doit.",x:"La banque qui vous a vendu une protection fait faillite avant de payer."},
 {t:"collatéral",c:"RISK",d:"Un bien ou des titres remis en garantie, saisis si l'emprunteur ne rembourse pas.",x:"Des obligations d'État déposées en garantie d'un prêt de trésorerie."},
 {t:"provisions",f:["provision"],c:"RISK BANQUE",d:"De l'argent mis de côté dans les comptes pour couvrir des pertes probables.",x:"La banque provisionne 1 M€ pour des prêts qui risquent de ne pas être remboursés."},
 /* ---------- nutrition ---------- */
 {t:"métabolisme de base",c:"NUTRI",d:"L'énergie que le corps dépense au repos complet, juste pour vivre (cœur, respiration, cerveau).",x:"Pour un adulte, souvent entre 1 300 et 1 800 kcal par jour."},
 {t:"IMC",c:"NUTRI",d:"Indice de masse corporelle : le poids (en kg) divisé par la taille (en m) au carré.",x:"70 kg pour 1,75 m : 70 / 3,06 = 22,9."},
 {t:"kcal",c:"NUTRI",d:"Kilocalorie : l'unité de l'énergie apportée par les aliments.",x:"Une pomme moyenne apporte environ 80 kcal."},
 {t:"glucides",c:"NUTRI",d:"Les sucres et l'amidon des aliments : la source d'énergie la plus rapide.",x:"Pain, pâtes, riz et fruits sont riches en glucides."},
 {t:"lipides",c:"NUTRI",d:"Les graisses des aliments.",x:"Huile, beurre, fromage, noix."},
 {t:"protéines",c:"NUTRI",d:"Les nutriments qui construisent et réparent les muscles et les tissus.",x:"Œufs, viande, poisson, lentilles, yaourt."},
 {t:"satiété",c:"NUTRI",d:"La sensation de ne plus avoir faim, qui dure après le repas.",x:"Un bol de lentilles tient plus longtemps au corps qu'un soda."},
 {t:"stéatose",c:"NUTRI",d:"Une accumulation de graisse dans le foie, souvent liée à un excès de sucre ou d'alcool.",x:"On parle aussi de « foie gras » humain."},
 {t:"insuline",c:"NUTRI",d:"L'hormone qui fait entrer le sucre du sang dans les cellules et favorise le stockage.",x:"Après un repas sucré, le pancréas libère de l'insuline."},
 {t:"oméga-3",c:"NUTRI",d:"Des graisses utiles au cœur et au cerveau, que le corps ne sait pas fabriquer.",x:"Sardine, maquereau, saumon, huile de colza, noix."},
 {t:"fibres",c:"NUTRI",d:"La partie des végétaux qu'on ne digère pas : elle rassasie et nourrit la flore intestinale.",x:"Légumes, fruits, légumineuses, pain complet."},
 {t:"masse grasse",c:"NUTRI",d:"La part du poids du corps faite de graisse.",x:"Deux personnes de 80 kg peuvent avoir une masse grasse très différente."},
 /* ---------- sports ---------- */
 {t:"clinch",c:"MMA",d:"Le corps à corps debout : les deux combattants se tiennent, souvent contre la cage.",x:"Il le plaque contre la cage et frappe aux genoux dans le clinch."},
 {t:"sprawl",c:"MMA",d:"La défense contre l'amenée : on jette les jambes en arrière et on écrase le dos de l'adversaire avec ses hanches.",x:"Il plonge sur les jambes, l'autre sprawle et se retrouve au-dessus."},
 {t:"amenée",f:["amenées"],c:"MMA",d:"Une technique pour faire tomber l'adversaire au sol (en anglais : takedown).",x:"Une double jambe qui envoie l'adversaire sur le dos."},
 {t:"TKO",c:"MMA",d:"KO technique : l'arbitre ou le médecin arrête le combat parce qu'un combattant ne se défend plus.",x:"Une série de coups au sol sans réaction : l'arbitre arrête, TKO."},
 {t:"uppercut",f:["uppercuts"],c:"MMA",d:"Un coup de poing qui monte de bas en haut, vers le menton.",x:"Il baisse la tête pour plonger et prend l'uppercut."},
 {t:"jab",f:["jabs"],c:"MMA",d:"Le coup droit rapide du bras avant, pour mesurer la distance et ouvrir la garde.",x:"Jab, jab, puis le direct du bras arrière."},
 {t:"low kick",f:["low kicks"],c:"MMA",d:"Un coup de pied circulaire dans la cuisse ou le mollet.",x:"Trois low kicks au mollet et il ne peut plus appuyer sur sa jambe."},
 {t:"soumission",f:["soumissions"],c:"MMA",d:"Une clé ou un étranglement qui force l'adversaire à abandonner en tapant.",x:"Un étranglement arrière : il tape, victoire par soumission."},
 {t:"lift",c:"TENNIS",d:"Un effet qui fait tourner la balle vers l'avant : elle plonge, puis rebondit haut.",x:"Un coup droit lifté qui gicle au-dessus de l'épaule de l'adversaire."},
 {t:"slice",c:"TENNIS",d:"Un effet coupé : la balle tourne vers l'arrière, reste basse et ralentit après le rebond.",x:"Un revers slicé qui oblige l'adversaire à se baisser."},
 {t:"break",f:["breaks"],c:"TENNIS",d:"Gagner un jeu sur le service de l'adversaire.",x:"À 4-3 avec un break d'avance, il sert pour mener 5-3."},
 {t:"tie-break",c:"TENNIS",d:"Le jeu décisif joué à 6 jeux partout : le premier à 7 points avec 2 points d'écart gagne le set.",x:"7-5 au tie-break, le set est à lui."},
 {t:"passing",f:["passings"],c:"TENNIS",d:"Un coup qui passe à côté de l'adversaire monté au filet.",x:"Il monte, elle le passe le long de la ligne."},
 {t:"volée",f:["volées"],c:"TENNIS",d:"Un coup frappé avant que la balle ne rebondisse, en général près du filet.",x:"Il monte au filet et termine d'une volée croisée."},
 {t:"lob",f:["lobs"],c:"TENNIS",d:"Une balle haute qui passe au-dessus de l'adversaire monté au filet.",x:"Collé au filet, il voit le lob retomber derrière lui."},
 {t:"xG",c:"FOOT",d:"Expected goals : la probabilité qu'un tir finisse au fond, selon sa position et la situation.",x:"Un penalty vaut environ 0,76 xG, une frappe de 30 mètres à peine 0,03."},
 {t:"pressing",c:"FOOT",d:"Presser le porteur du ballon à plusieurs pour le récupérer vite.",x:"Trois joueurs ferment les passes et forcent l'erreur du défenseur."},
 {t:"contre-pressing",c:"FOOT",d:"Presser tout de suite après avoir perdu le ballon, pour le reprendre dans les secondes qui suivent.",x:"Perte de balle, et les trois plus proches sautent sur le porteur."},
 {t:"bloc bas",c:"FOOT",d:"Une équipe qui défend près de sa surface, toutes ses lignes rapprochées.",x:"Mené 1-0, l'adversaire recule en bloc bas et ferme l'axe."},
 {t:"hors-jeu",c:"FOOT",d:"Un attaquant est hors-jeu s'il est plus près du but adverse que le ballon et l'avant-dernier défenseur au moment de la passe, dans le camp adverse.",x:"Il part un pas trop tôt : drapeau levé, hors-jeu."},
 {t:"demi-espace",f:["demi-espaces"],c:"FOOT",d:"Le couloir entre l'axe et le côté du terrain, dangereux car difficile à couvrir.",x:"Un milieu qui reçoit dans le demi-espace peut frapper ou centrer."},
 {t:"VAR",c:"FOOT",d:"L'assistance vidéo à l'arbitrage.",x:"La VAR revoit l'action et l'arbitre accorde le penalty."},
 {t:"roque",c:"ECHECS",d:"Un coup spécial : le roi va de deux cases vers une tour, la tour passe de l'autre côté du roi. Il met le roi à l'abri.",x:"Petit roque des Blancs : roi en g1, tour en f1."},
 {t:"clouage",f:["clouages"],c:"ECHECS",d:"Une pièce ne peut pas bouger sans exposer une pièce plus importante derrière elle.",x:"Le fou cloue le cavalier contre la dame : si le cavalier bouge, la dame tombe."},
 {t:"fourchette",f:["fourchettes"],c:"ECHECS",d:"Une pièce qui attaque deux pièces adverses en même temps.",x:"Le cavalier attaque à la fois le roi et la tour."},
 {t:"enfilade",c:"ECHECS",d:"On attaque une pièce importante qui, en s'écartant, laisse prendre celle qui est derrière.",x:"Échec de la tour au roi : il bouge, et la dame derrière lui tombe."},
 {t:"pat",c:"ECHECS",d:"Le joueur au trait n'est pas en échec mais n'a aucun coup légal : la partie est nulle.",x:"Avec une dame en plus, il bloque le roi sans le mettre en échec : pat, partie nulle."},
 {t:"Elo",c:"ECHECS",d:"Le classement chiffré des joueurs d'échecs : il monte quand on gagne, il baisse quand on perd.",x:"Un débutant tourne autour de 800, un bon joueur de club vers 1 800."},
 {t:"gambit",f:["gambits"],c:"ECHECS",d:"Une ouverture où l'on sacrifie un pion pour gagner du temps ou de l'activité.",x:"Le gambit dame : les Blancs offrent le pion c4."},
 {t:"tempo",f:["tempos"],c:"ECHECS DAMES",d:"Un temps de jeu : gagner un tempo, c'est atteindre son but avec un coup de moins que prévu.",x:"Développer une pièce en attaquant la dame adverse fait gagner un tempo."},
 {t:"rafle",f:["rafles"],c:"DAMES",d:"Une prise de plusieurs pièces adverses d'affilée, en un seul coup.",x:"Le pion saute trois pions d'un coup : c'est une rafle."},
 {t:"range",f:["ranges"],c:"POKER",d:"L'ensemble des mains qu'un joueur peut avoir dans une situation donnée.",x:"Une relance d'un joueur prudent en première position : sa range, ce sont surtout des grosses paires."},
 {t:"outs",c:"POKER",d:"Les cartes encore dans le paquet qui transformeraient ta main en main gagnante.",x:"Avec quatre cœurs, il reste 9 cœurs pour la couleur : 9 outs."},
 {t:"MDF",c:"POKER",d:"Minimum defense frequency : la part minimale de mains à défendre face à une mise, pour ne pas se faire exploiter par le bluff.",x:"Mise de la taille du pot : il faut défendre au moins la moitié de sa range."},
 {t:"c-bet",f:["continuation bet"],c:"POKER",d:"Continuation bet : miser au flop après avoir été le relanceur avant le flop.",x:"Il a relancé avant le flop, il mise un tiers du pot au flop."},
 {t:"3-bet",c:"POKER",d:"Une sur-relance : relancer quelqu'un qui a déjà relancé avant le flop.",x:"Ouverture à 3 blindes, il 3-bet à 9 blindes."},
 {t:"équité",c:"POKER",d:"La part du pot que ta main gagne en moyenne si l'on va jusqu'à la dernière carte.",x:"Un tirage couleur au flop a environ 35 % d'équité."},
 {t:"value bet",c:"POKER",d:"Miser avec une main forte pour être payé par des mains moins bonnes.",x:"Avec le brelan, il mise pour que la paire le suive."},
 /* ---------- YouTube ---------- */
 {t:"CTR",c:"YT",d:"Click-through rate : le pourcentage de personnes qui cliquent sur la vidéo après avoir vu sa miniature.",x:"1 000 impressions et 50 clics : CTR de 5 %."},
 {t:"taux de clic",c:"YT",d:"La part des gens qui cliquent après avoir vu la miniature (en anglais : CTR).",x:"50 clics pour 1 000 affichages : 5 % de taux de clic."},
 {t:"impressions",c:"YT",d:"Le nombre de fois où la miniature a été montrée à quelqu'un.",x:"La vidéo a eu 20 000 impressions et 1 000 vues."},
 {t:"rétention",c:"YT",d:"La part de la vidéo regardée en moyenne : elle montre où les spectateurs décrochent.",x:"50 % de rétention sur une vidéo de 10 minutes : 5 minutes regardées en moyenne."},
 {t:"RPM",c:"YT",d:"Revenu pour 1 000 vues, après la part de YouTube : ce que le créateur touche vraiment.",x:"RPM de 3 € : 100 000 vues rapportent environ 300 €."},
 {t:"CPM",c:"YT",d:"Le prix payé par les annonceurs pour 1 000 affichages de publicité.",x:"Les CPM grimpent en fin d'année, quand les marques dépensent plus."},
 {t:"packaging",c:"YT",d:"Le titre et la miniature d'une vidéo : ce qui donne envie de cliquer.",x:"Même vidéo, nouveau titre et nouvelle miniature : les vues doublent."},
 {t:"hook",f:["hooks"],c:"YT",d:"Les premières secondes de la vidéo, qui doivent accrocher pour qu'on reste.",x:"« Cette erreur m'a coûté 10 000 abonnés » dès la première phrase."},
 {t:"niche",c:"YT",d:"Le sujet précis et le public précis que vise une chaîne.",x:"Pas « la cuisine », mais « la cuisine rapide pour étudiants »."},
 /* ---------- humour ---------- */
 {t:"setup",c:"HUMOUR",d:"La mise en place d'une blague : la partie qui installe une attente chez le public.",x:"« Ma grand-mère fait du sport tous les jours... »"},
 {t:"callback",f:["callbacks"],c:"HUMOUR",d:"Le rappel d'une blague faite plus tôt, qui fait rire une seconde fois.",x:"Reparler du crossfit de l'ascenseur en fin de spectacle."},
 {t:"tag",f:["tags"],c:"HUMOUR",d:"Une chute bonus ajoutée juste après la première, sans nouveau setup.",x:"Après le rire, une phrase de plus qui relance."},
 /* ---------- style ---------- */
 {t:"chino",f:["chinos"],c:"STYLE",d:"Un pantalon en toile de coton, entre le jean et le pantalon de costume.",x:"Un chino beige avec une chemise en oxford."},
 {t:"oxford",c:"STYLE",d:"Selon le contexte : une chaussure de ville fermée et élégante, ou un coton de chemise légèrement texturé.",x:"Une chemise en oxford blanche se porte avec tout."},
 /* ---------- philosophie, developpement personnel ---------- */
 {t:"conatus",c:"SPINO",d:"L'effort de chaque chose pour persévérer dans son être, continuer d'exister et d'agir. Chez l'humain, c'est le désir.",x:"La plante qui pousse vers la lumière, l'élève qui s'acharne sur un exercice."},
 {t:"affect",f:["affects"],c:"SPINO",d:"Une variation de notre puissance d'agir : la joie l'augmente, la tristesse la diminue.",x:"Une bonne nouvelle te donne envie de tout faire : c'est un affect joyeux."},
 {t:"substance",c:"SPINO",d:"Ce qui existe en soi et par soi. Pour Spinoza, il n'y en a qu'une : Dieu, c'est-à-dire la Nature.",x:"Toi, l'océan et les étoiles êtes des manières d'être de la même substance."},
 {t:"attribut",f:["attributs"],c:"SPINO",d:"Une façon dont la substance s'exprime. Nous en connaissons deux : l'étendue (la matière) et la pensée.",x:"Ton corps relève de l'étendue, tes idées de la pensée."},
 {t:"nihilisme",c:"NIETZ",d:"La perte du sens : les valeurs suprêmes (Dieu, vérité, morale) se dévalorisent et plus rien ne semble valoir.",x:"« À quoi bon ? » est la petite phrase du nihilisme."},
 {t:"ressentiment",c:"NIETZ",d:"La rancune ruminée de celui qui se sent impuissant : elle le pousse à rabaisser ce qu'il ne peut atteindre.",x:"Mépriser les gens qui réussissent parce qu'on n'ose pas essayer."},
 {t:"ressentiment",c:"NON",d:"Une rancune qui s'accumule quand on dit oui à contrecœur, encore et encore.",x:"Accepter chaque week-end de garde, puis en vouloir à sa sœur sans le lui dire."},
 {t:"surhomme",c:"NIETZ",d:"L'idéal de Nietzsche : celui qui crée ses propres valeurs au lieu de suivre celles qu'on lui impose.",x:"Pas un super-héros, mais quelqu'un qui invente sa façon de vivre."},
 {t:"éternel retour",c:"NIETZ",d:"L'idée-test de Nietzsche : voudrais-tu revivre ta vie à l'identique, une infinité de fois ?",x:"Si la réponse est non, qu'est-ce que tu changes dès aujourd'hui ?"},
 {t:"volonté de puissance",c:"NIETZ",d:"La force de fond de tout vivant selon Nietzsche : croître et se dépasser, pas seulement survivre.",x:"L'arbre qui pousse au-delà de ce dont il a besoin pour vivre."},
 {t:"amor fati",c:"NIETZ",d:"« L'amour du destin » : aimer ce qui arrive, pas seulement le supporter.",x:"Voir un échec comme une pièce nécessaire de son histoire."},
 {t:"généalogie",c:"NIETZ",d:"Chez Nietzsche : chercher d'où viennent nos valeurs morales, et qui avait intérêt à les imposer.",x:"Se demander pourquoi l'humilité est devenue une vertu."},
 {t:"dionysiaque",c:"NIETZ",d:"Ce qui relève de Dionysos : l'ivresse, l'élan, la fusion, le chaos créateur.",x:"La foule qui danse comme un seul corps à un concert."},
 {t:"apollinien",c:"NIETZ",d:"Ce qui relève d'Apollon : la forme, la mesure, la clarté.",x:"Une sculpture grecque calme et parfaitement proportionnée."},
 {t:"dernier homme",f:["derniers hommes"],c:"NIETZ",d:"Chez Nietzsche, celui qui ne veut plus que son petit confort et ne prend plus aucun risque.",x:"« Nous avons inventé le bonheur », disent-ils, en clignant de l'œil."},
 {t:"assertivité",c:"NON",d:"S'affirmer en respectant l'autre : dire ce qu'on pense et ce qu'on veut, sans agresser ni se soumettre.",x:"« Je ne peux pas ce soir, mais samedi me va très bien. »"},
 {t:"CNV",c:"NON",d:"Communication non violente : décrire les faits, dire son sentiment, son besoin, puis faire une demande claire.",x:"« Quand tu arrives à 21 h, je m'inquiète. J'ai besoin d'être prévenu. Peux-tu m'écrire ? »"}
];
