/*UNIT*/
{id:215,c:"MMA",n:"Module 1",t:"Le MMA en vrai : règles, rounds, catégories et décisions",col:"--red",ic:"🏟️",guide:`
<h3>Ton premier soir au Dojo du Vieux-Port</h3>
<div class="gstory">Marseille, un mardi soir, 19 h. Le Dojo du Vieux-Port sent le caoutchouc et la sueur. Rachid Amrani, 44 ans, ancien combattant professionnel (18 victoires, 6 défaites), t'accueille : « Tu veux devenir l'analyste du club ? Alors avant de parler de coups, tu apprends les règles. Un combat se gagne aussi sur la feuille des juges. » Quatre combattants s'entraînent sur les tapis. Enzo, 24 ans, est un boxeur anglais qui passe au MMA. Lina, 27 ans, est une ancienne championne de France de lutte libre. Maëlle, 31 ans, est ceinture violette de jiu-jitsu brésilien. Tom, 19 ans, est débutant et fan de Conor McGregor. Dans six semaines, Enzo fait son premier combat professionnel.</div>
<h3>Ce qu'est le MMA</h3>
<p>Le <b>MMA</b> (<i>mixed martial arts</i>, arts martiaux mixtes) autorise la frappe debout (poings, pieds, genoux, coudes), le <b>clinch</b> (corps à corps debout), la <b>lutte</b> (amenées au sol) et le combat <b>au sol</b> (contrôle, frappes, soumissions). Ses ancêtres : le <b>vale tudo</b> brésilien (« tout est permis ») et l'<b>UFC 1</b>, le 12 novembre 1993 à Denver, gagné par <b>Royce Gracie</b>, un spécialiste du jiu-jitsu brésilien bien plus léger que ses adversaires. Depuis, les <b>règles unifiées</b> (nées au New Jersey en 2000) encadrent le sport.</p>
<div class="gsvg-wrap"><svg class='gsvg' viewBox='0 0 200 140' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='20' y='40' width='50' height='40' rx='8' fill='var(--blue)'/><text x='45' y='64' font-size='10' fill='var(--bg)' text-anchor='middle' font-weight='700'>Distance</text><rect x='75' y='40' width='50' height='40' rx='8' fill='var(--gold)'/><text x='100' y='64' font-size='10' fill='var(--bg)' text-anchor='middle' font-weight='700'>Clinch</text><rect x='130' y='40' width='50' height='40' rx='8' fill='var(--red)'/><text x='155' y='64' font-size='10' fill='var(--bg)' text-anchor='middle' font-weight='700'>Sol</text><path d='M70 60 L75 60 M125 60 L130 60' stroke='var(--txt)' stroke-width='2'/><path d='M45 90 Q100 130 155 90' fill='none' stroke='var(--dim)' stroke-width='2' stroke-dasharray='4 3'/><text x='100' y='126' font-size='9' fill='var(--dim)' text-anchor='middle' font-weight='600'>amenée au sol directe</text><path d='M155 30 Q100 0 45 30' fill='none' stroke='var(--green)' stroke-width='2'/><text x='100' y='18' font-size='9' fill='var(--green)' text-anchor='middle' font-weight='600'>se relever</text></svg></div>
<h3>Le format</h3>
<table><tr><th>Élément</th><th>Règle (UFC et règles unifiées)</th></tr>
<tr><td>Rounds</td><td>Un combat dure <b>3 rounds de 5 minutes</b>. Les combats de titre et les têtes d'affiche durent <b>5 rounds</b>. Les combattants ont 1 minute de repos entre deux rounds.</td></tr>
<tr><td>Gants</td><td>Environ <b>4 onces</b> (113 g), doigts libres pour saisir</td></tr>
<tr><td>Pointage</td><td><b>Système des 10 points</b> : le vainqueur du round reçoit 10, le perdant 9 (8 ou moins si domination nette)</td></tr>
<tr><td>Juges</td><td>3 juges autour de la cage</td></tr></table>
<h3>Comment un combat se termine</h3>
<table><tr><th>Issue</th><th>Définition</th></tr>
<tr><td><b>KO</b></td><td>Le combattant est inconscient ou incapable de continuer après un coup</td></tr>
<tr><td><b>TKO</b> (KO technique)</td><td>L'arbitre arrête le combat (le combattant ne se défend plus intelligemment), ou le médecin, ou le coin qui jette l'éponge</td></tr>
<tr><td><b>Soumission</b></td><td>Le combattant abandonne en tapant (au moins deux fois) ou en le disant, sur une clé ou un étranglement</td></tr>
<tr><td><b>Décision</b></td><td><b>Unanime</b> (3 juges pour le même), <b>partagée</b> (2 contre 1), <b>majoritaire</b> (2 pour, 1 égalité)</td></tr>
<tr><td>Match nul, disqualification, no contest</td><td>Il y a match nul quand les cartes des juges sont à égalité. Il y a disqualification après une faute grave. Le combat est déclaré sans décision (no contest) après une faute involontaire ou un contrôle antidopage positif.</td></tr></table>
<div class="gmnemo"><b>« K.T.S.D. : KO, TKO, Soumission, Décision. »</b> Les quatre façons normales de gagner. Et pour les décisions : <b>« Unanime 3-0, Partagée 2-1, Majoritaire 2-0-1. »</b></div>
<h3>Les fautes principales</h3>
<ul><li>Coups de tête, doigts dans les yeux, morsures, tirer les cheveux</li><li>Frapper les parties génitales, la gorge, l'arrière de la tête ou la colonne vertébrale</li><li>Tordre les petites articulations (doigts, orteils)</li><li>Coup de pied ou coup de genou à la tête d'un adversaire <b>au sol</b></li><li>S'agripper à la cage ou au short de l'adversaire</li></ul>
<div class="gtrap">Règle récente, souvent mal connue : depuis le <b>1er novembre 2024</b>, les règles unifiées de l'ABC autorisent le coude « <b>12-6</b> » (vertical, du haut vers le bas), longtemps interdit, là où les commissions l'ont adopté (l'UFC l'applique depuis le 2 novembre 2024). Et un combattant est désormais considéré <b>au sol</b> dès qu'une partie de son corps <b>autre que les mains ou les pieds</b> touche le tapis : poser une main ne suffit plus pour se protéger d'un coup de genou.</div>
<h3>Les catégories de poids (hommes, UFC)</h3>
<table><tr><th>Catégorie</th><th>Limite</th></tr>
<tr><td>Mouche</td><td>56,7 kg (125 lb)</td></tr><tr><td>Coq</td><td>61,2 kg (135 lb)</td></tr><tr><td>Plume</td><td>65,8 kg (145 lb)</td></tr><tr><td>Léger</td><td>70,3 kg (155 lb)</td></tr><tr><td>Mi-moyen</td><td>77,1 kg (170 lb)</td></tr><tr><td>Moyen</td><td>83,9 kg (185 lb)</td></tr><tr><td>Mi-lourd</td><td>93 kg (205 lb)</td></tr><tr><td>Lourd</td><td>120,2 kg (265 lb)</td></tr></table>
<p>Chez les femmes, la plus légère est la catégorie <b>paille</b> (52,2 kg, 115 lb). La pesée a lieu la veille du combat.</p>
<h3>Et en France ?</h3>
<p>Le MMA est <b>légal en France depuis janvier 2020</b>. Le ministère des Sports en a confié la délégation à la Fédération française de boxe, qui a créé une structure dédiée, la <b>FMMAF</b>. Celle-ci devient une fédération autonome à partir de <b>septembre 2026</b>, et la délégation court jusqu'au 31 décembre 2026. On compte environ 10 000 licenciés et 300 clubs. Le premier événement UFC en France a eu lieu à Paris le <b>3 septembre 2022</b>, avec Ciryl Gane en tête d'affiche.</p>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Décrire le format d'un combat et le système des 10 points</li><li>Nommer les issues possibles et les types de décision</li><li>Citer les fautes principales et la règle récente sur les coudes</li><li>Situer un combattant dans sa catégorie de poids</li></ul>`},
/*EXOS*/
{i:"m215_01",u:215,t:"slider",d:.2,nw:"Le format d'un combat",q:"Combien de minutes dure un round de MMA à l'UFC ?",min:1,max:10,step:1,a:5,tol:0,pre:"",un:" min",w:"5 minutes, avec 1 minute de repos. 3 rounds en général, 5 pour un titre ou une tête d'affiche."},
{i:"m215_02",u:215,t:"story",d:.2,q:"Tom demande combien de rounds fera Enzo pour son premier combat pro, qui n'est ni un titre ni une tête d'affiche.",sc:[{who:"Tom",txt:"Il va faire cinq rounds comme McGregor ?"}],o:["« Trois rounds de cinq minutes : cinq rounds, c'est pour les titres et les têtes d'affiche. »","« Cinq rounds de trois minutes, c'est la règle pour tous les combats. »","« Douze rounds de trois minutes, exactement comme en boxe anglaise. »","« Il n'y a pas de rounds, on combat jusqu'à ce que l'un abandonne. »"],a:0,w:"3 × 5 minutes pour un combat classique, 5 × 5 pour un titre ou une tête d'affiche."},
{i:"m215_03",u:215,t:"match",d:.25,q:"Associe chaque issue à sa définition.",p:[["KO","Combattant inconscient ou incapable de continuer après un coup"],["TKO","Arrêt par l'arbitre, le médecin ou le coin"],["Soumission","Abandon en tapant sur une clé ou un étranglement"],["Décision","Les juges départagent à la fin"]],w:"K.T.S.D. : les quatre façons normales de gagner."},
{i:"m215_04",u:215,t:"fill",d:.25,q:"Le premier UFC a eu lieu en 1993 et a été gagné par Royce ___.",o:["Gracie","McGregor","Silva","Rousey"],a:0,w:"Royce Gracie, spécialiste du jiu-jitsu brésilien, plus léger que ses adversaires. Le sol a surpris tout le monde. L'UFC 1 est né de l'esprit du vale tudo brésilien."},
{i:"m215_05",u:215,t:"tf",d:.25,q:"Depuis novembre 2024, le coude « 12-6 » est autorisé par les règles unifiées de l'ABC.",a:true,w:"Là où les commissions l'ont adopté. L'UFC l'applique depuis le 2 novembre 2024."},
{i:"m215_06",u:215,t:"sort",d:.3,q:"Classe chaque geste : autorisé ou faute ?",bins:["Autorisé","Faute"],it:[["Coup de pied au corps debout",0],["Doigts dans les yeux",1],["Étranglement arrière",0],["Tirer les cheveux",1],["Coup de genou à la tête d'un adversaire au sol",1],["Coup de coude au visage debout",0]],w:"Les fautes visent les zones et gestes dangereux sans intérêt sportif, et les frappes à la tête d'un adversaire au sol avec pied ou genou."},
{i:"m215_07",u:215,t:"mcq",d:.3,q:"Quelle décision correspond à deux juges pour Enzo et un juge pour son adversaire ?",o:["Décision partagée","Décision unanime","Décision majoritaire","Match nul"],a:0,w:"Unanime 3-0, partagée 2-1, majoritaire 2-0-1 (deux pour, un juge à égalité)."},
{i:"m215_08",u:215,t:"story",d:.3,q:"Le coin de l'adversaire d'Enzo jette l'éponge au 2e round. Comment le résultat s'appelle-t-il ?",sc:[{who:"Tom",txt:"C'est un KO, du coup ?"}],o:["« Un TKO : arrêt par le coin, sans que le combattant soit inconscient. »","« Un KO, puisque le combat s'arrête avant la fin du temps prévu. »","« Une soumission, puisque c'est son équipe qui a abandonné. »","« Un no contest, puisque le combattant n'a pas fini le combat. »"],a:0,w:"TKO : arrêt par l'arbitre, le médecin ou le coin. Le KO suppose un combattant inconscient ou hors d'état à la suite d'un coup."},
{i:"m215_09",u:215,t:"num",d:.35,q:"Round 1 : 10-9 pour Enzo. Round 2 : 9-10. Round 3 : 10-8 pour Enzo. Quel est le total d'Enzo sur cette carte ?",a:29,tol:0,un:" points",h:"10 + 9 + 10",w:"29-27 : Enzo gagne sur cette carte. Un 10-8 récompense une domination nette. Selon le système des 10 points, chaque round se note séparément."},
{i:"m215_10",u:215,t:"multi",d:.35,q:"Quelles zones est-il interdit de frapper ?",o:["L'arrière de la tête","La colonne vertébrale","La gorge","Les parties génitales","Le foie"],a:[0,1,2,3],w:"Le foie est une cible légale, et redoutable (module 2)."},
{i:"m215_11",u:215,t:"slider",d:.35,q:"Quelle est la limite de la catégorie des poids légers (en kg) ?",min:50,max:125,step:.1,a:70.3,tol:.3,pre:"",un:" kg",w:"70,3 kg (155 livres). La catégorie de Benoît Saint-Denis et de Khabib Nurmagomedov."},
{i:"m215_12",u:215,t:"fill",d:.4,q:"Le système de pointage du MMA s'appelle le système des ___ points.",o:["10","20","5","100"],a:0,w:"10-point must system : 10 au vainqueur du round, 9 ou moins au perdant."},
{i:"m215_13",u:215,t:"tf",d:.4,q:"En MMA, un combattant qui pose seulement une main au tapis est considéré « au sol ».",a:false,w:"Depuis la réforme de 2024, il faut qu'une partie du corps autre que les mains ou les pieds touche le tapis. Une main posée ne protège plus d'un coup de genou."},
{i:"m215_14",u:215,t:"order",d:.45,q:"Remets les catégories masculines dans l'ordre, de la plus légère à la plus lourde.",it:["Mouche","Coq","Plume","Léger","Mi-moyen","Moyen","Mi-lourd","Lourd"],w:"56,7 ; 61,2 ; 65,8 ; 70,3 ; 77,1 ; 83,9 ; 93 ; 120,2 kg."},
{i:"m215_15",u:215,t:"story",d:.45,q:"Tom croit que le MMA est « illégal en France, comme avant ». Que lui réponds-tu ?",sc:[{who:"Tom",txt:"On n'a pas le droit de faire des combats en France, non ?"}],o:["« C'est légal depuis janvier 2020, avec une fédération dédiée. »","« C'est toujours interdit, les combats pros se font tous à l'étranger. »","« C'est légal seulement pour les amateurs, jamais pour les pros. »","« C'est légal uniquement dans les salles privées, sans public. »"],a:0,w:"Légal depuis janvier 2020, délégation à la FFBoxe, puis FMMAF autonome à partir de septembre 2026."},
{i:"m215_16",u:215,t:"match",d:.45,q:"Associe chaque catégorie à sa limite.",p:[["Mouche","56,7 kg"],["Mi-moyen","77,1 kg"],["Mi-lourd","93 kg"],["Lourd","120,2 kg"]],w:"Connaître les catégories permet de lire une affiche et de comprendre les enjeux de la pesée."},
{i:"m215_17",u:215,t:"mcq",d:.5,q:"Combien pèsent environ les gants de MMA ?",o:["4 onces","10 onces","16 onces","Pas de gants"],a:0,w:"Environ 4 onces (113 g), doigts libres pour saisir. En boxe anglaise pro, 8 à 10 onces : les coups de MMA coupent plus et sont moins amortis."},
{i:"m215_18",u:215,t:"sort",d:.5,q:"Classe chaque résultat : victoire avant la limite ou aux points ?",bins:["Avant la limite","Aux points"],it:[["KO au 1er round",0],["Décision unanime",1],["Étranglement au 3e round",0],["Décision partagée",1],["Arrêt du médecin",0]],w:"KO, TKO et soumission finissent le combat ; la décision vient après le dernier round."},
{i:"m215_19",u:215,t:"story",d:.55,q:"Enzo est à 71 kg la veille de la pesée, en poids léger. Rachid s'inquiète. Pourquoi ?",sc:[{who:"Enzo",txt:"Il me reste juste 700 grammes, c'est rien."}],o:["« Il dépasse la limite de 70,3 kg : pénalité ou combat annulé. »","« Aucun souci, la limite des légers est à 77 kg, il a encore de la marge. »","« Il doit au contraire prendre du poids pour être au minimum de la catégorie. »","« La pesée n'a aucune importance, seul compte le poids le jour du combat. »"],a:0,w:"70,3 kg pour les légers. Un combattant hors poids perd souvent une partie de sa bourse, et le combat peut être maintenu à un poids intermédiaire ou annulé."},
{i:"m215_20",u:215,t:"tf",d:.55,q:"Un combattant peut abandonner en tapant sur l'adversaire ou le tapis, ou en le disant.",a:true,w:"C'est la soumission. Le taper se fait au moins deux fois pour être clair ; l'arbitre arrête aussitôt."},
{i:"m215_21",u:215,t:"fill",d:.6,q:"Le vale tudo, ancêtre brésilien du MMA, signifie « tout est ___ ».",o:["permis","interdit","perdu","gagné"],a:0,w:"Vale tudo : tout est permis. Le MMA moderne l'a encadré par les règles unifiées."},
{i:"m215_22",u:215,t:"num",d:.6,q:"Carte d'un juge : 10-9, 10-9, 9-10 pour Enzo. Un autre juge : 9-10, 9-10, 10-9. Le troisième : 10-9, 10-9, 10-9. Combien de juges donnent Enzo vainqueur ?",a:2,tol:0,un:" juges",h:"Compte les cartes où Enzo a plus de points",w:"Juge 1 : 29-28 Enzo ; juge 2 : 28-29 ; juge 3 : 30-27. Deux juges sur trois : décision partagée. Chaque juge utilise le système des 10 points pour chaque round."},
{i:"m215_23",u:215,t:"multi",d:.65,q:"Quelles phases trouve-t-on dans un combat de MMA ?",o:["La distance, où l'on frappe","Le clinch, corps à corps debout","Le sol","Les transitions entre ces phases","Une pause obligatoire à mi-round"],a:[0,1,2,3],w:"Distance, clinch, sol, et les passages de l'une à l'autre : c'est ce qui rend le MMA unique."},
{i:"m215_24",u:215,t:"story",d:.65,q:"Tom regarde un combat et s'indigne d'un coude vertical au sol : « C'est interdit ! » Qu'en dis-tu ?",sc:[{who:"Tom",txt:"Jon Jones a été disqualifié pour ça, je le sais !"}],o:["« C'était interdit à l'époque ; depuis fin 2024, les règles l'autorisent. »","« Tu as raison, le coude vertical reste interdit dans tous les pays du monde. »","« Il est autorisé depuis toujours, Jon Jones n'a jamais été disqualifié pour ça. »","« Il est interdit debout mais autorisé uniquement contre la cage. »"],a:0,w:"Jon Jones a perdu par disqualification en 2009 pour des coudes 12-6. La règle a été supprimée par l'ABC, effective le 1er novembre 2024."},
{i:"m215_25",u:215,t:"slider",d:.7,q:"Quelle est la limite de la catégorie paille chez les femmes (en kg) ?",min:40,max:70,step:.1,a:52.2,tol:.3,pre:"",un:" kg",w:"52,2 kg (115 livres), la catégorie la plus légère de l'UFC."},
{i:"m215_26",u:215,t:"tiles",d:.7,q:"Reconstitue le moyen mnémotechnique des victoires.",a:["KO","TKO","Soumission","Décision"],dd:["Pause","Forfait"],w:"K.T.S.D. Le forfait et la disqualification existent, mais ne sont pas des façons « normales » de gagner."},
{i:"m215_27",u:215,t:"mcq",d:.75,q:"En quelle année et dans quelle ville a eu lieu le premier événement UFC en France ?",o:["En 2022, à l'Accor Arena de Paris","2019, à Marseille","2016, à Lyon","2024, à Nice"],a:0,w:"UFC Paris, le 3 septembre 2022, avec Ciryl Gane en tête d'affiche."},
{i:"m215_28",u:215,t:"story",d:.75,q:"L'adversaire d'Enzo reçoit un doigt dans l'œil involontaire au 1er round et ne peut pas continuer. Quel résultat ?",sc:[{who:"Tom",txt:"Enzo gagne, du coup ?"}],o:["« Non : faute involontaire tôt dans le combat, donc c'est un no contest. »","« Oui, Enzo gagne par KO puisque l'adversaire ne peut plus continuer. »","« Non, Enzo perd automatiquement par disqualification immédiate. »","« Oui, Enzo gagne par soumission, car l'autre abandonne le combat. »"],a:0,w:"Une faute involontaire qui empêche de continuer avant la fin du temps prévu par les règles donne un no contest ; plus tard, on va aux cartes (décision technique)."},
{i:"m215_29",u:215,t:"tf",d:.8,q:"Un round 10-8 récompense un round simplement gagné, même de peu.",a:false,w:"Faux : un round gagné de peu, c'est 10-9. Le 10-8 demande une domination nette : dégâts importants, domination longue, ou impact qui met l'adversaire en danger."},
{i:"m215_30",u:215,t:"fill",d:.8,q:"Environ ___ personnes sont licenciées en MMA en France, dans près de 300 clubs.",o:["10 000","1 000","100 000","1 million"],a:0,w:"Environ 10 000 licenciés et 300 clubs, un sport jeune et en forte croissance."},
{i:"m215_31",u:215,t:"match",d:.85,q:"Associe chaque type de décision à la répartition des juges.",p:[["Unanime","3 juges pour le même"],["Partagée","2 juges contre 1"],["Majoritaire","2 juges pour, 1 à égalité"],["Match nul","Égalité globale"]],w:"Unanime 3-0, partagée 2-1, majoritaire 2-0-1."},
{i:"m215_32",u:215,t:"story",d:.9,q:"Synthèse : Rachid te demande de résumer à Tom ce qu'un analyste doit savoir des règles avant un combat.",sc:[{who:"Rachid",txt:"En une phrase, pour le petit."}],o:["« Format, fautes, catégorie, pointage : on gagne aussi sur la carte des juges. »","« Seul le KO compte, les règles et les juges n'ont jamais d'importance. »","« Il suffit de connaître les coups autorisés, le reste se règle sur place. »","« Les règles changent à chaque combat, inutile de les apprendre par cœur. »"],a:0,w:"K.T.S.D., 10 points, fautes, catégories : la base de toute analyse sérieuse."}
