/*UNIT*/
{id:221,c:"MMA",n:"Module 7",t:"La lutte : amener au sol quand on veut",col:"--red",ic:"🤸",guide:`
<h3>Lina montre ses jambes</h3>
<div class="gstory">Lundi matin, séance de lutte. Lina, ancienne championne de France de lutte libre, demande à Tom de lui lancer un direct. Tom frappe ; Lina a déjà disparu sous son bras, un genou au sol, les deux bras autour de ses cuisses. Une seconde plus tard, Tom est sur le dos et Lina rit : « Tu m'as donné ton poids en frappant. Merci. » Rachid à tout le monde : « Retenez ça. En MMA, celui qui décide où se passe le combat, debout ou au sol, a déjà gagné la moitié du combat. »</div>
<h3>Les lutteurs du MMA</h3>
<table><tr><th>Style</th><th>Particularité</th><th>Apport au MMA</th></tr>
<tr><td><b>Lutte libre</b></td><td>Saisies du corps entier, jambes comprises</td><td>Amenées aux jambes, contrôle</td></tr>
<tr><td><b>Lutte gréco-romaine</b></td><td>Saisies du haut du corps seulement</td><td>Clinch, projections, travail contre la cage</td></tr>
<tr><td>Lutte universitaire américaine</td><td>Très axée sur le contrôle au sol et le relevé</td><td>Beaucoup de champions de l'UFC viennent de là</td></tr>
<tr><td><b>Sambo</b> (Russie, Daghestan)</td><td>Lutte avec veste, projections et clés de jambe</td><td>Pression écrasante au sol (Khabib Nurmagomedov, Islam Makhachev)</td></tr>
<tr><td><b>Judo</b></td><td>Projections avec veste, balayages</td><td>Projections en clinch, déséquilibres</td></tr></table>
<h3>Les trois temps d'une amenée</h3>
<ol><li><b>Changer de niveau</b> : abaisser les hanches d'un coup, dos droit, tête haute.</li>
<li><b>Pénétrer</b> : un grand pas en avant, le genou avant vient au sol entre les pieds de l'adversaire.</li>
<li><b>Finir</b> : pousser en tournant (« passer le coin »), soulever ou faucher, pour l'envoyer au sol et arriver par-dessus.</li></ol>
<div class="gmnemo"><b>« Baisse, Plonge, Termine. »</b> Changer de niveau, pénétrer, finir. Et la règle d'or du timing : <b>« Plonge quand il frappe »</b> : un adversaire qui lance un coup a son poids engagé et ses mains loin de ses jambes.</div>
<h3>Les amenées à connaître</h3>
<table><tr><th>Amenée</th><th>Principe</th></tr>
<tr><td><b>Double jambe</b></td><td>Les deux bras autour des cuisses, épaule dans les hanches, on pousse et on tourne</td></tr>
<tr><td><b>Simple jambe</b></td><td>On saisit une seule jambe, on la soulève ou on fauche l'autre</td></tr>
<tr><td><b>Ceinture</b> (body lock)</td><td>Mains jointes autour de la taille, on colle et on fait tomber, souvent avec un crochet de jambe</td></tr>
<tr><td><b>Crochet de jambe</b> (trip)</td><td>Notre jambe bloque ou crochète la sienne pendant qu'on le pousse</td></tr>
<tr><td>Balayage (judo)</td><td>On chasse son pied au moment où il transfère son poids</td></tr>
<tr><td>Projection de hanche</td><td>On le charge sur la hanche et on le fait basculer</td></tr></table>
<h3>Préparer et enchaîner</h3>
<ul><li><b>Frapper pour plonger</b> : un 1-2 fait monter la garde, les jambes sont libres.</li>
<li><b>Plonger en réaction</b> : sous un coup de l'adversaire. Georges St-Pierre en a fait une signature.</li>
<li><b>Contre la cage</b> : l'adversaire ne peut pas reculer (module 6).</li>
<li><b>Lutte en chaîne</b> : si la simple jambe est défendue, on passe à la double, puis au crochet de jambe. Une amenée ratée n'est que le début de la suivante.</li></ul>
<h3>Deux combats pour comprendre</h3>
<ul><li><b>Khabib Nurmagomedov contre Conor McGregor</b> (UFC 229, 6 octobre 2018) : le lutteur amène le frappeur au sol, l'use par sa pression, et gagne par soumission (clé de cou) au 4e round.</li>
<li><b>Francis Ngannou contre Ciryl Gane</b> (UFC 270, 22 janvier 2022) : Ngannou, réputé pour ses KO, surprend Gane en l'amenant plusieurs fois au sol dans les derniers rounds et gagne aux points, malgré une blessure au genou. Même un frappeur peut gagner par la lutte.</li></ul>
<div class="gtrap">Idée reçue : « un lutteur, ça ne frappe pas ». Dans le MMA moderne, les meilleurs lutteurs mélangent frappe et amenée : c'est la <b>menace</b> de la lutte qui ouvre les coups, et inversement. Autre erreur fréquente : plonger de trop loin, sans préparation. Une amenée lancée hors de distance se fait « sprawler » (module 8) et peut finir en guillotine.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Distinguer les styles de lutte et leur apport au MMA</li><li>Décomposer une amenée en trois temps</li><li>Reconnaître double jambe, simple jambe, ceinture, crochet, balayage</li><li>Expliquer quand et comment préparer une amenée</li></ul>`},
/*EXOS*/
{i:"m221_01",u:221,t:"order",d:.2,nw:"Les trois temps d'une amenée",q:"Remets dans l'ordre les trois temps d'une amenée.",it:["Changer de niveau","Pénétrer","Finir"],w:"Baisse, plonge, termine. Le changement de niveau se fait d'un coup, dos droit."},
{i:"m221_02",u:221,t:"story",d:.2,q:"Tom lance un direct et se retrouve sur le dos. Qu'explique Lina ?",sc:[{who:"Tom",txt:"Comment tu as fait, j'étais en train de frapper !"}],o:["« En frappant, tu as engagé ton poids et éloigné tes mains de tes jambes. »","« Tu as glissé sur le tapis, ça n'a rien à voir avec ton coup de poing. »","« J'ai été plus rapide que toi, c'est uniquement une question de vitesse. »","« Tu as frappé trop doucement, un coup plus fort m'aurait arrêtée net. »"],a:0,w:"Plonge quand il frappe : poids engagé, mains loin des jambes. C'est l'amenée en réaction."},
{i:"m221_03",u:221,t:"match",d:.25,q:"Associe chaque style à sa particularité.",p:[["Lutte libre","Saisies des jambes autorisées"],["Lutte gréco-romaine","Haut du corps seulement"],["Sambo","Veste, projections, clés de jambe"],["Judo","Projections et balayages avec veste"]],w:"Chaque style apporte une arme différente au MMA."},
{i:"m221_04",u:221,t:"fill",d:.25,q:"Abaisser brusquement les hanches avant de plonger s'appelle changer de ___.",o:["niveau","garde","rythme","main"],a:0,w:"Le changement de niveau : dos droit, tête haute, hanches basses. C'est le premier temps."},
{i:"m221_05",u:221,t:"tf",d:.25,q:"La lutte gréco-romaine autorise les saisies aux jambes.",a:false,w:"Seulement le haut du corps. C'est la lutte libre qui autorise les jambes."},
{i:"m221_06",u:221,t:"mcq",d:.3,q:"Quel combat illustre un frappeur qui gagne grâce à la lutte ?",o:["Ngannou contre Gane, UFC 270","Holm contre Rousey, UFC 193","McGregor contre Aldo, UFC 194","Poirier contre McGregor, UFC 257"],a:0,w:"Ngannou, réputé pour ses KO, a amené Gane au sol plusieurs fois pour gagner aux points en 2022."},
{i:"m221_07",u:221,t:"story",d:.3,q:"Tom plonge sur les jambes de Lina depuis très loin, sans rien préparer. Il se fait écraser. Pourquoi ?",sc:[{who:"Tom",txt:"J'ai plongé super vite pourtant."}],o:["« Trop loin et sans préparation : elle l'a vu venir et a sprawlé. »","« Tu n'as pas plongé assez vite, il faut encore gagner en vitesse. »","« Tu aurais dû fermer les yeux pour mieux sentir ses jambes. »","« Tu aurais dû sauter à pieds joints au lieu de plonger au sol. »"],a:0,w:"Une amenée se prépare (coups, feintes, cage) et se lance à bonne distance. Sinon, sprawl et parfois guillotine."},
{i:"m221_08",u:221,t:"sort",d:.3,q:"Classe chaque amenée : saisie des jambes ou saisie du haut du corps ?",bins:["Jambes","Haut du corps"],it:[["Double jambe",0],["Ceinture",1],["Simple jambe",0],["Projection de hanche",1],["High crotch (jambe et hanche)",0]],w:"Les amenées aux jambes viennent de la lutte libre ; celles par le haut, de la gréco et du judo."},
{i:"m221_09",u:221,t:"tiles",d:.35,q:"Reconstitue les trois temps d'une amenée.",a:["baisse","plonge","termine"],dd:["frappe","recule","attends"],w:"Changer de niveau, pénétrer, finir. Et on plonge quand il frappe : son poids est engagé."},
{i:"m221_10",u:221,t:"multi",d:.35,q:"Comment préparer une amenée ?",o:["Frapper pour faire monter la garde","Plonger sous un coup adverse","Coincer l'adversaire contre la cage","Feinter une frappe","Plonger de très loin sans rien préparer"],a:[0,1,2,3],w:"Une amenée préparée passe ; une amenée de loin se fait sprawler."},
{i:"m221_11",u:221,t:"story",d:.35,q:"Tom croit que Khabib a battu McGregor « juste parce qu'il était plus fort physiquement ». Que lui réponds-tu ?",sc:[{who:"Tom",txt:"C'est juste un costaud, non ?"}],o:["« Il a imposé la lutte : amené, usé par la pression, soumis au 4e. »","« Il a gagné par KO au premier round d'un seul coup de poing. »","« McGregor a abandonné avant le combat à cause d'une blessure. »","« Il a gagné aux points par décision partagée, de justesse. »"],a:0,w:"UFC 229, 2018 : amenées, contrôle, pression, puis clé de cou au 4e round. Un plan de lutte parfait."},
{i:"m221_12",u:221,t:"fill",d:.4,q:"Dans le deuxième temps de l'amenée, le genou avant vient au sol entre les ___ de l'adversaire.",o:["pieds","bras","mains","épaules"],a:0,w:"La pénétration : un grand pas, genou au sol entre ses pieds, tête haute."},
{i:"m221_13",u:221,t:"tf",d:.4,q:"Dans la lutte en chaîne, une amenée ratée sert de point de départ à la suivante.",a:true,w:"Simple jambe défendue ? Double jambe. Défendue ? Crochet de jambe. On ne s'arrête pas."},
{i:"m221_14",u:221,t:"match",d:.45,q:"Associe chaque amenée à son principe.",p:[["Double jambe","Deux bras autour des cuisses, pousser et tourner"],["Simple jambe","Une jambe saisie, soulevée"],["Ceinture","Mains jointes autour de la taille"],["Balayage","Chasser le pied au transfert de poids"]],w:"Six amenées de base, à reconnaître en vidéo."},
{i:"m221_15",u:221,t:"story",d:.45,q:"Enzo, boxeur, demande pourquoi il doit apprendre la lutte offensive.",sc:[{who:"Enzo",txt:"Moi, je veux juste défendre, pas amener."}],o:["« La menace de ta lutte fera monter sa garde et ouvrira tes coups. »","« Tu n'en as pas besoin, un boxeur ne doit jamais toucher les jambes. »","« Seulement pour faire joli devant les juges, sans utilité réelle. »","« Parce que les règles imposent au moins une amenée par round. »"],a:0,w:"La menace de la lutte ouvre la frappe, et inversement : c'est le cœur du MMA moderne."},
{i:"m221_16",u:221,t:"mcq",d:.45,q:"Quel combattant a fait de l'amenée en réaction sous un coup sa signature ?",o:["Georges St-Pierre","Conor McGregor","Holly Holm","Anderson Silva, le Brésilien"],a:0,w:"GSP plongeait au moment où l'adversaire lançait un coup : poids engagé, jambes offertes."},
{i:"m221_17",u:221,t:"sort",d:.5,q:"Classe chaque moment : bon ou mauvais pour plonger ?",bins:["Bon moment","Mauvais moment"],it:[["Quand il lance un direct",0],["Quand il est dos à la cage",0],["Quand il est à quatre mètres, garde basse et hanches basses",1],["Après un 1-2 qui lui fait monter la garde",0],["Quand il attend, hanches basses, prêt à sprawler",1]],w:"On plonge sur un adversaire occupé ou coincé, pas sur un adversaire qui attend."},
{i:"m221_18",u:221,t:"fill",d:.5,q:"Pousser en tournant pour finir une double jambe s'appelle « passer le ___ ».",o:["coin","relais","mur","cap"],a:0,w:"On ne pousse pas droit : on tourne pour déséquilibrer et arriver par-dessus."},
{i:"m221_19",u:221,t:"story",d:.55,q:"Rappel du module 6 : Lina a Viktor dos à la cage avec une ceinture. Quelle amenée conseilles-tu ?",sc:[{who:"Lina",txt:"J'ai les mains jointes derrière lui, il est collé au grillage."}],o:["« Un crochet de jambe en le poussant : il ne peut pas reculer. »","« Le lâcher pour reculer au centre et recommencer à distance. »","« Un coup de pied haut, puisqu'il est collé et ne bougera pas. »","« Rester là sans rien faire jusqu'à ce que l'arbitre sépare. »"],a:0,w:"Ceinture plus crochet de jambe contre la cage : un classique. La cage bloque le recul."},
{i:"m221_20",u:221,t:"tf",d:.55,q:"Le sambo est une lutte avec veste, venue de Russie, qui inclut projections et clés de jambe.",a:true,w:"Khabib Nurmagomedov et Islam Makhachev, tous deux daghestanais, en sont issus."},
{i:"m221_21",u:221,t:"multi",d:.6,q:"Qu'est-ce qu'un bon changement de niveau ?",o:["Hanches basses d'un coup","Dos droit","Tête haute","Regard sur l'adversaire","Tête baissée vers le sol"],a:[0,1,2,3],w:"Tête baissée, on perd la posture et on s'expose à la guillotine."},
{i:"m221_22",u:221,t:"mcq",d:.6,q:"Pourquoi la tête doit-elle rester haute pendant le plongeon ?",o:["Pour la posture, et éviter la guillotine","Pour voir le public dans les gradins","Pour impressionner les juges de la cage","Parce que c'est la règle officielle de l'UFC"],a:0,w:"Tête basse : dos rond, perte de puissance et cou offert à la guillotine."},
{i:"m221_23",u:221,t:"story",d:.65,q:"Rappel du module 5 : Enzo attrape le middle kick de Viktor. Que peut-il faire ensuite ?",sc:[{who:"Enzo",txt:"J'ai sa jambe dans les bras, et maintenant ?"}],o:["« Le déséquilibrer en fauchant sa jambe d'appui : une amenée. »","« La lâcher tout de suite, garder une jambe est interdit en MMA. »","« La tenir sans bouger jusqu'à la fin du round pour le fatiguer. »","« Frapper sa jambe avec les coudes, c'est le seul coup autorisé. »"],a:0,w:"Un coup de pied attrapé devient une amenée : on fauche l'appui ou on le pousse en arrière."},
{i:"m221_24",u:221,t:"tiles",d:.65,q:"Reconstitue la règle du timing.",a:["plonge","quand","il","frappe"],dd:["recule","attends","dors"],w:"Un adversaire qui frappe a son poids engagé et ses mains loin de ses jambes."},
{i:"m221_25",u:221,t:"match",d:.7,q:"Associe chaque combattant à son style de lutte d'origine.",p:[["Khabib Nurmagomedov","Sambo et lutte du Daghestan"],["Lina, au dojo","Lutte libre"],["Un spécialiste des projections en veste","Judo"],["Un spécialiste du clinch sans jambes","Lutte gréco-romaine"]],w:"Lire le style d'origine d'un adversaire permet d'anticiper son plan."},
{i:"m221_26",u:221,t:"fill",d:.7,q:"Une amenée lancée hors de distance se fait « ___ » par l'adversaire.",o:["sprawler","checker","clincher","teeper"],a:0,w:"Le sprawl : hanches lourdes, jambes projetées en arrière. C'est le sujet du module 8."},
{i:"m221_27",u:221,t:"sort",d:.75,q:"Classe chaque idée : vraie ou idée reçue ?",bins:["Vraie","Idée reçue"],it:[["Les meilleurs lutteurs frappent aussi",0],["Un lutteur ne frappe jamais",1],["Une amenée se prépare",0],["Plus on plonge de loin, mieux c'est",1]],w:"Le MMA moderne mélange tout : la menace de la lutte ouvre les coups."},
{i:"m221_28",u:221,t:"story",d:.75,q:"Rappel du module 1 : Viktor amène Enzo trois fois mais ne fait rien au sol. Qui gagne le round ?",sc:[{who:"Tom",txt:"Trois amenées, c'est gagné pour Viktor, non ?"}],o:["« Pas forcément : si Enzo a plus touché debout, les juges le préféreront. »","« Oui, chaque amenée vaut automatiquement un round gagné, peu importe. »","« Non, les amenées sont interdites, Viktor perd des points à chaque tentative. »","« Personne, le round est annulé quand il y a plus de deux amenées. »"],a:0,w:"Les juges regardent d'abord l'impact. Une amenée sans suite pèse moins que des coups qui touchent."},
{i:"m221_29",u:221,t:"tf",d:.8,q:"Celui qui décide où se passe le combat, debout ou au sol, prend un gros avantage.",a:true,w:"C'est la leçon de Rachid : contrôler l'endroit du combat, c'est imposer son terrain."},
{i:"m221_30",u:221,t:"mcq",d:.8,q:"Par quoi Khabib a-t-il fini McGregor à l'UFC 229 ?",o:["Une clé de cou au 4e round","Un KO au 1er round","Une décision unanime des juges","Un arrêt du médecin au 3e round"],a:0,w:"Une clé de cou (neck crank) au 4e round, après trois rounds de domination au sol."},
{i:"m221_31",u:221,t:"fill",d:.85,q:"Beaucoup de champions de l'UFC viennent de la lutte ___ américaine.",o:["universitaire","gréco-romaine","olympique","de plage"],a:0,w:"Très axée sur le contrôle au sol et sur le fait de se relever : idéale pour le MMA."},
{i:"m221_32",u:221,t:"story",d:.9,q:"Synthèse : Rachid demande à Lina de résumer la lutte offensive en MMA pour Enzo.",sc:[{who:"Rachid",txt:"Une phrase pour qu'il s'en souvienne."}],o:["« Baisse, plonge, termine, au bon moment : quand il frappe, ou à la cage. »","« Plonge le plus souvent possible, de n'importe où, sans jamais préparer. »","« Ne plonge jamais, la lutte est réservée aux spécialistes, pas aux boxeurs. »","« Plonge uniquement à la dernière seconde de chaque round, pour les juges. »"],a:0,w:"Trois temps, un bon timing, une préparation : et la menace ouvre aussi la frappe."}
