/*UNIT*/
{id:222,c:"MMA",n:"Module 8",t:"Défendre l'amenée : sprawl, whizzer et se relever",col:"--red",ic:"🛡️",guide:`
<h3>Cent sprawls</h3>
<div class="gstory">Mardi, 7 h du matin. Rachid a promis à Enzo qu'il ne se ferait plus ramasser. Programme : cent sprawls, au sifflet, dans tous les états de fatigue. Lina plonge, Enzo jette ses jambes en arrière, écrase ses hanches sur ses épaules, et se relève. Au quatre-vingtième, Enzo vomit presque. Au centième, il sourit : Lina n'a plus réussi à le faire tomber depuis dix plongeons. Rachid : « Un boxeur qui sait sprawler et se relever, c'est un cauchemar pour un lutteur. On appelle ça le "sprawl and brawl". »</div>
<h3>La première ligne de défense : la distance et les mains</h3>
<ul><li>Hanches légèrement <b>basses</b>, poids au centre (module 3).</li>
<li>Les mains devant pour <b>repousser la tête</b> et les épaules du lutteur, et contrôler ses mains (la bataille des mains).</li>
<li>Ne pas rester <b>dos à la cage</b> : c'est là que les amenées passent le mieux.</li></ul>
<h3>Le sprawl</h3>
<div class="gsvg-wrap"><svg class='gsvg' viewBox='0 0 200 190' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><line x1='10' y1='170' x2='190' y2='170' stroke='var(--dim2)' stroke-width='2'/><path d='M22 168 L52 160 L108 146' stroke='var(--blue)' stroke-width='11' fill='none' stroke-linecap='round' stroke-linejoin='round'/><circle cx='120' cy='146' r='10' fill='var(--blue)'/><path d='M104 150 L140 164' stroke='var(--blue)' stroke-width='7' stroke-linecap='round'/><circle cx='96' cy='112' r='10' fill='var(--red)'/><path d='M104 118 L134 132 L186 166' stroke='var(--red)' stroke-width='11' fill='none' stroke-linecap='round' stroke-linejoin='round'/><path d='M104 122 L98 140' stroke='var(--red)' stroke-width='7' stroke-linecap='round'/><text x='100' y='30' font-size='10' fill='var(--txt)' text-anchor='middle' font-weight='700'>Sprawl (rouge) contre double jambe</text><text x='100' y='46' font-size='9' fill='var(--dim)' text-anchor='middle' font-weight='600'>hanches lourdes, jambes projetées en arrière</text></svg></div>
<p>Quand le lutteur plonge aux jambes, on <b>projette les deux jambes en arrière</b>, on <b>écrase les hanches</b> sur ses épaules ou sa tête et on repousse sa tête vers le sol. Son élan meurt dans le tapis. Ensuite, on se relève, ou on tourne autour de lui pour prendre son dos.</p>
<div class="gmnemo"><b>« Jambes derrière, hanches lourdes, tête en bas. »</b> Les trois gestes du sprawl. Et la philosophie du boxeur : <b>« Sprawl, lève-toi, frappe. »</b></div>
<h3>Les autres défenses</h3>
<table><tr><th>Défense</th><th>Contre quoi</th><th>Principe</th></tr>
<tr><td><b>Whizzer</b> (overhook)</td><td>Simple jambe, underhook adverse</td><td>Surpasser son bras, peser dessus, écarter les hanches</td></tr>
<tr><td><b>Underhook</b></td><td>Ceinture, clinch</td><td>Glisser un bras dessous pour pivoter et éviter le corps à corps</td></tr>
<tr><td><b>Cadres</b> (frames)</td><td>Toutes les entrées</td><td>Avant-bras sur la tête ou les épaules pour garder l'espace</td></tr>
<tr><td><b>Guillotine</b></td><td>Double jambe tête basse</td><td>Encercler son cou et serrer : une défense qui devient attaque</td></tr>
<tr><td>Frappe en contre</td><td>Plongeon lisible</td><td>Uppercut ou genou au moment où il baisse la tête</td></tr></table>
<h3>Se relever</h3>
<table><tr><th>Situation</th><th>Technique</th></tr>
<tr><td>Au sol, au centre, adversaire à distance</td><td><b>Relevé technique</b> : une main au sol derrière, l'autre protège la tête, on ramène la jambe sous soi et on se relève en reculant</td></tr>
<tr><td>Au sol contre la cage</td><td><b>Monter le long du grillage</b> : dos et tête contre la cage, pieds sous soi, underhook, on remonte en poussant sur les jambes</td></tr>
<tr><td>À quatre pattes, adversaire sur le dos</td><td>Contrôler ses mains, ne jamais laisser la tête basse et le cou exposé</td></tr></table>
<div class="gtrap">Erreur fréquente chez les frappeurs : s'accrocher au grillage pour ne pas tomber. C'est une <b>faute</b> (avertissement, puis retrait de point). Autre erreur : se relever en laissant le cou et la tête exposés, ce qui offre un étranglement ou un genou. Et une nuance sur les règles récentes : depuis fin 2024, poser une <b>main</b> au sol ne fait plus de toi un combattant « au sol » ; il faut une autre partie du corps que les mains ou les pieds (module 1).</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Décrire le sprawl et son timing</li><li>Choisir la bonne défense selon l'amenée</li><li>Expliquer les deux façons de se relever</li><li>Construire un plan « sprawl and brawl »</li></ul>`},
/*EXOS*/
{i:"m222_01",u:222,t:"mcq",d:.2,nw:"Le sprawl",q:"Sur ce schéma, que fait le combattant rouge ?",svg:"<svg viewBox='0 0 200 190' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><line x1='10' y1='170' x2='190' y2='170' stroke='var(--dim2)' stroke-width='2'/><path d='M22 168 L52 160 L108 146' stroke='var(--blue)' stroke-width='11' fill='none' stroke-linecap='round' stroke-linejoin='round'/><circle cx='120' cy='146' r='10' fill='var(--blue)'/><path d='M104 150 L140 164' stroke='var(--blue)' stroke-width='7' stroke-linecap='round'/><circle cx='96' cy='112' r='10' fill='var(--red)'/><path d='M104 118 L134 132 L186 166' stroke='var(--red)' stroke-width='11' fill='none' stroke-linecap='round' stroke-linejoin='round'/><path d='M104 122 L98 140' stroke='var(--red)' stroke-width='7' stroke-linecap='round'/><text x='100' y='30' font-size='10' fill='var(--txt)' text-anchor='middle' font-weight='700'>Sprawl (rouge) contre double jambe</text><text x='100' y='46' font-size='9' fill='var(--dim)' text-anchor='middle' font-weight='600'>hanches lourdes, jambes projetées en arrière</text></svg>",o:["Il sprawle contre une double jambe","Il réussit une projection de hanche","Il prend le dos de l'adversaire","Il frappe un genou au visage"],a:0,w:"Jambes projetées en arrière, hanches écrasées sur le dos du lutteur : c'est le sprawl."},
{i:"m222_02",u:222,t:"tiles",d:.2,q:"Reconstitue les trois gestes du sprawl.",a:["jambes","derrière","hanches","lourdes","tête","en","bas"],dd:["devant","légères","haut"],w:"Jambes derrière, hanches lourdes, tête du lutteur repoussée en bas."},
{i:"m222_03",u:222,t:"story",d:.25,q:"Enzo se fait amener chaque fois qu'il est dos au grillage. Que corrige Rachid en premier ?",sc:[{who:"Enzo",txt:"Au centre, je sprawle bien. Contre la cage, je tombe."}],o:["« Ne reste pas dos à la cage : elle bloque tes jambes pour le sprawl. »","« Accroche-toi au grillage avec les doigts pour ne plus jamais tomber. »","« Reste dos à la cage, mais baisse les mains pour protéger tes jambes. »","« Saute par-dessus le lutteur dès qu'il plonge, c'est la parade idéale. »"],a:0,w:"La première défense, c'est le placement : le centre pour moi. S'agripper à la cage est une faute."},
{i:"m222_04",u:222,t:"fill",d:.25,q:"La défense qui consiste à surpasser le bras de l'adversaire contre une simple jambe s'appelle le ___.",o:["whizzer","sprawl","pummel","plum"],a:0,w:"Le whizzer, un overhook appuyé : on pèse sur son bras et on écarte les hanches."},
{i:"m222_05",u:222,t:"tf",d:.25,q:"S'agripper au grillage pour éviter une amenée est autorisé.",a:false,w:"C'est une faute : avertissement, puis retrait de point."},
{i:"m222_06",u:222,t:"match",d:.3,q:"Associe chaque défense à l'attaque qu'elle contre.",p:[["Sprawl","Double jambe"],["Whizzer","Simple jambe"],["Underhook","Ceinture et clinch"],["Guillotine","Plongeon tête basse"]],w:"Chaque amenée a sa défense privilégiée. Mais la première défense reste la distance et le placement au centre."},
{i:"m222_07",u:222,t:"story",d:.3,q:"Lina plonge tête basse en double jambe. Quelle défense peut devenir une attaque ?",sc:[{who:"Rachid",txt:"Quand elle baisse la tête comme ça, qu'est-ce que tu lui prends ?"}],o:["« Son cou : une guillotine, en sprawlant pour la bloquer. »","« Sa jambe : une clé de talon, directement debout pendant l'entrée. »","« Rien, il faut toujours la laisser faire pour ne pas se fatiguer. »","« Son poignet : le tordre pour l'obliger à lâcher prise tout de suite. »"],a:0,w:"Tête basse, cou offert. La guillotine est une défense qui devient attaque. Tordre un poignet, lui, n'est pas une petite articulation interdite, mais inefficace ici."},
{i:"m222_08",u:222,t:"order",d:.35,q:"Remets dans l'ordre le relevé technique au centre.",it:["Une main au sol derrière soi","L'autre main protège la tête","Ramener une jambe sous soi","Se relever en reculant","Revenir en garde"],w:"On se relève sans offrir la tête, en reculant hors de portée."},
{i:"m222_09",u:222,t:"sort",d:.35,q:"Classe chaque réaction à un plongeon : bonne défense ou erreur ?",bins:["Bonne défense","Erreur"],it:[["Projeter les jambes en arrière",0],["Tomber sur le dos pour amortir",1],["Écraser les hanches sur ses épaules",0],["S'accrocher au grillage",1],["Repousser sa tête vers le sol",0]],w:"Jambes derrière, hanches lourdes, tête en bas. Jamais sur le dos, jamais la cage."},
{i:"m222_10",u:222,t:"mcq",d:.35,q:"Que signifie « sprawl and brawl » ?",o:["Défendre la lutte pour imposer la frappe","Amener au sol puis frapper au sol","Frapper uniquement au corps, jamais la tête","Se battre uniquement en clinch contre la cage"],a:0,w:"Le frappeur défend la lutte (sprawl) et ramène le combat debout, où il est plus fort (brawl)."},
{i:"m222_11",u:222,t:"story",d:.4,q:"Enzo est au sol contre la cage, Viktor au-dessus. Comment se relever ?",sc:[{who:"Enzo",txt:"Je suis coincé contre le grillage, je fais quoi ?"}],o:["« Dos contre la cage, pieds sous toi, underhook, et remonte. »","« Reste allongé et attends que l'arbitre vous remette debout. »","« Tourne-toi à plat ventre pour protéger ton visage des coups. »","« Accroche le grillage avec tes doigts pour te hisser debout. »"],a:0,w:"Monter le long du grillage : la cage devient un appui. Sans jamais s'y agripper avec les doigts."},
{i:"m222_12",u:222,t:"fill",d:.4,q:"Les avant-bras qui gardent l'espace sur la tête ou les épaules de l'adversaire s'appellent des ___.",o:["cadres","crochets","gardes","paumes"],a:0,w:"Les cadres (frames) : on ne pousse pas, on bloque la distance avec les os."},
{i:"m222_13",u:222,t:"tf",d:.4,q:"Depuis fin 2024, poser une seule main au sol suffit à être considéré comme « au sol » selon les règles unifiées.",a:false,w:"Il faut qu'une partie du corps autre que les mains ou les pieds touche le tapis. Une main posée n'empêche plus un coup de genou."},
{i:"m222_14",u:222,t:"multi",d:.45,q:"Quelle est la première ligne de défense contre les amenées ?",o:["Hanches un peu basses","Mains devant pour repousser","Éviter le dos à la cage","Contrôler les mains du lutteur","Rester immobile, hanches hautes"],a:[0,1,2,3],w:"Hanches hautes et immobilité, c'est offrir ses jambes."},
{i:"m222_15",u:222,t:"story",d:.45,q:"Rappel du module 7 : Viktor plonge toujours juste après son jab. Comment Enzo peut-il l'exploiter ?",sc:[{who:"Enzo",txt:"Jab, puis plongeon, il fait toujours pareil."}],o:["« Au jab, prépare le sprawl, ou un uppercut quand il plonge. »","« Au jab, baisse les mains pour protéger tes jambes à l'avance. »","« Au jab, recule tout droit jusqu'à la cage pour lui échapper. »","« Au jab, plonge toi aussi, pour que vos têtes se cognent. »"],a:0,w:"Un plongeon lisible se contre : sprawl, genou ou uppercut au moment où la tête descend."},
{i:"m222_16",u:222,t:"match",d:.45,q:"Associe chaque situation à la façon de se relever.",p:[["Au sol au centre, adversaire à distance","Relevé technique"],["Au sol contre la cage","Monter le long du grillage"],["Après un sprawl réussi","Se relever ou prendre le dos"],["Quatre pattes, adversaire dessus","Contrôler ses mains, tête haute"]],w:"Chaque situation a sa sortie. Dans tous les cas, on protège la tête et le cou pendant qu'on se relève."},
{i:"m222_17",u:222,t:"mcq",d:.5,q:"Après un sprawl réussi, que fait le frappeur ?",o:["Il se relève, ou tourne pour prendre le dos","Il reste allongé sur le lutteur longtemps","Il saute par-dessus la cage pour sortir","Il lève les bras pour saluer les juges"],a:0,w:"Sprawl, lève-toi, frappe. Ou, s'il en a les moyens, il prend le dos."},
{i:"m222_18",u:222,t:"sort",d:.5,q:"Classe chaque défense : utilisée debout au centre ou contre la cage ?",bins:["Au centre","Contre la cage"],it:[["Sprawl ample",0],["Underhook et pivot",1],["Relevé technique",0],["Monter le long du grillage",1]],w:"Au centre, on a la place de sprawler ; contre la cage, on pivote et on remonte."},
{i:"m222_19",u:222,t:"story",d:.55,q:"Tom se relève en tournant le dos et en baissant la tête. Rachid l'arrête. Pourquoi ?",sc:[{who:"Tom",txt:"Je me relève comme je peux, non ?"}],o:["« Tête basse et dos tourné, tu offres ton cou et un genou. »","« Il faut se relever encore plus vite, sans penser à la tête. »","« Il faut se relever en roulade avant, c'est la seule technique. »","« Il ne faut jamais se relever, le sol est ta meilleure position. »"],a:0,w:"Se relever sans protéger la tête et le cou offre un étranglement ou un coup de genou."},
{i:"m222_20",u:222,t:"fill",d:.55,q:"La philosophie du boxeur face à un lutteur : « Sprawl, lève-toi, ___ ».",o:["frappe","plonge","attends","recule"],a:0,w:"Ramener le combat là où il est le plus fort : debout."},
{i:"m222_21",u:222,t:"tf",d:.6,q:"Le sprawl consiste à projeter les jambes en arrière et à écraser les hanches sur l'adversaire.",a:true,w:"Son élan meurt dans le tapis. Puis on se relève ou on prend le dos."},
{i:"m222_22",u:222,t:"multi",d:.6,q:"Pourquoi faire cent sprawls à l'entraînement, même épuisé ?",o:["Le geste doit devenir un réflexe","La fatigue du combat ne laisse pas le temps de réfléchir","Les lutteurs attaquent souvent en fin de round","Les jambes doivent tenir le rythme","Pour punir le combattant de ses erreurs"],a:[0,1,2,3],w:"L'entraînement n'est pas une punition : c'est pour que le réflexe survive à la fatigue."},
{i:"m222_23",u:222,t:"story",d:.65,q:"Rappel du module 6 : Viktor tente une ceinture au centre. Quelle défense pour Enzo ?",sc:[{who:"Enzo",txt:"Il me serre la taille, il va me soulever."}],o:["« Un underhook, hanches reculées, et pivote pour casser sa prise. »","« Lever les bras au ciel pour que ses mains glissent vers le bas. »","« Se laisser tomber sur lui pour l'écraser de tout son poids. »","« Frapper sa nuque, c'est la seule cible accessible dans ce cas. »"],a:0,w:"Underhook et hanches loin. Frapper la nuque est une faute."},
{i:"m222_24",u:222,t:"mcq",d:.65,q:"Pourquoi le sprawl est-il plus difficile contre la cage ?",o:["Les jambes ne peuvent pas reculer","La cage est électrifiée à cet endroit","L'arbitre l'interdit près du grillage","Le tapis y est plus dur et glissant"],a:0,w:"Le grillage bloque les jambes. D'où l'importance de rester au centre."},
{i:"m222_25",u:222,t:"tiles",d:.7,q:"Reconstitue la philosophie du sprawl and brawl.",a:["sprawl","lève-toi","frappe"],dd:["dors","plonge","abandonne"],w:"Défendre la lutte pour imposer la frappe."},
{i:"m222_26",u:222,t:"sort",d:.7,q:"Classe chaque geste : faute ou technique légale ?",bins:["Technique légale","Faute"],it:[["Guillotine sur un plongeon",0],["Agripper le grillage",1],["Whizzer sur une simple jambe",0],["Coup de coude à la nuque",1],["Monter le long de la cage, dos contre elle",0]],w:"La cage sert d'appui, pas de poignée. La nuque est interdite."},
{i:"m222_27",u:222,t:"story",d:.75,q:"Rappel du module 7 : Ngannou a battu Gane en l'amenant au sol. Qu'aurait dû mieux faire Gane selon ce module ?",sc:[{who:"Tom",txt:"Gane est pourtant super mobile."}],o:["« Mieux défendre les entrées et se relever vite pour revenir debout. »","« Attaquer lui-même en lutte, en délaissant totalement sa frappe. »","« Rester au sol le plus longtemps possible pour reposer ses jambes. »","« Accrocher le grillage à chaque amenée pour ne pas tomber. »"],a:0,w:"Sprawl, lève-toi, frappe. Face à un adversaire qui change de plan, la défense de lutte et le relevé deviennent décisifs."},
{i:"m222_28",u:222,t:"fill",d:.75,q:"Une double jambe lancée tête basse offre le cou à la ___.",o:["guillotine","clé de bras","clé de talon","kimura"],a:0,w:"La guillotine : on encercle le cou et on serre. Une défense qui peut finir le combat."},
{i:"m222_29",u:222,t:"tf",d:.8,q:"Un frappeur qui sait sprawler et se relever est très difficile à battre pour un lutteur.",a:true,w:"C'est le profil « sprawl and brawl » : il ramène sans cesse le combat là où il domine."},
{i:"m222_30",u:222,t:"match",d:.8,q:"Associe chaque erreur à sa correction.",p:[["Dos à la cage","Revenir au centre"],["Hanches hautes","Baisser le centre de gravité"],["Se relever tête basse","Protéger la tête, reculer"],["S'agripper au grillage","Underhook et pivot"]],w:"Quatre erreurs de frappeur face à la lutte, quatre corrections."},
{i:"m222_31",u:222,t:"mcq",d:.85,q:"Quelle partie du corps le whizzer contrôle-t-il ?",o:["Le bras adverse, par-dessus","Sa jambe, par en dessous","Sa tête, par-derrière le cou","Ses deux poignets en même temps"],a:0,w:"Un overhook appuyé : on pèse sur son bras et on écarte les hanches pour casser la simple jambe."},
{i:"m222_32",u:222,t:"story",d:.9,q:"Synthèse : Rachid demande le plan de défense de lutte d'Enzo contre Viktor.",sc:[{who:"Rachid",txt:"Trois consignes, pas plus."}],o:["« Rester au centre, sprawler ses plongeons, se relever pour frapper. »","« Aller au sol avec lui pour lui montrer qu'on n'a pas peur de sa lutte. »","« Rester collé au grillage pour que ses amenées manquent de place. »","« Ne pas bouger du tout pour ne pas lui donner de signal de départ. »"],a:0,w:"Le centre pour moi ; jambes derrière, hanches lourdes, tête en bas ; sprawl, lève-toi, frappe."}
