/*UNIT*/
{id:223,c:"MMA",n:"Module 9",t:"Le sol, niveau 1 : les positions du jiu-jitsu brésilien",col:"--red",ic:"🧩",guide:`
<h3>Les échecs du sol</h3>
<div class="gstory">Jeudi soir, Maëlle, 31 ans, ceinture violette de jiu-jitsu brésilien (JJB), prend Tom sous son aile. En deux minutes, elle passe ses jambes, s'assoit sur son ventre, puis prend son dos, sans jamais forcer. Tom, rouge, s'étonne : « Tu fais 20 kilos de moins que moi ! » Maëlle : « Le sol, c'est des échecs. Chaque position vaut quelque chose. Tant que tu ne connais pas la valeur des cases, tu joues sans savoir qui gagne. » Elle dessine au feutre, sur le tableau blanc, cinq positions.</div>
<h3>D'où vient le JJB</h3>
<p>Au début du XXe siècle, le judoka japonais Mitsuyo Maeda enseigne au Brésil. La famille <b>Gracie</b> (Carlos, puis Hélio) adapte son art pour le combat au sol, en misant sur les <b>leviers</b> plutôt que sur la force. En 1993, Royce Gracie gagne l'UFC 1 (module 1) et le monde découvre le jiu-jitsu brésilien. Les ceintures adultes vont de la <b>blanche</b> à la <b>noire</b>, en passant par la bleue, la violette et la marron. Il faut souvent une dizaine d'années pour obtenir la noire.</p>
<h3>La hiérarchie des positions (pour celui du dessus)</h3>
<table><tr><th>Rang</th><th>Position</th><th>Pourquoi</th></tr>
<tr><td>1</td><td><b>Dos</b>, avec les crochets (pieds à l'intérieur de ses cuisses)</td><td>Il ne voit rien, ne peut pas frapper, étranglement arrière possible</td></tr>
<tr><td>2</td><td><b>Montée</b> (assis sur son ventre)</td><td>Frappes lourdes, clés de bras, il peut à peine frapper</td></tr>
<tr><td>3</td><td><b>Contrôle latéral</b> (en travers de sa poitrine)</td><td>Contrôle fort, ses jambes sont passées</td></tr>
<tr><td>4</td><td><b>Demi-garde</b> (une de tes jambes piégée)</td><td>Presque passé, mais il garde un peu de contrôle</td></tr>
<tr><td>5</td><td><b>Garde</b> (tu es entre ses jambes)</td><td>Ses jambes le protègent, il peut balayer ou soumettre</td></tr></table>
<div class="gsvg-wrap"><svg class='gsvg' viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='5' y='5' width='190' height='170' rx='10' fill='var(--card)'/><rect x='83' y='55' width='34' height='70' rx='17' fill='var(--blue)' transform='rotate(0 100 90)'/><circle cx='100' cy='44' r='11' fill='var(--blue)' stroke='var(--bg)' stroke-width='2'/><rect x='82' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 88 142)'/><rect x='106' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 112 142)'/><rect x='85' y='76' width='30' height='40' rx='15' fill='var(--red)' transform='rotate(0 100 96)'/><circle cx='100' cy='64' r='11' fill='var(--red)' stroke='var(--bg)' stroke-width='2'/><rect x='67' y='85' width='10' height='34' rx='5' fill='var(--red)' transform='rotate(-15 72 102)'/><rect x='123' y='85' width='10' height='34' rx='5' fill='var(--red)' transform='rotate(15 128 102)'/><text x='100' y='192' font-size='10' fill='var(--txt)' text-anchor='middle' font-weight='700'>Montée (rouge assis sur le ventre)</text></svg></div>
<div class="gmnemo"><b>« Plus tu es loin de ses jambes, mieux c'est. »</b> Les jambes du combattant du dessous sont ses armes et ses boucliers : passer ses jambes, c'est progresser. Et l'ordre : <b>« Dos, Montée, Latéral, Demi, Garde »</b>, du meilleur au moins bon pour celui du dessus.</div>
<h3>Les gardes, vues du dessous</h3>
<table><tr><th>Garde</th><th>Description</th></tr>
<tr><td><b>Garde fermée</b></td><td>Jambes croisées autour de la taille de l'adversaire : on le tire vers soi, il ne peut pas se redresser</td></tr>
<tr><td>Garde ouverte</td><td>Pieds sur les hanches, les biceps ou les genoux : on garde la distance et on prépare les balayages</td></tr>
<tr><td>Garde papillon</td><td>Pieds en crochets sous ses cuisses : idéale pour le soulever et se relever</td></tr>
<tr><td>Demi-garde</td><td>Une de ses jambes piégée entre les tiennes : dernière barrière avant d'être passé</td></tr></table>
<h3>Les points du JJB sportif</h3>
<table><tr><th>Action</th><th>Points (règles IBJJF)</th></tr>
<tr><td>Amenée au sol, balayage, genou sur le ventre</td><td>2</td></tr>
<tr><td>Passage de garde</td><td>3</td></tr>
<tr><td>Montée, prise de dos avec crochets</td><td>4</td></tr></table>
<p>Ce barème résume la hiérarchie : plus une position est dominante, plus elle vaut.</p>
<h3>S'échapper</h3>
<ul><li>La <b>crevette</b> (échappement de hanche) : on pousse sur un pied pour glisser les hanches sur le côté et remettre une jambe entre soi et l'adversaire. C'est le mouvement le plus important du JJB.</li>
<li>Le <b>pont</b> : sous la montée, on soulève les hanches en bloquant un bras et une jambe du même côté, pour le faire basculer.</li>
<li>Les <b>cadres</b> : avant-bras sur son cou ou ses hanches, pour garder l'espace.</li></ul>
<div class="gtrap">Précision importante : le JJB sportif et le sol du MMA ne sont pas identiques. En JJB, être sur le dos en garde est une position confortable. En MMA, l'adversaire du dessus peut <b>frapper</b>, et les juges voient souvent celui du dessus comme dominant. Une garde fermée passive en MMA fait donc perdre des rounds. Le module 11 détaille ces différences.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Classer les positions de la plus dominante à la moins dominante</li><li>Reconnaître chaque position sur un schéma</li><li>Distinguer les gardes et les points du JJB</li><li>Expliquer la crevette, le pont et les cadres</li></ul>`},
/*EXOS*/
{i:"m223_01",u:223,t:"mcq",d:.2,nw:"Les positions au sol",q:"Maëlle dessine cette position. Le rouge est au-dessus. Laquelle est-ce ?",svg:"<svg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='5' y='5' width='190' height='170' rx='10' fill='var(--card)'/><rect x='83' y='55' width='34' height='70' rx='17' fill='var(--blue)' transform='rotate(0 100 90)'/><circle cx='100' cy='44' r='11' fill='var(--blue)' stroke='var(--bg)' stroke-width='2'/><rect x='82' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 88 142)'/><rect x='106' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 112 142)'/><rect x='85' y='76' width='30' height='40' rx='15' fill='var(--red)' transform='rotate(0 100 96)'/><circle cx='100' cy='64' r='11' fill='var(--red)' stroke='var(--bg)' stroke-width='2'/><rect x='67' y='85' width='10' height='34' rx='5' fill='var(--red)' transform='rotate(-15 72 102)'/><rect x='123' y='85' width='10' height='34' rx='5' fill='var(--red)' transform='rotate(15 128 102)'/><text x='100' y='192' font-size='10' fill='var(--gold)' text-anchor='middle' font-weight='700'>Quelle position ?</text></svg>",o:["La montée","Le contrôle latéral","La garde fermée","Le dos"],a:0,w:"Rouge assis sur le ventre du bleu : la montée, deuxième position la plus dominante."},
{i:"m223_02",u:223,t:"order",d:.2,q:"Classe les positions pour celui du dessus, de la plus dominante à la moins dominante.",it:["Dos","Montée","Contrôle latéral","Demi-garde","Garde"],w:"Dos, Montée, Latéral, Demi, Garde. Plus tu es loin de ses jambes, mieux c'est."},
{i:"m223_03",u:223,t:"story",d:.25,q:"Tom, 20 kilos de plus que Maëlle, ne comprend pas pourquoi il perd au sol.",sc:[{who:"Tom",txt:"Je suis plus lourd et plus fort, c'est illogique."}],o:["« Le JJB mise sur les leviers et les positions, pas sur la force. »","« Maëlle triche forcément, c'est impossible avec 20 kilos d'écart. »","« Tu dois simplement prendre encore plus de poids pour l'écraser. »","« Le sol ne compte pas, seul le combat debout a une vraie valeur. »"],a:0,w:"C'est la leçon des Gracie et de Royce à l'UFC 1 : les leviers et la connaissance des positions battent la force."},
{i:"m223_04",u:223,t:"fill",d:.25,q:"Le mouvement qui fait glisser les hanches sur le côté pour remettre une jambe s'appelle la ___.",o:["crevette","grenouille","tortue","pieuvre"],a:0,w:"La crevette (échappement de hanche), le mouvement le plus important du JJB."},
{i:"m223_05",u:223,t:"tf",d:.25,q:"Dans la garde fermée, le combattant du dessous croise ses jambes autour de la taille de l'adversaire.",a:true,w:"Il le tire vers lui et l'empêche de se redresser. En MMA, attention à ne pas rester passif."},
{i:"m223_06",u:223,t:"mcq",d:.3,q:"Quelle position est représentée ? Le rouge est derrière le bleu.",svg:"<svg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='5' y='5' width='190' height='170' rx='10' fill='var(--card)'/><rect x='82' y='64' width='36' height='72' rx='18' fill='var(--red)' transform='rotate(0 100 100)'/><circle cx='100' cy='52' r='11' fill='var(--red)' stroke='var(--bg)' stroke-width='2'/><rect x='85' y='59' width='30' height='62' rx='15' fill='var(--blue)' transform='rotate(0 100 90)'/><circle cx='100' cy='44' r='11' fill='var(--blue)' stroke='var(--bg)' stroke-width='2'/><path d='M84 110 Q74 124 90 132' stroke='var(--red)' stroke-width='8' fill='none' stroke-linecap='round'/><path d='M116 110 Q126 124 110 132' stroke='var(--red)' stroke-width='8' fill='none' stroke-linecap='round'/><path d='M82 54 Q100 68 118 54' stroke='var(--red)' stroke-width='6' fill='none'/><text x='100' y='192' font-size='10' fill='var(--gold)' text-anchor='middle' font-weight='700'>Quelle position ?</text></svg>",o:["Le dos, avec crochets","La garde fermée inversée","La demi-garde profonde","La montée arrière"],a:0,w:"Rouge derrière, pieds à l'intérieur des cuisses du bleu, bras autour du cou : la prise de dos, la plus dominante."},
{i:"m223_07",u:223,t:"match",d:.3,q:"Associe chaque action du JJB sportif à ses points.",p:[["Balayage","2 points"],["Passage de garde","3 points"],["Montée","4 points"],["Dos avec crochets","4 points"]],w:"Plus la position est dominante, plus elle vaut."},
{i:"m223_08",u:223,t:"story",d:.3,q:"Tom est sous la montée de Maëlle et pousse de toutes ses forces sur sa poitrine. Que lui conseille-t-elle ?",sc:[{who:"Tom",txt:"Je pousse, mais elle ne bouge pas !"}],o:["« Bloque un bras et une jambe du même côté, puis fais le pont. »","« Pousse encore plus fort avec les deux bras tendus vers le haut. »","« Tourne-toi sur le ventre pour te protéger complètement le visage. »","« Ne bouge plus du tout, elle finira par se fatiguer toute seule. »"],a:0,w:"Le pont : on bloque le bras et la jambe du même côté pour qu'elle ne puisse pas se rattraper, et on la fait basculer. Se tourner sur le ventre, c'est donner le dos."},
{i:"m223_09",u:223,t:"sort",d:.35,q:"Classe chaque position : avantage à celui du dessus ou garde encore active du dessous ?",bins:["Avantage au dessus","Dessous encore protégé"],it:[["Montée",0],["Garde fermée",1],["Contrôle latéral",0],["Garde papillon",1],["Dos avec crochets",0]],w:"Tant que ses jambes sont entre lui et l'adversaire, le combattant du dessous reste protégé."},
{i:"m223_10",u:223,t:"tiles",d:.35,q:"Reconstitue le principe de Maëlle.",a:["plus","tu","es","loin","de","ses","jambes","mieux","c'est"],dd:["bras","près","pire"],w:"Les jambes du dessous sont ses armes et ses boucliers : les passer, c'est progresser."},
{i:"m223_11",u:223,t:"mcq",d:.35,q:"Quelle position est représentée ? Le rouge est en travers du bleu.",svg:"<svg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='5' y='5' width='190' height='170' rx='10' fill='var(--card)'/><rect x='83' y='55' width='34' height='70' rx='17' fill='var(--blue)' transform='rotate(0 100 90)'/><circle cx='100' cy='44' r='11' fill='var(--blue)' stroke='var(--bg)' stroke-width='2'/><rect x='82' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 88 142)'/><rect x='106' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 112 142)'/><rect x='107' y='69' width='70' height='30' rx='15' fill='var(--red)' transform='rotate(0 142 84)'/><circle cx='100' cy='80' r='11' fill='var(--red)' stroke='var(--bg)' stroke-width='2'/><text x='100' y='192' font-size='10' fill='var(--gold)' text-anchor='middle' font-weight='700'>Quelle position ?</text></svg>",o:["Le contrôle latéral","La montée","La garde ouverte","Le dos sans crochets"],a:0,w:"Rouge en travers de la poitrine du bleu, ses jambes passées : contrôle latéral."},
{i:"m223_12",u:223,t:"fill",d:.4,q:"Le judoka japonais qui a enseigné aux Gracie au Brésil s'appelle Mitsuyo ___.",o:["Maeda","Kano","Musashi","Mifune"],a:0,w:"Mitsuyo Maeda. Jigoro Kano est le fondateur du judo."},
{i:"m223_13",u:223,t:"story",d:.4,q:"Maëlle est en demi-garde au-dessus de Tom. Que cherche-t-elle ?",sc:[{who:"Tom",txt:"Elle essaie de sortir sa jambe, pourquoi ?"}],o:["« Libérer sa jambe piégée pour passer ta garde et monter. »","« Se relever pour quitter le combat au sol et frapper debout. »","« Te laisser la reprendre en garde fermée par politesse. »","« Rien de précis, elle se repose simplement entre deux actions. »"],a:0,w:"La demi-garde est la dernière barrière : une fois la jambe libérée, c'est le passage, puis le contrôle latéral ou la montée."},
{i:"m223_14",u:223,t:"multi",d:.4,q:"Quelles sont les ceintures adultes du JJB ?",o:["Blanche","Bleue","Violette","Marron","Jaune"],a:[0,1,2,3],w:"Blanche, bleue, violette, marron, puis noire. La jaune existe chez les enfants, pas chez les adultes."},
{i:"m223_15",u:223,t:"tf",d:.45,q:"En JJB sportif, un passage de garde rapporte 4 points.",a:false,w:"3 points. La montée et le dos avec crochets en rapportent 4."},
{i:"m223_16",u:223,t:"mcq",d:.45,q:"Quelle position est représentée ? Le rouge a une jambe piégée.",svg:"<svg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='5' y='5' width='190' height='170' rx='10' fill='var(--card)'/><rect x='83' y='55' width='34' height='70' rx='17' fill='var(--blue)' transform='rotate(0 100 90)'/><circle cx='100' cy='44' r='11' fill='var(--blue)' stroke='var(--bg)' stroke-width='2'/><rect x='82' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 88 142)'/><rect x='106' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 112 142)'/><rect x='102' y='75' width='32' height='58' rx='16' fill='var(--red)' transform='rotate(20 118 104)'/><circle cx='108' cy='72' r='11' fill='var(--red)' stroke='var(--bg)' stroke-width='2'/><path d='M112 150 Q126 136 132 128' stroke='var(--blue)' stroke-width='10' fill='none' stroke-linecap='round'/><text x='100' y='192' font-size='10' fill='var(--gold)' text-anchor='middle' font-weight='700'>Quelle position ?</text></svg>",o:["La demi-garde","La garde fermée","Le contrôle latéral","La montée"],a:0,w:"Une jambe du rouge est piégée entre celles du bleu : demi-garde, dernière barrière avant le passage."},
{i:"m223_17",u:223,t:"match",d:.5,q:"Associe chaque garde à sa description.",p:[["Garde fermée","Jambes croisées autour de la taille"],["Garde papillon","Pieds en crochets sous les cuisses"],["Garde ouverte","Pieds sur les hanches ou les biceps"],["Demi-garde","Une jambe adverse piégée"]],w:"Les gardes sont les boucliers du combattant du dessous."},
{i:"m223_18",u:223,t:"story",d:.5,q:"Rappel du module 8 : Enzo se retrouve sur le dos après une amenée. Que doit-il faire en premier ?",sc:[{who:"Enzo",txt:"Je suis au sol, panique à bord."}],o:["« Mettre ses jambes entre lui et Viktor, puis se relever. »","« Se mettre à plat ventre pour protéger son visage des coups. »","« Rester à plat dos sans bouger pour que l'arbitre les relève. »","« Tendre les bras vers Viktor pour le serrer contre lui très fort. »"],a:0,w:"Mettre ses jambes entre soi et l'adversaire, c'est se protéger ; ensuite, la garde papillon ou les cadres pour se relever."},
{i:"m223_19",u:223,t:"fill",d:.55,q:"En garde, avoir les pieds en crochets sous les cuisses de l'adversaire s'appelle la garde ___.",o:["papillon","araignée","fermée","inversée"],a:0,w:"La garde papillon : idéale pour soulever, balayer et se relever."},
{i:"m223_20",u:223,t:"sort",d:.55,q:"Classe chaque action : échappement du dessous ou progression du dessus ?",bins:["Échappement","Progression"],it:[["Crevette",0],["Passage de garde",1],["Pont sous la montée",0],["Prise de dos",1],["Cadres sur les hanches",0]],w:"Le dessous s'échappe par la crevette, le pont et les cadres ; le dessus progresse en passant les jambes."},
{i:"m223_21",u:223,t:"mcq",d:.6,q:"Quelle position est représentée ? Le rouge est entre les jambes du bleu.",svg:"<svg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='5' y='5' width='190' height='170' rx='10' fill='var(--card)'/><rect x='83' y='55' width='34' height='70' rx='17' fill='var(--blue)' transform='rotate(0 100 90)'/><circle cx='100' cy='44' r='11' fill='var(--blue)' stroke='var(--bg)' stroke-width='2'/><rect x='82' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 88 142)'/><rect x='106' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 112 142)'/><rect x='83' y='90' width='34' height='56' rx='17' fill='var(--red)' transform='rotate(0 100 118)'/><circle cx='100' cy='86' r='11' fill='var(--red)' stroke='var(--bg)' stroke-width='2'/><path d='M84 130 Q70 100 92 96' stroke='var(--blue)' stroke-width='10' fill='none' stroke-linecap='round'/><path d='M116 130 Q130 100 108 96' stroke='var(--blue)' stroke-width='10' fill='none' stroke-linecap='round'/><text x='100' y='192' font-size='10' fill='var(--gold)' text-anchor='middle' font-weight='700'>Quelle position ?</text></svg>",o:["La garde fermée","La montée","Le dos","Le contrôle latéral"],a:0,w:"Rouge entre les jambes croisées du bleu : garde fermée. Le bleu est dessous mais protégé."},
{i:"m223_22",u:223,t:"tf",d:.6,q:"En MMA, rester passif en garde fermée sur le dos peut faire perdre un round.",a:true,w:"Le combattant du dessus peut frapper, et les juges voient souvent le dessus comme dominant. On attaque ou on se relève."},
{i:"m223_23",u:223,t:"story",d:.65,q:"Tom tourne le dos sous la montée de Maëlle pour se protéger le visage. Elle sourit. Pourquoi ?",sc:[{who:"Tom",txt:"Au moins, elle ne peut plus me frapper au visage."}],o:["« Tu viens de lui donner ton dos, la position la plus dominante. »","« C'était une excellente idée, tu es maintenant en sécurité totale. »","« Parce que c'est interdit de tourner le dos, tu perds un point. »","« Parce qu'elle doit maintenant te laisser te relever tout seul. »"],a:0,w:"Tourner le dos sous la montée, c'est offrir la prise de dos et l'étranglement arrière. On fait le pont ou la crevette."},
{i:"m223_24",u:223,t:"multi",d:.65,q:"Pourquoi le dos est-il la position la plus dominante ?",o:["L'adversaire ne voit pas","Il ne peut pas frapper efficacement","L'étranglement arrière est possible","Les crochets l'empêchent de se tourner","Il peut facilement faire le pont"],a:[0,1,2,3],w:"Le pont marche sous la montée, pas quand on a le dos pris."},
{i:"m223_25",u:223,t:"fill",d:.7,q:"La famille brésilienne qui a développé le JJB s'appelle la famille ___.",o:["Gracie","Silva","Machado","Nogueira"],a:0,w:"Carlos et Hélio Gracie, puis Royce, vainqueur de l'UFC 1."},
{i:"m223_26",u:223,t:"match",d:.7,q:"Associe chaque échappement à sa situation.",p:[["Pont","Sous la montée"],["Crevette","Sous le contrôle latéral, pour remettre la garde"],["Cadres","Garder l'espace"],["Se relever en papillon","Depuis la garde, en MMA"]],w:"Chaque position du dessous a sa sortie. La crevette est le mouvement le plus important du JJB."},
{i:"m223_27",u:223,t:"story",d:.75,q:"Rappel du module 1 : Tom demande combien de points vaut une montée « en MMA ».",sc:[{who:"Tom",txt:"Donc en MMA, une montée, c'est 4 points ?"}],o:["« Non : en MMA, pas de points de position, on note le round sur 10. »","« Oui, exactement 4 points, comme en JJB, ajoutés au total des juges. »","« Non, en MMA une montée vaut 10 points et gagne le round directement. »","« Oui, et le premier à 12 points gagne le combat avant la limite. »"],a:0,w:"Le barème IBJJF concerne le JJB sportif. En MMA, système des 10 points par round : le contrôle et les dégâts comptent."},
{i:"m223_28",u:223,t:"tiles",d:.75,q:"Reconstitue l'ordre des positions, de la meilleure à la moins bonne pour celui du dessus.",a:["dos","montée","latéral","demi","garde"],dd:["tortue","debout"],w:"Dos, Montée, Latéral, Demi, Garde. Le dos est la pire position pour celui du dessous : étranglement arrière possible."},
{i:"m223_29",u:223,t:"mcq",d:.8,q:"Qu'est-ce qui permet au plus léger de battre le plus lourd au sol ?",o:["Les leviers et la position","La vitesse des coups de poing","La taille des gants","Le bruit du public"],a:0,w:"Le JJB est l'art des leviers : une bonne position vaut plus que 20 kilos."},
{i:"m223_30",u:223,t:"tf",d:.8,q:"En JJB sportif, un balayage rapporte 2 points.",a:true,w:"Amenée, balayage, genou sur le ventre : 2 points."},
{i:"m223_31",u:223,t:"sort",d:.85,q:"Classe chaque réflexe du dessous : bon ou mauvais ?",bins:["Bon réflexe","Mauvais réflexe"],it:[["Remettre une jambe entre soi et l'adversaire",0],["Tourner le dos sous la montée",1],["Faire des cadres sur les hanches",0],["Pousser à bras tendus sur sa poitrine",1]],w:"Pousser à bras tendus offre une clé de bras ; tourner le dos offre le dos."},
{i:"m223_32",u:223,t:"story",d:.9,q:"Synthèse : Maëlle demande à Tom ce qu'il retient de la soirée.",sc:[{who:"Maëlle",txt:"Alors, les échecs du sol ?"}],o:["« Chaque position a sa valeur : passer ses jambes, garder les miennes. »","« Il faut toujours être le plus lourd pour gagner au sol, sans exception. »","« Au sol, il faut tourner le dos pour protéger son visage des coups. »","« Le sol n'a aucune importance, il faut toujours rester debout. »"],a:0,w:"Dos, Montée, Latéral, Demi, Garde. Plus tu es loin de ses jambes, mieux c'est ; et les tiennes te protègent."}
