/*UNIT*/
{id:224,c:"MMA",n:"Module 10",t:"Le sol, niveau 2 : étranglements, clés et comment s'en sortir",col:"--red",ic:"🔒",guide:`
<h3>Taper, ce n'est pas perdre la face</h3>
<div class="gstory">Samedi, Maëlle fait « rouler » Tom six minutes. Elle lui prend le dos, glisse un bras sous son menton ; Tom serre les dents et refuse de taper. Maëlle relâche aussitôt et le regarde : « Si je ne lâche pas, dans quelques secondes tu dors. En compétition, l'arbitre arrête et tu as perdu quand même, en plus de t'être mis en danger. Taper, c'est se donner le droit de revenir demain. » Tom, vexé, promet de taper la prochaine fois. Rachid, qui passait, ajoute : « Et apprends pourquoi tu tapes. Chaque soumission a sa porte de sortie, si tu la prends assez tôt. »</div>
<h3>Deux familles de soumissions</h3>
<table><tr><th>Famille</th><th>Principe</th><th>Effet</th></tr>
<tr><td><b>Étranglements</b></td><td>Comprimer les artères du cou (carotides), plus rarement la trachée</td><td>Perte de conscience en quelques secondes si l'on ne tape pas</td></tr>
<tr><td><b>Clés</b> (articulaires)</td><td>Tordre une articulation au-delà de son amplitude : coude, épaule, genou, cheville</td><td>Douleur, puis entorse ou fracture</td></tr></table>
<div class="gmnemo"><b>« Sang ou os »</b> : l'étranglement coupe le sang, la clé menace l'os et l'articulation. Et pour le triangle : <b>« Un bras dedans, un bras dehors : triangle. Deux dedans ou deux dehors : pas de triangle. »</b></div>
<h3>Les étranglements</h3>
<table><tr><th>Nom</th><th>Depuis</th><th>Défense</th></tr>
<tr><td><b>Étranglement arrière</b> (rear naked choke, « mata leão » : le tue-lion)</td><td>Le dos</td><td>Rentrer le menton, combattre les mains avec les deux mains</td></tr>
<tr><td><b>Guillotine</b></td><td>De face, souvent sur une amenée tête basse (module 8)</td><td>Passer du côté du bras qui étrangle, garder le dos droit</td></tr>
<tr><td><b>Triangle</b></td><td>La garde : les jambes encerclent le cou et un bras</td><td>Posture droite, ne jamais laisser un bras dedans et l'autre dehors</td></tr>
<tr><td>Étranglement bras-tête</td><td>Contrôle latéral ou montée</td><td>Garder le bras collé à son corps, tourner vers l'adversaire</td></tr>
<tr><td>D'Arce, anaconda</td><td>Tête et bras de face, quand l'adversaire est à quatre pattes</td><td>Tête haute, ne pas plonger tête basse</td></tr></table>
<h3>Les clés</h3>
<table><tr><th>Nom</th><th>Articulation</th><th>Défense</th></tr>
<tr><td><b>Clé de bras</b> (armbar)</td><td>Coude, en hyperextension</td><td>Joindre ses mains, tourner le pouce vers l'extérieur, « empiler » l'adversaire</td></tr>
<tr><td><b>Kimura</b></td><td>Épaule, bras plié derrière le dos</td><td>Saisir son propre pantalon ou sa ceinture, garder le coude collé</td></tr>
<tr><td>Americana</td><td>Épaule, bras plié vers le haut</td><td>Garder les coudes collés au corps</td></tr>
<tr><td><b>Clé de talon</b> (heel hook)</td><td>Genou, par rotation</td><td>Cacher le talon, sortir le genou vite : c'est la plus dangereuse</td></tr>
<tr><td>Clé de cou</td><td>Colonne cervicale</td><td>Ne pas laisser la tête se faire enrouler</td></tr></table>
<p>La kimura porte le nom du judoka japonais Masahiko Kimura, qui a vaincu Hélio Gracie avec cette clé en 1951. Au sol, la règle d'or : <b>défendre avant que la prise soit posée</b>. Une soumission bien posée ne se défend presque plus.</p>
<h3>Des combats pour s'en souvenir</h3>
<ul><li><b>Nate Diaz contre Conor McGregor</b> (UFC 196, 5 mars 2016) : McGregor, fatigué, tente une amenée ; Diaz prend son dos et gagne par étranglement arrière au 2e round.</li>
<li><b>Khabib Nurmagomedov contre Conor McGregor</b> (UFC 229, 2018) : clé de cou au 4e round (module 7).</li></ul>
<div class="gtrap">Idée reçue dangereuse : « un vrai dur ne tape jamais ». Un étranglement bien serré fait perdre connaissance en quelques secondes ; une clé non tapée casse un coude ou un genou et peut arrêter une carrière. En compétition, si le combattant perd connaissance, l'arbitre arrête et il perd par soumission technique. Taper n'est pas une faiblesse : c'est une décision intelligente.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Distinguer étranglements et clés, et leur danger</li><li>Associer chaque soumission à sa position de départ</li><li>Donner la défense principale de chaque soumission</li><li>Analyser les soumissions célèbres de Diaz et de Khabib</li></ul>`},
/*EXOS*/
{i:"m224_01",u:224,t:"sort",d:.2,nw:"Les soumissions",q:"Classe chaque soumission : étranglement ou clé ?",bins:["Étranglement","Clé"],it:[["Étranglement arrière",0],["Clé de bras",1],["Guillotine",0],["Kimura",1],["Triangle",0],["Clé de talon",1]],w:"Sang ou os : l'étranglement coupe le sang, la clé menace l'articulation."},
{i:"m224_02",u:224,t:"story",d:.2,q:"Tom refuse de taper sur l'étranglement de Maëlle. Que lui explique-t-elle ?",sc:[{who:"Tom",txt:"Taper, c'est la honte. Je préfère résister."}],o:["« Dans quelques secondes tu dors, et tu perds quand même : tape. »","« Tu as raison, un vrai combattant ne tape jamais, quoi qu'il arrive. »","« Tape seulement quand tu as vraiment mal au bras, jamais sur le cou. »","« Résiste encore plus fort, ton cou va s'habituer à la pression. »"],a:0,w:"Un étranglement fait perdre connaissance en quelques secondes. Taper, c'est se donner le droit de revenir demain."},
{i:"m224_03",u:224,t:"fill",d:.25,q:"L'étranglement arrière s'appelle au Brésil « mata leão », c'est-à-dire le tue-___.",o:["lion","loup","taureau","tigre"],a:0,w:"Mata leão : le tue-lion. Depuis le dos, c'est la soumission la plus fréquente en MMA."},
{i:"m224_04",u:224,t:"tf",d:.25,q:"Un étranglement sanguin comprime surtout les artères carotides du cou.",a:true,w:"Le sang n'arrive plus au cerveau : perte de conscience en quelques secondes."},
{i:"m224_05",u:224,t:"match",d:.3,q:"Associe chaque soumission à sa position de départ.",p:[["Étranglement arrière","Le dos"],["Triangle","La garde"],["Guillotine","De face, sur une amenée tête basse"],["Étranglement bras-tête","Contrôle latéral ou montée"]],w:"Chaque position ouvre ses soumissions : c'est pourquoi on se bat pour les positions."},
{i:"m224_06",u:224,t:"mcq",d:.3,q:"Quelle articulation la clé de bras attaque-t-elle ?",o:["Le coude","L'épaule","Le poignet","Le genou"],a:0,w:"Le coude, en hyperextension. La kimura et l'americana attaquent l'épaule."},
{i:"m224_07",u:224,t:"story",d:.3,q:"Tom est dans la garde de Maëlle, un bras dedans, un bras dehors. Rachid crie. Pourquoi ?",sc:[{who:"Tom",txt:"Quoi, qu'est-ce que j'ai fait ?"}],o:["« Un bras dedans, un bras dehors : tu lui offres le triangle. »","« Tu dois mettre tes deux bras dehors pour frapper plus fort au sol. »","« Rien, Rachid crie toujours, ça ne veut absolument rien dire. »","« Tu dois te coucher sur elle pour qu'elle ne puisse plus bouger. »"],a:0,w:"Un bras dedans, un bras dehors : triangle. Deux dedans ou deux dehors : pas de triangle."},
{i:"m224_08",u:224,t:"tiles",d:.35,q:"Reconstitue le moyen mnémotechnique des soumissions.",a:["sang","ou","os"],dd:["peau","nerf","muscle"],w:"L'étranglement coupe le sang, la clé menace l'os et l'articulation."},
{i:"m224_09",u:224,t:"multi",d:.35,q:"Comment défendre un étranglement arrière ?",o:["Rentrer le menton","Combattre les mains avec les deux mains","Empêcher le bras de passer sous le menton","Tourner vers le côté du bras qui étrangle pour s'échapper","Lever le menton bien haut"],a:[0,1,2,3],w:"Lever le menton, c'est offrir le cou. Menton rentré et bataille des mains."},
{i:"m224_10",u:224,t:"fill",d:.35,q:"La clé d'épaule qui plie le bras derrière le dos porte le nom du judoka Masahiko ___.",o:["Kimura","Kano","Maeda","Yamamoto"],a:0,w:"Kimura, qui a battu Hélio Gracie avec cette clé en 1951."},
{i:"m224_11",u:224,t:"story",d:.4,q:"Tom demande comment McGregor a perdu contre Nate Diaz en 2016.",sc:[{who:"Tom",txt:"McGregor frappait mieux, non ?"}],o:["« Fatigué, il a tenté une amenée ; Diaz a pris son dos, étranglé. »","« Il a perdu aux points par décision unanime après cinq rounds serrés. »","« Il a été mis KO par un coup de pied haut dès le premier round. »","« Il a été disqualifié pour avoir frappé à l'arrière de la tête. »"],a:0,w:"UFC 196, 5 mars 2016 : étranglement arrière au 2e round. La fatigue pousse à des amenées mal préparées."},
{i:"m224_12",u:224,t:"tf",d:.4,q:"La clé de talon est considérée comme l'une des clés les plus dangereuses, car elle tord le genou par rotation.",a:true,w:"Les ligaments du genou cèdent souvent avant même que la douleur soit forte : on défend tôt et on tape tôt."},
{i:"m224_13",u:224,t:"mcq",d:.45,q:"Quelle est la règle d'or de la défense au sol ?",o:["Défendre avant que la prise soit posée","Attendre que la prise soit serrée pour réagir","Toujours taper dès qu'on est au sol","Ne jamais bouger pour ne rien offrir"],a:0,w:"Une soumission bien posée ne se défend presque plus. On anticipe : menton, coudes, posture."},
{i:"m224_14",u:224,t:"order",d:.45,q:"Remets dans l'ordre la façon dont Diaz a battu McGregor.",it:["McGregor, fatigué, perd de la vitesse","Il tente une amenée","Diaz renverse la situation au sol","Diaz prend le dos","Étranglement arrière : McGregor tape"],w:"UFC 196, 2016. La fatigue, une amenée désespérée, puis le dos et le mata leão."},
{i:"m224_15",u:224,t:"story",d:.45,q:"Maëlle tente une kimura sur Tom depuis la garde. Comment se défendre ?",sc:[{who:"Tom",txt:"Elle me plie le bras derrière le dos !"}],o:["« Saisis ta propre ceinture ou ton short et garde le coude collé. »","« Tends le bras bien droit pour qu'elle ne puisse plus le plier. »","« Laisse-toi tourner sur le ventre pour suivre la direction de la clé. »","« Mords-lui la jambe pour qu'elle lâche le bras, c'est efficace. »"],a:0,w:"On bloque la rotation de l'épaule en s'agrippant à soi-même. Tendre le bras offre une clé de bras ; mordre est une faute."},
{i:"m224_16",u:224,t:"match",d:.5,q:"Associe chaque clé à sa défense.",p:[["Clé de bras","Joindre ses mains, pouce vers l'extérieur"],["Kimura","Saisir sa ceinture, coude collé"],["Americana","Coudes collés au corps"],["Clé de talon","Cacher le talon, sortir le genou vite"]],w:"Chaque clé a sa porte de sortie, si on la prend assez tôt."},
{i:"m224_17",u:224,t:"fill",d:.5,q:"Si un combattant perd connaissance sur un étranglement, il perd par soumission ___.",o:["technique","volontaire","partielle","nulle"],a:0,w:"L'arbitre arrête : c'est une soumission technique. Résister n'a rien changé au résultat."},
{i:"m224_18",u:224,t:"sort",d:.55,q:"Classe chaque attitude : bonne défense ou erreur ?",bins:["Bonne défense","Erreur"],it:[["Menton rentré quand on a le dos pris",0],["Bras tendu sous la montée",1],["Posture droite dans la garde",0],["Un bras dedans, un bras dehors",1],["Taper sur une clé de talon bien posée",0]],w:"Taper à temps est aussi une bonne décision."},
{i:"m224_19",u:224,t:"story",d:.55,q:"Rappel du module 8 : Enzo plonge tête basse et Viktor encercle son cou. Que se passe-t-il ?",sc:[{who:"Enzo",txt:"Il me tient la tête sous son bras !"}],o:["« Une guillotine : passe du côté de son bras et garde le dos droit. »","« Un triangle : mets vite tes deux bras à l'intérieur de ses jambes. »","« Une kimura : saisis ton short pour bloquer la rotation de l'épaule. »","« Rien de dangereux, attends que l'arbitre vous sépare au centre. »"],a:0,w:"Plongeon tête basse, cou offert : guillotine. La défense consiste à passer du côté du bras qui étrangle."},
{i:"m224_20",u:224,t:"tf",d:.6,q:"Un vrai combattant ne doit jamais taper, même sur une clé bien posée.",a:false,w:"Idée reçue dangereuse : une clé non tapée casse l'articulation. Taper est une décision intelligente."},
{i:"m224_21",u:224,t:"multi",d:.6,q:"Quelles soumissions se prennent souvent depuis la garde ?",o:["Triangle","Clé de bras","Kimura","Guillotine","Étranglement arrière"],a:[0,1,2,3],w:"L'étranglement arrière vient du dos, pas de la garde."},
{i:"m224_22",u:224,t:"mcq",d:.65,q:"Par quelle soumission Khabib a-t-il battu McGregor ?",o:["Une clé de cou","Une clé de bras","Un triangle","Une kimura"],a:0,w:"Une clé de cou (neck crank) au 4e round de l'UFC 229, en 2018."},
{i:"m224_23",u:224,t:"story",d:.65,q:"Rappel du module 9 : Tom est sous la montée et pousse à bras tendus. Maëlle attaque. Quelle soumission risque-t-il ?",sc:[{who:"Tom",txt:"Je pousse pour qu'elle recule."}],o:["« Une clé de bras : un bras tendu, c'est un coude offert. »","« Une clé de talon : ses jambes sont juste à côté de ta tête. »","« Aucune, pousser à bras tendus est la meilleure défense. »","« Une guillotine, car tu as la tête baissée vers le sol. »"],a:0,w:"Bras tendus sous la montée : la clé de bras arrive. On fait le pont ou la crevette, coudes collés."},
{i:"m224_24",u:224,t:"tiles",d:.7,q:"Reconstitue la règle du triangle.",a:["un","bras","dedans","un","bras","dehors","triangle"],dd:["garde","deux","sol"],w:"Un bras dedans, un bras dehors : triangle. Deux dedans ou deux dehors : pas de triangle."},
{i:"m224_25",u:224,t:"fill",d:.7,q:"Une clé articulaire tord une articulation au-delà de son ___.",o:["amplitude","muscle","tendon","poids"],a:0,w:"Au-delà de son amplitude normale : douleur, puis entorse ou fracture."},
{i:"m224_26",u:224,t:"match",d:.75,q:"Associe chaque combat à sa soumission.",p:[["Diaz contre McGregor, UFC 196","Étranglement arrière"],["Khabib contre McGregor, UFC 229","Clé de cou"],["Kimura contre Hélio Gracie, 1951","Clé d'épaule, la kimura"],["Royce Gracie, UFC 1","Le JJB face aux frappeurs"]],w:"Des cas réels pour retenir chaque soumission."},
{i:"m224_27",u:224,t:"story",d:.75,q:"Tom demande pourquoi Rachid insiste sur les défenses alors qu'Enzo est boxeur.",sc:[{who:"Tom",txt:"Enzo ne va jamais au sol, lui."}],o:["« Si Viktor l'amène, il doit survivre et se relever : pas le choix. »","« Rachid a tort, un boxeur n'a jamais besoin d'apprendre le sol. »","« Pour le spectacle, les défenses au sol plaisent beaucoup au public. »","« Parce que les règles imposent de passer au moins un round au sol. »"],a:0,w:"En MMA, on ne choisit pas toujours où va le combat. Un frappeur doit savoir survivre au sol et se relever."},
{i:"m224_28",u:224,t:"sort",d:.8,q:"Classe chaque clé selon l'articulation visée.",bins:["Coude","Épaule","Genou"],it:[["Clé de bras",0],["Kimura",1],["Clé de talon",2],["Americana",1],["Clé de genou (kneebar)",2]],w:"Coude, épaule, genou : trois familles de clés à reconnaître en vidéo."},
{i:"m224_29",u:224,t:"tf",d:.8,q:"Une soumission bien posée se défend presque toujours facilement.",a:false,w:"Au contraire : c'est pourquoi on défend avant qu'elle soit posée."},
{i:"m224_30",u:224,t:"mcq",d:.85,q:"Dans la défense de la clé de bras, où doit être tourné le pouce ?",o:["Vers l'extérieur","Vers l'intérieur","Vers le sol","Peu importe"],a:0,w:"Pouce vers l'extérieur, le coude n'est plus dans l'axe de l'hyperextension. On joint aussi ses mains."},
{i:"m224_31",u:224,t:"fill",d:.85,q:"Dans le triangle, la défense principale est de garder une posture ___.",o:["droite","couchée","penchée","assise"],a:0,w:"Posture droite, et jamais un bras dedans et un bras dehors."},
{i:"m224_32",u:224,t:"story",d:.9,q:"Synthèse : Rachid demande à Tom ce qu'il a retenu des soumissions.",sc:[{who:"Rachid",txt:"Trois idées."}],o:["« Sang ou os ; défendre avant que la prise soit posée ; taper à temps. »","« Ne jamais taper ; toujours tendre le bras ; résister plus fort que lui. »","« Aller au sol le plus souvent possible, même sans rien connaître. »","« Les soumissions n'existent qu'en JJB, jamais en MMA professionnel. »"],a:0,w:"Deux familles, des défenses précoces, et l'intelligence de taper."}
