/*UNIT*/
{id:226,c:"MMA",n:"Module 12",t:"Chaque art a son trou : comparer les disciplines",col:"--red",ic:"🧬",guide:`
<h3>Le tableau de Rachid</h3>
<div class="gstory">Dimanche, jour de repos, Rachid t'invite à boire un café sur le Vieux-Port. Il sort un carnet usé : « Quand j'analyse un adversaire, je commence toujours par une question : d'où il vient ? Un boxeur, un lutteur, un karatéka, un judoka ne pensent pas pareil. Chacun a une force énorme et un trou. Mon travail, c'est de trouver le trou. » Il te tend le carnet : huit disciplines, deux colonnes, « ce qui marche » et « ce qui manque ». « Apprends-le par cœur. C'est la moitié de mon métier. »</div>
<h3>Les disciplines de base du MMA</h3>
<table><tr><th>Discipline</th><th>Force en MMA</th><th>Trou habituel</th><th>Exemple</th></tr>
<tr><td><b>Boxe anglaise</b></td><td>Mains, défense de tête, contres</td><td>Coups de pied, défense de lutte</td><td>Enzo</td></tr>
<tr><td><b>Muay Thaï</b></td><td>Huit armes, low kicks, clinch</td><td>Garde très de face, jambe avant exposée aux amenées</td><td>Somchai</td></tr>
<tr><td><b>Kick-boxing</b></td><td>Enchaînements rapides poings et pieds</td><td>Clinch court, sol</td><td>Alex Pereira</td></tr>
<tr><td><b>Karaté</b></td><td>Distance, entrées et sorties éclair, contres</td><td>Garde de profil sensible aux coups de pied bas et aux amenées si mal adaptée</td><td>Lyoto Machida, Georges St-Pierre (base karaté)</td></tr>
<tr><td><b>Taekwondo</b></td><td>Coups de pied rapides et variés</td><td>Mains basses, lutte</td><td>Plusieurs frappeurs de l'UFC</td></tr>
<tr><td><b>Lutte</b></td><td>Choisir où se passe le combat, contrôle</td><td>Frappe debout au début de carrière</td><td>Lina</td></tr>
<tr><td><b>Judo</b></td><td>Projections en clinch, équilibre</td><td>Sans veste, les prises changent</td><td>Ronda Rousey (bronze olympique en 2008)</td></tr>
<tr><td><b>Jiu-jitsu brésilien</b></td><td>Soumissions, jeu de jambes au sol</td><td>Amenées et frappe</td><td>Royce Gracie, Maëlle</td></tr>
<tr><td><b>Sambo</b></td><td>Projections plus sol, pression écrasante</td><td>Peu, mais souvent moins de frappe variée</td><td>Khabib Nurmagomedov, Fedor Emelianenko</td></tr></table>
<div class="gmnemo"><b>« Chaque art a son trou. »</b> Et le test du combattant complet : <b>« Trois cases : debout, clinch, sol »</b>. Un combattant est dangereux si on ne peut pas lui trouver une case vide.</div>
<h3>Ce qui passe tel quel, ce qui doit changer</h3>
<table><tr><th>Passe tel quel</th><th>Doit changer</th></tr>
<tr><td>Le jab, le direct, les contres de la boxe</td><td>Plonger sous les coups (genoux et amenées)</td></tr>
<tr><td>Le low kick, le teep, les coudes du Muay Thaï</td><td>Les gros coups de pied lents (attrapés)</td></tr>
<tr><td>Les amenées de lutte</td><td>Plonger de loin sans préparation</td></tr>
<tr><td>Les positions et soumissions du JJB</td><td>Tirer la garde, rester passif sur le dos</td></tr>
<tr><td>Les projections du judo</td><td>Les prises au kimono, absentes en MMA</td></tr></table>
<h3>Lire un adversaire par sa base</h3>
<ul><li>Face à un <b>boxeur</b> : lui imposer les coups de pied et la lutte.</li>
<li>Face à un <b>lutteur</b> : défendre les amenées, rester au centre, le faire payer à chaque entrée.</li>
<li>Face à un <b>spécialiste du JJB</b> : rester debout, ou au sol rester en haut sans s'engager dans ses jambes.</li>
<li>Face à un <b>karatéka</b> : couper la cage pour lui retirer l'espace dont il a besoin.</li></ul>
<div class="gtrap">Nuance essentielle : dans le MMA d'aujourd'hui, presque tous les combattants de haut niveau sont complets. Leur « base » reste visible dans leurs réflexes, surtout sous la fatigue et la pression, mais il ne faut pas les réduire à une étiquette. Un lutteur peut avoir une excellente boxe. L'analyse commence par la base, puis vérifie en vidéo.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Donner la force et le trou de chaque discipline</li><li>Dire ce qui passe tel quel en MMA et ce qui doit être adapté</li><li>Proposer une idée de plan selon la base d'un adversaire</li><li>Nuancer une analyse trop rapide fondée sur une étiquette</li></ul>`},
/*EXOS*/
{i:"m226_01",u:226,t:"match",d:.2,nw:"Comparer les disciplines",q:"Associe chaque discipline à sa force principale en MMA.",p:[["Boxe anglaise","Mains et contres"],["Lutte","Choisir où se passe le combat"],["JJB","Soumissions au sol"],["Muay Thaï","Huit armes et clinch"]],w:"Chaque art a son trou, mais aussi sa force."},
{i:"m226_02",u:226,t:"story",d:.2,q:"Rachid demande par quoi commencer l'analyse d'un nouvel adversaire.",sc:[{who:"Rachid",txt:"Première question que tu te poses ?"}],o:["« D'où il vient : sa base montre sa force et son trou. »","« Combien d'abonnés il a sur les réseaux, ça dit tout de lui. »","« Quelle est la couleur de son short, pour savoir son camp. »","« Combien il pèse le jour du combat, rien d'autre ne compte. »"],a:0,w:"La base d'un combattant révèle ses réflexes, surtout sous la fatigue."},
{i:"m226_03",u:226,t:"fill",d:.25,q:"Ronda Rousey a remporté une médaille de bronze olympique en 2008 en ___.",o:["judo","lutte","boxe","taekwondo"],a:0,w:"En judo, d'où ses projections en clinch et ses clés de bras. Le vale tudo brésilien opposait déjà ces disciplines."},
{i:"m226_04",u:226,t:"tf",d:.25,q:"Un spécialiste de Muay Thaï a souvent une jambe avant exposée aux amenées en MMA.",a:true,w:"Garde très de face, poids sur la jambe arrière, jambe avant légère : un lutteur la saisit facilement."},
{i:"m226_05",u:226,t:"sort",d:.3,q:"Classe chaque élément : passe tel quel en MMA ou doit être adapté ?",bins:["Passe tel quel","Doit être adapté"],it:[["Le jab de boxe",0],["Plonger sous les crochets",1],["Le low kick",0],["Tirer la garde",1],["Les amenées de lutte",0],["Les prises au kimono",1]],w:"Les armes efficaces restent ; les habitudes liées aux règles d'origine changent."},
{i:"m226_06",u:226,t:"mcq",d:.3,q:"Face à un spécialiste du JJB, quelle idée de plan est la plus logique ?",o:["Debout, ou dessus hors de ses jambes","Le suivre au sol, dans sa garde fermée","Tirer soi-même la garde dès le début","Plonger sur ses jambes, tête basse"],a:0,w:"On le prive de son terrain : debout, ou au-dessus en restant hors de ses jambes."},
{i:"m226_07",u:226,t:"story",d:.3,q:"Tom veut affronter un karatéka qui tourne sans arrêt et entre-sort très vite. Que lui conseilles-tu ?",sc:[{who:"Tom",txt:"Il est insaisissable, il rentre et ressort."}],o:["« Couper la cage pour lui retirer l'espace dont il a besoin. »","« Le poursuivre en ligne droite jusqu'à ce qu'il se fatigue enfin. »","« Rester immobile au centre, les mains baissées, pour l'attirer. »","« Tourner encore plus vite que lui, en sens inverse de sa rotation. »"],a:0,w:"Le karaté a besoin d'espace. Couper la cage (module 3) le lui retire."},
{i:"m226_08",u:226,t:"tiles",d:.35,q:"Reconstitue le principe de Rachid.",a:["chaque","art","a","son","trou"],dd:["prix","secret","roi"],w:"Chaque discipline a une force énorme et une lacune : le travail de l'analyste, c'est de la trouver."},
{i:"m226_09",u:226,t:"multi",d:.35,q:"Quels combattants viennent d'une base sambo ou lutte du Daghestan et de Russie ?",o:["Khabib Nurmagomedov","Fedor Emelianenko","Islam Makhachev","Des lutteurs à la pression écrasante","Conor McGregor"],a:[0,1,2,3],w:"McGregor vient de la boxe et du karaté. Les autres incarnent la pression de la lutte et du sambo."},
{i:"m226_10",u:226,t:"fill",d:.35,q:"Le test du combattant complet : trois cases, debout, clinch et ___.",o:["sol","cage","cardio","mental"],a:0,w:"Un combattant est dangereux si on ne peut pas lui trouver une case vide."},
{i:"m226_11",u:226,t:"story",d:.4,q:"Viktor est lutteur. Enzo est boxeur. Quel plan général pour Enzo ?",sc:[{who:"Enzo",txt:"Je fais quoi contre un lutteur ?"}],o:["« Défendre les amenées, rester au centre, le faire payer à chaque entrée. »","« Aller au sol avec lui pour lui prouver que tu n'as pas peur de sa lutte. »","« Le laisser t'amener pour le fatiguer au sol pendant tout le combat. »","« Changer toute ta garde pour une garde de lutteur, sans frapper. »"],a:0,w:"Contre un lutteur : sprawl and brawl, centre, et contres à chaque plongeon."},
{i:"m226_12",u:226,t:"match",d:.4,q:"Associe chaque combattant à sa base.",p:[["Royce Gracie","Jiu-jitsu brésilien"],["Ronda Rousey","Judo"],["Lyoto Machida","Karaté"],["Alex Pereira","Kick-boxing"]],w:"Connaître les bases des grands noms aide à reconnaître les styles."},
{i:"m226_13",u:226,t:"tf",d:.4,q:"Dans le MMA de haut niveau actuel, la plupart des combattants n'ont qu'une seule discipline.",a:false,w:"Presque tous sont complets ; leur base reste visible dans leurs réflexes, surtout sous la fatigue."},
{i:"m226_14",u:226,t:"mcq",d:.45,q:"Quel est le trou habituel d'un boxeur anglais en MMA ?",o:["Coups de pied et défense de lutte","La vitesse de ses mains","La défense de tête en esquive","Les contres en crochet"],a:0,w:"Ses mains sont une force ; ses jambes et sa défense de lutte sont souvent à construire."},
{i:"m226_15",u:226,t:"story",d:.45,q:"Un spécialiste du taekwondo lance des coups de pied très rapides mais garde les mains basses. Quel plan ?",sc:[{who:"Rachid",txt:"Il a des jambes de feu, et c'est tout."}],o:["« Réduire la distance, le forcer à boxer et menacer l'amenée. »","« Rester loin pour échanger des coups de pied avec lui toute la soirée. »","« Tourner le dos pour éviter ses coups de pied tournants rapides. »","« Lui laisser le centre pour qu'il se fatigue à force de frapper. »"],a:0,w:"Chaque art a son trou : mains basses et lutte faible. On le sort de sa distance."},
{i:"m226_16",u:226,t:"sort",d:.5,q:"Classe chaque discipline : surtout debout ou surtout au sol ?",bins:["Surtout debout","Surtout au sol"],it:[["Boxe",0],["JJB",1],["Muay Thaï",0],["Karaté",0],["Sambo, avec clés de jambe",1]],w:"Le sambo et le JJB brillent au sol ; boxe, Muay Thaï et karaté debout. La lutte fait le lien."},
{i:"m226_17",u:226,t:"fill",d:.5,q:"Face à un lutteur, on reste au ___ de l'octogone.",o:["centre","bord","coin","grillage"],a:0,w:"Le centre pour moi : contre la cage, les amenées passent mieux."},
{i:"m226_18",u:226,t:"multi",d:.55,q:"Qu'est-ce qui doit changer quand un judoka passe au MMA ?",o:["Les prises au kimono","La garde face aux coups","La défense des frappes au sol","La gestion de la distance de frappe","Ses projections en clinch"],a:[0,1,2,3],w:"Ses projections restent une arme ; le reste doit s'adapter à l'absence de veste et aux coups."},
{i:"m226_19",u:226,t:"story",d:.55,q:"Rappel du module 11 : Maëlle, spécialiste du JJB, veut tirer la garde contre une frappeuse. Que dit Rachid ?",sc:[{who:"Maëlle",txt:"Si je la tire au sol, je la soumets."}],o:["« Tirer la garde t'expose aux frappes : amène-la par la lutte. »","« Parfait, tire la garde dès le premier échange, c'est imparable. »","« Ne va jamais au sol, ton JJB ne sert à rien en MMA moderne. »","« Tire la garde, mais seulement dans la dernière minute du round. »"],a:0,w:"Mieux vaut amener et arriver dessus que s'offrir sur le dos."},
{i:"m226_20",u:226,t:"tf",d:.6,q:"Georges St-Pierre avait une base de karaté avant de devenir un lutteur redoutable en MMA.",a:true,w:"Karaté Kyokushin, puis lutte et JJB : l'exemple du combattant complet."},
{i:"m226_21",u:226,t:"mcq",d:.6,q:"Pourquoi la base d'un combattant ressort-elle surtout en fin de combat ?",o:["La fatigue ramène les réflexes profonds","Les règles changent au 3e round","Le public l'exige en criant fort","Les gants deviennent plus lourds"],a:0,w:"Sous la fatigue et la pression, on revient à ce qu'on a répété des milliers de fois."},
{i:"m226_22",u:226,t:"match",d:.65,q:"Associe chaque base adverse à l'idée de plan.",p:[["Boxeur","Coups de pied et lutte"],["Lutteur","Défense d'amenée, centre, contres"],["Spécialiste du JJB","Rester debout ou dessus"],["Karatéka","Couper la cage"]],w:"La base oriente le plan ; la vidéo le confirme."},
{i:"m226_23",u:226,t:"story",d:.65,q:"Tom classe un adversaire : « C'est un lutteur, il ne sait pas boxer. » Que lui réponds-tu ?",sc:[{who:"Tom",txt:"Un lutteur, donc zéro boxe."}],o:["« Méfie-toi des étiquettes : vérifie en vidéo, des lutteurs boxent bien. »","« Exact, un lutteur ne donne jamais de coups de poing, c'est son style. »","« Oui, et un boxeur ne peut jamais apprendre la lutte non plus. »","« Il faut toujours croire l'étiquette donnée par les commentateurs. »"],a:0,w:"La base oriente, la vidéo vérifie. Le MMA moderne fabrique des combattants complets."},
{i:"m226_24",u:226,t:"tiles",d:.7,q:"Reconstitue le test du combattant complet.",a:["trois","cases","debout","clinch","sol"],dd:["cage","cardio","gants"],w:"Un combattant dangereux n'a pas de case vide."},
{i:"m226_25",u:226,t:"sort",d:.7,q:"Classe chaque trou selon la discipline qui l'a souvent.",bins:["Boxe","JJB","Muay Thaï"],it:[["Défense de lutte faible",0],["Amenées et frappe faibles",1],["Jambe avant exposée aux amenées",2],["Pas de coups de pied",0],["Tendance à tirer la garde",1]],w:"Chaque art a son trou. Le travail de l'analyste est de trouver ce trou et de l'exploiter."},
{i:"m226_26",u:226,t:"fill",d:.75,q:"Le kick-boxing apporte des enchaînements rapides, mais son trou habituel est le clinch court et le ___.",o:["sol","jab","cardio","low kick"],a:0,w:"Poings et pieds, peu de clinch, pas de sol : il faut compléter."},
{i:"m226_27",u:226,t:"story",d:.75,q:"Rappel du module 7 : pourquoi Ngannou contre Gane illustre bien ce module ?",sc:[{who:"Tom",txt:"C'était un frappeur contre un frappeur, non ?"}],o:["« Ngannou a utilisé la lutte là où Gane l'attendait debout. »","« C'était un combat de JJB pur, sans aucun échange debout ni frappe. »","« Gane a gagné par KO au premier round, sans aucune surprise. »","« Ngannou a refusé toute lutte et a gagné uniquement debout. »"],a:0,w:"Un combattant qui remplit une case inattendue surprend l'adversaire qui l'avait étiqueté."},
{i:"m226_28",u:226,t:"tf",d:.8,q:"Selon ce module, le judo transfère ses projections en clinch, mais doit s'adapter à l'absence de kimono.",a:true,w:"Pas de revers ni de manches : les saisies changent (bras, nuque, ceinture), les projections restent."},
{i:"m226_29",u:226,t:"multi",d:.8,q:"Quelles questions poser pour analyser la base d'un adversaire ?",o:["Quelle est sa discipline d'origine ?","Que fait-il quand il est fatigué ?","Quelle case semble vide ?","Qu'a-t-il amélioré récemment ?","Quelle est sa couleur préférée ?"],a:[0,1,2,3],w:"La base, les réflexes sous fatigue, la case vide, l'évolution récente : quatre questions d'analyste."},
{i:"m226_30",u:226,t:"mcq",d:.85,q:"Que dit la règle des trois cases ?",o:["Pas de case vide : il est dangereux","Il faut gagner trois rounds sur cinq","Il faut maîtriser trois disciplines de frappe","Il faut trois entraîneurs différents"],a:0,w:"Debout, clinch, sol : un combattant complet ne laisse aucune case vide à exploiter."},
{i:"m226_31",u:226,t:"fill",d:.85,q:"L'analyse commence par la base, puis se vérifie en ___.",o:["vidéo","conférence","salle de sport","rêve"],a:0,w:"La base oriente, la vidéo confirme ou corrige."},
{i:"m226_32",u:226,t:"story",d:.9,q:"Synthèse : Rachid reprend son carnet et te demande la règle de ce module.",sc:[{who:"Rachid",txt:"Si tu ne retiens qu'une chose ?"}],o:["« Trouve la base, cherche son trou, puis vérifie en vidéo. »","« Méprise toutes les autres disciplines, seule la tienne compte vraiment. »","« Ne regarde jamais les vidéos, l'étiquette de départ suffit toujours. »","« Chaque discipline est parfaite, il n'y a jamais de trou à chercher. »"],a:0,w:"Chaque art a son trou ; trois cases ; la base oriente, la vidéo vérifie."}
