/*UNIT*/
{id:227,c:"MMA",n:"Module 13",t:"Stratégie : plan de combat, rounds, cardio et coin",col:"--red",ic:"🧠",guide:`
<h3>Le plan sur le tableau blanc</h3>
<div class="gstory">Dix jours avant le combat, Rachid réunit l'équipe autour du tableau blanc : Enzo, Lina qui joue le rôle de Viktor en sparring, Maëlle, et toi, l'analyste. En haut du tableau : « Gagner 2 rounds sur 3. » En dessous : plan A, plan B, et « ce qu'on dit à la minute de repos ». Rachid : « Un combat, ce n'est pas une bagarre. C'est quinze minutes de décisions. Celui qui a le meilleur plan et qui s'y tient quand il a mal gagne souvent contre plus fort que lui. »</div>
<h3>Comment les juges notent (règles unifiées)</h3>
<table><tr><th>Ordre</th><th>Critère</th><th>Explication</th></tr>
<tr><td>1</td><td><b>Impact</b> : frappe et lutte efficaces</td><td>Les dégâts, les coups qui secouent, les amenées suivies d'action, les tentatives de soumission sérieuses</td></tr>
<tr><td>2</td><td><b>Agressivité efficace</b></td><td>Seulement si le premier critère est égal : celui qui cherche à finir, pas celui qui avance sans toucher</td></tr>
<tr><td>3</td><td><b>Contrôle de l'espace</b></td><td>Seulement si les deux premiers sont égaux : qui dicte où et comment on se bat</td></tr></table>
<div class="gmnemo"><b>« I.A.C. : Impact, Agressivité, Contrôle. »</b> Dans cet ordre, et chaque critère ne sert que si le précédent est égal. Pour le coin : <b>« Deux consignes, pas dix. »</b></div>
<p>Un <b>10-8</b> récompense un round où l'un domine nettement par l'impact, la domination et la durée. Un 10-7 est rarissime.</p>
<h3>Construire un plan de combat</h3>
<ol><li><b>Analyser</b> : la base de l'adversaire, son trou, ses habitudes (module 12).</li>
<li><b>Choisir la phase</b> où l'on est le plus fort (distance, clinch ou sol) et celle à éviter.</li>
<li><b>Plan A</b> : la façon principale de gagner. <b>Plan B</b> : ce qu'on fait si le plan A ne passe pas.</li>
<li><b>Gérer les rounds</b> : dans un combat en 3 rounds, il faut en gagner 2. Mené après deux rounds, il faut finir ou gagner nettement le dernier.</li></ol>
<div class="gsvg-wrap"><svg class='gsvg' viewBox='0 0 200 140' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='20' y='40' width='50' height='40' rx='8' fill='var(--blue)'/><text x='45' y='64' font-size='10' fill='var(--bg)' text-anchor='middle' font-weight='700'>Distance</text><rect x='75' y='40' width='50' height='40' rx='8' fill='var(--gold)'/><text x='100' y='64' font-size='10' fill='var(--bg)' text-anchor='middle' font-weight='700'>Clinch</text><rect x='130' y='40' width='50' height='40' rx='8' fill='var(--red)'/><text x='155' y='64' font-size='10' fill='var(--bg)' text-anchor='middle' font-weight='700'>Sol</text><path d='M70 60 L75 60 M125 60 L130 60' stroke='var(--txt)' stroke-width='2'/><path d='M45 90 Q100 130 155 90' fill='none' stroke='var(--dim)' stroke-width='2' stroke-dasharray='4 3'/><text x='100' y='126' font-size='9' fill='var(--dim)' text-anchor='middle' font-weight='600'>amenée au sol directe</text><path d='M155 30 Q100 0 45 30' fill='none' stroke='var(--green)' stroke-width='2'/><text x='100' y='18' font-size='9' fill='var(--green)' text-anchor='middle' font-weight='600'>se relever</text></svg></div>
<h3>Les profils stratégiques</h3>
<table><tr><th>Profil</th><th>Principe</th><th>Comment le battre</th></tr>
<tr><td><b>Presseur</b></td><td>Avance sans cesse, pousse vers la cage</td><td>Déplacements en angle, contres, couper sa ligne</td></tr>
<tr><td><b>Contreur</b></td><td>Attend l'attaque pour contrer</td><td>Feintes, pression calme, attaques au corps et aux jambes</td></tr>
<tr><td><b>Volume</b></td><td>Beaucoup de coups, peu de puissance</td><td>Couper le rythme, clinch, gros contres</td></tr>
<tr><td><b>Puissance</b></td><td>Peu de coups, chacun dangereux</td><td>Rester mobile, l'user, gagner aux points</td></tr></table>
<h3>Le cardio et la pesée</h3>
<ul><li>Le MMA alterne des <b>efforts explosifs</b> (amenées, échanges) et des phases plus calmes. Le lutteur qui force les amenées fatigue vite s'il échoue.</li>
<li>La fatigue fait baisser les mains, ralentit le sprawl et rend les décisions mauvaises : Diaz contre McGregor (module 10).</li>
<li>Une <b>perte de poids brutale</b> avant la pesée (déshydratation) peut réduire le cardio et la résistance aux coups.</li></ul>
<h3>La minute de repos</h3>
<p>Une minute, c'est très court. Le coin donne de l'eau, fait respirer, pose la glace et donne <b>deux consignes claires</b> au maximum (« Tourne vers ta gauche. Calf kick quand il avance. »). Un coin qui crie dix choses n'en fait passer aucune. Le coin peut aussi <b>arrêter le combat</b> s'il juge son combattant en danger (TKO).</p>
<div class="gtrap">Idée reçue : « l'agressivité gagne les rounds ». Non : avancer sans toucher n'est pas de l'agressivité efficace. Les juges regardent d'abord l'<b>impact</b>. Un combattant qui recule mais touche plus fort et plus souvent peut gagner le round.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Appliquer les critères I.A.C. dans l'ordre</li><li>Construire un plan A et un plan B</li><li>Reconnaître les profils stratégiques et proposer une réponse</li><li>Donner des consignes utiles à la minute de repos</li></ul>`},
/*EXOS*/
{i:"m227_01",u:227,t:"order",d:.2,nw:"Les critères des juges",q:"Remets dans l'ordre les critères des juges.",it:["Impact (frappe et lutte efficaces)","Agressivité efficace","Contrôle de l'espace"],w:"I.A.C. : chaque critère ne sert que si le précédent est égal."},
{i:"m227_02",u:227,t:"story",d:.2,q:"Tom pense que Viktor a gagné le round « parce qu'il a avancé tout le temps ». Enzo, lui, a touché plus fort. Qu'en dis-tu ?",sc:[{who:"Tom",txt:"Il était plus agressif, donc il gagne."}],o:["« L'impact passe avant : si Enzo a touché plus fort, il gagne le round. »","« Tom a raison, celui qui avance gagne toujours, peu importe les coups. »","« Le round est forcément nul, car chacun a fait quelque chose de bien. »","« Viktor gagne, car les juges préfèrent toujours le plus lourd. »"],a:0,w:"Avancer sans toucher n'est pas de l'agressivité efficace. L'impact vient en premier."},
{i:"m227_03",u:227,t:"fill",d:.25,q:"Dans un combat en 3 rounds, il faut gagner au moins ___ rounds pour l'emporter aux points.",o:["2","1","3","4"],a:0,w:"2 sur 3 : d'où l'importance de ne pas « donner » un round en observant trop."},
{i:"m227_04",u:227,t:"tf",d:.25,q:"Un coin qui donne dix consignes pendant la minute de repos aide mieux son combattant.",a:false,w:"Deux consignes, pas dix. Un combattant épuisé n'en retient que deux."},
{i:"m227_05",u:227,t:"mcq",d:.3,q:"Genoux et coudes se jouent dans la zone marquée d'un point d'interrogation. Laquelle ?",svg:"<svg viewBox='0 0 200 195' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='20' y='20' width='160' height='34' rx='8' fill='var(--blue)' opacity='.25'/><text x='28' y='35' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Longue</text><rect x='20' y='62' width='130' height='34' rx='8' fill='var(--green)' opacity='.25'/><text x='28' y='77' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Moyenne</text><rect x='20' y='104' width='100' height='34' rx='8' fill='var(--gold)' opacity='1'/><text x='28' y='119' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>?</text><rect x='20' y='146' width='70' height='34' rx='8' fill='var(--red)' opacity='.25'/><text x='28' y='161' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Sol</text></svg>",o:["Courte : clinch et coudes","Longue : pieds et teep","Moyenne : les poings","Sol : lutte et JJB"],a:0,w:"La distance courte : clinch, genoux, coudes. De la longue au sol : pieds, poings, clinch, sol."},
{i:"m227_06",u:227,t:"match",d:.3,q:"Associe chaque profil à la façon de le battre.",p:[["Presseur","Angles et contres"],["Contreur","Feintes et attaques au corps"],["Volume","Casser le rythme, clinch"],["Puissance","Mobilité et points"]],w:"Chaque profil a sa réponse. Aucun profil n'est invincible : chacun a son antidote."},
{i:"m227_07",u:227,t:"story",d:.3,q:"Enzo est mené 2 rounds à 0 dans un combat en 3 rounds. Que lui dit Rachid avant le dernier ?",sc:[{who:"Enzo",txt:"Je fais quoi, là ?"}],o:["« Il te faut la finition : prends plus de risques pour le mettre KO. »","« Rien ne change, reste prudent, les juges te donneront le combat. »","« Laisse-toi amener au sol pour te reposer pendant ce dernier round. »","« Abandonne tout de suite, il n'y a plus aucune chance de gagner. »"],a:0,w:"Mené 0-2 en 3 rounds, gagner le dernier round ne suffit pas : il faut finir."},
{i:"m227_08",u:227,t:"tiles",d:.35,q:"Reconstitue les critères des juges dans l'ordre.",a:["impact","agressivité","contrôle"],dd:["style","public","poids"],w:"I.A.C. Impact d'abord : un coup qui fait mal pèse plus que dix coups sans effet."},
{i:"m227_09",u:227,t:"multi",d:.35,q:"Que fait-on pendant la minute de repos ?",o:["Boire un peu d'eau","Respirer et se calmer","Recevoir deux consignes claires","Se faire soigner une coupure","Refaire tout le plan de A à Z"],a:[0,1,2,3],w:"Une minute, c'est court : on simplifie, on ne refait pas tout."},
{i:"m227_10",u:227,t:"fill",d:.35,q:"Un round où un combattant domine nettement par l'impact, la domination et la durée peut valoir ___.",o:["10-8","10-9","10-10","9-9"],a:0,w:"10-8. Le 10-7 est rarissime. Il faut une domination nette par l'impact et la durée."},
{i:"m227_11",u:227,t:"story",d:.4,q:"Viktor est un presseur qui avance sans cesse. Quel plan pour Enzo ?",sc:[{who:"Rachid",txt:"Il va marcher sur toi pendant quinze minutes."}],o:["« Sortir en angle, contrer à chaque entrée, et lui couper la ligne. »","« Reculer tout droit vers la cage pour l'épuiser à force de le suivre. »","« Avancer aussi fort que lui pour gagner le centre à tout prix. »","« S'arrêter au milieu, les mains baissées, pour le tromper. »"],a:0,w:"Contre un presseur : angles, contres, et ne jamais lui offrir la cage."},
{i:"m227_12",u:227,t:"tf",d:.4,q:"L'agressivité efficace n'est regardée que si l'impact est égal entre les deux combattants.",a:true,w:"C'est l'ordre I.A.C. : chaque critère départage seulement si le précédent est égal."},
{i:"m227_13",u:227,t:"mcq",d:.45,q:"Qu'est-ce qu'un plan B ?",o:["Ce qu'on fait si le plan A échoue","Un plan pour un round bonus","Un plan pour gêner le coin adverse","Un plan de repli après le combat"],a:0,w:"Si l'amenée ne passe pas, si la frappe ne touche pas : on a préparé une autre voie."},
{i:"m227_14",u:227,t:"sort",d:.45,q:"Classe chaque action : impact ou simple apparence d'agressivité ?",bins:["Impact","Apparence"],it:[["Un crochet qui fait chanceler",0],["Avancer sans frapper",1],["Une amenée suivie de coups",0],["Crier en levant les bras",1],["Une tentative d'étranglement sérieuse",0]],w:"Les juges notent ce qui fait des dégâts ou met en danger."},
{i:"m227_15",u:227,t:"story",d:.45,q:"Enzo doit perdre 5 kg en trois jours par déshydratation. Rachid refuse. Pourquoi ?",sc:[{who:"Enzo",txt:"Tout le monde fait ça, non ?"}],o:["« Une déshydratation brutale réduit le cardio et le menton. »","« Parce que perdre du poids est interdit par toutes les fédérations. »","« Parce que 5 kg, ce n'est pas assez, il faut en perdre dix au moins. »","« Parce que la pesée n'a aucune importance pour un premier combat. »"],a:0,w:"Un cut brutal fragilise : cardio, menton, lucidité. On prépare le poids sur des semaines."},
{i:"m227_16",u:227,t:"mcq",d:.5,q:"Le teep et le high kick vivent dans la zone marquée. Laquelle ?",svg:"<svg viewBox='0 0 200 195' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='20' y='20' width='160' height='34' rx='8' fill='var(--blue)' opacity='1'/><text x='28' y='35' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>?</text><rect x='20' y='62' width='130' height='34' rx='8' fill='var(--green)' opacity='.25'/><text x='28' y='77' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Moyenne</text><rect x='20' y='104' width='100' height='34' rx='8' fill='var(--gold)' opacity='.25'/><text x='28' y='119' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Courte</text><rect x='20' y='146' width='70' height='34' rx='8' fill='var(--red)' opacity='.25'/><text x='28' y='161' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Sol</text></svg>",o:["Longue : pieds et teep","Moyenne : poings","Courte : clinch","Sol : lutte et soumissions"],a:0,w:"La distance longue, celle des coups de pied et du teep."},
{i:"m227_17",u:227,t:"match",d:.5,q:"Associe chaque critère à un exemple.",p:[["Impact","Un coup qui fait tomber"],["Agressivité efficace","Chercher la finition en touchant"],["Contrôle de l'espace","Dicter où se passe le combat"],["10-8","Domination nette sur tout le round"]],w:"Savoir noter un round, c'est savoir conseiller un combattant."},
{i:"m227_18",u:227,t:"story",d:.55,q:"Rappel du module 10 : pourquoi la fatigue a-t-elle coûté cher à McGregor contre Diaz ?",sc:[{who:"Tom",txt:"Il était juste fatigué, ce n'est pas grave ?"}],o:["« Fatigué, il a tenté une amenée mal préparée et a offert son dos. »","« La fatigue n'a joué aucun rôle, il a perdu par pur hasard. »","« Il a gagné ce combat-là, c'est le suivant qu'il a perdu. »","« Il a été disqualifié pour avoir quitté la cage pendant le round. »"],a:0,w:"La fatigue rend les décisions mauvaises : amenée désespérée, dos donné, étranglement."},
{i:"m227_19",u:227,t:"fill",d:.55,q:"Face à un contreur qui attend, on utilise les ___ pour le faire réagir.",o:["feintes","sprawls","clinchs","prières"],a:0,w:"Les feintes provoquent sa réaction ; on attaque ensuite le corps et les jambes, moins faciles à contrer."},
{i:"m227_20",u:227,t:"tf",d:.6,q:"Le coin peut arrêter le combat s'il juge son combattant en danger.",a:true,w:"C'est un TKO. Protéger son combattant fait partie du rôle du coin."},
{i:"m227_21",u:227,t:"multi",d:.6,q:"Quelles sont les étapes d'un plan de combat ?",o:["Analyser l'adversaire","Choisir la phase où l'on est le plus fort","Préparer un plan A et un plan B","Gérer les rounds","Improviser tout le soir du combat"],a:[0,1,2,3],w:"Un plan se prépare ; l'improvisation n'est que l'ajustement du plan."},
{i:"m227_22",u:227,t:"mcq",d:.65,q:"Maëlle est la reine de la zone marquée. Laquelle ?",svg:"<svg viewBox='0 0 200 195' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='20' y='20' width='160' height='34' rx='8' fill='var(--blue)' opacity='.25'/><text x='28' y='35' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Longue</text><rect x='20' y='62' width='130' height='34' rx='8' fill='var(--green)' opacity='.25'/><text x='28' y='77' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Moyenne</text><rect x='20' y='104' width='100' height='34' rx='8' fill='var(--gold)' opacity='.25'/><text x='28' y='119' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Courte</text><rect x='20' y='146' width='70' height='34' rx='8' fill='var(--red)' opacity='1'/><text x='28' y='161' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>?</text></svg>",o:["Le sol : lutte et JJB","La distance longue","La distance moyenne","Le clinch contre la cage"],a:0,w:"Le sol, dernière phase, où la lutte et le JJB dominent."},
{i:"m227_23",u:227,t:"story",d:.65,q:"À la minute de repos, quelles consignes Rachid donne-t-il à Enzo, qui a perdu le 1er round contre la cage ?",sc:[{who:"Rachid",txt:"Deux choses, pas plus."}],o:["« Tourne vers ta gauche au lieu de reculer ; calf kick dès qu'il avance. »","« Fais tout mieux, sois plus fort, plus rapide, et frappe plus souvent. »","« Change entièrement de style et deviens lutteur pour le prochain round. »","« Ne pense à rien, fais comme tu le sens et amuse-toi bien. »"],a:0,w:"Deux consignes, concrètes et exécutables. Pas de liste, pas de généralités."},
{i:"m227_24",u:227,t:"sort",d:.7,q:"Classe chaque consigne de coin : utile ou inutile ?",bins:["Utile","Inutile"],it:[["« Jab au corps, puis sors à droite »",0],["« Sois meilleur ! »",1],["« Check ses low kicks »",0],["« Fais tout ! »",1],["« Reste au centre »",0]],w:"Une bonne consigne dit quoi faire, où et quand."},
{i:"m227_25",u:227,t:"fill",d:.7,q:"Le profil qui envoie beaucoup de coups, mais peu puissants, est un combattant de ___.",o:["volume","puissance","contre","lutte"],a:0,w:"On le bat en cassant son rythme, en le clinchant, et par de gros contres."},
{i:"m227_26",u:227,t:"story",d:.75,q:"Rappel du module 12 : Viktor est lutteur et presseur. Quel plan A et plan B pour Enzo ?",sc:[{who:"Rachid",txt:"Plan A et plan B, en une phrase chacun."}],o:["« A : frapper au centre, défendre la lutte ; B : au sol, se relever vite. »","« A : l'amener au sol ; B : rester au sol le plus longtemps possible. »","« A : le laisser presser ; B : le laisser encore plus presser. »","« A : ne pas avoir de plan ; B : improviser selon l'humeur du jour. »"],a:0,w:"Le plan A exploite la force d'Enzo ; le plan B limite les dégâts si la lutte passe."},
{i:"m227_27",u:227,t:"tiles",d:.75,q:"Reconstitue la règle du coin.",a:["deux","consignes","pas","dix"],dd:["cent","cris","jamais"],w:"Un combattant épuisé ne retient que deux consignes."},
{i:"m227_28",u:227,t:"tf",d:.8,q:"Un combattant qui recule peut gagner un round s'il touche plus fort et plus souvent.",a:true,w:"L'impact vient avant tout. Reculer n'est pas perdre si on fait plus de dégâts."},
{i:"m227_29",u:227,t:"mcq",d:.8,q:"Enzo, boxeur, veut rester dans la zone marquée. Laquelle ?",svg:"<svg viewBox='0 0 200 195' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='20' y='20' width='160' height='34' rx='8' fill='var(--blue)' opacity='.25'/><text x='28' y='35' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Longue</text><rect x='20' y='62' width='130' height='34' rx='8' fill='var(--green)' opacity='1'/><text x='28' y='77' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>?</text><rect x='20' y='104' width='100' height='34' rx='8' fill='var(--gold)' opacity='.25'/><text x='28' y='119' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Courte</text><rect x='20' y='146' width='70' height='34' rx='8' fill='var(--red)' opacity='.25'/><text x='28' y='161' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Sol</text></svg>",o:["Moyenne : les poings","Longue : les pieds","Courte : le clinch","Sol : le jiu-jitsu"],a:0,w:"La distance moyenne, celle de la boxe. C'est la zone d'Enzo."},
{i:"m227_30",u:227,t:"match",d:.85,q:"Associe chaque situation de score (3 rounds) à la bonne stratégie.",p:[["Mène 2-0","Rester solide, sans prise de risque inutile"],["Mené 0-2","Chercher la finition"],["1-1 avant le 3e","Gagner nettement le dernier round"],["Round 1 serré","Ne pas trop observer"]],w:"Gagner 2 rounds sur 3 : la gestion des rounds est une stratégie."},
{i:"m227_31",u:227,t:"fill",d:.85,q:"Une perte de poids brutale par ___ peut réduire le cardio et la résistance aux coups.",o:["déshydratation","musculation","hydratation","alimentation"],a:0,w:"On prépare le poids sur des semaines, pas en trois jours. La déshydratation touche aussi la lucidité."},
{i:"m227_32",u:227,t:"story",d:.9,q:"Synthèse : Rachid efface le tableau et demande la règle à retenir.",sc:[{who:"Rachid",txt:"Une phrase pour tout le plan."}],o:["« Plan A et plan B, gagner l'impact à chaque round, deux consignes par pause. »","« Foncer sans plan et espérer le KO dès les premières secondes du combat. »","« Contrôler sans frapper, les juges préfèrent toujours le contrôle passif. »","« Changer de plan à chaque échange pour que personne ne le devine. »"],a:0,w:"I.A.C., gestion des rounds, plan A et B, deux consignes. Un combat, c'est quinze minutes de décisions."}
