/*UNIT*/
{id:230,c:"MMA",n:"Module 16",t:"Synthèse : le soir du combat, dans le coin d'Enzo",col:"--red",ic:"🏆",guide:`
<h3>Samedi, 21 h, Palais des sports de Marseille</h3>
<div class="gstory">Le vestiaire sent l'huile de massage. Enzo, bandes aux mains, sautille. Rachid lui répète le plan une dernière fois ; toi, tu tiens la feuille avec les trois failles de Viktor. Lina et Maëlle sont dans le coin avec vous, Tom dans le public avec une pancarte. Round 1 : Viktor avance, Enzo tourne vers sa gauche, touche au jab, place deux calf kicks ; Viktor plonge après son jab, Enzo sprawle et se relève. À la minute de repos, Rachid donne deux consignes : « Contre son direct au foie. Et calf kick quand il avance. » Round 2 : Viktor boite. Round 3 : Viktor respire bouche ouverte, baisse les mains ; Enzo accélère, crochet gauche au foie, puis direct au menton. Viktor tombe, l'arbitre arrête le combat. TKO au 3e round. Dans le coin, Rachid te serre la main : « Bon travail, l'analyste. »</div>
<h3>Le plan complet, relu module par module</h3>
<table><tr><th>Module</th><th>Ce qui a servi ce soir</th></tr>
<tr><td>1. Règles</td><td>3 rounds de 5 minutes, gagner 2 rounds, pas de fautes</td></tr>
<tr><td>2. Cibles</td><td>Foie à droite, crochet gauche ; mollet pour faire boiter</td></tr>
<tr><td>3. Garde et octogone</td><td>Loin de la main forte, le centre pour lui, couper la cage</td></tr>
<tr><td>4 et 5. Boxe et Muay Thaï</td><td>Jab, contres, calf kicks rapides préparés aux poings</td></tr>
<tr><td>6 à 8. Clinch et lutte</td><td>Éviter le grillage, sprawl, se relever</td></tr>
<tr><td>9 à 11. Sol</td><td>Savoir survivre et se relever si l'amenée passe (plan B)</td></tr>
<tr><td>12. Disciplines</td><td>Viktor lutteur : son trou, la frappe debout et le cardio</td></tr>
<tr><td>13. Stratégie</td><td>Plan A, plan B, deux consignes par pause</td></tr>
<tr><td>14. Lecture</td><td>Direct télégraphié, amenée après le jab, fatigue au 3e</td></tr>
<tr><td>15. Cas réels</td><td>Le contre d'Aldo, la leçon de Khabib, les calf kicks de Poirier</td></tr></table>
<div class="gmnemo"><b>« Placer, Préparer, Punir. »</b> Se placer (garde, centre, distance), préparer (jab, feintes, coups bas, lecture), punir (contres, finition au bon moment). Et la phrase de Rachid : <b>« Un combat, c'est quinze minutes de décisions. »</b></div>
<h3>Le rôle d'un coach responsable</h3>
<ul><li>Préparer le <b>poids</b> sur des semaines, jamais par une déshydratation brutale.</li>
<li>Protéger la <b>santé</b> : sparring à la tête limité, repos médical après un KO, et le courage d'arrêter un combat quand le combattant est en danger.</li>
<li>Donner un <b>plan simple</b> : un plan A, un plan B, deux consignes par pause.</li>
<li>Analyser <b>après</b> le combat, même en cas de victoire : ce qui a marché, ce qui a failli coûter cher.</li></ul>
<h3>Ce que tu dois savoir faire à l'examen</h3>
<ul><li>Lire un schéma : cible, garde, distance, position au sol</li><li>Construire un plan de combat complet à partir d'une analyse d'adversaire</li><li>Noter un round selon les critères I.A.C.</li><li>Relier une situation à la bonne technique : sprawl, check, underhook, crevette, pont</li><li>Citer et expliquer les combats de référence</li><li>Connaître les règles, y compris les changements de 2024</li></ul>
<div class="gtrap">Dernier rappel honnête : ce cours fait de toi un analyste solide, pas un combattant. Les techniques se travaillent avec un entraîneur diplômé, dans un club affilié, avec des protections. Et en France, le MMA se pratique dans le cadre de la fédération (FMMAF), avec un certificat médical.</div>`},
/*EXOS*/
{i:"m230_01",u:230,t:"story",d:.2,nw:"Le plan complet",q:"Au 1er round, Viktor avance. De quel côté Enzo doit-il tourner ?",sc:[{who:"Rachid",txt:"Il est gaucher, il avance. Tu tournes où ?"}],o:["« Vers ma gauche, loin de sa main gauche, sa main forte. »","« Vers ma droite, directement dans sa main gauche puissante. »","« Tout droit en arrière, jusqu'au grillage, pour l'attendre. »","« Nulle part, je reste immobile au centre sans bouger du tout. »"],a:0,w:"Loin de la main forte : contre un gaucher, on tourne vers sa gauche."},
{i:"m230_02",u:230,t:"mcq",d:.2,q:"Rachid montre ce schéma : où Enzo doit-il placer son crochet gauche au corps ?",svg:"<svg viewBox='0 0 200 220' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><g fill='var(--card2)' stroke='var(--dim)' stroke-width='2'><circle cx='100' cy='26' r='16'/><rect x='93' y='41' width='14' height='8' rx='3'/><path d='M72 50 Q100 44 128 50 L124 118 Q100 124 76 118 Z'/><path d='M72 52 L56 92 L62 96 L78 62 Z'/><path d='M128 52 L144 92 L138 96 L122 62 Z'/><path d='M78 118 L74 196 L90 196 L99 124 Z'/><path d='M122 118 L126 196 L110 196 L101 124 Z'/></g><circle cx='100' cy='38' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='100' y='41.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>1</text><circle cx='84' cy='26' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='84' y='29.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>2</text><circle cx='100' cy='82' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='100' y='85.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>3</text><circle cx='84' cy='104' r='7' fill='var(--red)' stroke='var(--bg)' stroke-width='1.5'/><text x='84' y='107.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>4</text><circle cx='118' cy='100' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='118' y='103.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>5</text><circle cx='84' cy='150' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='84' y='153.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>6</text><circle cx='80' cy='182' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='80' y='185.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>7</text><text x='100' y='214' font-size='10' fill='var(--gold)' text-anchor='middle' font-weight='700'>Quelle cible ?</text></svg>",o:["Au point rouge, le foie","Au plexus, au centre","Aux côtes, de l'autre côté","À la cuisse, en bas"],a:0,w:"Foie à droite, crochet gauche : le point 4."},
{i:"m230_03",u:230,t:"tiles",d:.25,q:"Reconstitue le résumé du plan en trois mots.",a:["placer","préparer","punir"],dd:["provoquer","plonger","prier"],w:"Se placer, préparer, punir. C'est le plan de frappeur qu'Enzo a suivi pour gagner."},
{i:"m230_04",u:230,t:"fill",d:.25,q:"Viktor plonge après son jab ; Enzo projette les jambes en arrière : c'est le ___.",o:["sprawl","check","pummel","teep"],a:0,w:"Jambes derrière, hanches lourdes, tête en bas. Puis on se relève."},
{i:"m230_05",u:230,t:"tf",d:.25,q:"À la minute de repos, Rachid a donné deux consignes plutôt que dix.",a:true,w:"Deux consignes, pas dix : un combattant épuisé ne retient que l'essentiel."},
{i:"m230_06",u:230,t:"mcq",d:.3,q:"Au 2e round, Viktor se retrouve ainsi au sol, le rouge au-dessus. Quelle position ?",svg:"<svg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='5' y='5' width='190' height='170' rx='10' fill='var(--card)'/><rect x='83' y='55' width='34' height='70' rx='17' fill='var(--blue)' transform='rotate(0 100 90)'/><circle cx='100' cy='44' r='11' fill='var(--blue)' stroke='var(--bg)' stroke-width='2'/><rect x='82' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 88 142)'/><rect x='106' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 112 142)'/><rect x='107' y='69' width='70' height='30' rx='15' fill='var(--red)' transform='rotate(0 142 84)'/><circle cx='100' cy='80' r='11' fill='var(--red)' stroke='var(--bg)' stroke-width='2'/><text x='100' y='192' font-size='10' fill='var(--gold)' text-anchor='middle' font-weight='700'>Quelle position ?</text></svg>",o:["Contrôle latéral","Montée","Garde fermée","Dos avec crochets"],a:0,w:"En travers de la poitrine : contrôle latéral. Troisième position la plus dominante."},
{i:"m230_07",u:230,t:"story",d:.3,q:"Au 2e round, Viktor boite après les calf kicks. Quelle consigne à la pause ?",sc:[{who:"Enzo",txt:"Il boite, je fais quoi ?"}],o:["« Continue les calf kicks, et frappe quand il s'appuie moins. »","« Arrête les coups de pied, par respect pour sa jambe blessée. »","« Amène-le au sol tout de suite pour finir son travail au sol. »","« Change complètement de plan et cherche uniquement la tête. »"],a:0,w:"Le mollet fait boiter : on insiste sur ce qui paye, sans oublier la garde."},
{i:"m230_08",u:230,t:"sort",d:.3,q:"Classe chaque action du soir selon le temps du plan.",bins:["Placer","Préparer","Punir"],it:[["Tourner loin de sa main forte",0],["Calf kicks répétés",1],["Crochet gauche au foie en contre",2],["Tenir le centre",0],["Jab pour mesurer",1],["Direct au menton quand il baisse les mains",2]],w:"Placer, préparer, punir : l'ordre d'un plan de frappeur."},
{i:"m230_09",u:230,t:"match",d:.35,q:"Associe chaque faille de Viktor au module qui a permis de la voir.",p:[["Direct télégraphié","Lire un combat"],["Jambe avant fragile","Cibles et Muay Thaï"],["Amenée après le jab","Lutte et défense de lutte"],["Fatigue au 3e round","Stratégie et cardio"]],w:"Chaque module du cours sert le soir du combat."},
{i:"m230_10",u:230,t:"fill",d:.35,q:"Enzo gagne par ___ au 3e round, l'arbitre arrêtant le combat.",o:["TKO","soumission","décision","forfait"],a:0,w:"Arrêt de l'arbitre après une chute : TKO."},
{i:"m230_11",u:230,t:"story",d:.4,q:"Imagine que Viktor réussit une amenée au 1er round. Quel est le plan B d'Enzo ?",sc:[{who:"Rachid",txt:"Plan B, vite."}],o:["« Casser sa posture, tenir ses poignets, se relever à la cage. »","« Tourner le dos pour protéger mon visage des coups au sol. »","« Tirer Viktor dans ma garde et attendre la fin du round. »","« M'accrocher au grillage pour ne pas rester au sol. »"],a:0,w:"Contrôle, Casse, Relève. Tourner le dos offre le dos ; s'accrocher à la cage est une faute. Et contre un adversaire debout, les coups de pied montants le tiennent à distance."},
{i:"m230_12",u:230,t:"mcq",d:.4,q:"Sur ce schéma, où Enzo doit-il viser pour faire boiter Viktor ?",svg:"<svg viewBox='0 0 200 220' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><g fill='var(--card2)' stroke='var(--dim)' stroke-width='2'><circle cx='100' cy='26' r='16'/><rect x='93' y='41' width='14' height='8' rx='3'/><path d='M72 50 Q100 44 128 50 L124 118 Q100 124 76 118 Z'/><path d='M72 52 L56 92 L62 96 L78 62 Z'/><path d='M128 52 L144 92 L138 96 L122 62 Z'/><path d='M78 118 L74 196 L90 196 L99 124 Z'/><path d='M122 118 L126 196 L110 196 L101 124 Z'/></g><circle cx='100' cy='38' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='100' y='41.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>1</text><circle cx='84' cy='26' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='84' y='29.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>2</text><circle cx='100' cy='82' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='100' y='85.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>3</text><circle cx='84' cy='104' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='84' y='107.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>4</text><circle cx='118' cy='100' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='118' y='103.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>5</text><circle cx='84' cy='150' r='7' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1.5'/><text x='84' y='153.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>6</text><circle cx='80' cy='182' r='7' fill='var(--red)' stroke='var(--bg)' stroke-width='1.5'/><text x='80' y='185.5' font-size='9' fill='var(--bg)' text-anchor='middle' font-weight='700'>7</text><text x='100' y='214' font-size='10' fill='var(--gold)' text-anchor='middle' font-weight='700'>Quelle cible ?</text></svg>",o:["Au mollet, le point rouge","Au menton, en crochet","Au plexus, en direct","À la tempe, en high kick"],a:0,w:"Le mollet externe, cible du calf kick : le pied ne répond plus."},
{i:"m230_13",u:230,t:"tf",d:.4,q:"Un bon coach analyse aussi le combat après une victoire.",a:true,w:"Ce qui a marché, et ce qui a failli coûter cher : une victoire se prépare aussi pour la suivante."},
{i:"m230_14",u:230,t:"order",d:.45,q:"Remets dans l'ordre le déroulé du combat d'Enzo.",it:["Round 1 : jab, calf kicks, sprawl","Pause : deux consignes","Round 2 : Viktor boite","Round 3 : Viktor fatigue, mains basses","Crochet au foie, direct, TKO"],w:"Placer, préparer, punir, round après round."},
{i:"m230_15",u:230,t:"multi",d:.45,q:"Quels sont les devoirs d'un coach responsable ?",o:["Préparer le poids sur des semaines","Limiter le sparring à la tête","Arrêter le combat si le combattant est en danger","Donner un plan simple","Pousser son combattant à continuer quoi qu'il arrive"],a:[0,1,2,3],w:"Protéger la santé fait partie du métier. La déshydratation avant la pesée est l'erreur la plus fréquente."},
{i:"m230_16",u:230,t:"mcq",d:.45,q:"Quelle distance Enzo doit-il privilégier, d'après ce schéma ?",svg:"<svg viewBox='0 0 200 195' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='20' y='20' width='160' height='34' rx='8' fill='var(--blue)' opacity='1'/><text x='28' y='35' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Longue</text><text x='28' y='48' font-size='9' fill='var(--bg)' text-anchor='start' font-weight='600'>pieds, teep</text><rect x='20' y='62' width='130' height='34' rx='8' fill='var(--green)' opacity='1'/><text x='28' y='77' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Moyenne</text><text x='28' y='90' font-size='9' fill='var(--bg)' text-anchor='start' font-weight='600'>poings</text><rect x='20' y='104' width='100' height='34' rx='8' fill='var(--gold)' opacity='1'/><text x='28' y='119' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Courte</text><text x='28' y='132' font-size='9' fill='var(--bg)' text-anchor='start' font-weight='600'>clinch, genoux, coudes</text><rect x='20' y='146' width='70' height='34' rx='8' fill='var(--red)' opacity='1'/><text x='28' y='161' font-size='11' fill='var(--bg)' text-anchor='start' font-weight='700'>Sol</text><text x='28' y='174' font-size='9' fill='var(--bg)' text-anchor='start' font-weight='600'>lutte au sol, JJB</text></svg>",o:["La moyenne, des poings","Le sol, en lutte et JJB","La courte, en clinch à la cage","Aucune distance en particulier"],a:0,w:"Boxeur face à un lutteur : la distance moyenne, en évitant le clinch et le sol."},
{i:"m230_17",u:230,t:"story",d:.5,q:"Rappel du module 13 : un juge donne le 1er round à Viktor, qui a avancé sans toucher. Qu'en penses-tu ?",sc:[{who:"Tom",txt:"Il avançait tout le temps !"}],o:["« Discutable : Enzo a touché plus ; l'impact passe d'abord. »","« Logique : avancer suffit toujours pour gagner un round. »","« Normal : le premier round revient toujours au plus lourd. »","« Juste : le public criait plus fort pour Viktor. »"],a:0,w:"I.A.C. : impact d'abord ; avancer sans toucher n'est pas de l'agressivité efficace."},
{i:"m230_18",u:230,t:"fill",d:.5,q:"Pour sortir d'un clinch contre la cage, Enzo cherche un ___ pour pivoter.",o:["underhook","overhook","sprawl","double-leg"],a:0,w:"Sous le bras, tu contrôles : l'underhook permet de pivoter et d'inverser."},
{i:"m230_19",u:230,t:"sort",d:.55,q:"Classe chaque technique selon la situation où elle sert.",bins:["Debout","Clinch","Sol"],it:[["Check",0],["Underhook",1],["Crevette",2],["Calf kick",0],["Pummeling",1],["Pont",2]],w:"Trois cases : debout, clinch, sol. Un combattant complet maîtrise les trois."},
{i:"m230_20",u:230,t:"tf",d:.55,q:"Ce cours suffit pour combattre en compétition sans entraîneur.",a:false,w:"Il forme un analyste. Les techniques se travaillent avec un entraîneur diplômé, en club affilié, avec certificat médical."},
{i:"m230_21",u:230,t:"mcq",d:.6,q:"Quel schéma de position doit alerter Enzo au sol ?",svg:"<svg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='5' y='5' width='190' height='170' rx='10' fill='var(--card)'/><rect x='82' y='64' width='36' height='72' rx='18' fill='var(--red)' transform='rotate(0 100 100)'/><circle cx='100' cy='52' r='11' fill='var(--red)' stroke='var(--bg)' stroke-width='2'/><rect x='85' y='59' width='30' height='62' rx='15' fill='var(--blue)' transform='rotate(0 100 90)'/><circle cx='100' cy='44' r='11' fill='var(--blue)' stroke='var(--bg)' stroke-width='2'/><path d='M84 110 Q74 124 90 132' stroke='var(--red)' stroke-width='8' fill='none' stroke-linecap='round'/><path d='M116 110 Q126 124 110 132' stroke='var(--red)' stroke-width='8' fill='none' stroke-linecap='round'/><path d='M82 54 Q100 68 118 54' stroke='var(--red)' stroke-width='6' fill='none'/><text x='100' y='192' font-size='10' fill='var(--gold)' text-anchor='middle' font-weight='700'>Quelle position ?</text></svg>",o:["Le dos pris : danger d'étranglement","La garde fermée, position sûre","La montée, position neutre","Aucun danger dans cette position"],a:0,w:"Dos pris : étranglement arrière possible. On rentre le menton et on combat les mains."},
{i:"m230_22",u:230,t:"story",d:.6,q:"Tom veut s'inscrire en compétition le mois prochain après avoir suivi ce cours. Que lui dis-tu ?",sc:[{who:"Tom",txt:"Je connais tout maintenant, je peux combattre !"}],o:["« Tu connais la théorie : il te faut des années d'entraînement encadré. »","« Oui, connaître la théorie suffit largement pour gagner en compétition. »","« Oui, mais seulement si tu combats contre des débutants comme toi. »","« Non, le MMA est interdit en France, il faut aller à l'étranger. »"],a:0,w:"Analyste n'est pas combattant. Et le MMA est légal en France, encadré par la fédération."},
{i:"m230_23",u:230,t:"match",d:.65,q:"Associe chaque règle récente ou importante à son contenu.",p:[["Coude 12-6","Autorisé depuis novembre 2024 par les règles unifiées"],["Combattant au sol","Une partie du corps autre que mains et pieds au tapis"],["MMA en France","Légal depuis janvier 2020"],["Rounds","3 fois 5 minutes, 5 pour un titre"]],w:"Les règles de base et leurs changements récents."},
{i:"m230_24",u:230,t:"tiles",d:.65,q:"Reconstitue la phrase de Rachid.",a:["un","combat","c'est","quinze","minutes","de","décisions"],dd:["coups","hasard","chance"],w:"Pour un combat en trois rounds : quinze minutes de décisions."},
{i:"m230_25",u:230,t:"story",d:.7,q:"Rappel du module 15 : pourquoi le contre au foie d'Enzo rappelle-t-il McGregor contre Aldo ?",sc:[{who:"Tom",txt:"Il n'y a aucun rapport, non ?"}],o:["« Dans les deux cas, c'est un contre sur un adversaire qui attaque. »","« Dans les deux cas, c'est une soumission au sol au premier round. »","« Dans les deux cas, le combat s'est fini en 13 secondes exactement. »","« Il n'y a vraiment aucun rapport entre ces deux combats. »"],a:0,w:"Le contre fait les KO : l'élan de l'adversaire s'ajoute à l'impact."},
{i:"m230_26",u:230,t:"fill",d:.7,q:"Les trois critères des juges, dans l'ordre : impact, agressivité et ___.",o:["contrôle","volume","poids","élégance"],a:0,w:"I.A.C. Chaque critère ne sert que si le précédent est égal."},
{i:"m230_27",u:230,t:"multi",d:.75,q:"Quelles leçons de combats célèbres Enzo a-t-il appliquées ?",o:["Le contre (Aldo)","Les calf kicks (Poirier)","Le terrain choisi (Khabib)","La lucidité et le calme (Gane)","Provoquer mains basses (Silva)"],a:[0,1,2,3],w:"La provocation mains basses est justement la leçon à ne pas suivre."},
{i:"m230_28",u:230,t:"mcq",d:.75,q:"Enzo, dessous, piège une jambe de Viktor, comme ici. Quelle position ?",svg:"<svg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='5' y='5' width='190' height='170' rx='10' fill='var(--card)'/><rect x='83' y='55' width='34' height='70' rx='17' fill='var(--blue)' transform='rotate(0 100 90)'/><circle cx='100' cy='44' r='11' fill='var(--blue)' stroke='var(--bg)' stroke-width='2'/><rect x='82' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 88 142)'/><rect x='106' y='119' width='12' height='46' rx='6' fill='var(--blue)' transform='rotate(0 112 142)'/><rect x='102' y='75' width='32' height='58' rx='16' fill='var(--red)' transform='rotate(20 118 104)'/><circle cx='108' cy='72' r='11' fill='var(--red)' stroke='var(--bg)' stroke-width='2'/><path d='M112 150 Q126 136 132 128' stroke='var(--blue)' stroke-width='10' fill='none' stroke-linecap='round'/><text x='100' y='192' font-size='10' fill='var(--gold)' text-anchor='middle' font-weight='700'>Quelle position ?</text></svg>",o:["La demi-garde","La montée","Le dos","Le contrôle latéral"],a:0,w:"Une jambe piégée : demi-garde, dernière barrière avant le passage."},
{i:"m230_29",u:230,t:"sort",d:.8,q:"Classe chaque attitude du coin : responsable ou dangereuse ?",bins:["Responsable","Dangereuse"],it:[["Arrêter un combattant qui ne se défend plus",0],["Pousser à continuer avec une commotion",1],["Deux consignes claires",0],["Faire perdre 5 kg en trois jours",1],["Analyser le combat après la victoire",0]],w:"La santé passe avant le résultat. Un bon coach protège son combattant avant de chercher le résultat."},
{i:"m230_30",u:230,t:"tf",d:.8,q:"Selon la synthèse, un combattant complet ne laisse aucune case vide entre debout, clinch et sol.",a:true,w:"C'est le test des trois cases (module 12)."},
{i:"m230_31",u:230,t:"story",d:.85,q:"Rachid te demande ce qu'un analyste apporte à un coin, en une phrase.",sc:[{who:"Rachid",txt:"Et toi, tu sers à quoi ?"}],o:["« Trouver les failles, en faire des consignes simples, vérifier en direct. »","« À crier plus fort que le public pour motiver le combattant dans la cage. »","« À remplacer l'entraîneur pendant les rounds, à sa place, dans le coin. »","« À prédire le résultat exact du combat avant qu'il ne commence. »"],a:0,w:"Observer, vérifier, traduire en consignes : c'est le métier d'analyste."},
{i:"m230_32",u:230,t:"story",d:.9,q:"Synthèse finale : Enzo te demande la leçon de tout le cours.",sc:[{who:"Enzo",txt:"Si tu devais me dire une seule chose ?"}],o:["« Placer, préparer, punir : et c'est toi qui choisis où se passe le combat. »","« Frapper le plus fort possible dès le premier coup de gong, sans réfléchir. »","« Toujours aller au sol, quelle que soit la base de l'adversaire. »","« Écouter le public, qui sait toujours ce qu'il faut faire. »"],a:0,w:"Placer, préparer, punir ; choisir le terrain ; quinze minutes de décisions."}
