/*UNIT*/
{id:135,c:"PATRI",n:"Module 3",t:"Réserve, quotité disponible et indivision",col:"--gold",ic:"🧱",guide:`
<h3>Le patrimoine est coupé en deux parts</h3>
<div class="gstory">Bernard Lefèvre te regarde droit dans les yeux : « Marc ne m'a pas adressé la parole depuis six ans. Je veux tout laisser à Julie et Sophie. » Tu vas devoir lui dire non, gentiment, et lui montrer ce qu'il peut faire à la place. La réserve est ton argument.</div>
<p>En présence d'enfants, le patrimoine se divise en deux :</p>
<ul><li>la <b>réserve héréditaire</b> : la part que la loi garantit aux enfants, que personne ne peut leur retirer ;</li>
<li>la <b>quotité disponible</b> : la part dont le défunt peut disposer librement, par donation ou testament, au profit de qui il veut.</li></ul>
<h3>Le tableau à connaître par cœur</h3>
<table><tr><th>Nombre d'enfants</th><th>Réserve globale</th><th>Quotité disponible</th></tr>
<tr><td>1</td><td>1/2</td><td>1/2</td></tr>
<tr><td>2</td><td>2/3</td><td>1/3</td></tr>
<tr><td>3 et plus</td><td>3/4</td><td>1/4</td></tr></table>
<div class="gmnemo">La réserve vaut <b>n / (n + 1)</b>, plafonnée à 3/4. Un enfant : 1/2. Deux : 2/3. Trois : 3/4. Et la quotité disponible, c'est toujours <b>1 / (n + 1)</b> : <b>une part d'enfant de plus</b>, que le parent garde pour lui. Au-delà de trois enfants, le gâteau ne rétrécit plus : la quotité reste à 1/4.</div>
<p>La réserve globale se partage à parts égales entre les enfants. Avec trois enfants, chacun a une réserve individuelle de 1/4 (3/4 divisé par 3).</p>
<p>Sans enfant, le <b>conjoint</b> a une réserve de 1/4. Les parents, eux, n'ont plus de réserve depuis 2006.</p>
<h3>Comment on calcule : la masse de calcul</h3>
<div class="formula">Masse de calcul = biens existants au décès
                - dettes
                + donations faites de son vivant (réunion fictive)
Réserve = masse × fraction de réserve
Quotité disponible = masse × fraction de quotité</div>
<p>Les donations passées sont ajoutées « sur le papier » : c'est la <b>réunion fictive</b>. Sinon, il suffirait de tout donner de son vivant pour contourner la réserve.</p>
<h3>Quand on dépasse : l'action en réduction</h3>
<p>Si les donations ou legs dépassent la quotité disponible, l'enfant lésé peut agir en <b>réduction</b> : le bénéficiaire doit rendre l'excédent, en principe sous forme d'une <b>indemnité</b> en argent. Délai : <b>5 ans</b> après le décès, ou 2 ans après la découverte de l'atteinte, sans dépasser 10 ans après le décès.</p>
<h3>La RAAR : quand l'enfant accepte d'avoir moins</h3>
<p>La <b>renonciation anticipée à l'action en réduction</b> permet à un héritier réservataire de renoncer, <b>du vivant du parent</b>, à contester une libéralité qui entamerait sa réserve. C'est l'une des rares façons de toucher à la réserve.</p>
<ul><li>Le renonçant doit être un <b>héritier présomptif réservataire</b> et avoir la <b>capacité de donner</b>.</li>
<li>Il renonce <b>au profit d'une personne désignée</b> : on sait pour qui.</li>
<li>C'est un acte <b>gratuit</b> (pas de contrepartie) sans être une libéralité.</li>
<li>Forme : acte reçu par <b>deux notaires</b>, signé séparément par chaque renonçant. Ton cours retient un coût modeste, de l'ordre de 125 €.</li>
<li>Elle engage le renonçant dès son <b>acceptation par le parent</b>, et elle est opposable à ses représentants (ses propres enfants).</li>
<li>Elle est <b>irrévocable</b>, sauf si le parent manque à son obligation alimentaire envers le renonçant, si le renonçant est dans le besoin au décès, ou si le bénéficiaire commet un crime ou un délit contre lui.</li></ul>
<div class="gstory">Stéphane a deux enfants : Hugo, ingénieur à Genève, et Lina, lourdement handicapée. Hugo signe une RAAR devant deux notaires pour que son père puisse léguer à Lina plus que la quotité disponible. Hugo sait pour qui il renonce, et pourquoi. C'est exactement l'esprit du texte : organiser la solidarité familiale.</div>
<div class="gmnemo">RAAR se lit « <b>R</b>enoncer <b>A</b>vant, <b>A</b>u profit de quelqu'un, <b>R</b>arement révocable ». Deux notaires, un nom de bénéficiaire, pas de retour en arrière.</div>
<h3>L'indivision : quand plusieurs possèdent le même bien</h3>
<p>Après un décès, les héritiers sont en <b>indivision</b> : chacun possède une quote-part de chaque bien, sans que les biens soient répartis. La maison d'Annecy appartient à un tiers à Julie, un tiers à Marc, un tiers à Sophie, mais aucun n'a « sa » chambre.</p>
<ul><li><b>« Nul n'est tenu de demeurer dans l'indivision »</b> : chaque indivisaire peut, à tout moment, demander le partage. Personne ne peut être forcé de rester propriétaire en commun.</li>
<li>Actes de gestion courante (louer, entretenir) : majorité des <b>deux tiers</b> des droits.</li>
<li>Vendre le bien, ou tout acte qui ne relève pas de la gestion normale : <b>unanimité</b>, sauf autorisation du juge.</li>
<li>Un indivisaire qui vend sa part à un étranger doit d'abord la proposer aux autres : c'est le <b>droit de préemption</b>.</li></ul>
<div class="gstory">Marc veut vendre la maison d'Annecy, Sophie veut la garder, Julie hésite. Marc ne peut pas vendre seul. Mais il peut demander le partage : si personne ne peut racheter sa part, le juge peut ordonner la vente aux enchères (licitation). D'où l'intérêt d'anticiper par une donation-partage (module 7).</div>`},
/*EXOS*/
{i:"p135_01",u:135,t:"match",d:.2,nw:"La réserve héréditaire",q:"Associe le nombre d'enfants à la réserve globale.",p:[["Un enfant","1/2"],["Deux enfants","2/3"],["Trois enfants","3/4"],["Cinq enfants","3/4"]],w:"La réserve vaut n/(n+1), plafonnée à 3/4. Au-delà de trois enfants, elle ne bouge plus."},
{i:"p135_02",u:135,t:"story",d:.3,q:"Que réponds-tu à Bernard ?",sc:[{who:"Bernard Lefèvre",txt:"Marc ne me parle plus. Je veux tout laisser à Julie et Sophie, par testament."},{who:"Toi",me:true,txt:"Je comprends votre colère. Mais la loi protège Marc, même contre vous."}],o:["Marc garde sa réserve de 1/4 ; vous pouvez donner la quotité de 1/4 à ses sœurs","Marc garde un tiers, car la réserve se calcule sur les enfants qui vous parlent","Le testament est valable si vous prouvez que Marc a rompu le premier le contact","Marc garde la moitié de la succession, quelle que soit la rédaction du testament"],a:0,w:"Trois enfants : réserve 3/4, soit 1/4 chacun, et quotité disponible 1/4. Bernard peut léguer la quotité à Julie et Sophie : elles auront chacune 1/4 + 1/8, Marc 1/4."},
{i:"p135_03",u:135,t:"slider",d:.3,q:"Colette n'a qu'un fils. Quelle part de sa succession peut-elle léguer librement à son amie ?",min:0,max:100,step:5,a:50,tol:0,pre:"",un:" %",w:"Un enfant : réserve 1/2, quotité disponible 1/2. Elle peut léguer la moitié à qui elle veut."},
{i:"p135_04",u:135,t:"num",d:.4,ctx:"Au décès, un père de deux enfants laisse 500 000 € de biens et 50 000 € de dettes. Dix ans plus tôt, il avait donné à son fils un studio qui vaut aujourd'hui 150 000 €.",q:"Quelle est la masse de calcul de la réserve, en euros ?",a:600000,tol:1,un:" €",h:"Biens moins dettes, plus les donations réunies fictivement",w:"500 000 - 50 000 + 150 000 = 600 000 €. La donation est réunie fictivement pour que la réserve ne puisse pas être contournée."},
{i:"p135_05",u:135,t:"num",d:.45,ctx:"Même famille : masse de calcul 600 000 €, deux enfants.",q:"Quel est le montant de la quotité disponible, en euros ?",a:200000,tol:1,un:" €",h:"Deux enfants : quelle fraction est libre ?",w:"Deux enfants : quotité disponible 1/3. 600 000 / 3 = 200 000 €. La réserve globale vaut 400 000 €, soit 200 000 € par enfant."},
{i:"p135_06",u:135,t:"tf",d:.25,q:"Depuis 2006, les parents du défunt ne sont plus héritiers réservataires.",a:true,w:"La réserve des ascendants a été supprimée. Ils bénéficient à la place d'un droit de retour sur les biens qu'ils avaient donnés."},
{i:"p135_07",u:135,t:"sort",d:.35,q:"Qui est héritier réservataire ?",bins:["Réservataire","Non réservataire"],it:[["Un enfant du défunt",0],["Le conjoint, en l'absence de descendant",0],["Le père du défunt",1],["Un frère du défunt",1],["Le partenaire de PACS",1],["Un petit-enfant venant par représentation",0]],w:"Réservataires : les descendants, et le conjoint en l'absence de descendant. Ni les parents, ni la fratrie, ni le partenaire de PACS."},
{i:"p135_08",u:135,t:"fill",d:.3,q:"La part dont on peut disposer librement s'appelle la ___.",o:["quotité disponible","réserve héréditaire","part virile","soulte"],a:0,w:"Quotité disponible : 1/2, 1/3 ou 1/4 selon le nombre d'enfants. Le reste est la réserve."},
{i:"p135_09",u:135,t:"story",d:.45,nw:"La RAAR",q:"Quel outil proposes-tu ?",ctx:"Stéphane a deux enfants : Hugo, 30 ans, ingénieur aisé, et Lina, 26 ans, lourdement handicapée. Il veut laisser à Lina bien plus que la quotité disponible. Hugo est d'accord.",sc:[{who:"Stéphane",txt:"Hugo me dit qu'il ne contestera jamais. Mais s'il change d'avis dans vingt ans ?"},{who:"Hugo",txt:"Je suis prêt à m'engager par écrit, officiellement."}],o:["Une renonciation anticipée à l'action en réduction, signée par Hugo devant deux notaires","Une lettre sur l'honneur d'Hugo, conservée avec le testament de son père","Un testament olographe qui prive Hugo de toute sa réserve, puisqu'il est d'accord aujourd'hui","Une donation à Hugo en contrepartie de son silence, pour acheter sa renonciation"],a:0,w:"La RAAR est faite pour ça : Hugo renonce à agir en réduction au profit de Lina, par acte reçu par deux notaires. Une promesse orale ou une lettre ne l'engagent pas."},
{i:"p135_10",u:135,t:"multi",d:.45,q:"Quelles conditions la RAAR doit-elle respecter ?",o:["Être reçue par deux notaires","Désigner la personne au profit de qui on renonce","Émaner d'un héritier présomptif réservataire","Prévoir une contrepartie financière pour le renonçant"],a:[0,1,2],w:"Deux notaires, un bénéficiaire désigné, un héritier réservataire capable. Et surtout aucune contrepartie : c'est un acte gratuit."},
{i:"p135_11",u:135,t:"tf",d:.35,q:"Une fois acceptée par le parent, la RAAR peut être révoquée librement par l'enfant qui l'a signée.",a:false,w:"Elle est irrévocable, sauf trois cas précis : manquement du parent à son obligation alimentaire, état de besoin du renonçant au décès, crime ou délit du bénéficiaire contre lui."},
{i:"p135_12",u:135,t:"multi",d:.55,q:"Dans quels cas une RAAR peut-elle être révoquée ?",o:["Le parent a manqué à son obligation alimentaire envers le renonçant","Le renonçant est dans le besoin au décès, à cause de sa renonciation","Le bénéficiaire a commis un crime contre le renonçant","Le renonçant s'est brouillé avec le bénéficiaire"],a:[0,1,2],w:"Trois cas seulement. Une simple brouille ne suffit pas : c'est ce qui rend la RAAR fiable."},
{i:"p135_13",u:135,t:"mcq",d:.35,q:"Quatre enfants. Quelle est la réserve individuelle de chacun ?",o:["3/16","1/4","1/5","3/4"],a:0,w:"Réserve globale 3/4, partagée entre quatre enfants : 3/16 chacun. La quotité disponible reste à 1/4."},
{i:"p135_14",u:135,t:"story",d:.4,nw:"L'indivision",q:"Que dis-tu à Marc ?",sc:[{who:"Marc Lefèvre",txt:"Papa est parti. Avec mes sœurs on a hérité de la maison d'Annecy, un tiers chacun. Je veux vendre, elles non."},{who:"Marc Lefèvre",txt:"Je peux vendre mon tiers de la maison à un ami ?"}],o:["Oui, mais tes sœurs peuvent racheter ta part en priorité","Non, un indivisaire ne peut jamais céder sa part à un tiers","Oui, et ton ami devient propriétaire sans que tes sœurs soient prévenues","Non, il faut attendre dix ans avant de pouvoir céder une part"],a:0,w:"Un indivisaire peut céder sa quote-part, mais il doit d'abord la proposer aux autres indivisaires : c'est leur droit de préemption."},
{i:"p135_15",u:135,t:"tiles",d:.3,q:"Reconstitue le principe de l'article 815 du Code civil.",a:["Nul","ne","peut","être","contraint","à","demeurer","dans","l'indivision"],dd:["toujours","doit","partage"],w:"Chaque indivisaire peut demander le partage à tout moment. Ton cours l'écrit « nul n'est censé demeurer dans l'indivision » : l'idée est la même."},
{i:"p135_16",u:135,t:"sort",d:.45,q:"Classe chaque acte selon la majorité nécessaire entre indivisaires.",bins:["Deux tiers des droits","Unanimité"],it:[["Louer la maison d'Annecy à un couple",0],["Vendre la maison",1],["Faire repeindre les volets",0],["Donner la maison à une association",1],["Confier la gestion à une agence",0]],w:"Gestion normale : deux tiers. Vendre ou donner : unanimité, sauf autorisation judiciaire. Le principe : plus l'acte est grave, plus il faut d'accord."},
{i:"p135_17",u:135,t:"mcq",d:.45,q:"Pourquoi ajoute-t-on fictivement les donations passées à la masse de calcul ?",o:["Pour empêcher de contourner la réserve en donnant tout de son vivant","Pour taxer une seconde fois les biens donnés au jour du décès","Pour obliger les donataires à rendre les biens en nature","Pour que les petits-enfants récupèrent les donations de leurs parents"],a:0,w:"La réunion fictive est purement comptable : elle sert à vérifier que la réserve est respectée. Elle ne crée pas de nouvel impôt."},
{i:"p135_18",u:135,t:"slider",d:.45,q:"Combien de temps un enfant lésé a-t-il en principe pour agir en réduction après le décès ?",min:1,max:10,step:1,a:5,tol:0,pre:"",un:" ans",w:"Cinq ans après l'ouverture de la succession, ou deux ans après la découverte de l'atteinte à sa réserve, sans jamais dépasser dix ans après le décès."},
{i:"p135_19",u:135,t:"story",d:.5,q:"Que risque Sophie ?",ctx:"Un père de deux enfants laisse une masse de calcul de 600 000 €. Il avait légué 300 000 € à sa fille Sophie, en plus de sa part de réservataire. Son fils n'a rien reçu d'autre que sa réserve.",sc:[{who:"Le frère de Sophie",txt:"Papa a légué trois cent mille euros à ma sœur. Je trouve ça injuste."},{who:"Sophie",txt:"C'est un testament, c'est sa volonté, il n'y a rien à dire."}],o:["La quotité est de 200 000 € : son frère peut réduire le legs de 100 000 €","Rien du tout : un testament l'emporte toujours sur la réserve des autres enfants","Tout le legs est annulé, et les 300 000 € sont partagés en deux","Son frère récupère le legs entier, car il dépasse la moitié de la masse"],a:0,w:"Deux enfants : quotité disponible 1/3 de 600 000, soit 200 000. Le legs la dépasse de 100 000 : c'est ce montant, et lui seul, qui peut être réduit, en principe sous forme d'indemnité."},
{i:"p135_20",u:135,t:"tf",d:.4,q:"La réduction se fait en principe en valeur : le bénéficiaire verse une indemnité plutôt que de rendre le bien.",a:true,w:"Depuis 2006, la réduction se fait en principe en valeur. Le bénéficiaire garde le bien et paie la différence."},
{i:"p135_21",u:135,t:"order",d:.4,q:"Remets dans l'ordre la vérification du respect de la réserve.",it:["Faire la liste des biens existants au décès","Retirer les dettes","Ajouter fictivement les donations passées","Appliquer la fraction de réserve selon le nombre d'enfants","Comparer les libéralités à la quotité disponible"],w:"Biens, moins dettes, plus donations, puis fractions. C'est la mécanique de l'article 922 du Code civil."},
{i:"p135_22",u:135,t:"mcq",d:.5,q:"Un enfant renonce à la succession et n'a pas de descendant. Compte-t-il pour calculer la réserve ?",o:["Non, sauf s'il doit rapporter une donation","Oui, un enfant compte toujours dans le calcul","Non, et la quotité disponible devient nulle","Oui, sa part de réserve va au conjoint"],a:0,w:"L'enfant qui renonce n'est compté que s'il est représenté ou tenu au rapport d'une libéralité. Sinon, on calcule comme s'il n'existait pas."},
{i:"p135_23",u:135,t:"story",d:.4,q:"Quelle est la bonne lecture ?",sc:[{who:"Hélène Lefèvre",txt:"Mon voisin dit qu'il peut tout laisser à son chien parce que ses enfants sont majeurs."},{who:"Toi",me:true,txt:"Votre voisin mélange deux choses."}],o:["La majorité des enfants ne change rien : leur réserve reste due","Il a raison : la réserve ne protège que les enfants mineurs","Il a raison, s'il rédige un testament authentique chez un notaire","Il peut tout laisser, à condition de le dire à ses enfants"],a:0,w:"La réserve protège tous les enfants, majeurs ou non, riches ou pauvres. Seule une RAAR peut l'aménager, avec leur accord."},
{i:"p135_24",u:135,t:"num",d:.5,ctx:"Trois enfants. Masse de calcul : 800 000 €.",q:"Quelle est la réserve individuelle de chaque enfant, en euros ?",a:200000,tol:1,un:" €",h:"Réserve globale, puis partage égal",w:"Réserve globale 3/4 de 800 000 = 600 000, soit 200 000 par enfant. Quotité disponible : 200 000 €."},
{i:"p135_25",u:135,t:"fill",d:.4,q:"La RAAR est un acte ___, sans contrepartie, même si ce n'est pas une libéralité.",o:["gratuit","onéreux","conditionnel","révocable"],a:0,w:"Gratuit : le renonçant ne reçoit rien en échange. Ce n'est pas une libéralité car il ne transmet rien lui-même."},
{i:"p135_26",u:135,t:"match",d:.45,q:"Associe chaque notion à sa définition.",p:[["Réserve","Part garantie aux héritiers réservataires"],["Quotité disponible","Part que l'on peut léguer librement"],["Réunion fictive","Ajout comptable des donations passées"],["Action en réduction","Recours contre une libéralité excessive"]],w:"Quatre mots qui forment une seule mécanique : on calcule la masse, on compare, on réduit si nécessaire."},
{i:"p135_27",u:135,t:"story",d:.55,q:"Qu'est-ce qui est juste ?",ctx:"Julie Lefèvre avait signé une RAAR au profit de sa sœur Sophie. Julie est décédée avant son père Bernard. Au décès de Bernard, Enzo, fils de Julie, vient à la succession à la place de sa mère.",sc:[{who:"Enzo",txt:"Maman a signé ce papier, pas moi. Je veux contester le legs fait à Sophie !"},{who:"Sophie",txt:"Ta mère s'était engagée, Enzo."}],o:["Non, la RAAR est opposable aux représentants du renonçant, donc à Enzo","Oui, la RAAR s'éteint au décès du renonçant, Enzo retrouve tous ses droits","Oui, si Enzo était mineur au moment où sa mère a signé la renonciation","Non, sauf si Sophie accepte de renoncer elle-même à son legs"],a:0,w:"La RAAR est opposable aux représentants du renonçant. Enzo, qui viendrait à la place de Julie, est tenu par la renonciation de sa mère."},
{i:"p135_28",u:135,t:"mcq",d:.4,q:"Un défunt sans enfant laisse son épouse. Quelle part peut-il léguer à d'autres par testament ?",o:["Les trois quarts","La moitié","La totalité","Un quart"],a:0,w:"Sans descendant, le conjoint est réservataire pour 1/4. La quotité disponible est donc de 3/4."},
{i:"p135_29",u:135,t:"slider",d:.5,q:"Six enfants. Quelle part du patrimoine le parent peut-il donner librement ?",min:0,max:50,step:1,a:25,tol:0,pre:"",un:" %",w:"À partir de trois enfants, la quotité disponible reste bloquée à 1/4, soit 25 %. Le nombre d'enfants au-delà de trois ne change que la réserve individuelle."},
{i:"p135_30",u:135,t:"story",d:.45,q:"Que risque-t-il de se passer ?",sc:[{who:"Sophie Lefèvre",txt:"Mon frère veut vendre la maison, ma sœur et moi voulons la garder, mais on n'a pas les moyens de lui racheter sa part."},{who:"Toi",me:true,txt:"Alors il faut regarder ce que la loi lui permet de faire."}],o:["Marc peut demander le partage, et le juge peut ordonner la vente aux enchères","Marc est bloqué tant que vous deux refusez, puisque vous détenez ensemble les deux tiers des droits","Marc doit attendre le décès de votre mère avant de pouvoir agir","Marc peut vendre toute la maison seul, puisqu'il est l'aîné des garçons"],a:0,w:"Nul n'est tenu de rester dans l'indivision : Marc peut demander le partage. Si le bien n'est pas partageable et que personne ne rachète, le juge peut ordonner une licitation, c'est-à-dire une vente aux enchères."},
{i:"p135_31",u:135,t:"tf",d:.45,q:"La RAAR engage le renonçant dès qu'il l'a signée, même si son parent ne l'a pas encore acceptée.",a:false,w:"Elle engage le renonçant à compter de son acceptation par le parent dont il a vocation à hériter."},
{i:"p135_32",u:135,t:"multi",d:.5,q:"Bernard, trois enfants, veut avantager Julie. Quelles solutions respectent la loi ?",o:["Léguer à Julie la quotité disponible, soit un quart","Obtenir des deux autres une RAAR au profit de Julie","Faire à Julie une donation hors part successorale dans la limite de la quotité","Déshériter Marc par un testament authentique"],a:[0,1,2],w:"On peut avantager un enfant dans la limite de la quotité disponible, ou au-delà avec une RAAR des autres. Déshériter totalement un enfant réservataire est impossible."}
