/*UNIT*/
{id:137,c:"PATRI",n:"Module 5",t:"Le démembrement : usufruit et nue-propriété",col:"--gold",ic:"🍎",guide:`
<h3>Un pommier, deux propriétaires</h3>
<div class="gstory">Hélène a choisi l'usufruit de toute la succession de Bernard. Dans le verger de la maison d'Annecy, il y a un vieux pommier. Les pommes sont à Hélène : elle les mange, les vend, en fait de la compote. Mais l'arbre appartient aux enfants : Hélène ne peut pas l'abattre ni le vendre. Le jour où Hélène disparaît, les enfants récupèrent l'arbre et les pommes, sans payer un centime de plus. Tu viens de comprendre le démembrement.</div>
<h3>Les trois attributs de la propriété</h3>
<div class="formula">Pleine propriété = usus (utiliser) + fructus (percevoir les fruits) + abusus (disposer)
Usufruit        = usus + fructus
Nue-propriété   = abusus</div>
<div class="gmnemo">« <b>Usufruit : j'Utilise et je cueille les Fruits. Nue-propriété : je suis propriétaire, mais tout Nu.</b> » Le nu-propriétaire possède l'arbre sans pouvoir en profiter. Au décès de l'usufruitier, il se « rhabille » : la pleine propriété se reconstitue, <b>sans droits de succession</b>.</div>
<h3>Qui fait quoi ?</h3>
<table><tr><th>Usufruitier</th><th>Nu-propriétaire</th></tr>
<tr><td>Habite le bien ou le loue et touche les loyers</td><td>Ne profite de rien pendant l'usufruit</td></tr>
<tr><td>Touche les dividendes des actions</td><td>Vote les décisions qui touchent au capital</td></tr>
<tr><td>Paie l'entretien courant et la taxe foncière</td><td>Paie les grosses réparations (toiture, gros murs)</td></tr>
<tr><td>Déclare le bien à l'IFI, en pleine propriété</td><td>Récupère la pleine propriété à la fin</td></tr></table>
<h3>Viager, temporaire, quasi-usufruit</h3>
<ul><li><b>Usufruit viager</b> : le principe. Il s'éteint au décès de l'usufruitier.</li>
<li><b>Usufruit temporaire</b> : durée fixée à l'avance (par exemple 5 ou 10 ans). Accordé à une société, il ne peut pas dépasser 30 ans. Exemple : un parent achète un studio et en donne l'usufruit pendant 5 ans à sa fille étudiante.</li>
<li><b>Quasi-usufruit</b> : usufruit sur des biens qui se consomment, comme l'argent. L'usufruitier peut dépenser la somme, mais à la fin il doit <b>restituer l'équivalent</b>. Au décès du quasi-usufruitier, ses héritiers nus-propriétaires détiennent une <b>créance de restitution</b> sur sa succession.</li></ul>
<div class="gtrap">Depuis les successions ouvertes le 29 décembre 2023 (article 774 bis du CGI), la dette de restitution née d'une <b>donation d'argent avec réserve de quasi-usufruit</b> n'est plus déductible de la succession. Elle reste déductible quand le quasi-usufruit vient de la loi (option du conjoint) ou d'une donation entre époux.</div>
<h3>Comment on calcule : le barème de l'article 669 du CGI</h3>
<table><tr><th>Âge de l'usufruitier</th><th>Usufruit</th><th>Nue-propriété</th></tr>
<tr><td>moins de 21 ans</td><td>90 %</td><td>10 %</td></tr>
<tr><td>21 à 30 ans</td><td>80 %</td><td>20 %</td></tr>
<tr><td>31 à 40 ans</td><td>70 %</td><td>30 %</td></tr>
<tr><td>41 à 50 ans</td><td>60 %</td><td>40 %</td></tr>
<tr><td>51 à 60 ans</td><td>50 %</td><td>50 %</td></tr>
<tr><td>61 à 70 ans</td><td>40 %</td><td>60 %</td></tr>
<tr><td>71 à 80 ans</td><td>30 %</td><td>70 %</td></tr>
<tr><td>81 à 90 ans</td><td>20 %</td><td>80 %</td></tr>
<tr><td>91 ans et plus</td><td>10 %</td><td>90 %</td></tr></table>
<div class="gmnemo">Usufruit = <b>110 moins la dizaine du dessus</b>. Tu as 64 ans : la dizaine du dessus, c'est 70. 110 - 70 = <b>40 %</b>. À 45 ans : 110 - 50 = 60 %. À 30 ans pile : 110 - 30 = 80 %. Plus l'usufruitier est jeune, plus il va profiter longtemps, plus son usufruit vaut cher.</div>
<p>Usufruit temporaire : <b>23 % par période de 10 ans</b>, sans tenir compte de l'âge (module 6).</p>
<h3>À quoi ça sert : donner la nue-propriété tôt</h3>
<div class="gstory">Bernard, 58 ans, donne à ses enfants la nue-propriété d'un appartement de 450 000 € et garde l'usufruit. Il continue d'encaisser les loyers. Fiscalement, la donation ne porte que sur 50 % (il a entre 51 et 60 ans), soit 225 000 €. À son décès, les enfants deviennent pleins propriétaires de 450 000 € (ou plus, si le bien a pris de la valeur) sans payer un euro de plus.</div>
<p>D'où la règle du cours : <b>plus on donne la nue-propriété tôt, moins elle vaut, moins on paie de droits</b>. Et toute la plus-value future échappe aux droits.</p>
<div class="gtrap">Céder un usufruit temporaire contre un prix n'est pas « sans fiscalité » : depuis 2013, le prix de la première cession d'un usufruit temporaire est imposé chez le vendeur comme un revenu (article 13, 5 du CGI). Pour une société, en revanche, l'usufruit acquis est amortissable.</div>`},
/*EXOS*/
{i:"p137_01",u:137,t:"match",d:.2,nw:"Les attributs de la propriété",q:"Associe chaque attribut à ce qu'il permet.",p:[["Usus","Utiliser le bien, l'habiter"],["Fructus","Percevoir les loyers, les dividendes"],["Abusus","Vendre, donner, détruire"],["Nue-propriété","Abusus seul, sans jouissance"]],w:"Usufruit = usus + fructus. Nue-propriété = abusus. Ensemble, ils reforment la pleine propriété."},
{i:"p137_02",u:137,t:"story",d:.3,q:"Que réponds-tu à Hélène ?",sc:[{who:"Hélène Lefèvre",txt:"J'ai l'usufruit de la maison d'Annecy. Je peux la louer l'été à des touristes ?"},{who:"Toi",me:true,txt:"Oui, et les loyers seront pour vous."},{who:"Hélène Lefèvre",txt:"Et la vendre pour acheter un appartement plus petit à Lyon ?"}],o:["Pas seule : vendre relève de l'abusus, il faut l'accord des enfants","Oui, l'usufruitier peut vendre, à condition de réinvestir le prix dans un bien","Oui, dès lors que la vente rapporte plus que la valeur fiscale de l'usufruit","Non, jamais : un bien démembré ne peut être vendu qu'au décès de l'usufruitier"],a:0,w:"L'usufruitier utilise et perçoit les fruits, mais ne dispose pas du bien. Une vente se fait avec l'accord des nus-propriétaires, le prix étant ensuite réparti ou remployé."},
{i:"p137_03",u:137,t:"slider",d:.3,nw:"Le barème de l'article 669",q:"Quelle est la valeur de l'usufruit pour un usufruitier de 64 ans ?",min:10,max:90,step:10,a:40,tol:0,pre:"",un:" %",w:"110 moins la dizaine du dessus : 110 - 70 = 40 %. La nue-propriété vaut donc 60 %."},
{i:"p137_04",u:137,t:"slider",d:.35,q:"Quelle est la valeur de la nue-propriété si l'usufruitier a 45 ans ?",min:10,max:90,step:10,a:40,tol:0,pre:"",un:" %",w:"Usufruit à 45 ans : 110 - 50 = 60 %. Nue-propriété : 100 - 60 = 40 %."},
{i:"p137_05",u:137,t:"num",d:.4,ctx:"Bernard, 58 ans, donne à ses enfants la nue-propriété d'un appartement de 450 000 €. Il conserve l'usufruit.",q:"Sur quelle valeur la donation est-elle taxée, en euros ?",a:225000,tol:1,un:" €",h:"Entre 51 et 60 ans",w:"À 58 ans, usufruit 50 %, nue-propriété 50 %. 450 000 × 50 % = 225 000 €."},
{i:"p137_06",u:137,t:"sort",d:.35,q:"Qui paie quoi dans une maison démembrée ?",bins:["Usufruitier","Nu-propriétaire"],it:[["La réfection complète de la toiture",1],["L'entretien du jardin",0],["La taxe foncière",0],["La reconstruction d'un gros mur",1],["Le remplacement de la chaudière usée par l'usage",0]],w:"Grosses réparations (toiture entière, gros murs, poutres) : nu-propriétaire. Entretien courant et taxe foncière : usufruitier."},
{i:"p137_07",u:137,t:"tf",d:.25,q:"Au décès de l'usufruitier, les nus-propriétaires paient des droits de succession pour récupérer l'usufruit.",a:false,w:"L'usufruit s'éteint et rejoint la nue-propriété sans aucun droit. C'est tout l'intérêt de donner la nue-propriété de son vivant."},
{i:"p137_08",u:137,t:"story",d:.45,nw:"Le quasi-usufruit",q:"Qu'est-ce qui est juste ?",ctx:"Hélène a l'usufruit de toute la succession de Bernard, dont 200 000 € sur un compte bancaire. Les enfants ont la nue-propriété.",sc:[{who:"Hélène",txt:"Je voudrais utiliser cet argent pour refaire la cuisine et voyager. J'ai le droit ?"},{who:"Marc",txt:"Maman, c'est à nous, cet argent, tu n'as que l'usufruit !"}],o:["Hélène peut le dépenser ; ses enfants auront une créance de 200 000 € sur sa succession","Hélène ne peut toucher que les intérêts : le capital appartient aux enfants","Hélène peut dépenser la moitié, l'autre moitié restant bloquée pour les enfants","Hélène doit rembourser chaque dépense à ses enfants dans l'année qui suit"],a:0,w:"Sur de l'argent, l'usufruit est un quasi-usufruit : Hélène peut consommer, mais à sa mort les enfants récupèrent l'équivalent, par une dette de restitution sur sa succession."},
{i:"p137_09",u:137,t:"multi",d:.45,q:"Quels biens se prêtent au quasi-usufruit ?",o:["Une somme d'argent sur un compte","Un stock de vin destiné à être bu","Un portefeuille de titres, si la convention le permet","Une maison de famille"],a:[0,1,2],w:"Le quasi-usufruit porte sur des choses consomptibles, comme l'argent ou des denrées, et par convention sur des titres. Une maison ne se consomme pas : usufruit classique."},
{i:"p137_10",u:137,t:"fill",d:.35,q:"À la fin d'un quasi-usufruit, l'usufruitier doit ___ une valeur équivalente.",o:["restituer","consommer","réinvestir","capitaliser"],a:0,w:"Obligation de restitution équivalente : c'est la contrepartie du droit de consommer."},
{i:"p137_11",u:137,t:"num",d:.5,ctx:"Hélène, 64 ans, a opté pour l'usufruit de toute la succession de Bernard, évaluée à 700 000 €.",q:"Quelle est la valeur fiscale de son usufruit, en euros ?",a:280000,tol:1,un:" €",h:"Barème de l'article 669",w:"À 64 ans, usufruit 40 %. 700 000 × 40 % = 280 000 €. Les enfants reçoivent la nue-propriété : 420 000 €."},
{i:"p137_12",u:137,t:"story",d:.5,q:"Quel conseil donnes-tu à Thomas ?",ctx:"Thomas Garnier a 52 ans. Il possède un immeuble de rapport de 800 000 € dont il veut garder les loyers jusqu'à sa retraite, tout en préparant la transmission à sa fille Léa.",sc:[{who:"Thomas",txt:"Je pensais attendre mes 75 ans pour donner l'immeuble à Léa, j'aurai plus de visibilité."},{who:"Toi",me:true,txt:"Attendre a un coût précis. Regardons les chiffres."}],o:["Donner la nue-propriété maintenant : taxée sur 50 %, contre 70 % à 75 ans","Attendre 75 ans : l'immeuble aura pris de la valeur, les droits seront moindres","Donner l'usufruit à Léa maintenant et garder la nue-propriété jusqu'à 75 ans","Vendre l'immeuble et donner le prix, pour éviter le barème de l'article 669"],a:0,w:"À 52 ans, la nue-propriété vaut 50 %. À 75 ans, elle vaudra 70 %. Et la plus-value entre-temps échappe aux droits. Plus on donne tôt, moins la nue-propriété coûte."},
{i:"p137_13",u:137,t:"tf",d:.35,q:"Plus l'usufruitier est jeune, plus la valeur de l'usufruit est élevée.",a:true,w:"Un jeune usufruitier va profiter du bien plus longtemps : son usufruit vaut plus. À moins de 21 ans, il vaut 90 %."},
{i:"p137_14",u:137,t:"order",d:.4,q:"Classe ces usufruitiers, de l'usufruit le plus cher au moins cher.",it:["Une étudiante de 19 ans","Un cadre de 35 ans","Une retraitée de 66 ans","Un veuf de 88 ans"],w:"90 %, 70 %, 40 %, 20 %. L'usufruit diminue de 10 points par tranche de dix ans."},
{i:"p137_15",u:137,t:"mcq",d:.45,q:"Qui déclare un bien démembré à l'IFI, en principe ?",o:["L'usufruitier, pour la pleine propriété","Le nu-propriétaire, pour la pleine propriété","Chacun, au prorata du barème de l'article 669","Personne, un bien démembré est exonéré d'IFI"],a:0,w:"En principe, l'usufruitier déclare la pleine propriété à l'IFI. D'où l'intérêt de certaines donations temporaires d'usufruit (module 6)."},
{i:"p137_16",u:137,t:"story",d:.4,q:"Qui touche le dividende ?",ctx:"Léa détient la nue-propriété de 1 000 actions, son père Thomas en a l'usufruit. La société verse un dividende de 5 € par action.",sc:[{who:"Léa",txt:"Ce sont mes actions, donc les 5 000 € de dividende sont pour moi."},{who:"Thomas",txt:"Tu es sûre ?"}],o:["Thomas, l'usufruitier : le dividende est un fruit","Léa, la nue-propriétaire : ce sont ses actions","Moitié chacun, comme dans toute indivision familiale","Personne : il est mis en réserve jusqu'à la fin de l'usufruit"],a:0,w:"Le dividende ordinaire est un fruit : il revient à l'usufruitier. Le nu-propriétaire, lui, récupérera les actions en pleine propriété à la fin."},
{i:"p137_17",u:137,t:"slider",d:.45,q:"Durée maximale d'un usufruit accordé à une société ?",min:5,max:99,step:1,a:30,tol:0,pre:"",un:" ans",w:"Trente ans pour une personne morale. Pour une personne physique, l'usufruit peut être viager ou fixé à la durée qu'on veut."},
{i:"p137_18",u:137,t:"multi",d:.5,q:"Quels sont les usages classiques du démembrement en gestion de patrimoine ?",o:["Donner la nue-propriété tout en gardant les revenus","Protéger le conjoint survivant par l'usufruit","Loger un enfant étudiant grâce à un usufruit temporaire","Faire disparaître définitivement le bien de toute succession"],a:[0,1,2],w:"Garder les revenus, protéger le conjoint, aider un enfant sur une durée. Le démembrement ne fait rien disparaître : il déplace la valeur dans le temps."},
{i:"p137_19",u:137,t:"num",d:.5,ctx:"Colette Roussel, 82 ans, veut donner à son neveu la nue-propriété d'un appartement de 300 000 €, en gardant l'usufruit.",q:"Quelle est la valeur fiscale de la nue-propriété donnée, en euros ?",a:240000,tol:1,un:" €",h:"Entre 81 et 90 ans",w:"À 82 ans, l'usufruit vaut 20 %, la nue-propriété 80 %. 300 000 × 80 % = 240 000 €. Donner si tard ne fait presque plus économiser."},
{i:"p137_20",u:137,t:"tf",d:.5,q:"Depuis fin 2023, la dette de restitution née d'une donation d'argent avec réserve de quasi-usufruit n'est plus déductible de la succession du donateur.",a:true,w:"Article 774 bis du CGI, pour les successions ouvertes depuis le 29 décembre 2023. Les quasi-usufruits légaux, comme celui du conjoint, restent déductibles."},
{i:"p137_21",u:137,t:"story",d:.55,q:"La créance des enfants est-elle déductible ?",ctx:"Hélène avait opté pour l'usufruit légal sur la succession de Bernard, dont 200 000 € de liquidités qu'elle a dépensés. Elle décède à son tour.",sc:[{who:"Sophie",txt:"On a une créance de 200 000 € sur la succession de maman. Le notaire va la déduire ?"},{who:"Toi",me:true,txt:"La règle a changé récemment, mais pas pour vous."}],o:["Oui : un quasi-usufruit issu de l'option légale du conjoint reste déductible","Non : depuis 2023, aucune dette de restitution n'est plus jamais déductible","Oui, mais seulement pour la moitié, l'autre moitié étant réputée consommée","Non, parce que les 200 000 € ont été dépensés et non placés sur un compte"],a:0,w:"L'article 774 bis vise les donations d'argent avec quasi-usufruit réservé. Il exclut expressément les usufruits issus de l'option du conjoint (article 757) ou d'une donation entre époux."},
{i:"p137_22",u:137,t:"tiles",d:.35,q:"Reconstitue la formule mémo du barème fiscal.",a:["Usufruit","=","110","moins","la","dizaine","du","dessus"],dd:["100","plus","âge"],w:"64 ans : 110 - 70 = 40 %. Tu n'as plus besoin de réciter le tableau."},
{i:"p137_23",u:137,t:"match",d:.4,q:"Associe chaque âge de l'usufruitier à la valeur de la nue-propriété.",p:[["25 ans","20 %"],["55 ans","50 %"],["68 ans","60 %"],["93 ans","90 %"]],w:"La nue-propriété, c'est 100 moins l'usufruit. Plus l'usufruitier vieillit, plus la nue-propriété vaut cher."},
{i:"p137_24",u:137,t:"mcq",d:.4,q:"Une personne de 30 ans pile est usufruitière. Quelle valeur fiscale pour son usufruit ?",o:["80 %","70 %","90 %","60 %"],a:0,w:"30 ans relève de la tranche 21 à 30 ans : 80 %. La formule donne 110 - 30 = 80. À 31 ans, on passe à 70 %."},
{i:"p137_25",u:137,t:"story",d:.45,q:"Que penses-tu de ce montage ?",sc:[{who:"Thomas",txt:"J'ai lu qu'en cédant l'usufruit temporaire de mes bureaux à ma société, j'encaisse un capital sans aucun impôt."},{who:"Toi",me:true,txt:"La société y gagne, c'est vrai. Pour toi, c'est moins rose."}],o:["Le prix de la première cession est imposé chez toi comme un revenu","C'est exact : un capital d'usufruit n'est jamais imposable chez le cédant","Le prix est taxé à 60 %, comme une transmission entre non-parents","Le prix est exonéré si l'usufruit dure moins de dix ans"],a:0,w:"Depuis 2013, la première cession d'un usufruit temporaire est imposée chez le cédant comme un revenu. La société, elle, peut amortir l'usufruit acquis."},
{i:"p137_26",u:137,t:"sort",d:.4,q:"Classe chaque droit selon celui qui l'exerce.",bins:["Usufruitier","Nu-propriétaire"],it:[["Habiter la maison",0],["Vendre la nue-propriété à un tiers",1],["Encaisser les loyers",0],["Récupérer la pleine propriété à la fin",1],["Toucher les dividendes ordinaires",0]],w:"L'usufruitier profite, le nu-propriétaire attend et peut seulement céder ses propres droits."},
{i:"p137_27",u:137,t:"tf",d:.4,q:"Le nu-propriétaire peut vendre sa nue-propriété sans l'accord de l'usufruitier.",a:true,w:"Chacun peut céder son propre droit. Le nu-propriétaire vend la nue-propriété, l'acquéreur attendra la fin de l'usufruit. Vendre la pleine propriété, en revanche, suppose l'accord des deux."},
{i:"p137_28",u:137,t:"num",d:.55,ctx:"Un bien de 600 000 € est démembré : l'usufruitier a 73 ans.",q:"Quelle est la valeur de la nue-propriété, en euros ?",a:420000,tol:1,un:" €",h:"71 à 80 ans",w:"Usufruit 30 %, nue-propriété 70 %. 600 000 × 70 % = 420 000 €."},
{i:"p137_29",u:137,t:"story",d:.4,q:"Quelle solution proposes-tu ?",sc:[{who:"Bernard",txt:"Sophie commence ses études de médecine à Grenoble, pour six ans. J'ai acheté un studio là-bas."},{who:"Bernard",txt:"Je voudrais qu'elle en profite sans lui donner le studio définitivement."}],o:["Lui donner l'usufruit temporaire du studio pour la durée de ses études","Lui donner la nue-propriété, pour qu'elle puisse l'habiter gratuitement","Le lui vendre à un euro symbolique avec une clause de retour","Lui donner le studio en pleine propriété et le récupérer par testament"],a:0,w:"L'usufruit temporaire répond exactement à ce besoin : Sophie habite ou loue le studio pendant six ans, puis Bernard récupère la pleine propriété."},
{i:"p137_30",u:137,t:"fill",d:.45,q:"Un usufruit sans durée fixée s'éteint au ___ de l'usufruitier.",o:["décès","départ","mariage","divorce"],a:0,w:"C'est l'usufruit viager, le principe. L'usufruit temporaire s'éteint, lui, à l'échéance prévue."},
{i:"p137_31",u:137,t:"multi",d:.55,q:"Bernard, 58 ans, donne la nue-propriété d'un bien de 450 000 € qui vaudra 600 000 € à son décès. Quelles affirmations sont justes ?",o:["La donation est taxée sur 225 000 €","À son décès, les enfants ne paient rien sur la reconstitution de la pleine propriété","La plus-value de 150 000 € échappe aux droits de succession","Les enfants paieront des droits sur les 150 000 € de plus-value"],a:[0,1,2],w:"Base taxable : 50 % de 450 000. À l'extinction de l'usufruit, rien n'est dû, plus-value comprise. C'est le double avantage de donner la nue-propriété tôt."},
{i:"p137_32",u:137,t:"mcq",d:.5,q:"Quel est le trio attendu par le professeur sur le démembrement ?",o:["Ce que c'est, à quoi ça sert, comment ça se calcule","Ce que c'est, qui le signe, combien de temps il dure","À quoi ça sert, qui le paie, quand il faut le déclarer","Comment ça se calcule, où on le déclare, qui le contrôle"],a:0,w:"Définition, utilité, calcul. Si tu sais faire les trois sur un cas concret, le démembrement est acquis pour l'examen."}
