/*UNIT*/
{id:138,c:"PATRI",n:"Module 6",t:"Les donations : types, abattements et barème",col:"--gold",ic:"🎁",guide:`
<h3>Donner, c'est définitif</h3>
<div class="gstory">Bernard veut aider ses enfants maintenant, « pas quand je serai mort et qu'ils auront cinquante ans ». Il hésite entre faire des virements, passer chez le notaire, tout donner d'un coup ou petit à petit. Chaque option a un prix, parfois caché quinze ans plus tard. Ce module est la carte de ce terrain.</div>
<p>Une <b>donation</b> transmet un bien de son vivant, <b>sans contrepartie</b>. Elle est <b>irrévocable</b> : on ne reprend pas ce qu'on a donné (sauf ingratitude grave ou inexécution d'une charge). Pour donner, il faut être <b>majeur</b> et <b>sain d'esprit</b>. En principe, la donation se fait devant notaire.</p>
<h3>Les formes de donation</h3>
<table><tr><th>Forme</th><th>À retenir</th></tr>
<tr><td><b>Don manuel</b></td><td>Remise de la main à la main (virement, chèque, objet), sans notaire. À déclarer au fisc. <b>Inconvénient</b> : rapporté à la succession et <b>réévalué</b>, avec le risque qu'un enfant doive « rendre » de l'argent aux autres.</td></tr>
<tr><td><b>Donation simple</b></td><td>Acte notarié. En avance de part successorale ou hors part.</td></tr>
<tr><td><b>Donation-partage</b></td><td>Donne ET partage en même temps. Les valeurs sont <b>figées au jour de la donation</b>. À privilégier quand on donne beaucoup ou à plusieurs enfants.</td></tr>
<tr><td><b>Donation en indivision</b></td><td>Un même bien donné à plusieurs, qui le possèdent ensemble.</td></tr>
<tr><td><b>Avec réserve d'usufruit</b></td><td>On donne la nue-propriété, on garde les revenus (module 5).</td></tr>
<tr><td><b>Avec réversion d'usufruit</b></td><td>Le donateur garde l'usufruit, puis il passe à son conjoint après son décès.</td></tr></table>
<h3>En avance de part ou hors part ?</h3>
<ul><li><b>En avance de part successorale</b> : c'est le principe entre parent et enfant. Au décès, on la « rapporte » : elle compte comme un acompte sur l'héritage, pour l'égalité entre enfants.</li>
<li><b>Hors part successorale</b> : un avantage voulu, qui s'impute sur la quotité disponible. Pas de rapport.</li></ul>
<div class="gstory">En 2010, Bernard fait un virement de 100 000 € à Marc pour son appartement. En 2030, l'appartement vaut 250 000 €. Au décès de Bernard, Marc doit rapporter <b>250 000 €</b> et non 100 000 € : la somme a servi à acheter un bien, on retient la valeur du bien. Julie et Sophie n'ont rien reçu : Marc risque de devoir leur verser une soulte. Avec une donation-partage, la valeur serait restée figée à 100 000 €.</div>
<div class="gmnemo">« <b>Le don manuel se réveille au décès, la donation-partage dort pour toujours.</b> » Le don simple est réévalué au jour du partage. La donation-partage, elle, garde la photo du jour où elle a été signée.</div>
<h3>Les abattements : ce qu'on donne sans payer</h3>
<table><tr><th>Bénéficiaire</th><th>Abattement (tous les 15 ans)</th></tr>
<tr><td>Enfant (par parent)</td><td>100 000 €</td></tr>
<tr><td>Petit-enfant</td><td>31 865 €</td></tr>
<tr><td>Arrière-petit-enfant</td><td>5 310 €</td></tr>
<tr><td>Époux ou partenaire de PACS</td><td>80 724 €</td></tr>
<tr><td>Frère ou sœur</td><td>15 932 €</td></tr>
<tr><td>Neveu ou nièce</td><td>7 967 €</td></tr>
<tr><td>Personne handicapée</td><td>159 325 €, cumulable</td></tr></table>
<p>En plus : le <b>don familial de sommes d'argent</b>, exonéré jusqu'à <b>31 865 €</b>, si le donateur a <b>moins de 80 ans</b> et que le bénéficiaire est <b>majeur</b> (enfant, petit-enfant, arrière-petit-enfant, ou neveu et nièce à défaut de descendant). Il se cumule avec l'abattement classique.</p>
<div class="gmnemo">« <b>Cent mille par enfant, trente et un huit six cinq par petit-enfant, et quinze ans d'attente.</b> » Un couple peut donner 2 × 100 000 € par enfant, plus 2 × 31 865 € en argent s'il a moins de 80 ans : <b>263 730 € par enfant, sans un euro de droits</b>, tous les quinze ans.</div>
<h3>Le barème en ligne directe (parents et enfants)</h3>
<table><tr><th>Part taxable après abattement</th><th>Taux</th></tr>
<tr><td>jusqu'à 8 072 €</td><td>5 %</td></tr>
<tr><td>8 072 à 12 109 €</td><td>10 %</td></tr>
<tr><td>12 109 à 15 932 €</td><td>15 %</td></tr>
<tr><td>15 932 à 552 324 €</td><td>20 %</td></tr>
<tr><td>552 324 à 902 838 €</td><td>30 %</td></tr>
<tr><td>902 838 à 1 805 677 €</td><td>40 %</td></tr>
<tr><td>au-delà</td><td>45 %</td></tr></table>
<div class="formula">Raccourci d'examen, entre 15 932 € et 552 324 € taxables :
droits = 20 % × part taxable - 1 805,65 €</div>
<p>Frères et sœurs : 35 % jusqu'à 24 430 €, puis 45 %. Parents jusqu'au 4e degré : 55 %. Au-delà et non-parents : 60 %. Ce barème est le même pour les donations et les successions.</p>
<h3>Le rappel fiscal de 15 ans</h3>
<p>Les abattements se rechargent tous les <b>15 ans</b>. Une donation consentie moins de 15 ans avant une nouvelle donation, ou avant le décès, a déjà « consommé » l'abattement.</p>
<div class="gtrap">Les notes disent qu'une donation faite moins de 15 ans avant le décès « n'a aucun effet » sur les droits de succession. C'est trop fort. Elle consomme l'abattement, c'est vrai, mais elle garde trois intérêts : la valeur est <b>figée</b> au jour de la donation, la <b>plus-value future</b> échappe aux droits, et le donateur peut <b>payer lui-même les droits</b> à la place de ses enfants sans que ce soit taxé comme un supplément de donation, ce qui réduit d'autant sa succession.</div>`},
/*EXOS*/
{i:"p138_01",u:138,t:"multi",d:.25,nw:"Qu'est-ce qu'une donation ?",q:"Quelles caractéristiques définissent une donation ?",o:["Elle se fait sans contrepartie","Elle est en principe irrévocable","Le donateur doit être majeur et sain d'esprit","Le donateur peut la reprendre s'il change d'avis"],a:[0,1,2],w:"Absence de contrepartie, irrévocabilité, capacité du donateur. On ne reprend pas un cadeau, sauf ingratitude grave ou charge non exécutée."},
{i:"p138_02",u:138,t:"story",d:.3,q:"Que dis-tu à Bernard ?",sc:[{who:"Bernard",txt:"J'ai donné 30 000 € à Julie l'an dernier. Maintenant qu'elle ne vient plus me voir, je veux les récupérer."},{who:"Toi",me:true,txt:"Je vous comprends, mais la loi est claire sur ce point."}],o:["Une donation est irrévocable ; une brouille ne suffit pas à la reprendre","Vous pouvez la reprendre dans les cinq ans, par simple courrier recommandé","Vous pouvez la reprendre si vous n'aviez pas déclaré le don au fisc","Vous pouvez la reprendre à condition de rembourser les droits payés"],a:0,w:"Irrévocabilité. Seules des causes graves, comme l'ingratitude au sens juridique (sévices, injure grave, refus d'aliments), permettent une révocation par le juge."},
{i:"p138_03",u:138,t:"match",d:.3,nw:"Les abattements",q:"Associe chaque bénéficiaire à son abattement en donation.",p:[["Enfant","100 000 €"],["Petit-enfant","31 865 €"],["Époux ou partenaire de PACS","80 724 €"],["Frère ou sœur","15 932 €"]],w:"Ces abattements se rechargent tous les 15 ans, par donateur et par bénéficiaire."},
{i:"p138_04",u:138,t:"num",d:.45,nw:"Le barème en ligne directe",q:"Bernard donne 150 000 € à Marc, sans donation antérieure. Combien de droits Marc doit-il payer, en euros ? (arrondi à l'euro)",a:8194,tol:2,un:" €",h:"Abattement, puis raccourci 20 % - 1 805,65",w:"150 000 - 100 000 = 50 000 taxables. 20 % × 50 000 - 1 805,65 = 8 194,35 €."},
{i:"p138_05",u:138,t:"story",d:.4,nw:"Le don familial de sommes d'argent",q:"Combien Hélène et Bernard peuvent-ils donner à Sophie, en argent, sans aucun droit ?",ctx:"Bernard a 67 ans, Hélène 64 ans. Sophie a 31 ans. Aucune donation depuis quinze ans.",sc:[{who:"Sophie",txt:"J'achète ma première maison. Vous pourriez m'aider ?"},{who:"Bernard",txt:"Combien on peut te donner sans que le fisc s'en mêle ?"}],o:["263 730 € : 2 × 100 000 € plus 2 × 31 865 € de dons familiaux","200 000 € : 100 000 € par parent, sans rien d'autre à ajouter","131 865 € au total, car le don familial ne se cumule pas entre parents","231 865 € : deux abattements classiques et un seul don familial pour le couple"],a:0,w:"Chaque parent : 100 000 € d'abattement + 31 865 € de don familial (moins de 80 ans, enfant majeur). Deux parents : 263 730 €."},
{i:"p138_06",u:138,t:"multi",d:.45,q:"Quelles conditions pour l'exonération du don familial de 31 865 € ?",o:["Donateur de moins de 80 ans","Bénéficiaire majeur ou émancipé","Don en argent","Bénéficiaire habitant chez le donateur"],a:[0,1,2],w:"Moins de 80 ans, bénéficiaire majeur (enfant, petit-enfant, arrière-petit-enfant, ou neveu et nièce à défaut de descendance), don de sommes d'argent."},
{i:"p138_07",u:138,t:"slider",d:.3,q:"Tous les combien d'années les abattements de donation se rechargent-ils ?",min:5,max:30,step:1,a:15,tol:0,pre:"",un:" ans",w:"Quinze ans : c'est le rappel fiscal. Donner tôt permet de profiter plusieurs fois des abattements."},
{i:"p138_08",u:138,t:"story",d:.5,nw:"Don manuel et rapport",q:"Qu'est-ce que Marc risque au décès de Bernard ?",ctx:"En 2010, Bernard a viré 100 000 € à Marc, sans notaire, pour acheter un appartement. Julie et Sophie n'ont rien reçu. Au décès de Bernard en 2030, l'appartement vaut 250 000 €.",sc:[{who:"Marc",txt:"Papa m'a donné cent mille euros. Je rapporte cent mille, point."},{who:"Julie",txt:"Ton appartement en vaut deux cent cinquante mille aujourd'hui."}],o:["Le rapport porte sur 250 000 € : la somme a servi à acquérir un bien","Le rapport porte sur 100 000 €, puisqu'un don d'argent n'est jamais réévalué","Rien : un don manuel non déclaré échappe définitivement au rapport","Le rapport porte sur 175 000 €, moyenne du don et de la valeur actuelle"],a:0,w:"Une somme d'argent employée à acquérir un bien se rapporte à la valeur de ce bien au jour du partage. Marc peut devoir une soulte à ses sœurs. La donation-partage aurait figé la valeur."},
{i:"p138_09",u:138,t:"sort",d:.4,q:"Classe chaque caractéristique selon la forme de donation.",bins:["Don manuel","Donation-partage"],it:[["Se fait sans notaire",0],["Valeurs figées au jour de la donation",1],["Réévalué au jour du partage successoral",0],["Évite les conflits entre enfants au décès",1],["Simple virement bancaire possible",0]],w:"Le don manuel est simple mais se réveille au décès. La donation-partage est notariée et figée pour toujours."},
{i:"p138_10",u:138,t:"tf",d:.3,q:"Un don manuel n'a jamais besoin d'être déclaré à l'administration fiscale.",a:false,w:"Le don manuel doit être déclaré, au plus tard quand il est révélé. Les droits sont dus au-delà des abattements."},
{i:"p138_11",u:138,t:"mcq",d:.4,q:"Quand privilégier la donation-partage selon ton cours ?",o:["Pour des sommes importantes ou plusieurs enfants","Pour un petit cadeau d'anniversaire","Uniquement pour un enfant unique","Uniquement pour des biens immobiliers"],a:0,w:"Elle fige les valeurs et évite les rapports entre enfants : plus il y a d'enjeux et de bénéficiaires, plus elle protège la paix familiale."},
{i:"p138_12",u:138,t:"num",d:.5,ctx:"Hélène donne à sa sœur Monique 50 000 €, sans donation antérieure. Barème frères et sœurs : 35 % jusqu'à 24 430 €, 45 % au-delà.",q:"Combien Monique paiera-t-elle de droits, en euros ? (arrondi à l'euro)",a:12888,tol:2,un:" €",h:"Abattement frère et sœur, puis deux tranches",w:"50 000 - 15 932 = 34 068 taxables. 24 430 × 35 % = 8 550,50 et 9 638 × 45 % = 4 337,10. Total : 12 887,60 €."},
{i:"p138_13",u:138,t:"fill",d:.35,q:"Entre un parent et son enfant, une donation est en principe consentie en ___ de part successorale.",o:["avance","dehors","complément","remplacement"],a:0,w:"En avance de part : c'est un acompte sur l'héritage, rapporté au décès pour l'égalité entre enfants. Sauf clause « hors part successorale »."},
{i:"p138_14",u:138,t:"story",d:.45,q:"Comment qualifier la donation ?",sc:[{who:"Bernard",txt:"Je veux donner 80 000 € à Sophie en plus de sa part, parce qu'elle s'est occupée de sa grand-mère pendant des années. Je ne veux pas que ses frère et sœur puissent le lui reprocher au partage."},{who:"Toi",me:true,txt:"Alors il faut le dire expressément dans l'acte."}],o:["Hors part successorale : elle s'imputera sur la quotité disponible","En avance de part successorale : elle sera rapportée au partage","En donation-partage : elle sera figée et partagée entre les trois","En don manuel : il suffit de ne pas le déclarer pour qu'il soit libre"],a:0,w:"Une donation hors part successorale n'est pas rapportable : c'est un avantage voulu. Elle s'impute sur la quotité disponible, donc dans la limite de celle-ci."},
{i:"p138_15",u:138,t:"slider",d:.4,q:"Jusqu'à quel âge du donateur le don familial de sommes d'argent est-il exonéré ?",min:60,max:95,step:1,a:80,tol:0,pre:"moins de ",un:" ans",w:"Moins de 80 ans au jour du don. Au-delà, seul l'abattement classique reste disponible."},
{i:"p138_16",u:138,t:"order",d:.4,q:"Remets dans l'ordre le calcul des droits de donation.",it:["Déterminer la valeur du bien donné","Retirer l'abattement du lien de parenté, s'il n'a pas été consommé depuis 15 ans","Appliquer le barème par tranches à la part taxable","Obtenir les droits à payer"],w:"Valeur, abattement, barème. Et toujours vérifier les donations des quinze dernières années."},
{i:"p138_17",u:138,t:"tf",d:.45,q:"Les droits de donation payés par le donateur à la place du donataire sont taxés comme un supplément de donation.",a:false,w:"La prise en charge des droits par le donateur n'est pas considérée comme une donation supplémentaire. C'est un moyen légal de réduire sa future succession."},
{i:"p138_18",u:138,t:"story",d:.55,q:"La donation garde-t-elle un intérêt ?",ctx:"Colette, 82 ans, envisage de donner 90 000 € à son neveu Loïc. Son médecin est pessimiste : elle ne vivra sans doute pas 15 ans de plus.",sc:[{who:"Colette",txt:"Mon notaire dit que si je meurs dans les quinze ans, ça ne servira à rien. Alors à quoi bon ?"},{who:"Toi",me:true,txt:"Ce n'est pas tout à fait « à rien »."}],o:["Si elle paie elle-même les droits, sa succession diminue d'autant, sans taxe en plus","Aucun : une donation rappelée est intégralement taxée une seconde fois au jour du décès de Colette","Aucun, sauf si Loïc renonce ensuite à la succession de sa tante","Elle efface les droits futurs, car un neveu est exonéré après 80 ans"],a:0,w:"L'abattement est consommé, mais la valeur est figée et Colette peut payer les droits elle-même : ces droits sortent de sa succession sans être taxés comme un supplément de donation. C'est le « sauf si » de tes notes."},
{i:"p138_19",u:138,t:"mcq",d:.45,q:"Quel abattement pour une donation à un arrière-petit-enfant ?",o:["5 310 €","31 865 €","7 967 €","1 594 €"],a:0,w:"5 310 € pour un arrière-petit-enfant, 31 865 € pour un petit-enfant, 7 967 € pour un neveu ou une nièce."},
{i:"p138_20",u:138,t:"num",d:.55,ctx:"Il y a 8 ans, Bernard a donné 60 000 € à Julie. Aujourd'hui, il lui donne 100 000 €.",q:"Quelle est la part taxable de la nouvelle donation, en euros ?",a:60000,tol:1,un:" €",h:"Il reste combien d'abattement ?",w:"Moins de 15 ans : l'abattement de 100 000 € a déjà servi pour 60 000. Il reste 40 000. 100 000 - 40 000 = 60 000 € taxables."},
{i:"p138_21",u:138,t:"story",d:.45,q:"Quel conseil ?",sc:[{who:"Hélène",txt:"On a trois enfants et une grosse somme à donner. Je voudrais surtout qu'ils ne se déchirent pas le jour de notre décès."},{who:"Toi",me:true,txt:"Il existe une forme de donation pensée pour ça."}],o:["La donation-partage : on donne et on partage en figeant les valeurs","Trois dons manuels identiques, déclarés le même jour à l'administration","Une donation en indivision de toute la somme aux trois enfants ensemble","Une donation hors part successorale au profit de l'aîné, chargé de répartir"],a:0,w:"La donation-partage répartit et fige les valeurs : au décès, pas de rapport, pas de réévaluation, pas de soulte. C'est l'outil de la paix des familles."},
{i:"p138_22",u:138,t:"tiles",d:.35,q:"Reconstitue la phrase qui oppose deux donations.",a:["Le","don","manuel","se","réveille","au","décès","la","donation-partage","dort"],dd:["toujours","jamais","rapport"],w:"Réévaluation au jour du partage pour l'un, valeur figée pour l'autre."},
{i:"p138_23",u:138,t:"slider",d:.5,q:"Quel taux s'applique à une part taxable de 300 000 € entre parent et enfant, dans sa tranche la plus haute ?",min:5,max:45,step:5,a:20,tol:0,pre:"",un:" %",w:"300 000 € se situe entre 15 932 et 552 324 € : tranche à 20 %. On peut appliquer le raccourci 20 % × 300 000 - 1 805,65."},
{i:"p138_24",u:138,t:"multi",d:.5,q:"Pourquoi donner tôt est-il un conseil classique ?",o:["Les abattements peuvent resservir tous les 15 ans","La plus-value future du bien échappe aux droits","En nue-propriété, la valeur taxable est plus faible quand on est jeune","Une donation précoce supprime la réserve des enfants"],a:[0,1,2],w:"Abattements rechargés, plus-value hors droits, nue-propriété moins chère. La réserve, elle, reste intacte."},
{i:"p138_25",u:138,t:"tf",d:.4,q:"Un couple peut donner 200 000 € à chacun de ses enfants sans droits, grâce aux abattements classiques.",a:true,w:"100 000 € par parent et par enfant. Avec le don familial en argent, on monte à 263 730 € si les parents ont moins de 80 ans."},
{i:"p138_26",u:138,t:"match",d:.5,q:"Associe chaque lien au taux maximal de droits.",p:[["Parent et enfant","45 %"],["Frère et sœur","45 % au-delà de 24 430 €"],["Neveu et oncle","55 %"],["Ami sans lien","60 %"]],w:"Ligne directe jusqu'à 45 %. Fratrie 35 % puis 45 %. Parents jusqu'au 4e degré 55 %. Étrangers 60 %."},
{i:"p138_27",u:138,t:"story",d:.5,q:"Quelle est la bonne réponse ?",sc:[{who:"Bernard",txt:"Je voudrais donner la nue-propriété de mon appartement à mes enfants, et qu'à mon décès l'usufruit passe à Hélène plutôt qu'aux enfants."},{who:"Toi",me:true,txt:"Cela porte un nom précis."}],o:["Une donation avec réserve d'usufruit et réversion au profit d'Hélène","Une donation temporaire d'usufruit au profit d'Hélène pour dix ans","Une donation-partage transgénérationnelle au profit d'Hélène","Une tontine entre Hélène et les enfants sur la nue-propriété"],a:0,w:"Réserve d'usufruit pour Bernard, puis réversion de l'usufruit à Hélène après son décès. Les enfants ne récupèrent la pleine propriété qu'au second décès."},
{i:"p138_28",u:138,t:"fill",d:.4,q:"La donation qui distribue et répartit les biens en une seule fois s'appelle la ___.",o:["donation-partage","donation simple","donation graduelle","donation indirecte"],a:0,w:"Donation-partage : un acte, une répartition, des valeurs figées."},
{i:"p138_29",u:138,t:"num",d:.6,ctx:"Hélène, 64 ans, donne en une fois 150 000 € en argent à Sophie, 31 ans. Aucune donation depuis 15 ans.",q:"Quelle est la part taxable, en euros ?",a:18135,tol:1,un:" €",h:"Deux exonérations se cumulent",w:"150 000 - 100 000 (abattement) - 31 865 (don familial, moins de 80 ans, enfant majeur, argent) = 18 135 € taxables."},
{i:"p138_30",u:138,t:"mcq",d:.5,q:"Quel abattement pour un neveu dans une donation de son oncle ?",o:["7 967 €","15 932 €","31 865 €","1 594 €"],a:0,w:"7 967 € pour un neveu ou une nièce. Au-delà, 55 % : donner à un neveu coûte cher, d'où l'intérêt de l'assurance-vie."},
{i:"p138_31",u:138,t:"sort",d:.5,q:"Classe chaque montant : abattement de donation ou exonération spéciale ?",bins:["Abattement de parenté","Exonération spéciale"],it:[["100 000 € pour un enfant",0],["31 865 € de don familial en argent",1],["80 724 € pour un époux",0],["159 325 € pour une personne handicapée",1],["15 932 € pour une sœur",0]],w:"Les abattements dépendent du lien de parenté. Le don familial et l'abattement handicap s'ajoutent par-dessus, sous conditions."},
{i:"p138_32",u:138,t:"story",d:.55,q:"Que réponds-tu à Enzo ?",sc:[{who:"Enzo",txt:"Mon grand-père Bernard veut me donner 60 000 € pour mes études. Il a 67 ans, j'ai 19 ans."},{who:"Enzo",txt:"Je vais payer combien ?"}],o:["Rien : 31 865 € d'abattement plus 31 865 € de don familial couvrent 63 730 €","Environ 5 600 € : seul l'abattement petit-enfant de 31 865 € s'applique","Rien du tout, car un étudiant de moins de 21 ans est toujours exonéré de droits de donation","12 000 € : un don d'un grand-parent est taxé à 20 % dès le premier euro"],a:0,w:"Petit-enfant : abattement 31 865 €, plus don familial en argent 31 865 € (grand-père de moins de 80 ans, petit-fils majeur). Jusqu'à 63 730 €, rien à payer."}
