/*UNIT*/
{id:140,c:"PATRI",n:"Module 8",t:"Donation entre époux et avantages matrimoniaux",col:"--gold",ic:"💞",guide:`
<h3>Deux façons de protéger son époux</h3>
<div class="gstory">Bernard et Hélène veulent que le survivant « ne manque de rien ». Deux notaires leur ont proposé deux choses différentes : une <b>donation au dernier vivant</b> et une <b>modification de leur contrat de mariage</b>. Ce ne sont pas des variantes du même outil : l'une joue sur l'héritage, l'autre sur le partage de la communauté, avant même que l'héritage commence.</div>
<div class="gmnemo">« <b>La donation au dernier vivant agit sur la succession, l'avantage matrimonial agit avant la succession.</b> » Imagine deux étages. Au rez-de-chaussée, on partage la communauté : c'est là que joue l'avantage matrimonial. À l'étage, on partage l'héritage : c'est là que joue la donation entre époux.</div>
<h3>La donation entre époux, ou donation au dernier vivant</h3>
<ul><li>Acte notarié, signé pendant le mariage, qui <b>élargit les droits</b> du conjoint survivant au-delà de ce que prévoit la loi.</li>
<li>Elle ne prend effet <b>qu'au décès</b> : elle porte sur des biens à venir.</li>
<li>Elle est <b>librement révocable</b> à tout moment, sans prévenir l'autre : c'est d'ordre public, on ne peut pas y renoncer. Et le divorce la révoque automatiquement.</li></ul>
<div class="formula">Avec des enfants, le conjoint choisira au décès entre :
  a) la quotité disponible ordinaire en pleine propriété (1/2, 1/3 ou 1/4)
  b) 1/4 en pleine propriété + 3/4 en usufruit
  c) 100 % en usufruit</div>
<div class="gtrap">Les notes disent « obtenir la quotité la plus large possible (la réserve) ». Ce n'est pas la réserve, qui appartient aux enfants : c'est la <b>quotité disponible spéciale entre époux</b>, la plus large que la loi autorise au profit d'un conjoint.</div>
<p>Autre intérêt : le <b>cantonnement</b>. Le conjoint peut limiter ce qu'il prend à une partie seulement des biens, pour laisser le reste aux enfants sans que ce soit une donation de sa part.</p>
<h3>Les avantages matrimoniaux</h3>
<p>Ce sont des <b>clauses du contrat de mariage</b>, sur mesure, qui accordent au survivant plus que le partage à 50/50 de la communauté.</p>
<ul><li>Ils ne portent <b>que sur les biens communs</b>. En séparation de biens, pas de communauté, donc pas d'avantage matrimonial.</li>
<li>Ce ne sont pas des donations : ils <b>peuvent dépasser la quotité disponible</b>. Seule limite : les <b>enfants d'une autre union</b> peuvent agir en <b>retranchement</b> pour protéger leur réserve.</li></ul>
<table><tr><th>Clause</th><th>Effet</th></tr>
<tr><td><b>Préciput</b></td><td>Le survivant prélève certains biens communs avant le partage (la maison, les meubles). En pleine propriété, nue-propriété ou usufruit.</td></tr>
<tr><td><b>Attribution intégrale</b></td><td>En communauté universelle, tous les biens communs vont au survivant. C'est un préciput sur toute la communauté.</td></tr>
<tr><td><b>Partage inégal</b></td><td>La communauté est partagée selon d'autres proportions, par exemple 70/30.</td></tr></table>
<div class="gtrap">Les notes disent que les avantages matrimoniaux « s'expriment en cas de décès ou de divorce » et qu'ils sont « révocables ». Précision importante : ceux qui prennent effet à la dissolution (préciput, attribution intégrale) sont <b>révoqués de plein droit par le divorce</b>, sauf volonté contraire de l'époux qui les a consentis. Et on ne les révoque pas seul comme une donation au dernier vivant : il faut <b>changer de régime matrimonial</b>, à deux.</div>
<h3>Le piège de l'attribution intégrale</h3>
<div class="gstory">Les Lefèvre passent en communauté universelle avec attribution intégrale. Au décès de Bernard, Hélène reçoit tout, sans droits, et les enfants rien. Au décès d'Hélène, les enfants reçoivent tout d'un coup. Ils n'utiliseront qu'<b>une seule fois</b> leur abattement de 100 000 € au lieu de deux, et leur part taxable montera dans le barème. Protection maximale du conjoint, facture maximale pour les enfants.</div>
<table><tr><th></th><th>Donation au dernier vivant</th><th>Avantage matrimonial</th></tr>
<tr><td>Où ?</td><td>Acte notarié séparé</td><td>Contrat de mariage</td></tr>
<tr><td>Sur quoi ?</td><td>Toute la succession</td><td>Les biens communs seulement</td></tr>
<tr><td>Limite</td><td>Quotité spéciale entre époux</td><td>Aucune, sauf retranchement</td></tr>
<tr><td>Révocation</td><td>Seul, à tout moment</td><td>À deux, changement de régime</td></tr>
<tr><td>Divorce</td><td>Révoquée</td><td>Révoqués, sauf maintien</td></tr></table>`},
/*EXOS*/
{i:"p140_01",u:140,t:"multi",d:.25,nw:"La donation au dernier vivant",q:"Qu'est-ce qui caractérise la donation entre époux ?",o:["Elle ne prend effet qu'au décès","Elle est révocable à tout moment","Elle élargit les droits du conjoint survivant","Elle transfère les biens dès la signature"],a:[0,1,2],w:"Biens à venir, effet au décès, révocable librement. Rien ne passe au conjoint du vivant des deux."},
{i:"p140_02",u:140,t:"match",d:.3,q:"Associe chaque option de la donation au dernier vivant à son contenu.",p:[["Option 1","Quotité disponible ordinaire en pleine propriété"],["Option 2","1/4 en pleine propriété et 3/4 en usufruit"],["Option 3","100 % en usufruit"],["Cantonnement","Ne prendre qu'une partie des biens"]],w:"Trois options au choix du survivant, plus la possibilité de cantonner pour laisser le reste aux enfants."},
{i:"p140_03",u:140,t:"story",d:.35,q:"Que réponds-tu à Hélène ?",sc:[{who:"Hélène",txt:"Si je signe une donation au dernier vivant, Bernard pourra un jour l'annuler sans me le dire ?"},{who:"Toi",me:true,txt:"Oui, et vous aussi."}],o:["Elle est librement révocable par chacun, c'est d'ordre public","Non, une fois signée devant notaire, elle devient définitive","Seulement avec votre accord écrit, devant le même notaire","Seulement en cas de divorce prononcé par le juge"],a:0,w:"La révocabilité de la donation entre époux de biens à venir est d'ordre public : chacun peut la révoquer seul, à tout moment, sans même en informer l'autre."},
{i:"p140_04",u:140,t:"num",d:.45,ctx:"Succession de 600 000 €. Deux enfants communs. Le conjoint a 70 ans et une donation au dernier vivant.",q:"Option quotité disponible ordinaire : quelle valeur reçoit le conjoint en pleine propriété, en euros ?",a:200000,tol:1,un:" €",h:"Deux enfants",w:"Deux enfants : quotité disponible 1/3. 600 000 / 3 = 200 000 € en pleine propriété."},
{i:"p140_05",u:140,t:"num",d:.5,ctx:"Même succession de 600 000 €, conjoint de 70 ans.",q:"Option 100 % en usufruit : quelle est la valeur fiscale de ses droits, en euros ?",a:240000,tol:1,un:" €",h:"Barème 669, entre 61 et 70 ans",w:"Usufruit à 70 ans : 40 %. 600 000 × 40 % = 240 000 €."},
{i:"p140_06",u:140,t:"sort",d:.35,nw:"Les avantages matrimoniaux",q:"Classe chaque clause.",bins:["Avantage matrimonial","Pas un avantage matrimonial"],it:[["Clause de préciput",0],["Attribution intégrale de la communauté",0],["Partage inégal 70/30 de la communauté",0],["Donation au dernier vivant",1],["Testament au profit du conjoint",1]],w:"Les avantages matrimoniaux sont des clauses du contrat de mariage qui jouent sur la communauté. La donation au dernier vivant et le testament jouent sur la succession."},
{i:"p140_07",u:140,t:"tf",d:.3,q:"Des époux mariés en séparation de biens peuvent prévoir une clause de préciput sur leurs biens communs.",a:false,w:"En séparation de biens, il n'y a pas de biens communs, seulement des biens propres ou indivis. Pas de communauté, pas d'avantage matrimonial."},
{i:"p140_08",u:140,t:"story",d:.45,q:"Quel outil lui proposes-tu ?",ctx:"Hélène et Bernard sont mariés sous la communauté légale. Ils veulent que, quoi qu'il arrive, le survivant garde la maison d'Annecy, bien commun, sans la partager avec les enfants.",sc:[{who:"Bernard",txt:"On ne veut pas tout donner au survivant, juste la maison."}],o:["Une clause de préciput sur la maison dans leur contrat de mariage","Une attribution intégrale de toute la communauté au survivant","Un partage inégal de la communauté à 90 pour le survivant, 10 pour les enfants","Une donation temporaire d'usufruit de la maison à chacun, pour dix ans"],a:0,w:"Le préciput permet au survivant de prélever un bien commun déterminé avant tout partage. On cible la maison sans tout attribuer."},
{i:"p140_09",u:140,t:"fill",d:.3,q:"La clause qui permet au survivant de prélever un bien commun avant le partage s'appelle le ___.",o:["préciput","cantonnement","retranchement","rapport"],a:0,w:"Préciput : « pris avant ». Il peut porter sur la pleine propriété, la nue-propriété ou l'usufruit."},
{i:"p140_10",u:140,t:"story",d:.55,nw:"Le piège de l'attribution intégrale",q:"Quel est le principal inconvénient pour les enfants ?",ctx:"Les Lefèvre passent en communauté universelle avec attribution intégrale au survivant. Patrimoine commun : 1 200 000 €. Trois enfants.",sc:[{who:"Marc",txt:"Si papa meurt, maman a tout, sans droits. C'est parfait, non ?"},{who:"Toi",me:true,txt:"Pour votre mère, oui. Pour vous, regardons le second décès."}],o:["Au second décès, ils reçoivent tout d'un coup et n'utilisent qu'une fois leur abattement","Ils paient des droits dès le premier décès, calculés sur toute la part transmise à leur mère par la clause","Ils perdent définitivement leur réserve, même au décès de leur mère","Ils doivent racheter la part de leur mère pour éviter l'indivision"],a:0,w:"Tout passe au survivant, puis tout d'un bloc aux enfants : un seul abattement de 100 000 € par enfant au lieu de deux, et des tranches plus hautes. C'est le coût fiscal de la protection maximale."},
{i:"p140_11",u:140,t:"tf",d:.4,q:"Un avantage matrimonial peut dépasser la quotité disponible.",a:true,w:"Ce n'est pas une libéralité : il n'est pas limité par la quotité disponible. Seuls les enfants d'une autre union peuvent agir en retranchement."},
{i:"p140_12",u:140,t:"story",d:.5,nw:"L'action en retranchement",q:"Que peut faire Hugo ?",ctx:"Stéphane et Claire sont mariés en communauté universelle avec attribution intégrale au survivant. Stéphane a un fils, Hugo, d'une première union. Stéphane décède.",sc:[{who:"Hugo",txt:"Claire a tout reçu. Moi, je n'ai rien. C'est légal ?"},{who:"Toi",me:true,txt:"Pas totalement, justement parce que vous n'êtes pas son fils."}],o:["Agir en retranchement pour récupérer sa réserve sur l'avantage consenti","Rien du tout : un avantage matrimonial n'est jamais une donation, donc il ne peut être réduit","Demander l'annulation du contrat de mariage signé par son père","Attendre le décès de Claire, qui lui laissera la moitié par la loi"],a:0,w:"Les enfants non communs peuvent exercer l'action en retranchement : l'avantage est réduit dans la mesure où il porte atteinte à leur réserve."},
{i:"p140_13",u:140,t:"order",d:.4,q:"Remets dans l'ordre ce qui se passe au décès d'un époux avec préciput et donation au dernier vivant.",it:["Le survivant exerce son préciput sur la maison commune","Le reste de la communauté est partagé par moitié","La moitié du défunt et ses biens propres forment la succession","Le survivant choisit une option de la donation au dernier vivant sur cette succession"],w:"Rez-de-chaussée : la communauté, avec le préciput. Étage : la succession, avec la donation au dernier vivant."},
{i:"p140_14",u:140,t:"mcq",d:.45,q:"Que devient la donation au dernier vivant en cas de divorce ?",o:["Elle est révoquée de plein droit","Elle reste valable jusqu'au décès","Elle se transforme en préciput","Elle profite aux enfants communs"],a:0,w:"Le divorce révoque de plein droit les donations de biens à venir entre époux."},
{i:"p140_15",u:140,t:"story",d:.5,q:"Qu'est-ce que tu corriges ?",sc:[{who:"Ta collègue",txt:"J'ai noté : les avantages matrimoniaux s'expriment au décès ou au divorce, et on peut les révoquer."},{who:"Toi",me:true,txt:"Ce n'est pas faux, mais c'est dangereusement imprécis."}],o:["En cas de divorce, ils sont révoqués de plein droit ; sinon, on les change à deux","Ils jouent aussi bien au divorce qu'au décès, exactement de la même manière et sans aucune différence d'effet","Ils sont révocables seul, à tout moment, comme une donation au dernier vivant","Ils ne jouent jamais au décès, uniquement pour partager en cas de divorce"],a:0,w:"Les avantages qui prennent effet à la dissolution sont révoqués par le divorce, sauf maintien voulu. Et on ne les supprime pas seul : il faut un changement de régime matrimonial."},
{i:"p140_16",u:140,t:"slider",d:.45,q:"Clause de partage inégal : quelle part de la communauté le survivant reçoit-il avec une clause 70/30 ?",min:30,max:100,step:5,a:70,tol:0,pre:"",un:" %",w:"70 % pour le survivant, 30 % pour la succession du défunt. Le partage inégal modifie la proportion au lieu d'attribuer des biens précis."},
{i:"p140_17",u:140,t:"multi",d:.45,q:"Sur quoi une clause de préciput peut-elle porter ?",o:["La pleine propriété d'un bien commun","La nue-propriété d'un bien commun","L'usufruit d'un bien commun","Un bien propre du défunt"],a:[0,1,2],w:"Le préciput porte uniquement sur des biens communs, en pleine propriété, nue-propriété ou usufruit."},
{i:"p140_18",u:140,t:"tiles",d:.35,q:"Reconstitue la règle des deux étages.",a:["L'avantage","matrimonial","joue","avant","la","succession"],dd:["après","toujours","réserve"],w:"L'avantage matrimonial s'exerce au partage de la communauté, avant l'ouverture de la succession proprement dite."},
{i:"p140_19",u:140,t:"num",d:.6,ctx:"Communauté universelle avec attribution intégrale : au second décès, les deux enfants reçoivent ensemble 1 200 000 €, soit 600 000 € chacun. Aucune donation antérieure.",q:"Combien de droits paie chaque enfant, en euros ? (arrondi à l'euro)",a:98194,tol:2,un:" €",h:"Abattement, puis raccourci 20 %",w:"600 000 - 100 000 = 500 000 taxables. 20 % × 500 000 - 1 805,65 = 98 194,35 € par enfant. En deux successions de 300 000 €, chacun aurait payé 2 × 38 194 € = 76 389 €."},
{i:"p140_20",u:140,t:"tf",d:.4,q:"Le conjoint qui hérite grâce à une donation au dernier vivant paie des droits de succession sur la part qui dépasse ses droits légaux.",a:false,w:"Le conjoint survivant est exonéré de droits de succession, quelle que soit l'origine de ses droits."},
{i:"p140_21",u:140,t:"story",d:.45,q:"Que penses-tu de ce qu'a noté ton stagiaire ?",sc:[{who:"Ton stagiaire",txt:"Donation entre époux : permet au conjoint d'obtenir la quotité la plus large possible, c'est-à-dire la réserve."}],o:["Faux : c'est la quotité disponible spéciale entre époux, pas la réserve","Juste : le conjoint récupère la réserve des enfants grâce à la donation","Juste, mais seulement s'il n'y a qu'un seul enfant dans la famille","Faux : la donation entre époux ne donne jamais de pleine propriété"],a:0,w:"La réserve appartient aux enfants et reste intouchable. La donation entre époux ouvre la quotité disponible spéciale, la plus large que la loi permet au profit d'un conjoint."},
{i:"p140_22",u:140,t:"mcq",d:.45,q:"À quoi sert le cantonnement ?",o:["À prendre moins que ses droits pour laisser le reste aux enfants","À bloquer la vente d'un bien commun par les enfants","À répartir la communauté selon d'autres proportions","À révoquer une donation au dernier vivant après le décès"],a:0,w:"Le conjoint limite son émolument à certains biens. Ce qu'il abandonne revient aux enfants sans être considéré comme une donation de sa part."},
{i:"p140_23",u:140,t:"sort",d:.45,q:"Donation au dernier vivant ou avantage matrimonial ?",bins:["Donation au dernier vivant","Avantage matrimonial"],it:[["Révocable seul, à tout moment",0],["Figure dans le contrat de mariage",1],["Porte sur toute la succession",0],["Ne concerne que les biens communs",1],["Limitée par la quotité spéciale entre époux",0],["Modifiable seulement par un changement de régime",1]],w:"Deux outils, deux logiques. L'un vit dans un acte séparé et joue sur l'héritage, l'autre vit dans le contrat de mariage et joue sur la communauté."},
{i:"p140_24",u:140,t:"story",d:.5,q:"Que conseilles-tu ?",ctx:"Hélène, 64 ans, et Bernard, 67 ans, ont trois enfants communs et un patrimoine important. Ils veulent protéger le survivant, mais sans trop pénaliser les enfants fiscalement.",sc:[{who:"Hélène",txt:"Mon amie a fait une communauté universelle avec attribution intégrale. On fait pareil ?"}],o:["Plutôt une donation au dernier vivant : le survivant choisira et pourra cantonner","Oui, c'est à la fois l'outil le plus protecteur pour le conjoint et le moins taxé pour les enfants","Plutôt un partage inégal à 100/0, qui évite le problème du second décès","Aucune protection : le conjoint hérite déjà de tout avec des enfants communs"],a:0,w:"La donation au dernier vivant laisse le choix au survivant au moment du décès, et le cantonnement permet de transmettre dès le premier décès aux enfants. On évite l'effet d'entonnoir de l'attribution intégrale."},
{i:"p140_25",u:140,t:"slider",d:.5,q:"Option « 1/4 en pleine propriété + 3/4 en usufruit » sur une succession de 400 000 € : quelle valeur en pleine propriété reçoit le conjoint, en milliers d'euros ?",min:0,max:400,step:10,a:100,tol:0,pre:"",un:" k€",w:"1/4 de 400 000 = 100 000 € en pleine propriété, plus l'usufruit des 300 000 € restants."},
{i:"p140_26",u:140,t:"fill",d:.4,q:"La donation entre époux porte sur des biens ___, puisqu'elle ne prend effet qu'au décès.",o:["à venir","présents","communs","propres"],a:0,w:"Donation de biens à venir : elle porte sur ce que le donateur laissera à son décès."},
{i:"p140_27",u:140,t:"match",d:.45,q:"Associe chaque clause à sa définition.",p:[["Préciput","Prélever un bien commun avant partage"],["Attribution intégrale","Toute la communauté au survivant"],["Partage inégal","Une autre proportion que 50/50"],["Retranchement","Recours des enfants d'une autre union"]],w:"Trois clauses pour avantager le survivant, un recours pour protéger les enfants non communs."},
{i:"p140_28",u:140,t:"tf",d:.5,q:"Avec une donation au dernier vivant, le conjoint peut choisir l'usufruit total même en présence d'un enfant non commun.",a:true,w:"Contrairement à la loi seule, qui impose le quart en pleine propriété face à un enfant non commun, la donation au dernier vivant ouvre les trois options. L'enfant non commun garde cependant des protections."},
{i:"p140_29",u:140,t:"story",d:.55,q:"Quel est le problème ?",ctx:"Stéphane veut protéger Claire au maximum. Il a Hugo d'une première union et Lina avec Claire. Il envisage une communauté universelle avec attribution intégrale.",sc:[{who:"Stéphane",txt:"Avec ça, Claire aura tout et Hugo récupérera sa part plus tard."},{who:"Toi",me:true,txt:"Plus tard, justement, ce n'est pas si sûr."}],o:["Au décès de Claire, Hugo n'héritera pas d'elle : il n'est pas son enfant","Hugo héritera de Claire comme Lina, puisqu'il est le fils de son époux","Hugo récupérera automatiquement la moitié au décès de Claire, par la loi","Hugo n'a aucun recours, un avantage matrimonial ne pouvant être contesté"],a:0,w:"Hugo n'est pas l'héritier de sa belle-mère. S'il ne reçoit rien au décès de son père, il ne recevra rien non plus au décès de Claire. D'où l'action en retranchement, et la prudence avec les familles recomposées."},
{i:"p140_30",u:140,t:"mcq",d:.45,q:"Où figure un avantage matrimonial ?",o:["Dans le contrat de mariage","Dans un testament authentique","Dans une donation-partage","Dans un pacte civil de solidarité"],a:0,w:"Les avantages matrimoniaux sont des clauses du contrat de mariage, conclu ou modifié devant notaire."},
{i:"p140_31",u:140,t:"multi",d:.55,q:"Quelles affirmations sur la communauté universelle avec attribution intégrale sont justes ?",o:["Elle protège au maximum le conjoint survivant","Elle peut alourdir les droits des enfants au second décès","Elle expose à l'action en retranchement des enfants non communs","Elle réduit les droits des enfants au premier décès"],a:[0,1,2],w:"Protection maximale, second décès coûteux, risque de retranchement. Au premier décès, les enfants ne reçoivent rien : il n'y a pas de droits à réduire."},
{i:"p140_32",u:140,t:"story",d:.5,q:"Que dis-tu à Bernard ?",sc:[{who:"Bernard",txt:"Nous avons signé une donation au dernier vivant il y a vingt ans. Hélène y a droit tout de suite, maintenant ?"}],o:["Non, elle ne produira ses effets qu'au décès du premier d'entre vous","Oui, elle peut déjà exercer son usufruit sur vos biens propres","Oui, pour la moitié des biens communs, dès la signature de l'acte","Non, elle est devenue caduque au bout de vingt ans faute de renouvellement"],a:0,w:"Donation de biens à venir : aucun effet du vivant des deux époux. Elle ne se périme pas avec le temps."}
