/*UNIT*/
{id:142,c:"PATRI",n:"Module 10",t:"Le testament : les trois formes",col:"--gold",ic:"📜",guide:`
<h3>Un testament qu'on ne retrouve pas n'existe pas</h3>
<div class="gstory">Une vieille dame dit à sa famille : « J'ai tout écrit, c'est sous la boîte à pain. » Elle décède. Personne ne se souvient de la phrase, la cuisine est vidée, la boîte à pain part à la déchetterie. Ses dernières volontés partent avec. Le professeur raconte aussi l'histoire du coffre : un enfant qui a les clés, un testament qui n'y est plus au décès. Garde ces deux images : tout ce module tourne autour de la <b>sécurité</b> du testament.</div>
<p>Le testament organise la transmission de ses biens <b>après le décès</b> : qui reçoit quoi, avec quelles modalités. C'est un acte <b>personnel</b>, <b>unilatéral</b> et <b>révocable</b>. La méthode reste la même : on cherche toujours d'abord s'il existe un testament.</p>
<h3>Le testament olographe</h3>
<ul><li>Entièrement <b>écrit à la main</b> par le testateur, <b>daté</b> et <b>signé</b>. Un texte tapé à l'ordinateur ou dicté à quelqu'un n'est pas un testament olographe valable.</li>
<li><b>Avantages</b> : simple, peu coûteux, souple, secret, facile à modifier.</li>
<li><b>Inconvénients</b> : il peut être perdu, détruit, falsifié, contesté dans son origine ou son authenticité, ou jamais retrouvé.</li>
<li>Les ratures ne l'annulent pas forcément, mais elles fragilisent la preuve : écrire proprement est une règle de prudence.</li>
<li>Désigner quelqu'un comme « mon héritier » est trop vague : il faut <b>identifier précisément</b> chaque bénéficiaire.</li></ul>
<div class="gmnemo">Olographe : « <b>O</b>n l'écrit tout seul, à la main, et on l'<b>O</b>ublie dans un tiroir ». Sa force est sa simplicité, sa faiblesse est le tiroir. Remède : le <b>déposer chez un notaire</b>, qui l'inscrit au fichier central des dispositions de dernières volontés.</div>
<h3>Le testament authentique</h3>
<p>Reçu par <b>deux notaires</b>, ou par <b>un notaire assisté de deux témoins</b>. Il suit cinq étapes :</p>
<div class="formula">1. Dictée    : le testateur exprime et dicte ses volontés
2. Écriture  : le notaire les retranscrit
3. Lecture   : le notaire relit le testament au testateur
4. Mention   : l'acte mentionne qu'il a été dicté, écrit et lu
5. Signature : testateur, notaire(s) et témoins signent</div>
<div class="gmnemo">« <b>D</b>es <b>É</b>lèves <b>L</b>isent <b>M</b>al <b>S</b>ouvent » : <b>D</b>ictée, <b>É</b>criture, <b>L</b>ecture, <b>M</b>ention, <b>S</b>ignature. Dans l'ordre où tu les vivrais assis dans le bureau du notaire.</div>
<ul><li><b>Avantages</b> : sécurité juridique supérieure, conservation dans les minutes du notaire, enregistrement au fichier central, responsabilité du notaire, meilleure protection contre les contestations. Adapté aux personnes qui ne savent pas ou plus écrire.</li>
<li><b>Inconvénients</b> : formalisme plus lourd, honoraires, présence éventuelle de témoins, plus de temps.</li></ul>
<div class="gmnemo">« <b>Le formalisme est le prix de la sécurité.</b> » Plus c'est lourd à faire, plus c'est solide ensuite.</div>
<h3>Les témoins</h3>
<p>Ils attestent de leur présence et de l'<b>état apparent</b> du testateur, sans forcément connaître le contenu. Ils doivent être <b>majeurs</b>, savoir signer, comprendre le français (le cours évoque une condition de nationalité française dans son anecdote) et ne pas être bénéficiaires du testament, ni leurs proches parents, ni les clercs du notaire. Le professeur raconte les petits tests de cohérence : l'âge, ce qu'on a regardé la veille, le nom du président. Une personne qui répond « le général de Gaulle » en 2026 attire l'attention.</p>
<h3>Le testament mystique</h3>
<p>Le testateur remet au notaire, devant deux témoins, une <b>enveloppe fermée</b> contenant son testament. Le notaire dresse un acte de suscription. Secret, mais coûteux et rare : le cours retient surtout qu'il existe.</p>
<h3>Conservation, perte, copies</h3>
<ul><li>L'<b>inscription au fichier central</b> n'est pas une condition de validité, mais c'est ce qui permet au notaire de la succession de retrouver le testament.</li>
<li>Si le testament est perdu, on peut encore le faire valoir en prouvant son <b>existence</b>, son <b>contenu</b> et que la perte vient d'un <b>cas de force majeure</b> et non d'une révocation.</li>
<li>Une <b>copie fiable</b> a la même force probante que l'original, avec une <b>présomption de fiabilité</b> jusqu'à preuve contraire. Mais un scan n'est pas l'original : les juges vérifient la volonté réelle et la fiabilité en cas de contestation. Référence citée par le cours : Francis Lefebvre.</li></ul>
<h3>Les testaments conjoints sont interdits</h3>
<div class="gstory">Monsieur et Madame Dubois, sans enfant, veulent laisser quelque chose à leur femme de ménage, Rosa. Ils ont trois options. Chacun peut rédiger son propre testament. Ils peuvent en rédiger un seul à deux. Madame peut donner procuration à Monsieur pour tester à sa place. Seule la première option est valable. Un testament exprime la volonté d'<b>une seule</b> personne. Monsieur peut être pauvre et Madame une riche héritière : ils n'ont ni le même patrimoine, ni forcément les mêmes volontés, et chacun doit pouvoir changer d'avis sans demander la permission à l'autre.</div>`},
/*EXOS*/
{i:"p142_01",u:142,t:"multi",d:.25,nw:"Le testament olographe",q:"Quelles conditions un testament olographe doit-il remplir ?",o:["Être entièrement écrit de la main du testateur","Être daté","Être signé","Être tapé puis signé à la main"],a:[0,1,2],w:"Écrit, daté, signé, de la main du testateur. Un texte dactylographié ne vaut pas testament olographe."},
{i:"p142_02",u:142,t:"story",d:.3,q:"Que dis-tu à Colette ?",sc:[{who:"Colette",txt:"J'ai écrit mon testament à l'ordinateur, je l'ai imprimé et signé. C'est bon ?"},{who:"Toi",me:true,txt:"La signature ne suffit pas à le sauver."}],o:["Non : un olographe doit être entièrement écrit à la main","Oui : la signature manuscrite valide tout le document imprimé","Oui, s'il est daté à la main en plus de la signature","Oui, à condition de le faire tamponner par la mairie"],a:0,w:"L'olographe est entièrement manuscrit. Un document tapé et signé n'est pas valable sous cette forme."},
{i:"p142_03",u:142,t:"order",d:.3,nw:"Le testament authentique",q:"Remets dans l'ordre les cinq étapes du testament authentique.",it:["Le testateur dicte ses volontés","Le notaire les écrit","Le notaire lit le testament au testateur","L'acte mentionne ces formalités","Tous signent"],w:"Des Élèves Lisent Mal Souvent : Dictée, Écriture, Lecture, Mention, Signature."},
{i:"p142_04",u:142,t:"sort",d:.35,q:"Olographe ou authentique : classe chaque caractéristique du testament.",bins:["Testament olographe","Testament authentique"],it:[["Peu coûteux et secret",0],["Conservé dans les minutes du notaire",1],["Risque de perte ou de destruction",0],["Adapté à une personne qui ne sait plus écrire",1],["Facile à modifier seul",0],["Intervention de témoins possible",1]],w:"Olographe : simple, secret, fragile. Authentique : formel, coûteux, solide. Le formalisme est le prix de la sécurité."},
{i:"p142_05",u:142,t:"story",d:.4,q:"Quelle solution est valable ?",ctx:"Monsieur et Madame Dubois, sans enfant, veulent tous les deux transmettre quelque chose à leur femme de ménage, Rosa.",sc:[{who:"Monsieur Dubois",txt:"On a pensé à trois options. Un seul testament qu'on signerait ensemble, chacun son testament, ou ma femme me donne procuration et j'écris pour nous deux."}],o:["Chacun rédige son propre testament en faveur de Rosa","Un testament unique, signé par les deux époux","Madame donne procuration à Monsieur pour tester à sa place","Un testament unique déposé chez le notaire, qui le rend valable"],a:0,w:"Le testament est un acte personnel. Les testaments conjoints sont interdits et on ne teste pas par procuration."},
{i:"p142_06",u:142,t:"tf",d:.3,q:"L'inscription au fichier central des dernières volontés est une condition de validité du testament.",a:false,w:"Un olographe non inscrit reste valable. L'inscription sert à le retrouver au moment de la succession, ce qui est essentiel en pratique."},
{i:"p142_07",u:142,t:"match",d:.35,q:"Associe chaque forme à sa définition.",p:[["Olographe","Écrit, daté et signé à la main"],["Authentique","Reçu par notaire, dicté puis relu"],["Mystique","Remis clos au notaire devant témoins"],["Conjoint","Interdit : deux volontés dans un acte"]],w:"Trois formes valables, une interdite. L'examen insiste surtout sur l'olographe et l'authentique."},
{i:"p142_08",u:142,t:"story",d:.45,q:"Qu'est-ce qui pose problème ?",sc:[{who:"Hélène",txt:"J'ai mis mon testament dans le coffre. Marc a les clés, au cas où il m'arriverait quelque chose."},{who:"Toi",me:true,txt:"C'est justement ce « au cas où » qui m'inquiète."}],o:["Le testament peut disparaître : mieux vaut le déposer chez un notaire","Le coffre annule le testament, qui doit rester à la vue de tous","Marc devient automatiquement exécuteur testamentaire en ayant les clés","Rien : un testament en coffre est toujours inscrit au fichier central"],a:0,w:"C'est l'exemple du coffre dans le cours : un enfant qui a les clés peut faire disparaître un testament qui ne l'arrange pas. Le dépôt chez un notaire sécurise la conservation."},
{i:"p142_09",u:142,t:"slider",d:.3,q:"Combien de témoins assistent un notaire seul pour un testament authentique ?",min:0,max:5,step:1,a:2,tol:0,pre:"",un:" témoins",w:"Deux notaires, ou un notaire et deux témoins."},
{i:"p142_10",u:142,t:"multi",d:.45,q:"Quel est le rôle des témoins d'un testament authentique ?",o:["Attester qu'ils ont assisté à la procédure","Constater l'état apparent du testateur","Signer l'acte","Décider à la place du notaire de la validité du testament"],a:[0,1,2],w:"Ils constatent et attestent, sans forcément connaître le contenu, et ne décident rien à la place du notaire."},
{i:"p142_11",u:142,t:"fill",d:.35,q:"Selon le cours, le formalisme est le prix de la ___.",o:["sécurité","liberté","rapidité","discrétion"],a:0,w:"Plus le formalisme est important, plus la sécurité est grande. C'est toute la différence entre olographe et authentique."},
{i:"p142_12",u:142,t:"story",d:.5,q:"Que peuvent faire les héritiers ?",ctx:"Au décès de Colette, tout le monde sait qu'elle avait rédigé un testament olographe au profit de sa fondation. L'original a brûlé dans l'incendie de son appartement deux mois avant son décès.",sc:[{who:"La fondation",txt:"Nous avons une photocopie. Elle vaut quelque chose ?"}],o:["On peut prouver le contenu et que la perte vient d'un cas de force majeure","Rien : sans original, le testament est réputé révoqué dans tous les cas","Il suffit de le faire réécrire par un proche, à l'identique","La photocopie vaut original sans aucune discussion possible"],a:0,w:"En cas de perte, on peut faire valoir le testament en prouvant son existence, son contenu et une perte par force majeure. La copie aide, mais la preuve peut être discutée."},
{i:"p142_13",u:142,t:"tf",d:.4,q:"Une copie fiable bénéficie d'une présomption de fiabilité, jusqu'à preuve du contraire.",a:true,w:"La reproduction fidèle de la forme et du contenu est présumée fiable. Mais cette présomption peut être contestée devant le juge."},
{i:"p142_14",u:142,t:"mcq",d:.4,q:"Pourquoi le cours conseille-t-il de privilégier le testament authentique ?",o:["Pour sécuriser la conservation et limiter les contestations","Parce que l'olographe est interdit depuis la numérisation","Parce qu'il est le seul à pouvoir léguer un bien immobilier","Parce qu'il permet de contourner la réserve des enfants"],a:0,w:"Sécurité, conservation, intervention d'un professionnel, recherche facile au décès. Il ne permet pas pour autant de toucher à la réserve."},
{i:"p142_15",u:142,t:"story",d:.5,q:"Que révèle cette réponse ?",ctx:"Un notaire reçoit un testament authentique. L'un des témoins demande au testateur, 88 ans, qui est le président de la République.",sc:[{who:"Le testateur",txt:"Le général de Gaulle, voyons."},{who:"Le témoin",txt:"..."}],o:["Un possible trouble cognitif qui doit alerter sur la capacité à tester","Rien d'anormal : les témoins n'ont pas à juger de l'état du testateur","Une simple erreur d'inattention sans portée, le notaire poursuit la dictée","Une preuve que le testament doit être rédigé sous forme olographe"],a:0,w:"C'est l'exemple du professeur : les témoins attestent de l'état apparent du testateur. Une réponse incohérente doit faire suspendre et vérifier la capacité."},
{i:"p142_16",u:142,t:"sort",d:.45,q:"Olographe : avantage ou inconvénient ?",bins:["Avantage","Inconvénient"],it:[["Reste secret",0],["Peut être falsifié",1],["Peu coûteux",0],["Peut ne jamais être retrouvé",1],["Facile à modifier",0],["Son authenticité peut être contestée",1]],w:"Simple, secret, gratuit, souple. Mais fragile : perte, destruction, falsification, contestation."},
{i:"p142_17",u:142,t:"tiles",d:.35,q:"Reconstitue la phrase qui résume l'interdiction.",a:["Un","testament","exprime","la","volonté","d'une","seule","personne"],dd:["deux","couple","toujours"],w:"Les testaments conjoints sont interdits. Deux époux font deux testaments distincts, qui peuvent se compléter."},
{i:"p142_18",u:142,t:"tf",d:.4,q:"Deux époux peuvent rédiger deux testaments distincts qui contiennent des dispositions complémentaires.",a:true,w:"C'est même la bonne solution. Chacun reste un testament personnel, que chacun peut modifier seul."},
{i:"p142_19",u:142,t:"story",d:.45,q:"Pourquoi le testament de Bernard est-il risqué ?",sc:[{who:"Bernard",txt:"J'ai écrit : « Je lègue ma collection de montres à mon héritier ». C'est clair, non ?"},{who:"Toi",me:true,txt:"Pour vous, oui. Pour le juge, pas du tout."}],o:["« Mon héritier » ne désigne personne précisément : il faut nommer le bénéficiaire","Une collection de montres ne peut pas être léguée par testament olographe","Le mot « lègue » est réservé aux testaments reçus par un notaire","Il faut obligatoirement indiquer la valeur de chaque montre pour que le legs soit valable"],a:0,w:"Le cours insiste : une désignation trop générale crée des difficultés d'interprétation. Il faut identifier clairement la personne."},
{i:"p142_20",u:142,t:"mcq",d:.4,q:"Qu'est-ce qu'un testament mystique ?",o:["Un testament remis clos au notaire devant deux témoins","Un testament rédigé en langage codé par le testateur","Un testament oral enregistré sur un support numérique","Un testament rédigé à deux par des époux"],a:0,w:"Le testateur présente une enveloppe fermée au notaire, qui dresse un acte de suscription. Rare et coûteux."},
{i:"p142_21",u:142,t:"story",d:.55,q:"Quel est le vrai problème ?",sc:[{who:"Madame Dubois",txt:"Mon mari a écrit un testament au nom de nous deux. Moi, je l'ai juste signé en dessous."},{who:"Toi",me:true,txt:"Votre signature ne le rend pas plus solide, au contraire."}],o:["Un acte portant la volonté de deux personnes est un testament conjoint, prohibé","Il suffit que Madame recopie le texte en dessous pour le rendre valable","Le testament est valable pour Monsieur, et il vaut aussi pour Madame puisqu'elle l'a signé","Le problème est uniquement l'absence de date à côté de la signature de Madame"],a:0,w:"Un acte écrit comme la volonté de deux personnes, ou signé par deux personnes, pose un problème de testament conjoint. Il faut deux testaments séparés."},
{i:"p142_22",u:142,t:"slider",d:.45,q:"Combien d'étapes compte la procédure du testament authentique dans le cours ?",min:2,max:8,step:1,a:5,tol:0,pre:"",un:" étapes",w:"Dictée, écriture, lecture, mention, signature : cinq étapes."},
{i:"p142_23",u:142,t:"match",d:.45,q:"Associe chaque histoire du cours à sa leçon.",p:[["La boîte à pain","Un testament introuvable ne sert à rien"],["Le coffre dont l'enfant a les clés","Un testament peut disparaître"],["La femme de ménage","Chacun son testament"],["Le général de Gaulle","Vérifier la cohérence du testateur"]],w:"Quatre images pour quatre règles. Si tu te souviens de l'histoire, tu te souviens de la règle."},
{i:"p142_24",u:142,t:"tf",d:.45,q:"Un testament numérisé a toujours exactement la même valeur que l'original, sans discussion possible.",a:false,w:"La numérisation ne fait pas automatiquement du fichier l'original juridiquement valable. La copie fiable est présumée, mais contestable."},
{i:"p142_25",u:142,t:"story",d:.45,q:"Quelle forme conseilles-tu ?",ctx:"Madame Morel, 84 ans, a une arthrose sévère des mains et ne peut presque plus écrire. Elle veut organiser précisément sa succession entre ses deux enfants et sa petite-fille.",sc:[{who:"Mme Morel",txt:"Je ne peux même plus tenir un stylo plus de trois lignes."}],o:["Un testament authentique : elle dicte, le notaire écrit","Un testament olographe écrit par sa fille, qu'elle signerait","Un testament dactylographié qu'elle signe avec l'aide d'un proche","Aucun testament : une personne qui ne peut écrire ne peut pas tester"],a:0,w:"L'authentique est adapté aux personnes qui ne savent pas ou ne peuvent plus écrire : elles dictent, le notaire retranscrit."},
{i:"p142_26",u:142,t:"fill",d:.45,q:"Le testament authentique est conservé dans les ___ du notaire.",o:["minutes","archives départementales","registres de mairie","coffres bancaires"],a:0,w:"Les minutes sont les originaux des actes conservés par le notaire. C'est l'une des forces de l'authentique."},
{i:"p142_27",u:142,t:"multi",d:.5,q:"En cas de contestation, sur quoi peut-elle porter selon le cours ?",o:["L'origine du testament","Sa forme","La capacité du testateur","Le montant des frais de notaire"],a:[0,1,2],w:"Origine, forme, capacité, authenticité, circonstances de la rédaction. Les juges recherchent la volonté réelle du testateur."},
{i:"p142_28",u:142,t:"story",d:.5,q:"Qu'est-ce qui est juste ?",sc:[{who:"Monsieur Dubois",txt:"Si j'écris mon testament en faveur de Rosa et que ma femme n'est pas d'accord, je dois lui demander la permission pour le modifier plus tard ?"}],o:["Non, chacun peut modifier ou révoquer son propre testament librement","Oui, dès lors que vous êtes mariés sous le régime de la communauté","Oui, si votre femme a signé un testament en faveur de la même personne","Non, mais il faut prévenir le notaire au moins un mois avant"],a:0,w:"La liberté de tester implique la liberté de révoquer, sans l'accord de personne, même de son conjoint."},
{i:"p142_29",u:142,t:"tf",d:.5,q:"Une rature dans un testament olographe entraîne automatiquement sa nullité.",a:false,w:"Les ratures fragilisent la preuve et peuvent rendre une disposition incertaine, mais n'annulent pas automatiquement le testament. Écrire proprement reste une règle de prudence."},
{i:"p142_30",u:142,t:"mcq",d:.5,q:"Qui ne peut pas être témoin d'un testament authentique ?",o:["Le bénéficiaire d'un legs dans ce testament","Un ami majeur du testateur","Une voisine majeure qui sait signer","Un commerçant du quartier, majeur"],a:0,w:"Un légataire ne peut pas être témoin du testament qui le gratifie, pas plus que ses proches parents ou les clercs du notaire. Les témoins doivent être majeurs, savoir signer et comprendre la langue."},
{i:"p142_31",u:142,t:"story",d:.55,q:"Pourquoi faire les choses vite ?",ctx:"Histoire racontée par le professeur : un dossier avec plusieurs filles. Des testaments avaient été préparés, qu'elles devaient recopier elles-mêmes, dater, signer, puis déposer chez le notaire contre un reçu.",sc:[{who:"L'une des filles",txt:"On a le brouillon, on le recopiera le mois prochain."}],o:["Si l'une décède avant d'avoir recopié et déposé, rien n'est valable","Le brouillon préparé par le notaire vaut testament authentique","Le reçu remis par le notaire suffit, même si le testament n'a pas été recopié","Le mois de délai est obligatoire avant toute signature"],a:0,w:"Un brouillon n'est pas un testament. Tant qu'il n'a pas été recopié, daté, signé et conservé, un décès rend la situation beaucoup plus complexe."},
{i:"p142_32",u:142,t:"sort",d:.5,q:"Authentique : avantage ou inconvénient ?",bins:["Avantage","Inconvénient"],it:[["Responsabilité du notaire",0],["Honoraires à payer",1],["Enregistrement au fichier central",0],["Procédure plus lourde",1],["Meilleure protection contre les contestations",0]],w:"Sécurité, conservation, responsabilité du professionnel, contre formalisme, temps et coût."}
