/*UNIT*/
{id:144,c:"PATRI",n:"Module 12",t:"Les legs et le legs avec charge",col:"--gold",ic:"🚗",guide:`
<h3>La voiture de Bernard</h3>
<div class="gstory">Bernard possède une Alpine A110 de 1972. Son ami Gilles en rêve depuis quarante ans. Bernard écrit : « Je lègue mon Alpine à Gilles. Mes enfants et Hélène recevront le reste. » Puis il ajoute : « à charge pour Gilles d'arroser mes rosiers chaque année ». Toute la matière de ce module tient dans ces deux phrases : un legs particulier, et une charge.</div>
<h3>Les trois legs</h3>
<table><tr><th>Legs</th><th>Ce qu'il donne</th><th>Exemple</th></tr>
<tr><td><b>Universel</b></td><td>Vocation à tout le patrimoine</td><td>« Je lègue tous mes biens à Loïc »</td></tr>
<tr><td><b>À titre universel</b></td><td>Une quote-part ou une masse de biens</td><td>« Je lègue le tiers de mes biens », « tous mes immeubles »</td></tr>
<tr><td><b>À titre particulier</b></td><td>Un ou plusieurs biens déterminés</td><td>« Je lègue mon Alpine à Gilles »</td></tr></table>
<div class="gmnemo">« <b>Tout, une part, une chose.</b> » Universel = tout. À titre universel = une part (un tiers, tous les meubles). Particulier = une chose précise. La personne qui reçoit s'appelle le <b>légataire</b>.</div>
<p>Le testament peut répartir des biens différents entre des personnes différentes : les enfants et le conjoint reçoivent le patrimoine, l'ami reçoit la voiture.</p>
<h3>Le legs avec charge</h3>
<p>Le testateur peut assortir un legs d'une <b>charge</b> : une obligation, une mission imposée au bénéficiaire. En acceptant le legs, il accepte la charge. S'il ne l'exécute pas, le legs peut être <b>révoqué</b> par le juge et le bien devoir être rendu.</p>
<ul><li>La charge doit être <b>licite</b> et respecter l'<b>ordre public</b>. On ne peut pas imposer n'importe quoi : l'exemple humoristique du professeur est l'obligation de « faire la danse du ventre ».</li>
<li>Elle peut être <b>financière</b> ou <b>personnelle</b>.</li></ul>
<h3>Le cadeau empoisonné</h3>
<div class="gstory">La voiture vaut 30 000 €. Mais la charge impose au légataire de financer l'entretien d'un jardin et d'une serre pendant vingt ans, pour environ 60 000 €. Sur le papier, c'est un cadeau. En réalité, Gilles perd 30 000 €. C'est un <b>cadeau empoisonné</b>.</div>
<div class="formula">Avant d'accepter un legs :
  Actif reçu (ce que je reçois)          : maison, voiture, argent, titres, entreprise
- Passif et obligations (ce que je dois) : dépenses, entretien, prise en charge d'une personne
= Avantage économique réel</div>
<div class="gmnemo">« <b>On ne compte pas les cadeaux, on compte ce qui reste après les avoir entretenus.</b> » Et n'oublie jamais la différence du cours : <b>donner</b>, c'est sans contrepartie, alors que <b>vendre</b>, c'est contre un prix. Une charge très lourde rapproche le legs d'un échange.</div>
<h3>Pourquoi utiliser un legs avec charge ?</h3>
<p>Ils sont rares, mais utiles dans les situations familiales complexes :</p>
<ul><li><b>Protéger un conjoint qui a besoin de soins</b> : « je lègue la maison à ma fille, à charge pour elle de s'occuper de sa mère ». Limite du professeur : on ne peut pas <b>décréter l'amour</b>. L'argent garantit une action, pas l'affection.</li>
<li><b>Protéger un enfant vulnérable</b> : un père possède une grosse entreprise et deux filles, dont l'une est handicapée. La fille valide reçoit l'entreprise, à charge de veiller sur sa sœur, qui reçoit surtout du cash pour vivre. Si elle refuse la charge, le père a prévu une autre organisation. Le juge des tutelles peut intervenir, et une personne extérieure à la famille si nécessaire. Logique : <b>« je te donne, tu rétribues »</b>.</li>
<li><b>Occuper une maison</b> : la fille reçoit la maison et doit « s'occuper » de sa mère. Mais s'occuper, c'est quoi ? L'héberger, lui rendre visite, l'aider au quotidien, payer son EHPAD, ses dépenses ? <b>Plus la charge est vague, plus elle crée de conflits.</b></li></ul>
<h3>Quand la charge disparaît</h3>
<p>Une charge doit avoir un <b>objet</b>. Si la fille doit s'occuper de sa mère et que sa mère décède, l'objet disparaît : la charge aussi. Il faut toujours regarder ce qui déclenche la charge, ce qui y met fin, sa durée, et la disparition possible de son objet.</p>
<h3>Refuser un legs avec charge</h3>
<p>Peut-on refuser la maison chargée et garder un autre bien ? Faut-il refuser toute la succession ? <b>Réponse du cours : ça dépend de la rédaction du testament.</b> La charge est-elle attachée à un bien précis ou à toute la transmission ? Les legs sont-ils indépendants ? Le testament prévoit-il les conséquences d'un refus ? Règle de méthode : <b>ne jamais répondre mécaniquement, d'abord lire le testament.</b></p>
<h3>Legs graduel et legs résiduel</h3>
<ul><li><b>Legs graduel</b> : le premier légataire doit <b>conserver</b> le bien et le <b>transmettre</b> à son décès à un second bénéficiaire désigné par le testateur.</li>
<li><b>Legs résiduel</b> : le second bénéficiaire recueille seulement <b>ce qui reste</b> au décès du premier, qui pouvait vendre ou consommer.</li></ul>
<div class="gstory">Stéphane lègue un appartement à Lina, sa fille handicapée, à charge pour elle de le conserver et de le transmettre à son décès à son demi-frère Hugo. Lina en profite toute sa vie, et l'appartement ne se perdra pas dans une succession où Hugo ne serait pas héritier. C'est un legs graduel.</div>
<h3>Une bonne rédaction</h3>
<p>Elle rend la volonté claire, limite les contestations, précise les bénéficiaires, les biens, les charges, les conséquences d'un refus et la fin des obligations. Idée forte du professeur : la personne à qui l'on demande un service acceptera plus facilement si le mécanisme est bien construit.</p>`},
/*EXOS*/
{i:"p144_01",u:144,t:"match",d:.25,nw:"Les trois legs",q:"Associe chaque clause au type de legs.",p:[["« Je lègue tous mes biens à Loïc »","Legs universel"],["« Je lègue le tiers de mes biens à Loïc »","Legs à titre universel"],["« Je lègue mon Alpine à Gilles »","Legs à titre particulier"],["« Je lègue tous mes immeubles à Sophie »","Legs à titre universel"]],w:"Tout, une part, une chose. Une catégorie entière de biens (tous les immeubles) est une part : legs à titre universel."},
{i:"p144_02",u:144,t:"fill",d:.25,q:"La personne qui reçoit un bien par testament s'appelle le ___.",o:["légataire","donataire","testateur","cessionnaire"],a:0,w:"Légataire pour un legs, donataire pour une donation, testateur pour celui qui teste."},
{i:"p144_03",u:144,t:"story",d:.35,nw:"Le legs avec charge",q:"Que se passe-t-il si Gilles n'arrose jamais les rosiers ?",ctx:"Bernard a légué son Alpine à Gilles, à charge pour lui d'arroser ses rosiers chaque année. Gilles a accepté le legs, puis n'a jamais mis les pieds dans le jardin.",sc:[{who:"Marc",txt:"Il a pris la voiture et il se moque du jardin de papa."}],o:["Les héritiers peuvent demander la révocation du legs pour inexécution de la charge","Rien : une fois accepté, un legs ne peut plus jamais être remis en cause","Gilles doit seulement payer une amende civile, fixée par le notaire chargé de régler la succession","La charge est nulle, car arroser des rosiers n'a pas de valeur économique"],a:0,w:"En acceptant le legs, Gilles a accepté la charge. Son inexécution permet de demander au juge la révocation du legs, et la voiture pourrait devoir être rendue."},
{i:"p144_04",u:144,t:"num",d:.4,ctx:"Legs d'une voiture de 30 000 €, assorti d'une charge d'entretien d'une serre évaluée à 60 000 € sur la durée prévue.",q:"Quel est l'avantage économique réel pour le légataire, en euros ?",a:-30000,tol:1,un:" €",h:"Actif moins obligations",w:"30 000 - 60 000 = -30 000 €. C'est le cadeau empoisonné du cours : il vaudrait mieux refuser."},
{i:"p144_05",u:144,t:"tf",d:.3,q:"Un testateur peut imposer n'importe quelle charge à un légataire, puisque celui-ci est libre de refuser le legs.",a:false,w:"La charge doit être licite et conforme à l'ordre public. L'exemple de la danse du ventre illustre qu'on ne peut pas imposer n'importe quoi."},
{i:"p144_06",u:144,t:"order",d:.35,q:"Remets dans l'ordre l'analyse d'un legs avec charge avant de l'accepter.",it:["Lire précisément le testament","Évaluer l'actif reçu","Évaluer le coût et la durée des obligations","Calculer l'avantage économique réel","Décider d'accepter ou de refuser"],w:"On ne répond jamais mécaniquement : on lit, on chiffre l'actif, on chiffre les obligations, on compare."},
{i:"p144_07",u:144,t:"story",d:.45,q:"Quelle est la limite de ce montage ?",ctx:"Monsieur Garnier lègue sa maison à sa fille, à charge pour elle de s'occuper de sa mère, atteinte de la maladie d'Alzheimer.",sc:[{who:"Monsieur Garnier",txt:"Comme ça, elle sera obligée de bien s'occuper de sa mère."}],o:["On peut obliger à des actes, pas décréter l'affection ; la charge doit être précise","Aucune : la charge garantit juridiquement l'affection et l'humanité du légataire","Le legs est nul, car une charge ne peut jamais porter sur la prise en charge d'une personne vivante","La mère perd tout droit sur la maison dès l'ouverture du testament"],a:0,w:"Le professeur insiste : on ne décrète pas l'amour. L'argent garantit une action mécanique, pas l'humanité attendue. D'où l'importance de préciser le contenu de la charge."},
{i:"p144_08",u:144,t:"multi",d:.45,q:"« S'occuper de sa mère » : pourquoi faut-il préciser cette charge ?",o:["Elle peut vouloir dire héberger, visiter, aider ou payer l'EHPAD","Une charge vague crée des conflits d'interprétation","Le juge devra deviner la volonté du testateur","Une charge précise est plus coûteuse à exécuter"],a:[0,1,2],w:"Plus la charge est vague, plus elle génère de difficultés. Précision n'est pas synonyme de coût : c'est de la sécurité."},
{i:"p144_09",u:144,t:"story",d:.5,q:"Que devient la charge ?",ctx:"La fille a reçu la maison à charge de s'occuper de sa mère. Deux ans plus tard, la mère décède.",sc:[{who:"Le frère",txt:"Maintenant que maman est partie, tu dois rendre la maison, tu ne remplis plus la charge !"}],o:["L'objet de la charge a disparu : elle s'éteint et la fille garde la maison","La fille doit rendre la maison, faute de pouvoir exécuter la charge","La charge se transfère au frère, qui récupère la moitié de la maison","La fille doit indemniser son frère pour toutes les années de charge restant à courir"],a:0,w:"Une charge doit avoir un objet. Si la personne à prendre en charge décède, il n'y a plus rien à exécuter : la charge disparaît."},
{i:"p144_10",u:144,t:"sort",d:.4,q:"Classe chaque élément reçu avec un legs.",bins:["Actif","Passif ou obligation"],it:[["Une maison",0],["L'obligation d'entretenir un parc",1],["Un portefeuille de titres",0],["La prise en charge d'une personne",1],["Une entreprise",0],["Le paiement de dépenses fixées par le testament",1]],w:"Avant même de parler de charge, le professeur demande : est-ce que je reçois un actif, un passif, ou les deux ?"},
{i:"p144_11",u:144,t:"story",d:.5,q:"Quelle est la bonne réponse ?",ctx:"Un testament lègue à Sophie la maison, à charge de s'occuper de sa tante, et un portefeuille de titres. Sophie ne veut pas de la charge.",sc:[{who:"Sophie",txt:"Je peux refuser la maison et garder les titres ?"},{who:"Toi",me:true,txt:"Ça dépend."}],o:["Ça dépend de la rédaction : charge liée à la maison seule ou à tout le legs","Oui, toujours : chaque bien d'un testament se refuse indépendamment","Non, jamais : refuser un bien chargé oblige à refuser toute la succession","Oui, mais seulement si la tante donne son accord écrit, signé devant le notaire de la famille"],a:0,w:"Règle de méthode du cours : ne jamais répondre mécaniquement. La réponse dépend de la façon dont le testament attache la charge aux biens et de ce qu'il prévoit en cas de refus."},
{i:"p144_12",u:144,t:"tf",d:.35,q:"Selon le cours, les legs avec charge sont très fréquents dans les successions ordinaires.",a:false,w:"Ils sont relativement rares et réservés à des situations particulières : conjoint à soigner, enfant vulnérable, bien à occuper."},
{i:"p144_13",u:144,t:"story",d:.5,q:"Quelle organisation le cours présente-t-il ?",ctx:"Un père possède une très grosse entreprise et deux filles. L'une est handicapée.",sc:[{who:"Le père",txt:"Je veux que ma fille handicapée soit à l'abri toute sa vie."}],o:["L'entreprise à la fille valide avec charge de veiller sur sa sœur, qui reçoit du cash","L'entreprise à parts égales entre les deux filles, dirigée par un administrateur nommé par le juge","Tout à la fille handicapée, qui confiera la gestion à sa sœur par mandat","Tout à la fille valide, sans charge, puisqu'elle est déjà la plus proche"],a:0,w:"« Je te donne, tu rétribues. » La fille valide reçoit l'entreprise et la mission. Si elle refuse, une autre organisation est prévue pour sécuriser sa sœur, avec le juge des tutelles si besoin."},
{i:"p144_14",u:144,t:"tiles",d:.35,q:"Reconstitue la logique du legs avec charge selon le professeur.",a:["Je","te","donne","tu","rétribues"],dd:["vends","paies","toujours"],w:"Si tu acceptes l'avantage, tu acceptes la mission. Si tu refuses la mission, l'organisation successorale sera différente."},
{i:"p144_15",u:144,t:"mcq",d:.4,q:"Quelle est la différence entre donner et vendre selon le cours ?",o:["Donner est sans contrepartie, vendre est contre un prix","Donner se fait chez le notaire, vendre chez l'avocat","Donner concerne les meubles, vendre les immeubles","Donner est révocable, vendre ne l'est jamais"],a:0,w:"Transmission gratuite contre transmission à titre onéreux. Une charge très lourde rapproche le legs d'un échange."},
{i:"p144_16",u:144,t:"multi",d:.5,nw:"Legs graduel et résiduel",q:"Qu'est-ce qui caractérise un legs graduel ?",o:["Le premier légataire doit conserver le bien","Il doit le transmettre à son décès au second bénéficiaire","Le second bénéficiaire est désigné par le testateur","Le premier légataire peut vendre le bien librement"],a:[0,1,2],w:"Conserver et transmettre. Si le premier légataire peut vendre ou consommer, et que le second ne reçoit que le reste, c'est un legs résiduel."},
{i:"p144_17",u:144,t:"sort",d:.5,q:"Legs graduel ou résiduel ?",bins:["Graduel","Résiduel"],it:[["Obligation de conserver le bien",0],["Le second reçoit ce qui reste",1],["Le premier peut vendre le bien",1],["Le second reçoit forcément le bien lui-même",0]],w:"Graduel : conserver et transmettre. Résiduel : transmettre ce qui reste."},
{i:"p144_18",u:144,t:"story",d:.55,q:"Quel outil proposes-tu à Stéphane ?",ctx:"Stéphane veut que Lina, sa fille handicapée, profite de son appartement toute sa vie, puis qu'à son décès l'appartement revienne à Hugo, son fils d'une première union.",sc:[{who:"Stéphane",txt:"Si Lina hérite simplement, qu'est-ce qui garantit qu'Hugo récupérera l'appartement ?"}],o:["Un legs graduel : Lina conserve, puis transmet à Hugo à son décès","Un legs universel à Lina, qui fera ensuite son propre testament","Un legs résiduel à Hugo, qui n'aura que ce qui reste du patrimoine","Une donation-partage de l'appartement entre Lina et Hugo"],a:0,w:"Le legs graduel impose à Lina de conserver l'appartement et désigne Hugo comme second bénéficiaire. Hugo n'est pas l'héritier naturel de Lina : sans ce mécanisme, rien ne le garantit."},
{i:"p144_19",u:144,t:"tf",d:.4,q:"Un testament peut attribuer la voiture à un ami et le reste du patrimoine aux enfants et au conjoint.",a:true,w:"Il n'est pas nécessaire que tous les biens soient attribués de la même manière. Un bien déterminé peut faire l'objet d'un legs précis."},
{i:"p144_20",u:144,t:"slider",d:.45,q:"Une maison de 250 000 € est léguée avec une charge estimée à 90 000 €. Quel est l'avantage réel, en milliers d'euros ?",min:0,max:300,step:5,a:160,tol:0,pre:"",un:" k€",w:"250 000 - 90 000 = 160 000 €. Le legs reste intéressant, mais bien moins qu'en apparence."},
{i:"p144_21",u:144,t:"story",d:.45,q:"Comment qualifies-tu ce legs ?",sc:[{who:"Colette",txt:"Je veux que tous mes meubles aillent à ma filleule, et le reste à ma fondation."}],o:["Les meubles : legs à titre universel ; le reste : legs universel","Les meubles : legs à titre particulier ; le reste : legs à titre universel","Les deux legs sont des legs universels, faute de quote-part chiffrée","Les meubles : legs universel ; le reste : legs à titre particulier"],a:0,w:"« Tous mes meubles » vise une catégorie entière : legs à titre universel. « Le reste » a vocation à tout ce qui n'est pas attribué : legs universel."},
{i:"p144_22",u:144,t:"fill",d:.45,q:"Un legs qui coûte plus au légataire qu'il ne lui rapporte est un cadeau ___.",o:["empoisonné","déguisé","indirect","rapportable"],a:0,w:"Voiture de 30 000 €, charges de 60 000 € : cadeau empoisonné. D'où la question systématique de l'actif et du passif."},
{i:"p144_23",u:144,t:"match",d:.45,q:"Associe chaque question à ce qu'il faut regarder dans une charge.",p:[["Qu'est-ce qui la déclenche ?","L'acceptation du legs"],["Qu'est-ce qui y met fin ?","Le terme prévu ou la disparition de l'objet"],["Combien de temps ?","La durée prévue par le testament"],["Que se passe-t-il si on refuse ?","Ce que prévoit la rédaction"]],w:"Une charge n'est pas nécessairement éternelle. Déclenchement, fin, durée, refus : tout est dans la rédaction."},
{i:"p144_24",u:144,t:"mcq",d:.5,q:"Pourquoi une charge contraire à l'ordre public pose-t-elle problème ?",o:["Parce qu'elle peut être jugée non valable","Parce qu'elle rend le legs taxable à 60 %","Parce qu'elle oblige à passer devant deux notaires","Parce qu'elle transforme le legs en donation"],a:0,w:"La liberté du testateur n'est pas absolue. Une charge illicite ou contraire à l'ordre public pose un problème de validité."},
{i:"p144_25",u:144,t:"story",d:.5,q:"Que dis-tu à Gilles ?",ctx:"Gilles reçoit en legs une maison de campagne de 120 000 €. La charge : payer l'EHPAD de la sœur du défunt, soit 2 500 € par mois. Elle a 78 ans et une bonne santé.",sc:[{who:"Gilles",txt:"Une maison gratuite, je signe tout de suite !"}],o:["Attends : à 30 000 € par an, la charge peut vite dépasser la valeur de la maison","Signe : un legs est toujours un gain, quelle que soit la charge","Signe sans hésiter : la loi limite toute charge testamentaire à cinq ans au maximum","Refuse : un legs avec charge est toujours défavorable au légataire"],a:0,w:"2 500 € × 12 = 30 000 € par an. En quatre ans, la charge dépasse la valeur de la maison. Il faut calculer avant d'accepter, sans a priori dans un sens ou dans l'autre."},
{i:"p144_26",u:144,t:"tf",d:.45,q:"Une charge peut être personnelle, comme s'occuper de quelqu'un, et pas seulement financière.",a:true,w:"Financière (payer), personnelle (s'occuper), matérielle (entretenir). Toutes doivent être évaluées avant d'accepter."},
{i:"p144_27",u:144,t:"multi",d:.55,q:"Qu'est-ce qu'une bonne rédaction testamentaire doit prévoir, selon le cours ?",o:["Les bénéficiaires précisément identifiés","Le contenu exact des charges","Les conséquences d'un refus","Un montant de droits fixé à l'avance"],a:[0,1,2],w:"Bénéficiaires, biens, charges, refus, fin des obligations. Les droits, eux, dépendent de la loi, pas du testament."},
{i:"p144_28",u:144,t:"story",d:.55,q:"Quel est l'intérêt de bien construire le mécanisme ?",sc:[{who:"Le professeur",txt:"La personne à qui on demande un service sera plus facilement susceptible d'accepter si..."}],o:["...le mécanisme est correctement construit et clair","...le testament est rédigé en présence de deux notaires","...la charge est imposée sans possibilité de refuser","...le legs est supérieur à la moitié de la succession"],a:0,w:"Un mécanisme clair, juste et prévisible donne envie d'accepter. Un mécanisme flou fait peur, ou finit devant le juge."},
{i:"p144_29",u:144,t:"slider",d:.5,q:"Charge de 1 500 € par mois pendant 3 ans, legs d'un bien de 60 000 €. Quel est l'avantage réel, en milliers d'euros ?",min:-30,max:60,step:1,a:6,tol:0,pre:"",un:" k€",w:"1 500 × 36 = 54 000 €. 60 000 - 54 000 = 6 000 €. À peine positif : c'est presque un cadeau empoisonné."},
{i:"p144_30",u:144,t:"mcq",d:.45,q:"Quelle charge serait la plus problématique ?",o:["Faire la danse du ventre chaque dimanche en public","Entretenir la tombe familiale","Verser une rente à la sœur du défunt","Conserver la bibliothèque du défunt"],a:0,w:"L'exemple humoristique du professeur : une charge extravagante, contraire à la dignité, ne peut pas être valablement imposée."},
{i:"p144_31",u:144,t:"tf",d:.5,q:"Si le testament ne dit rien, refuser un legs avec charge oblige toujours à refuser toute la succession.",a:false,w:"Pas toujours. Tout dépend de la rédaction et de l'articulation des legs. On lit le testament avant de conclure."},
{i:"p144_32",u:144,t:"story",d:.5,q:"Que retenir de cet exemple ?",ctx:"Le père prévoit : si la fille valide refuse l'entreprise avec la charge de veiller sur sa sœur, une autre organisation sécurisera la fille handicapée, et le juge des tutelles pourra désigner une personne extérieure.",sc:[{who:"La fille valide",txt:"Donc je peux refuser sans mettre ma sœur en danger ?"}],o:["Oui : le testament prévoit une solution de repli pour protéger sa sœur","Non : refuser la charge prive automatiquement sa sœur de sa part d'héritage","Non : une fois le testament ouvert, la charge ne peut plus être refusée","Oui, mais elle devra alors verser elle-même une rente à sa sœur"],a:0,w:"Le principe du choix : accepter l'avantage et la mission, ou refuser et laisser jouer l'organisation de secours. L'objectif reste la protection de la personne vulnérable."}
