/*UNIT*/
{id:146,c:"PATRI",n:"Module 14",t:"Évaluer, négocier, garantir la cession",col:"--gold",ic:"🤝",guide:`
<h3>Combien vaut l'entreprise de Thomas ?</h3>
<div class="gstory">Thomas Garnier est persuadé que sa société de transport vaut 4 millions. Son expert-comptable dit 900 000 €. Le repreneur propose 2,5 millions. Personne ne ment : ils n'utilisent pas la même méthode. Le comptable regarde le bilan, le repreneur regarde ce que l'entreprise va rapporter, Thomas regarde trente ans de sa vie. Ton travail : leur donner une langue commune.</div>
<h3>Les quatre familles de méthodes</h3>
<table><tr><th>Méthode</th><th>Principe</th><th>Avantage</th><th>Limite</th></tr>
<tr><td><b>ANC</b> (actif net comptable)</td><td>Actif moins dettes, lu au bilan. Version corrigée (ANCC) : on réévalue les actifs à leur valeur réelle.</td><td>Simple, objective</td><td>Ignore la rentabilité future et la clientèle</td></tr>
<tr><td><b>Comparative ou analogique</b></td><td>On applique des multiples observés sur des entreprises ou transactions comparables (par exemple un multiple de l'EBE)</td><td>Colle au marché</td><td>Difficile de trouver de vrais comparables</td></tr>
<tr><td><b>DCF</b> (Discounted Cash Flow)</td><td>On actualise les flux de trésorerie futurs générés par l'entreprise</td><td>Valorise la capacité future</td><td>Très sensible aux hypothèses de croissance et de taux</td></tr>
<tr><td><b>Mixte</b> (goodwill, surprofit)</td><td>Valeur = actif net réévalué + goodwill, calculé à partir du surprofit (le bénéfice au-delà d'une rémunération normale des capitaux)</td><td>Combine patrimoine et rentabilité</td><td>Plusieurs paramètres subjectifs</td></tr></table>
<div class="gmnemo">« <b>Le passé, les voisins, le futur, et le mélange.</b> » ANC = le passé (le bilan). Comparables = les voisins (ce que valent les autres). DCF = le futur (ce que ça rapportera). Goodwill = le mélange.</div>
<h3>Décotes et primes</h3>
<ul><li><b>Décote de minorité</b> : une participation minoritaire ne donne pas le pouvoir, elle vaut moins.</li>
<li><b>Décote d'illiquidité</b> : des titres non cotés sont difficiles à revendre.</li>
<li><b>Prime de contrôle</b> : acquérir la majorité donne le pouvoir, cela se paie.</li></ul>
<h3>Les étapes de la cession</h3>
<div class="formula">1. Préparer   : délimiter le périmètre cédé, clarifier la situation juridique et fiscale,
               élaborer un business plan de transmission
2. Trouver    : cercle restreint (famille, salariés, partenaires), marché ouvert,
               intermédiaires ; documents : teaser puis information memorandum
3. Négocier   : lettre d'intention (LOI), audits, garantie d'actif et de passif
4. Conclure   : protocole d'accord (SPA pour des titres, APA pour des actifs),
               puis acte définitif de cession
5. Après      : enregistrement, publicité, immatriculation,
               délai d'opposition des créanciers, transmission progressive</div>
<div class="gmnemo">« <b>P</b>etit <b>T</b>igre <b>N</b>égocie <b>C</b>ontrat <b>A</b>vec soin » : <b>P</b>réparer, <b>T</b>rouver, <b>N</b>égocier, <b>C</b>onclure, <b>A</b>près. Le <b>teaser</b> est la bande-annonce anonyme d'une ou deux pages ; l'<b>information memorandum</b> est le film complet, remis après un engagement de confidentialité.</div>
<h3>Les audits</h3>
<p>Avant de signer, l'acquéreur fait vérifier la société : audit <b>juridique</b> (contrats, litiges), <b>fiscal</b> (risques de redressement), <b>social</b> (salariés, contentieux), <b>comptable et financier</b> (qualité des comptes, dette).</p>
<h3>La garantie d'actif et de passif (GAP)</h3>
<p>Le cédant s'engage à <b>indemniser</b> l'acquéreur si :</p>
<ul><li>certains <b>actifs</b> étaient <b>surévalués</b> ;</li><li>certains <b>passifs</b> étaient <b>sous-évalués ou cachés</b> ;</li><li>un <b>événement antérieur à la cession</b> entraîne une charge imprévue (un redressement fiscal sur une année passée, un procès prud'homal ancien).</li></ul>
<table><tr><th>Élément</th><th>Contenu</th></tr>
<tr><td>Déclarations et garanties</td><td>Ce que le cédant affirme sur la société</td></tr>
<tr><td>Durée</td><td>En général <b>2 à 3 ans</b> ; pour le fiscal, jusqu'à l'expiration du <b>délai de reprise</b> de l'administration</td></tr>
<tr><td>Franchise</td><td>Montant en dessous duquel l'acquéreur n'est pas indemnisé</td></tr>
<tr><td>Seuil global</td><td>Montant cumulé de réclamations à atteindre pour déclencher la garantie</td></tr>
<tr><td>Plafond</td><td>Montant maximal de l'indemnisation, souvent un pourcentage du prix</td></tr>
<tr><td>Mise en œuvre</td><td>Délais de notification, gestion des litiges</td></tr></table>
<p>Intérêt : pour l'acquéreur, être protégé ; pour le cédant, limiter et encadrer sa responsabilité ; pour les deux, créer la confiance. Vigilance : la rédaction est examinée de près par les juges en cas de litige.</p>
<h3>Les clauses complémentaires</h3>
<table><tr><th>Clause</th><th>But</th></tr>
<tr><td><b>Non-concurrence</b></td><td>Le cédant ne recrée pas la même activité, limitée dans le temps, l'espace et l'activité</td></tr>
<tr><td><b>Non-sollicitation</b></td><td>Le cédant ne débauche ni les salariés ni les clients</td></tr>
<tr><td><b>Séquestre ou escrow</b></td><td>Une partie du prix est bloquée chez un tiers pour garantir la GAP</td></tr>
<tr><td><b>Earn-out</b></td><td>Un complément de prix versé si l'entreprise atteint des objectifs futurs</td></tr></table>
<div class="gstory">Karim est convaincu que son agence vaut 10 millions, le fonds n'en offre que 7. Solution : 7 millions payés à la signature, et un earn-out de 3 millions maximum si le chiffre d'affaires des deux prochaines années atteint l'objectif. Si Karim a raison, il touche ses 10 millions. S'il a tort, le fonds n'a pas surpayé.</div>`},
/*EXOS*/
{i:"p146_01",u:146,t:"match",d:.3,nw:"Les méthodes d'évaluation",q:"Associe chaque méthode à son principe.",p:[["ANC","Actif moins dettes, lu au bilan"],["Méthode comparative","Multiples d'entreprises semblables"],["DCF","Actualisation des flux de trésorerie futurs"],["Méthode mixte","Actif net réévalué plus goodwill"]],w:"Le passé, les voisins, le futur, et le mélange."},
{i:"p146_02",u:146,t:"num",d:.35,q:"Bilan d'une société : actif total 2 400 000 €, dettes 1 500 000 €. Quel est l'actif net comptable, en euros ?",a:900000,tol:1,un:" €",h:"Actif moins dettes",w:"2 400 000 - 1 500 000 = 900 000 €. C'est le chiffre de l'expert-comptable de Thomas."},
{i:"p146_03",u:146,t:"num",d:.4,q:"Une société dégage un EBE de 500 000 €. Les transactions comparables du secteur se font à 5 fois l'EBE. Quelle valeur obtient-on, en euros ?",a:2500000,tol:1,un:" €",h:"EBE multiplié par le multiple",w:"500 000 × 5 = 2 500 000 €. C'est la valeur du repreneur de Thomas, qui raisonne en comparables."},
{i:"p146_04",u:146,t:"story",d:.4,q:"Quelle est la limite principale de la méthode de l'expert-comptable ?",sc:[{who:"Thomas",txt:"Mon comptable dit que ma boîte vaut 900 000 €, la valeur du bilan. Je trouve ça injuste, j'ai des clients fidèles depuis vingt ans."}],o:["L'ANC ignore la rentabilité future et la valeur de la clientèle","L'ANC surestime toujours la valeur des entreprises de transport","L'ANC dépend trop des hypothèses de croissance futures","L'ANC n'est valable que pour les sociétés cotées en bourse"],a:0,w:"L'actif net comptable lit le passé. La clientèle fidèle, qui produira des bénéfices demain, n'y figure pas : c'est ce que capte le goodwill ou le DCF."},
{i:"p146_05",u:146,t:"sort",d:.4,q:"Avantage ou limite ?",bins:["Avantage","Limite"],it:[["DCF : valorise la capacité future",0],["DCF : très sensible aux hypothèses",1],["Comparables : colle au marché",0],["Comparables : difficile de trouver de vrais équivalents",1],["ANC : simple et objectif",0],["ANC : ignore la clientèle",1]],w:"Chaque méthode a sa force et sa faiblesse. D'où l'usage de plusieurs méthodes croisées."},
{i:"p146_06",u:146,t:"num",d:.5,ctx:"Actif net comptable corrigé : 1 200 000 €. Surprofit annuel estimé : 50 000 €, capitalisé à 10 %.",q:"Quelle valeur donne la méthode mixte, en euros ?",a:1700000,tol:1,un:" €",h:"Goodwill = surprofit / taux",w:"Goodwill : 50 000 / 10 % = 500 000 €. Valeur : 1 200 000 + 500 000 = 1 700 000 €."},
{i:"p146_07",u:146,t:"multi",d:.4,nw:"Décotes et primes",q:"Qu'est-ce qui fait baisser la valeur d'une participation ?",o:["Être minoritaire, sans pouvoir de décision","Détenir des titres non cotés difficiles à revendre","Une clientèle dépendante du dirigeant","Détenir la majorité du capital"],a:[0,1,2],w:"Décote de minorité, décote d'illiquidité, dépendance au dirigeant. La majorité, elle, justifie une prime de contrôle."},
{i:"p146_08",u:146,t:"slider",d:.4,q:"Une participation de 25 % vaut 1 000 000 € avant décote. On applique une décote de minorité de 20 %. Quelle valeur, en milliers d'euros ?",min:500,max:1000,step:10,a:800,tol:0,pre:"",un:" k€",w:"1 000 000 × (1 - 20 %) = 800 000 €. Le minoritaire achète une part du capital, pas du pouvoir."},
{i:"p146_09",u:146,t:"order",d:.35,nw:"Les étapes de la cession",q:"Remets dans l'ordre les grandes étapes d'une cession.",it:["Préparer l'entreprise","Trouver un acquéreur","Négocier","Conclure : protocole puis acte définitif","Formalités et transition"],w:"Petit Tigre Négocie Contrat Avec soin : Préparer, Trouver, Négocier, Conclure, Après."},
{i:"p146_10",u:146,t:"story",d:.45,q:"Quel document envoies-tu d'abord ?",sc:[{who:"Karim",txt:"J'ai une liste de vingt acheteurs potentiels. Je leur envoie tout le dossier de l'agence ?"},{who:"Toi",me:true,txt:"Surtout pas tout de suite."}],o:["Un teaser anonyme, puis le mémorandum après un engagement de confidentialité","Le mémorandum complet à tous, pour gagner du temps et susciter l'intérêt","La garantie d'actif et de passif déjà signée par Karim, pour rassurer d'emblée tous les candidats","Les comptes détaillés et la liste des clients, pour être transparent"],a:0,w:"Le teaser est la bande-annonce anonyme. L'information memorandum, complet, ne sort qu'après un accord de confidentialité, auprès des candidats sérieux."},
{i:"p146_11",u:146,t:"sort",d:.4,q:"Classe chaque piste de recherche de repreneur.",bins:["Cercle restreint","Marché ouvert ou intermédiaires"],it:[["Un salarié de l'entreprise",0],["La fille du dirigeant",0],["Une banque d'affaires",1],["Une annonce sur une bourse de transmission",1],["Un partenaire commercial historique",0]],w:"Cercle restreint : famille, salariés, partenaires. Marché ouvert : annonces, bourses. Intermédiaires : banques d'affaires, cabinets de fusions-acquisitions."},
{i:"p146_12",u:146,t:"fill",d:.35,q:"Le document par lequel un acquéreur exprime son intérêt et un prix indicatif s'appelle la lettre d'___.",o:["intention","engagement","exclusivité","offre ferme"],a:0,w:"La LOI, letter of intent : prix indicatif, conditions, souvent une période d'exclusivité pour faire les audits."},
{i:"p146_13",u:146,t:"multi",d:.45,q:"Quels audits le repreneur réalise-t-il avant de signer ?",o:["Audit juridique","Audit fiscal","Audit social","Audit de la vie privée du cédant"],a:[0,1,2],w:"Juridique, fiscal, social, comptable et financier. On vérifie la société, pas la vie du cédant."},
{i:"p146_14",u:146,t:"story",d:.5,nw:"La garantie d'actif et de passif",q:"Qui paie ?",ctx:"Un an après la vente de sa société, Thomas apprend que l'administration fiscale notifie un redressement de 80 000 € portant sur une année où il dirigeait encore. Une GAP a été signée, sans franchise, plafond 500 000 €.",sc:[{who:"Le repreneur",txt:"Ce redressement concerne votre gestion, pas la mienne."}],o:["Thomas indemnise l'acquéreur : c'est un passif né avant la cession","Le repreneur paie seul : il a acheté la société avec tout son passé","Ils partagent à parts égales, faute de clause de répartition","L'administration annule le redressement, la société ayant changé de main"],a:0,w:"C'est le cœur de la GAP : un événement antérieur à la cession entraînant une charge imprévue. Sans franchise et sous le plafond, Thomas indemnise 80 000 €."},
{i:"p146_15",u:146,t:"multi",d:.5,q:"Dans quels cas la GAP joue-t-elle ?",o:["Un actif était surévalué","Un passif était caché ou sous-évalué","Un événement antérieur à la cession crée une charge","Le chiffre d'affaires baisse après la vente par la faute du repreneur"],a:[0,1,2],w:"Actif surévalué, passif occulté, événement antérieur. Une baisse due à la gestion du repreneur relève de sa responsabilité à lui."},
{i:"p146_16",u:146,t:"slider",d:.4,q:"Quelle est la durée habituelle d'une GAP, hors passifs fiscaux ?",min:1,max:10,step:1,a:3,tol:1,pre:"",un:" ans",w:"En général 2 à 3 ans. Pour les passifs fiscaux, jusqu'à l'expiration du délai de reprise de l'administration."},
{i:"p146_17",u:146,t:"num",d:.55,ctx:"GAP avec une franchise de 20 000 € : en dessous de ce montant, rien n'est indemnisé, et au-dessus, seule la part excédentaire l'est. Un passif caché de 50 000 € est découvert.",q:"Quelle indemnité l'acquéreur reçoit-il, en euros ?",a:30000,tol:1,un:" €",h:"La franchise reste à sa charge",w:"50 000 - 20 000 = 30 000 €. La franchise est la part que l'acquéreur supporte lui-même."},
{i:"p146_18",u:146,t:"match",d:.45,q:"Associe chaque élément de la GAP à sa définition.",p:[["Franchise","Montant non indemnisé"],["Seuil global","Cumul à atteindre pour déclencher"],["Plafond","Indemnisation maximale"],["Durée fiscale","Jusqu'au délai de reprise du fisc"]],w:"Franchise, seuil, plafond, durée : les quatre curseurs de la négociation de la GAP."},
{i:"p146_19",u:146,t:"story",d:.5,nw:"L'earn-out",q:"Quelle clause débloque la négociation ?",ctx:"Karim estime son agence à 10 millions. Le fonds n'en offre que 7, car il doute de la croissance annoncée.",sc:[{who:"Karim",txt:"Je suis sûr de mes chiffres."},{who:"Le fonds",txt:"Alors prouvez-le."}],o:["Un earn-out : 7 millions tout de suite, jusqu'à 3 millions si les objectifs sont atteints","Un séquestre de 3 millions, bloqué chez un tiers et restitué à Karim au bout de dix ans quoi qu'il arrive","Une clause de non-concurrence de trois ans, payée 3 millions à Karim","Une décote de minorité de 30 %, compensée par une prime de contrôle"],a:0,w:"L'earn-out est un complément de prix lié aux performances futures. Si Karim a raison, il touche 10 millions ; sinon, le fonds n'a pas surpayé."},
{i:"p146_20",u:146,t:"sort",d:.45,q:"Classe chaque clause selon son but.",bins:["Protéger l'activité","Sécuriser le paiement ou le prix"],it:[["Non-concurrence",0],["Séquestre",1],["Non-sollicitation",0],["Earn-out",1]],w:"Non-concurrence et non-sollicitation protègent la valeur de l'activité. Séquestre et earn-out organisent le prix."},
{i:"p146_21",u:146,t:"tf",d:.4,q:"Une clause de non-concurrence peut interdire au cédant toute activité professionnelle, partout et pour toujours.",a:false,w:"Elle doit être limitée dans le temps, dans l'espace et quant à l'activité visée. Une interdiction générale serait disproportionnée."},
{i:"p146_22",u:146,t:"mcq",d:.45,q:"À quoi sert un séquestre, ou escrow ?",o:["Bloquer une partie du prix chez un tiers pour garantir la GAP","Verser un complément de prix selon les résultats futurs","Empêcher le cédant de débaucher les salariés","Remplacer l'acte définitif de cession"],a:0,w:"Le séquestre sécurise l'acquéreur : si la GAP joue, l'argent est déjà disponible chez le tiers."},
{i:"p146_23",u:146,t:"match",d:.45,q:"Associe chaque document à son rôle.",p:[["Teaser","Présentation anonyme courte"],["Information memorandum","Dossier complet après confidentialité"],["SPA","Protocole de cession de titres"],["APA","Protocole de cession d'actifs"]],w:"Du plus court au plus engageant : teaser, mémorandum, protocole, acte définitif."},
{i:"p146_24",u:146,t:"story",d:.5,q:"Pourquoi le cédant a-t-il aussi intérêt à la GAP ?",sc:[{who:"Thomas",txt:"La garantie de passif, c'est juste un cadeau pour l'acheteur, non ?"},{who:"Toi",me:true,txt:"C'est aussi une protection pour vous."}],o:["Elle encadre sa responsabilité : durée, franchise et plafond limitent ce qu'il devra","Elle lui permet de toucher automatiquement un complément de prix si l'entreprise se développe après la vente","Elle l'exonère d'impôt sur la plus-value de cession","Elle lui garantit de pouvoir racheter l'entreprise en cas d'échec"],a:0,w:"Sans GAP négociée, l'acquéreur pourrait agir sur d'autres fondements, sans limite claire. La GAP fixe les règles du jeu pour les deux parties."},
{i:"p146_25",u:146,t:"order",d:.5,q:"Remets dans l'ordre les formalités après la cession d'un fonds de commerce.",it:["Enregistrer l'acte auprès de l'administration fiscale","Publier la cession (annonce légale et BODACC)","Laisser courir le délai d'opposition des créanciers","Mettre à jour l'immatriculation","Accompagner le repreneur pendant la transition"],w:"Enregistrement, publicité, oppositions, immatriculation, puis transmission progressive."},
{i:"p146_26",u:146,t:"num",d:.55,q:"Méthode DCF simplifiée : un flux de trésorerie de 110 000 € est attendu dans un an. Taux d'actualisation 10 %. Quelle est sa valeur actuelle, en euros ?",a:100000,tol:1,un:" €",h:"Diviser par 1 + taux",w:"110 000 / 1,10 = 100 000 €. Le DCF additionne ces valeurs actuelles sur plusieurs années, plus une valeur terminale."},
{i:"p146_27",u:146,t:"tf",d:.45,q:"Une prime de contrôle augmente la valeur d'un bloc majoritaire.",a:true,w:"Acheter la majorité, c'est acheter le pouvoir de décider : cela se paie par une prime."},
{i:"p146_28",u:146,t:"story",d:.55,q:"Qu'est-ce qui est juste ?",ctx:"GAP : franchise 15 000 €, plafond 200 000 €. Un litige prud'homal antérieur à la vente coûte 260 000 € à la société.",sc:[{who:"Le repreneur",txt:"Thomas me doit 260 000 €."}],o:["Thomas doit 200 000 €, le plafond limitant son engagement","Thomas doit 260 000 €, la GAP couvrant tout passif antérieur","Thomas doit 245 000 €, franchise déduite, sans limite de plafond","Thomas ne doit rien, un litige prud'homal n'étant pas un passif"],a:0,w:"Franchise déduite, on obtient 245 000 €, mais le plafond de 200 000 € limite l'indemnisation. Le repreneur supporte le reste."},
{i:"p146_29",u:146,t:"fill",d:.45,q:"L'intérêt commun de la GAP pour les deux parties, c'est de créer la ___.",o:["confiance","concurrence","liquidité","décote"],a:0,w:"L'acquéreur est protégé, le cédant sait jusqu'où il s'engage : la transaction peut se conclure sereinement."},
{i:"p146_30",u:146,t:"mcq",d:.5,q:"Que signifie « délimiter le périmètre cédé » ?",o:["Définir précisément ce qui est vendu et ce qui ne l'est pas","Fixer la zone géographique de la clause de non-concurrence","Choisir les salariés qui suivront le repreneur","Calculer le montant de la décote d'illiquidité"],a:0,w:"Quelles activités, quels actifs, quels biens immobiliers, quelles filiales ? C'est la première étape de la préparation."},
{i:"p146_31",u:146,t:"story",d:.55,q:"Pourquoi ces trois valeurs sont-elles si différentes ?",sc:[{who:"Thomas",txt:"900 000 €, 2,5 millions, 4 millions. Qui a raison ?"},{who:"Toi",me:true,txt:"Chacun regarde une chose différente."}],o:["Chaque méthode mesure autre chose : le bilan, le marché, l'avenir ou l'affect","Seule la méthode de l'expert-comptable est reconnue légalement pour fixer le prix d'une cession","La plus haute est toujours la bonne, car le repreneur finit par s'aligner","La moyenne des trois est la valeur imposée par l'administration fiscale"],a:0,w:"L'ANC lit le passé, les comparables lisent le marché, le DCF lit l'avenir, et le cédant voit trente ans de sa vie. On croise les méthodes pour négocier."},
{i:"p146_32",u:146,t:"tiles",d:.4,q:"Reconstitue le principe de la garantie d'actif et de passif.",a:["Le","cédant","indemnise","l'acquéreur","pour","un","passif","antérieur","à","la","cession"],dd:["futur","repreneur","toujours"],w:"Le passé du vendeur reste de sa responsabilité, dans les limites négociées."}
