/*UNIT*/
{id:147,c:"PATRI",n:"Module 15",t:"La fiscalité de la cession",col:"--gold",ic:"🧾",guide:`
<h3>Deux personnes paient : le vendeur et l'acheteur</h3>
<div class="gstory">Thomas Garnier vend sa société 2 millions d'euros. Il imagine déjà la maison au bord du lac. Sauf que le fisc prendra sa part sur la plus-value, que l'acheteur paiera des droits d'enregistrement, et que selon que Thomas vend des actions ou des parts, qu'il part à la retraite ou non, qu'il a acheté ses titres avant ou après 2018, la facture peut varier de plusieurs centaines de milliers d'euros. Ce module est l'un des trois piliers de l'évaluation.</div>
<h3>Le vendeur : l'imposition de la plus-value</h3>
<div class="formula">Plus-value = prix de cession - prix d'acquisition

Par défaut : PFU ou « flat tax » de 31,4 % en 2026
   12,8 % d'impôt sur le revenu + 18,6 % de prélèvements sociaux
Sur option : barème progressif de l'impôt + 18,6 % de prélèvements sociaux</div>
<div class="gmnemo">« <b>Douze huit plus dix-huit six, trente et un quatre.</b> » Le PFU existe depuis le 1er janvier 2018 ; il est passé de 30 % à 31,4 % en 2026, parce que les prélèvements sociaux sont montés de 17,2 % à 18,6 %.</div>
<h3>Les abattements pour durée de détention : barème uniquement</h3>
<p>Ils ne s'appliquent que si <b>les titres ont été acquis avant le 1er janvier 2018</b> et si le vendeur <b>opte pour le barème</b>. Ils réduisent l'<b>impôt sur le revenu</b>, jamais les prélèvements sociaux, qui restent dus sur toute la plus-value.</p>
<table><tr><th>Abattement de droit commun</th><th>Abattement renforcé (PME de moins de 10 ans à l'acquisition)</th></tr>
<tr><td>2 à 8 ans : 50 %</td><td>1 à 4 ans : 50 %</td></tr>
<tr><td>8 ans et plus : 65 %</td><td>4 à 8 ans : 65 %</td></tr>
<tr><td></td><td>8 ans et plus : 85 %</td></tr></table>
<div class="gtrap">Les notes écrivent : « si on choisit le PFU, j'ai droit à un abattement de 65 % sur la plus-value ». C'est <b>faux</b> : les abattements pour durée de détention sont <b>incompatibles avec le PFU</b>. Elles écrivent aussi « départ en retraite : abattement de 85 % ». C'est une confusion : le départ en retraite ouvre un <b>abattement fixe de 500 000 €</b>, pas un pourcentage.</div>
<h3>Le départ en retraite du dirigeant : 500 000 €</h3>
<p>Un dirigeant de PME soumise à l'IS qui cède ses titres et part à la retraite peut retirer <b>500 000 €</b> de sa plus-value avant l'impôt sur le revenu, <b>même au PFU</b>. Conditions principales : avoir dirigé au moins <b>5 ans</b>, détenir au moins <b>25 %</b> des droits, céder la totalité (ou plus de 50 %) de ses titres, partir à la retraite dans les <b>2 ans</b> avant ou après la cession. Les prélèvements sociaux restent dus sur toute la plus-value. Le dispositif est prorogé jusqu'à fin 2031.</p>
<h3>Les très hauts revenus : CEHR et CDHR</h3>
<ul><li><b>CEHR</b> : 3 % de la part du revenu fiscal de référence entre 250 000 et 500 000 € (célibataire) ou 500 000 et 1 000 000 € (couple), 4 % au-delà.</li>
<li><b>CDHR</b> : garantit une imposition minimale de <b>20 % du RFR</b> au-delà de 250 000 € (célibataire) ou 500 000 € (couple). Réflexe du cours : <b>calculer si le client dépasse les 20 % sur son RFR</b>. Le fait que ce soit sur le RFR change tout : une grosse plus-value l'année de la vente peut déclencher la contribution.</li></ul>
<h3>L'acheteur : les droits d'enregistrement</h3>
<table><tr><th>Ce qui est acheté</th><th>Droits</th></tr>
<tr><td>Actions (SAS, SA)</td><td><b>0,1 %</b> du prix</td></tr>
<tr><td>Parts sociales (SARL)</td><td><b>3 %</b> après un abattement de 23 000 € proratisé selon la part du capital cédée</td></tr>
<tr><td>Parts d'une société à prépondérance immobilière</td><td><b>5 %</b></td></tr>
<tr><td>Fonds de commerce</td><td><b>0 %</b> jusqu'à 23 000 €, <b>3 %</b> de 23 000 à 200 000 €, <b>5 %</b> au-delà</td></tr></table>
<div class="formula">Exemple du cours : fonds de commerce de 400 000 €
  0 à 23 000        : 0 %
  23 000 à 200 000  : 3 % × 177 000 = 5 310 €
  au-delà           : 5 % × 200 000 = 10 000 €
  Total : 15 310 €</div>
<div class="gtrap">Les notes disent « même barème pour les parts que pour le fonds de commerce ». Faux : les parts de SARL sont taxées à <b>3 %</b> après un abattement de 23 000 € au prorata, pas au barème 0/3/5 du fonds. Les actions, elles, ne supportent que 0,1 %.</div>
<div class="gmnemo">« <b>Zéro, trois, cinq, avec deux frontières : vingt-trois mille et deux cent mille.</b> » Pour le fonds de commerce. Et « <b>un pour mille pour les actions</b> » : 0,1 %.</div>
<h3>Céder un fonds de commerce : les exonérations</h3>
<table><tr><th>Dispositif</th><th>Condition clé</th><th>Effet</th></tr>
<tr><td>Selon les recettes</td><td>Activité exercée depuis 5 ans ; recettes sous 250 000 € (ventes) ou 90 000 € (services)</td><td>Exonération totale, dégressive jusqu'à 350 000 € ou 126 000 €</td></tr>
<tr><td>Selon la valeur transmise</td><td>Activité de 5 ans, transmission d'une entreprise ou d'une branche complète</td><td>Exonération totale si la valeur est inférieure à 500 000 €, partielle jusqu'à 1 000 000 €</td></tr>
<tr><td>Départ en retraite de l'entrepreneur individuel</td><td>5 ans d'activité, cession intégrale, retraite dans les 2 ans</td><td>Exonération d'impôt sur le revenu sur la plus-value professionnelle</td></tr>
<tr><td>Transmission agricole à un jeune agriculteur</td><td>Activité agricole de 5 ans</td><td>Exonération totale sous 700 000 €, partielle jusqu'à 1 200 000 €</td></tr></table>
<div class="gtrap">Les notes parlent de « -90 K d'exonération en BNC et -250 K en BIC ». Ce ne sont pas des montants exonérés mais des <b>seuils de recettes</b> sous lesquels la plus-value est exonérée. Et les montants « 300 K et 450 K » pour l'agriculture ne correspondent pas au régime actuel : les seuils pour une transmission à un jeune agriculteur sont de <b>700 000 € et 1 200 000 €</b> depuis 2025.</div>`},
/*EXOS*/
{i:"p147_01",u:147,t:"match",d:.3,nw:"Le PFU en 2026",q:"Associe chaque composante de la flat tax 2026 à son taux.",p:[["Impôt sur le revenu","12,8 %"],["Prélèvements sociaux","18,6 %"],["PFU total","31,4 %"],["PFU avant 2026","30 %"]],w:"Douze huit plus dix-huit six, trente et un quatre. La hausse de 2026 vient des prélèvements sociaux, passés de 17,2 % à 18,6 %."},
{i:"p147_02",u:147,t:"num",d:.35,q:"Plus-value de cession de titres de 100 000 € en 2026, au PFU, sans abattement. Combien d'impôt et de prélèvements, en euros ?",a:31400,tol:1,un:" €",h:"31,4 %",w:"100 000 × 31,4 % = 31 400 €, dont 12 800 € d'impôt et 18 600 € de prélèvements sociaux."},
{i:"p147_03",u:147,t:"story",d:.4,nw:"Abattements et PFU",q:"Qu'est-ce qui est juste ?",ctx:"Thomas a acheté ses titres en 2008. Il les vend en 2026 avec une plus-value de 150 000 €.",sc:[{who:"Thomas",txt:"J'ai lu qu'avec le PFU, j'ai droit à 65 % d'abattement parce que je les détiens depuis plus de huit ans."}],o:["Les abattements pour durée de détention ne jouent qu'en optant pour le barème","Oui, 65 % d'abattement s'appliquent sur l'impôt et les prélèvements sociaux","Oui, mais seulement 50 %, car le PFU divise par deux tous les abattements pour durée de détention","Non, aucun abattement n'existe plus depuis la création du PFU en 2018"],a:0,w:"Les abattements pour durée de détention sont incompatibles avec le PFU. Titres acquis avant 2018 : il faut opter pour le barème pour en profiter, et ils ne réduisent jamais les prélèvements sociaux."},
{i:"p147_04",u:147,t:"sort",d:.4,q:"Classe chaque abattement.",bins:["Droit commun","Renforcé (PME)"],it:[["50 % entre 2 et 8 ans",0],["65 % au-delà de 8 ans",0],["50 % entre 1 et 4 ans",1],["65 % entre 4 et 8 ans",1],["85 % au-delà de 8 ans",1]],w:"Droit commun : 50 % puis 65 %. Renforcé : 50 %, 65 %, 85 %. Uniquement au barème, titres acquis avant 2018."},
{i:"p147_05",u:147,t:"num",d:.55,ctx:"Thomas vend en 2026 des titres acquis en 2008, plus-value 150 000 €. Il opte pour le barème. Abattement de droit commun (plus de 8 ans). Sa tranche marginale d'impôt est de 30 %. On simplifie : l'impôt = base après abattement × 30 %, et les prélèvements sociaux sont dus sur toute la plus-value.",q:"Combien paie-t-il au total, en euros ?",a:43650,tol:1,un:" €",h:"Impôt sur 35 % de la plus-value, prélèvements sur 100 %",w:"Base d'impôt : 150 000 × 35 % = 52 500, × 30 % = 15 750 €. Prélèvements : 150 000 × 18,6 % = 27 900 €. Total : 43 650 €, contre 47 100 € au PFU."},
{i:"p147_06",u:147,t:"story",d:.5,nw:"Le départ en retraite du dirigeant",q:"Que dis-tu à Thomas ?",ctx:"Thomas, 62 ans, dirige sa PME à l'IS depuis vingt ans et en détient 80 %. Il la vend en totalité et part à la retraite dans six mois.",sc:[{who:"Thomas",txt:"Mes notes disent que le départ en retraite donne 85 % d'abattement."}],o:["C'est un abattement fixe de 500 000 € sur la plus-value, même au PFU","C'est bien 85 % d'abattement, applicable au PFU comme au barème","C'est 85 % d'abattement, mais seulement sur les prélèvements sociaux","Le départ en retraite ne donne aucun avantage sur la cession de titres"],a:0,w:"Confusion fréquente : 85 % est l'abattement renforcé pour durée de détention. Le départ en retraite ouvre un abattement fixe de 500 000 € sur l'impôt, compatible avec le PFU. Les prélèvements sociaux restent dus sur tout."},
{i:"p147_07",u:147,t:"num",d:.6,ctx:"Thomas remplit les conditions de l'abattement de 500 000 € pour départ en retraite. Plus-value : 800 000 €. Il reste au PFU.",q:"Combien paie-t-il au total, en euros ?",a:187200,tol:1,un:" €",h:"12,8 % sur la plus-value après abattement, 18,6 % sur toute la plus-value",w:"Impôt : (800 000 - 500 000) × 12,8 % = 38 400 €. Prélèvements : 800 000 × 18,6 % = 148 800 €. Total : 187 200 €."},
{i:"p147_08",u:147,t:"multi",d:.5,q:"Quelles conditions pour l'abattement de 500 000 € au départ en retraite ?",o:["Avoir dirigé la société pendant au moins 5 ans","Détenir au moins 25 % des droits","Partir à la retraite dans les 2 ans avant ou après la cession","Avoir acquis les titres avant le 1er janvier 2018"],a:[0,1,2],w:"Direction 5 ans, 25 % des droits, cession de tout ou plus de la moitié, retraite dans les 2 ans. La date d'acquisition avant 2018 concerne les abattements pour durée de détention, pas celui-ci."},
{i:"p147_09",u:147,t:"num",d:.4,q:"Exemple du cours : droits d'enregistrement sur un fonds de commerce vendu 400 000 €. Combien, en euros ?",a:15310,tol:1,un:" €",h:"0 %, 3 %, 5 %",w:"0 % jusqu'à 23 000. 3 % × 177 000 = 5 310. 5 % × 200 000 = 10 000. Total : 15 310 €, payés par l'acquéreur."},
{i:"p147_10",u:147,t:"slider",d:.35,q:"Quel taux de droits d'enregistrement sur l'achat d'actions de SAS ?",min:0,max:5,step:.1,a:.1,tol:0,pre:"",un:" %",w:"Un pour mille : 0,1 %. C'est l'une des raisons de la popularité de la SAS en cas de cession."},
{i:"p147_11",u:147,t:"story",d:.5,nw:"Parts de SARL",q:"Quelle correction apportes-tu ?",sc:[{who:"Ton stagiaire",txt:"Pour les parts de SARL, j'ai appliqué le barème du fonds de commerce, 0, 3 et 5 %, comme dans mes notes."}],o:["Parts de SARL : 3 % après un abattement de 23 000 € proratisé","C'est juste : parts de SARL et fonds de commerce suivent le même barème","Parts de SARL : 0,1 %, comme les actions de toutes les sociétés","Parts de SARL : 5 % sur la totalité du prix, sans abattement"],a:0,w:"Parts sociales : 3 %, après un abattement de 23 000 € multiplié par la fraction du capital cédée. Le barème 0/3/5 est propre au fonds de commerce."},
{i:"p147_12",u:147,t:"num",d:.6,ctx:"Une SARL a 1 000 parts. Un associé en cède 400 pour 300 000 €. Ce n'est pas une société immobilière.",q:"Combien de droits d'enregistrement l'acquéreur paie-t-il, en euros ?",a:8724,tol:1,un:" €",h:"Abattement : 23 000 × 400 / 1 000",w:"Abattement : 23 000 × 40 % = 9 200 €. Base : 290 800 €. Droits : 3 % = 8 724 €."},
{i:"p147_13",u:147,t:"sort",d:.45,q:"Classe chaque acquisition selon son taux de droits.",bins:["0,1 %","3 % (après abattement)","5 %"],it:[["Actions d'une SA",0],["Parts d'une SARL commerciale",1],["Parts d'une SCI à prépondérance immobilière",2],["Actions d'une SAS",0]],w:"Actions : 0,1 %. Parts sociales : 3 % après abattement. Société à prépondérance immobilière : 5 %."},
{i:"p147_14",u:147,t:"tf",d:.35,q:"Les abattements pour durée de détention réduisent aussi les prélèvements sociaux.",a:false,w:"Ils ne réduisent que l'impôt sur le revenu. Les 18,6 % de prélèvements sociaux s'appliquent à toute la plus-value."},
{i:"p147_15",u:147,t:"story",d:.5,nw:"La CDHR",q:"Quel réflexe as-tu ?",ctx:"Karim, célibataire, vend son agence en 2026 avec une plus-value de 6 millions. Son revenu fiscal de référence explose cette année-là.",sc:[{who:"Karim",txt:"Au PFU, je paie 31,4 %, et c'est fini."}],o:["Vérifier la CEHR et que son imposition atteint 20 % du RFR, sinon la CDHR s'ajoute","Rien d'autre : le PFU est libératoire de toute contribution supplémentaire","Opter pour le barème progressif, qui supprime automatiquement la CEHR et la CDHR sur la plus-value","Étaler la vente sur dix ans, seule façon légale d'éviter la CEHR"],a:0,w:"Une grosse plus-value gonfle le RFR : CEHR de 3 % puis 4 %, et la CDHR garantit une imposition d'au moins 20 % du RFR. Le cours insiste : c'est sur le RFR, et ça change tout."},
{i:"p147_16",u:147,t:"slider",d:.45,q:"Imposition minimale garantie par la CDHR, en pourcentage du RFR ?",min:5,max:50,step:1,a:20,tol:0,pre:"",un:" %",w:"20 % du revenu fiscal de référence, au-delà de 250 000 € pour un célibataire ou 500 000 € pour un couple."},
{i:"p147_17",u:147,t:"match",d:.45,q:"Associe chaque dispositif à son critère principal.",p:[["Exonération selon les recettes","Recettes sous 250 000 € ou 90 000 €"],["Exonération selon la valeur","Valeur transmise sous 500 000 €"],["Abattement retraite sur titres","500 000 € fixes"],["Jeune agriculteur","Valeur sous 700 000 €"]],w:"Recettes, valeur, retraite, agriculture : quatre portes d'exonération, chacune avec ses seuils."},
{i:"p147_18",u:147,t:"story",d:.55,q:"Que corriges-tu ?",sc:[{who:"Ta collègue",txt:"Dans mes notes : BNC, 90 K d'exonération ; BIC, 250 K d'exonération."}],o:["Ce sont des seuils de recettes sous lesquels la plus-value est exonérée","Ce sont les montants de plus-value exonérés, au-delà tout est taxé","Ce sont les plafonds d'abattement du PFU pour les professions libérales","Ce sont les seuils de chiffre d'affaires pour créer une SARL"],a:0,w:"90 000 € (services) et 250 000 € (ventes) sont des seuils de recettes annuelles moyennes. En dessous, exonération totale, puis dégressive jusqu'à 126 000 € et 350 000 €."},
{i:"p147_19",u:147,t:"num",d:.45,q:"Droits d'enregistrement sur un fonds de commerce vendu 150 000 € ?",a:3810,tol:1,un:" €",h:"Rien sur les 23 000 premiers euros",w:"(150 000 - 23 000) × 3 % = 3 810 €. On n'atteint pas la tranche à 5 %."},
{i:"p147_20",u:147,t:"multi",d:.5,q:"Quand l'option pour le barème peut-elle battre le PFU ?",o:["Titres acquis avant 2018 et détenus longtemps, grâce aux abattements","Contribuable faiblement imposé, avec une tranche marginale basse","Abattement renforcé de 85 % sur des titres de PME","Titres acquis en 2022, détenus trois ans"],a:[0,1,2],w:"Le barème gagne quand un abattement s'applique ou quand la tranche marginale est basse. Pour des titres acquis après 2018 par un contribuable très imposé, le PFU gagne presque toujours. Et l'option vaut pour tous les revenus du capital de l'année."},
{i:"p147_21",u:147,t:"tf",d:.45,q:"L'abattement de 500 000 € pour départ en retraite peut s'appliquer avec le PFU.",a:true,w:"Oui, contrairement aux abattements pour durée de détention. Il réduit l'impôt sur le revenu, pas les prélèvements sociaux."},
{i:"p147_22",u:147,t:"story",d:.5,q:"Quelle exonération vises-tu ?",ctx:"Martine exploite un salon de coiffure en entreprise individuelle depuis 12 ans. Ses recettes annuelles sont d'environ 85 000 €. Elle vend son fonds pour s'installer à l'étranger.",sc:[{who:"Martine",txt:"Je vais payer combien sur la plus-value ?"}],o:["Exonération selon les recettes : sous 90 000 € pour une activité de services","Abattement de 500 000 € pour départ en retraite, applicable à tout vendeur","Aucune exonération possible, puisqu'elle quitte la France juste après la vente du fonds","Abattement renforcé de 85 %, car elle exerce depuis plus de 8 ans"],a:0,w:"Prestation de services, activité de plus de 5 ans, recettes sous 90 000 € : exonération totale de la plus-value professionnelle selon les recettes."},
{i:"p147_23",u:147,t:"fill",d:.4,q:"Le PFU a été mis en place le 1er janvier ___.",o:["2018","2013","2020","2026"],a:0,w:"2018 : c'est aussi la date qui sépare les titres ouvrant droit aux abattements pour durée de détention (acquis avant) de ceux qui n'y ont pas droit."},
{i:"p147_24",u:147,t:"order",d:.45,q:"Remets dans l'ordre le calcul de l'impôt d'un vendeur de titres.",it:["Calculer la plus-value : prix de vente moins prix d'achat","Vérifier les abattements possibles, dont celui de 500 000 € au départ en retraite","Comparer PFU et option pour le barème","Ajouter les prélèvements sociaux sur toute la plus-value","Contrôler la CEHR et la CDHR sur le RFR"],w:"Plus-value, abattements, choix du régime, prélèvements sociaux, hauts revenus."},
{i:"p147_25",u:147,t:"mcq",d:.45,q:"Qui paie les droits d'enregistrement lors d'une cession ?",o:["L'acquéreur, en principe","Le cédant, toujours","Moitié chacun, par la loi","La société cédée"],a:0,w:"Les droits d'enregistrement sont en principe à la charge de l'acquéreur. Le vendeur, lui, paie l'impôt sur la plus-value."},
{i:"p147_26",u:147,t:"num",d:.55,q:"Un acquéreur achète des actions de SAS pour 2 000 000 €. Combien de droits d'enregistrement, en euros ?",a:2000,tol:1,un:" €",h:"Un pour mille",w:"2 000 000 × 0,1 % = 2 000 €. En parts de SARL, pour le même prix, ce serait autour de 60 000 €."},
{i:"p147_27",u:147,t:"story",d:.55,q:"Quel est le bon chiffre pour une transmission à un jeune agriculteur ?",sc:[{who:"Un exploitant",txt:"Mon comptable m'a parlé de 300 000 € ou 450 000 € d'exonération si je cède à un jeune."}],o:["Depuis 2025 : exonération totale sous 700 000 €, partielle jusqu'à 1 200 000 €","C'est bien 300 000 € hors taxes pour un tiers repreneur et 450 000 € pour un jeune agriculteur","C'est 500 000 € pour tous les agriculteurs, sans distinction d'âge","Il n'existe aucun régime spécifique pour les transmissions agricoles"],a:0,w:"Les seuils de tes notes ne correspondent pas au régime actuel. Pour une transmission à un jeune agriculteur, l'exonération est totale sous 700 000 € et dégressive jusqu'à 1 200 000 €."},
{i:"p147_28",u:147,t:"tf",d:.5,q:"Pour des titres acquis en 2020, un vendeur qui opte pour le barème bénéficie de l'abattement de droit commun de 50 % après deux ans.",a:false,w:"Les abattements pour durée de détention ne concernent que les titres acquis avant le 1er janvier 2018."},
{i:"p147_29",u:147,t:"tiles",d:.35,q:"Reconstitue la composition du PFU 2026.",a:["12,8","%","d'impôt","plus","18,6","%","de","prélèvements","sociaux"],dd:["17,2","30","abattement"],w:"31,4 % au total. Les anciens chiffres (17,2 % et 30 %) sont les pièges à éviter."},
{i:"p147_30",u:147,t:"slider",d:.5,q:"Au-delà de quel montant le fonds de commerce est-il taxé à 5 % pour l'acquéreur ?",min:23000,max:500000,step:1000,a:200000,tol:0,pre:"",un:" €",w:"Deux frontières : 23 000 € et 200 000 €. Zéro, trois, cinq."},
{i:"p147_31",u:147,t:"story",d:.55,q:"Actions ou parts : que conseilles-tu ?",ctx:"Deux associés créent une société qu'ils comptent revendre dans quelques années. Ils hésitent entre SAS et SARL.",sc:[{who:"L'un des associés",txt:"Pour la revente, ça change quelque chose ?"}],o:["Pour l'acheteur, oui : 0,1 % sur des actions contre 3 % sur des parts","Non : actions et parts supportent exactement les mêmes droits","Oui : la SARL permet d'éviter l'impôt sur la plus-value du vendeur","Oui : la SAS impose l'abattement de 500 000 € à la revente"],a:0,w:"Les droits d'enregistrement pèsent sur l'acquéreur, donc sur le prix qu'il acceptera de payer. La SAS rend la revente plus fluide."},
{i:"p147_32",u:147,t:"mcq",d:.5,q:"Une entreprise individuelle part à la retraite et cède intégralement son activité exercée depuis 10 ans. Quel dispositif vise-t-on ?",o:["L'exonération de la plus-value professionnelle pour départ en retraite","L'abattement fixe de 500 000 € sur les titres de PME","L'abattement renforcé de 85 % pour durée de détention","Le pacte Dutreil appliqué à la cession à titre onéreux"],a:0,w:"Pour l'entrepreneur individuel, le départ en retraite exonère d'impôt la plus-value professionnelle (sous conditions). L'abattement de 500 000 € vise les cessions de titres de sociétés."}
