/*UNIT*/
{id:148,c:"PATRI",n:"Module 16",t:"Pacte Dutreil et holding",col:"--gold",ic:"🏛️",guide:`
<h3>Thomas et Léa : 78 000 € ou 1 600 €</h3>
<div class="gstory">Thomas Garnier, 64 ans, veut transmettre sa société de transport, valorisée 500 000 €, à sa fille Léa, qui y travaille depuis huit ans. S'il donne sans rien préparer, Léa paiera environ <b>78 000 €</b> de droits. Avec un pacte Dutreil et une donation avant ses 70 ans, elle en paiera environ <b>1 600 €</b>. Même entreprise, même famille, même notaire. La seule différence : deux engagements signés à temps.</div>
<h3>Le pacte Dutreil : la règle en vigueur</h3>
<ul><li><b>Engagement collectif</b> de conservation : les associés s'engagent à garder les titres au moins <b>2 ans</b>.</li>
<li><b>Engagement individuel</b> : celui qui reçoit les titres s'engage à les garder <b>6 ans</b> de plus.</li>
<li>Conservation totale minimale : <b>8 ans</b> (2 + 6).</li>
<li>L'un des signataires ou des bénéficiaires doit <b>diriger</b> l'entreprise pendant l'engagement collectif et <b>3 ans</b> après la transmission : un des signataires doit reprendre l'entreprise.</li>
<li>Effet : <b>exonération de 75 % de la valeur des titres</b> transmis, par donation ou succession. Les actifs de loisir (résidence non professionnelle, yacht, voiture de luxe) sont exclus de l'exonération.</li></ul>
<div class="gtrap">Tes notes donnent 2 ans + 4 ans = 6 ans. C'était la règle jusqu'au 20 février 2026. Pour les transmissions depuis le <b>21 février 2026</b> (loi de finances pour 2026), l'engagement individuel est de <b>6 ans</b>, soit <b>8 ans</b> au total.</div>
<div class="gmnemo">« <b>Deux, six, huit, soixante-quinze.</b> » Deux ans ensemble, six ans seul, huit au total, soixante-quinze pour cent d'exonération. Et le bonus : « <b>moins de 70 ans, moitié prix</b> ».</div>
<h3>Le piège du « 75 % »</h3>
<p>Les 75 % portent sur la <b>base taxable</b> (la valeur de l'entreprise), <b>pas</b> sur les droits à payer. Ensuite, on applique l'abattement personnel de 100 000 € et le barème. Et si c'est une <b>donation en pleine propriété</b> consentie par un donateur de <b>moins de 70 ans</b>, les droits obtenus sont encore <b>réduits de 50 %</b>.</p>
<div class="formula">Thomas donne à Léa une société de 500 000 €

Sans Dutreil : 500 000 - 100 000 = 400 000 taxables
               20 % × 400 000 - 1 805,65 = 78 194 €

Avec Dutreil : base 25 % × 500 000 = 125 000
               - 100 000 d'abattement = 25 000 taxables
               20 % × 25 000 - 1 805,65 = 3 194 €
               donation avant 70 ans : réduction de 50 % → 1 597 €</div>
<p>Le pacte est possible sur une <b>holding</b> si elle est <b>animatrice</b> : elle pilote réellement ses filiales, au-delà de la simple détention.</p>
<h3>La holding</h3>
<p>Une holding est une société qui détient des participations dans d'autres sociétés. On en crée souvent <b>quand on achète</b> une entreprise ou <b>quand on anticipe de la vendre</b>.</p>
<table><tr><th>Régime</th><th>Condition</th><th>Dividendes remontés</th></tr>
<tr><td><b>Mère-fille</b></td><td>Au moins 5 % du capital, conservés 2 ans</td><td>Exonérés à 95 % : quote-part de 5 % taxée à l'IS de 25 %, soit <b>1,25 %</b></td></tr>
<tr><td><b>Intégration fiscale</b></td><td>Au moins 95 % du capital</td><td>Quote-part de 1 % taxée à 25 %, soit <b>0,25 %</b></td></tr></table>
<div class="gtrap">Les notes disent que l'intégration fiscale n'est « pas du tout taxée ». C'est presque vrai : il reste une quote-part de <b>1 %</b>, soit 0,25 % d'impôt effectif. Elles disent aussi que les dividendes sont « touchés par la holding et par la personne physique ». En réalité, ils sont d'abord reçus par la holding quasiment sans impôt. Ils ne sont taxés chez la personne que si la holding les lui redistribue.</div>
<div class="gmnemo">« <b>Cinq pour cent de vingt-cinq pour cent, un et quart.</b> » Mère-fille : 5 % × 25 % = 1,25 %. Intégration : 1 % × 25 % = 0,25 %. Face aux 31,4 % d'une personne physique, la holding a trente points d'avance pour rembourser un emprunt.</div>
<h3>Pourquoi une holding pour racheter ?</h3>
<p>Une personne physique qui emprunte pour racheter une société doit se verser des dividendes taxés à 31,4 % avant de rembourser. Une holding reçoit ces dividendes presque sans impôt : sa <b>capacité d'endettement</b> et donc sa <b>capacité d'acquisition</b> sont bien plus fortes.</p>
<h3>L'apport-cession : un report, pas une exonération</h3>
<ul><li>Le dirigeant <b>apporte</b> ses titres à une holding qu'il contrôle. La plus-value d'apport est calculée, mais son imposition est <b>reportée</b> : c'est le <b>report d'imposition</b>.</li>
<li>La holding revend ensuite les titres. Comme elle les a reçus à leur valeur actuelle, elle ne réalise pratiquement pas de plus-value.</li>
<li>Si la holding revend dans les <b>3 ans</b> suivant l'apport, elle doit <b>réinvestir au moins 70 %</b> du prix (60 % pour les cessions avant le 21 février 2026) dans une activité économique, dans les <b>2 ans</b>. Sinon, le report tombe.</li>
<li>L'argent reste dans la holding : on <b>ne peut pas</b> s'en servir pour acheter une maison secondaire à titre personnel. La holding sert à <b>réinvestir</b>.</li></ul>
<div class="gmnemo">« <b>La holding ne supprime pas l'impôt, elle le fait attendre.</b> » Report, pas cadeau. Et la règle des chiffres : « <b>trois ans pour vendre, deux ans pour réinvestir, soixante-dix pour cent au minimum</b> ».</div>
<h3>Ce sur quoi porte l'évaluation</h3>
<p>Le professeur a annoncé six thèmes : <b>régime</b> matrimonial, <b>ordre</b> des héritiers, <b>Dutreil</b>, <b>démembrement</b>, <b>holding</b>, <b>fiscalité</b>. </p>
<div class="gmnemo">« <b>RO</b>déo <b>D</b>u <b>D</b>imanche : <b>H</b>old-up <b>F</b>iscal » : <b>R</b>égime, <b>O</b>rdre, <b>D</b>utreil, <b>D</b>émembrement, <b>H</b>olding, <b>F</b>iscalité. Imagine un rodéo où chaque cavalier porte un de ces six mots sur son dossard.</div>`},
/*EXOS*/
{i:"p148_01",u:148,t:"match",d:.3,nw:"Le pacte Dutreil",q:"Associe chaque élément du pacte Dutreil à sa valeur en vigueur.",p:[["Engagement collectif","2 ans minimum"],["Engagement individuel","6 ans"],["Conservation totale minimale","8 ans"],["Exonération","75 % de la valeur des titres"]],w:"Deux, six, huit, soixante-quinze. Règle applicable aux transmissions depuis le 21 février 2026."},
{i:"p148_02",u:148,t:"slider",d:.35,q:"Durée totale minimale de conservation des titres avec un pacte Dutreil, en 2026 ?",min:2,max:12,step:1,a:8,tol:0,pre:"",un:" ans",w:"2 ans d'engagement collectif + 6 ans d'engagement individuel = 8 ans. Tes notes indiquent 6 ans : c'était l'ancienne règle."},
{i:"p148_03",u:148,t:"num",d:.4,ctx:"Thomas donne à Léa sa société valorisée 500 000 €, sans pacte Dutreil. Aucune donation antérieure.",q:"Combien Léa paie-t-elle de droits, en euros ? (arrondi à l'euro)",a:78194,tol:2,un:" €",h:"Abattement, puis 20 % - 1 805,65",w:"500 000 - 100 000 = 400 000. 20 % × 400 000 - 1 805,65 = 78 194 €. C'est le chiffre de tes notes, qui est juste."},
{i:"p148_04",u:148,t:"num",d:.5,ctx:"Même donation de 500 000 € à Léa, mais avec un pacte Dutreil. On ne tient pas encore compte de la réduction pour âge.",q:"Combien Léa paie-t-elle, en euros ? (arrondi à l'euro)",a:3194,tol:2,un:" €",h:"75 % d'exonération sur la base, puis abattement",w:"Base : 25 % × 500 000 = 125 000. Moins 100 000 : 25 000 taxables. 20 % × 25 000 - 1 805,65 = 3 194 €."},
{i:"p148_05",u:148,t:"story",d:.5,nw:"Le piège des 75 %",q:"Qu'est-ce qui cloche dans son calcul ?",sc:[{who:"Ton stagiaire",txt:"Sans Dutreil, Léa paie 78 194 €. Avec Dutreil, 75 % d'exonération : je retire 75 % des droits, elle paie 19 548 €."}],o:["Les 75 % s'appliquent à la valeur de l'entreprise, pas aux droits : elle paie 3 194 €","Le calcul est juste : l'exonération Dutreil porte bien sur 75 % des droits calculés sans le pacte","Il fallait retirer 75 % de l'abattement de 100 000 €, pas des droits","Il fallait appliquer 75 % après la réduction de 50 %, soit 9 774 €"],a:0,w:"Tes notes le soulignent : ce sont 75 % de la base taxable, pas 75 % des droits. On réduit la valeur, puis on applique abattement et barème."},
{i:"p148_06",u:148,t:"story",d:.5,nw:"La réduction de 50 %",q:"Combien paiera Léa si Thomas donne avant ses 70 ans ?",ctx:"Donation en pleine propriété, avec pacte Dutreil. Thomas a 64 ans. Droits calculés avant réduction : 3 194 €.",sc:[{who:"Thomas",txt:"On m'a parlé d'une réduction en plus si je donne tôt."}],o:["Environ 1 597 € : moitié des droits, car il a moins de 70 ans","3 194 € : la réduction de 50 % ne se cumule jamais avec le Dutreil","0 € : avec un Dutreil avant 70 ans, les droits sont totalement effacés","Environ 799 € : la réduction de 50 % s'applique deux fois pour un enfant"],a:0,w:"Les 75 % d'exonération se cumulent avec la réduction de 50 % des droits si la donation est en pleine propriété et que le donateur a moins de 70 ans."},
{i:"p148_07",u:148,t:"multi",d:.45,q:"Quelles sont les conditions du pacte Dutreil ?",o:["Un engagement collectif de conservation d'au moins 2 ans","Un engagement individuel de 6 ans","Qu'un signataire ou bénéficiaire dirige l'entreprise","Que le donateur ait moins de 60 ans"],a:[0,1,2],w:"Engagement collectif, engagement individuel, fonction de direction. L'âge du donateur ne conditionne pas le Dutreil, seulement la réduction supplémentaire de 50 %."},
{i:"p148_08",u:148,t:"tf",d:.4,q:"Un pacte Dutreil peut porter sur une holding, à condition qu'elle soit animatrice.",a:true,w:"Une holding animatrice pilote réellement ses filiales. Ton cours dit « opérationnelle » : c'est l'idée."},
{i:"p148_09",u:148,t:"sort",d:.45,q:"Classe ces actifs d'une société sous pacte Dutreil.",bins:["Exonération de 75 % possible","Exclu de l'exonération"],it:[["Les camions de l'entreprise de transport",0],["Un yacht détenu par la société",1],["Les entrepôts d'exploitation",0],["Une résidence non affectée à l'activité",1],["Le fonds de commerce",0]],w:"Depuis 2026, les actifs de loisir qui ne servent pas exclusivement à l'activité sont exclus des 75 %."},
{i:"p148_10",u:148,t:"story",d:.55,q:"Combien paie chaque enfant ?",ctx:"Un père de 65 ans donne en pleine propriété, avec un pacte Dutreil, une société de 2 000 000 € à ses deux enfants, à parts égales. Aucune donation depuis 15 ans.",sc:[{who:"Le fils",txt:"On part sur combien chacun ?"}],o:["Environ 14 097 € : base 250 000, abattement, barème, puis moitié","Environ 28 194 € : la réduction de 50 % ne concerne pas les sociétés","Environ 98 194 € : le Dutreil ne s'applique qu'à un seul enfant","Rien : 2 000 000 € partagés restent sous les abattements"],a:0,w:"Chaque enfant reçoit 1 000 000 €. Base : 25 % = 250 000. Moins 100 000 : 150 000. Droits : 20 % × 150 000 - 1 805,65 = 28 194. Réduction de 50 % (donation en PP avant 70 ans) : 14 097 €."},
{i:"p148_11",u:148,t:"mcq",d:.4,nw:"La holding",q:"Quand crée-t-on souvent une holding, selon le cours ?",o:["Quand on achète une entreprise ou qu'on anticipe de la vendre","Uniquement quand on part à la retraite","Uniquement pour détenir sa résidence principale","Quand on se marie sans contrat"],a:0,w:"On crée une holding pour racheter (capacité d'emprunt) ou pour préparer une vente (apport-cession)."},
{i:"p148_12",u:148,t:"num",d:.45,q:"Une filiale verse 1 000 000 € de dividendes à sa holding, sous le régime mère-fille. Impôt sur les sociétés à 25 %. Combien d'impôt la holding paie-t-elle, en euros ?",a:12500,tol:1,un:" €",h:"Quote-part de 5 %",w:"1 000 000 × 5 % × 25 % = 12 500 €, soit 1,25 %. Une personne physique aurait payé 314 000 € au PFU."},
{i:"p148_13",u:148,t:"slider",d:.45,q:"Quel est le taux d'imposition effectif des dividendes en intégration fiscale ?",min:0,max:5,step:.05,a:.25,tol:0,pre:"",un:" %",w:"Quote-part de 1 % × IS de 25 % = 0,25 %. Pas « zéro » comme dans tes notes."},
{i:"p148_14",u:148,t:"match",d:.45,q:"Associe chaque régime à sa condition et à son coût.",p:[["Mère-fille","5 % du capital, 1,25 % d'impôt"],["Intégration fiscale","95 % du capital, 0,25 % d'impôt"],["Personne physique au PFU","31,4 % en 2026"],["Apport-cession","Report d'imposition"]],w:"Cinq pour cent de vingt-cinq pour cent, un et quart. L'écart avec 31,4 % explique la force de la holding de rachat."},
{i:"p148_15",u:148,t:"story",d:.5,q:"Pourquoi Karim devrait-il racheter via une holding ?",ctx:"Karim veut racheter une agence concurrente pour 3 millions d'euros, en empruntant. La cible dégage 400 000 € de bénéfices distribuables par an.",sc:[{who:"Karim",txt:"J'emprunte en mon nom et je rembourse avec les dividendes, c'est pareil, non ?"}],o:["En direct, il paierait 31,4 % sur chaque dividende avant de rembourser ; via une holding, 1,25 %","C'est pareil : la holding et la personne physique paient le même impôt sur les dividendes","La holding est interdite pour racheter un concurrent direct, au nom du droit de la concurrence européen","Via une holding, les dividendes sont totalement exonérés et l'emprunt disparaît"],a:0,w:"Sur 400 000 €, il resterait 274 400 € en direct, contre 395 000 € dans une holding sous mère-fille. Même emprunt, beaucoup plus de capacité de remboursement."},
{i:"p148_16",u:148,t:"tf",d:.4,q:"La holding permet d'échapper définitivement à l'impôt sur la plus-value de cession.",a:false,w:"C'est un report d'imposition, pas une exonération : l'impôt est calculé, puis payé plus tard si le report prend fin. La holding ne supprime pas l'impôt, elle le fait attendre."},
{i:"p148_17",u:148,t:"order",d:.45,nw:"L'apport-cession",q:"Remets dans l'ordre le mécanisme de l'apport-cession.",it:["Le dirigeant apporte ses titres à une holding qu'il contrôle","La plus-value d'apport est calculée et placée en report","La holding revend les titres presque sans plus-value","Si la vente a lieu dans les 3 ans, la holding réinvestit au moins 70 % dans les 2 ans"],w:"Apport, report, cession, réinvestissement. Trois ans pour vendre, deux ans pour réinvestir, soixante-dix pour cent au minimum."},
{i:"p148_18",u:148,t:"num",d:.5,q:"La holding de Thomas revend 18 mois après l'apport les titres reçus pour 3 000 000 €. Quel montant minimal doit-elle réinvestir pour garder le report, en euros ?",a:2100000,tol:1,un:" €",h:"Vente dans les 3 ans",w:"70 % × 3 000 000 = 2 100 000 €, dans les 2 ans, dans une activité économique éligible. Avant le 21 février 2026, le seuil était de 60 %."},
{i:"p148_19",u:148,t:"story",d:.5,q:"Que réponds-tu à Thomas ?",sc:[{who:"Thomas",txt:"Avec l'argent de la vente logé dans ma holding, je m'achète une maison au bord du lac d'Annecy. Pas d'impôt, c'est génial."}],o:["Non : l'argent de la holding sert à réinvestir, pas à financer un bien personnel","Oui, la holding peut acheter librement une résidence pour son dirigeant","Oui, à condition que Thomas loue ensuite la maison à sa propre holding pour un euro symbolique par an","Oui, si la maison est achetée plus de trois ans après la vente des titres"],a:0,w:"On ne peut pas vider la holding pour ses besoins personnels : ce serait un abus de biens sociaux ou une distribution taxée. La holding sert surtout à réinvestir."},
{i:"p148_20",u:148,t:"fill",d:.4,q:"Lors d'un apport de titres à une holding contrôlée, l'impôt sur la plus-value fait l'objet d'un ___ d'imposition.",o:["report","sursis","abattement","crédit"],a:0,w:"Report : l'impôt est calculé au jour de l'apport, et payé si un événement met fin au report."},
{i:"p148_21",u:148,t:"multi",d:.5,q:"Quels sont les avantages d'une holding de rachat par rapport à un achat en direct ?",o:["Une capacité d'endettement plus forte","Des dividendes remontés quasiment sans impôt grâce au mère-fille","Une plus grande capacité d'acquisition","La suppression définitive de toute imposition future"],a:[0,1,2],w:"Endettement, remontée de dividendes, capacité d'acquisition. Rien n'est supprimé définitivement : tout ce qui sortira de la holding vers la personne sera taxé."},
{i:"p148_22",u:148,t:"story",d:.55,q:"Quelle est la première question avant tout montage ?",ctx:"Premier rendez-vous avec Thomas, qui veut céder son entreprise ou la transmettre à Léa.",sc:[{who:"Thomas",txt:"On attaque directement le Dutreil et la holding ?"},{who:"Toi",me:true,txt:"Pas encore."}],o:["Qui détient quoi, sous quel régime matrimonial, avec quel accord du conjoint","Quel est le montant exact de l'IFI payé par Thomas l'an dernier","Quel sera le prix de vente final négocié avec les repreneurs","Léa est-elle vraiment prête à s'engager six ans, avant même de connaître le prix envisagé ?"],a:0,w:"En entretien : qui a quoi, quel régime matrimonial. En communauté, céder une entreprise commune exige l'accord du conjoint."},
{i:"p148_23",u:148,t:"tf",d:.45,q:"La réduction de 50 % des droits du pacte Dutreil joue aussi pour une transmission par succession.",a:false,w:"Elle ne concerne que les donations en pleine propriété consenties par un donateur de moins de 70 ans. En succession, on a les 75 %, sans la réduction de moitié."},
{i:"p148_24",u:148,t:"sort",d:.5,q:"Classe chaque chiffre de ce module.",bins:["Pacte Dutreil","Holding"],it:[["75 % d'exonération de la base",0],["5 % de quote-part imposable",1],["6 ans d'engagement individuel",0],["70 % de réinvestissement",1],["Moins de 70 ans pour la réduction de moitié",0],["95 % de détention pour l'intégration",1]],w:"Deux, six, huit, soixante-quinze pour le Dutreil. Cinq, un, soixante-dix, trois et deux pour la holding."},
{i:"p148_25",u:148,t:"story",d:.55,q:"Le pacte peut-il encore s'appliquer ?",ctx:"Léa a reçu les titres sous pacte Dutreil il y a quatre ans. Une belle offre de rachat arrive, et elle veut vendre toute la société maintenant.",sc:[{who:"Léa",txt:"Quatre ans, c'est ce que disaient les notes de mon père."}],o:["Non : il faut conserver 6 ans ; vendre maintenant remet en cause l'exonération","Oui : quatre ans d'engagement individuel suffisent pour garder les 75 %","Oui, si elle réinvestit au moins 70 % du prix de vente dans une autre entreprise","Oui, à condition de payer une amende de 50 % de l'avantage obtenu"],a:0,w:"Pour une transmission depuis le 21 février 2026, l'engagement individuel est de 6 ans. Vendre avant fait perdre l'exonération : le rappel des droits est dû."},
{i:"p148_26",u:148,t:"tiles",d:.35,q:"Reconstitue la formule du Dutreil 2026.",a:["Deux","ans","ensemble","six","ans","seul","soixante-quinze","pour","cent"],dd:["quatre","cinquante","toujours"],w:"2 + 6 = 8 ans, et 75 % d'exonération sur la valeur."},
{i:"p148_27",u:148,t:"mcq",d:.5,q:"Quelle condition de détention pour le régime mère-fille ?",o:["Au moins 5 % du capital, conservés 2 ans","Au moins 95 % du capital, sans durée","Au moins 50 % du capital, conservés 8 ans","Au moins 25 % du capital, conservés 5 ans"],a:0,w:"5 % et 2 ans pour le mère-fille. L'intégration fiscale demande 95 %."},
{i:"p148_28",u:148,t:"multi",d:.55,q:"Parmi ces thèmes, lesquels le professeur a-t-il annoncés pour l'évaluation ?",o:["Le régime matrimonial","L'ordre des héritiers","Le pacte Dutreil","La rémunération des notaires"],a:[0,1,2],w:"Régime, ordre, Dutreil, démembrement, holding, fiscalité. Les six piliers à maîtriser."},
{i:"p148_29",u:148,t:"story",d:.5,q:"Quel est le plus gros gain de Léa ?",ctx:"Comparaison pour une société de 500 000 € donnée par Thomas, 64 ans, à Léa : sans rien, avec Dutreil, avec Dutreil et réduction pour âge.",sc:[{who:"Léa",txt:"Au final, le Dutreil me fait économiser combien ?"}],o:["Environ 76 600 € : de 78 194 € à 1 597 €","Environ 58 600 € : 75 % des 78 194 € de droits","Environ 39 100 € : la moitié des droits seulement","Environ 3 200 € : la différence porte sur l'abattement"],a:0,w:"78 194 - 1 597 = 76 597 €. C'est l'illustration la plus parlante du module : deux engagements signés à temps valent presque 77 000 €."},
{i:"p148_30",u:148,t:"tf",d:.5,q:"Si la holding revend les titres apportés plus de 3 ans après l'apport, elle n'a pas d'obligation de réinvestissement pour garder le report.",a:true,w:"Au-delà de 3 ans, le produit peut être utilisé librement au sein de la holding, qui reste soumise aux règles des sociétés."},
{i:"p148_31",u:148,t:"fill",d:.5,q:"Pour être éligible au Dutreil, une holding doit être ___.",o:["animatrice","patrimoniale","cotée","étrangère"],a:0,w:"Animatrice : elle pilote réellement la politique de ses filiales. Une holding purement passive n'ouvre pas droit au Dutreil sur ses titres."},
{i:"p148_32",u:148,t:"story",d:.55,q:"Que conseilles-tu en priorité à Thomas, 64 ans ?",ctx:"Thomas veut transmettre sa société à Léa, qui la dirigera. Il hésite à attendre ses 72 ans pour « profiter encore un peu ».",sc:[{who:"Thomas",txt:"Si j'attends 72 ans pour donner, je perds quoi exactement ?"}],o:["La réduction de 50 % des droits, réservée aux donateurs de moins de 70 ans","Le pacte Dutreil, interdit aux donateurs de plus de 70 ans","L'abattement de 100 000 €, supprimé après 70 ans","Rien : les règles de donation ne dépendent jamais de l'âge"],a:0,w:"Le Dutreil reste possible après 70 ans, mais la réduction de 50 % disparaît. Donner avant 70 ans, en pleine propriété, divise encore les droits par deux."}
