/*UNIT*/
{id:293,c:"RUBIK",n:"Module 1",t:"Le cube en main : centres, arêtes, coins et couleurs",col:"--orange",ic:"🧩",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Nommer les <b>trois sortes de pièces</b> : centres, arêtes, coins.</li>
<li>Dire quelles couleurs sont <b>opposées</b> et comment elles sont placées.</li>
<li>Comprendre pourquoi on résout <b>couche par couche</b>, jamais face par face.</li>
<li>Tenir ton cube dans la <b>bonne position de départ</b>.</li></ul>
<h3>Le cube du grenier</h3>
<div class="gstory">Samedi après-midi, médiathèque de Tourcoing. Ton oncle <b>Thierry</b> pose sur la table un cube jauni de 1981 : « Quarante-cinq ans que je le tourne. Une face, oui. Jamais deux. » <b>Inès Morel</b>, qui anime le club cube du samedi, sourit : « Normal. Tu fais une face, et tu casses tout le reste en voulant faire la deuxième. » À côté, <b>Sacha</b>, 13 ans, résout le sien en 14 secondes sans lever les yeux. Inès te tend un cube neuf : « Garde-le en main pendant tout le cours. On apprend avec les doigts, pas avec les yeux. »</div>
<p>Règle du cours : <b>chaque partie se termine par « Cube en main »</b>. Tu fais les gestes au moment où tu lis, pas après.</p>
<h3>Trois sortes de pièces</h3>
<table><tr><th>Pièce</th><th>Nombre</th><th>Couleurs</th><th>Bouge ?</th></tr>
<tr><td><b>Centre</b></td><td>6</td><td>1</td><td>Il tourne sur lui-même mais ne change jamais de place</td></tr>
<tr><td><b>Arête</b></td><td>12</td><td>2</td><td>Elle voyage entre les places d'arête</td></tr>
<tr><td><b>Coin</b></td><td>8</td><td>3</td><td>Il voyage entre les places de coin</td></tr></table>
<p>Au total : <b>26 pièces visibles</b> et <b>54 autocollants</b> (6 faces de 9 cases).</p>
<div class="gmnemo"><b>« 6, 12, 8 »</b> comme un code de cadenas. Et une image : le <b>centre est le capitaine</b> de sa face. C'est lui qui dit de quelle couleur la face doit devenir.</div>
<h3>Cube en main : trouve les pièces</h3>
<ol><li>Pose ton doigt sur un <b>centre</b>, puis tourne la face. Le centre reste au milieu.</li>
<li>Touche une <b>arête</b> : compte ses deux couleurs.</li>
<li>Touche un <b>coin</b> : compte ses trois couleurs.</li>
<li>Cherche une arête <b>rouge et orange</b>. Tu n'en trouveras jamais : ces deux couleurs sont opposées.</li></ol>
<h3>Les couleurs opposées</h3>
<ul><li><b>Blanc</b> en face du <b>jaune</b>.</li>
<li><b>Rouge</b> en face de l'<b>orange</b>.</li>
<li><b>Bleu</b> en face du <b>vert</b>.</li>
<li>Sur un cube standard, avec le <b>blanc en haut</b> et le <b>vert devant</b>, le <b>rouge est à droite</b>.</li></ul>
<svg class='gsvg' viewBox='0 0 200 226' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><polygon points='100.0,31.8 159.1,65.9 100.0,100.0 100.0,168.2 40.9,134.1 40.9,65.9' fill='#141432'/><polygon points='100.0,35.3 116.8,45.0 100.0,54.7 83.2,45.0' fill='#FFD500'/><polygon points='119.1,46.3 135.8,56.0 119.1,65.7 102.3,56.0' fill='#FFD500'/><polygon points='138.1,57.3 154.9,67.0 138.1,76.7 121.3,67.0' fill='#FFD500'/><polygon points='80.9,46.3 97.7,56.0 80.9,65.7 64.2,56.0' fill='#FFD500'/><polygon points='100.0,57.3 116.8,67.0 100.0,76.7 83.2,67.0' fill='#FFD500'/><polygon points='119.1,68.3 135.8,78.0 119.1,87.7 102.3,78.0' fill='#FFD500'/><polygon points='61.9,57.3 78.7,67.0 61.9,76.7 45.1,67.0' fill='#FFD500'/><polygon points='80.9,68.3 97.7,78.0 80.9,87.7 64.2,78.0' fill='#FFD500'/><polygon points='100.0,79.3 116.8,89.0 100.0,98.7 83.2,89.0' fill='#FFD500'/><polygon points='44.0,69.0 60.8,78.7 60.8,98.0 44.0,88.3' fill='#009E60'/><polygon points='63.0,80.0 79.8,89.7 79.8,109.0 63.0,99.3' fill='#009E60'/><polygon points='82.1,91.0 98.9,100.7 98.9,120.0 82.1,110.3' fill='#009E60'/><polygon points='44.0,91.0 60.8,100.7 60.8,120.0 44.0,110.3' fill='#009E60'/><polygon points='63.0,102.0 79.8,111.7 79.8,131.0 63.0,121.3' fill='#009E60'/><polygon points='82.1,113.0 98.9,122.7 98.9,142.0 82.1,132.3' fill='#009E60'/><polygon points='44.0,113.0 60.8,122.7 60.8,142.0 44.0,132.3' fill='#009E60'/><polygon points='63.0,124.0 79.8,133.7 79.8,153.0 63.0,143.3' fill='#009E60'/><polygon points='82.1,135.0 98.9,144.7 98.9,164.0 82.1,154.3' fill='#009E60'/><polygon points='101.1,100.7 117.9,91.0 117.9,110.3 101.1,120.0' fill='#FF5800'/><polygon points='120.2,89.7 137.0,80.0 137.0,99.3 120.2,109.0' fill='#FF5800'/><polygon points='139.2,78.7 156.0,69.0 156.0,88.3 139.2,98.0' fill='#FF5800'/><polygon points='101.1,122.7 117.9,113.0 117.9,132.3 101.1,142.0' fill='#FF5800'/><polygon points='120.2,111.7 137.0,102.0 137.0,121.3 120.2,131.0' fill='#FF5800'/><polygon points='139.2,100.7 156.0,91.0 156.0,110.3 139.2,120.0' fill='#FF5800'/><polygon points='101.1,144.7 117.9,135.0 117.9,154.3 101.1,164.0' fill='#FF5800'/><polygon points='120.2,133.7 137.0,124.0 137.0,143.3 120.2,153.0' fill='#FF5800'/><polygon points='139.2,122.7 156.0,113.0 156.0,132.3 139.2,142.0' fill='#FF5800'/><text x='100' y='208' font-size='10' fill='var(--txt)' text-anchor='middle' font-weight='700'>Cube résolu : jaune en haut,</text><text x='100' y='220' font-size='10' fill='var(--txt)' text-anchor='middle' font-weight='700'>vert devant, orange à droite</text></svg>
<div class="gmnemo">Trois couples à retenir : <b>« le jour et le soleil »</b> (blanc et jaune), <b>« le feu et la braise »</b> (rouge et orange), <b>« le ciel et l'herbe »</b> (bleu et vert).</div>
<h3>Pourquoi pas face par face ?</h3>
<ul><li>Une face blanche peut être une <b>fausse face</b> : ses <b>bords</b> ne correspondent pas aux centres voisins.</li>
<li>On résout donc des <b>pièces</b>, pas des couleurs : chaque pièce doit être à sa place <b>et</b> dans le bon sens.</li>
<li>La méthode débutant monte <b>couche par couche</b> : le bas, le milieu, puis le haut.</li></ul>
<div class="gtrap">L'idée reçue de Thierry, « je fais une face, puis la suivante », est le piège numéro un. Une face finie au mauvais endroit oblige à tout défaire. Ce qui compte, c'est la <b>première couche</b> : la face blanche <b>et</b> la rangée du dessous de chaque côté, alignées avec les centres.</div>
<h3>Chiffres et histoire</h3>
<ul><li>Inventé en <b>1974</b> par <b>Ernő Rubik</b>, professeur d'architecture à Budapest, sous le nom de « cube magique ».</li>
<li>Vendu dans le monde entier à partir de <b>1980</b>.</li>
<li>Il a <b>43 252 003 274 489 856 000</b> positions possibles, soit environ 43 milliards de milliards.</li>
<li>Toute position se résout en <b>20 mouvements</b> au maximum, c'est le « nombre de Dieu », démontré en 2010.</li></ul>
<h3>Cube en main : la position de départ</h3>
<ol><li>Tiens le cube à deux mains, pouces devant, à hauteur de poitrine.</li>
<li>Mets le centre <b>jaune en haut</b> et le centre <b>vert face à toi</b>.</li>
<li>Vérifie : l'<b>orange</b> doit être à droite, le <b>rouge</b> à gauche.</li></ol>
<h3>Ce que tu dois retenir</h3>
<ul><li>6 centres fixes, 12 arêtes à 2 couleurs, 8 coins à 3 couleurs.</li>
<li>Blanc et jaune, rouge et orange, bleu et vert sont opposés.</li>
<li>On résout des pièces, couche par couche.</li></ul>`},
/*EXOS*/
{i:"rb293_01",u:293,t:"mcq",d:.15,nw:"Les pièces du cube",q:"Combien de couleurs porte une arête ?",o:["Deux","Une","Trois","Quatre"],a:0,w:"Une arête a deux couleurs, un coin en a trois, un centre une seule. Code du cadenas : 6, 12, 8."},
{i:"rb293_02",u:293,t:"match",d:.15,q:"Associe chaque pièce à son nombre.",p:[["Centres","6"],["Arêtes","12"],["Coins","8"],["Autocollants","54"]],w:"6 centres, 12 arêtes, 8 coins : le code du cadenas. Et 6 faces de 9 cases font 54 autocollants."},
{i:"rb293_03",u:293,t:"story",d:.2,q:"Que réponds-tu à Thierry ?",sc:[{who:"Thierry",txt:"J'ai fait la face blanche, mais les côtés sont tous mélangés. C'est quand même un bon début, non ?"}],o:["Non, les côtés doivent suivre les centres","Oui, il reste juste à faire la face jaune","Oui, une face suffit pour finir toutes les autres","Non, il faut toujours commencer par le rouge"],a:0,w:"Une face sans ses bords alignés sur les centres est une fausse face. On résout des pièces, couche par couche."},
{i:"rb293_04",u:293,t:"tf",d:.2,q:"Cube en main : tourne la face du dessus. Le centre jaune change de place.",a:false,w:"Le centre tourne sur lui-même mais reste au milieu. C'est le capitaine fixe de sa face."},
{i:"rb293_05",u:293,t:"fill",d:.2,q:"Le blanc est toujours opposé au ___.",o:["jaune","rouge","vert","bleu"],a:0,w:"Le jour et le soleil : blanc et jaune ne se touchent jamais."},
{i:"rb293_06",u:293,t:"sort",d:.25,q:"Cube en main : classe chaque pièce selon son nombre de couleurs.",bins:["1 couleur","2 couleurs","3 couleurs"],it:[["Le centre vert",0],["La pièce blanc et rouge",1],["La pièce blanc, vert et orange",2],["La pièce jaune et bleu",1],["Le centre jaune",0]],w:"Un centre a une couleur, une arête deux, un coin trois. Compte-les avec ton doigt."},
{i:"rb293_07",u:293,t:"multi",d:.25,q:"Quels couples de couleurs sont opposés sur un cube standard ?",o:["Blanc et jaune","Rouge et orange","Bleu et vert","Rouge et vert","Blanc et bleu"],a:[0,1,2],w:"Le jour et le soleil, le feu et la braise, le ciel et l'herbe."},
{i:"rb293_08",u:293,t:"story",d:.25,q:"Que répond Inès à Sacha ?",sc:[{who:"Sacha",txt:"Je cherche une arête rouge et orange depuis cinq minutes, je ne la trouve pas !"}],o:["Elle n'existe pas : couleurs opposées","Elle est sûrement cachée derrière le cube","Elle a été remplacée par une arête blanche","Il faut démonter le cube pour la trouver"],a:0,w:"Deux couleurs opposées ne sont jamais sur la même pièce. Pas d'arête rouge et orange, ni blanc et jaune."},
{i:"rb293_09",u:293,t:"slider",d:.3,q:"Combien de pièces visibles compte un cube 3x3 ?",min:9,max:54,step:1,a:26,tol:0,pre:"",un:" pièces",w:"6 + 12 + 8 = 26 pièces. Le 27e « cube » du milieu est le mécanisme."},
{i:"rb293_10",u:293,t:"mcq",d:.3,nw:"Les couleurs",q:"Blanc en haut, vert devant : quelle couleur est à droite ?",o:["Rouge","Orange","Bleu","Jaune"],a:0,w:"Schéma standard : blanc en haut, vert devant, rouge à droite. Retourne le cube jaune en haut : l'orange passe à droite."},
{i:"rb293_11",u:293,t:"tf",d:.3,q:"Cube en main : jaune en haut et vert devant, l'orange est à ta droite.",a:true,w:"C'est la position de départ de tout le cours : jaune en haut, vert face à toi, orange à droite, rouge à gauche."},
{i:"rb293_12",u:293,t:"tiles",d:.3,q:"Reconstitue la règle d'or du débutant.",a:["On","résout","couche","par","couche"],dd:["face","couleur"],w:"Le bas, le milieu, le haut. Jamais face par face."},
{i:"rb293_13",u:293,t:"story",d:.35,q:"Que réponds-tu à Thierry ?",ctx:"Thierry te montre un coin blanc, rouge et vert.",sc:[{who:"Thierry",txt:"Ce coin, il va forcément sur la face blanche ?"}],o:["Oui, entre les centres blanc, rouge, vert","Non, il va sur la face jaune, opposée","Non, un coin peut aller n'importe où sur le cube","Oui, mais seulement au centre de la face"],a:0,w:"Les centres sont fixes : un coin blanc, rouge et vert n'a qu'une place, celle où se croisent ces trois centres."},
{i:"rb293_14",u:293,t:"num",d:.35,q:"Une face compte 9 cases. Combien d'autocollants sur le cube entier ?",a:54,tol:0,un:" autocollants",h:"6 faces x 9",w:"6 x 9 = 54 autocollants : 6 de centres, 24 d'arêtes, 24 de coins."},
{i:"rb293_15",u:293,t:"match",d:.35,q:"Associe chaque couple à son image mémo.",p:[["Blanc et jaune","Le jour et le soleil"],["Rouge et orange","Le feu et la braise"],["Bleu et vert","Le ciel et l'herbe"],["Centre","Le capitaine de la face"]],w:"Trois images pour les couleurs opposées, une pour le centre fixe."},
{i:"rb293_16",u:293,t:"fill",d:.35,q:"La pièce qui dit de quelle couleur sera sa face est le ___.",o:["centre","coin","bord","dos"],a:0,w:"Le centre est le capitaine : il ne bouge jamais, la face prend sa couleur."},
{i:"rb293_17",u:293,t:"tf",d:.4,q:"Une face entièrement blanche signifie toujours que la première couche est finie.",a:false,w:"Piège de Thierry : la face peut être blanche avec des bords mal alignés. Fausse face. Une fausse face oblige à tout défaire."},
{i:"rb293_18",u:293,t:"multi",d:.4,q:"Cube en main : que doit vérifier une première couche réussie ?",o:["La face blanche est complète","Chaque côté a sa rangée du bas alignée","Les bords suivent la couleur des centres","La face jaune est déjà faite"],a:[0,1,2],w:"Face blanche et rangée du bas de chaque côté, en accord avec les centres."},
{i:"rb293_19",u:293,t:"mcq",d:.4,nw:"Histoire et chiffres",q:"Qui a inventé le cube, et quand ?",o:["Ernő Rubik, en 1974","Ernő Rubik, en 1999","Un ingénieur japonais, en 1980","Un mathématicien français, en 1962"],a:0,w:"Professeur d'architecture à Budapest, en 1974. Vendu dans le monde dès 1980. Depuis 1974, des centaines de millions de cubes vendus."},
{i:"rb293_20",u:293,t:"slider",d:.4,q:"En quelle année le cube est-il vendu dans le monde entier ?",min:1960,max:2000,step:1,a:1980,tol:0,pre:"",un:"",w:"Inventé en 1974, diffusé mondialement en 1980. Le cube de Thierry date de la grande vague de 1981."},
{i:"rb293_21",u:293,t:"story",d:.45,q:"Que répond Inès ?",sc:[{who:"Thierry",txt:"43 milliards de milliards de positions ! Il faut des millions de coups pour en sortir."}],o:["Non : 20 mouvements suffisent toujours, au plus","Oui, au moins un million de mouvements","Oui, et personne ne l'a jamais démontré","Non, 3 mouvements suffisent toujours"],a:0,w:"Le nombre de Dieu est 20, démontré en 2010. Un débutant en fait environ 100 à 150 : c'est normal."},
{i:"rb293_22",u:293,t:"tf",d:.45,q:"Toute position du cube peut se résoudre en 20 mouvements au maximum.",a:true,w:"C'est le nombre de Dieu, démontré en 2010 par calcul sur ordinateur. Malgré 43 milliards de milliards de positions."},
{i:"rb293_23",u:293,t:"order",d:.45,q:"Remets dans l'ordre les couches de la méthode débutant.",it:["La couche du bas (blanche)","La couche du milieu","La couche du haut (jaune)"],w:"Le bas, le milieu, le haut. Chaque couche finie reste intacte. Inventé en 1974, résolu couche par couche par les débutants depuis toujours."},
{i:"rb293_24",u:293,t:"story",d:.5,q:"Cube en main : que dit Inès ?",ctx:"Tu tiens le cube avec le blanc en haut et le bleu devant.",sc:[{who:"Inès Morel",txt:"Remets-toi en position de départ du cours."}],o:["Jaune en haut, vert devant toi","Blanc en haut, rouge devant","Jaune en haut, bleu devant","Vert en haut, jaune devant"],a:0,w:"Position de départ : jaune en haut, vert face à toi, orange à droite."},
{i:"rb293_25",u:293,t:"sort",d:.5,q:"Cette pièce existe-t-elle ?",bins:["Existe","N'existe pas"],it:[["Arête blanc et vert",0],["Arête blanc et jaune",1],["Coin jaune, bleu et rouge",0],["Coin rouge, orange et vert",1],["Arête bleu et orange",0]],w:"Jamais deux couleurs opposées sur une même pièce."},
{i:"rb293_26",u:293,t:"num",d:.5,q:"Un coin porte 3 autocollants. Combien d'autocollants de coin sur tout le cube ?",a:24,tol:0,un:" autocollants",h:"8 coins x 3",w:"8 x 3 = 24. Les 12 arêtes en portent aussi 24, les centres 6 : total 54."},
{i:"rb293_27",u:293,t:"fill",d:.55,q:"Le nombre maximal de mouvements pour résoudre n'importe quelle position s'appelle le nombre de ___.",o:["Dieu","Rubik","base","Budapest"],a:0,w:"Le nombre de Dieu vaut 20 : démontré en 2010. Et cela malgré 43 milliards de milliards de positions."},
{i:"rb293_28",u:293,t:"tiles",d:.55,q:"Reconstitue la consigne d'Inès.",a:["On","apprend","avec","les","doigts"],dd:["yeux","livres"],w:"Le cube se garde en main pendant toute la leçon : chaque geste se fait au moment où tu le lis."},
{i:"rb293_29",u:293,t:"tf",d:.55,q:"Une pièce bien placée doit aussi être dans le bon sens.",a:true,w:"Une arête peut être à sa place mais retournée : on résout la place et l'orientation."},
{i:"rb293_30",u:293,t:"mcq",d:.6,q:"Pourquoi le centre est-il si utile au débutant ?",o:["Il fixe la couleur finale de sa face","Il se déplace pour guider les arêtes","Il se transforme en coin à la toute fin","Il ne sert qu'à décorer le cube"],a:0,w:"Les centres ne bougent pas : ce sont les repères de toute la résolution."},
{i:"rb293_31",u:293,t:"multi",d:.6,q:"Cube en main : avec jaune en haut et vert devant, que vois-tu ?",o:["Le rouge à gauche","L'orange à droite","Le bleu derrière","Le blanc devant toi"],a:[0,1,2],w:"Le blanc est en dessous, caché. Le bleu est derrière, opposé au vert."},
{i:"rb293_32",u:293,t:"story",d:.65,q:"Synthèse : Inès te fait réciter.",sc:[{who:"Inès Morel",txt:"Trois phrases pour décrire le cube."}],o:["Centres fixes, couleurs opposées, couche par couche","Une face après l'autre, en commençant par le rouge","Les centres bougent, il faut les suivre partout","On tourne au hasard jusqu'à tomber sur la solution"],a:0,w:"Les centres sont des repères, les couleurs opposées ne se touchent jamais, et on monte couche par couche."}
