/*UNIT*/
{id:296,c:"RUBIK",n:"Module 4",t:"Étape 2, les coins blancs : le sexy move 1, 3 ou 5 fois",col:"--orange",ic:"🔺",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Trouver la <b>bonne place</b> d'un coin blanc grâce aux centres.</li>
<li>L'amener au-dessus de sa place, devant à droite.</li>
<li>L'insérer avec <b>R U R' U'</b> répété 1, 3 ou 5 fois.</li>
<li>Sortir un coin <b>coincé</b> en bas au mauvais endroit.</li></ul>
<h3>La machine à laver</h3>
<div class="gstory">Thierry a sa croix. Il tient un coin blanc, rouge et vert, et le tourne dans tous les sens. Sacha lui prend le cube : « Mets le coin en haut, juste au-dessus de sa place, devant à droite. Et maintenant, lance la machine à laver. » R U R' U'. R U R' U'. R U R' U'. Le coin descend, se tourne, et se pose tout seul, blanc en dessous. « Tu ne réfléchis pas. Tu tournes jusqu'à ce que ce soit propre. »</div>
<h3>La place d'un coin</h3>
<ul><li>Un coin <b>blanc, rouge et vert</b> va entre les centres <b>rouge</b> et <b>vert</b>, en bas.</li>
<li>Garde le <b>jaune en haut</b>, la croix blanche en bas.</li>
<li>Cherche les coins blancs dans la <b>couche du haut</b>.</li>
<li>Tourne <b>U</b> pour amener le coin <b>juste au-dessus</b> de sa place.</li></ul>
<div class="gmnemo">Le coin se range comme une voiture : il <b>se gare au-dessus de sa place</b>, devant à droite, puis la machine à laver le fait descendre. Ses deux couleurs de côté doivent <b>encadrer</b> la place, comme deux poteaux.</div>
<h3>Le geste : R U R' U'</h3>
<ul><li>Tourne le cube (avec <b>y</b>) pour que la place soit <b>devant à droite, en bas</b>.</li>
<li>Répète <b>R U R' U'</b> jusqu'à ce que le coin soit en place, blanc en dessous.</li>
<li>Ça prend <b>1, 3 ou 5 fois</b>, selon le sens du blanc.</li></ul>
<table><tr><th>Le blanc du coin regarde...</th><th>Nombre de R U R' U'</th></tr>
<tr><td>À <b>droite</b></td><td>1 fois</td></tr>
<tr><td>Vers le <b>haut</b></td><td>3 fois</td></tr>
<tr><td><b>Devant</b> toi</td><td>5 fois</td></tr></table>
<svg class='gsvg' viewBox='0 0 200 226' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><polygon points='100.0,31.8 159.1,65.9 100.0,100.0 100.0,168.2 40.9,134.1 40.9,65.9' fill='#141432'/><polygon points='100.0,35.3 116.8,45.0 100.0,54.7 83.2,45.0' fill='#4A4A78'/><polygon points='119.1,46.3 135.8,56.0 119.1,65.7 102.3,56.0' fill='#4A4A78'/><polygon points='138.1,57.3 154.9,67.0 138.1,76.7 121.3,67.0' fill='#4A4A78'/><polygon points='80.9,46.3 97.7,56.0 80.9,65.7 64.2,56.0' fill='#4A4A78'/><polygon points='100.0,57.3 116.8,67.0 100.0,76.7 83.2,67.0' fill='#FFD500'/><polygon points='119.1,68.3 135.8,78.0 119.1,87.7 102.3,78.0' fill='#4A4A78'/><polygon points='61.9,57.3 78.7,67.0 61.9,76.7 45.1,67.0' fill='#4A4A78'/><polygon points='80.9,68.3 97.7,78.0 80.9,87.7 64.2,78.0' fill='#4A4A78'/><polygon points='100.0,79.3 116.8,89.0 100.0,98.7 83.2,89.0' fill='#FF5800'/><polygon points='44.0,69.0 60.8,78.7 60.8,98.0 44.0,88.3' fill='#4A4A78'/><polygon points='63.0,80.0 79.8,89.7 79.8,109.0 63.0,99.3' fill='#4A4A78'/><polygon points='82.1,91.0 98.9,100.7 98.9,120.0 82.1,110.3' fill='#009E60'/><polygon points='44.0,91.0 60.8,100.7 60.8,120.0 44.0,110.3' fill='#4A4A78'/><polygon points='63.0,102.0 79.8,111.7 79.8,131.0 63.0,121.3' fill='#009E60'/><polygon points='82.1,113.0 98.9,122.7 98.9,142.0 82.1,132.3' fill='#4A4A78'/><polygon points='44.0,113.0 60.8,122.7 60.8,142.0 44.0,132.3' fill='#009E60'/><polygon points='63.0,124.0 79.8,133.7 79.8,153.0 63.0,143.3' fill='#009E60'/><polygon points='82.1,135.0 98.9,144.7 98.9,164.0 82.1,154.3' fill='#4A4A78'/><polygon points='101.1,100.7 117.9,91.0 117.9,110.3 101.1,120.0' fill='#FFFFFF'/><polygon points='120.2,89.7 137.0,80.0 137.0,99.3 120.2,109.0' fill='#4A4A78'/><polygon points='139.2,78.7 156.0,69.0 156.0,88.3 139.2,98.0' fill='#4A4A78'/><polygon points='101.1,122.7 117.9,113.0 117.9,132.3 101.1,142.0' fill='#4A4A78'/><polygon points='120.2,111.7 137.0,102.0 137.0,121.3 120.2,131.0' fill='#FF5800'/><polygon points='139.2,100.7 156.0,91.0 156.0,110.3 139.2,120.0' fill='#4A4A78'/><polygon points='101.1,144.7 117.9,135.0 117.9,154.3 101.1,164.0' fill='#4A4A78'/><polygon points='120.2,133.7 137.0,124.0 137.0,143.3 120.2,153.0' fill='#FF5800'/><polygon points='139.2,122.7 156.0,113.0 156.0,132.3 139.2,142.0' fill='#FF5800'/><text x='100' y='208' font-size='10' fill='var(--txt)' text-anchor='middle' font-weight='700'>Coin garé au-dessus de sa place,</text><text x='100' y='220' font-size='10' fill='var(--txt)' text-anchor='middle' font-weight='700'>blanc à droite : 1 sexy move</text></svg>
<div class="gmnemo"><b>« Droite 1, haut 3, devant 5 »</b>. Ou rien à retenir du tout : tu répètes jusqu'à ce que ce soit propre, la croix ne bouge jamais à la fin.</div>
<h3>Cube en main : quatre coins</h3>
<ol><li>Croix blanche en bas, jaune en haut.</li>
<li>Trouve un coin blanc en haut. Lis ses deux autres couleurs.</li>
<li>Tourne U jusqu'à ce qu'il soit au-dessus de sa place.</li>
<li>Tourne le cube (y) pour avoir cette place devant à droite.</li>
<li>R U R' U' jusqu'à ce qu'il soit posé. Recommence pour les trois autres.</li></ol>
<h3>Le coin coincé en bas</h3>
<ul><li>Parfois un coin blanc est <b>en bas</b>, mais à la mauvaise place ou à l'envers.</li>
<li>Mets-le <b>devant à droite</b>, et fais <b>R U R' U' une fois</b> : il remonte en haut.</li>
<li>Traite-le ensuite comme un coin normal.</li></ul>
<div class="gtrap">Erreur fréquente : tourner <b>U</b> pendant la répétition pour « aider ». Le coin quitte sa place de parking et tout se décale. Pendant la machine à laver, tu ne fais <b>que</b> R U R' U', rien d'autre. Et si la croix semble cassée au milieu de la série, <b>c'est normal</b> : elle se reforme à la fin.</div>
<h3>Le résultat</h3>
<ul><li>La <b>face blanche</b> est complète.</li>
<li>Sur chaque côté, la <b>rangée du bas</b> est d'une seule couleur, celle du centre.</li>
<li>Tu as fini la <b>première couche</b>. Thierry n'y était jamais arrivé.</li></ul>
<h3>Ce que tu dois retenir</h3>
<ul><li>Le coin se gare au-dessus de sa place, devant à droite.</li>
<li>R U R' U' jusqu'à ce que ce soit propre : 1, 3 ou 5 fois.</li>
<li>Coin coincé en bas : un R U R' U' le remonte.</li></ul>`},
/*EXOS*/
{i:"rb296_01",u:296,t:"mcq",d:.15,nw:"La place d'un coin",q:"Où va un coin blanc, rouge et vert ?",o:["En bas, entre les centres rouge et vert, sous eux","En haut, entre les centres rouge et vert","En bas, entre les centres rouge et bleu","N'importe où sur la face blanche"],a:0,w:"Les centres sont fixes : le coin va là où se croisent le blanc, le rouge et le vert."},
{i:"rb296_02",u:296,t:"story",d:.15,q:"Que dit Sacha à Thierry ?",sc:[{who:"Thierry",txt:"Mon coin est en haut, à l'opposé de sa place. Je lance la machine à laver ?"}],o:["Non, gare-le d'abord au-dessus de sa place","Oui, la machine trouve toujours la place","Oui, mais avec L U L' U' à la place","Non, il faut d'abord défaire la croix"],a:0,w:"Le coin se gare au-dessus de sa place avec U, puis la machine à laver le fait descendre."},
{i:"rb296_03",u:296,t:"order",d:.2,q:"Remets dans l'ordre l'insertion d'un coin.",it:["Lire les couleurs du coin","Tourner U au-dessus de sa place","Mettre la place devant à droite","R U R' U' jusqu'à ce qu'il soit posé"],w:"Lire, garer, se placer, laver. Quatre fois, un coin à chaque fois."},
{i:"rb296_04",u:296,t:"num",d:.2,nw:"Droite 1, haut 3, devant 5",q:"Le coin est garé, blanc vers le haut. Combien de R U R' U' ?",a:3,tol:0,un:" fois",h:"Droite 1, haut 3, devant 5",w:"Blanc en haut : trois fois. Vérifie-le cube en main."},
{i:"rb296_05",u:296,t:"tf",d:.2,q:"Cube en main : coin garé, blanc à droite. Un seul R U R' U' le pose.",a:true,w:"Droite 1. Le coin descend directement, blanc en dessous."},
{i:"rb296_06",u:296,t:"match",d:.25,q:"Associe le sens du blanc au nombre de répétitions.",p:[["Blanc à droite","1 fois"],["Blanc en haut","3 fois"],["Blanc devant","5 fois"],["Coin coincé en bas","1 fois pour le sortir"]],w:"Droite 1, haut 3, devant 5. Et un R U R' U' sort un coin coincé."},
{i:"rb296_07",u:296,t:"story",d:.25,q:"Que répond Inès ?",sc:[{who:"Thierry",txt:"Au milieu de la série, ma croix blanche est cassée ! J'arrête ?"}],o:["Continue, elle se reforme à la fin","Arrête et refais la croix tout de suite","Ajoute un U pour la réparer","Recommence le cube depuis le début"],a:0,w:"Pendant la machine à laver, la croix se défait puis se reforme. Ne touche à rien d'autre."},
{i:"rb296_08",u:296,t:"fill",d:.25,q:"Pour insérer un coin, on répète le ___ move.",o:["sexy","Sune","demi","Niklas"],a:0,w:"R U R' U' : le sexy move vu au module 2, ici en machine à laver."},
{i:"rb296_09",u:296,t:"multi",d:.3,q:"Cube en main : où doit être la place du coin avant la répétition ?",o:["Devant","À droite","En bas","Derrière à gauche"],a:[0,1,2],w:"Devant à droite en bas : c'est la case que R U R' U' sait remplir."},
{i:"rb296_10",u:296,t:"tf",d:.3,q:"Pendant les répétitions de R U R' U', on peut tourner U pour aider le coin.",a:false,w:"Erreur fréquente : le coin quitte sa place de parking. Uniquement R U R' U'."},
{i:"rb296_11",u:296,t:"sort",d:.3,q:"Combien de R U R' U' ? Classe chaque cas.",bins:["1 fois","3 fois","5 fois"],it:[["Coin garé, blanc à droite",0],["Coin garé, blanc vers le haut",1],["Coin garé, blanc devant toi",2],["Coin coincé en bas, à sortir",0]],w:"Droite 1, haut 3, devant 5. Sortir un coin coincé : 1 fois."},
{i:"rb296_12",u:296,t:"mcq",d:.35,q:"Quelle rotation utilises-tu pour mettre la place devant à droite ?",o:["y","x","z","M"],a:0,w:"y tourne tout le cube comme U : le jaune reste en haut, la croix en bas."},
{i:"rb296_13",u:296,t:"story",d:.35,q:"Cube en main : que fais-tu ?",ctx:"Un coin blanc, orange et bleu est en bas devant à droite, mais les centres de devant et de droite sont vert et orange.",sc:[{who:"Sacha",txt:"Il est coincé au mauvais endroit. Tu le sors comment ?"}],o:["Un R U R' U' le remonte en haut","Je fais F2 pour l'envoyer en haut","Je tourne D jusqu'à sa place","Je démonte le coin et je le remets"],a:0,w:"Un seul sexy move remonte le coin en haut. Ensuite on le gare au-dessus de sa vraie place."},
{i:"rb296_14",u:296,t:"tiles",d:.35,q:"Reconstitue le mémo des répétitions.",a:["Droite","1,","haut","3,","devant","5"],dd:["gauche","2,"],w:"Le sens du blanc dit combien de sexy moves il faut."},
{i:"rb296_15",u:296,t:"tf",d:.4,q:"Un coin garé au mauvais endroit finira quand même à sa place avec assez de R U R' U'.",a:false,w:"La machine à laver remplit la case devant à droite avec le coin du dessus : si ce n'est pas sa place, il s'y pose quand même, au mauvais endroit."},
{i:"rb296_16",u:296,t:"num",d:.4,q:"Combien de coins blancs faut-il placer pour finir la première couche ?",a:4,tol:0,un:" coins",h:"Un par coin de la face blanche",w:"Quatre coins, un à chaque angle de la croix blanche."},
{i:"rb296_17",u:296,t:"match",d:.4,q:"Associe chaque image à son idée.",p:[["Se garer","Amener le coin au-dessus de sa place"],["Machine à laver","Répéter R U R' U'"],["Deux poteaux","Les couleurs encadrent la place"],["Propre","Le coin est posé, blanc dessous"]],w:"Les images du module : garer, laver, encadrer, propre."},
{i:"rb296_18",u:296,t:"story",d:.45,q:"Que dit Inès ?",sc:[{who:"Thierry",txt:"Je ne sais jamais si c'est 3 ou 5 fois. Je dois tout apprendre par cœur ?"}],o:["Non, répète jusqu'à ce qu'il soit bien posé","Oui, sinon le coin se pose à l'envers","Oui, et ajoute un U à chaque fois","Non, fais-le toujours exactement 3 fois"],a:0,w:"Tu ne réfléchis pas : tu tournes jusqu'à ce que ce soit propre. Le compte vient avec la pratique."},
{i:"rb296_19",u:296,t:"multi",d:.45,nw:"La première couche",q:"Après cette étape, que vois-tu ?",o:["La face blanche complète","Une rangée du bas unie sur chaque côté","Les rangées du bas suivent les centres","La couche du milieu terminée"],a:[0,1,2],w:"La première couche est finie. La couche du milieu vient au module 5."},
{i:"rb296_20",u:296,t:"fill",d:.45,q:"Le coin doit être garé juste ___ sa place.",o:["au-dessus de","en dessous de","à gauche de","en face de"],a:0,w:"Dans la couche du haut, à la verticale de sa place, devant à droite."},
{i:"rb296_21",u:296,t:"tf",d:.5,q:"Cube en main : après 6 R U R' U' sur un coin déjà posé, il revient posé.",a:true,w:"Six sexy moves ramènent tout au départ : le coin fait un tour complet et revient."},
{i:"rb296_22",u:296,t:"mcq",d:.5,q:"Le coin garé a le blanc devant toi. Combien de R U R' U' ?",o:["5","1","3","6"],a:0,w:"Devant 5. Le blanc fait le tour par le haut puis la droite avant de descendre."},
{i:"rb296_23",u:296,t:"story",d:.5,q:"Rappel du module 3 : que dit Sacha ?",sc:[{who:"Thierry",txt:"Mes coins sont posés, mais un côté n'a pas de T en bas. Bizarre."}],o:["Ta croix était fausse : une arête mal placée","Les coins ont cassé la croix, c'est normal","Il faut faire la face jaune pour réparer","Un coin est à l'envers, tourne-le à la main"],a:0,w:"Une croix sans ses quatre T est fausse : les rangées du bas ne peuvent pas être unies."},
{i:"rb296_24",u:296,t:"order",d:.55,q:"Remets dans l'ordre le traitement d'un coin coincé en bas.",it:["Le mettre devant à droite","Faire R U R' U' une fois","Il est maintenant en haut","Le garer au-dessus de sa vraie place","Répéter R U R' U' jusqu'à ce qu'il soit posé"],w:"Sortir, garer, laver. Le coin coincé redevient un coin normal."},
{i:"rb296_25",u:296,t:"slider",d:.55,q:"Combien de quarts de tour font 5 sexy moves ?",min:0,max:40,step:1,a:20,tol:0,pre:"",un:" quarts",w:"4 quarts par sexy move, 5 fois : 20 quarts de tour. C'est le cas le plus long."},
{i:"rb296_26",u:296,t:"sort",d:.6,q:"Bon réflexe ou erreur ?",bins:["Bon réflexe","Erreur"],it:[["Garer le coin avant de répéter",0],["Tourner U pendant la répétition",1],["Continuer quand la croix se casse",0],["Insérer le coin en tournant L",1]],w:"Garer, répéter R U R' U' seulement, faire confiance au geste."},
{i:"rb296_27",u:296,t:"tf",d:.6,q:"À la fin de l'étape, chaque côté a sa rangée du bas de la couleur de son centre.",a:true,w:"C'est la vraie première couche : face blanche et bords alignés sur les centres."},
{i:"rb296_28",u:296,t:"story",d:.65,q:"Cube en main : que dis-tu à Thierry ?",ctx:"Thierry a un coin blanc, vert et orange en haut, garé au-dessus de la place vert et orange.",sc:[{who:"Thierry",txt:"La place est devant moi, mais à gauche. Je fais quand même R U R' U' ?"}],o:["Non, fais y' pour l'avoir devant à droite","Oui, R U R' U' marche à gauche aussi","Oui, en tournant U entre chaque série","Non, il faut le remonter avec F2"],a:0,w:"R U R' U' ne remplit que la case devant à droite. Une rotation du cube entier place la case au bon endroit."},
{i:"rb296_29",u:296,t:"tiles",d:.65,q:"Reconstitue la consigne de Sacha.",a:["Tu","tournes","jusqu'à","ce","que","ce","soit","propre"],dd:["compte","vite"],w:"La machine à laver : on répète sans réfléchir jusqu'à ce que le coin soit posé."},
{i:"rb296_30",u:296,t:"mcq",d:.7,q:"Pourquoi le coin doit-il être garé avant de lancer la machine à laver ?",o:["Le geste remplit seulement la case dessous","Le geste ne marche qu'avec le jaune en bas","Pour que la croix blanche ne bouge jamais","Pour retourner le blanc vers le haut"],a:0,w:"R U R' U' échange le coin du dessus avec la case devant à droite en bas. Le bon coin doit donc y être garé."},
{i:"rb296_31",u:296,t:"num",d:.7,q:"Pire cas : 4 coins garés blanc devant. Combien de sexy moves au total ?",a:20,tol:0,un:" sexy moves",h:"4 coins x 5",w:"4 x 5 = 20. En pratique, tu en feras plutôt 10 à 12."},
{i:"rb296_32",u:296,t:"story",d:.75,q:"Synthèse : Inès te fait réciter.",sc:[{who:"Inès Morel",txt:"L'étape des coins blancs, en une phrase."}],o:["Garer au-dessus, devant à droite, R U R' U' propre","Faire la face blanche couleur par couleur, sans croix","Tourner D jusqu'à ce que les coins tombent en place","Placer les coins jaunes avant les coins blancs"],a:0,w:"Garer, se placer, laver : quatre coins, et la première couche est finie."}
