/*UNIT*/
{id:299,c:"RUBIK",n:"Module 7",t:"Étape 5, placer les arêtes jaunes : la formule Sune",col:"--orange",ic:"🔁",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Vérifier quelles arêtes jaunes sont <b>bien placées</b> par rapport aux centres.</li>
<li>Tenir deux arêtes justes <b>derrière et à droite</b>.</li>
<li>Exécuter la formule <b>Sune</b> suivie de <b>U</b>.</li>
<li>Gérer le cas des deux arêtes justes <b>opposées</b>.</li></ul>
<h3>Le soleil de Sacha</h3>
<div class="gstory">Thierry a sa croix jaune. Mais sur les côtés, rien ne colle : l'arête rouge est au-dessus du centre vert. Sacha prend le cube : « Tourne le dessus jusqu'à ce que deux arêtes collent à leur centre. » Thierry tourne. Rouge sur rouge, bleu sur bleu. « Voisines ? Parfait. Mets-les derrière et à droite. Maintenant, le Sune. » Sept coups, puis un U. Les quatre arêtes collent. Sacha : « Sune, comme <i>sun</i>, le soleil. La forme qu'il fait apparaître ressemble à un poisson, mais on ne va pas chipoter. »</div>
<h3>Lire les arêtes</h3>
<ul><li>Une arête jaune est <b>bien placée</b> si sa couleur de côté est <b>au-dessus du centre</b> de même couleur.</li>
<li>Tourne <b>U</b> jusqu'à avoir <b>au moins deux</b> arêtes bien placées. C'est toujours possible.</li>
<li>Deux cas : elles sont <b>voisines</b> (en angle) ou <b>opposées</b> (face à face).</li></ul>
<h3>La formule</h3>
<div class="formula">R U R' U R U2 R' U</div>
<ul><li>Les sept premiers coups forment le <b>Sune</b>, la formule la plus connue du cube.</li>
<li>Le <b>U</b> final réaligne le dessus.</li>
<li>Effet : les arêtes de <b>devant</b> et de <b>gauche</b> s'échangent, celles de derrière et de droite restent.</li></ul>
<svg class='gsvg' viewBox='0 0 180 208' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='14' y='14' width='152' height='152' rx='10' fill='#141432'/><rect x='40.0' y='40.0' width='32.0' height='32.0' rx='4' fill='#009E60'/><rect x='74.0' y='40.0' width='32.0' height='32.0' rx='4' fill='#FFD500'/><rect x='108.0' y='40.0' width='32.0' height='32.0' rx='4' fill='#C41E3A'/><rect x='40.0' y='74.0' width='32.0' height='32.0' rx='4' fill='#FFD500'/><rect x='74.0' y='74.0' width='32.0' height='32.0' rx='4' fill='#FFD500'/><rect x='108.0' y='74.0' width='32.0' height='32.0' rx='4' fill='#FFD500'/><rect x='40.0' y='108.0' width='32.0' height='32.0' rx='4' fill='#FFD500'/><rect x='74.0' y='108.0' width='32.0' height='32.0' rx='4' fill='#FFD500'/><rect x='108.0' y='108.0' width='32.0' height='32.0' rx='4' fill='#0051BA'/><rect x='40.0' y='144.0' width='32.0' height='16.0' rx='4' fill='#FF5800'/><rect x='40.0' y='20.0' width='32.0' height='16.0' rx='4' fill='#FFD500'/><rect x='74.0' y='144.0' width='32.0' height='16.0' rx='4' fill='#C41E3A'/><rect x='74.0' y='20.0' width='32.0' height='16.0' rx='4' fill='#0051BA'/><rect x='108.0' y='144.0' width='32.0' height='16.0' rx='4' fill='#FFD500'/><rect x='108.0' y='20.0' width='32.0' height='16.0' rx='4' fill='#0051BA'/><rect x='20.0' y='40.0' width='16.0' height='32.0' rx='4' fill='#C41E3A'/><rect x='144.0' y='40.0' width='16.0' height='32.0' rx='4' fill='#FFD500'/><rect x='20.0' y='74.0' width='16.0' height='32.0' rx='4' fill='#009E60'/><rect x='144.0' y='74.0' width='16.0' height='32.0' rx='4' fill='#FF5800'/><rect x='20.0' y='108.0' width='16.0' height='32.0' rx='4' fill='#009E60'/><rect x='144.0' y='108.0' width='16.0' height='32.0' rx='4' fill='#FF5800'/><line x1='56.0' y1='90.0' x2='82.2' y2='116.2' stroke='#141432' stroke-width='6' stroke-linecap='round'/><line x1='56.0' y1='90.0' x2='82.2' y2='116.2' stroke='#FFFFFF' stroke-width='3' stroke-linecap='round'/><polygon points='87.9,121.9 78.0,120.5 86.5,112.0' fill='#FFFFFF' stroke='#141432' stroke-width='1.2'/><line x1='90.0' y1='124.0' x2='63.8' y2='97.8' stroke='#141432' stroke-width='6' stroke-linecap='round'/><line x1='90.0' y1='124.0' x2='63.8' y2='97.8' stroke='#FFFFFF' stroke-width='3' stroke-linecap='round'/><polygon points='58.1,92.1 68.0,93.5 59.5,102.0' fill='#FFFFFF' stroke='#141432' stroke-width='1.2'/><text x='90' y='188' font-size='10' fill='var(--txt)' text-anchor='middle' font-weight='700'>Arêtes justes derrière et à droite</text><text x='90' y='200' font-size='10' fill='var(--txt)' text-anchor='middle' font-weight='700'>: devant et gauche vont s'échanger</text></svg>
<div class="gmnemo">Le Sune se chante : <b>« monte, gauche, descends, gauche, monte, double, descends »</b>. R U R' U, puis R U2 R'. Retiens le rythme <b>1, 1, 2</b> : U, U, U2.</div>
<h3>Cube en main : deux arêtes voisines</h3>
<ol><li>Croix jaune faite. Tourne U jusqu'à deux arêtes bien placées et voisines.</li>
<li>Tourne <b>tout le cube</b> (y) pour mettre ces deux arêtes <b>derrière et à droite</b>.</li>
<li>Fais <b>R U R' U R U2 R' U</b>.</li>
<li>Tourne U si besoin : les quatre arêtes collent à leur centre.</li></ol>
<h3>Cube en main : deux arêtes opposées</h3>
<ol><li>Les deux arêtes justes sont face à face, devant et derrière.</li>
<li>Fais la formule <b>une fois</b>, de n'importe quelle position.</li>
<li>Tourne U : tu trouves maintenant deux arêtes <b>voisines</b>. Reprends le cas précédent.</li></ol>
<div class="gtrap">Le piège : vérifier les arêtes <b>sans tourner U</b> d'abord. On croit n'avoir aucune arête juste alors qu'un quart de tour en aligne deux. Autre piège : tenir les deux bonnes arêtes <b>devant et à gauche</b>. La formule les échangerait et tout serait à refaire.</div>
<h3>Les coins ne comptent pas encore</h3>
<ul><li>La formule déplace aussi les <b>coins jaunes</b>. C'est normal.</li>
<li>Seules comptent les <b>quatre arêtes</b> à cette étape.</li>
<li>Les coins se placent puis se tournent au module 8.</li></ul>
<h3>Ce que tu dois retenir</h3>
<ul><li>Tourne U jusqu'à deux arêtes bien placées.</li>
<li>Voisines : derrière et à droite, puis R U R' U R U2 R' U.</li>
<li>Opposées : une formule, puis tu as des voisines.</li></ul>`},
/*EXOS*/
{i:"rb299_01",u:299,t:"mcq",d:.15,nw:"Lire les arêtes",q:"Quand une arête jaune est-elle bien placée ?",o:["Sa couleur de côté est juste au-dessus de son centre","Son jaune regarde vers le haut, c'est suffisant","Elle touche un coin de la même couleur","Elle est juste devant le centre jaune"],a:0,w:"Le jaune vers le haut, c'est la croix. Bien placée veut dire alignée sur le centre de côté."},
{i:"rb299_02",u:299,t:"story",d:.15,q:"Que dit Sacha à Thierry ?",sc:[{who:"Thierry",txt:"Aucune arête ne colle à son centre. Je fais la formule ?"}],o:["Tourne d'abord U pour en aligner deux","Oui, la formule règle tous les cas","Non, refais la croix jaune avant","Oui, et répète-la jusqu'à ce que ça colle"],a:0,w:"Un quart de tour du dessus suffit souvent à aligner deux arêtes. On peut toujours en avoir au moins deux."},
{i:"rb299_03",u:299,t:"order",d:.2,nw:"La formule",q:"Remets dans l'ordre la formule des arêtes jaunes.",it:["R","U","R'","U","R","U2","R'","U"],w:"Le Sune (R U R' U R U2 R') puis U. Rythme U, U, U2."},
{i:"rb299_04",u:299,t:"fill",d:.2,q:"La formule R U R' U R U2 R' s'appelle le ___.",o:["Sune","sexy move","T-perm","Niklas"],a:0,w:"Sune, comme sun, le soleil. La formule la plus célèbre du cube."},
{i:"rb299_05",u:299,t:"tf",d:.2,q:"Pour la formule, les deux arêtes bien placées se tiennent derrière et à droite.",a:true,w:"La formule échange devant et gauche : les arêtes justes doivent donc être derrière et à droite."},
{i:"rb299_06",u:299,t:"sort",d:.25,q:"Classe chaque situation.",bins:["Voisines","Opposées"],it:[["Arêtes justes derrière et à droite",0],["Arêtes justes devant et derrière",1],["Arêtes justes à gauche et à droite",1],["Arêtes justes devant et à gauche",0]],w:"En angle, elles sont voisines. Face à face, elles sont opposées."},
{i:"rb299_07",u:299,t:"tiles",d:.25,q:"Reconstitue le Sune.",a:["R","U","R'","U","R","U2","R'"],dd:["F","L"],w:"Monte, gauche, descends, gauche, monte, double, descends."},
{i:"rb299_08",u:299,t:"story",d:.25,q:"Cube en main : que fais-tu ?",ctx:"Après un U, les arêtes justes sont devant et à droite.",sc:[{who:"Inès Morel",txt:"Elles sont voisines. Avant la formule ?"}],o:["Je les mets derrière et à droite","Je fais la formule tout de suite","Je fais la formule deux fois de suite","Je refais la croix jaune avant tout"],a:0,w:"Une rotation y du cube entier place la paire juste derrière et à droite. Ensuite, la formule."},
{i:"rb299_09",u:299,t:"mcq",d:.3,q:"Que font les arêtes de devant et de gauche pendant la formule ?",o:["Elles s'échangent","Elles restent en place","Elles se retournent","Elles descendent au milieu"],a:0,w:"Vérifié au simulateur : devant et gauche s'échangent, derrière et droite restent."},
{i:"rb299_10",u:299,t:"multi",d:.3,q:"Cube en main : la formule finie, que vérifies-tu ?",o:["Les quatre arêtes collent à leur centre","La croix jaune est toujours là","Les deux premières couches sont intactes","Les coins jaunes sont tous à leur place"],a:[0,1,2],w:"Les coins peuvent être mélangés : ils viennent au module 8."},
{i:"rb299_11",u:299,t:"tf",d:.3,q:"Il est possible de n'avoir aucune arête bien placée, quelle que soit la position de U.",a:false,w:"On peut toujours en aligner au moins deux en tournant le dessus."},
{i:"rb299_12",u:299,t:"story",d:.35,q:"Que dit Inès ?",ctx:"Les arêtes justes sont devant et derrière.",sc:[{who:"Thierry",txt:"Elles sont face à face. Je les mets où ?"}],o:["Où tu veux : une formule, puis des voisines","Devant et derrière, et la formule finit tout","À gauche et à droite, la formule finit tout","Il faut refaire la croix jaune depuis le début"],a:0,w:"Cas des opposées : une formule de n'importe quelle position, puis U pour trouver deux voisines."},
{i:"rb299_13",u:299,t:"match",d:.35,q:"Associe chaque cas à son traitement.",p:[["Deux voisines","Derrière et droite, puis formule"],["Deux opposées","Une formule, puis cas voisines"],["Quatre justes","Rien, étape suivante"],["Aucune juste","Tourner U d'abord"]],w:"Tous les cas de l'étape des arêtes jaunes."},
{i:"rb299_14",u:299,t:"num",d:.35,q:"Combien de coups compte la formule complète, U final compris ?",a:8,tol:0,un:" coups",h:"Sune + U",w:"7 coups de Sune, plus le U final : 8 coups."},
{i:"rb299_15",u:299,t:"fill",d:.4,q:"Le rythme des U dans le Sune est : U, U, ___.",o:["U2","U'","U","R2"],a:0,w:"1, 1, 2 : un quart, un quart, un demi-tour."},
{i:"rb299_16",u:299,t:"tf",d:.4,q:"Cube en main : la formule des arêtes déplace aussi les coins jaunes.",a:true,w:"C'est normal. À cette étape, seules les arêtes comptent."},
{i:"rb299_17",u:299,t:"story",d:.4,q:"Rappel du module 6 : que dit Sacha ?",sc:[{who:"Thierry",txt:"Après la formule des arêtes, ma croix jaune a disparu."}],o:["Ton cube a tourné pendant la formule","C'est normal, refais la croix ensuite","La formule casse toujours la croix jaune","Il fallait faire F R U R' U' F' avant"],a:0,w:"La formule garde la croix. Si elle disparaît, le cube a tourné dans les mains ou un coup a été oublié."},
{i:"rb299_18",u:299,t:"sort",d:.45,q:"Bon réflexe ou piège ?",bins:["Bon réflexe","Piège"],it:[["Tourner U avant de juger",0],["Tenir les bonnes arêtes devant et à gauche",1],["S'inquiéter des coins mélangés",1],["Mettre la paire juste derrière et à droite",0]],w:"Aligner, placer derrière et à droite, ignorer les coins pour l'instant."},
{i:"rb299_19",u:299,t:"mcq",d:.45,q:"Combien de formules au maximum pour placer les quatre arêtes ?",o:["2","1","4","6"],a:0,w:"Opposées : une formule pour obtenir des voisines, puis une pour finir."},
{i:"rb299_20",u:299,t:"tiles",d:.45,q:"Reconstitue la règle de position.",a:["Les","bonnes","derrière","et","à","droite"],dd:["devant","gauche"],w:"La formule échange devant et gauche. Les bonnes arêtes restent derrière et à droite."},
{i:"rb299_21",u:299,t:"tf",d:.5,q:"Le Sune doit son nom au mot anglais « sun », la lune.",a:false,w:"« Sun » veut dire soleil, pas lune. La forme jaune qu'il fait apparaître ressemble à un soleil, ou à un poisson."},
{i:"rb299_22",u:299,t:"story",d:.5,q:"Cube en main : que fais-tu ?",ctx:"Tu tournes U : une position donne quatre arêtes justes.",sc:[{who:"Inès Morel",txt:"Et maintenant ?"}],o:["Rien, je passe aux coins","Je fais la formule pour vérifier","Je refais la croix jaune","Je fais la formule deux fois"],a:0,w:"Quatre arêtes justes : l'étape est finie, on passe aux coins."},
{i:"rb299_23",u:299,t:"multi",d:.5,q:"Quelles paires d'arêtes sont voisines ?",o:["Derrière et droite","Devant et gauche","Gauche et derrière","Devant et derrière","Gauche et droite"],a:[0,1,2],w:"Voisines = en angle. Devant-derrière et gauche-droite sont opposées."},
{i:"rb299_24",u:299,t:"order",d:.55,q:"Remets dans l'ordre le cas des arêtes opposées.",it:["Constater les arêtes face à face","Faire la formule une fois","Tourner U jusqu'à deux voisines","Les mettre derrière et à droite","Faire la formule"],w:"Opposées, une formule, voisines, une formule."},
{i:"rb299_25",u:299,t:"fill",d:.55,q:"Avant de juger les arêtes, on tourne d'abord la face ___.",o:["U","R","F","D"],a:0,w:"U fait défiler les arêtes devant les centres sans rien casser."},
{i:"rb299_26",u:299,t:"story",d:.55,q:"Rappel du module 2 : que dit Inès ?",sc:[{who:"Thierry",txt:"Je confonds U2 et U'. C'est pareil ?"}],o:["Non : U2 demi-tour, U' quart inverse","Oui, les deux tournent vers la droite","Oui, U' veut dire deux fois U de suite","Non, U2 tourne la face du bas"],a:0,w:"U2 = deux quarts de tour. U' = un quart en sens inverse."},
{i:"rb299_27",u:299,t:"num",d:.6,q:"Combien de U (quarts de tour) contient le Sune, U2 compté comme deux ?",a:4,tol:0,un:" quarts",h:"U, U, U2",w:"1 + 1 + 2 = 4 quarts de tour de U dans le Sune."},
{i:"rb299_28",u:299,t:"tf",d:.6,q:"Cube en main : tu fais le Sune six fois de suite, le cube revient au départ.",a:true,w:"Vérifié au simulateur : le Sune répété 6 fois ramène le cube à son état initial."},
{i:"rb299_29",u:299,t:"mcq",d:.65,q:"Quelle rotation met deux arêtes voisines de devant-droite vers derrière-droite ?",o:["y'","y","x","z"],a:0,w:"y' tourne tout le cube comme U' : ce qui était devant passe à droite, ce qui était à droite passe derrière."},
{i:"rb299_30",u:299,t:"sort",d:.65,q:"Formule à faire ensuite ?",bins:["Formule des arêtes","Rien, étape suivante"],it:[["Deux arêtes justes voisines",0],["Quatre arêtes justes",1],["Deux arêtes justes opposées",0],["Arêtes justes, coins mélangés",1]],w:"Quatre arêtes justes : on passe aux coins, même s'ils sont mélangés."},
{i:"rb299_31",u:299,t:"match",d:.7,q:"Associe chaque étape du dessus à sa formule.",p:[["Croix jaune","F R U R' U' F'"],["Arêtes jaunes","R U R' U R U2 R' U"],["Coins blancs","R U R' U'"],["Arête du milieu à droite","U R U' R' U' F' U F"]],w:"Quatre formules déjà dans tes doigts : refais-les une par une, cube en main."},
{i:"rb299_32",u:299,t:"story",d:.75,q:"Synthèse : Inès te fait réciter.",sc:[{who:"Inès Morel",txt:"Les arêtes jaunes, en une phrase."}],o:["Deux arêtes alignées, derrière-droite, Sune, U","Sune à n'importe quel moment, jusqu'à six fois","Tourne le cube jusqu'à voir les arêtes collées","F R U R' U' F' répété jusqu'au bon alignement"],a:0,w:"Aligner, placer, Sune, U. Deux formules au plus."}
