/*UNIT*/
{id:168,c:"NON",n:"Module 2",t:"Tes droits et tes limites : ce que tu as le droit de refuser",col:"--pink",ic:"🧱",guide:`
<h3>La liste qu'Hélène t'a fait lire à voix haute</h3>
<div class="gstory">Deuxième séance. Hélène te tend une feuille : « Lisez-la à voix haute. » Tu commences : « J'ai le droit de dire non sans me justifier. J'ai le droit de changer d'avis. J'ai le droit de faire des erreurs... » À la quatrième ligne, ta voix tremble un peu. Hélène sourit : « Ce n'est pas une liste de privilèges. Ce sont des droits que tout le monde a déjà. Vous, vous ne vous les étiez simplement jamais accordés. »</div>
<h3>Les droits assertifs</h3>
<p>Le psychologue américain <b>Manuel J. Smith</b> les a formulés dans <i>When I Say No, I Feel Guilty</i> (1975, en français <i>Quand je dis non, je me sens coupable</i>). Voici les principaux, reformulés :</p>
<table><tr><th>Tu as le droit de...</th><th>Ce que ça change</th></tr>
<tr><td>Juger toi-même ton comportement, tes pensées, tes émotions</td><td>Tu n'as pas besoin de l'autorisation des autres pour décider</td></tr>
<tr><td>Ne pas donner de raisons ni d'excuses</td><td>« Non » est une phrase complète</td></tr>
<tr><td>Juger si tu es responsable des problèmes des autres</td><td>Le problème de Julie reste d'abord le problème de Julie</td></tr>
<tr><td>Changer d'avis</td><td>Un oui d'hier n'engage pas tous les jours suivants</td></tr>
<tr><td>Faire des erreurs, et en être responsable</td><td>Un faux pas n'efface pas tes droits</td></tr>
<tr><td>Dire « je ne sais pas »</td><td>Tu n'es pas obligé de répondre tout de suite</td></tr>
<tr><td>Être indépendant de la bonne volonté des autres</td><td>Tu peux vivre sans que tout le monde t'approuve</td></tr>
<tr><td>Prendre des décisions qui ne sont pas parfaitement logiques</td><td>« Je n'en ai pas envie » est une raison valable</td></tr>
<tr><td>Dire « je ne comprends pas »</td><td>Tu peux demander des précisions avant d'accepter</td></tr>
<tr><td>Dire « ça m'est égal »</td><td>Tu n'as pas à t'investir dans tout</td></tr></table>
<div class="gmnemo"><b>« Non » est une phrase complète.</b> C'est le droit le plus libérateur de la liste. Colle-le mentalement sur ton miroir. Une explication est un cadeau que tu fais à l'autre quand tu le veux, pas une taxe à payer pour avoir le droit de refuser.</div>
<h3>Les six familles de limites</h3>
<table><tr><th>Limite</th><th>Exemple</th></tr>
<tr><td><b>Temps</b></td><td>« Je ne travaille pas le week-end »</td></tr>
<tr><td><b>Énergie</b></td><td>« Ce soir, je rentre me reposer »</td></tr>
<tr><td><b>Argent</b></td><td>« Je ne prête plus d'argent tant que le précédent n'est pas rendu »</td></tr>
<tr><td><b>Corps et espace</b></td><td>« Je n'aime pas qu'on entre dans ma chambre sans frapper »</td></tr>
<tr><td><b>Émotions</b></td><td>« Je ne suis pas ta poubelle émotionnelle tous les soirs »</td></tr>
<tr><td><b>Valeurs</b></td><td>« Je ne mens pas au client pour toi »</td></tr></table>
<p>Une limite porte sur <b>ce que tu fais</b>, pas sur ce que l'autre doit faire. « Tu dois arrêter de me demander de l'argent » est une exigence (tu ne contrôles pas Sophie). « Je ne prête plus d'argent » est une limite (tu contrôles ton geste).</p>
<h3>Le test E.C.R. avant de répondre</h3>
<div class="formula">E comme Envie   : en ai-je envie ?
C comme Capacité : en ai-je le temps, l'énergie, les moyens ?
R comme Regret   : vais-je le regretter demain ?
Deux feux verts sur trois au moins, et pas de regret annoncé : oui possible.</div>
<div class="gmnemo"><b>E.C.R. comme un écran.</b> Avant de répondre, fais passer la demande sur ton écran intérieur : Envie, Capacité, Regret. Trois secondes suffisent. Si l'écran affiche « regret », la réponse est probablement non.</div>
<div class="gtrap">Piège fréquent : croire qu'une limite doit être justifiée par une « bonne » raison pour être légitime. Tu peux refuser un dîner parce que tu préfères lire. Autre piège : poser une limite en attaquant (« tu es sans gêne ! »). La limite concerne ton comportement, et se dit calmement, sans procès.</div>
<h3>Ce que tu dois savoir faire à la fin de ce module</h3>
<ul><li>Citer au moins six droits assertifs de Manuel J. Smith</li><li>Classer une limite dans l'une des six familles</li><li>Transformer une exigence envers l'autre en limite sur soi</li><li>Appliquer le test E.C.R.</li></ul>`},
/*EXOS*/
{i:"o168_01",u:168,t:"multi",d:.2,nw:"Les droits assertifs",q:"Lesquels font partie des droits assertifs de Manuel J. Smith ?",o:["Ne pas donner de raisons ni d'excuses","Changer d'avis","Faire des erreurs","Dire « je ne sais pas »","Exiger que tout le monde t'approuve"],a:[0,1,2,3],w:"Smith (1975) défend aussi le droit d'être indépendant de la bonne volonté des autres : personne n'a besoin de l'approbation de tous. Ces droits, tu les as déjà : il reste à te les accorder."},
{i:"o168_02",u:168,t:"tiles",d:.2,q:"Reconstitue la phrase à coller sur ton miroir.",a:["Non","est","une","phrase","complète"],dd:["méchante","toujours","excuse"],w:"Une explication est un cadeau, pas une taxe. Tu peux en donner une quand tu le souhaites, jamais par obligation."},
{i:"o168_03",u:168,t:"sort",d:.3,nw:"Les six familles de limites",q:"Classe chaque phrase dans sa famille de limite.",bins:["Temps","Argent","Émotions","Valeurs"],it:[["« Je ne réponds pas aux mails le dimanche »",0],["« Je ne prête plus tant que ce n'est pas rendu »",1],["« Je ne peux pas t'écouter te plaindre tous les soirs »",2],["« Je ne mentirai pas au client pour toi »",3],["« Je pars à 18 h le vendredi »",0],["« Je ne paie pas ta part du restaurant »",1]],w:"Temps, énergie, argent, corps et espace, émotions, valeurs : savoir laquelle est touchée t'aide à nommer clairement ce que tu refuses."},
{i:"o168_04",u:168,t:"story",d:.25,q:"Julie insiste pour connaître ta raison. Que peux-tu répondre ?",sc:[{who:"Julie",txt:"Tu ne peux pas relire mon dossier ce soir ? Mais pourquoi ? Tu as quoi de si important ?"}],o:["« Ce soir, ce n'est pas possible pour moi. »","« Désolé, j'ai un anniversaire, et en plus je suis crevé, et ma sœur m'attend. »","« Parce que tu me demandes toujours tout à moi, et c'est franchement pénible ! »","« Bon, d'accord, je vais le relire, mais c'est vraiment la dernière fois. »"],a:0,w:"Tu as le droit de ne pas te justifier : « non » est une phrase complète. Une réponse courte et calme suffit ; empiler les excuses donne à Julie autant de prises pour négocier. Et tu restes gentil : pas besoin d'attaquer."},
{i:"o168_05",u:168,t:"tf",d:.25,q:"Pour poser une limite, il faut d'abord avoir une excellente raison.",a:false,w:"« Je n'en ai pas envie » est une raison valable. Smith le formule ainsi : tu as le droit de prendre des décisions qui ne sont pas parfaitement logiques."},
{i:"o168_06",u:168,t:"order",d:.3,nw:"Le test E.C.R.",q:"Remets dans l'ordre les trois questions du test E.C.R.",it:["En ai-je envie ?","En ai-je la capacité ?","Vais-je le regretter ?"],w:"Envie, Capacité, Regret : ton écran intérieur. Trois secondes pour éviter un oui subi."},
{i:"o168_07",u:168,t:"fill",d:.3,q:"Une limite porte sur ce que ___ fais, pas sur ce que l'autre doit faire.",o:["tu","il","on","nous"],a:0,w:"« Je ne prête plus d'argent » est une limite que tu contrôles. « Tu dois arrêter de demander » est une exigence sur Sophie, que tu ne contrôles pas."},
{i:"o168_08",u:168,t:"story",d:.3,q:"Transforme cette exigence en limite.",sc:[{who:"Toi (brouillon)",txt:"« Sophie, tu dois arrêter de me demander de l'argent. »"},{who:"Hélène Marchal",txt:"Reformulez en parlant de ce que vous, vous faites."}],o:["« Sophie, je ne prête plus d'argent tant que le précédent n'est pas rendu. »","« Sophie, tu ne dois plus jamais me demander un seul euro, c'est compris ? »","« Sophie, tu pourrais peut-être arrêter de demander, si ça ne te dérange pas ? »","« Sophie, tout le monde trouve que tu exagères avec l'argent, tu sais. »"],a:0,w:"La limite parle de ton geste, calmement. Elle ne dépend pas de la bonne volonté de Sophie : c'est ce qui la rend solide."},
{i:"o168_09",u:168,t:"match",d:.3,q:"Associe chaque droit assertif à la situation où il t'aide.",p:[["Changer d'avis","Tu avais accepté, tu ne peux finalement plus"],["Dire « je ne sais pas »","Karim veut une réponse immédiate"],["Ne pas te justifier","Julie exige une raison détaillée"],["Faire des erreurs","Tu as oublié un rendez-vous"]],w:"Chaque droit est un outil concret. Plus tu les connais, moins tu te sens coupable d'exister avec tes propres besoins."},
{i:"o168_10",u:168,t:"mcq",d:.3,q:"Qui a formulé les droits assertifs dans « Quand je dis non, je me sens coupable » ?",o:["Manuel J. Smith","Marshall Rosenberg","Robert Cialdini","William Ury"],a:0,w:"Manuel J. Smith, 1975. Rosenberg a créé la communication non violente, Cialdini a étudié l'influence, Ury le non positif : tu les retrouveras tous dans ce cours."},
{i:"o168_11",u:168,t:"tf",d:.3,q:"Avoir dit oui une fois t'oblige à dire oui les fois suivantes.",a:false,w:"Tu as le droit de changer d'avis. Un oui d'hier n'engage pas tous les jours d'après. C'est même sain de réévaluer quand ta situation change."},
{i:"o168_12",u:168,t:"story",d:.35,q:"Applique le test E.C.R. à la demande de Mme Leblanc.",ctx:"Mme Leblanc, ta voisine de 78 ans, te demande de porter ses courses samedi matin. Tu es disponible, ça te prend dix minutes, et tu l'apprécies.",sc:[{who:"Mme Leblanc",txt:"Ça ne vous embête pas trop, mon petit ?"}],o:["Envie oui, capacité oui, pas de regret : un oui choisi, avec plaisir","Il faut refuser, sinon elle prendra l'habitude de tout te demander","Il faut accepter mais lui dire que c'est vraiment exceptionnel","Impossible de savoir, il faudrait d'abord connaître ses intentions"],a:0,w:"Le but n'est pas de dire non à tout ! Trois feux verts : ton oui est choisi, généreux, sans ressentiment. C'est exactement le genre de oui que ce cours veut protéger."},
{i:"o168_13",u:168,t:"sort",d:.4,q:"Classe chaque phrase : limite (sur toi) ou exigence (sur l'autre) ?",bins:["Limite","Exigence"],it:[["« Je quitte la réunion à 18 h »",0],["« Tu dois arrêter de m'appeler si tard »",1],["« Je ne réponds plus au téléphone après 22 h »",0],["« Tu ne dois plus entrer sans frapper »",1],["« Je frappe à ta porte, j'attends que tu m'invites à entrer »",0]],w:"La limite décrit ton action, que tu contrôles. L'exigence décrit ce que l'autre doit faire : elle dépend de sa bonne volonté."},
{i:"o168_14",u:168,t:"slider",d:.35,q:"Combien de secondes suffisent, selon Hélène, pour faire passer une demande sur ton écran E.C.R. ?",min:0,max:30,step:1,a:3,tol:1,pre:"",un:" s",w:"Environ trois secondes : une respiration. Ce petit délai casse le réflexe du oui immédiat."},
{i:"o168_15",u:168,t:"fill",d:.35,q:"Tu as le droit de juger si tu es ___ des problèmes des autres.",o:["responsable","coupable","témoin","juge"],a:0,w:"Le problème de Julie (un dossier en retard) est d'abord le sien. Tu peux l'aider par choix, mais tu n'en es pas responsable par défaut."},
{i:"o168_16",u:168,t:"story",d:.4,q:"Élodie t'appelle pour la troisième fois de la soirée. Quelle limite émotionnelle poses-tu ?",sc:[{who:"Élodie",txt:"J'ai encore besoin de te parler de Maxime, tu as bien une heure ?"},{who:"Toi",me:true,txt:"(il est 23 h, tu travailles tôt demain)"}],o:["« Je t'écoute dix minutes ce soir, et on en reparle demain midi. »","« Tu m'épuises avec tes histoires, trouve-toi quelqu'un d'autre. »","« Bien sûr, prends tout le temps qu'il faut, je ne dors pas de toute façon. »","« Je ne réponds plus, je vais faire semblant d'être déjà endormi. »"],a:0,w:"Une limite n'est pas un abandon : tu restes présent, avec un cadre. C'est souvent la forme la plus aimante du non."},
{i:"o168_17",u:168,t:"multi",d:.4,q:"Quelles sont les six familles de limites ?",o:["Temps","Énergie","Argent","Corps et espace","Émotions","Valeurs","Popularité"],a:[0,1,2,3,4,5],w:"Six familles. La popularité n'est pas une limite : c'est justement ce qu'on risque de sacrifier ses limites pour obtenir."},
{i:"o168_18",u:168,t:"mcq",d:.4,q:"Pourquoi une explication trop longue affaiblit-elle un refus ?",o:["Chaque raison devient une prise pour négocier","Elle rend le refus plus poli et plus crédible","Elle prouve qu'on a vraiment réfléchi","Elle empêche l'autre de se vexer"],a:0,w:"« J'ai un anniversaire » appelle « tu partiras juste après ». Une raison courte ou aucune raison laisse moins de prises."},
{i:"o168_19",u:168,t:"story",d:.45,q:"Karim veut une réponse immédiate pour un déplacement à Lyon. Quel droit utilises-tu ?",sc:[{who:"Karim",txt:"J'ai besoin de toi à Lyon mardi et mercredi. C'est bon pour toi ? Dis-moi maintenant."}],o:["« Je regarde mon planning et je te réponds avant 16 h. »","« Oui, bien sûr, pas de problème, je m'organiserai. »","« Non, je ne vais jamais en déplacement, c'est hors de question. »","« Pourquoi toujours moi ? Demande donc à quelqu'un d'autre. »"],a:0,w:"Le droit de dire « je ne sais pas » (encore) : tu gagnes du temps pour vérifier. Une réponse différée avec une échéance est professionnelle, pas une dérobade."},
{i:"o168_20",u:168,t:"tf",d:.4,q:"Refuser un dîner simplement parce qu'on préfère rester lire est une raison légitime.",a:true,w:"Tu n'as pas à justifier tes préférences. Tu peux simplement dire : « Merci pour l'invitation, je ne serai pas des vôtres cette fois. »"},
{i:"o168_21",u:168,t:"match",d:.45,q:"Associe chaque limite à sa famille.",p:[["« Je ne mens pas pour toi »","Valeurs"],["« Je frappe avant d'entrer et j'aimerais la même chose »","Corps et espace"],["« Ce soir, je me repose »","Énergie"],["« Je ne travaille pas le dimanche »","Temps"]],w:"Nommer la famille de ta limite t'aide à la formuler simplement et à la tenir."},
{i:"o168_22",u:168,t:"fill",d:.45,q:"Selon Smith, tu as le droit d'être indépendant de la bonne ___ des autres.",o:["volonté","humeur","réputation","éducation"],a:0,w:"Tu peux vivre sans que tout le monde t'approuve. C'est un droit, et c'est aussi une immense liberté."},
{i:"o168_23",u:168,t:"story",d:.45,q:"Lucas veut que tu lui prêtes ta voiture pour le week-end. Tu n'en as pas envie. Que dis-tu ?",sc:[{who:"Lucas",txt:"Allez, tu ne t'en sers pas ce week-end ! Tu me dois bien ça, non ?"}],o:["« Je ne prête pas ma voiture, Lucas. Par contre je peux t'aider à en louer une. »","« Je te la prête, mais si tu fais une rayure, je te préviens, on ne se parle plus. »","« Euh... je crois que je m'en sers peut-être, enfin je ne sais pas trop encore. »","« Tu ne manques pas de culot, toi ! Jamais de la vie je ne te la prête. »"],a:0,w:"Limite claire sur ton bien (argent et matériel), plus une aide alternative si tu le souhaites. Le « tu me dois bien ça » est une pression, tu verras comment la reconnaître au module 10."},
{i:"o168_24",u:168,t:"num",d:.45,q:"Sophie te doit 200 € de mars et te demande 300 € de plus. Si tu refuses, combien d'argent protèges-tu ?",a:300,tol:0,un:" €",h:"Le nouveau prêt demandé",w:"300 €, et tu rends ta limite visible : « Je ne prête plus tant que le précédent n'est pas rendu ». Les 200 € restent une conversation à avoir, calmement."},
{i:"o168_25",u:168,t:"sort",d:.5,q:"Classe chaque réponse au test E.C.R. : feu vert ou feu rouge ?",bins:["Feu vert","Feu rouge"],it:[["J'ai envie d'aider ce collègue",0],["Je n'ai plus aucune énergie cette semaine",1],["Je sais que je vais m'en vouloir demain",1],["J'ai deux heures libres samedi",0],["J'accepterais seulement pour ne pas le décevoir",1]],w:"Accepter uniquement pour ne pas décevoir, c'est un signal rouge : l'envie manque. Les feux rouges ne t'interdisent rien, ils t'informent."},
{i:"o168_26",u:168,t:"mcq",d:.5,q:"Rappel du module 1 : quelle différence entre un oui choisi et un oui subi ?",o:["Le choisi vient de l'envie, le subi de la peur du malaise","Le choisi est toujours plus facile à tenir que le subi","Le subi rend service, le choisi ne rend jamais service","Aucune, un oui reste un oui"],a:0,w:"Tout est dans la raison du oui. Le test E.C.R. sert précisément à savoir lequel tu es en train de dire."},
{i:"o168_27",u:168,t:"story",d:.5,q:"Tante Monique demande pourquoi tu ne viens pas. Quelle réponse respecte ton droit à ne pas te justifier ET la relation ?",sc:[{who:"Tante Monique",txt:"Et pourquoi tu ne viens pas dimanche, hein ? Tu as mieux à faire ?"}],o:["« Je ne viens pas ce dimanche, tatie. Je t'appelle mercredi pour qu'on se voie bientôt. »","« J'ai un séminaire, un anniversaire, un rendez-vous et une fuite d'eau à réparer. »","« Je n'ai pas à me justifier, c'est mon droit, j'ai lu ça dans un livre. »","« Bon, d'accord, je vais venir, mais je ne pourrai rester qu'une petite heure. »"],a:0,w:"Pas d'excuse inventée (« non » est une phrase complète), pas de procès, et un geste pour la relation. Citer ses droits comme un règlement braque l'autre : on les vit, on ne les récite pas."},
{i:"o168_28",u:168,t:"tiles",d:.5,q:"Reconstitue la définition d'une limite.",a:["Une","limite","porte","sur","ce","que","je","fais"],dd:["tu","dois","toujours"],w:"Je ne contrôle que mes actes. C'est ce qui rend une limite solide, même si l'autre n'est pas d'accord."},
{i:"o168_29",u:168,t:"tf",d:.55,q:"Selon Smith, on a le droit de dire « ça m'est égal ».",a:true,w:"Tu n'as pas à t'investir dans tout, ni à avoir un avis sur tout. Économiser ton énergie fait partie de tes limites."},
{i:"o168_30",u:168,t:"story",d:.55,q:"Julie te dit que tu as changé. Que réponds-tu, calmement ?",sc:[{who:"Julie",txt:"Avant tu m'aidais toujours. Tu as changé, toi..."}],o:["« Oui, j'apprends à mieux gérer mon temps. Je t'aiderai quand je le pourrai. »","« Non, pas du tout, je n'ai pas changé, je suis juste un peu fatigué en ce moment. »","« Oui, et c'est grâce à ma psy, qui m'a dit que tu profitais de moi. »","« Tu as raison, pardon, je reprends ton dossier ce soir si tu veux bien. »"],a:0,w:"Tu as le droit de changer. L'assumer calmement, sans accuser ni revenir en arrière, installe ta nouvelle limite. Les autres s'adaptent plus vite qu'on ne croit."},
{i:"o168_31",u:168,t:"order",d:.55,q:"Remets dans l'ordre ta façon de répondre à une demande avec le test E.C.R.",it:["Respirer avant de répondre","Vérifier l'envie","Vérifier la capacité","Anticiper le regret","Répondre oui, non ou « je te redis »"],w:"Respirer, puis Envie, Capacité, Regret. Et si tu ne sais pas encore, tu as le droit de différer ta réponse."},
{i:"o168_32",u:168,t:"multi",d:.6,q:"Quelles phrases posent une limite sans attaquer ?",o:["« Je pars à 18 h ce soir. »","« Je ne prête plus d'argent pour l'instant. »","« Je préfère qu'on en parle demain. »","« Tu es vraiment sans gêne ! »","« Tout le monde en a marre de toi. »"],a:[0,1,2],w:"Une limite se dit calmement, en parlant de soi. L'attaque transforme ta limite en conflit, alors que tu voulais seulement te protéger."}
