/*UNIT*/
{id:169,c:"NON",n:"Module 3",t:"Fuite, attaque, manipulation ou affirmation : les quatre attitudes",col:"--pink",ic:"🧭",guide:`
<h3>Quatre façons de réagir à la même demande</h3>
<div class="gstory">Hélène te montre une vidéo : Karim demande à quatre collaborateurs de rester jusqu'à 21 h. Le premier baisse les yeux, dit « oui oui » et envoie un message rageur à sa compagne dans les toilettes. La deuxième répond sèchement : « Encore ? Tu n'as vraiment aucune organisation ! » Le troisième dit « Pas de souci » puis, à 19 h, prétend avoir reçu un appel urgent et disparaît. La quatrième dit calmement : « Ce soir je ne peux pas rester après 19 h. Je peux arriver plus tôt demain pour finir. » Hélène coupe la vidéo : « Lequel vous ressemble ? Et lequel aimeriez-vous être ? »</div>
<h3>Les quatre attitudes face à une demande</h3>
<table><tr><th>Attitude</th><th>Ce qu'on fait</th><th>Ce qu'on croit</th><th>Ce que ça coûte</th></tr>
<tr><td><b>Fuite</b> (passivité)</td><td>On dit oui, on se tait, on évite</td><td>« Mes besoins comptent moins »</td><td>Ressentiment, épuisement</td></tr>
<tr><td><b>Attaque</b> (agressivité)</td><td>On accuse, on hausse le ton, on juge la personne</td><td>« Mes besoins comptent plus »</td><td>Relations abîmées, culpabilité après coup</td></tr>
<tr><td><b>Manipulation</b></td><td>On dit oui puis on se dérobe, on ment, on culpabilise</td><td>« Je ne peux pas dire les choses en face »</td><td>Perte de confiance quand c'est découvert</td></tr>
<tr><td><b>Affirmation</b> (assertivité)</td><td>On dit clairement ce qu'on veut et ce qu'on ne veut pas, en respectant l'autre</td><td>« Mes besoins et les tiens comptent autant »</td><td>Un malaise passager, puis du respect</td></tr></table>
<p>Cette grille est popularisée en France par le test d'assertivité de <b>Dominique Chalvin</b>, qui mesure la part de chacune des quatre attitudes chez une personne. Personne n'est à 100 % dans une case : on glisse de l'une à l'autre selon les situations et les personnes.</p>
<div class="gmnemo"><b>La boussole F.A.M.A.</b> Fuite au sud (je me baisse), Attaque au nord (je me dresse), Manipulation à l'ouest (je contourne), Affirmation à l'est, là où le soleil se lève. <b>Viser l'est</b> : ni au-dessus, ni en dessous, ni à côté de l'autre, mais en face, à la même hauteur.</div>
<h3>Le piège du balancier</h3>
<p>Beaucoup de personnes qui n'osent pas dire non passent de la fuite à l'attaque : elles accumulent des oui subis, puis explosent pour un détail. L'entourage ne comprend pas « pourquoi une telle colère pour si peu », et la personne en conclut qu'il vaut mieux se taire. Le cycle recommence. L'affirmation casse ce balancier : dire non tôt, calmement, avant que la cocotte ne siffle.</p>
<h3>Le triangle dramatique de Karpman</h3>
<p>Le psychiatre <b>Stephen Karpman</b> (1968) a décrit trois rôles dans lesquels on s'enferme dans les relations difficiles :</p>
<table><tr><th>Rôle</th><th>Phrase type</th><th>Lien avec le non</th></tr>
<tr><td><b>Sauveur</b></td><td>« Laisse, je m'en occupe »</td><td>Dit oui à tout, se rend indispensable, puis s'épuise</td></tr>
<tr><td><b>Victime</b></td><td>« Personne ne m'aide jamais »</td><td>Attire les sauveurs, n'assume pas ses choix</td></tr>
<tr><td><b>Persécuteur</b></td><td>« Tu n'es jamais à la hauteur »</td><td>Impose, critique, fait culpabiliser</td></tr></table>
<p>Les rôles tournent : le Sauveur épuisé devient Victime (« après tout ce que j'ai fait »), puis Persécuteur (« vous êtes tous des ingrats »). Sortir du triangle, c'est refuser d'y entrer : ne pas sauver quelqu'un qui ne l'a pas demandé, laisser l'autre responsable de son problème, et dire ce qu'on veut sans accuser.</p>
<div class="gtrap">Idée reçue : « l'assertivité, c'est être direct, quitte à être dur ». Non : l'attaque aussi est directe. Ce qui distingue l'affirmation, c'est le <b>respect des deux</b>. Autre idée reçue : « la manipulation, ce sont les autres ». Nous manipulons tous un peu quand nous n'osons pas dire non (fausse excuse, oui puis désistement). La repérer chez soi est un grand pas.</div>
<h3>Ce que tu dois savoir faire à la fin de ce module</h3>
<ul><li>Reconnaître les quatre attitudes dans une réponse</li><li>Expliquer le piège du balancier fuite-attaque</li><li>Nommer les trois rôles du triangle de Karpman</li><li>Transformer une réponse de fuite, d'attaque ou de manipulation en affirmation</li></ul>`},
/*EXOS*/
{i:"o169_01",u:169,t:"sort",d:.2,nw:"Les quatre attitudes",q:"Karim demande de rester jusqu'à 21 h. Classe chaque réponse.",bins:["Fuite","Attaque","Manipulation","Affirmation"],it:[["« Oui oui... » (puis message rageur en cachette)",0],["« Encore ? Tu n'as aucune organisation ! »",1],["« Pas de souci » puis faux appel urgent à 19 h",2],["« Je ne peux pas après 19 h, j'arrive plus tôt demain »",3]],w:"Fuite, Attaque, Manipulation, Affirmation. Seule la dernière respecte à la fois tes besoins et ceux de Karim. Et si tu te reconnais dans les trois autres, c'est normal : tout le monde y passe."},
{i:"o169_02",u:169,t:"mcq",d:.25,q:"Quelle croyance accompagne l'attitude d'affirmation ?",o:["« Mes besoins et les tiens comptent autant »","« Mes besoins comptent moins que les tiens »","« Mes besoins comptent plus que les tiens »","« Je ne peux pas dire les choses en face »"],a:0,w:"Ni au-dessus, ni en dessous : à la même hauteur. C'est l'est de la boussole F.A.M.A."},
{i:"o169_03",u:169,t:"story",d:.25,q:"Julie te refile encore un dossier. Quelle réponse est affirmée ?",sc:[{who:"Julie",txt:"Tu peux prendre le dossier Moreau ? Je suis débordée."}],o:["« Je ne peux pas le prendre cette semaine. Je peux te montrer une astuce pour aller vite. »","« Évidemment, tu es toujours débordée quand il s'agit de travailler, toi. »","« Oui, bien sûr, donne-le-moi. » (tu soupires longuement en le prenant)","« Pas de problème ! » (puis tu le laisses traîner en espérant qu'elle le reprenne)"],a:0,w:"Un non clair et une aide possible, sans jugement. Les trois autres sont l'attaque, la fuite et la manipulation. Chacune a un coût ; l'affirmation a juste un petit malaise passager."},
{i:"o169_04",u:169,t:"match",d:.3,nw:"Le triangle de Karpman",q:"Associe chaque rôle du triangle de Karpman à sa phrase type.",p:[["Sauveur","« Laisse, je m'en occupe »"],["Victime","« Personne ne m'aide jamais »"],["Persécuteur","« Tu n'es jamais à la hauteur »"],["Hors du triangle","« C'est ton choix, je te fais confiance »"]],w:"Karpman, 1968. On sort du triangle en laissant chacun responsable de son problème et en parlant d'égal à égal."},
{i:"o169_05",u:169,t:"tf",d:.25,q:"L'assertivité consiste à dire les choses directement, même si c'est blessant.",a:false,w:"L'attaque aussi est directe. L'affirmation est directe ET respectueuse. On peut dire non avec douceur."},
{i:"o169_06",u:169,t:"fill",d:.3,q:"Le test d'assertivité de Dominique ___ mesure la part de fuite, d'attaque, de manipulation et d'affirmation.",o:["Chalvin","Karpman","Rosenberg","Smith"],a:0,w:"Chalvin a popularisé ces quatre attitudes en France. Karpman a décrit le triangle dramatique, Rosenberg la CNV, Smith les droits assertifs."},
{i:"o169_07",u:169,t:"story",d:.3,q:"Tu as explosé contre Camille pour une histoire de vaisselle. Que s'est-il passé ?",ctx:"Depuis trois semaines, tu fais toutes les tâches sans rien dire. Hier soir, en voyant une tasse dans l'évier, tu as crié.",sc:[{who:"Camille",txt:"Tout ça pour une tasse ? Je ne te reconnais pas."}],o:["Le piège du balancier : trop de fuite accumulée, puis une attaque","Une vraie colère contre Camille, qui fait exprès de tout laisser traîner","Une simple fatigue passagère qui n'a rien à voir avec la vaisselle","Un trait de caractère colérique contre lequel on ne peut rien"],a:0,w:"Trois semaines de oui silencieux, puis l'explosion. Ce n'est pas un défaut de caractère : c'est un balancier. Dire les choses tôt et calmement l'arrête."},
{i:"o169_08",u:169,t:"multi",d:.3,q:"Quelles réponses relèvent de la manipulation ?",o:["Dire oui puis inventer un empêchement","Culpabiliser l'autre pour qu'il retire sa demande","Faire semblant de ne pas avoir vu le message","« Je ne peux pas ce soir, désolé »","« Non merci, je préfère rester chez moi »"],a:[0,1,2],w:"La manipulation contourne au lieu de dire. Nous le faisons tous parfois quand nous n'osons pas refuser en face. Les deux dernières réponses sont des refus directs et honnêtes."},
{i:"o169_09",u:169,t:"order",d:.35,q:"Remets dans l'ordre le cycle du balancier.",it:["Tu dis oui sans en avoir envie","Tu accumules du ressentiment en silence","Tu exploses pour un détail","L'autre ne comprend pas ta colère","Tu te sens coupable et te promets de te taire"],w:"Le cycle se referme sur le silence, et recommence. L'affirmation l'interrompt dès la première étape : dire non tôt, calmement."},
{i:"o169_10",u:169,t:"tiles",d:.3,q:"Reconstitue la devise de l'affirmation.",a:["Ni","au-dessus","ni","en","dessous","mais","à","la","même","hauteur"],dd:["toujours","contre","derrière"],w:"L'est de la boussole F.A.M.A. : en face, à la même hauteur que l'autre."},
{i:"o169_11",u:169,t:"story",d:.35,q:"Dans quel rôle de Karpman es-tu ?",sc:[{who:"Élodie",txt:"Je n'y arriverai jamais sans toi..."},{who:"Toi",me:true,txt:"Laisse, je vais appeler ton propriétaire moi-même, et je t'écris ta lettre de motivation ce soir."}],o:["Sauveur : tu prends en charge un problème qui est le sien","Victime : tu te plains de devoir tout faire pour les autres","Persécuteur : tu lui imposes tes solutions contre sa volonté","Aucun : c'est simplement de l'amitié et de la générosité"],a:0,w:"Faire à la place de l'autre, sans qu'on te l'ait vraiment demandé ou au-delà de tes forces, c'est le rôle du Sauveur. Aider, oui ; porter à sa place, non."},
{i:"o169_12",u:169,t:"tf",d:.35,q:"Une même personne peut être en fuite avec son manager et en attaque avec sa famille.",a:true,w:"Personne n'est à 100 % dans une case. On change d'attitude selon les personnes et les situations : c'est pourquoi on s'entraîne situation par situation."},
{i:"o169_13",u:169,t:"sort",d:.4,q:"Classe chaque phrase selon l'attitude.",bins:["Fuite","Attaque","Manipulation","Affirmation"],it:[["« Comme tu veux... »",0],["« Tu abuses toujours, c'est insupportable ! »",1],["« Si tu m'aimais vraiment, tu ne demanderais pas ça »",2],["« Je préfère ne pas, merci d'avoir pensé à moi »",3],["« Bon, d'accord, si ça peut te faire plaisir » (soupir)",0],["« Oui bien sûr » puis ne jamais le faire",2]],w:"Le soupir de la fuite, le « tu abuses » de l'attaque, le chantage de la manipulation, le « je préfère » de l'affirmation. Apprendre à les reconnaître, chez toi comme chez les autres, est une vraie compétence."},
{i:"o169_14",u:169,t:"mcq",d:.35,q:"Qui a décrit le triangle dramatique (Sauveur, Victime, Persécuteur) ?",o:["Stephen Karpman","Manuel J. Smith","Dominique Chalvin","Robert Cialdini"],a:0,w:"Stephen Karpman, 1968, dans le cadre de l'analyse transactionnelle."},
{i:"o169_15",u:169,t:"story",d:.4,q:"Transforme cette réponse de fuite en affirmation.",sc:[{who:"Lucas",txt:"On se fait un dernier bar ?"},{who:"Toi (réflexe)",txt:"Euh... bon... d'accord, un petit alors..."}],o:["« Pour moi c'est fini ce soir, je rentre. Super soirée, on remet ça bientôt ! »","« Non mais sérieux Lucas, tu ne sais jamais t'arrêter, c'est lourd à la fin. »","« Ok, j'arrive... » (puis tu files discrètement sans rien dire à personne)","« Je ne sais pas trop, peut-être, on verra bien plus tard dans la soirée, hein. »"],a:0,w:"Clair, chaleureux, et sans justification lourde. Une soirée qui se termine n'est pas une amitié qui se termine."},
{i:"o169_16",u:169,t:"fill",d:.4,q:"Sortir du triangle de Karpman, c'est laisser l'autre ___ de son problème.",o:["responsable","victime","coupable","dépendant"],a:0,w:"Tu peux proposer ton aide, écouter, conseiller ; mais le problème reste le sien. C'est aussi une marque de confiance en sa capacité."},
{i:"o169_17",u:169,t:"multi",d:.4,q:"Quels coûts l'attitude d'attaque entraîne-t-elle ?",o:["Des relations abîmées","De la culpabilité après coup","Une réputation de personne difficile","Plus de respect durable","Des accords plus solides"],a:[0,1,2],w:"L'attaque obtient parfois le résultat sur le moment, mais le paie cher dans la durée. L'affirmation obtient le respect sans ces coûts."},
{i:"o169_18",u:169,t:"story",d:.45,q:"Tu te surprends à manipuler. Que fais-tu ?",sc:[{who:"Toi (pensée)",txt:"Je vais dire à Sophie que ma banque a bloqué mon compte, comme ça elle ne me demandera plus rien."}],o:["Lui dire la vérité simplement : « Je ne prête plus d'argent pour l'instant. »","Maintenir l'excuse : c'est un petit mensonge qui évite un grand conflit","Ajouter plein de détails à l'excuse pour qu'elle soit plus crédible encore","Ne plus répondre à ses messages jusqu'à ce qu'elle oublie enfin sa demande"],a:0,w:"La fausse excuse est une manipulation douce : elle ne règle rien (Sophie redemandera quand la « banque » sera débloquée) et fragilise la confiance. La vérité, dite avec douceur, est plus simple à tenir."},
{i:"o169_19",u:169,t:"tf",d:.4,q:"Le Sauveur finit souvent par se sentir victime de ceux qu'il aide.",a:true,w:"« Après tout ce que j'ai fait pour eux... » : les rôles tournent dans le triangle. Aider par choix, dans tes limites, t'évite ce retournement."},
{i:"o169_20",u:169,t:"slider",d:.45,q:"Sur une semaine, tu as dit 10 oui subis et 0 non. Si tu transformes 3 de ces oui en non affirmés, quel pourcentage de tes réponses restent des oui subis ?",min:0,max:100,step:10,a:70,tol:0,pre:"",un:" %",w:"7 sur 10, soit 70 %. On ne vise pas 0 % d'un coup : chaque non affirmé est une victoire et entraîne le suivant."},
{i:"o169_21",u:169,t:"match",d:.45,q:"Associe chaque direction de la boussole à son attitude.",p:[["Sud","Fuite : je me baisse"],["Nord","Attaque : je me dresse"],["Ouest","Manipulation : je contourne"],["Est","Affirmation : je fais face"]],w:"La boussole F.A.M.A. Vise l'est, là où le soleil se lève."},
{i:"o169_22",u:169,t:"story",d:.45,q:"Karim joue le Persécuteur. Comment restes-tu hors du triangle ?",sc:[{who:"Karim",txt:"Franchement, si tu pars à 19 h, ne t'étonne pas si le projet rate. Ce sera ta faute."}],o:["« Je pars à 19 h. Voici où en est le projet et ce que je termine demain à 8 h. »","« Tu as raison, pardon, je reste jusqu'à ce soir tard, je ne voulais pas faire rater le projet. »","« Ce sera surtout la faute de ton organisation catastrophique, pas la mienne. »","« Personne ne me soutient jamais dans cette équipe, c'est toujours sur moi que ça tombe. »"],a:0,w:"Ni Victime (« personne ne me soutient »), ni Persécuteur en retour (« ton organisation catastrophique »), ni Sauveur coupable : des faits et un plan. C'est la sortie du triangle."},
{i:"o169_23",u:169,t:"mcq",d:.5,q:"Pourquoi les personnes qui n'osent pas dire non explosent-elles parfois « pour rien » ?",o:["Elles ont accumulé beaucoup de oui subis","Elles ont un caractère colérique inné","Elles cherchent surtout à se faire remarquer","Elles ne tiennent pas vraiment à leurs proches"],a:0,w:"C'est le balancier. L'explosion n'est pas pour la tasse, mais pour les trois semaines de silence. Dire non tôt protège aussi tes proches de tes colères."},
{i:"o169_24",u:169,t:"sort",d:.5,q:"Classe chaque rôle ou attitude : dans le triangle ou hors du triangle ?",bins:["Dans le triangle","Hors du triangle"],it:[["Faire le travail de l'autre sans qu'il le demande",0],["Proposer son aide et accepter un refus",1],["Se plaindre que personne ne nous aide",0],["Dire ce qu'on veut sans accuser",1],["Accuser l'autre d'être incapable",0]],w:"Sauver, se victimiser, persécuter : trois façons de rester dans le jeu. Proposer, accepter, dire sans accuser : trois façons d'en sortir."},
{i:"o169_25",u:169,t:"fill",d:.5,q:"Dans la boussole F.A.M.A., l'affirmation est à l'___.",o:["est","ouest","nord","sud"],a:0,w:"À l'est, là où le soleil se lève : en face de l'autre, à la même hauteur."},
{i:"o169_26",u:169,t:"story",d:.55,q:"Rappel du module 2 : quel droit utilises-tu face à Karim ?",sc:[{who:"Karim",txt:"Tu m'avais dit oui pour le salon de samedi. Tu ne peux pas revenir dessus."},{who:"Toi",me:true,txt:"(ta situation a changé, tu ne peux vraiment plus)"}],o:["Le droit de changer d'avis, en le disant tôt et en proposant une solution","Le droit de ne jamais travailler le samedi, qui est inscrit dans la loi","Le droit de ne pas répondre, en laissant tous ses messages sans réponse","Aucun : un oui donné à son manager ne peut jamais être repris"],a:0,w:"Tu as le droit de changer d'avis. Le faire tôt, franchement et avec une solution (un collègue, un autre créneau) respecte aussi Karim : c'est de l'affirmation."},
{i:"o169_27",u:169,t:"tiles",d:.55,q:"Reconstitue la clé pour sortir du triangle.",a:["Je","laisse","l'autre","responsable","de","son","problème"],dd:["sauve","accuse","toujours"],w:"Ni sauver, ni accuser, ni se plaindre : laisser à chacun sa part, et parler d'égal à égal."},
{i:"o169_28",u:169,t:"tf",d:.55,q:"Il est normal de se reconnaître dans les attitudes de fuite ou de manipulation.",a:true,w:"Tout le monde les utilise parfois. Les repérer sans te juger est exactement ce qui permet de choisir l'affirmation la prochaine fois."},
{i:"o169_29",u:169,t:"order",d:.6,q:"Remets dans l'ordre la rotation typique des rôles du triangle.",it:["Sauveur : « Laisse, je m'en occupe »","Victime : « Après tout ce que j'ai fait pour eux »","Persécuteur : « Vous êtes tous des ingrats »"],w:"Le Sauveur s'épuise, se victimise, puis attaque. Les rôles tournent tant qu'on reste dans le triangle."},
{i:"o169_30",u:169,t:"story",d:.6,q:"Mme Leblanc te demande un service. Tu es épuisé. Quelle réponse affirmée reste chaleureuse ?",sc:[{who:"Mme Leblanc",txt:"Vous pourriez me changer l'ampoule du couloir ce soir, mon petit ?"}],o:["« Ce soir je suis vraiment à plat. Demain à 18 h, ça vous irait ? »","« Encore ? Vous pourriez demander à quelqu'un d'autre de temps en temps ! »","« Oui, oui, bien sûr... » (tu y vas en traînant des pieds et en ruminant)","« Ah, je crois que je n'ai pas d'escabeau... » (alors que tu en as un)"],a:0,w:"Un non pour ce soir, un oui pour demain : tu respectes ta fatigue et sa demande. La fuite, l'attaque et le mensonge sont trois façons de rater cet équilibre."},
{i:"o169_31",u:169,t:"multi",d:.6,q:"Quelles sont les caractéristiques de l'affirmation de soi ?",o:["Dire clairement ce qu'on veut","Respecter l'autre en le disant","Accepter un malaise passager","Obtenir toujours ce qu'on demande","Écraser l'argument de l'autre"],a:[0,1,2],w:"L'affirmation ne garantit pas d'obtenir tout ce qu'on veut : elle garantit d'avoir été clair et respectueux. Et le petit malaise passe."},
{i:"o169_32",u:169,t:"mcq",d:.6,q:"Rappel du module 1 : pourquoi l'attitude de fuite est-elle si tentante ?",o:["Elle fait cesser le malaise tout de suite","Elle rend les autres bien plus reconnaissants","Elle protège durablement la relation","Elle fait gagner beaucoup de temps sur la durée"],a:0,w:"La fuite soulage immédiatement et coûte plus tard (les 3 R : ressentiment, retard, respect de soi). C'est un crédit à taux très élevé."}
