/*UNIT*/
{id:171,c:"NON",n:"Module 5",t:"Le non positif : Oui ! Non. Oui ?",col:"--pink",ic:"🌗",guide:`
<h3>Le non qui a rapproché Karim et toi</h3>
<div class="gstory">Karim te demande encore de rester jusqu'à 21 h. Cette fois, tu as préparé ta réponse avec Hélène. « Karim, je tiens à garder mes soirées du jeudi pour ma formation du soir, c'est important pour ma progression, et d'ailleurs pour l'équipe. Donc ce soir, je ne resterai pas après 18 h 30. Par contre, je peux arriver à 7 h 30 demain et te livrer la présentation à 10 h. Ça te va ? » Karim te regarde, surpris. Puis : « Ah. Ok. 10 h, c'est même mieux, en fait. » Tu sors du bureau en tremblant un peu. Et en souriant.</div>
<h3>La méthode de William Ury</h3>
<p><b>William Ury</b>, cofondateur du programme de négociation de Harvard (co-auteur de <i>Getting to Yes</i>), a écrit <i>The Power of a Positive No</i> (2007, en français <i>Le pouvoir d'un non positif</i>). Son idée : un bon non s'appuie sur un oui plus profond.</p>
<div class="formula">OUI !  à ce qui compte pour moi (mes intérêts, mes valeurs, mes priorités)
NON.   à la demande, clairement et respectueusement
OUI ?  à la relation : une proposition, une alternative, une question ouverte</div>
<table><tr><th>Temps</th><th>Ponctuation</th><th>Dans la réponse à Karim</th></tr>
<tr><td>Oui !</td><td>Un point d'exclamation : c'est ton élan, ce que tu protèges</td><td>« Je tiens à garder mes jeudis pour ma formation »</td></tr>
<tr><td>Non.</td><td>Un point : c'est ferme et posé</td><td>« Ce soir, je ne resterai pas après 18 h 30 »</td></tr>
<tr><td>Oui ?</td><td>Un point d'interrogation : c'est une invitation</td><td>« Je peux arriver à 7 h 30 et livrer à 10 h. Ça te va ? »</td></tr></table>
<div class="gmnemo"><b>« ! . ? »</b> Retiens la ponctuation d'Ury : un <b>point d'exclamation</b> (ce qui compte pour moi), un <b>point</b> (non), un <b>point d'interrogation</b> (une proposition). Et la phrase clé : <b>« Non à la demande, oui à la personne. »</b></div>
<h3>Préparer son non positif en trois étapes</h3>
<ol><li><b>Trouver ton oui</b> : pourquoi ce non est-il important pour toi ? Quel besoin, quelle valeur, quel projet protèges-tu ?</li>
<li><b>Renforcer ton non</b> : quel est ton <b>plan B</b> si l'autre n'accepte pas ton refus ? (C'est la MESORE de la négociation : ce que tu feras de toute façon.)</li>
<li><b>Respecter</b> : pendant tout l'échange, respect de la personne, même quand tu refuses la demande.</li></ol>
<h3>Les alternatives possibles (le « Oui ? »)</h3>
<table><tr><th>Alternative</th><th>Exemple</th></tr>
<tr><td>Plus tard</td><td>« Pas ce soir, mais samedi matin oui »</td></tr>
<tr><td>Moins</td><td>« Je ne relis pas tout, mais je regarde l'introduction »</td></tr>
<tr><td>Autrement</td><td>« Je ne te prête pas d'argent, je peux t'aider à faire ton budget »</td></tr>
<tr><td>Quelqu'un d'autre</td><td>« Demande à Léa, c'est son sujet »</td></tr>
<tr><td>Une ressource</td><td>« Voici le tutoriel qui m'a aidé »</td></tr></table>
<div class="gtrap">Piège : l'alternative n'est <b>pas obligatoire</b>. Tu n'as pas à compenser chaque non par un oui : parfois, un simple non courtois suffit (le vendeur au téléphone n'a pas besoin de plan B). Autre piège : proposer une alternative que tu ne veux pas vraiment tenir, par culpabilité. C'est un oui subi déguisé. Le « Oui ? » doit passer lui aussi le test E.C.R.</div>
<h3>Ce que tu dois savoir faire à la fin de ce module</h3>
<ul><li>Construire un non positif en trois temps</li><li>Identifier ton oui profond derrière un refus</li><li>Préparer un plan B</li><li>Choisir une alternative adaptée, ou décider de ne pas en proposer</li></ul>`},
/*EXOS*/
{i:"o171_01",u:171,t:"order",d:.2,nw:"Le non positif",q:"Remets dans l'ordre les trois temps du non positif de William Ury.",it:["Oui ! à ce qui compte pour moi","Non. à la demande","Oui ? à la relation, par une proposition"],w:"Point d'exclamation, point, point d'interrogation. Un non enraciné dans un oui plus profond est plus facile à dire et à entendre."},
{i:"o171_02",u:171,t:"sort",d:.25,q:"Découpe la réponse faite à Karim : à quel temps correspond chaque morceau ?",bins:["Oui !","Non.","Oui ?"],it:[["« Je tiens à garder mes jeudis pour ma formation »",0],["« Ce soir, je ne resterai pas après 18 h 30 »",1],["« Je peux arriver à 7 h 30 et livrer à 10 h. Ça te va ? »",2]],w:"Ton oui (la formation), ton non (ce soir), ta proposition (demain matin). Karim a obtenu mieux que ce qu'il demandait, et toi aussi."},
{i:"o171_03",u:171,t:"mcq",d:.25,q:"Qui a écrit « Le pouvoir d'un non positif » ?",o:["William Ury","Manuel J. Smith","Stephen Karpman","Marshall Rosenberg"],a:0,w:"William Ury (2007), cofondateur du programme de négociation de Harvard et co-auteur de Getting to Yes avec Roger Fisher."},
{i:"o171_04",u:171,t:"story",d:.3,q:"Sophie demande 300 €. Quel est le meilleur non positif ?",sc:[{who:"Sophie",txt:"Tu peux me dépanner de 300 € ? Je suis à sec."}],o:["« Je tiens à mon projet de voyage, donc je ne prête pas. Si tu veux, on regarde ton budget ensemble samedi ? »","« Non, désolé, je ne peux pas, je n'ai vraiment plus du tout d'argent en ce moment, je suis à découvert. »","« Encore ? Tu ne m'as toujours pas rendu les 200 € de mars, tu exagères franchement. »","« Oui, bien sûr, je te fais le virement tout de suite, ne t'inquiète pas pour moi. »"],a:0,w:"Oui à ton projet, non au prêt, oui à Sophie avec une aide qui te coûte peu. La deuxième est un mensonge, la troisième une attaque, la quatrième un oui subi."},
{i:"o171_05",u:171,t:"tf",d:.25,q:"Dans la méthode d'Ury, il faut toujours proposer une alternative après un non.",a:false,w:"L'alternative est une possibilité, pas une obligation. Au vendeur qui appelle, un « non merci » suffit. Et une alternative subie est un oui déguisé."},
{i:"o171_06",u:171,t:"tiles",d:.3,q:"Reconstitue la phrase clé du module.",a:["Non","à","la","demande","oui","à","la","personne"],dd:["jamais","toujours","excuse"],w:"Tu refuses une demande, pas quelqu'un. Le dire (ou le montrer) préserve la relation."},
{i:"o171_07",u:171,t:"match",d:.3,nw:"Les alternatives",q:"Associe chaque type d'alternative à son exemple.",p:[["Plus tard","« Pas ce soir, mais samedi oui »"],["Moins","« Je relis seulement l'introduction »"],["Autrement","« Je t'aide à faire ton budget »"],["Quelqu'un d'autre","« Demande à Léa, c'est son sujet »"]],w:"Plus tard, moins, autrement, quelqu'un d'autre, une ressource : cinq façons de dire oui à la personne sans dire oui à la demande."},
{i:"o171_08",u:171,t:"fill",d:.3,q:"Dans la ponctuation d'Ury, le dernier temps finit par un point d'___.",o:["interrogation","exclamation","suspension","ironie"],a:0,w:"« Oui ? » : une proposition, une invitation. On ne l'impose pas, on la soumet."},
{i:"o171_09",u:171,t:"story",d:.35,q:"Quel est ton « Oui ! » face à Lucas ?",sc:[{who:"Lucas",txt:"Soirée samedi, tu viens ?"},{who:"Toi",me:true,txt:"(tu as un semi-marathon dimanche matin, préparé depuis trois mois)"}],o:["Ta course de dimanche, que tu prépares depuis trois mois","L'envie de faire plaisir à Lucas pour ne pas le décevoir","La peur de rater une soirée dont tout le monde parlera","Le besoin de montrer que tu sais enfin dire non"],a:0,w:"Ton oui profond, c'est ce que tu protèges : ta course. Le dire rend ton non compréhensible : « Je cours dimanche, je veux être en forme, donc samedi je passe. On se fait un brunch la semaine prochaine ? »"},
{i:"o171_10",u:171,t:"multi",d:.35,q:"Quelles sont les trois étapes de préparation d'un non positif ?",o:["Trouver ton oui profond","Renforcer ton non avec un plan B","Respecter l'autre tout au long","Trouver une excuse imparable","Attendre que l'autre oublie"],a:[0,1,2],w:"Oui, Non, Respect. L'excuse imparable et l'oubli espéré sont des stratégies de fuite ou de manipulation."},
{i:"o171_11",u:171,t:"tf",d:.35,q:"Le plan B d'Ury ressemble à la MESORE de la négociation : ce que tu feras si l'autre n'accepte pas ton refus.",a:true,w:"Si Karim refuse ton départ à 18 h 30, ton plan B peut être de partir quand même en ayant prévenu, ou d'en parler aux RH si cela devient systématique. Le connaître te rend plus calme."},
{i:"o171_12",u:171,t:"story",d:.4,q:"Élodie veut que tu l'accompagnes à un mariage où tu ne connais personne. Quelle alternative choisis-tu ?",sc:[{who:"Élodie",txt:"Viens avec moi au mariage de ma cousine, je ne veux pas y aller seule !"}],o:["« Je ne viendrai pas au mariage, mais je t'aide à choisir ta tenue la veille, avec plaisir. »","« Oui, je viens, ça me fera plaisir, enfin sûrement, même si je ne connais personne. »","« Hors de question, c'est ton problème à toi, tu n'as qu'à y aller toute seule comme une grande. »","« Je viendrai peut-être, si je ne suis pas trop fatigué ce jour-là, on verra bien le moment venu. »"],a:0,w:"Non au mariage, oui à Élodie avec une aide que tu as vraiment envie de donner. C'est un oui qui passe le test E.C.R."},
{i:"o171_13",u:171,t:"mcq",d:.35,q:"Que représente le point d'exclamation dans « Oui ! Non. Oui ? » ?",o:["L'élan vers ce qui compte pour toi","L'agacement envers la demande","La surprise d'avoir été sollicité","L'enthousiasme de faire plaisir à l'autre"],a:0,w:"Le « Oui ! » est ton moteur : ce que tu protèges. C'est lui qui donne la force de dire non sans culpabilité."},
{i:"o171_14",u:171,t:"sort",d:.4,q:"Classe chaque alternative : passe le test E.C.R. ou oui subi déguisé ?",bins:["Passe le test","Oui subi déguisé"],it:[["Proposer un brunch dimanche, que tu as envie de faire",0],["Promettre de relire tout le dossier demain alors que tu n'en as aucune envie",1],["Envoyer un tutoriel utile, en deux minutes",0],["Proposer de payer la moitié du prêt pour te faire pardonner",1],["Indiquer une collègue experte du sujet",0]],w:"L'alternative doit être voulue et tenable. Sinon, tu remplaces un oui subi par un autre, juste différé."},
{i:"o171_15",u:171,t:"story",d:.4,q:"Karim n'accepte pas ton non positif. Que fais-tu ?",sc:[{who:"Karim",txt:"Non, j'ai besoin de toi ce soir, pas demain matin."}],o:["« Je comprends. Je ne peux pas ce soir. Qu'est-ce qui est vraiment urgent d'ici 18 h 30 ? »","« Bon, d'accord, je reste, je vais annuler ma formation, ce n'est pas grave. »","« Dans ce cas, je vais aller voir les RH immédiatement pour me plaindre de ton comportement. »","« Tu ne comprends jamais rien, je t'ai dit que je ne pouvais pas ce soir, point final ! »"],a:0,w:"On accueille, on maintient calmement, et on cherche ensemble le vrai besoin (qu'est-ce qui est urgent ?). Le plan B (RH) existe, mais on ne le brandit pas à la première résistance."},
{i:"o171_16",u:171,t:"fill",d:.4,q:"Un non positif est un non enraciné dans un ___ plus profond.",o:["oui","regret","doute","devoir"],a:0,w:"C'est le cœur de la méthode d'Ury. Trouver ce oui profond te donne l'énergie de dire non."},
{i:"o171_17",u:171,t:"story",d:.45,q:"Rappel du module 4 : quelle version de ton non positif est la plus claire ?",sc:[{who:"Mme Leblanc",txt:"Vous pourriez garder mon chat pendant trois semaines cet été ?"}],o:["« Je pars moi-même en août, donc je ne pourrai pas le garder. Je peux vous donner le contact de ma pet-sitter ? »","« Euh... trois semaines... je ne sais pas trop, il faudrait voir, peut-être une semaine, enfin... »","« Trois semaines ? Ce serait beaucoup trop, vous ne vous rendez pas compte de ce que vous demandez, franchement. »","« Oui, bien sûr, avec plaisir, je vais m'arranger d'une manière ou d'une autre pour mes propres vacances. »"],a:0,w:"Oui à tes vacances, non à la garde, oui à Mme Leblanc avec une solution concrète. Clair et chaleureux."},
{i:"o171_18",u:171,t:"tf",d:.45,q:"Expliquer ce qui compte pour toi (ton « Oui ! ») rend ton non plus facile à entendre.",a:true,w:"L'autre comprend que tu ne refuses pas contre lui mais pour quelque chose. C'est beaucoup moins vexant."},
{i:"o171_19",u:171,t:"num",d:.45,q:"Karim voulait que tu restes 2 h 30 ce soir. Tu proposes d'arriver 1 h 30 plus tôt demain. Combien de temps de travail supplémentaire donnes-tu, en heures ?",a:1.5,tol:.01,un:" h",h:"La durée proposée, pas celle demandée",w:"1,5 h au lieu de 2,5 h, et à l'heure qui te convient. Le « Oui ? » peut être plus petit que la demande : c'est une proposition, pas une compensation totale."},
{i:"o171_20",u:171,t:"match",d:.45,q:"Associe chaque ponctuation à son sens.",p:[["Oui !","Ce que je protège"],["Non.","Le refus, ferme et posé"],["Oui ?","Une proposition ouverte"],["Respect","Le fil qui tient tout l'échange"]],w:"! . ? : la ponctuation d'Ury. Et le respect de la personne du début à la fin."},
{i:"o171_21",u:171,t:"story",d:.5,q:"Tante Monique veut que tu passes tout le dimanche chez elle. Quel non positif choisis-tu ?",sc:[{who:"Tante Monique",txt:"Tu viens dimanche ? Tu resteras bien toute la journée, hein ?"}],o:["« J'ai besoin de mon après-midi pour souffler, donc je ne resterai pas la journée. Café à 11 h ? »","« Non, je ne viens pas, j'ai beaucoup trop de choses à faire ce week-end, vraiment désolé tatie. »","« Toute la journée ? Tu exagères toujours, tatie, tu sais bien que c'est impossible pour moi. »","« Oui, oui, bien sûr, je resterai toute la journée, comme d'habitude, avec plaisir. »"],a:0,w:"Oui à ton repos, non à la journée entière, oui à Monique avec un café à 11 h. Elle reçoit ta visite, tu gardes ton après-midi."},
{i:"o171_22",u:171,t:"multi",d:.5,q:"Quelles alternatives sont possibles face à Julie qui te demande de relire son dossier de 40 pages ce soir ?",o:["Relire seulement la synthèse","Relire le dossier jeudi matin","Lui envoyer ta checklist de relecture","Lui dire que Léa connaît mieux le sujet","Relire les 40 pages ce soir en soupirant"],a:[0,1,2,3],w:"Moins, plus tard, une ressource, quelqu'un d'autre. La dernière est le oui subi que tu cherches justement à éviter."},
{i:"o171_23",u:171,t:"slider",d:.5,q:"Sur les cinq familles d'alternatives (plus tard, moins, autrement, quelqu'un d'autre, ressource), combien en utilises-tu si tu dis « Je relis la synthèse jeudi » ?",min:0,max:5,step:1,a:2,tol:0,pre:"",un:"",w:"Deux : moins (la synthèse) et plus tard (jeudi). On peut combiner les familles pour ajuster l'aide exactement à ce que tu veux donner."},
{i:"o171_24",u:171,t:"story",d:.55,q:"Rappel du module 3 : quel rôle de Karpman évites-tu grâce au non positif ?",sc:[{who:"Élodie",txt:"Sans toi je n'y arriverai jamais, fais-le pour moi..."},{who:"Toi",me:true,txt:"Je ne vais pas l'écrire à ta place. Je relis ta lettre demain et je te donne mes conseils, d'accord ?"}],o:["Celui du Sauveur, qui fait à la place de l'autre","Celui de la Victime, qui se plaint d'être exploitée","Celui du Persécuteur, qui accuse et rabaisse","Aucun, ta réponse te place dans les trois rôles"],a:0,w:"Tu aides sans porter à sa place : Élodie reste responsable de sa lettre. C'est la sortie du triangle, et c'est aussi une marque de confiance en elle."},
{i:"o171_25",u:171,t:"tiles",d:.55,q:"Reconstitue la ponctuation d'Ury.",a:["Oui","!","Non",".","Oui","?"],dd:["Peut-être","...","Désolé"],w:"Trois temps, trois ponctuations. Le « peut-être » et les points de suspension sont justement ce qu'on évite."},
{i:"o171_26",u:171,t:"tf",d:.55,q:"Proposer une alternative par culpabilité, sans avoir envie de la tenir, reste un oui subi.",a:true,w:"Le « Oui ? » doit passer le test E.C.R. comme tout autre oui. Sinon, tu déplaces simplement le problème."},
{i:"o171_27",u:171,t:"story",d:.6,q:"Camille veut aller chez ses parents tous les week-ends. Quel non positif protège aussi votre couple ?",sc:[{who:"Camille",txt:"On va chez mes parents ce week-end ? Et le suivant aussi ?"}],o:["« J'ai besoin de week-ends à nous deux, donc pas tous les week-ends. Un sur deux, ça t'irait ? »","« Tes parents, encore ? Franchement, j'en ai vraiment marre de passer toute ma vie chez eux. »","« Oui, comme tu veux, ça m'est égal, de toute façon je n'ai jamais rien de prévu le week-end. »","« Je viendrai si tu insistes, mais je ne serai pas de très bonne humeur, je te préviens. »"],a:0,w:"Ton besoin (du temps à deux), ta limite (pas tous les week-ends), une proposition (un sur deux). Dans le couple, le non positif ouvre une négociation au lieu d'une dispute."},
{i:"o171_28",u:171,t:"mcq",d:.6,q:"Rappel du module 2 : pourquoi le « Oui ! » n'est-il pas une justification obligatoire ?",o:["Tu as le droit de ne pas donner de raisons","Il faut toujours cacher ses vraies raisons","Les autres n'écoutent jamais les raisons","Une raison rend toujours le non plus faible"],a:0,w:"Partager ton « Oui ! » est un choix qui aide la relation. Ce n'est jamais une dette à payer pour avoir le droit de refuser."},
{i:"o171_29",u:171,t:"sort",d:.6,q:"Classe chaque réponse à Lucas : non positif complet, ou incomplet ?",bins:["Non positif complet","Incomplet"],it:[["« Je cours dimanche, donc samedi je passe. Brunch la semaine prochaine ? »",0],["« Samedi je passe. »",1],["« Je cours dimanche. »",1],["« J'ai envie d'être en forme dimanche, je ne viens pas. On se voit mardi ? »",0]],w:"Complet : oui, non, proposition. Incomplet ne veut pas dire mauvais : « Samedi je passe » est un non clair et suffisant. Le non positif complet est juste plus chaleureux."},
{i:"o171_30",u:171,t:"fill",d:.6,q:"Pour Ury, le troisième temps dit oui à la ___.",o:["relation","demande","culpabilité","dispute"],a:0,w:"Non à la demande, oui à la relation. C'est ce qui rend son non « positif »."},
{i:"o171_31",u:171,t:"story",d:.65,q:"Hélène te félicite. Que retiens-tu de ta réussite avec Karim ?",sc:[{who:"Hélène Marchal",txt:"Il a accepté, et il a même trouvé votre solution meilleure. Qu'est-ce que ça vous apprend ?"}],o:["« Qu'un non bien construit peut servir les deux, et que ma peur exagérait le risque. »","« Que Karim était simplement de bonne humeur ce jour-là, j'ai eu beaucoup de chance. »","« Que je peux désormais dire non à tout, puisque tout le monde finit par accepter. »","« Que je devrais toujours proposer plus que ce qu'on me demande, pour être sûr. »"],a:0,w:"Une expérience réussie corrige la peur (souviens-toi de Givi et Kirk). Et ce n'est pas de la chance : c'est de la préparation. Chaque succès rend le suivant plus facile."},
{i:"o171_32",u:171,t:"multi",d:.65,q:"Qu'est-ce qui rend un non « positif » selon Ury ?",o:["Il protège quelque chose qui compte pour toi","Il reste ferme sur la demande","Il respecte la personne","Il ne déçoit jamais personne","Il est toujours accompagné d'un cadeau"],a:[0,1,2],w:"Un non positif peut décevoir, et c'est normal. Il reste respectueux, ferme et enraciné dans ton oui profond."}
