/*UNIT*/
{id:172,c:"NON",n:"Module 6",t:"Poser une limite qui dure : DESC et communication non violente",col:"--pink",ic:"🕊️",guide:`
<h3>La conversation que tu repoussais depuis trois mois</h3>
<div class="gstory">Depuis trois mois, Julie te transfère ses dossiers « urgents » le vendredi à 17 h. Tu as dit oui huit fois. Un non ponctuel ne suffit plus : il faut poser une limite qui dure, et donc avoir <i>la</i> conversation. Hélène te donne une structure : « Vous allez parler de faits, pas de Julie. De vous, pas d'elle. Et vous finirez par une demande précise. » Lundi matin, au calme, autour d'un café, tu te lances. Ça dure quatre minutes. Julie rougit, puis dit : « Je ne m'en rendais pas compte. » Depuis, plus aucun dossier le vendredi à 17 h.</div>
<h3>La méthode DESC</h3>
<p>Créée par <b>Sharon et Gordon Bower</b> (<i>Asserting Yourself</i>, 1976), elle sert à exprimer un désaccord ou à poser une limite durable.</p>
<table><tr><th>Lettre</th><th>Ce que tu fais</th><th>Avec Julie</th></tr>
<tr><td><b>D</b>écrire</td><td>Les faits, objectivement, sans jugement</td><td>« Ces trois derniers mois, tu m'as transmis huit dossiers le vendredi après 17 h. »</td></tr>
<tr><td><b>E</b>xprimer</td><td>Ce que tu ressens, en « je »</td><td>« Je me sens sous pression et j'arrive épuisé le week-end. »</td></tr>
<tr><td><b>S</b>pécifier</td><td>Ce que tu demandes, précis et réaliste</td><td>« J'aimerais qu'on se cale le jeudi à 14 h pour voir ce qui doit être relu. »</td></tr>
<tr><td><b>C</b>onséquences</td><td>Ce que ça apportera (ou ce que tu feras sinon)</td><td>« Comme ça, je relirai plus sereinement, et tes dossiers seront mieux faits. »</td></tr></table>
<div class="gmnemo"><b>DESC comme un bureau : on pose les faits DESSUS.</b> <b>D</b>es faits, <b>E</b>n « je », une <b>S</b>olution précise, des <b>C</b>onséquences positives. Et l'image : tu poses le problème sur le bureau entre vous deux, tu ne le jettes pas au visage de l'autre.</div>
<h3>La communication non violente (CNV)</h3>
<p>Créée par <b>Marshall Rosenberg</b> (livre en français : <i>Les mots sont des fenêtres (ou bien ce sont des murs)</i>), elle suit quatre étapes proches : <b>O</b>bservation, <b>S</b>entiment, <b>B</b>esoin, <b>D</b>emande (OSBD).</p>
<table><tr><th>Étape</th><th>Bon exemple</th><th>Piège</th></tr>
<tr><td>Observation</td><td>« Tu es arrivé à 20 h 30 trois fois cette semaine »</td><td>Une évaluation : « tu es toujours en retard »</td></tr>
<tr><td>Sentiment</td><td>« Je me sens triste, inquiet, agacé »</td><td>Un faux sentiment qui accuse : « je me sens manipulé, trahi, ignoré »</td></tr>
<tr><td>Besoin</td><td>« J'ai besoin de fiabilité, de repos, de considération »</td><td>Une stratégie déguisée : « j'ai besoin que tu arrêtes »</td></tr>
<tr><td>Demande</td><td>« Serais-tu d'accord pour me prévenir avant 19 h ? »</td><td>Une exigence : « tu dois me prévenir »</td></tr></table>
<p>La différence entre une <b>demande</b> et une <b>exigence</b> : une demande accepte un refus. Si tu punis l'autre quand il dit non, c'était une exigence.</p>
<div class="gtrap">Trois pièges classiques. Un : les mots « toujours » et « jamais », qui transforment un fait en procès (« tu me refiles toujours tout »). Deux : le « je » qui cache un « tu » (« je trouve que tu es égoïste » reste une accusation). Trois : choisir le mauvais moment. Une limite importante se pose au calme, en privé, jamais à chaud ni devant les autres.</div>
<h3>DESC ou CNV ?</h3>
<p>Les deux se ressemblent. DESC est plus directe et orientée solution (idéale au travail). La CNV met davantage l'accent sur les besoins (idéale dans les relations proches). Dans les deux cas : des faits, du « je », une demande précise.</p>
<h3>Ce que tu dois savoir faire à la fin de ce module</h3>
<ul><li>Construire un message DESC complet</li><li>Transformer une évaluation en observation</li><li>Distinguer un vrai sentiment d'un faux sentiment accusateur</li><li>Transformer une exigence en demande</li><li>Choisir le bon moment pour poser une limite durable</li></ul>`},
/*EXOS*/
{i:"o172_01",u:172,t:"order",d:.2,nw:"La méthode DESC",q:"Remets dans l'ordre les quatre étapes de la méthode DESC.",it:["Décrire les faits","Exprimer ce que tu ressens","Spécifier ta demande","Conséquences positives"],w:"Des faits, En « je », une Solution précise, des Conséquences positives. On pose le problème sur le bureau, on ne le jette pas au visage."},
{i:"o172_02",u:172,t:"sort",d:.25,q:"Classe chaque morceau du message à Julie dans la bonne lettre DESC.",bins:["D","E","S","C"],it:[["« Tu m'as transmis huit dossiers le vendredi après 17 h »",0],["« Je me sens sous pression »",1],["« J'aimerais qu'on se cale le jeudi à 14 h »",2],["« Tes dossiers seront mieux relus »",3]],w:"Décrire, Exprimer, Spécifier, Conséquences. Quatre minutes suffisent pour une conversation qui change des mois de frustration."},
{i:"o172_03",u:172,t:"story",d:.25,q:"Quelle phrase décrit un fait sans jugement ?",sc:[{who:"Toi (brouillon)",txt:"Julie, il faut qu'on parle de..."}],o:["« ...des huit dossiers reçus le vendredi après 17 h depuis juin. »","« ...ta façon de toujours me refiler ton travail en fin de semaine. »","« ...ton manque total d'organisation qui retombe sur les autres. »","« ...ton égoïsme, parce que franchement, ça ne peut plus durer. »"],a:0,w:"Un fait se vérifie (huit dossiers, vendredi, 17 h). « Toujours », « manque d'organisation », « égoïsme » sont des jugements : Julie se défendra au lieu d'écouter."},
{i:"o172_04",u:172,t:"mcq",d:.3,q:"Qui a créé la méthode DESC ?",o:["Sharon et Gordon Bower","Marshall B. Rosenberg","William Ury et Roger Fisher","Dominique Chalvin"],a:0,w:"Sharon et Gordon Bower, Asserting Yourself (1976). Rosenberg a créé la communication non violente."},
{i:"o172_05",u:172,t:"tf",d:.25,q:"« Je trouve que tu es égoïste » est un message en « je » correct.",a:false,w:"C'est un « tu » déguisé : le jugement porte sur Julie. Le vrai message en « je » parle de ton ressenti : « je me sens sous pression »."},
{i:"o172_06",u:172,t:"match",d:.3,nw:"La communication non violente",q:"Associe chaque étape de la CNV à son exemple.",p:[["Observation","« Tu es arrivé à 20 h 30 trois fois cette semaine »"],["Sentiment","« Je me sens inquiet »"],["Besoin","« J'ai besoin de fiabilité »"],["Demande","« Serais-tu d'accord pour me prévenir avant 19 h ? »"]],w:"OSBD : Observation, Sentiment, Besoin, Demande. Marshall Rosenberg."},
{i:"o172_07",u:172,t:"fill",d:.3,q:"Une demande accepte un refus ; sinon, c'est une ___.",o:["exigence","prière","question","suggestion"],a:0,w:"Si tu punis l'autre quand il dit non, ta demande était une exigence. Le vrai test d'une demande, c'est ta réaction au refus."},
{i:"o172_08",u:172,t:"sort",d:.3,q:"Classe chaque phrase : observation ou évaluation ?",bins:["Observation","Évaluation"],it:[["« Tu as laissé la vaisselle trois soirs de suite »",0],["« Tu ne fais jamais rien à la maison »",1],["« Tu m'as appelé à 23 h mardi et jeudi »",0],["« Tu es sans gêne »",1],["« Tu n'as pas rendu les 200 € prêtés en mars »",0],["« Tu es radine »",1]],w:"L'observation se filme ; l'évaluation se discute. Commencer par une observation évite que l'autre passe en défense."},
{i:"o172_09",u:172,t:"story",d:.35,q:"Tu veux parler à Camille de la vaisselle. Quelle ouverture choisis-tu ?",sc:[{who:"Camille",txt:"Tu voulais me parler ?"}],o:["« J'ai fait la vaisselle tous les soirs cette semaine. Je suis fatigué ; on alterne ? »","« Tu ne fais jamais la vaisselle, c'est toujours moi qui fais tout dans cette maison. »","« Je trouve que tu es un peu égoïste avec les tâches, tu ne penses qu'à toi en fait. »","« Rien, rien, laisse tomber, ce n'est pas grave du tout, je m'en occupe comme d'habitude. »"],a:0,w:"Fait, ressenti, demande : c'est DESC en une phrase. Les « jamais » et « égoïste » déclenchent la dispute, et le « laisse tomber » est une fuite qui prépare l'explosion."},
{i:"o172_10",u:172,t:"multi",d:.35,q:"Quels sont des faux sentiments qui accusent l'autre ?",o:["« Je me sens manipulé »","« Je me sens trahi »","« Je me sens ignoré »","« Je me sens triste »","« Je me sens inquiet »"],a:[0,1,2],w:"Manipulé, trahi, ignoré : ce sont des interprétations de ce que l'autre t'a fait. Triste, inquiet : ce sont de vrais sentiments, qui ne mettent personne en accusation."},
{i:"o172_11",u:172,t:"tiles",d:.35,q:"Reconstitue la règle du DESC.",a:["Je","parle","de","faits","pas","de","la","personne"],dd:["toujours","jamais","coupable"],w:"On critique un comportement, jamais une personne. C'est ce qui permet à l'autre de changer sans perdre la face."},
{i:"o172_12",u:172,t:"tf",d:.35,q:"Il vaut mieux poser une limite importante à chaud, au moment où la situation se produit.",a:false,w:"Pour une limite ponctuelle, on peut répondre sur le moment. Pour une limite durable, on choisit un moment calme et privé : à chaud, l'émotion transforme la limite en dispute."},
{i:"o172_13",u:172,t:"story",d:.4,q:"Quelle est la meilleure étape « Spécifier » pour Sophie ?",ctx:"Sophie ne t'a pas rendu les 200 € prêtés en mars. Tu as décrit les faits et exprimé ton malaise.",sc:[{who:"Sophie",txt:"Oui bon, je sais, je vais te les rendre, un jour..."}],o:["« J'aimerais qu'on fixe un remboursement : 50 € par mois dès le 5 octobre ? »","« J'aimerais que tu sois plus responsable avec l'argent en général, ça t'aiderait vraiment. »","« Je voudrais que tu fasses un effort, tu vois ce que je veux dire, enfin fais au mieux. »","« Tu dois me rembourser tout, tout de suite, sinon je le dis à papa et maman. »"],a:0,w:"Spécifier, c'est une demande précise, réaliste et datée. « Plus responsable » et « un effort » sont flous ; la menace transforme la demande en exigence."},
{i:"o172_14",u:172,t:"mcq",d:.4,q:"Quel est le livre de Marshall Rosenberg sur la CNV en français ?",o:["Les mots sont des fenêtres (ou bien ce sont des murs)","Quand je dis non, je me sens coupable (Manuel J. Smith)","Le pouvoir d'un non positif, de William Ury","Petit traité de manipulation à l'usage des honnêtes gens"],a:0,w:"Rosenberg, Les mots sont des fenêtres. Smith a écrit Quand je dis non, je me sens coupable ; Ury Le pouvoir d'un non positif ; Joule et Beauvois le Petit traité de manipulation (module 9)."},
{i:"o172_15",u:172,t:"sort",d:.4,q:"Classe chaque phrase : demande ou exigence ?",bins:["Demande","Exigence"],it:[["« Serais-tu d'accord pour baisser la musique après 23 h ? »",0],["« Tu dois baisser la musique, point. »",1],["« Est-ce qu'on peut se caler le jeudi à 14 h ? »",0],["« Tu arrêtes ça, sinon tu vas voir. »",1],["« Accepterais-tu de me rembourser 50 € par mois ? »",0]],w:"La demande est précise, positive, et accepte un refus (qu'on négociera). L'exigence menace ou ferme la discussion."},
{i:"o172_16",u:172,t:"story",d:.4,q:"Nathan, ton colocataire, met de la musique fort tous les soirs jusqu'à 1 h. Quel message DESC choisis-tu ?",sc:[{who:"Nathan",txt:"Ça va ? T'as l'air fatigué."}],o:["« Quatre soirs cette semaine, musique jusqu'à 1 h : je dors mal. On baisse après 23 h ? »","« Tu es vraiment sans gêne avec ta musique, tu ne penses jamais aux autres, ça devient franchement insupportable. »","« Non non, ça va, juste un peu fatigué, rien de grave, ne t'en fais pas pour moi, vraiment. »","« Je vais porter plainte pour tapage nocturne si tu continues comme ça, je te préviens. »"],a:0,w:"Faits, ressenti, demande précise, conséquence positive pour les deux. L'attaque, la fuite et la menace sautent directement à l'escalade ou à l'évitement."},
{i:"o172_17",u:172,t:"fill",d:.4,q:"Dans la CNV, « tu es toujours en retard » est une ___ et non une observation.",o:["évaluation","demande","émotion","observation datée"],a:0,w:"« Toujours » généralise et juge. L'observation serait : « tu es arrivé à 20 h 30 trois fois cette semaine »."},
{i:"o172_18",u:172,t:"multi",d:.45,q:"Quels mots transforment facilement un fait en procès ?",o:["Toujours","Jamais","À chaque fois","Mardi dernier","Trois fois cette semaine"],a:[0,1,2],w:"Les généralisations invitent l'autre à chercher le contre-exemple (« c'est faux, lundi je l'ai fait ! »). Les faits datés, eux, sont incontestables."},
{i:"o172_19",u:172,t:"story",d:.45,q:"Rappel du module 5 : Julie refuse ta demande de point le jeudi. Que fais-tu ?",sc:[{who:"Julie",txt:"Le jeudi, je ne peux pas, j'ai mon point client."}],o:["« D'accord. Quel créneau en début de semaine te conviendrait ? »","« Tant pis alors, je reprendrai tes dossiers le vendredi comme avant. »","« Tu refuses tout ce que je propose, tu es vraiment de mauvaise foi. »","« Très bien, alors débrouille-toi seule avec tes dossiers désormais. »"],a:0,w:"Une demande accepte un refus et cherche une autre voie. Revenir à l'ancien fonctionnement serait une fuite ; accuser ou couper les ponts, une attaque."},
{i:"o172_20",u:172,t:"match",d:.45,q:"Associe chaque piège à sa correction.",p:[["« Tu es toujours en retard »","« Tu es arrivé à 20 h 30 trois fois »"],["« Je me sens trahi »","« Je me sens triste et déçu »"],["« Tu dois me prévenir »","« Serais-tu d'accord pour me prévenir ? »"],["« Je trouve que tu es égoïste »","« J'ai besoin de plus d'aide à la maison »"]],w:"Évaluation, faux sentiment, exigence, jugement déguisé : quatre pièges, quatre corrections. C'est une gymnastique qui devient naturelle avec l'entraînement."},
{i:"o172_21",u:172,t:"slider",d:.45,q:"Combien de minutes a duré ta conversation DESC avec Julie ?",min:1,max:60,step:1,a:4,tol:1,pre:"",un:" min",w:"Quatre minutes. La conversation redoutée pendant des mois est souvent très courte quand elle est bien structurée. La peur est bien plus longue que la réalité."},
{i:"o172_22",u:172,t:"tf",d:.5,q:"DESC est plutôt orientée solution, la CNV met davantage l'accent sur les besoins.",a:true,w:"DESC convient très bien au travail ; la CNV aux relations proches. Mais les deux reposent sur la même base : faits, « je », demande précise."},
{i:"o172_23",u:172,t:"story",d:.5,q:"Karim t'a critiqué devant toute l'équipe. Que fais-tu ?",sc:[{who:"Karim",txt:"(en réunion) Et là, bien sûr, ton slide est encore raté."}],o:["Je lui demande un point en privé plus tard, et j'utilise DESC au calme","Je lui réponds devant tout le monde que ses slides à lui sont pires","Je ne dis rien, ni maintenant ni plus tard, et je rumine en silence chez moi","Je quitte la réunion en claquant la porte pour marquer le coup"],a:0,w:"En public et à chaud, on ne pose pas une limite durable. En privé et au calme : « Mardi en réunion, tu as dit que mon slide était encore raté. Je me suis senti humilié. J'aimerais que les critiques se fassent en tête-à-tête. »"},
{i:"o172_24",u:172,t:"fill",d:.5,q:"Dans DESC, la dernière étape présente les ___ positives du changement.",o:["conséquences","excuses","menaces","justifications"],a:0,w:"Montrer ce que chacun y gagne motive l'autre. On peut aussi, si nécessaire, dire calmement ce que tu feras sinon, sans menacer."},
{i:"o172_25",u:172,t:"story",d:.55,q:"Rappel du module 4 : ton message DESC à Nathan est bon, mais ton corps dit autre chose. Que corriges-tu ?",sc:[{who:"Hélène Marchal",txt:"Vous avez dit tout ça en regardant votre téléphone et en riant nerveusement."}],o:["Regarder Nathan, voix posée, visage neutre et bienveillant","Parler plus fort pour montrer que c'est vraiment sérieux cette fois","Lui envoyer le message par écrit pour éviter de le regarder","Ajouter des excuses pour compenser le rire nerveux"],a:0,w:"Les 4C valent aussi pour une limite durable : calme et clair, avec un corps aligné. Sinon, Nathan croira le rire, pas les mots."},
{i:"o172_26",u:172,t:"sort",d:.55,q:"Classe chaque sentiment : vrai sentiment ou faux sentiment accusateur ?",bins:["Vrai sentiment","Faux sentiment"],it:[["Fatigué",0],["Abandonné",1],["Agacé",0],["Méprisé",1],["Inquiet",0],["Exploité",1]],w:"Abandonné, méprisé, exploité décrivent ce que l'autre t'aurait fait. Fatigué, agacé, inquiet décrivent ce qui se passe en toi. Les seconds ouvrent le dialogue."},
{i:"o172_27",u:172,t:"mcq",d:.55,q:"Pourquoi critiquer le comportement plutôt que la personne ?",o:["L'autre peut changer un comportement sans perdre la face","Une personne ne peut jamais changer son comportement","Critiquer la personne est interdit par la loi française","Le comportement n'a aucune importance au fond"],a:0,w:"« Tu es désorganisée » attaque son identité ; « huit dossiers le vendredi à 17 h » vise un geste modifiable. On change plus volontiers un geste qu'une identité."},
{i:"o172_28",u:172,t:"story",d:.6,q:"Élodie t'appelle chaque soir pendant une heure. Quel message CNV choisis-tu ?",sc:[{who:"Élodie",txt:"Coucou ! Tu as une heure ? J'ai plein de trucs à te raconter !"}],o:["« On s'est appelés une heure chaque soir. Je suis épuisé, j'ai besoin de repos : deux soirs par semaine, ça t'irait ? »","« Tu m'appelles tout le temps, tu ne te rends pas du tout compte à quel point tu es envahissante, franchement, ça devient lourd. »","« Oui, bien sûr, je t'écoute, raconte-moi tout, j'ai tout mon temps ce soir encore, vas-y. »","« Je me sens complètement envahi et manipulé par tous tes appels du soir, tu dois arrêter maintenant, c'est clair ? »"],a:0,w:"Observation, sentiment, besoin, demande. La dernière réponse ressemble à de la CNV mais contient un faux sentiment (manipulé) et une exigence (tu dois)."},
{i:"o172_29",u:172,t:"tiles",d:.6,q:"Reconstitue les quatre étapes de la CNV.",a:["Observation","sentiment","besoin","demande"],dd:["jugement","exigence","reproche"],w:"OSBD. Jugement, exigence et reproche sont précisément ce que la CNV remplace."},
{i:"o172_30",u:172,t:"tf",d:.6,q:"On peut ajouter dans l'étape C ce que l'on fera si rien ne change, à condition de le dire calmement et de le tenir.",a:true,w:"« Si les dossiers continuent d'arriver le vendredi à 17 h, je les traiterai le lundi. » Ce n'est pas une menace : c'est l'annonce de ta limite. L'important est de la tenir."},
{i:"o172_31",u:172,t:"order",d:.65,q:"Remets dans l'ordre la préparation de la conversation avec Julie.",it:["Noter les faits précis et datés","Nommer ton ressenti","Formuler une demande précise","Prévoir les conséquences positives","Choisir un moment calme et privé"],w:"Préparer DESC par écrit, puis choisir le moment. Une limite durable se prépare comme une négociation."},
{i:"o172_32",u:172,t:"multi",d:.65,q:"Qu'est-ce qui rend une demande efficace ?",o:["Elle est précise","Elle est réaliste","Elle est formulée positivement","Elle accepte un refus","Elle est accompagnée d'une menace"],a:[0,1,2,3],w:"« J'aimerais qu'on se cale le jeudi à 14 h » plutôt que « arrête de me refiler tes dossiers ». Positive, précise, réaliste, et ouverte à la discussion."}
