/*UNIT*/
{id:173,c:"NON",n:"Module 7",t:"Tenir bon quand l'autre insiste : disque rayé, brouillard et compagnie",col:"--pink",ic:"🪨",guide:`
<h3>Lucas, champion de l'insistance</h3>
<div class="gstory">Samedi soir, il est 1 h. Tu as dit à Lucas que tu rentrais. Il insiste : « Allez, un dernier ! » Tu redis non. « T'es pas drôle ce soir. » « Tu nous fais une crise de vieux ? » « C'est moi qui paie ! » « Tu vas le regretter, il y a Inès qui arrive ! » Chaque phrase est une nouvelle porte. Avant, tu en aurais franchi une. Ce soir, tu as un outil : tu répètes, calmement, la même phrase. Au quatrième « je rentre, bonne soirée ! », Lucas éclate de rire : « Ok, ok, file ! » Tu es chez toi à 1 h 20.</div>
<h3>Les techniques de Manuel J. Smith</h3>
<p>Dans <i>Quand je dis non, je me sens coupable</i> (1975), Smith décrit des techniques pour <b>tenir</b> un non face à l'insistance, la critique ou la culpabilisation.</p>
<table><tr><th>Technique</th><th>Principe</th><th>Exemple</th></tr>
<tr><td><b>Disque rayé</b></td><td>Répéter calmement la même phrase, sans nouvelle justification</td><td>« Je comprends. Je rentre. » (et encore) « Je comprends. Je rentre. »</td></tr>
<tr><td><b>Brouillard</b> (ou édredon)</td><td>Reconnaître la part de vrai d'une critique, sans changer d'avis</td><td>« C'est possible que je sois moins drôle ce soir. Je rentre quand même. »</td></tr>
<tr><td><b>Assertion négative</b></td><td>Reconnaître calmement une vraie erreur, sans se flageller</td><td>« Oui, j'ai oublié ton anniversaire. C'est une erreur. »</td></tr>
<tr><td><b>Enquête négative</b></td><td>Demander des précisions sur une critique floue</td><td>« Qu'est-ce qui te déplaît exactement dans ma façon de faire ? »</td></tr>
<tr><td><b>Compromis réaliste</b></td><td>Proposer un accord sans renoncer à l'essentiel</td><td>« Je ne reste pas, mais je vous rejoins au brunch demain. »</td></tr></table>
<div class="gmnemo"><b>D.B.A.E.C. : « Dis-le, Bouge pas, Admets, Enquête, Coupe la poire intelligemment ».</b> Disque rayé (dis-le encore), Brouillard (bouge pas sous la critique), Assertion négative (admets l'erreur réelle), Enquête négative (demande ce qui cloche), Compromis réaliste. Et l'image du <b>brouillard</b> : les critiques entrent dedans et s'y perdent, sans jamais cogner contre un mur.</div>
<h3>Le disque rayé : pourquoi ça marche</h3>
<p>Chaque nouvelle justification donne à l'autre un nouvel argument à contrer. En répétant la <b>même</b> phrase, tu ne donnes aucune prise. L'autre comprend, au bout de trois ou quatre fois, que la discussion est close. L'astuce : commencer par une petite reconnaissance (« je comprends », « je sais ») pour que la répétition reste chaleureuse.</p>
<h3>Le brouillard : ne pas se défendre</h3>
<p>Face à « tu es égoïste », la réaction réflexe est de se défendre (« c'est faux ! j'ai fait ceci, cela ! »), ce qui ouvre un débat sans fin. Le brouillard consiste à reconnaître ce qui peut être vrai (« c'est possible que tu le voies comme ça »), <b>sans changer de décision</b>. Il n'y a plus de combat : la critique n'a rien sur quoi rebondir.</p>
<div class="gtrap">Le brouillard n'est pas de la soumission : on reconnaît une <b>possibilité</b>, pas une culpabilité, et on maintient sa décision. L'assertion négative ne concerne que les <b>vraies</b> erreurs : on ne s'accuse pas de fautes qu'on n'a pas commises. Et le disque rayé n'est pas un robot : on garde un ton chaleureux, on peut varier un mot, mais on ne rajoute pas de raison nouvelle.</div>
<h3>Ce que tu dois savoir faire à la fin de ce module</h3>
<ul><li>Utiliser le disque rayé face à une insistance</li><li>Répondre à une critique par le brouillard</li><li>Reconnaître une vraie erreur sans te flageller</li><li>Transformer une critique floue en information précise</li><li>Trouver un compromis réaliste</li></ul>`},
/*EXOS*/
{i:"o173_01",u:173,t:"match",d:.2,nw:"Les techniques de Smith",q:"Associe chaque technique à son principe.",p:[["Disque rayé","Répéter la même phrase sans nouvelle raison"],["Brouillard","Reconnaître la part de vrai sans changer d'avis"],["Assertion négative","Admettre une vraie erreur sans se flageller"],["Enquête négative","Demander des précisions sur une critique floue"]],w:"Quatre outils de Manuel J. Smith, plus le compromis réaliste. Ils te permettent de tenir ton non sans devenir dur."},
{i:"o173_02",u:173,t:"story",d:.25,q:"Lucas insiste pour la troisième fois. Que fais-tu (disque rayé) ?",sc:[{who:"Lucas",txt:"Allez, c'est moi qui paie le dernier verre !"}],o:["« C'est gentil. Je rentre, bonne soirée ! »","« Non mais même si tu paies, j'ai vraiment un truc demain matin tôt, tu sais bien. »","« Bon, si c'est toi qui paies, alors d'accord, juste un tout petit. »","« Arrête d'insister, Lucas, tu deviens vraiment lourd ce soir ! »"],a:0,w:"Même phrase, même calme, aucune nouvelle raison. Au bout de trois ou quatre fois, l'insistance s'éteint d'elle-même."},
{i:"o173_03",u:173,t:"tf",d:.25,q:"Dans le disque rayé, on ajoute une nouvelle justification à chaque répétition.",a:false,w:"C'est justement ce qu'on évite : chaque justification est un nouvel argument à contrer. La force du disque rayé, c'est la répétition sans prise."},
{i:"o173_04",u:173,t:"story",d:.3,q:"Tante Monique te traite d'ingrat. Quelle réponse est un brouillard ?",sc:[{who:"Tante Monique",txt:"Tu ne viens pas dimanche ? Tu es un ingrat, voilà ce que tu es."}],o:["« C'est possible que tu le voies comme ça, tatie. Je ne viendrai pas ce dimanche. »","« Moi, ingrat ? Je t'ai appelé trois fois ce mois-ci, et je suis venu à Pâques ! »","« Tu as raison, je suis ingrat, pardon, je vais venir dimanche finalement. »","« C'est toi qui es ingrate, tu ne me remercies jamais de rien, jamais. »"],a:0,w:"Brouillard : on reconnaît la possibilité, sans se défendre ni céder. La deuxième réponse ouvre un débat sans fin, la troisième cède, la quatrième attaque."},
{i:"o173_05",u:173,t:"mcq",d:.3,q:"Dans quel livre Manuel J. Smith décrit-il le disque rayé et le brouillard ?",o:["Quand je dis non, je me sens coupable","Les mots sont des fenêtres","Influence et manipulation","Le pouvoir d'un non positif"],a:0,w:"When I Say No, I Feel Guilty (1975). Cialdini a écrit Influence, Rosenberg Les mots sont des fenêtres, Ury Le pouvoir d'un non positif."},
{i:"o173_06",u:173,t:"sort",d:.3,q:"Classe chaque réponse selon la technique utilisée.",bins:["Disque rayé","Brouillard","Assertion négative","Enquête négative"],it:[["« Je comprends. Je rentre. »",0],["« C'est possible que je sois moins drôle ce soir. »",1],["« Oui, j'ai oublié de te rappeler. C'est une erreur. »",2],["« Qu'est-ce qui te déplaît exactement ? »",3]],w:"Répéter, reconnaître une possibilité, admettre une vraie erreur, demander des précisions : quatre outils, quatre situations."},
{i:"o173_07",u:173,t:"fill",d:.3,q:"Le brouillard reconnaît une possibilité, mais ne change pas la ___.",o:["décision","relation","conversation","vérité"],a:0,w:"C'est ce qui le distingue de la soumission : tu restes sur ta décision. La critique se perd dans le brouillard, sans rien percuter."},
{i:"o173_08",u:173,t:"story",d:.35,q:"Tu as réellement oublié l'anniversaire d'Élodie. Quelle réponse est une assertion négative ?",sc:[{who:"Élodie",txt:"Tu as oublié mon anniversaire. Franchement, ça m'a fait de la peine."}],o:["« Oui, j'ai oublié, c'est une erreur. Je suis désolé de t'avoir fait de la peine. »","« Je suis nul, le pire ami du monde, je ne mérite pas ton amitié, pardon pardon. »","« Oui, mais toi aussi tu avais oublié le mien il y a deux ans, je te rappelle. »","« Je n'ai pas oublié, j'étais juste débordé par le travail, ce n'est pas pareil. »"],a:0,w:"On admet l'erreur réelle, calmement, sans se flageller ni contre-attaquer. Admettre une erreur n'enlève rien à ta valeur."},
{i:"o173_09",u:173,t:"multi",d:.35,q:"Qu'est-ce qui rend le disque rayé efficace ?",o:["La même phrase répétée","Un ton calme et chaleureux","Aucune nouvelle justification","Une voix de plus en plus forte","Une nouvelle excuse à chaque fois"],a:[0,1,2],w:"Répétition, calme, pas de prise. Monter le ton transforme le disque rayé en dispute ; les excuses rouvrent la négociation."},
{i:"o173_10",u:173,t:"tiles",d:.35,q:"Reconstitue une phrase de disque rayé.",a:["Je","comprends","je","rentre","bonne","soirée"],dd:["peut-être","désolé","parce"],w:"Une petite reconnaissance, la décision, une sortie chaleureuse. Et on recommence tant qu'il le faut."},
{i:"o173_11",u:173,t:"story",d:.4,q:"Karim te dit que ton travail « n'est pas top ». Quelle réponse est une enquête négative ?",sc:[{who:"Karim",txt:"Ton rapport, franchement, c'est pas top."}],o:["« Qu'est-ce qui ne va pas précisément, pour que je puisse l'améliorer ? »","« Pas top ? J'ai passé tout mon week-end dessus, c'est injuste de dire ça. »","« Tu as raison, je suis vraiment mauvais pour ce genre de rapport. »","« Et toi, ton dernier rapport, tu crois qu'il était top peut-être ? »"],a:0,w:"L'enquête négative transforme une critique floue en information utile. Si la critique est fondée, tu apprends ; si elle ne l'est pas, elle se dégonfle."},
{i:"o173_12",u:173,t:"tf",d:.35,q:"Le brouillard est une forme de soumission.",a:false,w:"Le brouillard reconnaît une possibilité (« c'est possible »), pas une faute, et maintient la décision. Se soumettre, ce serait changer d'avis pour éviter le conflit."},
{i:"o173_13",u:173,t:"order",d:.4,q:"Remets dans l'ordre l'échange avec Lucas.",it:["Tu annonces que tu rentres","Lucas insiste avec un nouvel argument","Tu répètes calmement la même phrase","Lucas insiste encore","Tu répètes, il finit par accepter"],w:"Le disque rayé fonctionne en quelques tours. Chaque répétition calme fait comprendre à l'autre que la décision est prise."},
{i:"o173_14",u:173,t:"slider",d:.4,q:"Au bout de combien de répétitions calmes Lucas a-t-il accepté ton départ ?",min:1,max:10,step:1,a:4,tol:1,pre:"",un:" fois",w:"Quatre fois. C'est typique : trois ou quatre répétitions suffisent souvent. Tenir jusque-là demande de l'entraînement, et c'est pour ça qu'on s'entraîne ici."},
{i:"o173_15",u:173,t:"story",d:.45,q:"Dylan, le vendeur, enchaîne les arguments. Quelle réponse est un disque rayé ?",sc:[{who:"Dylan",txt:"Mais attendez, avec l'offre, vous avez aussi la télé gratuite six mois !"}],o:["« Je comprends. Je ne suis pas intéressé. Bonne journée. »","« Ah, la télé ? C'est-à-dire ? Et après les six mois, c'est combien ? »","« Non, parce que j'ai déjà la fibre chez un autre opérateur, voyez-vous. »","« Vous m'avez déjà dit ça trois fois, vous êtes vraiment pénible. »"],a:0,w:"Le vendeur est formé à rebondir sur chaque raison. Le disque rayé ne lui en donne aucune. Et tu as le droit de raccrocher poliment."},
{i:"o173_16",u:173,t:"fill",d:.4,q:"L'enquête négative transforme une critique ___ en information précise.",o:["floue","juste","méchante","écrite"],a:0,w:"« C'est pas top » devient « le tableau page 3 manque de sources ». Tu peux alors agir, ou constater que la critique ne tenait pas."},
{i:"o173_17",u:173,t:"match",d:.45,q:"Associe chaque situation à la technique la plus adaptée.",p:[["Quelqu'un insiste sans fin","Disque rayé"],["On te colle une étiquette (« égoïste »)","Brouillard"],["Tu as vraiment commis une erreur","Assertion négative"],["On te critique vaguement","Enquête négative"]],w:"Choisir la bonne technique selon la situation est la vraie compétence. Tu verras vite lesquelles te conviennent le mieux."},
{i:"o173_18",u:173,t:"story",d:.45,q:"Rappel du module 5 : quel compromis réaliste proposes-tu à Lucas ?",sc:[{who:"Lucas",txt:"Tu pars déjà ? On ne se voit jamais, en plus !"}],o:["« Je rentre ce soir. Brunch demain midi, je t'invite ? »","« D'accord, je reste encore deux heures, mais après je rentre, promis. »","« On ne se voit jamais parce que tu ne proposes que des soirées tardives. »","« Je rentre, et je ne sais pas quand on se reverra, on verra bien. »"],a:0,w:"Un compromis réaliste répond à son besoin (se voir) sans sacrifier le tien (dormir). C'est le « Oui ? » d'Ury."},
{i:"o173_19",u:173,t:"multi",d:.45,q:"Quelles réponses sont des brouillards ?",o:["« C'est possible. »","« Tu as peut-être raison sur ce point. »","« Je comprends que tu le voies comme ça. »","« C'est faux, et je vais te le prouver. »","« Tu as raison, je change d'avis. »"],a:[0,1,2],w:"Le brouillard reconnaît sans céder. « C'est faux » ouvre un débat ; « je change d'avis » est une soumission."},
{i:"o173_20",u:173,t:"tf",d:.5,q:"L'assertion négative consiste à s'accuser de toutes les fautes pour calmer l'autre.",a:false,w:"Seulement les vraies erreurs, et sans se flageller. Admettre ce qui est vrai te rend crédible ; t'accuser de tout te rend vulnérable."},
{i:"o173_21",u:173,t:"story",d:.5,q:"Julie critique ta nouvelle limite. Quelle combinaison de techniques utilises-tu ?",sc:[{who:"Julie",txt:"Depuis que tu vois ta psy, tu es devenu rigide. Avant tu étais sympa."}],o:["« C'est possible que je te paraisse plus ferme. Qu'est-ce qui te gêne concrètement ? »","« Pas du tout, je suis toujours aussi sympa, c'est toi qui exagères toujours tout. »","« Tu as raison, pardon, je redeviens comme avant, je reprends tes dossiers du vendredi. »","« Ma psy, c'est ma vie privée, ça ne te regarde absolument pas, merci bien. »"],a:0,w:"Brouillard (« c'est possible ») puis enquête négative (« qu'est-ce qui te gêne concrètement ? »). Tu ne te défends pas, tu ne cèdes pas, tu ouvres le dialogue."},
{i:"o173_22",u:173,t:"sort",d:.5,q:"Classe chaque réaction : tient le non, ou le fragilise ?",bins:["Tient le non","Fragilise le non"],it:[["Répéter la même phrase calmement",0],["Ajouter une nouvelle excuse à chaque relance",1],["Reconnaître une possibilité sans céder",0],["Se justifier longuement contre une étiquette",1],["Demander ce qui gêne concrètement",0]],w:"Chaque justification ouvre un débat ; chaque répétition calme le ferme. Tenir un non, c'est surtout ne pas remettre de pièce dans la machine."},
{i:"o173_23",u:173,t:"mcq",d:.5,q:"Pourquoi commence-t-on souvent le disque rayé par « je comprends » ?",o:["Pour que la répétition reste chaleureuse","Pour montrer qu'on va céder bientôt","Pour gagner du temps et trouver une excuse","Pour signaler qu'on est d'accord avec l'autre"],a:0,w:"La reconnaissance adoucit la répétition, sans rien concéder sur la décision. Tu n'es pas un robot : tu es une personne calme et décidée."},
{i:"o173_24",u:173,t:"story",d:.55,q:"Rappel du module 6 : ton brouillard ne suffit pas, Monique revient chaque semaine. Que fais-tu ?",sc:[{who:"Tante Monique",txt:"(pour la quatrième semaine) Encore absent dimanche, bien sûr."}],o:["Je prévois une vraie conversation au calme avec la méthode DESC","Je continue le brouillard indéfiniment, chaque dimanche, sans rien changer","Je finis par céder pour que les reproches s'arrêtent enfin","Je cesse de lui répondre au téléphone pour avoir la paix"],a:0,w:"Les techniques de Smith gèrent le moment. Quand un schéma se répète, il faut une limite durable : une conversation DESC, avec une proposition (un déjeuner par mois, par exemple)."},
{i:"o173_25",u:173,t:"fill",d:.55,q:"Dans le mnémotechnique D.B.A.E.C., le C correspond au compromis ___.",o:["réaliste","total","gratuit","secret"],a:0,w:"Un compromis réaliste préserve l'essentiel de ta limite tout en répondant au besoin de l'autre."},
{i:"o173_26",u:173,t:"story",d:.55,q:"Camille critique ta façon de gérer les comptes. La critique est en partie fondée. Que réponds-tu ?",sc:[{who:"Camille",txt:"Tu n'as pas payé la facture d'électricité, on a eu une pénalité."}],o:["« C'est vrai, je l'ai oubliée. On met un rappel automatique ? »","« Ce n'est pas ma faute, la facture est arrivée à une mauvaise date. »","« Je suis vraiment incapable, tu devrais tout gérer à ma place. »","« Et toi, tu as oublié les courses mardi, alors bon, on est quittes. »"],a:0,w:"Assertion négative (c'est vrai, je l'ai oubliée) suivie d'une solution. Admettre une erreur calmement désamorce le conflit bien mieux que se justifier ou contre-attaquer."},
{i:"o173_27",u:173,t:"tiles",d:.6,q:"Reconstitue une phrase de brouillard.",a:["C'est","possible","que","tu","le","voies","comme","ça"],dd:["faux","jamais","désolé"],w:"Tu reconnais le point de vue de l'autre sans te l'approprier, et sans changer de décision."},
{i:"o173_28",u:173,t:"tf",d:.6,q:"Tenir un non face à l'insistance devient plus facile avec l'entraînement.",a:true,w:"Comme un muscle. Les premières fois, ton cœur bat fort ; après une dizaine de disques rayés, c'est presque un jeu. C'est exactement ce qu'on entraîne ici."},
{i:"o173_29",u:173,t:"order",d:.6,q:"Remets dans l'ordre ta réponse à une critique floue de Karim.",it:["Accueillir : « J'entends »","Enquêter : « Qu'est-ce qui ne va pas précisément ? »","Écouter la réponse","Admettre ce qui est juste","Proposer une correction"],w:"Accueillir, enquêter, écouter, admettre le vrai, agir. La critique devient un outil au lieu d'une blessure."},
{i:"o173_30",u:173,t:"multi",d:.65,q:"Quelles réponses de Lucas sont de nouvelles « portes » qu'il ne faut pas franchir en se justifiant ?",o:["« T'es pas drôle ce soir. »","« C'est moi qui paie ! »","« Il y a Inès qui arrive ! »","« Tu nous fais une crise de vieux ? »","« Ok, file, bonne nuit ! »"],a:[0,1,2,3],w:"Culpabilité, avantage, curiosité, moquerie : quatre portes différentes, une seule réponse (le disque rayé). La dernière phrase, c'est la victoire."},
{i:"o173_31",u:173,t:"story",d:.65,q:"Rappel du module 4 : pendant ton disque rayé, qu'est-ce qui doit rester stable ?",sc:[{who:"Hélène Marchal",txt:"Au troisième « je rentre », votre voix est montée dans les aigus."}],o:["La voix posée, qui descend en fin de phrase, et le regard","Le volume, qui doit monter à chaque répétition","Le sourire gêné, pour rester sympathique avec lui","La vitesse, qu'il faut accélérer pour en finir"],a:0,w:"Voix posée, regard stable : c'est ce qui donne sa force au disque rayé. Une voix qui monte laisse croire qu'on est sur le point de céder."},
{i:"o173_32",u:173,t:"mcq",d:.65,q:"Quelle technique choisir quand tu as vraiment tort ?",o:["L'assertion négative","Le disque rayé","Le brouillard","Le compromis réaliste"],a:0,w:"Quand l'erreur est réelle, on l'admet simplement. S'affirmer, ce n'est pas avoir toujours raison, c'est être honnête, y compris sur ses erreurs."}
