/*UNIT*/
{id:177,c:"NON",n:"Module 11",t:"Les petits vices des autres et nos propres biais",col:"--pink",ic:"🎭",guide:`
<h3>Pourquoi les gens demandent autant ?</h3>
<div class="gstory">Hélène te pose une question étrange : « À votre avis, pourquoi Julie vous demande-t-elle tout ? Parce qu'elle est méchante ? » Tu hésites. Non, Julie n'est pas méchante. Elle est un peu paresseuse, un peu pressée, et surtout... ça marche. « Exactement, dit Hélène. Demander ne lui coûte rien, et vous dites toujours oui. À sa place, qui ne demanderait pas ? » Tu comprends soudain que le problème n'est pas Julie. C'est le prix de la demande : zéro.</div>
<h3>Demander ne coûte presque rien</h3>
<p><b>Flynn et Lake (2008)</b> ont demandé à des étudiants d'estimer combien d'inconnus ils devraient solliciter pour obtenir cinq oui à un petit service. Ils pensaient devoir en solliciter environ <b>20</b> ; il en a fallu environ <b>10</b>. Les gens disent oui bien plus souvent qu'on ne le croit, parce que dire non est difficile <b>pour tout le monde</b>. Conséquence : ceux qui l'ont compris demandent, « à tout hasard ». Ce n'est pas toujours du vice : c'est souvent de l'opportunisme ordinaire.</p>
<h3>Les sept petits vices du demandeur</h3>
<p>Les vieux « péchés capitaux » décrivent très bien les petits travers qui poussent les autres à abuser. Personne n'en est exempt, toi compris.</p>
<table><tr><th>Vice</th><th>Ce qu'il donne dans une demande</th><th>Exemple</th></tr>
<tr><td><b>Paresse</b></td><td>Refiler ses corvées</td><td>Nathan « oublie » toujours de sortir les poubelles</td></tr>
<tr><td><b>Avarice</b></td><td>Profiter financièrement</td><td>Sophie ne rembourse jamais</td></tr>
<tr><td><b>Gourmandise</b></td><td>En vouloir toujours plus après un oui</td><td>Lucas : « Et tant que tu y es... »</td></tr>
<tr><td><b>Orgueil</b></td><td>Ne pas supporter un non</td><td>Le client qui exige de « parler au responsable »</td></tr>
<tr><td><b>Envie</b></td><td>Rabaisser ton projet pour te garder à sa portée</td><td>Ton cousin Baptiste : « Ta formation, ça sert à rien »</td></tr>
<tr><td><b>Colère</b></td><td>Intimider pour obtenir</td><td>M. Ferrand, client, qui hausse le ton</td></tr>
<tr><td><b>Séduction intéressée</b></td><td>Charmer pour obtenir (la version moderne de la luxure)</td><td>Anthony, du marketing, tout sourire avant chaque « petit service »</td></tr></table>
<div class="gmnemo"><b>« P.A.G.O.E.C.S. : Pas Assez Gentil Ou Exigeant ? C'est Simple : ni l'un ni l'autre. »</b> Paresse, Avarice, Gourmandise, Orgueil, Envie, Colère, Séduction. Et l'image : ces vices sont des <b>petits cailloux</b> dans la chaussure des autres. Ce n'est pas à toi de marcher à leur place.</div>
<h3>Nos propres biais, qui nous font dire oui</h3>
<table><tr><th>Biais</th><th>Ce qui se passe dans ta tête</th></tr>
<tr><td><b>Désirabilité sociale</b></td><td>Vouloir paraître gentil, serviable, « bonne personne »</td></tr>
<tr><td><b>Erreur de prévision affective</b></td><td>Surestimer l'intensité et la durée du malaise qu'on ressentira après un non (Wilson et Gilbert)</td></tr>
<tr><td><b>Effet projecteur</b></td><td>Se croire observé et jugé (Gilovich, module 1)</td></tr>
<tr><td><b>Lecture de pensée</b></td><td>« Il va penser que je suis égoïste » sans preuve</td></tr>
<tr><td><b>Personnalisation</b></td><td>Se croire responsable des problèmes des autres</td></tr>
<tr><td><b>Coûts irrécupérables</b></td><td>« J'ai déjà tant donné, je ne peux pas arrêter maintenant »</td></tr></table>
<div class="gtrap">Deux erreurs opposées. La première : voir des vices partout et devenir soupçonneux. La plupart des gens demandent parce que c'est facile, pas parce qu'ils sont mauvais. La seconde : ignorer les schémas. Une demande isolée n'est rien ; une demande qui se répète, qui grossit et qui ne rend jamais rien est un signal. <b>On juge les schémas, pas les personnes.</b></div>
<h3>Ce que tu dois savoir faire à la fin de ce module</h3>
<ul><li>Expliquer pourquoi les gens demandent si facilement (Flynn et Lake)</li><li>Reconnaître les sept petits vices du demandeur</li><li>Nommer tes propres biais qui te poussent au oui</li><li>Distinguer une demande isolée d'un schéma qui se répète</li></ul>`},
/*EXOS*/
{i:"o177_01",u:177,t:"sort",d:.2,nw:"Les petits vices du demandeur",q:"Classe chaque comportement selon le petit vice qu'il révèle.",bins:["Paresse","Avarice","Gourmandise","Envie"],it:[["Nathan « oublie » toujours de sortir les poubelles",0],["Sophie ne rembourse jamais ses emprunts",1],["Lucas : « Et tant que tu y es, tu peux aussi... »",2],["Baptiste : « Ta formation, ça ne sert à rien »",3],["Julie te refile ses relectures",0]],w:"Ces petits vices existent chez tout le monde, toi compris. Les repérer n'est pas juger les gens : c'est comprendre pourquoi une demande arrive, et ne plus la prendre pour une obligation."},
{i:"o177_02",u:177,t:"slider",d:.25,nw:"Demander ne coûte presque rien",q:"Dans l'étude de Flynn et Lake (2008), les étudiants pensaient devoir solliciter environ 20 personnes pour obtenir 5 oui. Combien ont-ils dû en solliciter réellement ?",min:5,max:30,step:1,a:10,tol:1,pre:"",un:" personnes",w:"Environ 10, deux fois moins que prévu. Les gens disent oui très souvent, car dire non est difficile pour tout le monde. Tu n'es pas seul à avoir du mal !"},
{i:"o177_03",u:177,t:"story",d:.25,q:"Pourquoi Julie te demande-t-elle tout, selon Hélène ?",sc:[{who:"Hélène Marchal",txt:"Julie est-elle méchante ?"}],o:["« Non : demander ne lui coûte rien, et je dis toujours oui. »","« Oui : elle cherche consciemment à m'exploiter depuis le début. »","« Non : elle ne se rend pas compte qu'elle me demande quelque chose. »","« Oui : c'est une manipulatrice, elle coche toutes les cases. »"],a:0,w:"Le problème n'est pas Julie, c'est le prix de la demande : zéro. Quand tu commences à dire non, le prix augmente, et les demandes diminuent naturellement."},
{i:"o177_04",u:177,t:"tf",d:.25,q:"La plupart des gens qui demandent beaucoup sont de mauvaises personnes.",a:false,w:"Ils demandent surtout parce que c'est facile et que ça marche. On juge les schémas, pas les personnes. Ça te permet de refuser sans haine."},
{i:"o177_05",u:177,t:"match",d:.3,q:"Associe chaque vice à ce qu'il donne dans une demande.",p:[["Orgueil","Ne pas supporter un non"],["Colère","Intimider pour obtenir"],["Séduction intéressée","Charmer avant de demander"],["Avarice","Profiter financièrement"]],w:"P.A.G.O.E.C.S. : Paresse, Avarice, Gourmandise, Orgueil, Envie, Colère, Séduction. Les petits cailloux dans la chaussure des autres."},
{i:"o177_06",u:177,t:"fill",d:.3,q:"Surestimer le malaise qu'on ressentira après un non s'appelle l'erreur de prévision ___.",o:["affective","financière","sociale","logique"],a:0,w:"Wilson et Gilbert ont montré qu'on surestime l'intensité et la durée de nos émotions futures. Le malaise après un non est réel, mais plus court et plus léger que prévu."},
{i:"o177_07",u:177,t:"story",d:.3,q:"Baptiste rabaisse ton projet. Quel vice est à l'œuvre et que réponds-tu ?",sc:[{who:"Baptiste",txt:"Ta formation du soir ? Franchement ça sert à rien, viens plutôt au foot le jeudi comme avant."}],o:["L'envie : « Elle compte pour moi. Le foot, ce sera le dimanche. »","La paresse : « Tu as raison, je lâche la formation et je reviens au foot. »","L'avarice : « Tu dis ça parce que tu veux que je paie ta cotisation. »","La colère : « Tu es jaloux, avoue-le, tu ne supportes pas que je progresse. »"],a:0,w:"Rabaisser ton projet te garde à sa portée : c'est l'envie, souvent inconsciente. Pas besoin de l'accuser : tu affirmes ce qui compte et tu proposes autre chose."},
{i:"o177_08",u:177,t:"multi",d:.35,nw:"Nos propres biais",q:"Quels biais te poussent toi-même à dire oui ?",o:["La désirabilité sociale","L'erreur de prévision affective","La lecture de pensée","La personnalisation","L'amour de la vérité"],a:[0,1,2,3],w:"Désirabilité sociale, prévision affective, lecture de pensée, personnalisation : vouloir paraître gentil, surestimer le malaise, deviner les pensées, te croire responsable : quatre biais très courants chez ceux qui ont du mal à dire non."},
{i:"o177_09",u:177,t:"tiles",d:.35,q:"Reconstitue la règle de ce module.",a:["On","juge","les","schémas","pas","les","personnes"],dd:["toujours","vices","coupables"],w:"Une demande isolée n'est rien ; un schéma qui se répète est un signal. Et juger un schéma permet de refuser sans détester."},
{i:"o177_10",u:177,t:"story",d:.35,q:"M. Ferrand, un client, hausse le ton pour obtenir un délai impossible. Que fais-tu ?",sc:[{who:"M. Ferrand",txt:"Je veux ce dossier pour demain matin, sinon je change de prestataire, c'est clair ?!"}],o:["« Je comprends l'urgence. Demain, impossible ; jeudi 10 h, garanti. »","« Oui, bien sûr, je vais passer la nuit dessus, je suis vraiment désolé du retard. »","« Ne me parlez pas sur ce ton, monsieur, sinon je raccroche immédiatement. »","« Changez de prestataire si vous voulez, ce n'est pas mon problème à moi. »"],a:0,w:"La colère cherche à t'intimider pour obtenir un oui. Tu restes calme, tu accueilles l'urgence, tu proposes ce qui est tenable. Un client ferme se calme face à quelqu'un de calme."},
{i:"o177_11",u:177,t:"tf",d:.35,q:"Selon Flynn et Lake, les gens disent oui plus souvent qu'on ne le croit.",a:true,w:"Et c'est justement parce que dire non est difficile pour tout le monde. En le sachant, tu comprends pourquoi les demandes affluent, et pourquoi tes non sont si rares... pour l'instant."},
{i:"o177_12",u:177,t:"sort",d:.4,q:"Classe chaque pensée selon le biais qu'elle révèle.",bins:["Lecture de pensée","Personnalisation","Coûts irrécupérables","Désirabilité sociale"],it:[["« Il va penser que je suis égoïste »",0],["« Si son projet échoue, ce sera ma faute »",1],["« J'ai déjà tant aidé, je ne peux pas arrêter maintenant »",2],["« Je veux qu'on dise que je suis quelqu'un de bien »",3],["« Elle va croire que je ne l'aime plus »",0]],w:"Nommer le biais te permet de le questionner : « Ai-je une preuve qu'il pensera ça ? », « Est-ce vraiment ma responsabilité ? »."},
{i:"o177_13",u:177,t:"mcq",d:.4,q:"Quel biais correspond à « j'ai déjà tant donné, je ne peux pas arrêter maintenant » ?",o:["Les coûts irrécupérables","L'effet projecteur de Gilovich","La preuve sociale des autres","La lecture de pensée"],a:0,w:"Ce qui a été donné est donné ; ça ne justifie pas de continuer. La bonne question porte sur l'avenir : « Est-ce que je veux continuer à partir d'aujourd'hui ? »"},
{i:"o177_14",u:177,t:"story",d:.4,q:"Lucas enchaîne les demandes. Quel vice, et quelle réponse ?",sc:[{who:"Lucas",txt:"Merci pour la voiture ! Et tant que tu y es, tu peux passer me chercher à la gare dimanche, et arroser mes plantes ?"}],o:["La gourmandise : « La voiture, oui. Le reste, ce ne sera pas possible. »","L'orgueil : « Tu ne supportes jamais qu'on te dise non, toi, hein. »","L'avarice : « Tu pourrais au moins me payer l'essence cette fois. »","La colère : « Tu abuses, j'en ai marre de tes demandes à la chaîne ! »"],a:0,w:"Après un oui, un autre, puis un autre : c'est la gourmandise ordinaire. Tu honores le premier oui et tu refuses calmement la suite. Chaque demande se juge séparément (module 9)."},
{i:"o177_15",u:177,t:"fill",d:.4,q:"Se croire responsable des problèmes des autres est un biais appelé la ___.",o:["personnalisation","généralisation","projection","dramatisation excessive"],a:0,w:"Le projet de Julie qui échoue reste d'abord le problème de Julie. Tu peux aider, mais tu n'en es pas responsable. Ça rejoint un droit de Smith (module 2)."},
{i:"o177_16",u:177,t:"multi",d:.45,q:"Quels signes transforment une demande isolée en schéma à surveiller ?",o:["Elle se répète","Elle grossit avec le temps","Elle n'est jamais rendue","Elle arrive toujours au pire moment","Elle vient d'un ami"],a:[0,1,2,3],w:"Répétition, escalade, absence de réciprocité, mauvais timing systématique : quatre signaux. Qu'elle vienne d'un ami ne change rien, au contraire."},
{i:"o177_17",u:177,t:"story",d:.45,q:"Anthony, du marketing, te couvre de compliments. Que fais-tu ?",sc:[{who:"Anthony",txt:"Toi, t'es vraiment le meilleur de la boîte sur Excel... Tu pourrais me faire mon tableau de bord ce soir ?"}],o:["« Merci ! Ce soir, non. Je te montre la formule demain en cinq minutes ? »","« Merci infiniment, c'est trop gentil ! Bien sûr, je te le fais ce soir. »","« Tu dis ça à tout le monde pour obtenir ce que tu veux, Anthony. »","« Je ne suis pas si bon que ça, tu sais, mais bon, je vais quand même essayer. »"],a:0,w:"La séduction intéressée prépare la demande. Tu prends le compliment, tu juges la demande à part, et tu proposes une aide qui te convient."},
{i:"o177_18",u:177,t:"tf",d:.45,q:"Le malaise ressenti après un non dure généralement moins longtemps qu'on ne le prévoit.",a:true,w:"C'est l'erreur de prévision affective : on surestime l'intensité et la durée de nos émotions futures. Le souvenir de ce fait t'aide à oser."},
{i:"o177_19",u:177,t:"order",d:.5,q:"Remets dans l'ordre ta réflexion face à une demande de Nathan, ton colocataire.",it:["Remarquer que c'est la quatrième fois ce mois-ci","Reconnaître le schéma (paresse ordinaire)","Nommer ton propre biais (« il va me trouver pénible »)","Décider d'une limite claire","Lui en parler au calme, avec DESC"],w:"Observer le schéma, comprendre le vice, repérer ton biais, décider, puis parler. Pas de procès : un cadre."},
{i:"o177_20",u:177,t:"match",d:.5,q:"Associe chaque biais à la question qui le désamorce.",p:[["Lecture de pensée","« Ai-je une preuve de ce qu'il pense ? »"],["Personnalisation","« Est-ce vraiment ma responsabilité ? »"],["Coûts irrécupérables","« Est-ce que je veux continuer à partir d'aujourd'hui ? »"],["Erreur de prévision affective","« Combien de temps a duré mon malaise la dernière fois ? »"]],w:"Chaque biais a sa question. Les poser à voix basse, c'est déjà reprendre le volant."},
{i:"o177_21",u:177,t:"story",d:.5,q:"Rappel du module 10 : Sophie combine avarice et culpabilité. Que réponds-tu ?",sc:[{who:"Sophie",txt:"Tu es mon frère, tu as un bon salaire, et moi je galère. Tu ne vas pas me laisser tomber pour 300 € ?"}],o:["« Je t'aime et je ne te laisse pas tomber. Je ne prête pas, mais on fait ton budget ? »","« Bon, tu as raison, j'ai un bon salaire, je te fais le virement, excuse-moi. »","« Tu profites de moi depuis des années, c'est toujours la même chose avec toi. »","« Je ne peux pas, j'ai des dépenses énormes ce mois-ci, tu comprends, désolé. »"],a:0,w:"Tu sépares l'amour (réel) de la demande (refusée), et tu proposes une aide qui a du sens. La culpabilité (« tu ne vas pas me laisser tomber ») ne décide plus pour toi."},
{i:"o177_22",u:177,t:"fill",d:.55,q:"Vouloir paraître gentil et serviable aux yeux des autres est le biais de ___ sociale.",o:["désirabilité","preuve","pression","comparaison permanente"],a:0,w:"La désirabilité sociale : on veut être vu comme une « bonne personne ». Rappelle-toi : une bonne personne peut dire non, et elle est souvent plus respectée pour ça."},
{i:"o177_23",u:177,t:"mcq",d:.55,q:"Face à un client qui dit « je veux parler au responsable » parce que tu as refusé, quel vice est souvent en jeu ?",o:["L'orgueil : ne pas supporter un non","La paresse : ne pas vouloir chercher","L'avarice : vouloir payer moins","L'envie : jalouser tes compétences"],a:0,w:"L'orgueil blessé veut contourner le non. Tu peux rester calme : « Bien sûr, je vous mets en relation. Ma réponse, elle, reste la même. »"},
{i:"o177_24",u:177,t:"story",d:.6,q:"Tu remarques que toi aussi tu as un petit vice. Lequel, dans cette scène ?",sc:[{who:"Toi (pensée)",txt:"Je vais demander à Léa de relire mon rapport à ma place, elle dit toujours oui..."}],o:["La paresse, et la même facilité que Julie avec toi","L'envie, parce que Léa écrit bien mieux que toi","La colère, parce que tu en veux encore à Léa","L'orgueil, parce que tu ne supportes pas les non"],a:0,w:"Personne n'est exempt de ces petits vices. Le remarquer chez toi aide à comprendre les autres sans les juger. Et à ne pas faire à Léa ce que tu reproches à Julie !"},
{i:"o177_25",u:177,t:"tf",d:.6,q:"Quand tu commences à dire non, les demandes abusives ont tendance à diminuer.",a:true,w:"Le prix de la demande augmente : on la fait moins « à tout hasard ». Ce n'est pas immédiat, mais c'est presque toujours ce qui se passe."},
{i:"o177_26",u:177,t:"sort",d:.6,q:"Classe chaque demande : isolée (pas d'inquiétude) ou schéma (à surveiller) ?",bins:["Demande isolée","Schéma"],it:[["Un collègue te demande un chargeur une fois",0],["Julie transfère ses dossiers chaque vendredi à 17 h",1],["Ta voisine te demande de garder ses clés pendant ses vacances",0],["Sophie emprunte tous les deux mois sans jamais rendre",1],["Lucas demande « un dernier verre » à chaque soirée",1]],w:"Isolée : on juge au cas par cas, souvent oui avec plaisir. Schéma : on pose une limite durable (DESC)."},
{i:"o177_27",u:177,t:"story",d:.65,q:"Rappel du module 8 : Anthony combine séduction et unité. Quelle parade ?",sc:[{who:"Anthony",txt:"Entre nous, les deux seuls qui bossent vraiment ici... tu peux me rendre ce service ?"}],o:["« Merci ! Ce n'est pas possible pour moi cette fois. »","« Oui, entre nous, bien sûr, on doit se serrer les coudes. »","« Tu dis ça pour m'avoir, je connais la technique de l'unité. »","« Je ne sais pas, peut-être, si j'ai le temps, on verra bien. »"],a:0,w:"Accepter le compliment, refuser la demande, sans accuser. Le « nous deux » ne change rien à ta charge de travail."},
{i:"o177_28",u:177,t:"num",d:.65,q:"Julie te fait 4 demandes par semaine. Tu décides d'en refuser la moitié. Combien de demandes acceptes-tu sur 12 semaines ?",a:24,tol:0,un:" demandes",h:"4 × 12, puis la moitié",w:"48 demandes, tu en acceptes 24. Et en réalité, Julie en fera sûrement moins une fois que tes non seront installés : le prix de la demande aura augmenté."},
{i:"o177_29",u:177,t:"multi",d:.7,q:"Quelles attitudes t'évitent de devenir soupçonneux envers tout le monde ?",o:["Juger les schémas, pas les personnes","Se rappeler que demander est facile pour tous","Reconnaître ses propres petits vices","Supposer que chaque demande cache un piège","Refuser tout par principe"],a:[0,1,2],w:"Lucidité sans paranoïa. Tu peux dire oui avec plaisir aux demandes isolées et raisonnables, et poser des limites aux schémas."},
{i:"o177_30",u:177,t:"fill",d:.7,q:"Dans l'image du module, les petits vices des autres sont des ___ dans leur chaussure.",o:["cailloux","trous","lacets","semelles"],a:0,w:"Ce n'est pas à toi de marcher à leur place. Tu peux compatir, pas porter leur chaussure."},
{i:"o177_31",u:177,t:"story",d:.75,q:"Hélène te demande ce que tu as compris. Quelle réponse est la plus juste ?",sc:[{who:"Hélène Marchal",txt:"Alors, qu'est-ce qui a changé dans votre regard sur Julie ?"}],o:["« Elle n'est pas méchante. Elle demande parce que c'est gratuit. À moi de fixer le prix. »","« Elle est clairement manipulatrice, je vais l'éviter désormais autant que possible. »","« Elle a raison de demander, c'est à moi de m'adapter à ses besoins de collègue. »","« Je ne sais pas, j'ai encore besoin d'y réfléchir longtemps avant de changer quoi que ce soit. »"],a:0,w:"Tu vois Julie sans la diaboliser, et tu reprends ta part : fixer le prix de la demande. C'est la posture la plus solide et la plus apaisée."},
{i:"o177_32",u:177,t:"tiles",d:.75,q:"Reconstitue le constat de Flynn et Lake.",a:["Les","gens","disent","oui","plus","souvent","qu'on","ne","le","croit"],dd:["jamais","toujours","méchants"],w:"Parce que dire non est difficile pour tout le monde. Et c'est aussi pour ça que chaque non que tu apprends à dire a tant de valeur."}
