/*UNIT*/
{id:178,c:"NON",n:"Module 12",t:"Dire non au travail : manager, collègues, clients",col:"--pink",ic:"💼",guide:`
<h3>La pile qui ne descend jamais</h3>
<div class="gstory">Lundi, Karim te confie le dossier Duval. Mardi, Julie te demande « juste cinq minutes ». Mercredi, M. Ferrand, client, veut « une petite modification » qui prend deux jours. Jeudi, trois réunions dont tu ne comprends pas pourquoi tu y es. Vendredi, 20 h, tu envoies encore des mails. Hélène te montre une seule phrase, à dire à Karim dès lundi prochain : <b>« Avec plaisir. Qu'est-ce que je retire de ma pile pour faire de la place ? »</b> Karim ouvre de grands yeux. Puis il répond : « Ah. Mets le rapport Moreau en pause. » Pour la première fois depuis des mois, ta pile ne monte pas.</div>
<h3>Au travail, le non change de forme</h3>
<p>Au travail, certaines demandes sont des <b>obligations</b> (ton contrat, ta fiche de poste, les heures supplémentaires demandées dans les règles). On ne répond donc pas toujours par « non », mais par un <b>arbitrage</b> : on rend visible le coût de chaque oui, et on fait choisir celui qui a le pouvoir de choisir.</p>
<div class="formula">La question magique au manager :
« Avec plaisir. Qu'est-ce que je retire de ma pile pour faire de la place ? »</div>
<div class="gmnemo"><b>La pile d'assiettes.</b> Ton travail est une pile d'assiettes. Chaque nouvelle demande est une assiette de plus. Au-delà d'une certaine hauteur, tout tombe. Ta phrase magique ne dit pas « non » : elle demande <b>quelle assiette on enlève</b>. Et retiens <b>A.R.O. : Accueillir, Rendre visible le coût, Offrir un choix</b>.</div>
<h3>La matrice d'Eisenhower</h3>
<table><tr><th></th><th>Urgent</th><th>Pas urgent</th></tr>
<tr><td><b>Important</b></td><td>Faire maintenant</td><td>Planifier</td></tr>
<tr><td><b>Pas important</b></td><td>Déléguer ou négocier le délai</td><td>Refuser ou abandonner</td></tr></table>
<p>Beaucoup de demandes « urgentes » de collègues sont urgentes <b>pour eux</b>, pas importantes <b>pour ton travail</b>. Les classer t'aide à savoir où dire non.</p>
<h3>Situations types</h3>
<table><tr><th>Situation</th><th>Réponse type</th></tr>
<tr><td>Le collègue et ses « cinq minutes »</td><td>« Là je suis concentré. 15 h, ça te va ? »</td></tr>
<tr><td>La réunion floue</td><td>« Quel est l'objectif ? Est-ce que ma présence est nécessaire, ou un compte rendu suffit ? »</td></tr>
<tr><td>Le client qui élargit le périmètre</td><td>« C'est hors du périmètre signé. Je vous fais un devis pour cette partie. »</td></tr>
<tr><td>Le mail du soir</td><td>« Je le traite demain à 9 h. » (ou pas de réponse avant le matin)</td></tr></table>
<h3>Ce que dit le droit (France)</h3>
<ul><li><b>Droit à la déconnexion</b> : depuis la loi du 8 août 2016 (en vigueur au 1er janvier 2017), les entreprises d'au moins 50 salariés doivent en négocier les modalités (accord ou charte).</li>
<li><b>Temps de travail</b> : 10 heures par jour et 48 heures par semaine au maximum (sauf dérogations), 11 heures de repos consécutives par jour.</li>
<li><b>Heures supplémentaires</b> : demandées par l'employeur dans les règles, elles ne se refusent pas sans motif légitime (délai de prévenance trop court, impératif familial sérieux, abus...). Un refus systématique peut être sanctionné.</li></ul>
<div class="gtrap">Trois pièges. Un : croire qu'au travail on ne peut jamais dire non. On peut presque toujours négocier un délai, une priorité ou un périmètre. Deux : croire l'inverse, qu'on peut refuser tout ce qui ne plaît pas. Certaines demandes sont des obligations. Trois : confondre affirmation et harcèlement. Face à des propos humiliants répétés, ce n'est plus une question de technique : on note les faits et on alerte (RH, référent harcèlement, médecin du travail, inspection du travail).</div>
<h3>Ce que tu dois savoir faire à la fin de ce module</h3>
<ul><li>Transformer un oui automatique en arbitrage de priorités</li><li>Utiliser la matrice d'Eisenhower</li><li>Répondre aux « cinq minutes », aux réunions floues et aux clients qui débordent</li><li>Connaître les bases du droit à la déconnexion et des heures supplémentaires</li></ul>`},
/*EXOS*/
{i:"o178_01",u:178,t:"story",d:.2,nw:"L'arbitrage de priorités",q:"Karim te confie un dossier de plus. Quelle réponse choisis-tu ?",sc:[{who:"Karim",txt:"Tu peux prendre le dossier Duval en plus ? Merci !"}],o:["« Avec plaisir. Qu'est-ce que je retire de ma pile pour faire de la place ? »","« Oui, pas de souci, je vais trouver du temps le soir et le week-end. »","« Non, j'ai déjà beaucoup trop de travail, demande à quelqu'un d'autre. »","« Encore ? Tu ne vois pas que je suis déjà complètement débordé cette semaine ? »"],a:0,w:"Tu ne refuses pas : tu rends visible le coût, et tu fais arbitrer celui qui a le pouvoir d'arbitrer. C'est professionnel, et ça protège ta santé."},
{i:"o178_02",u:178,t:"sort",d:.25,nw:"La matrice d'Eisenhower",q:"Classe chaque tâche dans la matrice d'Eisenhower.",bins:["Faire maintenant","Planifier","Déléguer ou négocier","Refuser ou abandonner"],it:[["Réponse au client dont le contrat expire ce soir",0],["Préparer ta formation du trimestre prochain",1],["Relire le mail d'un collègue « pour avis » tout de suite",2],["Participer à une réunion sans objectif où tu n'as rien à apporter",3],["Mettre à jour le dossier annuel dû dans deux mois",1]],w:"Urgent et important : maintenant. Important pas urgent : planifier. Urgent pas important : déléguer ou négocier. Ni l'un ni l'autre : refuser."},
{i:"o178_03",u:178,t:"tf",d:.25,q:"Au travail, on peut refuser toutes les heures supplémentaires sans aucune justification.",a:false,w:"Demandées dans les règles, elles ne se refusent pas sans motif légitime (délai trop court, impératif familial, abus). L'affirmation au travail, c'est aussi connaître ses obligations."},
{i:"o178_04",u:178,t:"tiles",d:.25,q:"Reconstitue la question magique.",a:["Qu'est-ce","que","je","retire","de","ma","pile"],dd:["jamais","toujours","ajoute"],w:"La pile d'assiettes : tu ne refuses pas une assiette, tu demandes laquelle on enlève."},
{i:"o178_05",u:178,t:"story",d:.3,q:"Julie veut « juste cinq minutes » pendant que tu te concentres. Que dis-tu ?",sc:[{who:"Julie",txt:"T'as juste cinq minutes ? C'est rapide, promis !"}],o:["« Là je suis concentré. 15 h, ça te va ? »","« Oui vas-y, je t'écoute, pas de problème, j'arrête tout. »","« Tu me déranges toujours, tu ne vois pas que je bosse ? »","« Euh... d'accord, mais vraiment cinq minutes alors... »"],a:0,w:"Un non pour maintenant, un oui pour plus tard. Tu protèges ta concentration sans fermer la porte à Julie."},
{i:"o178_06",u:178,t:"mcq",d:.3,q:"Depuis quelle loi le droit à la déconnexion existe-t-il en France ?",o:["La loi du 8 août 2016","La loi Lemoine de 2022","La loi Hoguet de 1970","La loi Pacte de 2019"],a:0,w:"Loi Travail du 8 août 2016, en vigueur au 1er janvier 2017 : les entreprises d'au moins 50 salariés doivent négocier les modalités de la déconnexion."},
{i:"o178_07",u:178,t:"multi",d:.3,q:"Quels motifs peuvent rendre légitime le refus d'heures supplémentaires ?",o:["Un délai de prévenance trop court","Un impératif familial sérieux","Un abus manifeste de l'employeur","Une simple préférence pour sa soirée, sans autre raison","L'envie de faire comme un collègue"],a:[0,1,2],w:"Délai trop court, impératif familial, abus : motifs reconnus. Une préférence personnelle ne suffit pas en général : on négocie plutôt un autre créneau."},
{i:"o178_08",u:178,t:"fill",d:.3,q:"Le repos quotidien minimum entre deux journées de travail est de ___ heures consécutives.",o:["11","8","6","14"],a:0,w:"11 heures consécutives. Si tu finis à 22 h, tu ne devrais pas reprendre avant 9 h. C'est un point d'appui factuel pour poser une limite."},
{i:"o178_09",u:178,t:"story",d:.35,q:"M. Ferrand demande une « petite modification » hors contrat. Que réponds-tu ?",sc:[{who:"M. Ferrand",txt:"Vous pouvez aussi ajouter le module de paiement ? C'est trois fois rien pour vous."}],o:["« C'est hors du périmètre signé. Je vous envoie un devis pour cette partie demain. »","« Bien sûr, c'est trois fois rien, je vous l'ajoute cette semaine gratuitement. »","« Non, ça ne fait pas partie du contrat, débrouillez-vous avec un autre prestataire. »","« Je vais voir, peut-être, on verra si on a le temps de le glisser quelque part. »"],a:0,w:"Le client qui élargit le périmètre attend souvent qu'on n'ose pas le lui dire. Un devis, c'est un non au gratuit et un oui au travail payé : un non positif professionnel."},
{i:"o178_10",u:178,t:"match",d:.35,q:"Associe chaque situation à sa réponse type.",p:[["Réunion sans objectif","« Quel est l'objectif ? Un compte rendu suffit ? »"],["Mail à 22 h","« Je le traite demain à 9 h »"],["Collègue et ses cinq minutes","« Là je suis concentré, 15 h ? »"],["Client hors périmètre","« Je vous fais un devis »"]],w:"Chaque situation a sa phrase. Préparées à l'avance, elles sortent naturellement au bon moment."},
{i:"o178_11",u:178,t:"tf",d:.35,q:"Face à des propos humiliants répétés au travail, la bonne réponse est surtout de mieux s'affirmer.",a:false,w:"Là, ce n'est plus une affaire de technique : on note les faits (dates, témoins) et on alerte (RH, référent harcèlement, médecin du travail, inspection du travail). Tu n'as pas à gérer ça seul."},
{i:"o178_12",u:178,t:"story",d:.4,q:"Karim t'invite à une réunion d'une heure sans ordre du jour. Que fais-tu ?",sc:[{who:"Karim (invitation)",txt:"Point projet, jeudi 14 h - 15 h. Merci de ta présence."}],o:["« Quel est l'objectif ? Si ma partie est courte, je peux passer les dix premières minutes. »","« J'accepte sans rien dire, on ne refuse pas une invitation de son manager. »","« Je refuse l'invitation sans explication, ça lui apprendra à organiser des réunions inutiles. »","« Je dis oui, puis je trouve une excuse au dernier moment pour ne pas y aller. »"],a:0,w:"Une question sur l'objectif et une proposition adaptée : tu respectes Karim et ton temps. Fuite, attaque et manipulation sont les trois mauvaises options habituelles."},
{i:"o178_13",u:178,t:"slider",d:.4,q:"Quelle est la durée maximale de travail par semaine, sauf dérogations, en France (en heures) ?",min:35,max:60,step:1,a:48,tol:0,pre:"",un:" h",w:"48 heures sur une même semaine, et 44 heures en moyenne sur 12 semaines. Au-delà de ces repères, ta limite est aussi une limite légale."},
{i:"o178_14",u:178,t:"sort",d:.4,q:"Classe chaque demande : obligation à respecter, ou demande négociable ?",bins:["Obligation","Négociable"],it:[["Les tâches de ta fiche de poste",0],["Relire le travail d'un collègue le soir",1],["Des heures supplémentaires demandées dans les règles, avec un délai correct",0],["Répondre aux mails le week-end",1],["Participer à une réunion où ta présence est facultative",1]],w:"Distinguer obligation et demande négociable te rend crédible : tu tiens tes engagements, et tu poses tes limites là où tu peux le faire."},
{i:"o178_15",u:178,t:"order",d:.4,q:"Remets dans l'ordre la méthode A.R.O. face à une nouvelle demande de Karim.",it:["Accueillir la demande avec bienveillance","Rendre visible ce qu'elle coûte","Offrir un choix à Karim"],w:"Accueillir, Rendre visible le coût, Offrir un choix. Tu restes un collaborateur engagé, pas un mur."},
{i:"o178_16",u:178,t:"fill",d:.45,q:"Le droit à la déconnexion doit être négocié dans les entreprises d'au moins ___ salariés.",o:["50","11","250","1 000"],a:0,w:"50 salariés : accord ou, à défaut, charte. Dans les plus petites structures, rien n'interdit d'en parler avec ton manager."},
{i:"o178_17",u:178,t:"story",d:.45,q:"Rappel du module 5 : quel non positif fais-tu à Karim pour le salon du samedi ?",sc:[{who:"Karim",txt:"Tu tiens le stand du salon samedi ?"}],o:["« Je garde mes samedis pour ma famille. Je prépare tout le stand vendredi ? »","« Samedi, non, pas possible, ne compte pas sur moi pour ce genre d'événement commercial. »","« Oui, bien sûr, je serai là toute la journée, même si ce n'est pas prévu. »","« Je ne sais pas encore, je te dirai peut-être la veille, on verra bien. »"],a:0,w:"Oui à ta famille, non au samedi, oui à Karim avec la préparation du vendredi. Il a une solution, tu gardes ton week-end."},
{i:"o178_18",u:178,t:"multi",d:.45,q:"Quelles phrases transforment un oui automatique en arbitrage ?",o:["« Qu'est-ce que je mets en pause pour ça ? »","« Pour quelle date en as-tu vraiment besoin ? »","« Si je prends ça, le rapport Moreau glisse à mardi. Ça te va ? »","« Oui, je me débrouillerai. »","« Pas de souci, comme d'habitude. »"],a:[0,1,2],w:"Rendre visible le coût et la date réelle ouvre la discussion. « Je me débrouillerai » cache le coût, et c'est toi qui le paies."},
{i:"o178_19",u:178,t:"story",d:.5,q:"Tu reçois un mail de Karim à 22 h. Que fais-tu ?",sc:[{who:"Karim (mail, 22 h 04)",txt:"Tu peux me renvoyer la dernière version du fichier ?"}],o:["Je le traite demain matin à 9 h","Je réponds tout de suite pour montrer mon engagement","Je réponds sèchement qu'il est 22 h","Je lui envoie le fichier avec un message de reproche"],a:0,w:"Rien d'urgent : ça peut attendre 9 h. Répondre à 22 h installe l'habitude d'être disponible à 22 h. Le droit à la déconnexion commence par tes propres gestes."},
{i:"o178_20",u:178,t:"tf",d:.5,q:"Beaucoup de demandes « urgentes » de collègues sont urgentes pour eux, sans être importantes pour ton travail.",a:true,w:"C'est la case « urgent mais pas important » d'Eisenhower : on négocie le délai ou on redirige. Leur urgence ne devient pas automatiquement la tienne."},
{i:"o178_21",u:178,t:"match",d:.5,q:"Associe chaque case de la matrice d'Eisenhower à son action.",p:[["Urgent et important","Faire maintenant"],["Important, pas urgent","Planifier"],["Urgent, pas important","Déléguer ou négocier"],["Ni urgent ni important","Refuser ou abandonner"]],w:"Quatre cases, quatre gestes. La case du bas à droite est celle où tes non ont le plus de valeur."},
{i:"o178_22",u:178,t:"story",d:.55,q:"Rappel du module 7 : Karim insiste après ta question magique. Que fais-tu ?",sc:[{who:"Karim",txt:"Rien à retirer, tout est prioritaire. Tu prends Duval en plus, point."}],o:["« J'entends. Tout d'ici vendredi, impossible. Qu'est-ce qui passe en premier ? »","« D'accord, je vais le faire, je travaillerai tout le week-end s'il le faut. »","« Si tout est prioritaire, rien ne l'est, ton management est catastrophique. »","« Très bien, je vais voir les RH pour me plaindre de ma charge de travail. »"],a:0,w:"Disque rayé bienveillant : tu répètes le fait (tout n'est pas faisable) et tu redemandes l'arbitrage. Si la surcharge devient durable, on en parle ensuite à froid, et éventuellement aux RH."},
{i:"o178_23",u:178,t:"fill",d:.55,q:"Dans la méthode A.R.O., le R signifie ___ visible le coût.",o:["rendre","refuser","rester","remettre"],a:0,w:"Accueillir, Rendre visible le coût, Offrir un choix."},
{i:"o178_24",u:178,t:"num",d:.55,q:"Tu travailles 9 h par jour, 5 jours, et tu ajoutes 2 h le samedi. Combien d'heures cette semaine ?",a:47,tol:0,un:" h",h:"9 × 5 + 2",w:"47 heures : juste sous le maximum légal de 48 heures, et bien au-dessus des 35 heures. Chiffrer ta semaine rend ta limite concrète et discutable."},
{i:"o178_25",u:178,t:"story",d:.6,q:"Julie te propose de « mutualiser » : elle te donne ses relectures, tu lui donnes... rien. Que dis-tu ?",sc:[{who:"Julie",txt:"On pourrait s'organiser : tu fais toutes les relectures de l'équipe, t'es tellement bon pour ça !"}],o:["« Merci ! Je fais les miennes. Pour l'équipe, on tourne chaque semaine ? »","« Oui, avec plaisir, c'est vrai que j'aime bien relire, pas de souci. »","« Tu veux surtout te débarrasser de ton travail sur moi, je le vois bien. »","« Je ne sais pas, faut voir, on en reparlera peut-être un jour, qui sait. »"],a:0,w:"Flatterie et paresse ordinaire (module 11) : tu prends le compliment, tu gardes ta part, tu proposes un système équitable. Ni soupçon, ni soumission."},
{i:"o178_26",u:178,t:"sort",d:.6,q:"Classe chaque réaction à un mail de 22 h.",bins:["Respecte ta déconnexion","L'abîme"],it:[["Traiter le mail le lendemain à 9 h",0],["Répondre immédiatement « pour être sympa »",1],["Couper les notifications après 20 h",0],["Vérifier ta boîte à minuit « au cas où »",1],["Programmer tes propres mails pour le matin",0]],w:"Ta déconnexion commence par tes gestes : notifications, horaires d'envoi, habitudes. Les autres s'y adaptent."},
{i:"o178_27",u:178,t:"tf",d:.65,q:"Programmer l'envoi de ses propres mails tardifs au lendemain matin aide aussi les collègues à se déconnecter.",a:true,w:"Un mail envoyé à 23 h donne l'impression qu'il faut répondre à 23 h. En programmant, tu protèges tes collègues comme toi-même."},
{i:"o178_28",u:178,t:"story",d:.65,q:"Karim te critique en réunion pour la troisième fois ce mois-ci, de façon humiliante. Que fais-tu ?",sc:[{who:"Karim",txt:"(devant tout le monde) Franchement, ton travail, c'est du niveau stagiaire."}],o:["Je note les faits, je lui parle en privé, puis j'alerte les RH si ça continue","Je ne dis rien, c'est normal qu'un manager critique ses collaborateurs","Je lui réponds devant tout le monde que son management est nul","Je démissionne dès ce soir pour ne plus jamais avoir à le revoir"],a:0,w:"Des critiques humiliantes répétées ne sont pas du management normal. On documente, on pose une limite en privé (DESC), puis on alerte si besoin. Tu n'as pas à encaisser en silence."},
{i:"o178_29",u:178,t:"mcq",d:.7,q:"Rappel du module 11 : pourquoi Karim te confie-t-il tant de dossiers ?",o:["Tu dis toujours oui, donc c'est le plus simple pour lui","Il cherche consciemment à te faire échouer","Il ne sait pas du tout que tu as déjà beaucoup de travail","Tu es le seul de l'équipe capable de les faire"],a:0,w:"Comme pour Julie : le prix de la demande est nul. En rendant le coût visible (la pile), tu aides Karim à mieux répartir, sans lui prêter de mauvaises intentions."},
{i:"o178_30",u:178,t:"multi",d:.7,q:"Quelles sont de bonnes façons de dire non à un client exigeant ?",o:["Rappeler le périmètre signé","Proposer un devis pour le supplément","Proposer un délai réaliste","Faire gratuitement pour garder le client","Promettre sans pouvoir tenir"],a:[0,1,2],w:"Périmètre, devis, délai : trois non positifs professionnels. Le gratuit et la promesse intenable abîment ta crédibilité et ta santé."},
{i:"o178_31",u:178,t:"fill",d:.75,q:"Dans l'image du module, ton travail est une pile d'___.",o:["assiettes","dossiers","briques","classeurs"],a:0,w:"Chaque demande ajoute une assiette. Ta question magique demande laquelle on enlève."},
{i:"o178_32",u:178,t:"story",d:.75,q:"Un mois après, Karim te dit quelque chose. Qu'est-ce que ça montre ?",sc:[{who:"Karim",txt:"Depuis que tu me demandes ce que tu retires de ta pile, je m'organise mieux. Merci."}],o:["Qu'un non bien posé peut améliorer le travail de toute l'équipe","Que Karim a simplement eu de la chance ce mois-ci avec les dossiers","Qu'il faudrait désormais refuser toutes ses demandes","Que Karim va sûrement se venger de ta nouvelle attitude"],a:0,w:"Poser des limites claires aide aussi celui qui demande à mieux s'organiser. C'est l'effet le plus souvent observé, et le moins souvent anticipé par ceux qui n'osent pas dire non."}
