/*UNIT*/
{id:179,c:"NON",n:"Module 13",t:"Famille, couple, amis : dire non à ceux qu'on aime",col:"--pink",ic:"🏡",guide:`
<h3>Le repas de Noël</h3>
<div class="gstory">Réveillon chez tes parents. Ta mère a prévu que tu dormes là trois nuits (tu avais dit une). Tante Monique t'a gardé une place « à côté de ta cousine qui est célibataire, tu vois ». Ton père veut que tu reprennes du vin (« c'est Noël ! »). Sophie te glisse qu'elle aurait besoin d'argent « pour les cadeaux ». Et Camille te demande à voix basse pourquoi vous ne faites jamais Noël chez ses parents à lui. Tu aimes tous ces gens. Et tu as envie de disparaître sous la table. Ce module est pour ce soir-là.</div>
<h3>Pourquoi c'est plus dur avec les proches</h3>
<p>Avec un vendeur, on risque une vente. Avec un proche, on croit risquer l'<b>amour</b>. Les histoires anciennes (« tu as toujours été le plus gentil »), les rôles de famille (le serviable, le médiateur, le « petit ») et la peur de blesser rendent chaque non plus lourd. Pourtant, les relations proches sont aussi les plus <b>solides</b> : elles survivent très bien à un non gentil. Ce qui les abîme, ce sont les années de oui subis et de rancœur silencieuse.</p>
<h3>La règle des 3 A</h3>
<div class="formula">Affection   : commencer par le lien (« Je t'aime / ça me touche que tu penses à moi »)
Assurance   : dire le non clairement et calmement
Alternative : proposer autre chose, si tu le souhaites</div>
<div class="gmnemo"><b>Les 3 A : Affection, Assurance, Alternative.</b> C'est le non positif d'Ury version famille. Et la phrase à garder en tête : <b>« Proche ne veut pas dire propriétaire. »</b> Tes proches ont une place immense dans ta vie, pas un droit de propriété sur ton temps, ton argent ou tes choix.</div>
<h3>L'argent entre proches</h3>
<ul><li>Au-delà de <b>1 500 €</b>, un prêt se prouve par écrit (article 1359 du Code civil) : une <b>reconnaissance de dette</b> protège les deux.</li>
<li>Un prêt entre particuliers de plus de <b>5 000 €</b> doit être déclaré à l'administration fiscale (formulaire 2062).</li>
<li>Règle de sagesse : ne prête que ce que tu peux te permettre de ne jamais revoir. Sinon, dis non, ou fais un <b>don</b> assumé d'un montant choisi.</li></ul>
<h3>L'alcool et la pression du groupe</h3>
<p>Santé publique France recommande au maximum <b>10 verres par semaine</b>, <b>2 verres par jour</b>, et pas tous les jours. Tu n'as à justifier ni ta sobriété ni ton rythme : « Je ne bois plus ce soir » est une phrase complète. Astuce pratique : garder un verre d'eau ou de soda en main réduit fortement les relances.</p>
<h3>Le couple : le non comme négociation</h3>
<p>Dans le couple, un non n'est pas un point final : c'est le début d'une négociation entre deux besoins légitimes (Noël chez qui ? vacances où ? argent comment ?). Les outils : la CNV (besoins), le non positif, et la négociation intégrative (alterner, combiner). Ce qui abîme le couple, ce n'est pas le désaccord, c'est le désaccord jamais dit.</p>
<div class="gtrap">Piège n°1 : croire qu'un non gentil fera fuir quelqu'un qui t'aime. Les liens solides encaissent très bien un non ; ce sont les liens déjà fragiles que tes non révèlent. Piège n°2 : attendre que les proches « devinent » tes limites. Ils ne devinent pas : dis-les, calmement, une fois. Piège n°3 : prêter de l'argent qu'on ne peut pas perdre. C'est souvent l'argent, pas le refus, qui brise les relations.</div>
<h3>Ce que tu dois savoir faire à la fin de ce module</h3>
<ul><li>Appliquer les 3 A avec un proche</li><li>Connaître les règles de base d'un prêt entre proches</li><li>Refuser un verre sans te justifier</li><li>Transformer un conflit de couple en négociation de besoins</li></ul>`},
/*EXOS*/
{i:"o179_01",u:179,t:"order",d:.2,nw:"La règle des 3 A",q:"Remets dans l'ordre la règle des 3 A.",it:["Affection","Assurance","Alternative"],w:"Commencer par le lien, dire le non clairement, proposer autre chose si tu le veux. Aimer quelqu'un et lui dire non ne sont pas contradictoires."},
{i:"o179_02",u:179,t:"story",d:.25,q:"Ta mère a prévu trois nuits, tu en voulais une. Quelle réponse suit les 3 A ?",sc:[{who:"Ta mère",txt:"J'ai préparé ta chambre pour trois nuits, ça me fait tellement plaisir de t'avoir !"}],o:["« Ça me touche, maman. Je reste une nuit. On se fait un vrai déjeuner le 26 ? »","« Trois nuits ? Non, je t'avais dit une, tu n'écoutes jamais ce que je dis. »","« D'accord, trois nuits alors, je vais annuler ce que j'avais prévu, ce n'est rien. »","« Je vais voir, peut-être deux, ou trois, on verra en fonction de l'ambiance. »"],a:0,w:"Affection (ça me touche), Assurance (une nuit), Alternative (le déjeuner du 26). Ta mère reçoit ton amour et ta limite en même temps."},
{i:"o179_03",u:179,t:"tiles",d:.25,q:"Reconstitue la phrase à garder en tête avec les proches.",a:["Proche","ne","veut","pas","dire","propriétaire"],dd:["toujours","ennemi","jamais"],w:"Une place immense dans ta vie, pas un droit de propriété sur ton temps, ton argent ou tes choix."},
{i:"o179_04",u:179,t:"tf",d:.25,q:"Au-delà de 1 500 €, un prêt entre particuliers se prouve par écrit.",a:true,w:"Article 1359 du Code civil. Une reconnaissance de dette protège les deux, et clarifie les choses : c'est souvent le flou qui abîme les relations."},
{i:"o179_05",u:179,t:"story",d:.3,q:"Ton père insiste pour que tu reprennes du vin. Que dis-tu ?",sc:[{who:"Ton père",txt:"Allez, un petit dernier, c'est Noël quand même !"}],o:["« Merci papa, je m'arrête là pour ce soir. Il est délicieux, ce vin. »","« Je ne peux pas, je prends le volant demain très tôt, désolé. »","« Tu sais bien que je fais attention, arrête d'insister à chaque fois ! »","« Bon, d'accord, juste une goutte alors, pour te faire plaisir. »"],a:0,w:"Un non simple et chaleureux, sans justification à négocier. « Je prends le volant » appelle « tu dormiras ici ! »."},
{i:"o179_06",u:179,t:"slider",d:.3,q:"Selon Santé publique France, combien de verres d'alcool au maximum par semaine ?",min:0,max:30,step:1,a:10,tol:0,pre:"",un:" verres",w:"10 verres par semaine au maximum, 2 par jour, et pas tous les jours. Mais tu n'as à te justifier de rien : « je ne bois plus ce soir » suffit."},
{i:"o179_07",u:179,t:"multi",d:.3,q:"Quelles sont les règles de base d'un prêt entre proches ?",o:["Écrire une reconnaissance de dette au-delà de 1 500 €","Déclarer au fisc un prêt de plus de 5 000 €","Ne prêter que ce qu'on peut se permettre de perdre","Ne jamais parler de remboursement pour ne pas vexer","Prêter automatiquement à la famille"],a:[0,1,2],w:"Écrit, déclaration, prudence. Le silence sur le remboursement et le prêt automatique sont les deux chemins les plus sûrs vers la rancœur."},
{i:"o179_08",u:179,t:"fill",d:.3,q:"Un prêt entre particuliers de plus de 5 000 € doit être déclaré avec le formulaire ___.",o:["2062","2042","3916","2086"],a:0,w:"Formulaire 2062. Ça rend aussi le prêt officiel : une raison de plus pour y réfléchir avant de dire oui."},
{i:"o179_09",u:179,t:"story",d:.35,q:"Sophie demande de l'argent « pour les cadeaux ». Quelle réponse choisis-tu ?",sc:[{who:"Sophie",txt:"Tu pourrais m'avancer 150 € pour les cadeaux ? Je te rends en janvier."}],o:["« Je t'aime, sœurette. Je ne prête pas. On fait des cadeaux maison ensemble ? »","« 150 € ? Tu ne m'as toujours pas rendu les 200 € de mars, franchement ! »","« D'accord, tiens, mais c'est vraiment la toute dernière fois, je te préviens. »","« Je n'ai plus rien, j'ai tout dépensé, désolé, vraiment, je te jure. »"],a:0,w:"Les 3 A : affection, assurance, alternative. Les 200 € de mars méritent une conversation à part (DESC), au calme, pas au milieu du réveillon."},
{i:"o179_10",u:179,t:"match",d:.35,q:"Associe chaque situation familiale à une réponse 3 A.",p:[["Trois nuits prévues au lieu d'une","« Ça me touche. Une nuit. Déjeuner le 26 ? »"],["La cousine célibataire placée à côté","« C'est gentil, tatie. Je préfère être près de Camille. »"],["Un verre de plus","« Merci papa, je m'arrête là. »"],["150 € pour les cadeaux","« Je ne prête pas. Cadeaux maison ensemble ? »"]],w:"Même soirée, quatre non gentils. Chacun respecte le lien et ta limite."},
{i:"o179_11",u:179,t:"tf",d:.35,q:"Nos proches devraient deviner nos limites sans qu'on ait à les dire.",a:false,w:"Personne ne lit dans les pensées. Dire une limite une fois, calmement, est bien plus aimant que d'attendre qu'on la devine puis d'en vouloir aux autres."},
{i:"o179_12",u:179,t:"story",d:.4,q:"Camille demande pourquoi vous ne faites jamais Noël chez ses parents. Quelle réponse ouvre une négociation ?",sc:[{who:"Camille",txt:"On fait toujours Noël chez tes parents. Et les miens, alors ?"}],o:["« Tu as raison, c'est déséquilibré. On alterne : chez les tiens l'an prochain ? »","« Mes parents seraient trop tristes, on ne peut vraiment pas faire autrement, désolé. »","« Tes parents sont moins drôles, avoue-le, c'est pour ça qu'on vient ici. »","« Fais comme tu veux, moi je viendrai ici quoi qu'il arrive chaque année. »"],a:0,w:"Dans le couple, le désaccord devient une négociation intégrative : alterner, combiner. Tu reconnais le besoin de Camille et tu proposes une solution juste."},
{i:"o179_13",u:179,t:"sort",d:.4,q:"Classe chaque réponse à Lucas qui te ressert : aide à tenir, ou fragilise ?",bins:["Aide à tenir","Fragilise"],it:[["Garder un verre de soda en main",0],["« Je ne bois plus ce soir »",0],["« Je ne peux pas, je conduis » (et il propose un canapé)",1],["Expliquer longuement ton régime",1],["« Merci, je m'arrête là »",0]],w:"Un verre en main et une phrase simple coupent les relances. Les justifications ouvrent des négociations."},
{i:"o179_14",u:179,t:"mcq",d:.4,q:"Selon le module, qu'est-ce qui abîme surtout les relations proches ?",o:["Des années de oui subis et de rancœur silencieuse","Un non gentil dit une seule fois, calmement","Une limite posée avec douceur et affection","Une proposition d'alternative au moment du refus"],a:0,w:"Les relations solides encaissent très bien un non. Ce sont les non jamais dits qui les rongent de l'intérieur."},
{i:"o179_15",u:179,t:"story",d:.4,q:"Tante Monique t'a placé à côté de ta cousine « célibataire ». Que fais-tu ?",sc:[{who:"Tante Monique",txt:"Je t'ai mis à côté de Clara, elle est célibataire, tu vois, hein ?"}],o:["« C'est gentil de penser à moi, tatie. Je préfère m'asseoir près de Camille. »","« Tatie, tu sais très bien que je suis en couple, arrête avec ça enfin ! »","« Euh... d'accord... » (et tu passes toute la soirée mal à l'aise)","« Je vais aller aux toilettes... » (et tu changes de place en douce)"],a:0,w:"Affection, puis ta préférence dite simplement. Pas d'agacement, pas de fuite, pas de manœuvre."},
{i:"o179_16",u:179,t:"fill",d:.45,q:"Dans le couple, un non n'est pas un point final : c'est le début d'une ___.",o:["négociation","rupture","dispute","vengeance froide"],a:0,w:"Deux besoins légitimes se rencontrent. La CNV et la négociation intégrative aident à trouver une solution qui respecte les deux."},
{i:"o179_17",u:179,t:"story",d:.45,q:"Rappel du module 10 : ta mère utilise la culpabilité. Que réponds-tu ?",sc:[{who:"Ta mère",txt:"Une seule nuit ? On ne te voit jamais... tu sais, on ne sera pas éternels, ton père et moi."}],o:["« Je sais, maman, et je tiens à vous. Une nuit, et je viens déjeuner en février. »","« Arrête avec ça, tu me fais culpabiliser exprès à chaque fois, c'est pénible. »","« Tu as raison, pardon, je reste les trois nuits, je vais tout annuler. »","« On se voit souvent, je suis venu en octobre et en août, et aussi en juin dernier. »"],a:0,w:"Tu accueilles l'émotion (réelle) et tu tiens ta limite, avec un geste pour la relation. La culpabilité n'est pas un argument, même quand elle vient de quelqu'un que tu aimes."},
{i:"o179_18",u:179,t:"tf",d:.45,q:"Faire un don d'un montant choisi peut être une meilleure solution qu'un prêt qu'on ne reverra jamais.",a:true,w:"Un don assumé ne crée ni dette ni rancœur. Un prêt jamais rendu crée les deux. Si tu veux aider, choisis le montant et offre-le."},
{i:"o179_19",u:179,t:"multi",d:.5,q:"Pourquoi est-ce plus dur de dire non à un proche ?",o:["On croit risquer l'amour","Les rôles de famille sont anciens","On a peur de blesser","Les proches sont moins solides que les inconnus","On a de bonnes raisons de croire qu'ils ne pardonnent jamais"],a:[0,1,2],w:"Peur de perdre l'amour, rôles anciens, peur de blesser. Pourtant les liens proches sont souvent les plus solides : ils encaissent très bien un non gentil."},
{i:"o179_20",u:179,t:"story",d:.5,q:"Ton frère te demande de garder ses enfants tous les mercredis. Tu peux un mercredi sur deux. Que dis-tu ?",sc:[{who:"Ton frère",txt:"Tu pourrais prendre les petits tous les mercredis ? Ça nous sauverait la vie."}],o:["« J'adore les avoir. Tous les mercredis, non ; un sur deux, oui, avec plaisir. »","« Tous les mercredis ? Tu te rends compte de ce que tu me demandes, franchement ? »","« Bien sûr, tous les mercredis, pas de problème, je m'organiserai d'une façon ou d'une autre. »","« Je vais voir, peut-être, on essaiera, et on verra bien si ça tient dans le temps. »"],a:0,w:"Affection, assurance, alternative. Un oui partiel choisi vaut mieux qu'un oui total subi qui s'effondrera dans trois mois."},
{i:"o179_21",u:179,t:"match",d:.5,q:"Associe chaque piège à sa correction.",p:[["Attendre qu'on devine tes limites","Les dire calmement, une fois"],["Prêter ce qu'on ne peut pas perdre","Refuser, ou donner un montant choisi"],["Se justifier pour un verre","« Je ne bois plus ce soir »"],["Dire oui à tout pour éviter un conflit de couple","Négocier entre deux besoins légitimes"]],w:"Quatre pièges de famille, quatre corrections. Aucune ne demande de dureté."},
{i:"o179_22",u:179,t:"num",d:.55,q:"Tu as déjà prêté 200 € à Sophie en mars et 150 € en juin, jamais rendus. Si tu acceptes 150 € de plus, combien te devra-t-elle au total, en euros ?",a:500,tol:0,un:" €",h:"200 + 150 + 150",w:"500 €. Au-delà de 1 500 €, une preuve écrite serait nécessaire. Et surtout, chaque prêt non rendu rend le suivant plus difficile à refuser. Poser la limite tôt est un acte d'amour."},
{i:"o179_23",u:179,t:"story",d:.55,q:"Rappel du module 6 : tu veux parler des 500 € avec Sophie, en janvier. Quelle ouverture DESC ?",sc:[{who:"Sophie",txt:"Tu voulais me voir ?"}],o:["« Depuis mars, je t'ai prêté 500 €. Ça me pèse. 50 € par mois, ça t'irait ? »","« Tu es une profiteuse, tu m'empruntes sans arrêt et tu ne rends jamais rien. »","« Rien d'important... enfin... non, laisse tomber, ce n'est pas grave. »","« Je me sens exploité par toi depuis des mois, tu dois tout me rendre tout de suite. »"],a:0,w:"Faits, ressenti, demande précise. Sophie n'est pas attaquée, et la dette devient un plan concret."},
{i:"o179_24",u:179,t:"fill",d:.6,q:"Les 3 A sont : Affection, Assurance et ___.",o:["Alternative","Amour","Argument","Accord mutuel"],a:0,w:"Affection, Assurance, Alternative. L'alternative est facultative : un non affectueux et clair suffit parfois."},
{i:"o179_25",u:179,t:"sort",d:.6,q:"Classe chaque réponse à un proche : 3 A complète, ou incomplète ?",bins:["Complète","Incomplète"],it:[["« Je t'aime. Pas ce week-end. Dimanche prochain ? »",0],["« Pas ce week-end. »",1],["« Ça me touche que tu m'invites. Je ne viens pas. On s'appelle mardi ? »",0],["« Je t'aime, mais bon, je verrai... »",1]],w:"La deuxième est incomplète mais reste un non valable. La quatrième est un non mou : l'affection est là, l'assurance manque."},
{i:"o179_26",u:179,t:"tf",d:.65,q:"Tes non gentils peuvent révéler qu'une relation était déjà fragile.",a:true,w:"C'est douloureux, mais c'est une information précieuse. Une relation qui ne survit qu'à condition que tu dises toujours oui n'était pas équilibrée."},
{i:"o179_27",u:179,t:"story",d:.65,q:"Lucas se vexe parce que tu ne viens plus à toutes ses soirées. Que dis-tu ?",sc:[{who:"Lucas",txt:"T'as changé, avant tu venais tout le temps. Tu ne m'aimes plus ou quoi ?"}],o:["« Si, je tiens à toi. J'ai envie de te voir autrement aussi. Ciné jeudi ? »","« Tu as raison, pardon, je reviendrai à toutes tes soirées, promis. »","« T'es trop lourd avec tes soirées, voilà pourquoi je ne viens plus. »","« Non, rien n'a changé, j'étais juste très fatigué ces derniers temps. »"],a:0,w:"Affection affirmée, envie exprimée, proposition concrète. Tu nourris l'amitié sous une autre forme, sans revenir à tes oui subis."},
{i:"o179_28",u:179,t:"mcq",d:.7,q:"Rappel du module 5 : les 3 A sont une version familiale de quelle méthode ?",o:["Le non positif d'Ury (Oui ! Non. Oui ?)","La méthode DESC de Sharon et Gordon Bower","Le disque rayé de Manuel J. Smith","La matrice des priorités d'Eisenhower"],a:0,w:"Affection (le oui au lien), Assurance (le non), Alternative (le oui ?). La même structure, adaptée aux proches."},
{i:"o179_29",u:179,t:"multi",d:.7,q:"Quelles attitudes protègent une relation proche sur le long terme ?",o:["Dire ses limites tôt","Proposer des alternatives choisies","Parler d'argent clairement","Accumuler les oui pour éviter les conflits","Attendre qu'on devine ce qu'on ressent"],a:[0,1,2],w:"Clarté, générosité choisie, transparence sur l'argent. L'accumulation et le silence préparent les explosions."},
{i:"o179_30",u:179,t:"story",d:.75,q:"Le réveillon est fini. Tu as posé quatre limites. Comment te sens-tu, et que retiens-tu ?",sc:[{who:"Camille (dans la voiture)",txt:"Tu as vu ? Personne n'est fâché. Ta mère t'a même serré plus fort que d'habitude."}],o:["« Oui. Ma peur était bien plus grande que la réalité. Je recommencerai. »","« C'était de la chance, l'année prochaine ils seront sûrement très vexés. »","« Ils font semblant, je suis sûr qu'ils m'en veulent en secret. »","« Je n'aurais peut-être pas dû, j'ai peur d'avoir gâché leur Noël. »"],a:0,w:"Comme dans l'étude de Givi et Kirk : les conséquences d'un non gentil sont bien plus douces que prévu. Chaque expérience réussie rend la suivante plus facile."},
{i:"o179_31",u:179,t:"tiles",d:.75,q:"Reconstitue la règle des 3 A.",a:["affection","assurance","alternative"],dd:["argument","attaque","accusation"],w:"Affection, Assurance, Alternative. L'attaque et l'accusation sont précisément ce qu'elle évite."},
{i:"o179_32",u:179,t:"fill",d:.75,q:"Selon le module, c'est souvent l'___, plus que le refus, qui brise les relations.",o:["argent","alcool","éloignement","âge"],a:0,w:"Les prêts non rendus créent des rancœurs durables. Un refus gentil, lui, s'oublie vite."}
