/*UNIT*/
{id:180,c:"NON",n:"Module 14",t:"Vendeurs, démarchage et abonnements : ne plus signer sous pression",col:"--pink",ic:"🛒",guide:`
<h3>Trois fois en une semaine</h3>
<div class="gstory">Lundi, un démarcheur sonne pour « vérifier ton isolation » et repart presque avec ta signature pour des panneaux solaires. Mercredi, une jeune femme souriante t'arrête dans la rue pour une association, tablette en main : « Juste 15 € par mois, pour les enfants. » Samedi, en magasin, le vendeur du téléphone t'ajoute une extension de garantie à 129 €, une coque à 39 € et une assurance « indispensable ». À chaque fois, tu sens la même chose : il est plus facile de dire oui que de supporter le malaise du non. Ce module te donne une règle simple, et les droits qui vont avec.</div>
<h3>La règle d'or : jamais de signature le jour J</h3>
<div class="formula">S.T.O.P.
S : Stop, je ne décide pas maintenant
T : Temps, je prends au moins 24 heures
O : Offre réelle, je calcule le coût total, sur toute la durée
P : Partir, je m'autorise à m'en aller sans rien signer</div>
<div class="gmnemo"><b>S.T.O.P., comme au carrefour.</b> Face à un vendeur, tu marques l'arrêt : Stop, Temps, Offre réelle, Partir. Et la phrase qui fait tout : <b>« Je ne signe jamais le jour même. Laissez-moi la documentation. »</b> Un vendeur honnête l'accepte. Un vendeur qui refuse vient de te donner la meilleure raison de dire non.</div>
<h3>Tes droits (France, à jour en 2026)</h3>
<table><tr><th>Situation</th><th>Règle</th></tr>
<tr><td><b>Démarchage à domicile</b> (hors établissement)</td><td>Tu as 14 jours pour te rétracter. Aucun paiement ne peut être exigé pendant les 7 premiers jours.</td></tr>
<tr><td><b>Achat à distance</b> (internet, téléphone)</td><td>14 jours de rétractation, pour la plupart des produits</td></tr>
<tr><td><b>Achat en magasin</b></td><td><b>Aucun droit de rétractation légal</b> (seulement si le magasin l'offre commercialement)</td></tr>
<tr><td><b>Démarchage téléphonique</b></td><td>Depuis le 11 août 2026, le démarchage téléphonique est interdit sans ton <b>consentement préalable</b> (loi du 30 juin 2025). Bloctel disparaît. Ton consentement vaut un an au maximum et tu peux le retirer à tout moment.</td></tr>
<tr><td><b>Abonnement souscrit en ligne</b></td><td>Résiliation « en trois clics » obligatoire depuis le 1er juin 2023 (loi du 16 août 2022)</td></tr></table>
<h3>Les techniques de vente à reconnaître</h3>
<ul><li><b>La fausse urgence</b> (rareté) : « l'offre s'arrête ce soir ».</li>
<li><b>La vente additionnelle</b> : garantie, accessoires, assurance glissés au moment où tu as déjà dit oui (un cousin de l'amorçage).</li>
<li><b>Le « je dois voir avec mon responsable »</b> : le vendeur revient avec une « faveur exceptionnelle » (porte au nez et réciprocité).</li>
<li><b>La fausse autorité</b> : badge, gilet, « de la part des services de l'État ».</li>
<li><b>Le petit montant mensuel</b> : « juste 15 € par mois » cache 180 € par an.</li></ul>
<div class="gtrap">Le piège le plus répandu : croire qu'on peut toujours se rétracter. <b>En magasin, il n'y a pas de droit de rétractation légal.</b> Autre piège : penser qu'un non poli oblige à écouter tout l'argumentaire. Tu peux interrompre gentiment et partir (ou raccrocher) : « Merci, ça ne m'intéresse pas, bonne journée. » Ce n'est pas impoli, c'est clair.</div>
<h3>Ce que tu dois savoir faire à la fin de ce module</h3>
<ul><li>Appliquer S.T.O.P. face à n'importe quel vendeur</li><li>Connaître tes droits : rétractation, démarchage téléphonique, résiliation</li><li>Reconnaître les techniques de vente classiques</li><li>Calculer le vrai coût d'un « petit » montant mensuel</li><li>Interrompre et partir sans culpabilité</li></ul>`},
/*EXOS*/
{i:"o180_01",u:180,t:"order",d:.2,nw:"La méthode S.T.O.P.",q:"Remets dans l'ordre la méthode S.T.O.P. face à un vendeur.",it:["Stop : je ne décide pas maintenant","Temps : je prends au moins 24 heures","Offre réelle : je calcule le coût total","Partir : je m'autorise à m'en aller"],w:"Comme au carrefour : on marque l'arrêt. Presque toutes les techniques de vente perdent leur force en 24 heures."},
{i:"o180_02",u:180,t:"tf",d:.2,q:"Après un achat en magasin, on dispose toujours de 14 jours pour se rétracter.",a:false,w:"C'est le piège le plus répandu : en magasin, il n'y a pas de droit de rétractation légal. Les 14 jours concernent la vente à distance et hors établissement."},
{i:"o180_03",u:180,t:"story",d:.25,q:"Le vendeur de téléphone ajoute une extension de garantie. Que dis-tu ?",sc:[{who:"Le vendeur",txt:"Et je vous mets l'extension de garantie à 129 € ? Tout le monde la prend, c'est plus prudent."}],o:["« Non merci, juste le téléphone. »","« Euh... si tout le monde la prend, c'est peut-être plus prudent, oui... »","« Vous dites ça pour votre commission, je ne suis pas dupe du tout. »","« Je ne sais pas, qu'est-ce qu'elle couvre exactement, en détail ? »"],a:0,w:"La vente additionnelle arrive quand tu as déjà dit oui. Un « non merci, juste le téléphone » suffit. « Tout le monde la prend » est de la preuve sociale (module 8)."},
{i:"o180_04",u:180,t:"mcq",d:.25,nw:"Le démarchage téléphonique",q:"Depuis le 11 août 2026, un professionnel peut-il te démarcher par téléphone sans ton accord préalable ?",o:["Non, il faut ton consentement préalable","Oui, sauf si tu es inscrit sur Bloctel","Oui, en semaine de 10 h à 20 h","Oui, s'il est une entreprise française"],a:0,w:"La loi du 30 juin 2025 a inversé la logique : le démarchage téléphonique est interdit sans consentement préalable, et Bloctel disparaît. Le consentement vaut un an maximum."},
{i:"o180_05",u:180,t:"num",d:.3,q:"L'association propose « juste 15 € par mois ». Combien cela fait-il par an, en euros ?",a:180,tol:0,un:" €",h:"15 × 12",w:"180 € par an. Donner est une belle chose, à condition de le choisir : tu peux prendre la documentation et décider chez toi du montant et de l'association."},
{i:"o180_06",u:180,t:"sort",d:.3,q:"Classe chaque achat : droit de rétractation de 14 jours ou non ?",bins:["14 jours de rétractation","Pas de droit légal"],it:[["Une commande sur un site internet",0],["Un contrat signé chez toi après la visite d'un démarcheur",0],["Un téléphone acheté en magasin",1],["Un canapé acheté en boutique",1],["Un abonnement souscrit au téléphone",0]],w:"À distance ou hors établissement : 14 jours. En magasin : rien de légal, seulement ce que le commerçant accepte."},
{i:"o180_07",u:180,t:"fill",d:.3,q:"Après un démarchage à domicile, aucun paiement ne peut être exigé pendant les ___ premiers jours.",o:["7","3","14","30"],a:0,w:"7 jours sans paiement, et 14 jours de rétractation. Un démarcheur qui réclame un chèque tout de suite est hors la loi."},
{i:"o180_08",u:180,t:"story",d:.3,q:"Un démarcheur sonne pour « vérifier ton isolation ». Que fais-tu ?",sc:[{who:"Le démarcheur",txt:"Bonjour, c'est pour le contrôle de l'isolation, obligatoire dans votre quartier. Je peux entrer cinq minutes ?"}],o:["« Non merci. Laissez-moi votre documentation, je vérifierai moi-même. »","« Ah, si c'est obligatoire, entrez, je ne veux pas avoir de problème. »","« Cinq minutes alors, mais je ne signe rien, je vous préviens bien. »","« Vous êtes un escroc, partez tout de suite ou j'appelle la police ! »"],a:0,w:"La fausse obligation (« contrôle obligatoire ») est un classique de fausse autorité. Aucun contrôle d'isolation n'est imposé par démarchage. Tu peux refuser poliment et vérifier seul."},
{i:"o180_09",u:180,t:"tiles",d:.3,q:"Reconstitue la phrase qui fait tout.",a:["Je","ne","signe","jamais","le","jour","même"],dd:["toujours","aujourd'hui","peut-être"],w:"Un vendeur honnête l'accepte. Celui qui insiste vient de te donner la meilleure raison de dire non."},
{i:"o180_10",u:180,t:"match",d:.35,q:"Associe chaque technique de vente au levier d'influence qu'elle utilise.",p:[["« L'offre s'arrête ce soir »","Rareté"],["« Tout le monde la prend »","Preuve sociale"],["Gilet « services de l'énergie »","Autorité"],["« Je suis allé voir mon responsable pour vous »","Réciprocité"]],w:"Les leviers de Cialdini, version commerciale. Méfie-toi du REPAS au RU."},
{i:"o180_11",u:180,t:"tf",d:.35,q:"Depuis le 1er juin 2023, un abonnement souscrit en ligne doit pouvoir être résilié en ligne, en quelques clics.",a:true,w:"La loi du 16 août 2022 a créé la « résiliation en trois clics ». Plus besoin de lettre recommandée ni d'appel interminable pour ces abonnements."},
{i:"o180_12",u:180,t:"story",d:.35,q:"Le vendeur revient de chez son « responsable » avec une remise. Que fais-tu ?",sc:[{who:"Le vendeur",txt:"J'ai insisté auprès de mon responsable, il accepte exceptionnellement -20 %, mais seulement si vous signez maintenant."}],o:["« Merci pour l'effort. Je ne signe pas aujourd'hui. »","« Oh, c'est gentil d'avoir insisté, je signe alors, merci. »","« -20 % ? Alors -30 % et je signe tout de suite. »","« Votre responsable n'existe pas, c'est un vieux truc. »"],a:0,w:"Le « responsable » crée une dette (réciprocité) et une urgence (rareté). Tu peux remercier et maintenir S.T.O.P. Si l'offre est bonne, elle le sera encore demain."},
{i:"o180_13",u:180,t:"multi",d:.4,q:"Quelles phrases te permettent de partir poliment ?",o:["« Merci, ça ne m'intéresse pas, bonne journée. »","« Je réfléchis et je reviens si besoin. »","« Laissez-moi la documentation. »","« Expliquez-moi encore une fois tous les détails. »","« Je vais sûrement signer, mais pas tout de suite. »"],a:[0,1,2],w:"Trois sorties propres. Demander plus de détails prolonge l'argumentaire ; « je vais sûrement signer » crée un engagement (module 8)."},
{i:"o180_14",u:180,t:"slider",d:.4,q:"Combien de temps, au minimum, la règle S.T.O.P. recommande-t-elle avant de signer (en heures) ?",min:0,max:72,step:6,a:24,tol:0,pre:"",un:" h",w:"24 heures au minimum. Le temps désamorce la rareté, la réciprocité et l'engagement. Et il laisse ton test E.C.R. faire son travail."},
{i:"o180_15",u:180,t:"story",d:.45,q:"Dans la rue, la collecteuse insiste. Que dis-tu ?",sc:[{who:"La collecteuse",txt:"Vous aimez les enfants, non ? Alors 15 € par mois, ce n'est rien pour vous !"}],o:["« J'aime beaucoup votre cause. Je ne m'engage pas dans la rue. Bonne journée ! »","« Oui, j'aime les enfants... bon, d'accord, allez, je signe, vous avez raison. »","« Vous culpabilisez les passants, c'est vraiment une méthode détestable. »","« Je ne peux pas, je suis étudiant, je n'ai vraiment pas d'argent, désolé. »"],a:0,w:"« Vous aimez les enfants, non ? » est un engagement et une culpabilisation. Tu peux saluer la cause et refuser l'engagement sur le trottoir. Si tu veux donner, tu choisiras chez toi."},
{i:"o180_16",u:180,t:"fill",d:.45,q:"Depuis le 11 août 2026, le service ___ disparaît, car le démarchage téléphonique exige ton accord préalable.",o:["Bloctel","Pacitel","Signal Conso","France Services"],a:0,w:"Bloctel servait à s'inscrire pour ne plus être appelé. Désormais, c'est l'inverse : sans ton accord, on ne peut pas t'appeler."},
{i:"o180_17",u:180,t:"sort",d:.5,q:"Classe chaque réaction face à Dylan au téléphone.",bins:["Protège","Expose"],it:[["« Non merci, je ne suis pas intéressé. » puis raccrocher",0],["Écouter tout l'argumentaire par politesse",1],["Demander d'où il a ton numéro et s'il a ton consentement",0],["Donner ton code postal « pour vérifier l'éligibilité »",1],["Dire « rappelez-moi plus tard »",1]],w:"« Rappelez-moi plus tard » garantit un rappel. Refuser et raccrocher est poli et efficace ; demander le consentement rappelle tes droits."},
{i:"o180_18",u:180,t:"story",d:.5,q:"Rappel du module 9 : quelle technique utilise le vendeur de voitures ?",sc:[{who:"Le vendeur",txt:"Le modèle à 15 990 € en promo ? Ah, il vient de partir. Mais celui-ci, à 19 490 €, est encore mieux équipé !"}],o:["Le leurre : l'offre annoncée a disparu, on en propose une plus chère","La porte au nez : il demande énorme d'abord, puis beaucoup moins","Le pied dans la porte : une petite demande d'abord, puis une grande","Le pied dans la bouche : il te demande d'abord comment tu vas"],a:0,w:"Le leurre attire avec une offre qui n'existe plus. Parade : « Je venais pour celui à 15 990 €. Je reviendrai quand il sera disponible. »"},
{i:"o180_19",u:180,t:"tf",d:.5,q:"Interrompre poliment un vendeur pour dire que cela ne t'intéresse pas est impoli.",a:false,w:"C'est clair, pas impoli. Le laisser dérouler vingt minutes d'argumentaire pour rien, c'est ça qui est une perte de temps pour tous les deux."},
{i:"o180_20",u:180,t:"num",d:.55,q:"Téléphone à 699 €, extension de garantie à 129 €, coque à 39 €, assurance à 9 € par mois pendant 24 mois. Quel est le coût total, en euros ?",a:1083,tol:1,un:" €",h:"699 + 129 + 39 + 9 × 24",w:"699 + 129 + 39 + 216 = 1 083 €, soit 55 % de plus que le téléphone seul. Le O de S.T.O.P. : calculer l'offre réelle."},
{i:"o180_21",u:180,t:"story",d:.55,q:"Rappel du module 7 : Dylan rappelle trois fois dans la même journée. Quelle réponse est un disque rayé ?",sc:[{who:"Dylan",txt:"C'est encore moi ! Vous avez réfléchi pour l'offre fibre ?"}],o:["« Je vous l'ai dit : je ne suis pas intéressé. Au revoir. »","« Oui, mais je ne suis toujours pas sûr, vous pourriez m'expliquer à nouveau ? »","« Si vous rappelez encore une fois, je porte plainte contre votre entreprise. »","« Rappelez-moi la semaine prochaine, j'aurai peut-être plus de temps. »"],a:0,w:"Même phrase, calme, puis on raccroche. Et depuis août 2026, un appel sans ton consentement est interdit : tu peux le signaler (sur Signal Conso)."},
{i:"o180_22",u:180,t:"match",d:.55,q:"Associe chaque droit à sa durée.",p:[["Rétractation à distance ou hors établissement","14 jours"],["Pas de paiement après un démarchage à domicile","7 jours"],["Validité maximale d'un consentement au démarchage téléphonique","1 an"],["Rétractation après un achat en magasin","Aucune obligation légale"]],w:"Quatre chiffres à connaître. Ils transforment ton malaise en droits concrets."},
{i:"o180_23",u:180,t:"fill",d:.6,q:"Dans S.T.O.P., le O veut dire ___ réelle : on calcule le coût total sur toute la durée.",o:["offre","option","occasion","opinion"],a:0,w:"Le « petit » montant mensuel cache souvent un gros total. Le calculer ramène la décision à la réalité."},
{i:"o180_24",u:180,t:"story",d:.6,q:"Tu as signé chez toi pour des panneaux solaires sous pression. Le lendemain, tu regrettes. Que fais-tu ?",sc:[{who:"Toi (le lendemain)",txt:"Je crois que je me suis fait avoir..."}],o:["J'utilise mon droit de rétractation de 14 jours, par écrit","Je laisse tomber, j'ai signé, c'est trop tard","J'appelle le vendeur pour le supplier d'annuler","Je fais opposition sur mon compte sans rien dire"],a:0,w:"Contrat signé hors établissement : 14 jours de rétractation, par écrit (formulaire ou lettre recommandée). Et aucun paiement ne pouvait être exigé pendant 7 jours. Tu n'as rien à te reprocher : ces techniques sont faites pour ça."},
{i:"o180_25",u:180,t:"multi",d:.65,q:"Quelles affirmations sur le démarchage téléphonique depuis le 11 août 2026 sont justes ?",o:["Il faut ton consentement préalable","Le consentement vaut un an maximum","Tu peux retirer ton consentement à tout moment","Bloctel reste obligatoire pour être protégé","Tout professionnel peut t'appeler une fois par mois"],a:[0,1,2],w:"Consentement préalable, durée d'un an, retrait possible. Bloctel disparaît ; il n'existe pas de « quota » d'appels autorisés sans accord."},
{i:"o180_26",u:180,t:"tf",d:.65,q:"Un vendeur qui refuse de te laisser la documentation pour réfléchir te donne une bonne raison de refuser.",a:true,w:"Une offre sérieuse supporte d'être relue au calme. Si elle ne vaut que « maintenant », c'est la pression qui vend, pas le produit."},
{i:"o180_27",u:180,t:"story",d:.7,q:"Rappel du module 2 : l'extension de garantie passe-t-elle ton test E.C.R. ?",ctx:"Ton téléphone est déjà garanti deux ans par la loi (garantie légale de conformité). L'extension coûte 129 €.",sc:[{who:"Toi (pensée)",txt:"Envie ? Capacité ? Regret ?"}],o:["Pas d'envie réelle, et je regretterais 129 € pour une protection déjà en partie couverte","Oui, car tout ce qui protège un appareil est forcément une bonne idée","Oui, car le vendeur a bien dit que tout le monde la prenait","Je ne peux pas savoir, je dois d'abord le demander au vendeur"],a:0,w:"La garantie légale de conformité couvre déjà deux ans pour un bien neuf. Le test E.C.R. révèle souvent que la vente additionnelle répond à la peur, pas à un besoin."},
{i:"o180_28",u:180,t:"sort",d:.7,q:"Classe chaque phrase de vendeur selon la technique.",bins:["Fausse urgence","Vente additionnelle","Petit montant mensuel"],it:[["« Plus que deux heures pour profiter du prix »",0],["« Avec la coque et le chargeur rapide, c'est mieux »",1],["« Juste 9 € par mois, un café par semaine ! »",2],["« Cette promotion ne reviendra pas »",0],["« Je vous ajoute l'assurance casse ? »",1]],w:"Trois familles, trois parades : prendre du temps, dire « juste le produit », calculer le total annuel."},
{i:"o180_29",u:180,t:"fill",d:.75,q:"La loi du 16 août 2022 a créé la résiliation « en trois ___ ».",o:["clics","jours","lettres","appels"],a:0,w:"Effective depuis le 1er juin 2023 pour les contrats souscrits en ligne : un bouton de résiliation doit être facilement accessible."},
{i:"o180_30",u:180,t:"story",d:.75,q:"Le vendeur te dit que tu es « le client le plus sympa de la journée ». Que retiens-tu ?",sc:[{who:"Le vendeur",txt:"Franchement, vous êtes le client le plus sympa de la journée ! Alors, on part sur le pack complet ?"}],o:["Je prends le compliment et je juge le pack seul : « Merci ! Juste le téléphone. »","Je signe le pack complet pour le remercier de sa gentillesse","Je lui dis qu'il dit sûrement ça à tout le monde, pour le vexer un peu","Je me sens obligé de prendre au moins l'option la moins chère du pack"],a:0,w:"La sympathie (module 8) prépare la demande. Tu peux être aimable ET dire non. Ta gentillesse ne se paie pas en options."},
{i:"o180_31",u:180,t:"tiles",d:.8,q:"Reconstitue la méthode S.T.O.P.",a:["stop","temps","offre","réelle","partir"],dd:["signer","vite","maintenant"],w:"Stop, Temps, Offre réelle, Partir. Signer vite maintenant, c'est exactement ce que le vendeur espère."},
{i:"o180_32",u:180,t:"mcq",d:.8,q:"Quelle est la meilleure réponse universelle à un vendeur insistant ?",o:["« Je ne signe jamais le jour même. »","« Je vais demander à ma famille ce soir. »","« Je n'ai pas du tout d'argent en ce moment. »","« Revenez me voir le mois prochain. »"],a:0,w:"C'est une règle personnelle (« je ne... jamais »), difficile à négocier (module 4). Les excuses sur l'argent ou la famille appellent des solutions (« on peut étaler », « appelez-la maintenant »)."}
