/*UNIT*/
{id:182,c:"NON",n:"Module 16",t:"Ton plan de transformation : l'escalier des non",col:"--pink",ic:"🪜",guide:`
<h3>Six mois plus tard</h3>
<div class="gstory">Dernière séance avec Hélène. Tu relis ton carnet. Semaine 1 : « J'ai refusé un prospectus dans la rue. Cœur à 120. » Semaine 3 : « Refusé un verre à Lucas. Il a haussé les épaules, c'est tout. » Semaine 8 : « Conversation DESC avec Julie. Quatre minutes. » Semaine 14 : « Dit non à ma mère pour les trois nuits. Elle m'a serré plus fort. » Semaine 22 : « Aidé Mme Leblanc, oui choisi. » Hélène referme le carnet : « Vous n'êtes pas devenu dur. Vous êtes devenu libre. » Ce dernier module, c'est ton carnet à toi.</div>
<h3>L'escalier des non : l'exposition progressive</h3>
<p>Les thérapies comportementales utilisent l'<b>exposition progressive</b> : on affronte une peur par petites marches, de la plus facile à la plus difficile. Chaque marche réussie apprend au cerveau que le danger était surestimé.</p>
<table><tr><th>Niveau</th><th>Exemples de marches</th></tr>
<tr><td>Facile (1 à 3 sur 10)</td><td>Refuser un prospectus. Dire « non merci » au sac en caisse. Raccrocher à un démarcheur.</td></tr>
<tr><td>Moyen (4 à 6 sur 10)</td><td>Refuser un dernier verre. Proposer à un collègue « 15 h plutôt ». Renvoyer un plat mal cuit.</td></tr>
<tr><td>Difficile (7 à 10 sur 10)</td><td>Avoir la conversation DESC avec Julie. Parler des 500 € à Sophie. Demander l'arbitrage de Karim. Limiter les visites chez tes parents.</td></tr></table>
<div class="gmnemo"><b>« Une marche à la fois, jamais deux d'un coup. »</b> Monte l'escalier des non marche par marche. Et note chaque marche dans ton <b>journal des non</b> : situation, phrase dite, peur prévue sur 10, réalité sur 10. L'écart entre la peur prévue et la réalité est ton meilleur professeur.</div>
<h3>Le journal des non</h3>
<div class="formula">Date | Situation | Ce que j'ai dit | Peur prévue /10 | Ce qui s'est passé | Réalité /10
12/10 | Lucas, dernier verre | « Je m'arrête là » | 7 | Il a haussé les épaules | 2</div>
<p>Tu verras presque toujours la même chose : la peur prévue dépasse largement la réalité. C'est l'erreur de prévision affective (module 11), rendue visible, semaine après semaine.</p>
<h3>Combien de temps pour changer ?</h3>
<p>Une étude de <b>Phillippa Lally</b> et ses collègues (2010) a suivi des personnes qui installaient une nouvelle habitude : il leur a fallu en moyenne <b>66 jours</b> pour qu'elle devienne automatique, avec de grandes différences (de 18 à 254 jours). Un oubli ponctuel ne remettait pas en cause le progrès. Retiens : environ deux mois de pratique régulière, et le droit de rater des jours.</p>
<h3>Quand tu « rechutes » : l'auto-compassion</h3>
<p>Il t'arrivera de dire un oui subi par réflexe. La psychologue <b>Kristin Neff</b> a décrit l'<b>auto-compassion</b> en trois composantes :</p>
<ul><li><b>La bienveillance envers soi</b> : te parler comme à un ami (« c'était difficile, tu feras autrement la prochaine fois »).</li>
<li><b>L'humanité commune</b> : tout le monde a du mal à dire non (77 % ont déjà accepté une invitation non voulue).</li>
<li><b>La pleine conscience</b> : reconnaître l'émotion sans la grossir ni la nier.</li></ul>
<div class="gtrap">Deux pièges pour finir. Le premier : vouloir tout changer d'un coup et commencer par la marche 10 (la conversation avec ta mère). Tu risques un échec qui confirme ta peur, alors commence en bas. Le second : te juger sévèrement à chaque oui subi. La dureté envers soi ne fait pas progresser plus vite, l'auto-compassion, si. Tu n'as pas à être parfait, tu as juste à continuer.</div>
<h3>La carte de tout le cours</h3>
<table><tr><th>Moment</th><th>Outil</th></tr>
<tr><td>Avant de répondre</td><td>Respirer, test E.C.R., nommer le levier (REPAS RU, P.O.C.)</td></tr>
<tr><td>Pour dire non</td><td>Les 4C, « je ne fais pas », le non positif (! . ?), les 3 A en famille</td></tr>
<tr><td>Quand l'autre insiste</td><td>Disque rayé, brouillard, parade « première demande, vrai prix »</td></tr>
<tr><td>Pour une limite durable</td><td>DESC, CNV</td></tr>
<tr><td>Au travail</td><td>« Qu'est-ce que je retire de ma pile ? », Eisenhower</td></tr>
<tr><td>Face aux vendeurs</td><td>S.T.O.P., tes droits</td></tr>
<tr><td>Pour dire oui</td><td>V.D.R.C.E., oui partiel, conditionnel, différé</td></tr></table>
<h3>Ce que tu dois savoir faire à la fin du cours</h3>
<ul><li>Construire ton escalier des non en dix marches</li><li>Tenir un journal des non</li><li>Traverser une rechute avec auto-compassion</li><li>Choisir le bon outil pour chaque situation</li></ul>`},
/*EXOS*/
{i:"o182_01",u:182,t:"sort",d:.2,nw:"L'escalier des non",q:"Classe chaque marche selon sa difficulté.",bins:["Facile","Moyen","Difficile"],it:[["Refuser un prospectus dans la rue",0],["Refuser un dernier verre à Lucas",1],["Conversation DESC avec Julie",2],["Dire « non merci » pour le sac en caisse",0],["Renvoyer un plat mal cuit au restaurant",1],["Parler des 500 € à Sophie",2]],w:"Une marche à la fois, notée dans ton journal des non. Chaque petite victoire apprend à ton cerveau que le danger était surestimé. Tu construis ta confiance comme un muscle."},
{i:"o182_02",u:182,t:"order",d:.25,q:"Remets dans l'ordre les colonnes de ton journal des non.",it:["Date et situation","Ce que j'ai dit","Peur prévue sur 10","Ce qui s'est passé","Réalité sur 10"],w:"L'écart entre peur prévue et réalité est ton meilleur professeur. Semaine après semaine, il te montre que tu peux oser."},
{i:"o182_03",u:182,t:"mcq",d:.25,q:"Selon Lally et ses collègues (2010), combien de jours faut-il en moyenne pour qu'une habitude devienne automatique ?",o:["66 jours","21 jours","7 jours","365 jours"],a:0,w:"66 jours en moyenne, de 18 à 254 selon les personnes. Le mythe des 21 jours est faux. Et un jour raté ne remet pas en cause le progrès."},
{i:"o182_04",u:182,t:"story",d:.25,q:"Tu veux commencer ta transformation. Par quelle marche commences-tu ?",sc:[{who:"Hélène Marchal",txt:"Par où voulez-vous commencer, cette semaine ?"}],o:["« Par les marches faciles : prospectus, sac en caisse, démarcheur. »","« Par la conversation avec ma mère sur Noël, la plus difficile. »","« Par tout en même temps, pour aller plus vite dans la transformation. »","« Par rien pour l'instant, j'attends de me sentir vraiment prêt. »"],a:0,w:"On commence en bas de l'escalier. Commencer par la marche 10 risque un échec qui confirmerait ta peur. Attendre d'être prêt, c'est attendre longtemps : on devient prêt en pratiquant."},
{i:"o182_05",u:182,t:"multi",d:.3,nw:"L'auto-compassion",q:"Quelles sont les trois composantes de l'auto-compassion selon Kristin Neff ?",o:["La bienveillance envers soi","L'humanité commune","La pleine conscience","La sévérité envers soi","L'oubli de ses erreurs"],a:[0,1,2],w:"Te parler comme à un ami, te rappeler que tout le monde a du mal, reconnaître l'émotion sans la grossir. La sévérité ne fait pas progresser plus vite."},
{i:"o182_06",u:182,t:"tf",d:.25,q:"Être dur avec soi-même après un oui subi aide à progresser plus vite.",a:false,w:"La dureté décourage et fait reculer. L'auto-compassion aide à rebondir : « c'était difficile, je ferai autrement la prochaine fois »."},
{i:"o182_07",u:182,t:"num",d:.3,q:"Dans ton journal, ta peur prévue était de 8 sur 10, la réalité de 2 sur 10. De combien de points ta peur a-t-elle surestimé la réalité ?",a:6,tol:0,un:" points",h:"Peur prévue moins réalité",w:"6 points d'écart dans ton journal des non : c'est l'erreur de prévision affective, rendue visible. Note-le, relis-le avant ta prochaine marche."},
{i:"o182_08",u:182,t:"fill",d:.3,q:"L'exposition ___ consiste à affronter une peur par petites étapes, de la plus facile à la plus difficile.",o:["progressive","brutale","ponctuelle","immersive totale"],a:0,w:"Utilisée en thérapie comportementale : chaque étape réussie corrige la peur. C'est exactement l'escalier des non."},
{i:"o182_09",u:182,t:"story",d:.35,q:"Tu as dit un oui subi à Julie par réflexe. Que te dis-tu ?",sc:[{who:"Toi (le soir)",txt:"J'ai encore dit oui sans réfléchir. Je suis nul."}],o:["« Un réflexe ancien, tout le monde en a. Demain : je te réponds à 15 h. »","« Je suis vraiment incapable de changer, autant arrêter tout de suite ce travail. »","« Ce n'est pas grave du tout, je n'ai de toute façon pas besoin de changer. »","« C'est la faute de Julie, elle me manipule, je ne lui parlerai plus jamais. »"],a:0,w:"Bienveillance, humanité commune, et un plan concret. Une rechute fait partie du chemin : ce qui compte, c'est de continuer."},
{i:"o182_10",u:182,t:"match",d:.35,q:"Associe chaque moment au bon outil.",p:[["Avant de répondre","Test E.C.R."],["Quand l'autre insiste","Disque rayé"],["Pour une limite durable","DESC"],["Face à un vendeur","S.T.O.P."]],w:"Chaque situation a son outil. Tu n'as pas besoin de tout maîtriser : un outil bien choisi suffit."},
{i:"o182_11",u:182,t:"tiles",d:.35,q:"Reconstitue la règle de l'escalier.",a:["Une","marche","à","la","fois","jamais","deux","d'un","coup"],dd:["toujours","vite","tout"],w:"La progression lente est la plus rapide. Chaque marche solide porte la suivante."},
{i:"o182_12",u:182,t:"tf",d:.35,q:"Un jour raté ne remet pas en cause la construction d'une habitude.",a:true,w:"L'étude de Lally montre qu'un oubli ponctuel n'empêche pas l'habitude de s'installer. Tu as le droit de rater des jours."},
{i:"o182_13",u:182,t:"story",d:.4,q:"Rappel du module 4 : quelle phrase pour ta première marche (le démarcheur au téléphone) ?",sc:[{who:"Dylan",txt:"Bonjour ! Vous avez deux minutes pour une offre exceptionnelle ?"}],o:["« Non merci, je ne suis pas intéressé. Bonne journée. »","« Euh... là c'est pas trop le moment, mais... peut-être... »","« Vous m'expliquez rapidement et je vous dis si ça m'intéresse ? »","« Comment osez-vous m'appeler sans mon accord, c'est illégal ! »"],a:0,w:"Court, clair, calme, courtois, puis on raccroche. Première marche franchie : note-la dans ton journal des non !"},
{i:"o182_14",u:182,t:"slider",d:.4,q:"Dans l'étude de Lally, quel était le délai maximal observé pour installer une habitude (en jours) ?",min:30,max:365,step:1,a:254,tol:5,pre:"",un:" jours",w:"Jusqu'à 254 jours pour certains, 18 pour d'autres, 66 en moyenne. Chacun son rythme : l'important est la régularité, pas la vitesse."},
{i:"o182_15",u:182,t:"sort",d:.4,q:"Classe chaque pensée après un oui subi : auto-compassion ou dureté ?",bins:["Auto-compassion","Dureté"],it:[["« C'était difficile, je ferai autrement demain »",0],["« Je suis nul, je n'y arriverai jamais »",1],["« Tout le monde a du mal avec ça »",0],["« J'aurais dû savoir, c'est inadmissible »",1],["« Je remarque ma frustration, sans la dramatiser »",0]],w:"Te parler comme à un ami qui apprend. C'est ce qui te permet de remonter sur la marche le lendemain."},
{i:"o182_16",u:182,t:"fill",d:.45,q:"L'écart entre peur prévue et réalité, visible dans le journal, illustre l'erreur de prévision ___.",o:["affective","logique","financière","sociale"],a:0,w:"Wilson et Gilbert (module 11). Le journal transforme cette connaissance théorique en expérience vécue."},
{i:"o182_17",u:182,t:"story",d:.45,q:"Rappel du module 6 : tu arrives à la marche 8, la conversation avec Julie. Quelle phrase prépares-tu ?",sc:[{who:"Toi (brouillon)",txt:"Il faut que je lui parle des dossiers du vendredi..."}],o:["« Huit dossiers le vendredi soir depuis juin. Je suis sous pression. Jeudi 14 h ? »","« Tu me refiles toujours tout le vendredi, tu es vraiment désorganisée, ça ne peut plus durer. »","« Rien, je vais juste faire comme d'habitude et prendre sur moi, ce sera plus simple. »","« Je me sens exploité par toi depuis des mois, tu dois arrêter maintenant, c'est clair ? »"],a:0,w:"DESC en une phrase : faits, ressenti, demande. Tu es prêt, parce que tu as monté les marches d'avant."},
{i:"o182_18",u:182,t:"multi",d:.45,q:"Quels outils utilises-tu face à un vendeur insistant ?",o:["S.T.O.P.","Le disque rayé","La parade « première demande, vrai prix »","Le test E.C.R. au calme","La méthode DESC en magasin"],a:[0,1,2,3],w:"DESC sert aux limites durables avec des proches ou des collègues, pas à un vendeur que tu ne reverras pas."},
{i:"o182_19",u:182,t:"tf",d:.5,q:"On devient « prêt » à dire non en pratiquant, pas en attendant de se sentir prêt.",a:true,w:"La confiance suit l'action, elle la précède rarement. Chaque marche franchie te rend un peu plus prêt pour la suivante."},
{i:"o182_20",u:182,t:"match",d:.5,q:"Associe chaque auteur à son apport dans ce cours.",p:[["Manuel J. Smith","Les droits assertifs et le disque rayé"],["William Ury","Le non positif : Oui ! Non. Oui ?"],["Robert Cialdini","Les 7 leviers d'influence"],["Kristin Neff","L'auto-compassion"]],w:"Les grands noms du cours. Tu peux lire leurs livres pour aller plus loin : chacun t'apportera une nuance de plus."},
{i:"o182_21",u:182,t:"story",d:.55,q:"Rappel du module 10 : à la marche 9, ta mère te culpabilise. Que fais-tu ?",sc:[{who:"Ta mère",txt:"Tu ne viens plus aussi souvent... tu as bien changé, depuis ta coach."}],o:["« J'ai changé, oui : je choisis mieux mon temps. Je tiens à toi. Dimanche ? »","« Arrête de mettre ma coach là-dedans, tu ne comprends rien à ce que je vis. »","« Pardon maman, tu as raison, je vais revenir tous les week-ends comme avant. »","« Non, je n'ai pas changé du tout, c'est juste que j'ai beaucoup de travail. »"],a:0,w:"Brouillard (« j'ai changé, oui »), affection et proposition : les 3 A. Tu assumes ton évolution sans rejeter ta mère."},
{i:"o182_22",u:182,t:"fill",d:.55,q:"Selon Hélène, tu n'es pas devenu dur : tu es devenu ___.",o:["libre","froid","égoïste","méfiant"],a:0,w:"Libre de dire oui, libre de dire non. C'est la vraie transformation que vise ce cours."},
{i:"o182_23",u:182,t:"order",d:.6,q:"Remets dans l'ordre les grandes étapes de ta transformation.",it:["Comprendre pourquoi dire non est dur","Connaître tes droits et tes limites","Apprendre à dire un non clair","Tenir face à l'insistance et à la manipulation","Choisir tes oui","Pratiquer marche après marche"],w:"Comprendre, oser, tenir, choisir, pratiquer : le parcours de ces seize modules."},
{i:"o182_24",u:182,t:"story",d:.6,q:"Rappel du module 12 : à la marche 7, Karim te confie un dossier. Quelle phrase ?",sc:[{who:"Karim",txt:"Tu prends aussi le dossier Lambert ?"}],o:["« Avec plaisir. Qu'est-ce que je retire de ma pile pour faire de la place ? »","« Non, j'ai déjà trop de travail, et tu le sais très bien, Karim. »","« Oui, bien sûr, je me débrouillerai, comme d'habitude, pas de souci. »","« Je vais voir, peut-être, si j'ai le temps, on en reparlera plus tard. »"],a:0,w:"La question magique. Elle rend visible le coût et fait arbitrer celui qui en a le pouvoir. Karim a déjà appris à y répondre."},
{i:"o182_25",u:182,t:"sort",d:.65,q:"Classe chaque outil dans sa famille.",bins:["Dire non","Tenir le non","Limite durable","Dire oui"],it:[["Les 4C",0],["Le disque rayé",1],["DESC",2],["V.D.R.C.E.",3],["Le non positif",0],["Le brouillard",1],["La CNV",2],["Le oui partiel",3]],w:"Quatre familles d'outils. Ensemble, elles te donnent toute la palette, du grand oui au non tranquille."},
{i:"o182_26",u:182,t:"tf",d:.65,q:"L'objectif final du cours est de ne plus jamais ressentir le moindre malaise en disant non.",a:false,w:"Le malaise peut rester un peu, surtout avec les proches. L'objectif, c'est qu'il ne décide plus à ta place. Tu peux ressentir un pincement et dire non quand même."},
{i:"o182_27",u:182,t:"story",d:.7,q:"Rappel du module 8 : à la salle de sport, Dylan recommence. Que fais-tu désormais ?",sc:[{who:"Dylan",txt:"Offre exceptionnelle -50 %, uniquement aujourd'hui, pour les membres fidèles comme toi !"}],o:["Je nomme le levier (rareté, unité) : « Je ne signe jamais le jour même. »","Je signe vite, -50 % c'est une vraie occasion à ne surtout pas rater","Je lui explique longuement pourquoi je ne veux pas signer aujourd'hui","Je le traite de manipulateur devant tous les autres membres présents"],a:0,w:"Nommer le levier, puis S.T.O.P. Tu reconnais maintenant ces techniques au premier mot : c'est ta nouvelle liberté."},
{i:"o182_28",u:182,t:"multi",d:.7,q:"Quels signes montrent que ta transformation est en cours ?",o:["Tu prends une respiration avant de répondre","Tes non sont plus courts et plus calmes","Tu dis des grands oui avec plaisir","Tu te pardonnes tes rechutes","Tu refuses tout par principe"],a:[0,1,2,3],w:"Pause, clarté, générosité choisie, douceur envers toi. Refuser tout par principe serait un nouveau balancier, pas une transformation."},
{i:"o182_29",u:182,t:"fill",d:.75,q:"Le mythe des 21 jours pour une habitude est faux : la moyenne observée par Lally est de ___ jours.",o:["66","21","40","100"],a:0,w:"66 jours, soit environ deux mois de pratique régulière. Sois patient avec toi-même."},
{i:"o182_30",u:182,t:"story",d:.75,q:"Hélène te demande ce que tu dirais à quelqu'un qui commence ce cours. Quelle réponse est la plus juste ?",sc:[{who:"Hélène Marchal",txt:"Quel conseil donneriez-vous à celui qui commence ?"}],o:["« Commence par un petit non, note-le, et sois doux avec toi. La peur ment. »","« Force-toi à refuser tout ce qu'on te demande pendant un mois entier. »","« Lis tous les livres cités avant d'oser dire le moindre non à quelqu'un. »","« Ne change rien, les gens n'aiment pas du tout ceux qui disent non. »"],a:0,w:"Une marche, un journal, de l'auto-compassion. Et cette phrase, qui résume les études vues : la peur ment, la réalité est plus douce."},
{i:"o182_31",u:182,t:"tiles",d:.8,q:"Reconstitue la phrase finale d'Hélène.",a:["Tu","n'es","pas","devenu","dur","tu","es","devenu","libre"],dd:["égoïste","froid","méchant"],w:"Libre de choisir. C'est tout le sens de ces seize modules."},
{i:"o182_32",u:182,t:"mcq",d:.8,q:"Quelle est la phrase qui résume le mieux tout le cours ?",o:["Le but n'est pas de dire non, mais de choisir","Il faut toujours dire non pour être respecté","Il faut toujours dire oui pour être aimé","Il faut éviter toutes les demandes des autres"],a:0,w:"Choisir : un grand oui, un oui partiel, un non tranquille. Tu as maintenant les outils, les droits et l'entraînement. Il te reste à monter l'escalier, marche après marche."}
