/*UNIT*/
{id:233,c:"TENNIS",n:"Module 3",t:"Le croisé et les zones : jouer avec de la marge",col:"--gold",ic:"🎯",guide:`
<h3>Le seau de balles de Valérie</h3>
<div class="gstory">Samedi matin, court n° 3. Valérie pose deux cerceaux : l'un à un mètre de la ligne de côté, l'autre en plein milieu du fond de court. « Nathan, vingt coups droits dans le cerceau du couloir. » Il en réussit six, et en met huit dehors. « Maintenant, vingt dans l'autre, en croisé, à un mètre et demi au-dessus du filet. » Quinze réussis, une seule faute. Valérie sourit : « Tu viens de gagner neuf points sans frapper plus fort. Voilà ce que j'appelle jouer avec de la marge. »</div>
<h3>Pourquoi le croisé est la base</h3>
<table><tr><th>Avantage du croisé</th><th>Chiffre</th></tr>
<tr><td>Le filet est plus bas au centre</td><td>0,914 m contre 1,07 m aux poteaux</td></tr>
<tr><td>La diagonale est plus longue que la ligne droite</td><td>environ <b>25,15 m</b> en simple, d'un coin à l'autre, contre <b>23,77 m</b> en long de ligne</td></tr>
<tr><td>On reste au centre de sa zone après la frappe</td><td>moins de course pour revenir</td></tr>
<tr><td>On ouvre l'angle</td><td>l'adversaire sort du terrain</td></tr></table>
<div class="gsvg-wrap"><svg class='gsvg' viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Croisé (plein), ligne (pointillé)</text><circle cx='92' cy='178' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><line x1='92.0' y1='174.0' x2='48.0' y2='30.0' stroke='var(--gold)' stroke-width='1.8'/><polygon points='48.0,30.0 51.8,34.6 47.4,36.0' fill='var(--gold)'/><line x1='92.0' y1='174.0' x2='94.0' y2='30.0' stroke='var(--pink)' stroke-width='1.8' stroke-dasharray='3 2'/><polygon points='94.0,30.0 96.3,35.6 91.6,35.5' fill='var(--pink)'/></svg></div>
<p>Le <b>long de ligne</b> passe au-dessus de la partie haute du filet, sur une distance plus courte, et laisse le côté opposé ouvert si la balle revient croisée. On l'utilise pour <b>changer de direction</b> quand on contrôle l'échange, jamais par impatience.</p>
<h3>Les trois zones du joueur</h3>
<div class="gsvg-wrap"><svg class='gsvg' viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Les trois zones du joueur</text><rect x='25' y='186' width='90' height='13' fill='var(--red)' opacity='.7'/><text x='70' y='195.5' font-size='7' fill='var(--bg)' text-anchor='middle' font-weight='700'>défense</text><rect x='31' y='160' width='78' height='24' fill='var(--gold)' opacity='.45'/><text x='70' y='175' font-size='7' fill='var(--bg)' text-anchor='middle' font-weight='700'>neutre</text><rect x='31' y='118' width='78' height='40' fill='var(--green)' opacity='.5'/><text x='70' y='141' font-size='7' fill='var(--bg)' text-anchor='middle' font-weight='700'>attaque</text></svg></div>
<ul><li><b>Défense</b> (loin derrière la ligne de fond) : on joue haut, long et au centre pour gagner du temps.</li>
<li><b>Neutre</b> (autour de la ligne de fond) : on construit, on joue croisé et profond, on attend la balle courte.</li>
<li><b>Attaque</b> (dans le terrain) : on accélère, on change de direction, on monte au filet.</li></ul>
<p>La règle se résume ainsi : <b>la position de l'adversaire et la qualité de la balle reçue décident du coup</b>, pas l'envie du moment.</p>
<h3>Les cinq situations de jeu</h3>
<p>Tout point se joue dans l'une de ces situations : <b>servir</b>, <b>retourner</b>, <b>jouer du fond</b>, <b>attaquer ou monter au filet</b>, <b>défendre contre un joueur au filet</b> (passing, lob). Chacune a ses priorités.</p>
<div class="gmnemo"><b>« Croisé pour construire, long de ligne pour conclure. »</b> Et pour la marge : <b>« un mètre dedans, un mètre au-dessus »</b> : viser un mètre à l'intérieur des lignes et passer au moins un mètre au-dessus du filet en échange.</div>
<div class="gtrap">Idée reçue : « un bon joueur vise les lignes ». Faux : les pros visent des zones à un ou deux mètres des lignes, et la balle y termine parfois par dispersion. Autre piège : croire que le long de ligne est plus sûr parce qu'il est « plus direct ». Il passe au-dessus d'un filet plus haut, sur moins de longueur.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Justifier le croisé par le filet et la longueur</li><li>Choisir le coup selon sa zone</li><li>Savoir quand changer de direction</li><li>Donner les marges de sécurité</li></ul>`},
/*EXOS*/
{i:"t233_01",u:233,t:"story",d:.2,nw:"Le croisé",q:"Nathan veut tout jouer le long de la ligne pour « surprendre ». Que lui dit Valérie ?",sc:[{who:"Nathan",txt:"Le long de ligne, c'est plus direct, donc plus sûr."}],o:["« Il passe sur un filet plus haut, avec moins de distance : c'est moins sûr. »","« Il est interdit de jouer long de ligne plus de trois fois par jeu en match. »","« Il est plus sûr, mais il fatigue beaucoup plus le bras que le croisé. »","« Il est plus sûr, mais les arbitres le comptent faute plus souvent. »"],a:0,w:"Croisé pour construire, long de ligne pour conclure : la ligne droite est plus courte et le filet plus haut."},
{i:"t233_02",u:233,t:"slider",d:.2,q:"Longueur approximative de la diagonale en simple, d'un coin à l'autre (en m) ?",min:20,max:30,step:.1,a:25.15,tol:.3,pre:"",un:" m",w:"Environ 25,15 m, contre 23,77 m en long de ligne : près d'un mètre et demi de plus pour que la balle retombe dans le terrain."},
{i:"t233_03",u:233,t:"sort",d:.25,q:"Classe chaque action dans la bonne zone.",bins:["Défense","Neutre","Attaque"],it:[["Jouer haut et au centre, loin derrière la ligne",0],["Construire en croisé profond",1],["Accélérer long de ligne sur une balle courte",2],["Gagner du temps avec une balle lobée",0],["Monter au filet après une approche",2]],w:"La position et la balle reçue décident du coup."},
{i:"t233_04",u:233,t:"fill",d:.25,q:"Croisé pour construire, long de ligne pour ___.",o:["conclure","défendre","servir","attendre"],a:0,w:"On change de direction quand on contrôle l'échange, pas par impatience."},
{i:"t233_05",u:233,t:"mcq",d:.3,q:"Sur ce schéma, quelle frappe passe au-dessus du point bas du filet ?",svg:"<svg viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Deux frappes depuis le fond</text><circle cx='92' cy='178' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><line x1='92.0' y1='174.0' x2='48.0' y2='30.0' stroke='var(--gold)' stroke-width='1.8'/><polygon points='48.0,30.0 51.8,34.6 47.4,36.0' fill='var(--gold)'/><line x1='92.0' y1='174.0' x2='94.0' y2='30.0' stroke='var(--pink)' stroke-width='1.8' stroke-dasharray='3 2'/><polygon points='94.0,30.0 96.3,35.6 91.6,35.5' fill='var(--pink)'/></svg>",o:["La flèche pleine","La flèche en pointillé","Aucune des deux flèches","Les deux flèches autant"],a:0,w:"Le croisé traverse le centre, là où le filet ne fait que 0,914 m."},
{i:"t233_06",u:233,t:"tf",d:.3,q:"Les joueurs professionnels visent le plus souvent directement les lignes.",a:false,w:"Ils visent des zones à un ou deux mètres des lignes : un mètre dedans, un mètre au-dessus."},
{i:"t233_07",u:233,t:"story",d:.3,q:"Clara est à trois mètres derrière sa ligne, débordée. Quel coup lui conseilles-tu ?",sc:[{who:"Clara",txt:"J'ai envie de tenter le coup gagnant long de ligne."}],o:["« Une balle haute et longue au centre, pour revenir en place. »","« Le long de ligne à plat, c'est le moment de surprendre ton adversaire. »","« Une amortie, car ton adversaire ne s'y attend pas du tout. »","« Une balle très courte et croisée, pour ouvrir encore plus l'angle. »"],a:0,w:"En zone de défense, on gagne du temps : haut, long, au centre."},
{i:"t233_08",u:233,t:"multi",d:.35,q:"Quels sont les avantages du croisé ?",o:["Le filet est plus bas au centre","La diagonale est plus longue","On reste mieux placé après la frappe","On ouvre l'angle","La balle va forcément plus vite"],a:[0,1,2,3],w:"La vitesse dépend de la frappe, pas de la direction."},
{i:"t233_09",u:233,t:"order",d:.35,q:"Remets dans l'ordre la construction classique d'un point.",it:["Croisé profond pour construire","Balle courte de l'adversaire","Accélération long de ligne","Montée ou coup gagnant"],w:"Construire, provoquer la balle courte, changer de direction, conclure."},
{i:"t233_10",u:233,t:"match",d:.35,q:"Associe chaque situation de jeu à sa priorité.",p:[["Servir","Prendre l'initiative"],["Retourner","Remettre la balle en jeu"],["Jouer du fond","Construire avec de la marge"],["Défendre contre un volleyeur","Passing ou lob"]],w:"Les cinq situations : servir, retourner, fond de court, attaquer, défendre contre le filet."},
{i:"t233_11",u:233,t:"tiles",d:.4,q:"Reconstitue la règle des marges.",a:["un","mètre","dedans","un","mètre","au-dessus"],dd:["centimètre","sur","ligne"],w:"Viser un mètre à l'intérieur des lignes, passer un mètre au-dessus du filet."},
{i:"t233_12",u:233,t:"story",d:.4,q:"Malik reçoit une balle courte et haute au milieu de son terrain. Que fait-il ?",sc:[{who:"Malik",txt:"Je rejoue croisé pour être prudent ?"}],o:["« Non : zone d'attaque, tu accélères et tu changes de direction. »","« Oui : on joue toujours croisé, même sur les balles courtes du milieu. »","« Non : tu recules derrière ta ligne pour laisser la balle redescendre. »","« Oui : et tu restes derrière ta ligne de fond pendant tout l'échange. »"],a:0,w:"Balle courte = zone d'attaque : on accélère, souvent long de ligne, et on peut monter."},
{i:"t233_13",u:233,t:"num",d:.45,q:"Nathan réussit 6 coups sur 20 le long de la ligne, puis 15 sur 20 en croisé. Combien de balles de plus en jeu ?",a:9,tol:0,un:" balles",h:"15 moins 6",w:"9 balles de plus sans frapper plus fort : la marge gagne des points."},
{i:"t233_14",u:233,t:"fill",d:.45,q:"En zone de défense, on joue haut, long et au ___.",o:["centre","filet","couloir","service"],a:0,w:"Le centre réduit les angles de l'adversaire et laisse le temps de revenir."},
{i:"t233_15",u:233,t:"tf",d:.45,q:"Changer de direction sur une balle difficile est une prise de risque inutile.",a:true,w:"On change de direction sur une balle qu'on contrôle : sinon, on renvoie dans la même direction ou au centre."},
{i:"t233_16",u:233,t:"mcq",d:.5,q:"Pourquoi le long de ligne laisse-t-il un trou dans son propre camp ?",o:["La réponse croisée part vers le côté ouvert","Le filet se relève après chaque long de ligne","L'arbitre inverse les côtés après ce coup","On doit reculer pour laisser passer la balle"],a:0,w:"Après un long de ligne, l'adversaire peut répondre croisé, loin de toi : il faut que le coup fasse mal."},
{i:"t233_17",u:233,t:"story",d:.5,q:"Rappel du module 1 : Clara demande pourquoi viser un mètre à l'intérieur si « la ligne est bonne ».",sc:[{who:"Clara",txt:"La ligne compte, alors je la vise !"}],o:["« La viser, c'est accepter qu'une balle sur deux sorte. »","« Parce que la ligne n'est bonne qu'en double, jamais en simple. »","« Parce que l'arbitre ne voit jamais les balles sur les lignes. »","« Parce que viser la ligne est interdit dans les tournois FFT. »"],a:0,w:"Ta frappe se disperse autour du point visé : viser la ligne met la moitié de la dispersion dehors."},
{i:"t233_18",u:233,t:"sort",d:.55,q:"Balle reçue : faut-il construire ou attaquer ?",bins:["Construire","Attaquer"],it:[["Balle profonde qui te repousse",0],["Balle courte et haute",1],["Adversaire déjà hors du terrain",1],["Balle rapide dans tes pieds",0],["Balle molle au milieu du carré de service",1]],w:"La qualité de la balle reçue décide : on attaque les balles courtes, on construit sur les balles difficiles."},
{i:"t233_19",u:233,t:"slider",d:.55,q:"À quelle hauteur minimale au-dessus du filet faut-il passer en échange de fond de court (en m) ?",min:0,max:3,step:.1,a:1,tol:.2,pre:"",un:" m",w:"Environ un mètre au-dessus du filet : la balle va plus loin et le filet ne te coûte plus de points."},
{i:"t233_20",u:233,t:"multi",d:.6,q:"Quelles sont les cinq situations de jeu ?",o:["Servir","Retourner","Jouer du fond","Attaquer et monter","Défendre contre le filet","Ramasser les balles"],a:[0,1,2,3,4],w:"Tout point se joue dans l'une de ces cinq situations."},
{i:"t233_21",u:233,t:"story",d:.6,q:"L'adversaire de Nathan est collé au couloir gauche après un croisé. Quelle cible choisit Nathan ?",sc:[{who:"Nathan",txt:"Je le renvoie au même endroit ?"}],o:["« L'espace ouvert de l'autre côté : tu as créé le trou, alors profites-en. »","« Au même endroit, trois fois de suite, pour user son moral de joueur. »","« Au centre, sinon tu risques de le réveiller et de perdre le point. »","« Une chandelle au centre, pour lui laisser le temps de revenir. »"],a:0,w:"Croisé pour ouvrir, puis on joue dans l'espace libre : c'est la construction du point."},
{i:"t233_22",u:233,t:"mcq",d:.65,q:"Qu'est-ce qui décide du coup à jouer ?",o:["Sa zone et la qualité de la balle reçue","Son coup préféré du jour","Le score du court voisin","L'envie du moment présent"],a:0,w:"La position et la balle reçue décident, pas l'humeur."},
{i:"t233_23",u:233,t:"tf",d:.65,q:"Le croisé permet de rester plus près du centre de sa zone après la frappe.",a:true,w:"Après un croisé, l'adversaire répond souvent croisé : tu as moins de course pour couvrir."},
{i:"t233_24",u:233,t:"fill",d:.7,q:"Le filet mesure ___ m au centre.",o:["0,914","1,070","1,200","0,800"],a:0,w:"91,4 cm au centre, 1,07 m aux poteaux (rappel du module 1)."},
{i:"t233_25",u:233,t:"match",d:.7,q:"Associe chaque zone à son coup type.",p:[["Défense","Balle haute au centre"],["Neutre","Croisé profond"],["Attaque","Accélération long de ligne"],["Filet","Volée dans l'espace"]],w:"Chaque zone a son coup : défendre, construire, attaquer, conclure."},
{i:"t233_26",u:233,t:"story",d:.75,q:"Rappel du module 2 : Nathan, frustré de ses fautes, veut « tout jouer à fond » pour monter au classement. Ta réponse ?",sc:[{who:"Nathan",txt:"Plus je frappe fort, plus je gagne, non ?"}],o:["« Avec de la marge, tu gagnes plus de matchs, donc plus de points. »","« Oui, le classement FFT donne des points bonus pour les coups gagnants. »","« Oui, la vitesse de balle est comptée dans le calcul du classement FFT. »","« Non, car le classement ne compte que les matchs perdus en trois sets. »"],a:0,w:"Le classement compte les victoires ; les victoires viennent des points gagnés, et la marge en fait gagner plus."},
{i:"t233_27",u:233,t:"num",d:.75,q:"Différence entre la diagonale (25,15 m) et le long de ligne (23,77 m), en centimètres ?",a:138,tol:3,un:" cm",h:"25,15 moins 23,77",w:"Environ 1,38 m de plus pour que la balle retombe : c'est la marge offerte par le croisé."},
{i:"t233_28",u:233,t:"tiles",d:.8,q:"Reconstitue le principe du choix de coup.",a:["la","balle","reçue","décide","du","coup"],dd:["humeur","jamais","public"],w:"La qualité de la balle reçue et ta position décident de ce que tu peux jouer."},
{i:"t233_29",u:233,t:"mcq",d:.8,q:"Quand le long de ligne est-il le bon choix ?",o:["Sur une balle qu'on contrôle, pour conclure","Dès qu'on est en défense, pour surprendre","Sur une balle rapide reçue dans les pieds","Quand on est loin derrière sa ligne de fond"],a:0,w:"Long de ligne pour conclure, sur une balle confortable."},
{i:"t233_30",u:233,t:"sort",d:.85,q:"Classe chaque affirmation : vraie ou idée reçue ?",bins:["Vraie","Idée reçue"],it:[["Les pros visent les lignes",1],["Le croisé passe au-dessus du point bas du filet",0],["Le long de ligne est plus sûr car plus direct",1],["La marge fait gagner des points",0]],w:"Deux idées reçues corrigées dans le guide."},
{i:"t233_31",u:233,t:"story",d:.85,q:"Clara perd ses échanges en tentant des amorties depuis le fond. Que proposes-tu ?",sc:[{who:"Clara",txt:"J'aime bien surprendre."}],o:["« Construis en croisé profond, garde l'amortie pour les balles courtes. »","« Fais encore plus d'amorties, ton adversaire finira par se fatiguer. »","« Arrête de courir et joue toutes les balles au centre à plat, fort. »","« Joue uniquement des lobs, même quand ton adversaire est au fond. »"],a:0,w:"L'amortie se joue depuis la zone d'attaque, sur un adversaire loin derrière."},
{i:"t233_32",u:233,t:"story",d:.9,q:"Synthèse : Valérie demande à Malik de résumer la tactique de base.",sc:[{who:"Valérie",txt:"En une phrase ?"}],o:["« Croisé pour construire, long de ligne pour conclure, toujours avec de la marge. »","« Frapper le plus fort possible sur chaque balle, sans jamais réfléchir. »","« Viser les lignes sur chaque coup pour gagner les points plus vite. »","« Jouer toujours au même endroit, quelle que soit la balle reçue. »"],a:0,w:"Un mètre dedans, un mètre au-dessus, et la balle reçue décide du coup."}
