/*UNIT*/
{id:234,c:"TENNIS",n:"Module 4",t:"Le service : placer avant de cogner",col:"--gold",ic:"🚀",guide:`
<h3>Le radar de Malik</h3>
<div class="gstory">Mardi, 18 h 30. Malik, gaucher, a installé un radar sur son téléphone : 185 km/h ! Mais il perd son match du dimanche 6-4, 6-3, avec 11 doubles fautes et seulement 48 % de premières balles. Valérie pose trois plots dans le carré de service : un près du T, un au centre du carré, un près du couloir. « Tu sers vite. Maintenant, apprends à servir juste. Ton adversaire ne craint pas ta vitesse, il craint de ne pas savoir où ça va. »</div>
<h3>Les trois cibles</h3>
<div class="gsvg-wrap"><svg class='gsvg' viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Côté égalité : T, Corps, Ext.</text><circle cx='78' cy='188' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><line x1='78.0' y1='184.0' x2='68.0' y2='68.0' stroke='var(--gold)' stroke-width='1.8'/><polygon points='68.0,68.0 70.8,73.3 66.1,73.7' fill='var(--gold)'/><circle cx='66' cy='62' r='4.8' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/><text x='66' y='64.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>T</text><line x1='78.0' y1='184.0' x2='55.5' y2='74.0' stroke='var(--gold)' stroke-width='1.8'/><polygon points='55.5,74.0 58.9,78.9 54.3,79.9' fill='var(--gold)'/><circle cx='55.5' cy='68' r='4.8' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/><text x='55.5' y='70.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>C</text><line x1='78.0' y1='184.0' x2='45.0' y2='80.0' stroke='var(--gold)' stroke-width='1.8'/><polygon points='45.0,80.0 48.9,84.6 44.4,86.0' fill='var(--gold)'/><circle cx='45' cy='74' r='4.8' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/><text x='45' y='76.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>E</text></svg></div>
<table><tr><th>Cible</th><th>Pourquoi</th></tr>
<tr><td><b>T</b> (au centre, près de la ligne médiane)</td><td>Filet plus bas, distance plus courte, angle fermé pour le retour</td></tr>
<tr><td><b>Corps</b> (sur le relanceur)</td><td>Il doit se décaler : retour gêné, souvent court</td></tr>
<tr><td><b>Extérieur</b> (vers le couloir)</td><td>Sort le relanceur du terrain et ouvre le court pour le coup suivant</td></tr></table>
<p>On sert du côté <b>égalité</b> (à droite) quand le total des points du jeu est pair (0-0, 15-15, 30-0) et du côté <b>avantage</b> (à gauche) quand il est impair. On alterne le service à chaque jeu.</p>
<h3>Les trois effets</h3>
<ul><li><b>Plat</b> : le plus rapide, le moins sûr. Idéal au T en première balle.</li>
<li><b>Slicé</b> : la balle tourne sur le côté. Pour un droitier, il fuit vers l'extérieur côté égalité ; pour un <b>gaucher</b>, il fuit vers l'extérieur côté <b>avantage</b>, sur le revers d'un droitier.</li>
<li><b>Lifté (kick)</b> : la balle monte haut au rebond. C'est la <b>deuxième balle</b> de référence : grande marge au-dessus du filet, rebond haut sur le revers.</li></ul>
<h3>Première et deuxième balle en chiffres</h3>
<p>Chez les professionnels, on gagne environ <b>70 à 75 %</b> des points quand la première balle passe, et environ <b>50 %</b> seulement sur la deuxième. Le serveur a donc intérêt à passer beaucoup de premières balles (autour de <b>60 à 65 %</b>) plutôt qu'à en passer peu très vite.</p>
<div class="formula">Points gagnés au service = (% premières × % gagnés sur première) + (% deuxièmes × % gagnés sur deuxième)</div>
<p>Le coup qui suit le service s'appelle le <b>service + 1</b> : un service extérieur prépare un coup droit dans le terrain ouvert. Avec le retour, ce sont les deux premiers coups du point, là où tout se décide (module 8).</p>
<div class="gmnemo"><b>« T, Corps, Extérieur : TCE, Tu Changes Encore. »</b> Varie les cibles pour que le relanceur ne puisse jamais anticiper. Et pour la deuxième balle : <b>« haut, lifté, sur le revers »</b>.</div>
<div class="gtrap">Idée reçue : « la vitesse fait le bon service ». Faux : le placement et la variété comptent davantage chez les amateurs, et les doubles fautes coûtent des points gratuits. Autre piège : ralentir sa deuxième balle en la « poussant » sans effet. Une deuxième balle sûre se frappe avec de la vitesse de raquette, mais transformée en effet lifté.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Choisir la cible selon le côté et le relanceur</li><li>Choisir l'effet selon la balle (première ou deuxième)</li><li>Calculer le rendement au service</li><li>Préparer le service + 1</li></ul>`},
/*EXOS*/
{i:"t234_01",u:234,t:"story",d:.2,nw:"Le service",q:"Malik, fier de ses 185 km/h, ne comprend pas sa défaite. Que lui dit Valérie ?",sc:[{who:"Malik",txt:"Je sers le plus vite du club !"}],o:["« 48 % de premières et 11 doubles fautes : ta vitesse t'a coûté le match. »","« Il faut servir encore plus vite, au-delà de 200 km/h, pour gagner. »","« La vitesse ne compte pas du tout, seul le lancer de balle compte. »","« Il faut arrêter de servir en première balle et tout jouer à la cuillère. »"],a:0,w:"Placer avant de cogner : le relanceur craint de ne pas savoir où va le service, pas la vitesse seule."},
{i:"t234_02",u:234,t:"mcq",d:.2,q:"Quelle cible est indiquée par le point d'interrogation ?",svg:"<svg viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Quel placement ?</text><circle cx='78' cy='188' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><line x1='78.0' y1='184.0' x2='68.0' y2='68.0' stroke='var(--gold)' stroke-width='1.8'/><polygon points='68.0,68.0 70.8,73.3 66.1,73.7' fill='var(--gold)'/><circle cx='66' cy='62' r='4.8' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/><text x='66' y='64.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>?</text><line x1='78.0' y1='184.0' x2='55.5' y2='74.0' stroke='var(--dim2)' stroke-width='1.8' stroke-dasharray='3 2'/><polygon points='55.5,74.0 58.9,78.9 54.3,79.9' fill='var(--dim2)'/><circle cx='55.5' cy='68' r='4.8' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1'/><text x='55.5' y='70.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>C</text><line x1='78.0' y1='184.0' x2='45.0' y2='80.0' stroke='var(--dim2)' stroke-width='1.8' stroke-dasharray='3 2'/><polygon points='45.0,80.0 48.9,84.6 44.4,86.0' fill='var(--dim2)'/><circle cx='45' cy='74' r='4.8' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1'/><text x='45' y='76.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>E</text></svg>",o:["Le T","Le corps","L'extérieur","Le couloir de double"],a:0,w:"Le T, près de la ligne médiane : filet plus bas, distance plus courte, angle fermé."},
{i:"t234_03",u:234,t:"mcq",d:.25,q:"Sur ce service, où vise le serveur ?",svg:"<svg viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Quel placement ?</text><circle cx='78' cy='188' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><line x1='78.0' y1='184.0' x2='68.0' y2='68.0' stroke='var(--dim2)' stroke-width='1.8' stroke-dasharray='3 2'/><polygon points='68.0,68.0 70.8,73.3 66.1,73.7' fill='var(--dim2)'/><circle cx='66' cy='62' r='4.8' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1'/><text x='66' y='64.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>T</text><line x1='78.0' y1='184.0' x2='55.5' y2='74.0' stroke='var(--dim2)' stroke-width='1.8' stroke-dasharray='3 2'/><polygon points='55.5,74.0 58.9,78.9 54.3,79.9' fill='var(--dim2)'/><circle cx='55.5' cy='68' r='4.8' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1'/><text x='55.5' y='70.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>C</text><line x1='78.0' y1='184.0' x2='45.0' y2='80.0' stroke='var(--gold)' stroke-width='1.8'/><polygon points='45.0,80.0 48.9,84.6 44.4,86.0' fill='var(--gold)'/><circle cx='45' cy='74' r='4.8' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/><text x='45' y='76.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>?</text></svg>",o:["L'extérieur","Le T","Le corps","La ligne de fond"],a:0,w:"L'extérieur sort le relanceur du terrain et ouvre le court pour le service + 1."},
{i:"t234_04",u:234,t:"mcq",d:.25,q:"Et sur celui-ci, quelle zone est visée ?",svg:"<svg viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Quel placement ?</text><circle cx='78' cy='188' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><line x1='78.0' y1='184.0' x2='68.0' y2='68.0' stroke='var(--dim2)' stroke-width='1.8' stroke-dasharray='3 2'/><polygon points='68.0,68.0 70.8,73.3 66.1,73.7' fill='var(--dim2)'/><circle cx='66' cy='62' r='4.8' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1'/><text x='66' y='64.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>T</text><line x1='78.0' y1='184.0' x2='55.5' y2='74.0' stroke='var(--gold)' stroke-width='1.8'/><polygon points='55.5,74.0 58.9,78.9 54.3,79.9' fill='var(--gold)'/><circle cx='55.5' cy='68' r='4.8' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/><text x='55.5' y='70.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>?</text><line x1='78.0' y1='184.0' x2='45.0' y2='80.0' stroke='var(--dim2)' stroke-width='1.8' stroke-dasharray='3 2'/><polygon points='45.0,80.0 48.9,84.6 44.4,86.0' fill='var(--dim2)'/><circle cx='45' cy='74' r='4.8' fill='var(--dim2)' stroke='var(--bg)' stroke-width='1'/><text x='45' y='76.6' font-size='6' fill='var(--bg)' text-anchor='middle' font-weight='700'>E</text></svg>",o:["Le corps","Le T","L'extérieur","Le filet"],a:0,w:"Le service dans le corps oblige le relanceur à se décaler : le retour est souvent court."},
{i:"t234_05",u:234,t:"fill",d:.3,q:"La deuxième balle de référence est le service ___.",o:["lifté","plat","coupé","lobé"],a:0,w:"Haut, lifté, sur le revers : grande marge au-dessus du filet et rebond haut."},
{i:"t234_06",u:234,t:"tf",d:.3,q:"À 30-15, le serveur sert du côté avantage (à gauche).",a:true,w:"30-15 fait trois points joués, un total impair : côté avantage. Pair (0-0, 15-15, 30-0) : côté égalité."},
{i:"t234_07",u:234,t:"story",d:.3,q:"Clara pousse sa deuxième balle sans effet et se fait attaquer. Que lui conseilles-tu ?",sc:[{who:"Clara",txt:"J'ai peur de la double faute."}],o:["« Garde de la vitesse de raquette, mais transforme-la en effet lifté. »","« Ralentis encore ton bras pour être sûre de mettre la balle dedans. »","« Sers la deuxième balle à plat, aussi fort que ta première balle. »","« Sers les yeux fermés pour relâcher la pression pendant le geste. »"],a:0,w:"L'effet fait redescendre la balle : c'est lui qui donne la sécurité, pas la lenteur."},
{i:"t234_08",u:234,t:"num",d:.35,q:"Un serveur passe 60 % de premières et en gagne 75 % ; il gagne 50 % sur la deuxième. Quel pourcentage des points de service gagne-t-il ?",a:65,tol:0,un:" %",h:"0,6 × 75 + 0,4 × 50",w:"45 + 20 = 65 %. Passer plus de premières balles fait monter ce chiffre."},
{i:"t234_09",u:234,t:"match",d:.35,q:"Associe chaque effet à sa caractéristique.",p:[["Plat","Le plus rapide, le moins sûr"],["Slicé","Tourne et fuit sur le côté"],["Lifté","Rebond haut, grande marge"],["Service à la cuillère","Surprise, par en dessous"]],w:"Plat au T en première, slicé pour l'angle, lifté en deuxième."},
{i:"t234_10",u:234,t:"sort",d:.35,q:"Côté égalité ou côté avantage ?",bins:["Égalité (droite)","Avantage (gauche)"],it:[["0-0",0],["15-0",1],["15-15",0],["40-15",1],["30-30",0],["Avantage serveur",1]],w:"Total de points pair : égalité ; impair : avantage. À l'avantage, on sert toujours à gauche."},
{i:"t234_11",u:234,t:"story",d:.4,q:"Malik, gaucher, sert côté avantage contre un droitier au revers fragile. Quel service choisit-il ?",sc:[{who:"Malik",txt:"J'ai une balle de jeu."}],o:["« Le slicé extérieur : il fuit vers son revers et l'éjecte loin du terrain. »","« Le service à plat au T, c'est toujours le plus efficace des services. »","« Le lifté dans le coup droit, pour lui donner une balle confortable. »","« Le service à la cuillère, parce qu'il ne s'y attendra jamais du tout. »"],a:0,w:"L'arme du gaucher : le slicé côté avantage, qui fuit sur le revers d'un droitier."},
{i:"t234_12",u:234,t:"tiles",d:.4,q:"Reconstitue le moyen de retenir les cibles.",a:["T","Corps","Extérieur","Tu","Changes","Encore"],dd:["Toujours","Centre","Pareil"],w:"Varier les cibles empêche le relanceur d'anticiper."},
{i:"t234_13",u:234,t:"multi",d:.45,q:"Quels sont les atouts du service au T ?",o:["Le filet est plus bas","La distance est plus courte","L'angle du retour est fermé","La balle sort forcément du terrain","Il ouvre toujours le coup droit adverse"],a:[0,1,2],w:"Le T est au centre : filet bas, distance courte, angle réduit pour le relanceur."},
{i:"t234_14",u:234,t:"fill",d:.45,q:"Le coup qui suit le service s'appelle le service ___.",o:["+ 1","bis","retour","décalé"],a:0,w:"Service extérieur, puis coup droit dans le court ouvert : c'est le service + 1."},
{i:"t234_15",u:234,t:"slider",d:.45,q:"Quel pourcentage de points un pro gagne-t-il environ quand sa première balle passe (en %) ?",min:40,max:100,step:1,a:73,tol:4,pre:"",un:" %",w:"Environ 70 à 75 % sur la première, contre 50 % environ sur la deuxième."},
{i:"t234_16",u:234,t:"story",d:.5,q:"Nathan sert toujours au T. Son adversaire commence à anticiper. Que fait-il ?",sc:[{who:"Nathan",txt:"Mais c'est mon meilleur service !"}],o:["« Varie : un au corps, un à l'extérieur, et ton T redevient une arme. »","« Continue au T, il finira par se fatiguer à force de le relancer. »","« Sers uniquement à la cuillère pour casser complètement son rythme. »","« Change de raquette, ton adversaire lit la marque de ton cordage. »"],a:0,w:"TCE, Tu Changes Encore : la variété rend chaque cible plus efficace."},
{i:"t234_17",u:234,t:"tf",d:.5,q:"Un service qui touche le filet et tombe dans le bon carré est une faute.",a:false,w:"C'est un « let » : on rejoue la balle, sans pénalité (rappel du module 1)."},
{i:"t234_18",u:234,t:"order",d:.55,q:"Remets dans l'ordre la routine d'un bon service.",it:["Choisir la cible","Placer les pieds","Lancer la balle","Frapper","Préparer le service + 1"],w:"On décide avant de lancer : un service sans cible est un service au hasard."},
{i:"t234_19",u:234,t:"story",d:.55,q:"Rappel du module 3 : Clara demande pourquoi le T est « plus sûr » que l'extérieur en première balle.",sc:[{who:"Clara",txt:"Le T, c'est pourtant au milieu, non ?"}],o:["« Au T, tu passes au centre du filet, là où il est le plus bas. »","« Au T, la balle ne peut pas sortir, la ligne médiane est toujours bonne. »","« Au T, le relanceur n'a pas le droit de frapper un coup droit. »","« Au T, l'arbitre ne peut pas annoncer de faute de pied au serveur. »"],a:0,w:"Même logique que le croisé : le filet est plus bas au centre (0,914 m)."},
{i:"t234_20",u:234,t:"mcq",d:.6,q:"Pour un droitier, vers où fuit le service slicé côté égalité ?",o:["Vers l'extérieur","Vers le T central","Vers le filet","Vers le serveur"],a:0,w:"Le slicé d'un droitier fuit vers l'extérieur côté égalité ; celui d'un gaucher côté avantage."},
{i:"t234_21",u:234,t:"sort",d:.6,q:"Première ou deuxième balle : quel choix convient ?",bins:["Première balle","Deuxième balle"],it:[["Plat au T",0],["Lifté haut sur le revers",1],["Slicé extérieur appuyé",0],["Grande marge au-dessus du filet",1]],w:"On prend un risque mesuré sur la première, on assure avec l'effet sur la deuxième."},
{i:"t234_22",u:234,t:"num",d:.65,q:"Malik a fait 11 doubles fautes sur 9 jeux de service. Combien en moyenne par jeu (arrondi au dixième) ?",a:1.2,tol:.05,un:" par jeu",h:"11 divisé par 9",w:"Plus d'une double faute par jeu : c'est un point gratuit offert presque à chaque jeu de service."},
{i:"t234_23",u:234,t:"story",d:.65,q:"Un relanceur se place très à gauche pour protéger son revers côté égalité. Où sers-tu ?",sc:[{who:"Valérie",txt:"Il te laisse un trou énorme."}],o:["« À l'extérieur, dans le coup droit qu'il découvre, ou au T s'il recule. »","« Dans son revers, là où il s'est justement placé pour le protéger. »","« Au corps, car c'est toujours la meilleure cible possible au service. »","« Nulle part : il faut attendre qu'il se replace au centre avant de servir. »"],a:0,w:"Le placement du relanceur crée un trou : le service va dans l'espace qu'il découvre."},
{i:"t234_24",u:234,t:"fill",d:.7,q:"On sert du côté égalité quand le total des points joués dans le jeu est ___.",o:["pair","impair","nul","égal à trois"],a:0,w:"0-0, 15-15, 30-0 : pair, côté égalité (à droite)."},
{i:"t234_25",u:234,t:"tf",d:.7,q:"Chez les pros, on gagne environ autant de points sur la deuxième balle que sur la première.",a:false,w:"Environ 70 à 75 % sur la première, 50 % sur la deuxième : d'où l'intérêt d'un bon pourcentage de premières."},
{i:"t234_26",u:234,t:"match",d:.75,q:"Associe chaque cible à son effet sur le relanceur.",p:[["T","Angle de retour fermé"],["Corps","Il doit se décaler"],["Extérieur","Il sort du terrain"],["Kick sur le revers","Frappe au-dessus de l'épaule"]],w:"Chaque cible crée un problème différent au relanceur."},
{i:"t234_27",u:234,t:"multi",d:.75,q:"Qu'est-ce qui rend une deuxième balle sûre ?",o:["De l'effet lifté","Une grande marge au-dessus du filet","De la vitesse de raquette","Un bras ralenti sans effet","Une routine identique"],a:[0,1,2,4],w:"L'effet sécurise ; ralentir le bras sans effet donne une balle molle et attaquable."},
{i:"t234_28",u:234,t:"story",d:.8,q:"Nathan sert à 30-40, balle de break, en première balle. Quel choix est le plus malin ?",sc:[{who:"Nathan",txt:"Je tente un ace à 200 ?"}],o:["« Une première à 80 % de vitesse, bien placée : elle doit passer. »","« Un plat maximal sur la ligne : c'est le moment de prendre tous les risques. »","« Directement une deuxième balle, pour gagner du temps sur le point. »","« Un service à la cuillère, c'est le seul moyen de gagner ce point. »"],a:0,w:"Sur les points importants, une première qui passe vaut mieux qu'un ace hypothétique (70 à 75 % de points gagnés)."},
{i:"t234_29",u:234,t:"mcq",d:.8,q:"Quel pourcentage de premières balles vise un bon serveur professionnel ?",o:["Autour de 60 à 65 %","Autour de 30 à 35 %","Exactement 100 %","Moins de 20 % à peine"],a:0,w:"Environ 60 à 65 % : assez de risque pour faire mal, assez de réussite pour éviter la deuxième."},
{i:"t234_30",u:234,t:"tiles",d:.85,q:"Reconstitue la règle de la deuxième balle.",a:["haut","lifté","sur","le","revers"],dd:["plat","fort","coup droit"],w:"Rebond haut sur le revers : le retour est difficile à attaquer."},
{i:"t234_31",u:234,t:"story",d:.85,q:"Clara demande ce qu'elle doit préparer pendant son lancer de balle.",sc:[{who:"Clara",txt:"Je pense juste à frapper."}],o:["« Ton coup suivant : où va revenir le retour, et où tu vas l'envoyer. »","« Rien du tout : penser pendant le service fait rater toutes les balles. »","« Le score du set, pour savoir si tu peux te permettre une double faute. »","« Le prochain changement de côté, pour préparer ta boisson à temps. »"],a:0,w:"Service + 1 : un service extérieur prépare un coup droit dans le court ouvert."},
{i:"t234_32",u:234,t:"story",d:.9,q:"Synthèse : Valérie demande à Malik sa nouvelle philosophie au service.",sc:[{who:"Valérie",txt:"Alors, ce radar ?"}],o:["« Placer avant de cogner, varier TCE, et une deuxième balle haute et liftée. »","« Toujours servir à plus de 190 km/h, en première comme en deuxième. »","« Servir chaque fois au même endroit, pour trouver un rythme régulier. »","« Servir doucement pour éviter les fautes, sans chercher de cible. »"],a:0,w:"Le service est le seul coup que tu contrôles entièrement : place-le, varie-le, sécurise la deuxième."}
