/*UNIT*/
{id:235,c:"TENNIS",n:"Module 5",t:"Le retour de service : neutraliser puis attaquer",col:"--gold",ic:"🛡️",guide:`
<h3>Clara face au canon</h3>
<div class="gstory">Championnat par équipes, dimanche 9 h, au club de Balma. L'adversaire de Clara sert fort, très fort. Premier jeu : quatre points, quatre retours dans le filet, Clara a fait de grands gestes de coup droit comme en échange. Au changement de côté, Valérie, capitaine de l'équipe, lui glisse : « Petit geste, un pas en arrière sur la première, un pas en avant sur la deuxième, et tu remets au centre. Tu n'as pas besoin de gagner le point avec ton retour, seulement de ne pas le perdre. » Au jeu suivant, Clara remet quatre retours sur cinq. Le serveur, surpris de voir la balle revenir, commet deux fautes.</div>
<h3>La priorité : remettre la balle en jeu</h3>
<p>Chez les professionnels, le serveur remporte environ <b>80 %</b> de ses jeux de service chez les hommes (un peu moins chez les femmes). Chaque retour remis dans le terrain oblige le serveur à jouer un coup de plus, et une partie des points se perdent sur ce coup-là.</p>
<table><tr><th>Situation</th><th>Position et geste</th><th>Cible</th></tr>
<tr><td>Première balle rapide</td><td>Sur ou derrière la ligne, <b>petit geste</b>, on bloque</td><td>Profond au <b>centre</b></td></tr>
<tr><td>Deuxième balle</td><td><b>Un pas en avant</b>, on prend la balle tôt</td><td>On attaque le côté faible</td></tr>
<tr><td>Service lifté haut</td><td>Avancer pour la prendre avant qu'elle monte, ou reculer franchement</td><td>Profond</td></tr>
<tr><td>Serveur qui monte au filet</td><td>Retour bas, court et plongeant</td><td><b>Dans les pieds</b></td></tr></table>
<h3>Les clés techniques et tactiques</h3>
<ul><li><b>Le pas d'ajustement</b> (split-step) : un petit saut au moment où le serveur frappe, pour repartir dans n'importe quelle direction.</li>
<li><b>Le retour bloqué ou chipé</b> : un geste court, souvent en slice (chip), qui utilise la vitesse du service.</li>
<li><b>Le retour au centre</b> : il réduit les angles du serveur et l'empêche de jouer son coup + 1 dans un court ouvert.</li>
<li><b>Lire le serveur</b> : la position des pieds, le lancer de balle, et ses habitudes sur les points importants.</li></ul>
<div class="gmnemo"><b>« RPC : Remettre, Profond, Centre. »</b> Et pour la position : <b>« recule sur la première, avance sur la deuxième »</b>.</div>
<div class="gtrap">Idée reçue : « un bon retour est un retour gagnant ». Faux : même les meilleurs relanceurs du monde, comme Novak Djokovic, cherchent d'abord la profondeur au centre. Autre erreur fréquente : faire le même grand geste qu'en échange. Face à un service rapide, le temps manque : on raccourcit la préparation.</div>
<h3>Contre un gaucher</h3>
<p>Le slicé du gaucher côté avantage fuit vers l'extérieur, sur le revers d'un droitier. On se décale un peu plus vers le couloir de ce côté, et l'on s'attend à ce service sur les points importants.</p>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Choisir sa position selon la première ou la deuxième balle</li><li>Raccourcir son geste face à la vitesse</li><li>Choisir la cible du retour</li><li>Lire les habitudes du serveur</li></ul>`},
/*EXOS*/
{i:"t235_01",u:235,t:"story",d:.2,nw:"Le retour",q:"Clara vient de rater quatre retours avec de grands gestes. Que lui dit Valérie au changement de côté ?",sc:[{who:"Clara",txt:"Il sert trop fort, je n'y arrive pas."}],o:["« Petit geste, et remets au centre : tu n'as pas besoin de gagner le point. »","« Frappe encore plus fort que lui, c'est la seule façon de le calmer. »","« Tente un retour gagnant le long de la ligne sur chaque première. »","« Place-toi collée au filet pour prendre la balle avant son rebond. »"],a:0,w:"RPC : Remettre, Profond, Centre. Face à la vitesse, on raccourcit le geste."},
{i:"t235_02",u:235,t:"fill",d:.2,q:"Recule sur la première, ___ sur la deuxième.",o:["avance","recule","saute","attends"],a:0,w:"Sur la deuxième balle, plus lente, on prend la balle tôt pour attaquer."},
{i:"t235_03",u:235,t:"tf",d:.25,q:"Le pas d'ajustement (split-step) se fait au moment où le serveur frappe la balle.",a:true,w:"Un petit saut qui permet de repartir dans toutes les directions dès qu'on voit la trajectoire."},
{i:"t235_04",u:235,t:"match",d:.25,q:"Associe chaque service à la bonne réponse.",p:[["Première balle rapide","Petit geste, bloquer"],["Deuxième balle","Avancer, attaquer"],["Serveur qui monte","Retour dans les pieds"],["Service lifté haut","Le prendre tôt ou reculer"]],w:"La position et le geste s'adaptent au service reçu."},
{i:"t235_05",u:235,t:"slider",d:.3,q:"Quel pourcentage de ses jeux de service un pro masculin remporte-t-il environ (en %) ?",min:40,max:100,step:1,a:80,tol:4,pre:"",un:" %",w:"Environ 80 % : breaker est rare, chaque retour remis compte."},
{i:"t235_06",u:235,t:"story",d:.3,q:"Nathan veut prendre des risques sur les deuxièmes balles adverses, qui sont molles. Bonne idée ?",sc:[{who:"Nathan",txt:"Sa deuxième balle est à 120 km/h."}],o:["« Oui : un pas en avant, et tu attaques son côté faible. »","« Non : on retourne toujours au centre, même sur une balle molle. »","« Non : il faut reculer de trois mètres sur les balles lentes. »","« Oui : et tu montes au filet avant même que le service parte. »"],a:0,w:"Recule sur la première, avance sur la deuxième : la deuxième balle est l'occasion d'attaquer."},
{i:"t235_07",u:235,t:"multi",d:.35,q:"Quels signes peuvent trahir la cible du serveur ?",o:["Son lancer de balle","La position de ses pieds","Ses habitudes sur les points importants","La couleur de ses chaussettes","Son choix de cible au point précédent"],a:[0,1,2,4],w:"Lire le serveur : lancer, pieds, habitudes. Les chaussettes n'y sont pour rien."},
{i:"t235_08",u:235,t:"order",d:.35,q:"Remets dans l'ordre les étapes d'un retour.",it:["Se placer selon le service attendu","Pas d'ajustement à la frappe du serveur","Petit geste de préparation","Frappe profonde au centre","Replacement"],w:"Position, split-step, geste court, cible, replacement."},
{i:"t235_09",u:235,t:"sort",d:.4,q:"Première balle rapide ou deuxième balle : quelle réponse ?",bins:["Première rapide","Deuxième balle"],it:[["Bloquer au centre",0],["Avancer d'un pas",1],["Chip en slice profond",0],["Attaquer le revers adverse",1],["Rester derrière la ligne",0]],w:"On neutralise la première, on attaque la deuxième."},
{i:"t235_10",u:235,t:"tiles",d:.4,q:"Reconstitue le moyen mnémotechnique du retour.",a:["Remettre","Profond","Centre"],dd:["Risquer","Court","Ligne"],w:"RPC : l'objectif du retour est de neutraliser le service."},
{i:"t235_11",u:235,t:"story",d:.45,q:"Rappel du module 4 : Malik, gaucher, sert côté avantage. Son adversaire droitier te demande où se placer.",sc:[{who:"Adversaire",txt:"Il me sort toujours du terrain de ce côté."}],o:["« Décale-toi vers le couloir, son slicé fuit vers ton revers. »","« Colle-toi au T, car un gaucher ne sert jamais à l'extérieur. »","« Reste au centre exact, le côté ne change rien pour un gaucher. »","« Recule jusqu'au mur du fond, ses services sont trop rapides. »"],a:0,w:"Le slicé du gaucher côté avantage fuit vers l'extérieur : on anticipe en se décalant."},
{i:"t235_12",u:235,t:"mcq",d:.45,q:"Pourquoi viser le centre en retour ?",o:["Cela réduit fortement les angles du serveur","C'est obligatoire en tournoi FFT","Le filet y est nettement plus haut","L'arbitre le voit bien mieux"],a:0,w:"Un retour au centre empêche le coup + 1 dans un court ouvert. Et le filet y est plus bas, pas plus haut."},
{i:"t235_13",u:235,t:"num",d:.5,q:"Clara remet 4 retours sur 5 au 2e jeu, et le serveur fait 2 fautes sur ces 4 balles. Combien de points gagne-t-elle sans frapper de coup gagnant ?",a:2,tol:0,un:" points",h:"Les fautes du serveur",w:"Remettre la balle, c'est offrir au serveur l'occasion de se tromper."},
{i:"t235_14",u:235,t:"tf",d:.5,q:"Face à un serveur qui monte au filet, le meilleur retour est un lob haut et lent.",a:false,w:"On vise un retour bas et plongeant dans les pieds : il doit volleyer vers le haut."},
{i:"t235_15",u:235,t:"story",d:.55,q:"Le serveur de Malik sert très lifté, la balle monte au-dessus de son épaule. Que proposes-tu ?",sc:[{who:"Malik",txt:"Je frappe tout au-dessus de la tête."}],o:["« Avance pour la prendre avant qu'elle monte, ou recule franchement. »","« Reste exactement où tu es et frappe plus fort sur chaque balle haute. »","« Tourne le dos à la balle pour la frapper en passant entre tes jambes. »","« Demande à l'arbitre d'interdire ce service, qui est déloyal. »"],a:0,w:"Contre le kick, on évite la zone où la balle est la plus haute : tôt ou tard."},
{i:"t235_16",u:235,t:"fill",d:.55,q:"Le retour en slice, court et bloqué, s'appelle un ___.",o:["chip","smash","lob","kick"],a:0,w:"Le chip utilise la vitesse du service avec un geste très court."},
{i:"t235_17",u:235,t:"match",d:.6,q:"Associe chaque mot à sa définition.",p:[["Split-step","Petit saut à la frappe adverse"],["Chip","Retour court en slice"],["Break","Gagner le jeu de service adverse"],["Coup + 1","Coup qui suit le service"]],w:"Le vocabulaire du retour, et celui du service vu au module 4."},
{i:"t235_18",u:235,t:"story",d:.6,q:"Nathan a remarqué que son adversaire sert toujours au T sur les balles de break. Que fait-il à 30-40 ?",sc:[{who:"Nathan",txt:"Je triche vers le T ?"}],o:["« Oui, décale-toi d'un demi-pas vers le T et prépare ton coup. »","« Non, on ne change jamais de place, c'est interdit par les règles. »","« Non, il servira forcément ailleurs puisqu'il sait que tu l'as vu. »","« Oui, et tu te places carrément dans le carré de service adverse. »"],a:0,w:"Lire les habitudes sur les points importants : on anticipe un peu, sans se découvrir totalement."},
{i:"t235_19",u:235,t:"sort",d:.65,q:"Classe chaque affirmation : vraie ou idée reçue ?",bins:["Vraie","Idée reçue"],it:[["Un bon retour est un retour gagnant",1],["On raccourcit le geste face à la vitesse",0],["Même Djokovic cherche d'abord la profondeur",0],["On fait le même geste qu'en échange",1]],w:"Deux idées reçues corrigées dans le guide."},
{i:"t235_20",u:235,t:"mcq",d:.65,q:"Quel relanceur est cité comme l'un des meilleurs du monde ?",o:["Novak Djokovic","Ivo Karlović","John Isner","Milos Raonic"],a:0,w:"Djokovic est réputé pour son retour ; les trois autres sont surtout de grands serveurs."},
{i:"t235_21",u:235,t:"story",d:.7,q:"Rappel du module 3 : Clara, poussée loin derrière sa ligne par un retour de l'adversaire, veut enchaîner un coup gagnant. Ton conseil ?",sc:[{who:"Clara",txt:"Je le fusille long de ligne !"}],o:["« Tu es en défense : balle haute et longue au centre. »","« Oui, c'est le moment idéal pour tenter le long de ligne. »","« Monte au filet directement, il ne s'y attendra pas. »","« Une amortie depuis le fond, pour le prendre à contre-pied. »"],a:0,w:"Zone de défense : haut, long, au centre, pour gagner du temps."},
{i:"t235_22",u:235,t:"multi",d:.7,q:"Contre une première balle très rapide, que fais-tu ?",o:["Réduire ma préparation","Reculer un peu","Viser le centre","Tenter la ligne","Faire mon pas d'ajustement"],a:[0,1,2,4],w:"On neutralise : geste court, un peu de recul, centre profond, split-step."},
{i:"t235_23",u:235,t:"tiles",d:.75,q:"Reconstitue la règle de position.",a:["recule","sur","la","première","avance","sur","la","deuxième"],dd:["toujours","jamais","troisième"],w:"La position s'adapte à la vitesse du service."},
{i:"t235_24",u:235,t:"num",d:.75,q:"Un serveur gagne 80 % de ses jeux de service. Sur 10 jeux de service, combien de breaks en moyenne ?",a:2,tol:0,un:" breaks",h:"20 % de 10",w:"Environ 2 : c'est pourquoi chaque occasion de break est précieuse."},
{i:"t235_25",u:235,t:"story",d:.8,q:"Malik fait des retours gagnants spectaculaires, mais en rate sept sur dix. Que lui dis-tu ?",sc:[{who:"Malik",txt:"Quand ça passe, c'est magnifique !"}],o:["« Sept fautes sur dix, c'est un cadeau : vise le centre profond. »","« Continue comme ça, tu finiras par en réussir huit sur dix en match. »","« Tente-les seulement sur les premières balles les plus rapides. »","« Arrête de retourner et laisse passer la balle pour gagner du temps. »"],a:0,w:"Un retour sert d'abord à neutraliser : RPC."},
{i:"t235_26",u:235,t:"fill",d:.8,q:"Contre un serveur-volleyeur, on vise un retour bas dans ses ___.",o:["pieds","épaules","mains","yeux"],a:0,w:"Une balle basse le force à volleyer vers le haut, sans pouvoir attaquer."},
{i:"t235_27",u:235,t:"tf",d:.8,q:"Un retour remis dans le terrain oblige le serveur à jouer un coup de plus.",a:true,w:"Et une partie des points se perdent sur ce coup-là : remettre, c'est déjà gagner des points."},
{i:"t235_28",u:235,t:"order",d:.85,q:"Du plus défensif au plus offensif, classe ces retours.",it:["Chip bloqué au centre","Retour profond au centre","Retour croisé appuyé","Retour attaque long de ligne"],w:"On monte en risque à mesure que le service reçu devient plus facile."},
{i:"t235_29",u:235,t:"mcq",d:.85,q:"Qu'est-ce qu'un break ?",o:["Gagner un jeu sur le service adverse","Faire une pause de dix minutes entre sets","Casser sa raquette de colère sur le court","Perdre son propre jeu de service"],a:0,w:"Le break se prend en retour ; perdre son service, c'est se faire breaker."},
{i:"t235_30",u:235,t:"story",d:.9,q:"Clara demande quoi faire si le serveur change de cible à chaque point.",sc:[{who:"Clara",txt:"Je ne lis rien du tout."}],o:["« Reste au centre, split-step à la frappe, et vise le centre. »","« Devine au hasard et plonge d'un côté avant qu'il frappe la balle. »","« Abandonne le jeu en cours et concentre-toi sur ton propre service. »","« Change de place à chaque point pour qu'il ne sache plus où servir. »"],a:0,w:"Sans indice, on garde une position neutre et un objectif simple : remettre profond."},
{i:"t235_31",u:235,t:"sort",d:.9,q:"Quelle cible pour quel retour ?",bins:["Centre profond","Dans les pieds","Côté faible adverse"],it:[["Première balle rapide",0],["Serveur qui monte au filet",1],["Deuxième balle molle",2],["Service inconnu",0]],w:"La cible du retour dépend du service reçu et de ce que fait le serveur après."},
{i:"t235_32",u:235,t:"story",d:.95,q:"Synthèse : Valérie demande à Nathan son plan de retour pour dimanche.",sc:[{who:"Valérie",txt:"Tu as trois phrases."}],o:["« Remettre la première au centre, attaquer la deuxième, lire le serveur. »","« Tout frapper à fond, car le retour est le coup le plus important. »","« Rester derrière le mur du fond et renvoyer des lobs sur chaque balle. »","« Retourner uniquement en coup droit, en contournant tous mes revers. »"],a:0,w:"RPC, recule sur la première, avance sur la deuxième, et lis le serveur."}
