/*UNIT*/
{id:236,c:"TENNIS",n:"Module 6",t:"Le fond de court : profondeur, effets et coup droit décalé",col:"--gold",ic:"🔁",guide:`
<h3>La corde de Valérie</h3>
<div class="gstory">Jeudi, 19 h. Valérie tend une corde à 1,50 m au-dessus du filet et trace une ligne à la craie deux mètres devant la ligne de fond. « Nathan, tes balles passent à trente centimètres du filet et tombent au milieu du terrain. Ton adversaire les attend les pieds dans le terrain. Maintenant, tu passes au-dessus de la corde et tu fais tomber la balle derrière la craie. » Au bout de vingt minutes, son partenaire d'entraînement recule d'un mètre à chaque échange, et commence à raccourcir ses balles. Nathan n'a pourtant pas frappé plus fort.</div>
<h3>Profondeur et hauteur</h3>
<p>Une balle qui rebondit dans les <b>deux derniers mètres</b> du terrain repousse l'adversaire et l'empêche d'attaquer. Pour aller loin sans risque, on passe haut au-dessus du filet : <b>la hauteur donne la longueur</b>.</p>
<h3>Les effets</h3>
<table><tr><th>Effet</th><th>Trajectoire</th><th>Usage tactique</th></tr>
<tr><td><b>Lifté</b> (topspin)</td><td>Passe haut, plonge, rebondit haut</td><td>Sécurité, profondeur, balle haute sur un revers</td></tr>
<tr><td><b>Slice</b> (coupé)</td><td>Tendu, rebond bas qui fuse</td><td>Casser le rythme, défendre, approcher, gêner les grands joueurs</td></tr>
<tr><td><b>À plat</b></td><td>Rapide et tendu</td><td>Conclure sur une balle haute et facile</td></tr></table>
<p>Exemple célèbre : Rafael Nadal envoyait son coup droit très lifté, rebond haut, sur le <b>revers à une main</b> de Roger Federer. Un revers à une main frappe difficilement une balle au niveau de l'épaule.</p>
<h3>Le coup droit décalé</h3>
<div class="gsvg-wrap"><svg class='gsvg' viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Décalé : croisé (pointillé)</text><circle cx='52' cy='176' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><line x1='52.0' y1='172.0' x2='50.0' y2='30.0' stroke='var(--gold)' stroke-width='1.8'/><polygon points='50.0,30.0 52.4,35.5 47.7,35.6' fill='var(--gold)'/><line x1='52.0' y1='172.0' x2='94.0' y2='32.0' stroke='var(--pink)' stroke-width='1.8' stroke-dasharray='3 2'/><polygon points='94.0,32.0 94.6,38.0 90.2,36.6' fill='var(--pink)'/></svg></div>
<p>Le joueur contourne son revers pour frapper un coup droit depuis le côté gauche (pour un droitier). Deux options : le <b>croisé décalé</b> (inside-out), vers le revers adverse, ou le <b>long de ligne décalé</b> (inside-in), vers le coup droit adverse. Il laisse un grand espace côté coup droit : on ne le joue que si la balle permet de <b>faire mal</b>.</p>
<h3>Les schémas de jeu</h3>
<ul><li><b>Attaquer le revers</b> : chez la plupart des joueurs, c'est le côté le plus faible.</li>
<li><b>Varier la hauteur et le rythme</b> : une balle haute, puis une balle basse slicée, dérègle un joueur qui aime le rythme.</li>
<li><b>Changer de direction sur la balle qu'on contrôle</b> : le long de ligne se joue sur une balle confortable (module 3).</li></ul>
<div class="gmnemo"><b>« La hauteur donne la longueur. »</b> Et pour le choix d'effet : <b>« Lift pour la marge, slice pour le piège, plat pour la fin. »</b></div>
<div class="gtrap">Idée reçue : « une balle rasante est une bonne balle ». Faux chez les amateurs : elle part souvent dans le filet et tombe courte. Autre piège : contourner son revers à chaque balle. Le coup droit décalé ouvre tout le côté coup droit ; si l'adversaire répond long de ligne, on court tout le terrain.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Choisir l'effet selon la situation</li><li>Jouer profond avec de la hauteur</li><li>Décider quand jouer le coup droit décalé</li><li>Attaquer le point faible de l'adversaire</li></ul>`},
/*EXOS*/
{i:"t236_01",u:236,t:"story",d:.2,nw:"Le fond de court",q:"Nathan joue des balles rasantes qui tombent au milieu du terrain. Que lui propose Valérie ?",sc:[{who:"Nathan",txt:"Mes balles sont rapides pourtant."}],o:["« Passe bien plus haut au-dessus du filet : la hauteur donne la longueur. »","« Frappe encore plus fort à plat, pour que la balle aille plus loin. »","« Vise directement le filet, la balle rebondira dessus vers le fond. »","« Joue des amorties depuis le fond pour varier les longueurs de balle. »"],a:0,w:"La hauteur donne la longueur : une balle haute et liftée rebondit profond."},
{i:"t236_02",u:236,t:"match",d:.2,q:"Associe chaque effet à son usage.",p:[["Lifté","Marge et profondeur"],["Slice","Casser le rythme"],["À plat","Conclure une balle facile"],["Balle haute liftée","Gêner un revers à une main"]],w:"Lift pour la marge, slice pour le piège, plat pour la fin."},
{i:"t236_03",u:236,t:"fill",d:.25,q:"La hauteur donne la ___.",o:["longueur","vitesse","faute","couleur"],a:0,w:"Plus la balle passe haut au-dessus du filet, plus elle retombe loin."},
{i:"t236_04",u:236,t:"mcq",d:.25,q:"Sur ce schéma, quelle trajectoire est le croisé décalé (inside-out) ?",svg:"<svg viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Deux options du coup droit décalé</text><circle cx='52' cy='176' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><line x1='52.0' y1='172.0' x2='50.0' y2='30.0' stroke='var(--gold)' stroke-width='1.8'/><polygon points='50.0,30.0 52.4,35.5 47.7,35.6' fill='var(--gold)'/><line x1='52.0' y1='172.0' x2='94.0' y2='32.0' stroke='var(--pink)' stroke-width='1.8' stroke-dasharray='3 2'/><polygon points='94.0,32.0 94.6,38.0 90.2,36.6' fill='var(--pink)'/></svg>",o:["La flèche en pointillé","La flèche pleine dorée","Aucune des deux flèches","Les deux flèches à la fois"],a:0,w:"Depuis le côté revers, le croisé décalé part vers le revers adverse : c'est le pointillé."},
{i:"t236_05",u:236,t:"tf",d:.3,q:"Le slice produit un rebond bas qui fuse.",a:true,w:"L'effet coupé freine la balle en l'air et la fait glisser au rebond : idéal pour casser le rythme."},
{i:"t236_06",u:236,t:"story",d:.3,q:"Clara affronte une joueuse qui adore le rythme et frappe fort à hauteur de hanche. Quel plan ?",sc:[{who:"Clara",txt:"Elle me renvoie tout plus fort."}],o:["« Varie : une balle haute liftée, puis un slice bas qui fuse. »","« Joue plus fort qu'elle, à la même hauteur, pour la dépasser. »","« Joue toutes les balles à hauteur de hanche pour la mettre à l'aise. »","« Arrête d'échanger et monte au filet sur chaque balle de service. »"],a:0,w:"Un joueur de rythme aime les balles régulières : on lui retire le rythme en variant hauteur et effet."},
{i:"t236_07",u:236,t:"slider",d:.35,q:"Dans combien de mètres avant la ligne de fond une balle est-elle considérée comme profonde ?",min:0,max:8,step:.5,a:2,tol:.5,pre:"",un:" m",w:"Les deux derniers mètres : l'adversaire est repoussé et ne peut pas attaquer."},
{i:"t236_08",u:236,t:"sort",d:.35,q:"Quel effet choisir ?",bins:["Lifté","Slice","À plat"],it:[["Balle haute facile au milieu du terrain",2],["Mettre de la marge en échange",0],["Défendre en course, balle basse",1],["Approcher le filet en balle basse",1],["Envoyer haut sur un revers à une main",0]],w:"Lift pour la marge, slice pour le piège, plat pour la fin."},
{i:"t236_09",u:236,t:"story",d:.4,q:"Malik contourne son revers sur chaque balle, même quand elle est très croisée. Qu'en penses-tu ?",sc:[{who:"Malik",txt:"Mon coup droit est bien meilleur."}],o:["« Sur une balle très croisée, tu ouvres tout ton côté coup droit. »","« Parfait, il faut contourner son revers sur absolument toutes les balles. »","« Contourne aussi ton coup droit, pour jouer uniquement en revers. »","« C'est interdit par le règlement de jouer un coup droit côté revers. »"],a:0,w:"Le coup droit décalé se joue si la balle permet de faire mal ; sinon, l'adversaire joue long de ligne dans le trou. Quand il contourne, il a le choix entre inside-out (croisé décalé) et inside-in (long de ligne décalé)."},
{i:"t236_10",u:236,t:"tiles",d:.4,q:"Reconstitue le moyen mnémotechnique des effets.",a:["lift","pour","la","marge","slice","pour","le","piège"],dd:["plat","filet","vitesse"],w:"Et « plat pour la fin » : on conclut à plat sur une balle facile."},
{i:"t236_11",u:236,t:"mcq",d:.45,q:"Pourquoi Nadal envoyait-il des coups droits très liftés sur le revers de Federer ?",o:["Le revers à une main gère mal les balles hautes","Federer ne savait pas jouer de revers slicé","C'était imposé par l'arbitre de chaise","Pour ralentir volontairement le match"],a:0,w:"Une balle haute à hauteur d'épaule est difficile à frapper avec un revers à une main."},
{i:"t236_12",u:236,t:"multi",d:.45,q:"Quelles sont les conséquences d'une balle profonde ?",o:["L'adversaire recule","Il attaque plus difficilement","Sa réponse tombe souvent plus courte","Il gagne forcément le point","Il perd du temps pour se replacer"],a:[0,1,2,4],w:"La profondeur ne gagne pas le point à elle seule, mais elle prépare la balle courte."},
{i:"t236_13",u:236,t:"fill",d:.5,q:"Le long de ligne joué depuis le côté revers avec un coup droit s'appelle l'inside-___.",o:["in","out","over","up"],a:0,w:"Inside-in : long de ligne décalé, vers le coup droit adverse. Inside-out : croisé décalé. L'inside-in surprend car l'adversaire attend souvent le croisé décalé."},
{i:"t236_14",u:236,t:"story",d:.5,q:"Rappel du module 3 : Nathan a une balle courte et haute au centre. Quel coup ?",sc:[{who:"Nathan",txt:"Je joue encore croisé profond ?"}],o:["« Zone d'attaque : à plat et long de ligne, puis tu avances. »","« Oui, croisé profond et tu recules derrière ta ligne de fond. »","« Un slice court et bas, pour garder la balle en jeu sans risque. »","« Une chandelle haute au centre, pour bien te replacer au fond. »"],a:0,w:"Plat pour la fin, long de ligne pour conclure : la balle courte est l'occasion d'attaquer."},
{i:"t236_15",u:236,t:"tf",d:.55,q:"Chez les amateurs, une balle rasante au-dessus du filet est la balle la plus efficace.",a:false,w:"Elle part souvent dans le filet ou tombe courte. La hauteur donne la longueur."},
{i:"t236_16",u:236,t:"order",d:.55,q:"Remets dans l'ordre un schéma classique de coup droit décalé.",it:["Balle au centre, un peu courte","Contourner le revers","Croisé décalé vers le revers adverse","Balle faible en retour","Long de ligne gagnant"],w:"On contourne sur une balle confortable, on attaque le revers, puis on conclut dans l'espace. Variante : depuis la même position, l'inside-in (long de ligne décalé) vise le coup droit adverse."},
{i:"t236_17",u:236,t:"num",d:.6,q:"Sur 20 balles, Nathan en met 14 derrière la craie avec la corde, contre 5 avant. Combien de balles profondes en plus ?",a:9,tol:0,un:" balles",h:"14 moins 5",w:"Neuf balles profondes de plus sans frapper plus fort : la hauteur donne la longueur."},
{i:"t236_18",u:236,t:"story",d:.6,q:"L'adversaire de Clara mesure 1,90 m et adore les balles hautes. Quel effet privilégier ?",sc:[{who:"Clara",txt:"Il se régale de mes lifts."}],o:["« Le slice bas : un grand joueur déteste se baisser. »","« Encore plus de lift, pour que la balle monte au-dessus de sa tête. »","« Des lobs, parce qu'un grand joueur ne sait jamais smasher. »","« Uniquement des balles à plat sur sa hanche, à pleine vitesse. »"],a:0,w:"Slice pour le piège : le rebond bas oblige les grands joueurs à plier les jambes."},
{i:"t236_19",u:236,t:"match",d:.65,q:"Associe chaque terme à sa définition.",p:[["Inside-out","Croisé décalé"],["Inside-in","Long de ligne décalé"],["Topspin","Effet lifté"],["Slice","Effet coupé"]],w:"Le vocabulaire anglais revient dans toutes les analyses de match. Le coup droit décalé inside-in part long de ligne vers le coup droit adverse."},
{i:"t236_20",u:236,t:"sort",d:.65,q:"Classe chaque affirmation : vraie ou idée reçue ?",bins:["Vraie","Idée reçue"],it:[["La balle rasante est la meilleure",1],["La hauteur donne la longueur",0],["Il faut contourner son revers sur toutes les balles",1],["Le revers est souvent le côté faible",0]],w:"Deux idées reçues corrigées dans le guide."},
{i:"t236_21",u:236,t:"mcq",d:.7,q:"Quel côté attaque-t-on en priorité chez la plupart des joueurs ?",o:["Le revers","Le coup droit","La volée","Le smash"],a:0,w:"Le revers est souvent le côté le plus faible : on le fait jouer, puis on ouvre le coup droit."},
{i:"t236_22",u:236,t:"story",d:.7,q:"Rappel du module 4 : Malik vient de servir extérieur côté égalité. Le retour revient au centre, un peu court. Que joue-t-il ?",sc:[{who:"Malik",txt:"Mon service + 1 ?"}],o:["« Coup droit dans le court ouvert, du côté où tu l'as sorti. »","« Un lob défensif très haut au centre pour se replacer. »","« Au même endroit que ton service, dans le couloir adverse. »","« Une amortie derrière lui, juste à côté de sa raquette. »"],a:0,w:"Service extérieur, puis coup droit dans l'espace ouvert : c'est le service + 1."},
{i:"t236_23",u:236,t:"tf",d:.75,q:"Le coup droit décalé laisse un grand espace du côté coup droit de celui qui le joue.",a:true,w:"C'est son risque : si l'adversaire répond long de ligne, il faut couvrir tout le terrain."},
{i:"t236_24",u:236,t:"multi",d:.75,q:"Comment dérégler un joueur de rythme ?",o:["Varier la hauteur","Alterner lift et slice","Changer la vitesse","Lui donner toujours la même balle","Jouer parfois au centre"],a:[0,1,2,4],w:"On lui retire le rythme : hauteur, effet, vitesse, et parfois le centre pour lui ôter les angles."},
{i:"t236_25",u:236,t:"fill",d:.8,q:"Le lifté rebondit ___.",o:["haut","bas","à plat","de côté"],a:0,w:"Le lift plonge après le filet et rebondit haut ; le slice rebondit bas."},
{i:"t236_26",u:236,t:"story",d:.8,q:"Nathan voit que son adversaire recule d'un mètre à chaque balle profonde et répond court. Que fait-il ?",sc:[{who:"Nathan",txt:"Il est dans le mur."}],o:["« Encore une balle profonde, puis tu avances sur la courte. »","« Tu recules aussi, pour lui laisser l'initiative de l'échange. »","« Joue immédiatement une amortie sans attendre la balle courte. »","« Frappe dans le filet exprès pour changer son rythme de jeu. »"],a:0,w:"La profondeur prépare la balle courte, qu'on attaque en avançant."},
{i:"t236_27",u:236,t:"num",d:.85,q:"Une balle profonde tombe dans les 2 derniers mètres d'un terrain de 23,77 m. À combien de mètres du filet commence cette zone (arrondi au dixième) ?",a:9.9,tol:.1,un:" m",h:"Demi-terrain de 11,885 m, moins 2",w:"11,885 moins 2 : environ 9,9 m. Tout ce qui tombe au-delà repousse l'adversaire."},
{i:"t236_28",u:236,t:"tiles",d:.85,q:"Reconstitue le principe de profondeur.",a:["la","hauteur","donne","la","longueur"],dd:["vitesse","filet","largeur"],w:"Passer haut au-dessus du filet fait retomber la balle loin."},
{i:"t236_29",u:236,t:"story",d:.9,q:"Clara, en course, reçoit une balle basse très croisée. Quel coup choisir ?",sc:[{who:"Clara",txt:"Je la frappe à plat dans le coin ?"}],o:["« Un slice long et bas, pour gagner du temps et revenir vite au centre. »","« Oui, un coup à plat gagnant dans le coin opposé, c'est l'occasion. »","« Une amortie courte, puisque ton adversaire est déjà au fond. »","« Laisse passer la balle, elle sortira sûrement du terrain. »"],a:0,w:"En défense et en course, le slice long donne du temps : c'est le coup de sauvegarde."},
{i:"t236_30",u:236,t:"mcq",d:.9,q:"Qu'est-ce qui justifie un changement de direction ?",o:["Une balle qu'on contrôle bien","Une balle très rapide dans les pieds","Une course en défense","L'ennui pendant l'échange"],a:0,w:"On change de direction sur la balle qu'on contrôle, jamais en difficulté (module 3)."},
{i:"t236_31",u:236,t:"match",d:.95,q:"Associe chaque situation au bon coup de fond.",p:[["Balle courte et haute","Plat long de ligne"],["En course, balle basse","Slice long"],["Échange neutre","Lift croisé profond"],["Revers à une main en face","Balle haute liftée"]],w:"La balle reçue et l'adversaire décident de l'effet."},
{i:"t236_32",u:236,t:"story",d:.95,q:"Synthèse : Valérie demande à Nathan ce qu'il a appris avec la corde.",sc:[{who:"Valérie",txt:"Résume-moi la séance."}],o:["« Haut et profond pour construire, varier, attaquer la balle courte. »","« Frapper plus fort et plus bas pour que l'adversaire ne voie rien. »","« Toujours jouer le coup droit décalé, quelle que soit la balle reçue. »","« Viser les lignes avec des balles rasantes pour finir plus vite. »"],a:0,w:"La hauteur donne la longueur ; lift pour la marge, slice pour le piège, plat pour la fin."}
