/*UNIT*/
{id:238,c:"TENNIS",n:"Module 8",t:"Les chiffres du match : ce que disent vraiment les statistiques",col:"--gold",ic:"📈",guide:`
<h3>Le carnet de Clara</h3>
<div class="gstory">Clara, infirmière, adore les tableaux. Valérie lui confie une mission : noter chaque point du match de Nathan contre Paul, un 15 du club de Colomiers. Colonne 1 : nombre de frappes. Colonne 2 : fin du point (coup gagnant, faute directe, faute provoquée). Résultat, affiché au club-house : Nathan perd 6-4, 6-4, et 71 % des points ont duré quatre frappes ou moins. Nathan a perdu 19 de ces points courts sur ses propres fautes au retour et au coup suivant. « Tu t'entraînes à faire des échanges de vingt coups, lui dit Valérie, mais le match se joue sur les quatre premiers. »</div>
<h3>La règle des quatre premières frappes</h3>
<p>L'analyste Craig O'Shannessy, qui a travaillé avec Novak Djokovic, a mesuré sur des milliers de points professionnels masculins que :</p>
<table><tr><th>Durée du point</th><th>Part des points</th></tr>
<tr><td><b>0 à 4 frappes</b> (0 = double faute)</td><td>environ <b>70 %</b></td></tr>
<tr><td>5 à 8 frappes</td><td>environ 20 %</td></tr>
<tr><td>9 frappes et plus</td><td>environ 10 %</td></tr></table>
<p>Quatre frappes, c'est au maximum deux coups par joueur : <b>le service et le coup + 1</b>, ou <b>le retour et le coup suivant</b>. Le vainqueur du match gagne très souvent la majorité de ces points courts.</p>
<h3>Petit écart, grand résultat</h3>
<p>Roger Federer l'a raconté en 2024 dans un discours à l'université de Dartmouth : il a gagné près de <b>80 %</b> de ses matchs en simple, mais seulement environ <b>54 %</b> des points. Un petit avantage par point, répété sur des centaines de points, fait une grande carrière. On peut perdre beaucoup de points et gagner quand même.</p>
<h3>Lire une feuille de statistiques</h3>
<table><tr><th>Statistique</th><th>Ce qu'elle dit</th></tr>
<tr><td><b>Coup gagnant</b></td><td>L'adversaire ne touche pas la balle, ou à peine</td></tr>
<tr><td><b>Faute directe</b></td><td>Faute sur une balle jouable, sans pression</td></tr>
<tr><td><b>Faute provoquée</b></td><td>Faute causée par la qualité du coup adverse</td></tr>
<tr><td>% de premières balles, % gagnés sur 1re et 2e</td><td>La solidité au service (module 4)</td></tr>
<tr><td>Balles de break converties / sauvées</td><td>L'efficacité sur les points importants</td></tr>
<tr><td>Points gagnés au retour</td><td>La capacité à mettre la pression au retour</td></tr></table>
<p>Chez les amateurs, la grande majorité des points se terminent sur une faute plutôt que sur un coup gagnant. Réduire ses fautes directes est donc le levier le plus rentable.</p>
<div class="gmnemo"><b>« 70 dans les 4 »</b> : 70 % des points se jouent en quatre frappes ou moins. Et <b>« 54 suffit »</b> : on n'a pas besoin de gagner tous les points pour gagner le match.</div>
<div class="gtrap">Idée reçue : « le joueur qui fait le plus de coups gagnants gagne le match ». Faux : il faut regarder le bilan coups gagnants moins fautes directes, et le nombre de fautes provoquées. Un joueur peut frapper 40 coups gagnants et perdre avec 60 fautes directes. Autre piège : juger un match au nombre d'aces ; le pourcentage de points gagnés sur la deuxième balle en dit souvent plus.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Citer la répartition des points selon leur durée</li><li>Distinguer faute directe, faute provoquée et coup gagnant</li><li>Calculer un bilan et des pourcentages</li><li>En déduire des priorités d'entraînement</li></ul>`},
/*EXOS*/
{i:"t238_01",u:238,t:"story",d:.2,nw:"Les chiffres",q:"Nathan s'entraîne surtout aux longs échanges. Que lui montre la feuille de Clara ?",sc:[{who:"Nathan",txt:"J'ai perdu parce que je ne tiens pas l'échange."}],o:["« 71 % des points ont duré quatre frappes ou moins : tu perds là. »","« Tu perds parce que les échanges de vingt coups ne sont pas assez longs. »","« Tu as perdu parce que Paul a frappé beaucoup plus d'aces que toi. »","« La feuille ne montre rien, le tennis ne se mesure pas avec des chiffres. »"],a:0,w:"70 dans les 4 : le match se joue sur le service, le retour et le coup suivant."},
{i:"t238_02",u:238,t:"slider",d:.2,q:"Quelle part des points professionnels masculins dure 4 frappes ou moins (en %) ?",min:0,max:100,step:1,a:70,tol:4,pre:"",un:" %",w:"Environ 70 %, puis 20 % pour 5 à 8 frappes et 10 % pour 9 et plus."},
{i:"t238_03",u:238,t:"match",d:.25,q:"Associe chaque durée de point à sa part environ.",p:[["0 à 4 frappes","70 %"],["5 à 8 frappes","20 %"],["9 frappes et plus","10 %"],["Double faute","0 frappe"]],w:"Les chiffres de Craig O'Shannessy sur le circuit masculin."},
{i:"t238_04",u:238,t:"fill",d:.25,q:"Federer a gagné près de 80 % de ses matchs, mais environ ___ % des points.",o:["54","80","95","35"],a:0,w:"54 suffit : un petit avantage par point, répété, fait gagner les matchs."},
{i:"t238_05",u:238,t:"tf",d:.3,q:"Le joueur qui frappe le plus de coups gagnants gagne toujours le match.",a:false,w:"Il faut regarder le bilan avec les fautes directes : 40 coups gagnants et 60 fautes directes, c'est un bilan négatif."},
{i:"t238_06",u:238,t:"sort",d:.3,q:"Coup gagnant, faute directe ou faute provoquée ?",bins:["Coup gagnant","Faute directe","Faute provoquée"],it:[["Passing que l'adversaire ne touche pas",0],["Coup droit facile dans le filet",1],["Retour raté sur un service à 200 km/h",2],["Revers dehors sur une balle lente au centre",1],["Volée ratée sur un passing très rapide",2]],w:"La faute directe se commet sans pression ; la faute provoquée vient de la qualité du coup adverse."},
{i:"t238_07",u:238,t:"story",d:.35,q:"Malik a frappé 35 coups gagnants et 52 fautes directes. Il est fier de ses coups gagnants. Ta réaction ?",sc:[{who:"Malik",txt:"35 coups gagnants, record !"}],o:["« Ton bilan est de moins 17 : tes fautes ont offert le match. »","« Bravo, 35 coups gagnants garantissent la victoire à ce niveau. »","« Les fautes directes ne comptent pas, seuls les points gagnés comptent. »","« Il faudrait 60 coups gagnants pour compenser, frappe plus fort. »"],a:0,w:"35 moins 52 = moins 17. Réduire ses fautes directes est le levier le plus rentable."},
{i:"t238_08",u:238,t:"num",d:.35,q:"Nathan a perdu 19 points courts sur ses fautes. S'il en évite la moitié (arrondi à l'unité inférieure), combien de points récupère-t-il ?",a:9,tol:0,un:" points",h:"19 divisé par 2, arrondi en dessous",w:"9 points de plus sur un match serré, c'est souvent la différence entre gagner et perdre."},
{i:"t238_09",u:238,t:"mcq",d:.4,q:"Quatre frappes, c'est au maximum combien de coups par joueur ?",o:["Deux","Quatre","Un","Trois"],a:0,w:"Service et coup + 1, ou retour et coup suivant : deux coups chacun."},
{i:"t238_10",u:238,t:"story",d:.4,q:"Rappel du module 4 : Clara demande quelle statistique au service regarder en premier.",sc:[{who:"Clara",txt:"Le nombre d'aces ?"}],o:["« Le % de points gagnés sur la deuxième balle, il dit souvent plus. »","« Uniquement le nombre d'aces, c'est la mesure de tout bon service. »","« La vitesse maximale du radar, le reste n'a aucune importance. »","« Le nombre de lets, car ils montrent la précision du lancer. »"],a:0,w:"Les aces impressionnent ; la deuxième balle révèle la solidité du service."},
{i:"t238_11",u:238,t:"tiles",d:.45,q:"Reconstitue le premier moyen mnémotechnique du module.",a:["70","dans","les","4"],dd:["80","9","hors"],w:"70 % des points se jouent en 4 frappes ou moins."},
{i:"t238_12",u:238,t:"multi",d:.45,q:"Quels coups font partie des quatre premières frappes ?",o:["Le service","Le retour","Le coup + 1 du serveur","Le coup suivant du relanceur","La quinzième frappe de l'échange"],a:[0,1,2,3],w:"Les quatre premières frappes : service, retour, coup + 1, coup suivant du relanceur."},
{i:"t238_13",u:238,t:"fill",d:.5,q:"Une faute commise sur une balle jouable, sans pression, est une faute ___.",o:["directe","provoquée","gagnante","double"],a:0,w:"La faute directe est celle qu'on peut éliminer à l'entraînement et par la marge."},
{i:"t238_14",u:238,t:"num",d:.5,q:"Paul a converti 3 balles de break sur 5. Quel pourcentage ?",a:60,tol:0,un:" %",h:"3 divisé par 5",w:"60 % : une très bonne efficacité sur les points importants."},
{i:"t238_15",u:238,t:"story",d:.55,q:"Nathan veut s'entraîner deux heures par jour aux échanges de fond. Que proposes-tu ?",sc:[{who:"Nathan",txt:"Je dois être plus régulier."}],o:["« Passe la moitié du temps sur service, retour et coup suivant. »","« Parfait, les longs échanges représentent l'essentiel des points. »","« Entraîne-toi uniquement au smash, c'est le coup le plus décisif. »","« Arrête l'entraînement, le tennis se joue surtout dans la tête. »"],a:0,w:"70 dans les 4 : l'entraînement doit suivre la réalité du match."},
{i:"t238_16",u:238,t:"tf",d:.55,q:"Chez les amateurs, la grande majorité des points se terminent sur une faute.",a:true,w:"C'est pourquoi réduire ses fautes directes est le levier le plus rentable."},
{i:"t238_17",u:238,t:"match",d:.6,q:"Associe chaque statistique à ce qu'elle mesure.",p:[["% de premières balles","Régularité du service"],["Balles de break sauvées","Solidité sous pression"],["Points gagnés au retour","Pression sur le serveur"],["Fautes directes","Erreurs sans pression"]],w:"Chaque statistique éclaire une situation de jeu."},
{i:"t238_18",u:238,t:"story",d:.6,q:"Clara a perdu 7-5, 7-5 en gagnant 49 % des points. Elle se dit « nulle ». Que lui répond Valérie ?",sc:[{who:"Clara",txt:"Je suis nulle."}],o:["« Tu étais à deux points du match : un petit écart change tout. »","« Oui, 49 % des points, c'est un niveau très faible au tennis. »","« Tu aurais dû gagner 80 % des points pour avoir une chance. »","« Les pourcentages de points ne veulent rien dire au tennis. »"],a:0,w:"54 suffit : un point sur cent de plus, bien placé, et le match bascule."},
{i:"t238_19",u:238,t:"sort",d:.65,q:"Classe chaque affirmation : vraie ou idée reçue ?",bins:["Vraie","Idée reçue"],it:[["Plus de coups gagnants garantit la victoire",1],["70 % des points pros durent 4 frappes ou moins",0],["Les aces disent tout du service",1],["Federer a gagné environ 54 % des points",0]],w:"Deux idées reçues corrigées dans le guide."},
{i:"t238_20",u:238,t:"mcq",d:.65,q:"Qui a popularisé la statistique des 0 à 4 frappes ?",o:["Craig O'Shannessy","Roger Federer","Patrick Mouratoglou","Rafael Nadal"],a:0,w:"L'analyste Craig O'Shannessy, qui a notamment travaillé avec Novak Djokovic."},
{i:"t238_21",u:238,t:"num",d:.7,q:"Malik a 35 coups gagnants et 52 fautes directes. Quel est son bilan ?",a:-17,tol:0,un:"",h:"35 moins 52",w:"Moins 17 : un bilan négatif malgré un record de coups gagnants."},
{i:"t238_22",u:238,t:"story",d:.7,q:"Rappel du module 5 : que conclure de ces chiffres pour le retour ?",sc:[{who:"Clara",txt:"Le retour fait partie des 4 premières frappes ?"}],o:["« Oui : un retour remis au centre, et tu joues l'essentiel des points. »","« Non : le retour ne compte pas dans les statistiques de frappes. »","« Oui, et il faut donc tenter un retour gagnant à chaque point. »","« Non, car seuls les points de plus de neuf frappes comptent vraiment. »"],a:0,w:"Le retour est la deuxième frappe : le rater, c'est perdre un point court. RPC."},
{i:"t238_23",u:238,t:"fill",d:.75,q:"Un petit avantage par point, répété, fait gagner les ___.",o:["matchs","lets","balles","raquettes"],a:0,w:"54 suffit : Federer a gagné près de 80 % de ses matchs avec 54 % des points."},
{i:"t238_24",u:238,t:"order",d:.75,q:"Remets dans l'ordre la méthode pour noter un match.",it:["Préparer les colonnes","Noter le nombre de frappes","Noter la fin du point","Compter les totaux","En tirer une priorité d'entraînement"],w:"La feuille de Clara : mesurer, compter, décider."},
{i:"t238_25",u:238,t:"tf",d:.8,q:"Une faute provoquée est causée par la qualité du coup de l'adversaire.",a:true,w:"Un retour raté sur un service très rapide est une faute provoquée, pas une faute directe. La faute provoquée se distingue de la faute directe dans la feuille de statistiques."},
{i:"t238_26",u:238,t:"multi",d:.8,q:"Quelles priorités d'entraînement découlent de ces chiffres ?",o:["La régularité au retour","Le service + 1","Le pourcentage de premières balles","La deuxième balle","Les échanges de trente coups uniquement"],a:[0,1,2,3],w:"Les points longs existent, mais ils ne représentent qu'environ 10 % du total."},
{i:"t238_27",u:238,t:"story",d:.85,q:"Malik veut savoir s'il doit être plus agressif au retour contre un joueur qui gagne 75 % de ses points sur première balle et 40 % sur deuxième.",sc:[{who:"Malik",txt:"Je l'attaque où ?"}],o:["« Sur sa deuxième balle : c'est là qu'il est fragile. »","« Sur sa première balle, en tentant des retours gagnants. »","« Nulle part, il est trop fort au service pour l'attaquer. »","« Sur ses aces, en devinant la direction à chaque point. »"],a:0,w:"40 % sur deuxième balle : le serveur y perd six points sur dix. Recule sur la première, avance sur la deuxième."},
{i:"t238_28",u:238,t:"match",d:.85,q:"Associe chaque ligne de la feuille de Clara à sa lecture.",p:[["71 % de points courts","Le match se joue au début du point"],["19 fautes courtes de Nathan","Priorité : retour et coup suivant"],["Paul : 3 breaks sur 5","Efficace sur les points importants"],["Bilan négatif de Nathan","Trop de fautes directes"]],w:"Une statistique n'a de valeur que si elle débouche sur une décision. Une faute provoquée compte comme un point gagné par la qualité du coup adverse."},
{i:"t238_29",u:238,t:"tiles",d:.9,q:"Reconstitue le second moyen mnémotechnique.",a:["54","suffit"],dd:["100","jamais","80"],w:"On n'a pas besoin de gagner tous les points pour gagner le match."},
{i:"t238_30",u:238,t:"mcq",d:.9,q:"Quel est le levier le plus rentable pour un amateur ?",o:["Réduire ses fautes directes","Frapper plus d'aces","Tenter plus de coups gagnants","Changer de raquette"],a:0,w:"Chez les amateurs, la plupart des points finissent sur une faute."},
{i:"t238_31",u:238,t:"story",d:.95,q:"Rappel du module 2 : Nathan demande si la statistique des 54 % s'applique aussi à son classement.",sc:[{who:"Nathan",txt:"Je peux perdre des matchs et monter ?"}],o:["« Oui : ce sont tes meilleures victoires qui comptent, pas toutes. »","« Non : une seule défaite annule toutes tes victoires de l'année. »","« Oui, si tu gagnes au moins 80 % des points de chaque match. »","« Non : le classement FFT ne compte que le nombre de matchs joués. »"],a:0,w:"Le classement FFT retient les meilleures victoires : on peut perdre des matchs et monter."},
{i:"t238_32",u:238,t:"story",d:.95,q:"Synthèse : Valérie demande à Clara ce que sa feuille a changé pour l'équipe.",sc:[{who:"Valérie",txt:"Qu'est-ce qu'on retient ?"}],o:["« 70 dans les 4, moins de fautes directes, et 54 suffit pour gagner. »","« Frapper plus de coups gagnants, quel qu'en soit le prix en fautes. »","« Allonger les échanges, car les longs points font gagner les matchs. »","« Oublier les chiffres, qui ne servent qu'aux professionnels. »"],a:0,w:"Mesurer pour décider : entraîner les premières frappes et réduire les fautes."}
