/*UNIT*/
{id:240,c:"TENNIS",n:"Module 10",t:"Lire l'adversaire : profils, échauffement et plan B",col:"--gold",ic:"🔎",guide:`
<h3>L'enquête de l'échauffement</h3>
<div class="gstory">Samedi, 14 h, tournoi de Muret. Clara affronte Sophie, une 30 qu'elle n'a jamais vue. Valérie lui a donné une consigne pour les cinq minutes d'échauffement : « Tu n'es pas là pour te réchauffer seulement. Tu es là pour enquêter. » Clara envoie une balle haute sur le revers : Sophie la renvoie en slice, mal à l'aise. Une balle basse : parfait coup droit. Une balle courte : Sophie reste au fond. Un lob : smash hésitant. Au premier changement de côté, Clara a son plan : balles hautes sur le revers, et quelques amorties. Elle gagne 6-3, 6-2.</div>
<h3>Les cinq tests de l'échauffement</h3>
<table><tr><th>Test</th><th>Ce qu'on cherche</th></tr>
<tr><td>Balle <b>haute</b> sur chaque côté</td><td>Le côté qui gère mal les balles hautes</td></tr>
<tr><td>Balle <b>basse</b> en slice</td><td>Si l'adversaire plie les jambes</td></tr>
<tr><td>Balle <b>courte</b></td><td>S'il avance volontiers, ou reste au fond</td></tr>
<tr><td><b>Lob</b></td><td>La qualité de son smash</td></tr>
<tr><td>Ses <b>volées</b></td><td>S'il est à l'aise au filet</td></tr></table>
<h3>Les profils de joueurs et comment les jouer</h3>
<table><tr><th>Profil</th><th>Il aime</th><th>Plan contre lui</th></tr>
<tr><td><b>Contreur</b> (défenseur)</td><td>Les longs échanges, la vitesse adverse</td><td>Patience, monter au filet, amorties, varier le rythme</td></tr>
<tr><td><b>Attaquant de fond</b> (frappeur)</td><td>Les balles à hauteur de hanche, le temps</td><td>Balles basses en slice, profondeur au centre, le faire courir</td></tr>
<tr><td><b>Serveur-volleyeur</b></td><td>Les points courts, le filet</td><td>Retours dans les pieds, passings en deux temps, lobs</td></tr>
<tr><td><b>Pousseur</b> (balles hautes et lentes)</td><td>Les fautes adverses</td><td>Prendre la balle tôt, monter, volée haute</td></tr>
<tr><td><b>Gaucher</b></td><td>Son coup droit croisé sur le revers d'un droitier</td><td>Protéger son revers, jouer son revers à lui, anticiper le slicé côté avantage</td></tr></table>
<h3>Plan A, plan B</h3>
<p>Le vieux principe de Bill Tilden, champion des années 1920, reste d'actualité : <b>on ne change jamais une tactique qui gagne, on change toujours une tactique qui perd</b>. On se donne un plan A, un plan B, et un moment pour décider (par exemple, après un set perdu ou deux breaks d'écart).</p>
<div class="gmnemo"><b>« Haut, bas, court, lob, volée : cinq questions avant le premier point. »</b> Et pour le plan : <b>« Qui gagne continue, qui perd change. »</b></div>
<div class="gtrap">Idée reçue : « l'échauffement sert seulement à se chauffer ». Faux : c'est une enquête gratuite. Autre piège : juger un adversaire à son allure ou à son matériel. Un joueur au style peu académique, qui renvoie tout, bat souvent les joueurs « jolis » qui font des fautes.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Mener l'enquête pendant l'échauffement</li><li>Reconnaître un profil et choisir un plan</li><li>Décider quand passer au plan B</li></ul>`},
/*EXOS*/
{i:"t240_01",u:240,t:"story",d:.2,nw:"Lire l'adversaire",q:"Clara demande à quoi servent vraiment les cinq minutes d'échauffement.",sc:[{who:"Clara",txt:"Je me chauffe les bras, non ?"}],o:["« Tu enquêtes : balle haute, basse, courte, lob, volées. »","« À rien, on peut commencer le match directement sans échauffement. »","« À frapper le plus fort possible pour impressionner l'adversaire. »","« À choisir le côté du terrain où il y a le moins de soleil. »"],a:0,w:"Haut, bas, court, lob, volée : cinq questions avant le premier point."},
{i:"t240_02",u:240,t:"match",d:.2,q:"Associe chaque profil au plan contre lui.",p:[["Contreur","Monter au filet, amorties"],["Attaquant de fond","Balles basses slicées"],["Serveur-volleyeur","Retours dans les pieds"],["Pousseur","Prendre la balle tôt"]],w:"Chaque profil a un point faible qu'on exploite."},
{i:"t240_03",u:240,t:"fill",d:.25,q:"On ne change jamais une tactique qui gagne, on change toujours une tactique qui ___.",o:["perd","gagne","plaît","dure"],a:0,w:"Le principe de Bill Tilden : qui gagne continue, qui perd change."},
{i:"t240_04",u:240,t:"tf",d:.25,q:"Un joueur au style peu académique est forcément facile à battre.",a:false,w:"Un joueur qui renvoie tout bat souvent les joueurs « jolis » qui font des fautes."},
{i:"t240_05",u:240,t:"story",d:.3,q:"Nathan affronte un contreur qui renvoie tout. Il perd les échanges de fond. Quel plan ?",sc:[{who:"Nathan",txt:"Il est comme un mur."}],o:["« Patience, puis monte au filet et glisse des amorties. »","« Frappe de plus en plus fort jusqu'à ce qu'il craque. »","« Joue au centre à la même vitesse pendant tout le match. »","« Abandonne le match, les contreurs sont imbattables. »"],a:0,w:"Contre un contreur : patience, montées, amorties, variations de rythme."},
{i:"t240_06",u:240,t:"sort",d:.3,q:"Quel profil ?",bins:["Contreur","Attaquant de fond","Serveur-volleyeur"],it:[["Monte au filet après chaque service",2],["Renvoie tout en défense",0],["Frappe fort à hauteur de hanche",1],["Adore les échanges de trente coups",0],["Veut des points très courts au filet",2],["Cherche le coup gagnant du fond",1]],w:"Reconnaître le profil, c'est choisir le plan."},
{i:"t240_07",u:240,t:"tiles",d:.35,q:"Reconstitue les cinq tests de l'échauffement.",a:["haut","bas","court","lob","volée"],dd:["fort","service","vite"],w:"Cinq questions avant le premier point. À l'échauffement, chaque test révèle un point faible qu'on utilise dès le premier jeu."},
{i:"t240_08",u:240,t:"mcq",d:.35,q:"Pendant l'échauffement, l'adversaire renvoie les balles hautes sur son revers en slice, mal à l'aise. Que faire ?",o:["Viser son revers en balle haute","Éviter son revers","Jouer uniquement dans son coup droit","Ne rien en déduire"],a:0,w:"L'échauffement révèle le point faible : on s'en sert dès le premier jeu."},
{i:"t240_09",u:240,t:"story",d:.4,q:"Malik affronte un pousseur qui renvoie des balles hautes et lentes. Malik fait faute sur faute. Ton conseil ?",sc:[{who:"Malik",txt:"Ses balles sont nulles et je perds !"}],o:["« Avance, prends la balle tôt, et viens finir à la volée. »","« Recule contre le grillage et attends que la balle redescende. »","« Frappe chaque balle à plat au maximum depuis ta ligne de fond. »","« Renvoie les mêmes balles lentes pendant trois heures s'il le faut. »"],a:0,w:"Contre le pousseur : prendre la balle tôt, monter, volée haute."},
{i:"t240_10",u:240,t:"multi",d:.4,q:"Quelles informations peut-on recueillir à l'échauffement ?",o:["Le côté faible sur balle haute","S'il plie les jambes sur balle basse","S'il avance sur balle courte","La qualité de son smash","Son classement exact"],a:[0,1,2,3],w:"Le classement se lit sur l'application, pas dans les frappes."},
{i:"t240_11",u:240,t:"fill",d:.45,q:"Contre un attaquant de fond, on joue des balles ___ en slice.",o:["basses","hautes","lentes et hautes","dans le couloir"],a:0,w:"Le frappeur aime les balles à hauteur de hanche : le slice bas le prive de cette zone."},
{i:"t240_12",u:240,t:"story",d:.45,q:"Rappel du module 4 : Clara affronte un gaucher. Où doit-elle attendre son service sur les points importants côté avantage ?",sc:[{who:"Clara",txt:"Il est gaucher, ça change quoi ?"}],o:["« Le slicé extérieur, qui fuit vers ton revers. »","« Toujours au T, les gauchers ne servent pas ailleurs. »","« Dans ton coup droit, c'est leur service favori. »","« À la cuillère, c'est la spécialité des gauchers. »"],a:0,w:"L'arme du gaucher côté avantage : le slicé qui fuit sur le revers d'un droitier."},
{i:"t240_13",u:240,t:"order",d:.5,q:"Remets dans l'ordre la méthode avant et pendant un match.",it:["Enquête à l'échauffement","Plan A choisi","Point de décision fixé","Bilan au changement de côté","Plan B si le plan A perd"],w:"Qui gagne continue, qui perd change, à un moment décidé à l'avance."},
{i:"t240_14",u:240,t:"tf",d:.5,q:"Contre un serveur-volleyeur, les lobs et les passings en deux temps sont efficaces.",a:true,w:"Pieds d'abord, passing ensuite, et le lob s'il colle au filet (module 7)."},
{i:"t240_15",u:240,t:"story",d:.55,q:"Nathan mène 6-2, 3-1 avec son plan A. Il se demande s'il doit « varier pour ne pas être lu ». Ton avis ?",sc:[{who:"Nathan",txt:"Il va finir par comprendre."}],o:["« Continue : on ne change pas une tactique qui gagne. »","« Change tout maintenant, avant qu'il ne s'adapte à toi. »","« Passe au plan C, et garde le plan B pour le troisième set. »","« Arrête de jouer ton coup droit, il est trop prévisible. »"],a:0,w:"Qui gagne continue : c'est à l'adversaire de trouver une solution."},
{i:"t240_16",u:240,t:"match",d:.55,q:"Associe chaque test d'échauffement à ce qu'il révèle.",p:[["Balle haute","Le côté fragile en hauteur"],["Balle basse","S'il plie les jambes"],["Balle courte","S'il aime avancer"],["Lob","La qualité du smash"]],w:"Cinq questions, cinq réponses. On mène l'enquête pendant l'échauffement, avant même le premier point."},
{i:"t240_17",u:240,t:"mcq",d:.6,q:"Qui a formulé le principe « ne change jamais une tactique qui gagne » ?",o:["Bill Tilden","Rafael Nadal","Craig O'Shannessy","Serena Williams"],a:0,w:"Bill Tilden, champion américain des années 1920, auteur de livres de tactique."},
{i:"t240_18",u:240,t:"story",d:.6,q:"Clara perd 2-6, 0-2 avec son plan A (échanges de fond). Que fait-elle ?",sc:[{who:"Clara",txt:"Je continue, ça va tourner."}],o:["« Passe au plan B maintenant : monte, varie, change quelque chose. »","« Continue le plan A, la chance va finir par tourner en ta faveur. »","« Frappe plus fort avec le même plan, c'est le même plan en mieux. »","« Abandonne pour garder de l'énergie pour le prochain tournoi. »"],a:0,w:"Qui perd change : un plan perdant ne devient pas gagnant par miracle."},
{i:"t240_19",u:240,t:"sort",d:.65,q:"Classe chaque affirmation : vraie ou idée reçue ?",bins:["Vraie","Idée reçue"],it:[["L'échauffement sert seulement à se chauffer",1],["On juge un adversaire à sa raquette",1],["Le pousseur vit des fautes adverses",0],["Le gaucher cible le revers d'un droitier",0]],w:"Deux idées reçues corrigées dans le guide."},
{i:"t240_20",u:240,t:"num",d:.65,q:"Clara a noté 5 balles hautes sur le revers de Sophie à l'échauffement : 4 revenues courtes. Quel pourcentage ?",a:80,tol:0,un:" %",h:"4 divisé par 5",w:"80 % de balles courtes : le point faible est confirmé, le plan est clair."},
{i:"t240_21",u:240,t:"story",d:.7,q:"Rappel du module 6 : Malik affronte un grand frappeur de 1,95 m. Quel effet domine son plan ?",sc:[{who:"Malik",txt:"Il frappe tout ce qui arrive à la hanche."}],o:["« Le slice bas : fais-le plier sur chaque balle. »","« Le lift haut : c'est la balle qu'il préfère frapper. »","« Le plat à mi-hauteur, pile dans sa zone favorite. »","« La chandelle, parce qu'un grand ne sait pas smasher. »"],a:0,w:"Slice pour le piège : un grand joueur déteste se baisser."},
{i:"t240_22",u:240,t:"fill",d:.7,q:"Qui gagne continue, qui perd ___.",o:["change","abandonne","accélère","recommence"],a:0,w:"Le plan B se déclenche à un moment fixé à l'avance."},
{i:"t240_23",u:240,t:"multi",d:.75,q:"Comment jouer un contreur ?",o:["Faire preuve de patience","Monter au filet","Glisser des amorties","Varier le rythme","Frapper toujours plus fort depuis le fond"],a:[0,1,2,3],w:"Frapper toujours plus fort, c'est jouer son jeu : il vit de la vitesse adverse."},
{i:"t240_24",u:240,t:"story",d:.75,q:"Nathan découvre à l'échauffement que son adversaire smashe très mal. Comment l'utiliser ?",sc:[{who:"Nathan",txt:"Il rate tous ses smashs."}],o:["« Quand il monte, lobe-le : c'est un point presque gratuit. »","« Ne lobe jamais, il pourrait progresser pendant le match. »","« Monte toi-même au filet pour lui montrer comment smasher. »","« Rien, le smash n'arrive jamais dans un vrai match de tennis. »"],a:0,w:"Un point faible repéré à l'échauffement devient une arme dès le premier jeu."},
{i:"t240_25",u:240,t:"mcq",d:.8,q:"Quand décider de passer au plan B ?",o:["À un moment fixé à l'avance","Au premier point perdu","Jamais","Quand l'arbitre le dit"],a:0,w:"Par exemple après un set perdu ou deux breaks d'écart : on évite les changements de panique."},
{i:"t240_26",u:240,t:"tf",d:.8,q:"Contre un pousseur, reculer loin derrière sa ligne est la meilleure solution.",a:false,w:"On avance, on prend la balle tôt et on vient finir au filet."},
{i:"t240_27",u:240,t:"story",d:.85,q:"Rappel du module 8 : Clara veut prouver à Valérie que son plan B a fonctionné. Que note-t-elle ?",sc:[{who:"Clara",txt:"J'ai l'impression que ça a mieux marché."}],o:["« Les points gagnés au filet et les fautes directes avant et après. »","« Uniquement le score final, les détails n'ont aucune importance. »","« Le nombre de spectateurs, qui montre l'intérêt du match. »","« La couleur de la balle, car elle change la vitesse du jeu. »"],a:0,w:"Mesurer pour décider : comparer les chiffres avant et après le changement de plan."},
{i:"t240_28",u:240,t:"tiles",d:.85,q:"Reconstitue la règle du plan de jeu.",a:["qui","gagne","continue","qui","perd","change"],dd:["toujours","abandonne","jamais"],w:"Le principe de Bill Tilden, en version courte."},
{i:"t240_29",u:240,t:"num",d:.9,q:"Clara a gagné 11 points sur 15 au filet après son plan B, contre 3 sur 10 au fond avant. Combien de points gagnés au filet en plus ?",a:8,tol:0,un:" points",h:"11 moins 3",w:"8 points de plus : le plan B a changé le match."},
{i:"t240_30",u:240,t:"match",d:.9,q:"Associe chaque profil à ce qu'il aime.",p:[["Contreur","Les longs échanges"],["Attaquant de fond","Les balles à la hanche"],["Serveur-volleyeur","Les points courts"],["Pousseur","Les fautes adverses"]],w:"Savoir ce qu'il aime, c'est savoir ce qu'il ne faut pas lui donner."},
{i:"t240_31",u:240,t:"story",d:.95,q:"Malik joue un inconnu qui n'a pas de point faible visible à l'échauffement. Quel plan A ?",sc:[{who:"Malik",txt:"Il fait tout bien."}],o:["« Ton jeu : service + 1, croisé profond, et observe les premiers jeux. »","« Aucun plan : attends de voir ce qui se passe au troisième set. »","« Joue toutes tes balles dans son coup droit pour le rassurer. »","« Change de plan à chaque point pour qu'il ne comprenne rien. »"],a:0,w:"Sans indice, on joue ses points forts et on continue l'enquête pendant le match."},
{i:"t240_32",u:240,t:"story",d:.95,q:"Synthèse : Valérie demande à Clara comment elle a battu Sophie.",sc:[{who:"Valérie",txt:"Explique aux autres."}],o:["« J'ai enquêté à l'échauffement, choisi un plan, et je l'ai gardé. »","« J'ai frappé plus fort qu'elle sur chaque balle, du début à la fin. »","« J'ai joué au hasard, la chance a fait le reste du match. »","« J'ai changé de tactique à chaque jeu pour la surprendre. »"],a:0,w:"Haut, bas, court, lob, volée ; puis qui gagne continue, qui perd change."}
