/*UNIT*/
{id:241,c:"TENNIS",n:"Module 11",t:"Surfaces, vent et soleil : adapter son plan au terrain",col:"--gold",ic:"🌦️",guide:`
<h3>Trois tournois, trois matchs différents</h3>
<div class="gstory">En juillet, Malik enchaîne trois tournois. À Toulouse, sur terre battue, par 32 °C, ses services reviennent tous et les échanges durent quinze coups. À Albi, en salle sur résine, ses services font mal et il gagne en une heure. À Castres, en plein air sur surface synthétique, le vent souffle à 30 km/h : il envoie six coups droits dans le grillage avec le vent dans le dos. Le soir, Valérie lui dit : « Tu as joué trois fois le même match. Or tu as joué sur trois terrains différents. Le terrain fait partie de l'adversaire. »</div>
<h3>Les surfaces</h3>
<table><tr><th>Surface</th><th>Vitesse et rebond</th><th>Qui en profite</th><th>Tournoi repère</th></tr>
<tr><td><b>Terre battue</b></td><td>Lente, rebond haut, on glisse</td><td>Les joueurs patients et liftés, les défenseurs</td><td>Roland-Garros (Rafael Nadal, 14 titres)</td></tr>
<tr><td><b>Gazon</b></td><td>Rapide, rebond bas et parfois irrégulier</td><td>Les serveurs, le slice, le jeu vers l'avant</td><td>Wimbledon</td></tr>
<tr><td><b>Dur</b> (résine)</td><td>Moyen à rapide, rebond régulier</td><td>Les joueurs complets</td><td>Open d'Australie, US Open</td></tr>
<tr><td><b>Salle</b></td><td>Souvent rapide, sans vent ni soleil</td><td>Les serveurs et les attaquants</td><td>ATP Finals</td></tr></table>
<p>La Fédération internationale (ITF) classe la vitesse des surfaces en <b>cinq catégories</b>, de lente à rapide, grâce à un indice de vitesse du court (Court Pace Rating).</p>
<h3>Les conditions</h3>
<ul><li><b>Chaleur</b> : balle plus vive, rebond plus haut. <b>Froid et humidité</b> : balle lourde et lente.</li>
<li><b>Altitude</b> : l'air est moins dense, la balle va plus vite et plus loin (Madrid, à plus de 600 m).</li>
<li><b>Vent de face</b> : la balle ralentit, on peut frapper plus fort et plus profond. <b>Vent dans le dos</b> : la balle file, on ajoute du lift et de la marge. <b>Vent de côté</b> : on vise plus au centre.</li>
<li><b>Soleil</b> : on décale un peu son lancer de balle au service, et l'on lobe l'adversaire qui a le soleil dans les yeux.</li></ul>
<div class="gmnemo"><b>« Terre : patience, gazon : vitesse, dur : équilibre. »</b> Et pour le vent : <b>« Vent de face, on frappe. Vent dans le dos, on lifte. »</b></div>
<div class="gtrap">Idée reçue : « on joue pareil partout ». C'est faux. Sur terre, le coup gagnant arrive plus tard dans l'échange. Sur gazon, le service et le premier coup pèsent davantage. Autre erreur : ignorer le changement de côté. On change de côté après les jeux impairs (module 1), donc le vent et le soleil changent de camp, et la tactique aussi.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Adapter son plan à la surface</li><li>Jouer avec le vent, le soleil, la chaleur et l'altitude</li><li>Profiter du changement de côté</li></ul>`},
/*EXOS*/
{i:"t241_01",u:241,t:"story",d:.2,nw:"Surfaces et conditions",q:"Malik a joué de la même façon sur trois surfaces. Que lui dit Valérie ?",sc:[{who:"Malik",txt:"Mon jeu est mon jeu."}],o:["« Le terrain fait partie de l'adversaire : adapte ton plan. »","« Tu as raison, un bon joueur ne change jamais rien selon le terrain. »","« Ne joue plus que sur terre battue, c'est la seule vraie surface. »","« Change de raquette à chaque surface, c'est le seul réglage qui compte. »"],a:0,w:"Terre : patience, gazon : vitesse, dur : équilibre."},
{i:"t241_02",u:241,t:"match",d:.2,q:"Associe chaque surface à sa caractéristique.",p:[["Terre battue","Lente, rebond haut"],["Gazon","Rapide, rebond bas"],["Dur","Rebond régulier"],["Salle","Sans vent ni soleil"]],w:"Chaque surface récompense un style différent."},
{i:"t241_03",u:241,t:"fill",d:.25,q:"Vent de face, on frappe ; vent dans le dos, on ___.",o:["lifte","smashe","s'arrête","plonge"],a:0,w:"Avec le vent dans le dos, la balle file : le lift la fait redescendre."},
{i:"t241_04",u:241,t:"tf",d:.25,q:"Rafael Nadal a remporté Roland-Garros 14 fois.",a:true,w:"Un record sur terre battue, surface lente qui récompense la patience et le lift."},
{i:"t241_05",u:241,t:"story",d:.3,q:"Malik envoie ses coups droits dans le grillage avec le vent dans le dos. Que doit-il changer ?",sc:[{who:"Malik",txt:"Tout sort !"}],o:["« Ajoute du lift et de la marge : le vent pousse ta balle. »","« Frappe encore plus fort à plat pour que la balle traverse le vent. »","« Arrête de jouer tant que le vent ne s'est pas complètement calmé. »","« Vise directement le filet, le vent fera monter la balle au-dessus. »"],a:0,w:"Vent dans le dos, on lifte : l'effet ramène la balle dans le terrain."},
{i:"t241_06",u:241,t:"sort",d:.3,q:"Terre battue ou gazon ?",bins:["Terre battue","Gazon"],it:[["Rebond haut",0],["Rebond bas",1],["Échanges longs",0],["Service très payant",1],["On glisse sur ses appuis",0],["Wimbledon",1]],w:"Terre : patience ; gazon : vitesse. Terre : patience ; gazon : vitesse ; dur : équilibre."},
{i:"t241_07",u:241,t:"slider",d:.35,q:"En combien de catégories l'ITF classe-t-elle la vitesse des surfaces ?",min:1,max:10,step:1,a:5,tol:0,pre:"",un:" catégories",w:"Cinq catégories, de lente à rapide, selon l'indice de vitesse du court."},
{i:"t241_08",u:241,t:"mcq",d:.35,q:"Quel effet a l'altitude sur la balle ?",o:["Elle va plus vite et plus loin","Elle ralentit très fortement","Elle rebondit beaucoup plus bas","Aucun effet mesurable"],a:0,w:"L'air est moins dense : moins de freinage. À Madrid, les joueurs ajoutent de l'effet."},
{i:"t241_09",u:241,t:"story",d:.4,q:"Clara joue un matin froid et humide sur terre battue. Ses balles restent courtes. Que conseilles-tu ?",sc:[{who:"Clara",txt:"La balle est lourde."}],o:["« Frappe plus haut et plus loin : la balle lourde ralentit. »","« Joue des amorties, c'est la seule balle possible par ce temps. »","« Frappe plus bas, pour que la balle ne prenne pas l'humidité. »","« Change de chaussures, c'est ta seule solution par temps humide. »"],a:0,w:"Froid et humidité : balle lourde. La hauteur donne la longueur (module 6)."},
{i:"t241_10",u:241,t:"multi",d:.4,q:"Qu'est-ce qui rend la balle plus vive ?",o:["La chaleur","L'altitude","Une surface rapide","Le froid humide","Jouer en salle sur une surface rapide"],a:[0,1,2,4],w:"Le froid humide alourdit la balle. La chaleur, l'altitude et les surfaces rapides accélèrent la balle : on ajoute du lift."},
{i:"t241_11",u:241,t:"tiles",d:.45,q:"Reconstitue le moyen mnémotechnique des surfaces.",a:["terre","patience","gazon","vitesse","dur","équilibre"],dd:["salle","hasard","lenteur"],w:"Chaque surface récompense une qualité. La salle, sans vent ni soleil, favorise souvent les serveurs."},
{i:"t241_12",u:241,t:"story",d:.45,q:"Rappel du module 7 : sur gazon, Nathan hésite à monter au filet. Qu'en penses-tu ?",sc:[{who:"Nathan",txt:"Je reste au fond comme sur terre ?"}],o:["« Monte davantage : le rebond bas gêne les passings. »","« Reste au fond, on ne monte jamais au filet sur gazon. »","« Monte uniquement en fin de match, quand tu es épuisé. »","« Joue uniquement des lobs, le gazon fait monter la balle. »"],a:0,w:"Gazon : vitesse. Le jeu vers l'avant et le slice y sont payants."},
{i:"t241_13",u:241,t:"fill",d:.5,q:"Sur terre battue, le rebond est ___.",o:["haut","bas","nul","irrégulier"],a:0,w:"La terre ralentit la balle et la fait monter : on lifte et on patiente."},
{i:"t241_14",u:241,t:"tf",d:.5,q:"Par vent de côté, on vise plus près des lignes pour profiter du vent.",a:false,w:"Par vent de côté, on vise plus au centre : le vent déporte la balle."},
{i:"t241_15",u:241,t:"story",d:.55,q:"Le soleil est dans les yeux de l'adversaire de Malik quand il monte au filet. Quel coup tenter ?",sc:[{who:"Malik",txt:"Il plisse les yeux."}],o:["« Le lob : il devra regarder la balle dans le soleil. »","« Une balle à plat dans ses pieds, sans jamais lober. »","« Une amortie, pour qu'il avance encore plus vers toi. »","« Rien de spécial, le soleil ne change rien au jeu. »"],a:0,w:"Le soleil fait partie du terrain : on lobe l'adversaire qui l'a dans les yeux."},
{i:"t241_16",u:241,t:"order",d:.55,q:"Classe ces surfaces de la plus lente à la plus rapide (en général).",it:["Terre battue","Dur (résine)","Gazon"],w:"Terre : lente ; dur : moyen à rapide ; gazon : rapide."},
{i:"t241_17",u:241,t:"match",d:.6,q:"Associe chaque condition à l'adaptation.",p:[["Vent de face","Frapper plus fort"],["Vent dans le dos","Ajouter du lift"],["Vent de côté","Viser le centre"],["Soleil au service","Décaler le lancer"]],w:"Vent de face, on frappe ; vent dans le dos, on lifte."},
{i:"t241_18",u:241,t:"story",d:.6,q:"Rappel du module 1 : Clara joue contre le vent sur ce côté. Quand pourra-t-elle profiter du vent dans le dos ?",sc:[{who:"Clara",txt:"On change de côté quand ?"}],o:["« Après les jeux impairs : 1, 3, 5... le vent change de camp. »","« Jamais : on garde le même côté pendant tout le match. »","« Seulement à la fin du set, après le sixième jeu. »","« À chaque point joué, comme pendant le jeu décisif. »"],a:0,w:"On change de côté après les jeux impairs : la tactique change avec le vent."},
{i:"t241_19",u:241,t:"mcq",d:.65,q:"Quel tournoi se joue sur gazon ?",o:["Wimbledon","Roland-Garros","US Open","Open d'Australie"],a:0,w:"Wimbledon : gazon. Roland-Garros : terre battue. US Open et Open d'Australie : dur."},
{i:"t241_20",u:241,t:"sort",d:.65,q:"Classe chaque affirmation : vraie ou idée reçue ?",bins:["Vraie","Idée reçue"],it:[["On joue pareil sur toutes les surfaces",1],["Le changement de côté change le vent",0],["Sur gazon, le service pèse davantage",0],["La chaleur ralentit la balle",1]],w:"La chaleur rend la balle plus vive ; le froid humide l'alourdit."},
{i:"t241_21",u:241,t:"num",d:.7,q:"Sur terre battue, les échanges de Malik durent 15 coups ; en salle, 4 coups. Combien de coups de plus par point sur terre ?",a:11,tol:0,un:" coups",h:"15 moins 4",w:"Terre : patience. Le plan doit prévoir plus de construction."},
{i:"t241_22",u:241,t:"story",d:.7,q:"Nathan joue un tournoi à Madrid, en altitude. Ses balles sortent. Que faire ?",sc:[{who:"Nathan",txt:"La balle vole !"}],o:["« Plus d'effet lifté pour faire redescendre la balle. »","« Frappe plus à plat pour aller bien plus droit. »","« Joue avec une balle plus lourde, c'est autorisé. »","« Frappe moins haut au-dessus du filet, à ras. »"],a:0,w:"En altitude, l'air freine moins la balle : le lift la ramène dans le terrain."},
{i:"t241_23",u:241,t:"tf",d:.75,q:"En salle, il n'y a ni vent ni soleil à gérer.",a:true,w:"Les conditions sont stables : c'est souvent favorable aux serveurs et aux attaquants."},
{i:"t241_24",u:241,t:"fill",d:.75,q:"L'ITF mesure la vitesse d'un court grâce au Court Pace ___.",o:["Rating","Speed","Index Ball","Timer"],a:0,w:"Le Court Pace Rating classe les surfaces en cinq catégories."},
{i:"t241_25",u:241,t:"multi",d:.8,q:"Sur terre battue, que faut-il privilégier ?",o:["La patience","Le lift","La construction du point","Les glissades maîtrisées","Le service-volée systématique"],a:[0,1,2,3],w:"Le service-volée systématique est plutôt une arme de gazon."},
{i:"t241_26",u:241,t:"story",d:.8,q:"Rappel du module 10 : Clara affronte un contreur sur terre battue lente. Quel plan ?",sc:[{who:"Clara",txt:"Il est chez lui ici."}],o:["« Patience, puis amorties : sur terre, elles meurent vite. »","« Des coups gagnants dès le premier coup, sans construire. »","« Des balles à plat très rapides, que la terre accélère. »","« Aucun plan possible, un contreur sur terre est imbattable. »"],a:0,w:"Contre un contreur : patience, amorties, montées. La terre ralentit l'amortie."},
{i:"t241_27",u:241,t:"mcq",d:.85,q:"Sur quelle surface se jouent l'US Open et l'Open d'Australie ?",o:["Le dur","La terre battue","Le gazon","La moquette"],a:0,w:"Deux tournois sur dur, surface au rebond régulier qui récompense les joueurs complets."},
{i:"t241_28",u:241,t:"tiles",d:.85,q:"Reconstitue la règle du vent.",a:["vent","de","face","on","frappe"],dd:["dos","lifte","côté"],w:"Et vent dans le dos, on lifte. Et vent de côté : on vise plus au centre, car le vent déporte la balle."},
{i:"t241_29",u:241,t:"story",d:.9,q:"Malik a gagné en une heure en salle grâce à son service. Il veut garder ce plan sur terre battue. Ton avis ?",sc:[{who:"Malik",txt:"Mon service marche partout."}],o:["« Sur terre, tes services reviendront : prépare des échanges plus longs. »","« Garde exactement ce plan, un bon service suffit sur toutes les surfaces. »","« Arrête de servir fort sur terre, c'est interdit par le règlement. »","« Sers uniquement à la cuillère, la terre avantage ce service. »"],a:0,w:"Terre : patience. Le service y reste utile, mais le point dure plus longtemps."},
{i:"t241_30",u:241,t:"num",d:.9,q:"Malik commence le match face au vent. Après combien de jeux joués aura-t-il changé de côté deux fois ?",a:3,tol:0,un:" jeux",h:"On change après les jeux 1 et 3",w:"Changement après le 1er jeu, puis après le 3e : les jeux impairs."},
{i:"t241_31",u:241,t:"sort",d:.95,q:"Quelle adaptation pour quelle condition ?",bins:["Plus de lift","Viser le centre","Frapper plus fort"],it:[["Vent dans le dos",0],["Altitude",0],["Vent de côté",1],["Vent de face",2]],w:"Vent de face, on frappe ; vent dans le dos, on lifte ; vent de côté, on vise le centre."},
{i:"t241_32",u:241,t:"story",d:.95,q:"Synthèse : Valérie demande à Malik ce qu'il fera avant chaque match désormais.",sc:[{who:"Valérie",txt:"Ta routine d'avant-match ?"}],o:["« Regarder la surface, le vent, le soleil, et adapter mon plan. »","« Rien de nouveau, je jouerai exactement comme en salle partout. »","« Choisir uniquement des tournois en salle pour éviter le vent. »","« Changer de raquette selon la météo annoncée à la télévision. »"],a:0,w:"Le terrain fait partie de l'adversaire : on l'intègre au plan."}
