/*UNIT*/
{id:242,c:"TENNIS",n:"Module 12",t:"Le mental entre les points : 25 secondes pour tout changer",col:"--gold",ic:"🧠",guide:`
<h3>La raquette de Nathan</h3>
<div class="gstory">Championnat régional, deuxième set. Nathan rate un smash facile, crie, tape sa raquette sur le sol, et perd les trois points suivants en ruminant. Au changement de côté, Valérie lui montre son téléphone : une vidéo de ses 25 secondes après le smash. Tête basse, épaules tombées, il se précipite pour servir en 8 secondes. « Regarde. Le point était fini, mais toi, tu le rejouais encore. On va construire ta routine. » Deux semaines plus tard, même situation, Nathan tourne le dos au filet, remet ses cordes droites, respire lentement, regarde sa cible. Il gagne le point suivant.</div>
<h3>Le temps entre les points</h3>
<p>Le point dure en moyenne quelques secondes ; le temps entre deux points peut aller jusqu'à <b>25 secondes</b> chez les professionnels (compte à rebours officiel). On passe donc plus de temps <b>entre</b> les points que <b>pendant</b>. C'est là que se joue le mental.</p>
<h3>La routine en quatre étapes</h3>
<p>Le psychologue du sport Jim Loehr a observé les meilleurs joueurs et décrit une routine en quatre étapes :</p>
<table><tr><th>Étape</th><th>Ce que l'on fait</th></tr>
<tr><td>1. <b>Réagir</b></td><td>Une réaction physique positive : se retourner, changer la raquette de main, épaules hautes</td></tr>
<tr><td>2. <b>Relâcher</b></td><td>Respirer lentement (l'expiration plus longue que l'inspiration), marcher tranquillement</td></tr>
<tr><td>3. <b>Préparer</b></td><td>Regarder le score, choisir le plan du point suivant (cible, schéma)</td></tr>
<tr><td>4. <b>Ritualiser</b></td><td>Le même rituel avant chaque point : rebonds de balle, regard vers la cible</td></tr></table>
<h3>Ce qui aide vraiment</h3>
<ul><li><b>Se concentrer sur ce qu'on contrôle</b> : sa cible, son effort, sa routine. Pas l'arbitre, ni le public, ni le score final.</li>
<li><b>Le langage corporel</b> : l'adversaire lit tes épaules. Garder une posture droite aide aussi ton propre cerveau à tourner la page.</li>
<li><b>Le changement de côté</b> (90 secondes) : boire, faire le bilan, choisir le plan des deux jeux suivants.</li>
<li><b>La pression est un privilège</b> : la formule de Billie Jean King rappelle que la pression signifie que l'on joue quelque chose d'important.</li></ul>
<div class="gmnemo"><b>« Réagir, Relâcher, Préparer, Ritualiser : les 4 R. »</b> Et à chaque erreur : <b>« Point fini, point oublié. »</b></div>
<div class="gtrap">Idée reçue : « se mettre en colère réveille ». Parfois, sur un point ; mais la colère qui dure fait perdre les points suivants, comme Nathan. Autre piège : se précipiter après un point perdu. Servir en 8 secondes, c'est rejouer le point précédent. On utilise son temps.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Construire une routine entre les points</li><li>Distinguer ce qu'on contrôle de ce qu'on ne contrôle pas</li><li>Utiliser le changement de côté</li></ul>`},
/*EXOS*/
{i:"t242_01",u:242,t:"story",d:.2,nw:"Le mental",q:"Nathan vient de rater un smash facile et veut servir tout de suite pour « se rattraper ». Que lui dit Valérie ?",sc:[{who:"Nathan",txt:"Vite, je sers !"}],o:["« Prends ton temps : réagis, respire, prépare, puis ton rituel. »","« Oui, sers le plus vite possible, avant que la colère ne retombe. »","« Crie encore plus fort pour évacuer, puis sers sans réfléchir. »","« Demande à l'arbitre de rejouer le smash que tu viens de rater. »"],a:0,w:"Les 4 R : Réagir, Relâcher, Préparer, Ritualiser. Point fini, point oublié."},
{i:"t242_02",u:242,t:"order",d:.2,q:"Remets dans l'ordre les quatre étapes de la routine entre les points.",it:["Réagir","Relâcher","Préparer","Ritualiser"],w:"La routine de Jim Loehr : réaction positive, détente, plan, rituel."},
{i:"t242_03",u:242,t:"slider",d:.25,q:"Combien de secondes au maximum entre deux points chez les pros ?",min:5,max:60,step:1,a:25,tol:0,pre:"",un:" s",w:"25 secondes, avec un compte à rebours officiel. On passe plus de temps entre les points que pendant."},
{i:"t242_04",u:242,t:"fill",d:.25,q:"Point fini, point ___.",o:["oublié","rejoué","perdu","compté"],a:0,w:"On ne rejoue pas le point précédent dans sa tête : on prépare le suivant."},
{i:"t242_05",u:242,t:"tf",d:.3,q:"Pendant l'étape « Relâcher », on expire plus longtemps qu'on inspire.",a:true,w:"Une expiration longue calme le rythme cardiaque : c'est la base de la détente entre les points."},
{i:"t242_06",u:242,t:"sort",d:.3,q:"Ce que je contrôle ou ce que je ne contrôle pas ?",bins:["Je contrôle","Je ne contrôle pas"],it:[["Ma cible au service",0],["La décision de l'arbitre",1],["Ma respiration",0],["Le public",1],["Ma routine",0],["Le vent",1]],w:"On se concentre sur ce qu'on contrôle. Se concentrer sur ce qu'on contrôle libère l'attention pour le point suivant."},
{i:"t242_07",u:242,t:"story",d:.35,q:"Clara s'énerve contre les annonces douteuses de son adversaire. Elle perd quatre jeux de suite. Ton conseil ?",sc:[{who:"Clara",txt:"Elle triche, j'en suis sûre !"}],o:["« Appelle le juge-arbitre si besoin, puis reviens à ta cible. »","« Triche à ton tour, c'est la seule façon de rétablir l'équilibre. »","« Arrête de jouer et discute de chaque balle pendant dix minutes. »","« Accepte de perdre ce match, la triche est impossible à combattre. »"],a:0,w:"On règle le problème par la bonne voie, puis on revient à sa cible et à sa routine."},
{i:"t242_08",u:242,t:"match",d:.35,q:"Associe chaque étape à un exemple.",p:[["Réagir","Changer la raquette de main"],["Relâcher","Longue expiration"],["Préparer","Choisir sa cible"],["Ritualiser","Faire rebondir la balle"]],w:"Les 4 R, avec un geste concret pour chacun."},
{i:"t242_09",u:242,t:"mcq",d:.4,q:"Qui a formulé « la pression est un privilège » ?",o:["Billie Jean King","Jim Loehr","Bill Tilden","Craig O'Shannessy"],a:0,w:"Billie Jean King : la pression signifie que l'on joue quelque chose d'important."},
{i:"t242_10",u:242,t:"tiles",d:.4,q:"Reconstitue les 4 R.",a:["Réagir","Relâcher","Préparer","Ritualiser"],dd:["Rejouer","Râler","Ruminer"],w:"Rejouer, râler, ruminer : les trois R à éviter."},
{i:"t242_11",u:242,t:"story",d:.45,q:"Rappel du module 9 : Malik a une balle de break contre lui et sent ses jambes trembler. Que fait-il pendant ses 25 secondes ?",sc:[{who:"Malik",txt:"J'ai le cœur à 180."}],o:["« Longue expiration, cible la plus sûre, puis ton rituel. »","« Sers immédiatement, le stress disparaîtra une fois le point joué. »","« Pense au score final et à ce que diront tes parents après. »","« Change de plan complètement, c'est le moment de tout essayer. »"],a:0,w:"Relâcher puis préparer : gros point, gros pourcentage."},
{i:"t242_12",u:242,t:"multi",d:.45,q:"Que fait-on pendant le changement de côté ?",o:["Boire","Faire le bilan","Choisir le plan des deux jeux suivants","Respirer calmement","Ruminer les points perdus"],a:[0,1,2,3],w:"90 secondes pour récupérer et décider, pas pour ruminer."},
{i:"t242_13",u:242,t:"fill",d:.5,q:"Le changement de côté dure ___ secondes.",o:["90","25","300","10"],a:0,w:"90 secondes ; 120 secondes entre deux sets ; pas de pause après le premier jeu d'un set."},
{i:"t242_14",u:242,t:"tf",d:.5,q:"Le langage corporel n'a aucun effet sur l'adversaire.",a:false,w:"L'adversaire lit tes épaules : une tête basse lui donne confiance. Une posture droite t'aide aussi à tourner la page."},
{i:"t242_15",u:242,t:"story",d:.55,q:"Nathan dit qu'il « joue mieux énervé ». Que lui réponds-tu ?",sc:[{who:"Nathan",txt:"La colère me réveille."}],o:["« Parfois sur un point, mais la colère qui dure t'a coûté trois points. »","« Tu as raison, plus tu es en colère, plus tu joues bien au tennis. »","« La colère est interdite par le règlement, tu risques la disqualification. »","« Joue énervé tout le match, ton adversaire aura peur de toi. »"],a:0,w:"La vidéo l'a montré : trois points perdus en ruminant."},
{i:"t242_16",u:242,t:"num",d:.55,q:"Un point dure 6 secondes en moyenne et la pause 25 secondes. Combien de secondes de pause par seconde de jeu (arrondi au dixième) ?",a:4.2,tol:.1,un:" s",h:"25 divisé par 6",w:"Environ 4 secondes de pause par seconde de jeu : le mental se joue entre les points."},
{i:"t242_17",u:242,t:"match",d:.6,q:"Associe chaque pause à sa durée.",p:[["Entre deux points","25 s maximum"],["Changement de côté","90 s"],["Entre deux sets","120 s"],["Après le 1er jeu d'un set","Pas de pause assise"]],w:"Les durées officielles, que les amateurs gagnent à respecter aussi."},
{i:"t242_18",u:242,t:"story",d:.6,q:"Clara perd 1-5 et commence à « lâcher » les points. Que peut-elle se dire ?",sc:[{who:"Clara",txt:"C'est fichu."}],o:["« Un point à la fois : gagne ce jeu, puis le suivant. »","« C'est fichu, autant perdre vite et rentrer chez toi. »","« Tente des coups impossibles, il n'y a plus rien à perdre. »","« Arrête de jouer ton jeu et imite celui de ton adversaire. »"],a:0,w:"Se concentrer sur ce qu'on contrôle : le point suivant."},
{i:"t242_19",u:242,t:"sort",d:.65,q:"Classe chaque affirmation : vraie ou idée reçue ?",bins:["Vraie","Idée reçue"],it:[["La colère qui dure fait gagner",1],["Se précipiter après une faute aide",1],["On passe plus de temps entre les points que pendant",0],["Un rituel identique aide à se concentrer",0]],w:"Deux idées reçues corrigées dans le guide."},
{i:"t242_20",u:242,t:"mcq",d:.65,q:"Quel psychologue a décrit la routine en quatre étapes entre les points ?",o:["Jim Loehr","Billie Jean King","Bill Tilden","Rafael Nadal"],a:0,w:"Jim Loehr a observé les meilleurs joueurs et décrit ces quatre étapes."},
{i:"t242_21",u:242,t:"story",d:.7,q:"Rappel du module 10 : Malik perd 1-6 avec son plan A. Il est découragé. Comment utiliser la pause entre les sets ?",sc:[{who:"Malik",txt:"Je ne sais plus quoi faire."}],o:["« Respire, fais le bilan, et décide ton plan B. »","« Rumine les erreurs du set, pour ne plus jamais les refaire. »","« Quitte le terrain, un set perdu 1-6 annonce la défaite. »","« Écoute ta musique sans penser au match pendant la pause. »"],a:0,w:"La pause sert à décider : qui perd change."},
{i:"t242_22",u:242,t:"fill",d:.7,q:"Après un point perdu, la première étape est une réaction physique ___.",o:["positive","colérique","immobile","négative"],a:0,w:"Se retourner, changer la raquette de main, relever les épaules : le corps aide la tête."},
{i:"t242_23",u:242,t:"multi",d:.75,q:"Qu'est-ce qu'un bon rituel avant le point ?",o:["Le même à chaque point","Court","Tourné vers la cible","Qui calme","Différent à chaque fois"],a:[0,1,2,3],w:"Le rituel rassure parce qu'il est toujours le même."},
{i:"t242_24",u:242,t:"story",d:.75,q:"Nathan mène 5-1 et commence à penser à la finale. Il perd deux jeux. Que lui dis-tu ?",sc:[{who:"Nathan",txt:"Je me voyais déjà en finale."}],o:["« Reviens au point présent : ta cible, ta routine, rien d'autre. »","« Pense encore plus à la finale, cela te donnera de l'énergie. »","« Arrête de jouer quelques points pour laisser l'adversaire revenir. »","« Change de raquette pour marquer le début d'un nouveau match. »"],a:0,w:"Se concentrer sur ce qu'on contrôle : le point présent, pas le résultat."},
{i:"t242_25",u:242,t:"tf",d:.8,q:"Selon Billie Jean King, la pression est un privilège.",a:true,w:"La pression signifie qu'on joue quelque chose d'important : on peut l'accueillir plutôt que la fuir."},
{i:"t242_26",u:242,t:"tiles",d:.8,q:"Reconstitue la règle après une erreur.",a:["point","fini","point","oublié"],dd:["rejoué","perdu","toujours"],w:"On ne rejoue pas le point précédent. Les 4 R (Réagir, Relâcher, Préparer, Ritualiser) servent justement à tourner la page."},
{i:"t242_27",u:242,t:"num",d:.85,q:"Valérie chronomètre Nathan : 8 secondes entre la faute et son service. Combien de secondes lui restait-il sur les 25 ?",a:17,tol:0,un:" s",h:"25 moins 8",w:"17 secondes inutilisées pour réagir, relâcher, préparer et ritualiser."},
{i:"t242_28",u:242,t:"story",d:.85,q:"Rappel du module 8 : Clara veut savoir si sa routine marche. Que mesure-t-elle ?",sc:[{who:"Clara",txt:"Comment savoir ?"}],o:["« Les points gagnés juste après une faute, avant et après. »","« Le nombre de fois où elle a regardé le public pendant le match. »","« La durée totale du match, plus il est long, mieux c'est. »","« Rien du tout, le mental ne se mesure jamais au tennis. »"],a:0,w:"Mesurer pour décider : on compare les points qui suivent une erreur."},
{i:"t242_29",u:242,t:"mcq",d:.9,q:"Pendant l'étape « Préparer », que regarde-t-on ?",o:["Le score et le plan du point suivant","Les réactions du public en tribune","Les messages de son téléphone","Le tableau affiché du tournoi"],a:0,w:"On choisit la cible et le schéma du point suivant, selon le score."},
{i:"t242_30",u:242,t:"story",d:.9,q:"Malik enchaîne les doubles fautes et se traite de « nul » à voix haute. Que proposes-tu ?",sc:[{who:"Malik",txt:"Je suis nul, nul, nul."}],o:["« Remplace par une consigne : « Haut, lifté, sur le revers ». »","« Continue, se critiquer fort aide à se motiver pour la suite. »","« Crie encore plus fort pour que l'adversaire ait pitié de toi. »","« Arrête de servir et joue uniquement des services à la cuillère. »"],a:0,w:"Une consigne technique simple remplace le jugement : on revient à ce qu'on contrôle."},
{i:"t242_31",u:242,t:"sort",d:.95,q:"Quelle étape des 4 R ?",bins:["Réagir","Relâcher","Préparer"],it:[["Relever les épaules",0],["Marcher lentement",1],["Regarder le score",2],["Longue expiration",1],["Choisir sa cible",2]],w:"Réagir, Relâcher, Préparer, puis Ritualiser."},
{i:"t242_32",u:242,t:"story",d:.95,q:"Synthèse : Valérie demande à Nathan ce qui a changé depuis la vidéo.",sc:[{who:"Valérie",txt:"Qu'est-ce que tu fais maintenant ?"}],o:["« Les 4 R entre chaque point, et je ne rejoue plus le point fini. »","« Je crie plus fort après chaque faute pour évacuer ma colère. »","« Je sers plus vite pour ne pas laisser la colère retomber. »","« Je ne regarde plus jamais le score pendant le match. »"],a:0,w:"25 secondes pour tout changer : Réagir, Relâcher, Préparer, Ritualiser."}
