/*UNIT*/
{id:243,c:"TENNIS",n:"Module 13",t:"Le double : formations, interceptions et jeu au centre",col:"--gold",ic:"👥",guide:`
<h3>Clara et Malik, la paire improbable</h3>
<div class="gstory">Tournoi de double mixte du club, en juin. Valérie associe Clara, régulière et calme, à Malik, gaucher explosif. Premier set : chacun joue son simple, Malik reste collé à sa ligne de fond, Clara ne bouge pas au filet. 2-6. Pendant la pause, Valérie dessine sur une serviette : « Au centre, la solution. Malik, tu montes derrière ton service. Clara, sur le retour croisé, tu interceptes. Et vous vous parlez avant chaque point. » Clara fait un signe dans son dos, main ouverte : elle va croiser. Trois interceptions gagnantes plus tard, ils remportent le super jeu décisif 10-7.</div>
<h3>Les formations au service</h3>
<table><tr><th>Formation</th><th>Placement</th><th>Pourquoi</th></tr>
<tr><td><b>Classique</b></td><td>Le partenaire du serveur est au filet du côté opposé</td><td>Chacun couvre sa moitié</td></tr>
<tr><td><b>Australienne</b></td><td>Le partenaire est au filet du <b>même côté</b> que le serveur</td><td>Bloquer le retour croisé d'un relanceur qui le maîtrise</td></tr>
<tr><td><b>En I</b></td><td>Le partenaire est accroupi au centre du filet, le serveur près du centre</td><td>Semer le doute : on se décale au dernier moment</td></tr></table>
<div class="gsvg-wrap"><svg class='gsvg' viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Formation classique</text><circle cx='80' cy='188' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><circle cx='52' cy='118' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><circle cx='50' cy='12' r='4.5' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/><circle cx='86' cy='80' r='4.5' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/></svg></div>
<h3>Les principes du double</h3>
<ul><li><b>Au centre, la solution</b> : une balle entre les deux adversaires crée l'hésitation et réduit les angles.</li>
<li><b>Prendre le filet</b> : l'équipe qui a les deux joueurs au filet gagne la majorité des points. On monte derrière son service ou son retour.</li>
<li><b>L'interception</b> (poaching) : le joueur au filet traverse pour volleyer le retour croisé. Le partenaire couvre le côté laissé libre.</li>
<li><b>Les signaux</b> : le joueur au filet montre dans son dos un <b>poing fermé</b> (je reste) ou une <b>main ouverte</b> (je croise).</li>
<li><b>Les cibles</b> : les pieds du joueur au filet, ou le lob au-dessus de lui.</li></ul>
<h3>Les règles propres au double</h3>
<ul><li>L'ordre de service est fixé pour chaque set ; chaque relanceur garde son côté de retour pendant tout le set.</li>
<li>Au <b>point décisif</b> (sans avantage), l'équipe qui retourne choisit qui reçoit.</li>
<li>Les couloirs sont en jeu (10,97 m de large, sauf au service).</li>
<li>Le <b>super jeu décisif</b> en 10 points remplace souvent le troisième set.</li></ul>
<div class="gmnemo"><b>« Au centre, la solution. »</b> Et pour les signaux : <b>« Poing fermé, je reste ; main ouverte, je croise. »</b></div>
<div class="gtrap">Idée reçue : « le double, c'est deux simples côte à côte ». Faux : on joue ensemble, on se déplace comme reliés par une corde, et l'on vise le centre plutôt que les couloirs. Autre piège : le joueur au filet qui ne bouge jamais. Même sans interception, une fausse feinte gêne le relanceur.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Choisir une formation selon le relanceur</li><li>Intercepter et couvrir</li><li>Communiquer par signaux</li><li>Appliquer les règles du double</li></ul>`},
/*EXOS*/
{i:"t243_01",u:243,t:"story",d:.2,nw:"Le double",q:"Clara et Malik jouent chacun leur simple et perdent 2-6. Quel conseil principal leur donne Valérie ?",sc:[{who:"Malik",txt:"On joue bien, chacun de notre côté."}],o:["« Jouez ensemble : visez le centre, montez, parlez-vous. »","« Jouez chacun dans votre couloir, sans jamais vous parler. »","« Restez tous les deux au fond pendant tout le match. »","« Laissez Malik jouer toutes les balles, il frappe plus fort. »"],a:0,w:"Au centre, la solution ; le double se joue en équipe. Au centre, la solution : les deux adversaires hésitent."},
{i:"t243_02",u:243,t:"mcq",d:.2,q:"Quelle formation montre ce schéma ?",svg:"<svg viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Quelle formation ?</text><circle cx='80' cy='188' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><circle cx='82' cy='118' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><circle cx='50' cy='12' r='4.5' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/><circle cx='86' cy='80' r='4.5' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/></svg>",o:["Australienne","Classique","En I","Deux au fond"],a:0,w:"Le partenaire est au filet du même côté que le serveur : formation australienne."},
{i:"t243_03",u:243,t:"mcq",d:.25,q:"Et ce schéma, quelle formation ?",svg:"<svg viewBox='0 0 140 216' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='25' y='9' width='90' height='181' fill='var(--green-d)' rx='2'/><rect x='31' y='15' width='78' height='169' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='15' x2='40.7' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='99.3' y1='15' x2='99.3' y2='184' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='54' x2='99.3' y2='54' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='40.7' y1='145' x2='99.3' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='54' x2='70' y2='145' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='25' y1='99.5' x2='115' y2='99.5' stroke='var(--gold)' stroke-width='2'/><line x1='70' y1='184' x2='70' y2='181' stroke='var(--txt)' stroke-width='1.2' fill='none'/><line x1='70' y1='15' x2='70' y2='18' stroke='var(--txt)' stroke-width='1.2' fill='none'/><text x='70' y='212' font-size='7.5' fill='var(--txt)' text-anchor='middle' font-weight='700'>Quelle formation ?</text><circle cx='71' cy='188' r='4.5' fill='var(--blue)' stroke='var(--bg)' stroke-width='1'/><circle cx='70' cy='114' r='4.5' fill='var(--blue)' stroke='var(--bg)'/><circle cx='50' cy='12' r='4.5' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/><circle cx='86' cy='80' r='4.5' fill='var(--red)' stroke='var(--bg)' stroke-width='1'/></svg>",o:["En I","Classique","Australienne","Deux au fond"],a:0,w:"Le partenaire accroupi au centre du filet : formation en I, pour semer le doute."},
{i:"t243_04",u:243,t:"fill",d:.25,q:"Poing fermé, je reste ; main ouverte, je ___.",o:["croise","recule","sers","lobe"],a:0,w:"Le signal du joueur au filet, montré dans le dos, avant le service."},
{i:"t243_05",u:243,t:"tf",d:.3,q:"En double, les couloirs sont en jeu, sauf au service.",a:true,w:"Le terrain fait 10,97 m de large en double, mais le service doit tomber dans le carré de simple."},
{i:"t243_06",u:243,t:"story",d:.3,q:"Le relanceur adverse fait mal avec son retour croisé à chaque point. Quelle formation proposes-tu ?",sc:[{who:"Clara",txt:"Il nous transperce en croisé."}],o:["« L'australienne : je me place de son côté, le croisé est fermé. »","« Restons en classique, il finira par rater ses retours croisés. »","« Plaçons-nous tous les deux au fond pour récupérer ses retours. »","« Changeons de serveur à chaque point pour le perturber. »"],a:0,w:"La formation australienne bloque le retour croisé et oblige le relanceur à jouer long de ligne."},
{i:"t243_07",u:243,t:"match",d:.35,q:"Associe chaque formation à son but.",p:[["Classique","Chacun couvre sa moitié"],["Australienne","Bloquer le retour croisé"],["En I","Semer le doute"],["Deux au filet","Gagner le point en volée"]],w:"La formation se choisit selon le relanceur."},
{i:"t243_08",u:243,t:"sort",d:.35,q:"Bonne ou mauvaise cible en double ?",bins:["Bonne cible","Mauvaise cible"],it:[["Entre les deux adversaires",0],["Les pieds du joueur au filet",0],["Le couloir à chaque balle",1],["Un lob au-dessus du joueur au filet",0],["Une balle haute sur le volleyeur",1]],w:"Au centre, dans les pieds, ou par-dessus : jamais une balle haute offerte au volleyeur. Au centre, la solution : c'est la cible de base du double."},
{i:"t243_09",u:243,t:"story",d:.4,q:"Clara intercepte au filet. Que doit faire Malik, qui vient de servir ?",sc:[{who:"Malik",txt:"Elle part, et moi ?"}],o:["« Tu couvres le côté qu'elle laisse libre. »","« Tu restes à ta place et tu regardes l'échange. »","« Tu cours vers le filet derrière elle, du même côté. »","« Tu sors du terrain pour lui laisser plus de place. »"],a:0,w:"L'interception se joue à deux : le partenaire couvre le côté laissé libre."},
{i:"t243_10",u:243,t:"tiles",d:.4,q:"Reconstitue le principe du double.",a:["au","centre","la","solution"],dd:["couloir","fond","problème"],w:"Une balle au centre crée l'hésitation et réduit les angles."},
{i:"t243_11",u:243,t:"multi",d:.45,q:"Pourquoi viser le centre en double ?",o:["Les deux adversaires hésitent","Les angles se réduisent","Le filet est plus bas","On évite les couloirs","Le centre est interdit aux adversaires"],a:[0,1,2,3],w:"Rien n'interdit le centre aux adversaires : c'est l'hésitation qui fait la force de cette cible."},
{i:"t243_12",u:243,t:"fill",d:.45,q:"Au point décisif en double, c'est l'équipe qui ___ qui choisit qui reçoit.",o:["retourne","sert","mène","perd"],a:0,w:"Elle place au retour son meilleur relanceur du côté choisi."},
{i:"t243_13",u:243,t:"story",d:.5,q:"Rappel du module 7 : Malik sert puis reste au fond. Clara lui demande de monter. Pourquoi a-t-elle raison ?",sc:[{who:"Clara",txt:"Viens au filet avec moi !"}],o:["« L'équipe qui a ses deux joueurs au filet gagne la majorité des points. »","« Parce qu'il est interdit de rester au fond après le service en double. »","« Parce que le relanceur adverse ne peut pas faire de lob en double. »","« Parce que le fond de court est réservé au partenaire du relanceur. »"],a:0,w:"Prendre le filet : on monte derrière son service ou son retour."},
{i:"t243_14",u:243,t:"tf",d:.5,q:"En double, un relanceur peut changer de côté de retour à chaque jeu du même set.",a:false,w:"Chaque relanceur garde son côté de retour pendant tout le set ; l'ordre de service est aussi fixé pour le set."},
{i:"t243_15",u:243,t:"order",d:.55,q:"Remets dans l'ordre une interception réussie.",it:["Signal main ouverte dans le dos","Service au T","Départ au moment du retour","Volée au centre ou dans les pieds","Le serveur couvre le côté libre"],w:"Signal, service, départ au bon moment, volée, couverture."},
{i:"t243_16",u:243,t:"mcq",d:.55,q:"Quelle est la largeur du terrain de double ?",o:["10,97 m","8,23 m","12,50 m","9,40 m"],a:0,w:"10,97 m avec les couloirs, contre 8,23 m en simple (module 1)."},
{i:"t243_17",u:243,t:"story",d:.6,q:"Les deux adversaires sont au filet. Clara est au fond, en difficulté. Quel coup ?",sc:[{who:"Clara",txt:"Ils sont tous les deux collés au filet."}],o:["« Un lob par-dessus, ou une balle basse au centre. »","« Une balle haute et lente au milieu de leurs raquettes. »","« Un coup à plat dans le couloir, à chaque fois. »","« Une amortie, puisqu'ils sont déjà au filet. »"],a:0,w:"Contre deux volleyeurs : par-dessus ou dans les pieds, au centre. Au centre, la solution, même contre deux volleyeurs."},
{i:"t243_18",u:243,t:"match",d:.6,q:"Associe chaque signal ou mot au sens.",p:[["Poing fermé","Je reste"],["Main ouverte","Je croise"],["Poaching","Interception au filet"],["Fausse feinte","Faire douter le relanceur"]],w:"Poing fermé, je reste ; main ouverte, je croise."},
{i:"t243_19",u:243,t:"num",d:.65,q:"Clara et Malik gagnent le super jeu décisif 10-7. Combien de points ont été joués ?",a:17,tol:0,un:" points",h:"10 + 7",w:"17 points : le super jeu décisif en 10 points remplace le troisième set."},
{i:"t243_20",u:243,t:"sort",d:.65,q:"Classe chaque affirmation : vraie ou idée reçue ?",bins:["Vraie","Idée reçue"],it:[["Le double, c'est deux simples côte à côte",1],["Le joueur au filet ne doit jamais bouger",1],["On vise souvent le centre",0],["L'équipe qui retourne choisit au point décisif",0]],w:"Deux idées reçues corrigées dans le guide."},
{i:"t243_21",u:243,t:"story",d:.7,q:"Rappel du module 4 : Malik sert en double. Quelle cible facilite l'interception de Clara ?",sc:[{who:"Clara",txt:"Sers où pour que je puisse croiser ?"}],o:["« Au T : le retour revient vers le centre, là où tu interceptes. »","« À l'extérieur, pour que le retour parte loin de Clara. »","« Directement sur Clara, pour qu'elle volleye le service. »","« Un service très lent, pour laisser à Clara le temps de courir. »"],a:0,w:"Au T, l'angle du retour est fermé : la balle revient vers le centre, à portée de l'intercepteur."},
{i:"t243_22",u:243,t:"fill",d:.7,q:"Dans la formation ___, le partenaire est au filet du même côté que le serveur.",o:["australienne","classique","en I","parallèle"],a:0,w:"Elle ferme le retour croisé. La formation en I, elle, place le partenaire accroupi au centre du filet. Au centre, la solution."},
{i:"t243_23",u:243,t:"multi",d:.75,q:"Quelles règles s'appliquent au double ?",o:["Ordre de service fixé par set","Côté de retour fixé par set","Couloirs en jeu hors service","Super jeu décisif fréquent au 3e set","Service dans les couloirs autorisé"],a:[0,1,2,3],w:"Le service doit toujours tomber dans le carré de service de simple."},
{i:"t243_24",u:243,t:"story",d:.75,q:"Clara n'ose jamais intercepter. Le relanceur adverse joue tranquillement croisé. Que lui dis-tu ?",sc:[{who:"Clara",txt:"J'ai peur de laisser un trou."}],o:["« Fais au moins des fausses feintes : il doit douter de toi. »","« Reste immobile, c'est la meilleure façon de ne rien rater. »","« Recule au fond, tu seras plus utile en défense. »","« Tourne le dos au relanceur pour ne pas être influencée. »"],a:0,w:"Même sans interception, une feinte gêne le relanceur."},
{i:"t243_25",u:243,t:"mcq",d:.8,q:"Quelle équipe gagne le plus souvent le point en double ?",o:["Celle qui a ses deux joueurs au filet","Celle qui reste au fond de court","Celle qui sert le plus fort du tableau","Celle qui lobe à chaque coup joué"],a:0,w:"Prendre le filet : on volleye, on réduit le temps adverse et on vise le centre."},
{i:"t243_26",u:243,t:"story",d:.8,q:"Rappel du module 9 : 40-40, point décisif. Clara et Malik retournent. Qui reçoit ?",sc:[{who:"Malik",txt:"On choisit qui reçoit ?"}],o:["« Le meilleur relanceur face à ce service : vous choisissez. »","« Toujours celui qui a reçu le point précédent, c'est la règle. »","« Le serveur adverse décide qui doit recevoir le service. »","« L'arbitre tire au sort celui des deux qui reçoit. »"],a:0,w:"Au point décisif, l'équipe qui retourne choisit : gros point, gros pourcentage."},
{i:"t243_27",u:243,t:"tiles",d:.85,q:"Reconstitue le code des signaux.",a:["poing","fermé","je","reste"],dd:["ouvert","croise","sers"],w:"Et main ouverte, je croise. Le signal se montre dans le dos, avant le service, pour que le relanceur ne le voie pas."},
{i:"t243_28",u:243,t:"tf",d:.85,q:"En double, une balle haute sur le joueur au filet adverse est une bonne cible.",a:false,w:"C'est un cadeau : le volleyeur conclut. On vise ses pieds ou au-dessus de lui."},
{i:"t243_29",u:243,t:"story",d:.9,q:"Malik et Clara perdent 0-3 avec la formation classique. Que proposes-tu ?",sc:[{who:"Clara",txt:"On essaie autre chose ?"}],o:["« Oui : australienne ou en I, pour changer les repères du relanceur. »","« Non : on ne change jamais de formation pendant un match de double. »","« Oui : jouez tous les deux au fond et sans jamais monter. »","« Non : attendez le troisième set pour changer quoi que ce soit. »"],a:0,w:"Qui perd change (module 10) : la formation est un levier simple."},
{i:"t243_30",u:243,t:"match",d:.9,q:"Associe chaque situation à la bonne réponse.",p:[["Retour croisé redoutable","Formation australienne"],["Adversaires au filet","Lob ou pieds"],["Partenaire qui intercepte","Couvrir le côté libre"],["Balle au milieu","Celui qui a le coup droit"]],w:"Au milieu, on convient à l'avance que le coup droit (ou celui qui a volleyé le coup d'avant) prend la balle."},
{i:"t243_31",u:243,t:"num",d:.95,q:"En simple, le terrain fait 8,23 m de large ; en double, 10,97 m. Quelle est la largeur d'un couloir (arrondi au centième) ?",a:1.37,tol:.01,un:" m",h:"(10,97 moins 8,23) divisé par 2",w:"1,37 m par couloir : autant d'espace à défendre, d'où le jeu au centre."},
{i:"t243_32",u:243,t:"story",d:.95,q:"Synthèse : Valérie demande à la paire ce qui a retourné le match.",sc:[{who:"Valérie",txt:"Alors, ce double ?"}],o:["« Viser le centre, monter ensemble, intercepter et se parler. »","« Chacun a joué son simple, mais plus fort qu'au premier set. »","« On est restés au fond pour ne plus jamais être lobés. »","« Malik a pris toutes les balles et Clara a regardé. »"],a:0,w:"Au centre, la solution ; poing fermé, je reste ; main ouverte, je croise."}
