/*UNIT*/
{id:244,c:"TENNIS",n:"Module 14",t:"Le jour du match : préparer, coacher, récupérer",col:"--gold",ic:"🎒",guide:`
<h3>Le sac de Nathan</h3>
<div class="gstory">Dimanche 8 h 45, tournoi de Montauban, match à 9 h 30. Nathan arrive en retard, sans petit-déjeuner, avec une seule raquette. Au premier jeu, il casse une corde. Il emprunte une raquette trop lourde, s'énerve, a faim au deuxième set et perd. Valérie ne dit rien sur la route du retour. Le lendemain, elle lui tend une liste plastifiée : « Avant, pendant, après. Tu la gardes dans ton sac. » Trois semaines plus tard, même tournoi, même adversaire : Nathan arrive une heure avant, s'échauffe quinze minutes, garde deux raquettes cordées, une banane et une gourde. Il gagne 6-3, 6-4.</div>
<h3>Avant le match</h3>
<table><tr><th>Quand</th><th>Quoi</th></tr>
<tr><td>La veille</td><td>Sac prêt : <b>deux raquettes</b> au moins, surgrips, gourde, en-cas, serviette, tenue de rechange</td></tr>
<tr><td>2 à 3 h avant</td><td>Un repas riche en glucides et facile à digérer</td></tr>
<tr><td>45 à 60 min avant</td><td>Arriver, se signaler au juge-arbitre, repérer le court</td></tr>
<tr><td>15 min avant</td><td>Échauffement physique dynamique : course, pas chassés, montées de genoux</td></tr>
<tr><td>Sur le court</td><td>L'échauffement avec l'adversaire (souvent 5 minutes) : l'enquête du module 10</td></tr></table>
<p>Le <b>plan de match</b> tient en <b>trois consignes</b> au maximum, par exemple : « premières balles au T », « croisé profond sur son revers », « monter sur les balles courtes ». Au-delà, on ne retient rien sous pression.</p>
<h3>Pendant le match</h3>
<ul><li><b>Boire</b> à chaque changement de côté, avant d'avoir soif ; manger un en-cas (banane, barre) dans les longs matchs.</li>
<li><b>Le coaching</b> : depuis le <b>1er janvier 2025</b>, les règles de l'ITF autorisent le coaching depuis les tribunes, bref et discret, entre les points et pendant les pauses, jamais pendant un point. Chez les amateurs, le règlement de la compétition s'applique (par exemple, le capitaine en championnat par équipes).</li>
<li><b>Le fair-play</b> : sans arbitre, chacun annonce les balles de son côté, et une balle douteuse est bonne pour l'adversaire.</li></ul>
<h3>Après le match</h3>
<ul><li>Récupérer : boire, manger, retour au calme.</li>
<li>Remplir son <b>carnet de match</b> : adversaire, score, ce qui a marché, ce qui n'a pas marché, une priorité d'entraînement.</li></ul>
<div class="gmnemo"><b>« Deux raquettes, trois consignes, un carnet. »</b> C'est tout ce qu'il faut pour transformer un match en progrès.</div>
<div class="gtrap">Idée reçue : « un plan de match détaillé en dix points rassure ». Faux : sous pression, on n'en retient que deux ou trois. Autre erreur : croire que le coaching est toujours interdit. Il est autorisé chez les professionnels depuis 2025, dans des limites précises ; chez les amateurs, cela dépend du règlement de la compétition.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Préparer son sac et son timing</li><li>Écrire un plan en trois consignes</li><li>Connaître les règles du coaching et du fair-play</li><li>Tenir un carnet de match</li></ul>`},
/*EXOS*/
{i:"t244_01",u:244,t:"story",d:.2,nw:"Le jour du match",q:"Nathan a cassé une corde avec sa seule raquette. Que retient-il pour la prochaine fois ?",sc:[{who:"Nathan",txt:"Ma raquette m'a lâché."}],o:["« Toujours deux raquettes cordées dans le sac. »","« Il faut jouer plus doucement pour ne plus casser de corde. »","« Ne plus jamais corder ses raquettes, les cordes cassent. »","« Emprunter la raquette de l'adversaire en cas de problème. »"],a:0,w:"Deux raquettes, trois consignes, un carnet."},
{i:"t244_02",u:244,t:"order",d:.2,q:"Remets dans l'ordre la préparation d'un match.",it:["Sac prêt la veille","Repas 2 à 3 h avant","Arrivée 45 à 60 min avant","Échauffement physique","Échauffement avec l'adversaire"],w:"Une préparation qui supprime les imprévus évitables."},
{i:"t244_03",u:244,t:"fill",d:.25,q:"Un plan de match tient en ___ consignes au maximum.",o:["trois","dix","vingt","cinquante"],a:0,w:"Sous pression, on ne retient que deux ou trois consignes."},
{i:"t244_04",u:244,t:"tf",d:.25,q:"Depuis 2025, les règles de l'ITF autorisent le coaching depuis les tribunes, bref et discret.",a:true,w:"Entre les points et pendant les pauses, jamais pendant un point."},
{i:"t244_05",u:244,t:"story",d:.3,q:"Clara écrit un plan de match de dix consignes. Que lui conseilles-tu ?",sc:[{who:"Clara",txt:"Comme ça, je n'oublie rien."}],o:["« Garde les trois plus importantes : tu oublierais le reste. »","« Écris-en vingt, plus il y en a, mieux c'est pour ta confiance. »","« N'écris rien du tout, un plan de match empêche de bien jouer. »","« Relis tes dix consignes à chaque point pendant le match. »"],a:0,w:"Trois consignes : par exemple premières au T, croisé sur le revers, monter sur la courte."},
{i:"t244_06",u:244,t:"match",d:.3,q:"Associe chaque moment à l'action.",p:[["La veille","Préparer le sac"],["2 à 3 h avant","Repas riche en glucides"],["Changement de côté","Boire"],["Après le match","Remplir le carnet"]],w:"Avant, pendant, après : la liste plastifiée de Valérie."},
{i:"t244_07",u:244,t:"multi",d:.35,q:"Que doit contenir le sac de match ?",o:["Deux raquettes","Des surgrips","Une gourde","Un en-cas","Une seule raquette sans rechange"],a:[0,1,2,3],w:"Une seule raquette, c'est le match perdu à la première corde cassée."},
{i:"t244_08",u:244,t:"slider",d:.35,q:"Combien de minutes avant le match faut-il arriver au minimum ?",min:0,max:120,step:5,a:45,tol:5,pre:"",un:" min",w:"45 à 60 minutes : se signaler au juge-arbitre, s'échauffer, repérer le court."},
{i:"t244_09",u:244,t:"story",d:.4,q:"Pendant le match, Malik n'a pas soif et ne boit pas. Que lui dis-tu ?",sc:[{who:"Malik",txt:"Je boirai à la fin."}],o:["« Bois à chaque changement de côté, avant d'avoir soif. »","« Tu as raison, boire pendant le match alourdit l'estomac. »","« Bois uniquement si tu perds, pour te remotiver un peu. »","« Bois deux litres d'un coup au premier changement de côté. »"],a:0,w:"La soif arrive trop tard : on boit régulièrement à chaque changement de côté."},
{i:"t244_10",u:244,t:"tiles",d:.4,q:"Reconstitue le moyen mnémotechnique du jour de match.",a:["deux","raquettes","trois","consignes","un","carnet"],dd:["dix","zéro","une"],w:"Deux raquettes, trois consignes, un carnet."},
{i:"t244_11",u:244,t:"sort",d:.45,q:"Coaching autorisé ou interdit selon les règles de l'ITF depuis 2025 ?",bins:["Autorisé","Interdit"],it:[["Un signe bref entre deux points",0],["Des conseils pendant le changement de côté",0],["Crier une consigne pendant l'échange",1],["Un long discours pendant le point",1]],w:"Bref et discret, entre les points et pendant les pauses ; jamais pendant un point."},
{i:"t244_12",u:244,t:"fill",d:.45,q:"Sans arbitre, une balle douteuse est bonne pour l'___.",o:["adversaire","annonceur","arbitre","public"],a:0,w:"Chacun annonce son côté, et le doute profite à l'adversaire."},
{i:"t244_13",u:244,t:"story",d:.5,q:"Rappel du module 10 : Clara se demande ce qu'elle fait pendant les 5 minutes d'échauffement sur le court.",sc:[{who:"Clara",txt:"Je frappe tranquillement ?"}],o:["« Tu enquêtes : haut, bas, court, lob, volée. »","« Tu frappes le plus fort possible pour l'intimider. »","« Tu restes assise, l'échauffement fatigue pour rien. »","« Tu regardes ton téléphone pour rester détendue. »"],a:0,w:"Cinq questions avant le premier point : l'échauffement est une enquête."},
{i:"t244_14",u:244,t:"mcq",d:.5,q:"Quel repas prendre 2 à 3 heures avant un match ?",o:["Riche en glucides, facile à digérer","Très gras et copieux, pour tenir","Rien du tout, on joue à jeun","Uniquement du café très sucré"],a:0,w:"Des glucides pour l'énergie, et un repas léger pour ne pas gêner la digestion."},
{i:"t244_15",u:244,t:"num",d:.55,q:"Match à 9 h 30, arrivée 45 minutes avant : combien de minutes après 8 h Nathan doit-il être là au plus tard ?",a:45,tol:0,un:" min",h:"9 h 30 moins 45 min = 8 h 45",w:"8 h 45 au plus tard : c'est justement l'heure à laquelle il est arrivé, sans marge pour s'échauffer."},
{i:"t244_16",u:244,t:"tf",d:.55,q:"Un plan de match détaillé en dix points est plus efficace qu'un plan en trois consignes.",a:false,w:"Sous pression, on n'en retient que deux ou trois."},
{i:"t244_17",u:244,t:"story",d:.6,q:"Nathan a perdu et veut oublier le match au plus vite. Que lui propose Valérie ?",sc:[{who:"Nathan",txt:"Je ne veux plus y penser."}],o:["« Cinq lignes dans ton carnet : réussites, ratés, une priorité. »","« Oublie tout, les défaites n'apprennent jamais rien au tennis. »","« Rejoue mentalement chaque point perdu pendant toute la nuit. »","« Change de club, c'est la seule façon de repartir de zéro. »"],a:0,w:"Un carnet transforme un match, gagné ou perdu, en progrès."},
{i:"t244_18",u:244,t:"match",d:.6,q:"Associe chaque rubrique du carnet à un exemple.",p:[["Adversaire","Paul, 15, contreur"],["Ce qui a marché","Premières au T"],["Ce qui a raté","Retours trop longs"],["Priorité","Retour au centre"]],w:"Un carnet simple suffit : il se relit avant de rejouer le même adversaire."},
{i:"t244_19",u:244,t:"sort",d:.65,q:"Classe chaque affirmation : vraie ou idée reçue ?",bins:["Vraie","Idée reçue"],it:[["Le coaching est toujours interdit",1],["Dix consignes rassurent",1],["On boit avant d'avoir soif",0],["Deux raquettes au minimum",0]],w:"Deux idées reçues corrigées dans le guide."},
{i:"t244_20",u:244,t:"mcq",d:.65,q:"Depuis quand le coaching depuis les tribunes est-il inscrit dans les règles de l'ITF ?",o:["1er janvier 2025","1er janvier 1990","Il est toujours interdit","1er janvier 2030"],a:0,w:"Après des essais depuis 2017, et sur tous les circuits depuis 2023, la règle est devenue permanente en 2025."},
{i:"t244_21",u:244,t:"story",d:.7,q:"Rappel du module 12 : au changement de côté, Malik a 90 secondes. Comment les utiliser ?",sc:[{who:"Malik",txt:"Je m'assois et je rumine."}],o:["« Bois, relis tes trois consignes, choisis le plan à suivre. »","« Rumine tes erreurs pour ne plus les refaire au jeu suivant. »","« Regarde les autres matchs pour te changer les idées. »","« Reste debout sans boire pour garder ton rythme cardiaque. »"],a:0,w:"Boire, faire le bilan, décider : les 90 secondes sont un outil."},
{i:"t244_22",u:244,t:"fill",d:.7,q:"L'échauffement physique avant de monter sur le court dure environ ___ minutes.",o:["15","2","60","90"],a:0,w:"Environ 15 minutes d'échauffement dynamique : course, pas chassés, montées de genoux."},
{i:"t244_23",u:244,t:"multi",d:.75,q:"Qu'est-ce qu'une bonne consigne de plan de match ?",o:["Courte","Concrète","Liée à l'adversaire","Mesurable","Floue comme « jouer bien »"],a:[0,1,2,3],w:"« Jouer bien » n'est pas une consigne : « premières au T » en est une."},
{i:"t244_24",u:244,t:"story",d:.75,q:"L'adversaire de Clara annonce faute une balle qu'elle voit bonne, sans juge-arbitre. Comment réagir ?",sc:[{who:"Clara",txt:"Elle était dedans !"}],o:["« Demande-lui calmement ; si ça se répète, juge-arbitre. »","« Annonce toi aussi ses balles bonnes faute, pour compenser. »","« Quitte le court immédiatement en signe de protestation. »","« Crie sur elle pour que tout le club soit au courant. »"],a:0,w:"Chacun annonce son côté ; en cas de litige répété, le juge-arbitre intervient."},
{i:"t244_25",u:244,t:"tf",d:.8,q:"Dans les longs matchs, un en-cas comme une banane aide à tenir le rythme.",a:true,w:"Un apport de glucides facile à digérer pendant les pauses évite le coup de pompe."},
{i:"t244_26",u:244,t:"tiles",d:.8,q:"Reconstitue la règle de l'hydratation.",a:["boire","avant","d'avoir","soif"],dd:["après","jamais","faim"],w:"À chaque changement de côté. La soif arrive trop tard : on boit un peu à chaque changement de côté."},
{i:"t244_27",u:244,t:"story",d:.85,q:"Rappel du module 11 : Nathan joue à 14 h en plein soleil, par 33 °C. Qu'ajoute-t-il à sa préparation ?",sc:[{who:"Nathan",txt:"Il fait une chaleur !"}],o:["« Plus d'eau, une casquette, et du lift : la balle sera vive. »","« Rien, la chaleur ne change rien à la préparation d'un match. »","« Moins d'eau, pour ne pas être gêné pendant les courses. »","« Un repas gras juste avant, pour avoir des réserves. »"],a:0,w:"La chaleur rend la balle vive et déshydrate : on adapte le sac et le plan."},
{i:"t244_28",u:244,t:"num",d:.85,q:"Nathan boit 200 ml à chacun des 10 changements de côté. Combien de litres au total ?",a:2,tol:0,un:" L",h:"200 × 10 = 2000 ml",w:"2 litres : boire régulièrement évite la baisse de lucidité en fin de match."},
{i:"t244_29",u:244,t:"mcq",d:.9,q:"Que fait-on en arrivant sur le lieu d'un tournoi ?",o:["Se signaler au juge-arbitre","Choisir son adversaire","Réserver le meilleur court","Changer l'heure du match"],a:0,w:"Le juge-arbitre gère le tournoi : on se signale pour confirmer sa présence."},
{i:"t244_30",u:244,t:"story",d:.9,q:"Clara est capitaine de l'équipe le dimanche. Elle veut conseiller Malik pendant son match. Que doit-elle vérifier ?",sc:[{who:"Clara",txt:"J'ai le droit de lui parler ?"}],o:["« Le règlement de la compétition : il fixe quand conseiller. »","« Rien, on peut parler au joueur pendant les points sans aucune limite. »","« Il est interdit de parler à un joueur pendant tout le championnat. »","« Il suffit de demander l'accord de l'adversaire à chaque conseil. »"],a:0,w:"Chez les amateurs, le règlement de la compétition s'applique."},
{i:"t244_31",u:244,t:"sort",d:.95,q:"Avant, pendant ou après ?",bins:["Avant","Pendant","Après"],it:[["Préparer deux raquettes",0],["Boire au changement de côté",1],["Remplir le carnet",2],["Repas riche en glucides",0],["Relire ses trois consignes",1]],w:"La liste plastifiée : avant, pendant, après."},
{i:"t244_32",u:244,t:"story",d:.95,q:"Synthèse : Valérie demande à Nathan ce qui a changé entre ses deux matchs à Montauban.",sc:[{who:"Valérie",txt:"Même adversaire, autre résultat."}],o:["« Deux raquettes, un vrai échauffement, trois consignes. »","« J'ai frappé plus fort, la préparation ne change rien au résultat. »","« J'ai eu de la chance, l'adversaire était fatigué ce jour-là. »","« J'ai changé de raquette et de cordage, c'est ce qui a tout fait. »"],a:0,w:"Deux raquettes, trois consignes, un carnet : la préparation supprime les défaites évitables."}
