/*UNIT*/
{id:245,c:"TENNIS",n:"Module 15",t:"Lire un match comme un coach : les grands cas tactiques",col:"--gold",ic:"🎬",guide:`
<h3>Le ciné-club du mercredi</h3>
<div class="gstory">Chaque mercredi soir, Valérie projette un match célèbre au club-house des Minimes. Nathan, Clara et Malik ont chacun un carnet et une consigne : ne pas regarder la balle, mais les joueurs. « Où se place le relanceur ? Sur quel côté part la balle haute ? Qu'est-ce qui change après le premier set ? » Ce soir, c'est Roland-Garros 1989 : un adolescent de 17 ans, épuisé par les crampes, sert à la cuillère face au numéro un mondial. Malik n'en revient pas : « Il a le droit ? » Valérie sourit : « Il a le droit. Et il a gagné le tournoi. »</div>
<h3>Méthode : les 3 S</h3>
<table><tr><th>Question</th><th>Ce qu'on observe</th></tr>
<tr><td><b>Service</b> (et retour)</td><td>% de premières, cibles, position du relanceur</td></tr>
<tr><td><b>Schémas</b></td><td>Direction des échanges, côté attaqué, montées, effets</td></tr>
<tr><td><b>Score</b></td><td>Choix sur les points importants, changements après un set perdu</td></tr></table>
<h3>Cinq cas célèbres</h3>
<ul><li><b>Michael Chang contre Ivan Lendl, Roland-Garros 1989</b> : en huitième de finale, souffrant de crampes, Chang sert à la cuillère et se place tout près de la ligne de service au retour sur une balle de match. Lendl commet une double faute. Chang, 17 ans, remporte le tournoi et devient le plus jeune vainqueur masculin d'un tournoi du Grand Chelem. Leçon : <b>perturber les habitudes</b> de l'adversaire est parfaitement légal.</li>
<li><b>Rafael Nadal contre Roger Federer</b> : coup droit gaucher très lifté sur le revers à une main de Federer (module 6). Leçon : <b>attaquer le point faible avec son point fort</b>.</li>
<li><b>Federer contre Nadal, finale de l'Open d'Australie 2017</b> : de retour de blessure, Federer prend son revers plus tôt, plus à plat, au lieu de subir en slice. Il gagne en cinq sets. Leçon : <b>changer un schéma qui perdait</b>.</li>
<li><b>Ashleigh Barty</b> : son revers slicé, bas et varié, a dérangé les frappeuses ; elle a gagné Roland-Garros 2019, Wimbledon 2021 et l'Open d'Australie 2022. Leçon : <b>la variété bat la puissance</b>.</li>
<li><b>Daniil Medvedev</b> : il retourne souvent plusieurs mètres derrière sa ligne de fond, pour avoir le temps de remettre les premières balles rapides. Leçon : <b>la position au retour est un choix tactique</b>.</li></ul>
<div class="gmnemo"><b>« Les 3 S : Service, Schémas, Score. »</b> Et pour les cas : <b>« Chang surprend, Nadal cible, Federer change, Barty varie, Medvedev recule. »</b></div>
<div class="gtrap">Idée reçue : « le service à la cuillère est interdit ou antisportif ». Faux : il est autorisé par les règles. Il est parfois mal vu, mais c'est une arme tactique contre un relanceur placé très loin. Autre piège : regarder un match en suivant la balle. On ne voit alors ni les placements, ni les schémas.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Analyser un match avec les 3 S</li><li>Raconter et expliquer les cas célèbres</li><li>En tirer une leçon pour son propre jeu</li></ul>`},
/*EXOS*/
{i:"t245_01",u:245,t:"story",d:.2,nw:"Lire un match",q:"Malik demande si le service à la cuillère de Chang était permis. Que répond Valérie ?",sc:[{who:"Malik",txt:"Il a le droit ?"}],o:["« Oui, les règles l'autorisent : c'est une surprise. »","« Non, il a été disqualifié juste après ce service. »","« Oui, mais seulement pour les joueurs de moins de 18 ans. »","« Non, mais l'arbitre ne l'avait pas vu ce jour-là. »"],a:0,w:"Le service à la cuillère est légal ; Chang a perturbé les habitudes de Lendl."},
{i:"t245_02",u:245,t:"match",d:.2,q:"Associe chaque joueur à sa leçon.",p:[["Michael Chang","Surprendre"],["Rafael Nadal","Cibler le point faible"],["Roger Federer 2017","Changer de schéma"],["Ashleigh Barty","Varier"]],w:"Chang surprend, Nadal cible, Federer change, Barty varie, Medvedev recule."},
{i:"t245_03",u:245,t:"fill",d:.25,q:"Les 3 S : Service, Schémas, ___.",o:["Score","Smash","Sueur","Soleil"],a:0,w:"Le score révèle les choix sur les points importants."},
{i:"t245_04",u:245,t:"tf",d:.25,q:"Michael Chang avait 17 ans quand il a gagné Roland-Garros en 1989.",a:true,w:"Il est devenu le plus jeune vainqueur masculin d'un tournoi du Grand Chelem."},
{i:"t245_05",u:245,t:"story",d:.3,q:"Clara regarde un match en suivant la balle. Elle ne voit « rien de tactique ». Que lui conseille Valérie ?",sc:[{who:"Clara",txt:"Je vois juste des échanges."}],o:["« Regarde les joueurs : placements, cibles, changements. »","« Regarde encore plus la balle, en ralentissant la vidéo. »","« Regarde seulement le tableau d'affichage du score. »","« Écoute les commentaires, ils suffisent à tout comprendre. »"],a:0,w:"On ne voit les schémas qu'en regardant les joueurs, pas la balle."},
{i:"t245_06",u:245,t:"sort",d:.3,q:"Quel S observe-t-on ?",bins:["Service","Schémas","Score"],it:[["Position du relanceur",0],["Côté attaqué en échange",1],["Choix sur balle de break",2],["% de premières balles",0],["Montées au filet",1],["Changement après un set perdu",2]],w:"Service, Schémas, Score : trois colonnes dans le carnet."},
{i:"t245_07",u:245,t:"mcq",d:.35,q:"Qui a gagné la finale de l'Open d'Australie 2017 ?",o:["Roger Federer","Rafael Nadal","Novak Djokovic","Andy Murray"],a:0,w:"Federer bat Nadal en cinq sets, en prenant son revers plus tôt au lieu de subir."},
{i:"t245_08",u:245,t:"story",d:.35,q:"Nathan veut s'inspirer de Federer en 2017. Qu'a changé Federer dans ce match ?",sc:[{who:"Nathan",txt:"Il a fait quoi de spécial ?"}],o:["« Il a pris son revers plus tôt, plus à plat, sans subir. »","« Il a servi à la cuillère pendant tout le cinquième set. »","« Il a joué uniquement en coup droit, sans aucun revers. »","« Il est resté cinq mètres derrière sa ligne à chaque point. »"],a:0,w:"Federer change : un schéma qui perdait (revers slicé subi) remplacé par un revers attaquant."},
{i:"t245_09",u:245,t:"tiles",d:.4,q:"Reconstitue la méthode d'analyse.",a:["Service","Schémas","Score"],dd:["Style","Soleil","Sac"],w:"Les 3 S. Service, Schémas, Score : on regarde les joueurs, pas la balle."},
{i:"t245_10",u:245,t:"multi",d:.4,q:"Quels tournois du Grand Chelem Ashleigh Barty a-t-elle gagnés ?",o:["Roland-Garros 2019","Wimbledon 2021","Open d'Australie 2022","US Open 2020"],a:[0,1,2],w:"Trois titres avec un jeu varié, dont un revers slicé redoutable."},
{i:"t245_11",u:245,t:"story",d:.45,q:"Rappel du module 5 : Malik voit Medvedev retourner cinq mètres derrière sa ligne. Doit-il l'imiter ?",sc:[{who:"Malik",txt:"Je recule comme lui ?"}],o:["« Contre les premières rapides, et avance sur les deuxièmes. »","« Oui, toujours cinq mètres derrière, sur tous les services. »","« Non, reculer au retour est interdit dans les tournois amateurs. »","« Oui, et tu restes à cet endroit pendant tout l'échange. »"],a:0,w:"Recule sur la première, avance sur la deuxième : la position au retour est un choix."},
{i:"t245_12",u:245,t:"fill",d:.45,q:"Chang surprend, Nadal cible, Federer change, Barty varie, Medvedev ___.",o:["recule","attaque","sert","smashe"],a:0,w:"Medvedev recule au retour pour gagner du temps sur les premières balles."},
{i:"t245_13",u:245,t:"order",d:.5,q:"Remets dans l'ordre l'analyse d'un match vidéo.",it:["Noter le service et le retour","Repérer les schémas","Observer les points importants","Noter les changements de plan","Tirer une leçon pour soi"],w:"Service, Schémas, Score, puis la leçon. Chaque analyse se termine par une leçon concrète pour son propre jeu."},
{i:"t245_14",u:245,t:"tf",d:.5,q:"Le service à la cuillère est interdit par les règles du tennis.",a:false,w:"Il est autorisé. Il est parfois mal vu, mais c'est une arme contre un relanceur placé très loin."},
{i:"t245_15",u:245,t:"story",d:.55,q:"Rappel du module 6 : Clara demande pourquoi le coup droit de Nadal faisait autant mal au revers de Federer.",sc:[{who:"Clara",txt:"Federer avait un beau revers pourtant."}],o:["« Un revers à une main frappe mal une balle liftée à hauteur d'épaule. »","« Parce que Nadal jouait toujours à plat et très bas sur le revers. »","« Parce que Federer n'avait pas le droit de jouer en slice contre Nadal. »","« Parce que la balle de Nadal était plus lourde que les autres balles. »"],a:0,w:"Lift pour la marge, et balle haute sur un revers à une main : Nadal cible."},
{i:"t245_16",u:245,t:"num",d:.55,q:"Chang est né en février 1972 et gagne Roland-Garros en juin 1989. Quel âge a-t-il ?",a:17,tol:0,un:" ans",h:"1989 moins 1972",w:"17 ans : le plus jeune vainqueur masculin d'un tournoi du Grand Chelem."},
{i:"t245_17",u:245,t:"match",d:.6,q:"Associe chaque cas à la situation de jeu.",p:[["Chang 1989","Service et retour"],["Nadal contre Federer","Échange de fond"],["Medvedev","Position au retour"],["Barty","Effets et variété"]],w:"Chaque cas illustre une situation de jeu (module 3)."},
{i:"t245_18",u:245,t:"story",d:.6,q:"Nathan affronte un joueur qui recule très loin au retour. Que peut-il tenter, comme Chang ?",sc:[{who:"Nathan",txt:"Il est presque contre le grillage."}],o:["« Un service court et surprenant, voire à la cuillère, parfois. »","« Des services encore plus longs, pour qu'il recule plus loin encore. »","« Rien, un relanceur loin derrière est impossible à surprendre. »","« Servir toujours au même endroit pour qu'il s'habitue à ta balle. »"],a:0,w:"Chang surprend : perturber les habitudes du relanceur est légal et efficace."},
{i:"t245_19",u:245,t:"sort",d:.65,q:"Classe chaque affirmation : vraie ou idée reçue ?",bins:["Vraie","Idée reçue"],it:[["Le service à la cuillère est interdit",1],["On analyse un match en suivant la balle",1],["Barty a gagné Wimbledon en 2021",0],["Federer a battu Nadal en finale en 2017",0]],w:"Deux idées reçues corrigées dans le guide."},
{i:"t245_20",u:245,t:"mcq",d:.65,q:"Contre qui Chang a-t-il servi à la cuillère en 1989 ?",o:["Ivan Lendl","John McEnroe","Boris Becker","Stefan Edberg"],a:0,w:"Ivan Lendl, numéro un mondial, en huitième de finale de Roland-Garros."},
{i:"t245_21",u:245,t:"story",d:.7,q:"Rappel du module 10 : Clara analyse la vidéo de sa défaite. Elle voit qu'elle a gardé le même plan en perdant 1-6. Quelle leçon ?",sc:[{who:"Clara",txt:"J'aurais dû faire comme Federer."}],o:["« Qui perd change : un plan B et un moment pour l'appliquer. »","« Il faut garder le même plan jusqu'au bout, quoi qu'il arrive. »","« La vidéo ne sert à rien, un match perdu est un match perdu. »","« Il fallait changer de plan à chaque point pour la surprendre. »"],a:0,w:"Federer change : un plan qui perd doit être remplacé, à un moment décidé."},
{i:"t245_22",u:245,t:"multi",d:.7,q:"Que faut-il noter dans la colonne « Service » ?",o:["% de premières","Cibles","Position du relanceur","Points gagnés sur deuxième","Couleur de la tenue"],a:[0,1,2,3],w:"La tenue ne dit rien de la tactique. On y ajoute les points gagnés au retour, pour mesurer la pression mise sur le serveur."},
{i:"t245_23",u:245,t:"fill",d:.75,q:"Barty a dérangé les frappeuses avec son revers ___.",o:["slicé","à deux mains lifté","à plat","sauté"],a:0,w:"Slice pour le piège : bas, varié, il prive les frappeuses de leur zone de frappe."},
{i:"t245_24",u:245,t:"story",d:.75,q:"Malik regarde un match : un joueur perd le premier set 2-6 puis monte au filet à chaque occasion et gagne. Comment l'écrire dans son carnet ?",sc:[{who:"Malik",txt:"Je note quoi ?"}],o:["« Score : set perdu, plan B ; schémas : montées gagnantes. »","« Rien, c'est de la chance, ça ne s'analyse pas. »","« Uniquement le score final, le reste est inutile. »","« Le nom de sa raquette, c'est elle qui a fait la différence. »"],a:0,w:"Les 3 S : on relie le changement de schéma au moment du score."},
{i:"t245_25",u:245,t:"tf",d:.8,q:"Medvedev retourne souvent très loin derrière sa ligne de fond.",a:true,w:"Pour avoir le temps de remettre les premières balles rapides : la position au retour est un choix tactique."},
{i:"t245_26",u:245,t:"tiles",d:.8,q:"Reconstitue la leçon du cas Nadal.",a:["attaquer","le","point","faible","avec","son","point","fort"],dd:["éviter","jamais","service"],w:"Nadal cible : son coup droit lifté sur le revers de Federer."},
{i:"t245_27",u:245,t:"mcq",d:.85,q:"Quelle leçon tirer du cas Barty ?",o:["La variété peut battre la puissance","Seule la puissance gagne au final","Le slice est interdit chez les pros","Il faut toujours jouer à plat"],a:0,w:"Barty varie : effets, hauteurs et rythmes différents dérangent les frappeuses."},
{i:"t245_28",u:245,t:"story",d:.85,q:"Rappel du module 8 : Nathan veut analyser son dernier match. Par quoi commencer ?",sc:[{who:"Nathan",txt:"J'ai la vidéo entière."}],o:["« Compte les points de 0 à 4 frappes et qui les gagne. »","« Regarde uniquement tes plus beaux coups gagnants. »","« Compte le nombre de balles utilisées pendant le match. »","« Regarde seulement le dernier jeu, il résume tout le reste. »"],a:0,w:"70 dans les 4 : le service et le retour d'abord, c'est là que le match se joue."},
{i:"t245_29",u:245,t:"num",d:.9,q:"Federer bat Nadal 6-4, 3-6, 6-1, 3-6, 6-3. Combien de sets Federer a-t-il gagnés ?",a:3,tol:0,un:" sets",h:"Compte les sets où Federer a 6",w:"3 sets à 2 : un match en cinq sets où Federer a gagné en changeant son schéma de revers."},
{i:"t245_30",u:245,t:"match",d:.9,q:"Associe chaque leçon à son application pour toi.",p:[["Surprendre","Un service différent sur un gros point"],["Cibler","Mon point fort sur son point faible"],["Changer","Un plan B décidé à l'avance"],["Varier","Alterner lift et slice"]],w:"Chaque cas célèbre devient une règle pour son propre jeu."},
{i:"t245_31",u:245,t:"story",d:.95,q:"Clara prépare le ciné-club de la semaine prochaine. Quelle consigne donne-t-elle aux jeunes ?",sc:[{who:"Clara",txt:"C'est moi qui anime !"}],o:["« Regardez les joueurs, pas la balle, et remplissez les 3 S. »","« Regardez uniquement la balle, le reste n'est pas important. »","« Comptez les spectateurs, c'est ce qui fait la pression. »","« Notez la marque des chaussures de chaque joueur du match. »"],a:0,w:"Service, Schémas, Score : le carnet d'analyse du coach."},
{i:"t245_32",u:245,t:"story",d:.95,q:"Synthèse : Valérie demande à Malik la leçon des cinq cas.",sc:[{who:"Valérie",txt:"En une phrase ?"}],o:["« Surprendre, cibler, changer, varier, placer son retour. »","« Frapper plus fort que l'adversaire sur chaque balle, sans exception. »","« Toujours servir à la cuillère, c'est l'arme des grands champions. »","« Suivre la balle des yeux, c'est la seule vraie analyse d'un match. »"],a:0,w:"Chang surprend, Nadal cible, Federer change, Barty varie, Medvedev recule."}
