/*UNIT*/
{id:266,c:"FOOT",n:"Module 2",t:"Hors-jeu, fautes et VAR : juger une action comme l'arbitre",col:"--green",ic:"🚩",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Dire si un joueur est en <b>position de hors-jeu</b>.</li>
<li>Distinguer <b>position</b> de hors-jeu et <b>faute</b> de hors-jeu.</li>
<li>Choisir entre <b>coup franc direct</b>, <b>indirect</b> et <b>penalty</b>.</li>
<li>Juger une <b>main</b> selon la règle actuelle.</li>
<li>Savoir quand la <b>VAR</b> peut intervenir.</li></ul>
<h3>Le but refusé</h3>
<div class="gstory">23e minute, Racing-FC Scarpe, 0-0. Rayan glisse le ballon dans la course de l'attaquant, qui marque. Le drapeau de l'assistant se lève. Mehdi explose : « Il était derrière le défenseur au moment de la frappe, pas au moment de la passe ! » Élodie pose la vidéo sur pause, image de la passe de Rayan : l'épaule de l'attaquant dépasse l'avant-dernier défenseur. « Tout se juge à l'instant de la passe, Mehdi. »</div>
<h3>La position de hors-jeu</h3>
<p>Un joueur est en <b>position de hors-jeu</b> si, au moment où un coéquipier <b>joue ou touche</b> le ballon :</p>
<ul><li>une partie de sa <b>tête, de son corps ou de ses pieds</b> est dans la <b>moitié adverse</b>,</li>
<li>et plus près de la ligne de but adverse que le <b>ballon</b> et que l'<b>avant-dernier adversaire</b> (souvent le dernier défenseur, le gardien étant le dernier).</li></ul>
<p>Les <b>bras et les mains</b> ne comptent pas. Être <b>à la même hauteur</b> que l'avant-dernier adversaire, c'est être <b>en jeu</b>.</p>
<svg class='gsvg' viewBox='0 0 220 158' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='10' y='6' width='200' height='130' rx='3' fill='#1E6B3A'/><line x1='160' y1='6' x2='160' y2='136' stroke='#FFFFFF' stroke-width='2' stroke-dasharray='4 3'/><text x='160' y='20' font-size='8' fill='#FFFFFF' text-anchor='middle' font-weight='800'>ligne</text><rect x='10' y='6' width='200' height='130' rx='3' fill='none' stroke='#FFFFFF' stroke-width='1.4'/><line x1='110' y1='6' x2='110' y2='136' stroke='#FFFFFF' stroke-width='1.2'/><circle cx='110' cy='71' r='15' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><rect x='10' y='37' width='28' height='68' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><rect x='182' y='37' width='28' height='68' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><circle cx='120' cy='70' r='6.5' fill='#FFD23F' stroke='#1C1C48' stroke-width='1'/><text x='120' y='72.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#1C1C48'>10</text><circle cx='160' cy='50' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='160' y='52.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>4</text><circle cx='203' cy='71' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='203' y='73.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>G</text><circle cx='168' cy='78' r='6.5' fill='#FFD23F' stroke='#1C1C48' stroke-width='1'/><text x='168' y='80.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#1C1C48'>9</text><text x='110' y='151' font-size='9' fill='var(--txt)' text-anchor='middle' font-weight='700'>La ligne de hors-jeu se lit à l'instant de la passe</text></svg>
<div class="gmnemo">Le hors-jeu, c'est une <b>photo, pas un film</b>. On fige l'image à l'instant exact de la passe. Ce qui se passe après ne compte plus pour la position.</div>
<h3>Position ou faute ?</h3>
<p>Être en position de hors-jeu n'est <b>pas une faute</b>. Il y a faute seulement si le joueur participe au jeu :</p>
<ul><li>il <b>joue ou touche</b> le ballon,</li>
<li>il <b>gêne un adversaire</b> (bloque sa vue, le dispute),</li>
<li>il <b>tire un avantage</b> de sa position (ballon qui revient du poteau ou d'un arrêt du gardien).</li></ul>
<p>Pas de hors-jeu dans sa propre moitié, ni sur une touche, un corner ou un coup de pied de but. Sanction : <b>coup franc indirect</b>.</p>
<h3>Direct, indirect, penalty</h3>
<table><tr><th>Faute</th><th>Sanction</th></tr>
<tr><td>Pousser, tenir, faire trébucher, charger ou tacler de façon imprudente, main volontaire</td><td><b>Coup franc direct</b> : on peut marquer directement</td></tr>
<tr><td>La même faute dans <b>sa propre surface</b></td><td><b>Penalty</b></td></tr>
<tr><td>Jeu dangereux sans contact, obstruction, hors-jeu, gardien qui prend à la main une passe volontaire du pied d'un coéquipier</td><td><b>Coup franc indirect</b> : il faut une deuxième touche</td></tr></table>
<p>L'arbitre peut laisser jouer l'<b>avantage</b> si l'équipe victime de la faute en profite.</p>
<div class="gmnemo"><b>« Direct : tu peux marquer. Indirect : il faut passer. »</b> L'arbitre signale l'indirect en levant le bras tant que le ballon n'a pas touché un second joueur.</div>
<h3>La main</h3>
<ul><li>Faute si la main ou le bras va <b>volontairement</b> vers le ballon.</li>
<li>Faute si le bras rend le corps <b>anormalement plus grand</b>.</li>
<li>Un attaquant qui marque <b>immédiatement</b> après une main, même involontaire, voit son but <b>refusé</b>.</li>
<li>Le bras s'arrête à l'<b>aisselle</b> : l'épaule n'est pas la main.</li></ul>
<h3>La VAR</h3>
<p>L'assistance vidéo intervient seulement pour une <b>erreur claire et évidente</b> ou un incident grave manqué, dans <b>quatre situations</b> :</p>
<ul><li>un <b>but</b> (et ce qui le précède),</li>
<li>un <b>penalty</b>,</li>
<li>un <b>carton rouge direct</b>,</li>
<li>une <b>erreur d'identité</b> (le mauvais joueur sanctionné).</li></ul>
<p>Pour une question d'appréciation, l'arbitre va voir l'écran au bord du terrain. Pour un fait (hors-jeu, ballon sorti), la décision est corrigée directement. Dans les grandes compétitions, le <b>hors-jeu semi-automatique</b> modélise en 3D la position des joueurs.</p>
<div class="gmnemo">La VAR ne sort que pour <b>« But, Penalty, Rouge, Mauvais joueur »</b>. Retiens <b>B.P.R.M.</b>, comme « Bien Pour Refaire le Match ». Un carton jaune ou un corner oublié ne la concernent pas.</div>
<h3>Ce que tu dois retenir</h3>
<ul><li>Hors-jeu : photo à l'instant de la passe, bras exclus, égalité = en jeu.</li>
<li>Position n'est pas faute : il faut participer au jeu.</li>
<li>Direct, indirect, penalty dans sa surface.</li>
<li>VAR : B.P.R.M., seulement pour une erreur claire et évidente.</li></ul>`},
/*EXOS*/
{i:"k266_01",u:266,t:"story",d:.3,nw:"La position de hors-jeu",q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"Au moment de la frappe, il était derrière le défenseur ! Il n'était pas hors-jeu !"}],o:["On juge l'instant de la passe, pas la frappe","On juge l'instant de la frappe, donc le but est bien valable","On juge le moment où le ballon franchit la ligne de but adverse","On juge la position moyenne de l'attaquant sur toute l'action"],a:0,w:"Le hors-jeu est une photo, pas un film : on fige l'image quand le coéquipier joue le ballon."},
{i:"k266_02",u:266,t:"tiles",d:.3,q:"Reconstitue la formule mémo du hors-jeu.",a:["Une","photo,","pas","un","film"],dd:["vidéo,","ralenti,","match"],w:"La position s'apprécie à l'instant exact de la passe."},
{i:"k266_03",u:266,t:"tf",d:.3,q:"Un attaquant exactement à la même hauteur que l'avant-dernier défenseur est hors-jeu.",a:false,w:"À égalité, il est en jeu. Il faut être plus près de la ligne de but que le ballon et que l'avant-dernier adversaire."},
{i:"k266_04",u:266,t:"multi",d:.35,q:"Quelles parties du corps comptent pour juger la position de hors-jeu ?",o:["La tête","Les pieds","Le torse","Les mains","Les bras jusqu'à l'aisselle"],a:[0,1,2],w:"Tête, corps et pieds comptent. Les bras et les mains ne comptent pas."},
{i:"k266_05",u:266,t:"sort",d:.35,q:"Au moment de la passe, ce joueur est-il en position de hors-jeu ?",bins:["Position de hors-jeu","En jeu"],it:[["Épaule devant l'avant-dernier défenseur, dans le camp adverse",0],["Seulement la main devant le défenseur",1],["Dans sa propre moitié de terrain",1],["À hauteur exacte du défenseur",1],["Pied gauche devant le défenseur, près de la surface",0],["Derrière le ballon au moment de la passe",1]],w:"Tête, corps, pieds dans la moitié adverse, devant le ballon et l'avant-dernier adversaire. Égalité et propre moitié : en jeu."},
{i:"k266_06",u:266,t:"fill",d:.35,q:"Pour le hors-jeu, on compare la position de l'attaquant à celle de l'___ adversaire.",o:["avant-dernier","dernier","premier","plus proche du ballon"],a:0,w:"L'avant-dernier adversaire, car le dernier est le plus souvent le gardien."},
{i:"k266_07",u:266,t:"story",d:.4,nw:"Position ou faute de hors-jeu",q:"Que doit décider l'arbitre ?",ctx:"Un attaquant du Scarpe est en position de hors-jeu, loin de l'action, les mains sur les hanches. Son coéquipier marque depuis l'autre côté, sans que le hors-jeu gêne Tom.",sc:[{who:"Mehdi",txt:"Il y avait un joueur hors-jeu, le but doit être annulé !"}],o:["But valable : la position seule n'est pas une faute","But annulé : toute position de hors-jeu suffit à l'annuler","But annulé si le joueur hors-jeu se trouve dans la surface","But valable seulement si la VAR le confirme après examen"],a:0,w:"Il faut participer au jeu : jouer le ballon, gêner un adversaire ou tirer un avantage."},
{i:"k266_08",u:266,t:"multi",d:.4,q:"Dans quels cas un joueur en position de hors-jeu commet-il une faute ?",o:["Il touche le ballon","Il bloque la vue du gardien","Il reprend un ballon qui revient du poteau","Il reste immobile loin de l'action","Il se trouve dans sa propre moitié"],a:[0,1,2],w:"Jouer, gêner un adversaire, tirer avantage. Immobile et hors du jeu : pas de faute."},
{i:"k266_09",u:266,t:"mcq",d:.4,q:"Quelle est la sanction d'un hors-jeu ?",o:["Un coup franc indirect","Un coup franc direct à l'endroit de la faute","Un carton jaune pour l'attaquant","Une rentrée de touche pour l'adversaire"],a:0,w:"Coup franc indirect à l'endroit de la faute."},
{i:"k266_10",u:266,t:"tf",d:.4,q:"Un ballon qui revient du poteau vers un attaquant qui était en position de hors-jeu au moment du tir : il y a faute s'il le reprend.",a:true,w:"Il tire un avantage de sa position. Le rebond sur le poteau ou sur un arrêt du gardien ne remet pas à zéro."},
{i:"k266_11",u:266,t:"sort",d:.4,nw:"Direct, indirect, penalty",q:"Quelle sanction ?",bins:["Coup franc direct","Coup franc indirect","Penalty"],it:[["Lucas pousse un attaquant au milieu de terrain",0],["Un défenseur du Scarpe fait trébucher Rayan dans sa surface",2],["Tom prend à la main une passe volontaire du pied de Lucas",1],["Jeu dangereux, pied haut, sans contact",1],["Tirage de maillot à 30 m du but adverse",0],["Main volontaire d'un défenseur du Scarpe dans sa surface",2]],w:"Faute de contact : direct. La même dans sa propre surface : penalty. Jeu dangereux sans contact, passe en retrait prise à la main : indirect."},
{i:"k266_12",u:266,t:"tiles",d:.4,q:"Reconstitue la formule mémo des coups francs.",a:["Direct",":","tu","peux","marquer.","Indirect",":","il","faut","passer."],dd:["tirer.","attendre."],w:"Sur un indirect, il faut une deuxième touche avant de marquer. L'arbitre lève le bras."},
{i:"k266_13",u:266,t:"story",d:.45,q:"Que réponds-tu à Mehdi ?",ctx:"Coup franc indirect pour le Racing à 20 m. Rayan tire directement dans la lucarne, sans que personne ne touche le ballon.",sc:[{who:"Mehdi",txt:"Golazo ! Pourquoi l'arbitre ne l'accorde pas ?"}],o:["Indirect : il fallait une seconde touche","Parce que le mur n'était pas placé à 9,15 m du ballon","Parce que la VAR doit valider chaque but sur coup franc","Parce qu'un but sur coup franc est refusé en National 3"],a:0,w:"Indirect : il faut passer. Tir direct dans le but adverse sans autre touche : coup de pied de but."},
{i:"k266_14",u:266,t:"mcq",d:.45,q:"L'arbitre laisse jouer malgré une faute sur Rayan, car le Racing garde une belle occasion. Comment s'appelle cette règle ?",o:["L'avantage","La compensation","La tolérance","Le fair-play"],a:0,w:"L'avantage évite de punir l'équipe victime de la faute. L'arbitre peut sanctionner le fautif à l'arrêt suivant."},
{i:"k266_15",u:266,t:"slider",d:.45,q:"Combien de touches minimum faut-il sur un coup franc indirect avant qu'un but compte ?",min:1,max:4,step:1,a:2,tol:0,pre:"",un:" touches",w:"Le tireur, puis un second joueur (coéquipier ou adversaire)."},
{i:"k266_16",u:266,t:"fill",d:.45,q:"L'arbitre signale un coup franc indirect en levant le ___.",o:["bras","drapeau","carton","sifflet"],a:0,w:"Bras levé jusqu'à ce que le ballon touche un second joueur ou sorte."},
{i:"k266_17",u:266,t:"sort",d:.5,nw:"La main",q:"Main à sanctionner ou pas ?",bins:["Faute de main","Pas de faute"],it:[["Défenseur qui écarte les bras pour grandir son corps",0],["Ballon qui frappe l'épaule",1],["Bras qui va volontairement vers le ballon",0],["Attaquant qui marque juste après une main involontaire",0],["Ballon qui touche le bras collé au corps d'un défenseur",1]],w:"Volontaire ou corps anormalement agrandi : faute. L'épaule n'est pas le bras. Un but marqué juste après une main de l'attaquant est refusé."},
{i:"k266_18",u:266,t:"tf",d:.45,q:"Un but marqué immédiatement après une main involontaire du buteur est refusé.",a:true,w:"C'est la règle actuelle : l'attaquant ne peut pas marquer juste après une main, même accidentelle."},
{i:"k266_19",u:266,t:"story",d:.5,q:"Que réponds-tu à Élodie ?",sc:[{who:"Élodie Marchal",txt:"Leur défenseur dévie un centre avec le haut du bras, près de l'aisselle, bras collé au corps. Penalty ?"}],o:["Non : bras collé au corps, sous l'aisselle","Oui : tout contact au-dessus du coude est une faute de main","Oui : dans la surface, tout contact avec le bras donne penalty","Non : une main n'est jamais sifflée sur un centre adverse"],a:0,w:"La limite du bras est l'aisselle. Bras le long du corps, pas d'agrandissement : pas de faute."},
{i:"k266_20",u:266,t:"match",d:.5,q:"Associe chaque situation à la décision.",p:[["Défenseur bras écartés, ballon dessus","Faute de main"],["Ballon sur l'épaule","Pas de faute"],["Attaquant marque juste après une main involontaire","But refusé"],["Main volontaire du défenseur dans sa surface","Penalty"]],w:"Volonté, agrandissement, attaquant juste avant le but : les trois cas de faute de main à connaître."},
{i:"k266_21",u:266,t:"multi",d:.5,nw:"La VAR",q:"Dans quelles situations la VAR peut-elle intervenir ?",o:["Un but","Un penalty","Un carton rouge direct","Une erreur d'identité","Un deuxième carton jaune","Un corner oublié"],a:[0,1,2,3],w:"B.P.R.M. : But, Penalty, Rouge direct, Mauvais joueur. Ni les jaunes ni les corners."},
{i:"k266_22",u:266,t:"tiles",d:.45,q:"Reconstitue les quatre cas mémo de la VAR.",a:["But,","Penalty,","Rouge,","Mauvais","joueur"],dd:["Corner,","Jaune,","Touche,"],w:"B.P.R.M., comme « Bien Pour Refaire le Match »."},
{i:"k266_23",u:266,t:"story",d:.5,q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"L'arbitre a oublié un corner pour nous, la VAR va corriger ?"}],o:["Non : un corner n'est pas un cas de VAR","Oui : la VAR corrige toutes les erreurs visibles de l'arbitre","Oui, si le capitaine demande officiellement la vidéo","Non : la VAR ne fonctionne qu'en seconde période"],a:0,w:"La VAR ne sert que pour les buts, penalties, rouges directs et erreurs d'identité, en cas d'erreur claire et évidente."},
{i:"k266_24",u:266,t:"mcq",d:.5,q:"Quel critère la VAR doit-elle respecter pour intervenir ?",o:["Une erreur claire et évidente","Un doute, même léger, sur l'action","Une demande officielle de l'entraîneur","Un avis majoritaire du public en tribune"],a:0,w:"Elle n'arbitre pas le match à nouveau : elle corrige seulement les erreurs claires et évidentes ou les incidents graves manqués."},
{i:"k266_25",u:266,t:"fill",d:.5,q:"Pour une décision d'appréciation, l'arbitre va revoir l'action sur l'écran au bord du ___.",o:["terrain","vestiaire","banc","tunnel"],a:0,w:"C'est la révision au bord du terrain. Pour un fait objectif comme un hors-jeu, la correction est directe."},
{i:"k266_26",u:266,t:"tf",d:.5,q:"Le hors-jeu semi-automatique modélise la position des joueurs en 3D dans les grandes compétitions.",a:true,w:"Caméras et capteurs reconstituent la scène. L'humain valide la décision."},
{i:"k266_27",u:266,t:"order",d:.5,q:"Remets dans l'ordre l'analyse d'un but litigieux.",it:["Figer l'image à l'instant de la passe","Repérer l'avant-dernier défenseur","Comparer tête, corps et pieds de l'attaquant","Vérifier s'il participe au jeu","Décider : but ou coup franc indirect"],w:"Photo, repère, comparaison, participation, décision."},
{i:"k266_28",u:266,t:"story",d:.55,q:"Rappel du module 1 : que dis-tu ?",ctx:"Sur un corner du Racing, Lucas est seul derrière toute la défense adverse et marque de la tête.",sc:[{who:"Mehdi",txt:"Il était hors-jeu de trois mètres, c'est un scandale !"}],o:["Pas de hors-jeu directement sur un corner","Le but est refusé car Lucas était derrière le dernier défenseur","Il faut attendre la VAR pour savoir","Le but compte seulement si le corner est rentrant"],a:0,w:"T.C.6 : pas de hors-jeu sur Touche, Corner, 6 mètres."},
{i:"k266_29",u:266,t:"num",d:.55,q:"Rappel du module 1 : un coup franc direct à 25 m. À combien de mètres le mur doit-il se placer ?",a:9.15,tol:.01,un:" m",h:"Rayon du rond central",w:"9,15 m, le rayon du rond central. C'est la distance du mur sur tout coup franc, direct ou indirect."},
{i:"k266_30",u:266,t:"slider",d:.55,q:"Combien de situations la VAR peut-elle examiner ?",min:1,max:8,step:1,a:4,tol:0,pre:"",un:" situations",w:"Quatre : but, penalty, rouge direct, erreur d'identité."},
{i:"k266_31",u:266,t:"story",d:.6,q:"Que réponds-tu à Samir ?",ctx:"Le défenseur du Scarpe, dernier homme, fauche l'attaquant du Racing lancé seul vers le but, hors de la surface.",sc:[{who:"Samir Benhaddou",txt:"C'est quoi la sanction, au minimum ?"}],o:["Coup franc direct et rouge : occasion de but manifeste annihilée","Coup franc indirect et carton jaune","Penalty, puisque l'attaquant filait vers le but","Simple avertissement verbal au défenseur"],a:0,w:"Faute de contact hors de la surface : coup franc direct. Une occasion de but manifeste annihilée par une faute : rouge (module 1)."},
{i:"k266_32",u:266,t:"story",d:.6,q:"Synthèse : Élodie te demande ta méthode pour juger un but refusé.",sc:[{who:"Élodie Marchal",txt:"En une phrase, comment tu tranches un hors-jeu ?"}],o:["« Photo à la passe, avant-dernier défenseur, puis participation au jeu »","« Photo à la frappe, dernier défenseur, puis avis du public »","« Photo au but, gardien comme repère, et bras compris »","« Film de toute l'action, et la VAR tranche à chaque fois »"],a:0,w:"Instant de la passe, avant-dernier adversaire, tête-corps-pieds, puis participation. Position n'est pas faute."}
