/*UNIT*/
{id:268,c:"FOOT",n:"Module 4",t:"Les systèmes de jeu : lire un 4-3-3 et ses métamorphoses",col:"--green",ic:"📋",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Lire un <b>système</b> écrit en chiffres.</li>
<li>Donner les forces et faiblesses des systèmes courants : <b>4-4-2</b>, <b>4-3-3</b>, <b>4-2-3-1</b>, <b>3-5-2</b>.</li>
<li>Distinguer <b>système</b> (la photo de départ) et <b>animation</b> (le mouvement).</li>
<li>Reconnaître une équipe qui <b>change de forme</b> selon qu'elle a le ballon ou non.</li></ul>
<h3>Le schéma sur le tableau blanc</h3>
<div class="gstory">Mardi, séance vidéo au Racing. Samir dessine le FC Scarpe au tableau : « Sur le papier, ils jouent en 4-4-2. » Puis il lance la vidéo de leur dernier match. En possession, leur latéral gauche monte, leur milieu droit rentre, et le schéma devient méconnaissable. Mehdi, invité pour l'occasion, se gratte la tête : « Mais alors, ils jouent en quoi ? » Élodie : « En 4-4-2 quand ils défendent, en 3-2-5 quand ils attaquent. C'est ça, lire un match. »</div>
<h3>Lire les chiffres</h3>
<ul><li>On lit de l'<b>arrière vers l'avant</b> : défense, milieu, attaque.</li>
<li>Le <b>gardien ne compte pas</b> : la somme fait toujours <b>10</b>.</li>
<li>4-2-3-1 : 4 défenseurs, 2 milieux défensifs, 3 milieux offensifs, 1 avant-centre.</li></ul>
<div class="gmnemo"><b>« Toujours 10, jamais le gardien »</b>. Si ta somme fait 11, tu as compté le gardien. Si elle fait 9, il manque un joueur.</div>
<h3>Les quatre systèmes à connaître</h3>
<table><tr><th>Système</th><th>Forces</th><th>Faiblesses</th></tr>
<tr><td><b>4-4-2</b></td><td>Deux lignes de quatre très compactes, couloirs couverts, simple à organiser</td><td>Deux milieux seulement : risque d'infériorité face à trois milieux</td></tr>
<tr><td><b>4-3-3</b></td><td>Largeur, pressing haut à trois, triangle au milieu</td><td>Espaces derrière les latéraux quand ils montent</td></tr>
<tr><td><b>4-2-3-1</b></td><td>Équilibre : double pivot devant la défense, trois créateurs</td><td>Avant-centre souvent isolé</td></tr>
<tr><td><b>3-5-2</b></td><td>Trois centraux, surnombre dans l'axe, pistons dans les couloirs</td><td>Couloirs exposés quand les pistons sont montés</td></tr></table>
<p>Un <b>piston</b> est un latéral très offensif d'un système à trois défenseurs : il fait tout le couloir. Quand les pistons redescendent, un 3-5-2 devient un <b>5-3-2</b>.</p>
<svg class='gsvg' viewBox='0 0 220 158' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='10' y='6' width='200' height='130' rx='3' fill='#1E6B3A'/><rect x='10' y='6' width='200' height='130' rx='3' fill='none' stroke='#FFFFFF' stroke-width='1.4'/><line x1='110' y1='6' x2='110' y2='136' stroke='#FFFFFF' stroke-width='1.2'/><circle cx='110' cy='71' r='15' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><rect x='10' y='37' width='28' height='68' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><rect x='182' y='37' width='28' height='68' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><circle cx='196' cy='71' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='196' y='73.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>G</text><circle cx='168' cy='24' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='168' y='26.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>2</text><circle cx='170' cy='56' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='170' y='58.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>4</text><circle cx='170' cy='86' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='170' y='88.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>5</text><circle cx='168' cy='118' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='168' y='120.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>3</text><circle cx='140' cy='24' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='140' y='26.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>7</text><circle cx='142' cy='58' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='142' y='60.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>6</text><circle cx='142' cy='84' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='142' y='86.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>8</text><circle cx='140' cy='118' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='140' y='120.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>11</text><circle cx='114' cy='58' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='114' y='60.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>9</text><circle cx='114' cy='86' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='114' y='88.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>10</text><text x='110' y='151' font-size='9' fill='var(--txt)' text-anchor='middle' font-weight='700'>4-4-2 compact du FC Scarpe, qui attaque vers la gauche</text></svg>
<h3>Système et animation</h3>
<p>Le <b>système</b> est la photo de départ. L'<b>animation</b>, ce sont les mouvements qui la transforment. Une même équipe a souvent <b>deux formes</b> :</p>
<ul><li><b>Hors possession</b> : une forme compacte pour défendre, souvent un 4-4-2 ou un 4-5-1.</li>
<li><b>En possession</b> : une forme étirée pour attaquer, par exemple un <b>3-2-5</b> (trois derrière, deux au milieu, cinq devant).</li></ul>
<p>Le 3-2-5 naît souvent d'un latéral qui reste avec les centraux, d'un latéral inversé qui rentre au milieu, et d'ailiers qui fixent la largeur.</p>
<div class="gmnemo">Retiens : <b>« On défend en largeur réduite, on attaque en largeur maximale »</b>. Serré sans le ballon, écarté avec.</div>
<div class="gtrap">La fiche de la formation ne parle pas des systèmes. Mais sa grille d'observation demande de repérer les « ajustements à la pause (système, bloc, joueur) ». Impossible sans savoir lire un système, d'où ce module.</div>
<h3>Ce que tu dois retenir</h3>
<ul><li>On lit de l'arrière vers l'avant, somme de 10, sans le gardien.</li>
<li>4-4-2 compact, 4-3-3 large, 4-2-3-1 équilibré, 3-5-2 axial.</li>
<li>Système = photo, animation = film.</li>
<li>Une forme sans le ballon, une autre avec.</li></ul>`},
/*EXOS*/
{i:"k268_01",u:268,t:"fill",d:.2,nw:"Lire un système",q:"Dans un système écrit en chiffres, la somme fait toujours ___.",o:["10","11","9","12"],a:0,w:"Toujours 10, jamais le gardien. Si ta somme fait 11, tu as compté le gardien."},
{i:"k268_02",u:268,t:"tf",d:.25,q:"Dans un 4-2-3-1, le chiffre 1 désigne le gardien.",a:false,w:"On lit de l'arrière vers l'avant sans le gardien : le 1 est l'avant-centre."},
{i:"k268_03",u:268,t:"match",d:.3,q:"4-2-3-1 : associe chaque chiffre à sa ligne.",p:[["4","Défenseurs"],["2","Milieux défensifs"],["3","Milieux offensifs"],["1","Avant-centre"]],w:"De l'arrière vers l'avant : 4, 2, 3, 1. Le gardien n'est jamais dans les chiffres."},
{i:"k268_04",u:268,t:"tiles",d:.3,q:"Reconstitue la règle mémo de lecture.",a:["Toujours","10,","jamais","le","gardien"],dd:["11,","l'arbitre","souvent"],w:"La somme fait 10 : le gardien n'est pas compté."},
{i:"k268_05",u:268,t:"story",d:.3,q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"J'ai compté leur système : 4-4-3. C'est bien ça ?"}],o:["Ça fait 11 : tu as compté le gardien","Oui, c'est un système très offensif","Non, un système a toujours trois chiffres pairs","Oui, c'est le système le plus joué en N3"],a:0,w:"4 + 4 + 3 = 11. Toujours 10 : un joueur de trop, c'est le gardien."},
{i:"k268_06",u:268,t:"sort",d:.35,q:"Combien de défenseurs dans ce système ?",bins:["Trois défenseurs","Quatre défenseurs"],it:[["3-5-2",0],["4-4-2",1],["4-3-3",1],["3-4-3",0],["4-2-3-1",1]],w:"Le premier chiffre, c'est la défense. Le premier chiffre donne toujours le nombre de défenseurs."},
{i:"k268_07",u:268,t:"mcq",d:.35,nw:"Le 4-4-2",q:"Quelle est la force principale d'un 4-4-2 ?",o:["Deux lignes de quatre compactes","Trois milieux dans l'axe","Cinq attaquants en possession","Un avant-centre seul et isolé"],a:0,w:"Deux lignes de quatre serrées, couloirs couverts. Faiblesse : deux milieux seulement."},
{i:"k268_08",u:268,t:"story",d:.4,q:"Que conseilles-tu à Samir ?",ctx:"Le Racing joue en 4-4-2. Le FC Scarpe aligne trois milieux et domine le cœur du jeu.",sc:[{who:"Samir Benhaddou",txt:"On est toujours à deux contre trois au milieu. Pourquoi ?"}],o:["Le 4-4-2 n'a que deux milieux face à trois","Nos milieux ne courent pas assez vite","Le Scarpe triche en jouant à 12 joueurs","Nos défenseurs montent trop haut"],a:0,w:"Faiblesse classique du 4-4-2 : infériorité numérique au milieu face à un 4-3-3. Solution : faire redescendre un attaquant ou changer de système."},
{i:"k268_09",u:268,t:"mcq",d:.4,nw:"Le 4-3-3",q:"Quelle faiblesse guette souvent un 4-3-3 ?",o:["Les espaces derrière les latéraux","Le manque de largeur en attaque","L'absence de milieu défensif","Un seul attaquant de pointe"],a:0,w:"Les latéraux montent pour donner de la largeur : leur couloir se vide à la perte du ballon."},
{i:"k268_10",u:268,t:"multi",d:.4,q:"Quelles sont les forces d'un 4-3-3 ?",o:["La largeur offensive","Le pressing haut à trois","Le triangle au milieu","Des couloirs toujours protégés","Deux lignes de quatre"],a:[0,1,2],w:"Largeur, pressing à trois, triangle. Les couloirs sont justement sa faiblesse."},
{i:"k268_11",u:268,t:"fill",d:.4,nw:"Le 4-2-3-1",q:"Dans un 4-2-3-1, les deux milieux défensifs forment un double ___.",o:["pivot","piston","libéro","rideau"],a:0,w:"Le double pivot protège la défense et équilibre l'équipe."},
{i:"k268_12",u:268,t:"tf",d:.4,q:"Le risque d'un 4-2-3-1 est d'isoler l'avant-centre.",a:true,w:"Un seul attaquant de pointe : s'il n'est pas soutenu par les trois créateurs, il se bat seul."},
{i:"k268_13",u:268,t:"mcq",d:.45,nw:"Le 3-5-2 et les pistons",q:"Comment appelle-t-on le latéral très offensif d'un 3-5-2 ?",o:["Un piston","Un pivot","Un libéro","Un stoppeur"],a:0,w:"Le piston fait tout le couloir, de sa surface à celle d'en face."},
{i:"k268_14",u:268,t:"story",d:.45,q:"Que réponds-tu à Élodie ?",sc:[{who:"Élodie Marchal",txt:"Leur 3-5-2 devient un 5-3-2 dès qu'on a le ballon. Pourquoi ?"}],o:["Les pistons redescendent en défense","Deux milieux se blessent à chaque perte","L'arbitre impose cinq défenseurs","Leur gardien sort jouer défenseur"],a:0,w:"Hors possession, les pistons se replacent à côté des trois centraux : cinq défenseurs."},
{i:"k268_15",u:268,t:"sort",d:.45,q:"Force ou faiblesse du 3-5-2 ?",bins:["Force","Faiblesse"],it:[["Surnombre dans l'axe",0],["Couloirs exposés quand les pistons montent",1],["Trois centraux solides",0],["Pistons épuisés en fin de match",1]],w:"Axe renforcé, couloirs fragiles. Les pistons font tout le couloir et finissent souvent épuisés."},
{i:"k268_16",u:268,t:"match",d:.45,q:"Associe chaque système à sa faiblesse.",p:[["4-4-2","Infériorité au milieu"],["4-3-3","Espaces derrière les latéraux"],["4-2-3-1","Avant-centre isolé"],["3-5-2","Couloirs exposés"]],w:"Chaque système a sa zone fragile : c'est là que l'adversaire attaque."},
{i:"k268_17",u:268,t:"story",d:.5,nw:"Système et animation",q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"Le Scarpe est annoncé en 4-4-2 mais je vois trois défenseurs et cinq joueurs devant quand ils attaquent. La compo est fausse ?"}],o:["Non : 4-4-2 sans ballon, 3-2-5 avec","Oui, le journal s'est trompé de système","Oui, trois joueurs ont changé de poste","Non : ils jouent à 12 en attaque"],a:0,w:"Le système est la photo de départ, l'animation le film. Deux formes selon la possession."},
{i:"k268_18",u:268,t:"tiles",d:.45,q:"Reconstitue la formule mémo du système.",a:["Système","=","photo,","animation","=","film"],dd:["vidéo,","dessin","match"],w:"La photo de départ, puis les mouvements qui la transforment."},
{i:"k268_19",u:268,t:"multi",d:.5,q:"Comment une équipe passe-t-elle souvent en 3-2-5 en possession ?",o:["Un latéral reste avec les centraux","L'autre latéral rentre au milieu","Les ailiers fixent la largeur","Le gardien joue milieu","Les deux 6 montent en attaque"],a:[0,1,2],w:"Trois derrière, deux au milieu (le 6 et le latéral inversé), cinq devant."},
{i:"k268_20",u:268,t:"fill",d:.5,q:"En possession, une équipe cherche une largeur ___.",o:["maximale","réduite","nulle","centrale"],a:0,w:"On défend serré, on attaque écarté. Les ailiers restent collés à la ligne pour étirer la défense adverse."},
{i:"k268_21",u:268,t:"tf",d:.5,q:"Une équipe défend en général plus étirée qu'elle n'attaque.",a:false,w:"Faux : c'est l'inverse. On défend serré pour fermer les espaces, on attaque écarté pour en créer."},
{i:"k268_22",u:268,t:"num",d:.5,q:"En 3-2-5, combien de joueurs de champ sont derrière la ligne des cinq attaquants ?",a:5,tol:0,un:" joueurs",h:"3 + 2",w:"3 + 2 = 5, et 5 devant. Le gardien en plus."},
{i:"k268_23",u:268,t:"story",d:.5,q:"Rappel du module 3 : quel rôle permet ce 3-2-5 ?",sc:[{who:"Élodie Marchal",txt:"Leur latéral droit se retrouve au milieu à côté du 6 dès qu'ils ont le ballon."}],o:["Un latéral inversé","Un faux 9","Un pivot","Un ailier classique"],a:0,w:"Le latéral inversé rentre dans l'axe : c'est lui qui forme le 2 du 3-2-5 avec le 6."},
{i:"k268_24",u:268,t:"order",d:.5,q:"Remets dans l'ordre la lecture d'un système adverse.",it:["Compter les joueurs par ligne, de l'arrière vers l'avant","Vérifier que la somme fait 10","Observer la forme sans le ballon","Observer la forme avec le ballon","Repérer qui change de ligne"],w:"Photo de départ, vérification, puis les deux formes et les joueurs qui bougent. Le système est la photo, l'animation le film des mouvements."},
{i:"k268_25",u:268,t:"mcq",d:.55,q:"Face à un 4-3-3 adverse, où le Racing doit-il attaquer en priorité ?",o:["Derrière les latéraux montés","Dans l'axe, devant les trois milieux","Sur le gardien adverse","Sur les corners seulement"],a:0,w:"On attaque la faiblesse du système : les couloirs laissés libres par les latéraux."},
{i:"k268_26",u:268,t:"story",d:.55,q:"Rappel du module 2 : que réponds-tu ?",ctx:"Dans le 3-5-2 du Scarpe, un piston est à hauteur du dernier central au moment de la passe et marque.",sc:[{who:"Mehdi",txt:"Il était hors-jeu, forcément, il vient de si loin !"}],o:["À hauteur, il est en jeu : but valable","Il est hors-jeu dès qu'il court vite","Il est hors-jeu car un piston est un défenseur","La VAR doit annuler tout but de piston"],a:0,w:"Égalité avec l'avant-dernier adversaire : en jeu. La photo à la passe décide."},
{i:"k268_27",u:268,t:"tf",d:.55,q:"Un 3-5-2 et un 5-3-2 peuvent être la même équipe à deux moments différents.",a:true,w:"Pistons montés : 3-5-2. Pistons redescendus : 5-3-2."},
{i:"k268_28",u:268,t:"sort",d:.55,q:"Hors possession ou en possession ?",bins:["Forme hors possession","Forme en possession"],it:[["4-4-2 compact",0],["3-2-5 étiré",1],["5-3-2 avec pistons bas",0],["2-3-5 très offensif",1],["4-5-1 regroupé",0]],w:"Formes serrées sans le ballon, formes étirées avec."},
{i:"k268_29",u:268,t:"slider",d:.55,q:"En 4-2-3-1, combien de milieux offensifs ?",min:0,max:5,step:1,a:3,tol:0,pre:"",un:" milieux",w:"4 défenseurs, 2 milieux défensifs, 3 milieux offensifs, 1 attaquant."},
{i:"k268_30",u:268,t:"story",d:.6,q:"Que proposes-tu à Samir pour la seconde période ?",ctx:"Le Racing (4-4-2) est dominé au milieu par le 4-3-3 du Scarpe, dont les latéraux montent très haut.",sc:[{who:"Samir Benhaddou",txt:"Un changement de système, ou autre chose ?"}],o:["Un 4-3-3 pour égaliser au milieu, et viser leurs couloirs","Garder le 4-4-2 et demander de courir plus","Passer en 3-5-2 et retirer un milieu","Jouer à cinq attaquants pour marquer vite"],a:0,w:"Trois contre trois au milieu, et exploiter la faiblesse adverse : les espaces derrière les latéraux."},
{i:"k268_31",u:268,t:"mcq",d:.6,q:"Pourquoi l'analyste doit-il noter la forme en possession et hors possession ?",o:["Une équipe a souvent deux formes","Le système change chaque minute","L'arbitre exige deux systèmes","Seule la forme au coup d'envoi compte"],a:0,w:"Système de départ, forme défensive, forme offensive : trois photos à relever."},
{i:"k268_32",u:268,t:"story",d:.6,q:"Synthèse : Élodie te demande le résumé du Scarpe.",sc:[{who:"Élodie Marchal",txt:"Leur système, leurs deux formes, leur faiblesse. Une phrase."}],o:["« 4-4-2 sans ballon, 3-2-5 avec, couloir gauche vide à la perte »","« 4-4-3 fixe, aucune faiblesse, on ne peut rien faire »","« Un seul système, qui ne bouge jamais du coup d'envoi à la fin »","« 11 joueurs devant, 0 derrière, match gagné d'avance »"],a:0,w:"Photo de départ, deux formes, zone fragile : c'est le rapport d'un analyste."}
