/*UNIT*/
{id:269,c:"FOOT",n:"Module 5",t:"Les 4 phases du jeu : la boussole de l'analyste",col:"--green",ic:"🔄",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Nommer les <b>4 phases du jeu</b> dans l'ordre du cycle.</li>
<li>Dire dans quelle phase se trouve une équipe à un instant donné.</li>
<li>Donner l'<b>objectif</b> de chaque phase.</li>
<li>Expliquer pourquoi les <b>transitions</b> se jouent en <b>0 à 5 secondes</b>.</li></ul>
<h3>Le match découpé en quatre</h3>
<div class="gstory">Mi-temps de Racing-Scarpe. Élodie a monté une vidéo de quatre minutes. « Regarde : 12e minute, on a le ballon, on construit. 12e minute et 30 secondes, Rayan le perd. Trois secondes plus tard, ils sont dans notre surface. » Mehdi proteste : « Mais c'est la même action ! » Élodie : « Non. Ce sont quatre phases différentes, et c'est dans les deux phases courtes que le match s'est joué. »</div>
<h3>Le cycle des 4 phases</h3>
<table><tr><th>Phase</th><th>Situation</th><th>Objectif</th></tr>
<tr><td>1. <b>Possession organisée</b></td><td>On a le ballon, l'équipe est en place</td><td>Structure stable, progresser, créer des occasions</td></tr>
<tr><td>2. <b>Transition défensive</b></td><td>On vient de <b>perdre</b> le ballon</td><td>Réagir en <b>0 à 5 secondes</b> : récupérer ou freiner</td></tr>
<tr><td>3. <b>Défense organisée</b></td><td>L'adversaire a le ballon, notre bloc est replacé</td><td>Bloc stable, fermer les espaces, récupérer</td></tr>
<tr><td>4. <b>Transition offensive</b></td><td>On vient de <b>récupérer</b> le ballon</td><td>Exploiter le trou en <b>0 à 5 secondes</b>, avant que l'adversaire se replace</td></tr></table>
<p>Puis le cycle recommence : une transition offensive réussie devient une possession, une possession perdue devient une transition défensive.</p>
<div class="gmnemo">Le cycle en quatre verbes : <b>« Construire, Réagir, Défendre, Frapper »</b>. Les deux phases stables (construire, défendre) durent longtemps. Les deux transitions (réagir, frapper) durent <b>5 secondes</b> : ce sont elles qui font les buts.</div>
<h3>Pourquoi les transitions décident des matchs</h3>
<ul><li>À l'instant de la perte, l'équipe qui avait le ballon est <b>étirée</b> : latéraux montés, milieux avancés.</li>
<li>L'équipe qui récupère trouve donc des <b>espaces</b> qui n'existent pas contre un bloc replacé.</li>
<li>Ces espaces se referment en quelques secondes : d'où la fenêtre de <b>0 à 5 secondes</b>.</li>
<li>Deux réponses possibles à la perte : <b>contre-presser</b> tout de suite (module 10) ou <b>se replier</b> vite.</li></ul>
<h3>Reconnaître la phase en direct</h3>
<ul><li>Qui a le ballon depuis <b>combien de temps</b> ? Moins de 5 secondes après un changement de possession : transition.</li>
<li>Les deux équipes sont-elles <b>en place</b> ? Oui : phase organisée. Non : transition.</li>
<li>Combien de joueurs sont <b>derrière le ballon</b> ? Beaucoup : bloc replacé. Peu : transition en cours.</li></ul>
<div class="gmnemo">La règle de l'analyste : <b>« Changement de ballon, lance le chrono »</b>. Compte cinq secondes dans ta tête à chaque perte ou récupération, et regarde ce qui se passe dans ces cinq secondes.</div>
<div class="gtrap">Ta fiche donne les 4 phases et la fenêtre de 0 à 5 secondes, sans dire pourquoi. Retiens la raison : à la perte, l'équipe est étirée, et l'adversaire trouve des espaces qui disparaissent dès que le bloc se replace.</div>
<h3>Ce que tu dois retenir</h3>
<ul><li>Possession organisée, transition défensive, défense organisée, transition offensive.</li>
<li>Les transitions se jouent en 0 à 5 secondes.</li>
<li>Construire, Réagir, Défendre, Frapper.</li>
<li>Changement de ballon, lance le chrono.</li></ul>`},
/*EXOS*/
{i:"k269_01",u:269,t:"order",d:.2,nw:"Les 4 phases du jeu",q:"Remets les 4 phases dans l'ordre du cycle, en partant de la possession.",it:["Possession organisée","Transition défensive","Défense organisée","Transition offensive"],w:"Construire, Réagir, Défendre, Frapper, puis le cycle recommence."},
{i:"k269_02",u:269,t:"tiles",d:.25,q:"Reconstitue les quatre verbes mémo des phases.",a:["Construire,","Réagir,","Défendre,","Frapper"],dd:["Attendre,","Dribbler,","Reculer,"],w:"Deux phases stables, deux transitions de 5 secondes."},
{i:"k269_03",u:269,t:"match",d:.3,q:"Associe chaque situation à sa phase.",p:[["Le Racing fait circuler le ballon en place","Possession organisée"],["Rayan vient de perdre le ballon","Transition défensive"],["Le Scarpe attaque, notre bloc est replacé","Défense organisée"],["Lucas vient d'intercepter","Transition offensive"]],w:"Qui a le ballon, depuis combien de temps, et les équipes sont-elles en place ?"},
{i:"k269_04",u:269,t:"tf",d:.3,q:"La transition défensive commence à l'instant où l'équipe perd le ballon.",a:true,w:"C'est la phase Réagir : 0 à 5 secondes pour récupérer ou freiner."},
{i:"k269_05",u:269,t:"story",d:.3,q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"On construit, Rayan perd le ballon, ils marquent : c'est une seule action, non ?"}],o:["Non : trois phases, dont deux transitions","Oui, une action reste une seule phase","Non, c'est une phase de coup de pied arrêté","Oui, les phases n'existent qu'à la mi-temps"],a:0,w:"Possession organisée, transition défensive ratée, transition offensive adverse réussie."},
{i:"k269_06",u:269,t:"slider",d:.3,nw:"La fenêtre des 5 secondes",q:"Dans quelle fenêtre de temps se joue une transition, en secondes (borne haute) ?",min:1,max:15,step:1,a:5,tol:0,pre:"",un:" s",w:"0 à 5 secondes. Après, le bloc adverse s'est replacé."},
{i:"k269_07",u:269,t:"mcq",d:.35,q:"Quel est l'objectif de la possession organisée ?",o:["Progresser avec une structure stable","Récupérer le ballon en moins de 5 secondes","Se replier tous derrière la ligne du ballon","Dégager le plus loin possible vers l'avant"],a:0,w:"Structure stable, progression, création d'occasions."},
{i:"k269_08",u:269,t:"sort",d:.35,q:"Phase stable ou transition ?",bins:["Phase stable","Transition"],it:[["Possession organisée",0],["Transition défensive",1],["Défense organisée",0],["Transition offensive",1]],w:"Deux phases longues et stables, deux phases courtes de 5 secondes."},
{i:"k269_09",u:269,t:"fill",d:.35,q:"La transition offensive commence quand l'équipe ___ le ballon.",o:["récupère","perd","dégage en touche","touche de la main"],a:0,w:"Récupérer, puis frapper vite avant que l'adversaire se replace."},
{i:"k269_10",u:269,t:"story",d:.4,nw:"Pourquoi les transitions décident",q:"Que réponds-tu à Samir ?",sc:[{who:"Samir Benhaddou",txt:"Pourquoi on se fait toujours punir juste après avoir perdu le ballon, et jamais quand on est en place ?"}],o:["À la perte, nous sommes étirés et ouverts","L'arbitre siffle beaucoup moins de fautes juste après une perte","Le Scarpe est plus rapide que nous sur toute la durée du match","Nos joueurs sont physiquement fatigués à chaque perte de balle"],a:0,w:"Latéraux montés, milieux avancés : l'équipe qui vient de perdre est étirée. L'adversaire trouve des espaces qui disparaissent en 5 secondes."},
{i:"k269_11",u:269,t:"multi",d:.4,q:"Pourquoi une équipe qui vient de perdre le ballon est-elle vulnérable ?",o:["Ses latéraux sont souvent montés","Ses milieux sont avancés","Son bloc n'est pas replacé","L'adversaire a plus de joueurs","Le hors-jeu ne s'applique plus"],a:[0,1,2],w:"Elle est étirée et pas en place. L'adversaire n'a pas plus de joueurs : il a plus d'espace."},
{i:"k269_12",u:269,t:"tf",d:.4,q:"Contre un bloc replacé, l'équipe qui attaque trouve en général plus d'espaces qu'en transition.",a:false,w:"C'est l'inverse : en transition, l'adversaire est étiré. Contre un bloc replacé, les espaces sont fermés."},
{i:"k269_13",u:269,t:"mcq",d:.4,q:"Quelles sont les deux réponses possibles juste après une perte de balle ?",o:["Contre-presser ou se replier vite","Attendre en place ou protester auprès de l'arbitre","Dégager en touche ou tirer de très loin","Faire une faute tactique ou simuler un contact"],a:0,w:"Réagir, c'est soit reprendre le ballon tout de suite (contre-pressing, module 10), soit revenir se replacer très vite."},
{i:"k269_14",u:269,t:"tiles",d:.4,q:"Reconstitue la règle de l'analyste.",a:["Changement","de","ballon,","lance","le","chrono"],dd:["arrête","joueur,","sifflet"],w:"À chaque perte ou récupération, compte 5 secondes et observe."},
{i:"k269_15",u:269,t:"story",d:.45,nw:"Reconnaître la phase",q:"Dans quelle phase est le Scarpe ?",ctx:"Le FC Scarpe a le ballon depuis une minute. Ses dix joueurs de champ sont en place, le Racing est replié.",sc:[{who:"Élodie Marchal",txt:"Phase ?"}],o:["Possession organisée pour le Scarpe","Transition offensive pour le Scarpe","Transition défensive pour le Scarpe","Aucune phase, c'est un temps mort"],a:0,w:"Plus de 5 secondes de possession, équipes en place : phase organisée."},
{i:"k269_16",u:269,t:"multi",d:.45,q:"Quels indices montrent qu'on est en transition ?",o:["Moins de 5 secondes depuis le changement de ballon","Peu de joueurs derrière le ballon","Des blocs pas en place","Deux lignes de quatre compactes","Un long échange de passes latérales"],a:[0,1,2],w:"Chrono court, peu de joueurs derrière le ballon, blocs désorganisés."},
{i:"k269_17",u:269,t:"fill",d:.45,q:"Si beaucoup de défenseurs sont derrière le ballon et en place, l'équipe est en défense ___.",o:["organisée","de transition","offensive","individuelle"],a:0,w:"Bloc replacé et stable : défense organisée."},
{i:"k269_18",u:269,t:"sort",d:.45,q:"Du point de vue du Racing, quelle phase ?",bins:["Transition défensive","Transition offensive"],it:[["Rayan perd le ballon au milieu",0],["Tom capte un centre et relance vite",1],["Lucas se fait intercepter une passe",0],["Nabil récupère sur un tacle",1]],w:"On perd : transition défensive. On récupère : transition offensive."},
{i:"k269_19",u:269,t:"story",d:.5,q:"Rappel du module 4 : que réponds-tu ?",sc:[{who:"Élodie Marchal",txt:"En possession, ils passent en 3-2-5. À la perte, qu'est-ce qui les rend vulnérables ?"}],o:["Cinq devant, peu de monde derrière","Leur gardien joue beaucoup trop haut sur le terrain","Ils ont un joueur de moins quand ils ont le ballon","Ils oublient les règles du hors-jeu en possession"],a:0,w:"Plus la forme en possession est offensive, plus la transition défensive est risquée. D'où la rest defense (module 10)."},
{i:"k269_20",u:269,t:"mcq",d:.5,q:"Pourquoi faut-il frapper en moins de 5 secondes en transition offensive ?",o:["L'adversaire se replace très vite","L'arbitre siffle après 5 secondes","Le ballon doit être passé en 5 s","Au-delà, c'est hors-jeu"],a:0,w:"Les espaces créés par la perte adverse se referment dès que le bloc se replace."},
{i:"k269_21",u:269,t:"num",d:.5,q:"Une récupération à la 30e minute et 12 secondes. Jusqu'à quelle seconde (minute 30) dure la fenêtre de transition ?",a:17,tol:0,un:" s",h:"12 + 5",w:"12 + 5 = 17 secondes : 30'17. C'est la règle du chrono."},
{i:"k269_22",u:269,t:"tf",d:.5,q:"Les transitions durent en général plus longtemps que les phases organisées.",a:false,w:"Faux : les transitions durent environ 5 secondes. Construire et défendre sont les phases longues."},
{i:"k269_23",u:269,t:"story",d:.5,q:"Que conseilles-tu à Samir ?",ctx:"Le Racing a encaissé trois buts cette saison dans les 5 secondes suivant une perte au milieu.",sc:[{who:"Samir Benhaddou",txt:"On travaille quoi cette semaine ?"}],o:["La réaction à la perte de balle","Les corners offensifs, et uniquement eux cette semaine","Le jeu long systématique vers l'avant-centre","La frappe de loin de nos défenseurs centraux"],a:0,w:"Le problème est en transition défensive : c'est la phase Réagir qu'il faut entraîner."},
{i:"k269_24",u:269,t:"match",d:.5,q:"Associe chaque phase à son verbe mémo.",p:[["Possession organisée","Construire"],["Transition défensive","Réagir"],["Défense organisée","Défendre"],["Transition offensive","Frapper"]],w:"Construire, Réagir, Défendre, Frapper. Deux phases stables et deux transitions de 5 secondes."},
{i:"k269_25",u:269,t:"story",d:.55,q:"Rappel du module 3 : quel rôle aide le plus en transition offensive ?",sc:[{who:"Élodie Marchal",txt:"On récupère au milieu. Qui doit-on chercher en une passe ?"}],o:["L'attaquant ou l'ailier lancé dans l'espace","Le gardien, pour ralentir le jeu","Le défenseur central le plus proche","Le joueur le plus éloigné du but"],a:0,w:"Frapper vite : la passe vers l'avant, dans l'espace laissé par l'adversaire étiré."},
{i:"k269_26",u:269,t:"mcq",d:.55,q:"Rappel du module 1 : le Racing récupère, Tom garde le ballon 10 secondes en main pour calmer le jeu. Que risque-t-il ?",o:["Un corner pour l'adversaire","Un penalty","Un carton rouge","Rien, c'est autorisé"],a:0,w:"8 secondes au plus depuis 2025/26. Et il gâche la transition offensive."},
{i:"k269_27",u:269,t:"order",d:.55,q:"Remets dans l'ordre l'action type d'un but en transition.",it:["Le Racing construit","Rayan perd le ballon","Le Scarpe récupère","Le Scarpe frappe en moins de 5 secondes","But"],w:"Possession, perte, transition offensive adverse, but : l'action de la vidéo d'Élodie."},
{i:"k269_28",u:269,t:"fill",d:.55,q:"Quand la possession dure plus de 5 secondes et que les blocs sont en place, on est en phase ___.",o:["organisée","de transition","arrêtée","neutre"],a:0,w:"Le chrono est dépassé, les équipes sont replacées : phase organisée."},
{i:"k269_29",u:269,t:"tf",d:.55,q:"Une transition offensive réussie devient ensuite une possession organisée si l'attaque se pose.",a:true,w:"Le cycle tourne : si on ne frappe pas vite, on s'installe dans la possession."},
{i:"k269_30",u:269,t:"story",d:.6,q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"Pendant un match, je regarde quoi pour repérer les moments clés ?"}],o:["Chaque changement de ballon, puis 5 secondes","Uniquement les tirs au but et les arrêts du gardien","Le tableau d'affichage à chaque minute du match","Les joueurs qui courent le plus vite sur le terrain"],a:0,w:"Changement de ballon, lance le chrono : c'est le réflexe numéro 2 de ta fiche."},
{i:"k269_31",u:269,t:"slider",d:.6,q:"Combien de phases compte le cycle du jeu ?",min:2,max:6,step:1,a:4,tol:0,pre:"",un:" phases",w:"Quatre : deux organisées, deux transitions."},
{i:"k269_32",u:269,t:"story",d:.6,q:"Synthèse : Élodie te demande le résumé du module.",sc:[{who:"Élodie Marchal",txt:"Une phrase sur les phases."}],o:["« Quatre phases, et les buts naissent dans les 5 secondes des transitions »","« Une seule phase, le jeu est continu et ne se découpe pas »","« Deux phases : attaquer et défendre, le reste ne compte pas »","« Les transitions durent 20 minutes, entre deux mi-temps »"],a:0,w:"Construire, Réagir, Défendre, Frapper. Les deux phases courtes décident."}
