/*UNIT*/
{id:270,c:"FOOT",n:"Module 6",t:"Le bloc : haut, moyen ou bas, et comment on défend ensemble",col:"--green",ic:"🧱",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Situer le <b>bloc</b> d'une équipe : haut, moyen ou bas.</li>
<li>Donner les avantages et les risques de chaque hauteur.</li>
<li>Expliquer la <b>compacité</b> et le <b>coulissement</b>.</li>
<li>Distinguer défense de <b>zone</b>, <b>individuelle</b> et <b>mixte</b>.</li>
<li>Comprendre l'idée d'<b>orienter</b> l'adversaire vers les côtés.</li></ul>
<h3>Où est leur ligne ?</h3>
<div class="gstory">Première question de la grille d'Élodie : « Où se situe le bloc de chaque équipe ? » Tu regardes le FC Scarpe sans le ballon : leur défense se tient à trente mètres de leur but, leurs deux attaquants attendent au rond central. Mehdi, lui, compte les joueurs derrière le ballon : « Ils sont dix derrière ! Ils ont peur ! » Élodie corrige : « Ils ne reculent pas par peur. Ils ont choisi un bloc moyen-bas pour nous attendre et contrer. »</div>
<h3>La hauteur du bloc</h3>
<p>Le <b>bloc</b> est l'ensemble de l'équipe hors possession. Sa hauteur se lit à la position de la <b>ligne défensive</b>.</p>
<table><tr><th>Bloc</th><th>Où</th><th>Avantage</th><th>Risque</th></tr>
<tr><td><b>Haut</b></td><td>Ligne près du milieu de terrain</td><td>Récupérer loin de son but, étouffer l'adversaire</td><td>Grand espace dans le dos de la défense</td></tr>
<tr><td><b>Moyen</b></td><td>Autour du milieu de sa propre moitié</td><td>Équilibre : fermer l'axe, contrer</td><td>Laisser l'adversaire construire tranquillement</td></tr>
<tr><td><b>Bas</b></td><td>Ligne près de sa surface</td><td>Aucun espace dans le dos, surface protégée</td><td>Subir, récupérer très loin du but adverse</td></tr></table>
<svg class='gsvg' viewBox='0 0 220 158' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='10' y='6' width='200' height='130' rx='3' fill='#1E6B3A'/><rect x='10' y='6' width='40' height='130' fill='#4DA3FF' opacity='.45'/><rect x='50' y='6' width='30' height='130' fill='#FFD23F' opacity='.45'/><rect x='80' y='6' width='30' height='130' fill='#E5484D' opacity='.45'/><text x='30' y='20' font-size='8' fill='#FFFFFF' text-anchor='middle' font-weight='800'>BAS</text><text x='65' y='20' font-size='8' fill='#FFFFFF' text-anchor='middle' font-weight='800'>MOYEN</text><text x='95' y='20' font-size='8' fill='#FFFFFF' text-anchor='middle' font-weight='800'>HAUT</text><rect x='10' y='6' width='200' height='130' rx='3' fill='none' stroke='#FFFFFF' stroke-width='1.4'/><line x1='110' y1='6' x2='110' y2='136' stroke='#FFFFFF' stroke-width='1.2'/><circle cx='110' cy='71' r='15' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><rect x='10' y='37' width='28' height='68' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><rect x='182' y='37' width='28' height='68' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><text x='110' y='151' font-size='9' fill='var(--txt)' text-anchor='middle' font-weight='700'>Trois hauteurs de ligne défensive (on défend le but de gauche)</text></svg>
<div class="gmnemo">Les trois blocs : <b>« Haut je vole, moyen je contrôle, bas je protège »</b>. Le bloc haut vole le ballon près du but adverse, le moyen contrôle le milieu, le bas protège sa surface.</div>
<h3>La compacité</h3>
<ul><li>Un bon bloc est <b>compact</b> : peu d'espace entre les lignes (défense, milieu, attaque) et entre les joueurs d'une même ligne.</li>
<li>Repère courant : une trentaine de mètres entre le premier attaquant et le dernier défenseur.</li>
<li>Quand le bloc s'étire, des <b>espaces entre les lignes</b> s'ouvrent : c'est là que le 10 adverse reçoit.</li></ul>
<h3>Le coulissement</h3>
<p>Quand le ballon passe d'un côté à l'autre, tout le bloc <b>coulisse</b> latéralement vers le ballon. On accepte de laisser le côté opposé libre, car il est loin du ballon. On défend la <b>zone du ballon</b>, pas tout le terrain.</p>
<div class="gmnemo">Le bloc est un <b>accordéon</b> : il se resserre vers le ballon et se déplace en entier. Un joueur qui ne coulisse pas crée un trou, comme une touche cassée.</div>
<h3>Zone, individuelle, mixte</h3>
<table><tr><th>Défense</th><th>Principe</th></tr>
<tr><td><b>De zone</b></td><td>Chacun défend un <b>espace</b> et prend l'adversaire qui y entre</td></tr>
<tr><td><b>Individuelle</b> (homme à homme)</td><td>Chacun suit <b>un adversaire</b> partout</td></tr>
<tr><td><b>Mixte</b></td><td>Combinaison des deux, fréquente sur les coups de pied arrêtés (module 11)</td></tr></table>
<h3>Orienter l'adversaire</h3>
<p>Un bloc bien organisé ne subit pas : il <b>oriente</b> la construction adverse vers les <b>côtés</b>, où la ligne de touche sert de défenseur supplémentaire. On ferme l'axe, on laisse le couloir, puis on presse quand le ballon y arrive.</p>
<div class="gtrap">Ta fiche demande de repérer « où se situe le bloc (haut, moyen, bas) » sans définir les trois hauteurs. Retiens que la hauteur se lit à la <b>ligne défensive</b>, et que reculer n'est pas forcément avoir peur : c'est souvent un choix pour contrer.</div>
<h3>Ce que tu dois retenir</h3>
<ul><li>Haut je vole, moyen je contrôle, bas je protège.</li>
<li>Compacité : peu d'espace entre les lignes.</li>
<li>Coulissement : tout le bloc glisse vers le ballon.</li>
<li>Zone, individuelle, mixte. Orienter vers les côtés.</li></ul>`},
/*EXOS*/
{i:"k270_01",u:270,t:"mcq",d:.2,nw:"Le bloc",q:"À quoi se lit la hauteur du bloc d'une équipe ?",o:["À la position de sa ligne défensive","Au nombre de ses attaquants","À la position de son gardien de but, seul repère","À son nombre de passes réussies"],a:0,w:"La ligne défensive donne la hauteur du bloc : haut, moyen ou bas."},
{i:"k270_02",u:270,t:"match",d:.25,q:"Associe chaque bloc à son objectif.",p:[["Bloc haut","Récupérer près du but adverse"],["Bloc moyen","Fermer l'axe et contrer"],["Bloc bas","Protéger sa surface"],["Bloc compact","Peu d'espace entre les lignes"]],w:"Haut je vole, moyen je contrôle, bas je protège."},
{i:"k270_03",u:270,t:"tiles",d:.3,q:"Reconstitue la phrase mémo des blocs.",a:["Haut","je","vole,","moyen","je","contrôle,","bas","je","protège"],dd:["recule,","attaque,"],w:"Trois hauteurs, trois intentions : voler, contrôler, protéger."},
{i:"k270_04",u:270,t:"story",d:.3,q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"Ils ont dix joueurs derrière le ballon, ils ont peur de nous !"}],o:["C'est souvent un choix : attendre pour contrer","Oui, un bloc bas prouve toujours la peur","Non, ils sont fatigués et ne remontent plus sur chaque ballon","Oui, et l'arbitre devrait les sanctionner"],a:0,w:"Un bloc moyen-bas est une stratégie : fermer l'espace et frapper en transition."},
{i:"k270_05",u:270,t:"sort",d:.3,q:"Quel bloc ?",bins:["Haut","Moyen","Bas"],it:[["Ligne défensive au rond central",0],["Ligne défensive au bord de sa surface",2],["Ligne à mi-chemin de sa moitié",1],["Attaquants qui pressent le gardien adverse",0],["Dix joueurs dans ses 30 derniers mètres",2]],w:"La hauteur de la ligne défensive décide."},
{i:"k270_06",u:270,t:"tf",d:.35,q:"Le risque principal d'un bloc haut est l'espace laissé dans le dos de la défense.",a:true,w:"Ligne haute, grand espace derrière : un long ballon peut lancer un attaquant rapide."},
{i:"k270_07",u:270,t:"multi",d:.35,q:"Quels sont les avantages d'un bloc haut ?",o:["Récupérer loin de son but","Étouffer la construction adverse","Récupérer près du but adverse","Aucun espace dans son dos"],a:[0,1,2],w:"Voler le ballon haut, près du but adverse. Mais l'espace derrière est grand."},
{i:"k270_08",u:270,t:"fill",d:.35,q:"Le risque d'un bloc bas est de ___ et de récupérer loin du but adverse.",o:["subir","presser","dribbler","marquer"],a:0,w:"Bas je protège, mais je subis et j'ai loin à aller pour marquer."},
{i:"k270_09",u:270,t:"story",d:.4,q:"Que conseilles-tu à Samir ?",ctx:"Le FC Scarpe a un avant-centre très rapide qui gagne tous les duels de vitesse.",sc:[{who:"Samir Benhaddou",txt:"On joue avec un bloc haut comme d'habitude ?"}],o:["Plutôt moyen : ne pas lui offrir d'espace derrière","Oui, plus haut encore pour l'isoler","Oui, et sans aucune couverture derrière","Bas, avec nos attaquants aussi dans la surface quel que soit le score"],a:0,w:"Contre un attaquant rapide, un bloc haut offre l'espace qu'il aime. Un bloc moyen le réduit."},
{i:"k270_10",u:270,t:"mcq",d:.4,nw:"La compacité",q:"Qu'est-ce qu'un bloc compact ?",o:["Peu d'espace entre les lignes et les joueurs","Un bloc avec onze joueurs en défense, gardien compris","Un bloc qui reste toujours très bas","Un bloc sans milieu de terrain"],a:0,w:"Compact : lignes et joueurs proches, pas d'espace entre les lignes pour le 10 adverse."},
{i:"k270_11",u:270,t:"slider",d:.4,q:"Repère courant : distance entre le premier attaquant et le dernier défenseur d'un bloc compact, en mètres ?",min:10,max:70,step:5,a:30,tol:5,pre:"",un:" m",w:"Une trentaine de mètres. Au-delà, les lignes se séparent et des espaces s'ouvrent."},
{i:"k270_12",u:270,t:"story",d:.4,q:"Que vois-tu sur la vidéo ?",ctx:"Le 10 du Scarpe reçoit sans cesse le ballon libre entre la défense et le milieu du Racing.",sc:[{who:"Élodie Marchal",txt:"Pourquoi il est toujours seul, celui-là ?"}],o:["Nos lignes sont trop éloignées, le bloc est étiré","Il est hors-jeu à chaque fois","Il joue plus vite que tous nos milieux","L'arbitre le protège de nos tacles"],a:0,w:"Un bloc étiré ouvre des espaces entre les lignes. C'est la zone préférée des meneurs."},
{i:"k270_13",u:270,t:"fill",d:.45,nw:"Le coulissement",q:"Quand le ballon change de côté, tout le bloc ___ vers lui.",o:["coulisse","recule","s'écarte","s'arrête"],a:0,w:"Coulisser : glisser latéralement ensemble, comme un accordéon."},
{i:"k270_14",u:270,t:"tiles",d:.4,q:"Reconstitue l'image mémo du bloc.",a:["Le","bloc","est","un","accordéon"],dd:["mur","piano","ballon"],w:"Il se resserre vers le ballon et se déplace en entier."},
{i:"k270_15",u:270,t:"tf",d:.45,q:"En coulissant, un bloc accepte de laisser libre le côté opposé au ballon.",a:true,w:"On défend la zone du ballon. Le côté opposé est loin : il faudra un long changement de jeu pour l'atteindre."},
{i:"k270_16",u:270,t:"story",d:.45,q:"Que vois-tu ?",ctx:"Le ballon passe à droite. Tous les joueurs du Racing glissent, sauf Kylian qui reste à gauche. Un trou s'ouvre dans l'axe.",sc:[{who:"Élodie Marchal",txt:"Qu'est-ce qui ne va pas ?"}],o:["Kylian ne coulisse pas : il casse la compacité","Tout le bloc aurait dû reculer de dix mètres","Le Racing aurait dû presser le gardien","Rien, c'est la bonne position"],a:0,w:"Un joueur qui ne coulisse pas crée un trou, comme une touche cassée dans l'accordéon."},
{i:"k270_17",u:270,t:"match",d:.45,nw:"Zone, individuelle, mixte",q:"Associe chaque défense à son principe.",p:[["Zone","Défendre un espace"],["Individuelle","Suivre un adversaire partout"],["Mixte","Combiner les deux"],["Homme à homme","Autre nom de l'individuelle"]],w:"Défendre un espace, suivre un adversaire, ou combiner les deux."},
{i:"k270_18",u:270,t:"mcq",d:.45,q:"En défense de zone, que fait un défenseur quand un attaquant entre dans son espace ?",o:["Il le prend en charge","Il le suit jusqu'au vestiaire","Il l'ignore totalement","Il appelle l'arbitre"],a:0,w:"Chacun défend son espace et prend l'adversaire qui y entre, puis le passe au voisin s'il en sort."},
{i:"k270_19",u:270,t:"sort",d:.5,q:"Zone ou individuelle ?",bins:["Zone","Individuelle"],it:[["Lucas garde l'axe gauche de la surface",0],["Nabil suit leur 10 partout, même au milieu",1],["Chaque milieu couvre un couloir",0],["Le 6 colle à leur meneur tout le match",1]],w:"Un espace à tenir : zone. Un joueur à suivre : individuelle."},
{i:"k270_20",u:270,t:"tf",d:.5,q:"La défense mixte est interdite sur les coups de pied arrêtés.",a:false,w:"Faux : elle y est même fréquente, avec des postes fixes et du marquage individuel sur les meilleurs joueurs de tête."},
{i:"k270_21",u:270,t:"story",d:.5,nw:"Orienter vers les côtés",q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"Pourquoi nos milieux laissent leur latéral recevoir tranquille sur le côté ?"}],o:["On l'oriente vers la ligne de touche pour l'enfermer","Nos milieux sont trop lents pour le suivre pendant tout le match","C'est une erreur, il fallait tout fermer","Pour gagner du temps avant la mi-temps"],a:0,w:"Fermer l'axe, laisser le couloir, puis presser : la ligne de touche sert de défenseur supplémentaire."},
{i:"k270_22",u:270,t:"fill",d:.5,q:"Sur le côté, la ligne de ___ joue le rôle d'un défenseur supplémentaire.",o:["touche","but","médiane","surface"],a:0,w:"L'adversaire ne peut pas s'échapper au-delà de la touche : il a moins de solutions."},
{i:"k270_23",u:270,t:"multi",d:.5,q:"Quelles sont les qualités d'un bon bloc défensif ?",o:["Compact","Coulissant vers le ballon","Orientant vers les côtés","Étiré sur tout le terrain","Chaque joueur défend seul"],a:[0,1,2],w:"Compacité, coulissement, orientation : un bloc défend ensemble."},
{i:"k270_24",u:270,t:"story",d:.55,q:"Rappel du module 4 : quel bloc forme le 4-4-2 du Scarpe ?",sc:[{who:"Élodie Marchal",txt:"Deux lignes de quatre à 30 m de leur but, deux attaquants au rond central."}],o:["Un bloc moyen-bas compact","Un bloc haut","Un bloc individuel, chacun sur son joueur","Un bloc éclaté"],a:0,w:"Deux lignes de quatre compactes, basses et moyennes : la force du 4-4-2."},
{i:"k270_25",u:270,t:"order",d:.5,q:"Remets dans l'ordre le plan défensif du Scarpe.",it:["Se replacer en bloc moyen","Fermer l'axe","Orienter le Racing vers un côté","Coulisser vers le ballon","Presser dans le couloir"],w:"Replacement, fermeture, orientation, coulissement, pression."},
{i:"k270_26",u:270,t:"mcq",d:.55,q:"Rappel du module 5 : dans quelle phase le bloc est-il replacé et stable ?",o:["La défense organisée","La transition défensive","La transition offensive","La possession organisée"],a:0,w:"Défense organisée : le bloc est en place. En transition défensive, il est encore étiré."},
{i:"k270_27",u:270,t:"story",d:.55,q:"Rappel du module 2 : que se passe-t-il ?",ctx:"Le Racing joue avec une ligne haute. Lucas fait monter la défense d'un pas juste avant une passe adverse, l'attaquant reste derrière.",sc:[{who:"Mehdi",txt:"Il a fait quoi, là, Lucas ?"}],o:["Il a mis l'attaquant hors-jeu en montant la ligne","Il a commis une faute d'obstruction","Il a oublié de coulisser","Il a demandé la VAR"],a:0,w:"Monter la ligne au bon moment place l'attaquant devant l'avant-dernier défenseur à l'instant de la passe."},
{i:"k270_28",u:270,t:"slider",d:.55,q:"Combien de lignes forme un 4-4-2 hors possession, gardien exclu ?",min:1,max:5,step:1,a:3,tol:0,pre:"",un:" lignes",w:"Défense, milieu, attaque : trois lignes à garder proches."},
{i:"k270_29",u:270,t:"tf",d:.55,q:"Un bloc bas laisse beaucoup d'espace dans le dos de sa défense.",a:false,w:"C'est le bloc haut qui laisse de l'espace derrière. Le bloc bas n'en laisse presque pas."},
{i:"k270_30",u:270,t:"story",d:.6,q:"Que proposes-tu à Samir à la pause ?",ctx:"Le Racing, en bloc haut, a pris deux occasions sur des longs ballons dans son dos.",sc:[{who:"Samir Benhaddou",txt:"On change quoi ?"}],o:["Descendre le bloc d'un cran pour fermer le dos","Monter encore plus haut pour les étouffer sans se poser de question","Passer à la défense individuelle partout","Retirer un défenseur pour un attaquant"],a:0,w:"Le risque du bloc haut s'est réalisé : on réduit l'espace derrière. C'est un ajustement de bloc à la pause."},
{i:"k270_31",u:270,t:"mcq",d:.6,q:"Dans la grille d'Élodie, quelle est la première question ?",o:["Où se situe le bloc de chaque équipe ?","Qui a marqué le premier but ?","Combien de corners chaque équipe a-t-elle tirés ?","Quel joueur a le plus couru ?"],a:0,w:"La première question de la grille d'observation : la hauteur du bloc des deux équipes."},
{i:"k270_32",u:270,t:"story",d:.6,q:"Synthèse : Élodie veut ton rapport sur le bloc du Scarpe.",sc:[{who:"Élodie Marchal",txt:"Une phrase."}],o:["« Bloc moyen compact, il coulisse et nous oriente à gauche »","« Aucun bloc, ils défendent chacun pour soi »","« Bloc très haut, dos grand ouvert à chaque action de façon systématique »","« Ils défendent à onze dans les cinq mètres »"],a:0,w:"Hauteur, compacité, coulissement, orientation : les quatre éléments du rapport sur un bloc."}
