/*UNIT*/
{id:271,c:"FOOT",n:"Module 7",t:"Le pressing : qui presse qui, et quand déclencher",col:"--green",ic:"💨",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Distinguer pressing <b>individuel</b> et pressing <b>collectif</b>.</li>
<li>Reconnaître les <b>pressing triggers</b>, les signaux qui déclenchent la pression.</li>
<li>Expliquer la <b>couverture des lignes de passe</b>.</li>
<li>Lire le <b>PPDA</b>, la statistique qui mesure l'intensité du pressing.</li></ul>
<h3>Le déclic</h3>
<div class="gstory">20e minute. Le défenseur central du Scarpe fait une passe latérale molle vers son latéral, collé à la ligne de touche. D'un coup, trois joueurs du Racing foncent en même temps : Kylian sur le latéral, Rayan sur le milieu le plus proche, l'avant-centre dans la ligne de passe vers le central. Ballon récupéré, tir. Mehdi applaudit : « Ils ont couru plus vite ! » Élodie : « Non. Ils ont couru <b>ensemble</b>, au bon signal. »</div>
<h3>Presser, c'est quoi ?</h3>
<p><b>Presser</b>, c'est réduire le temps et l'espace du porteur du ballon pour le forcer à l'erreur ou récupérer. Deux grandes façons de faire :</p>
<table><tr><th>Pressing</th><th>Principe</th><th>Risque</th></tr>
<tr><td><b>Individuel</b> (homme à homme)</td><td>Chaque joueur prend un adversaire direct</td><td>Un duel perdu, et un adversaire se retrouve libre</td></tr>
<tr><td><b>Collectif</b> (de zone)</td><td>Le bloc se déplace ensemble, ferme les espaces et les lignes de passe</td><td>Un temps de retard, et la passe traverse</td></tr></table>
<div class="gmnemo">Le pressing, c'est une <b>meute</b>, pas un chasseur seul. Un joueur qui presse seul se fait éliminer d'une passe. Trois joueurs qui pressent ensemble ferment le piège.</div>
<h3>Les pressing triggers</h3>
<p>Un <b>pressing trigger</b> est un <b>signal</b> qui déclenche la pression collective. Les plus courants :</p>
<ul><li>une <b>passe latérale</b> ou en retrait (l'adversaire ne progresse pas),</li>
<li>un <b>mauvais contrôle</b> (le ballon s'éloigne du pied),</li>
<li>un joueur qui reçoit <b>dos au jeu</b>,</li>
<li>une passe vers un joueur <b>près de la ligne de touche</b> (il a moins de solutions),</li>
<li>une passe <b>lente</b> ou en l'air, qui laisse le temps d'arriver.</li></ul>
<div class="gmnemo">Les triggers en quatre mots : <b>« Latéral, Lent, Loupé, Ligne »</b>. Les quatre L : passe latérale, passe lente, contrôle loupé, joueur près de la ligne de touche. Plus le dos au jeu.</div>
<h3>Couvrir les lignes de passe</h3>
<p>Un bon presseur ne court pas droit sur le porteur. Il arrive en <b>courbe</b>, en se plaçant entre le porteur et son partenaire : son corps « cache » la passe. On appelle ça couvrir la ligne de passe, ou <b>l'ombre</b> du presseur. Le porteur n'a plus qu'une solution, souvent vers la ligne de touche.</p>
<h3>Le PPDA</h3>
<p>Le <b>PPDA</b> (passes per defensive action) mesure l'intensité du pressing : c'est le nombre de <b>passes</b> que l'équipe laisse faire à l'adversaire avant une <b>action défensive</b> (tacle, interception, faute), dans les 60 % du terrain les plus proches du but adverse.</p>
<ul><li><b>PPDA bas</b> : peu de passes tolérées, pressing <b>intense</b>.</li>
<li><b>PPDA élevé</b> : beaucoup de passes tolérées, équipe <b>attentiste</b>.</li>
<li>Repère approximatif : autour de 8 à 10 pour une équipe très pressante, au-delà de 15 pour un bloc qui attend.</li></ul>
<div class="formula">PPDA = passes adverses / actions défensives (dans les 60 % offensifs du terrain)
Exemple : 240 passes adverses pour 30 actions défensives : PPDA = 8</div>
<div class="gtrap">Ta fiche demande « qui presse qui : individuel ou collectif » et cite le pressing trigger. Le PPDA n'y figure pas. C'est pourtant la statistique qui chiffre ce que tu observes. Attention : un PPDA bas ne dit pas si le pressing <b>réussit</b>, seulement s'il est <b>intense</b>.</div>
<h3>Ce que tu dois retenir</h3>
<ul><li>Individuel = un adversaire chacun. Collectif = le bloc ensemble.</li>
<li>Triggers : Latéral, Lent, Loupé, Ligne, et dos au jeu.</li>
<li>Presser en courbe pour couvrir la ligne de passe.</li>
<li>PPDA bas = pressing intense.</li></ul>`},
/*EXOS*/
{i:"k271_01",u:271,t:"mcq",d:.2,nw:"Le pressing",q:"Quel est le but du pressing ?",o:["Réduire le temps et l'espace du porteur","Laisser l'adversaire construire en paix","Reculer pour protéger sa surface","Faire des fautes pour casser le jeu"],a:0,w:"Presser, c'est forcer l'erreur ou récupérer en réduisant temps et espace."},
{i:"k271_02",u:271,t:"story",d:.25,q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"On a récupéré parce que nos gars ont couru plus vite !"}],o:["Non : ils ont couru ensemble, au bon signal","Oui, la vitesse suffit toujours pour récupérer","Non, c'est l'arbitre qui a tout déclenché","Oui, et le Scarpe s'est arrêté de jouer"],a:0,w:"Le pressing est une meute : c'est la coordination, pas la vitesse seule, qui récupère."},
{i:"k271_03",u:271,t:"tiles",d:.3,q:"Reconstitue l'image mémo du pressing.",a:["Une","meute,","pas","un","chasseur","seul"],dd:["loup,","troupeau","mur"],w:"Presser seul, c'est se faire éliminer d'une passe."},
{i:"k271_04",u:271,t:"match",d:.3,nw:"Pressing individuel et collectif",q:"Associe chaque pressing à sa définition.",p:[["Individuel","Chacun prend un adversaire direct"],["Collectif","Le bloc se déplace ensemble"],["Risque de l'individuel","Un duel perdu libère un adversaire"],["Risque du collectif","Un temps de retard et la passe passe"]],w:"Homme à homme ou zone : deux logiques, deux risques."},
{i:"k271_05",u:271,t:"sort",d:.35,q:"Pressing individuel ou collectif ?",bins:["Individuel","Collectif"],it:[["Chaque attaquant colle un défenseur précis",0],["Le bloc glisse ensemble et ferme les passes",1],["Rayan suit leur 6 partout",0],["Trois joueurs ferment une zone autour du ballon",1]],w:"Un adversaire attitré : individuel. Une zone fermée ensemble : collectif."},
{i:"k271_06",u:271,t:"tf",d:.35,q:"Dans un pressing individuel, un seul duel perdu peut libérer un adversaire.",a:true,w:"Chacun a son joueur : si l'un est dribblé, personne ne couvre derrière."},
{i:"k271_07",u:271,t:"fill",d:.35,q:"Dans la grille d'Élodie, on note qui presse qui : individuel ou ___.",o:["collectif","aérien","latéral","offensif"],a:0,w:"Deuxième question de la grille : pressing individuel (homme à homme) ou collectif (par zone)."},
{i:"k271_08",u:271,t:"multi",d:.35,nw:"Les pressing triggers",q:"Quels signaux déclenchent souvent le pressing ?",o:["Une passe latérale ou en retrait","Un mauvais contrôle","Un joueur dos au jeu","Une passe rapide et verticale","Un porteur face au jeu et libre"],a:[0,1,2],w:"Latéral, Lent, Loupé, Ligne, dos au jeu. Une passe rapide vers l'avant, au contraire, ne se presse pas."},
{i:"k271_09",u:271,t:"tiles",d:.4,q:"Reconstitue les quatre L des triggers.",a:["Latéral,","Lent,","Loupé,","Ligne"],dd:["Long,","Libre,","Loin,"],w:"Passe latérale, passe lente, contrôle loupé, joueur près de la ligne."},
{i:"k271_10",u:271,t:"story",d:.4,q:"Que réponds-tu à Élodie ?",sc:[{who:"Élodie Marchal",txt:"Pourquoi on déclenche quand ils passent à leur latéral collé à la touche ?"}],o:["La touche lui retire des solutions de passe","Parce que les latéraux sont toujours plus lents","Parce que l'arbitre est plus loin","Parce qu'un latéral ne peut pas faire de passe"],a:0,w:"Près de la ligne, le porteur a moins d'options : le piège se referme plus facilement."},
{i:"k271_11",u:271,t:"sort",d:.4,q:"Faut-il déclencher le pressing ?",bins:["Trigger : on presse","Pas de trigger : on attend"],it:[["Leur central fait une passe latérale molle",0],["Leur 6 reçoit face au jeu, libre",1],["Leur latéral rate son contrôle près de la touche",0],["Leur 10 reçoit dos au but",0],["Une passe rapide et verticale traverse le bloc",1]],w:"Face au jeu et libre, ou passe rapide : trop tard. Latéral, lent, loupé, ligne ou dos au jeu : on y va."},
{i:"k271_12",u:271,t:"tf",d:.4,q:"Un joueur qui reçoit face au jeu, sans pression, est un bon moment pour déclencher le pressing.",a:false,w:"Face au jeu et libre, il voit tout : on risque d'être éliminé. On attend un signal plus favorable."},
{i:"k271_13",u:271,t:"mcq",d:.45,nw:"Couvrir les lignes de passe",q:"Pourquoi un presseur arrive-t-il en courbe plutôt que tout droit ?",o:["Pour couvrir une ligne de passe","Pour courir moins vite","Pour éviter un carton","Pour se mettre en jeu"],a:0,w:"En courbe, son corps cache le partenaire : le porteur perd une solution. Couvrir la ligne de passe ferme une solution au porteur."},
{i:"k271_14",u:271,t:"fill",d:.45,q:"Le presseur qui cache un partenaire avec son corps couvre une ligne de ___.",o:["passe","touche","but","hors-jeu"],a:0,w:"On parle aussi de l'ombre du presseur : son corps cache le partenaire."},
{i:"k271_15",u:271,t:"story",d:.45,q:"Que corriges-tu chez l'avant-centre ?",ctx:"Sur la vidéo, l'avant-centre du Racing fonce tout droit sur le central adverse, qui passe tranquillement à son partenaire juste à côté.",sc:[{who:"Samir Benhaddou",txt:"Il court, pourtant. Qu'est-ce qui cloche ?"}],o:["Il court droit : il doit arriver en courbe","Il court trop lentement, il faut sprinter plus","Il devrait tacler dès qu'il arrive","Il devrait rester en pointe sans presser"],a:0,w:"En courbe, il aurait caché le partenaire et forcé une passe vers la touche."},
{i:"k271_16",u:271,t:"multi",d:.5,q:"Qu'est-ce qui fait un pressing collectif efficace ?",o:["Un signal commun","Des joueurs qui partent ensemble","Des lignes de passe couvertes","Un seul joueur qui court partout","Des départs à des moments différents"],a:[0,1,2],w:"Un trigger, un départ commun, des passes fermées : la meute."},
{i:"k271_17",u:271,t:"mcq",d:.45,nw:"Le PPDA",q:"Que mesure le PPDA ?",o:["L'intensité du pressing","Le nombre de buts attendus","La possession de balle","La distance parcourue"],a:0,w:"Passes adverses tolérées par action défensive, dans les 60 % offensifs du terrain."},
{i:"k271_18",u:271,t:"tf",d:.5,q:"Un PPDA élevé signifie un pressing intense.",a:false,w:"Faux : un PPDA élevé veut dire beaucoup de passes laissées à l'adversaire, donc une équipe attentiste. Pressing intense = PPDA bas."},
{i:"k271_19",u:271,t:"num",d:.5,q:"L'adversaire fait 240 passes dans la zone concernée et le Racing réalise 30 actions défensives. Quel est le PPDA du Racing ?",a:8,tol:0,un:"",h:"Passes / actions",w:"240 / 30 = 8 : peu de passes tolérées, pressing intense."},
{i:"k271_20",u:271,t:"num",d:.5,q:"Le Scarpe laisse 300 passes au Racing pour 18 actions défensives. PPDA arrondi à l'unité ?",a:17,tol:0,un:"",h:"300 / 18",w:"300 / 18 ≈ 16,7, soit 17 : un bloc qui attend, cohérent avec leur bloc moyen-bas (module 6)."},
{i:"k271_21",u:271,t:"sort",d:.5,q:"Pressing intense ou équipe attentiste ?",bins:["Pressing intense","Équipe attentiste"],it:[["PPDA de 8",0],["PPDA de 18",1],["PPDA de 9",0],["PPDA de 22",1]],w:"Repère : 8 à 10, très pressant. Au-delà de 15, attentiste."},
{i:"k271_22",u:271,t:"story",d:.55,q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"On a un PPDA de 7, donc notre pressing a marché !"}],o:["Il est intense, ça ne dit pas s'il a réussi","Oui, un PPDA bas prouve toujours la réussite","Non, 7 veut dire qu'on n'a jamais pressé","Oui, et on a donc forcément gagné le match"],a:0,w:"Le PPDA mesure l'intensité, pas l'efficacité. Il faut regarder aussi les récupérations et les occasions concédées."},
{i:"k271_23",u:271,t:"fill",d:.5,q:"Le PPDA se calcule dans les ___ % du terrain les plus proches du but adverse.",o:["60","40","100","25"],a:0,w:"On compte les passes adverses dans les 60 % du terrain proches du but adverse, là où l'équipe cherche à presser."},
{i:"k271_24",u:271,t:"order",d:.5,q:"Remets dans l'ordre une séquence de pressing réussie.",it:["Le bloc attend en place","Un trigger apparaît : passe latérale lente","Trois joueurs partent ensemble","Les presseurs couvrent les lignes de passe","Récupération du ballon"],w:"Attendre, repérer le signal, partir en meute, fermer, récupérer. Chaque presseur couvre une ligne de passe en arrivant."},
{i:"k271_25",u:271,t:"story",d:.55,q:"Rappel du module 6 : que conseilles-tu ?",ctx:"Le Racing presse haut, mais chaque fois qu'un pressing échoue, un long ballon trouve l'attaquant rapide du Scarpe dans le dos.",sc:[{who:"Samir Benhaddou",txt:"On arrête de presser ?"}],o:["Presser sur trigger seulement, et couvrir le dos","Presser encore plus, sans aucun signal","Arrêter tout pressing et jouer très bas","Mettre un joueur de plus en attaque"],a:0,w:"Le risque d'un bloc haut est l'espace dans le dos. On presse au bon signal, et un défenseur couvre la profondeur."},
{i:"k271_26",u:271,t:"mcq",d:.55,q:"Rappel du module 5 : quand le pressing récupère haut, dans quelle phase entre le Racing ?",o:["La transition offensive","La défense organisée","La transition défensive","La possession organisée"],a:0,w:"Récupérer, puis frapper en moins de 5 secondes : transition offensive, près du but adverse."},
{i:"k271_27",u:271,t:"tf",d:.55,q:"Le pressing individuel impose que chaque joueur suive un adversaire précis.",a:true,w:"Homme à homme : un adversaire attitré par joueur."},
{i:"k271_28",u:271,t:"match",d:.55,q:"Associe chaque signal au L correspondant.",p:[["Passe vers le côté","Latéral"],["Passe qui roule doucement","Lent"],["Ballon qui s'échappe du pied","Loupé"],["Latéral collé à la touche","Ligne"]],w:"Latéral, Lent, Loupé, Ligne : les quatre L du pressing."},
{i:"k271_29",u:271,t:"slider",d:.6,q:"Repère : en dessous de quelle valeur de PPDA une équipe presse-t-elle très fort ?",min:4,max:20,step:1,a:10,tol:1,pre:"",un:"",w:"Autour de 8 à 10 : pressing très intense. C'est un repère approximatif, qui varie selon les championnats."},
{i:"k271_30",u:271,t:"story",d:.6,q:"Rappel du module 3 : qui doit presser leur gardien relanceur ?",sc:[{who:"Élodie Marchal",txt:"Leur gardien relance au pied, avec les deux centraux écartés."}],o:["L'avant-centre en courbe, en cachant un central","Le gardien du Racing, qui monte presser","Personne, un gardien ne se presse jamais","Nos deux défenseurs centraux ensemble"],a:0,w:"Le gardien relanceur est un joueur de plus à la relance. L'avant-centre le presse en courbe pour fermer un côté."},
{i:"k271_31",u:271,t:"tf",d:.6,q:"Un joueur qui presse seul, sans ses coéquipiers, se fait souvent éliminer d'une simple passe.",a:true,w:"Le porteur joue à côté du presseur isolé. D'où la meute."},
{i:"k271_32",u:271,t:"story",d:.6,q:"Synthèse : Élodie te demande ton rapport sur le pressing du Racing.",sc:[{who:"Élodie Marchal",txt:"Une phrase."}],o:["« Collectif, sur passe latérale, en courbe, PPDA de 8 »","« Individuel, sans signal, droit devant, PPDA de 20 »","« Aucun pressing, on attend tout le match dans la surface »","« Un seul joueur presse, les autres regardent »"],a:0,w:"Type, trigger, technique, chiffre : le rapport complet sur un pressing."}
