/*UNIT*/
{id:272,c:"FOOT",n:"Module 8",t:"La construction : sortir le ballon grâce au joueur libre",col:"--green",ic:"🏗️",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Définir le <b>build-up</b>, la sortie de balle depuis l'arrière.</li>
<li>Calculer un <b>surnombre</b> et trouver le <b>joueur libre</b>.</li>
<li>Expliquer pourquoi <b>qui décroche libère quelqu'un d'autre</b>.</li>
<li>Reconnaître le <b>troisième homme</b>.</li>
<li>Choisir entre relance <b>courte</b> et jeu <b>long</b>.</li></ul>
<h3>Tom a le ballon</h3>
<div class="gstory">Coup de pied de but pour le Racing. Tom pose le ballon. Les deux attaquants du Scarpe montent presser les deux centraux, Lucas et son partenaire, qui s'écartent jusqu'aux angles de la surface. Mehdi s'étrangle : « Mais dégage, Tom ! » Tom glisse le ballon à Lucas, qui le remet aussitôt au 6 descendu entre les deux centraux. Trois joueurs contre deux presseurs : le 6 est libre, il se retourne. Élodie : « Tu vois ? Trois contre deux, il y a toujours un homme libre. »</div>
<h3>Le build-up</h3>
<p>Le <b>build-up</b> est la <b>construction</b> depuis le gardien et les défenseurs. Objectif : sortir le ballon proprement de sa moitié pour attaquer dans de bonnes conditions, plutôt que de le rendre par un long dégagement.</p>
<h3>Le surnombre</h3>
<p>Le <b>surnombre</b>, c'est avoir <b>un joueur de plus</b> que les presseurs adverses dans une zone. En 3 contre 2, il y a <b>toujours un homme libre</b> : c'est lui qu'il faut trouver.</p>
<svg class='gsvg' viewBox='0 0 220 158' xmlns='http://www.w3.org/2000/svg' role='img' style='font-family:inherit'><rect x='10' y='6' width='200' height='130' rx='3' fill='#1E6B3A'/><line x1='40' y1='40' x2='54' y2='71' stroke='#FFD23F' stroke-width='2' stroke-dasharray='4 3'/><rect x='10' y='6' width='200' height='130' rx='3' fill='none' stroke='#FFFFFF' stroke-width='1.4'/><line x1='110' y1='6' x2='110' y2='136' stroke='#FFFFFF' stroke-width='1.2'/><circle cx='110' cy='71' r='15' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><rect x='10' y='37' width='28' height='68' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><rect x='182' y='37' width='28' height='68' fill='none' stroke='#FFFFFF' stroke-width='1.2'/><circle cx='20' cy='71' r='6.5' fill='#FFD23F' stroke='#1C1C48' stroke-width='1'/><text x='20' y='73.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#1C1C48'>G</text><circle cx='40' cy='40' r='6.5' fill='#FFD23F' stroke='#1C1C48' stroke-width='1'/><text x='40' y='42.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#1C1C48'>4</text><circle cx='40' cy='102' r='6.5' fill='#FFD23F' stroke='#1C1C48' stroke-width='1'/><text x='40' y='104.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#1C1C48'>5</text><circle cx='54' cy='71' r='6.5' fill='#FFD23F' stroke='#1C1C48' stroke-width='1'/><text x='54' y='73.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#1C1C48'>6</text><circle cx='58' cy='50' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='58' y='52.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>9</text><circle cx='58' cy='92' r='6.5' fill='#E5484D' stroke='#1C1C48' stroke-width='1'/><text x='58' y='94.3' font-size='6.5' font-weight='800' text-anchor='middle' fill='#FFFFFF'>10</text><text x='110' y='151' font-size='9' fill='var(--txt)' text-anchor='middle' font-weight='700'>3 contre 2 à la relance : le 6 est libre</text></svg>
<ul><li>Le gardien peut compter comme un joueur de la relance : c'est l'intérêt d'un <b>gardien relanceur</b> (module 3).</li>
<li>Si l'adversaire presse à trois, on cherche un quatrième joueur : un latéral qui descend, un 6 qui décroche.</li></ul>
<div class="gmnemo">La règle d'or de la relance : <b>« Un de plus qu'eux »</b>. Compte les presseurs, ajoute un : c'est le nombre de joueurs à placer pour avoir un homme libre.</div>
<h3>Le joueur structurellement libre</h3>
<p>La grille d'Élodie demande : <b>quel joueur est structurellement libre à la relance ?</b> « Structurellement » veut dire : libre grâce au <b>placement</b> des deux équipes, et pas par hasard. Si le Scarpe presse avec deux attaquants, le Racing, avec deux centraux et un 6, a toujours un joueur libre. Repérer lequel, c'est comprendre le plan de relance.</p>
<h3>Qui décroche libère quelqu'un d'autre</h3>
<ul><li>Quand un joueur <b>décroche</b> (revient vers son but pour recevoir), il attire souvent un adversaire.</li>
<li>L'adversaire qui le suit quitte sa zone : un <b>espace</b> s'ouvre, qu'un autre joueur peut attaquer.</li>
<li>Si personne ne le suit, il reçoit <b>libre</b>. Dans les deux cas, le décrochage crée un avantage.</li></ul>
<div class="gmnemo">Le réflexe numéro 3 de ta fiche : <b>« Qui décroche libère quelqu'un d'autre »</b>. Quand un joueur vient chercher le ballon, ne le regarde pas lui : regarde l'espace qu'il vient de vider.</div>
<h3>Le troisième homme</h3>
<p>Le <b>jeu à trois</b> : A passe à B, qui remet tout de suite à C, placé pour avancer. Le ballon atteint C, qu'A ne pouvait pas trouver directement. C'est l'arme favorite contre un pressing individuel.</p>
<h3>Court ou long ?</h3>
<table><tr><th>Relance</th><th>Avantage</th><th>Risque</th></tr>
<tr><td><b>Courte</b></td><td>Garder le ballon, attirer l'adversaire, trouver l'espace derrière son pressing</td><td>Une perte près de son but</td></tr>
<tr><td><b>Longue</b></td><td>Aucun risque près de son but, sauter le pressing</td><td>Ballon souvent perdu, second ballon à gagner (module 11)</td></tr></table>
<div class="gtrap">Ta fiche cite le build-up et le surnombre 3 contre 2 dans son lexique. Ajoute la limite : relancer court n'est une bonne idée que si l'on a le <b>surnombre</b>. Sans homme libre, la relance courte devient un cadeau.</div>
<h3>Ce que tu dois retenir</h3>
<ul><li>Build-up : sortir le ballon depuis l'arrière.</li>
<li>Un de plus qu'eux : en 3 contre 2, un homme est toujours libre.</li>
<li>Qui décroche libère quelqu'un d'autre.</li>
<li>Troisième homme contre le pressing. Court si surnombre, long sinon.</li></ul>`},
/*EXOS*/
{i:"k272_01",u:272,t:"fill",d:.2,nw:"Le build-up",q:"La phase de construction depuis le gardien et les défenseurs s'appelle le ___.",o:["build-up","pressing","overload","gegenpressing"],a:0,w:"Build-up : sortir le ballon proprement depuis l'arrière."},
{i:"k272_02",u:272,t:"story",d:.25,q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"Dégage, Tom ! Pourquoi il fait des passes courtes devant son but ?"}],o:["Avec un homme libre, relancer court est payant","Il fait ça pour faire perdre du temps à l'arbitre","Il a peur de rater son dégagement","Parce que le long ballon est interdit"],a:0,w:"Trois contre deux : un homme est toujours libre. Relancer court garde le ballon et attire le pressing."},
{i:"k272_03",u:272,t:"mcq",d:.3,nw:"Le surnombre",q:"Qu'est-ce qu'un surnombre de 3 contre 2 ?",o:["Un joueur de plus que les presseurs","Trois buts contre deux","Trois défenseurs pour deux attaquants","Trois passes pour deux duels"],a:0,w:"Un de plus qu'eux : il y a toujours un homme libre."},
{i:"k272_04",u:272,t:"tiles",d:.3,q:"Reconstitue la règle d'or de la relance.",a:["Un","de","plus","qu'eux"],dd:["moins","deux","autant"],w:"Compte les presseurs, ajoute un : tu obtiens le nombre de relanceurs."},
{i:"k272_05",u:272,t:"num",d:.3,q:"Le Scarpe presse la relance avec 3 joueurs. Combien de joueurs le Racing doit-il placer à la relance pour avoir un homme libre ?",a:4,tol:0,un:" joueurs",h:"Un de plus qu'eux",w:"3 + 1 = 4 : par exemple le gardien, deux centraux et le 6."},
{i:"k272_06",u:272,t:"tf",d:.35,q:"Le gardien peut compter comme un joueur dans le surnombre à la relance.",a:true,w:"C'est tout l'intérêt du gardien relanceur : un joueur de plus au départ de l'action."},
{i:"k272_07",u:272,t:"sort",d:.35,q:"Y a-t-il un homme libre à la relance ?",bins:["Oui, surnombre","Non, égalité"],it:[["Gardien, 2 centraux contre 2 attaquants",0],["2 centraux et le 6 contre 3 presseurs",1],["2 centraux, 6 et latéral contre 3 presseurs",0],["2 centraux seuls contre 2 attaquants",1]],w:"Un de plus qu'eux : sinon, égalité, et chaque relanceur est pris."},
{i:"k272_08",u:272,t:"story",d:.35,nw:"Le joueur structurellement libre",q:"Que réponds-tu à Élodie ?",sc:[{who:"Élodie Marchal",txt:"Leurs deux attaquants pressent Lucas et l'autre central. Qui est structurellement libre chez nous ?"}],o:["Le 6, placé entre les deux centraux","Lucas, il suffit qu'il dribble","Le gardien, s'il garde le ballon 20 secondes","L'avant-centre, loin devant"],a:0,w:"Deux presseurs, trois relanceurs : le 6 est libre grâce au placement, pas par chance."},
{i:"k272_09",u:272,t:"multi",d:.4,q:"Que veut dire « structurellement libre » ?",o:["Libre grâce au placement des équipes","Libre de façon prévisible","Libre à chaque relance si rien ne change","Libre par pur hasard","Libre parce que l'arbitre protège"],a:[0,1,2],w:"Ce n'est pas un hasard : c'est une conséquence du plan de relance face au plan de pressing."},
{i:"k272_10",u:272,t:"mcq",d:.4,q:"Le Scarpe ajoute un troisième presseur sur le 6. Que doit faire le Racing ?",o:["Trouver un quatrième relanceur","Continuer à trois, sans rien changer","Dégager systématiquement","Jouer à dix contre onze"],a:0,w:"Un de plus qu'eux : un latéral descend, ou le gardien participe davantage."},
{i:"k272_11",u:272,t:"story",d:.4,nw:"Qui décroche libère quelqu'un",q:"Que regardes-tu ?",ctx:"Rayan, le 10 du Racing, décroche au rond central. Le 6 du Scarpe le suit.",sc:[{who:"Mehdi",txt:"Rayan recule, il ne sert à rien là-bas !"}],o:["L'espace vidé par leur 6, entre leurs lignes","Rayan lui-même, qui va sûrement tenter un long dribble","Le banc, pour un changement","Le gardien, qui va tirer long"],a:0,w:"Qui décroche libère quelqu'un d'autre : le 6 adverse a quitté sa zone, un coéquipier peut l'attaquer."},
{i:"k272_12",u:272,t:"tiles",d:.4,q:"Reconstitue le réflexe numéro 3 de ta fiche.",a:["Qui","décroche","libère","quelqu'un","d'autre"],dd:["perd","le","ballon"],w:"Ne regarde pas le joueur qui décroche, regarde l'espace qu'il vide."},
{i:"k272_13",u:272,t:"tf",d:.4,q:"Si personne ne suit un joueur qui décroche, son décrochage ne sert à rien.",a:false,w:"Faux : s'il n'est pas suivi, il reçoit libre. Suivi ou non, le décrochage crée un avantage."},
{i:"k272_14",u:272,t:"sort",d:.45,q:"Rayan décroche. Quelle conséquence ?",bins:["Un espace s'ouvre ailleurs","Rayan reçoit libre"],it:[["Leur 6 le suit au rond central",0],["Personne ne le suit",1],["Leur central sort de sa ligne pour le suivre",0],["Leurs milieux restent en place, sans le marquer",1]],w:"Suivi : espace libéré. Pas suivi : joueur libre."},
{i:"k272_15",u:272,t:"fill",d:.45,q:"Quand un joueur ___, il revient vers son propre but pour recevoir le ballon.",o:["décroche","plonge","coulisse","presse"],a:0,w:"Décrocher : revenir chercher le ballon plus bas."},
{i:"k272_16",u:272,t:"match",d:.45,q:"Associe chaque mot à sa définition.",p:[["Build-up","Construction depuis l'arrière"],["Surnombre","Un joueur de plus que l'adversaire"],["Décrocher","Revenir chercher le ballon"],["Joueur structurellement libre","Libre grâce au placement"]],w:"Le vocabulaire de la relance, à connaître pour lire une sortie de balle."},
{i:"k272_17",u:272,t:"mcq",d:.45,nw:"Le troisième homme",q:"Qu'est-ce que le jeu à trois, ou troisième homme ?",o:["A passe à B, qui remet à C","A dribble B puis C","A tire, B et C suivent","A, B et C pressent ensemble"],a:0,w:"Le ballon atteint C, qu'A ne pouvait pas trouver directement."},
{i:"k272_18",u:272,t:"story",d:.5,q:"Que conseilles-tu à Samir ?",ctx:"Le Scarpe presse en individuel : chaque milieu du Racing est collé par un adversaire.",sc:[{who:"Samir Benhaddou",txt:"On ne trouve plus nos milieux. On fait comment ?"}],o:["Le jeu à trois : une remise vers un joueur lancé","Des passes plus lentes pour calmer le rythme du match","Garder le ballon au pied plus longtemps","Arrêter de jouer au milieu de terrain"],a:0,w:"Contre l'individuel, la remise en une touche vers un troisième homme fait sauter le marquage."},
{i:"k272_19",u:272,t:"tf",d:.5,q:"Le jeu à trois est particulièrement utile contre un pressing individuel.",a:true,w:"Le défenseur qui suit B est pris de vitesse par la remise vers C."},
{i:"k272_20",u:272,t:"sort",d:.5,nw:"Relance courte ou longue",q:"Relance courte ou jeu long ?",bins:["Relance courte","Jeu long"],it:[["Racing en surnombre à 3 contre 2",0],["Égalité parfaite, tous marqués",1],["Attaquant très grand et fort de la tête devant",1],["6 structurellement libre",0]],w:"Court si surnombre. Long si l'on est pris, surtout avec un bon point d'appui devant."},
{i:"k272_21",u:272,t:"mcq",d:.5,q:"Quel est le risque d'une relance courte sans surnombre ?",o:["Perdre le ballon près de son but","Recevoir un carton jaune","Jouer trop lentement","Rester hors-jeu"],a:0,w:"Sans homme libre, la relance courte devient un cadeau devant sa surface."},
{i:"k272_22",u:272,t:"fill",d:.5,q:"Après un long ballon, le ballon qui retombe d'un duel aérien s'appelle le ___ ballon.",o:["second","dernier","premier","faux"],a:0,w:"Le second ballon : zone souvent négligée, à gagner après un jeu long (module 11)."},
{i:"k272_23",u:272,t:"story",d:.55,q:"Rappel du module 7 : quel trigger le Scarpe attend-il ?",sc:[{who:"Élodie Marchal",txt:"Leur pressing ne part jamais tant qu'on joue vers l'avant. Sur quoi déclenchent-ils ?"}],o:["Sur nos passes latérales ou en retrait","Sur chacune de nos passes vers l'avant","Sur les touches seulement","Sur les coups de sifflet de l'arbitre"],a:0,w:"Latéral, Lent, Loupé, Ligne : la passe latérale est le trigger le plus courant à la relance."},
{i:"k272_24",u:272,t:"order",d:.5,q:"Remets dans l'ordre une sortie de balle réussie.",it:["Compter les presseurs adverses","Placer un joueur de plus","Repérer l'homme libre","Lui donner le ballon","Il se retourne et progresse"],w:"Compter, ajouter, repérer, servir, progresser. C'est un build-up réussi : sortie propre depuis l'arrière."},
{i:"k272_25",u:272,t:"num",d:.55,q:"Le Scarpe presse avec 2 attaquants et 1 milieu. Le Racing relance avec le gardien, 2 centraux, le 6 et un latéral. Combien de joueurs de plus que les presseurs ?",a:2,tol:0,un:" joueurs",h:"5 - 3",w:"5 relanceurs contre 3 presseurs : 2 de plus. Largement de quoi trouver un homme libre."},
{i:"k272_26",u:272,t:"story",d:.55,q:"Rappel du module 3 : quel rôle aide à créer le surnombre au milieu ?",sc:[{who:"Samir Benhaddou",txt:"On veut un joueur de plus à côté du 6 quand on relance."}],o:["Un latéral inversé qui rentre dans l'axe","Un ailier qui reste collé à la ligne de touche","Un avant-centre qui reste en pointe","Un gardien qui reste sur sa ligne"],a:0,w:"Le latéral inversé rentre au milieu : un joueur de plus dans l'axe."},
{i:"k272_27",u:272,t:"tf",d:.55,q:"Relancer court est toujours la meilleure option, quelle que soit la situation.",a:false,w:"Seulement avec un surnombre. Sinon, le jeu long évite une perte dangereuse."},
{i:"k272_28",u:272,t:"multi",d:.55,q:"Quels signes montrent une bonne construction ?",o:["Un homme libre trouvé à chaque relance","Des joueurs qui se retournent face au jeu","Peu de pertes dans sa moitié","Des dégagements à chaque ballon","Des passes toujours latérales"],a:[0,1,2],w:"Homme libre, joueurs orientés face au jeu, sécurité dans sa moitié."},
{i:"k272_29",u:272,t:"match",d:.6,q:"Rappel des modules 5 à 8 : associe chaque idée à son module.",p:[["5 secondes après la perte","Les phases de jeu"],["Haut, moyen, bas","Le bloc"],["Latéral, Lent, Loupé, Ligne","Le pressing"],["Un de plus qu'eux","La construction"]],w:"Les grandes règles de mémoire de la première moitié du cours."},
{i:"k272_30",u:272,t:"story",d:.6,q:"Que dis-tu à Samir à la pause ?",ctx:"Le Scarpe presse à trois. Le Racing relance à trois et perd trois ballons devant sa surface.",sc:[{who:"Samir Benhaddou",txt:"On arrête de relancer court ?"}],o:["Non : on ajoute un quatrième relanceur","Oui : dégagements à chaque fois","Non : on continue exactement pareil","Oui : et on recule tout le bloc"],a:0,w:"Un de plus qu'eux : trois contre trois, c'est l'égalité. Un latéral qui descend recrée le surnombre."},
{i:"k272_31",u:272,t:"mcq",d:.6,q:"Dans la grille, quelle question concerne la relance ?",o:["Quel joueur est structurellement libre ?","Combien de corners ont été tirés ?","Quelle est la hauteur du gardien ?","Qui a le plus de tirs cadrés ?"],a:0,w:"La grille d'observation demande quel joueur est structurellement libre, en surnombre, à la relance."},
{i:"k272_32",u:272,t:"story",d:.6,q:"Synthèse : Élodie te demande le plan de relance du Racing.",sc:[{who:"Élodie Marchal",txt:"Une phrase."}],o:["« Trois contre deux, le 6 libre, Rayan décroche pour vider l'axe »","« Dégagement à chaque fois, personne ne décroche jamais au milieu »","« Tout le monde attaque, le gardien relance seul »","« Deux contre trois, on attend l'erreur adverse »"],a:0,w:"Surnombre, homme libre, décrochage qui libère : les trois idées du module."}
