/*UNIT*/
{id:274,c:"FOOT",n:"Module 10",t:"Transitions : gegenpressing, rest defense et contre-attaque",col:"--green",ic:"⚡",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Expliquer le <b>gegenpressing</b> et sa fenêtre de <b>5 secondes</b>.</li>
<li>Décrire la <b>rest defense</b> et compter les joueurs qui la forment.</li>
<li>Reconnaître une bonne <b>contre-attaque</b>.</li>
<li>Choisir entre <b>contre-presser</b> et <b>se replier</b>.</li></ul>
<h3>Les cinq secondes du match</h3>
<div class="gstory">Racing-Scarpe, 55e minute. Rayan perd le ballon à trente mètres du but adverse. Au lieu de reculer, Kylian, Rayan et l'avant-centre sautent sur le porteur. Deux secondes plus tard, ballon récupéré, frappe, but. Mehdi hurle de joie, puis se tourne vers toi : « C'était une contre-attaque, ça ? » Élodie répond avant toi : « Non. C'était une contre-contre-attaque. En allemand, gegenpressing. »</div>
<h3>Le gegenpressing</h3>
<ul><li>Le <b>gegenpressing</b> (contre-pressing) est un <b>pressing immédiat</b> juste après la <b>perte</b> du ballon, dans les <b>5 secondes</b> qui suivent.</li>
<li>Pourquoi ça marche : l'adversaire qui vient de récupérer est souvent <b>mal orienté</b>, pas encore organisé pour ressortir.</li>
<li>Bonus : on récupère <b>près du but adverse</b>, là où une occasion est immédiate.</li>
<li>Si la récupération échoue en 5 secondes, on <b>se replie</b> dans le bloc.</li></ul>
<div class="gmnemo"><b>« Perdu ? Mords ! »</b>. Au moment de la perte, les joueurs proches du ballon mordent tout de suite, pendant cinq secondes. Après, on recule. Un entraîneur célèbre disait que le contre-pressing était le meilleur meneur de jeu du monde.</div>
<h3>La rest defense</h3>
<p>La <b>rest defense</b> est l'ensemble des joueurs qui restent <b>volontairement en couverture</b> pendant que l'équipe attaque haut. Leur rôle : empêcher la contre-attaque adverse et soutenir le gegenpressing.</p>
<ul><li>Structure fréquente : <b>3 + 2</b> (trois défenseurs et deux milieux) ou 2 + 3, soit <b>cinq joueurs</b> derrière le ballon.</li>
<li>Ils se placent pour couper les passes vers les attaquants adverses et gagner les seconds ballons.</li>
<li>Une rest defense trop légère : chaque perte devient une contre-attaque dangereuse.</li></ul>
<div class="gmnemo">La rest defense, c'est <b>« l'assurance de l'attaque »</b>. Plus on attaque à nombreux, plus l'assurance doit être solide. Le chiffre repère : <b>3 + 2</b>.</div>
<h3>La contre-attaque</h3>
<ul><li>Elle part d'une <b>récupération</b> (transition offensive).</li>
<li>Elle est <b>verticale</b> : la première passe va vers l'avant, dans l'espace.</li>
<li>Elle se joue en <b>peu de touches</b> et en <b>peu de temps</b>, avec des courses dans le dos et dans la largeur.</li>
<li>Elle doit finir avant que l'adversaire se replace : moins de 5 à 10 secondes.</li></ul>
<h3>Contre-presser ou se replier ?</h3>
<table><tr><th>Situation à la perte</th><th>Réponse</th></tr>
<tr><td>Plusieurs joueurs proches du ballon, adversaire mal orienté</td><td><b>Contre-presser</b></td></tr>
<tr><td>Peu de joueurs autour, adversaire face au jeu</td><td><b>Se replier</b> vite derrière le ballon</td></tr>
<tr><td>Contre-attaque adverse dangereuse et rien d'autre</td><td>Parfois une <b>faute tactique</b>, au prix d'un carton jaune</td></tr></table>
<div class="gtrap">Ta fiche définit gegenpressing et rest defense, et demande deux questions : que se passe-t-il dans les 5 secondes après chaque perte, et qui reste en rest defense. Ajoute le lien entre les deux : une bonne rest defense <b>rend possible</b> le gegenpressing, car elle couvre les passes qui permettraient à l'adversaire d'en sortir.</div>
<h3>Ce que tu dois retenir</h3>
<ul><li>Perdu ? Mords ! Gegenpressing dans les 5 secondes, puis repli.</li>
<li>Rest defense : l'assurance de l'attaque, souvent 3 + 2.</li>
<li>Contre-attaque : verticale, peu de touches, peu de temps.</li>
<li>Contre-presser si l'on est nombreux près du ballon, sinon se replier.</li></ul>`},
/*EXOS*/
{i:"k274_01",u:274,t:"mcq",d:.2,nw:"Le gegenpressing",q:"Qu'est-ce que le gegenpressing ?",o:["Presser tout de suite après la perte","Presser le gardien sur chaque relance","Reculer dès qu'on perd le ballon","Un pressing uniquement sur corner"],a:0,w:"Contre-pressing : dans les 5 secondes qui suivent la perte."},
{i:"k274_02",u:274,t:"story",d:.25,q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"On a perdu le ballon puis on l'a repris tout de suite : c'était une contre-attaque ?"}],o:["Non : c'est du gegenpressing, juste après notre perte","Oui, toute récupération de balle est forcément une contre-attaque","Non, c'est un coup de pied arrêté","Oui, et elle dure toujours dix minutes"],a:0,w:"Perdu ? Mords ! On presse immédiatement après la perte."},
{i:"k274_03",u:274,t:"tiles",d:.3,q:"Reconstitue la formule mémo du gegenpressing.",a:["Perdu","?","Mords","!"],dd:["Recule","Attends","Siffle"],w:"Les joueurs proches mordent tout de suite, pendant cinq secondes."},
{i:"k274_04",u:274,t:"slider",d:.3,q:"Combien de secondes dure la fenêtre du gegenpressing ?",min:1,max:15,step:1,a:5,tol:0,pre:"",un:" s",w:"Cinq secondes, puis on se replie si l'on n'a pas récupéré."},
{i:"k274_05",u:274,t:"multi",d:.35,q:"Pourquoi le gegenpressing est-il efficace ?",o:["L'adversaire vient de récupérer, mal orienté","On récupère près du but adverse","L'adversaire n'est pas encore organisé","L'arbitre ne siffle pas pendant 5 secondes","Le hors-jeu est suspendu"],a:[0,1,2],w:"Adversaire désorganisé, mal orienté, et récupération près du but adverse."},
{i:"k274_06",u:274,t:"tf",d:.35,q:"Si le gegenpressing échoue après 5 secondes, l'équipe doit se replier dans son bloc.",a:true,w:"On ne presse pas indéfiniment : après la fenêtre, on se replace."},
{i:"k274_07",u:274,t:"fill",d:.35,q:"Le mot gegenpressing vient de l'___.",o:["allemand","anglais","italien","espagnol"],a:0,w:"Gegen signifie « contre » : contre-pressing."},
{i:"k274_08",u:274,t:"story",d:.4,q:"Que dis-tu à Samir ?",ctx:"Sur la vidéo, chaque fois que le Racing perd le ballon, les joueurs proches marchent en protestant. L'adversaire ressort facilement.",sc:[{who:"Samir Benhaddou",txt:"On encaisse trop en transition. Qu'est-ce qui manque ?"}],o:["La réaction dans les 5 secondes : mordre ou reculer","Des frappes de loin bien plus nombreuses dans le match","Un gardien plus grand","Plus de centres depuis les côtés"],a:0,w:"La grille demande ce qui se passe dans les 5 secondes après chaque perte. Ici : rien."},
{i:"k274_09",u:274,t:"mcq",d:.4,nw:"La rest defense",q:"Qu'est-ce que la rest defense ?",o:["Les joueurs qui restent couvrir en attaque","Le repos accordé aux défenseurs pendant la mi-temps","Un bloc bas pendant tout le match","Les remplaçants sur le banc"],a:0,w:"L'assurance de l'attaque : ils restent derrière le ballon pendant la possession haute."},
{i:"k274_10",u:274,t:"slider",d:.4,q:"Structure repère de la rest defense : combien de joueurs au total dans un 3 + 2 ?",min:2,max:8,step:1,a:5,tol:0,pre:"",un:" joueurs",w:"Trois défenseurs et deux milieux : cinq joueurs d'assurance."},
{i:"k274_11",u:274,t:"tiles",d:.4,q:"Reconstitue l'image mémo de la rest defense.",a:["L'assurance","de","l'attaque"],dd:["la","défense","du"],w:"Plus on attaque à nombreux, plus l'assurance doit être solide."},
{i:"k274_12",u:274,t:"multi",d:.4,q:"Quel est le rôle de la rest defense ?",o:["Empêcher la contre-attaque","Soutenir le gegenpressing","Gagner les seconds ballons","Tirer les corners","Aller dans la surface adverse"],a:[0,1,2],w:"Couvrir, soutenir, récupérer : elle reste derrière le ballon."},
{i:"k274_13",u:274,t:"story",d:.45,q:"Rappel du module 4 : que vois-tu ?",ctx:"En 3-2-5, le Racing a cinq joueurs devant. Derrière le ballon : les trois défenseurs et deux milieux.",sc:[{who:"Élodie Marchal",txt:"Leur rest defense, tu la décris comment ?"}],o:["Un 3 + 2 : cinq joueurs en assurance","Aucune, tout le monde attaque","Un seul joueur, le gardien","Dix joueurs derrière le ballon, gardien non compris"],a:0,w:"Le 3-2-5 en possession garde naturellement un 3 + 2 derrière le ballon."},
{i:"k274_14",u:274,t:"tf",d:.45,q:"Une rest defense trop légère rend chaque perte de balle dangereuse.",a:true,w:"Personne pour couper la contre-attaque : chaque perte devient une occasion adverse."},
{i:"k274_15",u:274,t:"fill",d:.45,q:"Une bonne rest defense rend possible le ___, car elle couvre les passes de sortie adverses.",o:["gegenpressing","build-up","corner","hors-jeu"],a:0,w:"Les presseurs mordent devant, la rest defense ferme derrière : l'adversaire est pris en tenaille."},
{i:"k274_16",u:274,t:"sort",d:.45,q:"Dans la grille d'Élodie, quelle question pour chaque observation ?",bins:["5 secondes après la perte","Rest defense"],it:[["Les joueurs proches mordent-ils ?",0],["Qui reste derrière quand on attaque haut ?",1],["Récupère-t-on avant 5 secondes ?",0],["Combien de joueurs couvrent pendant la possession ?",1]],w:"Deux questions de la grille, deux moments : juste après la perte, et pendant la possession haute."},
{i:"k274_17",u:274,t:"mcq",d:.45,nw:"La contre-attaque",q:"Quelle est la première qualité d'une contre-attaque ?",o:["Être verticale, vers l'avant","Être lente et patiente","Passer par le gardien","Multiplier les passes latérales"],a:0,w:"Verticale, peu de touches, peu de temps."},
{i:"k274_18",u:274,t:"order",d:.5,q:"Remets dans l'ordre une contre-attaque type.",it:["Récupération du ballon","Première passe vers l'avant","Courses dans le dos et dans la largeur","Dernière passe","Tir avant le replacement adverse"],w:"Récupérer, verticaliser, accompagner, servir, finir vite."},
{i:"k274_19",u:274,t:"story",d:.5,q:"Que corriges-tu ?",ctx:"Le Racing récupère au milieu. Rayan fait deux passes latérales avant de jouer vers l'avant : le Scarpe est replacé.",sc:[{who:"Samir Benhaddou",txt:"On avait trois contre deux et on n'a rien fait. Pourquoi ?"}],o:["Il fallait jouer vers l'avant tout de suite","Il fallait garder le ballon plus longtemps","Il fallait dégager en touche","Il fallait attendre les défenseurs"],a:0,w:"La contre-attaque vit de sa verticalité. Deux passes latérales, et la fenêtre se ferme."},
{i:"k274_20",u:274,t:"tf",d:.5,q:"Une bonne contre-attaque se joue en beaucoup de touches pour bien s'organiser.",a:false,w:"Peu de touches, peu de temps : l'objectif est de frapper avant le replacement."},
{i:"k274_21",u:274,t:"sort",d:.5,nw:"Contre-presser ou se replier",q:"Que faire au moment de la perte ?",bins:["Contre-presser","Se replier"],it:[["Trois joueurs du Racing près du ballon, adversaire dos au jeu",0],["Un seul joueur proche, adversaire face au jeu",1],["Perte près de la surface adverse, porteur adverse mal orienté",0],["Adversaire lancé avec de l'espace, nos milieux loin",1]],w:"Nombreux près du ballon et adversaire mal orienté : mordre. Sinon : reculer."},
{i:"k274_22",u:274,t:"story",d:.55,q:"Que penses-tu de ce choix ?",ctx:"Contre-attaque du Scarpe à 3 contre 2. Le 6 du Racing tire le maillot du porteur au milieu de terrain. Carton jaune.",sc:[{who:"Mehdi",txt:"Quel idiot, il a pris un jaune !"}],o:["Une faute tactique : un jaune pour éviter un 3 contre 2","Une erreur : il aurait dû prendre un rouge","Une faute sans intérêt, il fallait laisser filer","Une simulation du porteur adverse"],a:0,w:"Faute tactique : au prix d'un avertissement, il casse une contre-attaque dangereuse."},
{i:"k274_23",u:274,t:"mcq",d:.5,q:"Rappel du module 1 : quel risque prend un joueur déjà averti qui fait une faute tactique ?",o:["Un deuxième jaune, donc l'exclusion","Un simple rappel oral","Un penalty automatique","Aucun risque supplémentaire pour lui ni pour l'équipe"],a:0,w:"Deux jaunes font un rouge : la faute tactique coûte cher à un joueur déjà averti."},
{i:"k274_24",u:274,t:"match",d:.55,q:"Associe chaque notion à sa définition.",p:[["Gegenpressing","Presser juste après la perte"],["Rest defense","Joueurs qui couvrent pendant l'attaque"],["Contre-attaque","Attaque rapide après récupération"],["Faute tactique","Faute volontaire pour casser un contre"]],w:"Le vocabulaire des transitions, à placer dans chaque rapport."},
{i:"k274_25",u:274,t:"story",d:.55,q:"Rappel du module 5 : dans quelle phase est le gegenpressing ?",sc:[{who:"Élodie Marchal",txt:"Rayan perd le ballon et Kylian saute sur le porteur. Phase ?"}],o:["Transition défensive","Transition offensive","Défense organisée","Possession organisée"],a:0,w:"On vient de perdre : Réagir. Le gegenpressing est une réponse en transition défensive."},
{i:"k274_26",u:274,t:"num",d:.55,q:"Perte du ballon à la 55e minute et 40 secondes. À quelle seconde (minute 55) se ferme la fenêtre du gegenpressing ?",a:45,tol:0,un:" s",h:"40 + 5",w:"40 + 5 = 45 : à 55'45, la fenêtre se ferme et l'on se replie."},
{i:"k274_27",u:274,t:"tf",d:.55,q:"La rest defense se met en place quand l'équipe défend en bloc bas.",a:false,w:"Elle se met en place pendant la possession haute : c'est l'assurance de l'attaque."},
{i:"k274_28",u:274,t:"multi",d:.6,q:"Rappel du module 7 : quels points communs entre le pressing et le gegenpressing ?",o:["On presse en meute","On couvre les lignes de passe","On cherche à récupérer vite","Ils se déclenchent sur la même situation","Ils durent tout le match"],a:[0,1,2],w:"Même technique, mais le gegenpressing se déclenche sur notre perte, pas sur un trigger adverse."},
{i:"k274_29",u:274,t:"story",d:.6,q:"Que proposes-tu à la pause ?",ctx:"Le Racing attaque avec huit joueurs. Deux contre-attaques du Scarpe ont failli faire but.",sc:[{who:"Samir Benhaddou",txt:"Un seul ajustement ?"}],o:["Renforcer la rest defense en 3 + 2","Mettre encore un joueur de plus devant","Supprimer le gegenpressing","Faire jouer le gardien au milieu"],a:0,w:"Plus on attaque à nombreux, plus l'assurance doit être solide."},
{i:"k274_30",u:274,t:"fill",d:.6,q:"Une contre-attaque doit finir avant que l'adversaire se ___.",o:["replace","repose","remplace","plaigne"],a:0,w:"Moins de 5 à 10 secondes, avant le replacement adverse."},
{i:"k274_31",u:274,t:"tf",d:.6,q:"Récupérer le ballon près du but adverse grâce au gegenpressing crée une occasion immédiate.",a:true,w:"C'est le bonus du contre-pressing : la récupération est déjà près du but."},
{i:"k274_32",u:274,t:"story",d:.6,q:"Synthèse : Élodie te demande ton rapport sur les transitions du Racing.",sc:[{who:"Élodie Marchal",txt:"Une phrase."}],o:["« Gegenpressing dans les 5 s, rest defense en 3 + 2, contres verticaux »","« Aucune réaction à la perte, huit joueurs devant, contres latéraux »","« On recule à chaque perte, on attend dix minutes pour contrer »","« Le gardien fait le gegenpressing tout seul »"],a:0,w:"Réaction à la perte, assurance, verticalité : les trois clés des transitions."}
