/*UNIT*/
{id:275,c:"FOOT",n:"Module 11",t:"Coups de pied arrêtés : un but sur cinq se prépare à l'entraînement",col:"--green",ic:"🥅",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Mesurer le <b>poids</b> des coups de pied arrêtés dans les buts.</li>
<li>Distinguer marquage de <b>zone</b>, <b>individuel</b> et <b>mixte</b> sur corner.</li>
<li>Reconnaître un corner <b>rentrant</b> et <b>sortant</b>, premier et second poteau.</li>
<li>Expliquer le <b>second ballon</b> et le rôle du <b>set-piece coach</b>.</li>
<li>Appliquer les règles du <b>penalty</b> et du <b>mur</b>.</li></ul>
<h3>Le corner du jeudi</h3>
<div class="gstory">Jeudi, entraînement du Racing. Un homme que tu n'as jamais vu installe des plots dans la surface : c'est <b>Julien</b>, le nouveau spécialiste des coups de pied arrêtés. Il fait répéter le même corner vingt fois : Lucas part au premier poteau, deux joueurs bloquent, Rayan attend en retrait pour le second ballon. Mehdi rigole : « Vingt fois le même corner ? » Samedi, 78e minute : corner, but de Lucas, exactement comme jeudi.</div>
<h3>Pourquoi c'est devenu une arme</h3>
<ul><li>En Premier League 2024-25, environ <b>un but sur cinq</b> (20,6 %, hors penalties) est venu d'un coup de pied arrêté, contre 19,8 % la saison précédente.</li>
<li>La tendance a continué à monter en 2025-26 : les grands clubs emploient des <b>set-piece coaches</b>, des entraîneurs spécialisés uniquement sur ces phases.</li>
<li>Un coup de pied arrêté se <b>prépare</b> comme un schéma répété : c'est l'action la plus contrôlable du football.</li></ul>
<div class="gmnemo"><b>« Un but sur cinq naît d'un ballon arrêté »</b>. Une équipe qui néglige les corners renonce à un cinquième de ses buts.</div>
<h3>Défendre un corner : zone, individuel, mixte</h3>
<table><tr><th>Marquage</th><th>Principe</th><th>Faiblesse</th></tr>
<tr><td><b>De zone</b></td><td>Des joueurs à des <b>postes fixes</b> (premier poteau, point de penalty…)</td><td>L'attaquant prend de l'élan sans être gêné</td></tr>
<tr><td><b>Individuel</b></td><td>Chaque défenseur suit un attaquant</td><td>Les blocs et les courses croisées font perdre le joueur</td></tr>
<tr><td><b>Mixte</b></td><td>Des postes fixes <b>et</b> du marquage individuel sur les meilleurs joueurs de tête</td><td>Demande une coordination parfaite</td></tr></table>
<h3>Attaquer un corner</h3>
<ul><li>Corner <b>rentrant</b> : le ballon tourne vers le but, dangereux au premier poteau et pour le gardien.</li>
<li>Corner <b>sortant</b> : le ballon s'éloigne du but, plus facile à attaquer de la tête en course.</li>
<li><b>Premier poteau</b> : on dévie. <b>Second poteau</b> : on reprend, souvent seul.</li>
<li>Les <b>blocs</b> gênent le défenseur sans le tenir. Tenir ou pousser est une faute.</li>
<li>Un joueur en retrait attend le <b>second ballon</b> : le ballon repoussé, qui retombe au bord de la surface.</li></ul>
<div class="gmnemo">Le trio du corner : <b>« Dévier, Reprendre, Récupérer »</b>. Premier poteau pour dévier, second poteau pour reprendre, retrait pour récupérer le second ballon.</div>
<h3>Coup franc et penalty</h3>
<ul><li>Sur coup franc, le mur est à <b>9,15 m</b>. Les attaquants ne peuvent pas se placer à moins d'un mètre d'un mur de trois joueurs ou plus.</li>
<li>Sur penalty, le gardien reste sur sa ligne, <b>au moins un pied</b> sur ou au-dessus de la ligne au moment du tir. Les autres joueurs restent hors de la surface et à 9,15 m du point.</li></ul>
<div class="gtrap">Ta fiche cite le marquage mixte, le second ballon et le set-piece coach, « courant en 2026 ». Le chiffre qui donne tout son sens : environ un but sur cinq en Premier League vient d'un coup de pied arrêté (2024-25, vérifié en septembre 2026).</div>
<h3>Ce que tu dois retenir</h3>
<ul><li>Un but sur cinq naît d'un ballon arrêté.</li>
<li>Zone, individuel, mixte : trois façons de défendre.</li>
<li>Dévier, Reprendre, Récupérer.</li>
<li>Mur à 9,15 m, gardien un pied sur la ligne au penalty.</li></ul>`},
/*EXOS*/
{i:"k275_01",u:275,t:"slider",d:.2,nw:"Le poids des coups de pied arrêtés",q:"En Premier League 2024-25, quelle part des buts (hors penalties) est venue d'un coup de pied arrêté, en pourcentage arrondi ?",min:5,max:50,step:1,a:21,tol:2,pre:"",un:" %",w:"20,6 % : environ un but sur cinq, contre 19,8 % la saison précédente."},
{i:"k275_02",u:275,t:"tiles",d:.25,q:"Reconstitue la phrase mémo.",a:["Un","but","sur","cinq","naît","d'un","ballon","arrêté"],dd:["dix","perdu","penalty"],w:"Environ 20 % des buts : on ne peut pas négliger les coups de pied arrêtés."},
{i:"k275_03",u:275,t:"story",d:.3,q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"Vingt fois le même corner à l'entraînement, c'est une perte de temps !"}],o:["C'est l'action la plus contrôlable : un but sur cinq","Oui, les corners ne marquent presque jamais","Non, c'est surtout pour fatiguer les joueurs avant samedi","Oui, il vaudrait mieux faire des tours de terrain"],a:0,w:"Un coup de pied arrêté se prépare comme un schéma. Samedi, Lucas a marqué comme jeudi."},
{i:"k275_04",u:275,t:"fill",d:.3,q:"L'entraîneur spécialisé uniquement sur les coups de pied arrêtés s'appelle le set-piece ___.",o:["coach","player","keeper","analyst"],a:0,w:"Set-piece coach : un métier devenu courant dans les grands clubs en 2026."},
{i:"k275_05",u:275,t:"tf",d:.3,q:"La part des buts sur coups de pied arrêtés en Premier League a augmenté entre 2023-24 et 2024-25.",a:true,w:"De 19,8 % à 20,6 %, et la tendance a continué ensuite."},
{i:"k275_06",u:275,t:"match",d:.35,nw:"Zone, individuel, mixte",q:"Associe chaque marquage sur corner à son principe.",p:[["Zone","Postes fixes dans la surface"],["Individuel","Chacun suit un attaquant"],["Mixte","Postes fixes et marquage des meilleurs de la tête"],["Faiblesse de la zone","L'attaquant prend de l'élan"]],w:"Des espaces, des joueurs, ou les deux : trois façons de défendre."},
{i:"k275_07",u:275,t:"sort",d:.35,q:"Quel marquage ?",bins:["Zone","Individuel","Mixte"],it:[["Quatre joueurs sur des postes fixes, personne ne suit",0],["Chaque défenseur colle un attaquant",1],["Trois postes fixes plus deux marqueurs sur leurs géants",2],["Lucas garde le point de penalty quoi qu'il arrive",0],["Nabil suit leur avant-centre partout",1]],w:"Postes fixes : zone. Suivre : individuel. Les deux : mixte."},
{i:"k275_08",u:275,t:"mcq",d:.35,q:"Quelle est la faiblesse du marquage individuel sur corner ?",o:["Les blocs et courses croisées perdent le défenseur","L'attaquant prend de l'élan sans être gêné par personne","Personne ne garde le premier poteau","Le gardien ne peut plus sortir"],a:0,w:"Un bloc légal ou une course croisée, et le défenseur perd son joueur."},
{i:"k275_09",u:275,t:"tf",d:.4,q:"Le marquage mixte combine des postes fixes et du marquage individuel.",a:true,w:"C'est le marquage le plus courant au haut niveau, cité dans ta fiche."},
{i:"k275_10",u:275,t:"story",d:.4,q:"Que conseilles-tu à Julien ?",ctx:"Le Scarpe défend en zone pure, sans marquage individuel. Leur défenseur au point de penalty ne bouge jamais.",sc:[{who:"Julien",txt:"Comment on exploite leur zone ?"}],o:["Lucas prend de l'élan loin et attaque la zone en course","Tout le monde se place immobile devant leur gardien de but","On joue le corner à deux au sol à chaque fois","On tire directement au but depuis le coin"],a:0,w:"La faiblesse de la zone : l'attaquant arrive lancé face à un défenseur immobile."},
{i:"k275_11",u:275,t:"mcq",d:.4,nw:"Corners rentrants et sortants",q:"Qu'est-ce qu'un corner rentrant ?",o:["Un ballon qui tourne vers le but","Un ballon qui s'éloigne du but et du gardien","Un corner joué à deux au sol","Un corner tiré en retrait"],a:0,w:"Rentrant : il tourne vers le but, dangereux au premier poteau et pour le gardien."},
{i:"k275_12",u:275,t:"sort",d:.45,q:"Rentrant ou sortant ?",bins:["Rentrant","Sortant"],it:[["Le ballon file vers le but en tournant",0],["Le ballon s'éloigne du gardien",1],["Le gardien est gêné par la trajectoire",0],["Un joueur attaque en course de la tête, loin du but",1]],w:"Rentrant vers le but, sortant loin du but."},
{i:"k275_13",u:275,t:"match",d:.45,q:"Associe chaque zone du corner à son rôle.",p:[["Premier poteau","Dévier"],["Second poteau","Reprendre"],["Retrait, bord de la surface","Récupérer le second ballon"],["Devant le gardien","Gêner sans faute"]],w:"Dévier, Reprendre, Récupérer : chaque zone a sa mission."},
{i:"k275_14",u:275,t:"tiles",d:.45,q:"Reconstitue le trio mémo du corner.",a:["Dévier,","Reprendre,","Récupérer"],dd:["Reculer,","Dribbler,","Protester,"],w:"Premier poteau pour dévier, second pour reprendre, retrait pour récupérer."},
{i:"k275_15",u:275,t:"fill",d:.45,nw:"Le second ballon",q:"Le ballon repoussé qui retombe au bord de la surface s'appelle le ___ ballon.",o:["second","dernier","faux","libre"],a:0,w:"Le second ballon : zone souvent négligée, d'où le joueur en retrait."},
{i:"k275_16",u:275,t:"story",d:.45,q:"Que vois-tu ?",ctx:"Sur trois corners du Racing, le Scarpe repousse, et le ballon retombe seul au bord de la surface. Personne ne le récupère.",sc:[{who:"Élodie Marchal",txt:"Qu'est-ce qui manque sur nos corners ?"}],o:["Un joueur en retrait pour le second ballon","Un joueur de plus sur la ligne de but","Un tireur gaucher plutôt que droitier","Un gardien qui monte dans la surface"],a:0,w:"Récupérer : le troisième temps du corner. Sans joueur en retrait, le second ballon est perdu."},
{i:"k275_17",u:275,t:"tf",d:.5,q:"Sur un corner, tenir un défenseur par le maillot pour le bloquer est autorisé.",a:false,w:"Un bloc gêne sans tenir. Tenir ou pousser est une faute, et un penalty en défense."},
{i:"k275_18",u:275,t:"multi",d:.5,q:"Que fait un bon schéma de corner ?",o:["Un joueur dévie au premier poteau","Un joueur reprend au second","Un joueur attend le second ballon","Tous les joueurs se collent au gardien","Chacun improvise"],a:[0,1,2],w:"Dévier, reprendre, récupérer : un schéma répété, pas de l'improvisation."},
{i:"k275_19",u:275,t:"num",d:.5,nw:"Coup franc et penalty",q:"Rappel du module 1 : à combien de mètres se place le mur sur un coup franc ?",a:9.15,tol:.01,un:" m",h:"Le rayon du rond central",w:"9,15 m. Et les attaquants restent à au moins un mètre d'un mur de trois joueurs ou plus."},
{i:"k275_20",u:275,t:"mcq",d:.5,q:"Au moment d'un penalty, où doit se trouver le gardien ?",o:["Au moins un pied sur ou au-dessus de sa ligne","N'importe où dans sa surface","À un mètre devant sa ligne","Derrière sa ligne de but"],a:0,w:"Sur sa ligne, au moins un pied au contact ou au-dessus de la ligne au moment du tir."},
{i:"k275_21",u:275,t:"slider",d:.5,q:"À quelle distance du mur les attaquants doivent-ils se tenir, au minimum, quand le mur compte trois joueurs ou plus ?",min:0,max:5,step:1,a:1,tol:0,pre:"",un:" m",w:"Un mètre : ils ne peuvent plus se glisser dans le mur."},
{i:"k275_22",u:275,t:"story",d:.55,q:"Que dis-tu à Mehdi ?",ctx:"Penalty pour le Racing. Le gardien du Scarpe avance de deux mètres avant le tir et arrête le ballon.",sc:[{who:"Mehdi",txt:"Il est sorti de sa ligne, c'est à retirer !"}],o:["Oui : s'il a avancé, le penalty est à retirer","Non : le gardien peut avancer autant qu'il veut","Non : seul le tireur doit respecter une règle","Oui, et le but est accordé directement"],a:0,w:"Si le gardien quitte sa ligne et arrête le tir, le penalty est à retirer."},
{i:"k275_23",u:275,t:"order",d:.5,q:"Remets dans l'ordre la préparation d'un corner par Julien.",it:["Analyser le marquage adverse","Choisir rentrant ou sortant","Répartir dévier, reprendre, récupérer","Répéter le schéma à l'entraînement","L'appliquer en match"],w:"Observer, choisir, répartir, répéter, exécuter. C'est le travail du set-piece coach."},
{i:"k275_24",u:275,t:"story",d:.55,q:"Rappel du module 10 : que dis-tu ?",ctx:"Le Racing envoie neuf joueurs dans la surface adverse sur un corner. Le Scarpe repousse et contre-attaque à trois contre un.",sc:[{who:"Samir Benhaddou",txt:"Qu'est-ce qui a manqué ?"}],o:["Une rest defense : garder des joueurs derrière","Un dixième joueur dans la surface pour gagner le duel","Un tireur de corner plus rapide","Un gardien plus grand"],a:0,w:"Même sur corner, il faut une assurance : deux ou trois joueurs derrière pour le second ballon et le contre."},
{i:"k275_25",u:275,t:"tf",d:.55,q:"Sur une touche longue lancée dans la surface, un attaquant ne peut pas être hors-jeu.",a:true,w:"Pas de hors-jeu sur Touche, Corner, 6 mètres (module 1). Les touches longues sont devenues une arme."},
{i:"k275_26",u:275,t:"multi",d:.55,q:"Pourquoi les coups de pied arrêtés sont-ils si travaillés en 2026 ?",o:["Ils pèsent environ un but sur cinq","On peut les répéter à l'entraînement","Des coaches spécialisés les préparent","Le hors-jeu y est supprimé partout","L'arbitre ne siffle jamais de faute"],a:[0,1,2],w:"Poids statistique, contrôle total, spécialistes. Le hors-jeu existe sur coup franc. Le set-piece coach est devenu un métier à part entière."},
{i:"k275_27",u:275,t:"fill",d:.55,q:"Défense sur corner : le marquage le plus courant au haut niveau est le marquage ___.",o:["mixte","libre","aérien","latéral"],a:0,w:"Des postes fixes plus du marquage individuel sur les meilleurs joueurs de tête."},
{i:"k275_28",u:275,t:"story",d:.6,q:"Rappel du module 2 : l'attaquant du Racing était hors-jeu sur un coup franc joué vers lui. Que se passe-t-il ?",sc:[{who:"Mehdi",txt:"Sur un coup franc, il n'y a pas de hors-jeu, non ?"}],o:["Si : le hors-jeu existe sur coup franc","Non, comme sur un corner","Non, seulement en seconde période","Si, mais seulement quand le coup franc est tiré dans la surface"],a:0,w:"T.C.6 seulement : Touche, Corner, 6 mètres. Sur coup franc, le hors-jeu s'applique."},
{i:"k275_29",u:275,t:"mcq",d:.6,q:"Quelle faiblesse du marquage de zone un bon schéma exploite-t-il ?",o:["L'élan de l'attaquant","Le manque de joueurs au sol","La taille du gardien","L'absence d'arbitre assistant"],a:0,w:"Le défenseur de zone est immobile, l'attaquant arrive lancé."},
{i:"k275_30",u:275,t:"sort",d:.6,q:"Coup de pied arrêté : hors-jeu possible ou non ?",bins:["Hors-jeu possible","Pas de hors-jeu"],it:[["Coup franc direct à 25 m",0],["Corner",1],["Touche longue",1],["Coup franc indirect dans le camp adverse",0],["Coup de pied de but",1]],w:"Pas de hors-jeu sur T.C.6. Sur coup franc, oui."},
{i:"k275_31",u:275,t:"tf",d:.6,q:"Un schéma de corner s'improvise en match, il ne se travaille pas à l'entraînement.",a:false,w:"Faux : c'est l'action la plus contrôlable du football. Elle se répète à l'entraînement, comme le corner de Julien."},
{i:"k275_32",u:275,t:"story",d:.6,q:"Synthèse : Julien te demande le plan pour les corners de samedi.",sc:[{who:"Julien",txt:"Une phrase."}],o:["« Corner sortant, élan contre leur zone, un en retrait, trois derrière »","« Neuf joueurs devant le gardien, personne derrière, on verra bien »","« Corner à deux au sol à chaque fois, sans schéma préparé »","« Tir direct du coin, le gardien ne s'y attendra pas »"],a:0,w:"Trajectoire, faiblesse adverse, second ballon, rest defense : un plan complet."}
