/*UNIT*/
{id:277,c:"FOOT",n:"Module 13",t:"Analyser en direct : la grille d'observation et les ajustements",col:"--green",ic:"🔎",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Réciter et appliquer les <b>7 questions</b> de la grille d'observation.</li>
<li>Appliquer les <b>3 réflexes</b> de l'observateur.</li>
<li>Prendre des <b>notes utiles</b> pendant le match.</li>
<li>Repérer et proposer des <b>ajustements à la pause</b> : système, bloc, joueur.</li></ul>
<h3>Ta première feuille de match</h3>
<div class="gstory">Samedi suivant, Racing contre l'US Marcq, leader. Élodie te confie la tablette : « Aujourd'hui, c'est toi qui fais le rapport de mi-temps. Tu as cinq minutes dans le vestiaire, pas une de plus. » Mehdi, en tribune, t'envoie un message : « Tu regardes le ballon comme moi ? » Tu souris : non. Tu as relu ta fiche cinq minutes avant le coup d'envoi, comme prévu.</div>
<h3>La grille d'observation en 7 questions</h3>
<table><tr><th>N°</th><th>Question</th><th>Module</th></tr>
<tr><td>1</td><td>Où se situe le <b>bloc</b> de chaque équipe (haut, moyen, bas) ?</td><td>6</td></tr>
<tr><td>2</td><td><b>Qui presse qui</b> : individuel ou collectif ?</td><td>7</td></tr>
<tr><td>3</td><td><b>Qui décroche</b> pour créer de l'espace, et qui en profite ?</td><td>8</td></tr>
<tr><td>4</td><td>Quel joueur est <b>structurellement libre</b> (surnombre) à la relance ?</td><td>8</td></tr>
<tr><td>5</td><td>Que se passe-t-il dans les <b>5 secondes</b> après chaque perte de balle ?</td><td>5 et 10</td></tr>
<tr><td>6</td><td>Qui reste en <b>rest defense</b> pendant les phases de possession haute ?</td><td>10</td></tr>
<tr><td>7</td><td>Quels <b>ajustements à la pause</b> (système, bloc, joueur) ?</td><td>4 et 13</td></tr></table>
<div class="gmnemo">La grille en sept mots : <b>« Bloc, Presse, Décroche, Libre, Cinq, Reste, Pause »</b>. Récite-les dans l'ordre du jeu : on défend (bloc, presse), on construit (décroche, libre), on perd (cinq), on attaque (reste), on s'adapte (pause).</div>
<h3>Les 3 réflexes</h3>
<ol><li><b>Suis la structure, pas le ballon</b> : regarde où sont les lignes et les espaces libres.</li>
<li><b>Observe les 5 secondes</b> juste après chaque perte ou récupération de balle.</li>
<li><b>Repère qui décroche</b> : ça sert toujours à libérer quelqu'un d'autre ailleurs.</li></ol>
<h3>Prendre des notes utiles</h3>
<ul><li>Note toujours la <b>minute</b>, la <b>phase</b> et le <b>fait</b> : « 23e, transition défensive, personne ne presse, contre adverse ».</li>
<li>Note les <b>répétitions</b> : un fait qui revient trois fois est un <b>schéma</b>, pas un accident.</li>
<li>Sépare les <b>faits</b> (« leur latéral monte à chaque attaque ») des <b>avis</b> (« il est mauvais »).</li></ul>
<div class="gmnemo">La règle des notes : <b>« Une fois, c'est un fait. Trois fois, c'est un plan. »</b> Le rapport de mi-temps ne parle que des plans.</div>
<h3>Les ajustements à la pause</h3>
<table><tr><th>Levier</th><th>Exemple</th></tr>
<tr><td><b>Système</b></td><td>Passer du 4-4-2 au 4-3-3 pour égaliser au milieu</td></tr>
<tr><td><b>Bloc</b></td><td>Descendre d'un cran pour fermer l'espace dans le dos</td></tr>
<tr><td><b>Joueur</b></td><td>Remplacer ou changer le rôle d'un joueur (un latéral qui ne monte plus)</td></tr></table>
<p>Un bon rapport de mi-temps tient en <b>trois points</b> : ce qui marche, ce qui ne marche pas, un ajustement proposé.</p>
<p>Observe aussi l'<b>adversaire</b> au retour des vestiaires : a-t-il changé de système, de bloc, de joueur ? Les dix premières minutes de la seconde période révèlent ses ajustements.</p>
<div class="gtrap">Ta fiche est faite pour être <b>relue 5 minutes avant un match</b>. C'est le bon usage : la grille ne s'apprend pas pendant le match, elle s'applique. Ce cours t'a donné le « pourquoi » de chaque question pour que tu saches quoi en faire.</div>
<h3>Ce que tu dois retenir</h3>
<ul><li>Bloc, Presse, Décroche, Libre, Cinq, Reste, Pause.</li>
<li>Structure, 5 secondes, qui décroche.</li>
<li>Une fois un fait, trois fois un plan.</li>
<li>Système, bloc, joueur : les trois leviers de la pause.</li></ul>`},
/*EXOS*/
{i:"k277_01",u:277,t:"order",d:.2,nw:"La grille d'observation",q:"Remets les 7 questions de la grille dans l'ordre.",it:["Hauteur du bloc","Qui presse qui","Qui décroche","Joueur libre à la relance","Les 5 secondes après la perte","La rest defense","Les ajustements à la pause"],w:"Bloc, Presse, Décroche, Libre, Cinq, Reste, Pause."},
{i:"k277_02",u:277,t:"tiles",d:.25,q:"Reconstitue les sept mots mémo de la grille.",a:["Bloc,","Presse,","Décroche,","Libre,","Cinq,","Reste,","Pause"],dd:["Ballon,","Score,","Corner,"],w:"L'ordre du jeu : défendre, construire, perdre, attaquer, s'adapter."},
{i:"k277_03",u:277,t:"slider",d:.3,q:"Combien de questions compte la grille d'observation ?",min:3,max:10,step:1,a:7,tol:0,pre:"",un:" questions",w:"Sept questions, à relire 5 minutes avant le match."},
{i:"k277_04",u:277,t:"match",d:.3,q:"Associe chaque question de la grille à son module.",p:[["Hauteur du bloc","Le bloc"],["Qui presse qui","Le pressing"],["Joueur structurellement libre","La construction"],["Rest defense","Les transitions"]],w:"Chaque question renvoie à un module du cours."},
{i:"k277_05",u:277,t:"story",d:.3,q:"Que réponds-tu à Mehdi ?",sc:[{who:"Mehdi",txt:"Tu regardes le ballon comme moi ?"}],o:["Non : je suis la structure et les espaces","Oui, le ballon raconte tout ce qui compte dans un match","Non, je regarde seulement le tableau d'affichage du stade","Oui, et je note chaque passe réussie par nos joueurs"],a:0,w:"Réflexe 1 : suis la structure, pas le ballon."},
{i:"k277_06",u:277,t:"multi",d:.35,nw:"Les 3 réflexes",q:"Quels sont les 3 réflexes de l'observateur ?",o:["Suivre la structure, pas le ballon","Observer les 5 secondes après chaque perte ou récupération","Repérer qui décroche","Compter les passes réussies","Suivre le meilleur joueur"],a:[0,1,2],w:"Structure, 5 secondes, décrochage : les trois réflexes de ta fiche."},
{i:"k277_07",u:277,t:"tf",d:.35,q:"Le réflexe 3 dit qu'un joueur qui décroche libère toujours quelqu'un d'autre ailleurs.",a:true,w:"Qui décroche libère quelqu'un d'autre : regarde l'espace qu'il vide."},
{i:"k277_08",u:277,t:"sort",d:.35,q:"Quelle question de la grille correspond à cette observation ?",bins:["Bloc","Cinq secondes","Rest defense"],it:[["Leur ligne défensive est à 30 m de leur but",0],["Après chaque perte, nos joueurs marchent",1],["Trois défenseurs et deux milieux restent derrière",2],["Ils récupèrent en moins de 3 secondes",1],["Leur bloc remonte au rond central",0]],w:"Chaque observation se range dans une question de la grille."},
{i:"k277_09",u:277,t:"fill",d:.4,nw:"Prendre des notes utiles",q:"Une bonne note contient la minute, la phase et le ___.",o:["fait","score","météo","sifflet"],a:0,w:"« 23e, transition défensive, personne ne presse, contre adverse » : minute, phase, fait."},
{i:"k277_10",u:277,t:"tiles",d:.4,q:"Reconstitue la règle des notes.",a:["Une","fois,","c'est","un","fait.","Trois","fois,","c'est","un","plan."],dd:["hasard.","deux"],w:"Le rapport de mi-temps ne parle que des schémas répétés."},
{i:"k277_11",u:277,t:"sort",d:.4,q:"Fait ou avis ?",bins:["Fait","Avis"],it:[["Leur latéral gauche monte à chaque attaque",0],["Leur latéral est nul",1],["Leur 6 décroche entre les centraux à la relance",0],["Ils jouent comme des amateurs",1],["Trois pertes dans notre moitié en 20 minutes",0]],w:"Un fait se vérifie sur la vidéo. Un avis ne sert à rien dans un rapport."},
{i:"k277_12",u:277,t:"story",d:.45,q:"Que notes-tu ?",ctx:"12e, 25e et 38e minutes : chaque fois que Nabil monte, l'ailier de Marcq attaque son couloir en contre.",sc:[{who:"Élodie Marchal",txt:"C'est un accident ou un plan ?"}],o:["Trois fois : un plan, à dire à la pause","Un accident, Nabil n'a simplement pas eu de chance","Un avis personnel, on ne peut rien en conclure","Un fait isolé, qu'il vaut mieux oublier vite"],a:0,w:"Trois fois, c'est un plan : Marcq attaque le couloir de Nabil sur les transitions."},
{i:"k277_13",u:277,t:"mcq",d:.45,q:"Pourquoi noter la phase de jeu à chaque observation ?",o:["Pour savoir quel moment du jeu corriger","Pour occuper le temps pendant le match","Parce que l'arbitre le demande","Pour compter les minutes jouées"],a:0,w:"Un problème en transition défensive ne se corrige pas comme un problème en défense organisée."},
{i:"k277_14",u:277,t:"multi",d:.45,nw:"Les ajustements à la pause",q:"Quels sont les trois leviers d'ajustement à la pause ?",o:["Le système","Le bloc","Le joueur","L'arbitre","Le ballon de match"],a:[0,1,2],w:"Système, bloc, joueur : la question 7 de la grille."},
{i:"k277_15",u:277,t:"match",d:.45,q:"Associe chaque problème à l'ajustement adapté.",p:[["Dominés à 2 contre 3 au milieu","Changer de système"],["Longs ballons dans notre dos","Descendre le bloc"],["Un latéral dépassé à chaque contre","Changer de joueur ou de rôle"],["Pas d'homme libre à la relance","Ajouter un relanceur"]],w:"À chaque problème son levier : système, bloc, joueur ou relance. Changer l'animation suffit parfois, sans toucher au système."},
{i:"k277_16",u:277,t:"story",d:.5,q:"Quel rapport fais-tu à Samir ?",ctx:"Mi-temps, 0-1. Marcq presse en individuel, le Racing relance à trois contre trois et perd le ballon. Leur ailier attaque le couloir de Nabil sur chaque perte.",sc:[{who:"Samir Benhaddou",txt:"Tu as cinq minutes. Trois points."}],o:["« Relance : un quatrième joueur. Nabil reste plus bas. Jeu à trois contre l'individuel »","« On est nuls, il faut courir plus, et l'arbitre est contre nous »","« Tout va bien, on continue exactement pareil »","« On change les onze joueurs et on joue en 2-2-6 »"],a:0,w:"Ce qui ne marche pas, pourquoi, un ajustement par problème : système, bloc, joueur."},
{i:"k277_17",u:277,t:"tf",d:.5,q:"Un bon rapport de mi-temps tient en trois points : ce qui marche, ce qui ne marche pas, un ajustement.",a:true,w:"Court et utile : cinq minutes dans le vestiaire, pas une de plus."},
{i:"k277_18",u:277,t:"fill",d:.5,q:"La fiche de révision se relit ___ minutes avant un match.",o:["5","30","60","1"],a:0,w:"Cinq minutes : la grille s'applique, elle ne s'apprend pas pendant le match."},
{i:"k277_19",u:277,t:"story",d:.5,q:"Que regardes-tu au retour des vestiaires ?",sc:[{who:"Élodie Marchal",txt:"Dix premières minutes de la seconde période : tu observes quoi ?"}],o:["Si Marcq a changé système, bloc ou joueur","Seulement le score, et absolument rien d'autre","La couleur des maillots de Marcq après la pause","Le nombre de spectateurs revenus en tribune"],a:0,w:"Les ajustements adverses se voient dans les dix premières minutes : il faut les repérer vite."},
{i:"k277_20",u:277,t:"order",d:.5,q:"Remets dans l'ordre la journée de l'analyste.",it:["Relire la fiche 5 minutes avant","Observer avec la grille","Noter minute, phase, fait","Faire le rapport de mi-temps en trois points","Repérer les ajustements adverses en seconde période"],w:"Préparer, observer, noter, rapporter, surveiller."},
{i:"k277_21",u:277,t:"mcq",d:.55,q:"Rappel du module 7 : Marcq presse en individuel. Quelle arme conseilles-tu ?",o:["Le jeu à trois","Le jeu long systématique","La relance à deux seulement","Le dribble du gardien"],a:0,w:"Contre l'individuel, la remise vers un troisième homme fait sauter le marquage (module 8)."},
{i:"k277_22",u:277,t:"story",d:.55,q:"Rappel du module 10 : que dis-tu ?",ctx:"Chaque fois que le Racing attaque, seuls deux joueurs restent derrière le ballon. Marcq contre-attaque à trois.",sc:[{who:"Samir Benhaddou",txt:"Question 6 de ta grille ?"}],o:["Rest defense trop légère : passer en 3 + 2","Rest defense parfaite, rien à changer","Il faut encore plus de monde devant","La rest defense ne concerne que les corners"],a:0,w:"Qui reste en rest defense ? Deux, c'est trop peu contre trois attaquants : l'assurance doit être renforcée."},
{i:"k277_23",u:277,t:"tf",d:.55,q:"Les ajustements de l'adversaire ne se voient jamais avant la fin du match.",a:false,w:"Faux : les dix premières minutes de la seconde période révèlent souvent le nouveau système, bloc ou joueur."},
{i:"k277_24",u:277,t:"sort",d:.55,q:"Levier : système, bloc ou joueur ?",bins:["Système","Bloc","Joueur"],it:[["Passer en 4-3-3",0],["Reculer la ligne de dix mètres",1],["Faire entrer un latéral plus défensif",2],["Passer en 3-5-2",0],["Presser plus haut",1],["Demander à Rayan de rester axial",2]],w:"Trois leviers, trois familles d'ajustement."},
{i:"k277_25",u:277,t:"num",d:.6,q:"Dans ton carnet : pertes de balle suivies d'un contre à la 12e, 25e, 38e et 44e. Combien de répétitions de ce schéma ?",a:4,tol:0,un:" fois",h:"Compte les minutes",w:"Quatre fois : bien plus qu'un plan, c'est la faille principale du match."},
{i:"k277_26",u:277,t:"multi",d:.6,q:"Qu'est-ce qui rend un rapport de mi-temps utile ?",o:["Des faits répétés","Un ajustement par problème","Trois points maximum","Des avis sur les joueurs","Un récit minute par minute"],a:[0,1,2],w:"Faits, ajustements, concision. Ni avis ni récit."},
{i:"k277_27",u:277,t:"match",d:.6,q:"Rappel du cours : associe chaque réflexe à son effet.",p:[["Suivre la structure","Voir les espaces libres"],["Observer 5 secondes","Juger les transitions"],["Repérer qui décroche","Trouver qui est libéré"],["Relire la fiche avant","Appliquer la grille sans hésiter"]],w:"Les réflexes transforment le spectateur en observateur."},
{i:"k277_28",u:277,t:"story",d:.6,q:"Rappel du module 12 : Samir te demande les chiffres de la mi-temps.",sc:[{who:"Samir Benhaddou",txt:"On a 60 % de possession, on domine, non ?"}],o:["Il faut les xG : la possession trompe","Oui, 60 % de possession suffit largement à le prouver","Non, il faudrait au moins 80 % pour dominer vraiment","Oui, et on va forcément gagner ce match à la fin"],a:0,w:"La possession dit qui a le ballon. Les xG et la grille disent qui crée."},
{i:"k277_29",u:277,t:"fill",d:.6,q:"Dans un rapport, on sépare les faits des ___.",o:["avis","chiffres","minutes","phases"],a:0,w:"Un avis (« il est nul ») ne se corrige pas. Un fait (« il monte à chaque attaque ») si."},
{i:"k277_30",u:277,t:"tf",d:.6,q:"La grille s'apprend pendant le match, en regardant l'action.",a:false,w:"Elle se relit avant et s'applique pendant. Pendant le match, on n'apprend pas : on observe."},
{i:"k277_31",u:277,t:"mcq",d:.6,q:"Quelle question de la grille vient en dernier ?",o:["Les ajustements à la pause","La hauteur du bloc","Le joueur libre à la relance","Les 5 secondes après la perte"],a:0,w:"Bloc, Presse, Décroche, Libre, Cinq, Reste, Pause."},
{i:"k277_32",u:277,t:"story",d:.6,q:"Synthèse : Élodie te félicite et te demande ta méthode.",sc:[{who:"Élodie Marchal",txt:"Explique ta méthode à Mehdi en une phrase."}],o:["« Grille en 7 questions, 3 réflexes, faits répétés, ajustement proposé »","« Je regarde le ballon et je crie sur l'arbitre »","« Je compte les passes et je devine le reste »","« Je lis le score et je compare avec la possession »"],a:0,w:"Grille, réflexes, notes, rapport : la méthode de l'observateur."}
