/*UNIT*/
{id:199,c:"SPINO",n:"Module 1",t:"Le succès qui rend triste : l'énigme de départ",col:"--purple",ic:"🏆",guide:`
<h3>La soirée de Léa</h3>
<div class="gstory">Bordeaux, quai des Chartrons, un jeudi soir de septembre. Léa Marchetti, 29 ans, fondatrice de Cargo &amp; Co (des vélos cargo pour les livreurs), vient d'annoncer une levée de fonds de 2 millions d'euros. Champagne, messages de félicitations, article dans le journal local. À minuit, elle appelle son grand frère Julien, professeur de philosophie au lycée Montaigne : « Je devrais être la femme la plus heureuse du monde. Et je me sens vide. Je suis folle ? » Julien pose son livre, l'<i>Éthique</i> de Spinoza : « Non. Tu viens de rencontrer le problème que ce type a passé sa vie à résoudre. Viens dimanche, je t'explique. » Ce cours, ce sont ces dimanches.</div>
<h3>L'impasse de l'ambitieux</h3>
<p>Ce cours s'appuie sur la vidéo de l'entrepreneur <b>Théo Lion</b>, « De la droite manière d'entreprendre », tournée à Amsterdam, et sur l'<i>Éthique</i> de Spinoza. Théo Lion décrit une « pénible déroute mentale » en trois temps :</p>
<table><tr><th>Étape</th><th>Ce qu'on vit</th></tr>
<tr><td>1. Le questionnement</td><td>À quoi bon souffrir au travail si le succès ne rend pas plus heureux ?</td></tr>
<tr><td>2. L'abattement</td><td>Renoncer au succès semble condamner à une vie banale, celle que l'ambitieux fuit</td></tr>
<tr><td>3. L'égarement</td><td>Même convaincu, on n'arrive pas à éteindre le désir de réussir</td></tr></table>
<p>Résultat : on est coincé entre une course au succès qui peut rendre malheureux et une vie sans ambition qu'on passera à combattre. C'est « la peste ou le choléra ». Or, constate Théo Lion, certains entrepreneurs chassent le succès <b>et</b> sont heureux. Pourquoi le succès est-il tantôt remède, tantôt poison ?</p>
<p>Spinoza répond dans la préface de la partie IV de l'<i>Éthique</i> : « Une seule et même chose peut être en même temps bonne et mauvaise, et aussi indifférente. Par exemple, la <b>musique</b> est bonne pour le mélancolique, mauvaise pour l'affligé, ni bonne ni mauvaise pour le sourd. » Le bien et le mal ne sont pas dans les choses : ils dépendent de ce qu'elles font <b>à quelqu'un</b>.</p>
<h3>Ce que veut vraiment dire « succès »</h3>
<ul><li>Le mot vient du latin <b>successus</b>, de <i>succedere</i> : « arriver à la suite », « advenir ». En latin classique, c'est l'<b>issue</b> d'une affaire, bonne ou mauvaise : on pouvait parler d'un <i>successus adversus</i>, un « mauvais succès ». Tacite l'emploie pour les issues incertaines des campagnes de Germanicus.</li>
<li>À la fin du XVIIe siècle, l'usage retient surtout les issues heureuses. Le dictionnaire de l'Académie française de <b>1694</b> note que le mot « se dit ordinairement en bonne part ». Le sens neutre disparaît au XIXe siècle.</li>
<li>Conclusion de Théo Lion : le succès n'est pas une qualité de l'action, c'est un <b>événement extérieur</b> et <b>contingent</b> (qui peut arriver ou non) : chiffre d'affaires, argent levé, croissance, articles de presse. Ces indicateurs publics et comparables ne disent rien, en eux-mêmes, d'un vrai progrès intérieur.</li></ul>
<div class="gmnemo"><b>« Le succès succède, la joie grandit. »</b> Le succès, c'est ce qui arrive <b>après</b> et <b>dehors</b> ; la joie, c'est ce qui grandit <b>dedans</b>. Et pour la musique : <b>« Mélancolique, affligé, sourd : bon, mauvais, indifférent. »</b></div>
<h3>Bonheur n'est pas béatitude</h3>
<p>Théo Lion évite le mot <b>bonheur</b> : il vient de « bon heur », et « heur » vient du latin <i>augurium</i>, le présage, puis la chance. Le bonheur, c'est littéralement une bonne fortune, un coup de chance. Or Spinoza cherche justement une joie qui <b>ne dépend pas</b> de la chance : il l'appelle la <b>béatitude</b>, une joie stable (module 15).</p>
<h3>Le témoignage de Théo Lion</h3>
<p>Sa première année d'entreprise : 23 300 € de chiffre d'affaires, sous l'objectif de 30 000 €, et pourtant « un souvenir incroyable ». En 2024 : 5,3 millions d'euros. Et le cap du million ? « J'étais content, mais très vite… tu n'es pas surpris, et tu as l'impression que tu dois l'être parce que les autres l'attendent. » Plus de succès n'a pas donné plus de joie.</p>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Expliquer l'impasse de l'ambitieux en trois temps</li><li>Donner l'étymologie de succès et de bonheur</li><li>Citer l'exemple de la musique et en tirer la relativité du bien</li><li>Distinguer issue extérieure et transformation intérieure</li></ul>`},
/*EXOS*/
{i:"s199_01",u:199,t:"story",d:.2,nw:"Le succès peut rendre triste",q:"Léa se sent vide après sa levée de fonds. Que lui répond Julien ?",sc:[{who:"Léa",txt:"J'ai tout ce que je voulais et je me sens vide. Je suis folle ?"}],o:["« Non : un succès extérieur ne garantit pas une joie intérieure. »","« Oui, avec deux millions, tu devrais être heureuse, c'est ton problème. »","« C'est la fatigue, dors deux jours et la joie reviendra toute seule. »","« Lève encore plus d'argent, la joie arrive toujours au deuxième tour. »"],a:0,w:"C'est l'énigme de départ du cours : le succès est une issue extérieure, la joie une transformation intérieure. Le succès succède, la joie grandit."},
{i:"s199_02",u:199,t:"order",d:.2,q:"Remets dans l'ordre la « pénible déroute mentale » de l'ambitieux décrite par Théo Lion.",it:["Le questionnement","L'abattement","L'égarement"],w:"On se demande à quoi bon, puis renoncer paraît banal, puis on n'arrive pas à éteindre le désir. D'où l'impasse."},
{i:"s199_03",u:199,t:"fill",d:.25,q:"Le mot succès vient du latin ___, « ce qui arrive à la suite ».",o:["successus","sucrosus","secessionis","sucessor"],a:0,w:"Successus, de succedere. En latin classique, c'est l'issue d'une affaire, heureuse ou malheureuse."},
{i:"s199_04",u:199,t:"match",d:.25,q:"Associe chaque personne à l'effet de la musique selon Spinoza.",p:[["Le mélancolique","Bonne"],["L'affligé","Mauvaise"],["Le sourd","Ni bonne ni mauvaise"],["Conclusion","Le bien dépend de ce que la chose fait à quelqu'un"]],w:"Préface de la partie IV de l'Éthique. Mélancolique, affligé, sourd : bon, mauvais, indifférent."},
{i:"s199_05",u:199,t:"tf",d:.25,q:"En latin classique, on pouvait parler d'un « mauvais succès ».",a:true,w:"Successus adversus : une issue défavorable. Le sens de « réussite » ne s'impose qu'à partir de la fin du XVIIe siècle."},
{i:"s199_06",u:199,t:"mcq",d:.3,q:"D'où vient le mot « bonheur » ?",o:["De « bon heur », une bonne chance","Du latin « bonus hora », la bonne heure","Du grec « eudaimonia »","D'un mot de Spinoza"],a:0,w:"« Heur » vient du latin augurium, le présage, puis la chance. Le bonheur est une bonne fortune ; Spinoza cherche une joie qui n'en dépend pas."},
{i:"s199_07",u:199,t:"sort",d:.3,q:"Classe chaque élément : succès (issue extérieure) ou joie (transformation intérieure) ?",bins:["Succès","Joie"],it:[["Une levée de 2 millions",0],["Comprendre enfin la comptabilité",1],["Un article dans le journal",0],["Savoir conduire après le permis",1],["Passer le million de chiffre d'affaires",0],["Maîtriser un nouveau métier",1]],w:"Le succès se mesure dehors, avec des indicateurs publics. La joie accompagne un gain de capacité : on sait faire plus."},
{i:"s199_08",u:199,t:"story",d:.3,q:"Samir, développeur, dit que « 5 000 € de plus par mois ne peuvent pas rendre plus malheureux ». Que réponds-tu ?",sc:[{who:"Samir",txt:"Franchement, gagner plus, ça ne peut que rendre plus heureux."}],o:["« Ça dépend de ce que cet argent fait à ta vie, pas de l'argent lui-même. »","« Tu as raison, chaque euro de plus ajoute toujours un peu de joie en toi. »","« Au contraire, l'argent rend toujours malheureux, il faut s'en méfier. »","« Seuls les millionnaires peuvent se poser ce genre de question, pas toi. »"],a:0,w:"Comme la musique, une même chose est bonne, mauvaise ou indifférente selon ce qu'elle fait à quelqu'un. Spinoza ne condamne pas l'argent."},
{i:"s199_09",u:199,t:"multi",d:.35,q:"Quels indicateurs du « succès entrepreneurial » cite Théo Lion ?",o:["La rentabilité","L'argent levé","La croissance","La reconnaissance médiatique","La joie de l'entrepreneur"],a:[0,1,2,3],w:"Quatre indicateurs publics et comparables. Aucun ne dit en lui-même si l'entrepreneur a gagné en puissance ou en joie."},
{i:"s199_10",u:199,t:"slider",d:.35,q:"En quelle année le dictionnaire de l'Académie française note-t-il que « succès » se dit surtout en bonne part ?",min:1600,max:1800,step:1,a:1694,tol:0,pre:"",un:"",w:"1694, première édition du dictionnaire de l'Académie. Le sens neutre disparaît complètement au XIXe siècle."},
{i:"s199_11",u:199,t:"tiles",d:.35,q:"Reconstitue la formule qui oppose succès et joie.",a:["Le","succès","succède","la","joie","grandit"],dd:["réussit","stagne","dehors"],w:"Le succès arrive après et dehors ; la joie grandit dedans."},
{i:"s199_12",u:199,t:"fill",d:.4,q:"Un événement qui peut arriver ou ne pas arriver est dit ___.",o:["contingent","nécessaire","éternel","absolu"],a:0,w:"Contingent. Le succès est contingent : il dépend de causes extérieures. C'est ce qui le rend fragile."},
{i:"s199_13",u:199,t:"story",d:.4,q:"Anaïs, l'associée de Léa, s'étonne : « On a triplé le chiffre d'affaires et l'équipe est moins joyeuse qu'au début ». Qu'en dis-tu ?",sc:[{who:"Anaïs",txt:"Au début, on n'avait rien et on était heureux. C'est absurde."}],o:["« Au début, vous appreniez tout chaque jour : c'est ça qui rendait joyeux. »","« C'est absurde en effet, il faut changer toute l'équipe au plus vite. »","« La joie baisse toujours avec le chiffre d'affaires, c'est mathématique. »","« Au début, vous étiez simplement plus jeunes et moins fatigués qu'aujourd'hui. »"],a:0,w:"Théo Lion le raconte : 23 300 € la première année, et un souvenir incroyable. Les débuts sont bourrés d'apprentissage, donc de gain de puissance."},
{i:"s199_14",u:199,t:"tf",d:.4,q:"Selon Théo Lion, franchir le million de chiffre d'affaires lui a apporté une joie immense et durable.",a:false,w:"Il était content, mais « pas surpris », avec l'impression de devoir l'être parce que les autres l'attendaient. Plus de succès n'a pas donné plus de joie."},
{i:"s199_15",u:199,t:"num",d:.45,q:"La première année, Théo Lion visait 30 000 € et a fait 23 300 €. Quel pourcentage de l'objectif a-t-il atteint (arrondi) ?",a:78,tol:1,un:" %",h:"23 300 / 30 000 × 100",w:"Environ 78 % de l'objectif, et pourtant un souvenir incroyable. La joie ne suivait pas le chiffre, elle suivait l'apprentissage."},
{i:"s199_16",u:199,t:"mcq",d:.45,q:"Dans quel livre Spinoza donne-t-il l'exemple de la musique ?",o:["L'Éthique","Le Discours de la méthode","Les Pensées","Le Prince"],a:0,w:"Dans la préface de la partie IV de l'Éthique. Le Discours est de Descartes, les Pensées de Pascal, le Prince de Machiavel."},
{i:"s199_17",u:199,t:"story",d:.45,q:"La mère de Léa, Maud, lui dit : « Ta levée prouve enfin ce que tu vaux ». Comment Julien reformule-t-il ?",sc:[{who:"Maud",txt:"Maintenant, tout le monde sait que tu as réussi."}],o:["« Elle prouve qu'une affaire a bien tourné, pas ce que tu vaux. »","« Maman a raison, ta valeur se mesure exactement au montant levé. »","« Ta valeur se mesurera seulement le jour où tu revendras la boîte. »","« Ta valeur dépend uniquement de ce que pensent tes investisseurs. »"],a:0,w:"Le succès est une issue extérieure et contingente. La valeur d'une personne ne se lit pas dans un indicateur public."},
{i:"s199_18",u:199,t:"sort",d:.5,q:"Classe chaque mot : proche de la chance ou proche de la joie stable ?",bins:["Chance, fortune","Joie stable"],it:[["Bonheur",0],["Béatitude",1],["Bon heur",0],["Augurium",0],["Joie qui ne dépend pas du hasard",1]],w:"Le bonheur est une bonne fortune ; la béatitude, une joie qui ne dépend pas de la chance. Spinoza vise la seconde."},
{i:"s199_19",u:199,t:"fill",d:.5,q:"Pour Spinoza, la joie qui ne dépend plus de la chance s'appelle la ___.",o:["béatitude","fortune","gloire","prospérité"],a:0,w:"La béatitude, forme la plus haute et la plus stable de la joie (module 15)."},
{i:"s199_20",u:199,t:"match",d:.5,q:"Associe chaque étape de l'impasse à sa description.",p:[["Questionnement","À quoi bon souffrir si le succès ne rend pas heureux ?"],["Abattement","Renoncer semble mener à une vie banale"],["Égarement","On n'arrive pas à éteindre le désir de réussir"],["Impasse","La peste ou le choléra"]],w:"L'impasse explique, selon Théo Lion, la dépression de certains entrepreneurs pourtant couronnés de succès."},
{i:"s199_21",u:199,t:"story",d:.55,q:"Samir cite un conseil de « stoïcien de YouTube » : « contrôle ta réaction aux choses ». Qu'en pense Théo Lion ?",sc:[{who:"Samir",txt:"Il suffit de contrôler ses émotions, non ?"}],o:["« Il lui faut une méthode plus forte qu'une injonction à se contrôler. »","« C'est exactement la méthode de Spinoza, il suffit de vouloir fort. »","« Il pense que les émotions sont inutiles et qu'il faut les supprimer. »","« Il pense qu'il faut se laisser aller à toutes ses émotions sans réfléchir. »"],a:0,w:"Théo Lion n'arrivait pas à appliquer ce conseil. Spinoza propose une autre méthode, fondée sur la compréhension des causes (modules 11 à 13)."},
{i:"s199_22",u:199,t:"tf",d:.55,q:"Pour Spinoza, le bien et le mal sont des qualités fixes contenues dans les choses.",a:false,w:"Une même chose peut être bonne, mauvaise ou indifférente selon la personne. Le bien et le mal sont relatifs à ce que la chose fait à quelqu'un."},
{i:"s199_23",u:199,t:"multi",d:.6,q:"Qu'est-ce qui caractérise le succès au sens moderne selon Théo Lion ?",o:["Un événement extérieur","Un résultat contingent","Des indicateurs publics","Une chose distincte de l'acte","Une qualité de l'action elle-même"],a:[0,1,2,3],w:"Le succès n'est pas une qualité de l'action : c'est l'issue qui en résulte, dehors, et qui peut arriver ou non."},
{i:"s199_24",u:199,t:"mcq",d:.6,q:"Quel titre porte la vidéo de Théo Lion ?",o:["De la droite manière d'entreprendre","Spinoza pour les entrepreneurs","L'éthique secrète du milliardaire","Le stoïcisme appliqué au bureau"],a:0,w:"« De la droite manière d'entreprendre » : une manière d'entreprendre qui mène vraiment à la joie."},
{i:"s199_25",u:199,t:"story",d:.65,q:"Victor, l'investisseur de Léa, lui dit : « Le succès, c'est quand tout va bien ». Que corrige Julien en pensant au latin ?",sc:[{who:"Victor",txt:"Le succès, par définition, c'est une bonne nouvelle."}],o:["« À l'origine, c'est l'issue d'une affaire, bonne ou mauvaise. »","« Il a raison, le mot a toujours voulu dire réussite, depuis Rome. »","« À l'origine, le succès désignait uniquement une victoire militaire. »","« Le mot succès a été inventé par Spinoza pour parler de la joie. »"],a:0,w:"Successus : ce qui arrive à la suite. Spinoza invite, selon Théo Lion, à retrouver cette neutralité."},
{i:"s199_26",u:199,t:"slider",d:.65,q:"Quel chiffre d'affaires (en millions d'euros) la société de Théo Lion a-t-elle réalisé en 2024 ?",min:0,max:10,step:.1,a:5.3,tol:.1,pre:"",un:" M€",w:"5,3 millions, contre 23 300 € la première année. Et la joie n'a pas grandi dans les mêmes proportions."},
{i:"s199_27",u:199,t:"tiles",d:.7,q:"Reconstitue la phrase de Spinoza sur la musique (pour les trois personnes).",a:["bonne","pour","le","mélancolique","mauvaise","pour","l'affligé"],dd:["heureux","joyeux","toujours"],w:"Et ni bonne ni mauvaise pour le sourd. Éthique, IV, préface."},
{i:"s199_28",u:199,t:"sort",d:.7,q:"Classe chaque phrase : fidèle à Spinoza ou contraire ?",bins:["Fidèle","Contraire"],it:[["Une chose peut être bonne pour l'un et mauvaise pour l'autre",0],["Il faut renoncer à toute ambition",1],["Le succès ne garantit pas la joie",0],["L'argent est mauvais en soi",1]],w:"Spinoza n'est ni un moraliste ni un ascète : il ne condamne ni l'argent ni l'ambition, il cherche ce qui rend vraiment joyeux."},
{i:"s199_29",u:199,t:"story",d:.75,q:"Léa demande à Julien pourquoi lire un philosophe du XVIIe siècle pour sa start-up.",sc:[{who:"Léa",txt:"Spinoza, c'est vieux. En quoi ça m'aide ?"}],o:["« Il cherche une joie qui dure au lieu d'alterner joie et tristesse. »","« Il a fondé plusieurs entreprises à succès à Amsterdam à son époque. »","« Il explique comment lever des fonds auprès des banquiers hollandais. »","« Il recommande de fuir le monde des affaires pour vivre seul. »"],a:0,w:"Les biens ordinaires sont éphémères ; l'Éthique cherche un bien qui procure une joie permanente, compatible avec l'envie d'accomplir."},
{i:"s199_30",u:199,t:"fill",d:.75,q:"Théo Lion constate que certains entrepreneurs chassent le succès et sont pourtant ___.",o:["heureux","ruinés","isolés","épuisés"],a:0,w:"C'est ce qui rend l'énigme intéressante : le succès n'est pas toujours un poison. Tout dépend de ce qu'on désire à travers lui."},
{i:"s199_31",u:199,t:"mcq",d:.8,q:"Pourquoi Théo Lion n'emploie-t-il pas le mot « bonheur » ?",o:["Il renvoie à la chance, dont on veut se libérer","Spinoza l'a interdit dans tous ses livres","Il est trop récent dans la langue française","Il désigne uniquement la richesse matérielle"],a:0,w:"Bonheur = bon heur, bonne fortune. La béatitude spinoziste, elle, repose sur l'action et la connaissance, pas sur le hasard."},
{i:"s199_32",u:199,t:"story",d:.85,q:"Synthèse : en une phrase, comment Julien résume-t-il l'énigme à Léa ?",sc:[{who:"Léa",txt:"Alors, c'est quoi mon problème exactement ?"}],o:["« Tu as eu le succès dehors sans la joie dedans : cherchons pourquoi. »","« Tu n'as pas assez réussi : il faudra lever dix millions pour être heureuse. »","« Tu es trop ambitieuse : il faut tout arrêter et changer de vie dès demain. »","« Tu es simplement ingrate envers ceux qui t'ont aidée à lever ces fonds. »"],a:0,w:"Le succès succède, la joie grandit. La suite du cours explique la cause de ce décalage, et comment le réparer."}
