/*UNIT*/
{id:201,c:"SPINO",n:"Module 3",t:"L'Éthique : un livre écrit comme un traité de géométrie",col:"--purple",ic:"📐",guide:`
<h3>Le livre qui fait peur</h3>
<div class="gstory">Dans le train du retour, Julien offre à Léa une édition de poche de l'<i>Éthique</i>. Elle l'ouvre au hasard : « Proposition 9. Démonstration. Corollaire. Scolie… » Elle referme, découragée : « On dirait mon manuel de maths de terminale. » Samir, le développeur qui partage la table, jette un œil : « Moi j'aime bien, c'est comme du code : des définitions, des règles, et tout s'enchaîne. » Julien rit : « Vous avez raison tous les deux. Et je vais vous apprendre à le lire par la bonne porte. »</div>
<h3>Le titre dit tout</h3>
<p>Le titre complet, en latin, est <b><i>Ethica ordine geometrico demonstrata</i></b> : « L'Éthique démontrée selon l'ordre géométrique ». Spinoza y travaille pendant près de quinze ans (environ 1661 à 1675). Il imite la méthode d'<b>Euclide</b>, le géomètre grec : on pose des définitions et des axiomes, puis on démontre des propositions, qui s'enchaînent comme des théorèmes.</p>
<p>Pourquoi parler de la vie comme de géométrie ? Pour ne pas juger. Dans la préface de la partie III, il annonce qu'il traitera des actions et des désirs humains « comme s'il était question de <b>lignes, de plans ou de corps</b> ». On ne reproche pas à un triangle d'avoir trois angles : on ne reproche pas non plus à un homme d'être en colère. On <b>comprend</b> pourquoi.</p>
<h3>Les cinq parties</h3>
<table><tr><th>Partie</th><th>Titre</th><th>Dans ce cours</th></tr>
<tr><td>I</td><td>De <b>Dieu</b></td><td>Module 4</td></tr>
<tr><td>II</td><td>De la nature et de l'origine de l'<b>esprit</b></td><td>Modules 5, 6, 12</td></tr>
<tr><td>III</td><td>De l'origine et de la nature des <b>affects</b></td><td>Modules 7, 8, 9</td></tr>
<tr><td>IV</td><td>De la <b>servitude</b> humaine, ou des forces des affects</td><td>Modules 10, 14</td></tr>
<tr><td>V</td><td>De la puissance de l'entendement, ou de la <b>liberté</b> humaine</td><td>Modules 13, 15</td></tr></table>
<div class="gmnemo"><b>« Des Esprits Affectés Sont Libérables »</b> : Dieu, Esprit, Affects, Servitude, Liberté. Le livre va de Dieu à la liberté : il part de tout ce qui existe pour arriver à toi et à ta joie.</div>
<h3>Les briques du texte</h3>
<table><tr><th>Élément</th><th>Rôle</th></tr>
<tr><td>Définition</td><td>Fixe le sens d'un mot (par exemple, la joie)</td></tr>
<tr><td>Axiome</td><td>Vérité posée comme évidente, sans démonstration</td></tr>
<tr><td>Proposition</td><td>Thèse à démontrer</td></tr>
<tr><td>Démonstration</td><td>Preuve qui s'appuie sur ce qui précède</td></tr>
<tr><td>Corollaire</td><td>Conséquence directe d'une proposition</td></tr>
<tr><td><b>Scolie</b></td><td>Commentaire libre, souvent polémique et concret : le cœur vivant du livre</td></tr>
<tr><td>Préface, appendice</td><td>Textes en prose au début ou à la fin d'une partie</td></tr></table>
<p>On cite l'<i>Éthique</i> avec un code : <b>E3P9S</b> veut dire « partie III, proposition 9, scolie ». Le philosophe Gilles Deleuze conseillait de commencer par les <b>scolies, préfaces et appendices</b>, qui forment comme un second livre, plus brûlant, caché dans le premier.</p>
<h3>Éthique n'est pas morale</h3>
<table><tr><th>Morale</th><th>Éthique (au sens de Spinoza)</th></tr>
<tr><td>Le Bien et le Mal, absolus</td><td>Le bon et le mauvais, relatifs à chacun (la musique, module 1)</td></tr>
<tr><td>Des devoirs, des commandements</td><td>Un art de vivre, une recherche de ce qui augmente la puissance</td></tr>
<tr><td>Juger, blâmer, punir</td><td>Comprendre les causes</td></tr></table>
<p>C'est ce qui frappe Théo Lion : « Ce n'est pas du tout un moraliste, c'est très apaisant. Tu as l'impression que c'est un pote qui te raconte des trucs, il n'y a jamais d'injonction. »</p>
<h3>Les autres œuvres</h3>
<ul><li><b>Traité de la réforme de l'entendement</b> (inachevé) : son prologue raconte sa conversion. Il a constaté que les trois biens poursuivis par la plupart des gens, la <b>richesse</b>, les <b>honneurs</b> et le <b>plaisir des sens</b>, sont vains, et il cherche un bien véritable. Il avoue : même en le voyant clairement, « je ne pouvais cependant pas renoncer à toute cupidité, sensualité et gloire ».</li>
<li><b>Traité théologico-politique</b> (1670) : défense de la liberté de penser et de lire la Bible comme un livre historique.</li>
<li><b>Traité politique</b> (inachevé) : « ne pas rire, ne pas pleurer, ne pas détester, mais <b>comprendre</b> » les actions humaines.</li>
<li>Une <b>correspondance</b> avec les savants de son temps.</li></ul>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Donner le titre latin et expliquer la méthode géométrique</li><li>Nommer les cinq parties dans l'ordre</li><li>Reconnaître les briques du texte et lire une référence comme E4P7</li><li>Distinguer éthique et morale</li></ul>`},
/*EXOS*/
{i:"s201_01",u:201,t:"story",d:.2,nw:"La méthode géométrique",q:"Léa trouve que l'Éthique ressemble à un manuel de maths. Que lui explique Julien ?",sc:[{who:"Léa",txt:"Pourquoi écrire sur la vie comme sur des triangles ?"}],o:["« Pour comprendre les passions sans juger, comme on étudie des figures. »","« Parce qu'il était professeur de mathématiques à l'université de Leyde. »","« Pour que personne ne puisse le lire et qu'il échappe à la censure. »","« Parce qu'au XVIIe siècle, tous les livres devaient être écrits ainsi. »"],a:0,w:"Préface de la partie III : traiter des actions humaines comme de lignes, de plans ou de corps. On ne blâme pas un triangle, on le comprend."},
{i:"s201_02",u:201,t:"order",d:.2,q:"Remets dans l'ordre les cinq parties de l'Éthique.",it:["De Dieu","De l'esprit","Des affects","De la servitude humaine","De la liberté humaine"],w:"Des Esprits Affectés Sont Libérables : Dieu, Esprit, Affects, Servitude, Liberté."},
{i:"s201_03",u:201,t:"fill",d:.25,q:"Le titre latin complet est Ethica ordine ___ demonstrata.",o:["geometrico","mathematico","philosophico","theologico"],a:0,w:"L'Éthique démontrée selon l'ordre géométrique, sur le modèle d'Euclide."},
{i:"s201_04",u:201,t:"match",d:.25,q:"Associe chaque élément du texte à son rôle.",p:[["Axiome","Vérité posée sans démonstration"],["Proposition","Thèse à démontrer"],["Corollaire","Conséquence directe"],["Scolie","Commentaire libre et concret"]],w:"Le squelette (définitions, axiomes, propositions, démonstrations) et la chair (scolies, préfaces, appendices)."},
{i:"s201_05",u:201,t:"tf",d:.25,q:"Spinoza a écrit l'Éthique en latin.",a:true,w:"Comme la plupart des livres savants de son temps. On le lit en français grâce aux traductions (Appuhn, Misrahi, Pautrat)."},
{i:"s201_06",u:201,t:"num",d:.3,q:"Dans la référence E4P37, quel est le numéro de la proposition ?",a:37,tol:0,un:"",h:"E = Éthique, 4 = partie, P = proposition",w:"Partie IV, proposition 37. Avec S pour scolie, C pour corollaire, D pour démonstration."},
{i:"s201_07",u:201,t:"mcq",d:.3,q:"Sur le modèle de quel auteur Spinoza construit-il sa méthode ?",o:["Euclide, le géomètre grec","Platon, le philosophe athénien","Machiavel, le penseur florentin","Pascal, le mathématicien français"],a:0,w:"Les Éléments d'Euclide : définitions, axiomes, propositions démontrées. Spinoza applique cet ordre à Dieu, à l'esprit et aux passions."},
{i:"s201_08",u:201,t:"sort",d:.3,q:"Classe chaque phrase : morale ou éthique au sens de Spinoza ?",bins:["Morale","Éthique"],it:[["Tu dois, tu ne dois pas",0],["Ce qui augmente ma puissance d'agir",1],["Le Mal absolu",0],["Comprendre les causes plutôt que blâmer",1],["Punir le pécheur",0],["Bon pour moi, mauvais pour un autre",1]],w:"La morale commande et juge ; l'éthique cherche ce qui convient à chacun et comprend. Spinoza n'est pas un moraliste."},
{i:"s201_09",u:201,t:"story",d:.35,q:"Samir veut lire l'Éthique de la première à la dernière page. Que lui conseille Julien ?",sc:[{who:"Samir",txt:"Je commence page 1 et je ne saute rien."}],o:["« Commence par les scolies, préfaces et appendices, comme disait Deleuze. »","« Commence par la dernière page, c'est toujours là que se cache la solution. »","« Lis uniquement les définitions, le reste est inutile pour comprendre. »","« Ne lis rien, regarde les vidéos YouTube, c'est exactement la même chose. »"],a:0,w:"Les scolies forment un second livre, plus concret et plus polémique. Ensuite, on revient aux démonstrations."},
{i:"s201_10",u:201,t:"fill",d:.35,q:"La devise du Traité politique : « ne pas rire, ne pas pleurer, ne pas détester, mais ___ ».",o:["comprendre","pardonner","oublier","corriger"],a:0,w:"Comprendre. C'est la même attitude que la méthode géométrique : étudier les passions sans les juger."},
{i:"s201_11",u:201,t:"multi",d:.4,q:"Quels biens, selon le prologue du Traité de la réforme de l'entendement, la plupart des gens poursuivent-ils ?",o:["La richesse","Les honneurs","Le plaisir des sens","La gloire et la réputation","La connaissance de la nature"],a:[0,1,2,3],w:"Richesse, honneurs (la gloire), plaisir sensuel : trois biens instables. Spinoza cherche un vrai bien, qu'il trouvera dans la connaissance."},
{i:"s201_12",u:201,t:"tiles",d:.4,q:"Reconstitue le moyen mnémotechnique des cinq parties.",a:["Des","Esprits","Affectés","Sont","Libérables"],dd:["Moraux","Punis","Riches"],w:"Dieu, Esprit, Affects, Servitude, Liberté."},
{i:"s201_13",u:201,t:"tf",d:.4,q:"Pour Spinoza, il faut blâmer les hommes pour leurs passions, comme on punit une faute.",a:false,w:"Il veut les comprendre « comme des lignes, des plans ou des corps ». Blâmer n'explique rien et n'aide pas à changer."},
{i:"s201_14",u:201,t:"story",d:.45,q:"Léa demande ce que Théo Lion aime chez Spinoza. Que répond Julien ?",sc:[{who:"Léa",txt:"Pourquoi un entrepreneur accroche à un philosophe aussi austère ?"}],o:["« Il n'est pas moraliste : il parle comme un pote, sans injonction. »","« Il donne une liste de règles strictes à appliquer chaque matin. »","« Il promet la richesse à ceux qui suivent sa méthode géométrique. »","« Il explique qu'il faut mépriser l'argent et vivre dans la pauvreté. »"],a:0,w:"« C'est très apaisant, tu as l'impression que c'est un pote qui te raconte des trucs. » L'éthique décrit, elle ne commande pas."},
{i:"s201_15",u:201,t:"mcq",d:.45,q:"Que signifie la lettre S dans une référence comme E3P9S ?",o:["Scolie","Section","Sommaire","Supplément"],a:0,w:"Scolie : le commentaire libre qui suit une proposition. E3P9S = partie III, proposition 9, scolie."},
{i:"s201_16",u:201,t:"match",d:.45,q:"Associe chaque partie au thème étudié dans ce cours.",p:[["Partie I","Dieu ou la Nature"],["Partie III","Les affects : désir, joie, tristesse"],["Partie IV","La servitude"],["Partie V","La liberté et la béatitude"]],w:"Le livre part de tout ce qui existe (Dieu) pour arriver à la liberté humaine."},
{i:"s201_17",u:201,t:"slider",d:.5,q:"Pendant environ combien d'années Spinoza a-t-il travaillé à l'Éthique ?",min:1,max:40,step:1,a:15,tol:2,pre:"",un:" ans",w:"Environ quinze ans, de 1661 à 1675. Puis il renonce à la publier ; ses amis le feront en 1677."},
{i:"s201_18",u:201,t:"story",d:.5,q:"Samir s'énerve : « Avec des définitions partout, c'est froid, il n'y a pas d'émotion ». Que réponds-tu ?",sc:[{who:"Samir",txt:"Un livre sur la joie ne devrait pas ressembler à du code."}],o:["« La rigueur sert à comprendre les émotions sans se laisser noyer. »","« Tu as raison, Spinoza ne parle jamais des émotions dans tout son livre. »","« C'est froid exprès, Spinoza voulait qu'on supprime toutes nos émotions. »","« Les définitions sont là pour décorer, il ne faut surtout pas les lire. »"],a:0,w:"La partie III est entièrement consacrée aux affects, avec 48 définitions. La méthode géométrique est un outil pour les comprendre. Les Opera posthuma de 1677 contiennent l'Éthique et ses 48 définitions des affects."},
{i:"s201_19",u:201,t:"fill",d:.5,q:"Le Traité théologico-politique, paru en 1670, défend avant tout la liberté de ___.",o:["penser","commercer","voyager","voter"],a:0,w:"La liberté de philosopher. Spinoza y soutient que l'État doit laisser chacun penser et dire ce qu'il pense."},
{i:"s201_20",u:201,t:"sort",d:.55,q:"Classe chaque texte : de Spinoza ou d'un autre auteur ?",bins:["Spinoza","Autre auteur"],it:[["Traité de la réforme de l'entendement",0],["Discours de la méthode",1],["Traité politique",0],["Les Passions de l'âme",1],["Éthique",0],["Manuel d'Épictète",1]],w:"Le Discours de la méthode et les Passions de l'âme sont de Descartes ; le Manuel, d'Épictète (rédigé par son élève Arrien). Spinoza les a tous lus."},
{i:"s201_21",u:201,t:"tf",d:.55,q:"Spinoza avoue qu'en voyant clairement le vrai bien, il n'arrivait pas pour autant à renoncer à la gloire et à la richesse.",a:true,w:"Prologue du Traité de la réforme de l'entendement. Savoir ne suffit pas : c'est tout le problème que l'Éthique va résoudre (module 10)."},
{i:"s201_22",u:201,t:"mcq",d:.6,q:"Quel philosophe du XXe siècle voyait dans les scolies un « second livre » caché dans l'Éthique ?",o:["Gilles Deleuze","Jean-Paul Sartre","Albert Camus","Michel Foucault"],a:0,w:"Deleuze, dans Spinoza, philosophie pratique (1981). Il parle d'une Éthique volcanique sous l'Éthique démonstrative."},
{i:"s201_23",u:201,t:"story",d:.6,q:"Léa veut une seule partie à lire pour son problème d'entrepreneuse. Laquelle conseille Julien d'abord ?",sc:[{who:"Léa",txt:"Je n'ai pas le temps de tout lire. Par où je commence ?"}],o:["« La partie III sur les affects, puis la IV sur la servitude. »","« La partie I sur Dieu, rien d'autre n'est vraiment utile pour toi. »","« Les définitions de la partie II, qui expliquent tout le livre. »","« Aucune, l'Éthique ne parle absolument pas de la vie concrète. »"],a:0,w:"Les parties III et IV décrivent le désir, la joie, la tristesse et pourquoi on désire ce qui nous rend triste. C'est le diagnostic de Léa."},
{i:"s201_24",u:201,t:"multi",d:.65,q:"Quelles briques trouve-t-on dans l'Éthique ?",o:["Définitions","Axiomes","Démonstrations","Appendices","Dialogues entre personnages"],a:[0,1,2,3],w:"Pas de dialogues comme chez Platon : Spinoza démontre. Les appendices et préfaces sont les passages en prose continue."},
{i:"s201_25",u:201,t:"fill",d:.65,q:"Pour Spinoza, on étudie les désirs humains comme s'il était question de lignes, de plans ou de ___.",o:["corps","nombres","cercles","couleurs"],a:0,w:"« Lignes, plans ou corps » (préface de la partie III). La nature humaine suit des lois, comme le reste de la nature."},
{i:"s201_26",u:201,t:"match",d:.7,q:"Associe chaque référence à sa lecture.",p:[["E1","Partie I, De Dieu"],["E3P9S","Partie III, proposition 9, scolie"],["E4 préface","Préface de la partie IV"],["E5P42","Partie V, proposition 42"]],w:"Savoir lire ces codes permet de retrouver une citation dans n'importe quelle édition."},
{i:"s201_27",u:201,t:"tiles",d:.7,q:"Reconstitue la traduction du titre latin.",a:["l'Éthique","démontrée","selon","l'ordre","géométrique"],dd:["morale","racontée","poétique"],w:"Ethica ordine geometrico demonstrata. Le titre annonce la méthode d'Euclide appliquée à la vie."},
{i:"s201_28",u:201,t:"story",d:.75,q:"Samir demande : « Si c'est démontré comme en géométrie, c'est forcément vrai ? » Que répond Julien ?",sc:[{who:"Samir",txt:"Une démonstration, ça ne se discute pas."}],o:["« C'est rigoureux, mais on peut discuter ses définitions : c'est lire en philosophe. »","« Oui, toute l'Éthique est prouvée comme un théorème, personne ne l'a jamais contestée. »","« Non, les démonstrations sont fausses exprès, pour tester l'attention du lecteur. »","« Ce n'est qu'un roman déguisé, il ne faut prendre aucune démonstration au sérieux. »"],a:0,w:"La rigueur logique n'empêche pas le débat : Leibniz, Hegel et bien d'autres ont discuté ses définitions. On lit, on comprend, puis on juge."},
{i:"s201_29",u:201,t:"tf",d:.75,q:"La méthode géométrique de Spinoza vise à juger les hommes plus sévèrement.",a:false,w:"Elle vise à les comprendre sans les juger. Ne pas rire, ne pas pleurer, ne pas détester, mais comprendre."},
{i:"s201_30",u:201,t:"mcq",d:.8,q:"Quel est le point d'arrivée du livre, dans sa partie V ?",o:["La liberté humaine et la béatitude","La démonstration de l'existence du diable","Un programme politique pour la Hollande","Une liste de commandements"],a:0,w:"Partie V : de la puissance de l'entendement, ou de la liberté humaine. Le livre finit sur la béatitude (module 15)."},
{i:"s201_31",u:201,t:"sort",d:.8,q:"Classe chaque attitude du lecteur : fidèle ou infidèle à l'esprit de l'Éthique ?",bins:["Fidèle","Infidèle"],it:[["Chercher la cause de sa colère",0],["Se traiter de nul pour une émotion",1],["Comprendre un concurrent jaloux",0],["Mépriser ceux qui ont des passions",1]],w:"Comprendre plutôt que juger, soi comme les autres. C'est le premier pas de la méthode."},
{i:"s201_32",u:201,t:"story",d:.85,q:"Synthèse : Léa résume ce qu'elle a compris du livre. Quelle phrase est la plus juste ?",sc:[{who:"Léa",txt:"Donc l'Éthique, c'est…"}],o:["« Une démonstration qui va de Dieu à la liberté, pour comprendre sans juger. »","« Un recueil de conseils moraux pour devenir riche et respecté dans sa ville. »","« Un roman autobiographique sur l'exclusion de Spinoza par sa communauté. »","« Un manuel de géométrie pure sans aucun lien avec la vie des hommes. »"],a:0,w:"Cinq parties, une méthode, un but : la liberté et la joie par la compréhension."}
