/*UNIT*/
{id:202,c:"SPINO",n:"Module 4",t:"Dieu ou la Nature : tu es une vague de l'océan",col:"--purple",ic:"🌊",guide:`
<h3>Le déjeuner de famille</h3>
<div class="gstory">Dimanche midi chez Maud, la mère de Léa et Julien, à Arcachon. Maud, catholique pratiquante, soupire : « Si ta levée de fonds te rend triste, c'est peut-être que Dieu te punit d'être trop ambitieuse. » Samir, invité, lève les yeux au ciel : « Dieu n'existe pas, Madame. » Julien sourit : « Spinoza vous aurait mis d'accord et fâchés en même temps. Pour lui, Dieu existe. Mais il ne punit personne, il ne veut rien, il ne pense pas à nous. Dieu, c'est la Nature. » Maud repose sa fourchette. Samir aussi. Dehors, les vagues du bassin se forment et se défont sans arrêt.</div>
<h3>Trois mots pour tout comprendre</h3>
<table><tr><th>Notion</th><th>Définition (Éthique, partie I)</th><th>Image</th></tr>
<tr><td><b>Substance</b></td><td>Ce qui est en soi et se conçoit par soi</td><td>L'océan</td></tr>
<tr><td><b>Attribut</b></td><td>Ce que l'entendement perçoit de la substance comme constituant son essence</td><td>L'eau vue comme liquide, ou comme mouvement</td></tr>
<tr><td><b>Mode</b></td><td>Une manière d'être de la substance, qui est en autre chose</td><td>Une vague</td></tr></table>
<p>Il n'existe <b>qu'une seule substance</b> : Dieu, un être absolument infini, doté d'une infinité d'attributs. Nous en connaissons deux : la <b>pensée</b> et l'<b>étendue</b> (la matière, l'espace). Tout le reste, les pierres, les arbres, toi, Léa, sa start-up, sont des <b>modes</b> : des manières d'être de cette substance unique. « Tout ce qui est, est en Dieu » (E1P15).</p>
<div class="gmnemo"><b>« S.A.M. : une Substance, des Attributs, des Modes. Et toi, tu es une vague de l'océan. »</b> La vague n'est pas séparée de l'océan, elle en est une forme passagère. Et la formule clé, en latin : <b>Deus sive Natura</b>, « Dieu, c'est-à-dire la Nature ».</div>
<h3>Un Dieu qui n'a rien d'un roi</h3>
<ul><li>Dieu est <b>cause de soi</b> (<i>causa sui</i>) : son essence implique son existence, rien ne l'a produit.</li>
<li>Il est la cause <b>immanente</b> de toutes choses, pas une cause extérieure (<b>transitive</b>) : il ne fabrique pas le monde comme un artisan fabrique une table, il s'exprime dans le monde, comme l'océan dans ses vagues.</li>
<li>Spinoza distingue la <b>nature naturante</b> (Dieu comme cause, la puissance qui produit) et la <b>nature naturée</b> (tout ce qui est produit, les modes).</li>
<li>Tout arrive par <b>nécessité</b> : « Il n'est rien donné de contingent dans la nature » (E1P29). Les choses ne pouvaient pas être produites autrement.</li>
<li>Dieu n'a <b>ni volonté, ni intention, ni colère</b>. Il ne récompense ni ne punit. Il est « libre » au sens de Spinoza : il agit par la seule nécessité de sa nature, sans contrainte extérieure.</li></ul>
<p>Descartes, lui, voyait <b>deux</b> substances créées, la pensée et l'étendue, et un Dieu créateur distinct du monde. Spinoza est <b>moniste</b> : une seule substance. On l'a accusé d'athéisme, puis on l'a appelé « panthéiste ». Le poète Novalis l'a surnommé « l'homme ivre de Dieu ». En 1929, <b>Einstein</b> répond à un rabbin de New York : « Je crois au Dieu de Spinoza, qui se révèle dans l'harmonie de tout ce qui existe, et non en un Dieu qui se préoccupe du destin et des actes des hommes. »</p>
<h3>L'appendice de la partie I : la chasse aux causes finales</h3>
<p>Les hommes croient que tout dans la nature est fait <b>pour eux</b> : les yeux pour voir, le soleil pour éclairer, la mer pour nourrir les poissons qu'on mange. Et quand un malheur arrive (tempête, maladie), ils pensent que Dieu est en colère. C'est le <b>finalisme</b>, un préjugé né de notre ignorance des causes. Exemple de Spinoza : une pierre tombe d'un toit et tue un passant. Le finaliste demande « pourquoi ce jour-là, pourquoi lui ? », remonte de question en question et finit par répondre « la volonté de Dieu », que Spinoza appelle l'<b>asile de l'ignorance</b>. En réalité : le vent soufflait, l'homme passait par là. Une chaîne de causes.</p>
<div class="gtrap">Nuance sur la vidéo : Théo Lion présente le Dieu de Spinoza comme une « cause non causée », la cause « tout en haut » d'une chaîne. Cette image est plutôt celle d'Aristote ou de Thomas d'Aquin (le premier moteur). Chez Spinoza, Dieu est <b>cause de soi</b> et cause <b>immanente</b> : il n'est pas au sommet ou au début de la chaîne, il est présent <b>dans chaque maillon</b>. L'idée pratique de Théo Lion reste juste : la nature est un réseau de causes dont on ne peut pas sortir.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Définir substance, attribut, mode et les illustrer</li><li>Expliquer Deus sive Natura et pourquoi Dieu ne punit pas</li><li>Opposer le monisme de Spinoza au dualisme de Descartes</li><li>Démonter un raisonnement finaliste avec l'exemple de la pierre</li></ul>`},
/*EXOS*/
{i:"s202_01",u:202,t:"story",d:.2,nw:"Deus sive Natura",q:"Maud pense que Dieu punit Léa pour son ambition. Que répondrait Spinoza ?",sc:[{who:"Maud",txt:"Si elle est triste, c'est peut-être une punition divine."}],o:["« Dieu, c'est la Nature : il ne veut rien, il ne punit personne. »","« Dieu la punit en effet, car l'ambition est un péché très grave. »","« Dieu n'existe pas du tout, Spinoza était un athée déclaré. »","« Dieu récompense les pauvres et punit toujours les riches. »"],a:0,w:"Deus sive Natura. Le Dieu de Spinoza n'a ni volonté ni colère : croire qu'il punit, c'est projeter nos passions sur la nature."},
{i:"s202_02",u:202,t:"match",d:.2,q:"Associe chaque notion à son image.",p:[["Substance","L'océan"],["Mode","Une vague"],["Attribut","L'océan vu comme mouvement ou comme matière"],["Dieu sive Natura","Tout ce qui existe"]],w:"S.A.M. : une Substance, des Attributs, des Modes. Tu es une vague de l'océan."},
{i:"s202_03",u:202,t:"fill",d:.25,q:"La formule latine de Spinoza est Deus sive ___.",o:["Natura","Ratio","Machina","Anima"],a:0,w:"Deus sive Natura : Dieu, c'est-à-dire la Nature. La formule apparaît dans la préface de la partie IV."},
{i:"s202_04",u:202,t:"tf",d:.25,q:"Pour Spinoza, il existe une seule substance.",a:true,w:"Une seule substance, Dieu, doté d'une infinité d'attributs. C'est le monisme, contre le dualisme de Descartes."},
{i:"s202_05",u:202,t:"mcq",d:.3,q:"Quels sont les deux attributs de Dieu que nous connaissons ?",o:["La pensée et l'étendue","L'amour et la colère","Le bien et le mal absolus","Le temps et l'argent"],a:0,w:"La pensée et l'étendue (la matière, l'espace). Dieu en a une infinité, mais nous n'en connaissons que deux."},
{i:"s202_06",u:202,t:"sort",d:.3,q:"Classe chaque réalité : substance ou mode ?",bins:["Substance","Mode"],it:[["Dieu ou la Nature",0],["Léa",1],["Un arbre",1],["La start-up Cargo & Co",1],["Une idée dans l'esprit de Samir",1]],w:"Il n'y a qu'une substance ; tout le reste, choses, personnes, idées, entreprises, sont des modes."},
{i:"s202_07",u:202,t:"story",d:.3,q:"Samir, athée, dit : « Si Dieu c'est la Nature, Spinoza est juste un athée poli ». Que répond Julien ?",sc:[{who:"Samir",txt:"Dieu ou la Nature, c'est une façon de ne pas dire athée."}],o:["« On l'a accusé d'athéisme, d'autres l'ont dit ivre de Dieu : le débat existe. »","« Non, Spinoza croyait à un Dieu personnel qui répond à toutes les prières. »","« Oui, et il l'a écrit clairement dans toute l'Éthique : Dieu n'existe pas. »","« Il n'a jamais parlé de Dieu, c'est une invention de ses traducteurs tardifs. »"],a:0,w:"Le débat existe depuis trois siècles. Spinoza parle bien de Dieu, mais d'un Dieu sans volonté ni intention, identique à la Nature."},
{i:"s202_08",u:202,t:"fill",d:.35,q:"Dieu est cause de ___ : son essence implique son existence.",o:["soi","tout","rien","mal"],a:0,w:"Causa sui, cause de soi (définition 1 de la partie I). Rien ne l'a produit."},
{i:"s202_09",u:202,t:"multi",d:.35,q:"Qu'est-ce que le Dieu de Spinoza n'a PAS ?",o:["Une volonté","Des intentions","Une colère","Un projet pour les hommes","Une existence nécessaire"],a:[0,1,2,3],w:"Dieu existe nécessairement, mais sans volonté, sans intention, sans colère ni projet. Il agit par la seule nécessité de sa nature."},
{i:"s202_10",u:202,t:"tiles",d:.35,q:"Reconstitue l'image de l'océan et de la vague.",a:["tu","es","une","vague","de","l'océan"],dd:["rocher","roi","hors"],w:"Un mode de la substance unique, pas un être séparé de la nature."},
{i:"s202_11",u:202,t:"mcq",d:.4,q:"Que Spinoza appelle-t-il « l'asile de l'ignorance » ?",o:["Le recours à la volonté de Dieu pour expliquer","Une prison pour les philosophes hérétiques","Une école religieuse d'Amsterdam fermée","Le cerveau humain au repos pendant le sommeil"],a:0,w:"Quand on ignore les causes, on se réfugie dans « la volonté de Dieu ». C'est dans l'appendice de la partie I."},
{i:"s202_12",u:202,t:"story",d:.4,q:"Une pierre tombe d'un toit et tue un passant. Maud dit : « C'était son destin, Dieu l'a voulu ». Comment raisonne Spinoza ?",sc:[{who:"Maud",txt:"Ça ne peut pas être un hasard, pourquoi lui, pourquoi ce jour-là ?"}],o:["« Le vent soufflait, il passait par là : des causes, pas une intention. »","« Dieu l'a voulu pour punir le passant de ses péchés cachés, forcément. »","« C'est un pur hasard sans aucune cause, rien ne peut l'expliquer. »","« Le passant l'a voulu inconsciemment, c'est lui qui a attiré la pierre. »"],a:0,w:"Ni intention divine ni hasard : des causes nécessaires. Le « pourquoi lui ? » qui remonte jusqu'à Dieu mène à l'asile de l'ignorance."},
{i:"s202_13",u:202,t:"tf",d:.4,q:"Selon Spinoza, les yeux ont été faits pour voir et le soleil pour nous éclairer.",a:false,w:"C'est justement le préjugé finaliste qu'il critique. Les hommes croient que tout est fait pour eux parce qu'ils ignorent les causes."},
{i:"s202_14",u:202,t:"order",d:.45,q:"Remets dans l'ordre le raisonnement finaliste que Spinoza démonte.",it:["Un malheur arrive","On demande « pourquoi moi ? »","On ignore les causes réelles","On invoque la volonté de Dieu","On s'arrête dans l'asile de l'ignorance"],w:"Le finalisme naît de l'ignorance des causes et projette des intentions humaines sur la nature."},
{i:"s202_15",u:202,t:"match",d:.45,q:"Associe chaque expression à son sens.",p:[["Nature naturante","Dieu comme puissance qui produit"],["Nature naturée","Tout ce qui est produit, les modes"],["Cause immanente","Cause qui reste dans ses effets"],["Cause transitive","Cause extérieure à ses effets"]],w:"Dieu est cause immanente : il s'exprime dans le monde comme l'océan dans ses vagues, il ne le fabrique pas de l'extérieur."},
{i:"s202_16",u:202,t:"fill",d:.45,q:"La doctrine selon laquelle il n'existe qu'une seule substance s'appelle le ___.",o:["monisme","dualisme","stoïcisme","finalisme"],a:0,w:"Monisme (du grec monos, seul). Descartes est dualiste : pensée et étendue sont deux substances."},
{i:"s202_17",u:202,t:"story",d:.5,q:"Léa demande ce que ça change pour elle, concrètement, que Dieu soit la Nature.",sc:[{who:"Léa",txt:"C'est joli, mais ça m'aide en quoi pour ma boîte ?"}],o:["« Tu fais partie d'un réseau de causes : pour être libre, comprends-les. »","« Rien du tout, c'est de la métaphysique sans aucun lien avec ta vie. »","« Tu peux prier la Nature pour que ta start-up réussisse plus vite. »","« Tu n'es responsable de rien, donc inutile de faire le moindre effort. »"],a:0,w:"C'est l'idée pratique retenue par Théo Lion : tu n'es pas hors de la nature. La liberté commence par la connaissance des causes qui te déterminent."},
{i:"s202_18",u:202,t:"tf",d:.5,q:"Einstein a déclaré croire au Dieu de Spinoza.",a:true,w:"En 1929, à un rabbin de New York : au Dieu qui se révèle dans l'harmonie de ce qui existe, pas à un Dieu qui s'occupe des actes des hommes."},
{i:"s202_19",u:202,t:"sort",d:.5,q:"Classe chaque phrase : spinoziste ou finaliste ?",bins:["Spinoziste","Finaliste"],it:[["La tempête est la colère de Dieu",1],["La tempête a des causes météorologiques",0],["La nature est faite pour l'homme",1],["Rien n'est contingent dans la nature",0],["Mon échec est un signe du destin",1]],w:"Le finaliste voit des intentions partout ; le spinoziste cherche des causes."},
{i:"s202_20",u:202,t:"mcq",d:.55,q:"Qui a surnommé Spinoza « l'homme ivre de Dieu » ?",o:["Le poète Novalis","Le philosophe Descartes","Le pape de l'époque","Le rabbin d'Amsterdam"],a:0,w:"Novalis, poète romantique allemand. Accusé d'athéisme par les uns, il est vu comme un mystique de la Nature par les autres."},
{i:"s202_21",u:202,t:"story",d:.55,q:"Samir reprend la vidéo : « Dieu, c'est la cause non causée tout en haut de la chaîne ». Que précise Julien ?",sc:[{who:"Samir",txt:"C'est bien ce que dit Théo Lion, non ?"}],o:["« Chez Spinoza, Dieu est cause de soi, dans chaque maillon, pas au sommet. »","« Exact, Dieu est une cause extérieure qui a lancé le monde puis s'est retirée. »","« Non, pour Spinoza le monde n'a aucune cause, tout arrive sans raison. »","« Dieu est la dernière cause de la chaîne, celle qui arrivera à la fin des temps. »"],a:0,w:"La « cause non causée » au sommet évoque le premier moteur d'Aristote. Le Dieu de Spinoza est cause immanente, en toutes choses."},
{i:"s202_22",u:202,t:"slider",d:.6,q:"En quelle année Einstein a-t-il écrit qu'il croyait au Dieu de Spinoza ?",min:1900,max:1960,step:1,a:1929,tol:0,pre:"",un:"",w:"1929, en réponse au rabbin Herbert Goldstein, de New York."},
{i:"s202_23",u:202,t:"multi",d:.6,q:"Quelles propositions correspondent à la partie I de l'Éthique ?",o:["Tout ce qui est, est en Dieu","Rien n'est contingent dans la nature","Dieu est cause immanente de toutes choses","Il n'y a qu'une seule substance","Dieu punit ceux qui désobéissent"],a:[0,1,2,3],w:"E1P15, E1P29, E1P18, E1P14. La punition divine est une projection finaliste."},
{i:"s202_24",u:202,t:"fill",d:.65,q:"Spinoza affirme : « Il n'est rien donné de ___ dans la nature ».",o:["contingent","nécessaire","divin","naturel"],a:0,w:"E1P29 : tout est déterminé par la nécessité de la nature divine à exister et à agir d'une certaine manière."},
{i:"s202_25",u:202,t:"story",d:.65,q:"Léa, après un contrat perdu, dit : « L'univers me fait payer mon arrogance ». Que lui répond Julien en spinoziste ?",sc:[{who:"Léa",txt:"Je le sens, c'est un signe."}],o:["« L'univers ne vise personne : cherchons les causes réelles de cette perte. »","« Oui, l'univers rééquilibre toujours les choses, c'est une loi de la nature. »","« C'est de ta faute, tu mérites cette punition et il faut l'accepter. »","« Les signes existent, il faut apprendre à les lire pour éviter les pièges. »"],a:0,w:"Voir un signe, c'est du finalisme : on projette une intention sur la nature. Chercher les causes, c'est se donner le moyen d'agir."},
{i:"s202_26",u:202,t:"tiles",d:.7,q:"Reconstitue la proposition E1P15.",a:["tout","ce","qui","est","est","en","Dieu"],dd:["hors","créé","par"],w:"Tout ce qui est, est en Dieu, et rien ne peut sans Dieu ni être ni être conçu."},
{i:"s202_27",u:202,t:"mcq",d:.7,q:"En quoi Spinoza s'oppose-t-il à Descartes sur la substance ?",o:["Une seule substance contre deux créées","Il nie totalement l'existence de la matière","Il nie totalement l'existence de la pensée","Il croit à trois substances distinctes"],a:0,w:"Descartes : substance pensante et substance étendue, créées par un Dieu distinct. Spinoza : pensée et étendue sont deux attributs d'une seule substance."},
{i:"s202_28",u:202,t:"tf",d:.75,q:"Pour Spinoza, Dieu fabrique le monde de l'extérieur, comme un artisan fabrique une table.",a:false,w:"C'est la cause transitive. Le Dieu de Spinoza est cause immanente : il est dans le monde qu'il produit."},
{i:"s202_29",u:202,t:"sort",d:.75,q:"Classe chaque mot : lié à la partie I de l'Éthique ou à un autre sujet ?",bins:["Partie I","Autre sujet"],it:[["Substance",0],["Conatus",1],["Asile de l'ignorance",0],["Béatitude",1],["Cause de soi",0]],w:"La partie I traite de Dieu. Le conatus (partie III) et la béatitude (partie V) viendront plus tard."},
{i:"s202_30",u:202,t:"story",d:.8,q:"Maud, un peu vexée, demande : « Alors, pour Spinoza, prier ne sert à rien ? »",sc:[{who:"Maud",txt:"Si Dieu n'écoute pas, à quoi bon ?"}],o:["« Son Dieu ne répond pas aux demandes ; le connaître rend libre et joyeux. »","« Prier oblige Dieu à changer ses plans, c'est ce que Spinoza enseigne. »","« Il faut prier chaque jour, sinon la Nature se venge sur la famille. »","« Il interdisait strictement la prière à tous ceux qui le lisaient. »"],a:0,w:"Pour Spinoza, la joie vient de la connaissance de Dieu, c'est-à-dire de la Nature. Il ne se moque pas des croyants : il comprend."},
{i:"s202_31",u:202,t:"match",d:.8,q:"Associe chaque penseur à sa vision de Dieu.",p:[["Spinoza","Dieu ou la Nature, sans volonté"],["Descartes","Dieu créateur, distinct du monde"],["Aristote","Premier moteur immobile"],["Einstein","L'harmonie de tout ce qui existe"]],w:"Savoir situer Spinoza parmi les autres permet d'éviter les confusions, y compris celles de la vidéo."},
{i:"s202_32",u:202,t:"story",d:.85,q:"Synthèse : au dessert, Julien résume la partie I en une phrase. Laquelle ?",sc:[{who:"Samir",txt:"OK, la version courte ?"}],o:["« Une seule Nature, dont tout est une manière d'être ; tout a une cause. »","« Deux mondes séparés, celui des corps et celui des âmes immortelles. »","« Un Dieu juge qui récompense les bons et punit les méchants à la fin. »","« Un univers de hasard pur, où rien n'a jamais aucune explication. »"],a:0,w:"Deus sive Natura, S.A.M., nécessité. C'est la base de la liberté spinoziste : comprendre les causes."}
