/*UNIT*/
{id:203,c:"SPINO",n:"Module 5",t:"Le corps et l'esprit : une seule chose, deux langues",col:"--purple",ic:"🫀",guide:`
<h3>Le client qui part</h3>
<div class="gstory">Lundi matin, 9 h 12, au bureau de Cargo &amp; Co. Un mail tombe : La Poste Bordeaux, leur plus gros client, ne renouvelle pas son contrat. Léa sent ses épaules se crisper, son ventre se nouer, sa tête s'embrumer ; elle relit trois fois le même paragraphe sans le comprendre. Anaïs, son associée, lui apporte un café : « Respire, on va trouver. » Le soir, Léa raconte la scène à Julien. Il sourit : « Théo Lion décrit exactement ça dans sa vidéo : la crispation des muscles, l'esprit qui s'embrume. Et Spinoza te dirait que ce n'est pas ton corps qui a paniqué, puis ton esprit. C'est la même chose, dite deux fois. »</div>
<h3>Ni pilote ni machine</h3>
<p><b>Descartes</b> pensait que l'âme et le corps sont deux substances différentes qui agissent l'une sur l'autre, par une petite glande au centre du cerveau, la <b>glande pinéale</b>. Spinoza s'en moque gentiment dans la préface de la partie V : comment une pensée pourrait-elle pousser une glande ?</p>
<p>Pour Spinoza, le corps et l'esprit sont <b>une seule et même chose</b>, conçue tantôt sous l'attribut de l'étendue (le corps), tantôt sous l'attribut de la pensée (l'esprit). Deux formules à connaître :</p>
<ul><li><b>E2P7</b> : « L'ordre et la connexion des idées est le même que l'ordre et la connexion des choses. »</li>
<li><b>E2P13</b> : l'objet de l'idée qui constitue l'esprit humain est le corps. Autrement dit, <b>l'esprit est l'idée du corps</b>.</li></ul>
<p>Conséquence (<b>E3P2</b>) : le corps ne peut pas forcer l'esprit à penser, ni l'esprit forcer le corps à bouger. Ils ne s'influencent pas : ils <b>expriment la même chose</b>, chacun dans sa langue. Quand le corps de Léa se crispe, son esprit s'embrume <b>en même temps</b>, parce que c'est un seul événement.</p>
<div class="gmnemo"><b>« Une pièce, deux faces. »</b> Pile, le corps ; face, l'esprit. Pour Samir le développeur : <b>« Un même fichier, deux formats d'affichage »</b>, pas un logiciel qui pilote une machine.</div>
<h3>« Personne n'a encore déterminé ce que peut un corps »</h3>
<p>Dans le scolie de E3P2, Spinoza lance une phrase devenue célèbre : on ne sait pas ce que peut un corps. On croit que l'esprit commande tout, alors que le corps fait des choses étonnantes (le somnambule marche sur les toits sans le vouloir). Et plus un corps est capable de choses nombreuses, plus l'esprit est capable de percevoir (E2P13, scolie). Muscler son corps, apprendre un geste, c'est aussi élargir son esprit.</p>
<h3>Pas un empire dans un empire</h3>
<p>Dans la préface de la partie III, Spinoza critique ceux qui voient l'homme dans la nature « comme un <b>empire dans un empire</b> » (<i>imperium in imperio</i>) : un être à part, qui échapperait aux lois naturelles et commanderait tout par sa volonté. Faux : nos émotions suivent les lois communes de la nature, comme la pluie ou la digestion. C'est une <b>bonne nouvelle</b> : ce qui suit des lois peut être compris.</p>
<h3>Deux mots à ne pas confondre</h3>
<table><tr><th>Mot</th><th>Sens</th><th>Exemple</th></tr>
<tr><td><b>Affection</b> (affectio)</td><td>La trace qu'un autre corps laisse sur mon corps</td><td>Le mail de La Poste qui arrive sous les yeux de Léa</td></tr>
<tr><td><b>Affect</b> (affectus)</td><td>La variation de ma puissance d'agir qui en résulte, dans le corps et dans l'esprit</td><td>La crispation et la tristesse de Léa</td></tr></table>
<div class="gtrap">Précision : on appelle souvent cette thèse le « parallélisme » de Spinoza. Le mot n'est pas de lui, il vient de Leibniz. Il peut tromper : il ne s'agit pas de deux lignes séparées qui avancent côte à côte, mais d'<b>une seule</b> réalité exprimée de deux façons. Le neurologue <b>Antonio Damasio</b> a consacré un livre à cette idée, <i>Spinoza avait raison</i> (2003) : pour lui, les neurosciences confirment que les émotions sont d'abord des états du corps.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Opposer Spinoza et Descartes sur l'union de l'âme et du corps</li><li>Citer E2P7, E2P13 et le « ce que peut un corps »</li><li>Expliquer « un empire dans un empire »</li><li>Distinguer affection et affect</li></ul>`},
/*EXOS*/
{i:"s203_01",u:203,t:"story",d:.2,nw:"L'esprit est l'idée du corps",q:"Léa demande si c'est son corps qui a paniqué avant son esprit, en lisant le mail. Que répond Julien ?",sc:[{who:"Léa",txt:"Mon ventre s'est noué, puis j'ai paniqué. Ou l'inverse ?"}],o:["« Ni l'un ni l'autre : c'est un seul événement, vu du corps et de l'esprit. »","« Ton esprit a paniqué d'abord, puis il a ordonné à ton corps de se crisper. »","« Ton corps a paniqué seul, l'esprit n'a aucun rôle dans les émotions. »","« Ta glande pinéale a transmis l'émotion de ton âme vers ton ventre. »"],a:0,w:"Corps et esprit sont une seule chose conçue sous deux attributs. Une pièce, deux faces."},
{i:"s203_02",u:203,t:"fill",d:.2,q:"Pour Spinoza, l'esprit est l'idée du ___.",o:["corps","monde","cerveau","cœur"],a:0,w:"E2P13 : l'objet de l'idée qui constitue l'esprit humain est le corps."},
{i:"s203_03",u:203,t:"match",d:.25,q:"Associe chaque philosophe à sa conception.",p:[["Descartes","Deux substances qui agissent l'une sur l'autre"],["Spinoza","Une seule chose sous deux attributs"],["Glande pinéale","Point de contact selon Descartes"],["Damasio","Spinoza avait raison"]],w:"Descartes est dualiste et interactionniste ; Spinoza, moniste. Damasio relit Spinoza avec les neurosciences."},
{i:"s203_04",u:203,t:"tf",d:.25,q:"Selon Spinoza, l'esprit peut forcer le corps à bouger par un ordre de la volonté.",a:false,w:"E3P2 : ni le corps ne détermine l'esprit à penser, ni l'esprit le corps au mouvement. Ils expriment la même chose."},
{i:"s203_05",u:203,t:"mcq",d:.25,q:"Que veut dire « un empire dans un empire » chez Spinoza ?",o:["L'illusion d'un homme hors de la nature","Un royaume allié à la Hollande de Spinoza","Une entreprise dans une grande entreprise","L'âme qui gouverne un grand corps humain"],a:0,w:"Imperium in imperio (préface de la partie III). L'homme fait partie de la nature et ses émotions suivent ses lois."},
{i:"s203_06",u:203,t:"tiles",d:.3,q:"Reconstitue la phrase célèbre du scolie de E3P2.",a:["personne","n'a","encore","déterminé","ce","que","peut","un","corps"],dd:["âme","veut","jamais"],w:"On croit que l'esprit commande tout, mais on ignore ce que le corps peut faire par ses seules lois."},
{i:"s203_07",u:203,t:"story",d:.3,q:"Samir compare : « L'esprit, c'est le logiciel, et le corps la machine qu'il pilote ». Julien corrige. Comment ?",sc:[{who:"Samir",txt:"C'est bien un logiciel qui tourne sur du matériel, non ?"}],o:["« Plutôt un même fichier lu dans deux formats : rien ne pilote rien. »","« Exactement, l'esprit est un programme qui commande la machine du corps. »","« C'est l'inverse : le corps est le logiciel et l'esprit la machine physique. »","« Il n'y a pas d'esprit du tout, seulement une machine sans aucune pensée. »"],a:0,w:"Chez Spinoza, pas de pilote : corps et esprit sont deux expressions d'une même réalité. L'image du logiciel est cartésienne."},
{i:"s203_08",u:203,t:"sort",d:.3,q:"Classe chaque terme : affection ou affect ?",bins:["Affection","Affect"],it:[["Le mail reçu, trace sur mon corps",0],["La tristesse de Léa",1],["La bousculade dans la rue",0],["La colère qui s'ensuit",1],["La crispation qui diminue ma puissance",1]],w:"L'affection est la trace d'un autre corps sur le mien ; l'affect, la variation de ma puissance qui en résulte."},
{i:"s203_09",u:203,t:"multi",d:.35,q:"Quelles réactions de Léa relèvent d'un même affect, dans le corps et dans l'esprit ?",o:["Épaules crispées","Ventre noué","Esprit embrumé","Relire trois fois sans comprendre","Le mail de La Poste lui-même"],a:[0,1,2,3],w:"Le mail est la cause extérieure (l'affection). Les quatre autres sont l'affect de tristesse, exprimé dans le corps et dans l'esprit."},
{i:"s203_10",u:203,t:"fill",d:.35,q:"E2P7 : « L'ordre et la connexion des idées est le même que l'ordre et la connexion des ___. »",o:["choses","mots","âmes","nombres"],a:0,w:"Ce qui se passe dans l'étendue et ce qui se passe dans la pensée suivent un seul et même ordre."},
{i:"s203_11",u:203,t:"mcq",d:.35,q:"Par quel organe Descartes expliquait-il l'union de l'âme et du corps ?",o:["La glande pinéale","Le cœur et ses artères","Le foie","Le cervelet"],a:0,w:"La glande pinéale, au centre du cerveau. Spinoza s'en moque dans la préface de la partie V."},
{i:"s203_12",u:203,t:"story",d:.4,q:"Anaïs fait du sport chaque matin et dit qu'elle « pense mieux après ». Qu'en dirait Spinoza ?",sc:[{who:"Anaïs",txt:"Après ma course, les idées viennent toutes seules."}],o:["« Plus un corps est capable de choses, plus l'esprit l'est aussi. »","« C'est une illusion, le corps n'a aucun rapport avec les idées. »","« C'est parce que le sport vide l'esprit de toute pensée inutile. »","« Il faudrait courir moins pour laisser plus de place à l'esprit. »"],a:0,w:"E2P13, scolie. Corps et esprit ne font qu'un : élargir les capacités du corps élargit celles de l'esprit. Scolie de E3P2 : personne n'a encore déterminé ce que peut un corps."},
{i:"s203_13",u:203,t:"tf",d:.4,q:"Le mot « parallélisme » pour désigner la thèse de Spinoza vient de Spinoza lui-même.",a:false,w:"Il vient de Leibniz. Et il peut tromper : ce n'est pas deux lignes séparées, mais une seule réalité dite deux fois."},
{i:"s203_14",u:203,t:"order",d:.45,q:"Remets dans l'ordre ce qui se passe quand Léa lit le mail, en langage spinoziste.",it:["Une cause extérieure affecte son corps","Sa puissance d'agir diminue","Elle éprouve un affect de tristesse","Corps et esprit l'expriment ensemble"],w:"Affection, variation de puissance, affect vécu à la fois dans le corps et dans l'esprit."},
{i:"s203_15",u:203,t:"slider",d:.45,q:"En quelle année Antonio Damasio publie-t-il Spinoza avait raison ?",min:1950,max:2025,step:1,a:2003,tol:0,pre:"",un:"",w:"2003 (titre original Looking for Spinoza). Pour Damasio, les émotions sont d'abord des états du corps."},
{i:"s203_16",u:203,t:"match",d:.45,q:"Associe chaque référence à son contenu.",p:[["E2P7","Même ordre des idées et des choses"],["E2P13","L'esprit est l'idée du corps"],["E3P2","Pas d'action de l'un sur l'autre"],["Préface de E3","Pas un empire dans un empire"]],w:"Quatre repères pour toute question sur le corps et l'esprit."},
{i:"s203_17",u:203,t:"story",d:.5,q:"Maud dit : « Il faut dompter son corps par la volonté, comme un cheval sauvage ». Que répond Julien ?",sc:[{who:"Maud",txt:"L'esprit doit commander, le corps obéir."}],o:["« Pour Spinoza, ni cavalier ni cheval : il faut comprendre, pas dompter. »","« C'est exactement la position de Spinoza dans toute la partie V de l'Éthique. »","« Il faut au contraire laisser le corps commander et l'esprit se taire. »","« Le corps doit être puni quand il désobéit, c'est la seule façon d'avancer. »"],a:0,w:"L'idée d'une volonté qui dompte le corps est cartésienne, et stoïcienne. Spinoza propose une autre voie : la connaissance des causes (modules 11 à 13)."},
{i:"s203_18",u:203,t:"fill",d:.5,q:"Imperium in imperio signifie « un empire dans un ___ ».",o:["empire","royaume","corps","esprit"],a:0,w:"L'homme n'est pas un empire dans un empire : il fait partie de la nature et en suit les lois."},
{i:"s203_19",u:203,t:"sort",d:.5,q:"Classe chaque phrase : spinoziste ou cartésienne ?",bins:["Spinoziste","Cartésienne"],it:[["L'âme agit sur le corps par la glande pinéale",1],["Corps et esprit sont une seule chose",0],["La volonté libre peut maîtriser les passions",1],["Les émotions suivent les lois de la nature",0]],w:"Spinoza admire Descartes mais rejette ses deux substances et sa volonté souveraine."},
{i:"s203_20",u:203,t:"story",d:.55,q:"Rappel du module 1 : Léa se souvient de sa joie en comprenant enfin la comptabilité. Que se passait-il dans son corps ?",sc:[{who:"Léa",txt:"Je me sentais légère, presque physiquement."}],o:["« Ta puissance d'agir augmentait, et ton corps l'exprimait aussi. »","« Rien, la joie de comprendre est purement intellectuelle, sans corps. »","« Ton corps se reposait parce que ton esprit travaillait à sa place. »","« Tu avais sans doute simplement bien dormi la nuit d'avant, c'est tout. »"],a:0,w:"La joie est un passage à une plus grande puissance, dans le corps comme dans l'esprit. Théo Lion compare avec la joie de comprendre un exercice de maths."},
{i:"s203_21",u:203,t:"tf",d:.55,q:"Pour Spinoza, le fait que nos émotions suivent des lois naturelles est une bonne nouvelle.",a:true,w:"Ce qui suit des lois peut être compris, et ce qui est compris peut être transformé. C'est la base de la méthode (module 13)."},
{i:"s203_22",u:203,t:"mcq",d:.6,q:"Quel exemple Spinoza donne-t-il pour montrer qu'on ignore ce que peut un corps ?",o:["Le somnambule qui marche sur les toits","L'athlète qui court un marathon entier","Le soldat qui résiste au froid d'hiver","Le musicien qui joue sans partition"],a:0,w:"Le somnambule fait des choses qu'il n'oserait pas éveillé : le corps a des capacités que l'esprit ignore. Personne n'a encore déterminé ce que peut un corps."},
{i:"s203_23",u:203,t:"multi",d:.6,q:"Quelles idées Damasio reprend-il de Spinoza ?",o:["Les émotions sont d'abord corporelles","L'esprit est lié à l'état du corps","La joie accompagne un meilleur fonctionnement de l'organisme","Il n'y a pas de pilote séparé du corps","L'âme habite la glande pinéale"],a:[0,1,2,3],w:"La glande pinéale est l'hypothèse de Descartes, que Damasio critique dans un autre livre, L'Erreur de Descartes (1994)."},
{i:"s203_24",u:203,t:"story",d:.65,q:"Samir se traite de « faible » parce qu'il a le cœur qui bat avant chaque réunion. Que lui dis-tu ?",sc:[{who:"Samir",txt:"Je devrais maîtriser ça, je suis nul."}],o:["« Ce n'est pas une faiblesse morale : c'est un affect, avec des causes. »","« Oui, un vrai entrepreneur ne ressent jamais rien avant une réunion importante. »","« Ton corps te trahit, il faut l'ignorer complètement et foncer quand même. »","« C'est un signe du destin : tu n'es pas fait pour les réunions, arrête. »"],a:0,w:"Spinoza ne juge pas : il comprend. Le cœur qui bat et l'angoisse sont un seul affect, qui a des causes."},
{i:"s203_25",u:203,t:"fill",d:.65,q:"La trace qu'un corps extérieur laisse sur mon corps s'appelle une ___.",o:["affection","ambition","attention","addition"],a:0,w:"Affectio. L'affect (affectus) est la variation de puissance qui en résulte."},
{i:"s203_26",u:203,t:"match",d:.7,q:"Associe chaque image au bon penseur.",p:[["Une pièce, deux faces","Spinoza"],["Le pilote dans son navire","Image refusée par Spinoza"],["Le somnambule","Ce que peut un corps"],["L'empire dans l'empire","Illusion de l'homme hors nature"]],w:"Les images aident à retenir : une seule réalité, pas de pilote, un corps plus puissant qu'on ne croit, un homme dans la nature."},
{i:"s203_27",u:203,t:"tiles",d:.7,q:"Reconstitue l'image du corps et de l'esprit.",a:["une","pièce","deux","faces"],dd:["pilote","trois","machine"],w:"Pile le corps, face l'esprit : une seule pièce."},
{i:"s203_28",u:203,t:"sort",d:.75,q:"Classe chaque attitude face à une émotion : spinoziste ou non ?",bins:["Spinoziste","Non spinoziste"],it:[["Chercher ce qui a causé ma crispation",0],["Me reprocher d'avoir un corps qui réagit",1],["Observer mes sensations sans me juger",0],["Décréter que je ne ressentirai plus rien",1]],w:"On ne décrète pas la fin d'un affect ; on en cherche les causes, sans honte."},
{i:"s203_29",u:203,t:"story",d:.75,q:"Rappel du module 4 : Léa demande pourquoi son corps et son esprit ne font qu'un.",sc:[{who:"Léa",txt:"Qu'est-ce que Dieu vient faire là-dedans ?"}],o:["« Pensée et étendue sont deux attributs d'une même substance : tu en es un mode. »","« Dieu a collé une âme dans ton corps à la naissance, comme une pièce rapportée. »","« Dieu n'a rien à voir, c'est une question de médecine et rien de plus. »","« Dieu contrôle ton corps, et toi tu contrôles seulement ton esprit. »"],a:0,w:"Tout se tient : une substance, deux attributs connus. Un mode est à la fois un corps (étendue) et une idée (pensée)."},
{i:"s203_30",u:203,t:"tf",d:.8,q:"Théo Lion raconte qu'il ressentait physiquement la perte d'un client, au début de son entreprise.",a:true,w:"« La crispation des muscles, l'esprit qui s'embrume » : c'est pour lui exactement le passage à une moindre perfection."},
{i:"s203_31",u:203,t:"mcq",d:.8,q:"Pourquoi Spinoza refuse-t-il l'image de la volonté qui dompte le corps ?",o:["Parce que l'esprit et le corps sont une même chose","Parce que le corps est bien plus noble que l'esprit","Parce que la volonté appartient à Dieu seul, pas à nous","Parce qu'il faut toujours céder à toutes ses envies"],a:0,w:"On ne peut pas dompter ce qui n'est pas séparé de soi. On peut en revanche comprendre et transformer (modules 11 à 13)."},
{i:"s203_32",u:203,t:"story",d:.85,q:"Synthèse : Léa résume le module pour Anaïs. Quelle phrase est la plus juste ?",sc:[{who:"Anaïs",txt:"Alors, ce Spinoza, il dit quoi sur le corps ?"}],o:["« Corps et esprit sont une seule chose : nos émotions ont des lois, on peut les comprendre. »","« L'esprit doit commander au corps, sinon on devient esclave de ses émotions. »","« Le corps est une prison dont l'esprit doit s'échapper par la méditation quotidienne. »","« Seul le corps compte, l'esprit n'est qu'une illusion inventée par les philosophes. »"],a:0,w:"Une pièce, deux faces ; pas un empire dans un empire. Ce qui a des lois se comprend, et ce qui se comprend se transforme."}
