/*UNIT*/
{id:204,c:"SPINO",n:"Module 6",t:"Le libre arbitre, une illusion : la pierre qui se croit libre",col:"--purple",ic:"🪨",guide:`
<h3>« J'ai choisi, moi ! »</h3>
<div class="gstory">Mardi soir, au bar La Comtesse, près de la place du Parlement. Samir annonce fièrement qu'il quitte son CDI pour lancer sa start-up : « C'est MON choix, personne ne m'a influencé. » Julien pose trois questions. Depuis quand y pense-t-il ? Depuis qu'il suit un « coach business » sur Instagram. Que font ses amis de promo ? Trois ont créé leur boîte. Et son père ? « Il a été ouvrier toute sa vie, il me dit toujours de ne pas finir comme lui. » Samir se tait. Julien : « Tu as bien choisi. Mais tu n'as pas choisi ce qui t'a fait choisir. »</div>
<h3>La phrase clé</h3>
<p>« Les hommes se trompent en ce qu'ils se croient <b>libres</b>, opinion qui consiste en cela seul qu'ils sont <b>conscients de leurs actions et ignorants des causes</b> par lesquelles ils sont déterminés » (E2P35, scolie). On trouve la même idée dans l'appendice de la partie I.</p>
<div class="gmnemo"><b>« Conscient des actes, ignorant des causes : voilà l'illusion. »</b> Et l'image de la lettre 58 : <b>« La pierre qui roule se croit libre. »</b></div>
<h3>La pierre de la lettre 58</h3>
<p>En 1674, Spinoza écrit à son ami Schuller : imagine une pierre lancée par quelqu'un. Si elle pouvait penser, elle croirait qu'elle continue de rouler <b>parce qu'elle le veut</b>. C'est exactement la liberté humaine dont tout le monde se vante. L'enfant croit désirer librement le lait, l'homme en colère croit vouloir librement se venger, l'ivrogne croit parler librement, et regrette le lendemain.</p>
<h3>La volonté n'est pas une faculté à part</h3>
<ul><li><b>Descartes</b> pense que la <b>volonté</b> est libre et infinie : elle peut dire oui ou non à une idée, suspendre son jugement, et même, dans <i>Les Passions de l'âme</i> (1649), acquérir un pouvoir absolu sur les passions.</li>
<li><b>Spinoza</b> répond (E2P48) : il n'y a dans l'esprit aucune volonté absolue ou libre. Et (E2P49, corollaire) : « <b>La volonté et l'entendement sont une seule et même chose</b> » (<i>voluntas et intellectus unum et idem sunt</i>).</li>
<li>Pourquoi ? Parce qu'une idée n'est pas une image muette qui attendrait une signature. <b>Chaque idée affirme déjà quelque chose</b>. L'idée du triangle affirme que ses trois angles valent deux droits. L'idée d'une ligne droite affirme sa droiture. Vouloir, c'est simplement l'affirmation contenue dans l'idée.</li></ul>
<p>Conséquence pratique, soulignée par Théo Lion : si je suis jaloux d'un concurrent, ce n'est pas parce que ma volonté a « laissé passer » la jalousie. C'est parce qu'une idée confuse (« son succès diminue ma valeur ») occupe mon esprit et produit mécaniquement son effet. Je ne peux pas la chasser par décret.</p>
<h3>Déterminisme n'est pas fatalisme</h3>
<table><tr><th>Fatalisme</th><th>Déterminisme de Spinoza</th></tr>
<tr><td>« C'était écrit, je n'y peux rien »</td><td>« Tout a des causes, que je peux connaître »</td></tr>
<tr><td>Résignation, passivité</td><td>Compréhension, puis action</td></tr>
<tr><td>Le destin a une intention</td><td>La nature n'a aucune intention (module 4)</td></tr></table>
<p>La vraie <b>liberté</b>, pour Spinoza, n'est pas le libre arbitre (choisir sans cause) : c'est agir par la <b>seule nécessité de sa nature</b> (définition 7 de la partie I), c'est-à-dire être la cause <b>adéquate</b> de ce qu'on fait. On devient libre en connaissant les causes, pas en les niant.</p>
<p>Et la responsabilité ? Spinoza répond à une objection (lettre à Oldenburg) : celui que la morsure d'un chien rend enragé est excusable, mais on a raison de s'en protéger. Comprendre la cause d'un acte nuisible ne le rend pas moins nuisible. Cela évite seulement la <b>haine</b>.</p>
<div class="gtrap">Précision sur la vidéo : Théo Lion dit que l'erreur sur le soleil « persiste tant que nous ignorons la vraie distance ». Spinoza dit plus fort (E2P35, scolie) : même quand nous connaissons la vraie distance, nous continuons d'<b>imaginer</b> le soleil à environ 200 pieds. L'image ne disparaît pas. Ce qui disparaît, c'est l'<b>erreur</b>, parce que nous savons ce que vaut cette image. Il en va de même pour nos désirs : comprendre ne supprime pas toujours l'envie, mais nous empêche d'en être dupes.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Citer et expliquer « conscients de leurs actions, ignorants des causes »</li><li>Raconter la pierre de la lettre 58</li><li>Opposer la volonté de Descartes et l'affirmation de l'idée chez Spinoza</li><li>Distinguer fatalisme, déterminisme et liberté spinoziste</li></ul>`},
/*EXOS*/
{i:"s204_01",u:204,t:"story",d:.2,nw:"L'illusion du libre arbitre",q:"Samir affirme avoir choisi seul de créer sa start-up. Que lui répond Julien ?",sc:[{who:"Samir",txt:"Personne ne m'a influencé, c'est mon choix !"}],o:["« Tu as choisi, mais tu n'as pas choisi ce qui t'a fait choisir. »","« Tu as raison, un vrai choix ne dépend jamais d'aucune cause extérieure. »","« Tu n'as rien choisi du tout, donc tu n'es responsable de rien du tout. »","« C'est ton coach qui a choisi à ta place, il faut lui rendre sa décision. »"],a:0,w:"Conscient des actes, ignorant des causes : voilà l'illusion. Le coach, les amis, le père sont des causes de son désir."},
{i:"s204_02",u:204,t:"fill",d:.2,q:"Les hommes se croient libres parce qu'ils sont conscients de leurs actions et ___ des causes qui les déterminent.",o:["ignorants","maîtres","créateurs","juges"],a:0,w:"E2P35, scolie. La liberté imaginaire, c'est une ignorance des causes."},
{i:"s204_03",u:204,t:"mcq",d:.25,q:"Dans la lettre 58, quel objet Spinoza imagine-t-il capable de penser ?",o:["Une pierre lancée","Une horloge murale","Un navire à voile","Une plume d'oie"],a:0,w:"Une pierre en mouvement, qui croirait rouler parce qu'elle le veut. La pierre qui roule se croit libre."},
{i:"s204_04",u:204,t:"tf",d:.25,q:"Pour Spinoza, la volonté et l'entendement sont une seule et même chose.",a:true,w:"E2P49, corollaire : voluntas et intellectus unum et idem sunt. Il n'y a pas de faculté qui signerait les idées."},
{i:"s204_05",u:204,t:"match",d:.25,q:"Associe chaque exemple de la lettre 58 à ce qu'il croit vouloir librement.",p:[["L'enfant","Le lait"],["L'homme en colère","La vengeance"],["L'ivrogne","Ce qu'il dit"],["La pierre","Continuer de rouler"]],w:"Tous sont conscients de leur désir et ignorants de ses causes."},
{i:"s204_06",u:204,t:"story",d:.3,q:"Léa est jalouse d'une start-up concurrente qui vient de lever 5 millions. Elle se reproche de « ne pas contrôler » sa jalousie. Que lui dit Julien ?",sc:[{who:"Léa",txt:"Je devrais juste décider de ne pas être jalouse."}],o:["« Tu ne la chasseras pas par décret : cherche l'idée qui la produit. »","« Oui, il suffit de vouloir très fort pour que la jalousie disparaisse. »","« La jalousie prouve que tu es une mauvaise personne, il faut l'avouer. »","« Lève 6 millions et la jalousie disparaîtra aussitôt, c'est certain. »"],a:0,w:"L'idée « son succès diminue ma valeur » produit mécaniquement la jalousie. On la change en formant une idée plus juste, pas par un ordre de la volonté."},
{i:"s204_07",u:204,t:"sort",d:.3,q:"Classe chaque phrase : fatalisme ou déterminisme spinoziste ?",bins:["Fatalisme","Déterminisme spinoziste"],it:[["C'était écrit, je n'y peux rien",0],["Tout a des causes que je peux connaître",1],["Le destin m'a puni",0],["Comprendre les causes me permet d'agir",1],["Inutile d'essayer",0]],w:"Le fatalisme résigne ; le déterminisme de Spinoza invite à connaître pour agir."},
{i:"s204_08",u:204,t:"tiles",d:.3,q:"Reconstitue l'image de la lettre 58.",a:["la","pierre","qui","roule","se","croit","libre"],dd:["mousse","sait","veut"],w:"Lettre 58 à Schuller, 1674. Si elle pouvait penser, elle croirait rouler parce qu'elle le veut."},
{i:"s204_09",u:204,t:"fill",d:.35,q:"Pour Spinoza, être libre, c'est agir par la seule ___ de sa nature.",o:["nécessité","volonté","fantaisie","morale"],a:0,w:"Définition 7 de la partie I. La liberté n'est pas l'absence de causes, mais le fait d'être soi-même la cause de ce qu'on fait."},
{i:"s204_10",u:204,t:"story",d:.35,q:"Maud objecte : « Si personne n'est libre, les criminels sont excusés ». Que répond Julien avec Spinoza ?",sc:[{who:"Maud",txt:"Alors on ne peut plus punir personne ?"}],o:["« Comprendre un acte ne le rend pas moins nuisible : on s'en protège. »","« Exactement, Spinoza voulait qu'on vide toutes les prisons de Hollande. »","« Les criminels sont libres, eux, contrairement aux gens honnêtes. »","« Il faut punir encore plus fort, puisqu'ils ne peuvent pas changer. »"],a:0,w:"L'exemple du chien enragé : excusable, mais on s'en protège. Comprendre supprime la haine, pas la prudence."},
{i:"s204_11",u:204,t:"multi",d:.35,q:"Quelles thèses sont celles de Descartes, et non de Spinoza ?",o:["La volonté est infinie","On peut suspendre son jugement","L'âme peut acquérir un pouvoir absolu sur ses passions","La volonté est distincte de l'entendement","Chaque idée affirme déjà quelque chose"],a:[0,1,2,3],w:"La dernière est la thèse de Spinoza, qui lui permet de réfuter les quatre autres."},
{i:"s204_12",u:204,t:"mcq",d:.4,q:"Quel exemple Spinoza donne-t-il pour montrer qu'une idée affirme d'elle-même ?",o:["Le triangle et la somme de ses angles","Le soleil qui se lève chaque matin","La pomme qui tombe de l'arbre","Le cercle et la longueur de son rayon"],a:0,w:"L'idée du triangle affirme que ses trois angles valent deux droits. Pas besoin d'une volonté pour signer : l'affirmation est dans l'idée."},
{i:"s204_13",u:204,t:"tf",d:.4,q:"Spinoza pense que le déterminisme doit rendre l'homme passif et résigné.",a:false,w:"Au contraire : connaître les causes est le seul chemin vers la liberté. La résignation, c'est le fatalisme."},
{i:"s204_14",u:204,t:"story",d:.45,q:"Samir objecte : « Hier, j'ai vaincu ma flemme et je suis allé à la salle. C'est bien ma volonté ! » Que répond Julien ?",sc:[{who:"Samir",txt:"Là, j'ai bien choisi contre mon envie."}],o:["« Un désir plus fort, venu d'une autre idée, l'a emporté sur la flemme. »","« Oui, c'est la preuve que ta volonté est libre et toute-puissante. »","« Tu y es allé par hasard, sans aucune raison, c'est tout ce qu'on peut dire. »","« C'est la salle de sport qui t'a choisi, pas toi qui as choisi d'y aller. »"],a:0,w:"C'est l'objection cartésienne relevée par Théo Lion. Pour Spinoza, un affect ne cède qu'à un affect plus fort (E4P7) : l'idée de ta santé ou de ta fierté a gagné."},
{i:"s204_15",u:204,t:"order",d:.45,q:"Remets dans l'ordre le mécanisme de la jalousie selon Spinoza et Théo Lion.",it:["Un concurrent réussit","L'idée confuse « il vaut plus que moi » s'installe","L'affect de jalousie se produit","La volonté ne peut pas le refuser par décret","Seule une idée plus claire peut le transformer"],w:"L'affect découle d'une idée. On agit sur l'idée, pas sur la volonté."},
{i:"s204_16",u:204,t:"slider",d:.45,q:"En quelle année Spinoza écrit-il à Schuller la lettre de la pierre ?",min:1650,max:1680,step:1,a:1674,tol:0,pre:"",un:"",w:"1674, trois ans avant sa mort. C'est la lettre 58."},
{i:"s204_17",u:204,t:"fill",d:.5,q:"Même en connaissant la vraie distance, nous continuons d'imaginer le soleil à environ 200 ___.",o:["pieds","lieues","mètres","coudées"],a:0,w:"E2P35, scolie. L'image reste ; l'erreur disparaît, parce qu'on sait ce qu'elle vaut."},
{i:"s204_18",u:204,t:"sort",d:.5,q:"Classe chaque affirmation : conforme au texte de Spinoza ou simplification de la vidéo ?",bins:["Conforme","Simplifiée"],it:[["Même en sachant la distance, on imagine le soleil proche",0],["L'erreur sur le soleil persiste tant qu'on ignore la distance",1],["La volonté et l'entendement sont une même chose",0],["Dieu est la cause non causée au sommet de la chaîne",1]],w:"La vidéo simplifie parfois. Le texte dit plus fin : l'image persiste, l'erreur disparaît ; Dieu est cause immanente."},
{i:"s204_19",u:204,t:"story",d:.5,q:"Léa, en regardant la Porsche d'un investisseur, sent l'envie d'en avoir une, tout en sachant que ça ne la rendra pas heureuse. Qu'en dirait Spinoza ?",sc:[{who:"Léa",txt:"Je sais que c'est idiot, mais j'en ai envie quand même."}],o:["« Comme le soleil vu proche : l'image reste, tu n'en es plus dupe. »","« Si tu en as encore envie, c'est que tu n'as rien compris du tout. »","« Achète-la tout de suite, l'envie prouve que c'est bon pour toi. »","« Ta volonté est trop faible, il faut l'entraîner chaque matin. »"],a:0,w:"L'imagination ne disparaît pas d'un coup ; savoir ce qu'elle vaut change déjà son pouvoir. La suite du cours montre comment l'affaiblir."},
{i:"s204_20",u:204,t:"match",d:.55,q:"Associe chaque référence à son contenu.",p:[["E2P35 scolie","Conscients des actions, ignorants des causes"],["E2P48","Aucune volonté absolue dans l'esprit"],["E2P49 corollaire","Volonté et entendement, même chose"],["Lettre 58","La pierre qui se croit libre"]],w:"Quatre textes pour démontrer que le libre arbitre est une illusion."},
{i:"s204_21",u:204,t:"tf",d:.55,q:"Dans Les Passions de l'âme, Descartes pense qu'une âme bien conduite peut acquérir un pouvoir absolu sur ses passions.",a:true,w:"C'est l'optimisme cartésien de la volonté. Spinoza le juge irréaliste dans la préface de la partie V."},
{i:"s204_22",u:204,t:"mcq",d:.6,q:"Quelle est la différence entre libre arbitre et liberté spinoziste ?",o:["Choisir sans cause, contre agir par sa nature","Choisir vite, contre choisir très lentement","Obéir à Dieu, contre obéir aux lois de l'État","Aucune, ce sont deux mots pour la même chose"],a:0,w:"Le libre arbitre est une illusion ; la liberté spinoziste consiste à être la cause adéquate de ses actes, grâce à la connaissance."},
{i:"s204_23",u:204,t:"story",d:.6,q:"Anaïs a raté une présentation et se traite d'idiote. Julien lui propose autre chose. Quoi ?",sc:[{who:"Anaïs",txt:"J'aurais dû faire mieux, je n'ai aucune excuse."}],o:["« Regarde les causes : manque de préparation, fatigue, trac. Et agis dessus. »","« Tu as raison, tu aurais pu tout faire autrement si tu l'avais vraiment voulu. »","« Ce n'est pas grave, rien n'a de cause, c'était simplement le hasard du jour. »","« Arrête de préparer tes présentations, le destin décide de toute façon. »"],a:0,w:"L'auto-reproche suppose un libre arbitre imaginaire. Chercher les causes donne prise sur la prochaine fois."},
{i:"s204_24",u:204,t:"multi",d:.65,q:"Quelles causes ont pu déterminer le désir d'entreprendre de Samir ?",o:["Le coach sur Instagram","Ses amis de promo","La phrase de son père","L'image valorisée de l'entrepreneur","Une décision sans aucune cause"],a:[0,1,2,3],w:"Une décision sans cause n'existe pas pour Spinoza. Identifier ces causes est le premier pas vers un désir plus libre."},
{i:"s204_25",u:204,t:"fill",d:.65,q:"Selon Spinoza, celui que la morsure d'un chien rend enragé est ___, mais on a raison de s'en protéger.",o:["excusable","coupable","libre","condamné"],a:0,w:"Lettre à Oldenburg. Comprendre la cause évite la haine, pas la prudence."},
{i:"s204_26",u:204,t:"tiles",d:.7,q:"Reconstitue le moyen mnémotechnique de l'illusion.",a:["conscient","des","actes","ignorant","des","causes"],dd:["maître","libre","volonté"],w:"Conscient des actes, ignorant des causes : voilà l'illusion."},
{i:"s204_27",u:204,t:"sort",d:.7,q:"Classe chaque réaction : fondée sur le libre arbitre imaginaire ou sur la compréhension ?",bins:["Libre arbitre imaginaire","Compréhension"],it:[["« Il l'a fait exprès, je le hais »",0],["« Qu'est-ce qui l'a poussé à agir ainsi ? »",1],["« J'aurais dû vouloir plus fort »",0],["« Quelles causes vais-je changer ? »",1]],w:"La haine et la culpabilité reposent souvent sur l'illusion du libre arbitre. La compréhension ouvre l'action."},
{i:"s204_28",u:204,t:"story",d:.75,q:"Rappel du module 4 : Samir demande si Dieu a décidé de sa start-up.",sc:[{who:"Samir",txt:"Si tout est déterminé, c'est Dieu qui a voulu ma boîte ?"}],o:["« Dieu ne veut rien : ta boîte vient d'une chaîne de causes. »","« Oui, Dieu a un plan précis pour chaque entreprise, dont la tienne. »","« Non, ta start-up est le seul événement du monde sans aucune cause. »","« Dieu a voulu ta boîte, mais il pourrait changer d'avis demain. »"],a:0,w:"Déterminisme n'est pas providence : il y a des causes, pas d'intention divine. Deus sive Natura."},
{i:"s204_29",u:204,t:"mcq",d:.75,q:"Pourquoi la volonté ne peut-elle pas « refuser » une idée selon Spinoza ?",o:["Parce que l'affirmation est contenue dans l'idée","Parce que Dieu interdit de refuser les idées","Parce que la volonté est trop fatiguée le soir","Parce que les idées viennent toujours des autres"],a:0,w:"Il n'y a pas d'idée neutre en attente de signature. Pour changer une affirmation, il faut une autre idée, plus claire."},
{i:"s204_30",u:204,t:"tf",d:.8,q:"Pour Spinoza, comprendre les causes de nos actes supprime toute responsabilité et toute prudence.",a:false,w:"Cela supprime la haine et le blâme moral, pas la nécessité de se protéger ni de corriger. Le chien enragé est excusable, mais on s'en garde."},
{i:"s204_31",u:204,t:"match",d:.8,q:"Associe chaque mot à sa définition spinoziste.",p:[["Libre arbitre","Illusion de choisir sans cause"],["Liberté","Agir par la nécessité de sa nature"],["Fatalisme","Résignation devant un destin"],["Déterminisme","Tout a des causes nécessaires"]],w:"Quatre mots souvent confondus. Spinoza rejette le premier et le troisième, défend le deuxième et le quatrième."},
{i:"s204_32",u:204,t:"story",d:.85,q:"Synthèse : Samir, un peu sonné, demande ce qui lui reste si le libre arbitre n'existe pas.",sc:[{who:"Samir",txt:"Alors je ne suis qu'une pierre qui roule ?"}],o:["« Une pierre qui peut comprendre ses causes : là commence ta liberté. »","« Oui, et il n'y a absolument rien à faire, sinon attendre la fin du chemin. »","« Non, toi seul es libre, contrairement à tous les autres humains. »","« Tu peux redevenir libre en décidant très fort de ne plus être déterminé. »"],a:0,w:"L'homme n'est pas une pierre : il peut connaître les causes qui le déterminent. C'est la porte d'entrée de la libération spinoziste."}
