/*UNIT*/
{id:205,c:"SPINO",n:"Module 7",t:"Le conatus : tu es du désir sur pattes",col:"--purple",ic:"🔥",guide:`
<h3>Pourquoi je veux grossir ?</h3>
<div class="gstory">Réunion du lundi chez Cargo &amp; Co. Victor, l'investisseur, projette une courbe : « Objectif 2027 : 50 villes, 300 salariés. » Tout le monde applaudit. Le soir, Léa demande à Julien : « Je veux vraiment tout ça ? Ou je le veux parce que Victor l'a projeté en grand sur un écran ? » Julien : « Théo Lion s'est posé la même question. Il voulait faire grossir son chiffre d'affaires vite. En creusant, il a trouvé un vrai désir de grandir, mais aussi un besoin de reconnaissance, "une crise d'adolescence", dit-il. Spinoza commence par là : tu es fait de désir. La question n'est pas d'arrêter de désirer. C'est de savoir <b>ce que</b> tu désires, et <b>pourquoi</b>. »</div>
<h3>Le conatus, cœur de la partie III</h3>
<ul><li><b>E3P6</b> : « Chaque chose, autant qu'il est en elle, s'efforce de <b>persévérer dans son être</b>. » Cet effort s'appelle le <b>conatus</b> (du latin <i>conari</i>, s'efforcer).</li>
<li><b>E3P7</b> : cet effort n'est rien d'autre que l'<b>essence actuelle</b> de la chose. Tu n'as pas un conatus : tu <b>es</b> ton conatus.</li>
<li><b>E3P4</b> : aucune chose ne peut être détruite, sinon par une cause <b>extérieure</b>. Rien ne cherche sa propre destruction de l'intérieur.</li></ul>
<p>Persévérer, ce n'est pas seulement survivre : c'est s'efforcer d'<b>augmenter sa puissance d'agir</b>. La plante pousse vers la lumière, l'enfant veut apprendre à marcher, l'entrepreneur veut faire grandir son projet.</p>
<h3>Volonté, appétit, désir</h3>
<table><tr><th>Nom</th><th>Le conatus rapporté à…</th></tr>
<tr><td><b>Volonté</b></td><td>l'esprit seul</td></tr>
<tr><td><b>Appétit</b></td><td>l'esprit et le corps ensemble</td></tr>
<tr><td><b>Désir</b> (cupiditas)</td><td>l'appétit accompagné de la <b>conscience</b> de lui-même</td></tr></table>
<p>Première définition des affects, à la fin de la partie III : « <b>Le désir est l'essence même de l'homme</b>. » Théo Lion reprend une formule qu'il aime : nous sommes « du désir sur pattes ».</p>
<h3>La phrase qui renverse tout (E3P9, scolie)</h3>
<p>« Nous ne désirons pas une chose parce que nous la jugeons bonne ; c'est au contraire parce que nous la désirons que nous la jugeons bonne. »</p>
<div class="gmnemo"><b>« Le désir d'abord, le bien ensuite. »</b> Ou plus court : <b>« D avant B »</b>. Et pour le conatus : <b>« Rien ne s'éteint de l'intérieur »</b> : on ne cesse de persévérer que sous l'effet d'une cause extérieure.</div>
<p>Conséquence énorme : le désir n'est pas guidé par le bien, il le fabrique. Or le désir est lui-même un affect, modelé par des causes extérieures (les images, les autres, la société). L'esprit s'efforce d'imaginer ce qui augmente sa puissance (E3P12), mais il se <b>trompe</b> souvent, parce qu'il imagine. Ce que nous croyons l'expression la plus intime de nous-mêmes, notre désir, est en partie façonné du dehors. C'est l'origine de nos erreurs (module 9).</p>
<h3>Le désir dans l'entreprise</h3>
<p>Le philosophe et économiste <b>Frédéric Lordon</b>, dans <i>Capitalisme, désir et servitude</i> (2010), relit Spinoza : une entreprise est une machine à <b>capter le conatus</b> des salariés, à aligner leurs désirs sur le désir du patron (ce qu'il appelle un désir « maître »). Un bon outil pour Léa : ses 40 salariés désirent-ils <b>avec</b> elle, ou sont-ils seulement alignés ?</p>
<p>Théo Lion témoigne aussi : quand son moteur de départ (reconnaissance, statut) s'est éteint, il a moins publié sur YouTube. Il a eu peur de ne plus trouver de raison. Puis un nouveau désir est né : explorer des idées et les partager. Le conatus ne disparaît pas, il <b>change d'objet</b>.</p>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Citer E3P6 et définir le conatus</li><li>Distinguer volonté, appétit et désir</li><li>Expliquer le renversement de E3P9, scolie, et ses conséquences</li><li>Appliquer ces idées à un projet d'entreprise</li></ul>`},
/*EXOS*/
{i:"s205_01",u:205,t:"fill",d:.2,nw:"Le conatus",q:"Chaque chose s'efforce de persévérer dans son être : cet effort s'appelle le ___.",o:["conatus","cogito","karma","nirvana"],a:0,w:"Conatus, du latin conari, s'efforcer. E3P6. C'est l'essence même de chaque chose."},
{i:"s205_02",u:205,t:"story",d:.2,q:"Léa se demande si elle veut vraiment 50 villes et 300 salariés. Que lui conseille Julien ?",sc:[{who:"Léa",txt:"Je le veux, ou je le veux parce que Victor l'a projeté en grand ?"}],o:["« Désirer est normal ; cherchons ce que tu désires vraiment, et pourquoi. »","« Arrête de désirer quoi que ce soit, c'est la seule voie vers la sagesse. »","« Si Victor le veut, c'est forcément bon pour toi, il a plus d'expérience. »","« Plus un objectif est grand, plus il est authentique, c'est une règle. »"],a:0,w:"On ne supprime pas le désir, c'est notre essence. On en examine l'objet et les causes. Le désir d'abord, le bien ensuite."},
{i:"s205_03",u:205,t:"tiles",d:.25,q:"Reconstitue la proposition E3P6.",a:["chaque","chose","s'efforce","de","persévérer","dans","son","être"],dd:["disparaître","Dieu","parfois"],w:"Autant qu'il est en elle. C'est la définition du conatus."},
{i:"s205_04",u:205,t:"match",d:.25,q:"Associe chaque nom à ce à quoi le conatus est rapporté.",p:[["Volonté","L'esprit seul"],["Appétit","L'esprit et le corps"],["Désir","L'appétit conscient de lui-même"],["Conatus","L'effort de persévérer dans son être"]],w:"E3P9, scolie. Le désir, c'est l'appétit avec conscience."},
{i:"s205_05",u:205,t:"tf",d:.25,q:"Pour Spinoza, nous désirons une chose parce que nous l'avons d'abord jugée bonne.",a:false,w:"C'est l'inverse : nous la jugeons bonne parce que nous la désirons. Le désir d'abord, le bien ensuite."},
{i:"s205_06",u:205,t:"mcq",d:.3,q:"Comment Spinoza définit-il le désir dans la première définition des affects ?",o:["L'essence même de l'homme","Un défaut à corriger vite","Une faiblesse du corps","Un péché d'orgueil"],a:0,w:"« Le désir est l'essence même de l'homme. » Théo Lion : nous sommes du désir sur pattes."},
{i:"s205_07",u:205,t:"story",d:.3,q:"Samir dit : « Si je désire ma start-up, c'est qu'elle est bonne pour moi, non ? » Que répond Julien ?",sc:[{who:"Samir",txt:"Mon désir ne peut pas se tromper sur ce qui est bon."}],o:["« Tu la juges bonne parce que tu la désires : reste à savoir d'où vient ce désir. »","« Oui, le désir est toujours un guide infaillible vers ce qui est bon pour soi. »","« Non, tout désir est mauvais, il faut toujours faire l'inverse de ce qu'on veut. »","« Le désir n'a aucun lien avec le jugement, ce sont deux mondes séparés. »"],a:0,w:"E3P9, scolie. Le désir fabrique le jugement de valeur. Or le désir peut être modelé par des causes extérieures : il faut l'examiner."},
{i:"s205_08",u:205,t:"sort",d:.3,q:"Classe chaque exemple : expression du conatus ou non ?",bins:["Conatus","Pas le conatus"],it:[["La plante qui pousse vers la lumière",0],["L'enfant qui apprend à marcher",0],["L'entrepreneur qui veut faire grandir son projet",0],["Une pierre brisée par un marteau",1]],w:"Toute chose s'efforce de persévérer et d'augmenter sa puissance. Sa destruction vient toujours du dehors (E3P4). L'appétit est ce même effort rapporté au corps et à l'esprit."},
{i:"s205_09",u:205,t:"fill",d:.35,q:"Aucune chose ne peut être détruite, sinon par une cause ___.",o:["extérieure","intérieure","divine","morale"],a:0,w:"E3P4. Rien ne s'éteint de l'intérieur : on ne cesse de persévérer que sous l'effet du dehors."},
{i:"s205_10",u:205,t:"multi",d:.35,q:"Quelles causes, selon Théo Lion, nourrissaient son désir de faire grossir son entreprise ?",o:["Un vrai désir de croissance","Un besoin de reconnaissance","Le statut","Une forme de crise d'adolescence","L'ordre d'un investisseur"],a:[0,1,2,3],w:"Il le dit lui-même : un vrai désir de grandir, mêlé à la reconnaissance et au statut. Ces derniers moteurs se sont éteints avec le temps."},
{i:"s205_11",u:205,t:"story",d:.35,q:"Anaïs a perdu l'envie de travailler sur l'expansion et craint de « ne plus rien désirer ». Que lui dit Julien ?",sc:[{who:"Anaïs",txt:"J'ai l'impression d'être éteinte."}],o:["« Le désir ne disparaît pas, il change d'objet : cherchons lequel. »","« C'est normal, le conatus s'éteint tout seul après quarante ans environ. »","« Force-toi à désirer l'expansion, la motivation reviendra avec le temps. »","« Tu n'as jamais désiré, tu faisais seulement semblant depuis le début. »"],a:0,w:"Comme pour Théo Lion : le moteur de départ s'est tari, un autre est né (explorer des idées et les partager)."},
{i:"s205_12",u:205,t:"mcq",d:.4,q:"Que veut dire « persévérer dans son être » chez Spinoza ?",o:["S'efforcer d'exister et d'accroître sa puissance","Rester exactement identique toute sa vie durant","Survivre à n'importe quel prix, même seul","Refuser tout changement, par simple principe"],a:0,w:"Le conatus n'est pas une simple survie : c'est un effort vers plus de puissance d'agir."},
{i:"s205_13",u:205,t:"order",d:.4,q:"Remets dans l'ordre le mécanisme décrit par E3P9, scolie.",it:["Le conatus me pousse","Un désir se porte sur un objet","Je juge cet objet bon","Je cherche des raisons de le poursuivre"],w:"Le désir d'abord, le bien ensuite, puis les justifications. Voilà pourquoi on peut désirer ce qui rend triste."},
{i:"s205_14",u:205,t:"tf",d:.4,q:"Selon E3P7, l'effort de persévérer n'est rien en dehors de l'essence actuelle de la chose.",a:true,w:"Tu n'as pas un conatus, tu es ton conatus."},
{i:"s205_15",u:205,t:"story",d:.45,q:"Victor, l'investisseur, dit que « les salariés doivent désirer ce que désire l'entreprise ». Quel penseur relit Spinoza sur ce point ?",sc:[{who:"Victor",txt:"Le secret, c'est que tout le monde veuille la même chose que moi."}],o:["« Frédéric Lordon : l'entreprise capte et aligne le conatus des salariés. »","« Descartes : chaque salarié a une volonté libre qui choisit l'entreprise. »","« Épicure : il faut que les salariés désirent le moins possible au travail. »","« Aristote : chaque salarié a une finalité naturelle fixée par Dieu. »"],a:0,w:"Capitalisme, désir et servitude (2010). Lordon parle d'un désir maître auquel les autres désirs sont alignés."},
{i:"s205_16",u:205,t:"match",d:.45,q:"Associe chaque référence à sa thèse.",p:[["E3P4","Destruction par une cause extérieure"],["E3P6","Effort de persévérer dans son être"],["E3P7","Cet effort est l'essence de la chose"],["E3P9 scolie","On juge bon ce qu'on désire"]],w:"Les quatre piliers de la théorie du désir."},
{i:"s205_17",u:205,t:"slider",d:.5,q:"En quelle année Frédéric Lordon publie-t-il Capitalisme, désir et servitude ?",min:1990,max:2025,step:1,a:2010,tol:0,pre:"",un:"",w:"2010, avec pour sous-titre Marx et Spinoza."},
{i:"s205_18",u:205,t:"fill",d:.5,q:"En latin, le désir se dit ___, dans la définition des affects.",o:["cupiditas","gloria","libido","voluntas"],a:0,w:"Cupiditas est ipsa hominis essentia : le désir est l'essence même de l'homme."},
{i:"s205_19",u:205,t:"sort",d:.5,q:"Classe chaque phrase : fidèle à Spinoza ou contraire ?",bins:["Fidèle","Contraire"],it:[["Il faut éteindre tout désir",1],["Le désir est notre essence",0],["Nos désirs sont en partie façonnés du dehors",0],["Le désir montre toujours le vrai bien",1],["Le conatus peut changer d'objet",0]],w:"Spinoza n'est pas ascète : on ne supprime pas le désir. Mais il n'est pas naïf : le désir peut se tromper d'objet."},
{i:"s205_20",u:205,t:"story",d:.55,q:"Rappel du module 6 : Samir dit « mon désir d'entreprendre est libre puisqu'il est à moi ». Que lui dit Julien ?",sc:[{who:"Samir",txt:"C'est MON désir, personne ne peut me l'avoir mis dans la tête."}],o:["« Ton désir est bien toi, mais il a des causes que tu ne vois pas. »","« Exact, un désir qui est le tien ne peut avoir aucune cause extérieure. »","« Ce n'est pas ton désir du tout, c'est entièrement celui de ton coach. »","« Les désirs viennent de Dieu, qui les distribue au hasard à chacun. »"],a:0,w:"Conscient des actes, ignorant des causes. Le désir est notre essence, mais il est affecté par des causes extérieures."},
{i:"s205_21",u:205,t:"mcq",d:.55,q:"Pourquoi l'esprit se trompe-t-il souvent en orientant son désir ?",o:["Parce qu'il imagine au lieu de connaître","Parce que Dieu le trompe volontairement","Parce que la volonté est bien trop faible","Parce qu'il désire beaucoup trop peu de choses"],a:0,w:"L'esprit s'efforce d'imaginer ce qui augmente sa puissance (E3P12), mais l'imagination reflète l'état du corps, pas la nature des choses (module 9)."},
{i:"s205_22",u:205,t:"tiles",d:.6,q:"Reconstitue la formule sur le désir et le bien.",a:["le","désir","d'abord","le","bien","ensuite"],dd:["jamais","devoir","raison"],w:"D avant B : on juge bon ce qu'on désire."},
{i:"s205_23",u:205,t:"multi",d:.6,q:"Quelles questions Léa peut-elle se poser pour examiner son désir de croissance ?",o:["D'où vient ce désir ?","Est-ce que j'apprends et grandis en le poursuivant ?","Est-ce que je le désirerais si personne ne le voyait ?","Est-ce le désir de Victor ou le mien ?","Comment supprimer tout désir ?"],a:[0,1,2,3],w:"On n'essaie pas de supprimer le désir. On cherche ses causes et ce qu'il fait à notre puissance d'agir."},
{i:"s205_24",u:205,t:"story",d:.65,q:"Maud, la mère, trouve que « trop désirer, c'est de l'avidité ». Que lui répond Julien ?",sc:[{who:"Maud",txt:"On m'a appris qu'il fallait se contenter de peu."}],o:["« Spinoza ne condamne pas le désir : certains rendent libre, d'autres esclave. »","« Tu as raison, Spinoza dit exactement qu'il faut se contenter de très peu. »","« Au contraire, il faut désirer tout et n'importe quoi, sans aucune limite. »","« Spinoza pensait que seuls les riches ont le droit de désirer beaucoup. »"],a:0,w:"L'Éthique intègre le désir d'accomplir au lieu de le condamner. Le vrai critère : ce désir augmente-t-il ou diminue-t-il notre puissance ?"},
{i:"s205_25",u:205,t:"tf",d:.65,q:"Pour Spinoza, il existe en nous une tendance intérieure à nous détruire nous-mêmes.",a:false,w:"E3P4 : rien ne peut être détruit sinon par une cause extérieure. Même les comportements destructeurs ont des causes venues du dehors."},
{i:"s205_26",u:205,t:"fill",d:.7,q:"Le désir, c'est l'appétit accompagné de la ___ de lui-même.",o:["conscience","honte","peur","nostalgie"],a:0,w:"E3P9, scolie. L'appétit est l'effort de l'esprit et du corps ; le désir, c'est cet appétit quand on en a conscience. L'appétit, rapporté au corps et à l'esprit, devient désir quand il est conscient."},
{i:"s205_27",u:205,t:"match",d:.7,q:"Associe chaque personnage à la situation de son désir.",p:[["Théo Lion","Moteur de reconnaissance éteint, nouveau désir de partager"],["Samir","Désir d'entreprendre aux causes mal connues"],["Léa","Objectif projeté par un investisseur"],["Anaïs","Désir qui cherche un nouvel objet"]],w:"Quatre situations du conatus. Aucune ne demande de supprimer le désir, toutes demandent d'en comprendre les causes."},
{i:"s205_28",u:205,t:"story",d:.75,q:"Léa veut expliquer le conatus à son équipe en une image. Laquelle choisis-tu ?",sc:[{who:"Léa",txt:"Il me faut une image simple pour la réunion de demain."}],o:["« La plante qui pousse vers la lumière tant qu'on ne l'arrache pas. »","« La pierre immobile qui attend qu'on la déplace pour exister vraiment. »","« Le robinet qu'on ouvre et qu'on ferme selon les besoins du moment. »","« La montre qu'on remonte chaque matin pour qu'elle avance. »"],a:0,w:"Le conatus est un effort interne, continu, orienté vers plus de puissance, interrompu seulement du dehors."},
{i:"s205_29",u:205,t:"sort",d:.75,q:"Classe chaque désir de Léa : lié à sa puissance d'agir ou à l'image des autres ?",bins:["Puissance d'agir","Image des autres"],it:[["Concevoir un meilleur vélo",0],["Être en couverture d'un magazine",1],["Apprendre à diriger une équipe",0],["Lever plus que son concurrent",1],["Résoudre le problème des livreurs",0]],w:"Un premier tri, avant le module 9 : certains désirs augmentent vraiment la puissance, d'autres dépendent du regard d'autrui."},
{i:"s205_30",u:205,t:"mcq",d:.8,q:"Que devient le conatus quand un moteur de désir s'éteint, selon l'expérience de Théo Lion ?",o:["Il se porte sur un nouvel objet","Il disparaît définitivement","Il se retourne contre soi-même","Il devient de la volonté pure et libre"],a:0,w:"Le désir de reconnaissance s'est tari ; celui d'explorer et de partager des idées l'a remplacé. Le conatus est notre essence : il ne s'arrête pas."},
{i:"s205_31",u:205,t:"tf",d:.8,q:"Pour Lordon, relisant Spinoza, le travail salarié repose sur l'alignement des désirs des salariés sur celui de l'entreprise.",a:true,w:"Il parle de capter le conatus. Pour Léa, la question devient : son équipe partage-t-elle vraiment son désir ?"},
{i:"s205_32",u:205,t:"story",d:.85,q:"Synthèse : Samir résume le module. Quelle phrase est la plus juste ?",sc:[{who:"Samir",txt:"Donc le désir, pour Spinoza…"}],o:["« C'est notre essence ; il fabrique nos jugements : connaissons ses causes. »","« C'est un défaut qu'on doit éteindre pour devenir enfin sage et serein. »","« C'est un guide parfait qu'il faut suivre sans jamais se poser de question. »","« C'est une invention des entreprises pour faire travailler les salariés. »"],a:0,w:"Tu es du désir sur pattes. Le désir d'abord, le bien ensuite. D'où la question du module 9 : pourquoi désire-t-on parfois ce qui rend triste ?"}
