/*UNIT*/
{id:206,c:"SPINO",n:"Module 8",t:"Les affects : désir, joie, tristesse et toute leur famille",col:"--purple",ic:"🎭",guide:`
<h3>La journée en montagnes russes</h3>
<div class="gstory">Mercredi chez Cargo &amp; Co. 9 h : un article élogieux dans Sud Ouest, Léa rayonne. 11 h : le concurrent parisien VéloFret annonce une levée de 5 millions, elle se crispe. 14 h : Hugo, le nouveau stagiaire, réussit enfin à monter seul une roue, toute l'équipe applaudit et Léa sourit sincèrement. 17 h : Victor écrit « Où en sont les chiffres ? », et une boule se forme dans son ventre. Le soir, elle dit à Julien : « J'ai vécu dix émotions différentes. » Julien sort une feuille : « Spinoza n'en compte que trois. Tout le reste, ce sont des mélanges. »</div>
<h3>Qu'est-ce qu'un affect ?</h3>
<p>Un <b>affect</b>, ce sont les affections du corps qui <b>augmentent ou diminuent sa puissance d'agir</b>, et en même temps les idées de ces affections (E3, définition 3). Quand nous en sommes la cause <b>adéquate</b> (complète), c'est une <b>action</b>. Sinon, c'est une <b>passion</b> : nous le subissons.</p>
<h3>Trois affects primaires (E3P11, scolie)</h3>
<table><tr><th>Affect</th><th>Définition</th></tr>
<tr><td><b>Désir</b></td><td>L'essence de l'homme, son conatus conscient (module 7)</td></tr>
<tr><td><b>Joie</b> (laetitia)</td><td>Le <b>passage</b> de l'homme d'une moindre à une plus grande perfection</td></tr>
<tr><td><b>Tristesse</b> (tristitia)</td><td>Le <b>passage</b> d'une plus grande à une moindre perfection</td></tr></table>
<p>« Perfection » ne veut pas dire « sans défaut » : c'est le degré de <b>réalité</b>, donc de <b>puissance d'agir</b>, d'un être. La joie n'est pas un état, c'est un <b>passage</b> : quelqu'un qui naîtrait parfait n'éprouverait pas de joie. Exemples de Théo Lion : réussir son permis (on devient plus libre de ses déplacements), comprendre enfin un exercice de maths, les « noob gains » des premiers mois de musculation.</p>
<div class="gmnemo"><b>« D.J.T. : Désir, Joie, Tristesse. Tout le reste, c'est D.J.T. plus une idée. »</b> Et la joie, c'est <b>l'ascenseur qui monte, pas l'étage</b>.</div>
<h3>La famille des affects (parmi les 48 définitions de la fin de la partie III)</h3>
<table><tr><th>Affect</th><th>Recette spinoziste</th></tr>
<tr><td><b>Amour</b></td><td>Joie accompagnée de l'idée d'une cause extérieure</td></tr>
<tr><td><b>Haine</b></td><td>Tristesse accompagnée de l'idée d'une cause extérieure</td></tr>
<tr><td><b>Espoir</b></td><td>Joie inconstante, née de l'idée d'une chose future dont l'issue est douteuse</td></tr>
<tr><td><b>Crainte</b></td><td>Tristesse inconstante, née de la même incertitude</td></tr>
<tr><td><b>Gloire</b></td><td>Joie accompagnée de l'idée d'une de nos actions que nous imaginons louée par les autres</td></tr>
<tr><td><b>Honte</b></td><td>Tristesse accompagnée de l'idée d'une de nos actions que nous imaginons blâmée par les autres</td></tr>
<tr><td><b>Envie</b></td><td>Haine qui attriste du bonheur d'autrui et réjouit de son malheur</td></tr>
<tr><td><b>Ambition</b></td><td>Désir immodéré de gloire</td></tr>
<tr><td><b>Émulation</b></td><td>Désir d'une chose, né de ce que nous imaginons que d'autres, semblables à nous, la désirent</td></tr></table>
<p>Pas d'espoir sans crainte. Celui qui espère doute, donc il craint. Celui qui craint doute, donc il espère. Quand le doute disparaît, l'espoir devient <b>sécurité</b> et la crainte devient <b>désespoir</b>.</p>
<h3>La fluctuation de l'âme</h3>
<p>Quand deux affects contraires nous tiraillent en même temps pour la même chose, Spinoza parle de <b>fluctuation de l'âme</b> (<i>fluctuatio animi</i>, E3P17, scolie). Théo Lion l'applique au succès : toute joie qui dépend d'une cause extérieure peut se renverser si la cause change. Un succès obtenu nourrit <b>déjà</b> la crainte de le perdre.</p>
<div class="gtrap">Nuance importante : Spinoza ne condamne pas les <b>passions joyeuses</b>. Elles augmentent vraiment la puissance, et elles sont un bon point de départ. Mais comme elles dépendent de causes extérieures, on ne peut pas en attendre une joie stable. Le vrai problème, ce sont les <b>passions tristes</b>. Et un point décisif : il n'existe d'affects actifs que de <b>joie et de désir</b>, jamais de tristesse (E3P59). Toute tristesse est une passion.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Définir affect, action et passion</li><li>Donner les trois affects primaires et définir la joie comme un passage</li><li>Reconstituer amour, haine, espoir, crainte, gloire, honte, envie, ambition, émulation</li><li>Expliquer la fluctuation de l'âme et l'appliquer au succès</li></ul>`},
/*EXOS*/
{i:"s206_01",u:206,t:"multi",d:.2,nw:"Les trois affects primaires",q:"Quels sont les trois affects primaires selon Spinoza ?",o:["Le désir","La joie","La tristesse","La colère","L'amour"],a:[0,1,2],w:"D.J.T. : désir, joie, tristesse (E3P11, scolie). La colère et l'amour sont des dérivés : D.J.T. plus une idée."},
{i:"s206_02",u:206,t:"fill",d:.2,q:"La joie est le passage d'une moindre à une plus grande ___.",o:["perfection","prospérité","sagesse","liberté"],a:0,w:"Définition 2 des affects. Perfection = réalité = puissance d'agir. C'est un passage, pas un état."},
{i:"s206_03",u:206,t:"match",d:.25,q:"Associe chaque affect à sa recette.",p:[["Amour","Joie + idée d'une cause extérieure"],["Haine","Tristesse + idée d'une cause extérieure"],["Gloire","Joie + idée d'une action louée par les autres"],["Honte","Tristesse + idée d'une action blâmée par les autres"]],w:"Tout le reste, c'est D.J.T. plus une idée."},
{i:"s206_04",u:206,t:"story",d:.25,q:"Léa a vécu « dix émotions » dans la journée. Comment Julien les ramène-t-il à Spinoza ?",sc:[{who:"Léa",txt:"Fierté, jalousie, attendrissement, angoisse… ça fait beaucoup."}],o:["« Ce sont des mélanges de désir, joie et tristesse, avec des idées. »","« Chaque émotion est une substance différente qui vit dans ton esprit. »","« Spinoza en compte exactement dix, et tu les as toutes eues aujourd'hui. »","« Ce sont des maladies, il faut toutes les soigner chez un médecin. »"],a:0,w:"Trois affects primaires ; les autres en dérivent quand on y joint l'idée d'une cause, d'un temps, d'un regard."},
{i:"s206_05",u:206,t:"tf",d:.25,q:"Pour Spinoza, la joie est un état de perfection atteint une fois pour toutes.",a:false,w:"C'est un passage, pas un état. L'ascenseur qui monte, pas l'étage. Un être né parfait n'éprouverait pas de joie."},
{i:"s206_06",u:206,t:"sort",d:.3,q:"Classe chaque moment de la journée de Léa : joie ou tristesse ?",bins:["Joie","Tristesse"],it:[["Article élogieux dans Sud Ouest",0],["Levée de 5 millions du concurrent",1],["Le stagiaire réussit seul sa roue",0],["Mail de Victor sur les chiffres",1]],w:"À chaque fois, la puissance d'agir monte ou descend. Reste à savoir quelle idée accompagne chaque passage."},
{i:"s206_07",u:206,t:"mcq",d:.3,q:"Qu'est-ce que l'envie selon Spinoza ?",o:["Une haine attristée du bonheur d'autrui","Un désir sain d'imiter les meilleurs","Une joie d'être admiré par ses pairs","Un amour déçu qui se venge en secret"],a:0,w:"Définition 23 : la haine qui attriste du bonheur d'autrui et réjouit de son malheur. À ne pas confondre avec l'émulation."},
{i:"s206_08",u:206,t:"story",d:.3,q:"Léa espère que Victor sera content des chiffres, mais elle a peur qu'il ne le soit pas. Que dit Spinoza de ce mélange ?",sc:[{who:"Léa",txt:"J'espère et j'ai peur en même temps, c'est épuisant."}],o:["« Pas d'espoir sans crainte : les deux naissent du même doute. »","« C'est rare : normalement, on éprouve l'un ou l'autre, jamais les deux. »","« L'espoir est toujours bon, seule la crainte est à combattre ce soir. »","« C'est de la haine envers Victor que tu confonds avec de la peur. »"],a:0,w:"Définitions 12 et 13. L'espoir et la crainte sont deux faces du même doute. Quand le doute tombe, ils deviennent sécurité ou désespoir."},
{i:"s206_09",u:206,t:"tiles",d:.35,q:"Reconstitue le moyen mnémotechnique sur la joie.",a:["l'ascenseur","qui","monte","pas","l'étage"],dd:["descend","toit","reste"],w:"La joie est un passage vers plus de puissance."},
{i:"s206_10",u:206,t:"fill",d:.35,q:"Un affect dont nous ne sommes pas la cause adéquate est une ___.",o:["passion","action","vertu","pensée"],a:0,w:"Définition 2 de la partie III : action si nous sommes cause adéquate, passion sinon."},
{i:"s206_11",u:206,t:"match",d:.35,q:"Associe chaque affect à son exemple chez Cargo & Co.",p:[["Émulation","Samir veut lever parce que ses amis lèvent"],["Ambition","Léa veut la une des magazines à tout prix"],["Crainte","Anaïs doute du renouvellement d'un client"],["Amour","L'équipe aime le stagiaire qui les fait rire"]],w:"Émulation : désir imité. Ambition : désir immodéré de gloire. Crainte : tristesse inconstante. Amour : joie + cause extérieure."},
{i:"s206_12",u:206,t:"tf",d:.4,q:"Selon E3P59, il n'existe pas d'affect actif de tristesse.",a:true,w:"Seuls la joie et le désir peuvent être des actions. Toute tristesse est une passion, une diminution de puissance subie."},
{i:"s206_13",u:206,t:"mcq",d:.4,q:"Comment Spinoza définit-il l'ambition ?",o:["Un désir immodéré de gloire","Une vertu des chefs d'entreprise","Le désir de mieux connaître","Une forme de courage"],a:0,w:"Définition 44. Déstabilisant pour Théo Lion : dans le monde entrepreneurial, l'ambition passe pour une vertu cardinale."},
{i:"s206_14",u:206,t:"story",d:.45,q:"Samir dit qu'il faut « éliminer toutes les passions » pour être sage. Que répond Julien ?",sc:[{who:"Samir",txt:"Une passion, c'est forcément mauvais, non ?"}],o:["« Les passions joyeuses augmentent la puissance ; la tristesse mine. »","« Oui, Spinoza demande de supprimer toute passion, joyeuse ou triste. »","« Non, il faut au contraire multiplier les passions tristes pour s'endurcir. »","« Les passions n'existent pas vraiment, ce sont des mots inventés. »"],a:0,w:"Spinoza ne condamne pas les passions joyeuses. Elles sont fragiles, car liées au dehors, mais elles sont un point de départ."},
{i:"s206_15",u:206,t:"fill",d:.45,q:"Deux affects contraires pour la même chose produisent une ___ de l'âme.",o:["fluctuation","élévation","purification","conversion"],a:0,w:"Fluctuatio animi, E3P17, scolie. Théo Lion : un succès nourrit déjà la crainte de le perdre."},
{i:"s206_16",u:206,t:"order",d:.45,q:"Remets dans l'ordre la fluctuation de l'âme autour d'un succès.",it:["Un succès extérieur arrive","Joie liée à cette cause extérieure","Idée qu'elle peut disparaître","Crainte de perdre le succès","L'âme oscille entre les deux"],w:"Toute passion joyeuse peut se renverser si sa cause change."},
{i:"s206_17",u:206,t:"sort",d:.5,q:"Classe chaque affect : famille de la joie ou famille de la tristesse ?",bins:["Joie","Tristesse"],it:[["Amour",0],["Haine",1],["Espoir",0],["Crainte",1],["Gloire",0],["Honte",1]],w:"Chaque affect dérivé garde la couleur de son affect primaire."},
{i:"s206_18",u:206,t:"slider",d:.5,q:"Combien de définitions des affects Spinoza donne-t-il à la fin de la partie III ?",min:3,max:100,step:1,a:48,tol:0,pre:"",un:"",w:"48 définitions, suivies d'une définition générale. Toutes dérivent des trois affects primaires."},
{i:"s206_19",u:206,t:"story",d:.5,q:"Hugo, le stagiaire, est fou de joie d'avoir monté sa roue seul. Qu'est-ce qui, selon Spinoza, le rend joyeux ?",sc:[{who:"Hugo",txt:"Je ne sais pas pourquoi, mais je suis trop content !"}],o:["« Tu viens de gagner une capacité : ta puissance d'agir a augmenté. »","« C'est la fierté d'avoir impressionné Léa, rien d'autre ne compte. »","« C'est un hasard chimique sans lien avec ce que tu viens de faire. »","« C'est parce que la roue est un objet précieux et coûteux. »"],a:0,w:"La joie accompagne une transformation de nos capacités, comme le permis de conduire de l'exemple de Théo Lion."},
{i:"s206_20",u:206,t:"mcq",d:.55,q:"Que devient l'espoir quand le doute disparaît et que l'issue est heureuse ?",o:["La sécurité","Le désespoir","La honte","L'envie"],a:0,w:"Définition 14 : la sécurité. Si l'issue redoutée devient certaine, la crainte devient désespoir (définition 15)."},
{i:"s206_21",u:206,t:"multi",d:.55,q:"Parmi ces exemples de Théo Lion, lesquels illustrent la joie comme passage à une plus grande puissance ?",o:["Réussir son permis de conduire","Comprendre un exercice de maths","Les progrès des premiers mois de musculation","Les premiers mois d'une entreprise pleins d'apprentissage","Perdre un client important"],a:[0,1,2,3],w:"Perdre un client, c'est l'inverse : un passage à une moindre perfection, donc de la tristesse."},
{i:"s206_22",u:206,t:"story",d:.6,q:"Léa se réjouit en secret que VéloFret ait un problème de livraison. Julien nomme l'affect. Lequel ?",sc:[{who:"Léa",txt:"C'est moche, mais ça m'a fait plaisir."}],o:["« C'est de l'envie : se réjouir du malheur de qui nous attriste. »","« C'est de l'amour, puisque tu penses beaucoup à ton concurrent. »","« C'est de la gloire, parce que tu as mieux réussi que lui ce jour-là. »","« C'est de l'espoir, car tu espères qu'il disparaisse bientôt du marché. »"],a:0,w:"Définition 23. Spinoza ne la blâme pas : il la décrit, pour qu'on puisse en comprendre la cause et s'en libérer."},
{i:"s206_23",u:206,t:"tf",d:.6,q:"Pour Spinoza, « perfection » veut dire être sans aucun défaut moral.",a:false,w:"Perfection = réalité = puissance d'agir. Ce n'est pas un idéal moral. « Par réalité et perfection, j'entends la même chose. »"},
{i:"s206_24",u:206,t:"fill",d:.65,q:"Le désir d'une chose, né de ce que d'autres semblables à nous la désirent, s'appelle l'___.",o:["émulation","ambition","humilité","admiration"],a:0,w:"Définition 33. C'est souvent ainsi que naît le désir d'entreprendre (module 9)."},
{i:"s206_25",u:206,t:"match",d:.65,q:"Associe chaque état à son origine.",p:[["Sécurité","Espoir dont le doute a disparu"],["Désespoir","Crainte dont le doute a disparu"],["Fluctuation","Deux affects contraires à la fois"],["Passion","Affect dont on n'est pas cause adéquate"]],w:"Espoir et crainte vivent du doute ; la fluctuation vit de la contradiction."},
{i:"s206_26",u:206,t:"story",d:.7,q:"Rappel du module 5 : quand le mail de Victor arrive, où se passe la tristesse de Léa ?",sc:[{who:"Léa",txt:"C'est dans ma tête ou dans mon ventre ?"}],o:["« Les deux : un affect est une variation du corps et de son idée. »","« Dans ta tête seulement, le ventre n'a rien à voir avec les affects. »","« Dans ton ventre seulement, la tête ne fait que constater ensuite. »","« Nulle part, c'est une illusion qui disparaîtra quand tu dormiras. »"],a:0,w:"Définition 3 de la partie III : les affections du corps et en même temps les idées de ces affections. Ce que peut un corps et ce que peut un esprit vont ensemble."},
{i:"s206_27",u:206,t:"sort",d:.7,q:"Classe chaque affect : passion joyeuse ou passion triste ?",bins:["Passion joyeuse","Passion triste"],it:[["Fierté après un article flatteur",0],["Jalousie envers un concurrent",1],["Joie d'une levée de fonds",0],["Honte d'une présentation ratée",1],["Crainte de perdre un client",1]],w:"Les passions joyeuses sont fragiles mais utiles ; les passions tristes minent la puissance. Spinoza cible surtout ces dernières."},
{i:"s206_28",u:206,t:"tiles",d:.75,q:"Reconstitue la définition de l'amour.",a:["une","joie","accompagnée","de","l'idée","d'une","cause","extérieure"],dd:["tristesse","intérieure","désir"],w:"Définition 6. Et la haine : une tristesse accompagnée de l'idée d'une cause extérieure."},
{i:"s206_29",u:206,t:"mcq",d:.75,q:"Pourquoi une joie liée à un succès extérieur est-elle fragile ?",o:["Elle dépend d'une cause qui peut changer","Elle est interdite par la morale","Elle abîme le corps à la longue","Elle vient toujours d'un mensonge"],a:0,w:"Si la cause extérieure se retire, la joie se défait. C'est le mécanisme de la fluctuation de l'âme."},
{i:"s206_30",u:206,t:"story",d:.8,q:"Anaïs demande : « Si toute tristesse est une passion, la joie peut-elle être une action ? »",sc:[{who:"Anaïs",txt:"Il y a des joies qu'on fabrique soi-même ?"}],o:["« Oui : celle qui naît de ce que tu comprends et fais par toi-même. »","« Non, toute joie vient forcément du dehors, sans exception possible. »","« Oui, mais seulement celle qui vient d'un succès financier très important. »","« Non, pour Spinoza la joie est toujours une faiblesse de l'esprit humain. »"],a:0,w:"E3P58-59 : il existe des joies et des désirs actifs, nés de la raison et de la compréhension. C'est vers eux que mène l'Éthique."},
{i:"s206_31",u:206,t:"fill",d:.8,q:"Spinoza écrit : « Par réalité et par ___, j'entends la même chose. »",o:["perfection","bonté","beauté","éternité"],a:0,w:"Partie II, définition 6. Plus un être a de réalité, plus il a de puissance : c'est sa perfection."},
{i:"s206_32",u:206,t:"story",d:.85,q:"Synthèse : Léa affiche au mur de son bureau un résumé du module. Lequel ?",sc:[{who:"Léa",txt:"Une phrase pour tout garder en tête."}],o:["« Désir, joie, tristesse : le reste en dérive ; la joie est un passage. »","« Toutes les émotions sont mauvaises, il faut apprendre à ne plus rien ressentir. »","« Seule la joie d'un succès financier compte, les autres ne sont que du bruit. »","« Les émotions viennent de Dieu, qui nous les envoie pour nous éprouver. »"],a:0,w:"D.J.T. plus une idée ; l'ascenseur qui monte, pas l'étage."}
