/*UNIT*/
{id:207,c:"SPINO",n:"Module 9",t:"Les faux biens : argent, gloire et amour de courtisane",col:"--purple",ic:"💸",guide:`
<h3>La Ferrari de Victor</h3>
<div class="gstory">Vendredi, 19 h, parking de l'incubateur Darwin, sur la rive droite. Victor arrive en Ferrari rouge pour la soirée des start-up. Samir la dévore des yeux : « Dans cinq ans, j'ai la même. » Sur scène, un fondateur raconte sa revente à 40 millions ; la salle applaudit debout. Samir s'inscrit le soir même à un programme « Devenir millionnaire en 12 mois ». Julien, qui l'a accompagné, lui pose une seule question : « Si tu avais la Ferrari, mais que personne ne pouvait la voir, tu la voudrais encore ? » Samir ne répond pas.</div>
<h3>Les trois raisons de désirer ce qui rend triste</h3>
<table><tr><th>Raison</th><th>Mécanisme</th><th>Texte</th></tr>
<tr><td><b>1. L'inversion</b></td><td>On juge bon ce qu'on désire, au lieu de désirer ce qui est bon</td><td>E3P9, scolie (module 7)</td></tr>
<tr><td><b>2. L'imagination</b></td><td>L'image montre l'état de notre corps plus que la nature des choses : elle associe la Ferrari à une joie qu'elle ne donnera pas</td><td>E2P16, E2P35 (le soleil à 200 pieds)</td></tr>
<tr><td><b>3. L'imitation</b></td><td>Si nous imaginons qu'un semblable éprouve un affect, nous l'éprouvons aussi ; nous désirons ce que nous voyons désiré</td><td>E3P27 ; l'émulation</td></tr></table>
<div class="gmnemo"><b>« Les 3 I du faux bien : Inversion, Imagination, Imitation. »</b> Et le test de Julien : <b>« Le voudrais-tu si personne ne le voyait ? »</b></div>
<p>Trois siècles plus tard, le penseur René Girard appellera ce troisième mécanisme le <b>désir mimétique</b> (1961). Théo Lion en tire une conséquence dérangeante : l'entrepreneuriat devenu à la mode est souvent poursuivi « comme une manière de ressembler à quelqu'un de riche », plus que comme une façon de s'accomplir.</p>
<h3>L'argent, moyen devenu fin</h3>
<p>Dans l'appendice de la partie IV (chapitre 28), Spinoza note que l'argent est devenu « l'abrégé de toutes choses » : son image occupe l'esprit du <b>vulgaire</b>, qui ne peut imaginer aucune joie sans l'idée de l'argent comme cause. <b>Vulgaire</b> vient du latin <i>vulgus</i>, la foule : ce n'est pas une classe sociale, mais une <b>disposition</b>, celle de rester prisonnier de l'imagination et de confondre les <b>moyens</b> et les <b>fins</b>. Spinoza ne condamne pas l'argent : ceux qui en connaissent le vrai usage et règlent leur richesse sur leurs besoins vivent contents (chapitre 29). L'entrepreneur qui mesure sa valeur à son chiffre d'affaires, lui, n'utilise plus l'argent pour étendre sa liberté : il en devient l'esclave.</p>
<h3>L'ambition et la gloire</h3>
<p>L'<b>ambition</b> est un désir immodéré de <b>gloire</b> ; la gloire, une joie liée à l'idée d'une action louée par les autres. C'est une passion entièrement suspendue au jugement d'autrui : l'ambitieux ne cherche pas à connaître sa puissance par lui-même, il attend qu'elle soit confirmée dans le regard des autres. Et la gloire fondée sur l'opinion de la foule est <b>vaine</b> : il faut sans cesse l'entretenir, avec l'angoisse de la perdre (E4P58, scolie).</p>
<h3>L'amour de courtisane (amor meretricius)</h3>
<p>Appendice de la partie IV, chapitre 19 : l'amour de courtisane, né de la beauté extérieure, et en général tout amour qui a une autre cause que la liberté de l'âme, se change facilement en <b>haine</b>. On n'aime pas l'autre pour ce qu'il est, mais pour l'image séduisante qu'il projette ; quand l'image se ternit, l'amour meurt. Théo Lion s'accuse lui-même : c'est ainsi que beaucoup d'entrepreneurs aiment leur boîte.</p>
<table><tr><th>Type d'entrepreneur (d'après Théo Lion)</th><th>Ce qu'il aime</th><th>Risque</th></tr>
<tr><td>Celui qui aime un <b>problème</b></td><td>Une innovation, un marché, une cause</td><td>Faible : son désir vient de lui</td></tr>
<tr><td>Celui qui aime l'entrepreneuriat et ne se voit pas faire autre chose</td><td>Créer, construire</td><td>Moyen</td></tr>
<tr><td>Celui qui trouve que c'est « stylé »</td><td>Le statut de fondateur, l'argent, l'image</td><td>Élevé : amour de courtisane, comme l'enfant qui veut être footballeur sans rien connaître du métier</td></tr></table>
<div class="gtrap">Précision : Spinoza ne dit nulle part que l'argent, la gloire ou l'ambition sont mauvais <b>en soi</b>. Rien n'est bon ou mauvais en soi (module 1). Le problème est leur <b>rapport</b> à nous : un moyen devenu fin, une joie suspendue à l'opinion. C'est exactement la conclusion de la vidéo : l'entrepreneur « vulgaire » est celui qui a remplacé un moyen par une fin.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Donner les trois raisons pour lesquelles on désire ce qui rend triste</li><li>Expliquer « vulgaire » et le rapport moyen et fin dans l'argent</li><li>Définir l'ambition, la gloire vaine et l'amour de courtisane</li><li>Classer une motivation d'entrepreneur dans la typologie de Théo Lion</li></ul>`},
/*EXOS*/
{i:"s207_01",u:207,t:"story",d:.2,nw:"Les faux biens",q:"Samir veut la même Ferrari que Victor. Quelle question lui pose Julien ?",sc:[{who:"Samir",txt:"Dans cinq ans, j'ai la même, c'est sûr."}],o:["« La voudrais-tu encore si personne ne pouvait la voir ? »","« Combien de chevaux a-t-elle exactement sous le capot ? »","« As-tu déjà calculé le prix de l'assurance d'une Ferrari ? »","« Pourquoi pas une Lamborghini, qui est plus rapide encore ? »"],a:0,w:"Le test du regard : si le désir disparaît quand personne ne voit, il était suspendu à l'imagination et à l'imitation."},
{i:"s207_02",u:207,t:"multi",d:.2,q:"Quelles sont les trois raisons pour lesquelles nous désirons des choses qui nous rendent tristes ?",o:["L'inversion : on juge bon ce qu'on désire","L'imagination qui se trompe sur la valeur","L'imitation du désir des autres","Un décret de Dieu","Un manque de volonté"],a:[0,1,2],w:"Les 3 I du faux bien : Inversion, Imagination, Imitation."},
{i:"s207_03",u:207,t:"fill",d:.25,q:"Le mot « vulgaire » vient du latin vulgus, qui signifie la ___.",o:["foule","saleté","pauvreté","bêtise"],a:0,w:"Vulgus, la multitude. Chez Spinoza, le vulgaire est une disposition : rester prisonnier de l'imagination, pas une classe sociale."},
{i:"s207_04",u:207,t:"match",d:.25,q:"Associe chaque notion à sa définition.",p:[["Ambition","Désir immodéré de gloire"],["Gloire","Joie liée à une action louée par autrui"],["Émulation","Désir né du désir des autres"],["Amour de courtisane","Amour d'une image extérieure"]],w:"Toutes ces passions dépendent du regard ou du désir d'autrui."},
{i:"s207_05",u:207,t:"tf",d:.25,q:"Pour Spinoza, l'argent est mauvais en soi.",a:false,w:"Il n'est ni bon ni mauvais en soi. Ceux qui en connaissent le vrai usage vivent contents ; le problème, c'est l'argent devenu fin."},
{i:"s207_06",u:207,t:"mcq",d:.3,q:"Comment Spinoza décrit-il l'argent dans l'appendice de la partie IV ?",o:["L'abrégé de toutes choses","La racine de tous les maux","Un don de Dieu aux justes","Une invention du diable"],a:0,w:"L'argent est devenu l'abrégé de toutes choses : son image occupe l'esprit du vulgaire, qui ne conçoit aucune joie sans lui."},
{i:"s207_07",u:207,t:"story",d:.3,q:"Samir s'inscrit à « Devenir millionnaire en 12 mois » après une soirée de pitchs. Quel mécanisme Julien lui montre-t-il ?",sc:[{who:"Samir",txt:"Tout le monde applaudissait, j'ai eu envie de ça."}],o:["« L'imitation des affects : tu désires ce que tu vois désiré et applaudi. »","« La raison pure : tu as calculé froidement que c'était le meilleur choix. »","« Le hasard : tu aurais pu t'inscrire à n'importe quel autre programme. »","« La vertu : c'est la preuve que tu es fait pour être entrepreneur. »"],a:0,w:"E3P27 : nous éprouvons les affects que nous imaginons chez nos semblables. La salle debout a déclenché l'émulation. René Girard parlera plus tard de désir mimétique."},
{i:"s207_08",u:207,t:"sort",d:.3,q:"Classe chaque motivation selon la typologie de Théo Lion.",bins:["Aime un problème","Trouve ça stylé"],it:[["Réduire la pollution des livraisons en ville",0],["Être appelé fondateur en soirée",1],["Résoudre la solitude des personnes âgées",0],["Poster sa levée de fonds sur LinkedIn",1],["Améliorer les vélos des livreurs",0]],w:"Aimer un problème, c'est désirer la chose même ; trouver ça stylé, c'est aimer l'image : l'amour de courtisane."},
{i:"s207_09",u:207,t:"tiles",d:.35,q:"Reconstitue les trois I du faux bien.",a:["Inversion","Imagination","Imitation"],dd:["Intuition","Intelligence"],w:"Les 3 I du faux bien. L'intuition, elle, fait partie de la solution (module 12)."},
{i:"s207_10",u:207,t:"fill",d:.35,q:"L'amour de courtisane se dit en latin amor ___.",o:["meretricius","intellectualis","fati","patriae"],a:0,w:"Amor meretricius (appendice de la partie IV, chapitre 19). L'amor intellectualis Dei, lui, est le sommet de l'Éthique."},
{i:"s207_11",u:207,t:"story",d:.35,q:"Léa se demande si elle aime Cargo & Co « comme une courtisane ». Quelle question l'aide à trancher ?",sc:[{who:"Léa",txt:"Comment savoir si j'aime ma boîte ou son image ?"}],o:["« L'aimerais-tu encore si elle était petite, discrète et inconnue ? »","« Combien de followers la page LinkedIn a-t-elle gagnés ce mois-ci ? »","« Ta boîte est-elle plus connue que celle de ton concurrent parisien ? »","« Les investisseurs trouvent-ils ta boîte assez prestigieuse ? »"],a:0,w:"L'amour de courtisane aime l'éclat extérieur ; il meurt quand l'image se ternit. L'amour du problème survit à l'anonymat."},
{i:"s207_12",u:207,t:"tf",d:.4,q:"Selon Spinoza, un amour fondé sur la beauté extérieure se change facilement en haine.",a:true,w:"Appendice de la partie IV, chapitre 19. Tout amour qui a une autre cause que la liberté de l'âme est fragile."},
{i:"s207_13",u:207,t:"mcq",d:.4,q:"Quel penseur du XXe siècle a appelé « désir mimétique » ce que Spinoza décrit par l'imitation des affects ?",o:["René Girard","Jean-Paul Sartre","Sigmund Freud","Karl Marx"],a:0,w:"Girard, Mensonge romantique et vérité romanesque (1961) : nous désirons selon le désir d'un autre. Spinoza l'avait décrit en E3P27."},
{i:"s207_14",u:207,t:"order",d:.45,q:"Remets dans l'ordre la naissance d'un faux désir d'entreprendre.",it:["On voit d'autres entrepreneurs applaudis","On imagine leur joie","On éprouve un désir semblable","On juge l'entrepreneuriat bon parce qu'on le désire","On poursuit une image plutôt qu'un problème"],w:"Imitation, imagination, inversion : les trois I en action."},
{i:"s207_15",u:207,t:"story",d:.45,q:"Victor dit : « L'ambition est la première vertu d'un fondateur ». Que répond Julien avec Spinoza ?",sc:[{who:"Victor",txt:"Sans ambition, on ne fait rien de grand."}],o:["« Pour Spinoza, l'ambition est une passion suspendue au regard des autres. »","« Spinoza dit exactement pareil : l'ambition est la vertu suprême de l'homme. »","« Spinoza interdit toute action grande, il faut rester petit et modeste. »","« L'ambition n'existe pas chez Spinoza, il n'en parle jamais du tout. »"],a:0,w:"C'est ce qui a déstabilisé Théo Lion. Désirer faire de grandes choses n'est pas le problème ; en dépendre du regard d'autrui, si."},
{i:"s207_16",u:207,t:"match",d:.45,q:"Associe chaque texte à son idée.",p:[["E3P27","Imitation des affects"],["E4 appendice ch. 19","Amour de courtisane"],["E4 appendice ch. 28","L'argent, abrégé de toutes choses"],["E4P58 scolie","Vanité de la gloire populaire"]],w:"Les textes de référence sur les faux biens."},
{i:"s207_17",u:207,t:"fill",d:.5,q:"Le vulgaire, selon Théo Lion, est celui qui confond les moyens et les ___.",o:["fins","débuts","risques","coûts"],a:0,w:"L'argent est un moyen légitime ; devenu fin absolue, il crée la servitude."},
{i:"s207_18",u:207,t:"sort",d:.5,q:"Classe chaque rapport à l'argent : moyen ou fin ?",bins:["Moyen","Fin"],it:[["Payer bien son équipe",0],["Mesurer sa valeur à son chiffre d'affaires",1],["Financer un nouveau prototype",0],["Accumuler pour dépasser son voisin",1],["Se libérer du temps pour sa famille",0]],w:"L'argent qui étend la liberté reste un moyen ; celui qui devient la mesure de soi est une fin, donc une servitude."},
{i:"s207_19",u:207,t:"multi",d:.5,q:"Pourquoi la gloire fondée sur l'opinion de la foule est-elle vaine selon Spinoza ?",o:["Il faut sans cesse l'entretenir","On craint toujours de la perdre","Elle dépend du jugement d'autrui","L'opinion de la foule change","Elle est interdite par la loi"],a:[0,1,2,3],w:"E4P58, scolie. La gloire vaine est une joie sous condition, donc une passion instable."},
{i:"s207_20",u:207,t:"story",d:.55,q:"Rappel du module 8 : Samir se réjouit quand un « gourou » concurrent perd des abonnés. Quel affect Julien nomme-t-il ?",sc:[{who:"Samir",txt:"Bien fait pour lui, il se la racontait."}],o:["« De l'envie : une haine qui réjouit du malheur de l'autre. »","« De la justice : il a mérité de perdre ces abonnés, c'est normal. »","« De l'amour : tu t'intéresses beaucoup à ce qu'il devient. »","« De la gloire : tu as gagné contre lui sans rien faire du tout. »"],a:0,w:"Définition 23. L'envie naît souvent de l'émulation : on souffre du succès de ceux à qui l'on se compare. L'envie illustre ce que Girard nommera la rivalité mimétique."},
{i:"s207_21",u:207,t:"mcq",d:.55,q:"Quelle image Théo Lion utilise-t-il pour l'entrepreneur qui trouve ça « stylé » ?",o:["L'enfant qui veut être footballeur","Le marin perdu en haute mer","Le moine seul dans son couvent","Le joueur de poker qui bluffe"],a:0,w:"L'enfant ne connaît rien au métier : il aime le statut et le respect qu'il voit. C'est un amour de l'image."},
{i:"s207_22",u:207,t:"tf",d:.6,q:"Pour Théo Lion, celui qui entreprend parce qu'il aime un problème court un faible risque d'amour de courtisane.",a:true,w:"Son désir porte sur la chose même, pas sur l'image. C'est la motivation la plus solide de sa typologie."},
{i:"s207_23",u:207,t:"story",d:.6,q:"Anaïs dit : « Moi, je veux juste gagner assez pour être tranquille ». Qu'en pense Spinoza ?",sc:[{who:"Anaïs",txt:"Je ne cherche pas la Ferrari, juste la sécurité."}],o:["« Régler sa richesse sur ses besoins, c'est le vrai usage de l'argent. »","« C'est de la paresse, un vrai entrepreneur veut toujours plus d'argent. »","« C'est impossible, l'argent est toujours une fin absolue pour tout le monde. »","« Il faut refuser tout argent pour être vraiment sage et libre. »"],a:0,w:"Appendice de la partie IV, chapitre 29 : ceux qui connaissent le vrai usage de l'argent vivent contents de peu."},
{i:"s207_24",u:207,t:"fill",d:.65,q:"Selon E3P27, nous éprouvons les affects que nous imaginons chez nos ___.",o:["semblables","ennemis","parents","dieux"],a:0,w:"L'imitation des affects vaut surtout pour ceux qui nous ressemblent : collègues, amis, entrepreneurs du même âge. C'est ce que René Girard appellera le désir mimétique."},
{i:"s207_25",u:207,t:"tiles",d:.65,q:"Reconstitue le test du regard.",a:["le","voudrais-tu","si","personne","ne","le","voyait"],dd:["payait","jamais","achetait"],w:"Un désir qui s'évanouit sans spectateur était suspendu à l'imitation et à la gloire."},
{i:"s207_26",u:207,t:"sort",d:.7,q:"Classe chaque phrase : fidèle à Spinoza ou caricature ?",bins:["Fidèle","Caricature"],it:[["L'argent n'est ni bon ni mauvais en soi",0],["Il faut vivre pauvre pour être sage",1],["La gloire fondée sur l'opinion est vaine",0],["Toute ambition est un péché",1],["On désire souvent ce que les autres désirent",0]],w:"Spinoza décrit des mécanismes ; il ne prêche ni la pauvreté ni la honte."},
{i:"s207_27",u:207,t:"story",d:.7,q:"Rappel du module 7 : Léa demande si tous ses désirs d'entreprendre sont faux.",sc:[{who:"Léa",txt:"Alors tout ce que je veux est une illusion ?"}],o:["« Non : trie ce qui vient de toi et ce qui vient du regard des autres. »","« Oui, tout désir d'entreprendre est une imitation, sans aucune exception. »","« Non, tous tes désirs sont vrais puisque tu les ressens vraiment en toi. »","« Oui, il faut tout arrêter et attendre qu'un vrai désir tombe du ciel. »"],a:0,w:"Le conatus est notre essence ; certains désirs expriment notre puissance, d'autres dépendent de causes extérieures. On trie, on ne supprime pas."},
{i:"s207_28",u:207,t:"mcq",d:.75,q:"Pourquoi Théo Lion juge-t-il « dérangeant » le rôle de l'émulation dans l'entrepreneuriat ?",o:["Elle forme le désir même d'entreprendre","Elle rend les entrepreneurs bien trop modestes","Elle empêche les jeunes de lever des fonds","Elle est interdite par le droit des sociétés"],a:0,w:"Voir d'autres fonder une entreprise suffit à déclencher le désir d'en fonder une : le désir d'entreprendre peut être un désir emprunté."},
{i:"s207_29",u:207,t:"match",d:.75,q:"Associe chaque personnage à son rapport aux faux biens.",p:[["Samir","Désir imité après une soirée de pitchs"],["Victor","Ambition présentée comme vertu"],["Anaïs","Richesse réglée sur ses besoins"],["Léa","Doute entre aimer sa boîte ou son image"]],w:"Chacun illustre un mécanisme. Le cours ne juge personne : il éclaire les causes."},
{i:"s207_30",u:207,t:"tf",d:.8,q:"Pour Spinoza, l'ambitieux connaît sa puissance par lui-même.",a:false,w:"Il attend que son existence soit confirmée dans le regard des autres. Sa joie suit l'admiration, sa tristesse le soupçon de la perdre."},
{i:"s207_31",u:207,t:"fill",d:.8,q:"Théo Lion : l'entrepreneur « vulgaire » est celui qui a remplacé un moyen par une ___.",o:["fin","cause","règle","dette"],a:0,w:"Moyen devenu fin : l'argent, le succès, la croissance oublient ce qu'ils devaient servir."},
{i:"s207_32",u:207,t:"story",d:.85,q:"Synthèse : Samir résume ce qu'il retient de la soirée à Darwin. Quelle phrase est la plus juste ?",sc:[{who:"Samir",txt:"Bon, je crois que j'ai compris quelque chose ce soir."}],o:["« Je désirais une image imitée ; je dois trouver un problème que j'aime. »","« Il faut que j'achète une Ferrari plus vite pour ne plus y penser du tout. »","« Tout désir est mauvais, je vais retourner en CDI et ne plus rien vouloir. »","« Les autres entrepreneurs sont tous des menteurs, il ne faut rien écouter. »"],a:0,w:"Inversion, imagination, imitation. Le remède n'est ni la honte ni le renoncement : c'est de réorienter le désir vers ce qui vient de soi."}
