/*UNIT*/
{id:208,c:"SPINO",n:"Module 10",t:"La servitude : voir le meilleur et faire le pire",col:"--purple",ic:"⛓️",guide:`
<h3>Le pacte d'actionnaires</h3>
<div class="gstory">Jeudi soir, Léa relit le pacte d'actionnaires signé avec le fonds de Victor : un conseil d'administration chaque mois, un reporting chaque semaine, un objectif de 50 villes en 2027, et une clause qui permet au fonds de remplacer la dirigeante si les objectifs ne sont pas atteints. Elle écrit à Julien : « J'ai levé 2 millions pour être plus libre. Et j'ai l'impression d'avoir signé mon contrat de travail le plus dur. » Le lendemain, elle se promet d'arrêter de consulter ses mails à minuit. À minuit, elle les consulte. Elle sait que c'est mauvais pour elle. Elle le fait quand même.</div>
<h3>La définition (préface de la partie IV)</h3>
<p>« J'appelle <b>servitude</b> l'impuissance humaine à gouverner et à contenir les affects. Car l'homme soumis aux affects ne relève pas de lui-même mais de la <b>fortune</b>, au pouvoir de laquelle il se trouve à tel point qu'il est souvent contraint, <b>voyant le meilleur, de faire le pire</b>. »</p>
<p>Spinoza cite le poète latin <b>Ovide</b> (les mots de Médée, dans les <i>Métamorphoses</i>) : <i>video meliora proboque, deteriora sequor</i>, « je vois le meilleur et je l'approuve, je fais le pire » (E4P17, scolie).</p>
<div class="gmnemo"><b>« Voir le meilleur, faire le pire : c'est la servitude. »</b> Et la réponse de Spinoza en une formule : <b>« Le vrai ne gagne que s'il devient un affect. »</b></div>
<h3>Pourquoi savoir ne suffit pas</h3>
<p>Théo Lion le dit avec humour : « S'il suffisait de savoir ce qui était bon pour nous pour le faire, aucun médecin ne fumerait et tout le monde mangerait cinq fruits et légumes par jour. » Spinoza l'explique :</p>
<ul><li><b>E4P14</b> : la vraie connaissance du bon et du mauvais ne peut contrarier aucun affect <b>en tant qu'elle est vraie</b>, mais seulement <b>en tant qu'elle est elle-même un affect</b>. Un savoir froid ne pèse rien face à une envie chaude.</li>
<li><b>E4P7</b> : un affect ne peut être contrarié ni supprimé que par un <b>affect contraire et plus fort</b> (on y reviendra au module 11).</li>
<li><b>E4P3</b> : notre force de persévérer est limitée et infiniment dépassée par la puissance des causes extérieures. <b>E4P4</b> : il est impossible que l'homme ne soit pas une partie de la nature et ne subisse rien.</li></ul>
<h3>Le présent écrase le futur</h3>
<table><tr><th>Proposition</th><th>Idée</th><th>Exemple</th></tr>
<tr><td>E4P9</td><td>Un affect dont on imagine la cause <b>présente</b> est plus fort que si elle était absente</td><td>Le mail à minuit, sous les yeux, contre le sommeil de demain</td></tr>
<tr><td>E4P10</td><td>Une chose future <b>proche</b> nous affecte plus qu'une chose lointaine</td><td>Le reporting de lundi pèse plus que la santé dans dix ans</td></tr>
<tr><td>E4P16</td><td>Le désir né de la connaissance du bien <b>futur</b> est facilement vaincu par le désir des plaisirs <b>présents</b></td><td>Samir remet à demain sa formation pour une soirée</td></tr></table>
<p>Spinoza décrit, trois siècles avant l'économie comportementale, ce qu'on appelle aujourd'hui la <b>préférence pour le présent</b>.</p>
<h3>Le vrai nœud : la dépendance</h3>
<p>Théo Lion en tire la conclusion : « Le vrai nœud du malheur n'est pas dans l'objet poursuivi, mais dans notre condition de <b>dépendance</b>. » Tant que notre joie repose sur des causes extérieures (un investisseur, un client, un article), nous restons exposés à leur perte. La <b>levée de fonds</b> en est l'exemple : plus de moyens, certes, mais l'entrepreneur devient tributaire du calendrier et des objectifs de ses investisseurs. Derrière l'apparente extension de sa liberté se cache une nouvelle forme de servitude, qui produira de la tristesse le jour où les intérêts divergeront.</p>
<div class="gtrap">Attention au contresens : la servitude spinoziste n'est pas d'abord politique ou économique (être esclave d'un maître), même si elle peut s'y exprimer. C'est l'état de celui qui est mené par ses <b>affects passifs</b>, par des causes qu'il ne comprend pas. Un milliardaire peut y être plongé ; un polisseur de lentilles peut en être sorti. Et Spinoza ne propose pas de fuir toute dépendance (impossible, E4P4), mais de devenir <b>davantage</b> cause de ce qui nous arrive.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Citer la définition de la servitude et la formule d'Ovide</li><li>Expliquer pourquoi savoir ne suffit pas (E4P14, E4P7)</li><li>Expliquer la force du présent sur le futur (E4P9, P10, P16)</li><li>Analyser une levée de fonds comme forme de dépendance</li></ul>`},
/*EXOS*/
{i:"s208_01",u:208,t:"fill",d:.2,nw:"La servitude",q:"Spinoza appelle servitude l'impuissance humaine à gouverner et contenir les ___.",o:["affects","dépenses","salariés","pensées"],a:0,w:"Préface de la partie IV. L'homme soumis aux affects relève de la fortune, pas de lui-même."},
{i:"s208_02",u:208,t:"story",d:.2,q:"Léa a levé 2 millions « pour être plus libre » et se sent enchaînée. Que lui dit Julien ?",sc:[{who:"Léa",txt:"J'ai plus de moyens, mais moins de liberté. C'est normal ?"}],o:["« Tu as gagné des moyens et une dépendance : c'est une forme de servitude. »","« Impossible, plus d'argent donne toujours plus de liberté, sans exception. »","« C'est une impression, ton pacte d'actionnaires ne change rien à ta vie. »","« Rembourse tout demain matin et tu retrouveras une liberté totale. »"],a:0,w:"C'est l'analyse de Théo Lion : derrière l'extension apparente de la liberté, la dépendance au calendrier et aux objectifs des investisseurs."},
{i:"s208_03",u:208,t:"tiles",d:.25,q:"Reconstitue la traduction de la formule d'Ovide citée par Spinoza.",a:["je","vois","le","meilleur","et","je","l'approuve","je","fais","le","pire"],dd:["refuse","évite","toujours"],w:"Video meliora proboque, deteriora sequor. Les mots de Médée dans les Métamorphoses."},
{i:"s208_04",u:208,t:"tf",d:.25,q:"Pour Spinoza, il suffit de savoir ce qui est bon pour le faire.",a:false,w:"La connaissance vraie ne l'emporte que si elle devient un affect plus fort (E4P14). D'où le médecin qui fume."},
{i:"s208_05",u:208,t:"mcq",d:.25,q:"Quel exemple Théo Lion donne-t-il pour montrer que savoir ne suffit pas ?",o:["Le médecin qui fume","Le banquier qui épargne","Le professeur qui lit","Le sportif qui court"],a:0,w:"« Aucun médecin ne fumerait et tout le monde mangerait cinq fruits et légumes par jour. »"},
{i:"s208_06",u:208,t:"match",d:.3,q:"Associe chaque proposition à son idée.",p:[["E4P3","Les causes extérieures nous dépassent infiniment"],["E4P7","Seul un affect plus fort l'emporte"],["E4P14","Le vrai ne pèse que comme affect"],["E4P16","Le plaisir présent bat le bien futur"]],w:"Quatre propositions qui expliquent pourquoi la raison seule perd souvent."},
{i:"s208_07",u:208,t:"story",d:.3,q:"Léa se promet d'arrêter les mails à minuit, puis recommence. Elle se traite de faible. Que lui dit Julien ?",sc:[{who:"Léa",txt:"Je sais que c'est mauvais pour moi. Je suis nulle."}],o:["« Savoir froidement ne pèse rien : il faut un affect plus fort, pas la honte. »","« Oui, c'est un manque de volonté, il faut te punir à chaque nouvelle rechute. »","« C'est normal, les mails à minuit sont très bons pour la productivité. »","« Supprime ta messagerie professionnelle, c'est la seule solution durable. »"],a:0,w:"E4P14 et E4P7. La honte est une tristesse de plus. La solution passe par un affect joyeux plus fort (module 13)."},
{i:"s208_08",u:208,t:"sort",d:.3,q:"Classe chaque situation : servitude au sens de Spinoza ou non ?",bins:["Servitude","Pas servitude"],it:[["Consulter ses mails malgré soi",0],["Choisir de lire un livre qu'on aime",1],["Acheter une voiture pour être envié",0],["Comprendre sa colère et s'apaiser",1],["Poursuivre un objectif fixé par peur du regard",0]],w:"La servitude, c'est être mené par des affects passifs dont on ignore les causes."},
{i:"s208_09",u:208,t:"fill",d:.35,q:"L'homme soumis aux affects ne relève pas de lui-même mais de la ___.",o:["fortune","famille","justice","raison"],a:0,w:"Fortuna : le hasard des rencontres extérieures. C'est pour cela que Spinoza cherche une joie qui ne dépende pas de la chance."},
{i:"s208_10",u:208,t:"mcq",d:.35,q:"Quel poète Spinoza cite-t-il pour illustrer la servitude ?",o:["Ovide","Virgile","Homère","Dante"],a:0,w:"Ovide, Métamorphoses, livre VII : Médée voit le meilleur et fait le pire. Cité en E4P17, scolie."},
{i:"s208_11",u:208,t:"story",d:.35,q:"Samir repousse chaque soir sa formation en ligne pour sortir avec ses amis. Quelle proposition l'explique ?",sc:[{who:"Samir",txt:"Je sais que la formation compte pour mon avenir, mais la soirée est là, maintenant."}],o:["« E4P16 : le bien futur perd contre le plaisir présent. »","« E1P15 : tout ce qui est, est en Dieu, donc aussi ta soirée. »","« E2P7 : l'ordre des idées est le même que celui des choses. »","« E3P6 : chaque chose persévère dans son être, même tes amis. »"],a:0,w:"Spinoza décrit la préférence pour le présent. La solution : rendre le bien futur présent et joyeux (module 13)."},
{i:"s208_12",u:208,t:"tf",d:.4,q:"Selon E4P4, il est impossible que l'homme ne soit pas une partie de la nature et ne subisse rien.",a:true,w:"On ne fuit pas toute dépendance. On devient davantage cause de ce qui nous arrive."},
{i:"s208_13",u:208,t:"multi",d:.4,q:"Quelles dépendances la levée de fonds a-t-elle créées pour Léa ?",o:["Le calendrier des investisseurs","Leurs objectifs de rentabilité","Le reporting chaque semaine","La menace d'être remplacée","Son amour du vélo"],a:[0,1,2,3],w:"Son amour du vélo est un désir propre, pas une dépendance. Les quatre autres sont des causes extérieures qui pèsent sur sa joie."},
{i:"s208_14",u:208,t:"order",d:.45,q:"Remets dans l'ordre le mécanisme de la servitude chez Léa, le soir.",it:["Le téléphone est là, présent","L'affect lié au mail présent est fort","Le savoir sur le sommeil reste froid","L'affect le plus fort l'emporte","Léa voit le meilleur et fait le pire"],w:"E4P9 et E4P14 : la cause présente et chaude bat le savoir abstrait."},
{i:"s208_15",u:208,t:"fill",d:.45,q:"Un affect dont nous imaginons la cause ___ est plus fort que si nous l'imaginions absente.",o:["présente","lointaine","divine","passée"],a:0,w:"E4P9. D'où l'efficacité d'éloigner la cause : le téléphone hors de la chambre."},
{i:"s208_16",u:208,t:"story",d:.45,q:"Victor dit à Léa : « Tu es libre, tu es la patronne ! » Que répond Julien en aparté ?",sc:[{who:"Victor",txt:"Tu n'as de comptes à rendre à personne."}],o:["« Être patronne n'empêche pas la servitude : elle vient des affects. »","« Il a raison, un chef d'entreprise est par définition l'être le plus libre. »","« Il a tort, seuls les salariés sont libres, jamais les patrons. »","« La liberté n'existe que pour ceux qui n'ont aucun investisseur. »"],a:0,w:"La servitude n'est pas d'abord un statut. Un dirigeant mené par la peur des chiffres est en servitude."},
{i:"s208_17",u:208,t:"sort",d:.5,q:"Classe chaque affect selon sa force probable, d'après E4P9 et E4P10.",bins:["Plus fort","Moins fort"],it:[["Le reporting de lundi",0],["La santé dans dix ans",1],["Le mail sous les yeux",0],["Le bilan de fin d'année prochaine",1]],w:"Le présent et le proche l'emportent sur l'absent et le lointain."},
{i:"s208_18",u:208,t:"mcq",d:.5,q:"Selon Théo Lion, où est le « vrai nœud du malheur » ?",o:["Dans notre dépendance au dehors","Dans l'objet que l'on poursuit","Dans le manque d'argent chronique","Dans la paresse naturelle des hommes"],a:0,w:"Ce n'est pas l'objet poursuivi qui rend malheureux, mais le fait que notre joie en dépende."},
{i:"s208_19",u:208,t:"story",d:.55,q:"Rappel du module 6 : Léa demande si la servitude prouve qu'elle n'a pas de volonté.",sc:[{who:"Léa",txt:"Si je fais le pire, c'est que ma volonté est faible ?"}],o:["« Pas de volonté séparée : c'est un affect plus fort qui l'emporte. »","« Oui, ta volonté est faible et il faut la muscler par des punitions. »","« Non, ta volonté est très forte, mais elle choisit exprès le pire. »","« La volonté n'a rien à voir, c'est ton horoscope qui décide le soir. »"],a:0,w:"Volonté et entendement sont une même chose (module 6). La question n'est pas la force de la volonté, mais la force des affects. E2P49 : la volonté et l'entendement sont une seule et même chose."},
{i:"s208_20",u:208,t:"tf",d:.55,q:"Pour Spinoza, un milliardaire peut vivre dans la servitude.",a:true,w:"La servitude est l'état de celui que ses affects passifs mènent. Elle ne dépend ni de la richesse ni du statut."},
{i:"s208_21",u:208,t:"match",d:.55,q:"Associe chaque personnage à sa forme de servitude.",p:[["Léa","Mails de minuit et objectifs du fonds"],["Samir","Plaisir présent contre formation future"],["Victor","Gloire suspendue aux classements"],["Le médecin qui fume","Savoir le bien sans le faire"]],w:"Chaque forme de servitude a la même structure : un affect passif plus fort que le savoir."},
{i:"s208_22",u:208,t:"fill",d:.6,q:"Les propositions E4P9 à E4P16 décrivent ce qu'on appelle aujourd'hui la préférence pour le ___.",o:["présent","risque","travail","collectif"],a:0,w:"Trois siècles avant l'économie comportementale, Spinoza explique pourquoi le proche l'emporte sur le lointain."},
{i:"s208_23",u:208,t:"story",d:.6,q:"Anaïs propose de mettre les téléphones au placard pendant les réunions de direction. Julien approuve. Pourquoi ?",sc:[{who:"Anaïs",txt:"C'est un petit truc, mais ça change tout."}],o:["« Éloigner la cause présente affaiblit l'affect : c'est E4P9 appliqué. »","« Parce que les téléphones émettent des ondes qui brouillent la raison. »","« Parce que Spinoza interdisait tout objet technique dans une réunion. »","« Parce que la volonté de chacun est trop faible et doit être punie. »"],a:0,w:"Plutôt que de lutter contre un affect fort, on agit sur sa cause. C'est une ruse d'organisation très spinoziste."},
{i:"s208_24",u:208,t:"multi",d:.65,q:"Quelles phrases résument la partie IV de l'Éthique ?",o:["Nos forces sont dépassées par les causes extérieures","Le vrai ne l'emporte que comme affect","Le présent pèse plus que le futur","On peut voir le meilleur et faire le pire","La volonté libre suffit pour tout maîtriser"],a:[0,1,2,3],w:"La dernière est la thèse cartésienne que Spinoza réfute."},
{i:"s208_25",u:208,t:"mcq",d:.65,q:"Que propose Spinoza face à une dépendance inévitable ?",o:["Devenir davantage cause de ce qui arrive","Fuir la société et vivre seul à la campagne","Tout refuser, y compris l'argent et le travail","Se résigner et ne plus rien espérer de la vie"],a:0,w:"On ne sort jamais de la nature (E4P4). On augmente sa part d'activité en comprenant les causes."},
{i:"s208_26",u:208,t:"tiles",d:.7,q:"Reconstitue la formule sur le vrai et les affects.",a:["le","vrai","ne","gagne","que","s'il","devient","un","affect"],dd:["jamais","volonté","froid"],w:"E4P14. Un savoir froid ne pèse rien face à une envie chaude."},
{i:"s208_27",u:208,t:"sort",d:.7,q:"Classe chaque remède : efficace selon Spinoza ou inefficace ?",bins:["Efficace","Inefficace"],it:[["Se faire honte après chaque rechute",1],["Rendre le bien futur présent et joyeux",0],["Éloigner la cause de la tentation",0],["Répéter « je dois » sans émotion",1]],w:"La honte et le devoir froid sont des tristesses ou des idées sans force. On agit par des affects joyeux et sur les causes."},
{i:"s208_28",u:208,t:"story",d:.75,q:"Rappel du module 9 : Samir demande si sa servitude vient de l'argent lui-même.",sc:[{who:"Samir",txt:"C'est l'argent le problème, non ?"}],o:["« Non : c'est ta dépendance à son image, un moyen devenu fin. »","« Oui, l'argent est mauvais en soi et il faut s'en débarrasser. »","« Non, le problème ce sont tes amis, il faut les quitter. »","« Oui, il faut n'accepter aucun salaire pour être enfin libre. »"],a:0,w:"Le vrai nœud est la dépendance, pas l'objet. L'argent comme moyen n'asservit pas."},
{i:"s208_29",u:208,t:"tf",d:.75,q:"La servitude spinoziste désigne d'abord l'esclavage politique d'un peuple.",a:false,w:"C'est d'abord l'impuissance face à ses propres affects passifs. Spinoza traite aussi de politique, mais ce n'est pas le sens premier ici."},
{i:"s208_30",u:208,t:"fill",d:.8,q:"Selon E4P7, un affect ne peut être supprimé que par un affect contraire et plus ___.",o:["fort","juste","ancien","rapide"],a:0,w:"C'est la clé de la méthode spinoziste : pas de suppression par décret, mais par un affect plus fort (module 11)."},
{i:"s208_31",u:208,t:"mcq",d:.8,q:"Que veut dire « relever de soi-même » par opposition à la servitude ?",o:["Être la cause de ses actions, pas les subir","Ne dépendre d'aucune personne au monde","Posséder seul son entreprise à 100 %","Vivre sans aucune émotion d'aucune sorte"],a:0,w:"Relever de soi (être sui juris), c'est agir par sa propre nature. C'est la liberté spinoziste."},
{i:"s208_32",u:208,t:"story",d:.85,q:"Synthèse : Léa résume la partie IV à Anaïs. Quelle phrase est la plus juste ?",sc:[{who:"Anaïs",txt:"Donc on est tous esclaves ?"}],o:["« Des affects plus forts que notre savoir nous mènent ; il faut des affects plus forts. »","« Oui, on est tous esclaves pour toujours, et il n'y a absolument rien à y faire. »","« Non, il suffit de vouloir très fort pour devenir entièrement libre en un jour. »","« Seuls les salariés sont esclaves ; les patrons, eux, sont libres par nature. »"],a:0,w:"Voir le meilleur, faire le pire : c'est la servitude. Le vrai ne gagne que s'il devient un affect. La partie V propose la sortie."}
