/*UNIT*/
{id:209,c:"SPINO",n:"Module 11",t:"Ni éteindre ni commander : remplacer un affect par un plus fort",col:"--purple",ic:"🔄",guide:`
<h3>Le rayon développement personnel</h3>
<div class="gstory">Samedi, librairie Mollat, rue Vital-Carles. Samir a les bras chargés : <i>Pensées pour moi-même</i> de Marc Aurèle, un livre sur le « détachement total », un autre intitulé <i>Contrôle tes émotions en 7 jours</i>. « Cette fois, je deviens stoïque. Plus aucune émotion. » Léa, qui l'accompagne, a essayé l'an dernier : une retraite de méditation, une semaine sans téléphone, des résolutions de fer. « Trois jours après, j'étais pire qu'avant. » Julien, en feuilletant Épictète : « Spinoza avait ce livre dans sa bibliothèque. Il le respectait. Et il explique pourquoi ça ne marche pas pour la plupart des gens. »</div>
<h3>Les remèdes antiques</h3>
<table><tr><th>École</th><th>Remède</th><th>Formule</th></tr>
<tr><td><b>Épicuriens</b></td><td>Trier les désirs : naturels et nécessaires (manger, s'abriter) contre désirs <b>vains</b> (gloire, pouvoir, richesse sans fin)</td><td>Lettre à Ménécée</td></tr>
<tr><td><b>Cyniques</b></td><td>Rejeter conventions sociales et biens superflus (Diogène et son tonneau)</td><td>Vivre selon la nature, sans honte</td></tr>
<tr><td><b>Stoïciens</b></td><td>Distinguer ce qui dépend de nous et ce qui n'en dépend pas ; n'accorder de valeur qu'au premier</td><td>Épictète : « Ce qui trouble les hommes, ce ne sont pas les choses, mais les jugements qu'ils portent sur les choses. »</td></tr></table>
<p>Ces remèdes paraissent cohérents : si les biens extérieurs nous rendent esclaves, renonçons-y ou rangeons-les hors de nos désirs. C'est, dit Théo Lion, le conseil le plus répandu sur internet pour les entrepreneurs. Il l'a essayé : « Théoriquement, ça fait beaucoup de sens. Dans la pratique, j'ai eu beaucoup de mal. »</p>
<h3>La double méprise</h3>
<ol><li><b>Croire qu'on peut éteindre le désir.</b> Impossible : le désir est notre essence (module 7). Vouloir le supprimer, c'est vouloir supprimer la vie. L'<b>ascétisme</b> est une impasse, comme décider de ne plus respirer pendant dix heures sous l'eau.</li>
<li><b>Croire que la volonté peut choisir l'objet du désir</b> et le limiter à ce qui dépend de nous. Cela suppose que l'homme puisse se soustraire aux causes extérieures. Or il n'est pas un empire dans un empire (module 5) : son corps est affecté par d'autres corps, son esprit par d'autres idées. Autant dire à un affamé de ne plus désirer le gâteau sous ses yeux.</li></ol>
<p>Dans la préface de la partie V, Spinoza le dit en toutes lettres : les <b>stoïciens</b> ont cru que les affects dépendaient absolument de notre volonté et que nous pouvions leur commander absolument ; l'expérience les a contredits. Et <b>Descartes</b>, avec sa glande pinéale, a eu la même illusion d'une volonté toute-puissante.</p>
<h3>La règle de Spinoza (E4P7)</h3>
<p>« Un affect ne peut être contrarié ni supprimé que par un <b>affect contraire et plus fort</b> que l'affect à contrarier. » On ne vainc pas une passion par la résistance ou le refus, mais en lui opposant un autre affect, plus puissant. Or la <b>connaissance</b> est elle-même un affect (elle produit de la joie), et les désirs qui naissent de la joie sont plus forts que ceux qui naissent de la tristesse (E4P18).</p>
<div class="gmnemo"><b>« Ni éteindre, ni commander : remplacer. »</b> L'ascète veut éteindre le désir, le stoïcien de YouTube veut le commander, Spinoza le remplace par un affect joyeux plus fort. Et les deux temps de Théo Lion : <b>« Accepter, puis comprendre. »</b></div>
<p>Théo Lion décrit la méthode en deux temps : d'abord <b>accepter</b> que l'émotion est là et qu'elle ne pouvait pas être autrement ; puis <b>comprendre sa cause</b>, ce qui procure une satisfaction, comme « un sac qui descend », et permet enfin de changer d'état d'esprit.</p>
<div class="gtrap">Nuance : le « stoïcisme de YouTube » (« contrôle ta réaction aux choses ») est une version appauvrie. Les vrais stoïciens (Épictète, Sénèque, Marc Aurèle) avaient une théorie fine : les passions sont des jugements erronés qu'on peut rectifier, et le sage connaît de « bonnes émotions » (joie raisonnable, vigilance). Spinoza partage beaucoup avec eux : le déterminisme, une Nature divine, l'acceptation de la nécessité. Il s'en sépare sur deux points : les affects sont aussi des états du <b>corps</b>, pas seulement des jugements ; et il n'existe pas de <b>volonté</b> capable de les commander absolument.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Présenter les remèdes épicurien, cynique et stoïcien</li><li>Expliquer la double méprise selon Spinoza</li><li>Citer et appliquer E4P7</li><li>Nuancer le « stoïcisme de YouTube »</li></ul>`},
/*EXOS*/
{i:"s209_01",u:209,t:"story",d:.2,nw:"Un affect plus fort",q:"Samir veut devenir stoïque et « ne plus avoir aucune émotion ». Que lui dit Julien ?",sc:[{who:"Samir",txt:"Cette fois, je supprime mes émotions."}],o:["« On n'éteint pas un affect : on le remplace par un affect plus fort. »","« Excellente idée, trois livres suffisent pour y arriver en une semaine. »","« Il faut supprimer uniquement les émotions joyeuses, qui rendent faible. »","« Garde tes émotions, mais ne dors plus pour avoir moins de temps pour elles. »"],a:0,w:"E4P7. Ni éteindre, ni commander : remplacer."},
{i:"s209_02",u:209,t:"fill",d:.2,q:"Un affect ne peut être contrarié ni supprimé que par un affect contraire et plus ___.",o:["fort","sage","ancien","noble"],a:0,w:"E4P7. C'est la règle centrale de la méthode spinoziste."},
{i:"s209_03",u:209,t:"match",d:.25,q:"Associe chaque école à son remède.",p:[["Épicuriens","Trier les désirs, écarter les désirs vains"],["Cyniques","Rejeter conventions et biens superflus"],["Stoïciens","Ne valoriser que ce qui dépend de nous"],["Spinoza","Remplacer un affect par un plus fort"]],w:"Trois remèdes antiques, et la réponse de Spinoza, qui les respecte mais les juge insuffisants."},
{i:"s209_04",u:209,t:"tf",d:.25,q:"Pour Spinoza, l'ascétisme, qui cherche à éteindre le désir, est une impasse.",a:true,w:"Le désir est notre essence : l'éteindre, c'est vouloir supprimer la vie. Comme retenir sa respiration dix heures sous l'eau. L'ascétisme veut éteindre ce qui est notre essence."},
{i:"s209_05",u:209,t:"mcq",d:.25,q:"Quelle phrase d'Épictète Théo Lion cite-t-il ?",o:["Ce sont nos jugements sur les choses qui troublent","Connais-toi toi-même, et tu connaîtras le monde","Je pense, donc je suis, et Dieu existe","L'homme est la mesure de toutes choses"],a:0,w:"Manuel d'Épictète, chapitre 5. Les autres sont de Socrate (Delphes), Descartes et Protagoras."},
{i:"s209_06",u:209,t:"story",d:.3,q:"Léa raconte sa semaine sans téléphone suivie d'une rechute pire qu'avant. Comment Julien l'explique-t-il ?",sc:[{who:"Léa",txt:"J'avais pourtant une volonté de fer."}],o:["« Tu as voulu commander le désir au lieu d'opposer un affect plus fort. »","« Ta volonté n'était pas assez forte, il fallait tenir un mois au lieu d'une semaine. »","« Le téléphone est plus fort que toi, il n'y a rien à faire contre cela. »","« Tu aurais dû jeter ton téléphone dans la Garonne, c'est plus efficace. »"],a:0,w:"La résistance crée un combat qu'on perd souvent. Spinoza propose de construire un désir joyeux plus puissant, pas de serrer les dents."},
{i:"s209_07",u:209,t:"sort",d:.3,q:"Classe chaque désir selon Épicure.",bins:["Naturel et nécessaire","Vain"],it:[["Manger à sa faim",0],["La gloire",1],["Se protéger du froid",0],["Le pouvoir sur les autres",1],["Une richesse sans limite",1]],w:"Lettre à Ménécée. Spinoza reconnaît le diagnostic, mais pas le remède : on ne supprime pas un désir en le déclarant vain."},
{i:"s209_08",u:209,t:"tiles",d:.3,q:"Reconstitue la formule des trois attitudes face au désir.",a:["ni","éteindre","ni","commander","remplacer"],dd:["obéir","fuir","juger"],w:"L'ascète éteint, le stoïcien commande, Spinoza remplace."},
{i:"s209_09",u:209,t:"multi",d:.35,q:"Quelles sont les deux méprises des remèdes antiques selon Spinoza, et ce qui en découle ?",o:["Croire qu'on peut éteindre le désir","Croire que la volonté choisit l'objet du désir","Oublier que nous sommes affectés par des causes extérieures","Surestimer la puissance de la volonté","Croire que le désir est notre essence"],a:[0,1,2,3],w:"La dernière est au contraire la thèse de Spinoza, qui rend les deux méprises visibles."},
{i:"s209_10",u:209,t:"fill",d:.35,q:"Dans la préface de la partie V, Spinoza reproche aux ___ d'avoir cru que les affects dépendent absolument de la volonté.",o:["stoïciens","épicuriens","sceptiques","platoniciens"],a:0,w:"Et à Descartes la même illusion, avec la glande pinéale. L'expérience les contredit."},
{i:"s209_11",u:209,t:"story",d:.4,q:"Samir cite Marc Aurèle : « Tu as pouvoir sur ton esprit, pas sur les événements ». Julien nuance. Comment ?",sc:[{who:"Samir",txt:"Donc je contrôle au moins mon esprit, non ?"}],o:["« Ton esprit aussi est affecté par des causes : pas de volonté hors nature. »","« Oui, ton esprit est entièrement sous le contrôle absolu de ta volonté libre. »","« Non, tu ne contrôles ni ton esprit ni rien, donc inutile d'essayer. »","« Marc Aurèle n'a jamais existé, c'est un personnage de roman inventé. »"],a:0,w:"L'esprit est l'idée du corps, affecté par d'autres corps et d'autres idées. On ne commande pas, on comprend et on remplace. Rappel : la volonté et l'entendement sont une même chose (E2P49)."},
{i:"s209_12",u:209,t:"mcq",d:.4,q:"Quelle image Théo Lion utilise-t-il pour montrer qu'on ne peut pas éteindre le désir ?",o:["Retenir son souffle dix heures sous l'eau","Éteindre un incendie avec un verre d'eau","Arrêter la marée montante avec les mains","Compter les étoiles du ciel une par une"],a:0,w:"Supprimer le désir, c'est vouloir supprimer la vie. Ce n'est pas humain. D'où l'échec de l'ascétisme."},
{i:"s209_13",u:209,t:"order",d:.4,q:"Remets dans l'ordre les deux temps de la méthode décrite par Théo Lion.",it:["L'émotion arrive","Accepter qu'elle ne pouvait pas être autrement","Chercher sa cause","Comprendre procure une satisfaction","Un affect joyeux remplace la tristesse"],w:"Accepter, puis comprendre. La compréhension est elle-même un affect joyeux."},
{i:"s209_14",u:209,t:"tf",d:.45,q:"Selon Spinoza, les désirs qui naissent de la joie sont plus forts que ceux qui naissent de la tristesse.",a:true,w:"E4P18. C'est pourquoi on combat une passion triste par un désir joyeux, pas par la honte ou la peur."},
{i:"s209_15",u:209,t:"story",d:.45,q:"Anaïs veut arrêter de grignoter au bureau par la seule force de sa volonté. Que lui suggère Julien, en spinoziste ?",sc:[{who:"Anaïs",txt:"Je vais juste me l'interdire."}],o:["« Trouve un plaisir plus fort : une vraie pause, une marche, un bon fruit. »","« Interdis-le toi très fort, et punis-toi à chaque écart, ça finira par marcher. »","« Mange encore plus pour t'en dégoûter, c'est la méthode la plus rapide. »","« Accepte de grignoter toute ta vie, rien ne pourra jamais changer cela. »"],a:0,w:"E4P7 appliqué au quotidien : on oppose un affect joyeux plus fort, on ne se contente pas d'interdire."},
{i:"s209_16",u:209,t:"match",d:.5,q:"Associe chaque penseur à sa position sur la maîtrise des passions.",p:[["Épictète","Ce qui dépend de nous, ce qui n'en dépend pas"],["Descartes","La volonté peut acquérir un pouvoir absolu"],["Diogène","Vivre selon la nature, sans conventions"],["Spinoza","Seul un affect plus fort l'emporte"]],w:"Les trois premiers surestiment, selon Spinoza, la maîtrise volontaire."},
{i:"s209_17",u:209,t:"fill",d:.5,q:"Le philosophe cynique célèbre pour avoir vécu dans un tonneau s'appelle ___.",o:["Diogène","Épicure","Sénèque","Zénon"],a:0,w:"Diogène de Sinope. Les cyniques rejetaient les conventions et les biens superflus."},
{i:"s209_18",u:209,t:"sort",d:.5,q:"Classe chaque phrase : stoïcisme de YouTube ou nuance du vrai stoïcisme ?",bins:["Stoïcisme de YouTube","Vrai stoïcisme"],it:[["Contrôle ta réaction, c'est tout",0],["Les passions sont des jugements qu'on peut rectifier",1],["Ne ressens plus rien",0],["Le sage connaît de bonnes émotions",1]],w:"Les vrais stoïciens étaient plus fins. Spinoza s'en sépare sur le corps et sur la volonté."},
{i:"s209_19",u:209,t:"story",d:.55,q:"Rappel du module 10 : Léa demande pourquoi la connaissance peut vaincre une passion, alors que savoir ne suffit pas.",sc:[{who:"Léa",txt:"Tu m'as dit que savoir ne suffisait pas. Alors ?"}],o:["« Un savoir froid ne suffit pas ; une compréhension joyeuse, si. »","« En fait, savoir suffit toujours, j'avais tort la semaine dernière. »","« La connaissance ne peut jamais vaincre une passion, c'est impossible. »","« Seule la connaissance des autres compte, jamais la tienne. »"],a:0,w:"E4P14 : le vrai ne pèse qu'en tant qu'affect. Comprendre la cause produit de la joie : c'est ce qui en fait un affect plus fort."},
{i:"s209_20",u:209,t:"tf",d:.55,q:"Spinoza partage avec les stoïciens l'idée que tout arrive selon une nécessité naturelle.",a:true,w:"Déterminisme, Nature divine, acceptation de la nécessité : Spinoza est voisin des stoïciens, tout en étant plus fin sur le corps et la volonté."},
{i:"s209_21",u:209,t:"mcq",d:.6,q:"Sur quel point essentiel Spinoza se sépare-t-il des stoïciens ?",o:["Nulle volonté ne commande absolument les affects","La nature n'obéit à aucune loi connaissable","Les émotions n'existent pas vraiment en nous","Le sage doit fuir la société et vivre seul"],a:0,w:"Les affects sont aussi des états du corps, et il n'existe pas de volonté hors nature pour les commander."},
{i:"s209_22",u:209,t:"multi",d:.6,q:"Quelles actions appliquent E4P7 à la vie d'une start-up ?",o:["Opposer à la peur des chiffres la joie d'un projet qu'on aime","Remplacer la jalousie par la curiosité pour le concurrent","Opposer à la honte d'un échec la joie d'en comprendre la cause","Remplacer le doomscrolling par une activité qui passionne","Se forcer à ne plus rien ressentir"],a:[0,1,2,3],w:"À chaque fois, un affect joyeux plus fort prend la place d'une passion triste."},
{i:"s209_23",u:209,t:"story",d:.65,q:"Victor affirme : « Un vrai leader ne ressent pas la peur ». Qu'en pense Julien avec Spinoza ?",sc:[{who:"Victor",txt:"La peur, c'est pour les faibles."}],o:["« Il la ressent comme tout le monde ; il a un désir plus fort qu'elle. »","« Il a raison, un vrai leader a supprimé la peur par sa volonté de fer. »","« Il a tort, un leader doit avoir peur tout le temps pour rester prudent. »","« La peur n'existe pas chez Spinoza, ce mot n'apparaît pas dans l'Éthique. »"],a:0,w:"La crainte est un affect défini par Spinoza. Le courage n'est pas l'absence de peur, mais un affect plus fort qu'elle."},
{i:"s209_24",u:209,t:"fill",d:.65,q:"Selon Théo Lion, comprendre la cause d'une émotion procure une satisfaction, comme « un sac qui ___ ».",o:["descend","explose","tombe","vole"],a:0,w:"L'image du poids qui se pose. Comprendre est déjà un soulagement, donc une joie."},
{i:"s209_25",u:209,t:"sort",d:.7,q:"Classe chaque méthode face à l'angoisse du lundi : spinoziste ou non ?",bins:["Spinoziste","Non spinoziste"],it:[["Chercher ce qui, précisément, angoisse",0],["Se répéter « je ne dois pas avoir peur »",1],["Préparer une première heure qui fait plaisir",0],["Nier l'angoisse devant l'équipe",1]],w:"On accepte, on comprend, on remplace. Nier et se sermonner n'agit pas sur la cause."},
{i:"s209_26",u:209,t:"tiles",d:.7,q:"Reconstitue les deux temps de la méthode de Théo Lion.",a:["accepter","puis","comprendre"],dd:["refuser","oublier","punir"],w:"Accepter que l'émotion ne pouvait pas être autrement, puis en comprendre la cause."},
{i:"s209_27",u:209,t:"story",d:.75,q:"Rappel du module 9 : Samir veut « ne plus désirer la Ferrari ». Comment appliquer E4P7 ?",sc:[{who:"Samir",txt:"Je me l'interdis, et c'est réglé."}],o:["« Cultive un désir plus fort, celui d'un projet qui te passionne. »","« Interdis-toi aussi de regarder des voitures dans la rue, pour toujours. »","« Achète une photo de Ferrari pour saturer ton désir en la regardant. »","« Désire deux Ferrari, le premier désir sera ainsi dilué dans le second. »"],a:0,w:"Un désir imité ne disparaît pas par interdiction ; il perd sa force face à un désir plus propre et plus joyeux."},
{i:"s209_28",u:209,t:"mcq",d:.75,q:"Pourquoi l'interdiction pure d'un désir échoue-t-elle souvent selon Spinoza ?",o:["Elle n'oppose aucun affect plus fort","Elle est contraire à la loi française","Elle fait bien trop plaisir à celui qui l'impose","Elle coûte beaucoup trop cher à tenir"],a:0,w:"L'interdiction est souvent une tristesse, plus faible qu'un désir joyeux. Il faut un affect contraire et plus fort."},
{i:"s209_29",u:209,t:"match",d:.8,q:"Associe chaque erreur à celui qui la commet, selon ce module.",p:[["Éteindre le désir","L'ascète"],["Commander le désir","Le stoïcien de YouTube"],["Maîtriser par la glande pinéale","Descartes"],["Réprimer par la honte","Léa après sa rechute"]],w:"Toutes surestiment la volonté ou nient le désir. Spinoza propose de remplacer. L'ascétisme et le stoïcisme de YouTube surestiment la volonté."},
{i:"s209_30",u:209,t:"tf",d:.8,q:"Pour Spinoza, les stoïciens ont eu tort de croire qu'on peut commander absolument ses affects.",a:true,w:"Préface de la partie V : l'expérience les contredit. Il faut beaucoup d'exercice et d'étude, et une autre méthode."},
{i:"s209_31",u:209,t:"fill",d:.85,q:"La connaissance est elle-même un ___, car elle produit de la joie.",o:["affect","dogme","hasard","devoir"],a:0,w:"C'est ce qui lui donne la force de remplacer une passion triste. La méthode détaillée arrive au module 13."},
{i:"s209_32",u:209,t:"story",d:.85,q:"Synthèse : Samir repose ses trois livres. Quelle phrase résume ce qu'il a compris ?",sc:[{who:"Samir",txt:"Bon, je prends lequel, finalement ?"}],o:["« Pas de détachement total : je vais chercher des joies plus fortes. »","« Je prends les trois, et je supprime toutes mes émotions en sept jours chrono. »","« Aucun, la philosophie ne sert à rien, il faut juste subir ses émotions. »","« Seulement celui de Marc Aurèle, qui dit exactement la même chose que Spinoza. »"],a:0,w:"Ni éteindre, ni commander : remplacer. Accepter, puis comprendre."}
