/*UNIT*/
{id:210,c:"SPINO",n:"Module 12",t:"Les trois genres de connaissance : entendre, démontrer, voir",col:"--purple",ic:"💡",guide:`
<h3>L'orage d'Arcachon</h3>
<div class="gstory">Dimanche soir, orage sur le bassin d'Arcachon. Chez Maud, la petite Zoé, 6 ans, la fille d'Anaïs, pleure sous la table : « Le ciel est fâché contre moi. » Julien s'assoit à côté d'elle et lui explique l'air chaud, l'air froid, les nuages chargés d'électricité, l'éclair, puis le bruit qui le suit. Il compte avec elle les secondes entre l'éclair et le tonnerre. Au troisième éclair, Zoé compte seule, et elle sourit. Léa observe la scène : « Tu viens de faire avec elle ce que tu fais avec moi depuis des semaines. » Julien : « C'est exactement ça. Spinoza l'appelle passer du premier au deuxième genre de connaissance. »</div>
<h3>Les trois genres (E2P40, scolie 2)</h3>
<table><tr><th>Genre</th><th>Nom</th><th>Comment on connaît</th><th>Valeur</th></tr>
<tr><td><b>1er</b></td><td><b>Opinion</b> ou <b>imagination</b></td><td>Par expérience vague (les sens, les hasards de la vie) et par signes (ouï-dire, lectures, souvenirs)</td><td>Idées confuses et mutilées : <b>seule source d'erreur</b> (E2P41)</td></tr>
<tr><td><b>2e</b></td><td><b>Raison</b></td><td>Par des <b>notions communes</b> et des idées adéquates des propriétés des choses, par déduction</td><td>Nécessairement vraie</td></tr>
<tr><td><b>3e</b></td><td><b>Science intuitive</b></td><td>De l'idée adéquate de certains attributs de Dieu à la connaissance adéquate de l'<b>essence</b> des choses singulières, d'un seul regard</td><td>Nécessairement vraie, source de la plus haute joie</td></tr></table>
<div class="gmnemo"><b>« Entendre, Démontrer, Voir. »</b> Premier genre : j'ai entendu dire. Deuxième : je démontre. Troisième : je vois d'un coup. Ou en initiales : <b>O.R.I. : Opinion, Raison, Intuition</b>.</div>
<h3>L'exemple des nombres proportionnels</h3>
<p>On te donne trois nombres. Il faut en trouver un quatrième qui soit au troisième ce que le deuxième est au premier. Prenons 1, 2, 3.</p>
<ul><li>Le <b>marchand</b> multiplie le deuxième par le troisième et divise par le premier, parce qu'on le lui a appris ou que ça a marché avant : <b>premier genre</b>.</li>
<li>Le <b>mathématicien</b> le démontre par la propriété des proportionnels (Euclide) : <b>deuxième genre</b>.</li>
<li>Avec des nombres si simples, <b>tout le monde voit</b> d'un coup que le quatrième est <b>6</b> : <b>troisième genre</b>.</li></ul>
<h3>Appliqué à l'entrepreneur</h3>
<table><tr><th>Genre</th><th>Exemple de la vidéo</th></tr>
<tr><td>1er</td><td>L'entrepreneur qui associe mécaniquement levée de fonds et bonheur, ou qui croit que plus d'argent le rendra plus séduisant. (« Plus d'argent vous rendra toujours plus séduisant… auprès des personnes séduites par l'argent », glisse Théo Lion.)</td></tr>
<tr><td>2e</td><td>L'enfant qui comprend que le tonnerre accompagne nécessairement l'orage : la peur se dissipe. L'entrepreneur qui comprend que l'argent, la gloire et le prestige ne sont pas des biens en soi, mais des moyens : son malaise change de nature.</td></tr>
<tr><td>3e</td><td>L'ancien fumeur devenu vraiment <b>non-fumeur</b> : il ne lutte plus contre l'envie, il ne la ressent plus. L'entrepreneur qui a saisi intuitivement qu'une levée mal motivée mène à la tristesse ne combat plus ce désir : il ne l'éprouve plus.</td></tr></table>
<p>La raison peut <b>réordonner</b> les passions, mais seule l'intuition les <b>transforme en profondeur</b>. Elle fait passer d'un combat perpétuel contre nos désirs à une vraie paix de l'âme, où ce qui nous nuisait cesse simplement de nous attirer.</p>
<h3>Le vrai se montre lui-même</h3>
<p>« Qui a une idée vraie sait en même temps qu'il a une idée vraie » (E2P43). Dans le scolie : <b>comme la lumière se manifeste elle-même et manifeste les ténèbres</b>, la vérité est la norme d'elle-même et du faux (<i>verum index sui et falsi</i>). Et dans la partie V : l'effort suprême de l'esprit est de connaître par le troisième genre (E5P25), d'où naît le plus grand contentement de l'esprit (E5P27).</p>
<div class="gtrap">Précision : le premier genre n'est pas « mauvais » et on ne s'en débarrasse jamais. On vit avec l'imagination (on continue à voir le soleil proche, module 6). Une idée imaginative n'est pas fausse en elle-même : elle le devient quand on la prend pour la vérité des choses. Et Spinoza ne dit pas que l'intuition est une inspiration mystérieuse ou un « feeling » : c'est une connaissance <b>adéquate</b>, préparée par la raison.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Nommer et définir les trois genres de connaissance</li><li>Expliquer l'exemple des nombres proportionnels</li><li>Classer une situation d'entrepreneur dans le bon genre</li><li>Expliquer pourquoi seul le troisième genre transforme en profondeur</li></ul>`},
/*EXOS*/
{i:"s210_01",u:210,t:"match",d:.2,nw:"Les trois genres de connaissance",q:"Associe chaque genre de connaissance à son nom.",p:[["Premier genre","Opinion ou imagination"],["Deuxième genre","Raison"],["Troisième genre","Science intuitive"],["Seule source d'erreur","Le premier genre"]],w:"O.R.I. : Opinion, Raison, Intuition. Entendre, démontrer, voir."},
{i:"s210_02",u:210,t:"story",d:.2,q:"Zoé a peur de l'orage, puis compte seule les secondes en souriant. Qu'a-t-il changé en elle ?",sc:[{who:"Léa",txt:"Julien n'a pas arrêté l'orage, pourtant elle n'a plus peur."}],o:["« Elle a compris la cause : une loi naturelle remplace l'idée d'un ciel fâché. »","« Elle s'est simplement habituée au bruit au bout de trois éclairs, voilà tout. »","« Julien lui a promis un bonbon pour qu'elle arrête de pleurer sous la table. »","« Elle a décidé par sa volonté de ne plus avoir peur de l'orage. »"],a:0,w:"Passage du premier au deuxième genre : connaître la cause dissipe la tristesse. C'est l'exemple de la vidéo. Le tonnerre suit l'éclair par une loi naturelle, pas par colère du ciel."},
{i:"s210_03",u:210,t:"fill",d:.25,q:"Dans l'exemple des nombres 1, 2, 3, le quatrième proportionnel que tout le monde voit d'un coup est ___.",o:["6","4","5","9"],a:0,w:"1 est à 2 comme 3 est à 6. Le voir d'un coup relève du troisième genre."},
{i:"s210_04",u:210,t:"tf",d:.25,q:"Pour Spinoza, le premier genre de connaissance est la seule cause de fausseté.",a:true,w:"E2P41. Le deuxième et le troisième genres sont nécessairement vrais."},
{i:"s210_05",u:210,t:"sort",d:.3,q:"Classe chaque façon de trouver le quatrième proportionnel.",bins:["1er genre","2e genre","3e genre"],it:[["Le marchand applique une règle apprise",0],["Le mathématicien démontre par Euclide",1],["On voit d'un coup que c'est 6",2],["On refait comme l'an dernier parce que ça avait marché",0]],w:"Entendre (ou expérience vague), démontrer, voir."},
{i:"s210_06",u:210,t:"mcq",d:.3,q:"Sur quoi repose le deuxième genre de connaissance ?",o:["Les notions communes","Les rumeurs du quartier","Les rêves nocturnes","Les révélations divines"],a:0,w:"Les notions communes : ce qui est commun à toutes choses ou à plusieurs corps. D'où des idées adéquates des propriétés des choses. Les notions communes sont la base de la raison, deuxième genre de connaissance."},
{i:"s210_07",u:210,t:"story",d:.3,q:"Samir pense qu'une levée de fonds le rendra heureux « parce que tous les fondateurs heureux ont levé ». Dans quel genre est-il ?",sc:[{who:"Samir",txt:"C'est prouvé, regarde les photos sur LinkedIn."}],o:["« Le premier : une association d'images, sans connaître les causes. »","« Le deuxième : c'est une démonstration mathématique rigoureuse. »","« Le troisième : il le voit d'un coup, c'est donc forcément vrai. »","« Aucun : Spinoza ne parle pas de ce genre de situation du tout. »"],a:0,w:"Expérience vague et signes : des photos, des récits. C'est le registre de l'imagination qui nourrit les passions tristes."},
{i:"s210_08",u:210,t:"tiles",d:.35,q:"Reconstitue le moyen mnémotechnique des trois genres.",a:["entendre","démontrer","voir"],dd:["croire","rêver","juger"],w:"Premier genre : j'ai entendu. Deuxième : je démontre. Troisième : je vois d'un coup."},
{i:"s210_09",u:210,t:"multi",d:.35,q:"Que comprend le premier genre de connaissance ?",o:["L'expérience vague","Le ouï-dire","Les lectures non comprises","Les souvenirs associés","La démonstration géométrique"],a:[0,1,2,3],w:"Expérience vague et connaissance par signes. La démonstration relève du deuxième genre."},
{i:"s210_10",u:210,t:"fill",d:.35,q:"Le troisième genre de connaissance s'appelle la science ___.",o:["intuitive","naturelle","divine","exacte"],a:0,w:"Scientia intuitiva : elle saisit l'essence d'une chose singulière d'un seul regard."},
{i:"s210_11",u:210,t:"story",d:.4,q:"L'oncle de Léa a arrêté de fumer il y a dix ans. On lui tend une cigarette : il ne ressent aucune envie. Quel genre Théo Lion y voit-il ?",sc:[{who:"Léa",txt:"Il ne lutte même pas, c'est fou."}],o:["« Le troisième : il ne combat plus le désir, il ne l'éprouve plus. »","« Le premier : il a entendu dire que le tabac est mauvais pour la santé. »","« Le deuxième : il calcule à chaque fois les risques pour sa santé. »","« Aucun : il a juste une volonté très forte qu'il exerce à chaque fois. »"],a:0,w:"L'intuition ne se contente pas de savoir qu'une passion est nuisible : elle le fait éprouver, au point que le désir disparaît de lui-même."},
{i:"s210_12",u:210,t:"tf",d:.4,q:"Pour Spinoza, l'intuition est une inspiration mystérieuse, un simple « feeling ».",a:false,w:"C'est une connaissance adéquate, préparée par la raison. Rien à voir avec un pressentiment."},
{i:"s210_13",u:210,t:"mcq",d:.45,q:"Quelle image Spinoza utilise-t-il pour dire que le vrai se montre lui-même ?",o:["La lumière qui montre elle-même et l'ombre","Le miroir qui reflète fidèlement le visage","La clé qui ouvre seule la bonne serrure","Le fleuve qui rejoint toujours la mer"],a:0,w:"E2P43, scolie : verum index sui et falsi. Le vrai est la norme de lui-même et du faux."},
{i:"s210_14",u:210,t:"order",d:.45,q:"Remets dans l'ordre le chemin de Léa face à son désir de lever toujours plus.",it:["Elle associe levée et bonheur (1er genre)","Elle comprend que l'argent est un moyen (2e genre)","Son malaise change de nature","Elle voit d'un coup ce qui la rend vraiment joyeuse (3e genre)","Le désir de lever pour lever ne l'attire plus"],w:"La raison réordonne, l'intuition transforme en profondeur. Comme l'ancien fumeur devenu non-fumeur, elle ne lutte plus."},
{i:"s210_15",u:210,t:"story",d:.45,q:"Anaïs dit : « Moi, j'ai compris que la gloire n'apporte rien, mais j'ai encore envie qu'on parle de nous ». Qu'en dit Julien ?",sc:[{who:"Anaïs",txt:"Donc comprendre ne sert à rien ?"}],o:["« Tu es au deuxième genre : la raison réordonne, l'intuition transformera. »","« Tu n'as rien compris du tout, sinon ton envie aurait déjà disparu. »","« C'est normal, et il n'y a absolument rien de plus à faire que d'attendre. »","« Tu dois te forcer à ne plus y penser du tout, par la seule volonté. »"],a:0,w:"La raison peut réordonner les passions, mais seule l'intuition les transforme en profondeur. C'est un chemin."},
{i:"s210_16",u:210,t:"match",d:.5,q:"Associe chaque proposition à son contenu.",p:[["E2P40 scolie 2","Les trois genres de connaissance"],["E2P41","Le premier genre, seule cause de fausseté"],["E2P43","Qui a une idée vraie sait qu'il l'a"],["E5P25","L'effort suprême : connaître par le troisième genre"]],w:"Les textes clés sur la connaissance. Avec ces quatre repères, on retrouve toute la théorie de la connaissance."},
{i:"s210_17",u:210,t:"fill",d:.5,q:"Selon Théo Lion, plus d'argent vous rendra plus séduisant… auprès des personnes séduites par l'___.",o:["argent","humour","intelligence","élégance"],a:0,w:"Une pointe d'humour qui illustre le premier genre : une association d'images qui ne dit rien de la valeur réelle."},
{i:"s210_18",u:210,t:"sort",d:.5,q:"Classe chaque situation selon le genre de connaissance.",bins:["1er genre","2e genre","3e genre"],it:[["Croire qu'un article en une rend heureux",0],["Démontrer qu'une dépendance expose à la tristesse",1],["Ne plus désirer une levée inutile, sans effort",2],["Choisir un associé sur sa photo LinkedIn",0],["Comprendre que le tonnerre suit l'éclair",1]],w:"Opinion, raison, intuition : trois rapports différents au même monde."},
{i:"s210_19",u:210,t:"slider",d:.55,q:"Combien de genres de connaissance Spinoza distingue-t-il dans l'Éthique ?",min:1,max:10,step:1,a:3,tol:0,pre:"",un:"",w:"Trois (E2P40, scolie 2). Dans un texte de jeunesse, le Traité de la réforme de l'entendement, il en comptait quatre modes."},
{i:"s210_20",u:210,t:"story",d:.55,q:"Rappel du module 6 : Léa sait que le soleil est loin, mais le voit toujours proche. Est-ce un échec de la connaissance ?",sc:[{who:"Léa",txt:"Si je sais, pourquoi je le vois encore petit et proche ?"}],o:["« Non : l'image reste, mais tu n'es plus dans l'erreur, tu sais ce qu'elle vaut. »","« Oui, cela prouve que la connaissance ne sert jamais à rien face à l'image. »","« Oui, et il faut arrêter de regarder le soleil pour que l'image disparaisse. »","« Non, car en réalité le soleil est vraiment tout proche de la Terre, en fait. »"],a:0,w:"L'imagination ne disparaît pas ; elle cesse de tromper. Le premier genre n'est pas faux en soi, il le devient quand on le prend pour la vérité."},
{i:"s210_21",u:210,t:"mcq",d:.6,q:"Quelle différence entre la raison et l'intuition selon Théo Lion ?",o:["La raison réordonne, l'intuition transforme","La raison est fausse, l'intuition est vraie","La raison vient des sens, l'intuition des livres","Aucune, ce sont deux mots pour la même chose"],a:0,w:"Les deux sont vraies ; mais seule l'intuition fait cesser le combat : ce qui nuisait cesse d'attirer."},
{i:"s210_22",u:210,t:"tf",d:.6,q:"Selon E5P27, le troisième genre de connaissance procure le plus grand contentement de l'esprit.",a:true,w:"C'est l'acquiescentia, le contentement de soi, qui prépare la béatitude (module 15)."},
{i:"s210_23",u:210,t:"multi",d:.65,q:"Quels exemples relèvent du deuxième genre ?",o:["L'enfant qui comprend la cause du tonnerre","Le mathématicien qui démontre une proportion","L'entrepreneur qui comprend que l'argent est un moyen","Le physicien qui explique une loi","Le marchand qui applique une règle sans la comprendre"],a:[0,1,2,3],w:"Le marchand qui applique sans comprendre reste au premier genre, même s'il trouve le bon résultat. Le deuxième genre repose sur les notions communes."},
{i:"s210_24",u:210,t:"fill",d:.65,q:"La formule latine verum index sui et falsi veut dire : le vrai est la norme de lui-même et du ___.",o:["faux","bien","beau","juste"],a:0,w:"E2P43, scolie. Comme la lumière révèle aussi l'obscurité."},
{i:"s210_25",u:210,t:"story",d:.7,q:"Samir demande : « Comment je passe du premier au deuxième genre sur mon projet ? » Que propose Julien ?",sc:[{who:"Samir",txt:"Concrètement, je fais quoi ?"}],o:["« Cherche les causes de ton désir, et ce qui est commun aux fondateurs joyeux. »","« Regarde encore plus de vidéos de fondateurs à succès sur les réseaux sociaux. »","« Écoute ton ventre et suis ton premier feeling, c'est toujours le troisième genre. »","« Arrête de réfléchir, la connaissance empêche d'entreprendre, il faut foncer. »"],a:0,w:"Les notions communes : ce qui se retrouve chez tous ceux dont le projet augmente la puissance. On remonte aux causes."},
{i:"s210_26",u:210,t:"tiles",d:.7,q:"Reconstitue la proposition E2P43.",a:["qui","a","une","idée","vraie","sait","qu'il","l'a"],dd:["doute","croit","fausse"],w:"Qui a une idée vraie sait en même temps qu'il a une idée vraie et ne peut douter de la vérité de la chose."},
{i:"s210_27",u:210,t:"sort",d:.75,q:"Classe chaque phrase : fidèle à Spinoza ou contresens ?",bins:["Fidèle","Contresens"],it:[["On ne se débarrasse jamais de l'imagination",0],["L'intuition est un feeling mystérieux",1],["La raison produit des idées adéquates",0],["Le premier genre est toujours faux",1]],w:"L'imagination n'est fausse que prise pour la vérité ; l'intuition est une connaissance adéquate."},
{i:"s210_28",u:210,t:"story",d:.75,q:"Rappel du module 9 : pourquoi l'imitation des désirs relève-t-elle du premier genre ?",sc:[{who:"Léa",txt:"Désirer ce que les autres désirent, c'est de l'imagination ?"}],o:["« Oui : on associe une image de joie à un objet, sans en connaître les causes. »","« Non, c'est du troisième genre, car on le ressent immédiatement en soi. »","« Non, c'est de la raison, car on imite les gens les plus intelligents du groupe. »","« Oui, mais c'est une connaissance nécessairement vraie malgré tout. »"],a:0,w:"L'émulation repose sur l'imagination de la joie d'autrui : connaissance confuse, source de passions tristes."},
{i:"s210_29",u:210,t:"mcq",d:.8,q:"Selon E5P25, quel est l'effort suprême de l'esprit ?",o:["Connaître par le troisième genre","Accumuler le plus de richesses","Être admiré par le plus grand nombre","Suivre les règles de sa religion"],a:0,w:"L'effort suprême de l'esprit et sa suprême vertu : comprendre les choses par la science intuitive."},
{i:"s210_30",u:210,t:"tf",d:.8,q:"Pour Spinoza, le marchand qui trouve le bon résultat avec une règle apprise connaît au deuxième genre.",a:false,w:"Il trouve juste sans comprendre pourquoi : c'est le premier genre, par ouï-dire ou expérience."},
{i:"s210_31",u:210,t:"match",d:.85,q:"Associe chaque personnage à son genre de connaissance dominant dans ce module.",p:[["Zoé après l'explication","Deuxième genre"],["Samir et les photos LinkedIn","Premier genre"],["L'oncle non-fumeur","Troisième genre"],["Anaïs qui a compris mais désire encore","Deuxième genre"]],w:"Chacun peut progresser d'un genre à l'autre. C'est tout le chemin de l'Éthique. Le tonnerre pour Zoé, le non-fumeur pour le troisième genre."},
{i:"s210_32",u:210,t:"story",d:.9,q:"Synthèse : Léa demande pourquoi Spinoza fait de la connaissance le cœur de la joie.",sc:[{who:"Léa",txt:"Pourquoi la connaissance, et pas l'action ?"}],o:["« Comprendre, c'est agir : on devient cause de ce qu'on vit, et ça réjouit. »","« Parce qu'il était philosophe et méprisait profondément toute action concrète. »","« Parce que la connaissance rapporte de l'argent, qui rend ensuite heureux. »","« Parce qu'il pensait que l'action rend toujours triste et qu'il faut l'éviter. »"],a:0,w:"Une idée adéquate fait de nous une cause active. Entendre, démontrer, voir : plus on comprend, plus on agit, plus on se réjouit."}
