/*UNIT*/
{id:211,c:"SPINO",n:"Module 13",t:"La méthode : comprendre une passion pour la transformer",col:"--purple",ic:"🛠️",guide:`
<h3>Le carnet de Léa</h3>
<div class="gstory">Trois mois après la levée, Cargo &amp; Co vient de passer le cap du million de chiffre d'affaires. Léa devrait sauter de joie, mais elle ressent une tristesse sourde. Cette fois, au lieu de se juger, elle ouvre le carnet que Julien lui a offert et remplit les colonnes. Situation : le million. Affect : tristesse, vide. Idée qui l'accompagne : « Ce n'est pas assez, VéloFret fait plus. » Cause réelle, après réflexion : elle voulait ce million pour prouver à ses anciens camarades d'école de commerce qu'elle avait réussi, et pour faire taire la peur d'échouer. Elle referme le carnet. Quelque chose s'est desserré. « C'est bizarre, dit-elle à Julien, rien n'a changé, et pourtant je me sens mieux. »</div>
<h3>Les propositions clés de la partie V</h3>
<table><tr><th>Texte</th><th>Idée</th></tr>
<tr><td><b>E5P3</b></td><td>« Un affect qui est une passion cesse d'être une passion sitôt que nous en formons une <b>idée claire et distincte</b>. »</td></tr>
<tr><td><b>E5P4</b></td><td>Il n'est aucune affection du corps dont nous ne puissions former un concept clair et distinct : <b>aucune tristesse n'est incompréhensible par nature</b>.</td></tr>
<tr><td><b>E5P2</b></td><td>Si l'on sépare un affect de l'idée d'une cause extérieure confuse, l'amour ou la haine envers cette cause sont détruits.</td></tr>
<tr><td><b>E5P6</b></td><td>Plus l'esprit comprend les choses comme <b>nécessaires</b>, moins il pâtit des affects. La tristesse d'une perte diminue quand on voit qu'elle ne pouvait être évitée.</td></tr>
<tr><td><b>E5P10</b></td><td>Tant que nous ne sommes pas dominés par des affects contraires à notre nature, nous avons le pouvoir d'<b>ordonner et d'enchaîner</b> les affections du corps selon l'ordre de l'entendement : le « super pouvoir » dont parle Théo Lion.</td></tr></table>
<h3>Les cinq remèdes (E5P20, scolie)</h3>
<ol><li><b>Connaître</b> les affects eux-mêmes.</li>
<li><b>Séparer</b> l'affect de l'idée d'une cause extérieure confusément imaginée.</li>
<li>Le <b>temps</b> : les affects liés à des choses comprises durent plus que ceux liés à des choses confuses.</li>
<li>La <b>multiplicité</b> des causes : un affect rapporté à beaucoup de causes pèse moins sur chacune.</li>
<li>L'<b>ordre</b> : enchaîner ses affects selon la raison.</li></ol>
<div class="gmnemo"><b>« Comprendre Sépare Toujours Mes Obsessions »</b> : Connaître, Séparer, Temps, Multiplier les causes, Ordonner. Et la règle d'or de la partie V : <b>« Passion comprise, passion transformée. »</b></div>
<h3>La mauvaise note et le mauvais chapitre</h3>
<p>Théo Lion donne un exemple : on vous annonce que votre mauvaise note vient de ce que vous avez révisé le mauvais chapitre. Le résultat ne change pas, vous avez échoué. Mais la compréhension vous indique comment agir la prochaine fois. Votre puissance d'agir augmente, donc vous ressentez de la <b>joie</b>. De même, l'entrepreneur qui découvre que sa tristesse vient de raisons imaginaires (prouver quelque chose à d'anciens camarades, égaler des figures admirées, fuir l'angoisse de l'échec) découvre que son malheur n'est pas un défaut obscur en lui, mais une <b>mécanique intelligible</b>. Cette idée plus adéquate réoriente déjà son désir vers ce qui exprime vraiment sa puissance : c'est une <b>joie active</b>.</p>
<h3>Les maximes à préparer (E5P10, scolie)</h3>
<p>Spinoza conseille de se forger à l'avance des <b>règles de vie</b>, de les mémoriser et de les appliquer sans cesse aux cas particuliers. Exemple : pour ne pas être emporté par la haine, penser souvent aux offenses que font les hommes et à la meilleure façon d'y répondre par la <b>générosité</b>. Pour la crainte, penser aux dangers habituels et à la façon de les éviter par la présence d'esprit. Toujours regarder ce qu'il y a de bon dans chaque chose, pour être déterminé à agir par la joie.</p>
<table><tr><th>Colonne du carnet</th><th>Question</th></tr>
<tr><td>1. Situation</td><td>Que s'est-il passé ?</td></tr>
<tr><td>2. Affect</td><td>Joie, tristesse, désir ? Lequel exactement (envie, honte, crainte…) ?</td></tr>
<tr><td>3. Idée imaginée</td><td>Quelle cause ai-je imaginée ?</td></tr>
<tr><td>4. Causes réelles</td><td>Quelles causes, nombreuses et nécessaires, l'expliquent vraiment ?</td></tr>
<tr><td>5. Réorientation</td><td>Vers quel désir joyeux, qui vient de moi, puis-je aller ?</td></tr></table>
<div class="gtrap">Nuance, rappelée par Théo Lion lui-même : « Ce n'est pas magique. » Quand on vient de perdre quelqu'un, aucune compréhension n'efface la peine sur-le-champ. Spinoza ne promet pas l'absence de tristesse, mais que la tristesse, comprise, <b>pèse moins et dure moins</b>. Et le carnet n'est pas une méthode écrite par Spinoza : c'est une façon moderne d'appliquer les remèdes de E5P20.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Citer et expliquer E5P3, E5P4, E5P6 et E5P10</li><li>Nommer les cinq remèdes aux affects</li><li>Analyser une tristesse d'entrepreneur jusqu'à ses causes</li><li>Préparer une maxime pour une situation qui revient souvent</li></ul>`},
/*EXOS*/
{i:"s211_01",u:211,t:"fill",d:.2,nw:"Passion comprise, passion transformée",q:"E5P3 : un affect qui est une passion cesse d'être une passion sitôt que nous en formons une idée claire et ___.",o:["distincte","joyeuse","morale","personnelle"],a:0,w:"Passion comprise, passion transformée. Comprendre, c'est devenir en partie cause active de ce qu'on vit."},
{i:"s211_02",u:211,t:"story",d:.2,q:"Léa se sent mieux après avoir rempli son carnet, alors que rien n'a changé. Comment Julien l'explique-t-il ?",sc:[{who:"Léa",txt:"Rien n'a changé, et pourtant je me sens mieux. Pourquoi ?"}],o:["« Comprendre la cause est une joie : ta passion devient une action. »","« C'est une illusion passagère, la tristesse reviendra demain à coup sûr. »","« Écrire fatigue le cerveau, et un cerveau fatigué ressent moins de choses. »","« C'est le papier du carnet qui absorbe les émotions négatives. »"],a:0,w:"E5P3 : l'idée claire transforme la passion. Et comprendre augmente la puissance d'agir : c'est de la joie."},
{i:"s211_03",u:211,t:"order",d:.25,q:"Remets dans l'ordre les colonnes du carnet des affects.",it:["Situation","Affect","Idée imaginée","Causes réelles","Réorientation du désir"],w:"Une façon moderne d'appliquer les remèdes de E5P20."},
{i:"s211_04",u:211,t:"tf",d:.25,q:"Selon E5P4, il existe des tristesses incompréhensibles par nature.",a:false,w:"Aucune affection du corps n'échappe à un concept clair et distinct. Si une tristesse nous écrase, c'est que nous en ignorons encore la cause."},
{i:"s211_05",u:211,t:"multi",d:.3,q:"Quels sont les remèdes aux affects selon E5P20, scolie ?",o:["Connaître les affects","Séparer l'affect de la cause extérieure imaginée","Le temps","Rapporter l'affect à beaucoup de causes","Se punir pour chaque passion"],a:[0,1,2,3],w:"Le cinquième remède est l'ordre, pas la punition. Comprendre Sépare Toujours Mes Obsessions."},
{i:"s211_06",u:211,t:"story",d:.3,q:"Dans son carnet, Léa trouve que le million devait prouver à ses anciens camarades qu'elle avait réussi. Qu'est-ce que ça change ?",sc:[{who:"Léa",txt:"Ça fait un peu honte, non ?"}],o:["« Ton malaise n'est pas un défaut obscur : c'est une mécanique. »","« Oui, c'est honteux, et il faudrait que tu t'excuses auprès de tes camarades. »","« Rien du tout, savoir d'où vient un désir ne change jamais rien à la vie. »","« Il faut viser dix millions pour vraiment impressionner tes anciens camarades. »"],a:0,w:"Le passage à une idée plus adéquate réoriente déjà le désir vers ce qui exprime vraiment sa puissance."},
{i:"s211_07",u:211,t:"tiles",d:.3,q:"Reconstitue la règle d'or de la partie V.",a:["passion","comprise","passion","transformée"],dd:["cachée","punie","oubliée"],w:"E5P3. Une idée claire et distincte transforme la passion en action."},
{i:"s211_08",u:211,t:"match",d:.35,q:"Associe chaque remède à son exemple.",p:[["Séparer","Détacher sa colère de l'image d'un « méchant » investisseur"],["Multiplier les causes","Voir les dix raisons d'un contrat perdu"],["Temps","Les affects compris durent plus que les confus"],["Ordonner","Préparer des maximes pour les situations fréquentes"]],w:"Chaque remède agit sur un aspect de l'affect : sa cause, sa durée, son poids, son ordre."},
{i:"s211_09",u:211,t:"mcq",d:.35,q:"Selon E5P6, que se passe-t-il quand l'esprit comprend les choses comme nécessaires ?",o:["Il pâtit moins des affects","Il devient indifférent à tout","Il perd tout désir","Il devient triste"],a:0,w:"La tristesse d'une perte diminue quand on voit qu'elle ne pouvait pas être évitée. Nécessité comprise, souffrance allégée."},
{i:"s211_10",u:211,t:"story",d:.4,q:"Anaïs déteste le conseiller du fonds, Marc, qui la contredit à chaque réunion. Quel remède Julien propose-t-il ?",sc:[{who:"Anaïs",txt:"Ce type est odieux, je le déteste."}],o:["« Sépare ta colère de l'image de Marc : cherche toutes ses causes. »","« Déteste-le encore plus fort, la haine donne de l'énergie pour gagner. »","« Évite-le toute ta vie, c'est la seule façon de ne plus rien ressentir. »","« Décide par ta volonté de l'aimer, dès demain matin en réunion. »"],a:0,w:"E5P2 et le 4e remède : séparer l'affect de la cause imaginée, multiplier les causes (pression du fonds, son propre stress). La haine se défait."},
{i:"s211_11",u:211,t:"fill",d:.4,q:"Selon E5P10, nous avons le pouvoir d'ordonner et d'___ les affections du corps selon l'ordre de l'entendement.",o:["enchaîner","effacer","dissimuler","vendre"],a:0,w:"C'est le « super pouvoir » dont parle Théo Lion : réordonner nos affects selon la raison."},
{i:"s211_12",u:211,t:"sort",d:.4,q:"Classe chaque réaction de Léa au million : passion ou début d'action ?",bins:["Passion","Début d'action"],it:[["Se dire « ce n'est jamais assez »",0],["Chercher ce que ce million devait prouver",1],["Se comparer à VéloFret le soir au lit",0],["Noter ce qui l'a vraiment réjouie cette année",1]],w:"Tant qu'on subit l'idée confuse, c'est une passion ; dès qu'on en cherche les causes, on devient actif."},
{i:"s211_13",u:211,t:"tf",d:.45,q:"Selon Théo Lion, la méthode de Spinoza est magique : elle efface immédiatement toute peine.",a:false,w:"« Ce n'est pas magique. » La tristesse comprise pèse moins et dure moins, mais un deuil ne s'efface pas d'un coup."},
{i:"s211_14",u:211,t:"story",d:.45,q:"Samir a raté un examen de certification parce qu'il a révisé le mauvais module. Qu'en dirait Théo Lion ?",sc:[{who:"Samir",txt:"J'ai échoué, c'est la catastrophe."}],o:["« Le résultat reste, mais la cause comprise te dit comment réussir. »","« C'est la preuve que tu n'es pas fait pour ce métier, il faut tout abandonner. »","« Ce n'est pas grave, les examens n'ont aucune importance dans la vie réelle. »","« C'est la faute du correcteur, il faut contester sans chercher plus loin. »"],a:0,w:"C'est l'exemple de la mauvaise note : comprendre augmente la puissance d'agir, donc produit de la joie."},
{i:"s211_15",u:211,t:"mcq",d:.5,q:"Que conseille Spinoza dans le scolie de E5P10 pour ne pas être emporté par la haine ?",o:["Préparer une réponse généreuse à l'avance","Éviter tout contact avec les autres hommes","Rendre chaque offense aussitôt, sans attendre","Faire semblant de ne rien ressentir du tout"],a:0,w:"Préparer des maximes, les mémoriser, les appliquer aux cas particuliers. La haine se vainc par l'amour ou la générosité (E4P46)."},
{i:"s211_16",u:211,t:"match",d:.5,q:"Associe chaque proposition à son idée.",p:[["E5P2","Séparer l'affect de la cause imaginée"],["E5P3","Idée claire, fin de la passion"],["E5P4","Toute affection peut être comprise"],["E5P6","Comprendre la nécessité allège"]],w:"Les quatre piliers de la méthode, avant le « super pouvoir » de E5P10."},
{i:"s211_17",u:211,t:"fill",d:.5,q:"Un affect rapporté à un grand nombre de ___ pèse moins sur chacune.",o:["causes","personnes","jours","objets"],a:0,w:"Quatrième remède : la multiplicité des causes. Un contrat perdu a dix raisons, pas un seul coupable."},
{i:"s211_18",u:211,t:"story",d:.55,q:"Rappel du module 11 : Léa demande pourquoi le carnet marche mieux que ses résolutions de fer.",sc:[{who:"Léa",txt:"L'an dernier, je me forçais. Là, je comprends."}],o:["« La résolution commande l'affect ; le carnet le comprend et le remplace. »","« Les résolutions marchent mieux, le carnet n'est qu'un effet de mode passager. »","« Les deux ne marchent pas, seul le temps finit par tout régler de lui-même. »","« Le carnet marche parce que tu l'as payé cher, c'est un effet placebo. »"],a:0,w:"Ni éteindre, ni commander : remplacer. Comprendre est un affect joyeux plus fort que la passion."},
{i:"s211_19",u:211,t:"sort",d:.55,q:"Classe chaque maxime : préparée à la manière de Spinoza ou non ?",bins:["Maxime spinoziste","Non spinoziste"],it:[["Quand un client part, je liste toutes les causes avant de juger",0],["Quand j'échoue, je me traite d'incapable",1],["Quand je jalouse un concurrent, je cherche ce que j'admire chez lui",0],["Quand j'ai peur, je fais comme si de rien n'était",1]],w:"Une maxime spinoziste prépare la compréhension et la joie ; elle n'installe ni la honte ni le déni."},
{i:"s211_20",u:211,t:"tf",d:.6,q:"Pour Spinoza, les affects nés de la raison sont, à long terme, plus puissants que ceux qui naissent de causes absentes imaginées.",a:true,w:"E5P7. C'est le troisième remède, le temps : ce qui est compris dure. Le non-fumeur du module 12 en est l'exemple : ce qui est compris dure."},
{i:"s211_21",u:211,t:"multi",d:.6,q:"Quelles raisons imaginaires, selon Théo Lion, peuvent pousser un entrepreneur à désirer la gloire ?",o:["Prouver à d'anciens camarades qu'il a réussi","Se hisser au niveau des figures qu'il admire","Fuir l'angoisse de l'échec","Accumuler des signes visibles de réussite","Accroître vraiment sa puissance d'agir"],a:[0,1,2,3],w:"La dernière serait une vraie raison ; les quatre autres sont imaginaires. Les identifier transforme la tristesse."},
{i:"s211_22",u:211,t:"tiles",d:.65,q:"Reconstitue le moyen mnémotechnique des cinq remèdes.",a:["Comprendre","Sépare","Toujours","Mes","Obsessions"],dd:["Punir","Jamais","Cacher"],w:"Connaître, Séparer, Temps, Multiplier les causes, Ordonner."},
{i:"s211_23",u:211,t:"story",d:.65,q:"Victor perd son père. Léa veut lui parler de Spinoza. Julien la retient. Pourquoi ?",sc:[{who:"Léa",txt:"Je pourrais lui expliquer que comprendre allège la peine ?"}],o:["« Ce n'est pas magique : face à un deuil, être là, pas faire la leçon. »","« Il faut lui expliquer tout de suite, un deuil se règle par la philosophie. »","« Spinoza interdit de parler de la mort à ceux qui sont en deuil. »","« Victor est investisseur, il n'est donc pas concerné par ces questions. »"],a:0,w:"Théo Lion le dit : un stoïcien qui arrive en disant « contrôle ta réaction » n'est pas très humain. La méthode s'applique à soi, avec patience."},
{i:"s211_24",u:211,t:"mcq",d:.7,q:"Pourquoi comprendre la cause d'une tristesse produit-il de la joie ?",o:["Parce que comprendre accroît la puissance","Parce que la cause disparaît aussitôt du monde","Parce que la tristesse est interdite par la raison","Parce que l'on oublie aussitôt l'événement"],a:0,w:"La joie est le passage à une plus grande puissance. Comprendre, c'est pouvoir agir autrement : une joie active."},
{i:"s211_25",u:211,t:"fill",d:.7,q:"Selon E5P6, la tristesse d'un bien perdu diminue quand on voit qu'il ne pouvait pas être ___.",o:["conservé","vendu","remplacé","caché"],a:0,w:"Le scolie donne cet exemple : comprendre la nécessité d'une perte en allège la tristesse."},
{i:"s211_26",u:211,t:"story",d:.75,q:"Rappel du module 8 : Léa remplit son carnet et écrit « tristesse ». Julien lui demande d'être plus précise. Pourquoi ?",sc:[{who:"Léa",txt:"Tristesse, c'est déjà bien, non ?"}],o:["« Nommer l'affect exact, envie ou crainte, montre déjà l'idée liée. »","« Parce qu'il faut un mot plus long pour que le carnet soit bien rempli. »","« Parce que la tristesse n'existe pas chez Spinoza, seul le désir existe. »","« Parce qu'un affect précis est plus facile à cacher aux investisseurs. »"],a:0,w:"Premier remède : connaître les affects. L'envie, c'est tristesse plus idée du bonheur d'autrui ; la crainte, tristesse plus doute sur l'avenir."},
{i:"s211_27",u:211,t:"sort",d:.75,q:"Classe chaque étape : premier remède (connaître) ou deuxième (séparer) ?",bins:["Connaître","Séparer"],it:[["Nommer précisément l'affect",0],["Voir que « Marc le méchant » est une image",1],["Distinguer envie et émulation",0],["Détacher sa colère d'une seule personne",1]],w:"Connaître l'affect, puis le détacher de la cause extérieure confusément imaginée."},
{i:"s211_28",u:211,t:"match",d:.8,q:"Associe chaque personnage à son usage de la méthode.",p:[["Léa","Carnet sur le million"],["Anaïs","Séparer sa colère de Marc"],["Samir","Comprendre son examen raté"],["Victor","D'abord une présence, pas une leçon"]],w:"Une méthode, des situations très différentes, et une limite humaine."},
{i:"s211_29",u:211,t:"tf",d:.8,q:"Le carnet des affects en cinq colonnes est une méthode écrite par Spinoza lui-même.",a:false,w:"C'est une façon moderne d'appliquer ses remèdes (E5P20, scolie). Spinoza conseille de préparer des maximes, pas un carnet précis."},
{i:"s211_30",u:211,t:"mcq",d:.85,q:"Qu'est-ce qu'une « joie active » selon ce module ?",o:["Une joie née de notre compréhension","Une joie liée à un grand succès extérieur","Une joie ressentie pendant un effort sportif","Une joie qu'on simule devant les autres"],a:0,w:"Elle vient de nous, d'une idée adéquate. Contrairement à la passion joyeuse, elle ne dépend pas d'une cause extérieure."},
{i:"s211_31",u:211,t:"fill",d:.85,q:"Spinoza conseille de toujours regarder ce qu'il y a de ___ dans chaque chose, pour être déterminé à agir par la joie.",o:["bon","caché","coûteux","ancien"],a:0,w:"Scolie de E5P10. Une maxime qui oriente l'attention vers ce qui augmente la puissance."},
{i:"s211_32",u:211,t:"story",d:.9,q:"Synthèse : Léa affiche la méthode dans la salle de réunion. Quelle phrase choisit-elle ?",sc:[{who:"Léa",txt:"Une phrase pour toute l'équipe."}],o:["« Quand ça fait mal, on cherche les causes avant un coupable. »","« Quand ça fait mal, on serre les dents et on ne montre rien à personne. »","« Quand ça fait mal, on trouve vite le responsable et on le sanctionne. »","« Quand ça fait mal, on attend que ça passe tout seul, sans en parler. »"],a:0,w:"Passion comprise, passion transformée. Chercher les causes, nombreuses et nécessaires, dissout la haine et la honte."}
