/*UNIT*/
{id:212,c:"SPINO",n:"Module 14",t:"L'utile propre : ta boussole, et les autres comme alliés",col:"--purple",ic:"🧭",guide:`
<h3>Deux listes sur un tableau blanc</h3>
<div class="gstory">Un samedi matin, Léa et Anaïs s'enferment dans la salle de réunion avec deux feutres. Colonne de gauche : « Ce dont Cargo &amp; Co a besoin. » Colonne de droite : « Ce qui me rend vraiment vivante. » Léa aime dessiner les vélos, parler aux livreurs, recruter. Elle déteste le reporting, les tableaux financiers, les réunions avec le fonds. Anaïs, elle, adore les process. Elles se regardent et rient : les deux colonnes se complètent presque parfaitement. Julien, passé déposer des croissants, lit le tableau : « Théo Lion a fait exactement ça avec son associé Paul. Vous venez de trouver votre utile propre. Et de découvrir que rien n'est plus utile à l'homme que l'homme. »</div>
<h3>Vertu = puissance</h3>
<p>Spinoza redéfinit la vertu : « Par vertu et puissance, j'entends la même chose » (E4, définition 8). La vertu n'est pas l'obéissance à une règle morale, c'est la <b>puissance d'agir selon sa propre nature</b>. D'où E4P20 : plus chacun s'efforce de chercher son <b>utile propre</b> (<i>suum utile</i>), c'est-à-dire de conserver et d'augmenter son être, plus il est vertueux.</p>
<p>L'<b>utile propre</b>, c'est ce qui convient réellement à ta nature singulière et te permet de persévérer dans ton être. Ce n'est pas l'égoïsme au sens courant : c'est ce qui augmente <b>vraiment</b> ta puissance, pas ce qui flatte ton imagination.</p>
<div class="gmnemo"><b>« Pic ou plateau ? »</b> Le test de Théo Lion : on sait qu'on est dans son utile propre quand l'action n'est pas suivie d'un <b>pic</b> (puis d'une chute), mais d'une <b>joie stable</b>. Comme la différence entre un repas de fast-food et un repas sain. Et pour les autres : <b>« Mon utile bien compris veut aussi le tien. »</b></div>
<h3>Rien n'est plus utile à l'homme que l'homme</h3>
<ul><li><b>E4P18, scolie</b> : « Rien n'est plus utile à l'homme que l'homme. » Rien n'est plus profitable que de s'unir à d'autres dont la nature s'accorde avec la nôtre.</li>
<li><b>E4P35, scolie</b> : « L'homme est un Dieu pour l'homme », quand il vit sous la conduite de la raison (à l'opposé du « l'homme est un loup pour l'homme » de Plaute, repris par Hobbes).</li>
<li><b>E4P37</b> : le bien que désire pour lui-même celui qui suit la vertu, il le désire aussi pour les autres hommes.</li>
<li><b>E4P73</b> : l'homme guidé par la raison est plus libre dans la cité, sous des lois communes, que dans la solitude.</li></ul>
<p>Autrui est d'abord ce qui <b>menace</b> notre liberté (haine, envie, jalousie naissent presque toujours dans le rapport aux autres) ; mais, compris adéquatement, il devient le <b>vecteur le plus sûr</b> de notre libération. La béatitude n'est pas celle du moine isolé : c'est une joie qui s'amplifie dans la <b>concorde</b>.</p>
<h3>Les vertus de l'homme libre</h3>
<table><tr><th>Vertu ou thèse</th><th>Contenu</th></tr>
<tr><td><b>Fermeté</b> (animositas)</td><td>Désir de conserver son être sous la seule dictée de la raison</td></tr>
<tr><td><b>Générosité</b> (generositas)</td><td>Désir d'aider les autres et de se les lier d'amitié, sous la dictée de la raison</td></tr>
<tr><td>La haine vaincue par l'amour</td><td>On répond à la haine par l'amour ou la générosité (E4P46)</td></tr>
<tr><td>Ni humilité, ni repentir</td><td>Ce ne sont pas des vertus : ce sont des tristesses ; « qui se repent est deux fois misérable » (E4P54)</td></tr>
<tr><td>Méditation de la vie</td><td>« L'homme libre ne pense à rien moins qu'à la mort, et sa sagesse est une méditation non de la mort mais de la vie » (E4P67)</td></tr>
<tr><td>Bonne foi</td><td>L'homme libre n'agit jamais en trompeur (E4P72)</td></tr></table>
<h3>Rilke et le jeune poète</h3>
<p>Théo Lion cite les <i>Lettres à un jeune poète</i> de Rainer Maria Rilke, adressées à Franz Xaver Kappus : « Vous regardez vers l'extérieur, et c'est justement cela que vous devriez éviter. Rentrez en vous-même. » Et la question décisive : mourriez-vous s'il vous était défendu d'écrire ? Il suffit de sentir qu'on pourrait vivre sans écrire pour n'en avoir pas le droit. Appliqué à l'entreprise : déshabiller son désir d'entreprendre ; si, après examen, il ne reste rien qui vienne du dehors, ce désir est une <b>action</b>, et entreprendre est ton chemin vers la joie.</p>
<div class="gtrap">Nuance : chercher son utile propre peut sembler égoïste. Théo Lion le craignait (« je pensais que c'était égoïste »). Mais chez Spinoza, l'utile propre <b>bien compris</b> inclut l'utile des autres : un entrepreneur dans son utile propre rend son entreprise plus forte, pas plus faible. Et l'utile propre est toujours une <b>sagesse incertaine</b> : comme au poker, on se couche parfois sans avoir vu les cartes de l'adversaire, sans preuve qu'on aurait perdu.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Définir la vertu comme puissance et l'utile propre</li><li>Citer « rien n'est plus utile à l'homme que l'homme » et « l'homme est un Dieu pour l'homme »</li><li>Expliquer pourquoi l'humilité et le repentir ne sont pas des vertus</li><li>Appliquer le test « pic ou plateau » à une décision d'entrepreneur</li></ul>`},
/*EXOS*/
{i:"s212_01",u:212,t:"fill",d:.2,nw:"L'utile propre",q:"Spinoza écrit : « Par vertu et ___, j'entends la même chose. »",o:["puissance","obéissance","humilité","sagesse"],a:0,w:"E4, définition 8. La vertu n'est pas l'obéissance à une règle, c'est la puissance d'agir selon sa nature."},
{i:"s212_02",u:212,t:"story",d:.2,q:"Léa se sent coupable de vouloir confier le reporting à Anaïs. « C'est égoïste », dit-elle. Que répond Julien ?",sc:[{who:"Léa",txt:"Je devrais tout faire moi-même, non ?"}],o:["« Ton utile propre bien compris sert aussi la boîte et Anaïs. »","« Oui, c'est égoïste, un vrai chef doit tout faire lui-même, même ce qu'il déteste. »","« Donne tout le travail à Anaïs, ta seule mission est de te reposer. »","« Vends ta part, tu n'as visiblement rien à faire dans cette entreprise. »"],a:0,w:"C'est ce que Théo Lion a fait avec son associé Paul. Mon utile bien compris veut aussi le tien."},
{i:"s212_03",u:212,t:"tiles",d:.25,q:"Reconstitue la phrase de E4P18, scolie.",a:["rien","n'est","plus","utile","à","l'homme","que","l'homme"],dd:["argent","loup","Dieu"],w:"Homini nihil homine utilius. S'unir à ceux dont la nature s'accorde avec la nôtre."},
{i:"s212_04",u:212,t:"tf",d:.25,q:"Pour Spinoza, l'humilité est une vertu.",a:false,w:"E4P53 : ce n'est pas une vertu, c'est une tristesse. De même le repentir : qui se repent est deux fois misérable (E4P54)."},
{i:"s212_05",u:212,t:"match",d:.25,q:"Associe chaque formule à son sens.",p:[["Suum utile","L'utile propre"],["Homo homini Deus","L'homme est un Dieu pour l'homme"],["Animositas","La fermeté"],["Generositas","La générosité"]],w:"Fermeté et générosité forment la force d'âme de l'homme qui vit sous la conduite de la raison."},
{i:"s212_06",u:212,t:"mcq",d:.3,q:"Quel test Théo Lion propose-t-il pour savoir si l'on est dans son utile propre ?",o:["Une joie stable plutôt qu'un pic","Un gain d'argent immédiat","L'approbation de tous ses amis","Une fatigue intense le soir"],a:0,w:"Pic ou plateau ? Comme la différence entre un fast-food et un repas sain."},
{i:"s212_07",u:212,t:"sort",d:.3,q:"Classe chaque activité de Léa avec le test « pic ou plateau ».",bins:["Plateau (utile propre)","Pic (passion)"],it:[["Dessiner un nouveau vélo",0],["Voir son nom dans un classement",1],["Parler aux livreurs de leurs besoins",0],["Recevoir 500 likes sur LinkedIn",1],["Recruter quelqu'un qui grandit ensuite",0]],w:"Le plateau accompagne une puissance réelle ; le pic, une cause extérieure qui s'évanouit."},
{i:"s212_08",u:212,t:"story",d:.3,q:"Samir cite Hobbes : « L'homme est un loup pour l'homme, donc je ne fais confiance à personne ». Que répond Julien ?",sc:[{who:"Samir",txt:"En affaires, chacun pour soi."}],o:["« Pour Spinoza, l'homme guidé par la raison est un Dieu pour l'homme. »","« Spinoza est d'accord, il faut se méfier de tous et travailler seul. »","« Hobbes et Spinoza n'ont jamais parlé des rapports entre les hommes. »","« Il faut faire confiance à tout le monde sans exception, même aux escrocs. »"],a:0,w:"E4P35, scolie. Les passions opposent les hommes ; la raison les accorde."},
{i:"s212_09",u:212,t:"fill",d:.35,q:"Plus chacun cherche son ___ propre, plus il est doué de vertu (E4P20).",o:["utile","plaisir","argent","devoir"],a:0,w:"L'utile propre : ce qui conserve et augmente vraiment son être, pas ce qui flatte l'imagination."},
{i:"s212_10",u:212,t:"multi",d:.35,q:"Que fait Théo Lion quand il se recentre sur son utile propre ?",o:["Il confie les process à son associé Paul","Il coache de nouveaux fondateurs","Il produit du contenu","Il distingue ce qui est bien pour la boîte et pour lui","Il revend son entreprise au plus offrant"],a:[0,1,2,3],w:"Il cherche où les deux colonnes s'alignent. Il ne quitte pas son entreprise : il y trouve une autre place."},
{i:"s212_11",u:212,t:"story",d:.4,q:"Anaïs regrette amèrement une erreur de recrutement d'il y a deux ans. Que lui dit Julien, avec E4P54 ?",sc:[{who:"Anaïs",txt:"Je m'en veux encore, je n'arrête pas d'y penser."}],o:["« Le repentir ajoute une tristesse : comprends l'erreur, puis avance. »","« C'est bien de s'en vouloir longtemps, c'est une grande vertu morale. »","« Oublie tout, cette erreur n'a aucune cause et ne t'apprend rien. »","« Tu dois t'en vouloir encore deux ans pour être vraiment quitte. »"],a:0,w:"Qui se repent est deux fois misérable : une fois par l'acte, une fois par la tristesse. Comprendre les causes, c'est la joie qui permet d'agir autrement."},
{i:"s212_12",u:212,t:"tf",d:.4,q:"Pour Spinoza, l'homme guidé par la raison est plus libre dans la cité que dans la solitude.",a:true,w:"E4P73. Contre le cliché du sage isolé : la liberté s'épanouit dans la concorde."},
{i:"s212_13",u:212,t:"mcq",d:.45,q:"Quelle est, selon E4P67, la sagesse de l'homme libre ?",o:["Méditer la vie, pas la mort","Une préparation constante à la mort","Un mépris de la vie terrestre","Une indifférence totale à tout"],a:0,w:"L'homme libre ne pense à rien moins qu'à la mort : il pense à agir et à vivre."},
{i:"s212_14",u:212,t:"order",d:.45,q:"Remets dans l'ordre l'examen du désir d'entreprendre inspiré de Rilke.",it:["Arrêter de regarder vers l'extérieur","Rentrer en soi-même","Se demander si l'on pourrait vivre sans entreprendre","Retirer tout ce qui vient du dehors","Si rien ne reste d'extérieur, le désir est une action"],w:"Lettres à un jeune poète, appliquées par Théo Lion au désir d'entreprendre."},
{i:"s212_15",u:212,t:"story",d:.45,q:"Victor a humilié Anaïs en réunion. Elle veut se venger au prochain conseil. Que suggère Julien ?",sc:[{who:"Anaïs",txt:"Il va voir, je vais le ridiculiser devant tout le monde."}],o:["« La haine appelle la haine ; répondre par la générosité te rend plus forte. »","« Venge-toi, la haine est une vertu quand elle est bien méritée par l'autre. »","« Ne dis rien et rumine en silence pendant des mois, c'est plus digne. »","« Démissionne tout de suite, c'est la seule façon de garder ta fierté intacte. »"],a:0,w:"E4P46 : la haine vaincue par l'amour se change en amour. Ce n'est pas se soumettre : c'est la fermeté plus la générosité."},
{i:"s212_16",u:212,t:"match",d:.5,q:"Associe chaque proposition à son contenu.",p:[["E4P20","Plus on cherche son utile, plus on est vertueux"],["E4P37","Le bien voulu pour soi, voulu pour les autres"],["E4P54","Qui se repent est deux fois misérable"],["E4P67","Méditation de la vie, pas de la mort"]],w:"Les grandes thèses de la fin de la partie IV sur l'homme libre."},
{i:"s212_17",u:212,t:"fill",d:.5,q:"Le poète que cite Théo Lion, auteur des Lettres à un jeune poète, s'appelle Rainer Maria ___.",o:["Rilke","Kafka","Goethe","Hesse"],a:0,w:"Rilke écrit à Franz Xaver Kappus : rentrez en vous-même. Rilke écrit ces lettres entre 1903 et 1908."},
{i:"s212_18",u:212,t:"sort",d:.5,q:"Classe chaque affect selon Spinoza : vertu de l'homme libre ou tristesse ?",bins:["Vertu","Tristesse"],it:[["Fermeté",0],["Humilité",1],["Générosité",0],["Repentir",1],["Pitié chez l'homme de raison",1]],w:"Fermeté et générosité sont des désirs actifs ; humilité, repentir et pitié sont des tristesses (E4P50, 53, 54)."},
{i:"s212_19",u:212,t:"story",d:.55,q:"Rappel du module 9 : Samir demande comment distinguer son utile propre d'un désir imité.",sc:[{who:"Samir",txt:"Je veux faire du e-commerce comme mes potes. C'est mon utile propre ?"}],o:["« Si c'est un plateau et que tu le voudrais sans spectateurs, peut-être. »","« Oui, tout ce que font tes amis est forcément ton utile propre aussi. »","« Non, rien de ce que font les autres ne peut jamais être bon pour toi. »","« L'utile propre se décide à pile ou face, c'est le seul moyen honnête. »"],a:0,w:"Deux tests : pic ou plateau, et le voudrais-tu si personne ne le voyait. Un désir partagé peut être propre, s'il vient vraiment de toi."},
{i:"s212_20",u:212,t:"tf",d:.55,q:"Pour Spinoza, chercher son utile propre revient à nuire aux autres.",a:false,w:"E4P37 : le bien que l'homme vertueux désire pour lui, il le désire aussi pour les autres. L'utile propre bien compris est convergent."},
{i:"s212_21",u:212,t:"mcq",d:.6,q:"À quoi Théo Lion compare-t-il la sagesse de l'utile propre ?",o:["Au joueur de poker qui se couche","Au marin qui suit toujours les étoiles","Au banquier qui calcule chaque risque","Au soldat qui obéit aux ordres reçus"],a:0,w:"On n'a jamais la preuve formelle qu'on aurait perdu : suivre son utile propre demande une sagesse incertaine."},
{i:"s212_22",u:212,t:"multi",d:.6,q:"Pourquoi « rien n'est plus utile à l'homme que l'homme » ?",o:["S'unir multiplie la puissance","Ceux dont la nature s'accorde avec la nôtre nous renforcent","La cité protège la liberté","La raison accorde les hommes entre eux","Les autres nous délivrent de tout effort"],a:[0,1,2,3],w:"Les autres ne dispensent pas de l'effort : ils le multiplient. Comme Léa et Anaïs, dont les colonnes se complètent."},
{i:"s212_23",u:212,t:"story",d:.65,q:"Léa se demande si elle devrait « tout sacrifier » pour Cargo & Co, santé comprise. Qu'en dirait Spinoza ?",sc:[{who:"Léa",txt:"Les grands fondateurs sacrifient tout, non ?"}],o:["« Se détruire n'est jamais une vertu : la vertu, c'est accroître son être. »","« Oui, le sacrifice total est la plus haute forme de vertu chez Spinoza. »","« Il faut sacrifier la santé mais jamais le sommeil, c'est la règle. »","« Spinoza ne s'intéresse pas à la santé, seulement aux idées pures. »"],a:0,w:"Le fondement de la vertu est l'effort pour conserver son être (E4P18, scolie). Méditation de la vie, pas du sacrifice."},
{i:"s212_24",u:212,t:"fill",d:.65,q:"Spinoza dit que l'homme libre n'agit jamais en ___, mais toujours de bonne foi.",o:["trompeur","héros","solitaire","juge"],a:0,w:"E4P72. Même quand tromper paraîtrait utile : la bonne foi fait partie de l'utile propre bien compris."},
{i:"s212_25",u:212,t:"tiles",d:.7,q:"Reconstitue le test de Théo Lion.",a:["pic","ou","plateau"],dd:["pente","gouffre","sommet"],w:"Joie stable, ou montée suivie de chute ? Le plateau signale l'utile propre."},
{i:"s212_26",u:212,t:"story",d:.7,q:"Rappel du module 13 : Anaïs, jalouse d'une rivale promue, demande quoi faire. Quelle voie spinoziste proposes-tu ?",sc:[{who:"Anaïs",txt:"Je la déteste depuis qu'elle a eu ce poste."}],o:["« Cherche les causes de ta jalousie, puis ce que vous feriez ensemble. »","« Déteste-la ouvertement, c'est plus honnête que de faire semblant. »","« Fais tout pour qu'elle échoue, c'est ton utile propre de gagner. »","« Ignore tes émotions, elles n'ont rien à voir avec ton travail. »"],a:0,w:"Comprendre, puis convertir la rivalité en alliance : rien n'est plus utile à l'homme que l'homme."},
{i:"s212_27",u:212,t:"match",d:.75,q:"Associe chaque personnage à la découverte de son utile propre.",p:[["Léa","Dessiner, recruter, parler aux livreurs"],["Anaïs","Construire les process"],["Théo Lion","Coacher des fondateurs et partager des idées"],["Paul, l'associé de Théo","S'occuper de ce dont la boîte a besoin"]],w:"Deux colonnes qui se complètent : l'utile propre de chacun renforce l'œuvre commune."},
{i:"s212_28",u:212,t:"mcq",d:.75,q:"Pourquoi la pitié est-elle, chez l'homme qui vit sous la conduite de la raison, inutile selon E4P50 ?",o:["Il aide par raison, sans s'attrister","Il ne faut jamais aider personne, par principe","La souffrance des autres est toujours méritée","La pitié coûte bien trop d'argent"],a:0,w:"L'homme de raison aide par générosité, non par une tristesse partagée. Spinoza ajoute que pour qui n'est pas guidé par la raison, mieux vaut la pitié que l'indifférence."},
{i:"s212_29",u:212,t:"sort",d:.8,q:"Classe chaque phrase : fidèle à Spinoza ou contresens ?",bins:["Fidèle","Contresens"],it:[["L'utile propre bien compris inclut les autres",0],["La vertu, c'est obéir aux règles",1],["La béatitude se vit dans la concorde",0],["Le sage vit seul, loin des hommes",1]],w:"Vertu = puissance ; l'homme est un Dieu pour l'homme ; la joie s'amplifie à plusieurs."},
{i:"s212_30",u:212,t:"tf",d:.8,q:"Théo Lion pensait d'abord que se demander ce qui était bien pour lui, à la tête de sa boîte, était égoïste.",a:true,w:"« Je pensais que c'était égoïste, mais pas du tout. » Distinguer ce qui est bon pour la boîte et pour soi, puis chercher l'alignement."},
{i:"s212_31",u:212,t:"fill",d:.85,q:"La force d'âme spinoziste se compose de la fermeté et de la ___.",o:["générosité","prudence","patience","tempérance"],a:0,w:"Fermeté : se conserver par la raison. Générosité : aider les autres et se les lier d'amitié par la raison."},
{i:"s212_32",u:212,t:"story",d:.9,q:"Synthèse : Léa efface le tableau blanc en gardant une phrase. Laquelle ?",sc:[{who:"Léa",txt:"Une phrase pour ne pas oublier ce samedi."}],o:["« Chercher ce qui me rend puissante, et le vouloir pour les autres. »","« Tout faire soi-même, sans jamais rien déléguer, même ce qu'on déteste. »","« Se méfier de chacun, car l'homme est toujours un loup pour l'homme. »","« Suivre les objectifs du fonds, quoi qu'il en coûte à la santé. »"],a:0,w:"Pic ou plateau ? Mon utile bien compris veut aussi le tien. Rien n'est plus utile à l'homme que l'homme."}
