/*UNIT*/
{id:213,c:"SPINO",n:"Module 15",t:"La béatitude : une joie qui ne dépend plus de la chance",col:"--purple",ic:"✨",guide:`
<h3>Un an plus tard</h3>
<div class="gstory">Un an après la levée, un dimanche de septembre, Léa et Julien marchent sur la dune du Pilat. Cargo &amp; Co n'a pas atteint les 50 villes : elle en compte 12, et Léa a renégocié le plan avec le fonds. Anaïs dirige les opérations, Léa dessine les vélos et recrute. Elle a encore des jours tristes, des mails qui crispent, des envies de Ferrari. Mais quelque chose a changé : « Je ne suis plus suspendue aux chiffres. Quand ça va mal, je cherche pourquoi, et ça me calme. Et je me sens… d'accord avec moi. » Julien s'assoit dans le sable : « Spinoza a un mot pour ça. Il appelle ça la béatitude. Et il avait prévenu que c'est difficile. Et rare. »</div>
<h3>Le contentement de soi</h3>
<p>La première forme de cette joie stable, c'est l'<b>acquiescentia in se ipso</b>, le <b>contentement de soi</b> : une joie née de ce que l'homme se considère lui-même et sa puissance d'agir (E3, définition 25). Ce n'est pas de la complaisance narcissique : c'est la satisfaction profonde qui accompagne la conscience claire de ce qu'on peut <b>réellement</b>. Le contentement qui naît de la raison est le plus grand possible (E4P52), et celui qui naît du troisième genre de connaissance est le plus haut (E5P27).</p>
<h3>Voir les choses sous l'aspect de l'éternité</h3>
<p>Connaître par le troisième genre, c'est comprendre les choses <b>sous l'aspect de l'éternité</b> (<i>sub specie aeternitatis</i>) : non plus comme des événements qui passent dans le temps, mais comme des conséquences nécessaires de la Nature. Spinoza écrit même : « Nous sentons et nous expérimentons que nous sommes <b>éternels</b> » (E5P23, scolie). Attention : éternité ne veut pas dire durée infinie après la mort, mais une manière de se comprendre hors du temps.</p>
<h3>L'amour intellectuel de Dieu</h3>
<p>De ce troisième genre naît l'<b>amour intellectuel de Dieu</b> (<i>amor Dei intellectualis</i>, E5P32) : une joie accompagnée de l'idée de Dieu, c'est-à-dire de la Nature, comme cause. Cet amour n'attend rien en retour : « Qui aime Dieu ne peut s'efforcer que Dieu l'aime en retour » (E5P19). Il est même, dit Spinoza, l'amour dont Dieu s'aime lui-même (E5P36).</p>
<h3>La béatitude</h3>
<p>« Notre salut, autrement dit notre <b>béatitude</b>, autrement dit notre <b>liberté</b>, consiste dans un amour constant et éternel envers Dieu » (E5P36, scolie). Et la dernière proposition du livre (E5P42) : « La béatitude n'est pas la <b>récompense</b> de la vertu, mais la vertu elle-même ; et nous n'en jouissons pas parce que nous réprimons nos penchants, c'est au contraire parce que nous en jouissons que nous pouvons les réprimer. »</p>
<div class="gmnemo"><b>« La béatitude n'est pas le salaire, c'est le travail. »</b> Pas une récompense après l'effort : la joie même d'agir en comprenant. Et la dernière phrase du livre : <b>« Tout ce qui est beau est aussi difficile que rare »</b> (<i>omnia praeclara tam difficilia quam rara sunt</i>).</div>
<h3>Le sage et l'ignorant (E5P42, scolie)</h3>
<table><tr><th>L'ignorant</th><th>Le sage</th></tr>
<tr><td>Agité par les causes extérieures</td><td>Conscient de lui-même, de Dieu et des choses</td></tr>
<tr><td>Ne jouit jamais du vrai contentement</td><td>Possède le vrai contentement de l'âme</td></tr>
<tr><td>Dès qu'il cesse de pâtir, il cesse d'être</td><td>Ne cesse jamais d'être</td></tr></table>
<h3>La joie, cause du succès</h3>
<p>Théo Lion conclut par un renversement. La béatitude est une <b>action</b>, car elle repose sur la joie, qui est un accroissement de la puissance d'agir. Or l'entrepreneur qui produit une issue favorable use de sa capacité d'agir. Donc la joie n'est pas le <b>résultat</b> de l'action : il n'y a pas d'action sans joie. « La réussite évitera toujours celui qui croit qu'elle le rendra joyeux. » Il cite aussi le philosophe grec Plotin (« l'âme devient ce qu'elle contemple ») et imagine Spinoza dire : si je contemple des images de gloire, j'en deviens l'esclave. Si je contemple les causes réelles de mes affects, je renverse le rapport de force. Sa leçon finale est très simple : « Détends-toi. Rien de ce qui arrive n'est grave. » Et la vraie difficulté n'est pas de comprendre la béatitude, mais de la <b>désirer plus que le succès</b>.</p>
<div class="gtrap">Attention aux fausses citations. Les formules latines de la fin de la vidéo, « <i>Laetitia est causa successus exterioris</i> » (la joie est cause du succès extérieur) et la phrase sur l'utile propre dans l'entrepreneuriat qui mène « nécessairement à la béatitude », sont des <b>pastiches de Théo Lion</b>, écrits à la manière de Spinoza. Elles ne figurent pas dans l'<i>Éthique</i>. L'idée est défendable (un désir né de la joie est plus fort, E4P18), mais on ne les cite pas comme du Spinoza.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Définir le contentement de soi et l'amour intellectuel de Dieu</li><li>Expliquer sub specie aeternitatis sans le confondre avec l'immortalité</li><li>Citer et expliquer E5P42 et la dernière phrase de l'Éthique</li><li>Distinguer les vraies citations de Spinoza des pastiches de la vidéo</li></ul>`},
/*EXOS*/
{i:"s213_01",u:213,t:"story",d:.2,nw:"La béatitude",q:"Sur la dune, Léa dit qu'elle se sent « d'accord avec elle-même », même quand ça va mal. Comment Julien nomme-t-il ce début de joie stable ?",sc:[{who:"Léa",txt:"Je ne suis plus suspendue aux chiffres."}],o:["« Le contentement de soi, qui mène vers la béatitude. »","« L'orgueil, qui est la plus haute vertu chez Spinoza. »","« L'indifférence, qui protège de toute émotion. »","« La chance, qui finit toujours par tourner. »"],a:0,w:"Acquiescentia in se ipso : une joie née de la conscience claire de sa propre puissance d'agir."},
{i:"s213_02",u:213,t:"fill",d:.2,q:"E5P42 : la béatitude n'est pas la récompense de la vertu, mais la ___ elle-même.",o:["vertu","liberté","connaissance","richesse"],a:0,w:"La béatitude n'est pas le salaire, c'est le travail. Dernière proposition de l'Éthique."},
{i:"s213_03",u:213,t:"match",d:.25,q:"Associe chaque expression latine à sa traduction.",p:[["Acquiescentia in se ipso","Contentement de soi"],["Amor Dei intellectualis","Amour intellectuel de Dieu"],["Sub specie aeternitatis","Sous l'aspect de l'éternité"],["Omnia praeclara tam difficilia quam rara","Tout ce qui est beau est difficile autant que rare"]],w:"Quatre formules du sommet de l'Éthique. Elles résument le sommet de la partie V de l'Éthique."},
{i:"s213_04",u:213,t:"tf",d:.25,q:"Pour Spinoza, on jouit de la béatitude parce qu'on a d'abord réprimé ses penchants.",a:false,w:"C'est l'inverse : c'est parce que nous en jouissons que nous pouvons réprimer nos penchants (E5P42)."},
{i:"s213_05",u:213,t:"mcq",d:.3,q:"Quelle est la dernière phrase de l'Éthique ?",o:["Tout ce qui est beau est rare et difficile","Je pense, donc je suis, et Dieu existe","Dieu est mort, et nous l'avons tué","Deviens ce que tu es, sans attendre"],a:0,w:"Omnia praeclara tam difficilia quam rara sunt. Les autres sont de Descartes, Nietzsche et Pindare (repris par Nietzsche)."},
{i:"s213_06",u:213,t:"story",d:.3,q:"Samir cite la vidéo : « Laetitia est causa successus exterioris, c'est du Spinoza ». Que corrige Julien ?",sc:[{who:"Samir",txt:"C'est dans l'Éthique, non ?"}],o:["« C'est un pastiche de Théo Lion : l'idée se défend, pas la citation. »","« Oui, c'est la dernière phrase de l'Éthique, mot pour mot, en latin. »","« C'est une phrase de Descartes que Spinoza a recopiée dans son livre. »","« C'est une devise gravée sur la tombe de Spinoza à La Haye. »"],a:0,w:"La formule est de Théo Lion, écrite à la manière de Spinoza. Un bon spinoziste vérifie ses citations."},
{i:"s213_07",u:213,t:"sort",d:.3,q:"Classe chaque trait : du sage ou de l'ignorant, selon E5P42 scolie ?",bins:["Sage","Ignorant"],it:[["Agité par les causes extérieures",1],["Conscient de lui-même et des choses",0],["Ne jouit jamais du vrai contentement",1],["Ne cesse jamais d'être",0],["Cesse d'être dès qu'il cesse de pâtir",1]],w:"Le sage possède le vrai contentement ; l'ignorant vit presque inconscient de lui-même."},
{i:"s213_08",u:213,t:"tiles",d:.35,q:"Reconstitue le moyen mnémotechnique de E5P42.",a:["pas","le","salaire","c'est","le","travail"],dd:["prime","repos","dette"],w:"La béatitude n'est pas une récompense future : c'est la joie même d'agir en comprenant."},
{i:"s213_09",u:213,t:"fill",d:.35,q:"Spinoza écrit : « Nous sentons et nous expérimentons que nous sommes ___. »",o:["éternels","mortels","libres","immortels"],a:0,w:"E5P23, scolie. L'éternité n'est pas une durée infinie, mais une manière de se comprendre dans la nécessité de la Nature."},
{i:"s213_10",u:213,t:"multi",d:.4,q:"Qu'est-ce qui caractérise l'amour intellectuel de Dieu ?",o:["Il naît du troisième genre de connaissance","C'est une joie accompagnée de l'idée de Dieu comme cause","Il n'attend rien en retour","Il est constant, non fluctuant","Il réclame des sacrifices et des prières"],a:[0,1,2,3],w:"E5P32, E5P19, E5P36. Rien à voir avec un culte : c'est la joie de comprendre la Nature."},
{i:"s213_11",u:213,t:"story",d:.4,q:"Maud demande si « l'éternité » de Spinoza veut dire qu'il croyait au paradis.",sc:[{who:"Maud",txt:"Il croyait donc à la vie après la mort ?"}],o:["« Non : c'est comprendre les choses hors du temps, pas une vie après. »","« Oui, il décrit précisément le paradis et l'enfer dans la partie V. »","« Oui, il pensait que les riches vivraient éternellement grâce à leurs dons. »","« Non, il pensait que rien n'existe, même pas le présent qu'on vit. »"],a:0,w:"Sub specie aeternitatis : voir les choses comme des conséquences nécessaires de la Nature. L'éternité n'est pas une durée infinie."},
{i:"s213_12",u:213,t:"mcq",d:.45,q:"Selon E5P19, que ne peut pas faire celui qui aime Dieu ?",o:["S'efforcer que Dieu l'aime en retour","Comprendre la nature et ses lois","Éprouver une joie durable","Aimer les autres hommes, ses semblables"],a:0,w:"L'amour intellectuel de Dieu est sans marchandage : on ne demande rien à la Nature, on la comprend."},
{i:"s213_13",u:213,t:"tf",d:.45,q:"Le contentement de soi chez Spinoza est une forme de complaisance narcissique.",a:false,w:"C'est la satisfaction qui accompagne la conscience claire de ce que l'on peut réellement. Le narcissisme, lui, dépend du regard des autres."},
{i:"s213_14",u:213,t:"order",d:.5,q:"Remets dans l'ordre le chemin vers la béatitude tel que l'Éthique le décrit.",it:["Comprendre ses affects","Passer de l'imagination à la raison","Accéder au troisième genre de connaissance","Éprouver le contentement de soi","Aimer Dieu d'un amour intellectuel : la béatitude"],w:"Passion comprise, passion transformée, jusqu'à la joie la plus stable."},
{i:"s213_15",u:213,t:"story",d:.5,q:"Victor dit à Léa : « Une fois qu'on aura atteint 50 villes, tu seras enfin heureuse ». Qu'en pense Théo Lion ?",sc:[{who:"Victor",txt:"La joie, c'est pour après la réussite."}],o:["« C'est l'inverse : la joie est la condition de l'action. »","« Il a raison, la joie arrive toujours après le succès, jamais avant. »","« Il faut viser 100 villes pour être sûr d'être heureuse à la fin. »","« La joie et l'entreprise n'ont strictement aucun rapport entre elles. »"],a:0,w:"« La réussite évitera toujours celui qui croit qu'elle le rendra joyeux. » Il n'y a pas d'action sans joie."},
{i:"s213_16",u:213,t:"match",d:.55,q:"Associe chaque proposition à son contenu.",p:[["E5P27","Du troisième genre naît le plus grand contentement"],["E5P32","Du troisième genre naît l'amour intellectuel de Dieu"],["E5P36 scolie","Salut, béatitude, liberté : un amour constant envers Dieu"],["E5P42","La béatitude est la vertu elle-même"]],w:"La partie V culmine dans ces quatre propositions."},
{i:"s213_17",u:213,t:"fill",d:.55,q:"Théo Lion cite Plotin : « L'âme devient ce qu'elle ___. »",o:["contemple","désire","possède","redoute"],a:0,w:"Si je contemple des images de gloire, j'en deviens l'esclave ; si je contemple les causes de mes affects, je deviens plus libre."},
{i:"s213_18",u:213,t:"sort",d:.6,q:"Classe chaque citation : vraiment de Spinoza ou pastiche de la vidéo ?",bins:["Spinoza","Pastiche de la vidéo"],it:[["La béatitude est la vertu elle-même",0],["Laetitia est causa successus exterioris",1],["Tout ce qui est beau est difficile autant que rare",0],["L'utile propre dans l'entrepreneuriat mène nécessairement à la béatitude",1]],w:"Les pastiches de Théo Lion sont intéressants, mais ce ne sont pas des citations de l'Éthique."},
{i:"s213_19",u:213,t:"story",d:.6,q:"Léa a encore des jours tristes et se demande si elle a « raté » la béatitude.",sc:[{who:"Léa",txt:"Si j'étais vraiment sage, je ne serais plus jamais triste, non ?"}],o:["« La voie est difficile et rare : c'est un chemin, pas un état acquis. »","« Oui, un seul jour de tristesse prouve que tu as tout raté depuis le début. »","« La béatitude, c'est ne plus jamais rien ressentir, comme une pierre. »","« Recommence tout depuis le module 1 jusqu'à ce que tu ne sois plus triste. »"],a:0,w:"La dernière phrase de l'Éthique le dit : tout ce qui est beau est difficile autant que rare. On progresse, on ne coche pas une case."},
{i:"s213_20",u:213,t:"tf",d:.65,q:"Pour Spinoza, béatitude, salut et liberté désignent la même chose.",a:true,w:"E5P36, scolie : notre salut, autrement dit notre béatitude, autrement dit notre liberté."},
{i:"s213_21",u:213,t:"mcq",d:.65,q:"Pourquoi le bonheur, au sens étymologique, n'est-il pas la béatitude ?",o:["L'un dépend de la chance, l'autre de l'action","Le bonheur est éternel, la béatitude passagère","Le bonheur est réservé aux seuls sages","Ce sont deux mots pour une même chose"],a:0,w:"Bon heur = bonne fortune (module 1). La béatitude repose sur la connaissance et la joie active, pas sur le hasard."},
{i:"s213_22",u:213,t:"multi",d:.7,q:"Quelles leçons Théo Lion tire-t-il de son voyage sur les traces de Spinoza ?",o:["Détends-toi, rien de ce qui arrive n'est grave","Il n'y a pas d'action sans joie","Le plus dur est de désirer la béatitude plus que le succès","La réussite évite celui qui croit qu'elle le rendra joyeux","Il faut arrêter d'entreprendre pour être heureux"],a:[0,1,2,3],w:"Il continue d'entreprendre, autrement. La béatitude n'exige pas de renoncer à agir."},
{i:"s213_23",u:213,t:"story",d:.7,q:"Rappel du module 12 : Samir demande pourquoi seul le troisième genre mène à la béatitude.",sc:[{who:"Samir",txt:"La raison ne suffit pas ?"}],o:["« La raison réordonne ; l'intuition voit chaque chose dans la nécessité. »","« La raison suffit toujours, le troisième genre est une option pour les mystiques. »","« Le premier genre suffit, il suffit d'écouter ce qu'on dit autour de soi. »","« Aucun genre de connaissance ne mène à la béatitude, seule la chance y mène. »"],a:0,w:"E5P25 et E5P32 : du troisième genre naissent le plus grand contentement et l'amour intellectuel de Dieu."},
{i:"s213_24",u:213,t:"fill",d:.75,q:"Selon Théo Lion, le plus dur pour les entrepreneurs est de désirer la béatitude plus que le ___.",o:["succès","sommeil","repos","pouvoir"],a:0,w:"Comprendre comment la béatitude se crée est moins difficile que de la désirer vraiment plus que la réussite extérieure."},
{i:"s213_25",u:213,t:"tiles",d:.75,q:"Reconstitue la dernière phrase de l'Éthique (en français).",a:["tout","ce","qui","est","beau","est","difficile","autant","que","rare"],dd:["facile","riche","toujours"],w:"Omnia praeclara tam difficilia quam rara sunt."},
{i:"s213_26",u:213,t:"sort",d:.8,q:"Classe chaque joie : passion joyeuse fragile ou joie active durable ?",bins:["Passion joyeuse","Joie active"],it:[["Joie d'un article flatteur",0],["Joie de comprendre pourquoi on était triste",1],["Joie d'un classement dans un magazine",0],["Contentement de faire ce qu'on sait faire",1]],w:"La première dépend d'une cause extérieure ; la seconde naît de notre propre compréhension."},
{i:"s213_27",u:213,t:"story",d:.8,q:"Rappel du module 1 : Léa relit sa question de départ. Que peut-elle répondre maintenant ?",sc:[{who:"Léa",txt:"Pourquoi ma levée de fonds m'avait rendue vide ?"}],o:["« J'attendais la joie d'un succès extérieur ; elle vient de ma puissance. »","« Parce que je n'avais pas levé assez d'argent, il fallait dix millions. »","« Parce que la joie n'existe pas, et qu'il faut s'habituer au vide. »","« Parce que Victor n'était pas un bon investisseur, il fallait en changer. »"],a:0,w:"Le succès succède, la joie grandit. Le cours boucle la boucle : la béatitude ne se lève pas, elle se construit. Plotin : l'âme devient ce qu'elle contemple ; Léa contemple désormais ses causes."},
{i:"s213_28",u:213,t:"mcq",d:.85,q:"Que devient l'ignorant, selon Spinoza, dès qu'il cesse de pâtir ?",o:["Il cesse d'être","Il devient sage","Il devient riche","Il devient éternel"],a:0,w:"Il n'existait que par les causes extérieures qui l'agitaient. Le sage, lui, ne cesse jamais d'être."},
{i:"s213_29",u:213,t:"match",d:.85,q:"Associe chaque personnage à la forme de joie qu'il découvre.",p:[["Léa","Contentement d'agir selon sa nature"],["Théo Lion","Joie d'explorer et de partager des idées"],["Zoé et l'orage","Calme né de la compréhension d'une cause"],["L'oncle non-fumeur","Paix où le désir nuisible n'attire plus"]],w:"Des formes différentes d'une même joie active, qui ne dépend pas de la chance. Le non-fumeur ne lutte plus : il ne désire plus."},
{i:"s213_30",u:213,t:"tf",d:.9,q:"Selon Théo Lion, la béatitude est une action, puisqu'elle repose sur la joie, accroissement de la puissance d'agir.",a:true,w:"C'est son renversement final : la joie n'est pas le produit du succès, c'est la condition de l'action qui le produit."},
{i:"s213_31",u:213,t:"fill",d:.9,q:"Pour Spinoza, l'amour intellectuel de l'esprit envers Dieu est l'amour même dont Dieu s'aime ___.",o:["lui-même","les hommes","le monde","les sages"],a:0,w:"E5P36. En comprenant la Nature, l'esprit participe à la puissance même de la Nature."},
{i:"s213_32",u:213,t:"story",d:.95,q:"Synthèse : sur la dune, Julien résume la partie V en une phrase. Laquelle ?",sc:[{who:"Léa",txt:"Et si tu devais tout dire en une phrase ?"}],o:["« Comprendre donne une joie qui ne dépend plus de la chance. »","« Réussir d'abord, puis la joie viendra comme une récompense bien méritée. »","« Renoncer à tout désir pour ne plus jamais souffrir de rien. »","« Prier la Nature chaque jour pour qu'elle nous accorde le succès. »"],a:0,w:"La béatitude n'est pas le salaire, c'est le travail. Tout ce qui est beau est aussi difficile que rare. Plotin disait que l'âme devient ce qu'elle contemple."}
