/*UNIT*/
{id:247,c:"FISCA",n:"Module 1",t:"VEFA : réserver un appartement sur plan sans se faire piéger",col:"--orange",ic:"🏗️",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Définir la <b>VEFA</b> et dire ce que le constructeur promet.</li>
<li>Lister les mentions du <b>contrat de réservation</b>.</li>
<li>Appliquer le <b>délai de rétractation de 10 jours</b>.</li>
<li>Calculer le <b>dépôt de garantie</b> maximum selon le délai avant la vente.</li>
<li>Reconnaître les <b>cinq cas de restitution</b> du dépôt.</li></ul>
<h3>Ton premier dossier au cabinet</h3>
<div class="gstory">Lille, rue Esquermoise. Tu commences comme conseiller au cabinet <b>Beffroi Patrimoine</b>. Ta patronne, <b>Nathalie Wattel</b>, te tend un dossier : « Camille et Yanis Benali, 31 et 33 ans, pacsés. Ils veulent réserver un T3 sur plan à Fives, résidence Les Jardins de Fives, 250 000 euros. Ils signent jeudi. Tu relis tout. » Derrière toi, <b>Théo</b>, le stagiaire, murmure : « Sur plan ? Donc ils achètent un terrain vague ? » Pas tout à fait, Théo.</div>
<p>Tu retrouveras ces personnes tout le long du cours. Les <b>Benali</b> (premier achat sur plan, PTZ). <b>Philippe Vandamme</b>, 52 ans, cadre, qui prépare sa retraite avec l'immobilier locatif. <b>Sandrine Duhamel</b>, kiné à Roubaix, 120 000 euros à placer. La famille <b>Carpentier</b> et sa SCI. <b>Jeanne Petit et Robert Masson</b>, concubins. <b>Madeleine Caron</b>, 79 ans, qui pense au viager. Chaque règle sera accrochée à l'un d'eux.</p>
<h3>La VEFA, c'est quoi ?</h3>
<p>La <b>vente en l'état futur d'achèvement</b> (VEFA) est la vente d'un logement <b>sur plan</b>. Au jour de la signature, il n'y a souvent qu'un <b>terrain nu</b>. Le promoteur promet que l'immeuble sera construit et <b>achevé</b>.</p>
<ul><li>Le vendeur s'engage à <b>achever</b> l'immeuble et à le livrer conforme.</li>
<li>L'acheteur paie <b>au fur et à mesure des travaux</b>, par des <b>appels de fonds</b>.</li>
<li>L'acheteur devient propriétaire du sol tout de suite, puis des constructions au fur et à mesure qu'elles sortent de terre.</li></ul>
<div class="gmnemo">Retiens l'image du <b>gâteau payé tranche par tranche</b>. Tu commandes un gâteau de mariage. Tu paies une part quand la base est cuite, une autre quand l'étage est posé, le reste quand il est décoré. Tu ne paies jamais un gâteau qui n'existe pas encore.</div>
<h3>Le contrat de réservation</h3>
<p>Avant l'acte chez le notaire, les parties signent en général un <b>contrat de réservation</b>, aussi appelé <b>contrat préliminaire</b>. Le promoteur réserve le lot, l'acheteur verse un dépôt de garantie.</p>
<table><tr><th>Mention obligatoire</th><th>Exemple chez les Benali</th></tr>
<tr><td><b>Surface habitable approximative</b> et nombre de pièces</td><td>T3 d'environ 64 m²</td></tr>
<tr><td>Situation du logement dans l'immeuble</td><td>2e étage, lot 21</td></tr>
<tr><td>Qualité de la construction (note technique)</td><td>Parquet, double vitrage</td></tr>
<tr><td><b>Prix prévisionnel</b> et règles de révision</td><td>250 000 euros</td></tr>
<tr><td>Date prévue de signature de l'acte</td><td>Dans 10 mois</td></tr>
<tr><td>Prêts que l'acheteur compte obtenir</td><td>200 000 euros, dont un PTZ</td></tr></table>
<div class="gtrap">Les notes disent que ce contrat est <b>obligatoire</b>. En droit, la loi dit que la vente <b>peut</b> être précédée d'un contrat préliminaire. En pratique, il est presque toujours signé. S'il est signé, ses <b>mentions</b> sont obligatoires.</div>
<h3>Le délai de rétractation : 10 jours</h3>
<p>L'acheteur particulier peut changer d'avis <b>sans motif</b> et sans frais pendant <b>10 jours</b>. Le délai part du <b>lendemain</b> de la première présentation de la lettre recommandée qui lui notifie le contrat signé.</p>
<div class="gtrap">Les notes indiquent <b>7 jours</b>. C'était la règle avant la <b>loi Macron du 6 août 2015</b>. Depuis, le délai est de <b>10 jours</b> (article L271-1 du Code de la construction et de l'habitation, vérifié en septembre 2026).</div>
<h3>Le dépôt de garantie : 5 %, 2 % ou rien</h3>
<p>Le dépôt réserve l'appartement. Son plafond dépend du <b>délai avant la signature de l'acte de vente</b>.</p>
<table><tr><th>Signature de l'acte prévue</th><th>Dépôt maximum</th></tr>
<tr><td>Dans moins d'un an</td><td><b>5 %</b> du prix prévisionnel</td></tr>
<tr><td>Entre un et deux ans</td><td><b>2 %</b></td></tr>
<tr><td>Au-delà de deux ans</td><td><b>Aucun dépôt</b></td></tr></table>
<div class="formula">Benali : acte dans 10 mois, prix 250 000 €
Dépôt maximum = 5 % x 250 000 = 12 500 €</div>
<p>Le dépôt est versé sur un <b>compte spécial</b> ouvert au nom de l'acheteur (banque ou notaire). Il est <b>indisponible</b>, <b>incessible</b> et <b>insaisissable</b>. Le promoteur ne peut pas y toucher.</p>
<div class="gmnemo">« <b>5 dans l'an, 2 dans les deux, rien au-delà</b> ». Plus l'attente est longue, plus le dépôt est petit : on ne bloque pas l'argent des gens pendant des années.</div>
<div class="gtrap">Les notes inversent la règle : « travaux à plus de 2 ans, 5 % ; moins de 2 ans, 2 % ». C'est faux. Le plafond <b>baisse</b> quand le délai s'allonge, et il ne se calcule pas sur la durée des travaux mais sur le délai avant la <b>signature de l'acte</b> (article R261-28).</div>
<h3>Les cinq cas où l'acheteur récupère son dépôt</h3>
<p>Hors rétractation, le dépôt est rendu <b>sans retenue</b> dans cinq cas (article R261-31). L'acheteur le demande par lettre recommandée. Le remboursement intervient dans les <b>trois mois</b>.</p>
<table><tr><th>Cas</th><th>Exemple</th></tr>
<tr><td>La vente n'est pas signée <b>du fait du vendeur</b></td><td>Le terrain se révèle inconstructible, le chantier s'arrête</td></tr>
<tr><td>Le <b>prix</b> final dépasse de <b>plus de 5 %</b> le prix prévisionnel</td><td>263 000 € au lieu de 250 000 € (+5,2 %)</td></tr>
<tr><td>Les <b>prêts</b> obtenus sont inférieurs de <b>plus de 10 %</b> aux prévisions</td><td>175 000 € au lieu de 200 000 €</td></tr>
<tr><td>Un <b>élément d'équipement</b> prévu ne sera pas réalisé</td><td>Le parking en sous-sol promis est abandonné</td></tr>
<tr><td>Le logement perd <b>plus de 10 %</b> de sa valeur prévue</td><td>Surface ou qualité nettement réduite</td></tr></table>
<div class="gmnemo">Les <b>5 P</b> de la sortie : <b>P</b>romoteur (la vente échoue de son fait), <b>P</b>rix (+5 %), <b>P</b>rêt (-10 %), <b>P</b>ièce manquante (équipement), <b>P</b>erte de valeur (-10 %). Un seul P suffit pour récupérer l'argent.</div>
<div class="gtrap">Les notes disent « l'acheteur n'obtient pas son prêt ». La règle exacte est plus large : il suffit que les prêts obtenus soient <b>inférieurs de plus de 10 %</b> au montant prévu dans le contrat. Les notes parlent aussi d'une surface « à plus ou moins 10 % ». La loi parle seulement d'une surface <b>approximative</b>. Le seuil de 10 % vise la <b>perte de valeur</b> du logement.</div>
<h3>Ce que tu dois retenir pour l'examen</h3>
<ul><li>VEFA : vente sur plan, paiement par appels de fonds, vendeur tenu d'achever.</li>
<li>Rétractation : 10 jours, sans motif.</li>
<li>Dépôt : 5 % sous un an, 2 % entre un et deux ans, zéro au-delà, sur un compte bloqué.</li>
<li>Restitution : les 5 P, remboursement sous trois mois.</li></ul>`},
/*EXOS*/
{i:"f247_01",u:247,t:"mcq",d:.2,nw:"La VEFA",q:"Que signifie le sigle VEFA ?",o:["Vente en l'état futur d'achèvement","Vente en état fini d'aménagement","Versement en échéances fixes d'achat","Vente d'un espace foncier aménageable"],a:0,w:"Vente en l'état futur d'achèvement : on achète un logement qui n'existe pas encore, le promoteur s'engage à l'achever. Image du gâteau payé tranche par tranche."},
{i:"f247_02",u:247,t:"story",d:.3,q:"Que réponds-tu à Théo ?",sc:[{who:"Théo",txt:"Si les Benali achètent sur plan, ils achètent un terrain vague et ils espèrent qu'on construira dessus, c'est ça ?"},{who:"Toi",me:true,txt:"Pas tout à fait."}],o:["Ils achètent un logement futur : le vendeur s'engage à achever l'immeuble","Oui, et ils devront ensuite trouver eux-mêmes une entreprise pour bâtir","Ils louent le terrain au promoteur jusqu'à ce que l'immeuble soit fini","Ils prêtent de l'argent au promoteur, qui leur rendra plus tard un logement"],a:0,w:"En VEFA, l'acheteur achète le logement à construire. Le vendeur a l'obligation d'achever. L'acheteur paie par appels de fonds au fil des travaux."},
{i:"f247_03",u:247,t:"tf",d:.25,q:"En VEFA, l'acheteur paie tout le prix le jour où il signe chez le notaire.",a:false,w:"Il paie au fur et à mesure de l'avancement des travaux, par appels de fonds. On ne paie jamais un gâteau qui n'existe pas encore."},
{i:"f247_04",u:247,t:"multi",d:.3,q:"Quelles affirmations décrivent bien la VEFA ?",o:["Le vendeur s'engage à achever l'immeuble","L'acheteur règle des appels de fonds au fil du chantier","Le logement n'existe souvent pas encore à la signature","L'acheteur supporte seul le risque d'abandon du chantier"],a:[0,1,2],w:"Achèvement promis, paiement échelonné, logement futur. Le risque d'abandon est justement couvert par la garantie d'achèvement (module 2)."},
{i:"f247_05",u:247,t:"multi",d:.35,nw:"Le contrat de réservation",q:"Quelles mentions doivent figurer dans le contrat de réservation des Benali ?",o:["La surface habitable approximative","Le prix prévisionnel et sa révision","La date prévue de l'acte de vente","Le nom du futur syndic de copropriété","Les prêts que les Benali comptent obtenir"],a:[0,1,2,4],w:"Surface approximative, pièces, situation, qualité, prix prévisionnel, date de l'acte, prêts envisagés. Le syndic n'est pas une mention du contrat préliminaire."},
{i:"f247_06",u:247,t:"fill",d:.3,q:"Le contrat de réservation est aussi appelé contrat ___.",o:["préliminaire","définitif","d'entreprise","de promotion"],a:0,w:"Contrat préliminaire, ou contrat de réservation : il précède l'acte définitif signé chez le notaire."},
{i:"f247_07",u:247,t:"story",d:.35,q:"Que réponds-tu à Yanis ?",sc:[{who:"Yanis Benali",txt:"Le vendeur m'a dit que ce contrat de réservation était obligatoire par la loi, sinon pas de vente."},{who:"Camille Benali",txt:"Du coup on signe sans lire, de toute façon on n'a pas le choix."}],o:["La loi le rend facultatif, mais s'il est signé ses mentions sont obligatoires","Il est obligatoire, et son contenu est libre : chaque promoteur écrit le sien","Il est facultatif et n'a aucune valeur juridique pour l'un ou l'autre camp","Il est obligatoire, et il remplace l'acte notarié que l'on ne signe plus"],a:0,w:"La vente peut être précédée d'un contrat préliminaire. En pratique il est quasi systématique, et ses mentions sont imposées. On le lit toujours."},
{i:"f247_08",u:247,t:"sort",d:.35,q:"Classe chaque élément selon le document où il apparaît d'abord.",bins:["Contrat de réservation","Acte définitif chez le notaire"],it:[["Surface habitable approximative",0],["Prix prévisionnel",0],["Désignation précise du lot",1],["Garantie financière d'achèvement",1],["Prêts envisagés par l'acheteur",0],["Délai de livraison ferme",1]],w:"La réservation donne les grandes lignes (surface approximative, prix prévisionnel, prêts envisagés). L'acte définitif précise le lot, le délai de livraison et la garantie d'achèvement (module 2)."},
{i:"f247_09",u:247,t:"slider",d:.3,nw:"Le délai de rétractation",q:"De combien de jours dispose un acheteur particulier pour se rétracter après la notification du contrat de réservation ?",min:3,max:15,step:1,a:10,tol:0,pre:"",un:" jours",w:"Dix jours depuis la loi Macron de 2015. Les notes disent 7 jours : c'est l'ancienne règle."},
{i:"f247_10",u:247,t:"tf",d:.3,q:"Pour se rétracter dans le délai, l'acheteur doit donner un motif sérieux.",a:false,w:"La rétractation se fait sans motif et sans frais. Il suffit d'une lettre recommandée dans les 10 jours."},
{i:"f247_11",u:247,t:"story",d:.4,q:"Que dis-tu à Camille ?",ctx:"Le contrat de réservation signé a été présenté aux Benali par lettre recommandée le lundi 5 octobre.",sc:[{who:"Camille Benali",txt:"Mes parents trouvent qu'on s'emballe. On a jusqu'à quand pour tout annuler sans frais ?"}],o:["Jusqu'au jeudi 15 octobre, le délai part du lendemain de la présentation","Jusqu'au lundi 12 octobre, soit sept jours après la présentation du courrier","Il est trop tard, la rétractation joue avant la signature seulement","Jusqu'à l'acte chez le notaire, vous pouvez partir quand vous voulez"],a:0,w:"Le délai de 10 jours part du lendemain de la première présentation : du 6 au 15 octobre. Après, sortir sans frais suppose un des 5 P."},
{i:"f247_12",u:247,t:"mcq",d:.35,q:"Quelle loi a porté le délai de rétractation de 7 à 10 jours ?",o:["La loi Macron de 2015","La loi ALUR du 24 mars 2014","La loi ELAN de 2018","La loi Pinel de 2014"],a:0,w:"La loi Macron du 6 août 2015. ALUR (2014) concerne surtout la location et l'encadrement des loyers, vus au module 12."},
{i:"f247_13",u:247,t:"slider",d:.35,nw:"Le dépôt de garantie",q:"L'acte des Benali est prévu dans 10 mois. Quel est le dépôt de garantie maximum, en pourcentage du prix ?",min:0,max:10,step:1,a:5,tol:0,pre:"",un:" %",w:"Signature dans moins d'un an : 5 % maximum. 5 dans l'an, 2 dans les deux, rien au-delà."},
{i:"f247_14",u:247,t:"num",d:.4,q:"Prix prévisionnel 250 000 €, acte prévu dans 10 mois. Quel dépôt de garantie maximum le promoteur peut-il demander, en euros ?",a:12500,tol:1,un:" €",h:"Moins d'un an avant l'acte",w:"5 % x 250 000 = 12 500 €. Au-delà, le promoteur viole l'article R261-28."},
{i:"f247_15",u:247,t:"num",d:.45,q:"Même appartement à 250 000 €, mais l'acte est prévu dans 18 mois. Dépôt maximum, en euros ?",a:5000,tol:1,un:" €",h:"Entre un et deux ans",w:"Entre un et deux ans : 2 %. 2 % x 250 000 = 5 000 €."},
{i:"f247_16",u:247,t:"story",d:.45,q:"Que réponds-tu au promoteur ?",sc:[{who:"Commercial du promoteur",txt:"L'acte ne sera signé que dans trente mois, le permis n'est pas purgé. Je demande quand même 2 % de dépôt pour bloquer le lot."}],o:["Au-delà de deux ans avant l'acte, aucun dépôt ne peut être exigé","C'est correct, 2 % reste le plafond dès que le délai dépasse un an","Il peut même demander 5 %, puisque le chantier sera long","C'est correct si le dépôt est versé sur votre compte professionnel"],a:0,w:"Au-delà de deux ans : aucun dépôt. Les notes inversent la règle en liant 5 % aux travaux longs. C'est l'inverse : plus on attend, moins on bloque."},
{i:"f247_17",u:247,t:"multi",d:.4,q:"Où et comment le dépôt de garantie est-il conservé ?",o:["Sur un compte spécial au nom de l'acheteur","Il est indisponible jusqu'à la vente","Il est insaisissable par les créanciers","Il finance les premiers travaux","Il est versé sur le compte du promoteur"],a:[0,1,2],w:"Compte spécial, indisponible, incessible, insaisissable. Personne ne peut y toucher, et surtout pas le promoteur pour financer le chantier."},
{i:"f247_18",u:247,t:"tiles",d:.4,q:"Reconstitue la formule mémo du dépôt de garantie.",a:["5","dans","l'an,","2","dans","les","deux,","rien","au-delà"],dd:["10","trois","mois"],w:"5 % si l'acte est prévu dans l'année, 2 % entre un et deux ans, aucun dépôt au-delà."},
{i:"f247_19",u:247,t:"fill",d:.35,q:"Le plafond du dépôt de garantie dépend du délai avant la signature de l'___.",o:["acte de vente","ouverture du chantier","obtention du prêt","livraison des clés"],a:0,w:"C'est le délai avant l'acte de vente qui compte, pas la durée des travaux. C'est l'erreur des notes."},
{i:"f247_20",u:247,t:"match",d:.4,q:"Associe chaque délai avant l'acte au dépôt maximum.",p:[["8 mois","5 %"],["15 mois","2 %"],["26 mois","Aucun dépôt"],["23 mois","2 %, jusqu'à deux ans"]],w:"Moins d'un an : 5 %. D'un à deux ans : 2 %. Plus de deux ans : rien."},
{i:"f247_21",u:247,t:"sort",d:.45,nw:"Les cinq cas de restitution",q:"Dans quels cas les Benali récupèrent-ils leur dépôt sans retenue ?",bins:["Restitution","Pas de restitution"],it:[["Le prix passe de 250 000 à 264 000 €",0],["Le prix passe de 250 000 à 259 000 €",1],["Le prêt obtenu est de 170 000 € au lieu de 200 000 €",0],["Le parking souterrain promis est abandonné",0],["Ils trouvent un appartement moins cher ailleurs après 10 jours",1],["Le chantier ne démarre pas par la faute du promoteur",0]],w:"Les 5 P : Promoteur, Prix au-delà de +5 %, Prêt en baisse de plus de 10 %, Pièce d'équipement abandonnée, Perte de valeur de plus de 10 %. 259 000 € fait +3,6 % seulement."},
{i:"f247_22",u:247,t:"num",d:.45,q:"Prix prévisionnel 250 000 €. Au-delà de quel prix final, en euros, les Benali peuvent-ils récupérer leur dépôt ?",a:262500,tol:1,un:" €",h:"Plus de 5 %",w:"250 000 x 1,05 = 262 500 €. Il faut dépasser de plus de 5 % le prix prévisionnel."},
{i:"f247_23",u:247,t:"story",d:.5,q:"Que conseilles-tu aux Benali ?",ctx:"Le contrat prévoyait 200 000 € de prêts. La banque n'accorde que 184 000 €. Les Benali veulent renoncer.",sc:[{who:"Yanis Benali",txt:"La banque nous prête moins que prévu. Si on renonce, on perd nos 12 500 euros ?"}],o:["Non si la baisse dépasse 10 %. Ici elle est de 8 %, le dépôt n'est pas rendu d'office","Oui, le prêt n'est jamais un motif pour récupérer un dépôt de garantie","Non, toute baisse de prêt, même légère, oblige à rendre le dépôt","Non, puisqu'ils ont obtenu un prêt : les notes parlent seulement d'un refus"],a:0,w:"184 000 sur 200 000 : baisse de 8 %, sous le seuil de 10 %. La règle exacte est plus large que les notes (pas besoin d'un refus total), mais il faut dépasser 10 %."},
{i:"f247_24",u:247,t:"tiles",d:.45,q:"Reconstitue les cinq P de la restitution du dépôt.",a:["Promoteur,","Prix,","Prêt,","Pièce,","Perte"],dd:["Plan,","Permis,","Paiement,"],w:"Promoteur (la vente échoue de son fait), Prix (+5 %), Prêt (-10 %), Pièce manquante (équipement), Perte de valeur (-10 %)."},
{i:"f247_25",u:247,t:"slider",d:.4,q:"En cas de restitution, dans quel délai maximum le dépôt doit-il être remboursé ?",min:1,max:12,step:1,a:3,tol:0,pre:"",un:" mois",w:"Trois mois à compter de la demande faite par lettre recommandée."},
{i:"f247_26",u:247,t:"story",d:.5,q:"Quelle est ta réponse ?",sc:[{who:"Camille Benali",txt:"On nous avait promis un garage en sous-sol. Le promoteur annonce qu'il est abandonné à cause de la nappe phréatique. Il propose une place aérienne."},{who:"Yanis Benali",txt:"On préfère annuler et récupérer notre dépôt."}],o:["C'est possible : un équipement prévu ne sera pas réalisé, dépôt rendu sans retenue","Impossible : l'abandon vient du sol et non du promoteur, vous perdez le dépôt","Possible seulement si le prix final augmente aussi de plus de 5 % en même temps","Possible, mais le promoteur garde la moitié du dépôt à titre de frais"],a:0,w:"C'est le P de la Pièce manquante : un élément d'équipement prévu ne sera pas réalisé. C'est l'exemple du garage de Lille dans les notes."},
{i:"f247_27",u:247,t:"tf",d:.4,q:"Si le logement perd plus de 10 % de la valeur prévue, l'acheteur peut récupérer son dépôt.",a:true,w:"Perte de valeur de plus de 10 % : c'est le cinquième P. C'est là que joue le seuil de 10 %, pas sur la surface."},
{i:"f247_28",u:247,t:"mcq",d:.45,q:"Les notes parlent d'une surface « à plus ou moins 10 % ». Que dit exactement la loi pour le contrat de réservation ?",o:["Elle exige une surface habitable approximative","Elle impose une tolérance de 10 % sur la surface","Elle interdit toute différence de surface","Elle ne parle pas de la surface du logement"],a:0,w:"Le contrat de réservation indique une surface approximative. Le seuil légal de 10 % concerne la perte de valeur du logement."},
{i:"f247_29",u:247,t:"order",d:.4,q:"Remets dans l'ordre le début d'un achat en VEFA.",it:["Choix du lot sur plan","Signature du contrat de réservation","Versement du dépôt sur un compte bloqué","Fin du délai de rétractation de 10 jours","Signature de l'acte chez le notaire"],w:"On choisit, on réserve, on dépose la garantie, le délai de 10 jours s'écoule, puis on signe l'acte définitif (module 2)."},
{i:"f247_30",u:247,t:"match",d:.45,q:"Associe chaque chiffre à sa règle.",p:[["10 jours","Rétractation"],["5 %","Dépassement de prix toléré"],["10 %","Baisse de prêt ouvrant la restitution"],["3 mois","Remboursement du dépôt"]],w:"10 jours pour se rétracter, +5 % de prix toléré, -10 % de prêt, 3 mois pour rembourser."},
{i:"f247_31",u:247,t:"mcq",d:.5,q:"Théo résume : « Le dépôt est de 5 % si les travaux durent plus de deux ans. » Quelle est la bonne correction ?",o:["5 % si l'acte est prévu dans l'année, 2 % entre un et deux ans","5 % dans tous les cas, quelle que soit la durée des travaux","2 % si l'acte est prévu dans l'année, 5 % au-delà","10 % si l'acte est prévu dans l'année, 5 % au-delà"],a:0,w:"Le plafond baisse quand l'attente s'allonge, et il se mesure au délai avant l'acte, pas à la durée des travaux."},
{i:"f247_32",u:247,t:"story",d:.55,q:"Synthèse : quel conseil donnes-tu aux Benali avant jeudi ?",sc:[{who:"Nathalie Wattel",txt:"Résume-leur en une phrase ce qui les protège."}],o:["« Dix jours pour réfléchir, un dépôt de 5 % au plus, bloqué et rendu dans cinq cas »","« Signez vite, car le dépôt est encaissé tout de suite par le promoteur, sans retour »","« Aucun délai de réflexion, mais le promoteur doit rendre le dépôt si vous changez d'avis »","« Sept jours pour se rétracter et un dépôt libre, fixé par le promoteur selon le chantier »"],a:0,w:"10 jours de rétractation, 5 % maximum ici (acte dans 10 mois), compte bloqué, et les 5 P pour récupérer le dépôt."}
