/*UNIT*/
{id:248,c:"FISCA",n:"Module 2",t:"VEFA : l'acte chez le notaire, les appels de fonds et les garanties",col:"--orange",ic:"📝",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Lister le contenu de l'<b>acte définitif</b> de VEFA.</li>
<li>Expliquer l'<b>obligation de conformité</b> et le piège de la <b>clause d'équivalence</b>.</li>
<li>Calculer les <b>appels de fonds</b> 35 %, 70 %, 95 %, 100 %.</li>
<li>Plafonner les <b>pénalités de retard de paiement</b>.</li>
<li>Distinguer la <b>garantie d'achèvement</b> et la <b>garantie de remboursement</b>.</li></ul>
<h3>Le rendez-vous chez le notaire</h3>
<div class="gstory">Dix mois après la réservation, les Benali sont convoqués chez <b>Maître Delattre</b>, notaire place du Théâtre. Le chantier de Fives a commencé. Trois semaines plus tôt, Camille t'a appelé, inquiète : « On a reçu un pavé de 180 pages, le projet d'acte. On doit vraiment tout lire ? » Oui. Et c'est justement pour ça que la loi l'oblige à arriver en avance.</div>
<p>L'acte définitif de VEFA est obligatoirement un <b>acte authentique</b>, signé <b>chez le notaire</b>. Il est signé quand la construction commence.</p>
<ul><li>Le <b>projet d'acte</b> est envoyé à l'acheteur <b>au moins un mois</b> avant la signature.</li>
<li>Ce mois sert à tout lire, comparer avec la réservation, poser des questions.</li></ul>
<h3>Ce que contient l'acte définitif</h3>
<table><tr><th>Élément</th><th>Pourquoi c'est important</th></tr>
<tr><td>La <b>désignation précise du lot</b> : étage, numéro, surface, annexes</td><td>On sait exactement ce qu'on achète</td></tr>
<tr><td>La <b>notice descriptive</b> et les plans</td><td>Base pour contrôler la conformité</td></tr>
<tr><td>Le <b>prix</b> et l'échéancier des paiements</td><td>Il remplace le prix prévisionnel</td></tr>
<tr><td>Le <b>délai de livraison</b></td><td>Il permet de réclamer des pénalités</td></tr>
<tr><td>La <b>garantie financière d'achèvement</b></td><td>Elle protège contre l'abandon du chantier</td></tr>
<tr><td>Le <b>règlement de copropriété</b> et l'état descriptif de division</td><td>Il fixe les règles de vie et les tantièmes</td></tr></table>
<p>Les <b>tantièmes</b> (souvent des millièmes) sont la part de chaque lot dans les parties communes. Ils servent à répartir les <b>charges</b> et les <b>voix</b> en assemblée générale. Le T3 des Benali vaut par exemple 64/1 000e de l'immeuble.</p>
<h3>L'obligation de conformité du vendeur</h3>
<ul><li>Tout ce qui a été <b>prévu</b> doit être réalisé.</li>
<li>Tout ce qui est réalisé doit être <b>conforme</b> : prises électriques au bon endroit, bons matériaux, bonnes cotes.</li></ul>
<p>Si la conformité n'est pas respectée, l'acheteur a trois leviers.</p>
<ul><li>Exiger la <b>remise en conformité</b>.</li>
<li>Demander des <b>dommages et intérêts</b>.</li>
<li>Négocier une <b>diminution du prix</b>.</li></ul>
<div class="gtrap">Méfie-toi de la <b>clause d'équivalence</b>. Elle permet au constructeur de remplacer un matériau prévu par un matériau dit « équivalent ». Le parquet chêne massif peut devenir un stratifié imitation chêne. Il faut la lire, la limiter ou la refuser.</div>
<div class="gmnemo">Conformité = <b>« Prévu, fait. Fait, juste. »</b> Deux phrases, deux obligations. Et si ce n'est pas juste, les trois leviers tiennent dans <b>R.D.P.</b> : Remise en conformité, Dommages et intérêts, Prix diminué.</div>
<h3>Le délai de livraison</h3>
<p>Le vendeur doit livrer dans le <b>délai</b> prévu. Il est conseillé de prévoir dans l'acte des <b>pénalités de retard</b> par jour de retard. Les promoteurs ajoutent souvent des causes légitimes qui suspendent le délai (intempéries, grève). Il faut vérifier qu'elles restent précises.</p>
<h3>Les appels de fonds : 35, 70, 95, 100</h3>
<p>L'acheteur doit honorer les <b>appels de fonds</b>. La loi fixe des <b>plafonds cumulés</b> (article R261-14 du Code de la construction).</p>
<table><tr><th>Étape du chantier</th><th>Cumul maximum payé</th><th>Benali (250 000 €)</th></tr>
<tr><td>Achèvement des <b>fondations</b></td><td>35 %</td><td>87 500 €</td></tr>
<tr><td><b>Mise hors d'eau</b> (toiture posée)</td><td>70 %</td><td>175 000 €</td></tr>
<tr><td><b>Achèvement</b> de l'immeuble</td><td>95 %</td><td>237 500 €</td></tr>
<tr><td><b>Livraison</b> (remise des clés)</td><td>100 %</td><td>250 000 €</td></tr></table>
<p>Les <b>5 derniers pour cent</b> ne sont payés qu'à la livraison. En cas de réserves, l'acheteur peut les <b>consigner</b> (les bloquer) jusqu'à la levée des réserves.</p>
<div class="gmnemo"><b>« 35 les pieds, 70 le chapeau, 95 la fin, 5 les clés »</b>. Les pieds, ce sont les fondations. Le chapeau, c'est la toiture qui met l'immeuble hors d'eau.</div>
<h3>Payer en retard : combien ça coûte ?</h3>
<p>Si l'acheteur paie un appel de fonds en retard, le contrat peut prévoir une pénalité. Elle est plafonnée à <b>1 % par mois</b> de retard sur la somme due.</p>
<div class="formula">Appel de 87 500 € payé avec 2 mois de retard
Pénalité maximum = 87 500 x 1 % x 2 = 1 750 €</div>
<div class="gtrap">Les notes disent « indemnités de retard pas au-delà de 10 % du prix de vente ». Le plafond légal est <b>1 % par mois de retard</b> sur la somme due (article R261-14, vérifié en septembre 2026).</div>
<h3>Les garanties du vendeur</h3>
<p>Le vendeur doit fournir une <b>garantie financière</b> délivrée par une banque ou un assureur.</p>
<table><tr><th>Garantie</th><th>Ce qu'elle fait</th></tr>
<tr><td><b>Garantie financière d'achèvement</b> (GFA)</td><td>Si le promoteur fait faillite, le garant paie la fin du chantier</td></tr>
<tr><td><b>Garantie de remboursement</b></td><td>Si la vente est résolue faute d'achèvement, le garant rembourse les sommes versées</td></tr></table>
<div class="gtrap">Les notes disent que le vendeur doit donner <b>les deux</b> garanties. La loi lui impose <b>l'une ou l'autre</b> (article L261-10-1). En pratique, c'est presque toujours la <b>GFA</b>. Depuis 2015, elle doit être donnée par un organisme extérieur (banque, assureur) : la garantie « intrinsèque » fondée sur la solidité du promoteur a été supprimée.</div>
<h3>Ce que tu dois retenir pour l'examen</h3>
<ul><li>Acte authentique chez le notaire, projet reçu un mois avant.</li>
<li>Conformité : prévu fait, fait juste. Clause d'équivalence à surveiller.</li>
<li>35, 70, 95, 100, et 1 % par mois au plus en cas de retard de paiement.</li>
<li>GFA ou garantie de remboursement, la GFA en pratique.</li></ul>`},
/*EXOS*/
{i:"f248_01",u:248,t:"tf",d:.25,nw:"L'acte définitif",q:"L'acte définitif d'une VEFA doit être signé chez un notaire.",a:true,w:"C'est un acte authentique, obligatoirement notarié. Il est signé quand la construction commence."},
{i:"f248_02",u:248,t:"slider",d:.3,q:"Combien de temps au moins avant la signature le projet d'acte doit-il être envoyé à l'acheteur ?",min:0,max:6,step:1,a:1,tol:0,pre:"",un:" mois",w:"Un mois au moins. Ce délai sert à tout relire et à comparer avec le contrat de réservation."},
{i:"f248_03",u:248,t:"story",d:.35,q:"Que réponds-tu à Camille ?",sc:[{who:"Camille Benali",txt:"On a reçu un projet d'acte de 180 pages trois semaines avant la signature. Le notaire le lira à voix haute, non ? On peut s'en passer ?"}],o:["Lisez-le : ce mois d'avance sert à repérer ce qui diffère de la réservation","Inutile, le notaire garantit que l'acte reprend mot pour mot la réservation","Inutile, l'acte définitif n'engage le promoteur que sur le prix final","Lisez seulement le prix, le reste est de la technique sans conséquence"],a:0,w:"Le projet arrive un mois avant pour une raison : vérifier la désignation du lot, la notice, le délai, les garanties et les clauses comme l'équivalence."},
{i:"f248_04",u:248,t:"multi",d:.35,q:"Que doit préciser l'acte définitif ?",o:["Le lot exact : étage, numéro","Le délai de livraison","La garantie d'achèvement","Le règlement de copropriété","Le nom du futur locataire"],a:[0,1,2,3],w:"Lot précis, prix, délai de livraison, garantie financière, règlement de copropriété et tantièmes. Le locataire n'a rien à y faire."},
{i:"f248_05",u:248,t:"fill",d:.35,nw:"Les tantièmes",q:"La part d'un lot dans les parties communes s'exprime en ___.",o:["tantièmes","annuités","appels de fonds","lots de copropriété"],a:0,w:"Les tantièmes, souvent des millièmes, répartissent les charges et les voix en assemblée générale."},
{i:"f248_06",u:248,t:"mcq",d:.35,q:"À quoi servent les tantièmes du T3 des Benali ?",o:["Répartir les charges et les voix en assemblée","Calculer la taxe foncière due chaque année à la commune","Fixer le montant des appels de fonds","Mesurer la surface habitable du lot"],a:0,w:"64/1 000e des parties communes : les Benali paient 6,4 % des charges communes et pèsent 64 voix sur 1 000. Ces tantièmes figurent dans le règlement de copropriété."},
{i:"f248_07",u:248,t:"tf",d:.35,q:"Le règlement de copropriété figure dans l'acte si l'immeuble est en copropriété.",a:true,w:"Règlement de copropriété, état descriptif de division et tantièmes font partie des éléments à fournir."},
{i:"f248_08",u:248,t:"story",d:.4,q:"Rappel du module 1 : quelle est ta réponse ?",sc:[{who:"Yanis Benali",txt:"Au final, l'acte fixe le prix à 256 000 euros au lieu des 250 000 prévus. On peut exiger notre dépôt et partir ?"}],o:["Non : 256 000 € fait +2,4 %, il faut dépasser 5 % pour sortir","Oui : tout écart de prix libère l'acheteur et oblige à rendre le dépôt","Oui, à condition de refuser l'acte dans les 10 jours de sa lecture","Non : le prix de l'acte n'a jamais d'effet sur le dépôt de garantie"],a:0,w:"Le P du Prix : il faut dépasser de plus de 5 % le prix prévisionnel, soit plus de 262 500 €."},
{i:"f248_09",u:248,t:"tiles",d:.35,nw:"L'obligation de conformité",q:"Reconstitue la formule mémo de la conformité.",a:["Prévu,","fait.","Fait,","juste."],dd:["payé.","vendu.","prévu."],w:"Tout ce qui est prévu doit être réalisé, tout ce qui est réalisé doit être conforme."},
{i:"f248_10",u:248,t:"story",d:.4,q:"Que dis-tu à Philippe Vandamme ?",ctx:"Philippe Vandamme, 52 ans, cadre à Villeneuve-d'Ascq, achète aussi sur plan un T2 pour le louer. Il relit son contrat.",sc:[{who:"Philippe Vandamme",txt:"Il y a une ligne : le promoteur peut remplacer les matériaux prévus par des matériaux équivalents. C'est plutôt rassurant, non ?"}],o:["Méfiance : cette clause d'équivalence peut transformer du chêne en stratifié","Oui, elle oblige le promoteur à poser des matériaux au moins aussi bons que prévu","Oui, c'est une clause imposée par la loi dans toute vente sur plan","C'est sans effet, un promoteur ne peut jamais changer un matériau"],a:0,w:"La clause d'équivalence laisse le constructeur juger de l'équivalence. Il faut la lire, la limiter ou la refuser."},
{i:"f248_11",u:248,t:"multi",d:.4,q:"Les prises électriques du T3 ne sont pas à l'endroit prévu par les plans. Que peuvent demander les Benali ?",o:["La remise en conformité","Des dommages et intérêts","Une diminution du prix","L'annulation automatique de la vente","Le remboursement du PTZ par l'État"],a:[0,1,2],w:"R.D.P. : Remise en conformité, Dommages et intérêts, Prix diminué. Un défaut de prises n'entraîne pas d'annulation automatique."},
{i:"f248_12",u:248,t:"tf",d:.35,q:"Une clause d'équivalence protège l'acheteur contre un changement de matériaux.",a:false,w:"C'est l'inverse : elle autorise le constructeur à changer de matériaux. C'est un piège signalé dans les notes."},
{i:"f248_13",u:248,t:"story",d:.4,q:"Quel conseil donnes-tu pour le délai de livraison ?",sc:[{who:"Camille Benali",txt:"Le contrat dit livraison au troisième trimestre 2027. Et si c'est en retard ? Notre bail actuel se termine à ce moment-là."}],o:["Prévoir des pénalités par jour de retard et des causes de suspension précises","Rien à faire : un promoteur n'est jamais tenu par une date de livraison","Payer tout de suite 100 % du prix pour que le chantier aille plus vite","Refuser tout délai écrit, pour garder de la souplesse de votre côté"],a:0,w:"Le vendeur doit respecter le délai. On conseille des pénalités de retard dans l'acte, et on vérifie que les causes légitimes de suspension restent précises."},
{i:"f248_14",u:248,t:"mcq",d:.4,q:"Quelle clause faut-il vérifier pour que le délai de livraison ne soit pas vidé de sa force ?",o:["Les causes légitimes de suspension","La clause de rétractation de 10 jours","Le montant du dépôt de garantie","La répartition des tantièmes"],a:0,w:"Intempéries, grèves, défaillance d'une entreprise : des causes trop larges suspendent le délai sans fin. Elles doivent être précises."},
{i:"f248_15",u:248,t:"match",d:.4,q:"Associe chaque défaut à la réponse la plus adaptée.",p:[["Carrelage posé au mauvais endroit","Remise en conformité"],["Déménagement retardé et loyer payé en double","Dommages et intérêts"],["Balcon plus petit que prévu, impossible à agrandir","Diminution du prix"],["Livraison prévue en juin, faite en décembre","Pénalités de retard"]],w:"On répare ce qui peut l'être, on indemnise le préjudice, on baisse le prix si l'écart est définitif, on applique les pénalités prévues pour le retard."},
{i:"f248_16",u:248,t:"fill",d:.35,q:"Les trois leviers en cas de non-conformité se retiennent avec le sigle ___.",o:["R.D.P.","V.E.F.A.","G.F.A.","P.R.I.M.O."],a:0,w:"Remise en conformité, Dommages et intérêts, Prix diminué."},
{i:"f248_17",u:248,t:"order",d:.35,nw:"Les appels de fonds",q:"Remets dans l'ordre les étapes qui déclenchent les appels de fonds.",it:["Achèvement des fondations","Mise hors d'eau","Achèvement de l'immeuble","Livraison et remise des clés"],w:"35 les pieds, 70 le chapeau, 95 la fin, 5 les clés."},
{i:"f248_18",u:248,t:"slider",d:.35,q:"Quel pourcentage cumulé du prix peut être appelé à la mise hors d'eau ?",min:0,max:100,step:5,a:70,tol:0,pre:"",un:" %",w:"70 % au maximum à la mise hors d'eau : le chapeau est posé."},
{i:"f248_19",u:248,t:"num",d:.45,q:"Les Benali paient 250 000 €. Combien ont-ils versé au maximum, en cumul, à l'achèvement des fondations ?",a:87500,tol:1,un:" €",h:"35 %",w:"35 % x 250 000 = 87 500 €. Ce sont des plafonds cumulés : le promoteur ne peut pas demander plus."},
{i:"f248_20",u:248,t:"num",d:.45,q:"Toujours 250 000 €. Combien reste-t-il à payer à la remise des clés, en euros ?",a:12500,tol:1,un:" €",h:"Les 5 derniers pour cent",w:"95 % sont payés à l'achèvement, soit 237 500 €. Il reste 5 %, 12 500 €, payés à la livraison et consignables en cas de réserves."},
{i:"f248_21",u:248,t:"story",d:.45,q:"Que réponds-tu au promoteur ?",ctx:"Les fondations viennent d'être achevées. La toiture n'est pas posée.",sc:[{who:"Service clients du promoteur",txt:"Nous vous adressons un appel de fonds pour atteindre 60 % du prix, afin d'anticiper la suite."}],o:["Refusez : avant la mise hors d'eau, le cumul est plafonné à 35 %","Payez : les plafonds légaux ne s'appliquent qu'aux investisseurs","Payez : le promoteur peut appeler 60 % dès que le permis est obtenu","Refusez : aucun appel de fonds n'est dû avant la remise des clés"],a:0,w:"Tant que l'immeuble n'est pas hors d'eau, le plafond reste 35 %. Les pourcentages sont des maximums cumulés fixés par l'article R261-14."},
{i:"f248_22",u:248,t:"tiles",d:.4,q:"Reconstitue la formule mémo des appels de fonds.",a:["35","les","pieds,","70","le","chapeau,","95","la","fin"],dd:["50","les","murs,"],w:"Fondations 35 %, mise hors d'eau 70 %, achèvement 95 %, et 5 % à la remise des clés."},
{i:"f248_23",u:248,t:"mcq",d:.4,q:"Pourquoi les 5 derniers pour cent sont-ils si précieux pour l'acheteur ?",o:["Il peut les bloquer tant que les réserves ne sont pas levées","Ils couvrent les frais de notaire de la vente","Ils sont versés à la banque pour le PTZ","Ils sont remboursés par l'État à l'acheteur une fois le chantier fini"],a:0,w:"Les 5 % dus à la livraison sont le dernier moyen de pression. En cas de réserves, on les bloque jusqu'aux réparations (module 3)."},
{i:"f248_24",u:248,t:"sort",d:.45,q:"Classe chaque demande du promoteur.",bins:["Conforme à la loi","Contraire à la loi"],it:[["35 % une fois les fondations faites",0],["95 % une fois l'immeuble achevé",0],["80 % dès la mise hors d'eau",1],["100 % avant la remise des clés",1],["70 % toiture posée",0],["50 % avant la fin des fondations",1]],w:"Plafonds cumulés : 35, 70, 95, puis le solde à la livraison. Au-delà, l'appel est illégal."},
{i:"f248_25",u:248,t:"num",d:.5,nw:"Les pénalités de retard de paiement",q:"Philippe paie un appel de fonds de 40 000 € avec 3 mois de retard. Quelle pénalité maximum le promoteur peut-il réclamer, en euros ?",a:1200,tol:1,un:" €",h:"1 % par mois de retard",w:"40 000 x 1 % x 3 = 1 200 €. Les notes parlent de 10 % du prix : c'est faux, le plafond est 1 % par mois sur la somme due."},
{i:"f248_26",u:248,t:"story",d:.5,q:"Que réponds-tu à Théo ?",sc:[{who:"Théo",txt:"J'ai lu dans les notes qu'en cas de retard de paiement, le promoteur peut réclamer jusqu'à 10 % du prix de vente. Donc 25 000 euros pour les Benali ?"}],o:["Non : c'est au plus 1 % par mois de retard, et sur la somme en retard","Oui : c'est le plafond légal, calculé sur le prix total du logement","Non : un promoteur ne peut réclamer aucune pénalité à un acheteur","Oui, et il peut en plus annuler la vente dès le premier jour de retard"],a:0,w:"Article R261-14 : pénalité plafonnée à 1 % par mois de retard, sur la somme due. Les notes contiennent une erreur sur ce point."},
{i:"f248_27",u:248,t:"mcq",d:.45,nw:"La garantie financière d'achèvement",q:"Le promoteur des Jardins de Fives fait faillite, l'immeuble est hors d'eau. Qui finance la fin du chantier ?",o:["Le garant de la garantie financière d'achèvement","Les acheteurs eux-mêmes, à proportion de leurs tantièmes","La commune de Lille, qui a délivré le permis","Le notaire qui a reçu l'acte de vente"],a:0,w:"La GFA est donnée par une banque ou un assureur : si le promoteur tombe, le garant paie la fin des travaux."},
{i:"f248_28",u:248,t:"tf",d:.45,q:"La loi impose au vendeur de fournir à la fois une garantie d'achèvement et une garantie de remboursement.",a:false,w:"La loi exige l'une ou l'autre. En pratique, c'est presque toujours la garantie financière d'achèvement. Les notes disent « les deux » : à corriger."},
{i:"f248_29",u:248,t:"match",d:.45,q:"Associe chaque garantie à son effet.",p:[["Garantie d'achèvement","Le garant paie la fin du chantier"],["Garantie de remboursement","Le garant rend les sommes versées"],["Dépôt de garantie","Réserve le lot, sur un compte bloqué"],["Pénalités de retard","Indemnisent le retard de livraison"]],w:"Ne confonds pas les garanties financières du vendeur avec le dépôt de garantie de l'acheteur (module 1)."},
{i:"f248_30",u:248,t:"fill",d:.4,q:"Depuis 2015, la garantie d'achèvement doit être donnée par un organisme ___, comme une banque ou un assureur.",o:["extérieur","public","notarial","municipal"],a:0,w:"La garantie intrinsèque, fondée sur la seule solidité du promoteur, a été supprimée. Seule reste la garantie extrinsèque."},
{i:"f248_31",u:248,t:"story",d:.55,q:"Rappel du module 1 : Yanis te pose une question de calendrier.",sc:[{who:"Yanis Benali",txt:"Entre le contrat de réservation et la remise des clés, on a signé quoi, et quand ?"}],o:["La réservation et ses 10 jours, puis l'acte notarié reçu un mois avant","L'acte notarié d'abord, puis la réservation une fois le chantier terminé","Une seule signature chez le promoteur, le notaire intervient à la livraison","La réservation, puis rien jusqu'à la livraison, où l'on signe la vente"],a:0,w:"Réservation (dépôt, 10 jours), projet d'acte reçu un mois avant, acte authentique au début du chantier, appels de fonds, livraison."},
{i:"f248_32",u:248,t:"story",d:.6,q:"Synthèse : Nathalie te demande ta check-list pour l'acte de Philippe.",sc:[{who:"Nathalie Wattel",txt:"Trois points à vérifier avant qu'il signe. Pas un de plus."}],o:["« Garantie d'achèvement, délai avec pénalités, pas de clause d'équivalence libre »","« Le taux du PTZ, le nom du futur syndic et la couleur des façades de l'immeuble »","« Le dépôt de 10 %, la rétractation de 7 jours et le paiement de 100 % d'avance »","« L'avis du voisin, la taxe foncière future et le règlement de la cantine »"],a:0,w:"La GFA protège contre la faillite, les pénalités protègent le délai, la clause d'équivalence encadrée protège la conformité. La loi admet aussi une garantie de remboursement, mais la GFA domine en pratique."}
