/*UNIT*/
{id:249,c:"FISCA",n:"Module 3",t:"VEFA : la remise des clés, les réserves et les garanties 1, 2 et 10 ans",col:"--orange",ic:"🔑",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Organiser une <b>livraison</b> et rédiger des <b>réserves</b>.</li>
<li>Choisir la bonne garantie : <b>parfait achèvement</b> (1 an), <b>bon fonctionnement</b> (2 ans), <b>décennale</b> (10 ans).</li>
<li>Dérouler la procédure quand le vendeur ne répare pas.</li>
<li>Distinguer <b>vice apparent</b> et <b>vice caché</b>.</li>
<li>Savoir quand payer les <b>5 derniers pour cent</b>.</li></ul>
<h3>Le jour de la remise des clés</h3>
<div class="gstory">Septembre 2027, Fives. Les Benali visitent leur T3 fini avec le conducteur de travaux. Tu es venu avec eux, une lampe torche et un mètre. Dans le salon, le mur du fond n'a pas la même teinte que les autres. Le robinet de la cuisine n'est pas le modèle de la notice. Un volet roulant de la chambre reste bloqué à mi-course. Camille chuchote : « On signe quand même ? Ils ont l'air pressés. » Tu souris : c'est maintenant ou jamais que les réserves se font.</div>
<p>La <b>livraison</b> est la remise des clés à l'acheteur. On dresse un <b>procès-verbal</b>. L'acheteur y note ses <b>réserves</b> : tout ce qui ne va pas.</p>
<ul><li>Les réserves portent sur les défauts <b>apparents</b> : visibles par quelqu'un qui n'est <b>pas un professionnel</b> du bâtiment.</li>
<li>Exemples : mur d'une autre couleur, élément manquant, robinet différent de la notice, défaut de construction visible, non-respect d'une règle visible.</li>
<li>L'acheteur peut encore signaler un défaut apparent par lettre recommandée <b>dans le mois</b> qui suit la prise de possession.</li></ul>
<div class="gmnemo">À la livraison, pense <b>« Œil, Main, Notice »</b> : je regarde tout, je touche et j'actionne tout (volets, robinets, portes), je compare avec la notice descriptive. Ce qui n'est pas écrit dans le procès-verbal devient difficile à réclamer.</div>
<h3>Les 5 % : le dernier levier</h3>
<p>Si les réserves concernent la conformité, l'acheteur peut <b>consigner</b> les 5 % restants chez un tiers (souvent le notaire ou la Caisse des dépôts). Une fois <b>toutes les réserves levées</b>, les 5 % sont versés au vendeur.</p>
<h3>Les trois garanties légales</h3>
<table><tr><th>Garantie</th><th>Durée</th><th>Ce qu'elle couvre</th><th>Exemple aux Jardins de Fives</th></tr>
<tr><td><b>Parfait achèvement</b></td><td>1 an</td><td>Tous les désordres signalés au PV ou notifiés par écrit dans l'année</td><td>Mur mal peint, porte qui frotte</td></tr>
<tr><td><b>Bon fonctionnement</b> (biennale)</td><td>2 ans au moins</td><td>Les équipements <b>dissociables</b> du bâtiment sans le dégrader</td><td>Volet roulant, robinet, chauffe-eau</td></tr>
<tr><td><b>Décennale</b></td><td>10 ans</td><td>Les dommages qui compromettent la <b>solidité</b> ou rendent le logement <b>impropre à sa destination</b></td><td>Fissure structurelle, infiltrations généralisées</td></tr></table>
<div class="gmnemo"><b>« 1, 2, 10 : je Parfais, ça Fonctionne, ça Tient »</b>. En 1 an, on parfait tout. En 2 ans, les équipements doivent fonctionner. En 10 ans, l'immeuble doit tenir debout et rester habitable.</div>
<h3>La garantie de parfait achèvement en détail</h3>
<ul><li>Elle couvre tout ce qui a été noté au procès-verbal, et tout ce qui est découvert ensuite et <b>notifié par écrit</b> dans l'année.</li>
<li>On ne peut <b>ni la limiter ni l'écarter</b> par contrat. Elle est d'ordre public.</li>
<li>L'acheteur et le vendeur conviennent d'un <b>délai</b> pour les réparations.</li></ul>
<div class="formula">Délai de réparation dépassé
  1. Mise en demeure par lettre recommandée
  2. Toujours rien : action en justice sous astreinte
     ou travaux faits par une autre entreprise, aux frais du vendeur</div>
<p>L'<b>astreinte</b> est une somme à payer par jour de retard, fixée par le juge, pour forcer l'exécution.</p>
<h3>La garantie de bon fonctionnement en détail</h3>
<p>Elle dure <b>au moins deux ans</b>. Le contrat peut la prolonger si le vendeur l'accepte. Elle vise ce qu'on peut enlever <b>sans abîmer</b> le bâtiment.</p>
<ul><li>Oui : volet roulant, robinetterie, baignoire, radiateur, porte intérieure.</li>
<li>Non : une canalisation noyée dans la dalle ou le carrelage collé relèvent d'autres garanties.</li></ul>
<h3>La garantie décennale en détail</h3>
<p>Elle couvre pendant <b>10 ans</b> les dommages graves : ceux qui touchent la <b>solidité</b> ou qui rendent le logement <b>impropre à sa destination</b>. Le constructeur est responsable <b>de plein droit</b>. L'acheteur n'a pas à prouver une faute.</p>
<p>L'<b>assurance dommages-ouvrage</b>, souscrite par le promoteur, préfinance les réparations décennales sans attendre qu'on désigne le responsable.</p>
<div class="gtrap">Les notes disent « c'est au constructeur de prouver qu'il n'a pas commis de faute ». C'est plus sévère : même en prouvant qu'il n'a <b>pas commis de faute</b>, il reste responsable. Seule une <b>cause étrangère</b> (force majeure, fait d'un tiers) l'exonère. Les notes rangent aussi une « garantie des vices connus » dans la décennale : la décennale couvre les dommages graves, <b>connus ou non</b> du vendeur.</div>
<h3>Vice apparent, vice caché</h3>
<table><tr><th></th><th>Vice apparent</th><th>Vice caché</th></tr>
<tr><td>Définition</td><td>Visible par un non-professionnel à la livraison</td><td>Invisible pour un non-professionnel, existant avant la vente</td></tr>
<tr><td>Quand agir</td><td>Réserves au PV, ou lettre dans le mois</td><td>Dans les <b>2 ans</b> suivant sa découverte</td></tr>
<tr><td>Résultat possible</td><td>Réparation</td><td><b>Annulation de la vente</b> (on rend le bien, on récupère le prix), ou <b>baisse du prix</b>, plus des dommages et intérêts</td></tr></table>
<p>La garantie des vices cachés est l'une des seules qui peut aller jusqu'à <b>défaire la vente</b>. Les juristes parlent d'<b>action rédhibitoire</b> (défaire) et d'<b>action estimatoire</b> (baisser le prix).</p>
<div class="gtrap">Les notes disent qu'il faut <b>prouver que le vendeur savait</b>. Pour obtenir l'annulation ou la baisse du prix, il suffit de prouver un défaut caché, antérieur et grave. La connaissance du vendeur compte pour obtenir en plus des <b>dommages et intérêts</b>. Et un vendeur professionnel, comme un promoteur, est <b>présumé</b> connaître les vices.</div>
<h3>Ce que tu dois retenir pour l'examen</h3>
<ul><li>Réserves au procès-verbal, ou lettre dans le mois pour un défaut apparent.</li>
<li>1 an parfait achèvement, 2 ans bon fonctionnement, 10 ans décennale.</li>
<li>Mise en demeure, puis astreinte ou travaux aux frais du vendeur.</li>
<li>5 % versés quand toutes les réserves sont levées.</li></ul>`},
/*EXOS*/
{i:"f249_01",u:249,t:"story",d:.3,nw:"La livraison et les réserves",q:"Que réponds-tu à Camille ?",sc:[{who:"Camille Benali",txt:"Le mur du salon n'a pas la même couleur et le volet de la chambre bloque. Ils ont l'air pressés, on signe le procès-verbal sans rien écrire ?"}],o:["Non, on note chaque défaut en réserve sur le procès-verbal","Oui, on pourra tout signaler dans dix ans grâce à la décennale","Oui, un défaut de peinture ne se réclame jamais après la vente","Non, on refuse les clés tant que l'immeuble entier n'est pas repeint"],a:0,w:"La livraison est le moment des réserves. Œil, Main, Notice : on regarde, on actionne, on compare, et on écrit tout au procès-verbal."},
{i:"f249_02",u:249,t:"multi",d:.3,q:"Lesquels de ces défauts sont des réserves typiques à la livraison ?",o:["Un mur d'une autre teinte","Un robinet différent de la notice","Un élément manquant dans la cuisine","Un défaut de fondation invisible","Un volet qui ne s'ouvre pas"],a:[0,1,2,4],w:"Les réserves portent sur ce qu'un non-professionnel peut voir ou tester. Un défaut de fondation invisible n'est pas apparent."},
{i:"f249_03",u:249,t:"tiles",d:.3,q:"Reconstitue la méthode de visite à la livraison.",a:["Œil,","Main,","Notice"],dd:["Plan,","Clé,","Photo,"],w:"Je regarde tout, j'actionne tout, je compare avec la notice descriptive."},
{i:"f249_04",u:249,t:"slider",d:.35,q:"Après la prise de possession, combien de temps l'acheteur a-t-il pour signaler par écrit un défaut apparent oublié au procès-verbal ?",min:0,max:12,step:1,a:1,tol:0,pre:"",un:" mois",w:"Un mois après la prise de possession, par lettre recommandée. Passé ce délai, le vendeur est déchargé des vices apparents."},
{i:"f249_05",u:249,t:"fill",d:.3,q:"Un défaut apparent est un défaut détectable par quelqu'un qui n'est pas un ___ du bâtiment.",o:["professionnel","copropriétaire","locataire","notaire"],a:0,w:"Le critère est l'œil d'un non-professionnel. Ce qu'il ne peut pas voir relève d'autres garanties."},
{i:"f249_06",u:249,t:"tf",d:.3,q:"Si les réserves de conformité ne sont pas levées, l'acheteur peut consigner les 5 % restants.",a:true,w:"Les 5 % sont le dernier levier. On les bloque chez un tiers jusqu'à la levée des réserves, puis on les verse au vendeur."},
{i:"f249_07",u:249,t:"num",d:.35,q:"Rappel du module 2 : prix 250 000 €. Combien les Benali peuvent-ils consigner à la livraison, en euros ?",a:12500,tol:1,un:" €",h:"Le solde après 95 %",w:"95 % sont payés à l'achèvement. Il reste 5 %, soit 12 500 €, consignables en cas de réserves."},
{i:"f249_08",u:249,t:"story",d:.4,q:"Que dis-tu à Yanis ?",sc:[{who:"Yanis Benali",txt:"Les réserves sont toutes réparées, le conducteur de travaux a signé la levée. On garde quand même les 12 500 euros, au cas où ?"}],o:["Non : toutes les réserves levées, les 5 % sont dus au vendeur","Oui : on garde les 5 % pendant toute la durée de la décennale","Oui : les 5 % ne sont jamais dus si l'acheteur a fait des réserves","Non : il faut payer 10 % de plus pour remercier le promoteur"],a:0,w:"Les 5 % servent de garantie jusqu'à la levée des réserves, pas au-delà. Après, les garanties légales prennent le relais."},
{i:"f249_09",u:249,t:"match",d:.35,nw:"Les trois garanties légales",q:"Associe chaque garantie à sa durée.",p:[["Parfait achèvement","1 an"],["Bon fonctionnement","2 ans au moins"],["Décennale","10 ans"],["Défaut apparent oublié au PV","1 mois pour l'écrire"]],w:"1, 2, 10 : je Parfais, ça Fonctionne, ça Tient."},
{i:"f249_10",u:249,t:"sort",d:.4,q:"Classe chaque désordre dans la bonne garantie.",bins:["Parfait achèvement","Bon fonctionnement","Décennale"],it:[["Peinture écaillée signalée au PV",0],["Chauffe-eau en panne au bout de 18 mois",1],["Fissure qui menace un mur porteur",2],["Porte qui frotte, notifiée au 4e mois",0],["Volet roulant bloqué à 20 mois",1],["Infiltrations qui rendent une chambre inhabitable",2]],w:"La première année, tout passe par le parfait achèvement. Ensuite, les équipements dissociables relèvent du bon fonctionnement, et les dommages graves de la décennale."},
{i:"f249_11",u:249,t:"tiles",d:.35,q:"Reconstitue la formule mémo des garanties.",a:["1,","2,","10","je","Parfais,","ça","Fonctionne,","ça","Tient"],dd:["5,","Paie,"],w:"Parfait achèvement 1 an, bon fonctionnement 2 ans, décennale 10 ans."},
{i:"f249_12",u:249,t:"mcq",d:.4,q:"Quelle garantie couvre un dommage qui compromet la solidité de l'immeuble à la 7e année ?",o:["La garantie décennale","La garantie de bon fonctionnement","La garantie de parfait achèvement","Le dépôt de garantie"],a:0,w:"Solidité ou impropriété à la destination, pendant 10 ans : garantie décennale."},
{i:"f249_13",u:249,t:"tf",d:.4,nw:"La garantie de parfait achèvement",q:"Un promoteur peut réduire la garantie de parfait achèvement à six mois par une clause du contrat.",a:false,w:"On ne peut ni limiter ni écarter la garantie de parfait achèvement. Elle dure un an, c'est d'ordre public."},
{i:"f249_14",u:249,t:"story",d:.45,q:"Que conseilles-tu à Camille ?",ctx:"Huit mois après la livraison, une fissure fine apparaît au-dessus de la porte du séjour. Elle n'était pas visible à la remise des clés.",sc:[{who:"Camille Benali",txt:"On n'a rien écrit au procès-verbal pour cette fissure, c'est trop tard ?"}],o:["Non : notifiez-la par écrit au vendeur, la première année tout est couvert","Oui : ce qui n'est pas au procès-verbal de livraison est définitivement perdu","Oui : il faut attendre dix ans pour savoir si c'est décennal","Non : réparez vous-même, la garantie ne rembourse que les volets"],a:0,w:"La garantie de parfait achèvement couvre aussi ce qui est découvert après la livraison et notifié par écrit dans l'année."},
{i:"f249_15",u:249,t:"order",d:.4,q:"Le vendeur ne répare pas dans le délai convenu. Remets les étapes dans l'ordre.",it:["Signaler le défaut par écrit","Convenir d'un délai de réparation","Envoyer une mise en demeure","Saisir le juge sous astreinte ou faire faire les travaux à ses frais"],w:"On signale, on s'accorde sur un délai, on met en demeure, puis on force : astreinte judiciaire ou exécution par un tiers aux frais du vendeur."},
{i:"f249_16",u:249,t:"fill",d:.4,q:"Une somme fixée par le juge et due par jour de retard d'exécution s'appelle une ___.",o:["astreinte","franchise","consignation","pénalité de rétractation"],a:0,w:"L'astreinte force l'exécution : plus le vendeur tarde, plus il paie. On y arrive après une mise en demeure restée sans effet."},
{i:"f249_17",u:249,t:"mcq",d:.4,nw:"La garantie de bon fonctionnement",q:"Quel critère fait entrer un équipement dans la garantie de bon fonctionnement ?",o:["On peut l'enlever sans abîmer le bâtiment","Il coûte moins de 1 000 euros à remplacer","Il a été choisi par l'acheteur sur catalogue","Il se trouve dans une pièce d'eau du logement"],a:0,w:"Équipement dissociable : on le retire sans dégrader le bâti. Volet, robinet, baignoire, radiateur."},
{i:"f249_18",u:249,t:"sort",d:.45,q:"Dissociable ou non ?",bins:["Dissociable : bon fonctionnement","Indissociable : autre garantie"],it:[["Volet roulant",0],["Robinet mitigeur",0],["Canalisation noyée dans la dalle",1],["Radiateur électrique",0],["Carrelage collé au sol",1],["Mur porteur",1]],w:"Ce qu'on démonte sans casser est dissociable. Ce qui fait corps avec l'ouvrage relève de la décennale ou du parfait achèvement."},
{i:"f249_19",u:249,t:"story",d:.45,q:"Que réponds-tu ?",ctx:"Vingt mois après la livraison, le volet roulant électrique de la chambre des Benali ne remonte plus.",sc:[{who:"Yanis Benali",txt:"Le parfait achèvement est terminé depuis huit mois. On paie de notre poche ?"}],o:["Non : le volet est dissociable, la garantie de bon fonctionnement joue","Oui : après un an, plus aucune garantie ne couvre un équipement du logement","Non : c'est la décennale, puisque la chambre devient inhabitable sans volet","Oui, sauf si vous prouvez que le promoteur savait que ce volet était fragile"],a:0,w:"Équipement dissociable, moins de deux ans : bon fonctionnement. Un volet bloqué ne rend pas la chambre impropre à sa destination."},
{i:"f249_20",u:249,t:"tf",d:.45,q:"La garantie de bon fonctionnement peut être prolongée au-delà de deux ans si le vendeur l'accepte.",a:true,w:"Deux ans est un minimum. Le contrat peut prévoir plus, si le vendeur est d'accord."},
{i:"f249_21",u:249,t:"multi",d:.45,nw:"La garantie décennale",q:"Quels dommages relèvent de la garantie décennale ?",o:["Une fissure qui menace la structure","Des infiltrations qui rendent un logement inhabitable","Un défaut d'isolation qui rend le logement impropre à l'usage","Une rayure sur une porte de placard","Une ampoule grillée dans l'entrée"],a:[0,1,2],w:"Solidité ou impropriété à la destination. Une rayure ou une ampoule n'en relèvent pas."},
{i:"f249_22",u:249,t:"story",d:.5,q:"Que réponds-tu au promoteur ?",ctx:"Six ans après la livraison, la toiture laisse passer l'eau dans tous les logements du dernier étage.",sc:[{who:"Avocat du promoteur",txt:"Mon client prouvera qu'il n'a commis aucune faute : il a choisi une entreprise sérieuse et contrôlé le chantier. Il n'est donc pas responsable."}],o:["La décennale est de plein droit : prouver l'absence de faute ne suffit pas","C'est exact, le constructeur s'exonère en prouvant qu'il n'a pas fauté","C'est exact, la décennale ne joue plus au-delà de cinq ans pour les toitures","C'est aux copropriétaires de prouver la faute précise du promoteur"],a:0,w:"Responsabilité de plein droit : seule une cause étrangère exonère. Les notes disaient que le constructeur devait prouver l'absence de faute : c'est insuffisant. L'assurance dommages-ouvrage préfinance la réparation sans attendre le procès."},
{i:"f249_23",u:249,t:"mcq",d:.45,q:"Quel est le rôle de l'assurance dommages-ouvrage ?",o:["Préfinancer vite les réparations décennales","Rembourser le dépôt de garantie de l'acheteur","Couvrir le retard de livraison du chantier","Assurer le mobilier des futurs occupants"],a:0,w:"L'assurance dommages-ouvrage paie les réparations décennales sans attendre de savoir qui est responsable, puis se retourne contre lui."},
{i:"f249_24",u:249,t:"tf",d:.5,q:"Selon la règle exacte, la garantie décennale ne couvre que les vices que le vendeur connaissait.",a:false,w:"La décennale couvre les dommages graves, connus ou non. Les notes parlent d'une « garantie des vices connus » : c'est une confusion."},
{i:"f249_25",u:249,t:"match",d:.45,nw:"Vice apparent et vice caché",q:"Associe chaque notion à sa définition.",p:[["Vice apparent","Visible par un non-professionnel à la livraison"],["Vice caché","Invisible, antérieur à la vente et grave"],["Action rédhibitoire","Défaire la vente et récupérer le prix"],["Action estimatoire","Garder le bien avec une baisse de prix"]],w:"Le vice caché ouvre deux voies : rédhibitoire (on défait la vente) ou estimatoire (on baisse le prix), plus des dommages et intérêts."},
{i:"f249_26",u:249,t:"slider",d:.45,q:"Dans quel délai l'acheteur doit-il agir après la découverte d'un vice caché ?",min:1,max:10,step:1,a:2,tol:0,pre:"",un:" ans",w:"Deux ans à compter de la découverte du vice (article 1648 du Code civil)."},
{i:"f249_27",u:249,t:"story",d:.5,q:"Que réponds-tu à Théo ?",sc:[{who:"Théo",txt:"D'après les notes, pour un vice caché il faut prouver que le vendeur savait. Donc face à un promoteur de bonne foi, l'acheteur ne peut rien faire ?"}],o:["Si : caché, antérieur et grave suffit. Savoir compte pour les dommages","Exact : sans preuve que le vendeur savait, aucune action n'est possible","Exact, sauf si le défaut apparaît pendant l'année de parfait achèvement","Si, mais seulement pour obtenir la réparation, jamais une baisse du prix"],a:0,w:"La connaissance du vendeur ouvre les dommages et intérêts. Et un vendeur professionnel est présumé connaître les vices : l'argument de bonne foi tombe. On choisit ensuite l'action rédhibitoire ou estimatoire."},
{i:"f249_28",u:249,t:"multi",d:.5,q:"Que peut obtenir un acheteur victime d'un vice caché ?",o:["L'annulation de la vente et le remboursement du prix","Une baisse du prix en gardant le bien","Des dommages et intérêts si le vendeur connaissait le vice","Une réduction d'impôt pour vice caché"],a:[0,1,2],w:"Défaire la vente (rédhibitoire), baisser le prix (estimatoire), plus des dommages et intérêts. C'est une des seules garanties qui peut défaire la vente."},
{i:"f249_29",u:249,t:"story",d:.55,q:"Rappel du module 2 : quelle réponse donnes-tu ?",sc:[{who:"Philippe Vandamme",txt:"Dans mon T2, le parquet chêne prévu a été remplacé par du stratifié. Mon contrat contient une clause d'équivalence."}],o:["C'est un défaut de conformité à réserver, et la clause se discute","Rien à faire : la clause d'équivalence valide tout remplacement de matériau","C'est un vice caché, vous pouvez agir pendant dix ans","C'est la garantie de bon fonctionnement qui s'applique ici"],a:0,w:"Prévu, fait. Fait, juste. Un stratifié n'est pas un chêne massif : on le note en réserve et on conteste l'équivalence prétendue."},
{i:"f249_30",u:249,t:"mcq",d:.5,q:"Quand les 5 derniers pour cent sont-ils versés au vendeur ?",o:["Quand toutes les réserves sont levées","À la signature du contrat de réservation","À la fin de la garantie décennale","À la mise hors d'eau de l'immeuble"],a:0,w:"Réserves levées, 5 % versés. C'est la fin du parcours VEFA."},
{i:"f249_31",u:249,t:"order",d:.5,q:"Remets dans l'ordre tout le parcours VEFA des Benali.",it:["Contrat de réservation et dépôt","Acte authentique chez le notaire","Appels de fonds jusqu'à 95 %","Livraison et réserves","Levée des réserves et paiement des 5 %"],w:"Modules 1, 2 et 3 en une ligne : réserver, signer, payer au fil du chantier, réceptionner, solder."},
{i:"f249_32",u:249,t:"story",d:.6,q:"Synthèse : que dis-tu aux Benali, un an après leur installation ?",sc:[{who:"Camille Benali",txt:"Le parfait achèvement s'arrête demain. Il nous reste quoi comme protection ?"}],o:["Un an de bon fonctionnement pour les équipements, et neuf de décennale","Plus rien, toutes les garanties expirent après la première année","La décennale seulement, le bon fonctionnement ne vaut que dans l'ancien","Encore un mois pour signaler tout ce que vous voulez, puis plus rien"],a:0,w:"Bon fonctionnement jusqu'à 2 ans, décennale jusqu'à 10 ans. Le premier anniversaire n'est pas la fin des garanties."}
