/*UNIT*/
{id:251,c:"FISCA",n:"Module 5",t:"Pinel : loyer plafonné, locataire choisi et stratégie retraite",col:"--gold",ic:"📐",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Calculer une <b>surface pondérée</b>.</li>
<li>Calculer le <b>coefficient multiplicateur</b> et le <b>loyer maximum</b>.</li>
<li>Vérifier le <b>plafond de ressources</b> du locataire avec ses revenus N-2.</li>
<li>Lister les <b>sanctions</b> en cas de non-respect.</li>
<li>Monter une <b>stratégie de complément de retraite</b> avec un investissement locatif.</li></ul>
<h3>Le locataire de Philippe</h3>
<div class="gstory">Le T2 Pinel de Philippe se libère. Une candidate se présente : <b>Léa</b>, 27 ans, kiné salariée à Lomme. Philippe voudrait louer 850 euros, « comme le voisin ». Nathalie secoue la tête : « Avant de fixer un euro de loyer, tu calcules le plafond. Et avant d'accepter Léa, tu regardes son avis d'impôt d'il y a deux ans. » Philippe soupire : « Deux ans ? Pourquoi pas celui de cette année ? »</div>
<h3>La surface pondérée</h3>
<p>Le loyer maximum ne se calcule pas sur la seule surface habitable. On utilise la <b>surface pondérée</b>, aussi appelée surface utile.</p>
<div class="formula">Surface pondérée = surface habitable + moitié des annexes
La moitié des annexes est retenue dans la limite de 8 m²</div>
<ul><li>Annexes : <b>balcon</b>, <b>cave</b>, <b>cellier</b>, loggia, terrasse (dans une certaine limite).</li>
<li>Philippe : 45 m² habitables, balcon 6 m², cave 4 m². Moitié des annexes : 5 m². Surface pondérée : <b>50 m²</b>.</li></ul>
<div class="gmnemo">Les annexes comptent <b>« à moitié, et pas plus de 8 »</b>. Un balcon, c'est la moitié d'une pièce : on ne vit pas dedans l'hiver.</div>
<h3>Le coefficient multiplicateur</h3>
<p>Le coefficient avantage les petites surfaces, dont le loyer au m² est plus élevé sur le marché.</p>
<div class="formula">Coefficient = 0,7 + 19 / surface pondérée   (plafonné à 1,2)
Philippe : 0,7 + 19 / 50 = 0,7 + 0,38 = 1,08</div>
<h3>Le loyer maximum</h3>
<div class="formula">Loyer maximum = plafond de la zone (€/m²) x surface pondérée x coefficient
Exemple d'école : 14 €/m² x 50 m² x 1,08 = 756 € par mois, hors charges</div>
<p>Le plafond au m² dépend de la <b>zone</b> et est revalorisé chaque année. Les 850 euros « comme le voisin » sont donc interdits : au-delà du plafond, Philippe perd l'avantage fiscal.</p>
<div class="gmnemo">Le loyer Pinel, c'est <b>« Zone x Surface x Coef »</b>. Retiens <b>Z.S.C.</b> comme un code postal : sans les trois, pas d'adresse, pas de loyer.</div>
<h3>Le plafond de ressources du locataire</h3>
<ul><li>Le locataire ne doit pas dépasser un <b>plafond de ressources</b>, qui dépend de la zone et de la composition du foyer.</li>
<li>On regarde le <b>revenu fiscal de référence</b> de l'année <b>N-2</b> : pour un bail signé en 2026, l'avis d'impôt 2025 sur les revenus 2024.</li>
<li>Le contrôle se fait au niveau du <b>foyer fiscal</b> du locataire.</li>
<li>On vérifie à la <b>signature</b> du bail. Si le locataire gagne plus ensuite, le propriétaire garde son avantage.</li></ul>
<p>Pourquoi N-2 ? Parce qu'à la signature d'un bail en début d'année, l'avis de l'année N-1 n'existe souvent pas encore.</p>
<h3>Les sanctions</h3>
<p>Le non-respect d'une condition (loyer trop élevé, locataire au-dessus du plafond, logement meublé, location tardive, vente avant la fin) entraîne :</p>
<ul><li>la <b>perte</b> de l'avantage fiscal pour l'avenir,</li>
<li>la <b>reprise</b> des réductions déjà obtenues (on rembourse),</li>
<li>parfois des <b>intérêts et pénalités</b> en plus.</li></ul>
<div class="gmnemo">Les sanctions tiennent en <b>« Perdre, Rendre, Payer »</b> : on perd l'avantage, on rend ce qu'on a touché, on paie les pénalités.</div>
<h3>La stratégie complément de retraite</h3>
<p>Le profil type : un investisseur d'environ <b>50 ans</b>, comme Philippe. Il achète, il loue pendant la durée d'engagement, il perçoit des loyers et une réduction d'impôt. Une fois l'engagement terminé, il peut <b>récupérer le logement</b> pour y vivre ou le relouer librement, souvent à l'arrivée de la <b>retraite</b>.</p>
<div class="gstory">L'exemple du prof : <b>Gérard Lemaire</b>, 58 ans, agriculteur à Wavrin. À six ans de la retraite, il fait construire un logement près de sa ferme et le loue six ans en Pinel. Le jour de la retraite, il laisse la ferme à son fils et emménague dans le logement. Six ans de loyers, six ans de réduction d'impôt, et une maison de retraite à lui.</div>
<p>Pour le prof, c'était « un des produits les plus intéressants pour ça », <b>au passé</b> : le Pinel est fermé depuis fin 2024. La même logique vaut aujourd'hui avec le <b>Jeanbrun</b> (engagement de 9 ans).</p>
<h3>Ce que tu dois retenir pour l'examen</h3>
<ul><li>Surface pondérée : habitable + moitié des annexes, 8 m² au plus.</li>
<li>Coefficient 0,7 + 19 / S, plafonné à 1,2.</li>
<li>Loyer = Zone x Surface x Coef. Ressources du locataire : N-2, à la signature.</li>
<li>Sanctions : Perdre, Rendre, Payer.</li></ul>`},
/*EXOS*/
{i:"f251_01",u:251,t:"fill",d:.3,nw:"La surface pondérée",q:"Pour le loyer Pinel, on ajoute à la surface habitable la ___ des annexes, dans la limite de 8 m².",o:["moitié","totalité","le quart","le tiers"],a:0,w:"Surface pondérée = habitable + moitié des annexes, 8 m² au plus. À moitié, et pas plus de 8."},
{i:"f251_02",u:251,t:"num",d:.35,q:"Philippe : 45 m² habitables, balcon de 6 m², cave de 4 m². Quelle est la surface pondérée, en m² ?",a:50,tol:0,un:" m²",h:"Moitié des annexes, 8 m² au plus",w:"Annexes 10 m², moitié 5 m², sous la limite de 8. 45 + 5 = 50 m²."},
{i:"f251_03",u:251,t:"num",d:.4,q:"Un T3 de 62 m² a une terrasse de 12 m² et une cave de 8 m². Quelle surface pondérée, en m² ?",a:70,tol:0,un:" m²",h:"La moitié des annexes est plafonnée",w:"Annexes 20 m², moitié 10 m², mais plafonnée à 8 m². 62 + 8 = 70 m²."},
{i:"f251_04",u:251,t:"multi",d:.35,q:"Quels éléments peuvent être des annexes dans la surface pondérée ?",o:["Un balcon","Une cave","Un cellier","La chambre principale","Le séjour"],a:[0,1,2],w:"Balcon, cave, cellier, loggia comptent à moitié. Les pièces de vie sont déjà dans la surface habitable."},
{i:"f251_05",u:251,t:"num",d:.4,nw:"Le coefficient multiplicateur",q:"Pour une surface pondérée de 50 m², quel est le coefficient multiplicateur ? (0,7 + 19 / S)",a:1.08,tol:.005,un:"",h:"19 / 50 = 0,38",w:"0,7 + 0,38 = 1,08. Plus le logement est petit, plus le coefficient monte, dans la limite de 1,2."},
{i:"f251_06",u:251,t:"slider",d:.4,q:"Quel est le plafond du coefficient multiplicateur ?",min:1,max:2,step:.1,a:1.2,tol:0,pre:"",un:"",w:"Le coefficient 0,7 + 19 / S ne peut pas dépasser 1,2. Pour un studio de 20 m², on trouverait 1,65, ramené à 1,2."},
{i:"f251_07",u:251,t:"tf",d:.35,q:"Le coefficient multiplicateur avantage les petits logements.",a:true,w:"Les petites surfaces se louent plus cher au m² sur le marché : le coefficient 0,7 + 19 / S le reconnaît."},
{i:"f251_08",u:251,t:"story",d:.4,q:"Que réponds-tu à Théo ?",sc:[{who:"Théo",txt:"Pour un studio de 19 m², je trouve un coefficient de 1,7. Le loyer sera énorme !"}],o:["Le coefficient est plafonné à 1,2, quel que soit le calcul","Oui, plus le studio est petit, plus le loyer peut monter sans fin","Le coefficient ne s'applique qu'aux logements de plus de 50 m²","Il faut diviser 19 par 0,7, tu t'es trompé de formule"],a:0,w:"0,7 + 19 / 19 = 1,7, ramené au plafond de 1,2."},
{i:"f251_09",u:251,t:"num",d:.45,nw:"Le loyer maximum Pinel",q:"Plafond de la zone : 14 €/m². Surface pondérée : 50 m². Coefficient : 1,08. Quel loyer maximum mensuel, en euros ?",a:756,tol:1,un:" €",h:"Zone x Surface x Coef",w:"Zone x Surface x Coef : 14 x 50 x 1,08 = 756 € par mois hors charges. Au-delà, l'avantage fiscal est perdu."},
{i:"f251_10",u:251,t:"story",d:.45,q:"Que dis-tu à Philippe ?",sc:[{who:"Philippe Vandamme",txt:"Mon voisin loue le même T2 à 850 euros. Je fais pareil, personne ne vérifiera."}],o:["Au-delà de 756 €, vous perdez la réduction et devez la rendre","Pas de souci : le plafond n'est qu'une recommandation","Vous pouvez, à condition de déclarer 756 € au fisc","Vous pouvez si le locataire accepte par écrit de payer plus"],a:0,w:"Zone x Surface x Coef = 756 €. Au-delà : Perdre, Rendre, Payer."},
{i:"f251_11",u:251,t:"tiles",d:.4,q:"Reconstitue la formule du loyer maximum Pinel.",a:["Plafond","de","zone","x","surface","pondérée","x","coefficient"],dd:["habitable","+","taux"],w:"Z.S.C. : Zone, Surface pondérée, Coefficient."},
{i:"f251_12",u:251,t:"order",d:.4,q:"Remets dans l'ordre le calcul du loyer maximum.",it:["Mesurer la surface habitable et les annexes","Calculer la surface pondérée","Calculer le coefficient 0,7 + 19 / S","Multiplier par le plafond de la zone"],w:"Surface, pondération, coefficient, puis Zone x Surface x Coef."},
{i:"f251_13",u:251,t:"slider",d:.4,nw:"Le plafond de ressources du locataire",q:"Pour un bail Pinel signé en 2026, de quelle année sont les revenus retenus pour le locataire ?",min:2020,max:2026,step:1,a:2024,tol:0,pre:"",un:"",w:"Revenus N-2 : 2024, figurant sur l'avis d'impôt reçu en 2025."},
{i:"f251_14",u:251,t:"story",d:.45,q:"Que réponds-tu à Philippe ?",sc:[{who:"Philippe Vandamme",txt:"Pourquoi N-2 ? Pourquoi pas les revenus de l'an dernier ?"}],o:["Au début de l'année, l'avis d'impôt de N-1 n'existe souvent pas encore","Parce que les revenus baissent toujours d'une année sur l'autre","C'est une erreur, la loi retient en fait les revenus de l'année en cours","Pour avantager les locataires qui ont été augmentés récemment"],a:0,w:"N-2 est le seul avis d'impôt toujours disponible à la signature. Le contrôle se fait sur le foyer fiscal du locataire."},
{i:"f251_15",u:251,t:"tf",d:.45,q:"Si le locataire Pinel dépasse le plafond de ressources deux ans après son entrée, Philippe perd sa réduction.",a:false,w:"Le plafond s'apprécie à la signature du bail. Une augmentation ultérieure du locataire ne remet pas en cause l'avantage."},
{i:"f251_16",u:251,t:"multi",d:.45,q:"Comment vérifie-t-on les ressources de Léa, candidate au T2 ?",o:["On regarde le revenu fiscal de référence","On prend l'année N-2","On raisonne au niveau de son foyer fiscal","On regarde son dernier bulletin de salaire seul","On vérifie ses revenus chaque année du bail"],a:[0,1,2],w:"Revenu fiscal de référence, N-2, foyer fiscal, à la signature. Pas de contrôle annuel."},
{i:"f251_17",u:251,t:"sort",d:.45,nw:"Les sanctions Pinel",q:"Ce comportement fait-il perdre l'avantage Pinel ?",bins:["Perte de l'avantage","Sans conséquence"],it:[["Louer 100 € au-dessus du plafond",0],["Louer meublé",0],["Louer 18 mois après la remise des clés",0],["Le locataire est augmenté après son entrée",1],["Changer de locataire en cours d'engagement",1],["Vendre le logement au bout de 4 ans sur 6",0]],w:"Loyer, meublé, délai, durée : chaque manquement coûte l'avantage. Un changement de locataire aux conditions reste possible."},
{i:"f251_18",u:251,t:"tiles",d:.4,q:"Reconstitue la formule mémo des sanctions.",a:["Perdre,","Rendre,","Payer"],dd:["Garder,","Louer,","Oublier,"],w:"On perd l'avantage, on rend les réductions déjà obtenues, on paie parfois des intérêts et pénalités."},
{i:"f251_19",u:251,t:"num",d:.5,q:"Philippe a touché 4 400 € de réduction par an pendant 5 ans, puis vend son T2 avant les 9 ans. Combien doit-il rembourser au fisc, hors pénalités, en euros ?",a:22000,tol:1,un:" €",h:"Reprise des réductions déjà obtenues",w:"5 x 4 400 = 22 000 € repris, et il ne touche pas les 4 années restantes. Perdre, Rendre, Payer."},
{i:"f251_20",u:251,t:"mcq",d:.45,q:"Que risque l'investisseur qui loue meublé un logement Pinel ?",o:["La reprise des réductions obtenues","Un simple rappel à l'ordre de la mairie","Une baisse du plafond de loyer de 10 %","Aucune sanction s'il baisse le loyer"],a:0,w:"Location nue obligatoire. Louer meublé fait perdre l'avantage et entraîne la reprise des réductions."},
{i:"f251_21",u:251,t:"story",d:.5,nw:"La stratégie complément de retraite",q:"Que proposes-tu à ce client ?",ctx:"Marc, 51 ans, cadre à Lille, part à la retraite dans 9 ans et veut un logement pour ses vieux jours, près de la mer, à Wimereux.",sc:[{who:"Marc",txt:"Je voudrais préparer ma retraite, mais sans payer un logement vide pendant neuf ans."}],o:["Investir, louer pendant l'engagement, puis récupérer le bien à la retraite","Acheter et laisser le logement vide pour qu'il reste propre","Acheter en Pinel et y passer ses week-ends en attendant","Attendre la retraite pour acheter, les taux seront meilleurs"],a:0,w:"La stratégie du prof : louer pendant la durée d'engagement, encaisser loyers et avantage fiscal, puis intégrer le bien à la retraite. Aujourd'hui via le Jeanbrun."},
{i:"f251_22",u:251,t:"order",d:.45,q:"Remets dans l'ordre la stratégie de Gérard, l'agriculteur de Wavrin.",it:["Faire construire un logement près de la ferme","Le louer nu pendant six ans","Percevoir loyers et réduction d'impôt","Partir à la retraite et laisser la ferme","Emménager dans le logement"],w:"L'exemple du prof : la durée d'engagement colle aux années qui restent avant la retraite."},
{i:"f251_23",u:251,t:"fill",d:.45,q:"Dans l'exemple du prof, l'agriculteur choisit une durée d'engagement égale au temps qui lui reste avant sa ___.",o:["retraite","succession","donation","mutation"],a:0,w:"Six ans avant la retraite, six ans d'engagement : le logement se libère au bon moment."},
{i:"f251_24",u:251,t:"tf",d:.5,q:"Une fois l'engagement Pinel terminé, le propriétaire peut habiter lui-même le logement.",a:true,w:"C'est tout l'intérêt de la stratégie retraite : à la fin de l'engagement, le propriétaire récupère le bien."},
{i:"f251_25",u:251,t:"story",d:.5,q:"Rappel du module 4 : Gérard demande combien il a gagné.",ctx:"Gérard a acheté en 2020 un logement de 180 000 €, 70 m², engagement de 6 ans.",sc:[{who:"Gérard Lemaire",txt:"Six ans de Pinel, ça m'a fait combien de réduction d'impôt en tout ?"}],o:["21 600 €, soit 12 % de 180 000 €","32 400 €, soit 18 % de 180 000 €","37 800 €, soit 21 % de 180 000 €","16 200 €, soit 9 % de 180 000 €"],a:0,w:"Achat en 2020, 6 ans : 12 %. 70 x 5 500 = 385 000 €, pas de plafond atteint. 180 000 x 12 % = 21 600 €."},
{i:"f251_26",u:251,t:"match",d:.45,q:"Associe chaque chiffre à sa règle.",p:[["0,7 + 19 / S","Coefficient multiplicateur"],["1,2","Plafond du coefficient"],["8 m²","Limite de la moitié des annexes"],["N-2","Année des revenus du locataire"]],w:"Quatre chiffres pour calculer le loyer et choisir le locataire."},
{i:"f251_27",u:251,t:"mcq",d:.5,q:"Pourquoi le prof dit-il que le Pinel était intéressant pour la retraite « au passé » ?",o:["Le dispositif est fermé depuis fin 2024","La retraite a été supprimée pour les cadres","Les loyers Pinel sont devenus libres","La réduction est devenue imposable"],a:0,w:"Le Pinel n'accepte plus de nouveaux investissements depuis le 1er janvier 2025. La logique survit avec le Jeanbrun. Comme l'agriculteur de Wavrin, on la transpose au Jeanbrun."},
{i:"f251_28",u:251,t:"story",d:.55,q:"Que réponds-tu à Léa ?",ctx:"Léa, candidate au T2, vit seule. Son revenu fiscal de référence 2024 est sous le plafond, mais elle vient d'être augmentée.",sc:[{who:"Léa",txt:"Avec mon augmentation, je vais dépasser votre plafond l'an prochain. Vous allez me mettre dehors ?"}],o:["Non, le plafond se vérifie à la signature, sur vos revenus N-2","Oui, il faudra quitter le logement dès que vous dépasserez","Oui, sauf si vous acceptez de payer un loyer plus élevé","Non, mais le propriétaire perdra alors sa réduction d'impôt"],a:0,w:"Contrôle à la signature, sur le revenu fiscal de référence N-2 du foyer. Une hausse ultérieure ne change rien."},
{i:"f251_29",u:251,t:"num",d:.55,q:"T2 de 40 m² habitables, sans annexe, zone à 14 €/m². Coefficient 0,7 + 19 / 40. Quel loyer maximum, arrondi à l'euro ?",a:658,tol:1,un:" €",h:"Coefficient = 1,175",w:"0,7 + 0,475 = 1,175. 14 x 40 x 1,175 = 658 €."},
{i:"f251_30",u:251,t:"sort",d:.5,q:"Rappel des modules 4 et 5 : règle vraie ou fausse ?",bins:["Règle exacte","Erreur"],it:[["Deux logements Pinel par an au plus",0],["Plafond de 5 000 € par m²",1],["Location nue obligatoire",0],["Revenus du locataire de l'année N-1",1],["Moitié des annexes, 8 m² au plus",0],["Coefficient plafonné à 1,5",1]],w:"5 500 € par m², revenus N-2, coefficient plafonné à 1,2. Les autres règles sont exactes."},
{i:"f251_31",u:251,t:"story",d:.6,q:"Synthèse : Philippe veut une réponse claire avant la visite de Léa.",sc:[{who:"Philippe Vandamme",txt:"Donne-moi les trois chiffres à vérifier avant de signer avec elle."}],o:["« Loyer sous 756 €, revenus 2024 sous le plafond, bail de location nue »","« Loyer à 850 €, revenus 2026 au plus haut, bail meublé d'un an »","« Loyer libre, revenus de ses parents, dépôt de 5 % du prix »","« Loyer au prix du voisin, aucun contrôle, bail précaire de 6 mois »"],a:0,w:"Zone x Surface x Coef = 756 €, ressources N-2, location nue en résidence principale."},
{i:"f251_32",u:251,t:"multi",d:.6,q:"Synthèse : quelles conditions faut-il respecter pendant tout l'engagement Pinel ?",o:["Location nue","Résidence principale du locataire","Loyer sous le plafond","Locataire contrôlé chaque année","Occupation estivale par le propriétaire"],a:[0,1,2],w:"Nu, résidence principale, loyer plafonné, sur toute la durée. Les ressources du locataire ne se contrôlent qu'à la signature. Et cela pendant tout l'engagement de 6, 9 ou 12 ans."}
