/*UNIT*/
{id:252,c:"FISCA",n:"Module 6",t:"Dispositif Jeanbrun : le successeur du Pinel qui amortit le logement",col:"--gold",ic:"🧱",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Situer le <b>Jeanbrun</b> : date, objectif, différence avec le Pinel.</li>
<li>Dire quels <b>logements</b> sont éligibles, neufs et anciens.</li>
<li>Calculer l'<b>amortissement</b> annuel avec les taux et les plafonds.</li>
<li>Lister les <b>interdictions</b> : meublé, famille, démembrement, cumul.</li>
<li>Expliquer l'effet sur l'impôt : <b>déduction</b> des revenus fonciers, pas réduction d'impôt.</li></ul>
<h3>Le nouveau T2 de Philippe</h3>
<div class="gstory">Mars 2026. Philippe a signé la réservation d'un second T2 neuf sur plan, à Lille-Moulins, 250 000 euros. Il arrive ravi : « Le promoteur dit que c'est un Pinel en mieux. Donc je retire encore 4 400 euros de mon impôt chaque année ? » Nathalie pose son stylo : « Non. Avec le Jeanbrun, tu ne retires rien de ton impôt. Tu retires quelque chose de ton revenu. Ce n'est pas du tout la même chose. »</div>
<h3>Le contexte : relance du logement</h3>
<ul><li>Le dispositif porte le nom de <b>Vincent Jeanbrun</b>, ministre du Logement. On l'appelle aussi <b>statut du bailleur privé</b>.</li>
<li>Il a été créé par la <b>loi de finances pour 2026</b> (loi du 19 février 2026), dans le plan de <b>relance du logement</b>.</li>
<li>Il <b>remplace le Pinel</b>, fermé fin 2024. Il est jugé <b>moins coûteux pour l'État</b>.</li>
<li>Il garde un objectif <b>social et fiscal</b>, avec des conditions plus strictes que le Pinel.</li>
<li>Il vise les acquisitions faites entre le <b>21 février 2026</b> et le <b>31 décembre 2028</b> : une fenêtre courte, moins de trois ans.</li></ul>
<div class="gtrap">Les notes situent le point de départ au dépôt du <b>permis de construire</b> entre le 20 février 2026 et le 31 décembre 2028. Les sources consultées en septembre 2026 retiennent la date d'<b>acquisition</b> du logement dans cette fenêtre. Vérifie la formulation attendue avec ton prof.</div>
<h3>Les logements éligibles</h3>
<table><tr><th>Type</th><th>Conditions</th></tr>
<tr><td><b>Neuf ou VEFA</b></td><td>Appartement dans un immeuble collectif</td></tr>
<tr><td><b>Ancien rénové</b></td><td>Travaux lourds d'au moins <b>30 %</b> du prix d'achat, et classe énergétique <b>A ou B</b> après travaux</td></tr></table>
<p>Les <b>maisons individuelles</b> sont exclues. Il n'y a <b>aucune zone</b> : le Jeanbrun s'applique partout en France, contrairement au Pinel.</p>
<div class="gtrap">Les notes parlent d'un « immeuble complet » pour l'ancien. Les sources vérifiées exigent un logement situé dans un <b>immeuble collectif</b>, sans imposer d'acheter tout l'immeuble. Un assouplissement (travaux ramenés à 20 %, gain de classes énergétiques) était en discussion au Parlement en septembre 2026 : à surveiller.</div>
<h3>L'avantage : un amortissement, pas une réduction</h3>
<p>Le Pinel donnait une <b>réduction d'impôt</b> : on retirait une somme de l'impôt. Le Jeanbrun donne un <b>amortissement</b> : chaque année, on déduit une fraction du prix du logement des <b>revenus fonciers</b> imposables.</p>
<ul><li>La base amortissable est de <b>80 %</b> du prix : le terrain ne s'use pas, il ne s'amortit pas.</li>
<li>Si l'amortissement crée un <b>déficit foncier</b>, celui-ci s'impute sur le revenu global dans la limite de <b>10 700 euros</b> par an.</li></ul>
<div class="gmnemo"><b>« Pinel réduit l'impôt, Jeanbrun réduit le revenu »</b>. Le Pinel te rend des euros d'impôt. Le Jeanbrun efface des euros de loyers imposables, et l'économie dépend donc de ta tranche d'imposition.</div>
<h3>Les taux et les plafonds</h3>
<table><tr><th>Niveau de loyer</th><th>Neuf : taux</th><th>Neuf : plafond annuel</th><th>Ancien rénové : taux</th></tr>
<tr><td><b>Intermédiaire</b></td><td>3,5 %</td><td>8 000 €</td><td>3 %</td></tr>
<tr><td><b>Social</b></td><td>4,5 %</td><td>10 000 €</td><td>3,5 %</td></tr>
<tr><td><b>Très social</b></td><td>5,5 %</td><td>12 000 €</td><td>4 %</td></tr></table>
<p>Dans l'ancien rénové, le plafond est <b>unique</b> : <b>10 700 euros</b> par an, quel que soit le niveau de loyer.</p>
<div class="gmnemo">Neuf : <b>« un point de plus, deux mille de plus »</b>. 3,5 % et 8 000, 4,5 % et 10 000, 5,5 % et 12 000. Ancien : 3, 3,5, 4, et un seul plafond, 10 700.</div>
<div class="formula">Philippe, neuf, 250 000 €, loyer intermédiaire
Base = 80 % x 250 000 = 200 000 €
Amortissement = 3,5 % x 200 000 = 7 000 € par an (sous 8 000)
Même logement à 300 000 € : base 240 000, 3,5 % = 8 400, ramené à 8 000 €</div>
<h3>Les conditions de location</h3>
<ul><li>Engagement de louer <b>9 ans</b> au moins, <b>nu</b>, en <b>résidence principale</b>.</li>
<li>Le loyer et les <b>ressources du locataire</b> sont plafonnés selon le niveau choisi.</li>
<li>Les ressources sont appréciées à la <b>signature du bail</b>.</li>
<li>Repères du prof : très social pour les revenus les plus faibles (RSA, sous le SMIC), social entre les deux, intermédiaire autour ou au-dessus du SMIC.</li></ul>
<div class="gtrap">Les notes parlent d'un « bail de 9 ans minimum » et d'un départ anticipé « si la situation personnelle change ». L'engagement de 9 ans est celui du <b>propriétaire</b>. Le locataire signe un bail d'habitation classique (3 ans renouvelable, module 12) et peut <b>toujours partir</b> avec un préavis. Le propriétaire reloue alors aux mêmes conditions.</div>
<h3>Les interdictions</h3>
<ul><li>Location <b>meublée</b> interdite.</li>
<li>Location à la <b>famille jusqu'au 2e degré inclus</b> : parents, enfants, grands-parents, petits-enfants, frères et sœurs.</li>
<li>Location à un membre du <b>foyer fiscal</b>.</li>
<li>Les cousins (4e degré) restent autorisés.</li>
<li>Logements <b>démembrés</b> (nue-propriété d'un côté, usufruit de l'autre) exclus.</li>
<li><b>Cumul</b> avec le Denormandie interdit.</li></ul>
<div class="gmnemo">Les interdits tiennent en <b>M.F.D.C.</b> : Meublé, Famille proche, Démembrement, Cumul. Retiens « <b>Mon Frère Dort Chez</b> moi » : et justement, ton frère ne peut pas être ton locataire Jeanbrun.</div>
<h3>À la revente et en société</h3>
<ul><li>À la revente, les amortissements déduits sont <b>réintégrés</b> dans le calcul de la plus-value. L'avantage est donc en partie repris.</li>
<li>Pour le cumul avec le LLI (module 7), la structure utilisée est une <b>SCI à l'impôt sur le revenu</b>.</li></ul>
<div class="gtrap">Les notes disent « compatible avec une SCI soumise à l'IS ». Le Jeanbrun est un amortissement de <b>revenus fonciers</b>, donc un mécanisme de l'impôt sur le revenu. Une SCI à l'IS amortit déjà son immeuble selon les règles de l'IS, sans ce dispositif. Les sources consultées recommandent une <b>SCI à l'IR</b> pour le cumul avec le LLI.</div>
<h3>Ce que tu dois retenir pour l'examen</h3>
<ul><li>Loi de finances 2026, acquisitions jusqu'au 31 décembre 2028, toute la France, immeubles collectifs.</li>
<li>Amortissement sur 80 % du prix, déduit des revenus fonciers, 9 ans d'engagement.</li>
<li>Neuf 3,5 / 4,5 / 5,5 % et 8 000 / 10 000 / 12 000 €. Ancien 3 / 3,5 / 4 %, plafond 10 700 €.</li>
<li>Interdits : Meublé, Famille jusqu'au 2e degré, Démembrement, Cumul Denormandie.</li></ul>`},
/*EXOS*/
{i:"f252_01",u:252,t:"mcq",d:.25,nw:"Le dispositif Jeanbrun",q:"Quel texte a créé le dispositif Jeanbrun ?",o:["La loi de finances pour 2026","La loi ALUR de 2014","La loi de finances pour 2024","La loi Macron de 2015"],a:0,w:"Loi de finances pour 2026, promulguée le 19 février 2026, dans le plan de relance du logement."},
{i:"f252_02",u:252,t:"story",d:.3,q:"Que réponds-tu à Philippe ?",sc:[{who:"Philippe Vandamme",txt:"Le promoteur dit que le Jeanbrun, c'est un Pinel en mieux. Donc je retire encore une somme fixe de mon impôt chaque année ?"}],o:["Non : le Jeanbrun déduit un amortissement de vos loyers imposables","Oui : c'est la même réduction d'impôt, avec des taux plus élevés","Oui, mais la réduction est versée par chèque au bout de neuf ans","Non : le Jeanbrun rembourse une partie des intérêts de votre prêt"],a:0,w:"Pinel réduit l'impôt, Jeanbrun réduit le revenu. L'économie réelle dépend de la tranche d'imposition."},
{i:"f252_03",u:252,t:"multi",d:.3,q:"Quelles affirmations décrivent bien le contexte du Jeanbrun ?",o:["Il remplace le Pinel","Il coûte moins cher à l'État","Il a un objectif social et fiscal","Il est réservé aux zones A bis et A","Il s'applique aux maisons individuelles"],a:[0,1,2],w:"Successeur du Pinel, moins coûteux, social et fiscal. Pas de zone, mais les maisons individuelles sont exclues."},
{i:"f252_04",u:252,t:"slider",d:.3,q:"Jusqu'à la fin de quelle année peut-on acquérir un logement en Jeanbrun ?",min:2025,max:2032,step:1,a:2028,tol:0,pre:"",un:"",w:"Du 21 février 2026 au 31 décembre 2028 : une fenêtre de moins de trois ans."},
{i:"f252_05",u:252,t:"sort",d:.35,nw:"Les logements éligibles au Jeanbrun",q:"Éligible au Jeanbrun ou non ?",bins:["Éligible","Non éligible"],it:[["T2 neuf en VEFA dans un immeuble à Lille",0],["Maison individuelle neuve à Arras",1],["Appartement ancien, 35 % de travaux, classe B après",0],["Appartement ancien, 10 % de travaux, classe D",1],["T3 neuf dans une petite ville en zone C",0],["Maison ancienne rénovée en classe A",1]],w:"Immeubles collectifs uniquement, neufs ou anciens rénovés (30 % de travaux, classe A ou B). Aucune zone. Les maisons sont exclues."},
{i:"f252_06",u:252,t:"tf",d:.3,q:"Comme le Pinel, le Jeanbrun est réservé aux zones tendues A bis, A et B1.",a:false,w:"Aucune zone : le Jeanbrun s'applique partout en France. C'est une différence majeure avec le Pinel."},
{i:"f252_07",u:252,t:"num",d:.35,q:"Un appartement ancien coûte 160 000 €. Quel montant minimum de travaux faut-il pour le Jeanbrun ancien, en euros ?",a:48000,tol:1,un:" €",h:"30 % du prix d'achat",w:"30 % x 160 000 = 48 000 €, et la classe énergétique doit atteindre A ou B après travaux."},
{i:"f252_08",u:252,t:"fill",d:.35,q:"Dans l'ancien, après travaux, le logement doit atteindre la classe énergétique A ou ___.",o:["B","C","D","E"],a:0,w:"A ou B après des travaux d'au moins 30 % du prix. Un assouplissement était en discussion en septembre 2026."},
{i:"f252_09",u:252,t:"mcq",d:.4,nw:"L'amortissement Jeanbrun",q:"Sur quelle base se calcule l'amortissement Jeanbrun ?",o:["80 % du prix, hors terrain","100 % du prix, terrain compris","50 % du prix, hors frais","Le montant du prêt immobilier"],a:0,w:"Le terrain ne s'use pas : on amortit 80 % du prix."},
{i:"f252_10",u:252,t:"tiles",d:.35,q:"Reconstitue la formule qui oppose Pinel et Jeanbrun.",a:["Pinel","réduit","l'impôt,","Jeanbrun","réduit","le","revenu"],dd:["loyer,","augmente","la"],w:"Réduction d'impôt pour le Pinel, amortissement déduit des revenus fonciers pour le Jeanbrun."},
{i:"f252_11",u:252,t:"story",d:.4,q:"Que réponds-tu à Théo ?",sc:[{who:"Théo",txt:"Si le Jeanbrun déduit 7 000 € par an, Philippe paie 7 000 € d'impôt en moins, non ?"}],o:["Non : 7 000 € de revenus en moins, taxés à sa tranche","Oui, un amortissement se retire toujours de l'impôt, euro pour euro","Non : il paie 7 000 € de plus, puisque l'amortissement est taxé","Oui, mais seulement pendant la toute première année de location"],a:0,w:"À 30 % de tranche, 7 000 € d'amortissement économisent 2 100 € d'impôt sur le revenu, plus les prélèvements sociaux sur les loyers effacés."},
{i:"f252_12",u:252,t:"num",d:.45,q:"Philippe est dans la tranche à 30 %. L'amortissement de 7 000 € efface autant de loyers imposables. Combien économise-t-il d'impôt sur le revenu, hors prélèvements sociaux, en euros ?",a:2100,tol:1,un:" €",h:"Montant déduit x tranche",w:"7 000 x 30 % = 2 100 €. C'est pour ça qu'un amortissement vaut plus pour un contribuable fortement imposé."},
{i:"f252_13",u:252,t:"match",d:.4,nw:"Les taux et plafonds Jeanbrun",q:"Neuf : associe chaque niveau de loyer à son taux et son plafond.",p:[["Intermédiaire","3,5 %, 8 000 €"],["Social","4,5 %, 10 000 €"],["Très social","5,5 %, 12 000 €"],["Ancien rénové, tous niveaux","Plafond de 10 700 €"]],w:"Un point de plus, deux mille de plus. Dans l'ancien, un seul plafond : 10 700 €."},
{i:"f252_14",u:252,t:"num",d:.45,q:"Philippe : T2 neuf à 250 000 €, loyer intermédiaire. Quel amortissement annuel, en euros ?",a:7000,tol:1,un:" €",h:"80 % puis 3,5 %",w:"Base 200 000 €. 3,5 % x 200 000 = 7 000 €, sous le plafond de 8 000 €."},
{i:"f252_15",u:252,t:"num",d:.5,q:"Même T2 à 250 000 €, mais loué en très social. Quel amortissement annuel, en euros ?",a:11000,tol:1,un:" €",h:"5,5 % de la base",w:"5,5 % x 200 000 = 11 000 €, sous le plafond de 12 000 €."},
{i:"f252_16",u:252,t:"num",d:.5,q:"Un T3 neuf à 300 000 €, loyer intermédiaire. Quel amortissement annuel retenu, en euros ?",a:8000,tol:1,un:" €",h:"Vérifier le plafond",w:"Base 240 000 €, 3,5 % = 8 400 €, ramené au plafond de 8 000 €. Si l'amortissement dépasse les loyers nets, il crée un déficit foncier imputable jusqu'à 10 700 €."},
{i:"f252_17",u:252,t:"slider",d:.45,q:"Dans l'ancien rénové, loyer social, quel est le taux d'amortissement ?",min:2,max:6,step:.5,a:3.5,tol:0,pre:"",un:" %",w:"Ancien : 3 % intermédiaire, 3,5 % social, 4 % très social, plafond unique 10 700 €."},
{i:"f252_18",u:252,t:"mcq",d:.5,q:"Base amortissable de 300 000 € dans l'ancien, loyer très social. Quel amortissement annuel ?",o:["10 700 €","12 000 €","16 500 €","9 000 €"],a:0,w:"4 % x 300 000 = 12 000 €, ramené au plafond unique de l'ancien : 10 700 €."},
{i:"f252_19",u:252,t:"tf",d:.45,q:"Si l'amortissement crée un déficit foncier, ce déficit peut s'imputer sur le revenu global dans la limite de 10 700 € par an.",a:true,w:"C'est le plafond de droit commun du déficit foncier imputable sur le revenu global : 10 700 € par an."},
{i:"f252_20",u:252,t:"story",d:.5,q:"Rappel du module 5 : que réponds-tu ?",sc:[{who:"Philippe Vandamme",txt:"Pour mon ancien T2 Pinel, j'ai trouvé un nouveau locataire. Je peux maintenant le passer en Jeanbrun et cumuler ?"}],o:["Non : le Jeanbrun vise les acquisitions faites depuis le 21 février 2026","Oui : tout logement loué nu peut basculer en Jeanbrun à tout moment","Oui, à condition de le louer meublé pendant les neuf ans à venir","Oui, et l'amortissement s'ajoute à la réduction Pinel restante"],a:0,w:"Le Jeanbrun vise les logements acquis entre le 21 février 2026 et le 31 décembre 2028. Le T2 de 2019 reste en Pinel jusqu'au bout."},
{i:"f252_21",u:252,t:"sort",d:.5,nw:"Les interdictions Jeanbrun",q:"Philippe peut-il louer son T2 Jeanbrun à cette personne ?",bins:["Autorisé","Interdit"],it:[["Sa fille, étudiante hors de son foyer fiscal",1],["Son cousin germain",0],["Sa mère",1],["Son frère",1],["Une infirmière sans lien de parenté",0],["Son petit-fils",1]],w:"Famille jusqu'au 2e degré inclus interdite : enfants, parents, frères et sœurs, grands-parents, petits-enfants. Le cousin est au 4e degré : autorisé."},
{i:"f252_22",u:252,t:"tiles",d:.45,q:"Reconstitue la phrase mémo des interdits Jeanbrun.",a:["Mon","Frère","Dort","Chez","moi"],dd:["Cousin","Loue","Paie"],w:"M.F.D.C. : Meublé, Famille proche, Démembrement, Cumul Denormandie."},
{i:"f252_23",u:252,t:"multi",d:.5,q:"Qu'est-ce qui est interdit en Jeanbrun ?",o:["Louer meublé","Acheter un logement démembré","Cumuler avec le Denormandie","Louer à un membre du foyer fiscal","Louer à un cousin germain"],a:[0,1,2,3],w:"Meublé, démembrement, cumul Denormandie, foyer fiscal et famille jusqu'au 2e degré. Le cousin reste possible."},
{i:"f252_24",u:252,t:"fill",d:.45,q:"En Jeanbrun, la location est interdite à la famille jusqu'au ___ degré inclus.",o:["2e","1er","4e","6e"],a:0,w:"2e degré : parents, enfants, frères et sœurs, grands-parents, petits-enfants. Les cousins, au 4e degré, sont autorisés."},
{i:"f252_25",u:252,t:"story",d:.5,q:"Que réponds-tu à Philippe ?",sc:[{who:"Philippe Vandamme",txt:"Si ma locataire trouve un poste à Lyon au bout de deux ans, elle est coincée neuf ans par le Jeanbrun ?"}],o:["Non : c'est vous qui vous engagez 9 ans, elle peut partir avec un préavis","Oui : le bail Jeanbrun est un bail de neuf ans que le locataire doit respecter","Oui, sauf si elle a eu un enfant, seul motif de départ anticipé","Non, mais vous perdez alors tout l'avantage fiscal obtenu"],a:0,w:"L'engagement de 9 ans est celui du propriétaire. Le locataire a un bail classique et peut partir. On reloue aux mêmes conditions."},
{i:"f252_26",u:252,t:"tf",d:.5,q:"Les ressources du locataire Jeanbrun sont appréciées à la signature du bail.",a:true,w:"Comme au Pinel, le contrôle se fait à l'entrée. Les notes le rappellent : revenus appréciés à la signature."},
{i:"f252_27",u:252,t:"mcq",d:.5,q:"Que se passe-t-il pour les amortissements quand Philippe revend son T2 Jeanbrun ?",o:["Ils sont réintégrés dans la plus-value","Ils sont effacés sans aucune conséquence","Ils sont remboursés en une fois par l'État","Ils s'imputent sur la taxe foncière"],a:0,w:"Les amortissements déduits sont réintégrés dans le calcul de la plus-value : l'avantage est en partie repris à la sortie."},
{i:"f252_28",u:252,t:"story",d:.55,q:"Que réponds-tu à Théo ?",sc:[{who:"Théo",txt:"Les notes disent que le Jeanbrun est compatible avec une SCI à l'IS. Donc on met tout en SCI à l'IS ?"}],o:["Prudence : c'est un outil de revenus fonciers, pensé pour l'IR","Oui : une SCI à l'IS double l'amortissement Jeanbrun chaque année","Oui : seule une SCI à l'IS peut détenir un logement Jeanbrun","Non : le Jeanbrun est interdit à toute forme de société"],a:0,w:"Une SCI à l'IS amortit déjà selon les règles de l'IS. Pour le cumul avec le LLI, les sources consultées recommandent une SCI à l'IR."},
{i:"f252_29",u:252,t:"match",d:.5,q:"Rappel des modules 4 et 6 : Pinel ou Jeanbrun ?",p:[["Réduction d'impôt","Pinel"],["Amortissement sur 80 % du prix","Jeanbrun"],["Zones A bis, A, B1","Pinel"],["Aucune zone, immeubles collectifs","Jeanbrun"]],w:"Pinel réduit l'impôt, en zone tendue. Jeanbrun réduit le revenu, partout, en collectif."},
{i:"f252_30",u:252,t:"order",d:.5,q:"Remets dans l'ordre le calcul de l'avantage Jeanbrun de Philippe.",it:["Vérifier l'éligibilité du logement","Calculer la base de 80 %","Appliquer le taux du niveau de loyer","Plafonner selon le niveau","Déduire l'amortissement des revenus fonciers"],w:"Éligibilité, base, taux, plafond, déduction. L'économie finale dépend de la tranche d'imposition."},
{i:"f252_31",u:252,t:"story",d:.6,q:"Synthèse : un client de 50 ans veut préparer sa retraite en 2026.",sc:[{who:"Client",txt:"Je voulais faire comme mon père avec son Pinel : louer neuf ans, puis habiter le logement à la retraite."}],o:["Le Jeanbrun permet la même logique : 9 ans de location nue, puis vous récupérez","Impossible : un logement Jeanbrun ne peut jamais être habité par son propriétaire","Il faut attendre le retour du Pinel, prévu pour 2029 selon le gouvernement","Achetez une maison individuelle, c'est le cas idéal pour le Jeanbrun"],a:0,w:"La stratégie retraite du prof survit avec le Jeanbrun : 9 ans d'engagement, puis le bien se libère. Attention, pas de maison individuelle."},
{i:"f252_32",u:252,t:"story",d:.6,q:"Synthèse : Nathalie te demande l'avantage de Philippe en une phrase.",sc:[{who:"Nathalie Wattel",txt:"250 000 euros, neuf, loyer intermédiaire. Résume."}],o:["« 7 000 € par an déduits de ses loyers pendant 9 ans, repris en partie à la revente »","« 4 400 € par an retirés de son impôt pendant 9 ans, sans rien rendre à la revente »","« 12 000 € par an retirés de son impôt, car il n'y a pas de plafond dans le neuf »","« Une TVA à 10 % et un crédit de taxe foncière, sans aucune condition de loyer »"],a:0,w:"80 % x 250 000 x 3,5 % = 7 000 €, déduits des revenus fonciers, réintégrés dans la plus-value à la revente. La TVA à 10 %, c'est le LLI (module 7)."}
