/*UNIT*/
{id:254,c:"FISCA",n:"Module 8",t:"Prêt à taux zéro : qui y a droit, combien, et quand on peut louer",col:"--green",ic:"🔑",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Vérifier les <b>conditions d'accès</b> au PTZ : primo-accédant, résidence principale, ressources.</li>
<li>Dire quels <b>logements</b> sont éligibles.</li>
<li>Estimer le <b>montant</b> et la <b>durée</b> selon la tranche de revenus.</li>
<li>Appliquer les <b>contraintes de financement</b>.</li>
<li>Savoir quand la <b>location</b> est permise, et à quelles conditions.</li></ul>
<h3>Le PTZ des Benali</h3>
<div class="gstory">Retour en 2026, au dossier de financement du T3 de Fives. Yanis a entendu parler du prêt à taux zéro à la machine à café : « Un prêt sans intérêt, c'est trop beau. Il y a forcément un piège. » Camille, elle, a une autre question : « Et si on doit partir à Rennes pour mon travail dans trois ans, on pourra louer l'appartement ? » Nathalie te glisse : « Le PTZ, c'est un cadeau avec un mode d'emploi. Lis-le-leur. »</div>
<p>Le <b>prêt à taux zéro</b> (PTZ) est un prêt <b>sans intérêts ni frais de dossier</b>, dont l'État paie les intérêts à la banque. Il complète le prêt principal pour l'achat d'une <b>résidence principale</b>.</p>
<h3>Les conditions d'accès</h3>
<ul><li><b>Résidence principale</b> uniquement : pas d'investissement locatif, pas de résidence secondaire.</li>
<li><b>Primo-accédant</b> : ne pas avoir été propriétaire de sa résidence principale au cours des <b>deux dernières années</b>.</li>
<li>En <b>couple</b>, les <b>deux</b> doivent être primo-accédants.</li>
<li>Respecter un <b>plafond de ressources</b>, fixé selon la zone et la taille du foyer. On retient le <b>revenu fiscal de référence de l'année N-2</b>.</li></ul>
<table><tr><th>Plafond 2026, une personne</th><th>Montant</th></tr>
<tr><td>Zone A et A bis</td><td>49 000 €</td></tr>
<tr><td>Zone B1</td><td>34 500 €</td></tr>
<tr><td>Zone B2</td><td>31 500 €</td></tr>
<tr><td>Zone C</td><td>28 500 €</td></tr></table>
<p>Pour un couple, on multiplie par 1,5 : en zone B1, <b>51 750 euros</b>. Les repères des notes (environ 33 000 euros pour un célibataire, 50 000 euros pour un couple) correspondent à peu près à la zone B1.</p>
<div class="gmnemo">Le PTZ se mérite en <b>P.R.I.M.O.</b> : <b>P</b>rimo-accédant, <b>R</b>ésidence principale, <b>I</b>mpôt N-2 sous le plafond, <b>M</b>ontant pas plus gros que les autres prêts, <b>O</b>ccupation 6 ans.</div>
<h3>Les logements éligibles</h3>
<ul><li><b>Neuf</b> : appartement ou maison, partout en France depuis le <b>1er avril 2025</b>.</li>
<li><b>Ancien avec travaux</b> (au moins 25 % du coût total), dans les zones <b>B2 et C</b>.</li>
<li><b>Logement social</b> vendu à ses occupants.</li></ul>
<div class="gtrap">Les notes disent « neuf, et ancien uniquement à caractère social ». C'est incomplet : l'ancien avec travaux est aussi éligible dans les zones B2 et C. Les notes disent aussi que le PTZ a été « créé en 2011 ». Le PTZ date de <b>1995</b>. En 2011, il est devenu le <b>PTZ+</b>, qui a en effet ouvert la voie aux durées longues.</div>
<h3>Le montant et la durée</h3>
<p>Le PTZ finance un <b>pourcentage du prix</b> (la quotité), appliqué à un <b>coût plafonné</b>. Exemple de plafond : <b>150 000 euros</b> pour une personne seule en zone A.</p>
<table><tr><th>Tranche de revenus</th><th>Quotité (neuf collectif)</th><th>Durée totale</th><th>Dont différé</th></tr>
<tr><td>1 (les plus modestes)</td><td>50 %</td><td>25 ans</td><td>10 ans</td></tr>
<tr><td>2</td><td>40 %</td><td>20 ans</td><td>8 ans</td></tr>
<tr><td>3</td><td>40 %</td><td>15 ans</td><td>2 ans</td></tr>
<tr><td>4 (les plus aisés)</td><td>20 %</td><td>10 ans</td><td>aucun</td></tr></table>
<p>Le <b>différé</b> est une période pendant laquelle on ne rembourse rien du PTZ : on paie d'abord le prêt principal.</p>
<div class="gtrap">Les notes parlent de 12 ans pour les ménages aisés. Avec le barème en vigueur en 2026, la durée va de <b>10 ans</b> (tranche 4) à <b>25 ans</b> (tranche 1). Le principe des notes reste juste : plus on est modeste, plus c'est long, avec un différé.</div>
<h3>Les contraintes de financement</h3>
<ul><li>Le montant du PTZ ne peut pas dépasser le montant des <b>autres prêts</b> de plus de deux ans. Le PTZ n'est donc jamais la part majoritaire du financement.</li>
<li>Les notes ajoutent que sa durée ne dépasse pas celle des autres prêts. C'est une exigence fréquente des banques. Retiens surtout la règle du montant.</li></ul>
<div class="formula">Benali : coût retenu 210 000 €, quotité 40 %
PTZ = 84 000 €
Prêt principal de 166 000 € : 84 000 ≤ 166 000, règle respectée</div>
<h3>Habiter, ou louer par exception</h3>
<p>Le logement doit rester la <b>résidence principale</b> pendant <b>6 ans</b>. La location, même d'une chambre, est interdite pendant ce temps, sauf exceptions.</p>
<ul><li><b>Mobilité professionnelle</b> : plus de <b>50 km</b> ou plus d'<b>1 h 30</b> de trajet. En couple, les deux doivent partir et libérer le bien.</li>
<li><b>Décès</b> d'un des accédants.</li>
<li><b>Chômage</b> de plus d'<b>un an</b>.</li>
<li>Divorce, rupture de PACS, invalidité.</li></ul>
<p>Pendant cette location exceptionnelle : durée limitée, locataire sous les <b>plafonds du logement social</b>, <b>loyer social</b> imposé. Sortie de secours : <b>rembourser le PTZ</b> pour louer librement.</p>
<div class="gtrap">Les notes disent qu'il faut habiter le bien « pendant la durée du prêt ». L'obligation légale est de <b>6 ans</b>. Les notes parlent aussi d'une mutation « au sein de la même entreprise » : le texte vise la <b>mobilité professionnelle</b> avec un critère de distance. Vérifie le cas précis avec la banque.</div>
<h3>L'avenir du PTZ</h3>
<p>Le PTZ coûte cher à l'État. Le prof le voit aller vers la restriction, voire la disparition. En 2025, il a pourtant été <b>élargi</b> au neuf partout en France, et il est prolongé jusqu'au <b>31 décembre 2027</b>. Il faut aller au bout de l'opération : un PTZ remboursé trop tôt perd son intérêt.</p>
<h3>Ce que tu dois retenir pour l'examen</h3>
<ul><li>P.R.I.M.O. : primo-accédant, résidence principale, ressources N-2, montant plafonné, 6 ans d'occupation.</li>
<li>10 à 25 ans selon la tranche, avec différé pour les plus modestes.</li>
<li>Location interdite sauf mobilité, décès, chômage long, avec loyer social.</li></ul>`},
/*EXOS*/
{i:"f254_01",u:254,t:"story",d:.3,nw:"Le prêt à taux zéro",q:"Que réponds-tu à Yanis ?",sc:[{who:"Yanis Benali",txt:"Un prêt sans intérêt ? La banque se paie forcément quelque part."}],o:["C'est l'État qui paie les intérêts à la banque","La banque ajoute des frais de dossier très élevés","Les intérêts sont payés en une fois à la fin","Le PTZ est financé par une hausse du prix"],a:0,w:"Sans intérêts ni frais de dossier : l'État compense la banque. Le cadeau a un mode d'emploi, c'est P.R.I.M.O."},
{i:"f254_02",u:254,t:"multi",d:.3,nw:"Les conditions du PTZ",q:"Quelles conditions faut-il remplir pour obtenir un PTZ ?",o:["Acheter sa résidence principale","Être primo-accédant","Respecter un plafond de ressources","Avoir moins de 35 ans","Acheter pour louer"],a:[0,1,2],w:"Résidence principale, primo-accédant, ressources N-2 sous le plafond. Il n'y a pas de condition d'âge."},
{i:"f254_03",u:254,t:"slider",d:.3,q:"Pour être primo-accédant, combien d'années faut-il ne pas avoir été propriétaire de sa résidence principale ?",min:0,max:10,step:1,a:2,tol:0,pre:"",un:" ans",w:"Deux ans avant l'offre de prêt. Et en couple, les deux doivent l'être."},
{i:"f254_04",u:254,t:"story",d:.35,q:"Que réponds-tu ?",ctx:"Sarah et Tom, un autre couple de clients, achètent un T2 neuf à Tourcoing.",sc:[{who:"Sarah",txt:"Moi je n'ai jamais rien acheté. Tom a vendu son studio de Roubaix il y a un an. On a droit au PTZ ?"}],o:["Non : en couple, les deux doivent être primo-accédants","Oui : il suffit qu'un seul des deux soit primo-accédant","Oui, mais le PTZ sera calculé sur la moitié du prix","Oui, puisque le studio a été vendu avant l'achat"],a:0,w:"Tom était propriétaire de sa résidence principale il y a un an : il n'est pas primo-accédant. Il aurait fallu deux ans."},
{i:"f254_05",u:254,t:"mcq",d:.35,q:"Quels revenus retient-on pour le plafond de ressources du PTZ ?",o:["Le revenu fiscal de référence N-2","Le salaire net du dernier mois travaillé","Les revenus de l'année en cours","Le patrimoine total du foyer"],a:0,w:"Revenu fiscal de référence de l'année N-2, comme pour les locataires Pinel."},
{i:"f254_06",u:254,t:"match",d:.4,q:"Associe chaque zone au plafond de ressources 2026 d'une personne seule.",p:[["Zone A","49 000 €"],["Zone B1","34 500 €"],["Zone B2","31 500 €"],["Zone C","28 500 €"]],w:"Plus la zone est tendue, plus le plafond est haut. Le repère des notes (33 000 €) est proche de la zone B1."},
{i:"f254_07",u:254,t:"num",d:.4,q:"En zone B1, le plafond d'une personne seule est de 34 500 €. Quel est le plafond pour un couple (coefficient 1,5), en euros ?",a:51750,tol:1,un:" €",h:"x 1,5",w:"34 500 x 1,5 = 51 750 €. Le repère des notes, environ 50 000 € pour un couple, correspond à peu près."},
{i:"f254_08",u:254,t:"tiles",d:.35,q:"Reconstitue les conditions mémo du PTZ.",a:["Primo-accédant,","Résidence","principale,","Impôt","N-2,","Montant,","Occupation"],dd:["Meublé,","Investissement,","N-1,"],w:"P.R.I.M.O. : Primo-accédant, Résidence principale, Impôt N-2, Montant, Occupation 6 ans."},
{i:"f254_09",u:254,t:"sort",d:.4,nw:"Les logements éligibles au PTZ",q:"Ce logement peut-il être financé par un PTZ en 2026 ?",bins:["Éligible","Non éligible"],it:[["Appartement neuf à Lille",0],["Maison neuve à Arras",0],["Ancien sans travaux à Lille",1],["Ancien avec 30 % de travaux en zone C",0],["Studio neuf acheté pour être loué",1],["Logement HLM vendu à son occupant",0]],w:"Neuf partout depuis avril 2025, ancien avec travaux en B2 et C, logement social vendu à l'occupant. Jamais d'investissement locatif."},
{i:"f254_10",u:254,t:"tf",d:.35,q:"Depuis avril 2025, une maison individuelle neuve peut être financée par un PTZ partout en France.",a:true,w:"Le PTZ a été élargi au neuf, collectif comme individuel, sur tout le territoire."},
{i:"f254_11",u:254,t:"story",d:.4,q:"Que réponds-tu à Théo ?",sc:[{who:"Théo",txt:"Les notes disent que le PTZ a été créé en 2011. Je le mets sur la fiche ?"}],o:["Non : le PTZ date de 1995, 2011 est l'année du PTZ+","Oui : il a bien été créé en 2011 par la loi Pinel","Non : il a été créé en 2025 avec l'élargissement au neuf","Oui : avant 2011, aucun prêt aidé n'existait"],a:0,w:"PTZ en 1995, PTZ+ en 2011, qui a ouvert la voie aux durées longues."},
{i:"f254_12",u:254,t:"fill",d:.4,q:"Dans l'ancien, le PTZ exige des travaux d'au moins ___ du coût total, en zones B2 et C.",o:["25 %","10 %","50 %","5 %"],a:0,w:"Ancien avec au moins 25 % de travaux, en zones détendues B2 et C."},
{i:"f254_13",u:254,t:"match",d:.4,nw:"La durée du PTZ",q:"Associe chaque tranche à la durée totale du PTZ.",p:[["Tranche 1","25 ans, dont 10 de différé"],["Tranche 2","20 ans, dont 8 de différé"],["Tranche 3","15 ans, dont 2 de différé"],["Tranche 4","10 ans, sans différé"]],w:"Plus on est modeste, plus c'est long, avec un différé plus long."},
{i:"f254_14",u:254,t:"mcq",d:.4,q:"Qu'est-ce que le différé de remboursement ?",o:["Une période sans rembourser le PTZ","Une remise d'une partie du capital","Un taux d'intérêt réduit au départ","Un délai pour signer chez le notaire"],a:0,w:"Pendant le différé, on ne rembourse rien du PTZ : on paie d'abord le prêt principal."},
{i:"f254_15",u:254,t:"slider",d:.45,q:"Durée maximale d'un PTZ pour les ménages les plus modestes (tranche 1) ?",min:5,max:30,step:1,a:25,tol:0,pre:"",un:" ans",w:"25 ans, dont 10 ans de différé. Les notes disaient 12 ans pour les aisés : c'est aujourd'hui 10 ans en tranche 4."},
{i:"f254_16",u:254,t:"tf",d:.4,q:"Un ménage de la tranche 4 bénéficie d'un différé de 10 ans.",a:false,w:"La tranche 4, la plus aisée, rembourse sur 10 ans sans aucun différé."},
{i:"f254_17",u:254,t:"num",d:.45,nw:"Le montant du PTZ",q:"Coût retenu plafonné : 210 000 €. Quotité : 40 %. Quel est le montant du PTZ, en euros ?",a:84000,tol:1,un:" €",h:"Coût x quotité",w:"210 000 x 40 % = 84 000 €. Il faut ensuite vérifier que ce montant ne dépasse pas les autres prêts de plus de deux ans."},
{i:"f254_18",u:254,t:"story",d:.45,q:"Que réponds-tu ?",ctx:"Un couple finance 200 000 € : PTZ de 80 000 €, prêt principal de 70 000 €, apport de 50 000 €.",sc:[{who:"Couple",txt:"On a un gros apport, donc on emprunte peu à la banque. Ça ne pose pas de problème ?"}],o:["Si : le PTZ ne peut pas dépasser les autres prêts de plus de deux ans","Non : le PTZ peut financer seul toute l'opération","Non, le PTZ doit simplement rester sous 100 000 €","Si : l'apport doit être au moins égal au montant du PTZ"],a:0,w:"80 000 € de PTZ contre 70 000 € d'autres prêts : c'est interdit. Le PTZ ne peut pas être la part majoritaire."},
{i:"f254_19",u:254,t:"fill",d:.45,q:"Le montant du PTZ ne peut pas dépasser le montant des autres prêts d'une durée de plus de ___ ans.",o:["deux","cinq","dix","quinze"],a:0,w:"Plus de deux ans. Le PTZ reste un prêt complémentaire."},
{i:"f254_20",u:254,t:"slider",d:.45,q:"Plafond de coût d'opération d'une personne seule en zone A, en milliers d'euros (repère des notes) ?",min:50,max:300,step:10,a:150,tol:0,pre:"",un:" k€",w:"150 000 € pour une personne seule en zone A. La quotité s'applique à ce coût plafonné."},
{i:"f254_21",u:254,t:"story",d:.5,nw:"La location d'un logement financé par PTZ",q:"Que réponds-tu à Camille ?",sc:[{who:"Camille Benali",txt:"Si je suis mutée à Rennes dans trois ans, on peut louer l'appartement ?"}],o:["Oui, par exception : plus de 50 km, et les deux partent, avec un loyer social","Non, jamais : un logement PTZ ne se loue sous aucun prétexte","Oui, librement, au prix du marché, dès la première année","Oui, mais seulement une chambre, en gardant l'appartement pour vous"],a:0,w:"Mobilité professionnelle à plus de 50 km ou 1 h 30 : location possible, mais les deux partent, loyer social, locataire sous plafonds."},
{i:"f254_22",u:254,t:"slider",d:.45,q:"Pendant combien d'années le logement doit-il rester la résidence principale ?",min:1,max:25,step:1,a:6,tol:0,pre:"",un:" ans",w:"Six ans. Les notes parlent de toute la durée du prêt : c'est plus strict que la règle."},
{i:"f254_23",u:254,t:"sort",d:.5,q:"Location autorisée par exception ou non ?",bins:["Exception admise","Location interdite"],it:[["Mutation à 400 km, le couple déménage",0],["Chômage de 14 mois",0],["Décès d'un des deux acheteurs",0],["On reste et on loue la chambre d'ami",1],["Envie de déménager à 10 km",1],["Nouvel emploi à 20 minutes",1]],w:"Mobilité à plus de 50 km ou 1 h 30, décès, chômage de plus d'un an. Louer une chambre en restant est interdit. Ce sont les exceptions de mobilité professionnelle, de décès et de chômage."},
{i:"f254_24",u:254,t:"multi",d:.5,q:"Quelles conditions s'appliquent pendant une location exceptionnelle ?",o:["Une durée limitée","Un locataire sous les plafonds du logement social","Un loyer social imposé","Un loyer libre au prix du marché","Un bail meublé obligatoire"],a:[0,1,2],w:"Location temporaire, locataire social, loyer social. Pour louer librement, il faut rembourser le PTZ."},
{i:"f254_25",u:254,t:"story",d:.5,q:"Que conseilles-tu ?",ctx:"Après 4 ans, un couple déménage à 15 km pour se rapprocher de ses parents et veut louer au prix du marché.",sc:[{who:"Couple",txt:"Aucune exception ne marche pour nous. On est coincés ?"}],o:["Vous pouvez rembourser le PTZ, puis louer librement","Vous pouvez louer, le PTZ se transforme en prêt à 4 %","Vous pouvez louer, les 6 ans sont une simple recommandation","Vous devez revendre le logement dans l'année"],a:0,w:"La sortie de secours : solder le PTZ. On perd l'avantage, mais on retrouve sa liberté."},
{i:"f254_26",u:254,t:"tf",d:.5,q:"Au-delà de six ans, les contraintes d'occupation du PTZ tombent.",a:true,w:"L'obligation de résidence principale dure six ans. Les notes disent « la durée du prêt » : c'est inexact."},
{i:"f254_27",u:254,t:"order",d:.45,q:"Remets dans l'ordre l'analyse d'un dossier PTZ.",it:["Vérifier que chacun est primo-accédant","Comparer le revenu N-2 au plafond de la zone","Vérifier l'éligibilité du logement","Calculer la quotité sur le coût plafonné","Vérifier que le PTZ ne dépasse pas les autres prêts"],w:"Personnes, ressources, logement, montant, financement : P.R.I.M.O. dans le bon ordre."},
{i:"f254_28",u:254,t:"story",d:.55,q:"Rappel du module 1 : que réponds-tu ?",sc:[{who:"Yanis Benali",txt:"La banque nous accorde 175 000 € au lieu des 200 000 € prévus, PTZ compris. On peut se retirer de la réservation ?"}],o:["Oui : les prêts baissent de 12,5 %, plus de 10 %, dépôt rendu","Non : une baisse du prêt ne libère jamais l'acheteur","Oui, mais le promoteur garde la moitié du dépôt","Non : il faudrait un refus total de la banque"],a:0,w:"Le P du Prêt : baisse de plus de 10 % par rapport aux prêts prévus. 25 000 sur 200 000, c'est 12,5 %."},
{i:"f254_29",u:254,t:"mcq",d:.5,q:"Jusqu'à quand le PTZ est-il prolongé à ce jour ?",o:["31 décembre 2027","31 décembre 2024","31 décembre 2030","Sans date de fin"],a:0,w:"Prolongé jusqu'au 31 décembre 2027. Le prof le voit à terme restreint, voire supprimé, car il coûte cher."},
{i:"f254_30",u:254,t:"mcq",d:.55,q:"Rappel du module 6 : Philippe, déjà propriétaire de sa résidence principale, veut un PTZ pour son T2 Jeanbrun.",o:["Impossible : ni primo-accédant, ni résidence principale","Possible, le PTZ finance aussi l'investissement locatif","Possible, à condition de louer en loyer très social","Possible, puisque le Jeanbrun est un dispositif d'État"],a:0,w:"Le PTZ finance une résidence principale de primo-accédant. Un investissement Jeanbrun n'y a jamais droit."},
{i:"f254_31",u:254,t:"match",d:.55,q:"Associe chaque erreur des notes à la bonne règle.",p:[["Créé en 2011","Créé en 1995, PTZ+ en 2011"],["Habiter pendant tout le prêt","Habiter 6 ans"],["12 ans pour les aisés","10 ans en tranche 4"],["Ancien seulement social","Ancien avec travaux en B2 et C aussi"]],w:"Quatre corrections à connaître pour ne pas recopier les notes."},
{i:"f254_32",u:254,t:"story",d:.6,q:"Synthèse : Nathalie te demande le mode d'emploi du PTZ en une phrase.",sc:[{who:"Nathalie Wattel",txt:"Pour les Benali, une phrase."}],o:["« Deux primo-accédants, sous plafond N-2, un PTZ minoritaire, et 6 ans d'occupation »","« Un seul primo-accédant suffit, pas de plafond, et on loue librement dès l'achat »","« Un prêt à 1 %, accordé à tous, pour tout logement, remboursé en 12 ans »","« Un prêt pour investir, sans condition, à rembourser dès la première année »"],a:0,w:"P.R.I.M.O. appliqué aux Benali : Primo-accédants tous les deux, Résidence principale, Impôt N-2, Montant minoritaire, Occupation 6 ans."}
