/*UNIT*/
{id:257,c:"FISCA",n:"Module 11",t:"SCPI : souscrire, revendre, emprunter et payer l'impôt",col:"--blue",ic:"🧾",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Lister les <b>documents</b> à remettre avant et pendant l'investissement.</li>
<li>Distinguer <b>souscription</b> et <b>achat de gré à gré</b>, et expliquer le <b>délai de jouissance</b>.</li>
<li>Expliquer pourquoi <b>revendre</b> peut être difficile.</li>
<li>Évaluer un achat de parts <b>à crédit</b>.</li>
<li>Appliquer la <b>fiscalité</b> : revenus fonciers, revenus financiers, plus-value.</li></ul>
<h3>Sandrine signe</h3>
<div class="gstory">Sandrine a choisi trois SCPI. Au moment de signer, le conseiller d'une banque concurrente lui avait seulement tendu un bulletin de souscription : « Signez là, le reste est sur Internet. » Nathalie est catégorique : « Chez nous, on remet tout, on fait signer un récépissé, et on explique l'impôt. Le jour où la SCPI baisse, c'est ce dossier qui nous protège, elle et nous. »</div>
<h3>Les documents obligatoires</h3>
<table><tr><th>Document</th><th>Ce qu'il apporte</th></tr>
<tr><td><b>Note d'information</b> (visée par l'AMF)</td><td>Les caractéristiques essentielles, le type d'immobilier, les frais</td></tr>
<tr><td><b>Statuts</b></td><td>Les règles de fonctionnement de la société</td></tr>
<tr><td><b>Document d'informations clés</b> (DIC)</td><td>Risques, coûts et scénarios de performance, en trois pages</td></tr>
<tr><td><b>Dernier rapport annuel</b></td><td>Résultats passés, situation actuelle, perspectives</td></tr>
<tr><td><b>Bulletin d'information</b> périodique</td><td>Le suivi régulier de la SCPI, en général chaque trimestre</td></tr>
<tr><td><b>Bulletin de souscription</b></td><td>Formalise l'achat : nombre de parts, prix</td></tr></table>
<p>Ces documents doivent être remis <b>avant</b> la souscription. S'ils manquent, la <b>responsabilité du vendeur</b> peut être engagée en cas de problème.</p>
<div class="gmnemo">Avant de signer, <b>« NoS DRôles de 2 B »</b> : <b>No</b>te d'information, <b>S</b>tatuts, <b>D</b>IC, <b>R</b>apport annuel, et les <b>2 B</b>ulletins (information et souscription).</div>
<h3>Acheter des parts</h3>
<ul><li>Par <b>souscription</b> : la SCPI émet de nouvelles parts, lors d'une <b>augmentation de capital</b> ou en continu pour les SCPI à capital variable.</li>
<li>De <b>gré à gré</b> ou sur le <b>marché secondaire</b> : on rachète les parts d'un associé qui vend, souvent par un intermédiaire (banque, société de gestion).</li>
<li>Les <b>frais de souscription</b> sont élevés : souvent <b>8 à 12 %</b> du prix. C'est une raison de plus pour garder longtemps.</li></ul>
<p>Le <b>délai de jouissance</b> est la période entre l'achat et le premier revenu : souvent <b>3 à 6 mois</b>. On est bien associé, mais les parts ne rapportent pas encore.</p>
<div class="gtrap">Les notes parlent d'un « délai de carence » où l'on ne devient pas propriétaire, à propos du gré à gré. Le bon terme est <b>délai de jouissance</b>. L'associé est propriétaire de ses parts dès l'achat. Ce sont les <b>revenus</b> qui démarrent plus tard, et ce délai concerne surtout la <b>souscription</b> de parts nouvelles.</div>
<h3>Revendre ses parts</h3>
<ul><li>L'associé demande à vendre (on parle de <b>retrait</b> dans une SCPI à capital variable).</li>
<li>La difficulté : trouver un <b>acheteur</b>. Si beaucoup d'associés veulent sortir en même temps, les parts restent <b>en attente</b>.</li>
<li>Exemple : en 2026, Pierval Santé avait 2,9 % de son patrimoine en parts en attente de retrait.</li></ul>
<h3>Acheter à crédit</h3>
<p>On peut acheter <b>comptant</b> ou avec un <b>prêt</b>. Les revenus distribués aident à rembourser, comme un appartement dont le loyer paie la mensualité. Les <b>intérêts d'emprunt</b> se déduisent des revenus fonciers au régime réel.</p>
<div class="gtrap">Les revenus d'une SCPI <b>ne sont pas garantis</b>. Si la distribution baisse, la mensualité, elle, reste la même.</div>
<h3>La fiscalité des SCPI</h3>
<table><tr><th>Revenu</th><th>Imposition (2026)</th></tr>
<tr><td><b>Loyers</b> (quote-part)</td><td>Revenus fonciers : barème de l'impôt + <b>17,2 %</b> de prélèvements sociaux</td></tr>
<tr><td><b>Produits financiers</b> (trésorerie placée)</td><td><b>PFU de 31,4 %</b> (12,8 % d'impôt + 18,6 % de prélèvements sociaux)</td></tr>
<tr><td><b>Plus-value</b> à la revente des parts</td><td>19 % + 17,2 %, avec abattements selon la durée de détention</td></tr></table>
<ul><li><b>Micro-foncier</b> : abattement de <b>30 %</b> si le total des revenus fonciers ne dépasse pas <b>15 000 euros</b>. Avec des SCPI, il faut aussi détenir en direct un logement loué nu.</li>
<li>Sinon, régime <b>réel</b> : on déduit les charges et les intérêts d'emprunt.</li>
<li>Plus-value : exonérée d'impôt sur le revenu après <b>22 ans</b> de détention, de prélèvements sociaux après <b>30 ans</b>.</li>
<li>Les SCPI investies à l'étranger : les loyers sont imposés dans le pays de l'immeuble, et échappent en principe aux prélèvements sociaux français.</li></ul>
<div class="gmnemo"><b>« 22 pour l'impôt, 30 pour le social »</b> : la plus-value immobilière s'efface par étapes. Et pour les revenus : les <b>loyers</b> vont au barème, la <b>trésorerie</b> au PFU.</div>
<div class="formula">Sandrine, tranche à 30 %, 5 000 € de loyers au régime réel sans charges
Impôt : 30 % x 5 000 = 1 500 €
Prélèvements sociaux : 17,2 % x 5 000 = 860 €
Net : 5 000 - 2 360 = 2 640 €</div>
<h3>Ce que tu dois retenir pour l'examen</h3>
<ul><li>Documents : NoS DRôles de 2 B, remis avant la souscription.</li>
<li>Souscription ou gré à gré, délai de jouissance de 3 à 6 mois.</li>
<li>Revente difficile si le marché manque d'acheteurs. Crédit possible, revenus non garantis.</li>
<li>Loyers : barème + 17,2 %. Trésorerie : PFU 31,4 %. Plus-value : 22 ans et 30 ans.</li></ul>`},
/*EXOS*/
{i:"f257_01",u:257,t:"multi",d:.3,nw:"Les documents obligatoires d'une SCPI",q:"Quels documents Sandrine doit-elle recevoir avant de souscrire ?",o:["La note d'information","Les statuts","Le document d'informations clés, ou DIC","Le dernier rapport annuel","Son avis d'impôt de l'année"],a:[0,1,2,3],w:"Note, Statuts, DIC, Rapport annuel, Bulletins. L'avis d'impôt n'est pas un document de la SCPI."},
{i:"f257_02",u:257,t:"match",d:.3,q:"Associe chaque document à son contenu.",p:[["Note d'information","Caractéristiques et type d'immobilier"],["Statuts","Règles de fonctionnement"],["Rapport annuel","Résultats et perspectives"],["Bulletin de souscription","Nombre de parts et prix"]],w:"Chaque document répond à une question de l'investisseur."},
{i:"f257_03",u:257,t:"tiles",d:.35,q:"Reconstitue la phrase mémo des documents.",a:["NoS","DRôles","de","2","B"],dd:["3","C","FoUs"],w:"Note, Statuts, DIC, Rapport, et les 2 Bulletins."},
{i:"f257_04",u:257,t:"story",d:.35,q:"Que dis-tu à Sandrine ?",sc:[{who:"Sandrine Duhamel",txt:"L'autre banque m'a juste fait signer le bulletin, en disant que le reste était sur Internet. C'est grave ?"}],o:["Oui : tout doit être remis avant, sinon sa responsabilité joue","Non : seul le bulletin de souscription a une valeur juridique","Non : l'AMF envoie elle-même les documents après la signature","Oui : la souscription est nulle et l'argent est rendu d'office"],a:0,w:"Remise préalable obligatoire. À défaut, la responsabilité du vendeur peut être engagée si la SCPI tourne mal."},
{i:"f257_05",u:257,t:"fill",d:.35,q:"La note d'information d'une SCPI reçoit le visa de l'___.",o:["AMF","ASPIM","INSEE","ACPR"],a:0,w:"L'Autorité des marchés financiers vise la note d'information. L'ASPIM est l'association professionnelle du secteur."},
{i:"f257_06",u:257,t:"tf",d:.35,q:"Le bulletin d'information est envoyé aux associés, en général chaque trimestre.",a:true,w:"Il permet de suivre la SCPI et d'aider l'associé à décider de garder ou de vendre."},
{i:"f257_07",u:257,t:"mcq",d:.4,q:"Quel document présente en trois pages les risques, les coûts et des scénarios de performance ?",o:["Le document d'informations clés, ou DIC","Le bulletin de souscription des parts","Les statuts de la SCPI","Le procès-verbal d'AG"],a:0,w:"Le DIC, document standardisé européen, permet de comparer les produits entre eux."},
{i:"f257_08",u:257,t:"sort",d:.4,q:"Avant ou pendant l'investissement ?",bins:["Remis avant la souscription","Reçu pendant la détention"],it:[["Note d'information",0],["Statuts",0],["DIC",0],["Bulletin trimestriel suivant",1],["Rapport annuel de l'année suivante",1],["Convocation à l'assemblée générale",1]],w:"Avant : de quoi comprendre le produit. Pendant : de quoi le suivre et voter."},
{i:"f257_09",u:257,t:"sort",d:.4,nw:"Souscription et gré à gré",q:"Souscription ou achat de gré à gré ?",bins:["Souscription","Gré à gré"],it:[["La SCPI émet de nouvelles parts",0],["On rachète les parts d'un associé qui vend",1],["Augmentation de capital",0],["Passage par un intermédiaire pour trouver le vendeur",1]],w:"Souscription : parts nouvelles. Gré à gré : parts existantes, rachetées à un associé."},
{i:"f257_10",u:257,t:"slider",d:.4,nw:"Le délai de jouissance",q:"Délai de jouissance courant d'une SCPI, en mois (valeur haute) ?",min:0,max:12,step:1,a:6,tol:0,pre:"",un:" mois",w:"Souvent 3 à 6 mois : on est associé, mais les revenus ne démarrent qu'ensuite."},
{i:"f257_11",u:257,t:"story",d:.4,q:"Que réponds-tu à Théo ?",sc:[{who:"Théo",txt:"Les notes disent que pendant 3 à 6 mois, on n'est pas propriétaire des parts."}],o:["Si : propriétaire tout de suite, revenus plus tard","Exact : les parts restent à la SCPI pendant six mois","Exact : c'est un droit de rétractation de six mois","Non : le délai dure deux ans, pas six mois"],a:0,w:"Délai de jouissance : propriété immédiate, revenus différés. Le terme « carence » des notes est trompeur."},
{i:"f257_12",u:257,t:"num",d:.45,q:"Sandrine souscrit 40 000 € avec 10 % de frais de souscription. Combien est réellement investi dans l'immobilier, en euros ?",a:36000,tol:1,un:" €",h:"On retire les frais",w:"40 000 - 4 000 = 36 000 €. Des frais de 8 à 12 % imposent un horizon long pour être amortis."},
{i:"f257_13",u:257,t:"tf",d:.45,nw:"La revente des parts",q:"Une SCPI est obligée de racheter immédiatement les parts de tout associé qui veut sortir.",a:false,w:"Il faut trouver un acheteur ou des souscriptions nouvelles. Sinon, les parts restent en attente."},
{i:"f257_14",u:257,t:"mcq",d:.45,q:"Quelle est la principale difficulté pour vendre ses parts ?",o:["Trouver assez d'acheteurs","Obtenir l'accord du notaire","Payer la TVA sur la vente","Attendre la fin du bail"],a:0,w:"Le risque de liquidité : si beaucoup veulent sortir en même temps, les acheteurs manquent. On peut vendre à un nouvel associé de gré à gré, souvent par un intermédiaire."},
{i:"f257_15",u:257,t:"story",d:.45,q:"Que réponds-tu à Sandrine ?",sc:[{who:"Sandrine Duhamel",txt:"J'ai lu que des parts sont en attente de retrait chez Pierval Santé. Ça veut dire quoi ?"}],o:["Des associés veulent vendre, sans acheteur","La SCPI a été fermée par l'AMF pour fraude","Les loyers de la SCPI ont cessé d'être versés","Les parts ont été rachetées d'office par la banque"],a:0,w:"En 2026, 2,9 % de son patrimoine était en attente de retrait. Ce n'est pas une faillite, c'est un manque de liquidité."},
{i:"f257_16",u:257,t:"num",d:.45,q:"Une SCPI de 3,3 milliards d'euros a 2,9 % de parts en attente. Montant en attente, en millions d'euros ?",a:95.7,tol:.5,un:" M€",h:"3 300 x 2,9 %",w:"3 300 x 2,9 % = 95,7 millions d'euros de parts qui cherchent un acheteur."},
{i:"f257_17",u:257,t:"multi",d:.5,nw:"Le financement à crédit des SCPI",q:"Quelles affirmations sur l'achat de parts à crédit sont justes ?",o:["Les revenus peuvent aider à rembourser","Les intérêts sont déductibles au régime réel","Les revenus ne sont pas garantis","La banque garantit la distribution","La mensualité baisse avec les revenus"],a:[0,1,2],w:"Effet de levier réel, mais la mensualité reste fixe alors que la distribution peut baisser."},
{i:"f257_18",u:257,t:"story",d:.5,q:"Que réponds-tu à Philippe ?",sc:[{who:"Philippe Vandamme",txt:"J'emprunte 100 000 € sur 15 ans pour des parts. Les revenus paieront tout, aucun risque."}],o:["Risque : si la distribution baisse, la mensualité reste due","Aucun risque : la banque suspend le prêt si les revenus baissent","Aucun risque : l'État garantit les revenus des SCPI à crédit","Risque : les intérêts ne sont jamais déductibles"],a:0,w:"Les revenus ne sont pas garantis. Les intérêts, eux, se déduisent des revenus fonciers au réel."},
{i:"f257_19",u:257,t:"fill",d:.45,q:"Les intérêts d'un emprunt pour acheter des parts se déduisent des revenus ___ au régime réel.",o:["fonciers","financiers","salariaux","exceptionnels"],a:0,w:"La quote-part de loyers d'une SCPI est un revenu foncier. On y déduit les intérêts au réel."},
{i:"f257_20",u:257,t:"tf",d:.5,q:"Acheter des parts de SCPI à crédit ressemble à un investissement locatif dont les loyers paient la mensualité.",a:true,w:"C'est la logique décrite dans les notes, avec la même réserve : les loyers peuvent baisser."},
{i:"f257_21",u:257,t:"match",d:.5,nw:"La fiscalité des SCPI",q:"Associe chaque revenu à son imposition en 2026.",p:[["Quote-part des loyers","Barème + 17,2 %"],["Produits de trésorerie","PFU de 31,4 %"],["Plus-value sur les parts","19 % + 17,2 %"],["Loyers d'immeubles à l'étranger","Impôt payé dans le pays de l'immeuble"]],w:"Les loyers vont au barème, la trésorerie au PFU, la plus-value au régime immobilier."},
{i:"f257_22",u:257,t:"num",d:.5,q:"Sandrine, tranche à 30 %, perçoit 5 000 € de loyers SCPI sans charges. Combien lui reste-t-il après impôt et prélèvements sociaux, en euros ?",a:2640,tol:1,un:" €",h:"30 % + 17,2 %",w:"1 500 € d'impôt et 860 € de prélèvements sociaux : il reste 2 640 €. La fiscalité pèse lourd pour les tranches élevées."},
{i:"f257_23",u:257,t:"slider",d:.5,q:"Taux du prélèvement forfaitaire unique en 2026, en pourcentage ?",min:20,max:40,step:.1,a:31.4,tol:0,pre:"",un:" %",w:"12,8 % d'impôt + 18,6 % de prélèvements sociaux = 31,4 % depuis la loi de financement de la Sécurité sociale pour 2026."},
{i:"f257_24",u:257,t:"story",d:.5,q:"Que réponds-tu ?",ctx:"Sandrine touche 5 000 € de loyers SCPI par an. Elle n'a aucun appartement loué en direct.",sc:[{who:"Sandrine Duhamel",txt:"Je peux prendre le micro-foncier et son abattement de 30 % ?"}],o:["Non : il faut aussi un bien loué nu en direct","Oui : il suffit de rester sous 15 000 € de revenus fonciers","Oui : le micro-foncier est réservé aux porteurs de SCPI","Non : le micro-foncier a été supprimé en 2026"],a:0,w:"Le micro-foncier s'applique aux porteurs de SCPI seulement s'ils détiennent aussi un immeuble loué nu en direct. Sinon, régime réel."},
{i:"f257_25",u:257,t:"mcq",d:.5,q:"Quel abattement le micro-foncier applique-t-il ?",o:["30 %","50 %","10 %","71 %"],a:0,w:"30 % d'abattement forfaitaire, sous 15 000 € de revenus fonciers bruts."},
{i:"f257_26",u:257,t:"tiles",d:.5,q:"Reconstitue la formule mémo de la plus-value.",a:["22","pour","l'impôt,","30","pour","le","social"],dd:["15","pour","la"],w:"Exonération d'impôt sur le revenu après 22 ans, de prélèvements sociaux après 30 ans."},
{i:"f257_27",u:257,t:"slider",d:.55,q:"Après combien d'années de détention la plus-value sur parts de SCPI est-elle exonérée d'impôt sur le revenu ?",min:5,max:35,step:1,a:22,tol:0,pre:"",un:" ans",w:"22 ans pour l'impôt, 30 ans pour les prélèvements sociaux."},
{i:"f257_28",u:257,t:"story",d:.55,q:"Rappel du module 10 : que réponds-tu ?",sc:[{who:"Sandrine Duhamel",txt:"Avec des frais d'entrée de 10 %, je peux quand même revendre au bout d'un an si le prix monte ?"}],o:["Il faudrait une forte hausse : c'est un placement long","Oui, une SCPI monte toujours de 10 % par an au moins","Oui, les frais d'entrée sont remboursés à la revente","Non, la revente est interdite pendant cinq ans"],a:0,w:"Frais d'entrée élevés, liquidité incertaine : 8 à 10 ans d'horizon. V.R.L."},
{i:"f257_29",u:257,t:"order",d:.5,q:"Remets dans l'ordre la souscription de Sandrine au cabinet.",it:["Remettre note, statuts, DIC et rapport annuel","Expliquer risques et fiscalité","Faire remplir le bulletin de souscription","Verser les fonds","Attendre le délai de jouissance avant les premiers revenus"],w:"Informer d'abord, signer ensuite, puis patienter avant les revenus. La souscription crée des parts nouvelles, le gré à gré rachète des parts existantes."},
{i:"f257_30",u:257,t:"multi",d:.55,q:"Rappel du module 9 : quels organes protègent Sandrine pendant sa détention ?",o:["Le conseil de surveillance","Le commissaire aux comptes","Le dépositaire","Le notaire de la souscription"],a:[0,1,2],w:"Surveiller, Certifier, Garder. Aucun notaire n'intervient dans une souscription de parts."},
{i:"f257_31",u:257,t:"story",d:.6,q:"Synthèse : Sandrine demande ce qu'elle touchera vraiment.",sc:[{who:"Sandrine Duhamel",txt:"120 000 euros à 4,9 %, tranche à 30 %. Net, ça fait combien par an, à peu près ?"}],o:["Environ 3 100 € : 5 880 € bruts moins environ 47 % d'impôts","5 880 € : les revenus de SCPI ne sont pas imposés","Environ 4 000 € : seul le PFU de 31,4 % s'applique","Environ 5 000 € : seuls les prélèvements sociaux sont dus"],a:0,w:"5 880 x (1 - 30 % - 17,2 %) ≈ 3 100 €. Pour une tranche élevée, les SCPI en direct sont lourdement taxées."},
{i:"f257_32",u:257,t:"story",d:.6,q:"Synthèse : Nathalie te demande la règle d'or de la souscription.",sc:[{who:"Nathalie Wattel",txt:"Une phrase pour le stagiaire."}],o:["« Tout remettre avant, expliquer l'impôt, et vendre pour dix ans »","« Faire signer vite, les documents peuvent attendre le trimestre »","« Promettre le taux de l'an dernier, c'est ce que veulent les clients »","« Conseiller le crédit à tous, les loyers remboursent toujours »"],a:0,w:"Information préalable, fiscalité claire, horizon long. C'est ce qui protège le client et le conseiller."}
