/*UNIT*/
{id:259,c:"FISCA",n:"Module 13",t:"SCI : créer une société de famille pour détenir l'immobilier",col:"--purple",ic:"🏘️",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Distinguer les <b>trois types</b> de SCI : construction-vente, attribution, location.</li>
<li>Expliquer les <b>intérêts</b> d'une SCI de location : protection, transmission, gestion.</li>
<li>Vérifier les <b>conditions de création</b> : associés, capital.</li>
<li>Lire la <b>répartition des parts</b> et ses pièges.</li>
<li>Repérer ce qu'il faut vérifier <b>en premier</b> dans une SCI.</li></ul>
<h3>La SCI des Tilleuls</h3>
<div class="gstory">Alain et Brigitte Carpentier, 63 et 61 ans, possèdent trois appartements loués à Tourcoing, achetés en indivision. Leurs enfants, Maxime et Chloé, ne s'entendent pas toujours. Alain s'inquiète : « Si on meurt, nos enfants se retrouvent en indivision. Au premier désaccord, l'un voudra vendre et l'autre non. » Son notaire lui a parlé d'une SCI. Il arrive au cabinet avec une question simple : « C'est quoi, au juste, et qui aura combien ? »</div>
<h3>Les trois types de SCI</h3>
<table><tr><th>Type</th><th>But</th><th>À savoir</th></tr>
<tr><td><b>Construction-vente</b></td><td>Construire puis vendre</td><td>Souvent liée à la VEFA, lots vendus à des acheteurs extérieurs, rare pour les particuliers</td></tr>
<tr><td><b>Attribution</b></td><td>Construire pour que chaque associé récupère un bien</td><td>Mêmes règles de travaux et d'appels de fonds, lots attribués et non vendus</td></tr>
<tr><td><b>Location</b> (ou de gestion)</td><td>Administrer et gérer des biens</td><td>La plus fréquente, souvent familiale, sans limite de taille</td></tr></table>
<ul><li>SCI d'attribution : on reste <b>entre associés</b>, la future copropriété est <b>plus simple</b> à gérer, et chacun devient propriétaire de son lot, qu'il peut <b>louer librement</b>.</li>
<li>SCI de location : familles, amis, mais aussi <b>artisans du bâtiment</b> qui rénovent eux-mêmes puis louent.</li></ul>
<div class="gmnemo">Trois verbes : <b>« Vendre, Partager, Louer »</b>. La construction-vente vend, l'attribution partage entre associés, la location loue. V.P.L., comme un <b>Vieux Pavillon Lillois</b>.</div>
<h3>Pourquoi une SCI de location ?</h3>
<ul><li><b>Protection</b> : les créanciers personnels d'un associé ne peuvent saisir que ses <b>parts</b>, pas l'immeuble. Saisir des parts puis vendre l'immeuble à travers elles est très difficile.</li>
<li><b>Transmission</b> : on évite l'<b>indivision</b> entre frères et sœurs. Les parents peuvent donner des parts petit à petit.</li>
<li><b>Gestion</b> : les statuts fixent les règles de décision, le gérant, la sortie d'un associé.</li>
<li><b>Couple</b> : la SCI permet d'organiser la détention des biens en tenant compte du régime matrimonial.</li></ul>
<div class="gtrap">La protection n'est pas absolue. Les <b>créanciers de la SCI</b> peuvent saisir l'immeuble. Et les associés répondent des dettes de la SCI <b>sans limite</b>, à proportion de leurs parts, si la société ne peut pas payer. Les notes disent aussi qu'en indivision, un héritier peut vendre sa part « à n'importe qui ». En réalité, les autres indivisaires ont un <b>droit de préemption</b> : ils passent en priorité. Mais surtout, <b>nul n'est tenu de rester en indivision</b> : chacun peut demander le partage, ce qui peut forcer la vente.</div>
<h3>Créer une SCI</h3>
<ul><li>Il faut <b>au moins deux associés</b> : personnes physiques ou sociétés. Il n'existe pas de SCI à associé unique.</li>
<li>Si toutes les parts se retrouvent dans une seule main, la SCI n'est pas dissoute d'office. Mais tout intéressé peut demander la dissolution si la situation n'est pas <b>régularisée dans l'année</b>.</li>
<li><b>Aucun capital minimum</b> : un capital de 1 euro est possible.</li></ul>
<div class="gtrap">Les notes disent qu'une SCI est possible « sans capital ». Une société suppose des <b>apports</b>, même symboliques. En pratique, on fixe un capital, parfois de quelques euros seulement.</div>
<div class="gmnemo"><b>« 2, 0, 1 »</b> : 2 associés au moins, 0 euro de capital minimum imposé, 1 an pour régulariser si un seul associé reste.</div>
<h3>La répartition des parts</h3>
<p>C'est <b>la première chose à vérifier</b> dans une SCI : qui détient combien.</p>
<ul><li>Les parts sont réparties <b>à proportion des apports</b> au capital, sauf clause contraire des statuts. Les bénéfices suivent ensuite les parts.</li>
<li>Payer 60 % du prix de l'immeuble ne donne <b>pas</b> automatiquement 60 % des parts. L'argent versé hors capital (compte courant, remboursement du prêt) crée une <b>créance</b> sur la SCI, pas des parts.</li>
<li>Si un accord différent a été conclu, il faut pouvoir le <b>prouver</b> : il doit être écrit.</li>
<li>La répartition est libre (99 % et 1 %, par exemple), mais <b>prudence avec le fisc</b> : un déséquilibre injustifié peut cacher une donation.</li>
<li>Cas courant : les <b>parents 80 %</b>, les enfants se partagent le reste.</li></ul>
<div class="gtrap">Les notes disent que la répartition est « par défaut égalitaire » si les statuts ne disent rien. La règle légale est la <b>proportion des apports</b>. La répartition n'est égalitaire que si les apports sont égaux.</div>
<div class="formula">SCI des Tilleuls, capital 1 000 €
Alain 400 € : 40 %   Brigitte 400 € : 40 %
Maxime 100 € : 10 %  Chloé 100 € : 10 %
Maxime verse 60 000 € en compte courant pour des travaux : toujours 10 % des parts, plus une créance de 60 000 €</div>
<h3>Ce que tu dois retenir pour l'examen</h3>
<ul><li>Vendre, Partager, Louer : les trois types de SCI.</li>
<li>Protection (relative), transmission sans indivision, gestion par statuts.</li>
<li>2 associés, aucun capital minimum, un an pour régulariser.</li>
<li>Parts à proportion des apports, et c'est ce qu'on vérifie en premier.</li></ul>`},
/*EXOS*/
{i:"f259_01",u:259,t:"match",d:.3,nw:"Les trois types de SCI",q:"Associe chaque SCI à son but.",p:[["Construction-vente","Construire puis vendre à des tiers"],["Attribution","Construire pour attribuer un lot à chaque associé"],["Location","Administrer et gérer des biens loués"],["SCI des Tilleuls","Gérer trois appartements familiaux"]],w:"Vendre, Partager, Louer. Les Carpentier ont une SCI de location."},
{i:"f259_02",u:259,t:"tiles",d:.3,q:"Reconstitue les trois verbes mémo des types de SCI.",a:["Vendre,","Partager,","Louer"],dd:["Acheter,","Garder,","Prêter,"],w:"Construction-vente, attribution, location : V.P.L., comme un Vieux Pavillon Lillois."},
{i:"f259_03",u:259,t:"mcq",d:.3,q:"Avec quel mode de vente la SCI de construction-vente est-elle souvent liée ?",o:["La VEFA","Le viager","La tontine","Le démembrement"],a:0,w:"Elle construit puis vend, souvent sur plan, en VEFA (modules 1 à 3)."},
{i:"f259_04",u:259,t:"multi",d:.35,q:"Quels sont les avantages d'une SCI d'attribution ?",o:["On reste entre associés","La copropriété est plus simple à gérer","Chacun reçoit son lot et peut le louer","Les lots sont vendus à des inconnus","Elle échappe à tout appel de fonds"],a:[0,1,2],w:"Attribution : on partage entre associés. Les règles de travaux et d'appels de fonds restent celles de la construction-vente."},
{i:"f259_05",u:259,t:"tf",d:.35,q:"La SCI de location peut détenir autant de biens qu'elle veut.",a:true,w:"Aucune limite de taille ni de nombre de biens. C'est la SCI la plus fréquente."},
{i:"f259_06",u:259,t:"story",d:.35,q:"Quel type de SCI conseilles-tu ?",ctx:"Karim, artisan plaquiste à Roubaix, veut acheter des maisons à rénover lui-même pour les louer ensuite, avec son associé.",sc:[{who:"Karim",txt:"Je rénove, puis je loue. Quelle SCI ?"}],o:["Une SCI de location","Une SCI de construction-vente","Une SCI d'attribution","Une SCPI de rendement"],a:0,w:"Cas fréquent cité par le prof : les artisans du bâtiment qui rénovent puis louent, via une SCI de location."},
{i:"f259_07",u:259,t:"fill",d:.35,q:"Dans une SCI d'attribution, les lots sont ___ aux associés, pas vendus.",o:["attribués","loués","prêtés","donnés à bail"],a:0,w:"Chaque associé récupère un lot, qui devient sa propriété. Il peut ensuite le louer librement."},
{i:"f259_08",u:259,t:"sort",d:.4,q:"Classe chaque projet dans le bon type de SCI.",bins:["Construction-vente","Attribution","Location"],it:[["Un promoteur bâtit 40 logements à vendre sur plan",0],["Trois amis font construire un petit immeuble, un étage chacun",1],["Une famille gère ses appartements loués",2],["Deux artisans rénovent et louent",2],["Des voisins font bâtir des maisons à se répartir",1]],w:"Vendre à des tiers, partager entre associés, ou louer."},
{i:"f259_09",u:259,t:"story",d:.4,nw:"La protection du patrimoine par la SCI",q:"Que réponds-tu à Alain ?",sc:[{who:"Alain Carpentier",txt:"Si Maxime a des dettes personnelles, ses créanciers peuvent saisir un appartement de la SCI ?"}],o:["Non : ils saisissent ses parts, pas l'immeuble","Oui : ils saisissent l'appartement de leur choix","Oui, mais seulement le plus petit appartement","Non : les parts de SCI sont insaisissables"],a:0,w:"Les créanciers personnels d'un associé ne peuvent saisir que ses parts. Vendre l'immeuble à travers elles est très difficile."},
{i:"f259_10",u:259,t:"tf",d:.4,q:"La SCI met les associés totalement à l'abri des dettes de la société.",a:false,w:"Les associés répondent des dettes de la SCI sans limite, à proportion de leurs parts. La protection vise les dettes personnelles d'un associé."},
{i:"f259_11",u:259,t:"story",d:.45,nw:"L'indivision",q:"Que réponds-tu à Chloé ?",sc:[{who:"Chloé Carpentier",txt:"Si on reste en indivision avec Maxime après le décès des parents, il pourra vendre sa part à n'importe qui, comme dit le cours ?"}],o:["Tu serais prioritaire, et il pourrait exiger le partage","Oui, à n'importe qui, sans que tu aies ton mot à dire","Non, une indivision entre héritiers dure toute la vie","Non, il faudra l'accord du notaire pour chaque vente"],a:0,w:"Droit de préemption des coïndivisaires, et surtout : nul n'est tenu de rester en indivision. La SCI évite ce blocage."},
{i:"f259_12",u:259,t:"multi",d:.45,q:"Pourquoi une SCI facilite-t-elle la transmission ?",o:["Elle évite l'indivision entre enfants","Les parents peuvent donner des parts progressivement","Les statuts fixent les règles de gestion","Elle supprime les droits de succession","Elle interdit aux enfants de vendre"],a:[0,1,2],w:"Pas d'indivision, donation par petits bouts, règles écrites. Les droits de succession restent dus sur la valeur des parts."},
{i:"f259_13",u:259,t:"slider",d:.4,nw:"La création d'une SCI",q:"Nombre minimum d'associés pour créer une SCI ?",min:1,max:7,step:1,a:2,tol:0,pre:"",un:" associés",w:"Deux au moins. Il n'existe pas de SCI à associé unique."},
{i:"f259_14",u:259,t:"mcq",d:.4,q:"Quel est le capital minimum légal d'une SCI ?",o:["Aucun minimum","1 000 euros","7 500 euros","37 000 euros au moins"],a:0,w:"Aucun minimum : un euro suffit. Il faut toutefois des apports, même symboliques."},
{i:"f259_15",u:259,t:"story",d:.45,q:"Que se passe-t-il ?",ctx:"Dans une SCI à deux associés, l'un rachète les parts de l'autre et se retrouve seul.",sc:[{who:"Associé restant",txt:"Ma SCI est dissoute du jour au lendemain ?"}],o:["Non, mais vous avez un an pour régulariser","Oui, la dissolution est immédiate et automatique","Non, une SCI peut vivre seule sans limite","Oui, et l'immeuble revient à l'État"],a:0,w:"Pas de dissolution d'office. Mais tout intéressé peut la demander au tribunal si la situation n'est pas régularisée dans l'année."},
{i:"f259_16",u:259,t:"tiles",d:.4,q:"Reconstitue le code mémo de la création.",a:["2","associés,","0","euro","minimum,","1","an"],dd:["3","7","500"],w:"2, 0, 1 : deux associés, aucun capital minimum imposé, un an pour régulariser."},
{i:"f259_17",u:259,t:"tf",d:.4,q:"Une société peut être associée d'une SCI.",a:true,w:"Les associés peuvent être des personnes physiques ou morales."},
{i:"f259_18",u:259,t:"fill",d:.45,q:"Les notes disent « possible sans capital ». Une société suppose pourtant des ___, même symboliques.",o:["apports","salariés","bureaux","emprunts"],a:0,w:"Une société naît d'apports. En pratique, on fixe un capital, parfois de quelques euros."},
{i:"f259_19",u:259,t:"num",d:.45,nw:"La répartition des parts",q:"Capital de 1 000 € : Alain 400, Brigitte 400, Maxime 100, Chloé 100. Quel pourcentage des parts détient Maxime ?",a:10,tol:0,un:" %",h:"Apport / capital",w:"100 / 1 000 = 10 %. Les parts suivent les apports au capital."},
{i:"f259_20",u:259,t:"story",d:.5,q:"Que réponds-tu à Maxime ?",sc:[{who:"Maxime Carpentier",txt:"J'ai payé 60 000 € de travaux sur mon compte courant d'associé, soit 60 % du total. J'ai donc 60 % des parts ?"}],o:["Non : 10 % des parts, et une créance de 60 000 €","Oui : payer 60 % donne 60 % des parts","Oui, dès que le notaire l'enregistre","Non : vous perdez ces 60 000 € au profit de la SCI"],a:0,w:"Payer 60 % du prix ne donne pas 60 % des parts. L'argent en compte courant est une créance sur la SCI, remboursable."},
{i:"f259_21",u:259,t:"story",d:.5,q:"Que réponds-tu à Théo ?",sc:[{who:"Théo",txt:"Les notes disent : si les statuts ne disent rien, la répartition est égalitaire. Donc 25 % chacun chez les Carpentier ?"}],o:["Non : les parts suivent les apports, 40, 40, 10, 10","Oui : sans clause, on partage toujours à parts égales","Oui, à condition qu'ils aient le même âge","Non : l'aîné reçoit la moitié par défaut"],a:0,w:"La loi retient la proportion des apports. L'égalité ne vaut que pour des apports égaux."},
{i:"f259_22",u:259,t:"mcq",d:.5,q:"Pourquoi faut-il être prudent avec une répartition 99 % et 1 % ?",o:["Le fisc peut y voir une donation","La loi interdit de descendre sous 5 %","Une SCI doit toujours être à 50 et 50","L'associé à 1 % peut bloquer toute vente"],a:0,w:"La répartition est libre, mais un déséquilibre injustifié avec les apports réels peut être requalifié par le fisc."},
{i:"f259_23",u:259,t:"multi",d:.5,q:"Que faut-il vérifier au sujet des parts ?",o:["Qui détient combien, en premier","Si les parts suivent les apports","Si un accord différent est écrit et prouvable","La couleur du logo de la SCI"],a:[0,1,2],w:"C'est la première vérification dans une SCI : répartition, cohérence avec les apports, preuve des accords."},
{i:"f259_24",u:259,t:"slider",d:.45,q:"Cas courant cité par le prof : quelle part les parents gardent-ils souvent, en pourcentage ?",min:0,max:100,step:5,a:80,tol:0,pre:"",un:" %",w:"Parents 80 %, enfants 20 % à se partager. Les parents gardent la main tout en commençant la transmission."},
{i:"f259_25",u:259,t:"sort",d:.5,q:"Règle exacte ou erreur des notes ?",bins:["Règle exacte","Erreur à corriger"],it:[["Deux associés au minimum",0],["Répartition égalitaire par défaut",1],["Aucun capital minimum",0],["Un héritier indivisaire vend à n'importe qui",1],["Les créanciers personnels saisissent les parts",0],["Payer 60 % donne 60 % des parts",1]],w:"Répartition selon les apports, préemption en indivision, argent hors capital = créance."},
{i:"f259_26",u:259,t:"story",d:.5,q:"Rappel du module 7 : que réponds-tu ?",sc:[{who:"Chloé Carpentier",txt:"Pour le LLI, Maxime et moi créons une SCI à deux. On la met au nom de nos parents pour simplifier ?"}],o:["Non : vos apports font de vous les associés","Oui : les parents doivent toujours être associés","Oui : une SCI LLI doit compter quatre associés","Non : le LLI se fait en nom propre"],a:0,w:"Deux associés suffisent pour le LLI. Ce sont les apports qui déterminent les parts."},
{i:"f259_27",u:259,t:"order",d:.5,q:"Remets dans l'ordre la création de la SCI des Tilleuls.",it:["Choisir le type : SCI de location","Réunir au moins deux associés","Fixer le capital et les apports","Rédiger les statuts et la répartition des parts","Apporter les appartements à la SCI"],w:"Type, associés, capital, statuts, apport des biens."},
{i:"f259_28",u:259,t:"tf",d:.55,q:"Dans une SCI, les bénéfices se répartissent en principe à proportion des parts de chacun.",a:true,w:"Sauf clause contraire des statuts, chacun reçoit les bénéfices et supporte les pertes à proportion de ses parts."},
{i:"f259_29",u:259,t:"match",d:.55,q:"Rappel du module 12 : associe chaque bailleur à la durée minimale du bail vide.",p:[["Alain, en nom propre","3 ans"],["La SCI familiale des Tilleuls","3 ans, comme un particulier"],["Une société commerciale","6 ans"],["Location meublée","1 an"]],w:"Une SCI familiale (parents et alliés jusqu'au 4e degré) signe des baux de 3 ans, comme une personne physique."},
{i:"f259_30",u:259,t:"story",d:.55,q:"Rappel du module 11 : Alain compare avec une SCPI.",sc:[{who:"Alain Carpentier",txt:"Pourquoi ne pas vendre nos appartements et tout mettre en SCPI ?"}],o:["La SCPI délègue tout, la SCI vous laisse la main","C'est pareil, une SCPI est une SCI familiale","La SCPI est impossible au-delà de 60 ans","La SCI est toujours plus rentable qu'une SCPI"],a:0,w:"SCPI : gestion déléguée, parts d'un grand patrimoine. SCI : vous gardez vos immeubles et décidez vous-mêmes."},
{i:"f259_31",u:259,t:"mcq",d:.6,q:"Quelle est la toute première chose à vérifier quand un client arrive avec une SCI existante ?",o:["La répartition des parts","Le montant des loyers","La date de la dernière AG","Le nom du gérant"],a:0,w:"Qui détient combien : tout en découle, la transmission, les décisions, les droits aux bénéfices."},
{i:"f259_32",u:259,t:"story",d:.6,q:"Synthèse : Alain veut ta recommandation.",sc:[{who:"Alain Carpentier",txt:"Alors, la SCI, on la fait ?"}],o:["« Oui : SCI de location, 80 % pour vous, donations de parts ensuite »","« Non : l'indivision protège mieux vos enfants que toute société »","« Oui, mais seul : une SCI à associé unique suffit pour vous »","« Oui : 25 % chacun par défaut, quels que soient les apports »"],a:0,w:"SCI de location, parents majoritaires, transmission progressive, statuts clairs. Et on n'oublie pas les limites de la protection."}
