/*UNIT*/
{id:264,c:"FISCA",n:"Module 18",t:"Synthèse : un an au cabinet, tous les dossiers d'un coup",col:"--gold",ic:"🏆",guide:`
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Choisir le bon outil pour chaque projet : VEFA, PTZ, Jeanbrun, LLI, SCPI, SCI, tontine, viager, placements.</li>
<li>Donner les <b>chiffres clés</b> de chaque dispositif sans hésiter.</li>
<li>Corriger les <b>erreurs des notes</b>.</li>
<li>Traiter un cas complet de client de A à Z.</li></ul>
<h3>Un an plus tard</h3>
<div class="gstory">Septembre 2027, rue Esquermoise. Les Benali ont reçu les clés de leur T3 à Fives et ont levé leurs réserves. Philippe loue son T2 Jeanbrun à une infirmière. Sandrine touche ses distributions de SCPI et a gardé une épargne de précaution. Les Carpentier ont agréé Julie dans la SCI. Jeanne et Robert se sont pacsés, tontine en poche. Madeleine lit sous son cerisier, Karim paie la rente. Et Théo ne confond plus Pinel et Jeanbrun. Nathalie te tend un dernier dossier : « Montre-moi que tu sais tout. »</div>
<h3>La carte du cours</h3>
<table><tr><th>Projet du client</th><th>Outil</th><th>La phrase à retenir</th></tr>
<tr><td>Acheter du neuf sur plan</td><td>VEFA</td><td>5 dans l'an, 2 dans les deux, rien au-delà. 35, 70, 95, 100.</td></tr>
<tr><td>Vérifier les défauts</td><td>Garanties</td><td>1, 2, 10 : je Parfais, ça Fonctionne, ça Tient</td></tr>
<tr><td>Premier achat de sa résidence</td><td>PTZ</td><td>P.R.I.M.O. et 6 ans d'occupation</td></tr>
<tr><td>Investir pour louer (avant 2025)</td><td>Pinel</td><td>6, 9, 12 donnent 12, 18, 21. Pinel réduit l'impôt.</td></tr>
<tr><td>Investir pour louer (2026 à 2028)</td><td>Jeanbrun</td><td>Jeanbrun réduit le revenu. 3,5 / 4,5 / 5,5 %.</td></tr>
<tr><td>Investir via une SCI en zone tendue</td><td>LLI (et cumul)</td><td>10, 15, 20</td></tr>
<tr><td>L'immobilier sans gestion</td><td>SCPI</td><td>La pierre sans les pierres dans la chaussure. V.R.L.</td></tr>
<tr><td>Louer un logement</td><td>Bail de 1989, ALUR</td><td>3, 6, 1, 9. Fourchette 70, 100, 120.</td></tr>
<tr><td>Détenir et transmettre en famille</td><td>SCI</td><td>Parts selon les apports. Le gérant gère, il ne vend pas.</td></tr>
<tr><td>Protéger un concubin</td><td>Tontine</td><td>Le dernier debout rafle la mise. A.P.E.N.</td></tr>
<tr><td>Rester chez soi avec un revenu</td><td>Viager</td><td>B + R. La rente grossit avec les bougies.</td></tr>
<tr><td>Placer en bourse</td><td>Valeurs mobilières</td><td>Action = associé. PFU 31,4 %.</td></tr></table>
<div class="gmnemo">Toute la méthode du conseiller en trois questions : <b>« Pour qui ? Pour quoi ? Pour combien de temps ? »</b>. Le PTZ est pour qui achète sa résidence. Le Jeanbrun pour qui veut louer 9 ans. La SCPI pour qui ne veut pas gérer. La tontine pour qui veut protéger. Le temps décide du reste.</div>
<h3>Les chiffres qu'on ne rate pas</h3>
<ul><li>VEFA : rétractation <b>10 jours</b>, dépôt <b>5 % ou 2 %</b>, restitution si prix <b>+5 %</b> ou prêts <b>-10 %</b>, pénalité de retard de paiement <b>1 % par mois</b>.</li>
<li>Pinel : <b>5 500 €/m²</b>, <b>300 000 €</b>, deux logements par an, fin au <b>31 décembre 2024</b>.</li>
<li>Jeanbrun : base <b>80 %</b>, plafonds <b>8 000, 10 000, 12 000 €</b> dans le neuf, <b>10 700 €</b> dans l'ancien, <b>9 ans</b>, jusqu'au <b>31 décembre 2028</b>.</li>
<li>PTZ : <b>6 ans</b> d'occupation, <b>10 à 25 ans</b> de durée, prolongé jusqu'au <b>31 décembre 2027</b>.</li>
<li>SCPI : part d'au moins <b>150 €</b>, distribution moyenne <b>4,91 %</b> en 2025, plus-value exonérée à <b>22 et 30 ans</b>.</li>
<li>Viager : règle des <b>20 jours</b>, rente imposable à <b>70, 50, 40 ou 30 %</b>.</li></ul>
<h3>Les erreurs des notes, en un tableau</h3>
<table><tr><th>Les notes disent</th><th>La règle juste</th></tr>
<tr><td>Rétractation de 7 jours</td><td>10 jours depuis 2015</td></tr>
<tr><td>Dépôt de 5 % si travaux longs</td><td>5 % si l'acte est dans l'année, 2 % entre un et deux ans, rien au-delà</td></tr>
<tr><td>Retard de paiement : 10 % du prix au plus</td><td>1 % par mois de retard</td></tr>
<tr><td>Deux garanties obligatoires</td><td>Garantie d'achèvement ou de remboursement, la GFA en pratique</td></tr>
<tr><td>Décennale : le constructeur prouve l'absence de faute</td><td>Responsabilité de plein droit, seule une cause étrangère exonère</td></tr>
<tr><td>Vice caché : prouver que le vendeur savait</td><td>Utile pour les dommages, un vendeur professionnel est présumé savoir</td></tr>
<tr><td>Pinel : 5 000 €/m² et un seul investissement</td><td>5 500 €/m², deux logements par an</td></tr>
<tr><td>Super Pinel avec amortissement Pinel</td><td>LLI + Jeanbrun (« Super Jeanbrun »), dans une SCI à l'IR</td></tr>
<tr><td>Lille en zone B1</td><td>Lille en zone A</td></tr>
<tr><td>PTZ créé en 2011, habiter toute la durée du prêt</td><td>Créé en 1995, 6 ans d'occupation</td></tr>
<tr><td>Société de gestion « généralement » agréée</td><td>Agrément AMF obligatoire</td></tr>
<tr><td>Bail précaire de 6 mois en location vide</td><td>3 ans minimum, bail mobilité en meublé</td></tr>
<tr><td>Parts de SCI égalitaires par défaut</td><td>Parts à proportion des apports</td></tr>
<tr><td>Gérant obligatoirement associé</td><td>Associé ou non</td></tr>
<tr><td>Vente de l'immeuble à la majorité relative</td><td>Statuts, sinon unanimité</td></tr>
<tr><td>« PierreVéran Santé », film avec Jean Gabin</td><td>Pierval Santé, film avec Michel Serrault</td></tr></table>
<div class="gtrap">Les notes n'annoncent pas le périmètre de l'évaluation. Prépare-toi donc sur tout le cours, avec deux priorités : les <b>calculs</b> (dépôt, appels de fonds, Pinel, Jeanbrun, PTZ, loyer encadré, rente) et les <b>cas clients</b> où il faut choisir le bon outil et justifier.</div>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Choisir l'outil adapté au projet d'un client et justifier en une phrase.</li>
<li>Faire les calculs clés sans calculatrice compliquée.</li>
<li>Signaler une règle périmée (Pinel, PFU à 30 %) et donner la règle en vigueur.</li>
<li>Distinguer un fait, une règle et une opinion du prof.</li></ul>`},
/*EXOS*/
{i:"f264_01",u:264,t:"match",d:.35,nw:"Choisir le bon outil",q:"Associe chaque projet à l'outil adapté.",p:[["Premier achat de sa résidence principale","PTZ"],["L'immobilier sans rien gérer","SCPI"],["Protéger un concubin sur la maison","Tontine"],["Rester chez soi avec un revenu à vie","Viager occupé"]],w:"Pour qui ? Pour quoi ? Pour combien de temps ? Les trois questions du conseiller."},
{i:"f264_02",u:264,t:"tiles",d:.35,q:"Reconstitue les trois questions du conseiller.",a:["Pour","qui","?","Pour","quoi","?","Pour","combien","de","temps","?"],dd:["où","comment"],w:"Le public, l'objectif, l'horizon : tout choix d'outil en découle."},
{i:"f264_03",u:264,t:"story",d:.4,q:"Rappel des modules 1 et 2 : que réponds-tu ?",ctx:"Un couple réserve un T4 sur plan à 320 000 €, acte prévu dans 8 mois.",sc:[{who:"Client",txt:"Le promoteur demande 20 000 € de dépôt. Et on a combien de jours pour réfléchir ?"}],o:["16 000 € au plus, et 10 jours pour se rétracter","20 000 € au plus, et 7 jours pour se rétracter","6 400 € au plus, et 14 jours pour se rétracter","Aucun dépôt, et un mois pour se rétracter"],a:0,w:"Acte dans moins d'un an : 5 % de 320 000 = 16 000 €. Rétractation : 10 jours."},
{i:"f264_04",u:264,t:"num",d:.45,q:"Rappel du module 2 : même T4 à 320 000 €. Cumul maximum payé à la mise hors d'eau, en euros ?",a:224000,tol:1,un:" €",h:"70 %",w:"35 les pieds, 70 le chapeau : 70 % x 320 000 = 224 000 €."},
{i:"f264_05",u:264,t:"sort",d:.4,q:"Rappel du module 3 : quelle garantie joue ?",bins:["Parfait achèvement","Bon fonctionnement","Décennale"],it:[["Porte qui frotte au 5e mois",0],["Radiateur en panne au 20e mois",1],["Affaissement du plancher en 8e année",2],["Peinture ratée notée au PV",0],["Infiltrations généralisées en 4e année",2]],w:"1, 2, 10 : je Parfais, ça Fonctionne, ça Tient. Si le vendeur tarde à réparer : mise en demeure, puis astreinte ou travaux à ses frais."},
{i:"f264_06",u:264,t:"tf",d:.4,q:"La garantie décennale est une responsabilité de plein droit du constructeur.",a:true,w:"L'acheteur n'a pas à prouver une faute. Seule une cause étrangère exonère le constructeur. L'assurance dommages-ouvrage préfinance les réparations."},
{i:"f264_07",u:264,t:"story",d:.45,q:"Rappel du module 8 : que réponds-tu ?",sc:[{who:"Cliente",txt:"J'ai acheté avec un PTZ il y a 7 ans. Je peux louer mon appartement maintenant ?"}],o:["Oui : l'obligation d'occupation était de 6 ans","Non : il faut l'habiter pendant toute la durée du prêt","Non, sauf à le louer meublé à un étudiant","Oui, mais seulement à un membre de la famille"],a:0,w:"Six ans de résidence principale. Les notes disaient « toute la durée du prêt » : c'est inexact. Avant 6 ans, seules des exceptions comme la mobilité professionnelle permettent de louer."},
{i:"f264_08",u:264,t:"multi",d:.45,q:"Rappel du module 8 : quelles conditions du PTZ sont exactes ?",o:["Primo-accédant depuis deux ans","Revenus N-2 sous le plafond","PTZ au plus égal aux autres prêts de plus de deux ans","Réservé aux moins de 35 ans","Possible pour un investissement locatif"],a:[0,1,2],w:"P.R.I.M.O. Pas de condition d'âge, jamais pour un investissement locatif."},
{i:"f264_09",u:264,t:"num",d:.5,q:"Rappel du module 4 : achat Pinel en 2021, 50 m², 290 000 €, engagement 9 ans. Réduction totale, en euros ?",a:49500,tol:1,un:" €",h:"Plafond m² puis 18 %",w:"50 x 5 500 = 275 000 € (sous 290 000 et 300 000). 275 000 x 18 % = 49 500 €."},
{i:"f264_10",u:264,t:"num",d:.5,q:"Rappel du module 6 : T3 neuf Jeanbrun à 280 000 €, loyer social. Amortissement annuel, en euros ?",a:10000,tol:1,un:" €",h:"80 %, 4,5 %, plafond",w:"80 % x 280 000 = 224 000 €. 4,5 % = 10 080 €, ramené au plafond social de 10 000 €. Un amortissement supérieur aux loyers nets crée un déficit foncier."},
{i:"f264_11",u:264,t:"story",d:.5,q:"Rappel des modules 4 et 6 : que réponds-tu à Théo ?",sc:[{who:"Théo",txt:"Le Jeanbrun, c'est la réduction d'impôt du Pinel avec un autre nom."}],o:["Non : c'est un amortissement déduit des revenus fonciers","Oui, avec les mêmes zones et les mêmes taux","Oui, mais réservé aux maisons individuelles","Non : c'est un prêt à taux zéro pour les bailleurs"],a:0,w:"Pinel réduit l'impôt, Jeanbrun réduit le revenu. Pas de zone, immeubles collectifs, 9 ans."},
{i:"f264_12",u:264,t:"sort",d:.5,q:"Rappel des modules 6 et 7 : autorisé ou interdit ?",bins:["Autorisé","Interdit"],it:[["LLI loué à la mère de l'associée",0],["Jeanbrun loué à son frère",1],["Jeanbrun loué à un cousin germain",0],["Jeanbrun loué meublé",1],["LLI acheté en nom propre",1]],w:"LLI : famille admise, société obligatoire. Jeanbrun : famille jusqu'au 2e degré interdite, meublé interdit."},
{i:"f264_13",u:264,t:"tiles",d:.45,q:"Rappel du module 7 : reconstitue la formule du LLI.",a:["TVA","à","10,","louer","15,","avantage","jusqu'à","20"],dd:["20,","5,","vendre"],w:"TVA réduite, 15 ans de location, crédit de taxe foncière jusqu'à 20 ans."},
{i:"f264_14",u:264,t:"tf",d:.45,q:"Le « Super Pinel » des notes correspond aujourd'hui au cumul du LLI et du Jeanbrun.",a:true,w:"Le Pinel est fermé et n'a jamais amorti. Le cumul actuel est LLI + Jeanbrun, souvent appelé Super Jeanbrun."},
{i:"f264_15",u:264,t:"story",d:.5,q:"Rappel des modules 9 et 10 : que réponds-tu ?",sc:[{who:"Client",txt:"Je veux la SCPI qui distribue le plus, c'est forcément la meilleure."}],o:["Non : on juge le patrimoine, la diversification et le gérant","Oui : le taux affiché est garanti par l'AMF","Oui, surtout si elle est investie en bureaux","Non : une SCPI ne verse jamais de revenus"],a:0,w:"Qualité, type, diversification, gérant, perspectives. Un taux élevé peut cacher un risque."},
{i:"f264_16",u:264,t:"match",d:.5,q:"Rappel du module 9 : associe chaque organe à son verbe.",p:[["Expert immobilier","Estimer"],["Dépositaire","Garder"],["Assemblée générale","Voter"],["Commissaire aux comptes","Certifier"]],w:"Grand Soleil Vers Calais, Et Gaufres : Gérer, Surveiller, Voter, Certifier, Estimer, Garder."},
{i:"f264_17",u:264,t:"num",d:.55,q:"Rappel du module 11 : 6 000 € de loyers SCPI, tranche à 30 %, sans charges. Impôt et prélèvements sociaux, en euros ?",a:2832,tol:1,un:" €",h:"30 % + 17,2 %",w:"6 000 x 47,2 % = 2 832 € (1 800 € d'impôt et 1 032 € de prélèvements sociaux). Le micro-foncier n'est pas possible ici sans bien loué nu en direct."},
{i:"f264_18",u:264,t:"story",d:.55,q:"Rappel du module 12 : que réponds-tu ?",sc:[{who:"Bailleur lillois",txt:"Référence de mon quartier : 13 €/m². Mon T2 fait 45 m². Je peux louer 720 € avec le garage ?"}],o:["Non : 702 € au plus, un garage n'est pas exceptionnel","Oui : le garage justifie toujours un complément","Oui, la fourchette ne s'applique qu'aux studios","Non : 585 € au plus, soit la référence exacte"],a:0,w:"13 x 1,2 x 45 = 702 €. Un garage fermé ne justifie pas de complément de loyer."},
{i:"f264_19",u:264,t:"slider",d:.5,q:"Rappel du module 12 : durée minimale d'un bail vide signé par une SCI familiale, en années ?",min:1,max:9,step:1,a:3,tol:0,pre:"",un:" ans",w:"Une SCI familiale est traitée comme une personne physique : 3 ans. Il se renouvelle ensuite par tacite reconduction."},
{i:"f264_20",u:264,t:"story",d:.55,q:"Rappel des modules 13 et 14 : que réponds-tu ?",sc:[{who:"Associé à 10 %",txt:"J'ai payé la moitié des travaux. Et le gérant veut vendre seul l'immeuble, les statuts ne disent rien."}],o:["Vos 10 % restent, plus une créance, et la vente exige l'unanimité","Vous avez désormais 50 %, et le gérant peut vendre seul","Vous gardez 10 %, et le gérant peut vendre à la majorité relative","Vous perdez vos parts si vous refusez la vente"],a:0,w:"Argent hors capital = créance. Vente : statuts, sinon unanimité (article 1852)."},
{i:"f264_21",u:264,t:"fill",d:.5,q:"Rappel du module 14 : le gérant d'une SCI peut être associé ou ___.",o:["non","pas","étranger","mineur"],a:0,w:"Article 1846 : une ou plusieurs personnes, associées ou non. Les notes disaient « obligatoirement associé »."},
{i:"f264_22",u:264,t:"tf",d:.55,q:"Rappel du module 13 : les parts d'une SCI se répartissent à proportion des apports, sauf clause contraire.",a:true,w:"La répartition n'est égalitaire que si les apports sont égaux. C'est la première chose à vérifier."},
{i:"f264_23",u:264,t:"story",d:.55,q:"Rappel du module 15 : que réponds-tu ?",ctx:"Un homme de 83 ans veut acheter en tontine avec sa nièce de 38 ans, qui ne paierait rien.",sc:[{who:"Client",txt:"C'est le moyen idéal de lui laisser la maison, non ?"}],o:["Risqué : sans aléa ni apport, le fisc y verra une donation","Idéal : la tontine est faite pour ça","Idéal, à condition qu'elle habite avec lui","Impossible : une nièce ne peut pas être tontinière"],a:0,w:"A.P.E.N. : ni aléa réel, ni espérance de vie comparable, ni participation. Donation déguisée."},
{i:"f264_24",u:264,t:"num",d:.6,q:"Rappel du module 15 : un concubin reçoit par tontine une part de 150 000 €. Droits dus (60 % après 1 594 €), arrondis à l'euro ?",a:89044,tol:2,un:" €",h:"60 % x (150 000 - 1 594)",w:"60 % x 148 406 = 89 043,60 €. D'où l'intérêt du PACS, qui exonère."},
{i:"f264_25",u:264,t:"story",d:.6,q:"Rappel du module 16 : que réponds-tu ?",sc:[{who:"Vendeuse de 66 ans",txt:"Je vends en viager et toucherai 1 000 € de rente par mois. Quelle part sera imposée ?"}],o:["40 % : 4 800 € par an","30 % : 3 600 € par an","70 % : 8 400 € par an","100 % : 12 000 € par an"],a:0,w:"70, 50, 40, 30 : entre 60 et 69 ans au premier versement, 40 % de la rente est imposable."},
{i:"f264_26",u:264,t:"multi",d:.6,q:"Rappel du module 16 : qu'est-ce qui protège un viager ?",o:["L'acte notarié","La bonne foi sur l'état de santé","La règle des 20 jours","Une rente inférieure aux loyers possibles"],a:[0,1,2],w:"Notaire, Bonne foi, Vingt jours. Une rente trop faible rend au contraire la vente annulable."},
{i:"f264_27",u:264,t:"num",d:.55,q:"Rappel du module 17 : 3 000 € d'intérêts d'obligations sur un compte-titres en 2026. Montant du PFU, en euros ?",a:942,tol:1,un:" €",h:"31,4 %",w:"3 000 x 31,4 % = 942 € : 384 € d'impôt (12,8 %) et 558 € de prélèvements sociaux (18,6 %)."},
{i:"f264_28",u:264,t:"mcq",d:.55,q:"Rappel du module 17 : que détient un porteur de FCP ?",o:["Des parts d'une copropriété de titres","Des actions d'une société de gestion","Des obligations émises par l'État","Des parts d'une SCPI de bureaux"],a:0,w:"FCP : C comme Copropriété, pas de vote. SICAV : S comme Société, avec vote. SICAV et FCP sont les deux formes d'OPCVM."},
{i:"f264_29",u:264,t:"sort",d:.6,q:"Fait, règle ou opinion du prof ?",bins:["Règle de droit","Opinion du prof"],it:[["Rétractation de 10 jours en VEFA",0],["Les bureaux ne remonteront jamais",1],["Tontine et viager vont prendre de plus en plus de place",1],["PTZ : 6 ans d'occupation",0],["Le Pinel était dépassé",1],["Agrément AMF obligatoire",0]],w:"Sur une copie, on distingue la règle (avec sa source) de l'avis (avec ses arguments)."},
{i:"f264_30",u:264,t:"order",d:.6,q:"Remets dans l'ordre la méthode pour traiter un cas client à l'examen.",it:["Identifier pour qui, pour quoi, pour combien de temps","Choisir l'outil adapté","Vérifier les conditions","Faire le calcul","Signaler les risques et conclure"],w:"Diagnostic, outil, conditions, chiffres, risques. Toujours dans cet ordre."},
{i:"f264_31",u:264,t:"story",d:.65,q:"Cas final : quelle stratégie proposes-tu ?",ctx:"Élise, 50 ans, cadre à Lille, tranche à 30 %, 60 000 € d'épargne, veut un complément de retraite dans 10 ans, sans soucis de gestion au quotidien.",sc:[{who:"Élise",txt:"Je veux des revenus plus tard, mais pas de locataires à gérer."}],o:["Des SCPI diversifiées sur 10 ans, en surveillant la fiscalité","Un T2 Jeanbrun géré seule, avec neuf ans de locataires","Un PTZ pour acheter un studio à louer en meublé","Une tontine avec son voisin pour réduire son impôt"],a:0,w:"Pas de gestion, horizon long : SCPI. À 30 %, les revenus seront fortement taxés, d'où l'intérêt d'étudier aussi l'assurance-vie."},
{i:"f264_32",u:264,t:"story",d:.7,q:"Synthèse finale : Nathalie te demande ce que tu as retenu.",sc:[{who:"Nathalie Wattel",txt:"En une phrase, ce qui fait un bon conseiller."}],o:["« Écouter le projet, choisir l'outil, vérifier chaque règle à jour »","« Proposer au client le produit qui rapporte le plus de commissions »","« Recopier les notes du cours sans jamais vérifier les chiffres »","« Vendre du Pinel à tout le monde, c'est toujours rentable »"],a:0,w:"Pour qui, pour quoi, pour combien de temps. Et des règles vérifiées, datées, pas recopiées."}
