/*UNIT*/
{id:183,c:"NUTRI",n:"Module 1",t:"Pourquoi on prend du poids : les chiffres, l'IMC, les trois piliers",col:"--green",ic:"⚖️",guide:`
<h3>Ton premier jour au cabinet</h3>
<div class="gstory">Lyon, quartier de la Croix-Rousse. Tu commences ton stage chez Nora Benali, diététicienne-nutritionniste. Première patiente : Chloé, 28 ans, qui s'assoit en soupirant : « J'ai pris 9 kilos depuis que je suis en couple. Je mange pareil qu'avant, je vous jure. » Nora sourit : « On va chercher ensemble. Mais avant de parler de votre assiette, parlez-moi de vos nuits et de vos journées. » Tout ce cours part de cette réponse, qui est aussi celle de la médecin nutritionniste Laurence Plumey dans le podcast LEGEND : le poids se joue sur trois terrains, pas un seul.</div>
<p>Tu retrouveras tout au long du cours : <b>Nora</b> (ta tutrice), <b>Chloé</b> (28 ans, prise de poids en couple), <b>Mehdi</b> (34 ans, agent de sécurité de nuit), la famille <b>Martin</b> (Léna, 8 ans, en surpoids, parents qui rentrent tard), <b>Paul</b> (52 ans, cadre, amateur de bière, foie gras au bilan), <b>Inès</b> (31 ans, projet de bébé), <b>Théo</b> (19 ans, étudiant, fast-food et boissons énergisantes) et <b>Mme Garcia</b> (67 ans, a arrêté les laitages).</p>
<h3>Qui est qui ? Les métiers de la nutrition</h3>
<table><tr><th>Titre</th><th>Ce qu'il garantit</th></tr>
<tr><td><b>Médecin nutritionniste</b></td><td>Un médecin spécialisé en nutrition, souvent rattaché à l'endocrinologie (l'étude des hormones : diabète, thyroïde, obésité). C'est le cas de Laurence Plumey, qui a créé la consultation d'obésité de l'enfant à l'hôpital Necker, puis travaille avec des adultes à l'hôpital Antoine-Béclère de Clamart.</td></tr>
<tr><td><b>Diététicien</b></td><td>Un titre <b>protégé</b> par le Code de la santé publique : il faut un diplôme reconnu (BTS diététique ou BUT génie biologique parcours diététique)</td></tr>
<tr><td><b>« Nutritionniste » seul</b></td><td>Un mot <b>non protégé</b> : n'importe qui peut l'utiliser, comme le souligne Laurence Plumey</td></tr></table>
<h3>L'épidémie en chiffres</h3>
<ul><li>Près d'<b>un adulte sur deux</b> en France est en surpoids ou en obésité (48,8 % selon les chiffres cités dans le podcast).</li>
<li>Environ <b>18 %</b> des adultes sont obèses, soit près de <b>10 millions</b> de personnes (Ligue contre l'obésité, 2024).</li>
<li>En 1997, l'obésité touchait environ <b>9 %</b> des adultes : elle a doublé en une génération.</li>
<li>Si la tendance continue, on pourrait atteindre <b>30 %</b> d'obésité vers 2050, le niveau actuel des États-Unis.</li></ul>
<h3>L'IMC, le repère médical</h3>
<div class="formula">IMC = poids (kg) / taille (m) × taille (m)
Moins de 18,5  : maigreur
18,5 à 25      : corpulence normale (idéal : 20 à 22)
25 à 30        : surpoids
30 et plus     : obésité
Exemple : 80 kg, 1,80 m → 80 / 3,24 = 24,7</div>
<p>L'IMC est un repère simple, utilisé notamment pour décider d'une chirurgie de l'obésité. Il a ses limites : il ne distingue pas le muscle de la graisse (un rugbyman peut avoir un IMC élevé sans excès de gras). L'obésité, au fond, c'est un <b>excès de masse grasse</b>. On complète donc avec le <b>tour de taille</b> : au-delà de <b>94 cm</b> chez l'homme et <b>80 cm</b> chez la femme, le risque augmente (repères de la Fédération internationale du diabète).</p>
<h3>La régulation : une machine d'une finesse incroyable</h3>
<p>On mange environ <b>40 tonnes</b> de nourriture au cours d'une vie (environ 1,5 kg par jour) et on ne prend, en moyenne, que quelques kilos. Le cerveau règle la faim et la satiété avec une précision remarquable. La prise de poids, c'est quand ce système est dérégulé.</p>
<h3>Pourquoi on grossit plus qu'avant : les trois piliers</h3>
<div class="gmnemo"><b>N.AP.SO : « Nos Assiettes Pèsent, Sommeil Oublié ».</b> <b>N</b> comme nutrition, <b>AP</b> comme activité physique, <b>SO</b> comme sommeil. C'est le nom de la <b>napsothérapie</b>, la méthode de prévention créée par Laurence Plumey en 2020. Image : un tabouret à trois pieds. Si un pied est trop court (tu dors mal), le tabouret penche, même si l'assiette est parfaite.</div>
<p>Le mode de vie moderne attaque les trois pieds à la fois : on dort moins (écrans, séries), on bouge moins (on ne marche plus pour trouver sa nourriture), on mange plus gras et plus sucré. La génétique compte pour environ <b>50 %</b>, l'environnement pour l'autre moitié.</p>
<div class="gtrap">Deux pièges. Le premier : croire que le poids ne dépend que de l'assiette. Chloé n'a pas changé ce qu'elle mange, mais peut-être son sommeil, son activité ou ses sorties. Le second : se croire « condamné » par ses gènes. Des gènes défavorables n'empêchent pas de garder un poids stable si l'on dort, bouge et mange bien. À l'inverse, des gènes protecteurs ne protègent pas d'un mode de vie déréglé.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Calculer un IMC et le classer</li><li>Citer les chiffres clés de l'obésité en France</li><li>Distinguer médecin nutritionniste, diététicien et « nutritionniste »</li><li>Nommer les trois piliers N.AP.SO et la part des gènes</li></ul>`},
/*EXOS*/
{i:"a183_01",u:183,t:"num",d:.2,nw:"L'IMC",q:"Chloé mesure 1,65 m et pèse 68 kg. Quel est son IMC (arrondi à une décimale) ?",a:25,tol:.1,un:"",h:"Poids divisé par la taille au carré",w:"68 / (1,65 × 1,65) = 68 / 2,72 ≈ 25,0 : juste à la limite du surpoids. Un chiffre ne dit pas tout : on regarde aussi le tour de taille et le mode de vie."},
{i:"a183_02",u:183,t:"sort",d:.25,q:"Classe chaque IMC dans sa catégorie.",bins:["Maigreur","Normal","Surpoids","Obésité"],it:[["17,5",0],["21",1],["27",2],["33",3],["24,5",1],["29,9",2]],w:"Moins de 18,5 maigreur, 18,5 à 25 normal (idéal 20 à 22), 25 à 30 surpoids, 30 et plus obésité."},
{i:"a183_03",u:183,t:"story",d:.25,q:"Que répond Nora à Chloé ?",sc:[{who:"Chloé",txt:"J'ai pris 9 kilos depuis que je suis en couple, mais je mange exactement pareil."}],o:["« Parlons d'abord de votre sommeil et de votre activité, pas seulement de l'assiette. »","« C'est impossible, vous mangez forcément plus qu'avant sans vous en rendre compte. »","« On va commencer un régime strict dès demain pour perdre ces 9 kilos rapidement. »","« C'est génétique, il n'y a malheureusement pas grand-chose à faire dans votre cas précis. »"],a:0,w:"Les trois piliers N.AP.SO : nutrition, activité physique, sommeil. Un régime seul peut rater la vraie cause, et les gènes n'expliquent que la moitié."},
{i:"a183_04",u:183,t:"multi",d:.25,nw:"Les trois piliers",q:"Quels sont les trois piliers de la napsothérapie ?",o:["La nutrition","L'activité physique","Le sommeil","Les compléments alimentaires","Le jeûne"],a:[0,1,2],w:"N comme nutrition, AP comme activité physique, SO comme sommeil. Un tabouret à trois pieds : si un pied est court, tout penche."},
{i:"a183_05",u:183,t:"tf",d:.2,q:"En France, le titre de « nutritionniste » seul est protégé par la loi.",a:false,w:"Il ne l'est pas : n'importe qui peut l'utiliser. Le titre de diététicien est protégé, et un médecin nutritionniste est un médecin."},
{i:"a183_06",u:183,t:"slider",d:.3,q:"Quel pourcentage des adultes français est obèse aujourd'hui, environ ?",min:0,max:50,step:1,a:18,tol:1,pre:"",un:" %",w:"Environ 18 %, soit près de 10 millions de personnes. Et près d'un adulte sur deux est en surpoids ou en obésité."},
{i:"a183_07",u:183,t:"fill",d:.25,q:"L'IMC se calcule en divisant le poids en kilos par la taille en mètres au ___.",o:["carré","cube","double","total"],a:0,w:"IMC = poids / taille². Pour 1,80 m : 1,80 × 1,80 = 3,24."},
{i:"a183_08",u:183,t:"match",d:.3,q:"Associe chaque titre à ce qu'il garantit.",p:[["Médecin nutritionniste","Un médecin formé à la nutrition"],["Diététicien","Un titre protégé, avec diplôme reconnu"],["Nutritionniste seul","Un mot non protégé"],["Endocrinologue","Un médecin spécialiste des hormones"]],w:"Pour choisir un professionnel, le titre compte. L'endocrinologie couvre le diabète, la thyroïde et l'obésité."},
{i:"a183_09",u:183,t:"story",d:.3,q:"Paul conteste son IMC. Que lui réponds-tu ?",sc:[{who:"Paul",txt:"Mon IMC est à 29, mais c'est du muscle, j'ai fait du rugby à 20 ans !"},{who:"Toi",me:true,txt:"(son tour de taille mesure 108 cm)"}],o:["« L'IMC confond muscle et gras, mais votre tour de taille montre trop de graisse abdominale. »","« Vous avez raison, l'IMC n'a aucune valeur pour les anciens sportifs, oublions-le complètement. »","« Avec un IMC de 29, vous êtes obèse, il faut envisager tout de suite une chirurgie. »","« Le rugby à 20 ans protège à vie du surpoids, vous n'avez vraiment pas à vous inquiéter. »"],a:0,w:"L'IMC a une limite réelle, d'où le tour de taille : 108 cm dépasse nettement le repère de 94 cm chez l'homme. Et un IMC de 29 est un surpoids, pas une obésité."},
{i:"a183_10",u:183,t:"tiles",d:.3,q:"Reconstitue la définition de l'obésité.",a:["Un","excès","de","masse","grasse"],dd:["poids","muscle","eau"],w:"Pas simplement « trop de kilos » : trop de graisse. C'est pourquoi on complète l'IMC par le tour de taille."},
{i:"a183_11",u:183,t:"mcq",d:.3,q:"Quelle est la part des gènes dans nos comportements et notre poids, selon Laurence Plumey ?",o:["Environ 50 %","Environ 10 %","Environ 90 %","Aucune"],a:0,w:"50 % gènes, 50 % environnement (alimentation, activité, sommeil). Les gènes chargent le pistolet, le mode de vie appuie ou non sur la gâchette."},
{i:"a183_12",u:183,t:"slider",d:.35,q:"Quel IMC Laurence Plumey considère-t-elle comme l'idéal (valeur haute de la zone) ?",min:15,max:30,step:1,a:22,tol:0,pre:"",un:"",w:"Idéal entre 20 et 22. La zone normale va de 18,5 à 25."},
{i:"a183_13",u:183,t:"num",d:.35,q:"On mange environ 1,5 kg de nourriture par jour. Combien de tonnes en 75 ans (arrondi à l'unité) ?",a:41,tol:1,un:" t",h:"1,5 × 365 × 75, puis en tonnes",w:"1,5 × 365 × 75 ≈ 41 000 kg, soit environ 41 tonnes. Et on ne prend que quelques kilos : la régulation du cerveau est d'une finesse incroyable."},
{i:"a183_14",u:183,t:"tf",d:.3,q:"Des gènes favorables à la prise de poids condamnent forcément à l'obésité.",a:false,w:"Avec un bon sommeil, de l'activité et une alimentation équilibrée, on peut garder un poids stable malgré des gènes défavorables. L'environnement compte pour l'autre moitié."},
{i:"a183_15",u:183,t:"sort",d:.35,q:"Classe chaque facteur moderne dans le pilier qu'il abîme.",bins:["Nutrition","Activité physique","Sommeil"],it:[["Les séries enchaînées jusqu'à 1 h",2],["Les boissons sucrées au rayon boissons",0],["La livraison de repas à domicile",0],["L'ascenseur et la voiture pour tout",1],["Le téléphone dans le lit",2],["Le télétravail sans déplacement",1]],w:"Le mode de vie moderne attaque les trois pieds du tabouret en même temps. D'où l'intérêt d'un bilan complet, pas seulement alimentaire."},
{i:"a183_16",u:183,t:"fill",d:.4,q:"Au-delà de 94 cm de tour de taille chez l'homme et de ___ cm chez la femme, le risque augmente.",o:["80","70","100","90"],a:0,w:"Repères de la Fédération internationale du diabète. Le tour de taille mesure la graisse du ventre, la plus liée aux maladies métaboliques."},
{i:"a183_17",u:183,t:"story",d:.4,q:"Un client te demande conseil. Que réponds-tu ?",sc:[{who:"Théo",txt:"J'ai trouvé un « nutritionniste » sur Instagram qui vend un programme détox. C'est un pro, non ?"}],o:["« Le titre n'est pas protégé : vérifie s'il est médecin ou diététicien diplômé. »","« Oui, s'il s'appelle nutritionniste, il a forcément fait des études de santé. »","« Oui, tous les nutritionnistes sur Instagram sont contrôlés par l'Ordre des médecins. »","« Non, les nutritionnistes sont toujours des arnaqueurs, fuis-les absolument. »"],a:0,w:"« Nutritionniste » seul ne garantit rien. Diététicien (titre protégé) ou médecin nutritionniste : là, il y a une formation vérifiable. Pas besoin pour autant de rejeter tout le monde."},
{i:"a183_18",u:183,t:"multi",d:.4,q:"Quelles limites l'IMC a-t-il ?",o:["Il ne distingue pas muscle et graisse","Il ne dit pas où se trouve la graisse","Il ne tient pas compte du mode de vie","Il est impossible à calculer sans prise de sang","Il n'est jamais utilisé en médecine"],a:[0,1,2],w:"Il reste un repère médical utile (utilisé pour la chirurgie de l'obésité), mais on le complète : tour de taille, habitudes, antécédents."},
{i:"a183_19",u:183,t:"mcq",d:.4,q:"En 1997, quelle part des adultes français était obèse ?",o:["Environ 9 %","Environ 2 %","Environ 18 %","Environ 30 %"],a:0,w:"Environ 9 % en 1997, environ 18 % aujourd'hui : l'obésité a doublé en une génération."},
{i:"a183_20",u:183,t:"order",d:.4,q:"Remets dans l'ordre la démarche de Nora avec un nouveau patient.",it:["Écouter son histoire","Explorer sommeil, activité et alimentation","Mesurer poids, taille et tour de taille","Identifier la vraie cause","Proposer une solution adaptée"],w:"Comprendre avant de conseiller : c'est ce que répète Laurence Plumey. Un régime donné sans comprendre la cause peut échouer."},
{i:"a183_21",u:183,t:"slider",d:.45,q:"Vers quel pourcentage d'obésité la France pourrait-elle monter vers 2050 si rien ne change ?",min:0,max:50,step:5,a:30,tol:0,pre:"",un:" %",w:"Environ 30 %, le niveau actuel des États-Unis. Un Français sur trois."},
{i:"a183_22",u:183,t:"num",d:.45,q:"Un homme de 1,80 m veut rester à un IMC de 25 au maximum. Quel poids maximal, en kg (arrondi à l'unité) ?",a:81,tol:1,un:" kg",h:"25 × 1,80 × 1,80",w:"25 × 3,24 = 81 kg. Laurence Plumey cite environ 80 kg pour un homme de 1,80 m : c'est la limite haute de la corpulence normale."},
{i:"a183_23",u:183,t:"story",d:.45,q:"Mehdi pense que seul son assiette compte. Que lui dis-tu ?",sc:[{who:"Mehdi",txt:"Je travaille de nuit, je dors 5 heures le jour. Mais bon, c'est mon alimentation le problème, non ?"}],o:["« Votre sommeil compte autant : c'est l'un des trois piliers, avec l'activité. »","« Oui, le sommeil n'a aucun rapport avec le poids, concentrons-nous sur l'assiette. »","« Arrêtez de travailler de nuit, c'est la seule solution possible dans votre cas. »","« Dormir 5 heures, c'est largement suffisant pour un adulte en bonne santé. »"],a:0,w:"N.AP.SO : le sommeil est un pilier à part entière. Le module 3 montrera comment le manque de sommeil fait grossir, avec des chiffres."},
{i:"a183_24",u:183,t:"match",d:.5,q:"Associe chaque chiffre à ce qu'il mesure.",p:[["18 %","Adultes obèses en France"],["48,8 %","Adultes en surpoids ou obèses (chiffre du podcast)"],["9 %","Obésité en 1997"],["30 %","Obésité possible en 2050"]],w:"Des chiffres à connaître pour mesurer l'ampleur du problème, et pour ne pas culpabiliser seul : c'est un phénomène de société."},
{i:"a183_25",u:183,t:"tf",d:.5,q:"La napsothérapie a été créée en 2020, au moment où les confinements ont fait grossir beaucoup de personnes.",a:true,w:"Laurence Plumey l'a créée en voyant les gens dormir moins, bouger moins et manger plus. C'est un métier de prévention primaire : agir avant la maladie."},
{i:"a183_26",u:183,t:"fill",d:.5,q:"La prévention ___ consiste à agir avant l'apparition de la maladie.",o:["primaire","secondaire","tertiaire","chirurgicale"],a:0,w:"Primaire : éviter la maladie. Secondaire : la dépister tôt. Tertiaire : limiter ses complications. La napsothérapie vise la prévention primaire."},
{i:"a183_27",u:183,t:"story",d:.55,q:"Quelle est la plus grande limite de ce raisonnement de Théo ?",sc:[{who:"Théo",txt:"Mon pote mange n'importe quoi et reste maigre. Moi je grossis. Donc c'est injuste et je n'y peux rien."}],o:["Les gènes comptent pour moitié, mais l'autre moitié dépend de son mode de vie","Les gènes ne jouent aucun rôle, son pote ment forcément sur ce qu'il mange","Théo a raison, le poids est entièrement décidé dès la naissance, sans recours","Le pote de Théo finira obèse quoi qu'il fasse, c'est inévitable"],a:0,w:"Oui, on n'est pas égaux (module 15). Mais l'environnement pèse aussi 50 % : Théo a de vrais leviers, et son ami pourrait grossir s'il se met à mal dormir et à ne plus bouger."},
{i:"a183_28",u:183,t:"mcq",d:.55,q:"Pourquoi l'IMC reste-t-il utilisé malgré ses limites ?",o:["C'est un repère objectif, simple et commun à tous les médecins","C'est la mesure la plus précise de la masse grasse","Il remplace l'avis et l'examen du médecin traitant","Il est obligatoire pour s'inscrire à la salle de sport"],a:0,w:"Pour décider d'une chirurgie, il faut des repères objectifs, pas un coup d'œil. L'IMC en est un, complété par d'autres mesures."},
{i:"a183_29",u:183,t:"sort",d:.6,q:"Classe chaque affirmation : vraie ou fausse ?",bins:["Vrai","Faux"],it:[["L'obésité est une maladie chronique",0],["L'obésité est seulement un manque de volonté",1],["Le regard des autres fait souffrir les personnes obèses",0],["Un bébé bien rond est forcément en mauvaise santé",1],["Le poids se joue aussi la nuit",0]],w:"L'obésité est une maladie chronique, source d'autres maladies, et la grossophobie ajoute une souffrance. Les petits bourrelets d'un nourrisson, eux, sont normaux (module 5)."},
{i:"a183_30",u:183,t:"tiles",d:.6,q:"Reconstitue le moyen mnémotechnique des trois piliers.",a:["Nos","Assiettes","Pèsent","Sommeil","Oublié"],dd:["Sport","Régime","Poids"],w:"N.AP.SO : Nutrition, Activité Physique, Sommeil."},
{i:"a183_31",u:183,t:"story",d:.65,q:"Chloé demande pourquoi on regarde son tour de taille. Que lui explique Nora ?",sc:[{who:"Chloé",txt:"Pourquoi vous mesurez mon ventre ? La balance ne suffit pas ?"}],o:["« La graisse du ventre est la plus liée aux maladies. La balance ne dit pas où est le gras. »","« C'est juste pour choisir la taille de vos vêtements, rien de plus, rassurez-vous. »","« La balance ne sert à rien, seul le tour de taille compte vraiment en nutrition moderne. »","« C'est une obligation administrative pour remplir votre dossier de la Sécurité sociale. »"],a:0,w:"Le tour de taille complète la balance : il repère la graisse abdominale, la plus dangereuse. Les deux mesures se complètent."},
{i:"a183_32",u:183,t:"tf",d:.65,q:"L'obésité de l'enfant peut être considérée comme une maladie qu'on laisse passer, car elle disparaît toujours à l'adolescence.",a:false,w:"Une grande partie des enfants obèses le restent (module 5). D'où la consultation créée par Laurence Plumey à Necker : réagir tôt, sans régime, sur les trois piliers."}
