/*UNIT*/
{id:186,c:"NUTRI",n:"Module 4",t:"Bouger : la marche avant la salle de sport",col:"--green",ic:"🚶",guide:`
<h3>Le rat sur le tapis de course</h3>
<div class="gstory">Pendant ses études de médecine, Laurence Plumey faisait courir des rats génétiquement obèses sur un tapis de course pour mesurer l'effet de l'activité physique sur leur poids. Trente ans plus tard, Nora ouvre le dossier de Paul : cadre, voiture, bureau, ascenseur, canapé. 1 800 pas par jour selon son téléphone. « Je n'aime pas le sport, prévient-il. » Nora sourit : « Parfait. On ne va pas parler de sport. On va parler de marcher. »</div>
<h3>Le constat</h3>
<ul><li>L'ANSES estime qu'environ <b>95 %</b> des adultes français sont exposés à un risque pour leur santé par manque d'activité physique ou excès de temps assis.</li>
<li>Selon Laurence Plumey, seuls environ <b>5 %</b> des adultes font réellement du sport de façon régulière.</li>
<li>Nos ancêtres parcouraient <b>15 à 20 km</b> par jour pour trouver leur nourriture. Aujourd'hui, elle arrive toute seule.</li></ul>
<h3>Les repères officiels</h3>
<table><tr><th>Repère</th><th>Contenu</th></tr>
<tr><td><b>OMS (adultes)</b></td><td>150 à 300 minutes d'activité modérée par semaine, ou 75 à 150 minutes d'activité intense, plus du renforcement musculaire 2 fois par semaine</td></tr>
<tr><td><b>France (PNNS)</b></td><td>Au moins 30 minutes d'activité modérée par jour</td></tr>
<tr><td><b>Conseil de Laurence Plumey</b></td><td>Marcher au moins <b>45 minutes par jour</b></td></tr>
<tr><td><b>Sédentarité</b></td><td>Se lever et bouger quelques minutes toutes les 1 h 30 à 2 h passées assis</td></tr></table>
<div class="gmnemo"><b>« Les marches avant les haltères. »</b> Double sens : les <b>marches</b> d'escalier et la <b>marche</b> à pied passent avant la salle de sport. Pour ceux qui n'aiment pas le sport, le bureau devient un terrain d'entraînement : toilettes de l'étage du dessus, fontaine à eau plus loin, escaliers au lieu de l'ascenseur, une station de métro à pied.</div>
<h3>Pourquoi la marche est si efficace</h3>
<p>Elle ne coûte rien, elle est accessible à presque tous, et elle agit partout : elle irrigue les neurones, fait travailler le cœur, vascularise les organes, entretient les articulations, aide à réfléchir. Elle entretient aussi la masse musculaire, donc la « chaudière » du métabolisme (module 2).</p>
<h3>L'activité du quotidien compte</h3>
<p>Les dépenses « invisibles » (marcher, se lever, porter, jardiner, monter les escaliers) peuvent peser plusieurs centaines de calories par jour. Les chercheurs parlent de <b>NEAT</b> (dépense d'activité hors exercice). Chez un sédentaire, c'est souvent le levier le plus simple à augmenter.</p>
<div class="gtrap">Deux nuances. Le chiffre de « 500 mètres par jour » cité dans le podcast est sans doute sous-estimé : un adulte sédentaire fait plutôt 3 000 à 5 000 pas, soit 2 à 4 km. L'idée reste juste : on marche beaucoup moins qu'avant. Autre nuance : les « 10 000 pas » sont un repère marketing né au Japon dans les années 1960. Les études récentes montrent que les bénéfices sur la mortalité augmentent jusqu'à environ 6 000 à 8 000 pas chez les plus de 60 ans et 8 000 à 10 000 pas chez les plus jeunes. Chaque pas compte, même en dessous.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Citer les repères de l'OMS, du PNNS et le conseil des 45 minutes</li><li>Proposer des activités intégrées au quotidien pour quelqu'un qui n'aime pas le sport</li><li>Expliquer pourquoi la marche aide à maigrir et à rester en bonne santé</li><li>Nuancer le mythe des 10 000 pas</li></ul>`},
/*EXOS*/
{i:"a186_01",u:186,t:"story",d:.2,nw:"Bouger sans faire de sport",q:"Paul n'aime pas le sport. Que lui propose Nora ?",sc:[{who:"Paul",txt:"Je vous préviens, je déteste la salle de sport."}],o:["« Marchez 45 minutes par jour, intégrées à vos trajets et au bureau. »","« Alors inscrivez-vous quand même, trois séances de musculation par semaine. »","« Tant pis, sans sport on ne peut rien faire pour votre poids, malheureusement. »","« Compensez en mangeant beaucoup moins, le sport n'est pas vraiment nécessaire. »"],a:0,w:"La marche est accessible, gratuite et efficace. Intégrée au quotidien (escaliers, trajets), elle ne demande pas d'aimer le sport."},
{i:"a186_02",u:186,t:"slider",d:.25,q:"Combien de minutes de marche par jour Laurence Plumey conseille-t-elle au minimum ?",min:0,max:120,step:5,a:45,tol:0,pre:"",un:" min",w:"Au moins 45 minutes. Le PNNS dit 30 minutes d'activité modérée : Laurence Plumey place la barre un peu plus haut."},
{i:"a186_03",u:186,t:"mcq",d:.25,q:"Selon l'ANSES, quelle part des adultes est exposée à un risque par manque d'activité ou excès de sédentarité ?",o:["Environ 95 %","Environ 25 %","Environ 50 %","Environ 5 %"],a:0,w:"Environ 95 %. Et seuls environ 5 % font du sport régulièrement, selon Laurence Plumey."},
{i:"a186_04",u:186,t:"multi",d:.3,nw:"Bouger au bureau",q:"Quelles idées permettent de bouger au bureau ?",o:["Utiliser les toilettes de l'étage du dessus","Prendre les escaliers plutôt que l'ascenseur","Aller à une fontaine à eau plus éloignée","Descendre une station de métro plus tôt","Manger à son bureau pour gagner du temps"],a:[0,1,2,3],w:"Chaque petit déplacement compte. Manger au bureau, au contraire, supprime une occasion de marcher."},
{i:"a186_05",u:186,t:"match",d:.3,nw:"Les repères d'activité",q:"Associe chaque repère à sa source.",p:[["150 à 300 min d'activité modérée par semaine","OMS"],["30 min d'activité modérée par jour","PNNS (France)"],["45 min de marche par jour","Laurence Plumey"],["Se lever toutes les 1 h 30 à 2 h","Lutte contre la sédentarité"]],w:"Plusieurs repères, un même message : bouger chaque jour et casser le temps assis."},
{i:"a186_06",u:186,t:"tf",d:.25,q:"Faire du sport le soir compense entièrement le fait de rester assis toute la journée.",a:false,w:"La sédentarité est un risque en soi : il faut aussi casser les longues périodes assises en se levant régulièrement."},
{i:"a186_07",u:186,t:"fill",d:.3,q:"Nos ancêtres marchaient environ ___ km par jour pour trouver leur nourriture.",o:["15 à 20","1 à 2","50 à 60","100"],a:0,w:"15 à 20 km : la nourriture ne venait pas toute seule. Notre corps est fait pour bouger, beaucoup."},
{i:"a186_08",u:186,t:"num",d:.3,q:"Paul marche 45 minutes par jour, 5 jours par semaine. Combien de minutes par semaine ?",a:225,tol:0,un:" min",h:"45 × 5",w:"225 minutes : il est dans la fourchette de l'OMS (150 à 300 minutes d'activité modérée)."},
{i:"a186_09",u:186,t:"story",d:.35,q:"Chloé croit que seule une heure de salle compte. Que lui dis-tu ?",sc:[{who:"Chloé",txt:"Je n'ai pas le temps d'aller à la salle, donc je ne fais rien."}],o:["« Escaliers, marche et trajets comptent aussi : chaque pas brûle des calories. »","« Sans salle de sport, l'activité physique ne sert malheureusement à rien du tout. »","« Achetez un vélo d'appartement, c'est la seule solution quand on manque de temps. »","« Rattrapez tout le dimanche avec trois heures de sport, ça compensera la semaine. »"],a:0,w:"L'activité du quotidien (le NEAT) peut peser plusieurs centaines de calories par jour. C'est souvent le levier le plus simple."},
{i:"a186_10",u:186,t:"sort",d:.35,q:"Classe chaque activité : exercice planifié ou activité du quotidien ?",bins:["Exercice planifié","Activité du quotidien"],it:[["Séance de natation",0],["Monter trois étages à pied",1],["Jardiner une heure",1],["Cours de boxe",0],["Aller à la boulangerie à pied",1],["Footing du dimanche",0]],w:"Les deux comptent. Pour un sédentaire, l'activité du quotidien est souvent la première marche."},
{i:"a186_11",u:186,t:"tiles",d:.35,q:"Reconstitue le moyen mnémotechnique de l'activité physique.",a:["Les","marches","avant","les","haltères"],dd:["régimes","salles","toujours"],w:"Marches d'escalier et marche à pied avant la salle de sport."},
{i:"a186_12",u:186,t:"mcq",d:.35,q:"Quel bénéfice de la marche Laurence Plumey cite-t-elle ?",o:["Elle irrigue les neurones et fait réfléchir","Elle remplace totalement une nuit de sommeil","Elle brûle 1 000 kcal en seulement 10 minutes","Elle n'agit que sur les muscles des jambes"],a:0,w:"Neurones, cœur, organes, articulations, réflexion : la marche agit sur tout le corps."},
{i:"a186_13",u:186,t:"tf",d:.4,q:"Les 10 000 pas par jour sont un seuil scientifique précis en dessous duquel la marche ne sert à rien.",a:false,w:"C'est un repère marketing japonais des années 1960. Les bénéfices augmentent déjà bien avant, jusqu'à environ 6 000 à 10 000 pas selon l'âge."},
{i:"a186_14",u:186,t:"num",d:.4,q:"Paul passe de 1 800 à 7 000 pas par jour. Combien de pas en plus par semaine ?",a:36400,tol:1,un:" pas",h:"(7 000 − 1 800) × 7",w:"5 200 × 7 = 36 400 pas de plus, soit environ 25 km par semaine. Sans jamais mettre les pieds à la salle."},
{i:"a186_15",u:186,t:"story",d:.4,q:"Un patient a pris 20 kg en un an après la naissance de son enfant. Quelle est la vraie cause, selon Laurence Plumey ?",ctx:"Il allait au sport le soir. Depuis la naissance, il va chercher son enfant à la crèche à 18 h.",sc:[{who:"Le patient",txt:"Je ne mange pas plus qu'avant, je vous assure."}],o:["L'arrêt du sport : il faut réorganiser les soirs de crèche","Il mange forcément plus en cachette, un régime strict s'impose","La paternité fait grossir les hommes, c'est hormonal et inévitable","Il faut arrêter d'aller chercher l'enfant, le sport passe avant tout"],a:0,w:"Le problème n'était pas dans l'assiette. Solution : alterner avec son épouse deux soirs par semaine pour libérer deux séances. Comprendre avant de prescrire."},
{i:"a186_16",u:186,t:"fill",d:.4,q:"L'OMS recommande aussi du renforcement ___ deux fois par semaine.",o:["musculaire","cardiaque","mental","respiratoire"],a:0,w:"Le muscle fait tourner la chaudière (métabolisme de base) et protège les os et les articulations."},
{i:"a186_17",u:186,t:"order",d:.45,q:"Remets dans l'ordre un plan progressif pour Paul.",it:["Mesurer ses pas actuels","Ajouter les escaliers au bureau","Marcher 20 minutes le midi","Monter à 45 minutes par jour","Ajouter deux séances de renforcement"],w:"Petites marches, progression, puis renforcement. On construit l'habitude avant d'augmenter l'intensité."},
{i:"a186_18",u:186,t:"multi",d:.45,q:"Pourquoi bouge-t-on beaucoup moins qu'avant ?",o:["La nourriture arrive sans effort","Les transports motorisés et l'ascenseur","Le travail assis devant un écran","La fatigue liée au manque de sommeil","Les humains ont perdu leurs muscles"],a:[0,1,2,3],w:"L'environnement a changé, pas notre biologie. Et la fatigue due au mauvais sommeil fait encore moins bouger (module 3)."},
{i:"a186_19",u:186,t:"slider",d:.5,q:"Toutes les combien d'heures, au maximum, faut-il se lever quand on est assis (valeur haute) ?",min:0,max:5,step:.5,a:2,tol:0,pre:"",un:" h",w:"Toutes les 1 h 30 à 2 h. Quelques minutes debout ou à marcher suffisent à casser la sédentarité."},
{i:"a186_20",u:186,t:"story",d:.5,q:"Rappel du module 3 : pourquoi Mehdi ne va-t-il plus à la salle ?",sc:[{who:"Mehdi",txt:"Quand je me lève après 5 heures de sommeil, je n'ai la force de rien faire."}],o:["La fatigue du manque de sommeil le fait s'économiser","Il n'aime tout simplement pas le sport depuis toujours","La salle de sport est trop chère pour son budget","Il fait déjà assez de sport la nuit au travail"],a:0,w:"Premier mécanisme du sommeil court : on s'économise. Améliorer le sommeil relancera l'activité. Les piliers sont liés."},
{i:"a186_21",u:186,t:"tf",d:.5,q:"Le muscle entretenu par l'activité aide à brûler des calories même au repos.",a:true,w:"Plus de muscle, métabolisme de base plus élevé. C'est aussi pour cela que les hommes maigrissent plus vite."},
{i:"a186_22",u:186,t:"match",d:.55,q:"Associe chaque objection de patient à une réponse concrète.",p:[["« Je n'ai pas le temps »","Marcher pendant les trajets"],["« Je n'aime pas le sport »","Escaliers, marche, jardinage"],["« Je suis trop fatigué »","Protéger d'abord le sommeil"],["« Je ne sais pas par où commencer »","Compter ses pas, puis progresser"]],w:"Chaque objection a sa réponse. L'activité doit s'adapter à la vie du patient, pas l'inverse."},
{i:"a186_23",u:186,t:"fill",d:.55,q:"La dépense liée aux activités du quotidien hors exercice est appelée ___ par les chercheurs.",o:["NEAT","IMC","VO2 max","NAP"],a:0,w:"NEAT : Non-Exercise Activity Thermogenesis. Se lever, marcher, porter : ça compte vraiment."},
{i:"a186_24",u:186,t:"story",d:.6,q:"Chloé et son compagnon partagent de bons restaurants. Quelle idée Laurence Plumey propose-t-elle ?",sc:[{who:"Chloé",txt:"On adore les restos à deux, je ne veux pas arrêter."}],o:["« Gardez-les, et ajoutez une activité à faire à deux : c'est le sport en couple. »","« Arrêtez complètement les restaurants, c'est la seule façon de maigrir en couple. »","« Mangez chacun de votre côté, les couples grossissent toujours ensemble. »","« Allez au restaurant mais sans dessert, et le problème sera réglé. »"],a:0,w:"Quitte à partager des comportements pas toujours sains, partagez-en un excellent : bouger ensemble (module 14)."},
{i:"a186_25",u:186,t:"sort",d:.6,q:"Classe chaque affirmation : fondée ou mythe ?",bins:["Fondée","Mythe"],it:[["Marcher est bon pour le cerveau",0],["En dessous de 10 000 pas, marcher ne sert à rien",1],["Prendre les escaliers augmente la dépense",0],["Il faut aimer le sport pour être actif",1],["Rester assis longtemps est un risque en soi",0]],w:"Les bénéfices de la marche commencent dès les premiers pas. Et on peut être actif sans aimer le sport."},
{i:"a186_26",u:186,t:"mcq",d:.6,q:"Selon les études récentes, jusqu'à combien de pas les bénéfices sur la mortalité augmentent-ils chez les plus de 60 ans ?",o:["Environ 6 000 à 8 000","Environ 1 000","Environ 30 000","Aucun bénéfice mesurable"],a:0,w:"Environ 6 000 à 8 000 chez les plus de 60 ans, 8 000 à 10 000 chez les plus jeunes. Un objectif réaliste motive plus qu'un chiffre magique."},
{i:"a186_27",u:186,t:"num",d:.65,q:"Une personne de 80 kg dépense environ 4 kcal par minute en marchant. Combien de kcal pour 45 minutes ?",a:180,tol:1,un:" kcal",h:"4 × 45",w:"Environ 180 kcal par jour, soit plus de 1 200 kcal par semaine. Et surtout, un effet sur le sommeil, l'humeur et le muscle."},
{i:"a186_28",u:186,t:"tf",d:.65,q:"Le chiffre de « 500 mètres par jour » cité dans le podcast est probablement sous-estimé pour la plupart des adultes.",a:true,w:"Un adulte sédentaire fait plutôt 3 000 à 5 000 pas, soit 2 à 4 km. Le message reste juste : on marche bien moins qu'autrefois."},
{i:"a186_29",u:186,t:"story",d:.7,q:"Rappel du module 2 : pourquoi préserver son muscle pendant une perte de poids ?",sc:[{who:"Nora",txt:"Pourquoi j'insiste sur la marche et le renforcement pendant un régime ?"}],o:["« Pour garder une chaudière qui brûle, et éviter la reprise de poids. »","« Pour gagner du poids en muscle et masquer la perte sur la balance. »","« Parce que le muscle se transforme en graisse si on ne l'utilise pas. »","« Uniquement pour l'apparence, ça n'a aucun effet sur le métabolisme. »"],a:0,w:"Un régime sans activité fait fondre le muscle, donc baisser le métabolisme de base, et prépare la reprise. Le muscle ne se transforme pas en graisse : c'est un mythe."},
{i:"a186_30",u:186,t:"multi",d:.7,q:"Quels effets de la marche sont cités dans le module ?",o:["Elle vascularise mieux les organes","Elle fait travailler les articulations","Elle fait travailler le cœur","Elle détruit les graisses saturées de l'assiette","Elle remplace les fruits et légumes"],a:[0,1,2],w:"La marche agit sur tout le corps, mais ne remplace pas une alimentation équilibrée : les trois piliers restent liés."},
{i:"a186_31",u:186,t:"order",d:.75,q:"Remets dans l'ordre la réponse à la question « pourquoi on ne bouge plus ».",it:["Pendant des millénaires, bouger était vital","La nourriture devait être cherchée à pied","Aujourd'hui la nourriture arrive toute seule","On marche beaucoup moins","L'activité doit être réintégrée volontairement"],w:"Ce n'est pas une faute individuelle, c'est un changement d'environnement. D'où la nécessité de remettre du mouvement de façon volontaire."},
{i:"a186_32",u:186,t:"fill",d:.75,q:"Selon Laurence Plumey, seuls environ ___ % des adultes font du sport régulièrement.",o:["5","50","80","25"],a:0,w:"Environ 5 %. Raison de plus pour miser sur la marche et l'activité quotidienne, accessibles à tous."}
