/*UNIT*/
{id:187,c:"NUTRI",n:"Module 5",t:"Le poids commence avant la naissance : grossesse, bébé, enfant",col:"--green",ic:"👶",guide:`
<h3>Le biberon de soda</h3>
<div class="gstory">Laurence Plumey raconte le pire qu'elle ait vu : une famille arrive en consultation, l'enfant dans une poussette alors qu'il a passé l'âge, un biberon à la main. Dans le biberon, du soda. Ces parents ne voulaient pas nuire : ils pensaient faire plaisir. Un nourrisson sourit dès qu'on dépose une goutte d'eau sucrée sur sa langue. Chez Nora, la famille Martin s'inquiète pour Léna, 8 ans : « Elle adore le sucré, on ne sait plus quoi faire. Et on rentre tard, alors on dîne à 20 h 30 tous ensemble. »</div>
<h3>Pourquoi agir tôt chez l'enfant</h3>
<ul><li>Laurence Plumey cite <b>70 %</b> d'enfants obèses qui restent en surpoids à l'âge adulte. La grande méta-analyse de Simmonds (2016) donne des chiffres proches : environ <b>55 %</b> des enfants obèses le restent à l'adolescence, <b>80 %</b> des adolescents obèses le restent adultes, et environ <b>70 %</b> sont obèses après 30 ans.</li>
<li>Chez l'enfant, la graisse en excès augmente le <b>volume</b> des cellules graisseuses (adipocytes) mais aussi leur <b>nombre</b>, car les facteurs de croissance sont très actifs. Ces cellules ne disparaissent pas : l'obésité s'installe plus solidement.</li>
<li>Le carnet de santé contient une <b>courbe de corpulence</b> (IMC selon l'âge). Un « rebond d'adiposité » (la courbe qui remonte) avant 6 ans est un signal d'alerte.</li></ul>
<h3>Ne pas forcer à finir l'assiette</h3>
<p>Le cerveau de l'enfant règle très bien la faim et le <b>rassasiement</b> (le signal « j'ai assez mangé »). Le forcer à finir, c'est lui apprendre à passer en « mode manuel » : ignorer ses signaux. Adulte, il mangera alors par émotion, stress ou plaisir, même sans faim. Mieux vaut <b>servir une petite assiette</b> et le laisser se resservir.</p>
<div class="gmnemo"><b>« Petite assiette, grande écoute. »</b> On sert peu, on laisse redemander, on respecte le « j'ai plus faim ». Et pour les horaires, retiens <b>« 19-20 »</b> : dîner vers <b>19 h</b>, au lit vers <b>20 h</b> pour un enfant qui se lève à 7 h (il lui faut 10 à 11 heures de sommeil, et environ 2 heures pour digérer).</div>
<h3>Dans le ventre de la mère : la programmation</h3>
<p>Des études sur des enfants nés de mères ayant connu la famine pendant la guerre (la plus célèbre porte sur l'hiver de famine aux Pays-Bas en 1944-1945) montrent plus d'obésité, de diabète et de maladies cardiovasculaires à l'âge adulte. Laurence Plumey compare les gènes à des <b>ampoules</b> qui s'allument ou s'éteignent : c'est l'<b>épigénétique</b>.</p>
<table><tr><th>Situation pendant la grossesse</th><th>Ce que fait le bébé</th><th>Risque ensuite</th></tr>
<tr><td>Mère qui mange trop peu (famine, régime, anorexie)</td><td>Allume les gènes du stockage pour survivre, naît petit (2,5 kg au lieu de 3,5)</td><td>Placé ensuite dans l'abondance (« on va le remplumer »), il stocke plus que les autres</td></tr>
<tr><td>Mère qui mange trop (par exemple 35 kg de prise de poids)</td><td>Stocke beaucoup, naît macrosome (plus de 4 kg)</td><td>Garde une facilité à prendre du poids</td></tr></table>
<p>Le bébé hérite pour moitié des gènes de sa mère et pour moitié de ceux de son père : les bons comportements concernent donc les deux parents. Pendant la grossesse, il faut une alimentation variée, sans régime et sans excès, et <b>zéro alcool</b>. Le fœtus n'a pas les enzymes pour éliminer l'alcool, et même un verre peut abîmer son cerveau en développement.</p>
<div class="gtrap">Correction du podcast : un nouveau-né n'a pas 30 % de graisse à la naissance, mais environ <b>15 %</b> (ce qui en fait déjà le mammifère le plus gras à la naissance). Le pic d'environ <b>25 %</b> est atteint entre 4 et 9 mois, puis l'enfant s'affine en commençant à marcher. L'idée de Laurence Plumey reste juste : les petits bourrelets du nourrisson sont normaux et utiles, c'est une réserve d'énergie pour affronter le monde.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Expliquer pourquoi l'obésité de l'enfant s'installe durablement</li><li>Conseiller des parents sur l'assiette, les horaires et le sommeil</li><li>Expliquer la programmation fœtale avec l'image des ampoules</li><li>Donner les règles de la grossesse : pas de régime, pas d'excès, zéro alcool</li></ul>`},
/*EXOS*/
{i:"a187_01",u:187,t:"story",d:.2,nw:"Ne pas forcer à finir l'assiette",q:"Que conseilles-tu aux parents de Léna ?",sc:[{who:"Mme Martin",txt:"On l'oblige à finir son assiette, on ne veut pas gâcher."}],o:["« Servez-lui une petite assiette, et qu'elle se resserve si elle a faim. »","« Continuez, finir son assiette apprend à ne pas gâcher, c'est essentiel. »","« Supprimez les féculents du soir, ce sont eux qui la font tant grossir. »","« Donnez-lui un bon dessert quand elle finit tout, ça la motivera. »"],a:0,w:"Petite assiette, grande écoute. Forcer à finir apprend à ignorer le rassasiement ; le dessert en récompense associe nourriture et émotion."},
{i:"a187_02",u:187,t:"mcq",d:.25,q:"Selon Simmonds (2016), quelle part des adolescents obèses le restent à l'âge adulte ?",o:["Environ 80 %","Environ 10 %","Environ 30 %","Aucun"],a:0,w:"Environ 80 %. Et environ 55 % des enfants obèses le restent à l'adolescence. D'où l'urgence d'agir tôt, sans régime, sur les trois piliers."},
{i:"a187_03",u:187,t:"slider",d:.25,q:"Combien d'heures de sommeil faut-il à un enfant de 8 ans (valeur haute) ?",min:6,max:14,step:1,a:11,tol:0,pre:"",un:" h",w:"10 à 11 heures. Pour un lever à 7 h, au lit vers 20 h : le sommeil fait grandir et protège du surpoids."},
{i:"a187_04",u:187,t:"fill",d:.25,q:"Le signal du cerveau qui dit « j'ai assez mangé » s'appelle le ___.",o:["rassasiement","réflexe digestif","rythme","refus nerveux"],a:0,w:"Rassasiement (ou satiété). Le respecter chez l'enfant, c'est lui apprendre à écouter son corps toute sa vie."},
{i:"a187_05",u:187,t:"tf",d:.25,q:"Chez l'enfant qui grossit, les cellules graisseuses augmentent en volume mais aussi en nombre.",a:true,w:"Les facteurs de croissance multiplient les cellules, dont les adipocytes. Elles ne disparaissent pas ensuite : l'obésité s'installe plus solidement. La méta-analyse de Simmonds (2016) montre qu'environ 80 % des adolescents obèses le restent adultes."},
{i:"a187_06",u:187,t:"num",d:.3,q:"Léna doit se lever à 7 h et dormir 11 h, et il faut environ 2 h de digestion avant le coucher. À quelle heure devrait-elle dîner au plus tard ?",a:18,tol:0,un:" h",h:"7 h − 11 h = coucher, puis − 2 h",w:"Coucher à 20 h, dîner à 18 h au plus tard (18 h 30-19 h reste acceptable pour un dîner léger). Laurence Plumey parle de 18 h 30-19 h."},
{i:"a187_07",u:187,t:"match",d:.3,nw:"La programmation fœtale",q:"Associe chaque situation pendant la grossesse à son effet.",p:[["Mère qui mange trop peu","Bébé qui allume les gènes du stockage"],["Mère qui mange beaucoup trop","Bébé macrosome, plus de 4 kg"],["Alcool pendant la grossesse","Cerveau du fœtus abîmé"],["Alimentation variée sans excès","Meilleures chances pour l'enfant"]],w:"Les gènes sont comme des ampoules : l'environnement pendant la grossesse les allume ou les éteint. C'est l'épigénétique."},
{i:"a187_08",u:187,t:"story",d:.3,q:"Une future maman s'inquiète. Que lui dis-tu ?",sc:[{who:"Inès (enceinte)",txt:"Si mon bébé devient obèse, ce sera ma faute ? Je me sens coupable de tout ce que je mange."}],o:["« Le bébé hérite des deux parents : mangez varié, sans régime ni excès, sans culpabiliser. »","« Oui, tout dépend uniquement de vous, faites un régime strict pour être tranquille. »","« Ne vous inquiétez pas, l'alimentation pendant la grossesse n'a aucune influence sur lui. »","« Mangez pour deux, le bébé a besoin de beaucoup de grosses réserves pour naître. »"],a:0,w:"Rassurer sans nier : moitié gènes de la mère, moitié du père, et l'environnement compte. Ni régime, ni excès, zéro alcool."},
{i:"a187_09",u:187,t:"tiles",d:.3,q:"Reconstitue le conseil pour les repas des enfants.",a:["Petite","assiette","grande","écoute"],dd:["régime","dessert","finis"],w:"On sert peu, on respecte les signaux, on laisse redemander."},
{i:"a187_10",u:187,t:"multi",d:.35,q:"Quelles erreurs de parents Laurence Plumey décrit-elle ?",o:["Donner du soda dans un biberon","Consoler avec un bonbon","Forcer à finir l'assiette","Faire dîner trop tard un enfant","Servir des légumes à chaque repas"],a:[0,1,2,3],w:"Quatre erreurs fréquentes et bien intentionnées. Servir des légumes est au contraire le bon réflexe."},
{i:"a187_11",u:187,t:"mcq",d:.35,q:"Quel pourcentage de graisse un nouveau-né a-t-il réellement à la naissance ?",o:["Environ 15 %","Environ 30 %","Environ 50 %","Environ 2 %"],a:0,w:"Environ 15 % (le podcast dit 30 %, c'est une erreur). Le pic d'environ 25 % arrive entre 4 et 9 mois, puis l'enfant s'affine."},
{i:"a187_12",u:187,t:"tf",d:.3,q:"Pendant la grossesse, un petit verre de champagne pour une fête est sans risque.",a:false,w:"Zéro alcool : le fœtus n'a pas les enzymes pour l'éliminer, l'alcool se répand dans ses cellules en développement. Même pas le petit verre."},
{i:"a187_13",u:187,t:"story",d:.4,q:"Un bébé est né à 2,5 kg après une grossesse où la mère mangeait très peu. Que conseilles-tu aux parents ?",sc:[{who:"Le père",txt:"C'est une petite crevette, on va bien le remplumer !"}],o:["« Suivez les repères du pédiatre sans le suralimenter : il stocke plus. »","« Oui, donnez-lui le plus possible, il doit rattraper son retard très vite. »","« Mettez-le au régime tout de suite pour éviter qu'il grossisse plus tard. »","« Son poids de naissance n'aura aucune conséquence sur sa santé future. »"],a:0,w:"Né petit avec des gènes du stockage allumés, il est plus sensible à l'abondance. On suit la croissance, sans suralimenter ni restreindre."},
{i:"a187_14",u:187,t:"fill",d:.4,q:"Un bébé qui pèse plus de 4 kg à la naissance est dit ___.",o:["macrosome","prématuré","hypotrophe","obèse"],a:0,w:"Macrosome. Souvent lié à une prise de poids excessive ou à un diabète de la mère ; il garde une facilité à prendre du poids."},
{i:"a187_15",u:187,t:"sort",d:.4,q:"Classe chaque geste : aide l'enfant à bien réguler, ou dérègle ?",bins:["Aide","Dérègle"],it:[["Laisser l'enfant se resservir s'il a faim",0],["Récompenser par des bonbons",1],["Respecter « j'ai plus faim »",0],["Donner du soda quand il a soif",1],["Dîner tôt pour dormir assez",0],["Forcer à finir un grand plat",1]],w:"Tout ce qui respecte ses signaux et son sommeil l'aide. Tout ce qui lie nourriture et émotion, ou ignore ses signaux, dérègle."},
{i:"a187_16",u:187,t:"mcq",d:.4,q:"Quel épisode historique a montré l'effet de la famine pendant la grossesse sur la santé des enfants devenus adultes ?",o:["L'hiver de famine aux Pays-Bas en 1944-1945","La Révolution française de 1789 à Paris","La crise économique de 1929 aux États-Unis","La grande peste noire au Moyen Âge"],a:0,w:"Les enfants nés de mères affamées ont eu plus d'obésité, de diabète et de maladies cardiovasculaires. C'est la base de la programmation fœtale."},
{i:"a187_17",u:187,t:"story",d:.45,q:"Le père de Léna dit qu'un enfant rond est un enfant en bonne santé. Que réponds-tu ?",sc:[{who:"M. Martin",txt:"Chez nous, un enfant bien rond, c'est un enfant bien portant."}],o:["« Vrai pour un nourrisson, mais à 8 ans, le surpoids est un risque pour sa santé. »","« Vous avez raison, le surpoids protège les enfants de toutes les maladies. »","« Un enfant rond est forcément malade, il faut l'hospitaliser très rapidement. »","« Le poids d'un enfant n'a vraiment aucune importance avant ses 18 ans. »"],a:0,w:"Les bourrelets du nourrisson sont normaux. À 8 ans, le surpoids s'installe (volume et nombre de cellules) et risque de durer. On réagit sans dramatiser ni culpabiliser. On suit la courbe de corpulence du carnet de santé plutôt que l'œil."},
{i:"a187_18",u:187,t:"slider",d:.45,q:"À quel âge, environ, un rebond de la courbe de corpulence est-il normal (en années) ?",min:1,max:12,step:1,a:6,tol:0,pre:"",un:" ans",w:"Vers 6 ans. Un rebond d'adiposité plus précoce (avant 6 ans) est un signal d'alerte à surveiller sur le carnet de santé."},
{i:"a187_19",u:187,t:"multi",d:.5,q:"Quelles règles donner pendant la grossesse ?",o:["Alimentation variée","Pas de régime","Pas d'excès","Zéro alcool","Manger pour deux"],a:[0,1,2,3],w:"« Manger pour deux » est une idée reçue : les besoins augmentent modérément, surtout en fin de grossesse. Une prise de poids excessive favorise la macrosomie."},
{i:"a187_20",u:187,t:"order",d:.5,q:"Remets dans l'ordre la chaîne de la programmation fœtale en cas de famine.",it:["La mère mange trop peu","Le bébé allume les gènes du stockage","Il naît avec un petit poids","Il grandit dans l'abondance","Il stocke plus que les autres"],w:"La survie dans le ventre prépare à la disette ; l'abondance ensuite piège ce corps « économe ». À l'inverse, un bébé macrosome (plus de 4 kg) garde lui aussi une facilité à stocker."},
{i:"a187_21",u:187,t:"story",d:.5,q:"Au restaurant, le menu enfant propose steak haché, frites, glace et soda. Que conseilles-tu aux Martin ?",sc:[{who:"Mme Martin",txt:"C'est toujours pareil, les menus enfants..."}],o:["« Demandez une petite part du plat adulte avec légumes, et de l'eau. »","« Prenez le menu enfant avec soda, il est fait exprès pour les enfants. »","« Ne l'emmenez plus jamais au restaurant, c'est bien trop risqué pour elle. »","« Donnez-lui double portion de frites pour qu'elle n'ait plus faim. »"],a:0,w:"Un enfant peut manger la même chose qu'un adulte, en plus petit. Laurence Plumey regrette que les restaurants proposent si peu d'autres menus enfants."},
{i:"a187_22",u:187,t:"tf",d:.55,q:"Le goût pour le sucré est inné chez le nourrisson.",a:true,w:"Une goutte d'eau sucrée le fait sourire. C'est pour ça qu'on ne doit pas l'entretenir avec des boissons sucrées : l'eau reste la boisson de l'enfant."},
{i:"a187_23",u:187,t:"fill",d:.55,q:"Les gènes qui s'allument ou s'éteignent selon l'environnement relèvent de l'___.",o:["épigénétique","anatomie","immunologie","endocrinologie"],a:0,w:"L'épigénétique : l'image des ampoules de Laurence Plumey. L'ADN ne change pas, mais son expression, oui."},
{i:"a187_24",u:187,t:"num",d:.55,q:"Un enfant de 10 ans pèse 100 kg au lieu d'environ 30 kg. Combien de fois le poids attendu ?",a:3.3,tol:.05,un:" fois",h:"100 / 30",w:"Environ 3,3 fois le poids attendu : le cas le plus lourd vu par Laurence Plumey à Necker. Sans prise en charge, il a de grandes chances de rester obèse adulte."},
{i:"a187_25",u:187,t:"story",d:.6,q:"Rappel du module 3 : pourquoi Léna est-elle fatiguée à l'école ?",sc:[{who:"Léna",txt:"On mange à 20 h 30 quand papa rentre, et je me couche à 21 h 30."}],o:["Elle dort trop peu : dîner tard, coucher tard, réveil à 7 h","Elle mange trop de légumes le soir, ce qui l'empêche de dormir","Elle ne boit pas assez de soda pour avoir de l'énergie","Elle se couche trop tôt pour son âge, elle devrait veiller"],a:0,w:"Dîner à 20 h 30, coucher à 21 h 30, lever à 7 h : 9 h 30 au lieu de 10 à 11 h. La solution : faire dîner Léna plus tôt, même si un parent arrive après."},
{i:"a187_26",u:187,t:"match",d:.6,q:"Associe chaque âge à son repère de sommeil.",p:[["Enfant de 8 ans","10 à 11 heures"],["Adulte","7 à 8 heures"],["Nourrisson","Bien plus, en plusieurs périodes"],["Adolescent","Naturellement décalé vers le soir"]],w:"Chaque âge a ses besoins. Chez l'enfant, le sommeil est aussi le moment où il grandit."},
{i:"a187_27",u:187,t:"tf",d:.6,q:"Pour aider un enfant en surpoids, il faut lui imposer un régime strict.",a:false,w:"Pas de régime chez l'enfant : on agit sur le sommeil, l'activité et l'équilibre alimentaire, avec toute la famille. Un régime ferait des dégâts sur la croissance et sur la relation à la nourriture."},
{i:"a187_28",u:187,t:"sort",d:.65,q:"Classe chaque affirmation : exacte ou erreur du podcast corrigée ?",bins:["Exacte","Erreur corrigée"],it:[["Les bourrelets du nourrisson sont normaux",0],["Un bébé naît avec 30 % de graisse",1],["La mère et le père transmettent chacun 50 % des gènes",0],["Le pic de graisse arrive entre 4 et 9 mois",0]],w:"Le fond est juste, le chiffre est corrigé : environ 15 % à la naissance, pic d'environ 25 % entre 4 et 9 mois."},
{i:"a187_29",u:187,t:"mcq",d:.65,q:"Pourquoi forcer un enfant à finir son assiette pose-t-il problème à l'âge adulte ?",o:["Il apprend à manger sans écouter sa satiété","Il deviendra forcément anorexique plus tard","Il détestera tous les légumes verts à vie","Il ne pourra plus digérer les féculents"],a:0,w:"Il passe en « mode manuel » : adulte, il mangera au stress, à l'émotion, au plaisir, même sans faim. C'est l'un des mécanismes du surpoids."},
{i:"a187_30",u:187,t:"story",d:.7,q:"Rappel du module 1 : que dis-tu aux Martin pour résumer ta prise en charge ?",sc:[{who:"Mme Martin",txt:"Alors, on fait quoi concrètement ?"}],o:["« Trois piliers : elle dort plus, bouge plus, mange équilibré, sans aucun régime. »","« On lui fait un régime à 1 000 calories, avec pesée chaque matin à la maison. »","« On attend l'adolescence, souvent ça se règle tout seul avec la croissance. »","« On supprime tout ce qui est sucré, y compris les fruits, jusqu'à nouvel ordre. »"],a:0,w:"Comme le dit Laurence Plumey : dès qu'un enfant s'arrondit, il faut qu'il dorme, qu'il bouge et qu'il mange de façon équilibrée. Pas de régime, mais réagir tout de suite. Selon Simmonds (2016), environ 55 % des enfants obèses le restent à l'adolescence."},
{i:"a187_31",u:187,t:"tiles",d:.75,q:"Reconstitue la règle des horaires pour un enfant qui se lève à 7 h.",a:["dîner","vers","19","h","au","lit","vers","20","h"],dd:["22","minuit","dessert"],w:"19-20 : dîner vers 19 h, lit vers 20 h. Et environ 2 heures de digestion entre les deux, idéalement un peu plus."},
{i:"a187_32",u:187,t:"fill",d:.75,q:"Le fœtus ne peut pas éliminer l'alcool car il n'a pas les ___ nécessaires.",o:["enzymes","dents","anticorps","globules"],a:0,w:"Sans enzymes, l'alcool se répand dans ses cellules en développement. D'où la règle : zéro alcool pendant toute la grossesse."}
