/*UNIT*/
{id:189,c:"NUTRI",n:"Module 7",t:"Sucre : les morceaux cachés et le foie gras humain",col:"--green",ic:"🍬",guide:`
<h3>Les morceaux sur la table</h3>
<div class="gstory">Nora a un rituel : sur son bureau de la Croix-Rousse, une boîte de sucres en morceaux. Quand Théo, 19 ans, lui dit qu'il boit « juste » un litre de cola par jour, elle aligne les morceaux un par un devant lui. Vingt et un. Théo se tait, puis rit jaune : « Je ne mettrais jamais vingt sucres dans mon café. » Son bilan sanguin montre des enzymes du foie (les transaminases) un peu élevées. À 19 ans.</div>
<h3>Lire le sucre en morceaux</h3>
<div class="formula">Grammes de sucre pour 100 ml × volume (en centaines de ml) ÷ 5 = morceaux de sucre</div>
<table><tr><th>Boisson</th><th>Sucre</th><th>En morceaux de 5 g</th></tr>
<tr><td>Cola, 1 litre</td><td>environ 106 g</td><td>environ 21 (Laurence Plumey dit « 20 »)</td></tr>
<tr><td>Cola, canette de 33 cl</td><td>environ 35 g</td><td>7</td></tr>
<tr><td>Cola, verre de 20 cl</td><td>environ 21 g</td><td>4</td></tr>
<tr><td>Jus d'orange, verre de 20 cl</td><td>environ 18 g</td><td>3 à 4</td></tr>
<tr><td>Yaourt aromatisé</td><td>environ 10 g de sucre ajouté</td><td>2</td></tr></table>
<h3>Les repères officiels</h3>
<p>L'OMS (2015) recommande de limiter les <b>sucres libres</b> (sucres ajoutés, plus miel, sirops et jus de fruits) à <b>moins de 10 % de l'énergie</b>, et idéalement <b>moins de 5 %</b>, soit environ <b>25 g par jour</b> pour un adulte : cinq morceaux. Une seule canette dépasse déjà cet idéal. Le sucre du <b>fruit entier</b> ne compte pas comme sucre libre : il est emballé dans des fibres et de l'eau.</p>
<div class="gmnemo"><b>« Divise par 5, compte les morceaux. »</b> Tous les grammes de sucre d'une étiquette deviennent des morceaux alignés sur la table. Et le plafond : <b>« 5 morceaux, 25 grammes »</b>.</div>
<h3>Du sucre au foie gras</h3>
<p>Le sucre en excès, surtout le <b>fructose</b> des boissons sucrées, est transformé en graisse <b>par le foie</b> (la lipogenèse). La graisse s'accumule dans le foie : c'est la <b>stéatose</b>, la maladie du « foie gras ». Laurence Plumey fait le parallèle avec le foie gras de canard, obtenu en gavant l'animal de maïs, donc d'amidon, donc de sucre. Son nom médical actuel : <b>MASLD</b> (maladie stéatosique du foie liée à une dysfonction métabolique), autrefois appelée NAFLD. Elle toucherait environ <b>un adulte sur trois</b> dans le monde.</p>
<table><tr><th>Étape</th><th>Ce qui se passe</th><th>Réversible ?</th></tr>
<tr><td>Stéatose</td><td>Graisse dans le foie</td><td>Oui, en quelques mois</td></tr>
<tr><td>Stéatohépatite (MASH)</td><td>Inflammation du foie</td><td>Souvent oui</td></tr>
<tr><td>Fibrose</td><td>Cicatrices dans le foie</td><td>En partie</td></tr>
<tr><td>Cirrhose</td><td>Foie durci qui fonctionne mal, risque de cancer</td><td>Non</td></tr></table>
<p>La bonne nouvelle : la stéatose régresse vite quand on supprime les boissons sucrées, qu'on bouge et qu'on perd un peu de poids (une perte de 7 à 10 % du poids améliore nettement le foie).</p>
<h3>Les pièges</h3>
<ul><li><b>Boissons énergisantes</b> : servies glacées, le froid masque le goût sucré (voir module 6).</li>
<li><b>Bières sans alcool aromatisées</b> : sans alcool ne veut pas dire sans sucre, certaines en contiennent autant qu'un soda.</li>
<li><b>Sucres cachés</b> : ketchup, sauces, céréales du petit-déjeuner, plats préparés, pain de mie.</li>
<li><b>Édulcorants</b> : pas de calories, mais l'OMS (2023) ne les conseille pas pour maigrir, et ils entretiennent le goût du sucré.</li></ul>
<div class="gtrap">Précision sur le podcast : le chiffre d'environ 4 morceaux « maximum par jour » donné pour le sucre est un ordre de grandeur. Le repère officiel est l'OMS : moins de 10 % de l'énergie en sucres libres, idéalement moins de 5 % (environ 25 g, 5 morceaux). Le sucre du fruit entier n'y est pas compté.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Transformer n'importe quelle étiquette en morceaux de sucre</li><li>Distinguer sucres libres et sucre du fruit entier</li><li>Expliquer à un patient comment le soda engraisse le foie, et que c'est réversible</li><li>Repérer les sucres cachés d'un chariot de courses</li></ul>`},
/*EXOS*/
{i:"a189_01",u:189,t:"num",d:.2,nw:"Divise par 5, compte les morceaux",q:"Un litre de cola contient 106 g de sucre. Combien de morceaux de 5 g (arrondi) ?",a:21,tol:1,un:" morceaux",h:"106 / 5",w:"Environ 21 morceaux. Laurence Plumey dit « 20 ». Divise par 5, compte les morceaux : l'image frappe plus que le chiffre."},
{i:"a189_02",u:189,t:"story",d:.2,q:"Théo découvre les 21 morceaux. Que lui dis-tu ensuite ?",sc:[{who:"Théo",txt:"OK, ça fait peur. Mais je fais quoi, j'arrête tout d'un coup ?"}],o:["« On divise d'abord par deux, et on remplace par de l'eau citronnée. »","« Oui, arrêt total dès ce soir, sinon ça ne sert à rien d'essayer quoi que ce soit. »","« Gardez le litre mais prenez du jus d'orange à la place, c'est bien plus sain. »","« Ne changez rien, à votre âge le sucre ne se stocke pas encore dans le foie. »"],a:0,w:"Un changement progressif et tenable vaut mieux qu'une rupture qui lâche en 3 jours. Le jus n'est pas une solution : c'est aussi du sucre libre."},
{i:"a189_03",u:189,t:"slider",d:.25,q:"Quelle quantité de sucres libres l'OMS juge-t-elle idéale par jour pour un adulte (en grammes) ?",min:0,max:100,step:5,a:25,tol:0,pre:"",un:" g",w:"Environ 25 g, soit moins de 5 % de l'énergie, 5 morceaux. Le plafond strict est de 10 % (environ 50 g)."},
{i:"a189_04",u:189,t:"fill",d:.25,q:"La maladie du foie chargé de graisse s'appelle la ___.",o:["stéatose","sclérose","scoliose","silicose"],a:0,w:"Stéatose, du grec « stéar », la graisse. Nom actuel : MASLD. Elle est réversible si on agit tôt."},
{i:"a189_05",u:189,t:"tf",d:.25,q:"Le sucre d'une pomme entière compte comme sucre libre selon l'OMS.",a:false,w:"Non : le sucre du fruit entier est emballé dans les fibres et l'eau. Le jus, lui, compte comme sucre libre. Le fructose du fruit entier arrive lentement, freiné par les fibres."},
{i:"a189_06",u:189,t:"order",d:.3,q:"Remets dans l'ordre l'évolution d'un foie qui reçoit trop de sucre pendant des années.",it:["Stéatose (graisse)","Stéatohépatite (inflammation)","Fibrose (cicatrices)","Cirrhose (foie durci)"],w:"On peut revenir en arrière aux premières étapes. La cirrhose, elle, ne se répare pas."},
{i:"a189_07",u:189,t:"multi",d:.3,q:"Lesquels de ces sucres sont des « sucres libres » ?",o:["Sucre ajouté dans un gâteau","Miel","Jus d'orange pressé","Sirop d'érable","Sucre d'une banane entière"],a:[0,1,2,3],w:"Sucres ajoutés, miel, sirops et jus sont libres. La banane entière, non : ses fibres ralentissent l'absorption."},
{i:"a189_08",u:189,t:"story",d:.3,q:"Paul s'étonne : « je ne bois pas d'alcool tous les jours et j'ai un foie gras ». Que lui expliques-tu ?",sc:[{who:"Paul",txt:"Le foie gras, c'est pas une maladie d'alcoolique ?"}],o:["« Le sucre en excès devient graisse dans le foie, comme chez le canard gavé. »","« Non, vous buvez forcément en cachette, le sucre n'a rien à voir avec votre foie. »","« C'est génétique, vous n'y pouvez rien, aucun changement ne le fera régresser. »","« C'est à cause de l'eau gazeuse, les bulles s'accumulent dans le foie avec l'âge. »"],a:0,w:"Le foie transforme le sucre en excès en graisse (lipogenèse). C'est la MASLD, qui touche environ un adulte sur trois, sans lien avec l'alcool."},
{i:"a189_09",u:189,t:"match",d:.35,q:"Associe chaque boisson à son nombre de morceaux de sucre.",p:[["Litre de cola","Environ 21"],["Canette de 33 cl","7"],["Verre de cola de 20 cl","4"],["Yaourt aromatisé","2"]],w:"Divise par 5 : 106 g, 35 g, 21 g, 10 g. Ces repères suffisent pour parler à n'importe quel patient."},
{i:"a189_10",u:189,t:"mcq",d:.35,q:"Quel sucre des boissons sucrées le foie transforme-t-il le plus facilement en graisse ?",o:["Le fructose","Le lactose","L'amidon","La cellulose"],a:0,w:"Le fructose est traité presque entièrement par le foie. En excès, il part en lipogenèse : graisse dans le foie."},
{i:"a189_11",u:189,t:"sort",d:.35,q:"Classe chaque aliment : sucre caché fréquent ou pas de sucre ajouté ?",bins:["Sucre caché","Pas de sucre ajouté"],it:[["Ketchup",0],["Pain de mie industriel",0],["Céréales du petit-déjeuner",0],["Œuf",1],["Lentilles nature",1],["Fromage blanc nature",1]],w:"Sauces, pain de mie, céréales cachent souvent du sucre. Les produits bruts, non : on lit la liste des ingrédients."},
{i:"a189_12",u:189,t:"story",d:.4,q:"Mehdi a remplacé le soda par de la bière sans alcool aromatisée. Que lui dis-tu ?",sc:[{who:"Mehdi",txt:"Sans alcool, c'est bon pour la ligne, non ?"}],o:["« Sans alcool ne veut pas dire sans sucre : les aromatisées en sont pleines. »","« Parfait, la bière sans alcool ne contient absolument aucune calorie, allez-y. »","« Mieux vaut revenir au soda, la bière sans alcool abîme bien plus le foie. »","« Prenez-la avec de la vraie bière pour équilibrer, ça revient au même au final. »"],a:0,w:"Les bières sans alcool aromatisées (agrumes, fruits rouges) contiennent souvent 4 à 6 g de sucre pour 100 ml. On lit l'étiquette : divise par 5."},
{i:"a189_13",u:189,t:"num",d:.4,q:"Une bière aromatisée sans alcool de 33 cl affiche 6 g de sucre pour 100 ml. Combien de morceaux (arrondi) ?",a:4,tol:.5,un:" morceaux",h:"6 × 3,3 / 5",w:"19,8 g, environ 4 morceaux. Presque la moitié d'une canette de cola, pour une boisson perçue comme « légère »."},
{i:"a189_14",u:189,t:"tiles",d:.4,q:"Reconstitue le plafond idéal de l'OMS.",a:["5","morceaux","25","grammes"],dd:["10","100","litres"],w:"Moins de 5 % de l'énergie en sucres libres, environ 25 g par jour. Moins de 10 % reste le maximum."},
{i:"a189_15",u:189,t:"tf",d:.45,q:"Une stéatose peut régresser en quelques mois.",a:true,w:"Oui : supprimer les boissons sucrées, bouger, perdre 7 à 10 % du poids améliore nettement le foie. C'est une bonne nouvelle à donner au patient."},
{i:"a189_16",u:189,t:"mcq",d:.45,q:"Quel est l'avis de l'OMS (2023) sur les édulcorants pour perdre du poids ?",o:["Elle les déconseille","Elle les recommande","Elle les rend obligatoires","Elle les interdit"],a:0,w:"Pas d'effet durable sur le poids, et ils entretiennent le goût du sucré. Mieux vaut réhabituer le palais."},
{i:"a189_17",u:189,t:"story",d:.45,q:"Chloé affirme que le miel « c'est naturel, donc pas du sucre ». Que réponds-tu ?",sc:[{who:"Chloé",txt:"Je mets trois cuillères de miel dans mon thé, c'est naturel."}],o:["« Le miel est un sucre libre : trois cuillères font déjà environ 3 morceaux. »","« Vous avez raison, le miel ne compte pas, il est entièrement naturel. »","« Le miel est pire que tout, il faut l'interdire totalement de votre cuisine. »","« Remplacez par du sirop d'agave, qui lui ne contient aucun sucre libre. »"],a:0,w:"Naturel ne veut pas dire sans sucre. Miel, sirop d'agave, sirop d'érable : tous des sucres libres. On compte, sans diaboliser."},
{i:"a189_18",u:189,t:"fill",d:.5,q:"La fabrication de graisse par le foie à partir du sucre s'appelle la ___.",o:["lipogenèse","glycolyse","digestion","néoglucogenèse"],a:0,w:"Lipogenèse (lipo = graisse, genèse = fabrication). C'est le lien entre soda et foie gras."},
{i:"a189_19",u:189,t:"slider",d:.5,q:"Quelle proportion des adultes dans le monde serait touchée par la MASLD (en %) ?",min:0,max:80,step:5,a:30,tol:5,pre:"",un:" %",w:"Environ 30 %, un adulte sur trois. C'est la maladie du foie la plus fréquente, devant l'alcool et les hépatites."},
{i:"a189_20",u:189,t:"match",d:.5,q:"Associe chaque piège à son explication.",p:[["Boisson énergisante glacée","Le froid masque le sucre"],["Bière sans alcool aromatisée","Sans alcool mais sucrée"],["Jus 100 % pur fruit","Sucre libre sans les fibres"],["Soda light","Entretient le goût du sucré"]],w:"Chaque boisson a son alibi. On revient toujours à l'étiquette et à l'eau."},
{i:"a189_21",u:189,t:"story",d:.55,q:"Théo revient 3 mois plus tard : un demi-litre de cola en moins par jour. Ses transaminases ont baissé. Que lui dis-tu ?",sc:[{who:"Théo",txt:"Franchement, je pensais pas que ça changerait si vite."}],o:["« Votre foie se répare quand on arrête de le noyer : continuons sur la suite. »","« C'est un hasard, le foie ne change jamais aussi vite, recommencez les analyses. »","« Parfait, maintenant vous pouvez reprendre le litre complet sans aucun risque. »","« Il faut maintenant arrêter aussi tous les fruits, ils contiennent du fructose. »"],a:0,w:"Valoriser le progrès, expliquer la réversibilité, fixer l'étape suivante. Le fruit entier n'est pas un problème : ses fibres freinent le fructose."},
{i:"a189_22",u:189,t:"mcq",d:.55,q:"Avec quoi gave-t-on un canard pour obtenir un foie gras ?",o:["Du maïs, riche en amidon","De la viande hachée","Des huiles végétales","Du poisson séché"],a:0,w:"Du maïs, donc de l'amidon, donc du sucre. Chez l'humain, les boissons sucrées font la même chose au foie."},
{i:"a189_23",u:189,t:"multi",d:.55,q:"Qu'est-ce qui fait régresser une stéatose ?",o:["Supprimer les boissons sucrées","Bouger tous les jours","Perdre 7 à 10 % de son poids","Limiter l'alcool","Remplacer le soda par du jus"],a:[0,1,2,3],w:"Le jus reste un sucre libre. Tout le reste soulage directement le foie."},
{i:"a189_24",u:189,t:"sort",d:.6,q:"Classe : réversible ou non réversible ?",bins:["Réversible","Non réversible"],it:[["Stéatose",0],["Stéatohépatite prise tôt",0],["Cirrhose",1],["Transaminases un peu hautes chez Théo",0]],w:"Tant qu'on n'est pas au stade de cirrhose, on peut beaucoup récupérer. D'où l'intérêt d'agir tôt."},
{i:"a189_25",u:189,t:"story",d:.6,q:"Rappel du module 5 : Mme Martin donne un yaourt aromatisé et un jus à Léna au goûter. Que proposes-tu ?",sc:[{who:"Mme Martin",txt:"Elle adore ça, et c'est des laitages et des fruits, donc c'est sain."}],o:["« Yaourt nature et fruit entier coupé : même plaisir, bien moins de sucre. »","« Parfait, c'est le goûter idéal pour un enfant, ne changez surtout rien. »","« Supprimez le goûter, un enfant de 8 ans n'en a absolument pas besoin. »","« Donnez-lui un soda light à la place du jus, ça règle le problème. »"],a:0,w:"Yaourt aromatisé (2 morceaux) + jus (3 à 4) = environ 6 morceaux, plus que le plafond idéal adulte. Le nature + fruit garde le plaisir."},
{i:"a189_26",u:189,t:"tf",d:.6,q:"Un jus d'orange pressé maison n'est pas un sucre libre, puisqu'il n'y a rien d'ajouté.",a:false,w:"Si : pour l'OMS, tous les jus de fruits comptent comme sucres libres. Presser libère le sucre de ses fibres."},
{i:"a189_27",u:189,t:"num",d:.65,q:"Pour un adulte à 2 000 kcal, combien de grammes de sucres libres représente la limite de 10 % (1 g de sucre = 4 kcal) ?",a:50,tol:0,un:" g",h:"2 000 × 10 % / 4",w:"200 kcal / 4 = 50 g, 10 morceaux. L'idéal de 5 % donne 25 g. Rappel du module 2 : 4 kcal par gramme de glucides."},
{i:"a189_28",u:189,t:"fill",d:.65,q:"Le nom médical actuel de la maladie du « foie gras » métabolique est la ___.",o:["MASLD","BPCO","SEP","HNPCC"],a:0,w:"MASLD, anciennement NAFLD. Stade inflammatoire : MASH. Retenir surtout le mécanisme : sucre en excès, graisse dans le foie."},
{i:"a189_29",u:189,t:"story",d:.7,q:"Rappel du module 3 : Mehdi grignote des bonbons pendant ses nuits. Que relies-tu ?",sc:[{who:"Mehdi",txt:"La nuit, j'ai envie de sucre, c'est plus fort que moi."}],o:["« Le manque de sommeil pousse au sucre : collation salée prévue et sieste. »","« C'est de la gourmandise pure, il suffit d'un peu plus de volonté la nuit. »","« Les bonbons aident à rester éveillé, c'est même recommandé pour les veilleurs. »","« Buvez une boisson énergisante à la place, elle contient beaucoup moins de sucre. »"],a:0,w:"Fatigue = cerveau qui réclame de l'énergie rapide (module 3, les 3 S). Collation prévue, eau, sieste courte : on agit sur la cause. Le travail de nuit décale la faim vers les heures où l'offre est la plus sucrée."},
{i:"a189_30",u:189,t:"mcq",d:.7,q:"Quel plafond de sucres libres l'OMS fixe-t-elle au maximum ?",o:["10 % de l'énergie","1 % de l'énergie","25 % de l'énergie","50 % de l'énergie"],a:0,w:"Moins de 10 %, idéalement moins de 5 %. En pratique : 5 à 10 morceaux par jour selon l'objectif."},
{i:"a189_31",u:189,t:"tiles",d:.75,q:"Reconstitue la chaîne sucre, foie.",a:["sucre","en","excès","graisse","dans","le","foie"],dd:["muscles","eau","cerveau"],w:"La lipogenèse : c'est ce qui relie le litre de cola aux transaminases de Théo. C'est surtout le fructose des boissons sucrées qui part en lipogenèse."},
{i:"a189_32",u:189,t:"story",d:.8,q:"Synthèse : un patient te demande la règle la plus simple pour le sucre. Laquelle ?",sc:[{who:"Patient",txt:"Donnez-moi un truc que je peux faire au supermarché."}],o:["« Divisez par 5 les grammes de sucre, restez sous 5 morceaux par jour. »","« Achetez tout ce qui est marqué « naturel », c'est forcément pauvre en sucre. »","« Prenez tout en version light, les édulcorants règlent le problème du sucre. »","« Évitez tous les fruits, c'est la principale source de sucre dans l'alimentation. »"],a:0,w:"Divise par 5, compte les morceaux ; 5 morceaux, 25 grammes. Le fruit entier reste un allié."}
