/*UNIT*/
{id:190,c:"NUTRI",n:"Module 8",t:"Alcool : le cardiologue, le cancérologue et le verre de trop",col:"--green",ic:"🍷",guide:`
<h3>Le dîner de Paul</h3>
<div class="gstory">Paul raconte à Nora son dîner du samedi chez son beau-frère, cardiologue à Lyon Sud. « Il m'a dit qu'un verre de rouge par jour protège le cœur. Et ma belle-sœur, oncologue, lui a répondu que l'alcool donne le cancer. Ils se sont disputés jusqu'au fromage. Alors, qui a raison ? » Nora sort une feuille : « Les deux ont vu quelque chose de vrai. Mais aujourd'hui, c'est la cancérologue qui a les meilleures preuves. »</div>
<h3>Le débat du podcast</h3>
<table><tr><th>Le cardiologue</th><th>Le cancérologue</th></tr>
<tr><td>Des études anciennes montrent une courbe en U, ou courbe en J, : les petits buveurs auraient moins d'infarctus que les abstinents.</td><td>L'alcool est classé <b>cancérogène certain</b> (groupe 1) par le CIRC, l'agence de l'OMS sur le cancer, depuis 1988.</td></tr>
<tr><td>On invoque les <b>polyphénols</b> du vin rouge (comme le resvératrol).</td><td>Le risque augmente <b>dès le premier verre</b> : il n'existe pas de dose sans risque pour le cancer.</td></tr></table>
<p>Pourquoi le cardiologue a moins raison qu'on le pensait : dans ces études, le groupe des « abstinents » comptait beaucoup d'anciens buveurs malades qui avaient arrêté, ce qui les faisait paraître en moins bonne santé. Les analyses récentes qui corrigent ce biais ne retrouvent plus de protection nette. Et les polyphénols du vin sont en quantité bien trop faible : on en trouve beaucoup plus dans les fruits rouges, le raisin, le thé ou le cacao, sans alcool.</p>
<div class="gtrap">Précision sur le podcast : la liste de cancers liés à l'alcool établie par le CIRC comprend la <b>bouche, le pharynx, le larynx, l'œsophage, le foie, le côlon-rectum et le sein</b>. L'estomac et le pancréas sont cités dans le podcast : les preuves y sont plus limitées (probables ou possibles). L'essentiel reste vrai : l'alcool est responsable d'environ <b>8 % des cancers</b> en France (INCa, données 2015), et d'environ <b>41 000 morts par an</b> (Santé publique France).</div>
<h3>Les repères français (Santé publique France et INCa, 2017)</h3>
<div class="gmnemo"><b>« 2, 10, pas tous les jours »</b> : au maximum <b>2 verres par jour</b>, au maximum <b>10 verres par semaine</b>, et <b>des jours sans alcool</b> chaque semaine. Laurence Plumey dit plus simplement : « un ou deux verres, et pas tous les jours ». Pendant la grossesse : <b>zéro</b>.</div>
<h3>Le verre standard</h3>
<p>En France, un <b>verre standard</b> contient <b>10 g d'alcool pur</b>, quelle que soit la boisson, à condition de respecter la dose servie au bar :</p>
<table><tr><th>Boisson</th><th>Dose servie</th><th>Degré</th><th>Alcool pur</th></tr>
<tr><td>Vin</td><td>10 cl</td><td>12,5 %</td><td>10 g</td></tr>
<tr><td>Bière</td><td>25 cl</td><td>5 %</td><td>10 g</td></tr>
<tr><td>Pastis, whisky</td><td>3 cl</td><td>40 à 45 %</td><td>10 g</td></tr>
<tr><td>Champagne</td><td>10 cl</td><td>12 %</td><td>10 g</td></tr></table>
<div class="formula">Grammes d'alcool = volume (ml) × degré (%) ÷ 100 × 0,8</div>
<p>L'alcool apporte <b>7 kcal par gramme</b> (module 2) : un verre standard, c'est déjà 70 kcal, sans compter le sucre de la boisson. Une bouteille de vin, c'est environ 7 verres standard et 500 à 600 kcal. Et l'alcool passe <b>en priorité</b> : tant que le foie l'élimine, les graisses du repas sont stockées. C'est la bière avec les chips de Paul.</p>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Arbitrer le débat cardiologue contre cancérologue avec les preuves actuelles</li><li>Calculer les grammes d'alcool d'une boisson et ses calories</li><li>Donner les repères « 2, 10, pas tous les jours » et le zéro de la grossesse</li><li>Accompagner un patient qui veut réduire, sans le juger</li></ul>`},
/*EXOS*/
{i:"a190_01",u:190,t:"story",d:.2,nw:"Cardiologue contre cancérologue",q:"Qui a raison au dîner de Paul ?",sc:[{who:"Paul",txt:"Mon beau-frère cardiologue dit qu'un verre protège, ma belle-sœur oncologue dit que ça donne le cancer."}],o:["« Les preuves récentes donnent raison à l'oncologue : pas de dose sûre. »","« Le cardiologue a raison, un verre de rouge par jour est même conseillé. »","« Aucun des deux, l'alcool n'a aucun effet mesurable sur la santé humaine. »","« Les deux ont tort, seul le vin blanc protège le cœur, jamais le rouge. »"],a:0,w:"L'ancienne courbe en J venait d'un biais (anciens buveurs malades chez les abstinents). Le CIRC classe l'alcool cancérogène certain : le risque commence au premier verre."},
{i:"a190_02",u:190,t:"slider",d:.2,q:"Combien de grammes d'alcool pur contient un verre standard en France ?",min:0,max:30,step:1,a:10,tol:0,pre:"",un:" g",w:"10 g, que ce soit 10 cl de vin, 25 cl de bière ou 3 cl de whisky, à la dose servie au bar."},
{i:"a190_03",u:190,t:"tiles",d:.25,q:"Reconstitue le repère officiel sur l'alcool.",a:["2","verres","par","jour","10","par","semaine","pas","tous","les","jours"],dd:["5","chaque","soir"],w:"« 2, 10, pas tous les jours » : Santé publique France et INCa, 2017. Et zéro pendant la grossesse."},
{i:"a190_04",u:190,t:"num",d:.25,q:"Un verre standard contient 10 g d'alcool. Combien de kcal apporte cet alcool (7 kcal par gramme) ?",a:70,tol:0,un:" kcal",h:"10 × 7",w:"70 kcal, rien que pour l'alcool, avant le sucre de la boisson. Rappel du module 2 : 4, 4, 9, 7."},
{i:"a190_05",u:190,t:"match",d:.3,q:"Associe chaque boisson à la dose qui fait un verre standard.",p:[["Vin à 12,5 %","10 cl"],["Bière à 5 %","25 cl"],["Whisky à 40 %","3 cl"],["Champagne à 12 %","10 cl"]],w:"Même quantité d'alcool pur dans chaque verre du bar. À la maison, les verres sont souvent plus remplis : on compte large."},
{i:"a190_06",u:190,t:"tf",d:.3,q:"L'alcool est classé cancérogène certain (groupe 1) par le CIRC.",a:true,w:"Depuis 1988. Comme le tabac ou l'amiante, ce qui ne veut pas dire « aussi dangereux », mais « cancérogène de façon certaine »."},
{i:"a190_07",u:190,t:"multi",d:.3,q:"Quels cancers le CIRC relie-t-il de façon certaine à l'alcool ?",o:["Bouche et pharynx","Œsophage","Foie","Sein","Peau (mélanome)"],a:[0,1,2,3],w:"Bouche, pharynx, larynx, œsophage, foie, côlon-rectum, sein. Le mélanome est surtout lié aux UV. Estomac et pancréas : preuves plus limitées."},
{i:"a190_08",u:190,t:"story",d:.35,q:"Paul boit « juste deux bières » chaque soir devant le match. Que calcules-tu avec lui ?",sc:[{who:"Paul",txt:"Deux demis, c'est rien, non ?"}],o:["« 2 verres par jour, 14 par semaine : au-dessus des 10, sans pause. »","« C'est très peu, vous êtes largement sous tous les repères officiels. »","« C'est trop, un adulte ne devrait jamais dépasser un verre par mois. »","« Aucun problème tant que ce n'est pas du vin, la bière ne compte pas. »"],a:0,w:"2 × 7 = 14 verres par semaine, au-delà du plafond de 10, et aucun jour sans. On vise « pas tous les jours » : 3 ou 4 soirs sans."},
{i:"a190_09",u:190,t:"fill",d:.35,q:"Les molécules du vin rouge censées protéger le cœur sont les ___.",o:["polyphénols","protéines","acides gras","sulfites"],a:0,w:"Polyphénols (dont le resvératrol). En quantité trop faible dans le vin : fruits rouges, thé, cacao en apportent plus, sans alcool."},
{i:"a190_10",u:190,t:"num",d:.4,q:"Combien de grammes d'alcool dans une pinte de 50 cl de bière à 6 % ?",a:24,tol:.5,un:" g",h:"500 × 6 / 100 × 0,8",w:"24 g, soit près de 2,5 verres standard dans un seul verre. La pinte trompe : on compte en grammes."},
{i:"a190_11",u:190,t:"mcq",d:.4,q:"Pourquoi les anciennes études voyaient-elles un effet protecteur des petites doses ?",o:["Les abstinents comptaient d'anciens buveurs malades","L'alcool fluidifiait vraiment le sang de chacun","Les buveurs faisaient tous beaucoup plus de sport","Les études étaient toutes financées par l'État"],a:0,w:"Le biais de « l'ancien buveur » : des malades qui avaient arrêté faisaient paraître les abstinents en moins bonne santé. Corrigé, l'effet disparaît presque."},
{i:"a190_12",u:190,t:"sort",d:.4,q:"Classe chaque argument : du camp « cardiologue » ou du camp « cancérologue » ?",bins:["Cardiologue","Cancérologue"],it:[["Courbe en U ou en J",0],["Polyphénols du vin rouge",0],["Cancérogène certain du CIRC",1],["Risque dès le premier verre",1],["Paradoxe français",0],["8 % des cancers en France",1]],w:"Les arguments cardiologues reposent sur des études biaisées ou des molécules en faible dose ; ceux des cancérologues sont solides."},
{i:"a190_13",u:190,t:"story",d:.45,q:"Inès, enceinte, demande si un verre de vin à Noël est acceptable. Que réponds-tu ?",sc:[{who:"Inès",txt:"Juste une gorgée pour trinquer, c'est bon ?"}],o:["« Zéro alcool pendant la grossesse : on trinque avec un jus pétillant. »","« Une gorgée à Noël, c'est même conseillé pour la détente du bébé. »","« Un verre par jour est acceptable à partir du sixième mois de grossesse. »","« Seul le vin rouge est interdit, le champagne ne pose aucun souci. »"],a:0,w:"Le fœtus n'a pas les enzymes pour éliminer l'alcool (module 5). Aucune dose n'est sûre : zéro, sans culpabiliser si c'est arrivé avant de savoir."},
{i:"a190_14",u:190,t:"slider",d:.45,q:"Quelle part des cancers en France est attribuable à l'alcool (en %) ?",min:0,max:30,step:1,a:8,tol:1,pre:"",un:" %",w:"Environ 8 % (INCa, données 2015), deuxième cause évitable de cancer après le tabac."},
{i:"a190_15",u:190,t:"order",d:.45,q:"Remets dans l'ordre le calcul des grammes d'alcool d'une boisson.",it:["Prendre le volume en ml","Multiplier par le degré","Diviser par 100","Multiplier par 0,8 (densité de l'alcool)"],w:"Volume × degré ÷ 100 × 0,8. Exemple : 100 ml × 12,5 ÷ 100 × 0,8 = 10 g."},
{i:"a190_16",u:190,t:"tf",d:.5,q:"Tant que le foie élimine l'alcool, les graisses du repas ont tendance à être stockées.",a:true,w:"L'alcool est traité en priorité : c'est un toxique. Bière et chips, ou apéritif et charcuterie, font un duo qui s'installe sur le ventre."},
{i:"a190_17",u:190,t:"story",d:.5,q:"Paul veut réduire mais « ne veut pas être le seul à table sans verre ». Que proposes-tu ?",sc:[{who:"Paul",txt:"Chez mes amis, refuser un verre, c'est mal vu."}],o:["« Un verre en début de soirée, puis de l'eau pétillante : vous restez là. »","« Arrêtez de voir vos amis quelque temps, c'est la seule façon de réussir. »","« Buvez comme eux le week-end, et rattrapez en ne mangeant rien le lundi. »","« Dites que vous êtes malade, personne ne posera de question sur l'alcool. »"],a:0,w:"On garde le lien social, on réduit la dose. Pas de compensation par le jeûne (ça dérègle), pas de mensonge qui s'use."},
{i:"a190_18",u:190,t:"mcq",d:.5,q:"Combien de morts par an l'alcool cause-t-il en France selon Santé publique France ?",o:["Environ 41 000","Environ 400","Environ 4 000","Environ 400 000"],a:0,w:"Environ 41 000 décès par an (données 2015) : cancers, maladies du foie, accidents, maladies cardiovasculaires."},
{i:"a190_19",u:190,t:"fill",d:.55,q:"Le CIRC est l'agence de l'___ chargée de classer les cancérogènes.",o:["OMS","ONU","UE","ANSES"],a:0,w:"Centre international de recherche sur le cancer, à Lyon, rattaché à l'OMS. Ses classements font référence."},
{i:"a190_20",u:190,t:"num",d:.55,q:"Une bouteille de vin (75 cl) contient environ 7 verres standard. Combien de kcal viennent de l'alcool seul ?",a:490,tol:10,un:" kcal",h:"7 × 10 g × 7 kcal",w:"490 kcal, l'équivalent d'un repas. Avec le sucre résiduel, 500 à 600 kcal. Partagée à deux, c'est 250 kcal chacun."},
{i:"a190_21",u:190,t:"match",d:.55,q:"Associe chaque notion à sa définition.",p:[["Verre standard","10 g d'alcool pur"],["Groupe 1 du CIRC","Cancérogène certain"],["Courbe en J","Protection apparente des petits buveurs"],["Resvératrol","Polyphénol du vin rouge"]],w:"Ces quatre notions suffisent pour tenir la discussion avec un patient ou un proche cardiologue."},
{i:"a190_22",u:190,t:"story",d:.6,q:"Mme Garcia boit un verre de vin rouge chaque midi « pour le cœur ». Que lui dis-tu ?",sc:[{who:"Mme Garcia",txt:"Mon médecin de l'époque me l'avait conseillé."}],o:["« On sait que ça ne protège pas : gardez-le pour le plaisir, pas chaque jour. »","« Continuez, c'est le meilleur médicament du cœur, doublez même la dose. »","« Arrêtez tout de suite ou vous aurez un cancer dans l'année, c'est certain. »","« Remplacez-le par du whisky, qui contient bien plus de polyphénols utiles. »"],a:0,w:"Actualiser sans faire peur. Le plaisir est légitime ; l'argument santé ne l'est plus. On propose des jours sans, et les fruits rouges pour les polyphénols."},
{i:"a190_23",u:190,t:"tf",d:.6,q:"Pour le cancer, il existe une dose d'alcool en dessous de laquelle le risque est nul.",a:false,w:"Non : le risque augmente dès les faibles consommations, surtout pour le cancer du sein. Les repères limitent le risque, ils ne l'annulent pas."},
{i:"a190_24",u:190,t:"multi",d:.6,q:"Quelles sources de polyphénols recommander à la place du vin ?",o:["Fruits rouges","Raisin","Thé","Cacao","Soda au cola"],a:[0,1,2,3],w:"Fruits rouges, raisin, thé, cacao, chocolat noir : des polyphénols sans alcool. Le soda n'en apporte pas."},
{i:"a190_25",u:190,t:"story",d:.65,q:"Rappel du module 7 : Paul demande si la bière sans alcool est une bonne alternative. Que dis-tu ?",sc:[{who:"Paul",txt:"Je passe à la sans alcool, c'est réglé ?"}],o:["« Bonne idée si elle est nature : les aromatisées, elles, sont souvent sucrées. »","« Elle contient autant d'alcool que la normale, cela ne change absolument rien. »","« Non, la bière sans alcool abîme bien plus le foie que la bière classique. »","« Oui, et vous pouvez en boire trois litres par jour sans aucun souci. »"],a:0,w:"La sans alcool nature (moins de 0,5 %) retire l'essentiel du risque. Les aromatisées ajoutent du sucre : on lit l'étiquette, divise par 5."},
{i:"a190_26",u:190,t:"mcq",d:.65,q:"Laurence Plumey résume sa position ainsi :",o:["Un ou deux verres, et pas tous les jours","Un verre de rouge chaque jour du mois","Zéro alcool pour tout le monde, toujours","Autant qu'on veut le samedi et dimanche"],a:0,w:"Une position proche des repères officiels « 2, 10, pas tous les jours ». Zéro pendant la grossesse."},
{i:"a190_27",u:190,t:"sort",d:.7,q:"Classe chaque consommation hebdomadaire : dans les repères ou au-dessus ?",bins:["Dans les repères","Au-dessus"],it:[["Un verre 4 soirs par semaine",0],["Deux verres tous les soirs",1],["Trois verres le samedi, rien sinon",1],["Deux verres le vendredi et le samedi",0]],w:"Au plus 2 par jour, au plus 10 par semaine, des jours sans. Trois verres le même soir dépassent le plafond quotidien."},
{i:"a190_28",u:190,t:"fill",d:.7,q:"Un gramme d'alcool apporte ___ kcal.",o:["7","4","9","0"],a:0,w:"7 kcal par gramme : 4 pour glucides et protéines, 9 pour les lipides, 7 pour l'alcool (module 2, « Glu-Pro, gras, gorgée »)."},
{i:"a190_29",u:190,t:"story",d:.75,q:"Un patient dit : « de toute façon, on meurt tous de quelque chose ». Comment réagis-tu ?",sc:[{who:"Patient",txt:"Je ne vais pas arrêter de vivre pour quelques pourcents de risque."}],o:["« Vous décidez. Mon rôle : que vous choisissiez en connaissant les chiffres. »","« Vous avez tort et vous le regretterez, je refuse de vous suivre ici. »","« Vous avez raison, l'alcool n'a de toute façon aucun effet réel sur vous. »","« Dans ce cas, inutile de revenir en consultation, c'est votre problème. »"],a:0,w:"Respecter l'autonomie, informer sans moraliser, garder la relation. C'est ce qui permet au patient de revenir le jour où il sera prêt."},
{i:"a190_30",u:190,t:"num",d:.75,q:"Paul boit 14 verres par semaine et passe à 8. Combien de kcal d'alcool économise-t-il par semaine (70 kcal par verre) ?",a:420,tol:0,un:" kcal",h:"(14 − 8) × 70",w:"420 kcal par semaine, plus de 20 000 par an, l'équivalent de près de 3 kg de graisse (7 700 kcal par kg)."},
{i:"a190_31",u:190,t:"tiles",d:.8,q:"Reconstitue la raison du biais des anciennes études.",a:["les","abstinents","comptaient","d'anciens","buveurs","malades"],dd:["sportifs","jeunes","riches"],w:"Le biais de l'ancien buveur a fait croire à la courbe en J. Corrigé, la protection disparaît presque."},
{i:"a190_32",u:190,t:"story",d:.8,q:"Synthèse : que retiens-tu pour Paul en une phrase ?",sc:[{who:"Paul",txt:"Alors, je fais quoi avec l'alcool ?"}],o:["« Au plus 2 verres, 10 par semaine, des soirs sans, pas d'alibi santé. »","« Rien, le verre de rouge quotidien protège votre cœur, gardez-le. »","« Arrêt total immédiat, sans exception, pour le reste de votre vie. »","« Uniquement de la bière, qui ne compte pas dans les repères officiels. »"],a:0,w:"« 2, 10, pas tous les jours ». Réduire, pas forcément arrêter : c'est ce qui tient, et chaque verre en moins compte."}
