/*UNIT*/
{id:191,c:"NUTRI",n:"Module 9",t:"Le bon gras : oméga-3, huile d'olive et poêle en inox",col:"--green",ic:"🫒",guide:`
<h3>Le gras n'est pas l'ennemi</h3>
<div class="gstory">Chloé arrive chez Nora avec une liste : « J'ai supprimé tout le gras. Plus d'huile, plus de beurre, plus de fromage, que du 0 %. » Elle a faim tout le temps, la peau sèche, et elle n'a perdu que 800 g en un mois. Nora pose sur la table le livre de Laurence Plumey, <i>Le monde merveilleux du gras</i> : « Votre corps a besoin de gras. La question n'est pas combien, mais lequel. »</div>
<h3>Le gras du corps est un organe</h3>
<p>Le tissu adipeux représente environ <b>20 % du poids du corps</b> chez une personne de corpulence normale, soit <b>10 à 15 kg</b>. C'est un vrai organe : il stocke l'énergie, isole du froid, protège les organes et fabrique des hormones, comme la <b>leptine</b> qui informe le cerveau du niveau des réserves et participe à la satiété. Le problème n'est pas le gras, c'est son <b>excès</b>, surtout autour des organes du ventre (le gras <b>viscéral</b>, qu'on mesure avec le tour de taille, module 1).</p>
<h3>Les familles de gras dans l'assiette</h3>
<table><tr><th>Famille</th><th>Où la trouver</th><th>Effet</th></tr>
<tr><td>Acides gras <b>saturés</b></td><td>Beurre, crème, fromage, gras du jambon, charcuterie, viande grasse, huile de palme</td><td>En excès, augmentent le mauvais cholestérol (LDL). On en mange déjà trop.</td></tr>
<tr><td><b>Oméga-9</b> (mono-insaturés)</td><td>Huile d'olive, avocat, amandes</td><td>Protègent le cœur. Base du régime méditerranéen.</td></tr>
<tr><td><b>Oméga-3</b> (poly-insaturés)</td><td>Sardine, maquereau, saumon, hareng, huiles de colza et de noix, noix</td><td>Protègent le cœur et le cerveau. On en manque souvent.</td></tr>
<tr><td><b>Oméga-6</b> (poly-insaturés)</td><td>Huile de tournesol, de maïs, produits industriels</td><td>Utiles mais en excès en France par rapport aux oméga-3.</td></tr>
<tr><td>Acides gras <b>trans</b> industriels</td><td>Huiles partiellement hydrogénées (viennoiseries et biscuits industriels anciens)</td><td>Les plus nocifs pour le cœur, à éviter.</td></tr></table>
<div class="gmnemo"><b>« Poisson gras deux fois, olive pour cuire, colza pour assaisonner. »</b> Et pour retenir les trois poissons gras les moins chers : <b>« S.M.S. : Sardine, Maquereau, Saumon »</b>. Le Programme national nutrition santé conseille du poisson deux fois par semaine, dont un poisson gras.</div>
<h3>Le Nord et le Sud</h3>
<p>Laurence Plumey rappelle que le <b>régime méditerranéen</b>, cuisiné à l'huile d'olive, est l'un des meilleurs pour la santé, et qu'en France, le Nord (beurre, crème) a historiquement plus de maladies cardiovasculaires que le Sud (huile d'olive). Le beurre n'est pas interdit : sur la tartine du matin, en petite quantité, c'est très bien.</p>
<h3>Cuire sans brûler</h3>
<ul><li>Le beurre seul <b>noircit</b> vite à la chaleur : il devient irritant pour l'estomac. L'astuce de Laurence Plumey : <b>un peu d'huile d'abord, puis un peu de beurre</b>. Le beurre ne brûle plus et donne son goût de noisette.</li>
<li>La <b>poêle en inox</b> : on la chauffe fort, on met l'huile, on dépose l'aliment, on attend qu'il saisisse et se décolle tout seul, puis on baisse le feu. Elle dure des décennies.</li></ul>
<div class="gtrap">Nuance sur le podcast : l'animateur affirme que le Téflon des poêles est « très cancérigène ». C'est exagéré. Le revêtement lui-même (PTFE) est très stable, et une particule avalée traverse le tube digestif sans être absorbée. Le vrai problème vient de deux choses. D'abord, les <b>PFAS</b>, ces « polluants éternels » de la même famille. L'un d'eux, le <b>PFOA</b>, utilisé autrefois pour fabriquer le Téflon, est classé <b>cancérogène certain</b> par le CIRC depuis 2023 et interdit en Europe depuis 2020. Ensuite, la <b>surchauffe</b> d'une poêle vide (au-delà d'environ 260 °C) libère des fumées toxiques. Le bon conseil : jeter une poêle rayée, ne jamais la chauffer à vide, et savoir que l'inox ou la fonte sont de bonnes alternatives.</div>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Expliquer pourquoi supprimer tout le gras est une erreur</li><li>Classer un aliment dans sa famille de gras</li><li>Construire une semaine avec deux poissons dont un gras et les bonnes huiles</li><li>Conseiller une cuisson saine et démêler le vrai du faux sur le Téflon</li></ul>`},
/*EXOS*/
{i:"a191_01",u:191,t:"story",d:.2,nw:"Le gras est un organe utile",q:"Que réponds-tu à Chloé qui a supprimé tout le gras ?",sc:[{who:"Chloé",txt:"Zéro gras, c'est bien la meilleure façon de maigrir, non ?"}],o:["« Votre corps a besoin de gras : on garde les bons, en quantité dosée. »","« Oui, et supprimez aussi les féculents pour aller encore plus vite. »","« Continuez, un mois de plus et votre faim finira par disparaître. »","« Le gras ne compte pas, seules les calories des sucres font grossir. »"],a:0,w:"Supprimer tout le gras donne faim, abîme la peau et prive d'oméga-3. La question n'est pas combien, mais lequel."},
{i:"a191_02",u:191,t:"slider",d:.2,q:"Quelle part du poids du corps représente le gras chez une personne de corpulence normale (en %) ?",min:0,max:60,step:5,a:20,tol:5,pre:"",un:" %",w:"Environ 20 %, soit 10 à 15 kg selon Laurence Plumey. Un peu moins chez l'homme, un peu plus chez la femme."},
{i:"a191_03",u:191,t:"sort",d:.25,q:"Classe chaque aliment selon son gras dominant.",bins:["Saturé","Oméga-3","Oméga-9"],it:[["Beurre",0],["Sardine",1],["Huile d'olive",2],["Gras du jambon",0],["Huile de colza",1],["Avocat",2]],w:"Saturés : beurre, crème, charcuterie. Oméga-3 : poissons gras, colza, noix. Oméga-9 : olive, avocat, amandes."},
{i:"a191_04",u:191,t:"fill",d:.25,q:"L'hormone fabriquée par le tissu adipeux qui informe le cerveau des réserves s'appelle la ___.",o:["leptine","ghréline","insuline","mélatonine"],a:0,w:"La leptine vient du gras et participe à la satiété. La ghréline, elle, vient de l'estomac et donne faim (module 3)."},
{i:"a191_05",u:191,t:"tiles",d:.25,q:"Reconstitue les trois poissons gras du moyen mnémotechnique.",a:["Sardine","Maquereau","Saumon"],dd:["Cabillaud","Colin","Sole"],w:"S.M.S. Le cabillaud, le colin et la sole sont des poissons maigres : bons, mais pauvres en oméga-3."},
{i:"a191_06",u:191,t:"tf",d:.3,q:"Laurence Plumey enlève le gras du jambon.",a:true,w:"C'est du gras saturé, « pas une graisse très intéressante, et on en mange déjà assez ». Le bon gras, c'est celui des poissons gras et des huiles."},
{i:"a191_07",u:191,t:"story",d:.3,q:"Paul adore cuisiner au beurre. Que lui conseilles-tu pour sa côte de bœuf ?",sc:[{who:"Paul",txt:"Je mets une grosse noix de beurre dans la poêle et je saisis à fond."}],o:["« Un peu d'huile d'abord, puis un peu de beurre : il ne noircit plus. »","« Continuez, le beurre brûlé donne du goût et n'a aucun effet négatif. »","« Supprimez toute matière grasse, faites-la cuire directement à sec. »","« Remplacez le beurre par de la margarine, elle supporte mieux le feu. »"],a:0,w:"Le beurre seul noircit et devient irritant. Huile puis beurre : le goût de noisette sans la brûlure."},
{i:"a191_08",u:191,t:"multi",d:.3,q:"À quoi sert le tissu adipeux ?",o:["Stocker l'énergie","Isoler du froid","Protéger les organes","Fabriquer des hormones","Digérer les aliments"],a:[0,1,2,3],w:"Un organe à part entière. La digestion, elle, se fait dans l'estomac et l'intestin."},
{i:"a191_09",u:191,t:"mcq",d:.35,q:"Pourquoi le Nord de la France a-t-il historiquement plus de maladies cardiovasculaires que le Sud selon Laurence Plumey ?",o:["Plus de beurre et de crème, moins d'olive","Un climat bien plus froid qui abîme le cœur","Plus de poisson, donc beaucoup trop d'oméga-3","Moins de pain complet consommé chaque jour"],a:0,w:"Cuisine au beurre et à la crème au Nord, à l'huile d'olive au Sud. Le régime méditerranéen reste l'un des meilleurs."},
{i:"a191_10",u:191,t:"match",d:.35,q:"Associe chaque huile à son usage conseillé.",p:[["Huile d'olive","Cuisson et assaisonnement"],["Huile de colza","Assaisonnement, riche en oméga-3"],["Huile de noix","Salades, à ne pas chauffer"],["Beurre","Tartine du matin, en petite quantité"]],w:"Olive pour cuire, colza et noix pour assaisonner (leurs oméga-3 sont fragiles à la chaleur), beurre en petite touche."},
{i:"a191_11",u:191,t:"story",d:.35,q:"Mme Garcia jette sa poêle « parce que le Téflon donne le cancer ». Que lui dis-tu ?",sc:[{who:"Mme Garcia",txt:"Je l'ai vu à la télé, toutes les poêles antiadhésives sont dangereuses."}],o:["« Jetez-la si elle est rayée, ne la chauffez jamais à vide ; l'inox est bien. »","« La télé a raison, toute poêle antiadhésive donne un cancer en quelques années. »","« Gardez-la même très rayée, ces revêtements n'ont jamais posé le moindre souci. »","« Remplacez-la par une poêle en aluminium brut, elle ne libère jamais rien. »"],a:0,w:"Le PTFE est stable ; le risque vient des PFAS de fabrication (PFOA, interdit en Europe depuis 2020) et de la surchauffe. Nuancer sans nier."},
{i:"a191_12",u:191,t:"fill",d:.4,q:"Le gras stocké autour des organes du ventre s'appelle le gras ___.",o:["viscéral","cutané","musculaire","osseux"],a:0,w:"Viscéral, autour des viscères. C'est le plus dangereux pour le cœur et le foie ; on le suit avec le tour de taille (module 1)."},
{i:"a191_13",u:191,t:"num",d:.4,q:"Une femme de 65 kg a 25 % de masse grasse. Combien de kilos de gras a-t-elle ?",a:16.25,tol:.3,un:" kg",h:"65 × 0,25",w:"Environ 16 kg. C'est dans la norme féminine (plus de gras que l'homme, notamment pour la grossesse et l'allaitement)."},
{i:"a191_14",u:191,t:"tf",d:.4,q:"Le PFOA, utilisé autrefois pour fabriquer le Téflon, est classé cancérogène certain par le CIRC depuis 2023.",a:true,w:"Oui, et il est interdit en Europe depuis 2020. C'est lui, et les autres PFAS, qui justifient la prudence, plus que le revêtement lui-même."},
{i:"a191_15",u:191,t:"order",d:.45,q:"Remets dans l'ordre la cuisson d'un œuf dans une poêle en inox.",it:["Chauffer la poêle à feu vif","Mettre l'huile et la laisser chauffer","Déposer l'œuf","Attendre qu'il saisisse et se décolle","Baisser le feu pour finir la cuisson"],w:"La méthode décrite dans le podcast. L'inox ne colle plus quand il est assez chaud et qu'on attend que l'aliment saisisse."},
{i:"a191_16",u:191,t:"mcq",d:.45,q:"Combien de fois par semaine le PNNS conseille-t-il de manger du poisson ?",o:["Deux fois, dont un poisson gras","Une seule fois par mois environ","Chaque jour, le midi et le soir","Jamais, à cause du mercure marin"],a:0,w:"Deux fois par semaine, dont un gras (sardine, maquereau, saumon, hareng) pour les oméga-3. C'est l'un des piliers du régime méditerranéen."},
{i:"a191_17",u:191,t:"story",d:.45,q:"Théo mange du saumon fumé une fois par mois et « déteste le poisson ». Comment l'aider à avoir des oméga-3 ?",sc:[{who:"Théo",txt:"Le poisson, ça pue et c'est cher."}],o:["« Sardines en boîte sur du pain, huile de colza, noix : pas cher du tout. »","« Prenez des gélules d'oméga-6 en pharmacie, c'est bien la même chose. »","« Les oméga-3 ne servent à rien à votre âge, attendez d'avoir quarante ans. »","« Mangez plus de beurre et de fromage, ils sont très riches en oméga-3. »"],a:0,w:"La sardine en boîte est l'une des sources les moins chères. Colza et noix complètent. Beurre et fromage apportent surtout des saturés."},
{i:"a191_18",u:191,t:"sort",d:.5,q:"Classe chaque conseil : juste ou exagéré ?",bins:["Juste","Exagéré"],it:[["Jeter une poêle antiadhésive rayée",0],["Toute poêle antiadhésive est très cancérigène",1],["Ne pas chauffer une poêle antiadhésive vide",0],["Supprimer tout le gras pour maigrir",1],["Préférer l'huile d'olive pour cuire",0]],w:"Le bon conseil nuance : prudence avec les PFAS et la surchauffe, pas de panique ; le gras se choisit, il ne se supprime pas."},
{i:"a191_19",u:191,t:"fill",d:.5,q:"Les « polluants éternels » de la famille du Téflon s'appellent les ___.",o:["PFAS","OGM","PCB","HAP"],a:0,w:"PFAS : substances per- et polyfluoroalkylées, qui ne se dégradent presque pas dans la nature ni dans le corps."},
{i:"a191_20",u:191,t:"match",d:.5,q:"Associe chaque aliment à la famille de gras à surveiller ou à privilégier.",p:[["Viennoiserie industrielle ancienne","Trans, à éviter"],["Saucisson","Saturés, à limiter"],["Maquereau","Oméga-3, à privilégier"],["Amandes","Oméga-9, à privilégier"]],w:"On limite saturés et trans, on privilégie oméga-3 et oméga-9."},
{i:"a191_21",u:191,t:"story",d:.55,q:"Rappel du module 2 : Chloé demande pourquoi le gras « fait grossir plus ». Que réponds-tu ?",sc:[{who:"Chloé",txt:"C'est vrai que le gras est plus calorique ?"}],o:["« Oui, 9 kcal par gramme contre 4 : on dose l'huile, sans la bannir. »","« Non, le gras apporte exactement autant de calories que le sucre au gramme. »","« Le gras n'apporte aucune calorie, il passe directement dans les intestins. »","« Seul le gras animal apporte des calories, l'huile d'olive n'en apporte pas. »"],a:0,w:"4, 4, 9, 7. Une cuillère à soupe d'huile, c'est environ 90 kcal, olive comprise. On dose, on ne supprime pas."},
{i:"a191_22",u:191,t:"slider",d:.55,q:"Au-delà de quelle température, environ, une poêle antiadhésive vide libère-t-elle des fumées toxiques (en °C) ?",min:100,max:400,step:10,a:260,tol:20,pre:"",un:" °C",w:"Environ 260 °C, atteint vite sur un feu vif sans rien dedans. Règle simple : ne jamais chauffer une antiadhésive à vide."},
{i:"a191_23",u:191,t:"multi",d:.55,q:"Quelles sources apportent des oméga-3 ?",o:["Sardine","Huile de colza","Noix","Hareng","Huile de tournesol"],a:[0,1,2,3],w:"Le tournesol apporte surtout des oméga-6, déjà trop présents dans l'alimentation française."},
{i:"a191_24",u:191,t:"tf",d:.6,q:"Il faut chauffer fortement l'huile de noix pour profiter de ses oméga-3.",a:false,w:"Au contraire : les oméga-3 sont fragiles à la chaleur. Noix et colza s'utilisent à froid, en assaisonnement."},
{i:"a191_25",u:191,t:"story",d:.6,q:"Paul, cholestérol LDL élevé, mange charcuterie et fromage tous les jours. Quel échange proposes-tu en premier ?",sc:[{who:"Paul",txt:"Je ne peux pas vivre sans mon fromage."}],o:["« Gardez le fromage à un repas, et la charcuterie du midi devient sardines. »","« Supprimez définitivement tout produit laitier et toute viande dès maintenant. »","« Ajoutez du beurre à chaque repas pour équilibrer le cholestérol de la journée. »","« Aucun lien entre ce que vous mangez et votre cholestérol, n'y pensez plus. »"],a:0,w:"On garde le plaisir principal, on remplace un saturé par un oméga-3. Un échange tenable vaut mieux qu'une interdiction."},
{i:"a191_26",u:191,t:"mcq",d:.65,q:"Pourquoi le régime méditerranéen est-il cité comme l'un des meilleurs ?",o:["Huile d'olive, poisson, légumes, légumineuses","Beaucoup de viande rouge et de beurre doux","Aucune matière grasse, jamais, nulle part","Uniquement des produits crus et entiers"],a:0,w:"Huile d'olive (oméga-9), poisson (oméga-3), légumes, fruits, légumineuses, céréales : le trio cœur, poids, longévité."},
{i:"a191_27",u:191,t:"num",d:.65,q:"Chloé met 3 cuillères à soupe d'huile (10 g chacune) dans sa salade. Combien de kcal (9 kcal par gramme) ?",a:270,tol:0,un:" kcal",h:"3 × 10 × 9",w:"270 kcal, autant qu'un petit repas. Une cuillère par personne suffit : on dose sans supprimer."},
{i:"a191_28",u:191,t:"fill",d:.7,q:"L'huile d'olive est surtout riche en ___.",o:["oméga-9","oméga-6","acides trans","cholestérol"],a:0,w:"Oméga-9 (mono-insaturés), bons pour le cœur. Une huile végétale ne contient pas de cholestérol."},
{i:"a191_29",u:191,t:"story",d:.7,q:"Rappel du module 1 : Paul demande pourquoi on mesure son tour de taille et pas seulement son poids.",sc:[{who:"Paul",txt:"Mon poids, ça ne suffit pas ?"}],o:["« Le tour de taille reflète le gras viscéral, le plus dangereux pour le cœur. »","« C'est pour choisir la bonne taille de pantalon, rien de plus important. »","« Le tour de taille ne sert qu'aux femmes, pour les hommes seul l'IMC compte. »","« Le poids dit tout, le tour de taille est une mode sans aucun intérêt. »"],a:0,w:"108 cm chez Paul : au-delà de 94 (et surtout 102) chez l'homme, le risque cardiovasculaire monte. C'est le gras viscéral qui parle."},
{i:"a191_30",u:191,t:"tiles",d:.75,q:"Reconstitue la règle des huiles.",a:["olive","pour","cuire","colza","pour","assaisonner"],dd:["palme","frire","beurre"],w:"Poisson gras deux fois, olive pour cuire, colza pour assaisonner."},
{i:"a191_31",u:191,t:"mcq",d:.75,q:"Qu'est-ce que Laurence Plumey appelle « le bon gras » ?",o:["Poissons gras et huiles végétales","Le gras du jambon et du lard fumé","La crème fraîche et le bon beurre","Les frites maison et les chips"],a:0,w:"Sardine, maquereau, saumon, colza, noix, olive. Le gras du jambon, lui, est saturé."},
{i:"a191_32",u:191,t:"story",d:.8,q:"Synthèse : Chloé veut une semaine type pour le gras. Que proposes-tu ?",sc:[{who:"Chloé",txt:"Concrètement, je remets quoi dans mon assiette ?"}],o:["« 2 poissons dont 1 gras, une cuillère d'huile par repas, des noix. »","« Rien de gras de la semaine, sauf un grand plat de frites le samedi soir. »","« Du beurre à chaque repas, c'est un gras naturel donc sans aucun risque. »","« Uniquement de l'huile de tournesol, la plus riche en oméga-3 du marché. »"],a:0,w:"S.M.S. deux fois, olive pour cuire, colza et noix pour assaisonner, saturés limités. Le gras bien choisi rassasie et protège."}
