/*UNIT*/
{id:193,c:"NUTRI",n:"Module 11",t:"Les aliments stars : œuf, yaourt, surimi, matcha, patate douce",col:"--green",ic:"🥚",guide:`
<h3>Le panier de Mme Garcia</h3>
<div class="gstory">Mme Garcia, 67 ans, vide son panier sur le bureau de Nora : des œufs (« mais pas plus de deux par semaine, à cause du cholestérol »), du surimi (« c'est des déchets, je sais, mais j'aime ça »), des yaourts aux fruits (« je ne supporte pas les laitages nature »), et un sachet de matcha offert par sa petite-fille. « Alors, qu'est-ce que je garde ? » Nora sourit : presque tout, mais pas pour les raisons qu'elle croit.</div>
<h3>L'œuf, la meilleure protéine la moins chère</h3>
<p>Un œuf de <b>50 g</b> contient tout ce qu'il faut pour faire vivre un poussin. Deux œufs apportent environ <b>12 g de protéines</b>, la moitié d'un steak, pour quelques dizaines de centimes. Ses protéines sont parmi les mieux utilisées par le corps. Deux œufs couvrent <b>25 à 100 % des besoins</b> de nombreuses vitamines, plus du fer, du zinc et de l'iode. Laurence Plumey dit « 9 vitamines sur 13 », et en fait l'œuf contient toutes les vitamines sauf la C. Dur, au plat ou en omelette, il garde les mêmes qualités.</p>
<p><b>Le cholestérol de l'œuf</b> a peu d'effet sur le cholestérol sanguin chez la plupart des gens : c'est surtout le foie qui fabrique le cholestérol, stimulé par les graisses saturées. On peut manger <b>2 à 3 œufs par jour</b> selon Laurence Plumey. Nuance : quelques personnes sont très sensibles, et en cas de diabète ou d'hypercholestérolémie familiale, on en parle au médecin.</p>
<h3>Le yaourt et le calcium</h3>
<p>Un yaourt, c'est du lait <b>fermenté</b> par deux bactéries vivantes. Un pot en contient environ <b>10 milliards</b>. Environ <b>80 %</b> meurent dans l'estomac, très acide (<b>pH 2</b>, comme le jus de citron), et les survivantes rejoignent le microbiote. Les autres aliments fermentés (kéfir, choucroute, fromages) nourrissent aussi le microbiote.</p>
<div class="gtrap">Correction du podcast : les besoins en calcium ne sont pas de 800 mg mais de <b>950 mg par jour</b> pour un adulte de plus de 25 ans (Anses, 2016), et de 1 000 mg de 18 à 24 ans. Un pot de yaourt de 125 g apporte environ <b>150 à 200 mg</b> : deux pots couvrent donc environ un tiers du besoin, pas la moitié. Le reste vient des autres aliments : eaux minérales riches en calcium, légumes verts, amandes, sardines avec leurs arêtes, pain. D'où le repère officiel de Santé publique France (2019) : <b>2 produits laitiers par jour pour un adulte</b>, et 3 pour les enfants et les adolescents, qui grandissent.</div>
<p>Le <b>yaourt aux fruits ou aromatisé</b> contient environ <b>2 morceaux de sucre</b> par pot, et très peu de fruit. L'astuce : un yaourt nature avec des myrtilles, ou une petite cuillère de confiture ou de miel que l'on dose soi-même.</p>
<div class="gmnemo"><b>« Œuf complet, yaourt nature, fruit coloré. »</b> Les trois réflexes du chariot de Laurence Plumey. Et pour le calcium : <b>« 2 laitiers par jour, 950 au compteur »</b> (les laitiers plus les eaux, légumes verts et amandes).</div>
<h3>Le surimi, pas si méchant</h3>
<p>Le surimi est une <b>recette</b>, pas du poisson : environ <b>30 à 40 % de chair de poisson</b> (poissons pêchés pour ça, congelés sur le bateau), de l'huile de colza, de la fécule, un peu de sucre, roulé dans le <b>paprika</b> pour la couleur, avec un arôme de crabe. Moins de <b>20 kcal par bâtonnet</b>, des protéines, pas toxique. Mais pas de vitamines ni de minéraux (la chair est très lavée).</p>
<div class="gtrap">Nuance sur le podcast : le surimi n'est pas « sans sucre ni gras » ni « sans additifs ». Il contient un peu de sucre et d'huile, souvent des additifs de conservation, et surtout <b>du sel</b> (environ 1,5 à 2 g pour 100 g). Il reste un produit ultra-transformé acceptable de temps en temps, pas un équivalent du poisson.</div>
<h3>Matcha, patate douce, kiwi</h3>
<ul><li><b>Matcha</b> : thé vert japonais en poudre. Les plants sont mis à <b>l'ombre</b> avant la récolte : pour capter le peu de lumière, ils fabriquent plus de <b>chlorophylle</b> (comme le corps fabrique plus de globules rouges en altitude). Très riche en <b>EGCG</b> (épigallocatéchine gallate, un antioxydant) et en <b>théanine</b>, une molécule relaxante. Il contient aussi de la caféine : pas le soir.</li>
<li><b>Patate douce</b> : c'est un <b>féculent</b>, pas un légume. Plus riche en bêta-carotène que la pomme de terre : si on a le choix, on la préfère.</li>
<li><b>Kiwi</b> : environ 70 à 80 mg de vitamine C par fruit, soit une grande part du besoin (110 mg par jour selon l'Anses). Agrumes, mangue, fruits rouges et myrtilles sont aussi des champions.</li></ul>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Rassurer sur l'œuf et le cholestérol, avec la nuance</li><li>Calculer un apport en calcium et corriger le chiffre du podcast</li><li>Lire une étiquette de surimi et de yaourt aromatisé</li><li>Expliquer pourquoi le matcha est si vert et ce qu'il apporte</li></ul>`},
/*EXOS*/
{i:"a193_01",u:193,t:"story",d:.2,nw:"L'œuf et le cholestérol",q:"Mme Garcia limite les œufs à deux par semaine. Que lui dis-tu ?",sc:[{who:"Mme Garcia",txt:"Mon médecin de 1990 m'a dit que les œufs bouchent les artères."}],o:["« Le cholestérol de l'œuf influe peu : 1 à 2 par jour, c'est très bien. »","« Il avait raison, l'œuf est l'aliment le plus dangereux pour les artères. »","« Mangez uniquement le jaune, c'est le blanc qui contient le cholestérol. »","« Remplacez les œufs par de la charcuterie, qui contient moins de gras. »"],a:0,w:"Le cholestérol sanguin vient surtout du foie, stimulé par les graisses saturées. Pour une senior, l'œuf est une protéine précieuse et bon marché. On garde un œil sur un bilan anormal."},
{i:"a193_02",u:193,t:"num",d:.2,q:"Deux œufs apportent 12 g de protéines. Combien pour une omelette de 3 œufs ?",a:18,tol:0,un:" g",h:"12 / 2 × 3",w:"18 g, presque un steak. Rappel du module 2 : un adulte de 70 kg a besoin d'environ 58 g de protéines par jour (0,83 g/kg)."},
{i:"a193_03",u:193,t:"slider",d:.25,q:"Quel est le besoin en calcium d'un adulte de plus de 25 ans selon l'Anses (en mg par jour) ?",min:200,max:1500,step:50,a:950,tol:0,pre:"",un:" mg",w:"950 mg (1 000 mg de 18 à 24 ans). Le podcast dit 800 mg : c'est l'ancien repère."},
{i:"a193_04",u:193,t:"fill",d:.25,q:"Le thé matcha est très vert car ses plants poussent à l'___ avant la récolte.",o:["ombre","altitude","humidité","engrais"],a:0,w:"À l'ombre, la plante fabrique plus de chlorophylle pour capter la lumière qui manque, comme le corps fabrique plus de globules rouges en altitude."},
{i:"a193_05",u:193,t:"tf",d:.25,q:"La patate douce est un légume.",a:false,w:"C'est un féculent, comme la pomme de terre. Mais plus riche en bêta-carotène : si on a le choix, on la préfère."},
{i:"a193_06",u:193,t:"match",d:.25,q:"Associe chaque aliment à son atout principal.",p:[["Œuf","Protéines complètes pas chères"],["Yaourt nature","Calcium et bactéries vivantes"],["Kiwi","Vitamine C"],["Matcha","EGCG et théanine"]],w:"Œuf complet, yaourt nature, fruit coloré : les réflexes du chariot. La patate douce, elle, est un féculent riche en bêta-carotène."},
{i:"a193_07",u:193,t:"story",d:.3,q:"Mme Garcia ne supporte pas le yaourt nature. Que proposes-tu ?",sc:[{who:"Mme Garcia",txt:"Nature, c'est trop acide. Je prends aux fruits."}],o:["« Un yaourt nature avec des myrtilles, ou du miel que vous dosez. »","« Gardez les yaourts aux fruits, ils contiennent surtout des fruits frais. »","« Arrêtez tous les laitages, le calcium n'est plus utile à votre âge. »","« Prenez-en quatre aux fruits par jour pour atteindre votre calcium. »"],a:0,w:"Un yaourt aux fruits, c'est environ 2 morceaux de sucre et peu de fruit. En le sucrant soi-même, on met souvent deux fois moins. Et le calcium reste essentiel après 60 ans."},
{i:"a193_08",u:193,t:"mcq",d:.3,q:"Quelle proportion des bactéries du yaourt meurt dans l'estomac, selon Laurence Plumey ?",o:["Environ 80 %","Environ 5 %","Aucune","Toutes, sans exception"],a:0,w:"L'estomac est à pH 2, comme le jus de citron. Environ 80 % meurent, les autres rejoignent le microbiote. Kéfir, choucroute, fromages : les autres aliments fermentés apportent aussi des bactéries."},
{i:"a193_09",u:193,t:"multi",d:.3,q:"Que contient réellement une recette de surimi ?",o:["Chair de poisson","Huile de colza","Fécule","Paprika","Carapace de crabe"],a:[0,1,2,3],w:"Environ 30 à 40 % de poisson, de l'huile, de la fécule, un peu de sucre, du paprika et un arôme de crabe. Pas de crabe."},
{i:"a193_10",u:193,t:"num",d:.35,q:"Deux yaourts de 180 mg de calcium chacun : quel pourcentage des 950 mg couvrent-ils (arrondi) ?",a:38,tol:1,un:" %",h:"360 / 950 × 100",w:"Environ 38 %, un gros tiers, pas la moitié comme dit dans le podcast. D'où le repère de 2 laitiers par jour chez l'adulte, complété par les eaux calciques, légumes verts et amandes."},
{i:"a193_11",u:193,t:"tiles",d:.35,q:"Reconstitue les trois réflexes du chariot.",a:["œuf","complet","yaourt","nature","fruit","coloré"],dd:["aromatisé","soda","blanc"],w:"Œuf complet, yaourt nature, fruit coloré."},
{i:"a193_12",u:193,t:"story",d:.35,q:"La petite-fille de Mme Garcia lui a offert du matcha. Elle demande quand le boire.",sc:[{who:"Mme Garcia",txt:"Le soir, pour me détendre avant de dormir ?"}],o:["« Plutôt le matin ou à midi : il contient aussi de la caféine. »","« Le soir, c'est parfait, il ne contient absolument aucun excitant. »","« Jamais, le matcha est toxique pour les personnes de plus de 60 ans. »","« Uniquement avec beaucoup de sucre, sinon il n'a aucun effet santé. »"],a:0,w:"La théanine détend, mais la caféine peut gêner le sommeil. Matin ou midi, sans sucre."},
{i:"a193_13",u:193,t:"sort",d:.4,q:"Classe chaque affirmation sur le surimi : vraie ou fausse ?",bins:["Vraie","Fausse"],it:[["Moins de 20 kcal par bâtonnet",0],["Fabriqué avec des déchets",1],["Riche en vitamines et minéraux",1],["Assez salé",0],["Environ 30 à 40 % de poisson",0],["Contient du crabe",1]],w:"Une recette acceptable, peu calorique, mais salée et pauvre en micronutriments. Ni poison, ni poisson."},
{i:"a193_14",u:193,t:"fill",d:.4,q:"La molécule relaxante du matcha s'appelle la ___.",o:["théanine","théobromine","taurine","tyrosine"],a:0,w:"La théanine, un acide aminé du thé, donne une sensation de calme. La théobromine, c'est celle du chocolat."},
{i:"a193_15",u:193,t:"tf",d:.4,q:"Un œuf dur et un œuf au plat ont les mêmes qualités nutritionnelles.",a:true,w:"Dur, coque, au plat, en omelette : mêmes protéines, mêmes vitamines. Seule la matière grasse ajoutée change le total."},
{i:"a193_16",u:193,t:"mcq",d:.45,q:"Quelle est la seule vitamine absente de l'œuf ?",o:["La vitamine C","La vitamine D","La vitamine B12","La vitamine A"],a:0,w:"L'œuf contient toutes les vitamines sauf la C. D'où l'idée de l'associer à des crudités ou à un kiwi."},
{i:"a193_17",u:193,t:"story",d:.45,q:"Chloé veut une salade composée légère pour le bureau. Laquelle proposes-tu ?",sc:[{who:"Chloé",txt:"J'ai 5 minutes le matin, pas plus."}],o:["« Crudités, 2 œufs durs ou du surimi, pois chiches, huile de colza. »","« Salade iceberg seule, sans assaisonnement, pour le moins de calories. »","« Pâtes au fromage et lardons, ça tient plus longtemps au bureau. »","« Un paquet de chips et un soda light, c'est rapide et peu calorique. »"],a:0,w:"Légumes, protéines (œuf, surimi, thon, sardines), fibres (pois chiches), bon gras. Laurence Plumey cite justement le surimi dans la salade composée."},
{i:"a193_18",u:193,t:"slider",d:.45,q:"Combien de morceaux de sucre contient un yaourt aux fruits, selon Laurence Plumey ?",min:0,max:8,step:1,a:2,tol:0,pre:"",un:"",w:"Environ 2 morceaux (10 g de sucre ajouté), et très peu de fruit. Nature + fruit frais : même plaisir, moins de sucre."},
{i:"a193_19",u:193,t:"match",d:.5,q:"Associe chaque fruit à son antioxydant vedette.",p:[["Kiwi","Vitamine C"],["Myrtille","Anthocyanes"],["Mangue","Bêta-carotène"],["Orange","Vitamine C et flavonoïdes"]],w:"Kiwi, agrumes, mangue, fruits rouges : les fruits colorés cités dans le podcast. La patate douce, orange, est aussi une source de bêta-carotène."},
{i:"a193_20",u:193,t:"order",d:.5,q:"Remets dans l'ordre la fabrication du surimi.",it:["Pêche de poissons dédiés","Filets congelés sur le bateau","Malaxage avec huile, fécule et un peu de sucre","Cuisson et mise en bâtonnets","Roulage dans le paprika"],w:"Une recette à base de poisson, comme le décrit Laurence Plumey. Pas des déchets."},
{i:"a193_21",u:193,t:"tf",d:.5,q:"Le podcast dit que deux yaourts couvrent la moitié du besoin en calcium : c'est exact avec les repères actuels.",a:false,w:"Avec 950 mg de besoin et 150 à 200 mg par pot, deux yaourts couvrent environ un tiers. Repère adulte : 2 laitiers par jour, plus les autres sources de calcium."},
{i:"a193_22",u:193,t:"story",d:.55,q:"Rappel du module 2 : Mme Garcia mange peu de protéines et perd du muscle. Que proposes-tu ?",sc:[{who:"Mme Garcia",txt:"La viande, c'est cher et dur à mâcher."}],o:["« Un œuf ou deux par jour, un yaourt par repas, du poisson en boîte. »","« Mangez plus de pain, il contient autant de protéines que la viande. »","« À votre âge, on a besoin de moins de protéines, ne changez rien. »","« Prenez des compléments de vitamine C, ils remplacent les protéines. »"],a:0,w:"Après 65 ans, le besoin de protéines est au moins aussi élevé. L'œuf est la protéine la moins chère et la plus facile à manger."},
{i:"a193_23",u:193,t:"mcq",d:.55,q:"Pourquoi Laurence Plumey compare-t-elle le matcha au corps en altitude ?",o:["Dans les deux cas, on compense un manque","Dans les deux cas, on respire bien moins","Les deux font perdre du poids durablement","Le matcha pousse en très haute montagne"],a:0,w:"En altitude, on fabrique plus de globules rouges pour capter l'oxygène qui manque ; à l'ombre, le thé fabrique plus de chlorophylle pour capter la lumière."},
{i:"a193_24",u:193,t:"fill",d:.55,q:"L'antioxydant vedette du thé vert, cité par Laurence Plumey, est l'___.",o:["épigallocatéchine","isoflavone du soja","hémoglobine","anthocyanidine"],a:0,w:"L'épigallocatéchine gallate (EGCG). Le matcha en contient encore plus que le thé vert infusé, car on boit la feuille entière en poudre."},
{i:"a193_25",u:193,t:"story",d:.6,q:"Rappel du module 10 : Paul demande si le kéfir est une mode ou un vrai atout.",sc:[{who:"Paul",txt:"Ma fille m'en fait boire, c'est sérieux ?"}],o:["« Fermenté comme le yaourt, il nourrit le microbiote : un vrai plus. »","« Pure mode, les aliments fermentés n'ont aucun effet sur l'intestin. »","« C'est dangereux, les aliments fermentés sont des aliments pourris. »","« Ça remplace les fibres, vous pouvez arrêter légumes et lentilles. »"],a:0,w:"Kéfir, yaourt, choucroute : les fermentés enrichissent le microbiote. Ils ne remplacent pas les fibres, qui le nourrissent."},
{i:"a193_26",u:193,t:"num",d:.6,q:"Un kiwi apporte 75 mg de vitamine C et le besoin est de 110 mg. Quel pourcentage couvre-t-il (arrondi) ?",a:68,tol:2,un:" %",h:"75 / 110 × 100",w:"Environ 68 %, deux tiers du besoin en un seul fruit. Avec une orange, on dépasse les 100 %. La vitamine C aide aussi à neutraliser les radicaux libres."},
{i:"a193_27",u:193,t:"sort",d:.6,q:"Classe chaque aliment : bon réflexe au quotidien ou occasionnel ?",bins:["Quotidien","Occasionnel"],it:[["Yaourt nature",0],["Œufs",0],["Yaourt aux fruits",1],["Surimi",1],["Kiwi",0],["Crème dessert",1]],w:"Le surimi reste acceptable mais salé et pauvre en micronutriments : occasionnel. Le yaourt aux fruits : dessert sucré, pas laitage santé. Le yaourt nature est un aliment fermenté, le yaourt aux fruits un dessert."},
{i:"a193_28",u:193,t:"multi",d:.65,q:"Qu'apporte l'œuf en plus des protéines ?",o:["Fer","Zinc","Iode","Vitamines du groupe B","Vitamine C"],a:[0,1,2,3],w:"Fer, zinc, iode, vitamines B, A, D, E. Tout sauf la vitamine C."},
{i:"a193_29",u:193,t:"story",d:.7,q:"Un patient a une hypercholestérolémie familiale et veut manger 3 œufs par jour après avoir vu une vidéo.",sc:[{who:"Patient",txt:"Laurence Plumey dit qu'on peut en manger trois par jour !"}],o:["« Pour la plupart des gens oui ; votre cas, voyez-le avec votre médecin. »","« Allez-y, trois œufs par jour ne posent de problème à personne. »","« Interdiction totale des œufs pour vous, et pour toute votre famille aussi. »","« Remplacez-les par du beurre, qui contient bien moins de cholestérol. »"],a:0,w:"Le message général est juste, mais certaines personnes (hypercholestérolémie familiale, diabète) sont plus sensibles. Un bon professionnel adapte au patient."},
{i:"a193_30",u:193,t:"tiles",d:.7,q:"Reconstitue la correction sur le calcium.",a:["950","mg","par","jour","2","laitiers"],dd:["800","3","soda"],w:"2 laitiers par jour chez l'adulte (3 chez l'enfant), 950 au compteur. Le podcast cite 800 mg, repère ancien."},
{i:"a193_31",u:193,t:"mcq",d:.75,q:"Quel est le principal point de vigilance du surimi ?",o:["Le sel","Le mercure","Le cholestérol","Le gluten caché"],a:0,w:"Environ 1,5 à 2 g de sel pour 100 g. Pour une personne hypertendue, on le garde occasionnel."},
{i:"a193_32",u:193,t:"story",d:.8,q:"Synthèse : que gardes-tu du panier de Mme Garcia ?",sc:[{who:"Mme Garcia",txt:"Alors, docteur, qu'est-ce que je garde ?"}],o:["« Les œufs sans limite stricte, yaourts nature, surimi parfois, matcha le matin. »","« Rien du tout, tous ces produits sont à bannir définitivement de votre panier. »","« Seulement le surimi et les yaourts aux fruits, les œufs sont trop dangereux. »","« Uniquement le matcha, il remplace à lui seul tous les autres aliments du panier. »"],a:0,w:"Œuf complet, yaourt nature, fruit coloré. Le surimi n'est pas un poison, juste un produit occasionnel. Le matcha, oui, mais pas le soir."}
