/*UNIT*/
{id:194,c:"NUTRI",n:"Module 12",t:"Cuisine sûre : le riz de la veille, le micro-ondes et le frigo",col:"--green",ic:"🍚",guide:`
<h3>Le riz de Théo</h3>
<div class="gstory">Théo cuisine le dimanche soir un kilo de riz « pour toute la semaine ». La casserole reste sur la plaque jusqu'au lendemain matin, puis part au frigo sans couvercle, à côté du poulet cru. Jeudi, il en réchauffe 30 secondes au micro-ondes dans sa boîte en plastique. Deux heures plus tard : vomissements. Aux urgences, on lui parle d'une bactérie au nom de film d'horreur, <i>Bacillus cereus</i>. Nora, au rendez-vous suivant : « Le riz n'était pas mauvais. C'est tout ce qu'on a fait autour qui l'était. »</div>
<h3>Pourquoi le riz cuit est piégeux</h3>
<p>Le riz pousse dans l'eau et la chaleur : il porte naturellement une bactérie, <b>Bacillus cereus</b>. La cuisson tue les bactéries actives, mais pas leurs <b>spores</b>, de petites formes de survie très résistantes à la chaleur. Si le riz cuit reste à <b>température ambiante</b>, les spores germent, les bactéries se multiplient et fabriquent une <b>toxine</b>. Cette toxine résiste à la chaleur : <b>réchauffer ne la détruit pas</b>. On l'appelle parfois le « syndrome du riz frit ».</p>
<div class="gtrap">Précision sur le podcast : les spores ne « se multiplient » pas dans le frigo. Le froid (4 °C ou moins) ralentit fortement les bactéries sans les tuer : Laurence Plumey a raison de dire que le frigo n'est pas stérilisant, les bactéries y sont « endormies ». Le moment le plus dangereux est celui où le riz refroidit lentement à température ambiante. Règle juste : refroidir vite (au frigo en moins de 2 heures), consommer dans les <b>24 heures</b> pour le riz (48 heures au plus pour les autres restes), et bien réchauffer une seule fois.</div>
<div class="gmnemo"><b>« Riz cuit : 2 heures pour le frigo, 24 heures pour le manger, 1 seul réchauffage. »</b> Et la bonne dose : un sachet pour deux, pas un kilo pour la semaine. Pour le frigo : <b>« Couvert, séparé, sous 4 degrés »</b>.</div>
<h3>Le micro-ondes : chauffer n'est pas cuire</h3>
<ul><li>Un réchauffage de 30 secondes <b>tiède</b> le plat sans agir sur les bactéries. Il faut chauffer <b>à cœur</b> (fumant partout, au moins 70 °C), en remuant à mi-temps car le micro-ondes chauffe de façon inégale.</li>
<li>On ne réchauffe pas un plat <b>plusieurs fois</b> : à chaque refroidissement, les bactéries repartent. On sort la portion qu'on va manger, pas le plat familial entier.</li>
<li>On ne réchauffe pas dans le <b>plastique d'origine</b> : la chaleur fait migrer des molécules du contenant vers l'aliment (bisphénols, phtalates, des <b>perturbateurs endocriniens</b>, module 14). On transvase dans du <b>verre</b> ou une assiette.</li></ul>
<h3>Le frigo n'est pas stérile</h3>
<table><tr><th>Règle</th><th>Pourquoi</th></tr>
<tr><td>Température à 4 °C ou moins</td><td>En dessous, la plupart des bactéries se multiplient très lentement</td></tr>
<tr><td>Restes couverts, dans des boîtes fermées</td><td>Éviter la <b>contamination croisée</b> (les bactéries d'un aliment passent à un autre)</td></tr>
<tr><td>Viande crue en bas, jamais au-dessus des aliments prêts à manger</td><td>Le jus de viande crue coule et contamine</td></tr>
<tr><td>Planche et couteau lavés entre viande crue et crudités</td><td>Même risque de contamination croisée</td></tr>
<tr><td>Zone de danger entre 4 et 63 °C</td><td>C'est là que les bactéries prolifèrent : on n'y laisse pas les plats</td></tr></table>
<p>Sur les emballages, la <b>DLC</b> (« à consommer jusqu'au ») est une date de sécurité, à respecter strictement. La <b>DDM</b> (« à consommer de préférence avant ») est une date de qualité : le produit reste consommable après.</p>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Expliquer le risque du riz cuit et les bons gestes</li><li>Donner les règles du réchauffage au micro-ondes</li><li>Organiser un frigo sans contamination croisée</li><li>Distinguer DLC et DDM pour éviter le gaspillage sans prendre de risque</li></ul>`},
/*EXOS*/
{i:"a194_01",u:194,t:"story",d:.2,nw:"Le riz cuit et Bacillus cereus",q:"Théo demande ce qui l'a rendu malade. Que lui expliques-tu ?",sc:[{who:"Théo",txt:"Le riz était cuit, pourtant, ça tue tout, non ?"}],o:["« La cuisson laisse des spores ; resté dehors, le riz a fabriqué une toxine. »","« Le riz cru était périmé, la cuisson n'avait donc servi strictement à rien. »","« C'est le micro-ondes qui a créé des bactéries en chauffant trop fort le plat. »","« C'est une allergie au riz, arrêtez d'en manger définitivement dès maintenant. »"],a:0,w:"Bacillus cereus : les spores survivent à la cuisson, germent à température ambiante, et la toxine résiste au réchauffage. Riz cuit : 2 heures pour le frigo, 24 heures pour le manger."},
{i:"a194_02",u:194,t:"slider",d:.2,q:"Combien de temps au maximum garder du riz cuit au frigo selon Laurence Plumey (en heures) ?",min:0,max:96,step:12,a:24,tol:0,pre:"",un:" h",w:"24 heures pour le riz (48 heures au plus pour les autres restes). Le reste, on le jette : mieux vaut cuire la juste dose."},
{i:"a194_03",u:194,t:"fill",d:.25,q:"Les formes de survie des bactéries, très résistantes à la chaleur, s'appellent les ___.",o:["spores","toxines","virus","levures"],a:0,w:"Les spores. La cuisson ne les détruit pas : c'est pour ça que le riz cuit doit vite partir au frigo."},
{i:"a194_04",u:194,t:"tf",d:.25,q:"Le frigo tue les bactéries.",a:false,w:"Il les endort. À 4 °C ou moins, elles se multiplient très lentement ; à température ambiante, elles repartent."},
{i:"a194_05",u:194,t:"order",d:.25,q:"Remets dans l'ordre les bons gestes après la cuisson du riz.",it:["Cuire la juste dose","Servir tout de suite","Mettre les restes en boîte fermée au frigo en moins de 2 h","Les manger dans les 24 h","Les réchauffer une seule fois, bien chaud"],w:"La juste dose évite la plupart des problèmes : un sachet pour deux, comme le conseille Laurence Plumey."},
{i:"a194_06",u:194,t:"multi",d:.3,q:"Quelles erreurs Théo a-t-il faites ?",o:["Cuire un kilo pour la semaine","Laisser le riz sur la plaque toute la nuit","Le ranger sans couvercle près du poulet cru","Le réchauffer 30 secondes dans du plastique","Le cuire dans l'eau bouillante"],a:[0,1,2,3],w:"Quatre erreurs en chaîne. Cuire dans l'eau bouillante, lui, est tout à fait normal."},
{i:"a194_07",u:194,t:"match",d:.3,q:"Associe chaque sigle ou notion à son sens.",p:[["DLC","Date de sécurité, à respecter"],["DDM","Date de qualité, consommable après"],["Contamination croisée","Bactéries d'un aliment passées à un autre"],["Zone de danger","Entre 4 et 63 °C"]],w:"DLC stricte, DDM souple : un yaourt a une DLC, des pâtes sèches une DDM."},
{i:"a194_08",u:194,t:"story",d:.3,q:"La famille Martin réchauffe le gratin familial trois fois dans la semaine. Que conseilles-tu ?",sc:[{who:"Mme Martin",txt:"On le remet au micro-ondes à chaque repas, c'est pratique."}],o:["« Sortez seulement la portion du jour et réchauffez-la une fois, bien à cœur. »","« Aucun souci, le micro-ondes détruit toutes les bactéries à chaque passage. »","« Laissez-le sur la table entre les repas, il se conserve mieux que froid. »","« Congelez-le et décongelez-le à chaque repas, c'est la méthode la plus sûre. »"],a:0,w:"Chaque refroidissement relance les bactéries. On découpe les portions, on réchauffe une seule fois, fumant partout."},
{i:"a194_09",u:194,t:"mcq",d:.35,q:"Pourquoi réchauffer le riz contaminé ne suffit-il pas à éviter l'intoxication ?",o:["La toxine résiste à la chaleur","Le riz refroidit trop vite","Le micro-ondes crée des bactéries","Le riz perd ses vitamines"],a:0,w:"La toxine de Bacillus cereus est thermostable : une fois fabriquée, elle reste. Il faut empêcher sa formation, en refroidissant vite."},
{i:"a194_10",u:194,t:"sort",d:.35,q:"Classe chaque geste : sûr ou risqué ?",bins:["Sûr","Risqué"],it:[["Restes au frigo en boîte fermée",0],["Riz laissé toute la nuit sur la plaque",1],["Viande crue en bas du frigo",0],["Même planche pour poulet cru et salade",1],["Réchauffer une seule fois à cœur",0],["Plat réchauffé dans sa barquette plastique",1]],w:"Couvert, séparé, sous 4 degrés, et un seul réchauffage dans du verre."},
{i:"a194_11",u:194,t:"num",d:.35,q:"Le frigo de Théo affiche 9 °C. De combien de degrés doit-il le baisser pour atteindre la bonne température ?",a:5,tol:0,un:" °C",h:"9 − 4",w:"5 degrés. À 9 °C, on est dans la zone de danger (4 à 63 °C) : les bactéries se multiplient bien plus vite."},
{i:"a194_12",u:194,t:"tiles",d:.4,q:"Reconstitue la règle du frigo.",a:["couvert","séparé","sous","4","degrés"],dd:["ouvert","10","mélangé"],w:"Couvert, séparé, sous 4 degrés : les trois gestes contre la contamination croisée."},
{i:"a194_13",u:194,t:"story",d:.4,q:"Chloé réchauffe son plat préparé dans sa barquette plastique. Que lui dis-tu ?",sc:[{who:"Chloé",txt:"C'est marqué « micro-ondable », c'est bon, non ?"}],o:["« Transvasez dans du verre : la chaleur fait migrer des molécules. »","« Aucun risque, le plastique ne libère rien, même chauffé plusieurs minutes. »","« Mettez plutôt du papier aluminium dessus, ça protège de la migration. »","« Réchauffez-le au maximum de puissance, les molécules seront détruites. »"],a:0,w:"Conseil de Laurence Plumey : jamais dans le conditionnement d'origine. Bisphénols et phtalates, perturbateurs endocriniens, migrent avec la chaleur. L'aluminium au micro-ondes, lui, fait des étincelles."},
{i:"a194_14",u:194,t:"fill",d:.4,q:"La bactérie du riz cuit mal conservé s'appelle Bacillus ___.",o:["cereus","coli","botulinum","listeria"],a:0,w:"Bacillus cereus, « le bacille des céréales ». Il cause vomissements ou diarrhées quelques heures après le repas."},
{i:"a194_15",u:194,t:"tf",d:.45,q:"Un plat réchauffé 30 secondes au micro-ondes est débarrassé de ses bactéries.",a:false,w:"30 secondes, c'est tiède. Il faut chauffer à cœur (fumant partout, au moins 70 °C) en remuant, et ça n'élimine toujours pas les toxines déjà formées."},
{i:"a194_16",u:194,t:"mcq",d:.45,q:"Où ranger la viande crue dans le frigo ?",o:["En bas, dans une boîte fermée","En haut, au-dessus des laitages","Dans la porte, près des œufs","Posée à nu près des crudités"],a:0,w:"En bas, pour que son jus ne coule pas sur les aliments prêts à manger. Et toujours dans une boîte fermée."},
{i:"a194_17",u:194,t:"story",d:.45,q:"Mme Garcia jette un paquet de pâtes sèches dont la date « de préférence avant » est passée d'un mois.",sc:[{who:"Mme Garcia",txt:"C'est périmé, je ne prends pas de risque."}],o:["« C'est une DDM : les pâtes restent bonnes, ne les jetez pas. »","« Vous avez raison, toute date dépassée rend l'aliment toxique. »","« Gardez-les, mais faites-les bouillir deux heures pour être sûre. »","« Jetez aussi le riz et la farine, ils périment tous en même temps. »"],a:0,w:"DDM = date de qualité. La DLC (« à consommer jusqu'au »), elle, se respecte strictement : viande, poisson, laitages frais."},
{i:"a194_18",u:194,t:"match",d:.5,q:"Associe chaque aliment à sa bonne pratique.",p:[["Riz cuit","Au frigo en moins de 2 h, mangé en 24 h"],["Poulet cru","En bas du frigo, boîte fermée"],["Plat en barquette plastique","Transvasé dans du verre"],["Pâtes sèches","DDM, consommables après la date"]],w:"Chaque aliment a son geste. Le plus important à retenir : le riz cuit ne traîne jamais à température ambiante."},
{i:"a194_19",u:194,t:"slider",d:.5,q:"À quelle température minimale un plat doit-il être réchauffé à cœur (en °C) ?",min:30,max:100,step:5,a:70,tol:5,pre:"",un:" °C",w:"Au moins 70 °C à cœur, fumant partout. Le micro-ondes chauffe de façon inégale : on remue à mi-temps."},
{i:"a194_20",u:194,t:"story",d:.5,q:"Rappel du module 5 : les Martin préparent le biberon de lait d'un bébé à l'avance pour la nuit. Que dis-tu ?",sc:[{who:"M. Martin",txt:"On le prépare à 20 h et on le donne à 3 h du matin."}],o:["« Un lait préparé ne se garde pas des heures : préparez-le au moment. »","« Aucun souci, le lait infantile se conserve plusieurs jours sur la table. »","« Réchauffez-le trois fois dans la nuit, les bactéries n'aiment pas ça. »","« Ajoutez un peu de sucre, ça conserve le lait comme de la confiture. »"],a:0,w:"Le lait est un milieu idéal pour les bactéries, et le bébé y est très sensible. On prépare au moment, ou on garde au frigo moins de 24 h selon les consignes."},
{i:"a194_21",u:194,t:"tf",d:.55,q:"La contamination croisée, c'est le passage de bactéries d'un aliment à un autre.",a:true,w:"Par contact, par un jus qui coule, par une planche ou un couteau. D'où le frigo couvert et séparé, et la planche lavée entre viande crue et crudités."},
{i:"a194_22",u:194,t:"multi",d:.55,q:"Quels gestes évitent la contamination croisée ?",o:["Laver la planche entre viande et crudités","Ranger les restes couverts","Se laver les mains après la viande crue","Mettre la viande crue en bas du frigo","Poser le poulet cru sur la salade"],a:[0,1,2,3],w:"Le poulet cru posé sur la salade est l'exemple type de contamination croisée."},
{i:"a194_23",u:194,t:"num",d:.6,q:"Théo cuisine 1 000 g de riz cru ; il en mange 125 g cru par repas. Combien de repas faudrait-il pour tout finir ?",a:8,tol:0,un:" repas",h:"1 000 / 125",w:"8 repas, soit bien plus que les 24 heures de conservation. D'où le conseil : cuire la juste dose, un sachet pour deux."},
{i:"a194_24",u:194,t:"story",d:.6,q:"Paul demande si les « bisphénols » ont un lien avec sa santé.",sc:[{who:"Paul",txt:"On en parle à la télé, c'est quoi exactement ?"}],o:["« Des molécules de plastiques qui perturbent les hormones : on ne les chauffe pas. »","« Des vitamines ajoutées aux plats préparés pour les rendre plus nutritifs. »","« Des bactéries du plastique qui provoquent des intoxications en quelques heures. »","« Un additif du sel de table, sans lien avec les contenants en plastique. »"],a:0,w:"Les bisphénols sont des perturbateurs endocriniens. Le bisphénol A est interdit dans les contenants alimentaires en France depuis 2015 ; par prudence, on ne chauffe pas dans le plastique."},
{i:"a194_25",u:194,t:"fill",d:.6,q:"La date « à consommer jusqu'au » s'appelle la ___.",o:["DLC","DDM","DLUO","TVA"],a:0,w:"DLC : date limite de consommation, date de sécurité. La DDM a remplacé l'ancienne DLUO."},
{i:"a194_26",u:194,t:"sort",d:.65,q:"Classe chaque produit selon sa date habituelle.",bins:["DLC stricte","DDM souple"],it:[["Steak haché",0],["Riz cru en paquet",1],["Yaourt",0],["Café moulu",1],["Poisson frais",0],["Conserve de thon",1]],w:"Frais et périssable : DLC. Sec ou appertisé : DDM. Savoir les distinguer évite le gaspillage sans risque."},
{i:"a194_27",u:194,t:"mcq",d:.65,q:"Pourquoi faut-il remuer un plat à mi-cuisson au micro-ondes ?",o:["Il chauffe de façon inégale","Pour refroidir le centre du plat","Pour garder toutes les vitamines","Pour éviter les étincelles"],a:0,w:"Des zones restent froides, où les bactéries survivent. On remue et on vérifie que c'est fumant partout."},
{i:"a194_28",u:194,t:"story",d:.7,q:"Théo commande souvent en livraison et garde les restes. Quelle règle lui donnes-tu ?",sc:[{who:"Théo",txt:"Je finis le lendemain soir, c'est bon ?"}],o:["« Au frigo dans l'heure, mangé sous 24 à 48 h, réchauffé une fois. »","« Laissez la boîte sur le bureau, le carton garde la chaleur toute la nuit. »","« Tout peut se garder une semaine si c'est très épicé, les épices tuent tout. »","« Mangez-le froid, sans le réchauffer, c'est bien plus sûr pour les restes. »"],a:0,w:"Mêmes règles que pour le riz : froid rapide, courte conservation, un seul réchauffage à cœur. Les épices ne stérilisent pas."},
{i:"a194_29",u:194,t:"tiles",d:.7,q:"Reconstitue la règle du riz cuit.",a:["2","heures","pour","le","frigo","24","heures","pour","le","manger"],dd:["7","jours","table"],w:"Et un seul réchauffage. La toxine de Bacillus cereus résiste à la chaleur : c'est la prévention qui protège."},
{i:"a194_30",u:194,t:"tf",d:.75,q:"Selon les connaissances actuelles, le moment le plus dangereux pour le riz cuit est le refroidissement lent à température ambiante.",a:true,w:"C'est là que les spores germent et que la toxine se forme. Le frigo ralentit fortement le processus sans l'arrêter complètement."},
{i:"a194_31",u:194,t:"match",d:.75,q:"Associe chaque idée reçue à sa correction.",p:[["Le frigo tue les bactéries","Il les endort"],["Le micro-ondes stérilise","Il chauffe inégalement"],["Toute date dépassée est dangereuse","Seule la DLC est stricte"],["Réchauffer détruit la toxine du riz","Elle résiste à la chaleur"]],w:"Quatre idées reçues qui causent des intoxications ou du gaspillage."},
{i:"a194_32",u:194,t:"story",d:.8,q:"Synthèse : Théo te demande les 3 règles à coller sur son frigo.",sc:[{who:"Théo",txt:"Trois règles, pas plus, sinon j'oublie."}],o:["« Juste dose ; restes couverts au frigo sous 2 h ; un réchauffage à cœur, en verre. »","« Cuire beaucoup pour gagner du temps ; laisser refroidir la nuit ; réchauffer 30 secondes. »","« Tout garder une semaine ; mélanger cru et cuit ; réchauffer dans la barquette d'origine. »","« Ne jamais manger de restes ; tout jeter après le repas ; ne plus cuisiner de riz. »"],a:0,w:"Simple et complet. Pas besoin d'arrêter le riz : il suffit d'arrêter de le laisser traîner."}
