/*UNIT*/
{id:195,c:"NUTRI",n:"Module 13",t:"Fast-food, livraison et dîner : manger dehors sans tout dérégler",col:"--green",ic:"🍔",guide:`
<h3>Le vendredi de Théo</h3>
<div class="gstory">Vendredi, 22 h 15, dans le studio de Théo à Villeurbanne. Il a commandé sur son téléphone : un burger trois étages, une grande frite, un grand soda. Samedi midi, en sortant de la fac, une « box croustillante » à 6 euros : 600 g de poulet pané, riz, sauce crémeuse. Il montre les photos à Nora, un peu fier : « Je dépense moins qu'au resto ! » Nora ne fait pas la morale. Elle sort une calculatrice.</div>
<h3>Ce qu'il y a dans un menu</h3>
<table><tr><th>Élément</th><th>Calories (ordre de grandeur donné par Laurence Plumey)</th></tr>
<tr><td>Burger haut, plusieurs étages</td><td>500 à 600 kcal</td></tr>
<tr><td>Portion de frites</td><td>environ 300 kcal</td></tr>
<tr><td>Grand soda</td><td>environ 300 kcal</td></tr>
<tr><td><b>Total du menu</b></td><td><b>1 000 à 1 200 kcal</b></td></tr>
<tr><td>Box croustillante de 600 g (poulet pané, riz, sauce), environ 6 €</td><td>près de 1 000 kcal</td></tr></table>
<p>Laurence Plumey estime que les besoins d'un jeune vont de 1 500 à 2 000 kcal : un seul menu en couvre alors environ <b>70 %</b>. Le prix d'un menu a aussi beaucoup augmenté : <b>10 à 14 euros</b> aujourd'hui.</p>
<div class="gtrap">Nuance sur le podcast : 1 500 à 2 000 kcal correspond plutôt aux besoins d'une adolescente ou d'une jeune femme peu active. Un jeune homme actif de 18 à 25 ans a besoin d'environ <b>2 400 à 2 800 kcal</b>. Pour Théo, un menu représente donc plutôt 40 à 50 % de sa journée. Le message tient toujours : c'est un repas très dense, avec peu de fibres et peu de légumes.</div>
<h3>Le problème, ce n'est pas le fast-food, c'est l'habitude</h3>
<p>Laurence Plumey ne diabolise pas : aller au fast-food <b>de temps en temps</b>, pour se faire plaisir, « aucun problème ». Ça croustille, c'est gras, c'est sucré : tout est fait pour plaire. Ce qui la gêne, c'est quand ça devient <b>une cantine</b> ou <b>un modèle</b> : les parents épuisés qui commandent tacos, pizza ou burger tous les soirs grâce à la <b>livraison</b>. À l'hôpital Necker, elle voyait des enfants qui ne mangeaient pas au fast-food tous les jours, mais « façon fast-food » à la maison tous les jours.</p>
<div class="gmnemo"><b>« Plaisir oui, cantine non. »</b> Et au comptoir, la règle <b>« 1 petit, 1 vert, 1 eau »</b> : un burger simple, une salade ou des légumes à la place d'une partie des frites, et de l'eau.</div>
<h3>À quelle heure dîner</h3>
<p>Pour un adulte qui se lève à 7 h et veut dormir 8 heures, le coucher est à 23 h ; il faut environ <b>2 heures</b> de digestion, donc un dîner vers <b>20 h</b>. Deux pièges :</p>
<ul><li><b>Trop tard</b> (21 h 30, 22 h) : la digestion retarde l'endormissement (le cerveau envoie le signal du sommeil vers 22 h 30) et le sommeil est de mauvaise qualité. La grosse raclette du soir donne une « nuit cata ». Mauvais sommeil, prise de poids (module 3).</li>
<li><b>Trop tôt</b> (19 h pour un adulte qui se couche à 23 h) : l'intestin se vide, le cerveau envoie un signal de faim, et on <b>grignote</b> biscuits ou chocolat devant la télé.</li></ul>
<p>Si on dîne tôt avec les enfants, on prévoit une petite collation calculée (un yaourt, un fruit) plutôt que de grignoter au hasard.</p>
<h3>Les gènes et la coriandre</h3>
<p>Certaines personnes trouvent à la coriandre un <b>goût de savon</b>. C'est en partie <b>génétique</b> : une variante d'un gène du récepteur olfactif (OR6A2) rend très sensible à ses aldéhydes. Selon les populations, 4 à 21 % des gens sont concernés. Laurence Plumey en tire une leçon plus large : nos comportements alimentaires sont en partie guidés par nos gènes et notre cerveau, un <b>« inconscient métabolique »</b>. On maîtrise moins qu'on croit : raison de plus pour ne pas culpabiliser, et pour organiser son environnement.</p>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Chiffrer un menu fast-food et le comparer aux besoins</li><li>Aider un patient à commander mieux sans interdire</li><li>Fixer une heure de dîner adaptée à l'heure de coucher</li><li>Expliquer pourquoi dîner trop tôt peut aussi faire grignoter</li></ul>`},
/*EXOS*/
{i:"a195_01",u:195,t:"num",d:.2,nw:"Le menu fast-food",q:"Burger 550 kcal, frites 300 kcal, soda 300 kcal : combien de kcal dans le menu de Théo ?",a:1150,tol:0,un:" kcal",h:"550 + 300 + 300",w:"1 150 kcal, dans la fourchette de 1 000 à 1 200 donnée par Laurence Plumey. Un seul repas, très dense et presque sans fibres."},
{i:"a195_02",u:195,t:"story",d:.2,q:"Théo s'attend à ce que tu lui interdises le fast-food. Que lui dis-tu ?",sc:[{who:"Théo",txt:"Allez-y, dites-moi que c'est interdit."}],o:["« De temps en temps pour le plaisir, aucun souci ; le souci, c'est l'habitude. »","« C'est interdit, plus jamais de fast-food jusqu'à la fin de votre suivi. »","« Aucun problème, même tous les jours, du moment que vous faites du sport. »","« Prenez le fast-food uniquement au petit-déjeuner, il est alors mieux digéré. »"],a:0,w:"Plaisir oui, cantine non. Interdire provoque souvent l'effet inverse ; on travaille sur la fréquence et les choix."},
{i:"a195_03",u:195,t:"slider",d:.25,q:"Combien d'heures de digestion prévoir entre le dîner et le coucher d'un adulte ?",min:0,max:5,step:.5,a:2,tol:0,pre:"",un:" h",w:"Environ 2 heures. Coucher à 23 h, dîner vers 20 h : l'heure « traditionnelle » est la bonne selon Laurence Plumey."},
{i:"a195_04",u:195,t:"tf",d:.25,q:"Dîner trop tôt peut aussi favoriser le grignotage.",a:true,w:"Dîner à 19 h et veiller jusqu'à 23 h : l'intestin se vide, le cerveau envoie un signal de faim, et on grignote. Ni trop tôt, ni trop tard."},
{i:"a195_05",u:195,t:"fill",d:.25,q:"Laurence Plumey regrette que le fast-food devienne une ___ pour certaines familles.",o:["cantine","récompense","exception","sortie"],a:0,w:"Plaisir oui, cantine non. Avec la livraison, le fast-food entre dans le quotidien des familles fatiguées."},
{i:"a195_06",u:195,t:"match",d:.3,q:"Associe chaque élément du menu à ses calories approximatives.",p:[["Burger haut","500 à 600 kcal"],["Portion de frites","Environ 300 kcal"],["Grand soda","Environ 300 kcal"],["Box croustillante de 600 g","Près de 1 000 kcal"]],w:"Les chiffres du podcast. Additionnés, ils expliquent pourquoi un menu couvre une grande part de la journée."},
{i:"a195_07",u:195,t:"story",d:.3,q:"Au comptoir, Théo veut manger « un peu mieux » sans renoncer. Que proposes-tu ?",sc:[{who:"Théo",txt:"Je suis devant la borne, je prends quoi ?"}],o:["« Un burger simple, une salade ou petite frite, et de l'eau à la place du soda. »","« Deux burgers sans frites, comme ça vous évitez complètement le gras des frites. »","« Le plus grand menu, mais en mangeant très lentement pour mieux digérer. »","« Juste un grand soda et une glace, c'est moins lourd qu'un burger complet. »"],a:0,w:"1 petit, 1 vert, 1 eau. Le soda seul retire environ 300 kcal. On garde le plaisir, on enlève le superflu."},
{i:"a195_08",u:195,t:"mcq",d:.3,q:"Selon Laurence Plumey, quelle part du besoin d'un jeune couvre un menu fast-food ?",o:["Environ 70 %","Environ 10 %","Environ 30 %","Plus de 150 %"],a:0,w:"1 000 à 1 200 kcal pour un besoin estimé à 1 500 à 2 000. Pour un jeune homme actif (2 400 à 2 800), c'est plutôt 40 à 50 %."},
{i:"a195_09",u:195,t:"order",d:.35,q:"Remets dans l'ordre la chaîne du dîner trop tardif.",it:["Dîner à 22 h","Digestion en cours à l'heure du coucher","Endormissement retardé","Sommeil de mauvaise qualité","Fatigue et faim le lendemain"],w:"Le cerveau envoie le signal du sommeil vers 22 h 30 ; s'il gère la digestion, il le retarde. Mauvais sommeil, prise de poids."},
{i:"a195_10",u:195,t:"num",d:.35,q:"Théo se lève à 7 h et veut dormir 8 h, avec 2 h de digestion. À quelle heure doit-il dîner au plus tard ?",a:21,tol:0,un:" h",h:"7 h − 8 h = 23 h, puis − 2 h",w:"Coucher à 23 h, dîner au plus tard à 21 h, idéalement vers 20 h. Le même calcul que pour Léna, avec 8 heures au lieu de 11."},
{i:"a195_11",u:195,t:"sort",d:.35,q:"Classe chaque habitude : plaisir occasionnel ou modèle problématique ?",bins:["Plaisir occasionnel","Modèle problématique"],it:[["Fast-food un samedi par mois entre amis",0],["Livraison de pizza tous les soirs",1],["Burger après un match de temps en temps",0],["Tacos commandés 5 fois par semaine",1]],w:"La fréquence fait la différence. Laurence Plumey n'est gênée que quand ça devient une cantine."},
{i:"a195_12",u:195,t:"story",d:.4,q:"Paul dîne à 19 h avec ses enfants et grignote à 23 h devant la télé. Que proposes-tu ?",sc:[{who:"Paul",txt:"À 23 h, j'ai faim, c'est plus fort que moi."}],o:["« Gardez le dîner en famille et prévoyez une petite collation vers 21 h 30. »","« Dînez une seconde fois à 22 h, un vrai repas complet pour tenir la nuit. »","« Ne dînez plus avec vos enfants, mangez seul à 22 h 30, c'est la solution. »","« Buvez un grand soda à 23 h, le sucre coupe la faim sans calories. »"],a:0,w:"Intestin vide = signal de faim. Une collation calculée (yaourt, fruit) remplace le grignotage au hasard, et on garde le repas familial."},
{i:"a195_13",u:195,t:"tiles",d:.4,q:"Reconstitue la règle du comptoir.",a:["1","petit","1","vert","1","eau"],dd:["grand","soda","XL"],w:"Un burger simple, une salade ou des légumes, de l'eau. Plaisir oui, cantine non."},
{i:"a195_14",u:195,t:"fill",d:.4,q:"Chez certaines personnes, la coriandre a un goût de ___.",o:["savon","fraise","fumée","miel"],a:0,w:"De savon, à cause d'une variante génétique d'un récepteur olfactif très sensible à ses aldéhydes."},
{i:"a195_15",u:195,t:"mcq",d:.45,q:"Combien coûte une « box croustillante » de 600 g selon le podcast ?",o:["Environ 6 €","Environ 1 €","Environ 25 €","Environ 50 €"],a:0,w:"Environ 6 € pour près de 1 000 kcal : moins cher qu'un menu burger (10 à 14 €), mais tout aussi dense et pauvre en légumes."},
{i:"a195_16",u:195,t:"tf",d:.45,q:"Selon Laurence Plumey, un enfant pourrait manger la même chose qu'un adulte au restaurant, en plus petite quantité.",a:true,w:"Elle regrette que les menus enfants soient toujours « steak haché, frites, glace » : les fast-foods ont occupé ce vide."},
{i:"a195_17",u:195,t:"story",d:.45,q:"Rappel du module 3 : Mehdi, de nuit, commande souvent en livraison à 3 h du matin. Que proposes-tu ?",sc:[{who:"Mehdi",txt:"À 3 h, il n'y a que ça qui est ouvert."}],o:["« Préparez une boîte repas avant la garde : légumes, féculent, protéines. »","« Continuez, la livraison de nuit est adaptée aux horaires décalés. »","« Ne mangez rien de toute la nuit, jeûner compense le manque de sommeil. »","« Buvez trois boissons énergisantes à la place, elles calent bien plus. »"],a:0,w:"Le travailleur de nuit est déjà exposé au surpoids. Anticiper son repas évite l'offre de nuit, grasse et sucrée. Environ 15 % des salariés font du travail de nuit en France."},
{i:"a195_18",u:195,t:"multi",d:.5,q:"Pourquoi le fast-food plaît-il tant aux jeunes, selon Laurence Plumey ?",o:["Ça croustille","C'est gras","C'est sucré","C'est rapide et proche","C'est riche en légumes"],a:[0,1,2,3],w:"« Il y a tout pour plaire. » Comprendre ce plaisir aide à proposer des alternatives qui le respectent."},
{i:"a195_19",u:195,t:"num",d:.5,q:"Théo remplace son grand soda (300 kcal) par de l'eau à chacun de ses 3 menus hebdomadaires. Combien de kcal économise-t-il par mois (4 semaines) ?",a:3600,tol:0,un:" kcal",h:"300 × 3 × 4",w:"3 600 kcal par mois, près d'un demi-kilo de graisse (7 700 kcal par kg), sans rien changer d'autre."},
{i:"a195_20",u:195,t:"match",d:.5,q:"Associe chaque situation au bon conseil.",p:[["Dîner à 22 h 30","Avancer le repas ou alléger"],["Dîner à 19 h, coucher à 23 h","Prévoir une collation"],["Livraison tous les soirs","Préparer des repas à l'avance"],["Menu XL avec soda","1 petit, 1 vert, 1 eau"]],w:"Chaque situation a son levier : l'heure, l'anticipation ou le choix au comptoir."},
{i:"a195_21",u:195,t:"story",d:.55,q:"Rappel du module 5 : les Martin, épuisés, commandent des pizzas trois soirs par semaine. Que proposes-tu ?",sc:[{who:"Mme Martin",txt:"On rentre à 19 h 30, on n'a plus la force de cuisiner."}],o:["« Cuisinez en double le dimanche et congelez : le soir, il n'y a qu'à réchauffer. »","« Continuez les pizzas, les enfants grandissent et brûlent tout ce qu'ils mangent. »","« Faites sauter le dîner des enfants ces soirs-là, ils mangeront mieux le lendemain. »","« Remplacez la pizza par des tacos, qui sont nettement moins caloriques. »"],a:0,w:"La livraison répond à la fatigue, pas à la faim. Le batch cooking du week-end répond au même besoin, en mieux."},
{i:"a195_22",u:195,t:"tf",d:.55,q:"D'après les besoins de l'Anses, un jeune homme actif de 20 ans a besoin de 1 500 kcal par jour.",a:false,w:"Plutôt 2 400 à 2 800 kcal. Le chiffre de 1 500 à 2 000 du podcast correspond davantage à une adolescente ou une jeune femme peu active."},
{i:"a195_23",u:195,t:"mcq",d:.55,q:"Qu'appelle Laurence Plumey « l'inconscient métabolique » ?",o:["Nos choix guidés par nos gènes et notre cerveau","Un trouble du sommeil lié à un dîner tardif","Une hormone fabriquée par le tissu adipeux","Une perte de connaissance après un repas"],a:0,w:"On croit tout maîtriser, mais nos gènes et notre cerveau orientent beaucoup nos goûts et nos choix : raison de plus pour ne pas culpabiliser. Exemple : la coriandre, qui a un goût de savon pour certains à cause d'un gène."},
{i:"a195_24",u:195,t:"sort",d:.6,q:"Classe chaque heure de dîner pour un adulte qui se couche à 23 h.",bins:["Bonne heure","Trop tôt","Trop tard"],it:[["20 h",0],["19 h sans collation",1],["22 h 30",2],["20 h 30",0],["18 h",1],["22 h",2]],w:"Vers 20 h, 2 heures avant le coucher. Trop tôt : faim tardive ; trop tard : sommeil perturbé."},
{i:"a195_25",u:195,t:"story",d:.6,q:"Paul organise une grosse raclette un mardi soir à 21 h. Que lui dis-tu ?",sc:[{who:"Paul",txt:"C'est l'hiver, on se fait plaisir."}],o:["« Plutôt le week-end, plus tôt, avec une salade : sinon, nuit mauvaise. »","« Aucun effet sur le sommeil, un repas lourd aide même à s'endormir vite. »","« Faites-la à minuit pour que la digestion se fasse pendant le sommeil. »","« Supprimez définitivement toute raclette, c'est le plat le plus dangereux. »"],a:0,w:"« Grosse raclette, nuit cata. » On garde le plaisir, on déplace le moment et on allège."},
{i:"a195_26",u:195,t:"fill",d:.6,q:"Vers 22 h 30, le cerveau envoie le signal du ___.",o:["sommeil","réveil","repas","stress"],a:0,w:"« Le rideau qui se baisse. » Si la digestion l'occupe, il retarde ce signal et on se couche plus tard."},
{i:"a195_27",u:195,t:"multi",d:.65,q:"Quelles astuces permettent de mieux manger quand on est fatigué le soir ?",o:["Cuisiner en double le week-end","Garder des légumes surgelés","Avoir des œufs et des conserves de poisson","Préparer une salade composée d'avance","Commander dès qu'on se sent fatigué"],a:[0,1,2,3],w:"Anticiper, c'est ce qui bat la livraison. Les surgelés nature et les œufs sont les alliés des soirs sans énergie."},
{i:"a195_28",u:195,t:"num",d:.7,q:"Un jeune homme a besoin de 2 500 kcal. Quel pourcentage représente un menu de 1 100 kcal ?",a:44,tol:1,un:" %",h:"1 100 / 2 500 × 100",w:"44 %, presque la moitié de la journée en un repas pauvre en légumes et en fibres."},
{i:"a195_29",u:195,t:"story",d:.7,q:"Chloé déteste la coriandre et son compagnon l'adore. Elle se demande si elle est « difficile ».",sc:[{who:"Chloé",txt:"Pour moi ça a un goût de savon, il se moque de moi."}],o:["« C'est en partie génétique : vous ne sentez pas la même chose que lui. »","« Vous êtes difficile, forcez-vous et vous aimerez en quelques jours. »","« C'est une allergie grave, il faut consulter un allergologue en urgence. »","« C'est psychologique, la coriandre a exactement le même goût pour tous. »"],a:0,w:"Une variante du gène OR6A2 rend certaines personnes très sensibles aux aldéhydes de la coriandre. Chacun son palais, sans jugement. Laurence Plumey parle d'inconscient métabolique : nos gènes orientent une partie de nos goûts."},
{i:"a195_30",u:195,t:"tiles",d:.75,q:"Reconstitue la phrase de synthèse de Laurence Plumey sur le fast-food.",a:["plaisir","oui","cantine","non"],dd:["jamais","toujours","interdit"],w:"Ce n'est pas le fast-food qui pose problème, c'est l'habitude qui en fait un modèle."},
{i:"a195_31",u:195,t:"mcq",d:.75,q:"Combien coûte aujourd'hui un menu burger selon le podcast ?",o:["10 à 14 €","2 à 3 €","25 à 30 €","50 €"],a:0,w:"10 à 14 €, bien plus qu'avant. Bien manger à la maison est souvent moins cher : un argument concret pour un étudiant."},
{i:"a195_32",u:195,t:"story",d:.8,q:"Synthèse : quel plan donnes-tu à Théo pour ses repas du week-end ?",sc:[{who:"Théo",txt:"Un truc simple que je peux vraiment tenir."}],o:["« Un fast-food par semaine en 1 petit, 1 vert, 1 eau, et le reste cuisiné d'avance. »","« Plus aucun fast-food, et un jeûne le lundi pour compenser les écarts du week-end. »","« Tous les repas en livraison, mais uniquement des pizzas végétariennes. »","« Deux menus XL le samedi, et rien du tout le dimanche pour équilibrer. »"],a:0,w:"Plaisir oui, cantine non : une fois par semaine avec des choix malins, et de l'anticipation pour le reste. Pas de compensation par le jeûne."}
