/*UNIT*/
{id:196,c:"NUTRI",n:"Module 14",t:"Fertilité et vie de couple : le poids se joue à deux",col:"--green",ic:"💑",guide:`
<h3>Inès et Karim</h3>
<div class="gstory">Inès, 31 ans, revient voir Nora, cette fois avec son compagnon Karim, 34 ans. Ils essaient d'avoir un bébé depuis quatorze mois. Karim a pris 12 kg depuis leur mariage : restaurants, apéros du vendredi, desserts partagés « pour se faire plaisir ». Il fume encore quelques cigarettes et travaille avec son ordinateur portable posé sur les cuisses. « On cherche l'aliment miracle pour la fertilité », dit Inès. Nora secoue la tête : « Il n'y en a pas. Mais il y a beaucoup de choses à faire, et à deux. »</div>
<h3>La fertilité masculine en chute</h3>
<p>On pense souvent que l'infertilité est un problème de femme. C'est faux : les hommes sont concernés dans environ la moitié des cas. La concentration des spermatozoïdes a fortement baissé dans les pays occidentaux.</p>
<div class="gtrap">Précision sur le podcast : Laurence Plumey dit « de 100 à 50 millions par millilitre en 30 ans ». Voici les données vérifiées. La grande méta-analyse de Levine (2017) trouve une baisse d'environ <b>52 %</b> de la concentration entre 1973 et 2011 dans les pays occidentaux. En France, l'étude de Santé publique France (Rolland, 2013) montre une baisse d'environ <b>32 %</b> en 17 ans, d'environ 74 à 50 millions par ml. L'ordre de grandeur « divisé par deux » est donc juste à l'échelle mondiale sur 40 ans.</div>
<p>Les spermatozoïdes sont « fatigués » par : le <b>surpoids</b> et l'inflammation qu'il entraîne, le <b>tabac</b>, l'<b>alcool</b>, les <b>perturbateurs endocriniens</b> et la <b>chaleur</b>. Les testicules sont à l'extérieur du corps car ils fonctionnent mieux autour de <b>35 °C</b>, deux degrés de moins que les 37 °C du corps. Ordinateur sur les cuisses, bains très chauds, sous-vêtements serrés, canicules : tout ce qui les chauffe les pénalise. Un spermatozoïde met environ <b>74 jours</b> à se fabriquer : les efforts se voient au bout de <b>trois mois</b>.</p>
<h3>Les perturbateurs endocriniens</h3>
<p>Ce sont des substances qui imitent ou bloquent nos hormones : <b>bisphénols</b>, <b>phtalates</b> (certains plastiques), <b>parabènes</b> (cosmétiques), certains <b>pesticides</b>, les <b>PFAS</b>. Gestes simples : ne pas chauffer d'aliments dans du plastique (module 12), préférer le verre et l'inox (module 9), laver fruits et légumes, aérer son logement.</p>
<h3>Manger pour la fertilité : pas d'aliment miracle</h3>
<p>Laurence Plumey compare le corps à un <b>jardin</b> : pour que la graine pousse, il faut une terre de bonne qualité. Donc : manger <b>équilibré et un peu de tout</b>, <b>sans carence</b>, <b>ne pas sauter de repas</b>, <b>pas de régime d'exclusion</b> (sans viande, sans laitages, sans gluten sans raison médicale), bien dormir (la testostérone a un pic vers 5 h du matin et suit un cycle de 24 heures), bien bouger. Et ce qui manque le plus : <b>les légumes</b>, à midi et le soir.</p>
<table><tr><th>Moment</th><th>Journée type proposée par Laurence Plumey</th></tr>
<tr><td>Petit-déjeuner</td><td>Pain ou flocons d'avoine, un laitage, un fruit</td></tr>
<tr><td>Déjeuner</td><td>De la viande, du poisson ou des œufs. Une assiette avec moitié légumes et moitié féculents. Un fromage ou un laitage, puis un fruit.</td></tr>
<tr><td>Goûter</td><td>Un fruit et quelques amandes</td></tr>
<tr><td>Dîner</td><td>Viande, poisson ou œufs (légumes secs pour les végétariens), légumes, fruit</td></tr></table>
<p>À ajouter, conseil officiel : l'<b>acide folique</b> (vitamine B9), 400 microgrammes par jour chez la femme <b>dès le projet de grossesse</b>, au moins un mois avant, pour réduire le risque de malformation du tube neural du bébé. Et <b>zéro alcool, zéro tabac</b>, pour les deux.</p>
<div class="gmnemo"><b>« Terre saine, graine pleine : Dormir, Bouger, Manger de tout, et au frais. »</b> Et pour les ennemis du spermatozoïde, <b>« les 5 C : Chaleur, Cigarette, Cuite, Corpulence, Chimie »</b>.</div>
<h3>Le mariage fait grossir</h3>
<p>Laurence Plumey voit beaucoup de patients qui prennent du poids après s'être mis en couple : on est dans l'<b>émotionnel</b>, on veut faire plaisir, on sort au restaurant, on partage le dessert et le verre de vin. Et il y a l'<b>imprégnation</b> : on adopte les habitudes de l'autre. L'idéal : entraîner l'autre vers les bons comportements, et faire au moins une chose à deux : <b>le sport en couple</b>.</p>
<p>Son cas célèbre : un homme prend <b>20 kg</b> dans l'année qui suit son mariage. Le problème n'était pas alimentaire : avec le bébé, il allait chercher l'enfant à la <b>crèche</b> le soir et avait arrêté ses séances de sport. La solution n'était pas un régime, mais une réorganisation : deux soirs par semaine, sa femme récupère l'enfant et lui le dépose le matin. <b>Comprendre le problème avant de prescrire</b> : c'est l'esprit de la napsothérapie (module 15).</p>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Expliquer la baisse de la fertilité masculine et ses causes</li><li>Donner une journée alimentaire type pour un projet de bébé</li><li>Repérer les perturbateurs endocriniens du quotidien</li><li>Trouver la vraie cause d'une prise de poids avant de parler de régime</li></ul>`},
/*EXOS*/
{i:"a196_01",u:196,t:"story",d:.2,nw:"Pas d'aliment miracle pour la fertilité",q:"Inès cherche « l'aliment miracle ». Que lui réponds-tu ?",sc:[{who:"Inès",txt:"Il y a bien un aliment qui aide à tomber enceinte ?"}],o:["« Aucun aliment miracle : manger de tout, sans carence, bien dormir, à deux. »","« Oui, les huîtres : trois douzaines par semaine et la grossesse arrive vite. »","« Faites un régime sans gluten, c'est ce qui aide le plus à concevoir. »","« Sautez le dîner chaque soir pour perdre du poids avant la grossesse. »"],a:0,w:"Terre saine, graine pleine. Pas d'aliment miracle, pas de régime d'exclusion, pas de repas sauté : un corps sans carence et reposé."},
{i:"a196_02",u:196,t:"slider",d:.2,q:"À quelle température les testicules fonctionnent-ils le mieux (en °C) ?",min:30,max:40,step:1,a:35,tol:0,pre:"",un:" °C",w:"Environ 35 °C, deux degrés de moins que le corps. C'est pour ça qu'ils sont à l'extérieur, et que la chaleur les pénalise."},
{i:"a196_03",u:196,t:"multi",d:.25,q:"Qu'est-ce qui « fatigue » les spermatozoïdes selon Laurence Plumey ?",o:["Le surpoids","Le tabac","L'alcool","La chaleur","Les légumes verts"],a:[0,1,2,3],w:"Les 5 C : Chaleur, Cigarette, Cuite, Corpulence, Chimie (perturbateurs endocriniens). Les légumes, eux, aident. Les testicules fonctionnent mieux vers 35 °C."},
{i:"a196_04",u:196,t:"fill",d:.25,q:"Les substances qui imitent ou bloquent nos hormones s'appellent les perturbateurs ___.",o:["endocriniens","digestifs","neurologiques","sanguins"],a:0,w:"Endocriniens (qui touchent les glandes à hormones). Bisphénols, phtalates, parabènes, certains pesticides, PFAS."},
{i:"a196_05",u:196,t:"tf",d:.25,q:"L'infertilité d'un couple vient presque toujours de la femme.",a:false,w:"Les hommes sont concernés dans environ la moitié des cas. D'où l'intérêt de faire le travail à deux."},
{i:"a196_06",u:196,t:"story",d:.3,q:"Karim travaille avec son ordinateur portable sur les cuisses. Que lui dis-tu ?",sc:[{who:"Karim",txt:"C'est pratique, je bosse dans le canapé."}],o:["« Posez-le sur une table : la chaleur freine la fabrication des spermatozoïdes. »","« Aucun effet, seules les ondes du téléphone posent un problème réel. »","« Continuez, un peu de chaleur stimule plutôt bien les spermatozoïdes. »","« Mettez une bouillotte à la place, c'est plus confortable pour travailler. »"],a:0,w:"Les testicules aiment 35 °C. Ordinateur sur les cuisses, bains très chauds, sous-vêtements serrés : autant de sources de chaleur à éviter."},
{i:"a196_07",u:196,t:"num",d:.3,q:"En France, la concentration est passée d'environ 74 à 50 millions par ml. Quelle baisse en pourcentage (arrondie) ?",a:32,tol:1,un:" %",h:"(74 − 50) / 74 × 100",w:"Environ 32 % en 17 ans (Rolland, 2013). La méta-analyse mondiale de Levine (2017) trouve environ 52 % en 40 ans."},
{i:"a196_08",u:196,t:"match",d:.3,q:"Associe chaque repas à la proposition de Laurence Plumey.",p:[["Petit-déjeuner","Pain ou avoine, laitage, fruit"],["Déjeuner","Protéine, moitié légumes moitié féculents"],["Goûter","Fruit et amandes"],["Dîner","Protéine, légumes, fruit"]],w:"Une journée sans carence, sans repas sauté, avec des légumes midi et soir."},
{i:"a196_09",u:196,t:"mcq",d:.35,q:"Combien de temps faut-il pour fabriquer un spermatozoïde ?",o:["Environ 74 jours","Environ 24 heures","Environ 7 jours","Environ 2 ans"],a:0,w:"Environ 74 jours : les changements d'hygiène de vie se voient au bout d'environ trois mois. Il faut prévenir le couple pour éviter le découragement."},
{i:"a196_10",u:196,t:"tiles",d:.35,q:"Reconstitue les 5 C, ennemis du spermatozoïde.",a:["Chaleur","Cigarette","Cuite","Corpulence","Chimie"],dd:["Carottes","Course"],w:"Chaleur, Cigarette, Cuite (alcool), Corpulence (surpoids), Chimie (perturbateurs endocriniens)."},
{i:"a196_11",u:196,t:"story",d:.35,q:"Karim ne comprend pas pourquoi il a pris 12 kg depuis le mariage. Que lui expliques-tu ?",sc:[{who:"Karim",txt:"Je mange pareil qu'avant, je vous assure."}],o:["« Le couple change les habitudes : restos, apéros, desserts, moins de sport. »","« C'est l'âge, à 34 ans le métabolisme s'effondre, vous n'y pouvez rien. »","« Le mariage modifie les gènes, c'est prouvé, le poids est donc inévitable. »","« C'est de l'eau, ça partira tout seul en arrêtant de boire le soir, voilà. »"],a:0,w:"L'émotionnel, l'envie de faire plaisir et l'imprégnation des habitudes de l'autre. La solution est à deux : entraîner l'autre vers le bon, et le sport en couple."},
{i:"a196_12",u:196,t:"sort",d:.4,q:"Classe chaque produit : source possible de perturbateurs endocriniens ou non ?",bins:["Source possible","Pas en cause"],it:[["Barquette plastique chauffée",0],["Cosmétique avec parabènes",0],["Poêle en inox",1],["Fruits non lavés traités aux pesticides",0],["Plat en verre",1],["Emballages traités aux PFAS",0]],w:"Verre et inox sont les alliés. On chauffe hors plastique, on lit les étiquettes des cosmétiques, on lave les fruits."},
{i:"a196_13",u:196,t:"fill",d:.4,q:"Dès le projet de grossesse, la femme prend 400 microgrammes par jour d'acide ___.",o:["folique","citrique","lactique","urique"],a:0,w:"L'acide folique (vitamine B9), au moins un mois avant la conception, réduit le risque de malformation du tube neural. Conseil officiel à ajouter au podcast."},
{i:"a196_14",u:196,t:"tf",d:.4,q:"Selon Laurence Plumey, un régime sans gluten sans raison médicale peut aider à tomber enceinte.",a:false,w:"Au contraire : « surtout pas, ce n'est pas le moment ». On mange de tout pour éviter les carences."},
{i:"a196_15",u:196,t:"order",d:.45,q:"Remets dans l'ordre l'histoire du patient qui a pris 20 kg.",it:["Il se marie","Un bébé arrive","Il va chercher l'enfant à la crèche le soir","Il arrête ses séances de sport","Il prend 20 kg en un an"],w:"Le problème n'était pas alimentaire. Un régime aurait échoué : il fallait retrouver le sport."},
{i:"a196_16",u:196,t:"story",d:.45,q:"Quelle solution propose Laurence Plumey à ce patient ?",sc:[{who:"Le patient",txt:"Depuis la crèche, je n'ai plus le temps d'aller à la salle."}],o:["« Deux soirs par semaine, votre femme récupère l'enfant ; vous, le matin. »","« Un régime à 1 200 kcal, c'est la seule façon de perdre ces 20 kg vite. »","« Mettez votre enfant en crèche plus tard, jusqu'à 20 h, tous les jours. »","« Allez à la salle à 23 h, après le coucher de toute la famille, chaque soir. »"],a:0,w:"Comprendre le problème avant de prescrire : l'inversion des trajets libère deux séances de sport par semaine."},
{i:"a196_17",u:196,t:"mcq",d:.45,q:"Quelle image Laurence Plumey utilise-t-elle pour parler de fertilité ?",o:["Le jardinier et la terre","Le moteur et son essence","La banque et l'épargne","Le pompier et son feu"],a:0,w:"Pour que la graine pousse, il faut une terre de bonne qualité : un corps sans carence, reposé, serein."},
{i:"a196_18",u:196,t:"num",d:.5,q:"Karim change ses habitudes le 1er mars. Au bout de combien de jours environ un nouveau cycle complet de spermatozoïdes sera-t-il produit ?",a:74,tol:2,un:" jours",h:"Durée de fabrication d'un spermatozoïde",w:"Environ 74 jours, soit mi-mai. On prévient le couple : les effets se mesurent après trois mois."},
{i:"a196_19",u:196,t:"match",d:.5,q:"Associe chaque geste au perturbateur ou au risque qu'il limite.",p:[["Chauffer dans du verre","Bisphénols et phtalates"],["Lire la liste des cosmétiques","Parabènes"],["Laver fruits et légumes","Résidus de pesticides"],["Remplacer une poêle rayée","PFAS"]],w:"Des gestes simples, sans panique, qui réduisent l'exposition au quotidien."},
{i:"a196_20",u:196,t:"story",d:.5,q:"Rappel du module 8 : Karim demande si « un verre ou deux » gêne le projet bébé.",sc:[{who:"Karim",txt:"Inès ne boit plus, mais moi je peux, non ?"}],o:["« L'alcool fatigue aussi les spermatozoïdes : on réduit fort, à deux. »","« Aucun effet chez l'homme, seul l'alcool de la femme compte pour le bébé. »","« Buvez plutôt du vin rouge, ses polyphénols améliorent la fertilité. »","« Doublez les apéros, l'alcool détend et favorise les rapports. »"],a:0,w:"L'alcool est l'un des 5 C. Solidarité et biologie vont dans le même sens : on réduit ensemble. Un spermatozoïde met environ 74 jours à se fabriquer : les efforts se voient après trois mois."},
{i:"a196_21",u:196,t:"tf",d:.55,q:"La testostérone suit un cycle de 24 heures, avec un pic en fin de nuit.",a:true,w:"Pic vers 5 h du matin selon Laurence Plumey. C'est une des raisons pour lesquelles le sommeil compte pour la fertilité."},
{i:"a196_22",u:196,t:"multi",d:.55,q:"Quelles règles alimentaires pour un couple qui veut un enfant ?",o:["Manger un peu de tout","Ne pas sauter de repas","Des légumes midi et soir","Zéro alcool et zéro tabac","Un régime sans laitages"],a:[0,1,2,3],w:"Pas de régime d'exclusion. On ajoute l'acide folique chez la femme, dès le projet."},
{i:"a196_23",u:196,t:"fill",d:.55,q:"Le fait d'adopter peu à peu les habitudes alimentaires de son conjoint s'appelle l'___.",o:["imprégnation","inflammation","hydratation","inhibition"],a:0,w:"L'imprégnation. D'où le conseil : entraîner l'autre vers les bons comportements plutôt que de suivre les mauvais."},
{i:"a196_24",u:196,t:"story",d:.6,q:"Rappel du module 13 : Inès et Karim commandent des pizzas trois soirs par semaine. Quel plan à deux proposes-tu ?",sc:[{who:"Inès",txt:"On rentre crevés tous les deux."}],o:["« Cuisinez ensemble le dimanche, gardez une soirée pizza par semaine. »","« Chacun mange séparément, comme ça personne n'influence l'autre. »","« Supprimez le dîner, deux repas par jour suffisent pour faire un bébé. »","« Passez aux tacos, ils sont plus riches en protéines que les pizzas. »"],a:0,w:"Plaisir oui, cantine non, et à deux : l'imprégnation joue alors dans le bon sens."},
{i:"a196_25",u:196,t:"mcq",d:.6,q:"Quelle baisse de concentration des spermatozoïdes la méta-analyse de Levine (2017) a-t-elle trouvée ?",o:["Environ 52 %","Environ 5 %","Environ 90 %","Aucune baisse"],a:0,w:"Environ 52 % entre 1973 et 2011 dans les pays occidentaux. Le « divisé par deux » du podcast est un bon ordre de grandeur."},
{i:"a196_26",u:196,t:"sort",d:.65,q:"Classe chaque idée : conseil de Laurence Plumey ou idée reçue ?",bins:["Conseil","Idée reçue"],it:[["Faire du sport en couple",0],["Les huîtres rendent fertile",1],["Ne pas sauter de repas",0],["L'infertilité est un problème de femme",1],["Des légumes à chaque repas",0]],w:"Comportements plutôt qu'aliments miracles, et un travail à deux."},
{i:"a196_27",u:196,t:"num",d:.65,q:"Karim fume 8 cigarettes par jour. S'il réduit de moitié chaque mois, combien en fumera-t-il après 3 mois ?",a:1,tol:0,un:" cigarette",h:"8 / 2 / 2 / 2",w:"1 cigarette, puis zéro. Le tabac est l'un des 5 C ; une réduction progressive, accompagnée (tabacologue, 39 89), marche mieux qu'un arrêt brutal non préparé."},
{i:"a196_28",u:196,t:"story",d:.7,q:"Inès culpabilise : « si on n'y arrive pas, c'est à cause de mes kilos ». Que lui dis-tu ?",sc:[{who:"Inès",txt:"Je me sens responsable de tout."}],o:["« La fertilité se joue à deux, avec bien des facteurs : on agit ensemble, sans culpabiliser. »","« Oui, c'est entièrement votre faute, il faut perdre dix kilos avant tout. »","« Le poids n'a strictement aucun lien avec la fertilité, ni pour vous ni pour lui. »","« Arrêtez d'essayer, le stress est de toute façon bien trop élevé chez vous deux. »"],a:0,w:"Rassurer, partager la responsabilité, agir sur ce qui se modifie. Après 12 mois d'essais, un bilan médical des deux partenaires est conseillé."},
{i:"a196_29",u:196,t:"tiles",d:.7,q:"Reconstitue la règle d'or de la consultation selon Laurence Plumey.",a:["comprendre","le","problème","avant","de","prescrire"],dd:["régime","toujours","peser"],w:"Le patient aux 20 kg n'avait pas un problème alimentaire : il avait perdu son sport. Un régime aurait échoué."},
{i:"a196_30",u:196,t:"mcq",d:.75,q:"Après combien de mois d'essais sans grossesse parle-t-on d'infertilité et consulte-t-on ?",o:["12 mois","1 mois","3 semaines","5 ans"],a:0,w:"Après 12 mois de rapports réguliers sans contraception (6 mois si la femme a plus de 35 ans). Inès et Karim en sont à 14 : bilan des deux."},
{i:"a196_31",u:196,t:"tf",d:.75,q:"Faire du sport en couple est l'un des conseils de Laurence Plumey pour éviter de grossir à deux.",a:true,w:"Si l'on partage des restos et des desserts, on peut aussi partager le sport. L'imprégnation fonctionne dans les deux sens."},
{i:"a196_32",u:196,t:"story",d:.8,q:"Synthèse : quel plan en 4 points pour Inès et Karim ?",sc:[{who:"Karim",txt:"On veut un plan clair, pour nous deux."}],o:["« De tout avec des légumes, zéro alcool et tabac, sport à deux, pas de chaleur. »","« Un régime sans gluten pour les deux, des huîtres, et un jeûne un jour sur deux. »","« Rien à changer pour Karim, Inès doit perdre 10 kg et prendre des compléments. »","« Arrêter le sport, qui fatigue le corps, et manger beaucoup pour faire des réserves. »"],a:0,w:"Terre saine, graine pleine, et les 5 C évités. Plus l'acide folique pour Inès, et un bilan des deux à 14 mois."}
