/*UNIT*/
{id:197,c:"NUTRI",n:"Module 15",t:"Maigrir pour de bon : régimes, chirurgie, médicaments",col:"--green",ic:"⚖️",guide:`
<h3>Paul et Chloé, même programme, pas le même résultat</h3>
<div class="gstory">Paul et Chloé ont commencé leur suivi chez Nora le même mois. Même programme : plus de soda, des légumes à chaque repas, marche quotidienne, coucher plus tôt. Trois mois plus tard, Paul a perdu 9 kg. Chloé, 3 kg. Elle est furieuse : « C'est injuste, je fais tout pareil que lui ! » Nora pose la balance de côté : « Ce n'est pas vous qui faites moins bien. C'est votre corps qui ne part pas du même endroit. »</div>
<h3>Pourquoi les hommes maigrissent plus vite</h3>
<table><tr><th>Facteur</th><th>Homme</th><th>Femme</th></tr>
<tr><td>Muscle (en % du poids)</td><td>environ 40 %</td><td>environ 25 à 30 %</td></tr>
<tr><td>Besoins quotidiens</td><td>environ 2 500 kcal (voire 3 000)</td><td>environ 2 000 kcal</td></tr>
<tr><td>Écart avec un apport de 1 500 kcal</td><td>environ 1 000 kcal par jour</td><td>environ 500 kcal par jour</td></tr>
<tr><td>Rétention d'eau liée au cycle</td><td>non</td><td>oui, masque la perte sur la balance</td></tr>
<tr><td>Régimes passés</td><td>rares : « vierge » des régimes</td><td>fréquents : corps devenu résistant à la restriction</td></tr></table>
<p>Laurence Plumey cite l'exemple extrême : avec les mêmes conseils, un homme peut perdre <b>20 kg en 6 mois</b>, une femme <b>6 ou 7</b>. La femme a naturellement plus de réserves pour assumer grossesse et allaitement. Ce n'est ni un manque de volonté, ni une injustice à combattre, c'est de la biologie.</p>
<h3>Le piège des régimes rapides</h3>
<p>Un régime très strict fait perdre vite… surtout de <b>l'eau</b> : les réserves de sucre du foie et des muscles (le <b>glycogène</b>) retiennent chacune 3 à 4 fois leur poids d'eau. On perd aussi du muscle, le métabolisme ralentit, et on reprend. Laurence Plumey décrit la spirale : une personne avec <b>5 kg de trop</b> enchaîne les régimes, maigrit, reprend <b>plus</b> qu'elle n'a perdu, et passe du surpoids modéré à l'<b>obésité</b>. C'est l'effet <b>yo-yo</b>.</p>
<div class="gmnemo"><b>« Vite perdu, vite repris ; doucement perdu, durablement parti. »</b> Un repère raisonnable : 0,5 à 1 kg par semaine au plus. Et la méthode, toujours la même : <b>N.AP.SO</b> (Nutrition, Activité Physique, SOmmeil, module 1).</div>
<h3>La napsothérapie</h3>
<p>Créée par Laurence Plumey en <b>2020</b>, pendant le Covid, quand elle a vu les courbes de poids s'affoler. Le nom vient de <b>N</b>utrition, <b>A</b>ctivité <b>P</b>hysique, <b>SO</b>mmeil. C'est un métier de <b>prévention primaire</b> : auditer les habitudes d'une personne sur ces trois piliers, trouver les erreurs et les corriger, <b>avant</b> la maladie. La formation dure <b>9 mois</b> à distance, ouverte aux professionnels de santé et aux autres ; environ <b>200 praticiens</b> sont installés, avec un annuaire en ligne. Elle rappelle que <b>40 %</b> des patients en consultation se plaignent de troubles du sommeil.</p>
<div class="gtrap">Précision : le titre de napsothérapeute est un diplôme privé, pas une profession de santé réglementée. Le titre de <b>diététicien</b> est protégé par la loi (diplôme d'État, BTS ou BUT) ; celui de <b>médecin nutritionniste</b> suppose un diplôme de médecine. Un napsothérapeute fait de la prévention ; une maladie (obésité sévère, diabète, trouble du comportement alimentaire) relève d'un médecin.</div>
<h3>La chirurgie de l'obésité</h3>
<p>Le podcast annonce le cas d'un patient de <b>200 kg</b> qui en perd <b>100 en un an</b> grâce à une <b>sleeve</b> (on retire environ les deux tiers de l'estomac, qui devient un tube). C'est l'intervention la plus pratiquée en France. Les critères de la Haute Autorité de santé : <b>IMC d'au moins 40</b>, ou <b>d'au moins 35 avec une maladie liée</b> (diabète, hypertension, apnée du sommeil…), après l'échec d'une prise en charge médicale bien conduite, et avec un <b>suivi à vie</b> (risque de carences en fer, vitamine B12, vitamine D). L'IMC sert justement de repère objectif pour décider d'opérer (module 1).</p>
<h3>Les « médicaments miracles »</h3>
<p>Annoncés dans le podcast sans être détaillés, voici les faits vérifiés. Les <b>analogues du GLP-1</b> imitent une hormone intestinale de satiété : le <b>sémaglutide</b> a fait perdre environ <b>15 %</b> du poids en 68 semaines dans l'essai STEP-1 (2021), le tirzépatide environ 20 % (SURMOUNT-1, 2022). Mais ce sont des médicaments sur <b>prescription</b>, avec des effets digestifs fréquents (nausées), une perte de muscle si on ne bouge pas, et une <b>reprise d'environ deux tiers du poids perdu</b> dans l'année qui suit l'arrêt. Ils ne remplacent pas N.AP.SO : ils l'accompagnent.</p>
<h3>Ce que tu dois savoir faire</h3>
<ul><li>Expliquer à une femme pourquoi elle perd moins vite, sans la décourager</li><li>Démonter un régime rapide et l'effet yo-yo</li><li>Donner les critères de la chirurgie et les limites des médicaments</li><li>Situer la napsothérapie parmi les métiers de la nutrition</li></ul>`},
/*EXOS*/
{i:"a197_01",u:197,t:"story",d:.2,nw:"Pourquoi les hommes maigrissent plus vite",q:"Chloé est furieuse de perdre moins vite que Paul. Que lui dis-tu ?",sc:[{who:"Chloé",txt:"Je fais tout pareil que lui, c'est injuste !"}],o:["« Il a plus de muscle et de besoins : votre perte est normale, et elle durera. »","« Vous trichez sûrement un peu, sinon vous perdriez autant que Paul chaque mois. »","« Passez à 800 kcal par jour, vous rattraperez son rythme en quelques semaines. »","« C'est à cause de votre âge, après 25 ans une femme ne peut plus maigrir. »"],a:0,w:"Plus de muscle, besoins plus élevés, donc écart calorique plus grand chez l'homme. Rétention d'eau et régimes passés freinent la balance chez la femme. Vite perdu, vite repris."},
{i:"a197_02",u:197,t:"slider",d:.2,q:"Quelle part du poids d'un homme représente le muscle, selon Laurence Plumey (en %) ?",min:10,max:60,step:5,a:40,tol:0,pre:"",un:" %",w:"Environ 40 %, contre 25 à 30 % chez la femme. Plus de muscle = plus de dépense, même au repos."},
{i:"a197_03",u:197,t:"num",d:.25,q:"Paul a besoin de 2 500 kcal et mange 1 500 kcal ; Chloé a besoin de 2 000 kcal et mange 1 500. Combien de fois l'écart de Paul est-il plus grand ?",a:2,tol:0,un:" fois",h:"1 000 / 500",w:"Deux fois plus grand : 1 000 kcal par jour contre 500. À régime identique, l'homme maigrit plus vite."},
{i:"a197_04",u:197,t:"fill",d:.25,q:"Les réserves de sucre du foie et des muscles, qui retiennent beaucoup d'eau, s'appellent le ___.",o:["glycogène","glucagon","glucosamine","glycérol"],a:0,w:"Le glycogène. Un régime très strict le vide : la balance chute vite, mais c'est surtout de l'eau."},
{i:"a197_05",u:197,t:"tf",d:.25,q:"Une perte de 3 kg en une semaine de régime très strict est surtout une perte de graisse.",a:false,w:"C'est surtout de l'eau (glycogène) et un peu de muscle. 1 kg de graisse, c'est 7 700 kcal : impossible d'en perdre 3 en une semaine. Sur les 40 tonnes de nourriture d'une vie, ce sont les petits excès répétés qui comptent, pas une semaine."},
{i:"a197_06",u:197,t:"match",d:.3,q:"Associe chaque lettre de N.AP.SO à son pilier.",p:[["N","Nutrition"],["AP","Activité physique"],["SO","Sommeil"],["Napsothérapie","Métier de prévention créé en 2020"]],w:"Le fil rouge du cours depuis le module 1. Les trois piliers se renforcent : mal dormir fait manger plus et bouger moins."},
{i:"a197_07",u:197,t:"order",d:.3,q:"Remets dans l'ordre la spirale du yo-yo décrite par Laurence Plumey.",it:["5 kg de trop","Premier régime strict","Perte rapide, surtout d'eau et de muscle","Reprise supérieure à la perte","Nouveau régime, puis obésité"],w:"Vite perdu, vite repris. C'est pour casser cette spirale qu'elle a créé la napsothérapie : agir tôt, sans régime."},
{i:"a197_08",u:197,t:"story",d:.3,q:"Théo veut perdre 10 kg en un mois pour l'été avec un régime trouvé sur les réseaux.",sc:[{who:"Théo",txt:"C'est 600 kcal par jour, ça marche super vite."}],o:["« Vous perdrez eau et muscle, puis reprendrez : visez 0,5 à 1 kg par semaine. »","« Excellent choix, plus c'est rapide, plus la perte est durable dans le temps. »","« Faites-le deux mois au lieu d'un, vous serez encore plus sûr du résultat. »","« Ajoutez une boisson énergisante chaque matin pour tenir sans manger. »"],a:0,w:"600 kcal, c'est une famine : glycogène vidé, muscle perdu, métabolisme ralenti, reprise assurée. Doucement perdu, durablement parti."},
{i:"a197_09",u:197,t:"mcq",d:.35,q:"En quelle année Laurence Plumey a-t-elle lancé la napsothérapie ?",o:["2020","1995","2010","2024"],a:0,w:"En 2020, pendant le Covid, quand elle a vu les gens grossir, mal dormir et ne plus bouger."},
{i:"a197_10",u:197,t:"multi",d:.35,q:"Pourquoi une femme perd-elle souvent moins vite sur la balance ?",o:["Moins de muscle","Besoins énergétiques plus faibles","Rétention d'eau selon le cycle","Régimes passés plus nombreux","Manque de volonté"],a:[0,1,2,3],w:"Quatre raisons biologiques ou historiques. La volonté n'y est pour rien : le dire rassure et évite l'abandon."},
{i:"a197_11",u:197,t:"sort",d:.35,q:"Classe chaque personne : critère HAS de chirurgie rempli ou non ?",bins:["Critère rempli","Non rempli"],it:[["IMC 42 sans autre maladie",0],["IMC 36 avec diabète de type 2",0],["IMC 32 sans maladie",1],["IMC 37 sans aucune maladie liée",1],["IMC 35 avec apnée du sommeil",0]],w:"IMC d'au moins 40, ou d'au moins 35 avec une maladie liée, après échec d'une prise en charge médicale. Puis un suivi à vie."},
{i:"a197_12",u:197,t:"fill",d:.4,q:"L'intervention qui retire environ les deux tiers de l'estomac s'appelle la ___.",o:["sleeve","coloscopie","liposuccion","appendicectomie"],a:0,w:"La sleeve gastrectomie, la plus pratiquée en France. La liposuccion, elle, retire du gras sous la peau et ne traite pas l'obésité."},
{i:"a197_13",u:197,t:"story",d:.4,q:"Paul a vu une vidéo sur « la piqûre qui fait maigrir ». Que lui expliques-tu ?",sc:[{who:"Paul",txt:"Pourquoi se fatiguer si une piqûre fait tout ?"}],o:["« Efficace sur ordonnance, mais on reprend à l'arrêt si rien n'a changé. »","« Aucun effet réel, c'est une arnaque totale inventée par les réseaux sociaux. »","« Achetez-la en ligne sans ordonnance, c'est plus rapide que chez le médecin. »","« Elle fait perdre du gras sans jamais toucher au muscle, c'est parfait. »"],a:0,w:"Sémaglutide : environ 15 % de perte en 68 semaines, mais environ deux tiers repris un an après l'arrêt. Prescription médicale, effets digestifs, N.AP.SO indispensable."},
{i:"a197_14",u:197,t:"tf",d:.4,q:"Le titre de diététicien est protégé par la loi en France.",a:true,w:"Il faut un diplôme d'État, un BTS ou un BUT. Le titre de napsothérapeute, lui, est un diplôme privé de prévention."},
{i:"a197_15",u:197,t:"num",d:.45,q:"Un patient de 110 kg perd 15 % de son poids sous sémaglutide. Combien de kilos perd-il ?",a:16.5,tol:.1,un:" kg",h:"110 × 0,15",w:"16,5 kg, le résultat moyen de STEP-1. S'il arrête sans changer ses habitudes, il en reprendra environ les deux tiers, soit 11 kg."},
{i:"a197_16",u:197,t:"mcq",d:.45,q:"Quelle hormone les nouveaux médicaments de l'obésité imitent-ils ?",o:["Le GLP-1, hormone de satiété","L'adrénaline, hormone du stress","La mélatonine, hormone du sommeil","La testostérone"],a:0,w:"Le GLP-1 est une hormone intestinale qui ralentit la vidange de l'estomac et signale la satiété au cerveau."},
{i:"a197_17",u:197,t:"story",d:.45,q:"Rappel du module 3 : un patient consulte pour du poids, mais dort 5 heures par nuit. Par quoi commences-tu ?",sc:[{who:"Patient",txt:"Je veux juste un régime, le sommeil ce n'est pas le sujet."}],o:["« Le sommeil est un des trois piliers : sans lui, le régime lutte contre la faim. »","« Vous avez raison, le sommeil n'a aucun lien avec le poids, parlons calories. »","« Dormez moins encore, vous brûlerez plus de calories en restant éveillé. »","« Prenez un somnifère tous les soirs et ne changez rien d'autre à votre vie. »"],a:0,w:"40 % des patients se plaignent du sommeil. Manque de sommeil = faim, fatigue, sucre (les 3 S). N.AP.SO se traite en entier. Après une nuit courte, la ghréline (faim) monte et la leptine (satiété) baisse."},
{i:"a197_18",u:197,t:"tiles",d:.5,q:"Reconstitue le moyen mnémotechnique du rythme de perte.",a:["vite","perdu","vite","repris","doucement","perdu","durablement","parti"],dd:["jamais","toujours","régime"],w:"Repère : 0,5 à 1 kg par semaine au plus."},
{i:"a197_19",u:197,t:"slider",d:.5,q:"Quel IMC minimal, sans autre maladie, permet d'envisager une chirurgie de l'obésité selon la HAS ?",min:25,max:50,step:1,a:40,tol:0,pre:"",un:"",w:"40, ou 35 avec une maladie liée (diabète, hypertension, apnée du sommeil…). D'où l'intérêt de l'IMC comme repère objectif."},
{i:"a197_20",u:197,t:"match",d:.5,q:"Associe chaque traitement à sa limite principale.",p:[["Régime très strict","Effet yo-yo"],["Sleeve","Suivi à vie et risque de carences"],["Sémaglutide","Reprise à l'arrêt"],["N.AP.SO","Demande du temps et de l'accompagnement"]],w:"Aucune solution n'est magique. Les trois piliers restent la base de toutes les autres."},
{i:"a197_21",u:197,t:"story",d:.55,q:"Un patient de 200 kg a perdu 100 kg en un an après une sleeve. Il pense que « c'est fini ». Que lui dis-tu ?",sc:[{who:"Patient",txt:"Je suis guéri, je peux arrêter les rendez-vous."}],o:["« Bravo, mais le suivi est à vie : carences possibles, risque de reprise. »","« Oui, la sleeve guérit définitivement, plus aucun suivi n'est nécessaire. »","« Recommencez un régime strict pour perdre encore 50 kg très vite. »","« Arrêtez vos compléments, l'estomac réduit absorbe désormais mieux tout. »"],a:0,w:"Fer, vitamine B12, vitamine D : les carences sont fréquentes. Et sans nouvelles habitudes, une partie du poids revient."},
{i:"a197_22",u:197,t:"tf",d:.55,q:"Selon Laurence Plumey, une femme a naturellement plus de réserves pour assumer grossesse et allaitement.",a:true,w:"Plus de gras, moins de muscle : une adaptation biologique. Ce n'est pas un défaut à corriger, c'est une donnée à intégrer. C'est une part de ce que Laurence Plumey appelle l'inconscient métabolique."},
{i:"a197_23",u:197,t:"fill",d:.55,q:"Un métier qui agit avant l'apparition de la maladie relève de la prévention ___.",o:["primaire","secondaire","tertiaire","palliative"],a:0,w:"Prévention primaire : éviter la maladie. Secondaire : la dépister tôt. Tertiaire : limiter ses complications. La napsothérapie vise la première."},
{i:"a197_24",u:197,t:"sort",d:.6,q:"Classe chaque profession : titre protégé par la loi ou non ?",bins:["Titre protégé","Non protégé"],it:[["Diététicien",0],["Médecin nutritionniste",0],["Napsothérapeute",1],["Coach minceur",1]],w:"Pour une maladie, on oriente vers un diététicien ou un médecin. La prévention peut aussi passer par d'autres accompagnants."},
{i:"a197_25",u:197,t:"mcq",d:.6,q:"Quelle part du poids perdu reprend-on environ un an après l'arrêt du sémaglutide (STEP-1) ?",o:["Environ deux tiers","Environ 5 %","Rien du tout, jamais","Le double du poids"],a:0,w:"Environ deux tiers. Le médicament traite une maladie chronique : son effet dure tant qu'on le prend et que les habitudes suivent."},
{i:"a197_26",u:197,t:"story",d:.65,q:"Rappel du module 14 : un homme a pris 20 kg après la naissance de son enfant. Quel est ton premier réflexe ?",sc:[{who:"Patient",txt:"Il me faut le régime le plus strict possible."}],o:["« D'abord comprendre ce qui a changé dans votre vie, puis l'assiette. »","« D'accord, 1 000 kcal par jour dès demain, sans aucune exception. »","« Des médicaments tout de suite, les régimes ne marchent jamais, voilà. »","« Une chirurgie, c'est la seule solution au-delà de 15 kg de trop. »"],a:0,w:"Comprendre le problème avant de prescrire : chez ce patient, c'était l'arrêt du sport à cause de la crèche."},
{i:"a197_27",u:197,t:"num",d:.65,q:"Chloé perd 0,5 kg par semaine. Combien de kilos en 6 mois (26 semaines) ?",a:13,tol:0,un:" kg",h:"0,5 × 26",w:"13 kg en 6 mois, sans régime extrême, et bien plus durables que 10 kg perdus en un mois."},
{i:"a197_28",u:197,t:"multi",d:.7,q:"Quels effets indésirables peut-on observer avec les analogues du GLP-1 ?",o:["Nausées","Troubles digestifs","Perte de muscle sans activité","Reprise de poids à l'arrêt","Croissance des cheveux"],a:[0,1,2,3],w:"D'où la prescription et le suivi médical, et l'intérêt de bouger (protéger le muscle) pendant le traitement."},
{i:"a197_29",u:197,t:"story",d:.7,q:"Rappel du module 1 : un patient avec 5 kg de trop veut « un vrai régime ». Que proposes-tu ?",sc:[{who:"Patient",txt:"Cinq kilos, c'est rien, je fais un régime express et c'est réglé."}],o:["« Pas de régime : on audite N.AP.SO, on corrige deux ou trois habitudes. »","« Parfait, un régime express de 15 jours, puis on n'en parle plus. »","« Cinq kilos, c'est déjà l'obésité, il faut consulter un chirurgien. »","« Ne faites rien du tout, ces kilos partiront tout seuls avec l'âge. »"],a:0,w:"C'est exactement le moment clé selon Laurence Plumey : à 5 kg, on évite la spirale des régimes et l'obésité future."},
{i:"a197_30",u:197,t:"tiles",d:.75,q:"Reconstitue les critères de la HAS pour la chirurgie.",a:["IMC","40","ou","35","avec","une","maladie","liée"],dd:["25","30","sport"],w:"Et toujours après l'échec d'une prise en charge médicale bien conduite, avec un suivi à vie."},
{i:"a197_31",u:197,t:"mcq",d:.75,q:"Selon Laurence Plumey, quelle part des patients en consultation se plaint de troubles du sommeil ?",o:["Environ 40 %","Environ 4 %","Environ 90 %","Aucun"],a:0,w:"40 %. Le sommeil est souvent le pilier oublié, alors qu'il commande la faim et l'énergie."},
{i:"a197_32",u:197,t:"story",d:.8,q:"Synthèse : Chloé demande la stratégie la plus sûre pour perdre ses 9 kg.",sc:[{who:"Chloé",txt:"Je ne veux plus jamais faire le yo-yo."}],o:["« N.AP.SO, 0,5 kg par semaine, un suivi régulier, une pesée par semaine. »","« Un régime à 800 kcal pendant un mois, puis on voit pour la suite de l'année. »","« Une piqûre de sémaglutide sans ordonnance, commandée sur internet. »","« Rien du tout, à votre âge une femme ne peut plus perdre durablement. »"],a:0,w:"Doucement perdu, durablement parti. En 18 semaines, les 9 kg sont partis, sans casser son métabolisme."}
