/*UNIT*/
{id:198,c:"NUTRI",n:"Module 16",t:"Synthèse : mène ta propre consultation de A à Z",col:"--green",ic:"🩺",guide:`
<h3>Ton dernier jour de stage</h3>
<div class="gstory">Vendredi, 17 h, au cabinet de la Croix-Rousse. Nora enlève sa blouse et te la tend : « Lundi, c'est toi qui reçois. » Dans le planning, tous les visages de ces quinze modules : Chloé et ses 9 kg, Mehdi et ses nuits de garde, les Martin et Léna, Paul et son tour de taille, Inès et Karim et leur projet de bébé, Théo et son cola, Mme Garcia et son panier. Tu as tout vu, tout calculé, tout corrigé. Il reste une chose : tout assembler en une consultation.</div>
<h3>Le déroulé d'une consultation</h3>
<table><tr><th>Étape</th><th>Ce que tu fais</th><th>Exemple</th></tr>
<tr><td>1. Accueillir</td><td>Écouter la demande, sans juger</td><td>« Qu'est-ce qui vous amène aujourd'hui ? »</td></tr>
<tr><td>2. Mesurer</td><td>Poids, taille, IMC, tour de taille</td><td>Paul : IMC 29, tour de taille 108 cm</td></tr>
<tr><td>3. Auditer N.AP.SO</td><td>Journée type, sommeil, activité, boissons</td><td>Mehdi : 5 h de sommeil, boisson énergisante</td></tr>
<tr><td>4. Comprendre la cause</td><td>Chercher ce qui a changé</td><td>Le patient de la crèche qui a arrêté le sport</td></tr>
<tr><td>5. Choisir 2 ou 3 changements</td><td>Les plus rentables, que le patient accepte</td><td>Théo : moitié moins de cola</td></tr>
<tr><td>6. Fixer un objectif chiffré</td><td>Précis, mesurable, réaliste, daté</td><td>0,5 kg par semaine, 30 min de marche par jour</td></tr>
<tr><td>7. Suivre</td><td>Revoir, valoriser, ajuster</td><td>Rendez-vous dans un mois</td></tr></table>
<div class="gmnemo"><b>« A.M.A.C.O.F.S. : Accueillir, Mesurer, Auditer, Comprendre, Opter, Fixer, Suivre. »</b> Ou en phrase : <b>« Avant Mon Assiette, Comprends On Fait Simple. »</b></div>
<h3>Les repères officiels à connaître par cœur (Santé publique France, 2019)</h3>
<table><tr><th>Aliment</th><th>Repère adulte</th></tr>
<tr><td>Fruits et légumes</td><td>Au moins 5 par jour</td></tr>
<tr><td>Légumineuses</td><td>Au moins 2 fois par semaine</td></tr>
<tr><td>Fruits à coque</td><td>Une petite poignée par jour, sans sel</td></tr>
<tr><td>Féculents complets</td><td>Au moins un par jour</td></tr>
<tr><td>Poisson</td><td>2 fois par semaine, dont un gras</td></tr>
<tr><td>Viande hors volaille</td><td>500 g par semaine au plus</td></tr>
<tr><td>Charcuterie</td><td>150 g par semaine au plus</td></tr>
<tr><td>Produits laitiers</td><td>2 par jour</td></tr>
<tr><td>Boissons sucrées</td><td>Au plus un verre par jour</td></tr>
<tr><td>Alcool</td><td>2 verres par jour, 10 par semaine au plus, pas tous les jours</td></tr>
<tr><td>Activité physique</td><td>Au moins 30 minutes par jour</td></tr></table>
<h3>L'assiette</h3>
<p>Laurence Plumey propose : une protéine (viande, poisson ou œufs), puis <b>moitié légumes, moitié féculents</b>, un laitage, un fruit, avec « un légume et un fruit à chaque repas ». D'autres modèles (l'assiette de Harvard) donnent la moitié aux légumes et un quart aux féculents, un quart aux protéines, utile pour une personne qui veut perdre du poids. Les deux se rejoignent : beaucoup de légumes, des féculents plutôt complets, du bon gras en petite quantité.</p>
<h3>Les corrections du podcast à retenir</h3>
<div class="gtrap">Tout au long du cours, tu as corrigé les chiffres trop rapides du podcast : graisse du bébé (15 % à la naissance, pas 30 %), pastèque (92 % d'eau, pas 98 %), fibres de 600 g de fruits et légumes (12 à 15 g, pas 30), microbiote (38 000 milliards de bactéries pour environ 200 g, pas 100 000 milliards pour 1,5 kg), calcium (950 mg, pas 800), cancers de l'alcool (liste du CIRC), Téflon (nuance PFAS), surimi (salé), besoins d'un jeune homme (2 400 à 2 800 kcal), spermatozoïdes (baisse d'environ 32 % en France, 52 % dans les pays occidentaux). Le fond du discours de Laurence Plumey est juste, mais un professionnel vérifie quand même chaque chiffre.</div>
<h3>Ce que tu dois savoir faire en examen</h3>
<ul><li>Mener une consultation dans l'ordre A.M.A.C.O.F.S.</li><li>Calculer IMC, besoins (Mifflin-St Jeor), calories (4, 4, 9, 7), sucre en morceaux, alcool en grammes, fibres, calcium</li><li>Relier chaque symptôme à son pilier N.AP.SO</li><li>Réciter les repères officiels et corriger une idée reçue avec une source</li><li>Proposer un plan de 2 ou 3 changements chiffrés, adaptés à la vie du patient</li></ul>`},
/*EXOS*/
{i:"a198_01",u:198,t:"order",d:.2,nw:"Le déroulé d'une consultation",q:"Remets dans l'ordre les étapes d'une consultation.",it:["Accueillir la demande","Mesurer poids, IMC et tour de taille","Auditer N.AP.SO","Comprendre la cause","Choisir 2 ou 3 changements","Fixer un objectif chiffré","Suivre et ajuster"],w:"A.M.A.C.O.F.S. : Accueillir, Mesurer, Auditer, Comprendre, Opter, Fixer, Suivre."},
{i:"a198_02",u:198,t:"story",d:.2,q:"Un nouveau patient s'assoit. Quelle est ta première phrase ?",sc:[{who:"Patient",txt:"Bonjour… je ne sais pas trop par où commencer."}],o:["« Qu'est-ce qui vous amène ? Prenez votre temps. »","« Montez sur la balance, on verra après ce qui ne va pas. »","« Voici votre régime à 1 200 kcal, on commence dès lundi. »","« Vous mangez sûrement trop, on va arranger ça très vite. »"],a:0,w:"Accueillir avant de mesurer. Un patient qui se sent jugé ne dit pas la vérité sur ses habitudes."},
{i:"a198_03",u:198,t:"num",d:.25,q:"Paul pèse 96 kg pour 1,82 m. Quel est son IMC (arrondi à l'unité) ?",a:29,tol:.5,un:"",h:"96 / (1,82 × 1,82)",w:"96 / 3,31 = 29 : surpoids, juste sous l'obésité. Avec 108 cm de tour de taille, le gras viscéral est le vrai signal (module 1). Rappel : sur une vie, on mange environ 40 tonnes de nourriture ; la balance mesure surtout les habitudes."},
{i:"a198_04",u:198,t:"match",d:.25,q:"Associe chaque patient à son pilier N.AP.SO prioritaire.",p:[["Mehdi, veilleur de nuit","Sommeil"],["Le patient de la crèche","Activité physique"],["Théo et son litre de cola","Nutrition"],["Léna qui dîne à 20 h 30","Sommeil"]],w:"Chaque patient a son levier principal. Comprendre la cause avant de prescrire. Pour Mehdi, le manque de sommeil fait monter la ghréline et baisser la leptine : il a plus faim. Le travail de nuit reste un facteur majeur de prise de poids."},
{i:"a198_05",u:198,t:"tf",d:.25,q:"Santé publique France recommande 2 produits laitiers par jour pour un adulte.",a:true,w:"Depuis 2019 : 2 pour un adulte, 3 pour les enfants et les adolescents. Le reste du calcium vient des eaux, légumes verts, amandes."},
{i:"a198_06",u:198,t:"sort",d:.3,q:"Classe chaque repère : limite maximale ou minimum à atteindre ?",bins:["Minimum","Maximum"],it:[["5 fruits et légumes par jour",0],["500 g de viande hors volaille par semaine",1],["Légumineuses 2 fois par semaine",0],["150 g de charcuterie par semaine",1],["30 minutes d'activité par jour",0],["10 verres d'alcool par semaine",1]],w:"Au moins : végétaux, légumineuses, activité. Au plus : viande rouge, charcuterie, alcool, boissons sucrées."},
{i:"a198_07",u:198,t:"story",d:.3,q:"Mehdi revient : il dort 6 h au lieu de 5, a arrêté la boisson énergisante, a perdu 2 kg. Que fais-tu ?",sc:[{who:"Mehdi",txt:"C'est peu, 2 kilos, non ?"}],o:["« C'est un vrai progrès : on garde, et on ajoute une marche après la garde. »","« C'est trop peu, on passe à un régime strict pour accélérer le mois prochain. »","« Recommencez les boissons énergisantes, elles aidaient à brûler les graisses. »","« Arrêtez le suivi, vous avez atteint votre objectif final. »"],a:0,w:"Valoriser, consolider, ajouter un seul changement. Suivre, c'est la dernière lettre d'A.M.A.C.O.F.S."},
{i:"a198_08",u:198,t:"fill",d:.3,q:"Laurence Plumey propose une assiette avec moitié légumes et moitié ___.",o:["féculents","fromages","fruits frais","viandes"],a:0,w:"Moitié légumes, moitié féculents, avec la protéine à côté. Pour perdre du poids, on peut pencher vers plus de légumes (modèle de Harvard). Le régime méditerranéen suit la même logique, cuisiné à l'huile d'olive."},
{i:"a198_09",u:198,t:"multi",d:.35,q:"Que mesures-tu à l'étape « Mesurer » ?",o:["Poids","Taille","IMC","Tour de taille","Groupe sanguin"],a:[0,1,2,3],w:"Le poids seul ne suffit pas : l'IMC situe, le tour de taille révèle le gras viscéral."},
{i:"a198_10",u:198,t:"story",d:.35,q:"Chloé veut changer « tout d'un coup » dès lundi. Que lui réponds-tu ?",sc:[{who:"Chloé",txt:"Cette fois je fais tout : sport tous les jours, zéro sucre, coucher à 22 h."}],o:["« Deux changements que vous tiendrez, puis on en ajoutera. »","« Parfait, plus on change de choses en même temps, plus ça tient. »","« Ajoutez aussi un jeûne le week-end pour aller encore plus vite. »","« Faites tout, et si ça lâche, c'est que vous manquez de volonté. »"],a:0,w:"Opter : 2 ou 3 changements acceptés valent mieux que 10 abandonnés en une semaine."},
{i:"a198_11",u:198,t:"num",d:.35,q:"Théo boit 1 litre de cola (106 g de sucre) et passe à 50 cl. Combien de morceaux de sucre économise-t-il par jour (arrondi) ?",a:11,tol:1,un:" morceaux",h:"53 / 5",w:"53 g, environ 11 morceaux par jour. Divise par 5, compte les morceaux (module 7)."},
{i:"a198_12",u:198,t:"tiles",d:.4,q:"Reconstitue le moyen mnémotechnique de la consultation.",a:["Avant","Mon","Assiette","Comprends","On","Fait","Simple"],dd:["Régime","Pèse","Vite"],w:"A.M.A.C.O.F.S. : Accueillir, Mesurer, Auditer, Comprendre, Opter, Fixer, Suivre. Garde aussi en tête l'inconscient métabolique : les goûts, comme celui de la coriandre, ne se choisissent pas tous."},
{i:"a198_13",u:198,t:"mcq",d:.4,q:"Quelle quantité maximale de charcuterie par semaine recommande Santé publique France ?",o:["150 g","1 kg","50 g par jour","Aucune limite"],a:0,w:"150 g par semaine, soit environ 3 tranches de jambon. La viande hors volaille : 500 g par semaine au plus."},
{i:"a198_14",u:198,t:"story",d:.4,q:"Rappel du module 7 : Paul a des transaminases élevées et boit 14 bières par semaine. Quel objectif chiffré fixes-tu ?",sc:[{who:"Paul",txt:"Je veux un chiffre précis."}],o:["« Au plus 8 verres par semaine, 3 soirs sans, pendant un mois. »","« Zéro alcool pour toujours, dès ce soir, sans exception possible. »","« Continuez à 14, mais passez à la bière sans alcool aromatisée. »","« Buvez autant, mais uniquement le week-end, c'est moins mauvais. »"],a:0,w:"Précis, mesurable, réaliste, daté. Sous les repères « 2, 10, pas tous les jours », et bon pour le foie."},
{i:"a198_15",u:198,t:"tf",d:.45,q:"Selon le cours, le fond du discours de Laurence Plumey est juste, mais plusieurs chiffres du podcast sont à corriger.",a:true,w:"Graisse du bébé, pastèque, fibres, microbiote, calcium, cancers de l'alcool : un professionnel vérifie chaque chiffre avant de le transmettre."},
{i:"a198_16",u:198,t:"match",d:.45,q:"Associe chaque chiffre du podcast à sa correction.",p:[["Bébé : 30 % de graisse","Environ 15 % à la naissance"],["Pastèque : 98 % d'eau","Environ 92 %"],["Calcium : 800 mg","950 mg chez l'adulte"],["Microbiote : 1,5 kg","Environ 200 g"]],w:"Quatre corrections à connaître par cœur, avec leur source (Ciqual, Anses, Sender 2016)."},
{i:"a198_17",u:198,t:"story",d:.45,q:"Les Martin reviennent : Léna dîne à 19 h, se couche à 20 h 30, boit de l'eau. Elle a arrêté de grossir. Que dis-tu à Léna ?",sc:[{who:"Léna",txt:"Je suis toujours ronde, alors ça marche pas ?"}],o:["« Tu grandis sans grossir : ton corps s'affine, c'est gagné. »","« Il faut que tu perdes 5 kilos avant l'été, on va faire un régime. »","« Tu dois encore arrêter de manger ton goûter, c'est bien trop. »","« Ça ne marche pas, il faut essayer des médicaments pour toi. »"],a:0,w:"Chez l'enfant, stabiliser le poids pendant la croissance suffit : l'IMC baisse naturellement. Pas de régime, et on rassure. La courbe de corpulence du carnet de santé le confirme."},
{i:"a198_18",u:198,t:"slider",d:.5,q:"Combien de fois par semaine faut-il manger des légumineuses selon Santé publique France (au moins) ?",min:0,max:7,step:1,a:2,tol:0,pre:"",un:" fois",w:"Au moins 2 fois : lentilles, pois chiches, haricots secs. Fibres, protéines, pas chères, et bonnes pour le microbiote."},
{i:"a198_19",u:198,t:"fill",d:.5,q:"L'étape où l'on cherche ce qui a changé dans la vie du patient s'appelle : ___ la cause.",o:["comprendre","ignorer","deviner","minimiser"],a:0,w:"Le patient de la crèche en est l'exemple : sans cette étape, on lui aurait prescrit un régime inutile."},
{i:"a198_20",u:198,t:"sort",d:.5,q:"Classe chaque objectif : bien formulé ou mal formulé ?",bins:["Bien formulé","Mal formulé"],it:[["Marcher 30 minutes 5 jours par semaine pendant un mois",0],["Manger mieux",1],["Un demi-litre de cola en moins par jour dès lundi",0],["Faire plus d'efforts",1],["Se coucher avant 23 h en semaine",0]],w:"Un objectif précis, mesurable, réaliste et daté se suit. « Manger mieux » ne se mesure pas. Le NEAT, l'activité du quotidien (escaliers, marche, ménage), compte aussi dans ces objectifs."},
{i:"a198_21",u:198,t:"story",d:.55,q:"Rappel du module 14 : Inès et Karim te demandent quoi prioriser en premier.",sc:[{who:"Karim",txt:"On ne peut pas tout changer en même temps."}],o:["« Zéro tabac et alcool pour les deux, acide folique pour Inès, puis le reste. »","« Karim ne change rien, seule Inès doit faire des efforts pour le bébé. »","« Commencez par un régime sans gluten, c'est le plus efficace pour la fertilité. »","« Achetez des compléments pour la fertilité, ils suffisent à eux seuls. »"],a:0,w:"Opter : les changements les plus rentables d'abord. Les 5 C, l'acide folique, puis les légumes et le sport à deux."},
{i:"a198_22",u:198,t:"mcq",d:.55,q:"Quelle formule sert à estimer le métabolisme de base dans ce cours ?",o:["Mifflin-St Jeor","Formule de Broca","Formule de Lorentz","Loi de Newton"],a:0,w:"Mifflin-St Jeor (module 2) : 10 × poids + 6,25 × taille en cm − 5 × âge, + 5 chez l'homme, − 161 chez la femme."},
{i:"a198_23",u:198,t:"num",d:.6,q:"Mifflin-St Jeor pour Paul, 52 ans, 96 kg, 182 cm : 10 × 96 + 6,25 × 182 − 5 × 52 + 5. Quel résultat (arrondi) ?",a:1843,tol:2,un:" kcal",h:"960 + 1 137,5 − 260 + 5",w:"Environ 1 843 kcal au repos. Multiplié par son niveau d'activité (NAP 1,4 à 1,6), ses besoins sont d'environ 2 600 à 2 950 kcal."},
{i:"a198_24",u:198,t:"story",d:.6,q:"Rappel du module 11 : Mme Garcia a perdu 3 kg sans le vouloir en 2 mois. Que fais-tu ?",sc:[{who:"Mme Garcia",txt:"Je suis contente, j'ai minci !"}],o:["« Chez une personne âgée, une perte involontaire se signale au médecin. »","« Bravo, continuez à manger moins, c'est très bon à votre âge. »","« Supprimez aussi les œufs pour continuer de perdre encore plus vite. »","« Ce n'est rien, c'est sûrement dû à la pesée faite le matin à jeun. »"],a:0,w:"Après 65 ans, une perte de poids non voulue peut signaler une dénutrition ou une maladie. On oriente, on enrichit l'alimentation en protéines."},
{i:"a198_25",u:198,t:"multi",d:.65,q:"Quels calculs un professionnel doit-il savoir faire à la fin de ce cours ?",o:["IMC","Sucre en morceaux","Alcool en grammes","Fibres d'une journée","Horoscope alimentaire"],a:[0,1,2,3],w:"Plus les besoins (Mifflin-St Jeor), les calories (4, 4, 9, 7) et le calcium. L'horoscope, lui, n'a jamais nourri personne. Et pour relativiser un écart : on mange environ 40 tonnes de nourriture dans une vie."},
{i:"a198_26",u:198,t:"tf",d:.65,q:"Un bon plan comporte en général 2 ou 3 changements à la fois, pas dix.",a:true,w:"Opter, puis ajouter au suivi suivant. C'est ce qui évite l'abandon et le yo-yo. Exemple d'objectif : 150 minutes de marche par semaine, soit 30 minutes 5 jours sur 7."},
{i:"a198_27",u:198,t:"story",d:.7,q:"Un patient te montre un article disant que « manger après 20 h fait grossir ». Que réponds-tu ?",sc:[{who:"Patient",txt:"C'est vrai ou pas ?"}],o:["« Ce n'est pas l'heure qui fait grossir, mais le sommeil et le grignotage. »","« Vrai : tout aliment avalé après 20 h se transforme entièrement en graisse. »","« Faux : on peut dîner à minuit tous les soirs sans aucune conséquence. »","« Vrai, il faut donc arrêter de manger dès 17 h, même en rentrant tard. »"],a:0,w:"Dîner tard retarde et abîme le sommeil ; dîner trop tôt fait grignoter. Vers 20 h, 2 heures avant le coucher (module 13)."},
{i:"a198_28",u:198,t:"fill",d:.7,q:"Les trois piliers de la santé selon Laurence Plumey forment l'acronyme ___.",o:["N.AP.SO","P.N.N.S","I.M.C","O.M.S"],a:0,w:"Nutrition, Activité Physique, SOmmeil. « Nos Assiettes Pèsent, Sommeil Oublié » (module 1)."},
{i:"a198_29",u:198,t:"match",d:.75,q:"Associe chaque moyen mnémotechnique à son module.",p:[["Glu-Pro, gras, gorgée","Calories 4, 4, 9, 7"],["Divise par 5, compte les morceaux","Sucre"],["2, 10, pas tous les jours","Alcool"],["S.M.S.","Poissons gras"]],w:"Ces formules sont tes outils d'examen : elles contiennent les chiffres essentiels. Ajoute « trois couleurs dans l'assiette » : l'assiette arc-en-ciel."},
{i:"a198_30",u:198,t:"story",d:.75,q:"Théo, six mois plus tard, a perdu 8 kg et craint de tout reprendre. Que lui dis-tu ?",sc:[{who:"Théo",txt:"J'ai peur que ça revienne comme pour mon père."}],o:["« Vous avez changé d'habitudes, pas fait un régime : ça vous protège. »","« Ça reviendra forcément, c'est génétique, vous n'y pouvez rien du tout. »","« Pour éviter la reprise, faites un régime strict chaque printemps. »","« Arrêtez de vous peser et de faire attention, ça ne sert plus à rien. »"],a:0,w:"Doucement perdu, durablement parti. On garde un suivi espacé et on revient aux trois piliers en cas d'écart."},
{i:"a198_31",u:198,t:"mcq",d:.8,q:"Combien de fruits et légumes par jour Santé publique France recommande-t-elle au minimum ?",o:["5","1","10","2"],a:0,w:"Au moins 5 par jour. Laurence Plumey le traduit par « un légume et un fruit à chaque repas ». Leurs antioxydants neutralisent les radicaux libres."},
{i:"a198_32",u:198,t:"story",d:.85,q:"Synthèse finale : Nora te demande ce que tu as appris de plus important.",sc:[{who:"Nora",txt:"Si tu ne devais garder qu'une phrase ?"}],o:["« Comprendre la personne et ses trois piliers avant son assiette. »","« Le meilleur régime est toujours le plus strict et le plus rapide possible. »","« Il suffit de compter les calories, le reste n'a pas vraiment d'importance. »","« Chaque patient doit suivre exactement le même plan, sans exception. »"],a:0,w:"Avant Mon Assiette, Comprends On Fait Simple. C'est l'esprit de Laurence Plumey et de tout ce cours."}
